README.md
docs/README.md
docs/architecture.md
docs/components.md

Signed-off-by: Fabian Deutsch <fabiand@redhat.com>

docs: Update create/delete VM flow

---

.travis.yml
hack/config.sh

And also tag the builds accordingly.

travis: Do builds for tags as well

---

images/libvirtd/augconf
images/libvirtd/libvirtd-ds.yaml
images/libvirtd/libvirtd.sh

A few improvements to the libvirt image.

Libvirt image

---

cmd/virt-api/virt-api.go
cmd/virt-controller/virt-controller.go
cmd/virt-handler/virt-handler.go
cmd/virt-launcher/virt-launcher.go
pkg/kubecli/kubecli.go
pkg/logging/logging.go
pkg/logging/logging_test.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-controller/services/vm.go
pkg/virt-controller/watch/pod.go
pkg/virt-controller/watch/vm.go

Introduce a filtered logging wrapper. Messages will be filtered if
they are not a high enough priority. Verbosity is currently broken.

Logging module

---

pkg/kubecli/kubecli.go
pkg/logging/logging.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/vm.go
pkg/virt-controller/watch/pod.go
pkg/virt-controller/watch/vm.go

Logging works now a little bit different than before, so we have to
adjust the final message which needs to be printed.

Make use of the new logger module

---

pkg/kubecli/kubecli.go
pkg/virt-controller/watch/pod.go
pkg/virt-controller/watch/vm.go
pkg/virt-handler/vm.go

Create a Controller in kubecli which contains common controller logic.
Use it to implement the virt-handler VM controller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/48)

Extract common controller logic

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/52)

WIP: Update README

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/60)

readme: Include a link to the demo

---

cmd/virt-handler/virt-handler.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/63)

Fix libvirt-uri flag in virt-handler

---

FAQ.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/65)

Add FAQ.md

---

images/libvirtd/libvirtd-ds.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/66)

libvirtd: Update pull policy

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/68)

README.md: Fix typo: architetcure->architecture

---

docs/getting-started.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/71)

Document Vagrant sudo requirements

---

pkg/virt-handler/virtwrap/schema.go

Libvirt only works with XML, there is no need to support JSON.
Solves #69.

remove json tag from libvirt XML schema

---

cmd/virt-launcher/virt-launcher.go
pkg/virt-controller/watch/vm.go

Nothing too important, makes the reading nicer though.

fix typos in few comments

---

README.md

Signed-off-by: Fabian Deutsch <fabiand@redhat.com>

readme: Add pointers to where to reach us

---

README.md

Link to the channel via kiwiirc.

GitHub mardkdown does not allow irc url

---

pkg/api/v1/schema.go

shapshot -> snapshot in Disk struct

fix typo in schema.go

---

cluster/kubectl.sh
cmd/virt-api/virt-api.go
images/haproxy/haproxy.cfg
pkg/kubecli/kubecli.go
pkg/middleware/middleware.go
pkg/rest/endpoints/builder.go
pkg/rest/endpoints/decoders.go
pkg/rest/endpoints/encoders.go
pkg/rest/endpoints/patch_test.go
pkg/rest/endpoints/put_test.go
pkg/rest/filter/filter.go
pkg/rest/mime.go
pkg/virt-api/rest/kubeproxy.go
pkg/virt-api/rest/kubeproxy_test.go
pkg/virt-api/rest/matcher_test.go
pkg/virt-api/rest/rest_suite_test.go
pkg/virt-api/rest/spice.go
vendor/vendor.json

Improve REST and Swagger Part 2

---

LICENSE

Setting a sane owner for easy copy n' paste.
Fixes #104

LICENSE: Add date and owner

---

cluster/migration.yaml
cmd/virt-api/virt-api.go
manifests/migration-resource.yaml.in
pkg/api/types.go
pkg/api/v1/types.go
pkg/api/v1/types_swagger_generated.go

Tracking the changes to launch VM Migration Jobs

Migration API

---

pkg/virt-handler/virtwrap/cache/cache.go
pkg/virt-handler/virtwrap/cache/cache_suite_test.go
pkg/virt-handler/virtwrap/cache/cache_test.go
pkg/virt-handler/virtwrap/manager_test.go

@mpolednik FYI. Will rebase my tests after your PR is merged.

Add unit tests to libvirt cache package

---

tests/vmlifecycle_test.go

Make sure that the test repeatedly checks for the start and stop events
and waits for the start event before deleting the VM.

Make libvirt event checking test less flaky

---

tests/utils.go

Move VM status check for tests into an eventually loop

---

tests/vm_migration_test.go

The test suite currently fails but I believe it should work once all feature branches are merged.

Migration tests

---

cmd/virt-launcher/qemu-kube
tests/vm_migration_test.go

* Fix resolv.conf cleanup
* 	Remove flakiness from main migration test

Some fixes

---

pkg/kubecli/kubecli.go
pkg/virt-controller/watch/job.go
pkg/virt-controller/watch/job_test.go
pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/pod.go
pkg/virt-controller/watch/vm.go
pkg/virt-handler/domain.go
pkg/virt-handler/vm.go

Only last patch should be in this PR.  Others are in earlier PRs.

Remove useless job test

---

pkg/api/v1/types.go
pkg/kubecli/kubecli.go
pkg/virt-controller/watch/job.go
pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/pod.go
pkg/virt-controller/watch/vm.go
pkg/virt-handler/domain.go
pkg/virt-handler/vm.go

Want to change to an interface before changing all of the unit tests to drop the controller,

Controller dispatch interface

---

cluster/vm.json
cluster/vm.yaml
pkg/api/v1/schema.go
pkg/virt-handler/virtwrap/schema.go
tests/utils.go

Allow omitting optional VideoMemory fields

---

.gitignore
cluster/kubectl.sh
cmd/virtctl/virtctl.go
hack/config.sh
pkg/virt-api/rest/console.go
pkg/virtctl/console/console.go
pkg/virtctl/virtctl.go
vendor/vendor.json

When the VM is running, run 
```
cluster/kubectl.sh console testvm
```

Websocket virtctl

---

cluster/deploy.sh
cluster/vagrant/setup_kubernetes_common.sh
cluster/vagrant/setup_kubernetes_master.sh
cluster/vagrant/setup_kubernetes_node.sh
cluster/vagrant/sync_config.sh
cluster/verify-qemu-kube
cmd/virt-launcher/qemu-kube
images/vm-killer/Dockerfile
images/vm-killer/vm-killer.sh
pkg/api/v1/types.go
pkg/api/v1/types_test.go
pkg/virt-controller/services/vm.go
pkg/virt-controller/services/vm_test.go
pkg/virt-handler/domain.go
pkg/virt-handler/virtwrap/api/schema.go
pkg/virt-handler/virtwrap/cache/cache.go
tests/utils.go
tests/vmlifecycle_test.go

* Upgrade to 1.6.1
* Make sure hostPID is working on Pods
* Adapt to new kubelet 1.6.1 cgroup layout
* Make sure VM killer pod is always scheduled on the node of the VM to kill

Kubernetes 1.6.1

---

pkg/virt-handler/rest/console.go
pkg/virt-handler/rest/console_test.go
pkg/virt-handler/virtwrap/generated_mock_manager.go
pkg/virt-handler/virtwrap/manager.go
pkg/virt-handler/virtwrap/manager_test.go

fixes #199 
Needs to be merged after #198

Free domains

---

tests/console_test.go

Read the stream line by line, to allow checking for specific log lines.

Fix flaky functional test which check for CirrOS boot message

---

Vagrantfile

Revert vagrant provider to previous value.

Use libvirt provider in Vagrantfile

---

.gitignore
cmd/virt-manifest/Dockerfile
cmd/virt-manifest/virt-manifest.go
hack/config.sh
images/libvirt-kubevirt/Dockerfile
images/libvirt-kubevirt/libvirtd-limited.sh
images/libvirt-kubevirt/libvirtd.sh
manifests/virt-manifest.yaml.in
pkg/virt-handler/virtwrap/manager.go
pkg/virt-manifest/defaults.go
pkg/virt-manifest/defaults_test.go
pkg/virt-manifest/mapper.go
pkg/virt-manifest/mapper_test.go
pkg/virt-manifest/rest/manifest.go
tests/virtmanifest_test.go

Initial groundwork for a virt-manifest service.

Virt manifest service

---

docs/architecture.md

Especially highlight how TPRs, controllers, and daemons cooperate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/46)

WIP docs: Explain the architecture a little more

---

docs/live-migration.md

Wanted to get this officially on as a pulle request.  Going to pull out the API docs parts.

Migration doc

---

tests/utils.go
tests/vmlifecycle_test.go

By specifying on the ObjectEventWatcher in the functional tests a start
resourceVersion, we can first create an object and then establish a long
polling collection. This way we get all events which might have occoured
between the object modification and the watch start.

Make sure that all events associated to an object are observed in tests

---

hack/config.sh
images/spice-proxy/Dockerfile
manifests/squid.yaml.in

- add spice-proxy Dockerfile
- run spice-proxy as non-root user, part of the fix for #113

Move spice-proxy image Dockerfile to Kubevirt

---

images/iscsi-demo-target-tgtd/run-tgt.sh
tests/storage_test.go

images: Increase tgtd bootup time

---

docs/config-and-instances.md

docs: Adjust title of config-and-instance.md

---

pkg/virt-handler/rest/console_test.go

In the virt-handler unit tests, the httptest server sometimes reports
already that the server is done, before the handler method call is done.
This leads to flaky checks on the expected mocked out calls. Therefore,
make sure that the http handler is done, by explicitly waiting for a
channel, which signals that.
This fixes temporary test errors like
missing call(s) to *virtwrap.MockVirDomain.Free()
Fixes #308.

tests: Wait until console handler is done before checking mocks

---

docs/glossary.md

This is my attempt at consolidating the discussion spawned from issue #305 into an update to the KubeVirt glossary.

Updates to glossary based on community feedback.

---

cmd/virt-controller/virt-controller.go
pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-controller/watch/vm.go
pkg/virt-controller/watch/vm_test.go

works toward common initialization code between unit tests and live

Common init for virt-controller

---

.travis.yml

Push docker images from Golang 1.8.3 travis builds

---

docs/libvirt-pod-networking.md

docs: libvirt pod networking update

---

.travis.yml
pkg/virt-handler/virtwrap/api/api_suite_test.go
pkg/virt-handler/virtwrap/api/schema_test.go

Let goveralls ignore generated gomock code

---

cmd/virt-api/virt-api.go
cmd/virt-handler/virt-handler.go
pkg/healthz/healthz.go
pkg/informers/virtinformers.go
pkg/kubecli/generated_mock_kubevirt.go
pkg/kubecli/kubecli.go
pkg/kubecli/kubevirt.go
pkg/virt-api/rest/kubeproxy.go
pkg/virt-api/rest/kubeproxy_test.go
pkg/virt-api/rest/spice.go
pkg/virt-controller/services/vm.go
pkg/virt-controller/services/vm_test.go
pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-controller/watch/vm.go
pkg/virt-controller/watch/vm_test.go
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go
pkg/virtctl/spice/spice.go
tests/console_test.go
tests/registry_disk_test.go
tests/spice_test.go
tests/storage_test.go
tests/utils.go
tests/virtmanifest_test.go
tests/vm_migration_test.go
tests/vmlifecycle_test.go

Use single entry point for all API requests

---

cmd/virtctl/virtctl.go

virtctl: Add spice comment

---

docs/dev-env-local.md
docs/getting-started.md

Some doc format fixes

---

docs/release.md

A small doc describing the formal release process.

docs: Add release process documentation

---

.travis.yml
Makefile
docs/release.md
hack/release-announce.sh

A few improvements to ease a release:
- Some automation
- Some process improvements

Release script

---

pkg/cloud-init/cloud-init.go
pkg/cloud-init/cloud-init_test.go

This change adds a conservative upper limit timeout to the iso creation command. 
Iso creation is already non-blocking. This command is executed async in a separate go routine from the VM launch flow. It's still theoretically possible that the command could execute indefinitely without some sort of timeout mechanism in place, which we'd rather not happen.

Add timeout to cloud-init iso creation command

---

glide.lock
glide.yaml
pkg/api/v1/types.go
pkg/kubecli/controller.go
pkg/kubecli/generated_mock_kubevirt.go
pkg/virt-api/rest/kubeproxy.go
pkg/virt-handler/virtwrap/api/schema.go
pkg/virt-handler/vm_test.go

Align our code with go-client master branch

---

cluster/vagrant/setup_kubernetes_common.sh

Add --fail-swap-on=false flag to kubelet command

---

cluster/vagrant/setup_kubernetes_master.sh

Fixes #483 
Temporary W/A until https://github.com/kubernetes/kubernetes/issues/53356 will be fixed.

Remove /var/lib/kubelet before kubeadm init

---

cmd/virt-api/virt-api.go
pkg/virt-api/rest/kubeproxy.go

Added documentation and align with Kubernetes naming for KubeVirt API calls.

Added doc strings for swagger documentation

---

docs/getting-started.md

docs: Small getting started guide fixes

---

docs/debugging.md

Update debugging guide on how to collect events for all namespaces

---

cmd/virt-launcher/virt-launcher.go

Delete socket if it already exists in virt-launcher

---

pkg/virt-controller/watch/vm.go

This fixes some issues with transient failures in our functional test suite. If we start/stop/start a VM, the second start should not occur until the pod from the first start has exited.
Basically, don't enter into a situation where two running VM virt-launcher pods can be active at the same time. The virt-controller can recover from two active pods, but it involves rate limiting a key which causes inconsistent timing for our functional tests. We should avoid this condition when possible.

Don't create VM pod while previous one is still running

---

pkg/virt-controller/watch/vm.go

Signed-off-by: David Vossel <davidvossel@gmail.com>

Fixes error caused by merge conflict

---

automation/test.sh

So far we only deleted deployments.

Also delete daemon sets from old deployments on CI

---

pkg/inotify-informer/inotify.go

I was prototyping some code earlier and saw quite a few inotify informer error messages getting output. This patch fixes the issue.

Only send inotify informer updated on supported events

---

docs/vm-configuration.md

Add general rules on how to decide how to map different device types to
our top-level API. For some devices there exist already some decisions,
add them too.
Fixes #462.

Document mapping rules and decisions on how to construct our API

---

tests/utils.go

We weren't waiting on the spice port to get populated in the status field in our functional tests.
After some recent changes (which are doing the right thing) it's technically possible for the Phase to get updated to Running slightly before the graphic's status get's populated.

fixes inconsistent spice functional test results

---

.travis.yml
Makefile
api/openapi-spec/README.md
api/openapi-spec/swagger.json
cmd/virt-api/virt-api.go

* added option to generate openapi specification
* added test to travis to check changes in API definition

Added OpenAPI specification json file

---

pkg/virt-controller/watch/migration.go
tests/spice_test.go

Update spice host address after migration

---

pkg/log/log.go
pkg/log/log_test.go
pkg/virt-handler/virtwrap/api/schema.go
pkg/virt-handler/virtwrap/cache/cache.go
pkg/virt-handler/virtwrap/cache/cache_test.go

Another attempt to fix THE flaky CI test.

Simplify and improve Libvirt event notification

---

Makefile

Only update hashes if dep succeeds

---

.mailmap

mailmap: Add dvossel mapping

---

automation/test.sh

Improve removing traces from old deployments

---

automation/test.sh

Do not remove k8s service on clean phase

---

.gitignore
docs/dev-env-local.md

Additionally, also updated .gitignore with the generated files
Signed-off-by: Saravanan KR <skramaja@redhat.com>

Corrected the local env setup command

---

api/openapi-spec/swagger.json
pkg/virt-api/rest/kubeproxy.go

openapi: Align names for list operations

---

automation/test.sh
cluster/deploy.sh
cluster/vagrant/setup_kubernetes_common.sh
manifests/haproxy.yaml.in
manifests/iscsi-auth-demo-target.yaml.in
manifests/iscsi-demo-target.yaml.in
manifests/libvirt.yaml.in
manifests/rbac.authorization.k8s.io.yaml.in
manifests/squid.yaml.in
manifests/virt-api.yaml.in
manifests/virt-controller.yaml.in
manifests/virt-handler.yaml.in
manifests/virt-manifest.yaml.in
pkg/controller/expectations_test.go
pkg/virt-controller/leaderelectionconfig/config.go
tests/storage_test.go
tests/utils.go

Move our manifests to kube-system namespace

---

api/openapi-spec/swagger.json
pkg/api/v1/schema.go
pkg/api/v1/types.go

schema: update json tags to allow optional fields be empty

---

cluster/vagrant/setup_kubernetes_master.sh

Install updated weave CNI plugin for our vagrant environment

---

api/openapi-spec/swagger.json
pkg/rest/mime.go
pkg/virt-api/rest/kubeproxy.go

openapi: adding watch parameter on get & list operations

---

cluster/vagrant/setup_kubernetes_node.sh

Fix kubeadm deployment on vagrant for new kubeadm version

---

docs/vm-configuration.md

Update VM mapping decision principles on how to extend the API.

Update vm mapping documentation

---

pkg/virt-controller/watch/replicaset.go

Set correct API version for OwnerReference

---

docs/getting-started.md

Signed-off-by: Alexander Wels <alexanderwels4@gmail.com>

- Updated getting started document

---

.travis.yml

api-reference: removing tag condition for doc deployment

---

hack/dockerized

Signed-off-by: Martin Kletzander <mkletzan@redhat.com>

Wait for rsyncd to be ready

---

docs/getting-started.md

Signed-off-by: Martin Kletzander <mkletzan@redhat.com>

Just a tiny missing fix for `vagrant up` -> `make cluster-up`

---

pkg/log/log.go
pkg/log/log_test.go

Skip correct number of frames

---

docs/getting-started.md

Signed-off-by: Suraj Narwade <surajnarwade353@gmail.com>

Fixed typo in getting started guide

---

docs/devel/offline-virtual-machine.md

This PR introduces the devel documentation how to handle and implement the OfflineVirtualMachine.
It stil work in progress and should be treated as such.
Moreover, I have ommited for now parts that does not fit to MVP.
The text partly originated in [Romans document](https://docs.google.com/document/d/1A0qjTRwilbgUqXFh07waeIczPBfeVrTzZoEev67-Q2A/edit#heading=h.2levx6g5otrd), the rest is mine.
Please take a look and comment. @fabiand @rmohr @stu-gott @davidvossel @mpolednik
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/641)

Offlinevm devel doc

---

tests/vmlifecycle_test.go

We have crash related functional tests for virt-launcher and virt-controller already. We needed something similar for virt-handler.
This test just verifies that virt-handler can continue to process domain events for active VMs after virt-handler recovers from a crash.

Virt-handler crash recovery functional test

---

api/openapi-spec/swagger.json
pkg/rest/mime.go
pkg/virt-api/rest/kubeproxy.go

* adding missing parameters for delete and list operation
* fixes Produces/Consumes definitions
* Align HTTP return codes with K8S

openapi: Align KubeVirt API with K8S

---

hack/common.sh
hack/gen-swagger-doc/gen-swagger-docs.sh

api-reference: fix hack/common.sh to determine root of repository

---

docs/devel/offline-virtual-machine.md

Related to: kubevirt-incubator/api-reference#7

offline-vm-doc: fixed links to api-reference

---

docs/components.md

This updates the components.md file to reflect recent changes involving virt-launcher, libvirt, and CRDs. 
The architecture pictures need to be updated as well. I've been unsuccessful in editing the .svg files though. No program I have opens them successfully without the text looking weird. It's possible I don't have access to a font that's required.

Update components.md to reflect decentralized libvirtd

---

cluster/vagrant-openshift/provider.sh

Don't build optional docker containers for OC environment

---

Makefile
cluster/clean.sh

Eventhough cluster-deploy takes care of cleaning, it is useful to provide
an entry to clean the environment from makefile.

Added cluster-clean command to clean all the resources

---

cluster/vagrant-kubernetes/setup_master.sh
hack/config-default.sh

I opened an issue for weave problem https://github.com/weaveworks/weave/issues/3239, we can use `flannel` until it will be fixed.

Change default network provider

---

api/openapi-spec/swagger.json
pkg/api/v1/schema.go
pkg/api/v1/schema_swagger_generated.go

Signed-off-by: Martin Polednik <mpolednik@redhat.com>

typo: weather -> whether

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go

controller: Use a nicer launcher pod name separator

---

cluster/vagrant-openshift/setup_master.sh

Use specific openshift-ansible tag for deployment

---

tests/console_test.go
tests/controller_leader_election_test.go
tests/registry_disk_test.go
tests/replicaset_test.go
tests/storage_test.go
tests/vm_configuration_test.go
tests/vm_monitoring_test.go
tests/vm_userdata_test.go
tests/vmlifecycle_test.go
tests/vnc_test.go

Refactor our tests descriptions to be more narrative

---

automation/test.sh
cluster/clean.sh

Follow up for #708 to merge kubevirt cluster clean up into one place.

Merged cluster clean

---

docs/direct-pv-disks.md
docs/filesystem-pv-disks.md

This proposal describes a mechanism to leverage stock file-system based Kubernetes volumes as backing stores for virtual machien disks.
Resolves #266

Filesystem pv disks

---

tests/vm_networking_test.go

Signed-off-by: David Vossel <davidvossel@gmail.com>

Only skip network test with dns resolution if in jenkins

---

tests/utils.go
tests/vm_userdata_test.go

Add test for ssh-key injection via user-data

---

api/openapi-spec/swagger.json
cluster/vm-nocloud.yaml
pkg/api/v1/schema.go
pkg/api/v1/schema_swagger_generated.go
pkg/cloud-init/cloud-init.go
pkg/cloud-init/cloud-init_test.go
tests/vm_userdata_test.go

Make possible to add cloud-init data to VM without
encode it to base64 format.

Inline cloud-init user data

---

manifests/release/kubevirt.yaml.in

Use docker_prefix in controller release manifests

---

cluster/vm-template-rhel7.yaml
cluster/vm-template-windows2012r2.yaml

Added VM templates for RHEL 7.4 and Windows Server 2012 R2
Signed-off-by: Yanir Quinn yquinn@redhat.com

Add VM templates for windows and linux

---

pkg/cloud-init/cloud-init.go
tests/utils.go
tests/vm_configuration_test.go
tests/vm_networking_test.go
tests/vm_userdata_test.go

Signed-off-by: karmab <karimboumedhel@gmail.com>

Generate properly cloudinit metadata file

---

cluster/vm-template-rhel7.yaml
cluster/vm-template-windows2012r2.yaml

Labels for OfflineVirtualMachines fixed accroding to docummentation [1]
and sample OVM [2].
[1] https://raw.githubusercontent.com/kubevirt/kubevirt/master/docs/devel/offline-virtual-machine.md
[2] https://raw.githubusercontent.com/kubevirt/kubevirt/master/cluster/my-ovm.yaml

Fix Linux and Windows templates for labels

---

.gitignore
tests/polarion_reporter.go
tests/tests_suite_test.go

Produces XML file that can be imported to polarion

Ginkgo polarion reporter

---

pkg/api/v1/types.go
pkg/api/v1/types_swagger_generated.go
pkg/virt-controller/watch/ovm.go
pkg/virt-controller/watch/ovm_test.go

Fix ovm validation and ovm json mapping

---

cluster/ephemeral-provider-common.sh

update cli to properly clean up broken clusters

---

cluster/vm-template-fedora.yaml

cluster: Add a fedora template

---

automation/test.sh
cluster/deploy.sh
cluster/ephemeral-provider-common.sh
cluster/os-3.9.0-alpha.4/provider.sh

Start running functional tests on openshift.

Enable openshift tests

---

automation/test.sh
cluster/deploy.sh
cluster/ephemeral-provider-common.sh
cluster/k8s-1.9.3/provider.sh
cluster/os-3.9.0-alpha.4/provider.sh

- create NFS server
- create windows PV disk

Prepare CI environment for Windows testing

---

api/openapi-spec/swagger.json
pkg/virt-api/api.go

Fixes: #853
Signed-off-by: Lukas Bednar <lbednar@redhat.com>

openapi: add offlinevirtualmachines resource to api server

---

pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
pkg/virt-launcher/virtwrap/network/dhcp/dhcp_test.go

Should address #848 
Signed-off-by: Vladik Romanovsky <vromanso@redhat.com>

dhcp: Stop adding default gateway to gateway-less routes

---

docs/vm-presets.md
pkg/api/v1/types.go
pkg/virt-controller/watch/preset.go
pkg/virt-controller/watch/preset_test.go
tests/vmpreset_test.go

Fixes https://github.com/kubevirt/kubevirt/issues/805

Do not allow VirtualMachinePresets to conflict

---

tests/vm_networking_test.go

Signed-off-by: Vladik Romanovsky <vromanso@redhat.com>

A functional test to verify VM to VM connectivity

---

cluster/k8s-1.9.3/provider.sh
cluster/os-3.9.0-alpha.4/provider.sh

- os-3.9.0-alpha.4
- k8s-1.9.3

Update images tags

---

docs/devel/offline-virtual-machine.md

This PR fixes a offline virtual machine documentation. The merge was incorrect.
@cynepco3hahue @stu-gott @fabiand PRM
Signed-off-by: Petr Kotas <petr.kotas@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/880)

Fix patch documentation

---

cluster/vm-template-rhel7.yaml
cluster/vm-template-windows2012r2.yaml

Signed-off-by: karmab <karimboumedhel@gmail.com>

Make sure rhel7 and windows show up in virtualization category

---

cmd/registry-disk-v1alpha/entry-point.sh
cmd/virt-launcher/entrypoint.sh
pkg/virt-launcher/monitor.go
pkg/virt-launcher/monitor_test.go
tests/vmlifecycle_test.go

This functional test is in response to #876
This test targets verifying pod termination after a VM is deleted.

Add functional test to verify pod termination

---

cluster/ephemeral-provider-common.sh
hack/functests.sh
tests/utils.go
tests/windows_test.go

- create windows VM via kubectl
- delete windows VM via kubectl

Windows kubectl tests

---

tests/windows_test.go

Windows tests spell fixes

---

glide.lock
glide.yaml
tests/tests_suite_test.go
vendor/github.com/kubevirt/qe-tools/.gitignore
vendor/github.com/kubevirt/qe-tools/LICENSE
vendor/github.com/kubevirt/qe-tools/Makefile
vendor/github.com/kubevirt/qe-tools/ginkgo-reporters/junit_reporter.go
vendor/github.com/kubevirt/qe-tools/ginkgo-reporters/polarion_reporter.go
vendor/github.com/kubevirt/qe-tools/glide.lock
vendor/github.com/kubevirt/qe-tools/glide.yaml
vendor/github.com/kubevirt/qe-tools/hack/dep-prune.sh

Import ginkgo reporters from qe-tools repository

---

cluster/vm-template-fedora.yaml
cluster/vm-template-rhel7.yaml
cluster/vm-template-windows2012r2.yaml

Signed-off-by: karmab <karimboumedhel@gmail.com>

Add proper icons to templates

---

tests/storage_test.go
tests/utils.go

This PR add system tests for a VM with two PVCs. 
The code introduces as little changes as possible.
@rmohr @fabiand PRM
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/843)

Add system test for multiple pvc

---

cluster/vm-template-fedora.yaml

Fix #943
Signed-off-by: Guohua Ouyang <gouyang@redhat.com>

Correct description of fedora template

---

README.md

- Added kubevirt-ansible related resource

---

automation/test.sh
cluster/deploy.sh
cluster/os-3.9.0-crio/README.md
cluster/os-3.9.0-crio/provider.sh
cluster/os-3.9.0/provider.sh

Relevant image PR - https://github.com/kubevirt/kubevirtci/pull/2

Add support for CRIO environment under our CI

---

cmd/virt-launcher/virt-launcher.go

This patch gives us a strong guarantee that the cmd server is definitely processing requests before the VM start flow beings.  It's unlikely that this fixes any of the errors we are seeing in #937 , but it does however limit the possible causes. 
related to #937

Ensure cmdserver is responsive before marking virt-launcher ready

---

docs/getting-started.md

Document how to execute specific functional tests

---

cmd/virt-launcher/virt-launcher.go
pkg/cloud-init/cloud-init.go
pkg/log/log_test.go
pkg/middleware/middleware.go
pkg/testutils/matchers.go
pkg/virt-controller/watch/replicaset.go
pkg/virt-launcher/monitor.go
tests/utils.go

Fixed some spelling issues in error messages and comments.

Fix spelling

---

pkg/virt-controller/watch/node.go

- Fixed some golint warnings.
- Fixed ineffectual assign of a variable.

Fix static analysis issues node.go

---

api/openapi-spec/swagger.json
manifests/generated/ovm-resource.yaml

- Ran make generate to fix travis

Fix travis

---

pkg/virt-launcher/virtwrap/api/converter.go
pkg/virt-launcher/virtwrap/api/converter_test.go
tests/storage_test.go
tests/utils.go

Fixes https://github.com/kubevirt/kubevirt/issues/1036

Fix readonly

---

pkg/api/v1/types_test.go
pkg/virt-api/api.go
pkg/virt-controller/watch/preset_test.go
pkg/virt-launcher/virtwrap/network/dhcp/dhcp_test.go

- Fixed some gofmt simplify issues.

gofmt fixes:

---

cluster/k8s-1.9.3/provider.sh
cluster/os-3.9.0-crio/provider.sh
cluster/os-3.9.0/provider.sh

Relevant kubevirtci PR - https://github.com/kubevirt/kubevirtci/pull/13

Use latest versions of docker and CentOs

---

api/openapi-spec/swagger.json
cmd/subresource-access-test/subresource-access-test.go
hack/build-go.sh
hack/version.sh
manifests/dev/rbac.authorization.k8s.yaml.in
manifests/release/kubevirt.yaml.in
pkg/kubecli/generated_mock_kubevirt.go
pkg/kubecli/kubevirt.go
pkg/kubecli/version.go
pkg/kubecli/version_test.go
pkg/version/base.go
pkg/version/types.go
pkg/version/version.go
pkg/virt-api/api.go
pkg/virt-api/rest/authorizer.go
pkg/virtctl/root.go
pkg/virtctl/version/version.go
tests/subresource_api_test.go
tests/version_test.go

PR for the follow issues
[Create version resource for virt-api](https://github.com/kubevirt/kubevirt/issues/1018)
[Add virtcl version command](https://github.com/kubevirt/kubevirt/issues/891)

Add version command to virtctl

---

tests/vm_networking_test.go

go routines under the test make debugging more complicated
and it does not save a lot of time, so let just get rid of them

Get rid of go routines under network test

---

tests/vmlifecycle_test.go

Probably fixes `virt-handler` failure under https://github.com/kubevirt/kubevirt/issues/1014#issuecomment-389199091

Wait for virt-handler pods after the destructive test

---

api/openapi-spec/swagger.json
manifests/generated/ovm-resource.yaml
manifests/generated/vm-resource.yaml
manifests/generated/vmpreset-resource.yaml
manifests/generated/vmrs-resource.yaml
pkg/api/v1/deepcopy_generated.go
pkg/api/v1/openapi_generated.go
pkg/api/v1/schema.go
pkg/api/v1/schema_swagger_generated.go
pkg/virt-api/validating-webhook/validating-webhook.go
pkg/virt-api/validating-webhook/validating-webhook_test.go
pkg/virt-launcher/virtwrap/api/converter.go
pkg/virt-launcher/virtwrap/api/converter_test.go
pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
pkg/virt-launcher/virtwrap/api/schema.go
tests/utils.go
tests/vmlifecycle_test.go

Per discussion on mailing list, add ability to provide boot order to disks
https://groups.google.com/d/topic/kubevirt-dev/tBhwK8Y4UE0/discussion

Add disk boot order to API

---

.mailmap

Signed-off-by: Marc Sluiter msluiter@redhat.com

Added myself to mailmap

---

pkg/virt-controller/watch/preset.go
pkg/virt-controller/watch/preset_test.go
tests/vmdefaults_test.go

Fixes #1068
Signed-off-by: Marc Sluiter <msluiter@redhat.com>

Apply default values

---

tests/vmlifecycle_test.go

Need to check that all DS values equal to desired one

Really fix virt-handler test

---

README.md
cluster/examples/ovm-cirros.yaml
cluster/examples/vm-ephemeral.yaml
cluster/examples/vm-fedora.yaml
cluster/examples/vm-flavor-small.yaml
cluster/examples/vm-nocloud.yaml
cluster/examples/vm-replicaset-cirros.yaml
cluster/examples/vm-sata.yaml
cluster/vm-template-fedora.yaml
docs/getting-started.md
tools/vms-generator/vms-generator.go

* Make that mentioned vm examples work again
* Mention nested virtualization as a requirement

Fix some bumps in the getting started guide

---

cmd/virt-launcher/virt-launcher.go
pkg/log/log.go
pkg/log/log_test.go
pkg/service/service.go

Fixes #1098
Signed-off-by: Marc Sluiter <msluiter@redhat.com>

Better default log verbosity initialization

---

docs/devel/hostpath-provisioner.yaml
docs/devel/storage.md

- Updated storage.md to include steps to setup hostPath storage using
the hostpath-provisioner.
- Added hostpath-provisioner.yaml to make it easy to setup the hostpath
provisioner.

Initial storage development document.

---

docs/devel/storage.md

- Added missing backticks to close code highlighting block

Fix missing highlighting back ticks

---

cluster/vm-template-fedora.yaml

Fixes #1134 
Signed-off-by: karmab <karimboumedhel@gmail.com>

add fedora template to virtualization tab

---

docs/logging.md
pkg/log/log.go
pkg/log/log_test.go
pkg/virt-controller/watch/ovm.go
pkg/virt-launcher/monitor.go
pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go

Signed-off-by: Marc Sluiter <marc@slintes.net>

Added doc about our logging, removed debug log level

---

api/openapi-spec/swagger.json
manifests/generated/ovm-resource.yaml
manifests/generated/vm-resource.yaml
manifests/generated/vmrs-resource.yaml
pkg/api/v1/deepcopy_generated.go
pkg/api/v1/openapi_generated.go
pkg/api/v1/types.go
pkg/api/v1/types_swagger_generated.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go

Fixes #1101, fixes #1127
Signed-off-by: Marc Sluiter <marc@slintes.net>

Implemented PodAffinity and PodAntiAffinity

---

docs/devel/storage.md

Found a small error with the PVC path and ended up fixing a few nits.

fix PVC path in storage doc

---

cluster/k8s-1.10.4/README.md
cluster/k8s-1.10.4/provider.sh

I had to test an issue in k8s v1.10.4. We might as well add this as a provider since I already did the work.

Add k8s v1.10.4 provider

---

cluster/examples/vmi-preset-small.yaml
cluster/examples/vmi-replicaset-cirros.yaml
tools/vms-generator/vms-generator.go

Travis reported that it failed, so the relevant PR should not have been
merged.

Fix example generation

---

pkg/virt-api/validating-webhook/validating-webhook.go
pkg/virt-api/validating-webhook/validating-webhook_test.go
tools/vms-generator/vms-generator.go

This is to fix https://github.com/kubevirt/kubevirt/issues/1041 The series also includes changes that make error handling in the tool better (in other words, errors are actually handled). Also fixed an issue with error message formatting while at it.

Validate specs in vms generator

---

pkg/virt-controller/watch/preset_test.go

Fixes https://github.com/kubevirt/kubevirt/issues/773

Use Gomock instead of ghttp in VMI Preset unit tests

---

api/openapi-spec/swagger.json
manifests/generated/vmipreset-resource.yaml
pkg/api/v1/deepcopy_generated.go
pkg/api/v1/openapi_generated.go
pkg/api/v1/schema.go
pkg/api/v1/schema_swagger_generated.go

related to https://github.com/kubevirt/kubevirt/pull/1115 ... left out one important field from that PR.

add Memory field to DomainPresetSpec struct

---

pkg/kubecli/vmi.go
tests/console_test.go
tests/expose_test.go
tests/storage_test.go
tests/utils.go
tests/vm_test.go
tests/vmi_configuration_test.go
tests/vmi_lifecycle_test.go
tests/vmi_monitoring_test.go
tests/vmi_networking_test.go
tests/vmi_userdata_test.go

Check on error before close the expecter

---

manifests/dev/virt-api.yaml.in
manifests/dev/virt-controller.yaml.in
manifests/dev/virt-handler.yaml.in
manifests/release/kubevirt.yaml.in

Fixes: https://github.com/kubevirt/kubevirt/issues/1149
Signed-off-by: Shiyang Wang <shiywang@redhat.com>

add critical-pod annotation for pods

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Prepare issue and pull request templates for prow.
```release-note
NONE
```

Prepare Issues and PRs for Prow

---

cluster/examples/vm-template-fedora.yaml
cluster/examples/vm-template-rhel7.yaml
cluster/examples/vm-template-windows2012r2.yaml
tools/vms-generator/vms-generator.go

Fixes #1202
```release-note
NONE
```
Signed-off-by: Marc Sluiter <msluiter@redhat.com>

Fixed CPU / Cores in example vm templates

---

.gitignore
Makefile
cluster/ephemeral-provider-common.sh
hack/verify-build.sh

* Add .coverprofile to ignored files, so that travis builds do not mark binaries as "dirty"
* Add a basic check which ensures that the binaries are "clean" before pushing to the registry
```release-note
NONE
```

Verify build is clean

---

docs/README.md
docs/env-providers.md

Documentation makes reference to scripts and constructs that no longer exist.
```release-note
NONE
```

Update outdated documentation

---

.travis.yml
cmd/virt-api/Dockerfile
cmd/virt-controller/Dockerfile
cmd/virt-handler/Dockerfile
cmd/virt-launcher/Dockerfile
cmd/virt-launcher/entrypoint.sh
cmd/virt-launcher/sh.sh
hack/build-manifests.sh
hack/common.sh
hack/docker-builder/Dockerfile
manifests/dev/virt-api.yaml.in
manifests/dev/virt-controller.yaml.in
manifests/dev/virt-handler.yaml.in
manifests/release/kubevirt.yaml.in
pkg/virt-api/rest/subresource.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-launcher/virtwrap/util/libvirt_helper.go

Fixes #1252 
```release-note
Provide jinja2 templates for manifests
```

release-0.6: Release manifest templates

---

tests/utils.go

On the environment with at least one non-compute node, our tests will always fail, because the non-compute node will lack virt-handler pod and in the result, it will not have KVM and TUN devices.
Fixes #
```release-note
NONE
```

Check on KVM device only nodes with virt-handler pod

---

hack/build-go.sh
pkg/virt-handler/device-manager/device_controller_test.go
pkg/virt-launcher/monitor_test.go

basic race detection in our unit tests. 
```release-note
NONE
```

Turn on -race for test suite

---

docs/getting-started.md

With this change, the "code generation" section is slightly renamed. I add an explanation about what *is* "generated code" and remove "noisy" note about when not needing to care about it.
Fixes nothing
@cynepco3hahue I hope that the suggested text is more approachable for newcomers.
```release-note
NONE
```

getting-started: cleanup "code generation" section

---

tests/vmi_networking_test.go
tests/vmi_slirp_interface_test.go

Fixes #
```release-note
NONE
```

Remove debug message from slirp and network tests

---

docs/getting-started.md

Add a missing verb. Also, add `make` to show how a "successful build" is done.
Fixes nothing
@stu-gott a review by an English speaker is most welcome.
```release-note
NONE
```

getting started: testing: fix English glitches

---

pkg/kubecli/version.go
pkg/kubecli/version_test.go

This future-proofs querying the version of a running Kubevirt instance
by dynamically determining the preferred API.
Signed-off-by: Ben Warren <bawarren@cisco.com>
Determines the kubevirt API version on a cluster before querying the Kubevirt version info.  Without this fix, the **virtctl version** command fails when querying a cluster where the Kubevirt API version is older, for example **v1alpha1**
None
```release-note
NONE
```

Discover server version API version dynamically

---

cluster/os-3.10.0/provider.sh

Relevant PR under `kubevirtci` https://github.com/kubevirt/kubevirtci/pull/24
Fixes #
```release-note
NONE
```

Use latest os-3.10.0 image

---

hack/dockerized

Make possible to run dockerizied script under enforced SELinux.
Fixes #794
Fixes #
```release-note
NONE
```

Make possible to run dockerizied under enforcing SELinux

---

.mailmap
hack/release-announce.sh

hack: Update release script and mailMap

---

automation/check-patch.k8s-1.10.3-dev.mounts
automation/check-patch.k8s-1.10.3-dev.packages
automation/check-patch.k8s-1.10.3-dev.sh
automation/check-patch.k8s-1.10.3-release.mounts
automation/check-patch.k8s-1.10.3-release.packages
automation/check-patch.k8s-1.10.3-release.sh
automation/check-patch.openshift-3.10-release.mounts
automation/check-patch.openshift-3.10-release.packages
automation/check-patch.openshift-3.10-release.sh
automation/check-patch.packages.el7
automation/check-patch.sh
automation/check-patch.windows2016-release.mounts
automation/check-patch.windows2016-release.packages
automation/check-patch.windows2016-release.sh
automation/check-patch.yaml
hack/version.sh
stdci.yaml

Fixes #
```release-note
NONE
```

Fix stdci configuration for the project

---

automation/test.sh
cluster/ephemeral-provider-common.sh

- focus on windows tests when target equals to windows
- use more memory for VM's only when target equals to windows
Fixes #
```release-note
NONE
```

Small fixes for CI windows run

---

api/openapi-spec/swagger.json
manifests/generated/vm-resource.yaml
manifests/generated/vmi-resource.yaml
manifests/generated/vmirs-resource.yaml
pkg/api/v1/deepcopy_generated.go
pkg/api/v1/openapi_generated.go
pkg/api/v1/types.go
pkg/api/v1/types_swagger_generated.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-controller/watch/vmi.go
tests/vmi_lifecycle_test.go

Fixes https://github.com/kubevirt/kubevirt/issues/445
```release-note
Support Tolerations for VMs 
```

Add Toleration to VMI 

---

api/openapi-spec/swagger.json
pkg/api/v1/openapi_generated.go
pkg/api/v1/schema.go
pkg/api/v1/schema_swagger_generated.go
tests/utils.go

Respond to the comments from https://github.com/kubevirt/kubevirt/pull/1363
Fixes #
```release-note
NONE
```

CPU model syntax fixes

---

pkg/api/v1/types.go

**What this PR does / why we need it**: document annotations / labels specific to kubevirt.
Fixes #1080 
**Special notes for your reviewer**: I was not there when all of these labels / annotations were added and hence may miss some crucial details. Feel free to point out any mistakes you can find. Some annotations / labels seem duplicative on first sight. I would be glad to learn if they are indeed duplicates and hence can be consolidated, or there is special reason for each of them to exist.
```release-note
NONE
```

Document kubevirt specific annotations and labels

---

README.md
docs/components.md

**What this PR does / why we need it**: remove glossary info according to #1009
Fixes #
**Special notes for your reviewer**: remove glossary info according to #1009
```release-note
None
```

remove glossary info according to #1009

---

CONTRIBUTING.md
docs/debugging.md
docs/direct-pv-disks.md
docs/iscsi-authentication.md
docs/release.md

Fixes https://github.com/kubevirt/kubevirt/issues/1255
Signed-off-by: Shiyang Wang <shiywang@redhat.com>
@alexxa @adityaramteke @fabiand PTAL
```release-note
NONE
```

Update invalid URLs in this repo

---

pkg/virtctl/expose/expose.go

Signed-off-by: Shiyang Wang <shiywang@redhat.com>
```release-note
NONE
```

fix expose example unclear

---

glide.lock
glide.yaml
vendor/google.golang.org/appengine/go.mod
vendor/google.golang.org/appengine/go.sum
vendor/kubevirt.io/qe-tools/.gitattributes
vendor/kubevirt.io/qe-tools/glide.lock
vendor/kubevirt.io/qe-tools/glide.yaml
vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
vendor/kubevirt.io/qe-tools/pkg/polarion-generator/test_cases_generator.go

- has ginkgo 1.6 that will make possible to return
`xunit` reports
Fixes #
```release-note
NONE
```

Use latest qe-tools package

---

pkg/virt-controller/watch/vm.go

Fixes the #1057
Signed-off-by: Petr Kotas <petr.kotas@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/1074)

Fix the logging messages

---

automation/check-patch.openshift-3.10-crio-release.mounts
automation/check-patch.openshift-3.10-crio-release.packages
automation/check-patch.openshift-3.10-crio-release.sh
automation/test.sh
cluster/os-3.10.0-crio/README.md
cluster/os-3.10.0-crio/provider.sh
cluster/os-3.10.0/provider.sh
cluster/os-3.9.0-crio/provider.sh
stdci.yaml

Fixes #
```release-note
NONE
```

Add OpenShift CRI-O provider and CI job

---

tests/utils.go

Fixes #
```release-note
NONE
```

Omit expecter library output in our tests

---

tests/windows_test.go

Get pod selector before VMI deletion.
Fixes #
```release-note
NONE
```

Fix windows test

---

tests/vmi_lifecycle_test.go

Get pod selector before VMI deletion.
Fixes #
```release-note
NONE
```

Fix VMI lifecycle test

---

automation/check-patch.mounts
automation/test.sh
cluster/ephemeral-provider-common.sh

Fetch windows image from remote http server to CI nodes.
Fixes #
```release-note
NONE
```

Fetch windows image from remote http server

---

tests/vmi_lifecycle_test.go

Add  functional tests for node/pod affinity/anti-affinity 
Fixes #1144
```release-note
NONE
```

Create functest for node/pod (anti-)affinity

---

api/openapi-spec/swagger.json
manifests/generated/vm-resource.yaml
manifests/generated/vmi-resource.yaml
manifests/generated/vmipreset-resource.yaml
manifests/generated/vmirs-resource.yaml
pkg/api/v1/openapi_generated.go
pkg/api/v1/schema.go
pkg/api/v1/schema_swagger_generated.go
pkg/virt-api/validating-webhook/validating-webhook.go
pkg/virt-api/validating-webhook/validating-webhook_test.go
pkg/virt-launcher/virtwrap/network/podinterface.go
pkg/virt-launcher/virtwrap/network/podinterface_test.go
tests/utils.go
tests/vmi_networking_test.go

Backport of #1213. Depends on #1427 
Rebasing of tests was wild, please pay extra attention to that part.

static MAC on VM interfaces for 0.6

---

pkg/virtctl/version/version.go

Signed-off-by: Shiyang Wang <shiywang@redhat.com>
Fixes #
```release-note
add --client flag to virtctl version
```

add --client flag to virtctl version

---

cluster/os-3.10.0/provider.sh
tests/networkpolicy_test.go
tests/utils.go

Add some functional test for networkpolicy
Fixes #
```release-note
NONE
```

Add functional test for networkpolicy

---

cluster/examples/vm-template-fedora.yaml
cluster/examples/vm-template-rhel7.yaml
cluster/examples/vm-template-windows2012r2.yaml
tools/vms-generator/utils/utils.go

Signed-off-by: Guohua Ouyang <gouyang@redhat.com>
Fixes #1403
```release-note
Support displaying operating system of virtual machine on web console.
```

Add label "kubevirt.io/os" to VM spec

---

cluster/clean.sh
pkg/kubecli/vm.go
tests/datavolume_test.go
tests/vm_test.go

Signed-off-by: Guohua Ouyang <gouyang@redhat.com>
Fixes #
```release-note
NONE
```

cleanup offlinevirtualmachine in the repo

---

pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go

The validation webhook gets the old object as part of the requested
review. No need to get it from somewhere else.
Fixes #
```release-note
NONE
```

Don't use VMI informers to get an old object on VMI updates

---

cluster/local/README.md

**What this PR does / why we need it**: this PR details how to deal with firewall issues on the node; how to deploy CNI; how to deploy older kubernetes releases.
```release-note
NONE
```

Added more details to local provider README

---

cluster/local/README.md

modify an example script, to use the shorter  `systemctl disable --now`
NONE
```release-note
NONE
```

--now is cool

---

docs/cloud-init.md

Fix minor typo

---

pkg/api/OWNERS

Add a `kind/api-change` label to every PR which potentially changes the API.
Fixes #
```release-note
NONE
```

Add a label to all PRs which potentially changes the API

---

api/openapi-spec/swagger.json
manifests/generated/vm-resource.yaml
manifests/generated/vmi-resource.yaml
manifests/generated/vmipreset-resource.yaml
manifests/generated/vmirs-resource.yaml
pkg/api/v1/deepcopy_generated.go
pkg/api/v1/openapi_generated.go
pkg/api/v1/schema.go
pkg/api/v1/schema_swagger_generated.go
pkg/api/v1/schema_test.go
pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go
pkg/virt-launcher/virtwrap/api/converter.go
pkg/virt-launcher/virtwrap/api/converter_test.go
pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
pkg/virt-launcher/virtwrap/api/schema.go
pkg/virt-launcher/virtwrap/api/schema_test.go
tests/utils.go
tests/vmi_configuration_test.go

Initial implementation of virtio block multi-queue.
```release-note
Implement virtio block multi-queue.
```

Introduce virtio multi-queue

---

cmd/virt-launcher/virt-launcher.go

Right now we don't receive libvirt events for migrations unless a synchronous api call is made to libvirt. We knew this was happening but didn't know how to fix it. Our workaround was to execute listDomains in a background loop in order to guarantee libvirt fired events.
Now we know what is occuring. Libvirt requires us to register the event impl before establishing a connection and registering the event callback.
This bugzilla comment explains what was occurring in more detail.
https://bugzilla.redhat.com/show_bug.cgi?id=1638894#c6
```release-note
NONE
```

Fixes Libvirt Lifecycle event callback

---

tests/storage_test.go
tests/utils.go

Use a new PV and PVC for the test, it's not possible to run multiple tests with the same PV
```release-note
NONE
```

Improved block volume PVC test

---

api/openapi-spec/swagger.json
pkg/api/v1/openapi_generated.go
pkg/api/v1/schema.go
pkg/api/v1/schema_swagger_generated.go

Fixed schema doc.
Fixes #
```release-note
VM high performance - add cache options
```

schema doc - new line

---

cluster/k8s-genie-1.11.1/provider.sh

use new image from: https://github.com/kubevirt/kubevirtci/pull/48
```release-note
NONE
```

use new hash for genie image

---

tests/console_test.go

Ensure that a console connection is closed as soon as a new one is opened
See discussion on https://github.com/kubevirt/kubevirt/pull/1640
I cross checked that this test fails if we don't close console connections in virt-launcher's sock-connector
```release-note
NONE
```

Improved console test

---

pkg/cloud-init/cloud-init.go
pkg/log/log.go
pkg/registry-disk/registry-disk.go

The method `fmt.Errorf` is a more conventional way to generate formatted error message.
```release-note
NONE
```

Use fmt.Errorf instead of errors.New(fmt.Sprintf)

---

automation/test.sh

Instead of using a spinlock, which might leave the lock behind if the
process was killed with SIGKILL, we will use flock which releases the
lock as soon as the process dies.
It's needed now because we're planning to abort tests on a specific PR
when the PR is being updated, the abort is not guaranteed to be
graceful.

test.sh: use flock instead of a spinlock

---

pkg/virtctl/vnc/vnc.go

Completes/addresses comments on  (seemingly abandoned) pull #1216, adding 'virtctl vnc' capability for OSX with installed third party VNC viewers.
Fixes #812 #1084
@fabiand @rmohr @slintes
```release-note
Allows 'virtctl vnc' command to work on OSX, provided one of Tiger VNC, Chicken, or Real VNC are installed.
```

Add vnc script support for MAC OSX

---

automation/test.sh

- Fixed a race in safe_download()
- Added sha1sum verification to download files

Few fixes to safe_download()

---

automation/test.sh
tests/vmi_slirp_interface_test.go

Reduce the amount of tests to run for the networking related lanes.
Fixes #
```release-note
NONE
```

Run only networking related tests on multus and genie test lanes

---

docs/getting-started.md

Add virt-viewer download instructions for Windows. Took me some searching to figure this out, and thought it was worth documenting.
```release-note
NONE
```

Add virt-viewer download instructions for Windows

---

api/openapi-spec/swagger.json
pkg/virt-api/api.go

Improved a VM restart doc
Fixes #
```release-note
a new endpoint which is providing a VM restart functionality
```

better description of VM restart endpoint

---

README.md

point to the correct user documentation
Fixes #
```release-note
point to the correct user documentation
```

correct link to the user guide

---

pkg/virtctl/vnc/vnc.go

Signed-off-by: imjoey <majunjiev@gmail.com>
Current the supported version of TigerVNC client is restricted to `1.8.0` (hardcoded). This pull request changes the way to find the TigerVNC executable file and enables the compatibility with multiple versions. If there has multiple versions installed, the latest one will always be launched first.
This PR has been tested locally at several conditions:
1. With both TigerVNC v1.9.0 and v1.8.0 installed, v1.9.0 was launched
2. With only TigerVNC v1.9.0 installed, v1.9.0 was launched
3. With no TigerVNC installed, the …

virtctl: Compatible with multiple TigerVNC versions on OSX

---

pkg/virt-launcher/virtwrap/api/converter.go
tests/vmi_lifecycle_test.go

gracePeriod NPE fix
Fixes #1780 
```release-note
NONE
```

Termination grace period fix

---

cmd/container-disk-v1alpha/Dockerfile

Every container image is based on fedora, this is unification with the rest.
Fixes #
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/1719)

Change registry disk base to fedora

---

docs/architecture.md

to me, the security reasoning was the obvious one; but let us state it explicitly as our current sriov implementation breaks it
@booxter @fabiand @rmohr
```release-note
NONE
```

native workloads principle continued: security

---

cluster/os-3.10.0-multus/provider.sh
cluster/os-3.11.0-crio/provider.sh
cluster/os-3.11.0/provider.sh
manifests/testing/disks-images-provider.yaml.in

New images include fix from https://github.com/kubevirt/kubevirtci/pull/54
Fixes #
```release-note
NONE
```

Use updated os images

---

.travis.yml
manifests/release/kubevirt.yaml.in

Reverts kubevirt/kubevirt#1828
see https://github.com/kubevirt/kubevirt/pull/1828#issuecomment-446631231 ff

Revert "Make sure the kubevirt namespace exists"

---

images/fedora-cloud-container-disk-demo/Dockerfile

Update fedora image to fedora 29
```release-note
NONE
```

Update fedora cloud image to f29

---

cluster/clean.sh
cluster/deploy.sh
manifests/dev/kubevirt-ns.yaml.in
manifests/release/kubevirt.yaml.in

Add kubevirt namespace via manifests to avoid the need to create it manually.
Fixes #
```release-note
Create kubevirt namespace via manifests
```

Create kubevirt NS via manifests

---

cluster/deploy.sh
hack/build-docker.sh
hack/build-func-tests-container.sh
hack/build-manifests.sh
hack/common.sh
hack/functests.sh
manifests/testing/cdi-v1.3.0.yaml.in
manifests/testing/disks-images-provider.yaml.in
manifests/testing/local-block-storage.yaml.in
manifests/testing/rbac-for-testing.yaml.in
manifests/testing/ssc-for-ocp.yaml.in
tests/Dockerfile
tests/README.md
tests/entrypoint.sh
tests/utils.go
tools/manifest-templator/manifest-templator.go
tools/vms-generator/vms-generator.go

Signed-off-by: Lukas Bednar <lbednar@redhat.com>

Build container to run tests containerised

---

tests/registry_disk_test.go
tests/utils.go

Mounts virtio as sata cdrom and
tests whether the files are really
present.
Fixes #
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/1833)

Add virtio mount test

---

cmd/example-hook-sidecar/smbios.go
pkg/staging/glog/glog.go

This PR fixes occured errors during the compilation process for golang 1.11.2. Btw. this should be fixed even if we are not using 1.11.2 yet.
Fixes #
```release-note
None
```

Bugfix for go 1.11.2

---

tests/vmi_networking_test.go

Automate vNIC tests:
- Verify default NIC model type is VirtIO.
- Verify unsupported NIC model type cannot be applied.

Automate vNIC tests

---

hack/docker-builder/Dockerfile
pkg/api/v1/schema_swagger_generated.go
pkg/api/v1/schema_test.go
pkg/api/v1/types_swagger_generated.go
pkg/controller/expectations_test.go
pkg/util/openapi/openapi.go
pkg/virt-controller/services/template_test.go
pkg/virt-operator/creation/rbac/cluster.go
tests/vmi_configuration_test.go

Update golang to 1.11.2 version
Fixes #
```release-note
None
```

Update golang to 1.11.2 version

---

docs/architecture.md

I heard The Razor evoked several times during design discussions, but I don't seem to find
it mentioned in a formal setting.
Fixes #
@fabiand @rmohr @booxter 
I think we should mention this principle explicitly and loudly.
```release-note
NONE
```

design principle: The Razor

---

automation/test.sh
tests/imageupload_test.go
tests/utils.go

- print relevant PV's and PVC's under `FailHandler`
- remove PVC after `imageupload` test
- use separate storage class for RHEL and Windows PV's
Fixes #
```release-note
NONE
```

tests: stabilize RHEL template test

---

tests/vmi_multus_test.go

Add test attributes to L2 network configuration in multus.

Add test attributes to L2 network configuration in multus.

---

tests/vm_test.go

Add Polarion test ids to vm test
```release-note
NONE
```

[CNV QE] Add Polarion id to vm test

---

tests/config_test.go

**What this PR does / why we need it**: `Added test attributes to config_test`
Fixes #
```
NONE
```

Added test attributes to config_test

---

tests/networkpolicy_test.go

Changed all test to have rfe id, test id, criticality etc attributes
Fixes #
```release-note
NONE
```

Add test attributes for networkpolicy cases

---

tests/console_test.go

**What this PR does / why we need it**: `Added test attributes to console_test`
Fixes #
```
NONE
```

Added test attributes to console_test

---

hack/kubevirt-builder/Dockerfile

Use builder image hash instead of tag
Fixes #
```release-note
NONE
```

Use builder image hash instead of tag

---

tests/vmi_userdata_test.go

**What this PR does / why we need it**: `Added test_attributes for vmi_userdata`
Fixes #
```
NONE
```

Added test_attributes for vmi_userdata

---

tests/vnc_test.go

**What this PR does / why we need it**: `Added test_attributes for vnc_test`
Fixes #
```
NONE
```

Added test_attributes for vnc_test

---

cmd/container-disk-v1alpha/entry-point.sh
pkg/container-disk/container-disk.go
tests/registry_disk_test.go

Improves the unintuitive container-image custom path handling. Now it fully behaves as is written in the documentation.
Fixes https://bugzilla.redhat.com/1660412
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/1891)

Fix custom path handling

---

tests/vmi_lifecycle_test.go

**What this PR does / why we need it**: `Added test_attributes for vmilifecycle_tests`
Fixes #
```
NONE
```

Added test_attributes for vmilifecycle_tests

---

tests/vmi_configuration_test.go

**What this PR does / why we need it**: `Added test_attributes for vmi_configuration`
Fixes #
```
NONE
```

Added test_attributes for vmi_configuration

---

docs/architecture.md

**What this PR does / why we need it**: Addresses a few typos in documentation.
```release-note
NONE
```

Minor improvements to architecture documentation

---

pkg/kubecli/generated_mock_kubevirt.go
pkg/kubecli/kubecli.go
pkg/kubecli/kubevirt.go
pkg/virt-operator/util/client.go
pkg/virt-operator/util/client_test.go

Improved test for OpenShift by using the discovery client
Follow up of https://github.com/kubevirt/kubevirt/pull/1966#discussion_r252320217
```release-note
NONE
```

Improved test for OpenShift by using the discovery client

---

cluster/deploy.sh

Improved deploy script:
- wait for KubeVirt CRD and CR
- wait for Ready condition
```release-note
NONE
```

Improved deploy script

---

tests/utils.go
tests/vmi_multus_test.go
tests/vmi_networking_test.go

Add negative tests for invalid MAC address on POD network and on Multus network 
```release-note
NONE
```

Tests for invalid MAC

---

docs/getting-started.md

Signed-off-by: Vijay Bellur <vbellur@redhat.com>
Minor improvements to getting-started guide. Updates an old URL and fixes a few typos.
```release-note
NONE
```

Minor improvements to getting-started guide

---

doc.go

Added a random Go file to project root, for "dep" dependency manager
Fixes #2017
```release-note
NONE
```

Added a random Go file to project root, for "dep" dependency manager

---

tests/expose_test.go

Automate service expose test:
Expose VM as a Cluster IP service, delete the VM and verify the service is no longer functional.

Automate service expose test

---

hack/dockerized

Mount .docker directory only when it exists
Fixes #
```release-note
NONE
```

Mount .docker directory only when it exists

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go

Signed-off-by: Marcin Franczyk <mfranczy@redhat.com>
It allows to read node selectors from kubevirt-config configMap, as example:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: kubevirt-config
namespace: {{.Namespace}}
labels:
kubevirt.io: ""
data:
node-selectors: |
kubernetes.io/hostname=node02
node-role.kubernetes.io/compute=true
```
**Special notes for  your reviewer**:
```release-note
Limit VMIs to specific nodes
```

read node selectors from kubevirt-config configMap

---

tests/expose_test.go
tests/utils.go

Automate HTTP expose test:
Verify a VM exposed as service can be used for HTTP connection.

Automate HTTP expose test

---

.gitignore
.travis.yml
Makefile
hack/dockerized
pkg/virtctl/imageupload/BUILD.bazel
pkg/virtctl/imageupload/imageupload_test.go

Bazel tests run under the sandbox with the relative folder structure, so do use some file we need to bring it first to sandbox.
Fixes #2039
```release-note
NONE
```

Bring cirros images to the sandbox where the test runs

---

tests/utils.go
tests/vmi_configuration_test.go

Fixes #2048 
```release-note
None
```

don't depend on hard-coded names for node

---

WORKSPACE

Update the virt-win image to latest.
This PR allow as to configure the right MTU inside a windows machine interface via the domXML
Related to https://github.com/kubevirt/kubevirt/pull/1905
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/2066)

Update virt-win iso to latest

---

tests/expose_test.go
tests/vmi_multus_test.go
tests/vmi_networking_test.go

Added more test attributes to expose_test.go, vmi_mulutus_test.go, vmi_networking_test.go

Added more test attributes to expose_test.go, vmi_mulutus_test.go, vmi_networking_test.go

---

Makefile
automation/test.sh
hack/bazel-build-images.sh

Fixes #
```release-note
NONE
```

Repeat bazel build under CI to be sure that it succeeds

---

WORKSPACE

Fixes the wrong image hash in WORKSPACE
@cynepco3hahue please review
Fixes #
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/2112)

Fix virtio hash in WORKSPACE

---

WORKSPACE

Updated libstdc++ version
```release-note
NONE
```

Updated libstdc++ version

---

pkg/virt-handler/device-manager/device_controller_test.go

Fix device manager tests.
Fixes #2132 
```release-note
NONE
```

Fix device manager test race

---

cluster/k8s-multus-1.13.3/provider.sh
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go

Related to a work done in istio https://github.com/istio/istio/pull/11321
We introduce a new label for kubevirt to help manage the traffic getting in and out of the envoy process
Fixes #
```release-note
Istio integration with masquerade
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/2047)

Add annotaion to the virt-launcher template for istio

---

pkg/virt-launcher/virtwrap/network/common.go

change the location of error log
Fixes #
```release-note
```

change the location of error log.

---

tests/migration_test.go
tests/utils.go
tests/vmi_lifecycle_test.go

This PR does not add feature or fix any issue, it just make the code in tests/ more consistent.
```release-note
NONE
```

tests: use GetAllSchedulableNodes() function where possible

---

docs/getting-started.md

Add getting-started documentation for macOS

---

hack/bazel-build-images.sh
hack/bazel-push-images.sh

Use for loop instead of if clause with same content but different DOCKER_TAG.
```release-note
NONE
```

Deduplicate bazel hack scripts

---

.travis.yml
hack/build-manifests.sh
hack/config-default.sh
hack/config.sh
hack/olm.sh
tools/manifest-templator/manifest-templator.go

Removed default value for QUAY_REPOSITORY + skip quay access when not set
There are situations without internet access
```release-note
NONE
```

Removed default value for QUAY_REPOSITORY + skip quay access when not set

---

pkg/monitoring/vms/prometheus/prometheus.go
pkg/virt-launcher/virtwrap/stats/types.go
pkg/virt-launcher/virtwrap/statsconv/converter.go
pkg/virt-launcher/virtwrap/statsconv/domstats_expected.json
tests/infra_test.go

Add support for more memory metrics: Swap{In,Out} reporting
Fixes https://github.com/kubevirt/kubevirt/issues/2023
none
```release-note
Add support to report SwapIn and SwapOut metrics
```

prometheus: metrics: add Swap{In,Out} reporting

---

.travis.yml
docs/devel/olm-integration.md
hack/build-manifests.sh
hack/kubevirt-builder/Dockerfile
hack/olm.sh
manifests/release/olm/bundle/kubevirtoperator.VERSION.csv.yaml.in
tools/manifest-templator/manifest-templator.go

- Added flag to skip j2 template generation, they are not needed always
- Added missing fields in CSV and improved verification
Fixes #2191 
```release-note
NONE
```

OLM integration fixes

---

pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go

In some cases live migration can fail due to a reason which is not reported via getJobStats and eventually will remain masked.
This PR improves error reporting.
```release-note
NONE
```

handle migration failures inside the migration monitor

---

tests/BUILD.bazel
tests/datavolume_test.go
tests/operator_test.go
tests/utils.go

Adds more DataVolume related functional tests. 
```release-note
NONE
```

Functional tests for enabling/disabling datavolume feature gate

---

tests/vmi_configuration_test.go

Fixes #
```release-note
NONE
```

Fix flaky usb controller test

---

cmd/virt-launcher/virt-launcher.go

VMI's conrainerDisk containers are not terminating, on the CRIO runtime, when the main virt-launcher container terminates. This affects mainly the live migration. When source pod doesn't completely terminate, it isn't possible to schedule another migration for the VMI. In addition, the non-terminated pod doesn't release disk resources.
This PR simple cleans up the ephemeralDisk directory before virt-launcher completely exits, effectively making containerDisks to terminate. 
Fixes #2240 
```release-note
NONE
```

make all container disks exit after virt-launcher terminates

---

tests/vmipreset_test.go

Add missing functional test for VMIs overriding Presets

---

tests/vmipreset_test.go

[Testing] Add missing test case for VMI Preset lifecycle

---

tests/storage_test.go

[Testing] add hostdisk test_id

---

tests/vmi_iothreads_test.go

[Testing] Add more tests for ioThreadPolicies

---

tests/probes_test.go

Adds ref_id for test cases.
Fixes #
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/2279)

[Testing]Add polarion refid for liveness and readiness

---

tests/BUILD.bazel
tests/vmi_multiqueue_test.go

[Testing] Add missing test for Block MultiQueue

---

docs/env-providers.md
docs/getting-started.md

Fix documentation regarding updated k8s default provider.
Fixes #
```release-note
NONE
```

Update k8s provider default in docs.

---

tests/migration_test.go

Add test ID for TLS secured migration test
Fixes #
```release-note
NONE
```

[tests] Add test ID for TLS secured migration test

---

tests/datavolume_test.go
tests/template_test.go
tests/utils.go
tests/vm_test.go
tests/windows_test.go

[Testing] Test VM creation via command line

---

tests/vm_test.go

[Testing] Add test ID's for runStrategy tests

---

tests/storage_test.go

Test id's for hostDisk and PV initialization tests
```release-note
None
```

[Testing] add test id's for hostDisk and PV initialization tests

---

docs/updates.md

Documents how updates work. 
```release-note
NONE
```

KubeVirt Update documentation

---

automation/test.sh

Fixes #
```release-note
NONE
```

Use Prow env variable to detect if we run under the CI environment

---

.travis.yml
manifests/release/olm/bundle/kubevirt-package.yaml.in
manifests/release/olm/bundle/kubevirtoperator.vVERSION.clusterserviceversion.yaml.in
tools/manifest-templator/manifest-templator.go

Improved OLM integration:
- fixed some issues identified during initial contribution to operatorhub.io (missing/misconfigured fields), see https://github.com/operator-framework/community-operators/pull/314
- improved description
- fixed release of CSV file (only release latest one)
Fixes #2248 
Description is almost a copy from our README.md
/cc @fabiand 
```release-note
NONE
```

Olm improvements

---

tests/vmipreset_test.go

[Testing] Add missing functional test covering matchExpressions of Presets

---

SECURITY.md

It adjusts the fresh security policy.
Fixes #
```release-note
NONE
```

Security policy rewording

---

hack/build-docker.sh

Before we did not parse the `${target}` parameter, so we never really pulled or pushed the image.
Fixes #
```release-note
NONE
```

Fix builder caching under the CI

---

tests/vmipreset_test.go

Add missing functional test for matching multiple VMs via MatchLabel

---

tests/storage_test.go

An issue has been filed to track this
https://github.com/kubevirt/kubevirt/issues/2272
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/2353)

Disable ISCSI storage tests for provider v1.13.3

---

.gitignore

This PR update the git ignore file to remove _ci-configs folder fromthe git history
Related to https://github.com/kubevirt/kubevirt/pull/2335
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/2363)

Update git ignore file for _ci-configs folder

---

cluster-up/kubectl.sh
cluster-up/virtctl.sh
hack/config-default.sh

Fixes #2367
```release-note
NONE
```

Pull in kubevirtci fix for virtctl.sh script

---

tests/BUILD.bazel
tests/utils.go
tests/vmi_configuration_test.go
tests/vmi_headless_test.go

Extend test coverage for headless VMs. The tests cover memory overcommit and graphics check.
Both positive and negative.
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/2289)

[Testing] Add headless VM tests

---

cluster-up/cluster/ephemeral-provider-common.sh
cluster-up/cluster/external/README.md
cluster-up/cluster/external/provider.sh
cluster-up/ssh.sh
hack/cluster-build.sh
hack/config-default.sh

Fixes #2380
```release-note
NONE
```

Push latest images on make cluster-sync

---

tests/windows_test.go

Adds ids to tests so that they can be found.
Fixes #
```release-note
NONE
```

Add test ids

---

tests/vmi_configuration_test.go

With spec.domain.cpu.cores,
*) should configure correct no.of vcpus
*) should start a vm with no cpu pinning after a vm with cpu pinning on same node.
*) should start a vm with cpu pinning after a vm with no cpu pinning on same node.
**What this PR does / why we need it**: Adds few more cpu-pinning tests 
Fixes #
```
NONE
```

Added the remaining cpu-pinning tests.

---

tests/vmi_configuration_test.go

Fixes #
```release-note
None
```

[Testing] add test 'check guest memory different from requested memory'

---

hack/cluster-build.sh

Push updated images to all nodes on run of `make cluster-sync` command.
Fixes #
```release-note
NONE
```

Push updated images to all nodes

---

tests/storage_test.go

polarion id for block pvc test
```release-note
None
```

[Testing] polarion id for block pvc test

---

pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go

Improve that log message as suggested by @rmohr on #2304.
```release-note
NONE
```

Improve logging of memory-request being set according to cluster memory-overcommit

---

hack/functests.sh

A lot of tests got added. We need to increase the timeout.
Fixes #
```release-note
NONE
```

Increase test timeout for the whole test suite

---

Makefile

Fixes #
```release-note
NONE
```

Rename functest-build-image to functest-image-build

---

hack/builder-cache.sh
hack/common.sh

Fixes #
Sorry for all this TYPO's :cry: 
```release-note
NONE
```

Fix name of build functest image function

---

tests/storage_test.go

polarion id for non-existent pvc test
Fixes #
```release-note
None
```

[Testing] add polarion id for non-existent pvc test

---

tests/vmi_configuration_test.go

Fixes #
```release-note
Added OverCommit VM memory tests
```

[Test] Adding OverCommit VM memory tests

---

pkg/monitoring/vms/prometheus/prometheus.go
tests/infra_test.go

Add metrics about packets and errors, which will be consumed
by the UI.
N/A
```release-note
None
```

prometheus: network: report packets and error

---

cmd/virt-launcher/virt-launcher.go
pkg/util/net/grpc/grpc.go

Signed-off-by: Jim Ma <ema@redhat.com>
Fixes #2434 

Remove duplicate code to delete/create socketPath in virt-launcher

---

OWNERS

Allows lgtm and approve to work, which in turn will allow automatic
retest.
Fixes #
```release-note
NONE
```

Add initial owners file

---

OWNERS

mfranczy added to reviewers group
Fixes #
```release-note
None
```

add mfranczy to reviewers

---

OWNERS

Will add me to the list of reviewers.
Fixes #
```release-note
NONE
```

Add dhiller to reviewers section of OWNERS

---

manifests/testing/kubevirt-config.yaml.in
pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
pkg/virt-config/feature-gates.go
tests/BUILD.bazel
tests/operator_test.go
tests/utils.go
tests/vmi_hook_sidecar_test.go

It introduces a sidecar feature gate in order to give cluster administrator some control on executed code within pod's environment
Fixes #
```release-note
introduce sidecar feature gate
```

introduce sidecar feature gate

---

WORKSPACE

Fixes #
```release-note
NONE
```

Add mirror for libvirt packages

---

OWNERS_ALIASES

Add me as a reviewer.
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/2513)

Add me as a reviewer

---

hack/functests.sh

Fixes non-working oc command in integration tests.
Fixes #
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/2500)

Fix nonworking oc command

---

.travis.yml

Publish staging on master or tags instead of when on tagged master.
Fixes #
```release-note
NONE
```

Publish staging on master or tags

---

tests/vmi_networking_test.go

The default MTU on the pod network interface varies, depending
on the environment on which the cluster runs, and it made some
of the tests to fail.
Now the test covers all the possible MTU values.

Fixed failure of networking tests.

---

pkg/virt-api/rest/subresource.go
pkg/virt-api/rest/subresource_test.go

In virt-api subresources, Changed http status code from StatusBadRequest to StatusForbidden to present correct status code and errors
Fixes #2373 
```release-note
Changed http status code from StatusBadRequest to StatusForbidden
```

Changed http status code from StatusBadRequest to StatusForbidden

---

pkg/monitoring/vms/prometheus/prometheus.go

Add debug logs about unlikely failure scenarios
Fixes: N/A
Spawned from the review of https://github.com/kubevirt/kubevirt/pull/2501
```release-note
NONE
```

metrics: add debug logs about collection failures

---

tests/migration_test.go

We are not fast  enough to check on every proxy if our tls certificate gets refused. In order to still make this test valuable, verify that the proxy which copies the memory, and is therefore long running, refuses the certificate. Further ensure that any successful connection attempt would make the test fail.
Fixes #2480
```release-note
NONE
```

Fix flaky tls migration check test

---

tests/vmi_configuration_test.go

Corrected duplicate test-id
Fixes #
```release-note
NONE
```

Corrected duplicate test-id

---

tests/migration_test.go

Once tainting the node unschedulable,
the migration can take time to kick in.
Specificaly wait for it.
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/2564)

Add wait until migration kick in

---

tests/vmi_headless_test.go

Fixes #
```release-note
NONE
```

Add test_id for vmi_headless test

---

staging/src/kubevirt.io/client-go/README.md

readme.md url fixed
Signed-off-by: Kunal Kushwaha <kunal.kushwaha@gmail.com>
fixes the broken link in client-go readme file.
https://github.com/kubevirt/kubevirt/pull/2551#discussion_r311431901
Fixes #
https://github.com/kubevirt/kubevirt/pull/2551#discussion_r311431901
```release-note
NONE
```

typo fixed.

---

manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/controller/virtinformers.go
pkg/virt-operator/application.go
pkg/virt-operator/creation/components/BUILD.bazel
pkg/virt-operator/creation/components/scc.go
pkg/virt-operator/creation/rbac/operator.go
pkg/virt-operator/install-strategy/create.go
pkg/virt-operator/install-strategy/delete.go
pkg/virt-operator/install-strategy/strategy.go
pkg/virt-operator/kubevirt.go
pkg/virt-operator/kubevirt_test.go
pkg/virt-operator/util/types.go
tests/operator_test.go

It handles SecurityContextConstraints objects and creates the `kubevirt` SCC for virt-launcher.
Fixes #
Still updating tests.
```release-note
SecurityContextConstraints support
```

add kubevirt SecurityContextConstraints

---

tests/reporter/BUILD.bazel
tests/reporter/kubernetes.go
tests/utils.go

Log domain XMLs on test failures.
Fixes #
```release-note
NONE
```

Log domain XMLs on test failures

---

tests/migration_test.go

Fix handling error in migration wait loop
Sometimes kube-api returns "unexpected EOF"
while calling GET for any object.
The error is rare and reported in
https://github.com/kubernetes-sigs/kubespray/issues/2322
The fix makes the loop resilient to these errors
by ignoring and retrying.
Also it makes the VM smaller, to enable faster migration.
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt/2557)

Fix handling error in migration wait loop

---

tests/vmi_lifecycle_test.go

Fixes RHBZ#https://bugzilla.redhat.com/show_bug.cgi?id=1717511
No intended changes in behaviour. We are updating to a very old default CPU to a slightly less older default CPU. Both should be perfectly fine for our test purposes.
```release-note
None
```

tests: bump default CPU to Nehalem

---

pkg/virtctl/imageupload/imageupload.go
pkg/virtctl/imageupload/imageupload_test.go

so that we won't show a weird message when it's missing
Fixes #2496 
```release-note
NONE
```

make pvc-size a mandatory param

---

hack/build-go.sh

The containerdisk binary is used in containerdisk images which are build from scratch, so it needs to be static
```release-note
NONE
```

Static go build of containerdisk binary

---

tests/vmi_configuration_test.go

Added test_id in the test
Added test_id in the test
Fixes #
```release-note
Added test_id in the test
```

Added test_id in the test

---

tests/operator_test.go

**What this PR does / why we need it**: `Add the test-id to check kubevirt SCCs created tests`
Fixes #
```
NONE
```

Add test-id to check kubevirt SCCs created tests

---

docs/getting-started.md

the doc is not up-to-date now.. we need update accordingly
Fixes #
```release-note
```

Update doc of getting start

---

tests/virt_control_plane_test.go

Adds ids to tests to connect test cases to polarion test plans.
Fixes #
```release-note
NONE
```

Add polarion test case ids regarding PDB test cases

---

pkg/virt-config/feature-gates.go
tests/networkpolicy_test.go
tests/vnc_test.go

Fix polarion test id of multiple VNC consoles test
```release-note
NONE
```

Fix polarion test id of multiple VNC consoles test

---

tests/access_test.go
tests/vm_test.go

**What this PR does / why we need it**: `Add test-ids for the regular user and sa user tests`
Fixes #
```
NONE
```

Add test-ids for the regular user and sa user tests

---

tests/vmi_multus_test.go

**What this PR does / why we need it**: test custom MAC address for SR-IOV interfaces in kubevirt context
```release-note
NONE
```

Added functional test for custom MAC address for SR-IOV

---

OWNERS_ALIASES

Since I am able to merge kubevirt PRs manually (github permissions), I would like to keep my rights to approve PRs.
Fixes #
```release-note
NONE
```

add mfranczy to approvers

---

manifests/generated/operator-csv.yaml.in
tools/csv-generator/csv-generator.go

Signed-off-by: Ido Rosenzwig <irosenzw@redhat.com>

Increase replicas on the csv-generator

---

docs/getting-started.md

I am using the ssh way to test but actually it's `kind`, so we need change doc about this
Fixes #
```release-note
NONE
```

update doc about ssh method usage

---

tests/windows_test.go

Link Polarion test id to Start a VM via CLI command test.
None
```release-note
```

Link test id to Start VM via CLI test

---

tests/console_test.go
tests/migration_test.go

Several test_id corrections
Fixes #
```release-note
None
```

test_id correction

---

pkg/virt-handler/selinux/labels.go

See - https://github.com/kubevirt/kubevirt/issues/2664#issuecomment-527766499
Fixes #
```release-note
Log errors under virt-handler SELinux package
```

Log the error under the SELinux package

---

tests/vmi_networking_test.go

Fix compile error in test
Happened when merging several PRs
```release-note
NONE
```

Fix compile error in test

---

WORKSPACE

Fix virtio-win dl location
```release-note
NONE
```

Fix virtio-win dl location

---

tests/operator_test.go

**What this PR does / why we need it**: `Add test_id for with servicemonitor enabled`
Fixes #
```
NONE
```

Add test_id for with servicemonitor enabled

---

tests/expose_test.go
tests/migration_test.go
tests/storage_test.go
tests/utils.go
tests/windows_test.go

This PR removes two functions from `tests/utils.go` and minimize the generation of random names within the tests.
```release-note
NONE
```

Cleanup in functional tests

---

tests/vm_test.go

Enhanced virtctl tests to verify the error message also
Previously these messages had error in showing the correct text
Fixes #
```release-note
Enhanced virtctl tests to verify the error message also
```

Enhanced virtctl tests to verify the error message also

---

OWNERS_ALIASES

Fixes #
```release-note
NONE
```

Add fabiand as a maintainer

---

README.md

Add best practice badge, as requested in #2679
Fixes #
```release-note
NONE
```

Add best practice badge

---

cmd/example-cloudinit-hook-sidecar/cloudinit.go

typofix.
delete extra blank lines.
```release-note
delete extra blank
```

cmd/example-cloudinit-hook-sidecar: delete extra blank lines.

---

pkg/util/cluster/BUILD.bazel
pkg/util/cluster/cluster.go
pkg/util/cluster/cluster_suite_test.go
pkg/util/cluster/cluster_test.go
pkg/util/util.go
pkg/virt-handler/BUILD.bazel
pkg/virt-handler/device-manager/BUILD.bazel
pkg/virt-handler/device-manager/generic_device.go
pkg/virt-handler/selinux/BUILD.bazel
pkg/virt-handler/selinux/labels.go
pkg/virt-handler/vm.go
pkg/virt-operator/BUILD.bazel
pkg/virt-operator/application.go
pkg/virt-operator/util/BUILD.bazel
pkg/virt-operator/util/client.go
pkg/virt-operator/util/client_test.go
tests/BUILD.bazel
tests/utils.go

- It checks a CPU policy from `cpu_manager_state` file
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=1718944
```release-note
cpu-manager detection fix
```

cpu-manager detection fix

---

OWNERS_ALIASES

Access to [CNCF services](https://github.com/cncf/servicedesk) is limited to project maintainers.
As a community liaison I'd need to interact with these services, hence this request
Fixes #
```release-note
NONE
```

Add Pep as a maintainer

---

pkg/hooks/manager.go

Fix a typo in variable name

---

tests/vmi_multus_test.go

Cherrypick of commits contained in https://github.com/kubevirt/kubevirt/pull/2649 to port the test to release 0.20 
```release-note
NONE
```

[release-0.20] failing ptp test

---

pkg/virt-handler/cmd-client/client.go

Fixes #
```release-note
NONE
```

Check GetDomain and GetDomainStats response not to be nil

---

pkg/monitoring/vms/prometheus/collector.go
pkg/monitoring/vms/prometheus/prometheus.go

Reduce promethues messages, which arent' very informative unless we are troubleshooting issues,
and in that case we want more verbose log anyway.
Fixes: https://github.com/kubevirt/kubevirt/issues/2729
N/A
```release-note
NONE
```

Prometheus verbosity

---

WORKSPACE

Ensure that our dependencies don't disappear.
Fixes #
```release-note
NONE
```

Put all our direct dependencies on our mirror

---

pkg/virt-launcher/virtwrap/api/converter.go

Fixes #
```release-note
NONE
```

fix file close panic when error happens in OpenFile

---

WORKSPACE

Put all our direct dependencies on our mirror
Fixes #
```release-note
NONE
```

[release-0.20] Put all our direct dependencies on our mirror

---

WORKSPACE

Put all our direct dependencies on our mirror
Fixes #
```release-note
NONE
```

[release-0.21] Put all our direct dependencies on our mirror

---

WORKSPACE

Put all our direct dependencies on our mirror
Fixes #
```release-note
NONE
```

[release-0.22] Put all our direct dependencies on our mirror

---

tests/vmi_lifecycle_test.go

**What this PR does / why we need it**: `bump default CPU to Nehalem`
Fixes #
```
NONE
```

[release-0.20] tests: bump default CPU to Nehalem

---

tests/operator_test.go

Fixes #
```release-note
NONE
```

Operator test: add test ids

---

tests/vmi_configuration_test.go

update RFE ids and add new test ids
Fixes #
```release-note
NONE
```

vmi configuration: add test ids

---

tests/storage_test.go

Fixes #
```release-note
NONE
```

Storage add test ids

---

tests/vmi_iothreads_test.go

update RFE ids and add new test ids
Fixes #
```release-note
NONE
```

IOthreads test:Add test ids

---

tests/vmi_hook_sidecar_test.go

Fixes #
```release-note
NONE
```

vmi hook sidecar test: add test ids

---

tests/windows_test.go

Fixes #
```release-note
NONE
```

Window vm: add test ids

---

tests/vm_test.go
tests/vmi_cloudinit_hook_sidecar_test.go

Fixes #
```release-note
NONE
```

vm test and cloudInit sidecar hooks: add test ids

---

tests/subresource_api_test.go

Fixes #
```release-note
NONE
```

Subresource test: add test ids

---

tests/vmi_cloudinit_test.go

Fixes #
```release-note
NONE
```

CloudInit userData: add test ids

---

tests/datavolume_test.go
tests/infra_test.go
tests/storage_test.go

Fixes #
```release-note
NONE
```

Data volume test - add tests ids

---

tests/utils.go

Fixes #
```release-note
NONE
```

Set send timeout to the expecter

---

tests/operator_test.go

Fixes #
```release-note
NoNE
```

operator test add add test ids

---

tests/pausing_test.go

**What this PR does / why we need it**: `Adds the test_id for the pausing_test`
Fixes #
```
NONE
```

Add the test_id for pausing_test

---

OWNERS
OWNERS_ALIASES

Signed-off-by: Marcin Franczyk <marcin0franczyk@gmail.com>
With new projects, it's hard to track changes in KubeVirt code, I should not be an approver anymore.
Fixes #
```release-note
None
```

move mfranczy to emeritus approvers

---

pkg/virtctl/imageupload/imageupload.go

typos in recently replaced help text
Fixes #
```release-note
NONE
```

fix typos in virtctl image-upload command

---

OWNERS_ALIASES

Asking permission to be added as a code reviewer
Fixes #
```
NONE
```

Add Igor Bezukh to reviewers

---

OWNERS_ALIASES

Signed-off-by: Daniel Hiller <daniel.hiller.1972@gmail.com>
We are currently lacking approvers, so we need some more in this group of people to be able to approve PRs in a timely manner.
Fixes #
```release-note
NONE
```

Add dbelenky and dhiller to approvers

---

.travis.yml
Makefile
hack/prom-rule-ci/BUILD.bazel
hack/prom-rule-ci/rule-spec-dumper.go
hack/prom-rule-ci/verify-rules.sh
pkg/virt-operator/creation/components/crds.go

Fixed PromQL syntax error and added CI to ensure that we catch issues
like this in the future.
```release-note
NONE
```

Fix Prometheus alert rules and add CI for it

---

tests/kubectl_test.go

Fix the flaky oc tests
Fixes #
```release-note
fix flaky oc tests
```

Fix flaky oc tests

---

README.md

Signed-off-by: Alberto Losada <alosadag@redhat.com>
Keep the README.md updated and align with the project state
Fixes #2761 
It is replaced the chat information to contact with KubeVirt community. It has been added further resources to run and manage KubeVirt: blog and video channel.
```release-note
```

Updating the README.md file to align with project state

---

Makefile
hack/bump-kubevirtci.sh

Add bump-kubevirtci make target
```release-note
NONE
```

Add bump-kubevirtci make target

---

hack/ci/Dockerfile.ci
hack/ci/test.sh
hack/ci/wandisco-git.repo

Is _required_ to get openshift/release#6146 in. Checks fixes for @sallyom 's add-dockerfile-ci PR kubevirt/kubevirt#2991, as I don't want to mess with her branch.
As discussed with @rmohr we should clean up on this, and the cleanup should not be deferred that long. I.e. it looks like there is a couple of things we could remove if we extend from the builder image that has been updated recently. But as we need to get this in in order to be able to test this with the other PR openshift/release#6146 I'd be fine to merge this and create an issue for the cleanup. …

Add dockerfile ci

---

tests/vmi_networking_test.go

Fix "Multiple VM connectivity" tests to allow any mtu > 1000 
```release-note
None
```

Fix "Multiple VM connectivity" tests to allow any mtu > 1000

---

hack/cluster-deploy.sh

Need to retry in case of errors such as
Unable to connect to the server, request timed out
which are temporary
```release-note
None
```

Fix cluster-sync

---

CONTRIBUTING.md

The [contributing guide](https://github.com/kubevirt/kubevirt/blob/master/CONTRIBUTING.md) is missing a statement about DCO, which is added here.
See [this PR comment](https://github.com/kubevirt/kubevirt/pull/3082#issuecomment-587324475), try to find the instructions after clicking on the contribution guide link.
```release-note
NONE
```

Add missing DCO paragraph to CONTRIBUTING.md

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-controller/watch/vmi_test.go
tests/vmi_lifecycle_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1805627 by specifying fsGroup
```release-note
None
```

Ensure virt-launcher runs with qemu as a supplemental group

---

pkg/virtctl/pause/BUILD.bazel
pkg/virtctl/pause/pause.go

PR is adding better error messages for user which is trying to pause stopped VM.
Fixes #3061
```release-note
NONE
```

added error messages for pause cmd

---

docs/components.md

Signed-off-by: Joowon Cheong <jwcheong0420@gmail.com>
To fix typo in docs/components.md(corrsponding -> corresponding)
```release-note
NONE
```

Fix typo in docs/components.md

---

pkg/virt-launcher/virtwrap/api/converter.go
tests/vmi_iothreads_test.go

Currently, IOThreads are being placed on the same physical CPUs as the guest's virtual CPUs.
However, this may affect the expected latency of a vCPU
When `isolateEmulatorThread` is requested along with with `dedicatedCpuPlacement`, KubeVirt will allocate an additional pCPU and pin the QEMU emulator thread to it. In order to not affect the vcpu latency, this PR will pin the IOThread and the emulator thread on the same pCPU, if the iothread policy was set to the default "automatic". 
oVirt follows a similar pattern of placing io and the emulation threads on the same pCPU.
https://www.ovirt.org/develop/release-management/features/virt/high-performance-vm.html
```release-note
NONE
```

Pin the IO and the Emulator threads on the same pCPU when iothreads policy is Automatic

---

tests/operator_test.go

Fixes #
```release-note
NONE
```

Add test id to BlockUninstallIfWorkloadsExist test

---

tests/security_features_test.go

Fixes #
```release-note
NONE
```

Add test id: security features test

---

automation/repeated_test.sh

Current script does not work as it returns an exit code of 1 in case of "no tests changed". This modification disables option `e` for the function in order to return 0 in case of no tests changed.
Furthermore it corrects the default providers that changed until recently.
Fixes #
/cc @danielBelenky 
```release-note
NONE
```

Move fetching new tests into function, correct providers

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/migration_test.go
tests/vmi_multus_test.go

This is a manual cherry-pick of #3178
/assign stu-gott
```release-note
NONE
```

[release-0.26] Increase memory overhead for VFIO devices

---

tests/vmi_configuration_test.go

Fixes #
```release-note
NONE
```

Add test cases cdrom

---

docs/architecture.md

Signed-off-by: Ravid Brown <ravid@redhat.com>
Fixes #
```release-note
NONE
```

Elaborate on VM resource in architecture document

---

automation/repeated_test.sh

If there are a lot of test files touched, the result is a timeout as the
lane takes too long. We estimate the number of tests that are run and
skip if there are too many (taking as limit the number of total tests
for now).
Fixes #
See https://prow.apps.ovirt.org/?job=pull-kubevirt-check-tests-for-flakes&state=failure for examples (runs taking longer than 7h)
```release-note
NONE
```

Skip test run for flake lane for too many tests

---

tests/kubectl_test.go

These tests did not constrain their queries to a specific resource,
nor did they perform proper cleanup.
```release-note
None
```

Make kubectl related tests more reliable

---

OWNERS_ALIASES

Fixes #
```release-note
NONE
```

Add Jed to code-reviewers

---

automation/repeated_test.sh

Fixes the problem when test files have been deleted ([example](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3206/pull-kubevirt-check-tests-for-flakes/1247474309442572288) )
Fixes #
```release-note
NONE
```

Ignore deleted test files when checking for changes in test folder

---

tests/vmi_multus_test.go

We should validate that connectivity over SR-IOV works with both IPv4 and IPv6.
```release-note
NONE
```

Test sriov ipv6 ping

---

tests/vm_test.go

A handful of functional tests relied on using "--token" to indicate preference as to which service account the test should run as. These tests might have worked at some point in the past, but don't behave correctly with current k8s or openshift clients.
Since the intention of the test is to simply verify VM creation behavior/permissions, these tests have been changed to instead use the "auth can-i" subcommand--which unambiguously checks permissions for the explicitly named account.
```release-note
NONE
```

Fix tests relying on bearer token behavior

---

CONTRIBUTING.md

Just a small spelling fix in CONTRIBUTING.md.

CONTRIBUTING: Spelling fix, propoals -> proposals

---

tests/vmi_multus_test.go

Add test ids for SR-IOV tests
Fixes #
```release-note
None
```

Add test ids for SR-IOV tests

---

CONTRIBUTING.md

Introduce a simple procedure for contributors to join the kubevirt organization.

CONTRIBUTING: Add a procedure for joining the organization

---

OWNERS_ALIASES

Adding @AlonaKaplan to the list of code reviewers.
```
NONE
```

Adding @AlonaKaplan to code-reviewers

---

docs/devel/networking.md

Provide a developer guide focused on networking.
Partially Fixes #3333
Explains the 2 phases of pod networking setup, and the BindMechanism concept.
Still needed to explain each BindMechanism, and the multiple networks section.
```release-note
NONE
```

Add networking dev guide

---

docs/architecture.md

This is fixing some minor grammar issues.
```release-note
NONE
```
Signed-off-by: Doron Fediuck <dfediuck@redhat.com>

Minor corrections to architecture document

---

tests/vmi_configuration_test.go

Add test_id for vmi test
Fixes #
```release-note
NONE
```

Add test_id for vmi test

---

tests/console_test.go
tests/infra_test.go
tests/kubectl_test.go
tests/migration_test.go
tests/replicaset_test.go
tests/vm_test.go
tests/vmi_configuration_test.go
tests/vmi_iothreads_test.go
tests/vmi_lifecycle_test.go
tests/vmidefaults_test.go

Fixes #
```release-note
NONE
```

Add test cases ids

---

go.mod
go.sum
staging/src/kubevirt.io/client-go/go.mod
vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
vendor/modules.txt

Pull in the newer version of the qe-tools ginkgo reporter.
Fixes #
```release-note
NONE
```

Bump qe-tools dependency

---

OWNERS_ALIASES

Adding myself to code-reviewers
```release-note
NONE
```

Add omeryahud to code reviewers

---

tests/infra_test.go

It temporarily disables some flaky tests, we need it for test lanes to pass.
Fixes #
```release-note
NONE
```

Disable 2 flaky functional tests

---

CONTRIBUTING.md
docs/getting-started.md

Some parts of the documentation are incorrect.
```release-note
NONE
```

Minor fixes to documentation

---

docs/devel/networking.md

This PR adds information about the bridge binding mechanism to the networking dev guide.
Explaining the bridge bind mechanism is a pre-requirement to explain the masquerade bind mechanism, since plenty of the bridge implementation is re-used in that binding mechanism.
Partially Fixes #3333
Depends on #3342 
```release-note
NONE
```

Explain bridge bind mechanism

---

tests/config_test.go

Instead of sata use virtio on tests where we expect the same device
order like in the VMI spec. With sata we have no order-guarantee, with
virtio we have, if the VMI has the corresponding kernel drivers
installed.
This fixes flaky test
```
[rfe_id:899][crit:medium][vendor:cnv-qe@redhat.com][level:component]Config With a Secret and a ConfigMap defined With a single volume [test_id:786]Should be that cfgMap and secret fs layout same for the pod and vmi
```
where now and then the order of some of the sata disks changes.
Fixes #
```release-note …
```

Use virtio in tests where the disk order matters

---

tests/vmi_slirp_interface_test.go

fix tiny typo

---

OWNERS_ALIASES

Adding @rnetser to the list of test-reviewers
```release-note
NONE
```

Adding @rnetser to the list of test-reviewers

---

tests/migration_test.go
tests/storage_test.go
tests/utils.go

Tests existing functionality using NFS
```release-note
NONE
```

Add functional tests using NFS as backing store

---

docs/devel/networking.md

This PR adds information about the masquerade binding mechanism to the networking dev guide.
It focuses on how the packets are NAT'ed from the pod networking interface to the in-pod bridge, and the other way around.
Depends on: #3344 
```release-note
NONE
```

Explain masquerade bind mechanism

---

automation/repeated_test.sh

The list of kubevirt providers for the flakiness check lane was hard coded, this is now replaced by fetching the available k8s providers from the `cluster-up` directory, sorting them and picking the three most recent ones.
Fixes #
/cc @oshoval 
```release-note
NONE
```

Improve lane selection for repeated tests

---

automation/test.sh

Collect infra logs from infra containers to debug CI failures

---

pkg/virt-operator/creation/components/crds.go
tests/kubectl_test.go
tests/vm_watch_test.go

This is a cherrypick of PR #3414
```release-note
NONE
```

[release-0.29] Fix inconsistency in VM CRD CLI output

---

docs/devel/networking.md

This commit explains how masquerade for ipv6 works, using as base
IPv4 masquerade configuration.
```release-note
NONE
```

docs: explain masquerade bind mechanism for ipv6

---

tests/storage_test.go
tests/vmi_configuration_test.go

Fixes empty temporary directory left behind by some tests
Fixes #
```release-note
NONE
```

Cleanup a couple of leftover tmp dirs in tests

---

docs/graceful-shutdown.md

Signed-off-by: Joowon Cheong <jwcheong0420@gmail.com>
To fix typo in docs/graceful-shutdown.md
```release-note
NONE
```

Fix typo in docs/graceful-shutdown.md

---

OWNERS_ALIASES

Add Alona as approver

---

tests/container_disk_test.go

**What this PR does / why we need it**: `Add test to check kubevirt disk perms`
Fixes #
**Special notes for your reviewer**: `Add test to check kubevirt disk perms`
```
NONE
```

Add test to check kubevirt disk perms

---

api/openapi-spec/swagger.json
staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types.go
staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types_swagger_generated.go

dumb copy/paste error
Fixes #
```release-note
NONE
```

fix wrong json tag name for VirtualMachineSnapshot.Spec.DeletionPolicy

---

tests/vmi_multus_test.go

SRIOV functional tests are run in all environments today, even those that do not support SRIOV, this fix checks if the environment has SRIOV enabled and only then allows the tests to be run otherwise they are skipped. 
Fixes #
```NONE
```

Fix for checking if an environment has SRIOV enabled before executing the SRIOV functional tests. 

---

images/disks-images-provider/entrypoint.sh

In ubuntu host, selinux is not enabled by default.
When starting disks-images-provider, following failure
would appear:
"can't apply partial context to unlabeled file".
Check if file selinux tag exist before use chcon.

fix disks-images-provider error in ubuntu host

---

tests/security_features_test.go
tests/utils.go

**What this PR does / why we need it**: `Add test related to launcher capabilities`
Fixes #
**Special notes for your reviewer**: `Add test related to launcher capabilities`
```
NONE
```

Add test related to launcher capabilities

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
pkg/virt-config/feature-gates.go
tests/storage_test.go
tests/vmi_configuration_test.go
tools/vms-generator/vms-generator.go

This PR adds the feature gate "HostDisk" that has to be enabled to use hostDisks.
Fixes #
```release-note
The "HostDisk" feature gate has to be enabled to use hostDisks
```

Add a feature gate to enable hostDisks

---

tests/infra_test.go

Fix reference to hardcoded namespace in functional test

---

tests/vmi_configuration_test.go

**What this PR does / why we need it**:  `Add test-id for EFI secure boot test`
Fixes #
**Special notes for your reviewer**: `Add test-id for EFI secure boot test`
```
NONE
```

Add test-id for EFI secure boot test

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
pkg/virt-config/feature-gates.go
tests/storage_test.go
tests/vmi_configuration_test.go
tools/vms-generator/vms-generator.go

This is a cherry-pick of https://github.com/kubevirt/kubevirt/pull/3635
```release-note
The "HostDisk" feature gate has to be enabled to use hostDisks
```

[release-0.30] Add a feature gate to enable hostDisks

---

FAQ.md

Closes #3515
```release-note
NONE
```

Add a FAQ entry with a comparison to Kata containers.

---

tests/container_disk_test.go

**What this PR does / why we need it**: `Add test to check kubevirt disk perms`
Fixes #
**Special notes for your reviewer**: `Add test to check kubevirt disk perms`
```
None
```

[release-0.30] Add test to check kubevirt disk perms

---

pkg/virt-handler/notify-server/server.go

GRPC Stop doesn't wait for existing RPC to be finished totally,
but just until it opens a grpc serveStreams go routine.
It cause serveStreams goroutines to exists even after
reflector eventChan is closed, and can cause a race that would
result in panic: send on closed channel.
GracefulStop does wait for the whole grpc connections to be
totally closed, existing RPCs would first finish, new ones will
not be created and just after all existing ones are closed,
the channel would be closed.
Currently we close the server upon application layer client ERROR,
which is not needed, since the server has one instance per virt-handler,
and client side errors shouldn't affect
grpc server side, which serves all the clients in the node.
This would be taken care of in another commit.
Meanwhile we should …

Use GracefulStop instead of Stop for GRPC server

---

tests/security_features_test.go

Let the selinux tests use the new config propagation mechanism. This fixes test flakes like this:
```
/root/go/src/kubevirt.io/kubevirt/tests/security_features_test.go:146
Expected
<string>: spc_t
to equal
<string>: container_t
/root/go/src/kubevirt.io/kubevirt/tests/security_features_test.go:164
```
like experienced in https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3599/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1278713572813180928.
Fixes #
```release-note
NONE
```

Ensure that selinux context tests wait for configpropagation

---

tests/security_features_test.go
tests/utils.go

**What this PR does / why we need it**: `Add test related to launcher capabilities`
Fixes #
**Special notes for your reviewer**: `Add test related to launcher capabilities`
```
NONE
```

[release-0.30] Add test related to launcher capabilities

---

tests/security_features_test.go
tests/utils.go

**What this PR does / why we need it**: `Add tests related to qemu processes`
Fixes #
**Special notes for your reviewer**: `Add tests related to qemu processes`
```
NONE
```

Add tests related to qemu processes

---

docs/metrics.md

Signed-off-by: arthursens arthursens2005@gmail.com
What this PR does / why we need it:
Add a document to explain kubevirt vmi metrics
Which issue(s) this PR fixes
Fixes #3400
Special notes for your reviewer:
There is still a lot to be done. Maybe some examples could help... but know exactly which metrics should need examples e which one shouldn't
Metrics for Reflector, Client and Workqueue I think that could be docummented on another PR, since I don't have the necessary knowledge right now and could take quite some time
```release-note
NONE
```

Added Metrics docummentation

---

api/openapi-spec/swagger.json
pkg/virt-api/rest/definitions.go
staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
staging/src/kubevirt.io/client-go/api/v1/types.go
staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go

It is an oversight that the KubeVirt resource was never published.
Changing that.
Fixes #
```release-note
NONE
```

Add the KubeVirt resource to the published openapi spec

---

tests/reporter/kubernetes.go

Occasionally namespace objects deletion at test suite `AfterSuite` cleanup
fails and the object is stuck on `Terminating` phase, 
This behavior causes test suite to report error in AfterSuite and the prow-job to report failure
even if all tests passed, for example: sriov-lane jobs 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3806/pull-kubevirt-e2e-kind-1.17-sriov/1282212196058664964
This PR extends kuberentes custom reporter to dump namespace
objects for easier debugging.
Fixes # …

Add Namespaces logging to kuberentes reporter

---

pkg/ephemeral-disk/ephemeral-disk.go
pkg/virt-handler/container-disk/mount.go
tests/container_disk_test.go

Changing emphemeral disk perm to 640.
Changing container disk perm to 444.
Fixes #
```release-note
NONE
```

Tighten up perm on container/emphemeral disk.

---

hack/autobump-generic.sh
hack/autobump-kubevirtci.sh

The pr-creator binary is on one of the usual PATH locations.
Fixes #
```release-note
NONE
```

Look up the pr-creator binary the right way

---

pkg/monitoring/vms/prometheus/prometheus.go

Signed-off-by: arthursens <arthursens2005@gmail.com>
This PR was originally created to address a small NIT that wasn't tackled by #3636
But there is still value to keep that struct. So the metrics descriptors were transformed into local variables, but the VMI object, it's labels, the channel and the functions that update metrics' values are now strongly tied together.
Fixes #
See also: https://github.com/kubevirt/kubevirt/pull/3636#discussion_r455068264
```release-note
NONE
```

Update the vmiMetrics struct with better attributes

---

OWNERS_ALIASES
tests/OWNERS

Add test approvals from QE 
```release-note
NONE
```

Add test approvers

---

tests/migration_test.go

Some builds of the virt-launcher container don't include killall, but they have kill. This caused the functional test to fail. 
```release-note
NONE
```

Use 'kill' instead of 'killall' for notify connection resilience func test. 

---

tests/console_test.go
tests/imageupload_test.go
tests/infra_test.go
tests/operator_test.go
tests/pausing_test.go
tests/snapshot_test.go
tests/storage_test.go
tests/version_test.go
tests/vm_test.go
tests/vmi_cloudinit_test.go
tests/vmi_configuration_test.go
tests/vmi_gpu_test.go
tests/vmi_monitoring_test.go
tests/vmi_multiqueue_test.go

**What this PR does / why we need it**: `Add all the missing test-ids`
Fixes #
**Special notes for your reviewer**: `Add all the missing test-ids`
```
NONE
```

Add all the missing test-ids

---

OWNERS_ALIASES

I'd like to nominate myself as a approver of test PRs. I'd like to help
with refactoring of test tests utils and networking tests specifically.
These tests are partially outdated and most of them were not ever
restructured to reflect new features. That all makes it really hard to
add new tests.
Vote for Petr to keep your tests clean.
Fixes #
```release-note
NONE
```

tests: Add phoracek to approvers

---

tests/vmi_networking_test.go

In case the cluster is dual stack, 2 ips might exists.
Test each one of the existing ips on networking test 1780.
Use PingFromVMConsole new mechanism
instead of trace route, for simplification.
Depends on
```release-note
None
```

tests, vmi networking, make test 1780 dual stack compatible

---

Makefile

Due to removal of some of the steps in the travis build the functest
binary is not built implicitly any more. Add dependencies to Makefile
that build the required files.
Fixes https://travis-ci.org/github/kubevirt/kubevirt/builds/721267551#L1377
```release-note
NONE
```

Add required dependencies for functest image build

---

tests/vmi_configuration_test.go

Added tests to verify custom pciAddress slots and function, this enhances the check for supported range of pci addresses
Fixes #
```release-note
Added tests to verify custom pciAddress slots and function
```

Added tests to verify custom pciAddress slots and function

---

tests/vmi_configuration_test.go

This PR adapt the test `[test_id:4153]VMI with masquerade binding and guest agent should expose Pod IP as its public address` 
for dual-stack clusters
Fixes #
Rebased on top #3958 (1 commit)
```release-note
NONE
```

adapt tests for dual-stack cluster: [test_id:4153]VMI with masquerade binding and guest agent should expose Pod IP as its public address

---

tests/vmi_networking_test.go

As part of migrating the network tests to dual stack we need to check
that ICMP ping at masquerade between VMs is working with ipv4 and ipv6, since
TCP and ICMP are not the same thing and also we are already doing this test
for bridge binding mechanism.
Fixes #
```release-note
NONE
```

test, masquerade: Add dual stack vmi to vmi ping

---

tests/networkpolicy_test.go

Check ping from all existing ips, in order
to make sure network policy is working as expected
on dual stack clusters.
**Special notes for your reviewer:**
```release-note
None
```

tests, Make network policy tests dual stack compatible

---

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go

Allow updating the metadata and status sections of a VM object that is under rename process.
The same admit policy approach is also seen in VM snapshot admission control.
There are some cases when VM object metadata should be updated by the controller.
For example, create the API resource version labels on a new VM object.
Fixes #3974
```release-note
None
```

virt-api: introduce a more relaxed admission policy for a VM that is under rename process

---

tests/infra_test.go

The CriticalAddonsOnly taint and toleration is meant to be used by K8s
addons that can be scheduled on a compute node but are critical for the
proper functionality of the cluster. KubeVirt is one example for such
addon.
In the existing test, we used to taint every node that runs a kubevirt
component and our components can be scheduled on the master nodes we
might end up tainting masters. The problem with doing it is that some
core components might not tolerate this taint and we might end up with a
broken cluster which might not recover properly.
This patch limits the taint in the test to be set only on one compute
node. It should be enough for us to ensure that our components can
actually tolerate while not risking any core components. …

Limit CriticalAddonsOnly taint to a single compute

---

tests/ping.go
tests/vmi_networking_test.go

tests, net: Add dual-stack checks for post migration connectivity
---
tests, net: Remove post migration connectivity workaround
In order to overcome the arp table update (post the VMI migration)
issue, ingress traffic has been generated at the test.
Such a workaround is inappropriate as it does not reflect the actual
scenario and overcomplicates the test.
A proper solution should be embedded in the production code such that it
will lower the time it takes for the connectivity to recover.
This change drops the workaround and consequently increases the test time.
Fixes # …

tests, net: Post migration connectivity check with dual stack support.

---

pkg/virtctl/vnc/vnc.go

**What this PR does / why we need it**: Small cleanup that I found while reading the VNC code. Second try from [3978](https://github.com/kubevirt/kubevirt/pull/3978)
Fixes #
```release-note
NONE
```

Fixes for vnc

---

api/openapi-spec/swagger.json
staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
staging/src/kubevirt.io/client-go/api/v1/schema.go
staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go

I'm guessing 'insidejsondata' is a typo...

Fix ACPI doc string

---

tests/kubectl_test.go
tests/vnc_test.go

Add missing test ids
Fixes #
```release-note
NONE
```

Add missing test ids

---

tests/vmi_lifecycle_test.go

Signed-off-by: Ashley Schuett <ashleyns1992@gmail.com>
This test occasionally fails with
```Waited for 60 seconds on the event stream to match a specific event: event type Warning, reason = Stopped```
We should wait for the `vmi-killer` pod to be running before we wait for the VMI warning event of type stopped. In some cases the `vmi-killer` pod might take more time run which will then take time away from waiting for the VMI to produce a stopped event. 
If you take a look at the events you will see that there was an issue creating the `vmi-killer` pod, which then had to be killed and recreated. This made it so there wasn't enough time for the VMI to crash and produce the `Stopped` warning event. 
Failed test: …

wait for vmi-killer pod to start before moving on

---

manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-operator/creation/rbac/cluster.go
tests/access_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1871775
Fixes #
```release-note
Fixed bug preventing non-admin users from pausing/unpausing VMs
```

Pause permissions

---

tests/reporter/kubernetes.go

`kubectl get all --all-namespaces -o wide` gives a nice overview over
the current cluster-state which can be very valuable for test debugging.
Save it to `X_overview.log`. It looks similar to this snippet:
```
NAMESPACE     NAME                                           READY   STATUS    RESTARTS   AGE   IP               NODE     NOMINATED NODE   READINESS GATES
kubevirt      pod/virt-operator-5b57bdf9d4-lqn45             1/1     Running   0          15m   10.244.196.136   node01   <none>           <none>
kubevirt      pod/virt-operator-5b57bdf9d4-zwmjp             1/1     Running   0          15m   10.244.196.137   node01   <none>           <none>
[...]
NAMESPACE     NAME                                  TYPE        CLUSTER-IP       EXTERNAL-IP …
```

Add a nice cluster-overview to the collected test artifacts

---

hack/cluster-deploy.sh

cluster_dump can return a non-0 exit code. If it did so, it prevented
the script from exiting the wait loop for the kubevir-operator, leading
to endless waits.
Now we use pipefail and a trap to dump the cluster-state.
Fixes #
Here an example: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4292/pull-kubevirt-e2e-windows2016/1312060536942235648
```release-note
NONE
```

Properly exit if kubevirt does not get ready on cluster-sync

---

tests/migration_test.go

**What this PR does / why we need it**: `Add test_id for post-copy migration with Guest Agent Test`
Fixes #
**Special notes for your reviewer**:  `Add test_id for post-copy migration with Guest Agent Test`
```
NONE
```

Add test_id for post-copy migration with Guest Agent Test

---

BUILD.bazel

Exclude .git and _ci-configs at bazel's goimports
Fixes #
```release-note
NONE
```

Exclude .git and _ci-configs at bazel's goimports

---

docs/getting-started.md

Signed-off-by: Nelson Mimura Gonzalez <nelson@ibm.com>
Fix a few typos and propose some formatting changes.
Fixes #
```release-note
NONE
```

Fix typos and formatting

---

Makefile
hack/dockerized
hack/gosec.sh

Moves the junit file to correct directory. 
Fixes #
```release-note
"NONE"
```

Fix artifacts in gosec target

---

pkg/controller/virtinformers.go

Fix one of the gosec issue.
Fixes #
```release-note
NONE
```

Fix gosec issue: week random generator

---

pkg/virt-controller/watch/snapshot/snapshot.go
pkg/virt-controller/watch/snapshot/snapshot_test.go
tests/BUILD.bazel
tests/snapshot_test.go

Non-automated cherry-pick of https://github.com/kubevirt/kubevirt/pull/4374
Fixes #
```release-note
NONE
```

[release-0.34] Ignore VolumeSnapshot error status

---

hack/cluster-deploy.sh

Currently all sriov lane jobs are failing due to checking if CDI objects exists.
Since CDI operator is not deployed on sriov lane we should not check if any object that related to CDI exists.
This PR skips this check on sriov-lane.
Fixes #
```release-note
NONE
```

Fix SRIOV lane: cancel CDI insecure registries check on sriov lane

---

tests/infra_test.go
tests/libnet/ipaddress.go

Adapt tests in infra_test.go to check dual stack if exists using `DescribeTable`.
```release-note
None
```

tests, infra-test, Adapt infra_test to support dual stack

---

tests/pausing_test.go

In cc62349
I increased the time of the long process, because I noticed that
sometimes, the process ends before we manage to pause the vmi.
I forgot to increase the time we wait, to make sure the vmi was indeed
paused. that was the original intention of this commit.
Instead of that This commit removed the old test and suggested a new one,
that verifies the pausing success on the basis of the difference between
the uptime of the guest and the host, before and after the pausing.
By that we get the pausing verification without waiting and
sleep operations that slowers the test, and are prone to bugs.
Signed-off-by: alonSadan <asadan@redhat.com>
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …

tests, pausing_test: change long process test

---

tests/infra_test.go

Fix panic when endpoints were empty.
Give additional time for endpoints to be propagated.
Fixes #
```release-note
NONE
```

Fix panic when endpoints were empty.

---

tests/migration_test.go

Make sure the killer-pod has been deleted in order not to affect other tests.
In time frame between a deletion TS was added to
the killer pod and until it's actually has been deleted
we may have an inconsistent bahavior where the killer pod
keeps killing the virt-handler in the upcoming tests.
```release-note
None
```

tests: ensure the virt-handler killer pod has gone after deletion

---

pkg/config/config.go
pkg/controller/controller_ref_manager.go

Signed-off-by: zouyu <zouy.fnst@cn.fujitsu.com>
Fix comment typos
Fixes #
```release-note
NONE
```

Fix comment typos

---

tests/vm_test.go

This test only runs on OpenShift clusters (which is why CI is passing)
Real root cause of the problems surrounding this test is the use of service accounts instead of users. "add-role-to-user" is literal.
```release-note
NONE
```

Fix permissions tests for VMs

---

api/openapi-spec/swagger.json
pkg/virt-config/config-map.go
pkg/virt-config/virt-config.go
pkg/virt-controller/services/template.go
staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
staging/src/kubevirt.io/client-go/api/v1/types.go
staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go

Cherry-pick for #4415
Fixes #
```release-note
NONE
```

[release-0.34] Remove 'string' from json tag to preserve type information in our API

---

OWNERS_ALIASES

Add Igor Bezukh to test approvers

---

tests/infra_test.go

This is a manual cherry-pick of pull request #4426 
```release-note
None
```

[release-0.34] Infra test made invalid assumptions about cluster composition

---

docs/software-emulation.md
pkg/virt-config/BUILD.bazel
pkg/virt-config/config_test.go

Some issues with tests and documentation for the KubeVirt CR are addressed.
None.
None.
```release-note
NONE
```

virt-config fixes (tests and docs)

---

OWNERS_ALIASES

Add @enp0s3 to the approvers list
```release-note
NONE
```

Add enp0s3 to approvers list

---

pkg/ephemeral-disk-utils/utils.go
pkg/virt-operator/install-strategy/patches.go
pkg/virt-operator/util/config.go

Mark usages of weak cryptographic algorithms for hashing as false
positives for gosec.
Fixes #
```release-note
NONE
```

gosec - fix CWE 326

---

pkg/virt-operator/install-strategy/patches.go
pkg/virt-operator/util/config.go

Signed-off-by: Ezra Silvera <ezra@il.ibm.com>
Ignore false positive warnings on using sha1 for cryptographic 
Fixes #
```release-note
"NONE"
```

Fix gosec issu: weak sha1 cryptographic module

---

tests/probes_test.go

some of the dual stack tests test both IPv4 and IPv6 and iterate over
the IP addresses and act accordingly. A better way will be to
test each protocol separately.
This PR splits tests which tests both protocols, to separate tests, or
table entries.
Signed-off-by: alonSadan <asadan@redhat.com>
Fixes #
```release-note
NONE
```

tests, dual stack: split probes tests to test per IP-Family

---

tests/network/primary_pod_network.go

There is a race between guest agent connection check and VMIs IPs check since it could
happend that GA is connected but has not quick in yet, to overcome this this PR first
check the known IPv6 static address first to ensure that GA has started to report and then
it checks that VMI Status IPs contains VMI Status IP field.
Fixes #4570 
```release-note
NONE
```

 tests, primary_pod_network: Remove race condition at bridge binding GA test

---

go.mod
go.sum
manifests/testing/cdi-v1.26.1.yaml.in
staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
staging/src/kubevirt.io/client-go/go.mod
staging/src/kubevirt.io/client-go/go.sum
vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types_swagger_generated.go
vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/utils.go
vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
vendor/modules.txt

Bumps CDI to 1.26.1. This CDI contains a fix [1] that is needed for PR #4025 .
[1] https://github.com/kubevirt/containerized-data-importer/pull/1500
Fixes #
```release-note
NONE
```

Cdi bump 1.26.1

---

Makefile
hack/gosec.sh

This PR enable to run subset of test and therefore we can run blocking prow jobs on merging.(regarding gosec)
Fixes #
```release-note
NONE
```

Allow to run subset of rules for gosec

---

tests/vmi_multus_test.go

The SRIOV VMs are setting network configuration using cloud-init network
data, it takes some time to be set so sometimes it make ping fail since
IPs are not be set already, to fix that increasing ping dealdine should
be enough.
Fixes #
```release-note
NONE
```

Test sriov increase ping retries

---

api/api-rule-violations-known.list
api/api-rule-violations.list
api/openapi-spec/swagger.json
manifests/generated/kv-resource.yaml
pkg/virt-operator/creation/components/crds.go
pkg/virt-operator/creation/components/crds_test.go
pkg/virt-operator/creation/components/validations_generated.go
staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
staging/src/kubevirt.io/client-go/api/v1/types.go
staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
tests/infra_test.go
tests/kubectl_test.go
tests/operator_test.go

Enable validation on all kubevirt objects.
Fixes #
```release-note
KubeVirt is now explainable!
```

Explain Kubevirt

---

tests/console/login.go

The login prompt is sometimes ripped into parts by asynchronous daemon
status updates.
Instead of waiting three minutes for the login prompt to appear, restart
the login procedure after two minutes and wait for one minute. This has
the advantage that we re-send newlines, which helps working around
potentially broken login prompts after boot.
This fixes our current most flaky test (https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-12-02-168h.html#row1):
```
Configurations Check KVM CPUID advertisement [test_id:5271]test cpuid hidden
```
The login promt is sometimes corrupted due to asynchronous cloud-init updates.
An example from this log https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevi …

If the fedora login expecter is stuck, retry

---

ADOPTERS.md

Signed-off-by: Marcin Franczyk <marcin.franczyk@kubermatic.com>
This PR adds Kubermatic to adopters list.
Fixes #
```release-note
NONE
```

add Kubermatic to adopters list

---

tests/windows_test.go

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>
Fixes #
```release-note
NONE
```

windows_test: remove duplicate code

---

pkg/virt-launcher/virtwrap/manager_test.go
pkg/virt-launcher/virtwrap/network/common_test.go

Fixes #
```release-note
NONE
```

Cleanup tempfiles

---

pkg/certificates/bootstrap/cert-manager.go
pkg/certificates/triple/cert/cert.go
pkg/cloud-init/cloud-init.go
pkg/ephemeral-disk-utils/utils.go
pkg/util/net/ip/ip.go
pkg/virt-handler/cache/cache.go
pkg/virt-handler/container-disk/mount.go
pkg/virt-handler/device-manager/common.go
pkg/virt-handler/device-manager/mediated_device.go
pkg/virt-handler/selinux/labels.go
pkg/virt-handler/vm.go
pkg/virt-launcher/monitor.go
pkg/virt-launcher/virtwrap/api/converter.go
pkg/virt-launcher/virtwrap/util/libvirt_helper.go
pkg/virtctl/imageupload/imageupload.go
pkg/watchdog/watchdog.go

Signed-off-by: Ezra Silvera <ezra@il.ibm.com>
Analyze all cases of this static analysis warning and make sure a file injection attack is not possible or relevant 
Fixes #
```release-note
"NONE"
```

Fix gosec issue: Potential file inclusion via variable

---

OWNERS_ALIASES

Add [Miguel Duarte](https://github.com/maiqueb) as reviewer.
```release-note
NONE
```

Add @maiqueb to code-reviewers list

---

tests/vmi_lifecycle_test.go

We should not be manually changing the virt-handler daemonset, as once we introduce reconcile for this resource the test will break. Instead this PR changes to use the workload placement api to change the location of the virt-handler pods through the KubeVirt CR. 
Fixes #
```release-note
NONE
```

use placement api for assinging virt-handler pod

---

pkg/virt-launcher/virtwrap/api/converter.go

Refactor iface multi queue, network indexing and extract SRIOV hostdev creation.
Fixes #
```release-note
NONE
```

Launcher converter vm2domain refactor some network parts

---

hack/common.sh

Allows using GOFLAGS provided by the environment. This shall make it easier to customize the build.
```release-note
NONE
```

Don't overwrite user-provided GOFLAGS

---

pkg/virt-operator/install-strategy/create.go
pkg/virt-operator/install-strategy/create_test.go

This ensures kubevirt components and workloads are only scheduled on linux nodes
Signed-off-by: Kevin Wiesmueller <kwiesmul@redhat.com>
This should prevent kubevirt components and workloads from being scheduled on Windows nodes.
Fixes #3134 
I don't know if this is the right change. After some reading through the issue and the repo I found this way for handing in the nodeSelectors.
Explicitly for the virt-handler only the workload part would be required, but I think linux containers don't like window nodes in general, right?
One thing we might want to do is making this a default value as in the current setup virt-handler should never run on windows and it's better to have a sane …

add linux nodeSelector to kubevirt-cr

---

ADOPTERS.md

add Kubevirt as part of  CloudOS  in H3C

add H3C to the list of ADOPTERS 

---

tests/vmi_configuration_test.go

Fix test id for IO driver mode test

---

OWNERS_ALIASES

Eddy's has a big history of reviews in the project.
His reviews are very thorough and helpful.
Eddy also contributed high quality code to the project.
I propose him as a code reviewer.
Fixes #
```release-note
NONE
```

Reviewers update: Adding EdDev as a code reviewer

---

pkg/virt-handler/hotplug-disk/mount.go
tests/storage/hotplug.go

The cpu manager overwrites changes we make to the devices.list of running pods. If the timing is wrong this happens right before we want to attach the block device to a VM during hotplug. This PR checks if the volume is ready (and thus attached) and if not but the new device file exists, it ensures that devices.list allows the block device.
This will solve the remaining failures on block device tests. This PR also enables them, and removes the serial from the tests.
Fixes #
```release-note …
```

Ensure block devices are allowed, when the volume has not been attached to VM

---

docs/libvirt-pod-networking.md
docs/release.md

Signed-off-by: zouyu <zouy.fnst@cn.fujitsu.com>
Fix some typo in docs
Fixes #
```release-note
NONE
```

Fix some typo in docs

---

staging/src/kubevirt.io/client-go/api/v1/register.go

This is a fix for anyone who is consuming the kubevirt client-go package and encounters the "multiple group-version-kinds associated with type *v1.KubeVirt, refusing to guess at one" error when using the controller-runtime packages. 
Example. ```export KUBEVIRT_CLIENT_GO_SCHEME_REGISTRATION_VERSION=v1alpha3``` would cause only the v1alpha3 api to be registered when using our KubeVirt v1 client-go package.
The larger issue here is KubeVirt is not generating it's client go using the standard client-gen tooling, which is why we end up in odd scenarios like this. While this workaround with the env var should unblock us now that we have both v1 and v1alpha3 apis supported, our long term approach should be to transition to something that is compatible with client-gen. This will take some time …

ENV VAR for client-go scheme registration version

---

.travis.yml

mailing list discussion found at the link below
https://groups.google.com/g/kubevirt-dev/c/F-C1Bpfdhes
```release-note
None
```

Remove travis-ci logic for pushing to quay app registry

---

cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/certsecret.go

Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
Fix typos in log output.
Fixes #
```release-note
NONE
```

Fix typos in log output

---

WORKSPACE

Bump to latest bazeldnf with minor improvements.
Fixes #
```release-note
NONE
```

bump bazeldnf

---

tests/storage/hotplug.go

Add additional hotplug functional tests to satisfy test plans.
Fixes #
```release-note
NONE
```

Additional hotplug functional tests

---

tests/utils.go

Fix some issues in the tests/utils.go file.
NONE
```release-note
NONE
```

test/utils: fix some issues

---

pkg/container-disk/container-disk_test.go
pkg/virt-handler/device-manager/mediated_device_test.go
pkg/virt-handler/hotplug-disk/mount_test.go
pkg/virt-handler/vm_test.go
pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go
pkg/virt-launcher/virtwrap/network/common.go
tests/reporter/kubernetes.go
tests/restore_test.go
tests/vm_test.go
tests/vm_watch_test.go
tools/util/marshaller.go

Fixes #
```release-note
NONE
```

Fix ineffassign issues

---

OWNERS
OWNERS_ALIASES

Remove danielBelenky from reviewers. Also remove ci-approvers as there's noone that wouldn't be able to
approve otherwise.
Fixes #
```release-note
NONE
```

Remove danielBelenky from reviewers

---

ADOPTERS.md

Add NVIDIA as a KubeVirt ADOPTER

---

pkg/virt-controller/watch/migration.go
pkg/virt-handler/cache/cache_test.go
pkg/virt-handler/cmd-client/client_test.go
pkg/virt-handler/isolation/isolation_test.go
pkg/virt-handler/migration-proxy/migration-proxy_test.go
pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
pkg/virt-launcher/virtwrap/manager_test.go
pkg/virt-operator/creation/components/secrets_test.go
tests/config_test.go
tests/infra_test.go
tests/replicaset_test.go
tests/vmi_gpu_test.go
tests/vmipreset_test.go
tests/vnc_test.go
tools/vms-generator/utils/utils.go

Fixes #
```release-note
NONE
```

Fix ineffassign issues 

---

pkg/monitoring/vms/prometheus/prometheus.go
pkg/monitoring/vms/prometheus/prometheus_test.go

Adding os, workload and flavor to the kubevirt_vmi_phase_count
metric to provide some more information about the types of guest
machines that are running on the cluster.  The data is taken from the
vm.kubevirt.io/{os,workload,flavor} annotation on each VMI, if it
exists.
Fixes #
```release-note
Added os, workflow and flavor labels to the kubevirt_vmi_phase_count metric
```

Extend VMI count metric to include osinfo

---

pkg/virt-launcher/virtwrap/converter/BUILD.bazel
pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/converter_suite_test.go

Rename the suite test (from api to converter).
Cleanup unused functions and constants.
Fixes #
```release-note
NONE
```

Launcher converter cleanup

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

Livirt does not support disks with SATA and DedicatedIOThread. Currently VMs with such configurations are failing to boot with Libvirt error.
This PR will lead to the the user seeing Kubevirt error instead of Libvirt error.
PR Addresses the following Bugzilla ticket: https://bugzilla.redhat.com/show_bug.cgi?id=1911590
```release-note
NONE
```

[virt-launcher]: Issue an error for disk with DedicatedIOThread and SATA bus

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go

Removes some [technical debt](https://sonarcloud.io/component_measures?id=kubevirt_kubevirt&metric=sqale_index&selected=kubevirt_kubevirt%3Apkg%2Fvirt-api%2Fwebhooks%2Fvalidating-webhook%2Fadmitters%2Fvmi-create-admitter.go) by refactoring the vmi_create_admitter.go.
Fixes #
Outcome of refactoring looks like this: https://sonarcloud.io/dashboard?id=kubevirt_kubevirt&pullRequest=4935
```release-note
NONE
```

Refactor vmi create admitter

---

tests/network/services.go

At network service testing the timeout for jobs failing or not is 90
seconds and those jobs have three retries, in case the test is expected
to fail 4 differenct containers are going to be create/run/delete since
the job is going to retry it and this reaches the timeout limit (more
often at k8s >= 1.20).
Since on test that expect job to fail retries does not make sense this
change add a parameter to the job creatin function so we specify no
retries if job is expected to fail.
Fixes #4938
```release-note
NONE
```

Don't retry jobs that are expected to fail

---

automation/test.sh

make `bazel-build-images` happens 4 times, even if all the times
succeeded, wasting resources.
Fix it by stopping when it first managed to finish successfully.
```release-note
None
```

automation, Remove unneeded build repetitions

---

pkg/virt-handler/selinux/BUILD.bazel
pkg/virt-handler/selinux/context_executor.go
pkg/virt-launcher/virtwrap/network/BUILD.bazel
pkg/virt-launcher/virtwrap/network/common.go

Move the selinux context switch code that allows creating the tap device for the VM with the correct selinux context to a separate file.
Use some constants instead of arbitrary numbers, which will hopefully make the code clearer.
```release-note
NONE
```

Selinux exec context refactor

---

pkg/virt-controller/services/template.go

This PR attempts to make clearer the selinux context alignment code in the POD.
Please refer to https://github.com/kubernetes/kubernetes/issues/90759 for more information;
Fixes #
```release-note
NONE
```

Refactor pod selinux context alignment

---

tests/vmi_lifecycle_test.go

**What this PR does / why we need it**
This adds eventuallys to check for vmi status and schedulable nodes which will hopefully decrease the number of false negatives. 
Fixes #
Potentially a fix for 
- https://github.com/kubevirt/kubevirt/issues/4958 && https://github.com/kubevirt/kubevirt/issues/4715 
- adding an eventually and only get schedulable nodes for for test 1634. It seems that sometimes the master node is selected which is not schedulable by kubevirt which means it can not have a virt-handler and thus can not connect to a virt-handler on the selected node  
- ex. …

[flakey tests] add eventually to increase the robustness of vmi lifecycle tests 

---

docs/metrics.md
pkg/monitoring/vms/prometheus/prometheus.go

Moved common code to functions to ease the addition of new vmi metrics.
Fixes #
```release-note
None
```

Refactored vm monitoring code

---

tests/vmi_multus_test.go

Signed-off-by: Jakub Guzik <jakubmguzik@gmail.com>
PR refactors one of the helper functions in tests/ to return an error to test case. I fixed only one expect right now just to get feedback if everything looks good, or it should be done another way
Related to #4101
**Release note**
```release-note
NONE
```

tests: refactor expect in cidrToIP fcn in vmi_multus_test

---

pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/multus_annotations.go
pkg/virt-controller/services/multus_annotations_test.go
pkg/virt-controller/services/template.go

This PR attempts to increase the readability of the pod annotation generation.
Fixes #
```release-note
NONE
```

Refactor template pod annotations

---

hack/gosec.sh

make `make gosec` output slightly easier to find

---

docs/snapshot-restore.md

Minor updates to snapshot doc.
Fixes #
```release-note
NONE
```

Snapshot doc updates from QE review

---

pkg/cloud-init/cloud-init.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-handler/device-manager/deviceplugin/v1beta1/constants.go
pkg/virtctl/vm/vm_test.go

Fixes #
```release-note
NONE
```

pkg, cleanup: Remove unused constants

---

pkg/controller/controller_ref_manager_test.go
pkg/virt-api/webhooks/utils.go
pkg/virtctl/expose/expose.go

Fixes #
```release-note
NONE
```

pkg, cleanup: Remove unused global variables

---

tests/config_test.go
tests/infra_test.go
tests/migration_test.go
tests/reporter/kubernetes.go
tests/utils.go
tests/virt_control_plane_test.go
tests/vmi_gpu_test.go
tests/vmi_hostdev_test.go
tests/vmi_multus_test.go
tests/vmi_networking_test.go

- Rename (to _) unused parameters
- Remove unused functions
- Remove unused constants
- Remove redundant type in composite literal
- Remove redundant blank expression in for-loop
Fixes #
```release-note
NONE
```

tests, cleanup: Various cleanups on the e2e tests.

---

tests/reporter/kubernetes.go

Fix audit log path and as consequence, we now have audit logs again :)
```release-note
None
```
/cc @rmohr @fgimenez

Fix audit logs

---

pkg/config/sysprep.go

Signed-off-by: Tomas Psota <to.psota@gmail.com>
Reduces cognitive complexity of func CreateSysprepDisks and therefore fixes following sonarcloud issue: https://sonarcloud.io/project/issues?id=kubevirt_kubevirt&open=AXewXGpXmBrudGDaPwaN&resolved=false
Fixes #
```release-note
NONE
```

Reduce cognitive complexity

---

pkg/container-disk/container-disk.go
pkg/util/openapi/openapi.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-handler/cmd-client/client.go
pkg/virt-handler/vm.go
pkg/virt-operator/kubevirt_test.go
pkg/virt-operator/resource/apply/admissionregistration.go
pkg/virt-operator/resource/apply/apps_test.go
pkg/virt-operator/resource/apply/scc_test.go

Fixes #
```release-note
NONE
```

pkg, cleanup: Remove redundant blank expression in for-loop

---

pkg/hooks/manager_test.go
pkg/monitoring/vms/prometheus/prometheus_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-controller/watch/node_test.go
pkg/virt-controller/watch/snapshot/snapshot_base.go
pkg/virt-controller/watch/vmi_test.go
pkg/virt-launcher/notify-client/notify_test.go
pkg/virt-launcher/virtwrap/agent-poller/agent_parser_test.go
pkg/virt-launcher/virtwrap/api/schema_test.go
pkg/virt-launcher/virtwrap/cmd-server/server_test.go
pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/manager_test.go
pkg/virt-launcher/virtwrap/network/dhcp/dhcp_test.go
pkg/virt-launcher/virtwrap/network/network_test.go
pkg/virt-operator/resource/apply/apps_test.go
pkg/virt-operator/resource/apply/reconcile_test.go
pkg/virt-operator/resource/generate/components/crds.go
pkg/virtctl/vm/vm_test.go

Fixes #
```release-note
NONE
```

pkg, cleanup: Remove redundant type in composite literal

---

tests/datavolume_test.go
tests/migration_test.go

They fail very often on trusted code: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-03-15-168h.html
Fixes #
```release-note
NONE
```

Move tests 2731,3193,3194 into quarantine

---

tests/migration_test.go

The default VMsize of VMs is less than the VMsize used in the stress command introduced in some of the migration tests. So the stress command never successfully executes in those tests.
Signed-off-by: Shweta Padubidri <spadubid@redhat.com>
Fixes #
```release-note
None
```

Introduce a VMsize paramter in the runstress function to use custom values for different migration tests. 

---

pkg/virt-api/rest/subresource.go

Signed-off-by: Tomas Psota <tpsota@redhat.com>
It reduces the cognitive complexity of func generateVMVolumeRequestPatch  and therefore fixes following sonarcloud issue:
https://sonarcloud.io/project/issues?id=kubevirt_kubevirt&open=AXaytY2uEuOqpBE3N0lg&resolved=false&severities=CRITICAL&types=CODE_SMELL
Fixes #
```release-note
NONE
```

Refactor func generateVMVolumeRequestPatch 

---

docs/getting-started.md

Update incorrect doc

---

docs/devel/networking.md

Signed-off-by: Kavya <soldatargent@gmail.com>
**What this PR does / why we need it**: Fixes broken link to [user-guide](https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#masquerade-ipv4-and-ipv6-dual-stack-support) from `docs/devel/networking.md`.
Fixes #
```release-note
NONE
```

Fix broken URL link

---

pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

Add missing events to VMI object when hotplugging volumes.
Fixes #
```release-note
NONE
```

Add missing events to hotplug

---

hack/bazel-test.sh

Reducing the amount of retests for now until the tests are improved.
Fixes #
```release-note
NONE
```

Some unit tests appear to be more load sensitive than expected

---

pkg/virtctl/vm/vm.go

Fixes #5274
```release-note
None
```

Update VM and VMI in command line to make it more clear

---

tests/storage/imageupload.go

Removes quarantine label from test 4621. Issue https://github.com/kubevirt/kubevirt/issues/4527, was fixed by https://github.com/kubevirt/kubevirt/pull/5178. 
Did not see it happen since merging the fix.
Fixes #
```release-note
NONE
```

Lift quarantine from 4621

---

tests/BUILD.bazel
tests/network/BUILD.bazel
tests/network/probes.go

Following #5170 #5167 
Move network related probes tests to network package
Fixes #
```release-note
NONE
```

Move network probes tests to network package

---

pkg/virt-launcher/virtwrap/network/common.go
pkg/virt-launcher/virtwrap/network/network.go
pkg/virt-launcher/virtwrap/network/podinterface.go

drop dead code (left by a rebase of mine) and consolidate placement of related functions.
```release-note
NONE
```

network pacakge: minor cleanup

---

tests/storage_test.go
tests/vm_test.go

Removes quarantine label from tests 1015 and 4643
Did not see failure since merging the CIDR/Calico fixes to kubevirt.
Original issues where the tests were found as flaky:
https://github.com/kubevirt/kubevirt/issues/4961
https://github.com/kubevirt/kubevirt/issues/4939
Fixes #
```release-note
NONE
```

Removes quarantine label from tests 1015 4643

---

pkg/virt-operator/resource/apply/crds.go
pkg/virt-operator/resource/apply/crds_test.go

Reverts kubevirt/kubevirt#5310
This change causes CRDs to be updated on every pass since the kubernetes API creates them as "v1" but they are returned as v1beta1 and compared against a v1beta1. v1 has new defaulted fields which makes the `EnsureCustomResourceDefinitionV1Beta1` think that the existing object and the desired object are different. We should wait until https://github.com/kubevirt/kubevirt/pull/5017 is merged to fix this.

Revert "reconcile crd to desired state"

---

pkg/virt-handler/cmd-client/client.go
pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go

Reverts kubevirt/kubevirt#5322

Revert "virtwrap: fix unit test flakyness"

---

docs/sriov.md
tests/network/vmi_multus.go

Signed-off-by: alonsadan <asadan@redhat.com>
Issue #4642 has been resolved and no xfail failures seen since.
Removing the xfail.
Fixes #
```release-note
NONE
```

tests, sriov: remove xfail

---

go.mod
vendor/modules.txt

Running `make deps-update` on master branch has unexpected results.
The results are hereby pushed to allow future changes to reflect only the
expected changes.
```release-note
NONE
```

build: Update make-deps-update results

---

tests/storage/hotplug.go

**What this PR does / why we need it**: Adds `Hotplug Offline VM Should add volumes on an offline VM with DataVolume` to quarantine, it has been failing on the periodics for a week now, 5/14 failures during the last week https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-latest&width=20 and https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-prev&width=20
/cc @brybacki 
Fixes #
```release-note
NONE
```

Quarantine Hotplug test

---

pkg/virt-operator/resource/apply/apiservices.go
pkg/virt-operator/resource/apply/apps.go
pkg/virt-operator/resource/apply/crds.go
pkg/virt-operator/resource/apply/crds_test.go
pkg/virt-operator/resource/apply/prometheus.go
pkg/virt-operator/resource/apply/reconcile.go
pkg/virt-operator/resource/apply/reconcile_test.go

improve readability of creating a patch with labels/annotation and spec field since multiple resource need to create this patch. 
Fixes #
```release-note
NONE
```

pull out some duplicated code to improve readability

---

automation/test.sh

~~This version of kubevirtci has a newer version of rook/ceph baked right in!  Won't have to pull images when doing cluster-sync.~~
kubevirtci updated to sufficient level here https://github.com/kubevirt/kubevirt/pull/4907 so just updating automation test script
Fixes #
```release-note
NONE
```

update automation test script for new rook/ceph

---

docs/hotplug.md
pkg/virtctl/root.go
pkg/virtctl/vm/BUILD.bazel
pkg/virtctl/vm/vm.go
pkg/virtctl/vm/vm_test.go
tests/storage/BUILD.bazel
tests/storage/hotplug.go

This PR adds two new commands to virtctl:
- addvolume Adds the specified volume to the specified VMI
- removevolume Removes the specified from the specified VMI
Also adds documentation for hotplug.
Fixes #
```release-note
Support hotplug with virtctl using addvolume and removevolume commands
```

Support hotplug with virtctl

---

pkg/config/config_test.go
pkg/controller/controller_ref_manager_test.go
pkg/monitoring/vms/prometheus/prometheus.go
pkg/virt-api/rest/definitions.go
pkg/virt-config/config-map.go
pkg/virt-controller/services/template.go
pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
pkg/virt-controller/watch/drain/evacuation/evacuation.go
pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/node.go
pkg/virt-controller/watch/replicaset.go
pkg/virt-controller/watch/vm.go
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/workload-updater/workload-updater.go
pkg/virt-handler/cache/cache.go
pkg/virt-handler/device-manager/device_controller_test.go
pkg/virt-handler/device-manager/generic_device.go
pkg/virt-handler/device-manager/mediated_device.go
pkg/virt-handler/device-manager/pci_device.go
pkg/virt-handler/hotplug-disk/mount_test.go
pkg/virt-handler/notify-server/server.go
pkg/virt-handler/vm.go
pkg/virt-launcher/virtwrap/cmd-server/server.go
pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
pkg/virt-launcher/virtwrap/network/podinterface.go
pkg/virt-operator/kubevirt.go
pkg/virt-operator/resource/apply/reconcile_test.go

Fixes #
```release-note
NONE
```

pkg, cleanup: Rename (to _) unused parameters

---

tests/network/vmi_multus.go

This PR is adding a test to vmi_multus_tests to make sure the correct MTU is propagated to the vm interface in case there is no dhcp server running on the virt-launcher pod.
The test is especially important to verify that libvirt upgrade in PR https://github.com/kubevirt/kubevirt/pull/5147, which includes MTU bug fix, preserved the functionality of passing the MTU of unmanaged tap device to qemu. 
Fixes #
```release-note
NONE
```

network tests: test MTU on the secondary interface with no dhcp server

---

cmd/virt-chroot/tap-device-maker.go

The creation of the tap device has been observed failing randomly on CI
with the following error:
`Tuntap IOCTL TUNSETIFF failed [0], errno operation not permitted`
Investigation[1] revealed that a retry is enough to overcome the
failure.
The source of the problem seems to have been handled by BZ#1933627 [2]
and only appears on specific kernel versions.
(between kernel-4.18.0-215.el8 (included) and kernel-4.18.0-297.el8
(not included))
Therefore, a retry mechanism is applied on the tap device creation to
support these kernels (as we do not have control on which kernel
kubevirt is expected to run).
We should consider removing this workaround and add a warning on the
release notes to avoid these version in the future.
This should solve the immediate …

virt-chroot, tap: Retry the creation of the tap device

---

hack/dockerized
hack/prom-rule-ci/verify-rules.sh

Use builder image from quay.io …
Change PROM image to quay.io 
Fixes #
```release-note
NONE
```

Fix docker io pull limits

---

pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/converter_test.go

This PR fixes the `virtwrap/converter` code for hotplug PVCs and adds unit-tests. 
This PR supersedes https://github.com/kubevirt/kubevirt/pull/4753
```release-note
NONE
```

Fix hotplug pvc converter

---

pkg/virt-controller/watch/vm.go
tests/storage/datavolume.go
tests/utils.go

We didn't stop VM if the datavolumes were not ready.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1893790
```release-note
None
```

Fix stop of VM

---

OWNERS_ALIASES

I have been working with Kubevirt experts for a few months and authored several feature and bug PRs, and I would love to contribute to Kubevirt further with code-reviewing. 
Fixes #
```release-note
```

Request to be added into Kubevirt code-reviewers

---

pkg/virt-controller/watch/application.go

Fix verbosity for virt-controller

---

docs/quarantine.md

**What this PR does / why we need it**: It adds a description of the test quarantine procedure.
Fixes #
```release-note
NONE
```

Add Quarantine doc

---

automation/release.sh

Instead of checking whether the folder exists we just try to delete it
recursively while ignoring the errors instead, as we do only care to
delete it if it exists in order to remove previously created artifacts.
Fixes issues like these: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/push-release-kubevirt-tag/1384121154242875392#1:build-log.txt%3A1674
/cc @rmohr @davidvossel 
```release-note
NONE
```

Delete previous folder, ignore error if not exists

---

pkg/host-disk/host-disk.go

Refactor the function so its cognitive complexity
is reduced below 15 and corresponding sonarcloud
issue is fixed.
Signed-off-by: Tomas Psota <tpsota@redhat.com>
Fixes #
```release-note
NONE
```

Refactor func hostdisk.Create

---

tests/network/vmi_multus.go

After the VMI migration is over, the SR-IOV VF is hot-plugged into the
domain. The guest OS can name the new interface per its naming
convention, which at the moment is not persistent even between boots
(ethX).
Therefore, the interface name is re-queried (based on the expected mac
address) in order to correctly detect the right interface.
Note: Post migration, it is unclear if the VMI status is up to date with
the new Guest Agent data, therefore, the interface with the proper MAC
address check is added to the retry loop.
This issue has been seen infrequently when running the SR-IOV migration
tests on CI [1], specifically when the original interface name was
assigned as `eth0`.
[1] https://github.com/kubevirt/kubevirt/pull/5486
**Which issue(s) this …

tests, network, sriov: Post migration, learn interface name

---

pkg/virt-operator/kubevirt_test.go
pkg/virt-operator/resource/apply/core.go

Reconcile on all required labels/annotations. Refactor for readability. 
Fixes #
```release-note
Reconcile Secret resources 
```

refactor reconcile certificate secret

---

pkg/virt-operator/kubevirt_test.go
pkg/virt-operator/resource/apply/BUILD.bazel
pkg/virt-operator/resource/apply/apiservices.go

Reconcile APIService resources
Fixes #
```release-note
Reconcile APIService resources
```

Reconcile apiservice

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter_test.go
pkg/virt-controller/watch/snapshot/restore.go
pkg/virt-controller/watch/snapshot/snapshot.go
pkg/virt-controller/watch/snapshot/snapshot_test.go
tests/storage/restore.go
tests/storage/snapshot.go
tests/utils.go

Currently online snapshot of VM was prevented. This PR removed the restrictions and allows it.
Added and changed tests to check and support online vm snapshot.
Fixes #
Tested on multiple host and guest file systems. It does not support xfs as host FS.
```release-note
NONE
```

Snapshot online vm

---

pkg/virt-operator/resource/apply/core.go
pkg/virt-operator/resource/apply/core_test.go

This checks to see that KubeVirt manged ServiceAccounts have the labels and annotations that we expect and if they are not present we update the resource. 
Fixes #
```release-note
Reconcile ServiceAccount resources
```

reconcile ServiceAccount resources

---

tests/vmi_configuration_test.go

remove test_id: 1678 from quarantine
Fixes #
```
NONE
```

remove test_id: 1678 from quarantine

---

tests/job.go
tests/network/expose.go
tests/network/services.go

Issue https://github.com/kubevirt/kubevirt/issues/4428 is already closed
so as the TODO specifices the "if condition code" is removed.
Fixes #
```release-note
NONE
```

tests, jobs: cleanup of a netcat closed issue

---

pkg/virt-operator/resource/apply/core.go
pkg/virt-operator/resource/apply/reconcile.go

This PR is split into 3 parts by three commits. 
1. remove unused configmap reconcile code
2. reconcile on all labels/annotations that are required 
3. refactor code for readability 
Fixes #
```release-note
Reconcile required labels and annotations on ConfigMap resources 
```

Reconcile configmap

---

tests/vmi_configuration_test.go

test showed stability for the defined period of 14 days
```release-note
NONE
```

[tests] take test_id:5268 out of quarantine

---

automation/repeated_test.sh

Makes `pull-kubevirt-check-tests-for-flakes` test lane skip quarantined tests. 
Fixes #
FYI @oshoval 
```release-note
NONE
```

Skip quarantined tests

---

tests/operator_test.go

Add functional test for service resources. 
Fixes #
```release-note
NONE
```

add func test for service reconciliation

---

pkg/virt-operator/resource/generate/components/apiservices.go
pkg/virt-operator/resource/generate/components/crds.go
pkg/virt-operator/resource/generate/components/deployments.go
pkg/virt-operator/resource/generate/components/secrets.go
pkg/virt-operator/resource/generate/components/webhooks.go

Addressing [these SonarCloud issues](https://sonarcloud.io/project/issues?directories=pkg/virt-operator/resource/generate/components&id=kubevirt_kubevirt&open=AXaytZNNEuOqpBE3N0xT&resolved=false&rules=go:S1192&severities=CRITICAL&types=CODE_SMELL).
Clear SonarCloud issues
```release-note
NONE
```

[Sonar Cloud]: Add constants for duplicated strings

---

tests/operator_test.go

Adds functional tests for DS reconciliation. 
Fixes #
```release-note
NONE
```

add daemonset reconciliation functional test

---

tests/storage/hotplug.go

Fix identified code smells in sonar cloud.
Fixes #
```release-note
NONE
```

Fix duplicate strings in hotplug tests

---

tests/utils.go

1. Manipulating the kubevirt components directly is now deprecated. It is required to do so only via the Kubevirt CR
2. More accurate way to manage configuration propogation among the components was introduced by [this](https://github.com/kubevirt/kubevirt/blob/9e50a26bb721bb98e79210dc7583c6dd8d379fff/tests/utils.go#L4543) function
3. KV CR/CM is being modified when using `apply-default-configuration` flag and it's propagation to virt-components is being validated [here](https://github.com/kubevirt/kubevirt/blob/4785aff198092b888f8fec821e427bf98755d795/tests/utils.go#L735)
while the re-scaling occurs only when using `deploy-testing-infra` flag and in that case KV config doesn't change.
**Release …

[tests] remove redundant re-scaling of virt components upon setup/teardown stages

---

tests/BUILD.bazel
tests/storage/BUILD.bazel
tests/storage/datavolume.go
tests/vm_test.go

Continue the cleanup. Some storage tests where defined in VM/compute group. 
Fixes #
```release-note
NONE
```

Move sig-storage tests to storage subdir

---

pkg/util/webhooks/tls.go

Signed-off-by: Krzysztof Majcher <kmajcher@redhat.com>
This is just to remove some cosmetic code smell.
https://sonarcloud.io/project/issues?id=kubevirt_kubevirt&open=AXaytYwdEuOqpBE3N0jR&resolved=false&rules=go%3AS1192&severities=CRITICAL
```release-note
NONE
```

fixing code smell

---

cmd/example-cloudinit-hook-sidecar/cloudinit.go
cmd/example-hook-sidecar/smbios.go
pkg/virt-handler/vm_test.go
tools/vms-generator/utils/utils.go

Signed-off-by: Zou Yu <zouy.fnst@cn.fujitsu.com>
Fixes #
```release-note
NONE
```

Fix gofmt warning: redundant type from array, slice, or map composite literal

---

tests/migration_test.go

We're missing functional tests that explicitly test migration with huge pages. This PR validates that workflow: it creates a VMI that requests either 2M or 1G hugepages, then attempts a migration.
```release-note
NONE
```

Migration tests with huge pages

---

tests/migration_test.go

This focus was merged accidentally as part of this commit:
220bd65bfcf3102bc8b1daf6a0485f5384853bc1
```release-note
NONE
```

Stop focusing on test_id 4747

---

tests/vmi_lifecycle_test.go

With the previous way to hit API and do assertion against it might make the change of labels lost in between of the assertions; Switching to use event watch on node this way will make it more reliable
One of the failure: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5514/pull-kubevirt-e2e-k8s-1.19/1385290108260847616
Fixes the flake for `test_id:4716`
Fixes #
```release-note
NONE
```

Change the test to use the event watch for accurate assertion 

---

pkg/virt-handler/node-labeller/node_labeller.go
staging/src/kubevirt.io/client-go/api/v1/types.go
tests/infra_test.go

this is a backport of  https://github.com/kubevirt/kubevirt/pull/5606
Fixes #
```
add node-labeller.kubevirt.io/skip-node annotation 
```

[release-0.41] add special node-labeller annotations

---

tests/storage/datavolume.go

Tests 3189 and 5252 are stable for two weeks since the fix. Remove quarantine. 
Fixes #
This was originally fixed by: https://github.com/kubevirt/kubevirt/pull/5613
```release-note
NONE
```

Remove quarantine 3189

---

tests/utils.go

Tiny addition to include the label which has trouble picking up kubevirt updated configuration.
This should help the effort to take test 2666 out of quarantine (see PR https://github.com/kubevirt/kubevirt/pull/5669).
```release-note
NONE
```

Add information about which component can't pick up kubevirt config

---

tests/storage/restore.go

Signed-off-by: dalia-frank <dafrank@redhat.com>
Fixes #
```release-note
```

Update test ID

---

pkg/cloud-init/cloud-init_test.go
pkg/container-disk/container-disk_test.go
pkg/hooks/manager_test.go
pkg/ignition/ignition_test.go
pkg/virt-handler/migration-proxy/migration-proxy_test.go
pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
pkg/virt-launcher/virtwrap/manager_test.go

add err check for ioutil.TempDir

---

pkg/virt-launcher/virtwrap/network/podinterface.go
pkg/virt-launcher/virtwrap/network/podinterface_test.go

The pod interface name is available in the pod nic link structure, which is required for all bind mechanisms.
This PR drops the `podInterfaceName` member of the struct, and replaces all calls to rely on the member of the pod nic link struct, thus making the code a less error prone.
Fixes #
```release-note
NONE
```

Drop pod interface name from bind mech implementations

---

pkg/virt-api/api.go
pkg/virt-handler/selinux/context_executor_test.go

Fixes #
```release-note
NONE
```

Fix some misspell

---

hack/goveralls.sh
pkg/virt-launcher/virtwrap/manager_test.go

Adjusts the ignore list to cover generated files, ie `...generated.go` and `....pb.go`
Fixes #
```release-note
NONE
```

Improve coverage

---

tests/storage/BUILD.bazel
tests/storage/hotplug.go

Switch the VM OS to cirros instead of fedora to reduce resource usage.
Fixes #5667
```release-note
NONE
```

Cirros for hotplug tests

---

docs/direct-pv-disks.md

Signed-off-by: ansijain <ansi.jain@india.nec.com>
**What this PR does / why we need it**: Updated Incorrect URL
Fixes #
```release-note
NONE
```

Updated URL

---

tests/operator_test.go

Remove quarantined test
Fixes #
```release-note
NONE
```

Remove quarantined test

---

OWNERS_ALIASES

Since I think I tick all the boxes in https://github.com/kubevirt/community/blob/master/membership_policy.md#requirements-1 I'd like to join the reviewers list.
Fixes #
```release-note
NONE
```

Add acardace to reviewers list

---

pkg/network/cache/fake/infocache.go
pkg/network/cache/infocache.go
pkg/network/cache/types.go
pkg/network/cache/types_test.go
pkg/network/dhcp/configurator.go
pkg/network/dhcp/configurator_test.go
pkg/network/driver/common.go
pkg/network/driver/generated_mock_common.go
pkg/virt-launcher/virtwrap/network/podinterface.go
pkg/virt-launcher/virtwrap/network/podinterface_test.go

This PR refactors functions names and struct to use DHCP instead of dhcp, without changing any code logic
Fixes #
```release-note
NONE
```

network, Refactor dhcp refrences to DHCP

---

docs/monitoring-guidelines.md

This PR adds a guideline for alerts, to have a verbose message, since it is being used in the [metrics.md](https://github.com/kubevirt/kubevirt/blob/master/docs/metrics.md) automatically and adds the definition for alerts severity levels.
Fixes #
```release-note
NONE
```

Update alert rules guidelines

---

tests/vm_watch_test.go

A recent PR (#5675) has changed how the timeout is used in vm_watch_test.go when waiting for VM/VMI status to change.
This PR increases this timeout from 2 minutes to 5 minutes, to avoid flaky tests.
```release-note
NONE
```

Increase timeout in vm_watch_test

---

pkg/virt-operator/resource/generate/rbac/BUILD.bazel
pkg/virt-operator/resource/generate/rbac/operator_test.go
pkg/virt-operator/resource/generate/rbac/rbac_suite_test.go

Adds basic tests for:
- rbac generation for operator
Fixes #
```release-note
NONE
```

Improve code coverage

---

tests/storage/datavolume.go

Sometimes we test for before/after equality of size, and it seems
like OCS sometimes has a <10 byte differences in the way we
calculate space usage. Those are probably insignificant as we
don't even do sub-512 byte accesses for a VM.
Fixes some of the flakes in #5790.
Sometimes the import fails. This seems to be a different failure.
```release-note
NONE
```

Round image size to a multiple of 512 in the OCS case

---

pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go

manual backport of the primary fix and unit test for #5849
This backport focuses only on the segfault and targeted unit test and does not include the other unit test enhancements #5849 introduced.
```release-note
```

[release-0.41] fix pdb controller segfault

---

tests/storage/hotplug.go

Not all clusters will have enough local storage filesystem PVs available and the
test will fail because it can't allocate the appropriate PV. This checks if
we have the required PVs before attempting to run the test
Fixes #
```release-note
NONE
```

Verify enough local file system PVs before WFFC hotplug test.

---

.fossa.yml
Makefile
README.md
hack/fossa.sh

Updates the fossa analysis configuration file, adds the make target and script to run fossa analysis.
Also updates the FOSSA link in the README.md to point to the new FOSSA project.
Presubmit and postsubmit created with this PR: https://github.com/kubevirt/project-infra/pull/1262
Fixes #
```release-note
NONE
```

Update fossa config, add fossa make target

---

cmd/virt-handler/virt-handler.go
pkg/testutils/mock_config.go
pkg/virt-config/config-map.go
pkg/virt-config/config_test.go
pkg/virt-config/virt-config.go
pkg/virt-operator/resource/generate/components/daemonsets.go

Signed-off-by: Howard Zhang <howard.zhang@arm.com>
**What this PR does / why we need it**
add CPUArch in kubevirt config
```release-note
NONE
```

add CPUArch in kubevirt config

---

staging/src/kubevirt.io/client-go/kubecli/kubecli.go

Fixes #5964 
```release-note
NONE
```

make shallow copy of config parameter

---

pkg/monitoring/client/prometheus/prometheus.go

Expose the latency of the client-side rate-limiter.
Fixes #
```release-note
NONE
```

Wire the client side rate limiter metric

---

pkg/virt-handler/vm.go
pkg/virt-launcher/virtwrap/BUILD.bazel
pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/efi/BUILD.bazel
pkg/virt-launcher/virtwrap/efi/efi.go
pkg/virt-launcher/virtwrap/efi/efi_suite_test.go
pkg/virt-launcher/virtwrap/efi/efi_test.go
pkg/virt-launcher/virtwrap/manager.go
staging/src/kubevirt.io/client-go/api/v1/types.go

Follow-up PR to https://github.com/kubevirt/kubevirt/pull/5751.
Fixes #
```release-note
NONE
```

Refactor UEFI-mode without secureboot

---

OWNERS_ALIASES

* Update needed so I can use CNCF tools
* Pep is no longer assigned to project KubeVirt so I'm removing him as well

Update to OWNERS_ALIASES

---

tests/vmi_configuration_test.go

Manual backport of #5987
Fixes #
```release-note
NONE
```

[release-0.41] If the hostDisk feature gate is not enabled, skip tests

---

pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go
tests/storage/datavolume.go

We do not want to delete temporary pods that are not owned by the VMI.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1974289
```release-note
BugFix: Pending VMIs when creating concurrent bulk of VMs backed by WFFC DVs
```

Don't delete temp pods that aren't associated with VMI

---

pkg/virt-controller/services/template.go
tests/network/vmi_multus.go

These comments present on the code are misleading, since we have no interest in honoring them.
Let's be true to ourselves.
```release-note
NONE
```

Remove outdated comments

---

README.md

This PR adds the KubeVirt logo that is taken from the CNCF [1] website, similar to Kubernetes readme [2]. See [3] how it looks in the forked repository.
[1] https://cncf-branding.netlify.app/projects/kubevirt (Logos/Icon color)
[2] https://github.com/kubernetes/kubernetes#kubernetes-k8s
[3] https://github.com/benukhanov/kubevirt/tree/docs/readme-logo#kubevirt
Fixes #
Please let me know if you want to add the logo to the docs folder (I'll do it).
```release-note
NONE
```

Add kubevirt logo

---

tests/io_utils.go
tests/storage/events.go
tests/storage/storage.go

Depends on https://github.com/kubevirt/kubevirt/issues/5859
Fixes #
```release-note
None
```

Ioerror resume

---

rpm/BUILD.bazel

Add symlink for the ca-certificate for the libguestfs-tool container image
Fixes #6024
```release-note
NONE
```

Add symlink for the ca-certificates

---

README.md

As a new user, I see a big screenshot of the console in README.md. I had no idea that it's clickable to go to see the video of it. So, I added a new instruction that's important to a new reader.
Fixes #
```release-note
NONE
```

Add click example instruction

---

tests/virt_control_plane_test.go

Fixing leak of the test that affect [[test_id:2666]
](https://github.com/kubevirt/kubevirt/pull/6001). 
Fixes #
```release-note
NONE
```

Fix test: handler losing connectivity

---

pkg/virt-controller/watch/vm.go

Very small refactoring to avoid duplicating the code (15 line +-) 3 times.
```release-note
NONE
```

[virt-controller]: Small refactoring to avoid code duplication

---

docs/components.md

Fixes #
```release-note
NONE
```

Fix url in components doc

---

automation/assert-not-all-tests-skipped.sh
automation/test.sh

We look at the junit xml file to compare the number of tests
against the number of tests skipped and if the number of skipped tests
is not lesser then we fail.
This is to make visible situations like in this PR: #5835 
Fixes #
```release-note
Add check that not all tests have been skipped
```

Assert not all tests skipped
