tests/network/vmi_passt.go
Waiting of a VMI object readiness before it actually exists causes flakes.
There is no apparent reason to use a VM in this case. Directly using a VMI simplifies the test and avoids the detected flake.
Fixes #
```release-note
NONE
```
=> tests, network, vmi_passt: Create the VMI object directly

.golangci.yml, Makefile, tests/BUILD.bazel, tests/libnet/vmnetserver/BUILD.bazel, tests/libnet/vmnetserver/servers.go, tests/migration/BUILD.bazel, tests/migration/migration.go, tests/network/BUILD.bazel, tests/network/bindingplugin_passt.go, tests/network/networkpolicy.go, tests/network/port_forward.go, tests/network/probes.go, tests/network/services.go, tests/network/vmi_istio.go, tests/network/vmi_networking.go, tests/vmi_servers.go, tests/vmi_vsock_test.go
Move the helpers closer to its common users and maintainers.
Fixes #
```release-note
NONE
```
=> tests, network: Move `vmi_servers` to a new `network/vmnetserver` pkg

tests/network/hotplug.go
This is a backport from #10755 to reduce stable branch e2e test flakes.
Restarting the VM after the interfaces in the spec are gone is redundant. The VM will obviously be re-created based on the new spec.
Fixes #
```release-note
NONE
```
=> [release-1.0] tests, network, hot-unplug: Drop the VM restart step

tests/libnode/node.go, tests/utils.go, tests/vmi_configuration_test.go, tests/vmi_lifecycle_test.go
GetSupportedCPUFeatures is located in the tests/utils package
After this PR:
GetSupportedCPUFeatures is located in the tests/libnode package where it is more natural for it to be.
Fixes #
```release-note
NONE
```
=> tests/utils: Move GetSupportedCPUFeatures to libnode package

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
Cherry-pick of https://github.com/kubevirt/kubevirt/pull/11265
A cache is corrupted.
After this PR:
A cache is not corrupted ;)
Fixes #
This is a suboptimal patch to be able to backport this for the latest releases.
```release-note
Bug fix: VM controller doesn't corrupt its cache anymore
```
=> [release-1.0] vm controller copy fix

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
Cherry-pick of https://github.com/kubevirt/kubevirt/pull/11265
A cache is corrupted.
After this PR:
A cache is not corrupted ;)
Fixes #
This is a suboptimal patch to be able to backport this for the latest releases.
```release-note
Bug fix: VM controller doesn't corrupt its cache anymore
```
=> [release-1.1] vm controller copy fix

tests/storage/hotplug.go
`dvNames` was read/written concurrently, so it needs to be protected by a mutex or accessed safely (this PR does the latter), otherwise, data-races will occur.
Also prealloc `dvNames` and `testVolumes` to avoid reallocations.
Reported by the check-tests-for-flakes lane: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11205/pull-kubevirt-check-tests-for-flakes/1756981198619414528
```release-note
NONE
```
=> tests: fix datarace in hotplug test and make it faster

tests/utils.go, tests/vmi_configuration_test.go
Get rid of utils `NewRandomFedoraVMIWithBlacklistGuestAgent`
Use libvmi directly instead.
Fixes #
```release-note
None
```
=> e2e: Drop utils NewRandomFedoraVMIWithBlacklistGuestAgent

tests/swap_test.go
This PR removes closure functions from the swap tests file
Fixes #
**Checklist**
```release-note
NONE
```
=> test/swap: Refactor lambda functions to regular functions

pkg/controller/virtinformers.go, pkg/virt-controller/watch/clone/BUILD.bazel, pkg/virt-controller/watch/clone/clone.go, pkg/virt-controller/watch/clone/clone_base.go, pkg/virt-controller/watch/clone/clone_test.go, tests/clone_test.go
Once the target vm is deleted the vm clone can be
deleted since it is referring to a resource that cannot be
retrieved anymore.
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-30877
**Checklist**
```release-note
fix(vmclone): delete vmclone resource when the target vm is deleted
```
=> fix(vmclone) Delete vmclone resource when target vm is deleted

tests/storage/hotplug.go, tests/utils.go, tests/vmi_configuration_test.go
This PR moves out some functions that are being used only in one place from tests/utils to the file they are used at.
After this PR:
Fixes #
```release-note
NONE
```
=> tests: Move out some fns from tests/utils that used only in one place 

pkg/network/setup/netpod/netpod.go
Fix a typo!
We experienced an error that pointed to using ipv6 when it was disabled. When looking into [pull/10921](https://github.com/kubevirt/kubevirt/pull/10921), it seemed that did not fix it fully for us. Looking further in the code I found this typo which resulted in a desired pod network without issues.
After this PR:
The VM started as expected.
Fixes a typo.
=> BugFix ipv4/ipv6 typo.

tests/libvmi/network.go, tests/network/services.go
Refactor the e2e network services tests and helpers.
This is part of a bigger goal to cover all network tests by the linter.
Fixes #
```release-note
NONE
```
=> tests, network: Refactor services test

pkg/virt-api/webhooks/validating-webhook/admitters/migrationpolicy-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/migrationpolicy-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
Removing the client variable simplifies the code and prevents users from adding unauthorized API calls, which is not recommended in admission control. This change makes the code clearer and more secure.
After this PR:
Fixes #
```release-note
NONE
```
=> Remove client and config from migrationPolicy admitter

tests/vmi_lifecycle_test.go
The startup time on Arm64 platform is over 30 seconds, so set the startup timeout to 45 seconds
https://github.com/kubevirt/project-infra/issues/3262
cc: @dhiller @brianmcarey @xpivarc 
```release-note
NONE
```
=> tests, vmi_lifecycle: set the startup timeout

tests/vmi_cloudinit_test.go
The refactored tests used the deprecated `NewRandomVMIWithEphemeralDiskAndUserdata`.
After this PR:
The refactored tests use `libvmi`.
Fixes #
There is one last instance of `NewRandomVMIWithEphemeralDiskAndUserdata` left in this file that will be handled in a follow-up PR.
```release-note
NONE
```
=> E2E, CloudInitNoCloud: Refactor userdata and b64 userdata

tests/operator/operator.go
libvmi.New(libvmi.WithResourceMemory("1Mi")) is simpler and smaller, yet just as good for these tests that do not need a guest at all.
```release-note
NONE
```
=> tests/operator: Avoid usage of complex tests.NewRandomVMI

OWNERS, OWNERS_ALIASES, tests/OWNERS
sig-tests owned only the e2e tests.
After this PR:
unit tests are included under sig-tests ownership.
The approvers list was extended.
Fixes #
```release-note
None
```
=> sig-tests: Add approvers and include unit tests under sig-tests ownership

tests/swap_test.go
* Get rid or deprecated pointer package.
* Remove unused const.
* Remove named variables, most of the places even didnt use them.
* Add offset to expects.
* Refactor function to fail fast and not return a value in case of an error.
* Remove non required kubevirt configuration restoration 
(it is done already on global AfterEach).
Improve readability and maintainability.
```release-note
None
```
=> tests,swap: Cosmetics

tests/utils.go, tests/vmi_configuration_test.go
The tests/utils.go::listCgroupThreads function only used in one place.
This change move this function to the file that actually use it.
code cleanup
```release-note
None
```
=> Remove the listCgroupThreads func from utils

tests/vnc_test.go
`libvmi.New(libvmi.WithResourceMemory("1Mi"))` is simpler and smaller, yet just as good for tests that do not need a guest at all.
```release-note
NONE
```
=> vnc_test: avoid usage of complex tests.NewRandomVMI

hack/perfscale-tests.sh, tools/perfscale-load-generator/README.md, tools/perfscale-load-generator/flags/flags.go
A panic occurs in the periodic performance lanes as the v flag is redefined[1]. Update the perfscale-load-generator flag to verbose rather than v to avoid this clash
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-performance-cluster-100-density-test/1760162626240778240#1:build-log.txt%3A2082
Fixes #
/cc @alaypatel07 @rthallisey @dhiller @xpivarc 
```release-note
NONE
```
=> perfscale: Change v flag to verbose in load generator

hack/check-unassigned-tests.sh
check-unassigned-tests.sh uses deprecated flag `dryRun`.
```
You're using deprecated Ginkgo functionality:
=============================================
push_pin
--dryRun is deprecated, use --dry-run instead
Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed-command-line-flags
```
([source](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11234/pull-kubevirt-check-unassigned-tests/1759564442426675200#1:build-log.txt%3A331))
After this PR:
check-unassigned-tests.sh uses flag `dry-run`.
Fixes # …
=> kubevirt, check: update deprecated dryRun call

tests/vnc_test.go
Variables with a too-wide scope may have unexpected side-effects, particularly when multiple lambda closures are defined and used.
Let us define an err variable closer to its needed context.
Requested by @xpivarc on https://github.com/kubevirt/kubevirt/pull/11302#discussion_r1500332243
```release-note
NONE
```
=> vnc_test: place err variable more locally

api/openapi-spec/swagger.json, pkg/controller/controller.go, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/migration_test.go, pkg/virt-controller/watch/vmi.go, pkg/virt-handler/vm.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/libmigration/migration.go, tests/migration/migration.go
Migration state has no source pod and no failure reason
After this PR:
Migration state has a source pod and a failure reason
Fixes #
```release-note
More information in the migration state of VMI / migration objects
```
=> migration state: add source pod and failure reason

tests/BUILD.bazel, tests/mdev_configuration_allocation_test.go, tests/migration/migration.go, tests/monitoring/vm_monitoring.go, tests/portforward_test.go, tests/storage/restore.go, tests/storage/snapshot.go, tests/subresource_api_test.go, tests/swap_test.go, tests/utils.go, tests/vm_state_test.go, tests/vmi_configuration_test.go, tests/vmi_headless_test.go, tests/vmi_hostdev_test.go, tests/vmi_multiqueue_test.go, tests/vmi_tpm_test.go, tests/vmi_vsock_test.go
Use libvmi and libnet directly instead `NewRandomFedoraVMI`
```release-note
None
```
=> e2e: Use libvmi and libnet directly instead NewRandomFedoraVMI

pkg/network/dhcp/server/server.go, pkg/virt-api/rest/subresource.go
Simplifying the routine of adding elements to a list.
Fixes #
```release-note
NONE
```
=> refectory: simplifying the routine of adding elements to a list

pkg/virt-handler/heartbeat/ksm.go, pkg/virt-handler/heartbeat/ksm_test.go, staging/src/kubevirt.io/api/core/v1/types.go
Currently, KubeVirt adds the `kubevirt.io/ksm-enabled` label to those nodes that match the labelSelector defined in kvConfiguration. The value of that label will be true only if that node is under pressure, false otherwise.
After this PR:
This is wrong since we need to provide users the information that a particular node is configured to use ksm, so that it can be used to schedule vms there.
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-38568
```release-note
fix(ksm): set the …
```
=> fix(ksm): set ksm-enabled label to true independently from node pressure

pkg/virt-handler/heartbeat/ksm.go, pkg/virt-handler/heartbeat/ksm_test.go, staging/src/kubevirt.io/api/core/v1/types.go
This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/11306
Fixes #
Conflict on `ksm.go` file:
- `ksm, err := calculateNewRunSleepAndPages(enabled)` vs `ksm, err := calculateNewRunSleepAndPages(node, enabled)`
```release-note
fix(ksm): set the `kubevirt.io/ksm-enabled` node label to true if the ksm is managed by KubeVirt, instead of reflect the actual ksm value.
```
/cc @Barakmor1 @jean-edouard
=> [release-1.2] fix(ksm): set ksm-enabled label to true independently from node pressure

pkg/virt-launcher/virtwrap/live-migration-source.go
bytes to Mbps conversion is wrong.
After this PR:
bytes to Mbps conversion is correct.
```release-note
NONE
```
=> live-migration: fix bytes to Mbps conversion in log

pkg/virt-api/api.go
Currently the APIResourceList reports an invalid v1alpha3 apiVersion. This is not standard compliant and causes issues with kube-rs operators.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: fixes #10899
Fixes #
**Checklist**
```release-note
BugFix: Fixed incorrect APIVersion of APIResourceList
```
=> Fixed incorrect APIVersion in APIResourceList

tests/storage/snapshot.go
Instead of returning true/false if something
is as expected we should use matchers that
will give explanations of why something
is not as expected.
Improve debug info in case of failures
Fixes #
-
```release-note
None
```
=> Tests: Use matchers to get better info in case of failures

pkg/storage/types/dv.go, pkg/storage/types/pvc.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
Currently DataVolume ownership is not preserved under certain DR/Restore scenarios.  This is because PVCs are typically created very early in the failover/restore process and until recently [1] CDI did not allow "adopting" existing volumes.  So let's make sure that we always request that volumes are adoptable.  We also have to make sure that we don't attempt to adopt previously garbage collected DVs.  To help CDI added this PR [2]
If volumes are not adopted, they will not be owned by the VM and therefore will not be deleted when the VM is deleted (or relocated back to primary cluster in DR scenario).  Because of this, this PR should be considered a bug fix not a feature.  DR is currently broken.
[1] https://github.com/kubevirt/containerized-data-importer/pull/3029
[2] …
=> Add annotation to DataVolumeTemplates to better handle DR/Restore

pkg/controller/controller.go, pkg/storage/types/dv.go, pkg/storage/types/pvc.go, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, pkg/virt-controller/watch/workload-updater/workload-updater.go
Removes the usage of Informers in the VM controller as what we really need is `cache.Store` or `cache.Indexer`. 
Fixes #
The last commit mentions the simplification of unit tests. The problem is that we are using informers in the tests even when we most likely don't need them. This creates a problem because the `framework.FakeControllerSource` is not reflecting the changes synchronously. Meaning, an `.Add` will not be reflected in the underlying `cache.Store` right away and we always need to assert the existence if we don't want flaky behavior. Converting the controller to use `cache.Store` allows us to also switch the unit tests to directly use the store, removing the need for synchronization.
Note: We can also directly use the `cache.Store` of the informers today.
```release-note
NONE …
```
=> Vm controller remove Informers 

pkg/virt-controller/watch/vm.go
`cleanupRestartRequired` and `addRestartRequiredIfNeeded` don't require a Copy anymore.
Fixes #
This is being redundant since https://github.com/kubevirt/kubevirt/pull/11265
```release-note
NONE
```
=> VM: Remove redundant DeepCopy - cleanupRestartRequired & addRestartRequiredIfNeeded

pkg/virt-controller/watch/vm.go
A failed update returns a nil for the VM. This
commit fixes a potential panic.
Fixes #10811
```release-note
Bug-fix: Fix nil panic if VM update fails
```
=> virt-controller: fix panic when VM udate fails

pkg/storage/snapshot/snapshot.go, pkg/storage/snapshot/snapshot_test.go, tests/storage/snapshot.go
When trying to take VM snapshot of a VM, when one of the disk volumes is in Terminating
state, if one try to take a snapshot in this state, the process will "silienty" fails on timeout with 
"snapshot deadline exceeded" 
This PR changes the phase to be "Errored" with conditions and error explaining the issue
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-35452
**Checklist**
```release-note …
```
=> Update vmsnapshot error phase in case of volumesnapshot errors which prevent the snapshot from being ready

tests/utils.go, tests/vmi_configuration_test.go
The tests/utils.go:GetProcessName function only used in one place.
This change move this function to the file that actually use it.
code cleanup
```release-note
None
```
=> Move GetProcessName from util

tests/libvmi/factory.go
`libvmi.NewGuestless` would be useful by many tests that just want to define a VMI, but do not care about running a guest operating system inside it. The memory of such VMI can be much smaller (and thus, less demanding on our CI).
This has been discussed in https://github.com/kubevirt/kubevirt/pull/11366
I propose it here to allow quicker review by @EdDev .
sig code-quality
```release-note
NONE
```
=> libvmi: introduce NewGuestless

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
Removes redundant `DeepCopy` calls because we now have https://github.com/kubevirt/kubevirt/pull/11265 
Fixes #
```release-note
NONE
```
=> Remove redundant DeepCopy calls

tests/vnc_test.go
The VNC screenshot test fails on ARM64[1] as the VMI fails to start due to
not enough memory being available. The NewGuestless function that was
recently introduced into libvmi creates a guestless VMI that caters
for the increased memory requirement of ARM64[2].
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11400/pull-kubevirt-e2e-arm64/1764549347174780928
[2] https://github.com/kubevirt/kubevirt/blob/0ca03aa05ccab5fefc6bfe7b474e5e05e18929a4/tests/libvmi/factory.go#L96C1-L101C3
Fixes # …
=> e2e,vnc: Use NewGuestless function to create VMIs as it can handle the larger arm64 memory requirement

tests/libvmi/factory.go, tests/vm_test.go
The tests that are affected by the modified `BeforeEach` do not make use of the guest. They can run just as well with much less memory.
```release-note
NONE
```
=> vm_test: use a simpler smaller VMI

automation/test.sh
The previous git check would lead to a large diff if the contributor's fork falls behind kubevirt main[1].
Using the diff based off a common ancestor of both commits[2], returns the
diff for the pull request.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11286/pull-kubevirt-e2e-k8s-1.29-sig-compute-migrations/1762051220236668928#1:build-log.txt%3A33
[2] https://git-scm.com/docs/git-diff#Documentation/git-diff.txt-emgitdiffemltoptionsgtltcommitgtltcommitgt--ltpathgt82308203-1
Fixes #
/cc @dhiller @oshoval @fabiand 
Approvers are …
=> e2e: Update skip docs check to get just PR diff

cmd/virtctl/OWNERS, pkg/handler-launcher-com/OWNERS, pkg/virt-handler/OWNERS, pkg/virtctl/OWNERS, tests/libvmi/OWNERS
Before this PR: OWNERS files without label based sig or area assignment existed.
After this PR: All OWNERS files have label based sig or area assignments, this helps to make sure that this ownership is bubbling up into labels during PR reviews.
Fixes #
The following tradeoffs were made: N/A
The following alternatives were considered: N/A
None
```release-note
NONE
```
=> OWNERS: Add sig/ or area/ to every OWNERS file which was missing it.

tests/dryrun_test.go, tests/libvmi/selector.go, tests/migration/BUILD.bazel, tests/migration/eviction_strategy.go, tests/migration/migration.go
=> Stop using the deprecated NewRandomVMIWithEphemeralDisk function in several files

tests/monitoring/component_monitoring.go
After this PR:
Fixes #
```release-note
NONE
```
=> component_monitoring.go: Remove use of NewRandomVMI func

OWNERS_ALIASES, pkg/handler-launcher-com/OWNERS, pkg/virt-handler/OWNERS
Before this PR: We had more but empty and unusued sigs
After this PR: We have less - but used and staffed - sigs
The following tradeoffs were made: Keep the current lis of sigs, but this would require staffing and defining ownership, which is tricky, thus we realign on sig-compute for now
The following alternatives were considered: Keep sigs, but this would require more work to define ownership and update code, htis is too much work that we do not want right now
Links to places where the discussion took place: i.e. https://groups.google.com/g/kubevirt-dev/c/dXvwU6Pon7Y
The decision about sig-node and sig-cluster/scheduling can take place separataely, but should not block this PR.
This PR reflects reality.
This checklist is not enforcing, but it's a reminder of items that could be relevant …
=> Cleanup owner aliases

tests/monitoring/vm_monitoring.go
In `tests/monitoring/vm_monitoring.go`, use libvmi instead of `NewRandomVMI()` which was deprecated.
```release-note
None
```
=> Remove use of NewRandomVMI in vm_monitoring.go

tests/monitoring/component_monitoring.go
`VirtControllerRESTErrorsBurst` and `VirtControllerRESTErrorsHigh` alerts e2e test is failing, probably due to leftovers from other test cases. This PR puts the testcase on `PIT`, until we investigate it further, in order to release the monitoring lane.
Fixes https://issues.redhat.com/browse/CNV-38827
```release-note
None
```
=> tests: PIT flaky component monitoring test

tests/migration/migration.go
After this PR:
Fixes #
```release-note
NONE
```
=> migration.go: Remove use of NewRandomVMI func

pkg/virt-handler/rest/lifecycle.go, tests/storage/snapshot.go
This is a manual backport of https://github.com/kubevirt/kubevirt/pull/11051. I'm adding the quarantined test for consistency, but feel free to argue otherwise.
Fixes # https://issues.redhat.com/browse/CNV-32664
```release-note
Bugfix: Improve error reporting when fsfreeze fails
```
=> [release-1.2] Manual backport of improve error reporting when fsfreeze fails

pkg/virtctl/create/vm/vm.go, pkg/virtctl/create/vm/vm_test.go
This adds the GCS volume source to the --volume-import flag of virtctl
create vm, which allows to import a volume from GCS when creating a VM.
Cannot import volumes from GCS storage
After this PR:
Can import volumes from GCS storage
Fixes #
-
Merger after #11144 and #11148
```release-note
virtctl: It is possible to import volumes from GCS when creating a VM now
```
=> virtctl: Allow importing from GCS when creating VM

hack/bump-common-instancetypes.sh
/cc 0xFelix
`bump-common-instancetypes` would sync `kubevirt` with the latest release of `common-instancetypes`.
After this PR:
`bump-common-instancetypes` continues to sync `kubevirt` with the latest release of `common-instancetypes` by default but can also sync with a stable branch if one is provided as an argument.
Partial Fix# https://github.com/kubevirt/common-instancetypes/issues/162
```release-note
NONE
```
=> bump-common-instancetypes: Add support for stable branch releases

OWNERS_ALIASES
I a top-level approver, but not assigned to any SIGs.
After this PR:
I am assigned as a sig-compute approver.
This is part of the process to refine SIGs and ownerships in Kubevirt.
Related to https://github.com/kubevirt/kubevirt/pull/11046 and https://github.com/kubevirt/kubevirt/pull/11355.
Also see below links for reference.
- https://groups.google.com/g/kubevirt-dev/c/-5TLpOcRkco
- https://groups.google.com/g/kubevirt-dev/c/dXvwU6Pon7Y
- ~[ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not …
=> Nominate myself as a sig-compute approver

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
This is a manual backport of https://github.com/kubevirt/kubevirt/pull/11038
Fixes #
```release-note
NONE
```
/cc @xpivarc
=> [release-1.1] vmi update admission webhook: fix volume miscount when using filesystems

pkg/virtctl/vmexport/vmexport.go, pkg/virtctl/vmexport/vmexport_test.go, tests/storage/export.go
The `virtctl vmexport download` command always deleted the vmexport resources after exiting. This behavior wasn't ideal since we could be potentially deleting resources created in advance. This behavior could be improved.
Now the command will delete vmexport resources by default when the `download` command creates them itself. However, the resources will be retained if they were created in advance.
A new, `--delete-vme` flag has been included to allow deleting the vmexport everytime the download exits. `--keep-vme` does the opposite, so we can retain the vmexport resource even when the command creates it. 
Fixes # https://github.com/kubevirt/kubevirt/issues/11080
Following several offline conversations we decided this was the best approach to handle …
=> Improve default handling of export resources in virtctl vmexport

pkg/virt-config/deprecation/feature-gates.go, pkg/virt-config/deprecation/macvtap.go, pkg/virt-config/deprecation/passt.go, pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go
/cc ormergi
The warning message emitted when each deprecated feature gate is enabled made no reference to the underlying state of the feature and may be confusing to the reader. For example, the `LiveMigration` feature gate is deprecated but the feature itself is GA.
After this PR:
The feature state is now included within the warning message message.
Fixes #
```release-note
NONE
```
=> feature-gates: cleanup deprecation warning message

tests/config_test.go, tests/libpod/BUILD.bazel, tests/libpod/query.go, tests/migration/eviction_strategy.go, tests/migration/migration.go, tests/monitoring/BUILD.bazel, tests/monitoring/vm_monitoring.go, tests/network/port_forward.go, tests/network/primary_pod_network.go, tests/network/sriov.go, tests/network/vmi_multus.go, tests/network/vmi_networking.go, tests/network/vmi_slirp_interface.go, tests/operator/operator.go, tests/realtime/BUILD.bazel, tests/realtime/realtime.go, tests/security_features_test.go, tests/storage/datavolume.go, tests/storage/storage.go, tests/utils.go, tests/virtiofs/config.go, tests/virtiofs/datavolume.go, tests/vm_test.go, tests/vmi_cloudinit_test.go, tests/vmi_configuration_test.go, tests/vmi_kernel_boot_test.go, tests/vmi_lifecycle_test.go, tests/windows_test.go
`GetRunningPodByVirtualMachineInstance` is a redundant wrapper that can be dropped in favor of `libpod.GetPodByVirtualMachineInstance`.
Fixes #
```release-note
NONE
```
=> tests, utils: Drop GetRunningPodByVirtualMachineInstance

pkg/cloud-init/cloud-init_test.go, pkg/emptydisk/emptydisk_test.go, pkg/virt-api/rest/subresource_test.go, pkg/virt-controller/watch/vm_test.go, tests/hotplug/affinity.go
`fmt.Println` was used during various tests to dump state to stdout making the actual test output cluttered and hard to read.
After this PR:
Use of `fmt.Println` removed from various tests where it makes sense.
Fixes #
```release-note
NONE
```
=> chore: Remove use of fmt.Println from tests

pkg/storage/export/export/export_test.go
Fix export_test:
1) Chenge reactor functions return nil obj with AlreadyExists err 
2) The parameters for errors.NewAlreadyExists should be an obj name
Fixes #
I think there may be an issue with the parameters passed into the NewAlreadyExists method in the export test.
```
return true, secret, errors.NewAlreadyExists(schema.GroupResource{}, "already exists")
```
"already exists" should be an obj name.
As well as, Reactor functions should return nil on the returned value when the returned error is not nil.
We have problems in clone_test too.
**Checklist**
This …
=> (Fix export_test): change reactor functions which return AlreadyExists err

tests/libvmi/vmi.go, tests/testsuite/fixture.go, tests/vmipreset_test.go
This PR adds an annotation to VMIs created by libvmi with the name of the current test (if available).
This will help identify which test created any rogue VMI.
Fixes #
**Checklist**
```release-note
NONE
```
=> e2e tests: libvmi: add annotation with test name to new VMIs

pkg/virt-controller/network/BUILD.bazel, pkg/virt-controller/network/network_suite_test.go
The current unit tests of `pkg/virt-controller/network` were not running
because this file was missing (injected an error and saw that).
Fixes #
```release-note
None
```
=> unit tests, network: Add missing virt-controller/network suite file

tests/network/vmi_istio.go
Istio tests skipped migration tests in case of passt.
After this PR:
Istio tests test passt migration.
Fixes #
```release-note
None
```
=> tests: passt supports migration, update istio tests

pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-operator/resource/generate/components/BUILD.bazel, pkg/virt-operator/resource/generate/components/daemonsets.go
`"k8s.v1.cni.cncf.io/networks"` belongs to and already defined in existing package:
`network-attachment-definition-client`.
Use it from that one instead adding our const / hardcoded values.
Fixes #
```release-note
None
```
=> annotations: Remove unneeded const

pkg/instancetype/instancetype.go, pkg/storage/types/dv.go, pkg/virt-controller/services/nodeselectorrenderer.go, pkg/virt-controller/services/template.go, pkg/virt-controller/watch/pool.go, pkg/virt-controller/watch/pool_test.go, pkg/virt-controller/watch/vm.go
In this PR I'm starting to use new Go's `maps` package that's presented in Go 1.21.
This package leverages generics in order to provide official functions to clone, copy, delete and check equality, and more.
We manually copy and clone maps with code that is duplicated throughout the repo.
After this PR:
Duplicated private functions are deleted and official functions from the `maps` package are being used.
- ~[ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required~
- ~[ ] Upgrade: Impact of this change on upgrade flows was considered and …
=> [code-clean] Use Go 1.21 `maps` package to clone and copy maps

tests/hyperv_test.go, tests/kubectl_test.go, tests/storage/snapshot.go, tests/utils.go, tests/vmi_configuration_test.go
The function `GetPodByVirtualMachineInstance` in `tests/utils.go` was used to get pods using labels. 
After this PR:
- Drop `GetPodByVirtualMachineInstance`  and `getPodsByLabel `from `utils.go`.
- Instead used `libpod.GetPodByVirtualMachineInstance` for its callers
Fixes #11440
```release-note
NONE
```
=>  refactor: drop GetPodByVirtualMachineInstance,getPodsByLabel . Use `libpod.GetPodByVirtualMachineInstance` instead at all its callers.

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
A VM with memory limits set could not hotplug memory.
After this PR:
A VM with memory limits set can hotplug memory.
```release-note
Allow to hotplug memory for VMs with memory limits set
```
=> Allow to set memory limits when doing memory hotplug 

pkg/downwardmetrics/virtio-serial/server.go
The number of requests per second is set to 5, which causes an excessive resources consumption by the virt-handler if many VMs are running on the cluster and requesting the metrics.
After this PR:
It reduces the number of requests per second that can be addressed to the downwardMetrics server to 1 to reduce the virt-handler resource consumption.
Fixes # [CNV-38661](https://issues.redhat.com/browse/CNV-38661)
```release-note
Reduce the downwardMetrics server maximum number of request per second to 1.
```
=> chore(fix): Reduces the downwardMetrics rate limit

api/openapi-spec/swagger.json, manifests/generated/kv-resource.yaml, pkg/virt-config/configuration.go, pkg/virt-config/configuration_test.go, pkg/virt-config/virt-config.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go
`spec.config.emulatedMachines` and `spec.config.ovmfPath` got obsoleted by https://github.com/kubevirt/kubevirt/pull/8293 but they still exist and should therefore be honored if set to not break compatibility.
The fields are now also marked as deprecated so that they can be removed in the future.
Setting `spec.config.emulatedMachines` and `spec.config.ovmfPath` doesn't work.
After this PR:
Setting `spec.config.emulatedMachines` and `spec.config.ovmfPath` works.
```release-note
NONE
```
=> Fix and deprecate `emulatedMachines` and `ovmfPath`

tests/network/BUILD.bazel, tests/network/vmi_slirp_interface.go
Remove most of the SLIRP e2e tests and leave a single one running.
As a follow up, two changes should be considered:
- Use directly the binding plugin API instead of the core API.
- Check real connectivity and not just the configuration (e.g. use a job
that sends HTTP req to the VM).
Fixes #
```release-note
NONE
```
=> tests, net, slirp: Remove most of the slirp tests

tests/libstorage/datavolume.go, tests/migration/migration.go, tests/storage/datavolume.go, tests/storage/export.go, tests/storage/hotplug.go, tests/storage/imageupload.go, tests/storage/restore.go, tests/storage/storage.go, tests/utils.go
`tests/utils.go` file contains several utility functions that can be considered duplicated.
This is because the same result can be achieved with the already present libvmi/etc options.
After this PR:
This PR aims to drop the `NewRandomVMIWithDataVolume` wrapper function,
replacing its occurrences with:
```
vmi := libvmi.New(
libvmi.WithInterface(libvmi.InterfaceDeviceWithMasqueradeBinding()),
libvmi.WithNetwork(v1.DefaultPodNetwork()),
libvmi.WithDataVolume("disk0", dataVolume.Name),
libvmi.WithResourceMemory("1Gi"),
)
```
Fixes #
During the conversion, some other improvements have been made, in the vision of using `libvmi.Option`.
In particular: …
=> refactor(e2e): use `libvmi` instead of `NewRandomVMIWithDataVolume`

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/converter_test.go, pkg/virt-launcher/virtwrap/converter/testdata/domain_ppc64le.xml.tmpl, pkg/virt-launcher/virtwrap/converter/testdata/domain_x86_64.xml.tmpl, pkg/virt-launcher/virtwrap/converter/testdata/domain_x86_64_root.xml.tmpl
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/11219
Libvirt only supports IOThreads in disks with virtio bus (see [this](https://github.com/libvirt/libvirt/blob/master/src/qemu/qemu_validate.c#L2703)). This behavior was unaddressed in Kubevirt and could lead to several unhandled cases, mainly, enabling dedicated IOThreads on a single, valid virtio disks would cause other non-virtio disks to error. 
Fixes # https://issues.redhat.com/browse/CNV-34292
This Pull Request introduces changes such as:
- Webhook rejection of disks with non-virtio bus explicitly setting dedicated IOThreads.
- Using dedicated IOThreads in a single disk would mean enabling them for all remaining ones independently of their bus type. Now, only virtio disks will use IO threads when another …
=> [release-1.1] Manual backport of address incompatibility between IOThreads and unsupported buses

hack/cluster-deploy.sh
Syncing against an external cluster where kubevirt is not installed in "kubevirt" fails
After this PR:
Syncing against an external cluster where kubevirt is not installed in "kubevirt" succeeds
Fixes #
```release-note
NONE
```
=> Don't use hardcoded "kubevirt" ns name in sync script

tests/reporter/kubernetes.go, tests/tests_suite_test.go
When we use programatic focussing via `FIt` and we want to see k8s logs, we need to modify the test setup code for k8s-reporter - we need to remove the return statement that skips dumping logs if the test case succeeded.
After this PR:
When we use programatic focussing via `FIt` we now emit k8s logs, so we are able to look at k8s logs even if the tests succeed.
Fixes #
We could introduce an env var, however that would need to get remembered somewhere and also it would have need to get set every time. 
/cc @iholder101 @andreabolognani @enp0s3  …
=> tests, k8s: emit k8s log if tests focused via FIt

tests/infrastructure/k8s-client-changes.go, tests/pool_test.go, tests/replicaset_test.go
There was an issue in cri-o[1] that caused these tests to be very flaky.
This has been fixed in the latest releases of cri-o so we can reintroduce these tests to the presubmit test lanes.
[1] https://github.com/cri-o/cri-o/pull/7735
Fixes #
Requires https://github.com/kubevirt/kubevirt/pull/11465 to merge first. 
```release-note
NONE
```
=> e2e,quarantine: Remove tests from quarantine that were effected by slower deletion issue

tests/libstorage/storageclass.go, tests/virtiofs/datavolume.go
Virtiofs tests using multiple PVCs ask for a storage class supporting access mode `ReadWriteMany`. For the purpose of these tests, it is not required any specific access mode and, if this storage class is not found, the PVC requested through this non-existent storage class gets stuck in `Pending` state causing the test to fail.
After this PR:
It changes the requested storage class to any available one, regardless of the access mode. Moreover, this will ensure the test will work in the majority of scenarios.
```release-note
NONE
```
=> test(fix): virtiofs multiple PVCs tests

staging/src/kubevirt.io/client-go/kubecli/vmi.go
Generated client common methods does not return the GroupVersionKind of the resource.
This is caused by https://github.com/kubernetes/client-go/issues/541 and causes the goveralls job to constantly fails.
While working of how to permanently fix it, let's reintroduce the explicit groupVersionKind set.
goveralls lane is failing
After this PR:
goveralls lane is not failing anymore
Fixes #
```release-note
NONE
```
/cc @alicefr @xpivarc @brianmcarey
=> fix: revert dropping wrapper functions for VMI

pkg/controller/conditions.go, pkg/util/util.go, pkg/virt-api/rest/console.go, pkg/virt-api/rest/vnc.go, pkg/virt-api/webhooks/hyperv.go, pkg/virt-api/webhooks/utils.go, pkg/virt-config/virt-config.go, pkg/virt-launcher/virtwrap/api/defaults.go, pkg/virt-operator/util/readycheck.go, tests/watcher/watcher.go
The if condition expression has been modified to be simpler than before.
Fixes #
```release-note
NONE
```
=> refectory: if condition expression has been modified.

Makefile, tests/containerdisk/containerdisk.go, tests/migration/migration.go, tests/utils.go
Move functions from the tests utils to where they belong.
```release-note
NONE
```
=> tests, utils: Move functions from tests utils and tighten test/utils lines limit 

tests/clone_test.go, tests/framework/matcher/phase.go, tests/migration/migration.go, tests/storage/datavolume.go, tests/storage/export.go, tests/storage/imageupload.go, tests/storage/restore.go, tests/storage/snapshot.go, tests/storage/storage.go, tests/utils.go, tests/virtiofs/BUILD.bazel, tests/virtiofs/datavolume.go, tests/vmi_configuration_test.go
This PR fixes tests which are not adjusted to pass with wffc snapshotable storage classes.
Most of the issues is either not taking into account the new PendingPopulation phase or
expecting datavolume to be populated when with wffc they will be populated only when VMs are started and the
pvcs are mounted by the virt-launcher.
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-35788
```release-note
NONE
```
=> Fix tests to pass with snapshotable wffc storage

tests/infra_test.go
This is a manual cherry-pick of: https://github.com/kubevirt/kubevirt/pull/11277
The test did not correctly check prefixes of pod names, so it always passed.
And after finishing, it left the cluster in an inconsistent state, so other tests could fail.
After this PR:
An `Eventually()` is used in `AfterEach()` to wait until all deployments that were running on the tainted node are ready again.
```release-note
None
```
=> [release-1.0] test: Fix node taint test

tests/BUILD.bazel, tests/hyperv_test.go, tests/libnode/node.go, tests/utils.go, tests/vmi_configuration_test.go, tests/vmi_lifecycle_test.go
This PR moves GetSupportedCPUModels to libnode where it is more relevant.
Fixes #
```release-note
NONE
```
=> tests: Move get GetSupportedCPUModels to libnode

tests/utils.go, tests/vmi_configuration_test.go
Move GetVcpuMask func as a private func to vmi_configuration_test.go. 
Since it is the only place it is being called.
After this PR:
Fixes #
```release-note
NONE
```
=> tests, utils: Extract GetVcpuMask func as a private func

tests/storage/export.go, tests/storage/restore.go, tests/utils.go
Dropping NewRandomVMWithDataVolumeAndUserDataInStorageClass for direct libvmi usage.
Fixes #
```release-note
NONE
```
=> tests, utils: Drop NewRandomVMWithDataVolumeAndUserDataInStorageClass

tests/storage/storage.go
Remove `newVMIWithEphemeralPVC()` function in `tests/storage/storage.go`, and use `libvmi.New()` and `libvmifact.NewGuestless()` instead.
```release-note
None
```
=> tests/storage: remove newVMIWithEphemeralPVC()

tests/config_test.go, tests/utils.go
Function `DeleteConfigMap` and ` DeleteSecret` present in  `tests/utils.go` are inlined into the place where they are used.
The functions `DeleteConfigMap` and `DeleteSecret` in `tests/utils.go` doesnot look so useful because these function being called again and again in `tests/config_test.go`.
After this PR:
Then, These function are removed from `tests/utils.go` and inlined into the `tests/config_test.go` where they are used.
Fixes #11427
- Because it removes the overhead of the function call itself. 
- The second is it permits the compiler to more effectively apply other optimisation strategies. …
=> Function DeleteConfigMap and DeleteSecret are inlined

tests/vmi_configuration_test.go
After this PR:
Fixes #
```release-note
NONE
```
=> vmi_configuration_test.go Remove use of NewRandomVMI func

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
This PR improves test readability by using libvmi which shortens the code and makes it more elegant.
All vmis created for admitter unit tests were made with `NewMinimalVMI()`.
After this PR:
Unit tests are using libvmi in order to create vmis more elgantly.
```release-note
NONE
```
=> [code-clean] Add libvmi to admitter unit tests

Makefile, pkg/network/admitter/BUILD.bazel, pkg/network/admitter/admit.go, pkg/network/admitter/admit_suite_test.go, pkg/network/admitter/admit_test.go, pkg/network/admitter/slirp.go, pkg/network/admitter/slirp_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
Validation admitters related to network spec are moved under the network package in order to decouple them from the other admitters and allow the sig-network to properly own them.
In addition, work on simplifying the validation code and its tests has been included in this effort.
Fixes #
```release-note
NONE
```
=> virt-api, admitter: Refactor & move network validation admitters to the network package

Makefile, tests/BUILD.bazel, tests/libsecret/BUILD.bazel, tests/libsecret/secret.go, tests/vmi_cloudinit_test.go
Move the secret definition code to new package 'tests/libsecret'
In follow up PR, other tests will change to use libsecret and remove "kubevirt.io/secret" from tests/utils/labels
On cloud-init e2ev test suite, each test would define the same secret object but with different data.
Each test will use libsecret to define Secret objects 
Fixes #
```release-note
NONE
```
=> tests,cloud-init: Move secret creation to package

tests/kubectl_test.go
After this PR:
Fixes #
```release-note
NONE
```
=> kubectl_test.go Remove use of NewRandomVMI func

pkg/config/BUILD.bazel, pkg/config/config-map_test.go, pkg/config/secret_test.go, pkg/config/service-account_test.go
This PR improves test readability by using libvmi which shortens the code and makes it more elegant.
All vmis created for admitter unit tests were made with NewMinimalVMI() and disks are manually added.
After this PR:
Unit tests are using libvmi, adding disks elegantly and cleary.
```release-note
NONE
```
=> Use libvmi in disk related unit tests

tests/subresource_api_test.go
After this PR:
Fixes #
```release-note
NONE
```
=> subresource_api_test.go Remove use of NewRandomVMI func

tests/utils.go, tests/vmi_configuration_test.go
moves function to relevant place it is used
Fixes #
```release-note
NONE
```
=> tests/utils: Move function getPodCPUSet to only place it is used

pkg/libvmi/cloudinit.go, tests/utils.go, tests/vmi_cloudinit_test.go
Use libvmi directly at the caller instead of `NewRandomVMIWithEphemeralDiskAndUserdataNetworkData`.
After this PR:
Fixes #
- Since LaunchVMI() returned value is not used, the VMI instance in the
test context never get updated with the namespace causing failures.
It worked because 'NewRandomVMIWithEphemeralDiskAndUserdataNetworkData'
set the VMI with a namespace, so the instance in the test context had
the namespace.
To address this assign the the returned value from LaunchVMI().
- Regarding the test 'should have cloud-init network-config from k8s secret':
NewCirros() set cloudInit by default (to prevent it to hang at boot time).
Since the test …
=> tests: Use libvmi instead of 'NewRandomVMIWithEphemeralDiskAndUserdataNetworkData'

pkg/virt-launcher/virtwrap/api/defaults.go, pkg/virt-launcher/virtwrap/converter/converter.go
Shorten the isArch functions by returning the result of the comparison directly.
The functions were more complex than it needed to be.
After this PR:
The code is 6 lines shorter with no change to functionality and a tiny bit easier to read.
It is also more inline with other functions that do the same work.
Fixes #
None
None
```release-note
NONE
```
=> virt-launcher: Refactor/Simplify is<ARCH> functions

docs/getting-started.md
It resolves the Build command error while fetching the go container registry during the build process.
After this PR: 
Fixes #11549 
The following tradeoffs were made: 
Links to places where the discussion took place:  https://kubernetes.slack.com/archives/C0163DT0R8X/p1710856660625449
```release-note
"NONE"
```
=> docs: added a command to resolve the build error #11549

tests/storage/datavolume.go, tests/utils.go
Move the function from utils.
Remove unrequired parameters because they are the same that are used all over.
Remove unrequired table that does the same on both cases.
Fixes #
```release-note
None
```
=> e2e, datavolume: Refactor NewRandomVMWithDataVolume

pkg/monitoring/rules/alerts/virt-operator.go
During the alerts refactoring made by https://github.com/kubevirt/kubevirt/pull/10700, `NoLeadingVirtOperator` and `LowReadyVirtOperatorsCount` alerts duration to be triggered was accidentally changed from `10m` to `60m`. This PR fixes it.
Fixes https://issues.redhat.com/browse/CNV-39295
/cc @machadovilaca @sradco 
```release-note
None
```
=> Fix alerts duration to be triggered

hack/prom-rule-ci/prom-rules-tests.yaml, pkg/monitoring/rules/recordingrules/vm.go
In some cases there might be multiple instances of metrics, which differ in their `prometheus_replica` label. This is causing the following error in `kubevirt_vm_container_free_memory_bytes_based_on_working_set_bytes` recording rule:
```
many-to-many matching not allowed: matching labels must be unique on one side
```
due to two instances of the underlying metric `container_memory_working_set_bytes`, one with `prometheus_replica="prometheus-k8s-0"` and another with `prometheus_replica="prometheus-k8s-1"`. This PR fixes `kubevirt_vm_container_free_memory_bytes_based_on_working_set_bytes` expression, to take only one of them.
Fixes https://issues.redhat.com/browse/CNV-39570
Approvers are …
=> Fix kubevirt_vm_container_free_memory_bytes_based_on_working_set_bytes

tests/migration/migration.go, tests/utils.go
Move `RunCommandOnVmiTargetPod()` function to the only file it is used in. 
```release-note
None
```
=> tests/utils: Move RunCommandOnVmiTargetPod()

pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel, pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator.go, pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator_test.go
The Migration create mutator's tests ran three times - once for each `It` clause.
The Migration create mutator was replacing the migration object's spec for no apparent reason.
After this PR:
The Migration create mutator's test run once, is shorter and more explicit.
The Migration create mutator is no longer replacing the migration object's spec.
Fixes #
```release-note
None
```
=> Migration create mutator: Refactor unit test

pkg/apimachinery/patch/BUILD.bazel, pkg/apimachinery/patch/patch.go, pkg/apimachinery/patch/patch_suite_test.go, pkg/apimachinery/patch/patch_test.go, pkg/instancetype/instancetype.go, pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go, pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
Several ways how to perform patch operations with a mixture of hardcoded strings and types.
After this PR:
Gradually introduce the patch package to replace hardcoded patch operations. This package and the PatchSet type tries to follow the same style as libvmi.
The https://github.com/kubevirt/kubevirt/pull/11211 can be used as reference to see which files and operations we can replace with this new type.
This PR only modifies a couple of files to give an example how the package can be used. More refactoring PRs will follow.
```release-note
NONE
```
=> Create patchset type for patching operations

pkg/util/migrations/BUILD.bazel, pkg/util/migrations/migrations.go
Add check if VMI is nil in `IsMigrating`. This function could be called in different places of the code where the vmi object can be empty and this causes a panic.
```release-note
NONE
```
=> migrations: add check for vmi equal to nil

tests/guestlog/guestlog.go, tests/virtiofs/datavolume.go, tests/vmi_hook_sidecar_test.go
Some tests assert the number of containers in virt-launcher,
and later also ensure the container they care about in fact exists.
In such case, the former check is redundant.
Fixes #
```release-note
NONE
```
=> e2e tests: Drop some checks for amount of containers in virt-launcher

pkg/virt-launcher/virtwrap/BUILD.bazel, pkg/virt-launcher/virtwrap/cmd-server/server.go, pkg/virt-launcher/virtwrap/cmd-server/server_test.go, pkg/virt-launcher/virtwrap/generated_mock_manager.go, pkg/virt-launcher/virtwrap/manager.go, pkg/virt-launcher/virtwrap/manager_test.go, tools/cache/BUILD.bazel, tools/cache/cache_suite_test.go, tools/cache/time-defined-cache.go, tools/cache/time-defined-cache_test.go
This PR introduces a generic thread-safe and time-defined cache.
The main idea is that when the `Get()` method is called, the cache would either re-calculate the value or return the cached value according to the parameters passed to it during its creation.
This cache gets a few parameters:
* `minRefreshDuration`: If the value is requested before the minRefreshDuration has passed, the cached value will be returned. If minRefreshDuration is zero, the value will always be recalculated.
* `useValueLock`: which hurts performance a bit, but makes the cache thread-safe.
* `reCalcFunc`: a function to re-calculate the desired value.
The value can be also explicitly set with `Set()`.
This PR uses the cache for `GetDomainStats()`, and caches it for 5 seconds.
This is important since many GUI layers …
=> Introduce a generic thread-safe time-defined cache

docs/metrics.md, pkg/monitoring/metrics/virt-api/vm_metrics.go, pkg/monitoring/rules/recordingrules/vm.go
Since `kubevirt_vm_created_total` is exposed by all `virt-api` replicas with the total value of VMs created by that instance, the metric values on Prometheus were labeled by namespace but also by the original `virt-api` pod.
After this PR:
Since the need for `kubevirt_vm_created_total` was originally having a single metric with the total value of the VMs created, this PR renames the metric created by the `virt-api` pods, and creates a new recording rule based on that metric which contains the total value of VMs created broken down only by namespace.
jira-ticket: https://issues.redhat.com/browse/CNV-37015
Fixes #
This checklist is not enforcing, …
=> Fix kubevirt_vm_created_total being broken down by virt-api pod

hack/bump-common-instancetypes.sh
/cc @0xFelix 
The releases/latest GitHub API doesn't include pre-releases however we'd like to sync these to the main branch of kubevirt/kubevirt for testing ahead of GA.
RC releases of common-instancetypes were not sync'd.
After this PR:
RC releases of common-instancetypes are now sync'd.
Fixes #
```release-note
NONE
```
=> bump-common-instancetypes: Allow RC releases to be sync'd

staging/src/kubevirt.io/client-go/log/log.go, staging/src/kubevirt.io/client-go/log/log_test.go
This is similar to golang's glog.V() method which is useful to add conditional block of code (e.g: debug) when a high enough verbosity is set.
```go
if log.Verbosity(5) {
// do something you wouldn't otherwise
}
```
No way to make conditional log related to verbosity.
After this PR:
We have a way to do it.
Fixes #
Should help move forward with https://github.com/kubevirt/kubevirt/pull/11580 and related.
```release-note
NONE
```
=> logger: Add Verbosity() method

cmd/cniplugins/passt-binding/cmd/BUILD.bazel
The custom CNI plugin that is used with the `passt` network binding plugin is distributed through the release assets.
In order to allow it to run on different platforms, build it statically to avoid shared library conflicts.
This change should resolve issues [1] reported by users when attempting to use the `passt` binding plugin.
[1] https://github.com/kubevirt/kubevirt/issues/11586
Fixes #11586
```release-note
Build the `passt`custom CNI binary statically, for the `passt` network binding plugin.
Resolves …
```
=> cmd, cniplugins, passt-binding: Build the binary statically

pkg/network/admitter/BUILD.bazel, pkg/network/admitter/admit.go, pkg/network/admitter/admit_test.go, pkg/network/admitter/binding.go, pkg/network/admitter/binding_test.go, pkg/network/admitter/netsource.go, pkg/network/admitter/netsource_test.go, pkg/network/admitter/slirp.go, pkg/network/admitter/slirp_test.go, pkg/network/admitter/validator.go, pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
Relocate & refactor network validation admitters to the `network/admitter` package.
These changes include placing the validation logic under the sig-network ownership, optimize and simplify validation code, removing duplicate tests, adding missing tests. 
Fixes #
This is a continuation of #11511 
```release-note
NONE
```
=> net, admitter: Move network related admiter validations to the `network/admitter` package

tests/infrastructure/virt-controller-leader-election.go
The leader election test removes the virt-controller leader pod expecting the second replica to become the new leader.
However, after deletion, a new virt-controller pod is instantly created, and has good chances of becoming the new leader.
After this PR:
We just expect a new leader to get elected, since the old one doesn't exist anymore.
We shouldn't care if the new leader is the other replica or a newly created pod.
Fixes #
Reducing the number of replicas in the virt-controller deployment as suggested by the TODO.
That however would still race against the pod deletion...
I realize this effectively remove the problematic part, but I don't think it makes much sense. …
=> tests: fix flaky leader election test

tests/guestlog/guestlog.go, tests/virtiofs/datavolume.go, tests/vmi_hook_sidecar_test.go
Manual cherry pick of https://github.com/kubevirt/kubevirt/pull/11615
Fixes #
```release-note
NONE
```
=> [release-1.2] e2e tests: Drop some checks for amount of containers in virt-launcher

pkg/controller/controller_ref_manager.go, pkg/util/util.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter.go
After this PR:
Fixes #
```release-note
None
```
=> chore: fix function names in comment

pkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go, pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel, pkg/virt-api/webhooks/mutating-webhook/mutators/clone-create-mutator.go, pkg/virt-api/webhooks/mutating-webhook/mutators/clone-create-mutator_test.go
After this PR:
Tests were united into a table.
The actual AdmissionResponse object is tested against an expected AdmissionResponse object.
The mutator sets the correct APIGroup when the source is a `VirutalMachineSnapshot` object.
Tests were added to cover scenarios when the source it a `VirutalMachineSnapshot` object.
External dependencies were removed.
Tests were moved to the `mutators_test` package.
Fixes #
Since this PR is already quite big, follow-up PR(s) should:
1. Make the JSON patch more precise.
2. Handle the case when the mutator has nothing to do. …
=> VMClone create mutator: Refactor unit tests

pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator_test.go
PR #11561 introduced two new functions to the unit test file:
- newAdmissionReview
- expectedJSONPatch
Since:
1. Other mutators' tests will have similar functions
2. The tests share the same `mutators_test` package
add a suffix to differentiate them and avoid name collisions.
[1] https://github.com/kubevirt/kubevirt/pull/11561
[2] https://github.com/kubevirt/kubevirt/pull/11625
After this PR:
Fixes #
```release-note
NONE
```
=> Migration create mutator, tests: Avoid name collisions

pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
After this PR:
Import aliases have more meaningful names.
Imports are better organized.
Fixes #
```release-note
None
```
=> Evacuation controller, test: Tidy the imports

tests/sysprep_test.go, tests/utils.go
The deprecated NewRandomVMI is finally dropped from its two remaining users.
sysprep_test was calling NewRandomVMI and completely overwriting it with getWindowsSysprepVMISpec. This PR avoids the pointless dependency on the deprecated NewRandomVMI.
NewRandomVMIWithEphemeralDisk is re-implemented using libvmi. The re-implementation keeps the pre-existing unfortunate conditionals, which would disappear when NewRandomVMIWithEphemeralDisk is inlined into its own users.
The PR keeps the test in its less-than-ideal state. In the future, the VMI should be built using libvmi.
```release-note
NONE
```
=> tests: drop the deprecated NewRandomVMI

tools/cache/BUILD.bazel, tools/cache/time-defined-cache.go, tools/cache/time-defined-cache_test.go
A quick follow-up to https://github.com/kubevirt/kubevirt/pull/11634.
Specifically, addresses @vasiliy-ul feedback in [this comment](https://github.com/kubevirt/kubevirt/pull/11634#discussion_r1555314830).
The following can occur before this commit:
* thread 1 calls Get(), sees value is not set yet.
* thread 2 calls Get(), sees value is not set yet.
* thread 1 captures the write lock
* thread 2 waits on the write lock
* thread 1 calculates value and sets it, releases lock
* thread 2 catches lock, calculates value and sets it
After this PR:
Get() is being locked in its entirety and give up on using RWMutex. Not only that the behavior would be more correct, but it would also be more performant as it avoids redandunt re-calculations.
This checklist is not enforcing, but it's …
=> [time-defined cache] [follow-up]: Use a regular Mutex over RWMutex to lock the entire Get() function

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
The pod eviction admitter unit test file was long, did not cover all possible scenarios and had code duplication. 
After this PR:
The pod eviction admitter unit test file is about the same length, covers more scenarios and its readability is improved.
Fixes #
This is done in preparation for introducing the descheduler integration logic https://github.com/kubevirt/community/pull/258.
```release-note
NONE
```
=> Refactor pod eviction admitter unit tests

tests/reporter/kubernetes.go
/cc @dhiller 
68ebda2ae7d20 started to always collect logs when focus containers are used by tests. While useful the step logging suggested that a failure had occurred even if the test passes and was confusing to the reader.
After this PR:
This change provides a useful reason for the log collection and also renames the associated KubernetesReporter attribute to make it clear what it actually relates to.
Fixes #
```release-note
NONE
```
=> tests, k8s: Improve log collection logging

tests/storage/imageupload.go
Fix test to pass with WFFC storage class
Fixes # jira-tickat: https://issues.redhat.com/browse/CNV-35788
```release-note
NONE
```
=> tests/imageupload: add force bind for test to pass with wffc storage class

tests/operator/operator.go
The common-instancetypes feature gate is disabled by default but could be enabled during the deployment of KubeVirt.
After this PR:
Disable the common-instancetypes feature gate explicitly before running virt-operator common-instancetypes deployment tests to make sure the feature gate was not enabled before (e.g. in downstream deployments).
Also, improve the definition of vars/consts a little by using blocks.
Fixes:
https://issues.redhat.com/browse/CNV-35336
https://issues.redhat.com/browse/CNV-35337
https://issues.redhat.com/browse/CNV-35333 …
=> fix: Disable common-instancetypes feature gate before tests

docs/metrics.md, go.mod, go.sum, pkg/monitoring/rules/recordingrules/BUILD.bazel, pkg/monitoring/rules/recordingrules/operator.go, pkg/monitoring/rules/recordingrules/recordingrules.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/prometheusrules.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/registry.go, vendor/modules.txt
We currently have rules that calculate the available memory for all pods per container.
After this PR:
This pr adds rule that calculate issues with the pods like the memory of the pod with the highest memory exception value by container based on working set/rss memory (in bytes).
For example, if the virt-api container has 2 pods, one of which has an exception rate of 1000 and the other has -2000: the rule will show 1000. 
The rules added is `kubevirt_memory_delta_from_requested_bytes` which includes both the working_set and rss memory minus the requested memory, see:
**cnv_abnormal added to hco repo, see pr: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2855
Fixes #
Jira-ticket: https://issues.redhat.com/browse/CNV-39598
this pr is the next step after …
=> Add rule to collect issues with the pods

docs/metrics.md, hack/prom-rule-ci/prom-rules-tests.yaml, pkg/monitoring/metrics/common/client/rest_metrics.go, pkg/monitoring/rules/alerts/alerts.go, tests/monitoring/metrics.go, tools/perfscale-audit/metric-client/metric-client.go, tools/prom-metrics-collector/metrics_collector.go
Rest client metrics were not following naming conventions because they were not prefixed with `kubevirt_`
After this PR:
Those metrics are correctly named
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-40202
```release-note
Rename rest client metrics to include kubevirt prefix
```
=> Rename rest client metrics to include kubevirt prefix

pkg/monitoring/metrics/virt-controller/vmistats_collector.go, pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go, tests/monitoring/BUILD.bazel, tests/monitoring/vm_monitoring.go
No guest agent info was collected and exposed through vmi metrics.
After this PR:
`kernelRelease`, `machine`, `name` and `versionId` fields from `vmi.status.guestOsInfo` are collected and added as labels to `kubevirt_vmi_phase_count` metric.
Fixes # https://issues.redhat.com/browse/CNV-37369
We would like to have more visibility regarding VMIs OS, so we can differentiate between running VMs, and alert for specific OS issues (e.g. https://issues.redhat.com/browse/CNV-38482).
```release-note
Collect VMI OS info from the Guest agent as `kubevirt_vmi_phase_count` metric labels
```
=> Collect VMI OS info from the Guest agent

Makefile, tests/BUILD.bazel, tests/config_test.go, tests/libconfigmap/BUILD.bazel, tests/libconfigmap/configmap.go, tests/migration/BUILD.bazel, tests/migration/migration.go, tests/operator/BUILD.bazel, tests/operator/operator.go, tests/sysprep_test.go, tests/utils.go, tests/virtiofs/BUILD.bazel, tests/virtiofs/config.go
Remove the CreateConfigMap function from tests/utils.go in favor of a dedicated package for configmap management.
Fixes #
```release-note
NONE
```
=> tests/utils.go: move Configmap build logic to a dedicated package

go.mod, go.sum, vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/prometheusrules.go, vendor/modules.txt
Unit tests failed since we have 2 recording rules with the same name.
Even if we sort the rules it could happen that the resulting order is different, since we only compare names, and not the expressions.
This causes a false semantic deepEqual, and so a (one more) patch operation.
this PR fixed it observability repo https://github.com/machadovilaca/operator-observability/pull/11 
After this PR:
Uit test pass, and rules with same names count as 2 rules.
```release-note
NONE
```
=> Upgrade operator-observability to fix unit tests

cmd/virt-launcher/node-labeller/node-labeller.sh, pkg/virt-handler/node-labeller/cpu_plugin.go, pkg/virt-handler/node-labeller/cpu_plugin_test.go, pkg/virt-handler/node-labeller/model.go, pkg/virt-handler/node-labeller/node_labeller.go, pkg/virt-handler/node-labeller/node_labeller_test.go, pkg/virt-handler/node-labeller/util/util.go, pkg/virt-launcher/virtwrap/converter/converter.go
Refined CPU Validation per Libvirt Guidelines
**Issue:**
Libvirt validation fails when a CPU model is usable
by QEMU but lacks features listed in
`/usr/share/libvirt/cpu_map/[CPU Model].xml` on a node.
**Resolution:**
Nodes are now labeled with a CPU model only if all
features listed in the corresponding `cpu_map` XML file
are present and the model is usable by QEMU.
This prevents validation issues caused by missing features.
**Libvirt's Recommendation:**
Libvirt advises against using its internal data files for
feature validation.
As recommended, we're exploring the use only Libvirt's API
to identify usable CPU models, avoiding direct `cpu_map`
file dependency.
**New Approach:**
To avoid the validation error mentioned above we will disable
some of the features in the …
=> BugFix: Refined CPU Validation per Libvirt Guidelines

tests/BUILD.bazel
Set up the architecture in the image manifest based on bazel architecture.
Otherwise, the architecture in the manifest of conformance would be same to the CPU arch of the build server.
Fixes #11702
```release-note
None
```
=> conformance: fix multi-arch image manifest issue

tests/operator/operator.go
Fix a copy-paste mistake in the common-instancetypes feature gate test by looking up the correct FeatureGate in BeforeEach.
Fixes #11680
```release-note
None
```
=> fix: Lookup right FG in common-instancetypes FG test

pkg/util/status/status.go, pkg/util/status/status_test.go, pkg/virt-controller/watch/replicaset.go, pkg/virt-controller/watch/replicaset_test.go, pkg/virt-operator/webhooks/webhook.go, pkg/virt-operator/webhooks/webhook_test.go, pkg/virtctl/expose/expose.go, pkg/virtctl/expose/expose_test.go, staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go, staging/src/kubevirt.io/client-go/kubecli/kubevirt.go, staging/src/kubevirt.io/client-go/kubecli/replicaset.go, staging/src/kubevirt.io/client-go/kubecli/replicaset_test.go, tests/dryrun_test.go, tests/infrastructure/k8s-client-changes.go, tests/libreplicaset/replicaset.go, tests/network/expose.go, tests/replicaset_test.go, tests/vmi_lifecycle_test.go
We have our custom `virtualMachineInstanceReplicasetInterface` interface with the common `Get`, `Delete`, etc...
From https://github.com/kubevirt/kubevirt/pull/11297 the common methods implementation works as a wrapper with different signatures for the generated ones, redirecting the requests to them.
After this PR:
Convert using the generated client signatures instead of the custom one. The generated `virtualMachineInstanceReplicaset`  is embedded into our custom one, also providing new `DeleteCollection` and `Watch` methods.
The changes inherited are:
- `Patch` and `PatchStatus` now use metav1.PatchOptions{} instead of *metav1.PatchOptions{}.
- `List` now uses metav1.ListOptions{} instead of *metav1.ListOptions{}.
- `Get` now uses metav1.GetOptions{} instead of …
=> Generated client: embed generated methods into VMIRS interface

staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go, staging/src/kubevirt.io/client-go/kubecli/kubevirt.go, staging/src/kubevirt.io/client-go/kubecli/vmipreset.go, staging/src/kubevirt.io/client-go/kubecli/vmipreset_test.go, tests/dryrun_test.go, tests/vmipreset_test.go
We have our custom `virtualMachineInstancePresetInterface` interface with the common `Get`, `Delete`, etc...
From https://github.com/kubevirt/kubevirt/pull/11297 the common methods implementation works as a wrapper with different signatures for the generated ones, redirecting the requests to them.
After this PR:
Convert using the generated client signatures instead of the custom one. The generated `virtualMachineInstancePreset`  is embedded into our custom one, also providing new `DeleteCollection` and `Watch` methods.
The changes inherited are:
- `Patch` now uses metav1.PatchOptions{} instead of *metav1.PatchOptions{}.
- `List` now uses metav1.ListOptions{} instead of *metav1.ListOptions{}.
- `Get` now uses metav1.GetOptions{} instead of *metav1.GetOptions{}.
- `Delete` …
=> Generated client: embed generated methods into VMIP interface

pkg/controller/controller.go, pkg/storage/types/dv.go, pkg/storage/types/pvc.go, pkg/util/migrations/migrations.go, pkg/util/pdbs/pdbs.go, pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go, pkg/virt-controller/watch/drain/evacuation/evacuation.go, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/node.go, pkg/virt-controller/watch/pool.go, pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, pkg/virt-controller/watch/workload-updater/workload-updater.go
Remove informers from controllers:
- Get rid of informers in controllers struct and use indexers.
- Additional field in controllers `hasSynced` and lighten parameters `WaitForCacheSync` with this new field.
The updated controllers are:
Fixes #11570
I'm Sylvain from KubeVirt contribfest at the kubecon.
Continued of PR #11379.
```release-note
NONE
```
=> refactor: remove informers from controllers

tests/replicaset_test.go, tests/utils.go
Running is used only in tests/replicaset_test.go
Changes:
- Move it to where it is used as private function
- Rename it to make it clear that this function
is used for filtering.
Fixes #
```release-note
NONE
```
=> tests/utils.go:  Remove `Running` function from utils.go

tests/sysprep_test.go
Currently the `periodic-kubevirt-e2e-sysprep` test lane is failing trying to create a VMI without a namespace[1].
Update the test to include the namespace. 
Successful run with this change: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-sysprep/1780626069154435072
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-sysprep/1780385919203807232
Fixes #
```release-note
NONE
```
=> e2e,sysprep: Fix VMI namespace for sysprep test

pkg/monitoring/metrics/virt-controller/vmistats_collector.go, pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go, tests/monitoring/BUILD.bazel, tests/monitoring/vm_monitoring.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/11283.
```release-note
Collect VMI OS info from the Guest agent as `kubevirt_vmi_phase_count` metric labels
```
=> [release-1.2] Collect VMI OS info from the Guest agent

docs/metrics.md, pkg/monitoring/rules/recordingrules/BUILD.bazel, pkg/monitoring/rules/recordingrules/operator.go, pkg/monitoring/rules/recordingrules/recordingrules.go
This is a manual cherry-pick for https://github.com/kubevirt/kubevirt/pull/11557.
The automated one closed since had a rebase conflicts: https://github.com/kubevirt/kubevirt/pull/11703 
The operator-observability package was already bumped to 0.20 here: https://github.com/kubevirt/kubevirt/pull/11721
Jira-ticket: https://issues.redhat.com/browse/CNV-40387
```release-note
New memory statistics added named kubevirt_memory_delta_from_requested_bytes
```
=> [release-1.2] Add rule to collect issues with the pods

pkg/storage/backend-storage/BUILD.bazel, pkg/storage/backend-storage/backend-storage.go, pkg/virt-controller/watch/BUILD.bazel, pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/application_test.go, pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go
VMIs can encounter a (non-fatal) error while starting if the PVC is not ready.
After this PR:
VMIs will wait until the PVC is ready and not run into any error.
Fixes #
```release-note
NONE
```
=> Wait until backend storage PVC is ready before starting VMIs

staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_virtualmachineinstance_expansion.go, staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachineinstance_expansion.go, staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go, staging/src/kubevirt.io/client-go/kubecli/vmi.go, staging/src/kubevirt.io/client-go/kubecli/vmi_test.go, tests/launchsecurity/sev.go
vmis/sev/<subresource> requests use `RequestURI(uri)`, which overrides entirely the path during its construction. This means that in proxied servers SEV requests will not be correctly redirected to the proxy server.
Using AbsPath solves this issue, preserving the proxy server path at the beginning of the request path.
Also, added the possibility to pass the context from the caller for all the SEV methods.
SEV methods don't redirect to the correct path in case of proxied server
After this PR:
SEV methods are correctly redirected to the proxied server if exists.
Fixes # …
=> Allow SEV requests in proxied servers

pkg/monitoring/vmistats/collector.go, pkg/monitoring/vmistats/collector_test.go, tests/monitoring/BUILD.bazel, tests/monitoring/vm_monitoring.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/11283.
Required for implementing a fix for https://issues.redhat.com/browse/CNV-38482.
```release-note
Collect VMI OS info from the Guest agent as `kubevirt_vmi_phase_count` metric labels
```
=> [release-1.0] Collect VMI OS info from the Guest agent

pkg/monitoring/vmistats/collector.go, pkg/monitoring/vmistats/collector_test.go, tests/monitoring/BUILD.bazel, tests/monitoring/vm_monitoring.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/11283.
Required for implementing a fix for https://issues.redhat.com/browse/CNV-38482.
```release-note
Collect VMI OS info from the Guest agent as `kubevirt_vmi_phase_count` metric labels
```
=> [release-1.1] Collect VMI OS info from the Guest agent

tests/vmi_configuration_test.go
According to [quarantine docs](https://github.com/kubevirt/kubevirt/blob/main/docs/quarantine.md#putting-tests-in-quarantine) tests may be put in quarantine if they have a 20%+ impact.
The above test has 26% impact over the last 2 days, thus we quarantine it. 
We also see an overall degradation of merges from the queue for that reason.
https://search.ci.kubevirt.io/?search=hugepages-2Mi+with+guest+memory+set+explicitly&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
After this PR:
Test is quarantined, so it will not block merges with it's high failure rate.
Fixes #
/cc @brianmcarey …
=> flake, quarantine: test_id:1672 hugepages-2Mi with guest memory set explicitly

automation/test.sh, tests/decorators/decorators.go, tests/libnet/skips.go, tests/network/expose.go
Use labels instead.
It statically determine which tests to run, without dynamic skipping.
Fixes #
```release-note
None
```
=> tests, network: Remove SkipWhenNotDualStackCluster

pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go, pkg/virt-launcher/virtwrap/cli/libvirt.go
After this PR:
Unused methods and their generated mocks are removed from virt-launcher's libvirt wrapper.
Fixes #
```release-note
NONE
```
=> virt-launcher, libvirt: Remove unused methods and mocks

tests/container_disk_test.go, tests/operator/operator.go
Continue to remove the calls to the `NewRandomVMIWithEphemeralDisk` function, and replace it with libvmi functions.
Also, replace several lambda function in tests/operator/operator.go, to be a regular function.
```release-note
None
```
=> Retire the NewRandomVMIWithEphemeralDisk function (cont)

automation/test.sh
"make dump" needs a valid cluster KUBECONFIG,
so if cluster-up failed, it doesn't make sense.
It also hides and error, and we need to scroll a bit to find the fact cluster-up failed, instead seeing it directly.
Example https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11763/pull-kubevirt-e2e-k8s-1.29-sig-compute-migrations/1782065904025079808
Fixes #
```release-note
```
=> tests: Remove dump when cluster-up fails

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-config/feature-gates.go
There were 3 types of verbiage for MultiArchitecture:
* multi-architecture feature gate in the error message
* Multiarchitecture variable name in golang
* MultiArchitecture in the yaml
To not break any compatibility, renamed the `multi-architecture` and `Multiarchitecture` to `MultiArchitecture`.
Fixes: https://github.com/kubevirt/kubevirt/issues/11774
=> nit: make MultiArchitecture verbiage consistent

tests/storage/storage.go, tests/utils.go
`CopyAlpineWithNonQEMUPermissions` and its sibling
`DeleteAlpineWithNonQEMUPermissions` do a complex preparation (and later cleanup) of an Alpine test image for NFS tests.
I do not understand the tests that use them and why CopyAlpineWithNonQEMUPermissions is called ForEach one of them. Cleaning up this is left as a future exercise.
This commit only moves the convoluted functions next to the tests that uses them.
```release-note
NONE
```
=> tests: hide Copy/DeleteAlpineWithNonQEMUPermissions

tests/storage/datavolume.go
Before this PR: Some storage tier 1 tests would create storage classes and never remove them
After this PR: No storage classes are leaked from tests
Fixes [CNV-38887](https://issues.redhat.com/browse/CNV-38887)
Links to places where the discussion took place:  [CNV-38887](https://issues.redhat.com/browse/CNV-38887)
```release-note
NONE
```
=> Fix leaked storage classes in tier 1 storage tests

pkg/virt-api/rest/BUILD.bazel, pkg/virt-api/rest/streamer_norace_test.go, pkg/virt-api/rest/streamer_race_test.go, pkg/virt-api/rest/streamer_test.go
Empty and close channels after each test run to avoid race condition.
Skip check test checking for closed write-only channels, as it is mutually exclusive with the `-race`-flag.
Running `make go-test` fails with race condition found.
After this PR:
Running `make go-test` passes.
Fixes #8765 
Detecting if the `-race` flag is set via `runtime.debug`, however the `BuildInfo.Settings` was empty.
```release-note
NONE
```
=> virt-api: Fix race condition on streamer unit-test

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
Remove `isMigrationInProgress` which is not used.
Fixes #
```release-note
NONE
```
=> virt-api, admitter: Remove unused method from the VM validation

pkg/monitoring/rules/recordingrules/operator.go
Fix kubevirt_memory_delta_from_requested_bytes reason label to contain `_delta_from_requested` suffix.
In order to be able to understand the full reason when called in hco: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2855.
```release-note
none
```
=> Fix kubevirt_memory_delta_from_requested_bytes label

pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/vmi.go
Useless consts/params in template.go
After this PR:
No more.
```release-note
NONE
```
=> code cleanup: template.go: remove unused consts/params

tests/infrastructure/certificates.go, tests/utils.go
Function is used only on one file, therefore move it from utils.
Remove unrequired boolean which isn't used anyhow,
the error and cert return values are enough.
Split `getPodsCertIfSynced` to:
1. Get all certs.
2. Validate certs are valid and equal.
3. Use first cert to verify it was updated.
Fixes #
```release-note
None
```
=> tests: Hide GetPodsCertIfSynced

OWNERS_ALIASES
Edward is a core developer in the kubevirt network team,  
he sent more than 250 PRs to kubevirt and reviewed more than 750.
He pays close attention to the broad picture, clean code, project conventions and CI limitations . His reviews are comprehensive.
He certainly deserves to be a network approver.
Eddy wasn't sig-network approver.
After this PR:
Eddy is a sig-network approver.
Fixes #
The following apply to the part of project for which one would be an approver in the [OWNERS_ALIASES](https://github.com/kubevirt/kubevirt/tree/main/OWNERS_ALIASES) file.
```release-note
```
=> Adding Eddy as a sig-network approver

tests/hotplug/affinity.go, tests/hotplug/cpu.go, tests/hotplug/memory.go
The following code appears in the tests:
```go
libwait.WaitForSuccessfulVMIStart(vmi)
By("Ensuring the compute container has 2 CPU")
compute := libpod.LookupComputeContainer(tests.GetVmiPod(virtClient, vmi))
```
After `WaitForSuccessfulVMIStart()` finishes, the vmi variable is not being updated, hence the variable represents a vmi which is not running. This is currently failing tests for https://github.com/kubevirt/kubevirt/pull/11710, as the vmi's UID is being used to find the virt-launcher pod, but the UID might be empty if the vmi represents a non-running vmi.
After this PR:
The code above is being changed to:
```go
vmi = libwait.WaitForSuccessfulVMIStart(vmi)
By("Ensuring the compute container has 2 CPU")
compute := …
```
=> Fix hotplug tests by updating the VMI variable after waiting for it to run

automation/test.sh
These new targets allow the splitting of the sig-compute presubmit lane
into a lane with the parallel tests and a separate lane with the serial
tests.
The sig-compute lane is by far the longest running lane - over 3.5 hours
on average[1]. Splitting this lane will give quicker CI feedback to contributors
[1] https://grafana.ci.kubevirt.io/d/gY4hNc5Iz/kubevirt-kubevirt-e2e-test-runtimes?orgId=1&viewPanel=2&from=now-90d&to=now
Fixes #
Mailing list: https://groups.google.com/g/kubevirt-dev/c/YhD-XNUeJJc
```release-note
NONE …
```
=> e2e,compute: Add sig-compute-serial e2e target

pkg/virt-api/webhooks/mutating-webhook/mutators/clone-create-mutator.go, pkg/virt-api/webhooks/mutating-webhook/mutators/clone-create-mutator_test.go
Currently, the VMClone create mutator creates a JSON patch to replace the admitted object's spec even when there is no need to replace it (spec.target is fully set).
After this PR:
VMClone create mutator does not add a JSON patch to the AdmissionResponse in case there is no need to mutate the object.
Fixes #
```release-note
NONE
```
=> VMClone create mutator: Don't mutate when there is no need

pkg/virt-controller/watch/vmi_test.go
Use fake client instead of mocking in order to simulate real behavior.
The PR is exposing and fixing few tests: 
- [vmi ctrl: fix pod annotation patch tests](https://github.com/kubevirt/kubevirt/pull/11751/commits/c4819ab6466eeac5026c52f82603e87f82b8c7d0)
- [fix(vmi ctrl): remove empty activepods and volumestatus](https://github.com/kubevirt/kubevirt/pull/11751/commits/699c126a54ddbc3b99c8d9fc1f2fd04950a65421)
- [vmi ctrl: fix vmi status hotplug disk tests](https://github.com/kubevirt/kubevirt/pull/11751/commits/9cf28da2c16cb0634e2220309de4bd195923dda9)
- [vmi ctrl: fix invtsc and hyperv tests](https://github.com/kubevirt/kubevirt/pull/11751/commits/f3f4bf50117d45d06c7ca0329fbeb0c91c33db0f)
This PR also improved some tests:
- [fix(vmi ctrl): improve some …
=> VMI controller - move unit tests to fake client (VirtualMachineInstanceInterface)

pkg/storage/types/pvc.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
All the type of volumes were live-updatable. However, this assumption is incorrect. The only volumes that can be changed while the VM is running are hotpluggable volumes which can be added, replaced or removed.
After this PR:
This PR takes into account the volume types for the volume update and add the restart required condition accordingly.
```release-note
Fix the live updates for volumes and disks
```
=> Fix live updates for the volumes

tests/hotplug/cpu.go, tests/hotplug/memory.go, tests/libpod/container.go, tests/utils.go
This PR removes utils' GetVmiPod() function and replace it with libpod functions.
```release-note
NONE
```
=> Remove utils' GetVmiPod() function and replace it with libpod functions

pkg/util/migrations/migrations.go, pkg/virt-controller/watch/workload-updater/workload-updater.go, pkg/virt-controller/watch/workload-updater/workload-updater_test.go, staging/src/kubevirt.io/api/core/v1/types.go, tests/hotplug/BUILD.bazel, tests/hotplug/cpu.go
The workload updater doesn't currently support the ability to abort a migration due to an automated workload update. Today, the workload update is mostly used for CPU and memory hotplug.
After this PR:
This change introduces a mechanism to aborts a workload update.
The migration abortion can be detected if the VMI doesn't have any VMI*Change conditions but there is a migration due to a automated workload update. If this condition is met, then it means that the change condition was present (has triggered the migration) but now it has been removed. This assumption simplifies the workload updater that needs only to take care of deleting the migration.
We have also introduced a new annotation kubevirt.io/kubevirt.io/testWorkloadUpdateMigrationAbortion that should only be used …
=> workload-update: cancel a workload update migration

tests/compute/BUILD.bazel, tests/compute/credentials.go, tests/libnet/cloudinit/cloudinit.go, tests/utils.go, tests/vmi_configuration_test.go
Moved GetFedoraToolsGuestAgentBlacklistUserData out of /test/utils.go to /tests/libnet/cloudinit/cloudinit.go
After this PR:
Fixes #
```release-note
NONE
```
=> Move GetFedoraToolsGuestAgentBlacklistUserData

tests/libreplicaset/BUILD.bazel, tests/libreplicaset/replicaset.go, tests/pool_test.go, tests/replicaset_test.go, tests/utils.go
- Move `NotDeleted()` to `/libreplicaset` (since it's used only by replicaset test), rename it to `FilterNotDeletedVMIs()` and remove its [named returned value](https://go.dev/tour/basics/7).
- Move `NotDeletedVMs()` to `pool_test.go` (the only file it's used in), and improve by integrating it within
`notDeletedVMs()` function, which was renamed to `filterNotDeletedVMIsOwnedByPool()`.
```release-note
None
```
=> test/utils: Remove NotDeleted() and NotDeletedVMs()

pkg/network/namescheme/networknamescheme.go, pkg/network/namescheme/networknamescheme_test.go
The OrdinalPodInterfaceName() returned `net0` if it only had one secondary network
I will now return `net1` as it should.
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/11678
Fixes #
```release-note
Improve the handling of ordinal pod interface name for upgrade
```
=>  [release-1.0] Improve the handling of ordinal pod interface name for upgrade

pkg/storage/backend-storage/BUILD.bazel, pkg/storage/backend-storage/backend-storage.go, pkg/virt-controller/watch/BUILD.bazel, pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/application_test.go, pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go
Manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/11373
```release-note
NONE
```
=> [release-1.2] Wait until backend storage PVC is ready before starting VMIs

docs/handling-eviction-requests.md
One needs to dig through a lot of code in order to understand how KubeVirt handles K8s' API-initiated eviction [1].
After this PR:
The way KubeVirt handles K8s' API-initiated eviction is documented.
[1] https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/
Fixes #
```release-note
NONE
```
=> Docs: Document handling eviction requests

docs/coding-conventions.md
This adds coding-convetions.md which contains coding guidelines for the KubeVirt project.
Fixes #11259 
We need coding conventions to ensure the maintainability of the codebase.
The rules are opinionated and subject to discussion/change.
Do not provide guidelines and become desperate maintaining the code. :)
See #11259 
```release-note
None
```
=> docs: Add coding-conventions.md

api/openapi-spec/swagger.json, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-config/feature-gates.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go
No support for the update volume strategy
After this PR:
This PR introduces the updateVolumeStrategy described in [update-volume-strategy proposal](https://github.com/kubevirt/community/blob/main/design-proposals/volume-update-strategy.md). 
Fixes #
This change prepares the virt-controller to support the volume update. It is a preparation for the [volume migration](https://github.com/kubevirt/kubevirt/pull/11533) and the migration update volume strategy.
Both volume migration and hotplug will also update the volume set of the VM, and we need to be able to distinguish the type of update that the user wants. This is the role of the new field `updateVolumeStrategy`.
```release-note
Add the updateVolumeStrategy field
```
=> Introduce the update volume strategy field

tests/BUILD.bazel, tests/infrastructure/BUILD.bazel, tests/infrastructure/certificates.go, tests/infrastructure/tls-configuration.go, tests/libpod/BUILD.bazel, tests/libpod/certs.go, tests/migration/migration.go, tests/operator/operator.go, tests/utils.go
Extract functions from utils, to reduce utils size.
Fix linter problems (since we moved the function to a new file, which is now scanned).
Fixes #
```release-note
None
```
=> tests: Extract GetCertsForPods (and related functions) from utils

tests/containerdisk/containerdisk.go, tests/utils.go, tests/vm_test.go
vm_test.go used a deprecated function named NewRandomVirtualMachineInstanceWithFileDisk
After this PR:
vm_test.go uses libvmi instead and NewRandomVirtualMachineInstanceWithFileDisk is removed
After this PR it would be easier to remove NewRandomVirtualMachineInstanceWithBlockDisk and later NewRandomVirtualMachineInstanceWithDisk
```
NONE
```
=> Replace NewRandomVirtualMachineInstanceWithFileDisk inside vm_test.go

tests/libsecret/secret.go, tests/vmi_cloudinit_test.go
Users can pass in data as a map of strings or a map of bytes.
The current usage requires only a map of strings, but the bytes version has been created to allow passing in also that type when needed.
In this form, it should be easier for the callers to pass the data in the most convenient manner.
Ref: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/#Secret
Fixes #
```release-note
NONE
```
=> tests, libsecret: Generalize data used for secret

pkg/virt-controller/watch/vm_test.go
/cc @xpivarc 
As reported by bug #11872 syncCache is hitting a timeout in the VM controller tests after recently being added by 782a6ff2c47. This change simply doubles this timeout to avoid the timeout while still waiting for the cache to be correctly populated.
Fixes #11872
```release-note
NONE
```
=> controller: Increase syncCache timeout in VM tests

pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
When the criteria for VMI evacuation are met (see  https://github.com/kubevirt/kubevirt/pull/11286):
1. The eviction admitter marks the VMI for evacuation.
2. The eviction admitter approves the eviction request.
3. kube-api [denies](https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/#how-api-initiated-eviction-works) the eviction request because the virt-launcher is protected by a PDB.
When a [descheduler](https://github.com/kubernetes-sigs/descheduler) tries to evict a virt-launcher pod owned by a VMI that could be evacuated, it receives a denial for the eviction request and cannot understand that a VMI evacuation was triggered in the background.
After this PR:
When a VMI is marked for evacuation the eviction request is denied with a spacial message. …
=> Eviction admitter: Deny when triggering VMI evacuation

cmd/sidecars/smbios/BUILD.bazel, cmd/sidecars/smbios/smbios.go
Would require `virt-launcher/virtwrap/api` when building `smbios.go` out-of-tree.
After this PR:
Requires `libvirtxml` instead.
Fixes #11817
```release-note
SMBios sidecar can be built out-of-tree
```
=> Prefer libvirtxml over schema.go in smbios sidecar example

pkg/virtctl/pause/pause.go
Before this PR: Typo in error message ("Virtual" vs "Virtual")
After this PR: Properly spelled error messages
```release-note
NONE
```
=> Fix typo: VirutalMachineInstance => VirtualMachineInstance

pkg/controller/virtinformers.go, pkg/storage/backend-storage/BUILD.bazel, pkg/storage/backend-storage/backend-storage.go, pkg/storage/backend-storage/backend-storage_suite_test.go, pkg/storage/backend-storage/backend-storage_test.go, pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/application_test.go, pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, pkg/virt-handler/BUILD.bazel, pkg/virt-handler/vm.go, tests/storage/BUILD.bazel, tests/storage/backendstorage.go
- Using backend storage (i.e. persistent TPM and/or UEFI) requires setting a storage class in the CR
- The storage class has to support RWX Filesystem mode
After this PR:
- The default storage class will be used if none is specified in the CR
- If that storage class has a storage profile that indicates it only supports Filesystem in RWO then a RWO PVC will be created and the VMI will be marked as non-migratable.
Fixes #
A VMI status field was added for virt-controller to let virt-handler know that the backend storage PVC is RWO.
Having virt-handler check if the PVC is RWX or RWO but virt-handler currently has no PVC informer.
Having virt-controller add the non-migratable condition, but that …
=> backend storage: add logic to improve usability

tests/vmipreset_test.go
NewRandomVMIWithEphemeralDisk is deprecated
This PR is a continues effort to drop usage of this function, this time from the tests/vmipreset_test.go
In addition, the PR also contains some general cleanups, like handling variables better (e.g. make const vars to be real consts), and use proper gomega matchers for maps.
```release-note
None
```
=> stop calling NewRandomVMIWithEphemeralDisk in tests/vmipreset_test.go

tests/pausing_test.go, tests/security_features_test.go, tests/vmi_headless_test.go, tests/vmi_hook_sidecar_test.go, tests/vmi_iothreads_test.go, tests/vmi_kernel_boot_test.go, tests/vmi_multiqueue_test.go
NewRandomVMIWithEphemeralDisk is deprecated. This PR removes calls to
this function from all test files (except for tests/vmipreset_test.go, that is done in #11826)
```release-note
None
```
=> Remove call to NewRandomVMIWithEphemeralDisk

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
A VM with cpu requests and/or limits set could not hotplug vcpus.
After this PR:
A VM with cpu requests and/or limits set can hotplug vcpus.
Fixes #
```release-note
Allow to hotplug vcpus for VMs with CPU requests and/or limits set
```
=>  Allow to set cpu reqs/limits when doing cpu hotplug

pkg/virt-controller/watch/BUILD.bazel, pkg/virt-controller/watch/migration_test.go
Use fake client instead of mocking in order to simulate real behavior.
Fixes #
Lower the bar for unit tests, eliminate false positives. The fake is standard for testing.
```release-note
NONE
```
=> VMIM controller - move unit tests to fake client

tests/clone_test.go, tests/console/console.go, tests/console/login.go, tests/migration/migration.go, tests/reporter/kubernetes.go, tests/softreboot_test.go
Developers running functional tests locally sometimes have to wait multiple time 3 minutes waiting for the log collector to fail to login to some VMI(s).
Those who use a lightweight cluster without things like CNAO also keep seeing:
dump network-attachment-definitions: the server could not find the requested resource
After this PR:
When collecting logs, we only try to login to VMIs for 20 seconds, which might still be too long.
That message about NADs is also removed.
Just a convenience PR, but the shorter timeout might actually improve lane runtime
```release-note
NONE
```
=> e2e suite: slight improvement to developer experience

tests/vm_test.go
This test is very flaky at the moment[1] and meets the criteria for quarantine.
The large timeout[2] in this test allowed the test VM to gracefully shutdown so it may not have been testing force restart at all.
This flake could be exposing an issue with force restart.
Quarantining for now to allow for investigation.
[1] https://search.ci.kubevirt.io/?search=test_id%3A3007&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
[2] https://github.com/kubevirt/kubevirt/blob/037618edc09d7a490f9a6bfed6b60ed31339600c/tests/vm_test.go#L791
Fixes #
/cc @jean-edouard @fossedihelm @dhiller  …
=> e2e,compute: Quarantine flaky force restart e2e test

tests/compute/BUILD.bazel, tests/compute/credentials.go, tests/storage/BUILD.bazel, tests/storage/export.go, tests/virtctl/BUILD.bazel, tests/virtctl/credentials.go, tests/vmi_configuration_test.go, tests/vmi_lifecycle_test.go
Change tests that involve defining simple Secret objects to use `tests/libsecret` package
Affected test suites:
- compute/credentials.go
- storage/export.go
- virtctl/credentials.go
- vmi_configuration_test.gp
- vmi_lifecycle_test.go
E2E tests created the secret in-line, some added the `kubevirt.io/secret` label and some dont.
E2E tests create the secret object using libsecret, all tests use the same expected configuration.
Fixes #
The global test suite deletes cleanup that runs after each test delete secrets who has `kubevirt.io/secret` label.
It is not clear why this filtering is necessary, therefore we should revisit it …
=> tests: Make use of tests/libsecret

tests/storage/hotplug.go, tests/storage/storage.go, tests/utils.go, tests/virtiofs/datavolume.go
Move the function to the place the pod returned
is actually used. Other places that only need to
get to succeeded just run explicitly 3 code lines
of create pod and wait succeeded.
* currently rebased on top of  #11756 so should review only second commit
Function in test utils
After this PR:
function in right place or without a call to a function that does extra get without the need.
Fixes #
```release-note
NONE
```
=> tests/utils: Move function RunPodAndExpectCompletion

pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/network.go
`CreateDomainInterfaces()` had unused `domain` parameter.
After this PR:
`CreateDomainInterfaces()` does not have an unused parameter.
Fixes #
```release-note
NONE
```
=> Launcher, CreateDomainInterfaces: Remove unused param

tests/network/bindingplugin_slirp.go, tests/network/expose.go, tests/utils.go
Move GenerateHelloWorldServer() to test/network, as network is the only package using it.
```release-note
None
```
=> test/utils: Move GenerateHelloWorldServer() to tests/network

pkg/virt-controller/watch/vmi_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/11751
```release-note
NONE
```
=> [release-1.2] VMI controller - move unit tests to fake client (VirtualMachineInstanceInterface)

.golangci.yml, Makefile, hack/builder/Dockerfile, hack/dockerized, hack/gofumpt.sh, pkg/instancetype/compatibility_test.go, pkg/instancetype/instancetype.go, pkg/instancetype/instancetype_test.go, pkg/libvmi/selector.go, pkg/libvmi/storage.go, pkg/libvmi/vmi.go, pkg/network/admitter/admit_test.go, pkg/network/admitter/binding.go, pkg/network/admitter/binding_test.go, pkg/network/admitter/macvtap.go, pkg/network/admitter/netiface_test.go, pkg/network/admitter/netsource_test.go, pkg/network/admitter/passt.go, pkg/network/admitter/slirp.go, pkg/network/deviceinfo/deviceinfo_test.go, pkg/network/domainspec/generators_test.go, pkg/network/domainspec/interface.go, tests/console/console.go, tests/console/login.go, tests/libnet/cloudinit/cloudinit.go, tests/libnet/cluster/cluster.go, tests/libnet/job/job.go, tests/libnode/node.go, tests/libpod/certs.go, tests/libpod/render.go
A stricter formater allows to reduce formatting and style opinionated comments in reviews.
It provides consistency and helps with code readability.
[gofumpt](https://github.com/mvdan/gofumpt) seems to be popular among the Go community, therefore chosen for this task.
Used the `extra` flag to add all rules.
To automatically format the code, use: `make gofumpt` or:
```
gofumpt -l -w -extra \
pkg/instancetype \
pkg/libvmi \
pkg/network/admitter \
pkg/network/namescheme \
pkg/network/domainspec \
pkg/network/deviceinfo \
tests/console \
tests/libnet \
tests/libnode \
tests/libconfigmap \
tests/libpod \
tests/libvmifact \
tests/libsecret
```
Fixes # …
=> linter: Introduce a stricter formatter `gofumpt`

tests/hotplug/affinity.go, tests/hotplug/rolloutstrategy.go
Add polarion test IDs for RollOutStrategy and Affinity test cases
```release-note
None
```
=> Add test IDs for tests

docs/network/network-binding-plugin.md
Document the migrations support details in the network binding plugin developer-guide.
Fixes #
```release-note
NONE
```
=> docs, network-binding-plugin: Document migration support

pkg/storage/export/export/BUILD.bazel, pkg/storage/export/export/export.go, pkg/storage/export/export/export_test.go
Since https://github.com/kubevirt/kubevirt/pull/8953, the export controller allows rendering virtual machine manifests to complete VM information with export URLs. However, this mechanism uses custom logic to complete the `DataVolumeTemplate` field, leading to api incompatibilities when the original VM had volumes with populated SourceRef fields.
This pull request aims to fix this behavior by setting the `SourceRef` field to nil when populating the HTTP source in the export controller.
Fixes # https://issues.redhat.com/browse/CNV-40606
I considered modifying the manifest in the export sever (instead of in the controller). However, since the controller is setting the http source, I think it makes way more sense to fix this in the controller. …
=> Fix VM manifest rendering in export-controller

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
The delta calculation was based on the VM instead of the VMI, this caused a miscalculation of the delta when multiple hotplug were requested.
Before this patch:
T0: VM has  `limits.cpu: 1` and `sockets: 1`
T1: hotplug 1 more socket
T2: VM has  `limits.cpu: 1100m` and `sockets: 2`
T1: hotplug 1 more socket
T2: VM has  `limits.cpu: 1100m` and `sockets: 3`
After this patch:
T0: VM has  `limits.cpu: 1` and `sockets: 1`
T1: hotplug 1 more socket
T2: VM has  `limits.cpu: 1100m` and `sockets: 2`
T1: hotplug 1 more socket
T2: VM has  `limits.cpu: 1200m` and `sockets: 3` …
=> controller: fix bug when limits are used with CPU hotplug

tests/monitoring/component_monitoring.go
Ref: https://github.com/kubevirt/kubevirt/commit/0c086a0acd4a3658dc15b61310223ef7ec9aaf1d
virt-handler component monitoring test is flaky
After this PR:
virt-handler component monitoring test is disabled
Fixes #
```release-note
NONE
```
=> tests: PIT flaky virt-handler component monitoring test

pkg/virt-operator/resource/apply/apps.go, pkg/virt-operator/resource/apply/apps_test.go, pkg/virt-operator/resource/apply/reconcile.go, pkg/virt-operator/resource/apply/reconcile_test.go, pkg/virt-operator/strategy_job.go
Some of Kubevirt's infrastructure components are powerful and privileged. Running these components on worker nodes is a security issue which compromises the cluster. For more information, please see the conversation here: https://github.com/kubevirt/community/pull/246#discussion_r1550188378
As of today, it's solely the admin's responsibility to set the right NodePlacement under Kubevirt CR. It seems that some major Kubevirt users (e.g. OpenShift Virtualization) are not setting this properly, and we should strive to help them by using a sensible default.
After this PR:
Kubevirt, by default, requires running infrastructure components on control-plane nodes. This will only happen if the user did not specify any node placement settings in Kubevirt CR.
After this PR Kubevirt …
=> Require scheduling infra components onto control-plane nodes

Makefile, go.mod, go.sum, hack/builder/Dockerfile, hack/dockerized, pkg/monitoring/rules/BUILD.bazel, pkg/monitoring/rules/rules_suite_test.go, pkg/monitoring/rules/rules_test.go, vendor/github.com/grafana/regexp/.gitignore, vendor/github.com/grafana/regexp/BUILD.bazel, vendor/github.com/grafana/regexp/LICENSE, vendor/github.com/grafana/regexp/README.md, vendor/github.com/grafana/regexp/backtrack.go, vendor/github.com/grafana/regexp/exec.go, vendor/github.com/grafana/regexp/onepass.go, vendor/github.com/grafana/regexp/regexp.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/BUILD.bazel, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_custom_validations.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_validation.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/linter.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/problem.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/recording_rule_validation.go, vendor/modules.txt
Apply the following linters:
- [monitoringlinter](https://github.com/kubevirt/monitoring/tree/main/monitoringlinter) that was implemented in https://github.com/kubevirt/monitoring/pull/221, and was designed to enforce https://github.com/kubevirt/community/pull/219.
This linter ensures that all monitoring-related practices are implemented within the `pkg/monitoring` directory using [operator-observability](https://github.com/machadovilaca/operator-observability/tree/main) methods. It verifies that all metrics, alerts and recording rules registrations are centralized in this directory, and restricts the direct use of [Prometheus registration methods](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#Registerer).
Example for a message reported by the linter:
``` …
```
=> Apply monitoring linters

tests/vm_test.go
There has been a big increase in the flakiness of this test over the past two days[1]
With 31% impact on 1.29 sig-compute lane it qualifies for quarantining
[1] https://search.ci.kubevirt.io/?search=test_id%3A6993&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
/cc @dhiller @jean-edouard @acardace 
```release-note
NONE
```
=> e2e,compute: Quarantine flaky test with RunStrategyManual and failing VMI

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
PodEvictionAdmitter:
1. Had exported (public) fields and could be instantiated incorrectly.
2. Used the old `kubecli.KubevirtClient` clientset.
3. Used gomock in unit tests.
After this PR:
PodEvictionAdmitter:
1. Has a factory function and only unexported (private) fields.
2. Uses kubernetes' official generated clientset.
3. Uses KubeVirt's generated clientset.
4. Uses KubeVirt's generated fake clientset in unit tests instead of gomock.
Fixes #
This is a follow up to https://github.com/kubevirt/kubevirt/pull/11380. …
=> Eviction admitter: Use KubeVirt generated clientset

pkg/virtctl/imageupload/imageupload.go
Signed-off-by: Ido Aharon <iaharon@redhat.com>
Currently virtctl has a hard coded `v1alpha1` endpoint for both regular and async image upload. We no longer support v1alpha1, so we should update the endpoint to `v1beta1`.
Fixes [CNV-41625](https://issues.redhat.com/browse/CNV-41625)
```release-note
Update virtctl to use v1beta1 endpoint for both regular and async image upload
```
=> Update virtctl to use v1beta1 endpoint

staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/BUILD.bazel, staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/kubevirt_expansion.go, staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachine_expansion.go, staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachineinstance_expansion.go, staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachineinstancereplicaset_expansion.go, staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel, staging/src/kubevirt.io/client-go/kubecli/kv.go, staging/src/kubevirt.io/client-go/kubecli/replicaset.go, staging/src/kubevirt.io/client-go/kubecli/vm.go, staging/src/kubevirt.io/client-go/kubecli/vmi.go
Our `vm`,  `vmi`, `kv`, `vmirs` structs respectively embed generated
`VirtualMachineInterface`, `VirtualMachineInstanceInterface`,
`KubeVirtInterface` and  `VirtualMachineInstanceResplicasetInterface`.
The latter define the custom methods but do not
implement them, which are only defined in the custom structs.
We can move the expanded methods implementations
in the `virtualmachine_expansion`, `virtualmachineinstance_expansion`,
`kubevirt_expansion`, `virtualmachineinstancereplicaset_expansion` files so that our custom structs
can simply inherit them.
Also, switched to using full `AbsPath` with fmt.Sprintf()
to request composition with `Namespace()`, `Resource()`,
`Name()` and `SubResource()`.
N.B. methods that require clientConfig, like `PortForward`, remain implemented only 
in our …
=> client-go: Move custom <resource> struct methods to <resource>_expansion files

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-controller/watch/BUILD.bazel, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
Any VMs referencing an instance type were rejected by the validation webhooks when `LiveUpdate` was enabled.
After this PR:
VMs referencing an instance type are now allowed when `LiveUpdate` is enabled. Additionally any changes to the `{Instancetype,Preference}Matcher` of the VM will result in the `RestartRequired` condition being added.
Fixes #11960
This will be manually cherry-picked back to release-1.2 as I've used recently introduced libvmi functionality in the tests here so an automated cherry-pick will fail.
Approvers are …
=> instancetype: Allow `VirtualMachines` referencing instance types when `LiveUpdate` is enabled and trigger the `RestartRequired` condition if changed

tests/instancetype/upgrade.go
/cc @brianmcarey 
/test periodic-kubevirt-e2e-k8s-1.29-sig-compute-root
As set out in #11958 the rootful periodic tests actually use a different namespace to the default leading to a failure. Instead use the namespace provided by the object as set within the recently introduced builder.
Fixes #11958
```release-note
NONE
```
=> instancetype: Avoid hardcoding namespace in upgrade tests

pkg/virt-launcher/virtwrap/converter/BUILD.bazel, pkg/virt-launcher/virtwrap/converter/amd64.go, pkg/virt-launcher/virtwrap/converter/archconverter.go, pkg/virt-launcher/virtwrap/converter/archconverter_test.go, pkg/virt-launcher/virtwrap/converter/arm64.go, pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/converter_test.go, pkg/virt-launcher/virtwrap/converter/ppc64le.go
Replace long switch case statements for arch specific conversions into separate code files by utilizing an interface.
Fix some code warnings in converter.go
Big chunks of arch specific code is mixed with general virt-launcher code
After this PR:
arch specific code is mostly in arch specific files. Exceptions is for trivial paths where only single string values are different and the effort and additional complexity of splitting it would not be worth it.
Fixes #
- Some arch specific configuration values are still in the main code
https://github.com/kubevirt/kubevirt/pull/10490#issuecomment-2024935029 …
=> virt-launcher: Use interface for arch specific conversions

api/openapi-spec/swagger.json, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go
When switching to the `RerunOnFailure` RunStrategy the VM does not get started
After this PR:
When switching to the `RerunOnFailure` RunStrategy the VM does get started
This PR also slightly refactors vm-controller sync() loop and removes the `VirtualMachineInitialized` condition.
Fixes #
```release-note
Fix RerunOnFailure RunStrategy
```
=> Fix RerunOnFailure RunStrategy

api/openapi-spec/swagger.json, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/11963
Fixes #
```release-note
Fix RerunOnFailure RunStrategy
```
/cc @acardace
=> [release-1.2] Fix RerunOnFailure RunStrategy

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
This PR fixes cases where RestartRequired condition is not propagated to Kubernetes API. The cause is Update call that should not be called when only .Status is changed (note if a change was made the condition will be missing). Also ensure that we detect a .Status change in the updateStatus.
Fixes #
```release-note
Bug fix: Correctly reflect RestartRequired condition
```
=> Restart required correctly propagate

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/11973
Fixes #
Conflicts are in vm test, where we need to use `controller.<informer>.getIndexers()` instead of `controller.<indexer>`
```release-note
Bug fix: Correctly reflect RestartRequired condition
```
/cc @acardace @jean-edouard
=>  [release-1.2] Restart required correctly propagate

pkg/virt-handler/device-manager/BUILD.bazel, pkg/virt-handler/device-manager/device_controller_test.go, pkg/virt-handler/device-manager/device_plugin_base.go, pkg/virt-handler/device-manager/generic_device.go, pkg/virt-handler/device-manager/mediated_device.go, pkg/virt-handler/device-manager/pci_device.go, pkg/virt-handler/device-manager/socket_device.go, pkg/virt-handler/device-manager/socket_device_test.go, pkg/virt-handler/device-manager/usb_device.go
All methods on plugins are implemented without a common interface to unify testing
After this PR:
Define the `DevicePlugin` interface to group methods
Fixes:
https://github.com/kubevirt/kubevirt/issues/11293#event-11910506102
Other common shared methods are found in device plugins such as `cleanup`, `register`.. etc.
However I propose the interface to be as minimal as can be as to not make it difficult to implement on adding a new plugin. extra guidance on if any of these methods are needed in the interface may be required from the project maintainers .
Also there exists an interface called `Device` that implements the same thing in `kubevirt/pkg/virt-handler/device-manager/generic_device.go`. However its unclear whether its required to …
=> add device plugin interface

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
Currently, it is possible to reduce the sockets count of a VirtualMachine object.
Doing so causes the following steps to happen:
1. The VirtualMachineInstance is updated.
2. A migration is triggered.
3. The target virt-launcher pod is created according to the updated VMI.
4. The domain is migrated as-is.
5. On the target virt-launcher pod - the domain is updated to fit.
This works well for CPU hotplug, but is problematic for CPU hotunplug in several scenarios, for example:
1. When using dedicated CPUs
2. When using `networkInterfaceMultiqueue: true`
After this PR:
RestartRequired condition is added on the VM in case the socket count is reduced.
This will make sure the virt-launcher pod and the domain are aligned.
Fixes #
The following …
=> Ctrl, VM: Require restart when socket count is reduced

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
This is an manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/11883
Conflicts with indexer in the test
```release-note
Restart of a VM is required when the CPU socket count is reduced
```
=> [release-1.2] Ctrl, VM: Require restart when socket count is reduced

pkg/virt-operator/resource/apply/reconcile.go, pkg/virt-operator/resource/apply/reconcile_test.go
In many environments, the control-plane nodes are tainted with a NoSchedule effect. Therefore, by default infra pods should tolerate it.
In many environments the `master` key is still being used (e.g. [1]), so I'm adding a toleration for that as well.
[1] https://docs.openshift.com/container-platform/4.15/nodes/scheduling/nodes-scheduler-taints-tolerations.html
Infra components do not tolerate by default control-plane nodes with a NoSchedule taint.
After this PR:
Infra components do tolerate by default control-plane nodes with a NoSchedule taint.
A follow-up to https://github.com/kubevirt/kubevirt/pull/11659
```release-note
Infra components control-plane nodes NoSchedule toleration
```
=> Infra components control-plane nodes NoSchedule toleration

docs/metrics.md, pkg/monitoring/metrics/virt-controller/vmistats_collector.go, pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go, pkg/monitoring/rules/recordingrules/vmi.go, tests/infrastructure/prometheus.go, tests/monitoring/vm_monitoring.go
kubevirt_vmi_phase_count has OS label but doesn't identify VMI, so we cannot use this information to filter VMStorageClassWarning only for VMI with Windows OS reported by the guest.
After this PR:
We create a kubevirt_vmi_info metric, similar to kube_pod_info, that contains detailed information about the workload, including the name and namespace.
We also create a recording rule for kubevirt_vmi_phase_count, that aggregates the new kubevirt_vmi_info by node, phase, os, workload, flavor, instance_type and preference.
Fixes # …
=> Create kubevirt_vmi_info metric

pkg/storage/snapshot/snapshot.go, pkg/storage/snapshot/snapshot_test.go
If unfreeze() continually returns an error, user is unable to delete VMSnapshot
After this PR:
Handle unfreeze() error if VMSnapshot is terminating
Fixes #9998
```release-note
snapshot: Ignore unfreeze error if VMSnapshot deleting
```
=> snapshot: Ignore unfreeze error if VMSnapshot deleting

pkg/storage/export/export/vmsnapshot-source.go, pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_test.go
In case of volumesnapshot missing while in the restore process we are getting to a nil pointer dereference
After this PR:
Handle nil pointer and return error that volumesnapshot missing
Fixes # jira-ticket: https://issues.redhat.com/browse/CNV-42228
```release-note
BugFix: Fix restore panic in case of volumesnapshot missing
```
=> [BUGFIX] Fix restore panic in case of volumesnapshot missing

hack/dockerized
We've stopped using Travis CI for a while now, so it's no longer useful to carry this around.
```release-note
NONE
```
=> dockerized: Remove Travis CI hack

docs/metrics.md, hack/prom-metric-linter/metric_name_linter.sh, pkg/monitoring/metrics/virt-api/connection_metrics.go, pkg/virt-api/rest/console.go, pkg/virt-api/rest/portforward.go, pkg/virt-api/rest/usbredir.go, pkg/virt-api/rest/vnc.go, tests/monitoring/BUILD.bazel, tests/monitoring/metrics.go, tests/monitoring/vm_monitoring.go
Add `kubevirt_vmi_last_api_connection_timestamp_seconds` metric, which reports the last connection timestamp per VMI. Connections covered: console, vnc, usbredir, portforward and SSH.
Fixes https://issues.redhat.com/browse/CNV-14659
This metric will help users to identify VMs that have not been logged into for a long time and have allocated resources but are not actually being used.
```release-note
Add kubevirt_vmi_last_connection_timestamp_seconds metric
```
=> Add a metric that reports the VMI last connection timestamp

tests/vm_test.go
This test is causing 24% impact to the 1.30 sig-compute lane[1] - it qualifies for quarantine.
This flake is likely related to the flake in the adjacent test[2]
[1] https://search.ci.kubevirt.io/?search=A+valid+VirtualMachine+given+Using+virtctl+interface+Using+RunStrategyManual+with+a+failing+VMI&maxAge=48h&context=1&type=all&name=pull-kubevirt-e2e-k8s-1.30-sig-compute&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
[2] https://github.com/kubevirt/kubevirt/pull/11953
Fixes #
/cc @acardace @xpivarc @EdDev  …
=> e2e,quarantine: Quarantine flaky test using RunStrategyManual with a failing VMI

tests/vmi_hook_sidecar_test.go
test "should update domain XML with SM BIOS properties" did not have ID
After this PR:
test "should update domain XML with SM BIOS properties" is having an ID
Fixes #
needed so test can part of tire1 tests
https://github.com/kubevirt/kubevirt/pull/11954
```release-note
NONE
```
=> add test ID for test verify hook annotation updates domainxml

pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
Just fixing a few instances in which the architecture name was misspelled.
```release-note
NONE
```
=> Spell ppc64le correctly

pkg/network/admitter/netiface.go, pkg/network/admitter/netiface_test.go, pkg/network/link/BUILD.bazel, pkg/network/link/mac.go
The mac address validation is currently embedded in the VMI Spec admitter. In order to allow reuse of the mac validation for other specs, the validation logic is extracted out.
Fixes #
```release-note
NONE
```
=> net, admitter: Extract the mac-address validation for reuse

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
A VM with cpu requests and/or limits set could not hotplug vcpus.
After this PR:
A VM with cpu requests and/or limits set can hotplug vcpus.
Fixes #
```release-note
Allow to hotplug vcpus for VMs with CPU requests and/or limits set
```
=> [release-1.2] Allow to set cpu reqs/limits when doing cpu hotplug

OWNERS
The golangci linters are managed through the `.golangci.yml` configuration file.
At the moment, most of the code that is covered by the linter is under the sig-test, sig-compute and sig-network ownership, therefore it would be useful if the approvers on those SIGs will also have "approve" access to accept changes to it.
Fixes #
```release-note
NONE
```
=> OWNERS: Allow test, compute and network SIGs to own `.golangci.yml`

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
check for the returned error as the `vmi` variable being not nil does not necessarily mean that the VMI actually exists.
Because of this bug if you had a VM with `Manual` RunStrategy and you were to start the VM while the DataVolumes were not ready the just issued StartRequest would get trimmed by the virt-controller. To workaround this you'd have to issue a second start request when the DVs would get ready.
Unfortunately, our production and test code differ in this behavior as the production code always returns `vmi != nil` and the fake client returns the `vmi == nil` if the VMI does not exist.
If you had a VM with `Manual` RunStrategy and you were to start the VM while the DataVolumes were not ready the just issued StartRequest would get trimmed by the virt-controller. …
=> ctrl: fix starting VM with Manual RunStrategy

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
check for the returned error as the `vmi` variable being not nil does not necessarily mean that the VMI actually exists.
Because of this bug if you had a VM with `Manual` RunStrategy and you were to start the VM while the DataVolumes were not ready the just issued StartRequest would get trimmed by the virt-controller. To workaround this you'd have to issue a second start request when the DVs would get ready.
Unfortunately, our production and test code differ in this behavior as the production code always returns `vmi != nil` and the fake client returns the `vmi == nil` if the VMI does not exist.
If you had a VM with `Manual` RunStrategy and you were to start the VM while the DataVolumes were not ready the just issued StartRequest would get trimmed by the virt-controller. …
=> [release-1.2] ctrl: fix starting VM with Manual RunStrategy

tests/compute/vmidefaults.go
RunVMAndExpectLaunchWithRunStrategy should be deprecated as it is part of tests_utils.go and use expensive get and update API calls
Instead of Updating VM runStrategy in tests/compute/vmidefaults.go create vm with with the desired runStrategy.
After this PR:
Fixes #
```release-note
NONE
```
=> tests/compute/vmidefaults.go: Remove use of RunVMAndExpectLaunchWithRunStrategy func

docs/metrics.md, pkg/monitoring/metrics/virt-controller/BUILD.bazel, pkg/monitoring/metrics/virt-controller/vmi_metrics.go, pkg/monitoring/metrics/virt-controller/vmi_metrics_test.go, pkg/monitoring/metrics/virt-handler/BUILD.bazel, pkg/monitoring/metrics/virt-handler/virt_handler_suite_test.go, pkg/virt-controller/services/BUILD.bazel, pkg/virt-controller/services/template.go
No visibility over calculate overhead memory for vmi launchers
After this PR:
Metric with  overhead memory for vmi launchers value
jira-ticket: https://issues.redhat.com/browse/CNV-41807
Fixes #
```release-note
Create kubevirt_vmi_launcher_memory_overhead_bytes metric
```
=> Create kubevirt_vmi_launcher_memory_overhead_bytes metric

pkg/virt-operator/resource/apply/apps.go, pkg/virt-operator/resource/apply/apps_test.go
Currently, virt-operator constantly removes the Kubernetes revision
annotation as it is not part of the operator definition in the
installStrategy.
This behavior is incorrect because the Kubernetes control plane keeps
adding the revision annotation back, as it is a system annotation that
should not be handled by virt-operator.
Fixes #
```release-note
NONE
```
=> virt-operator: [BUGFIX] Retain Kubernetes revision annotation

pkg/virt-operator/resource/apply/reconcile.go, pkg/virt-operator/resource/apply/reconcile_test.go
In many environments the `master` key is still being used (e.g. [1]).
[1] https://docs.openshift.com/container-platform/4.15/nodes/scheduling/nodes-scheduler-taints-tolerations.html
Therefore, allow infra pods to be scheduled to such nodes as well.
Follow-up to: https://github.com/kubevirt/kubevirt/pull/11659
See this comment especially: https://github.com/kubevirt/kubevirt/pull/11659#discussion_r1555270580
```release-note
NONE
```
=> Allow infra components to be scheduled to master nodes

.golangci.yml, tests/libnet/BUILD.bazel, tests/libnet/hotplug.go, tests/libnet/mac.go, tests/network/BUILD.bazel, tests/network/bindingplugin.go, tests/network/bindingplugin_macvtap.go, tests/network/hotplug.go, tests/network/hotplug_bridge.go, tests/network/hotplug_sriov.go, tests/network/sriov.go, tests/network/vmi_multus.go
Move helper function from the network tests to `libnet`.
Fixes #
```release-note
NONE
```
=> tests, network:  Move helper function from the network tests to `libnet`

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, pkg/virt-controller/watch/volume-migration/volume-migration_test.go, staging/src/kubevirt.io/api/core/v1/types.go
Currently, if the volumes cannot be live updated we
are setting the `VirtualMachineInstanceVolumesChange` condition
to the vm.
This is wrong for two reasons:
- `VirtualMachineInstanceVolumesChange` is a vmi condition and not a vm condition.
- We need to specify that the vm requires a restart if validateVolume fails
```release-note
NONE
```
/cc @alicefr @vladikr @mhenriks
=> Use restartRequired condition when volumes cannot be updated

tests/monitoring/vm_monitoring.go
Remove any synchronization assumptions from `kubevirt_vmi_last_api_connection_timestamp_seconds` e2e test, which introduced flakiness. Change the test to only check that the metric value gets increased when a connection is being made.
`kubevirt_vmi_last_api_connection_timestamp_seconds` e2e test was flaky.
After this PR:
`kubevirt_vmi_last_api_connection_timestamp_seconds` e2e test is no longer flaky.
```release-note
None
```
=> Fix flaky connection metric test

docs/handling-eviction-requests.md
PR #11532 changed the behavior of the pod eviction webhook.
Update the document to align it with the implementation.
Add an example output of `kubectl drain` command.
Fixes #
```release-note
None
```
=> docs: Update handling eviction requests

pkg/monitoring/metrics/virt-controller/migrationstats_collector.go, tests/monitoring/vm_monitoring.go
`kubevirt_vmi_migration_succeeded` and `kubevirt_vmi_migration_failed` metrics didn't have the VMI namespace label.
After this PR:
`kubevirt_vmi_migration_succeeded` and `kubevirt_vmi_migration_failed` metrics have the VMI namespace label.
Fixes #https://issues.redhat.com/browse/CNV-42622
```release-note
None
```
=> Add the VMI namespace to migration succeeded/failed metrics

pkg/virt-config/feature-gates.go
The network hotplug feature, limited to bridge and SR-IOV binding interfaces has not changed since v1.1. There has been no rejections from the community so far and no special additions are foreseen at the moment
The network hotplug feature has a Feature Gate which is now marked as Beta in the next Kubevirt release (v1.3).
This change also updates the documentation in a retrospective to specify that it was in Alpha from its introduction in v1.1
User guide has been updated here: https://github.com/kubevirt/user-guide/pull/806
Fixes # …
=> net, hotplug: Mark network hotplug feature as Beta

pkg/storage/export/export/vmsnapshot-source.go, pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_test.go
This is a manual cherry-pick of PR: https://github.com/kubevirt/kubevirt/pull/11996
```release-note
BugFix: Fix restore panic in case of volumesnapshot missing
```
=> [release-1.1][BUGFIX] Fix restore panic in case of volumesnapshot missing

tests/operator/operator.go
Get rid of several lambda functions from tests/operator/operator.go
operator.go is a single file in its package. There is no reason to use lambdas there, because there is no risk for naming pollution, as there are no other files in this package.
Some of the functions are only used once - then this PR drops them and copies their logic to the relevant tests. Other lambdas are now regular functions.
```release-note
None
```
=> Start dropping lambdas from operator.go

pkg/storage/export/export/vmsnapshot-source.go, pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_test.go
This is a manual cherry-pick of PR: https://github.com/kubevirt/kubevirt/pull/11996
```release-note
BugFix: Fix restore panic in case of volumesnapshot missing
```
=> [release-1.0][BUGFIX] Fix restore panic in case of volumesnapshot missing

tests/storage/guestfs.go
The tests were using their own FS creation function that was not using the RWOFilesystem configuration and using the default storage class. 
After this PR:
Replaced that with the libstorage function that uses the RWOFilesystem to determine the correct storage class to use.
Fixes #
```release-note
NONE
```
=> Use libstorage to create FS PVC in guestfs tests

pkg/testutils/BUILD.bazel, pkg/testutils/mock_queue.go, pkg/virt-controller/watch/BUILD.bazel, pkg/virt-controller/watch/vm_test.go
Remove informers in order to simplify test setup. This also improve test runtime from ~15 seconds down to ~0.2 seconds.
Fixes #
```release-note
NONE
```
=> VM unit tests, remove informers

pkg/virt-controller/watch/vm.go
This patch fixes the test test_id:6867 when LiveUpdate is used as a rollout-strategy.
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/2846/pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp/1798844855967813632
MaxSockets was not considering CPU requests, this fixes it.
Test 'test_id:6867' fails with LiveUpdate as rollout-strategy.
After this PR:
Test 'test_id:6867' passes with LiveUpdate as rollout-strategy.
Fixes # …
=>  [release-1.2] ctrl: fix MaxSockets calculation

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, tests/vm_test.go
Since https://github.com/kubevirt/kubevirt/pull/10383, any delete request to a VM object sets the VMI's terminationGracePeriodSeconds to 0,
effectively bypassing graceful deletion via `libvirt.DOMAIN_SHUTDOWN_ACPI_POWER_BTN`;
This happens because the `GracePeriodSeconds` delete option does not apply to custom CRs (https://github.com/kubernetes/kubernetes/issues/56567#issuecomment-557536904), so `meta.DeletionGracePeriodSeconds` ends up being 0,
and thus we're effectively propagating a 0 to the VMI any time the VM has a deletion timestamp. https://github.com/kubevirt/kubevirt/blob/a7e0311d8704663351abd4bc9bbc8511753d2838/pkg/virt-controller/watch/vm.go#L1628-L1629
Fixes #
Links to places where the discussion …
=> Fix non-graceful termination of domain when deleting VM object

pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go, pkg/virt-launcher/virtwrap/cli/libvirt.go, pkg/virt-launcher/virtwrap/manager_test.go
Following PR #8820, VirDomain.GetMetadata is no longer used by production code.
After this PR:
Remove it from unit tests and remove its generated mock.
Fixes #
https://kubernetes.slack.com/archives/C0163DT0R8X/p1713438588741539
This is a follow-up to PR https://github.com/kubevirt/kubevirt/pull/11746.
```release-note
NONE
```
=> virt-launcher: Remove VirDomain.GetMetadata

manifests/generated/operator-csv.yaml.in, manifests/generated/rbac-operator.authorization.k8s.yaml.in, pkg/virt-operator/resource/generate/rbac/operator.go, pkg/virt-operator/resource/generate/rbac/operator_test.go
virt-operator collects rules from virt-* Roles and ClusterRoles under its ClusterRole
After this PR:
virt-operator collects rules from virt-* Roles under its Role and ClusterRoles under its ClusterRole
Fixes #
```release-note
Less privileged virt-operator ClusterRole
```
=> Collect component Role rules under operator Role instead of ClusterRole

pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go, pkg/virt-launcher/virtwrap/access-credentials/BUILD.bazel, pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go, pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go, tests/compute/credentials.go
The old way is not needed, because used libvirt version supports the new command.
This commit also fixes a bug, where virt-handler was checking availability of incorrect guest agent commands.
Fixes: https://issues.redhat.com/browse/CNV-38523
```release-note
None
```
=> virt-launcher: Fix SSH propagation command check for AgentVersionNotSupported condition

tests/infrastructure/node-labeller.go
We are setting `kubevirt.configuration.ObsoleteCPUModels` to nil to align with test expectations. The test assumes that `kubevirt.configuration.ObsoleteCPUModels` is not set. 
Before this PR, if `kubevirt.configuration.ObsoleteCPUModels` was set before the tests started running, then the test would fail. 
After this PR, if `kubevirt.configuration.ObsoleteCPUModels` was set before the tests started running, it will be set to nil to prevent failure.
Additionally, we will wait for 30 seconds before failing to give the node labeller enough time to set the new labels on the nodes.
Fixes # …
=> tests/node_labeller.go: Fix test_id: 6247

tests/monitoring/vm_monitoring.go
test wasnt having ID
After this PR:
test have an ID
Fixes #
adding testID so test can be part if T1
https://github.com/kubevirt/kubevirt/pull/11283
```release-note
None
```
=> add testID for kubevirt_vmi_info correctly configured with guest OS labels

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
After this PR:
Fixes #11305
This refactoring of validateDisks function reduces the length of the function, improves readbility, improves maintainability and preserves the same functionality. It was done this way to reduce the number of nested conditions, nested loops, and code duplication.
Links to places where the discussion took place: https://github.com/kubevirt/kubevirt/issues/11305
```release-note
NONE
```
=> Refactor validateDisks function to improve readability

pkg/virt-api/rest/BUILD.bazel, pkg/virt-api/rest/subresource.go, pkg/virt-api/rest/subresource_test.go, pkg/virt-api/webhooks/mutating-webhook/mutators/clone-create-mutator.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
Hardcoded operation in virt-api package.
Replaced all the patch operations with the `patch.PatchSet` in the virt-api package.
Fixes #
Partially address: https://github.com/kubevirt/kubevirt/issues/11654
**N.B.**
The vmi mutation webhook now does not return the patch
field if no patch are requested. Previously, it always
returns a patch, eventually "null".
```release-note
NONE
```
/cc @alicefr @0xFelix
=> virt-api: replace hardcoded patch operations with patchset

pkg/virt-api/webhooks/arm64.go
After this PR:
fix some function names
```release-note
None
```
=> chore: fix some function names

pkg/virt-config/feature-gates.go
/sig api
/cc @fabiand 
/cc @0xFelix 
/cc @EdDev 
/cc @alaypatel07
Apologies for the mass `/cc` here but I'd appreciate your thoughts on doing this retrospectively given it's purely a documentation change from alpha to beta at the moment.
With the feature lifecycle discussion [1] heading towards consensus this change retrospectively moves the CommonInstancetypesDeploymentGate to Beta from 1.2.0 with an eye on moving to GA and removal of the FG by 1.4.0.
This is done retrospectively as the FG itself is now enabled by default by HCO with KubeVirt 1.2 and as such is already meeting the criteria of the beta phase defined by the feature lifecycle document.
As this is purely documentation the impact of this change is zero and just helps us move the process forward in the …
=> feature-gates: Retrospectively document CommonInstancetypesDeploymentGate as Beta from 1.2.0

pkg/virt-api/webhooks/defaults.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-controller/watch/vm.go
Check that guest memory is set before accessing it.
Creating a VM with hugepages set with no `domain.guest.memory` (so memory is set using requests) will crash virt-api. 
After this PR:
Creating a VM with hugepages set with no `domain.guest.memory` (so memory is set using requests) does not crash virt-api. 
Fixes #
Captured panic using KubeVirt v1.2, here virt-controller crashes because the code has been moved from there
```
{"component":"virt-controller","kind":"DataVolume","level":"error","msg":"Cant find the matching VM for DataVolume: dv1-rhel-ocs","name":"dv1-rhel-ocs","namespace":"default","pos":"vm.go:2141","timestamp":"2024-06-12T14:06:56. …
```
=> virt-api: fix panic in setupMemoryHotplug()

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/converter_test.go
A VM configured with memory hotplug and hugepages does not start
After this PR:
A VM configured with memory hotplug and hugepages starts correctly
Fixes #
```release-note
Support Memory Hotplug with Hugepages
```
=> Support Memory Hotplug with Hugepages

pkg/virt-controller/watch/vm.go
Check that guest memory is set before accessing it.
Creating a VM with hugepages set with no `domain.guest.memory` (so memory is set using requests) will crash virt-controller. 
After this PR:
Creating a VM with hugepages set with no `domain.guest.memory` (so memory is set using requests) does not crash virt-controller. 
Fixes #
Captured panic using KubeVirt v1.2
```
{"component":"virt-controller","kind":"DataVolume","level":"error","msg":"Cant find the matching VM for DataVolume: dv1-rhel-ocs","name":"dv1-rhel-ocs","namespace":"default","pos":"vm.go:2141","timestamp":"2024-06-12T14:06:56.369402Z","uid":"b56e99bf-12e8-4730-84a9-8e0ea026a823"} …
```
=> [release-1.2] virt-api: fix panic in setupMemoryHotplug()

tests/replicaset_test.go
the `should replace a VMI immediately when a virt-launcher pod gets deleted` in 
replicaset_test.go had a little bit of code not using libvmi 
After this PR:
the `should replace a VMI immediately when a virt-launcher pod gets deleted` in 
replicaset_test.go uses only libvmi.
partially address #12059
```release-note
NONE
```
=> moved replicaset_test.go to use libvmi

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
Fix panic when creating a VMPool with vmRolloutStrategy set to 'LiveUpdate'.
```
{"component":"virt-api","level":"info","msg":"http: panic serving 192.168.66.101:28276: runtime error: invalid memory address or nil pointer dereference\ngoroutine 654 [running]:\nnet/http.(*conn).serve.func1()\n\tGOROOT/src/net/http/server.go:1898 +0xbe\npanic({0x21d51e0?, 0x3e47530?})\n\tGOROOT/src/ru
ntime/panic.go:770 +0x132\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook/admitters.validateLiveUpdateCPU(0xc000cac120?, 0x0?)\n\tpkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:509 +0x1e\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook/admitters.validateL
iveUpdateFeatures(0xc003604120, 0xc00044aae8, 0xc000cac120)\n\tpkg/virt-api/webhooks/validating-webhook/admit …
```
=> virt-api: fix panic

pkg/virtctl/imageupload/BUILD.bazel, pkg/virtctl/imageupload/imageupload_test.go, tests/BUILD.bazel, tests/clone_test.go, tests/libstorage/BUILD.bazel, tests/libstorage/datavolume.go, tests/libstorage/image.go, tests/migration/BUILD.bazel, tests/migration/migration.go, tests/storage/datavolume.go, tests/storage/export.go, tests/storage/hotplug.go, tests/storage/imageupload.go, tests/storage/memorydump.go, tests/storage/restore.go, tests/storage/snapshot.go, tests/storage/storage.go, tests/utils.go, tests/virtiofs/datavolume.go, tests/vm_test.go
This PR aims to clean up most of the storage-specific functions in `tests/utils.go`, so we move the logic to the specific tests instead of condensing all functions into a single file.
This PR makes the following changes:
- `NewRandomVirtualMachineInstanceWithBlockDisk` has been removed from `tests/utils.go`. It's been substituted by equivalent functions in the tests that used it.
- `NewRandomVMWithDataVolumeWithRegistryImport` has been removed from `test/utils.go`. It's been substituted by `RenderVMWithRegistryImportDataVolume` in  `tests/storage/datavolume.go`.
- `NewRandomVirtualMachineInstanceWithDisk` has been removed from `test/utils.go`. No need for a substitute since this function wasn't used outside this file.
- `ChangeImgFilePermissionsToNonQEMU` and `ArchiveToFile` have been …
=> Clean up storage functions in tests/utils.go

tests/storage/datavolume.go, tests/storage/export.go, tests/storage/restore.go, tests/storage/snapshot.go
Use the PatchSet struct from the patch package to replace hardcoded jsonpatch operations to improve readability, in the tests/storage package.
Hardcoded jsonpatches in the tests/storage package.
After this PR:
All hardcoded jsonpatches were updated to use `patch.patchSet` type, for readability and maintainability .
Fixes #
```release-note
NONE
```
=> tests/storage: Replace hardcoded patch operations with patchset

tests/monitoring/metrics.go, tests/storage/hotplug.go, tests/utils.go
Remove the following repetitive code:
```go
Eventually(func() bool {
vm, err := virtClient.VirtualMachine(testsuite.GetTestNamespace(vm)).Get(context.Background(), vm.Name, metav1.GetOptions{})
Expect(err).ToNot(HaveOccurred())
return vm.Status.Ready
}, 300*time.Second, 1*time.Second).Should(BeTrue())
```
and use instead:
`Eventually(ThisVM(vm)).WithTimeout(300 * time.Second).WithPolling(time.Second).Should(BeReady())`
```release-note
None
```
=> tests: Simplify waiting for VM to become ready

pkg/storage/export/export/BUILD.bazel, pkg/storage/export/export/export.go, pkg/storage/export/export/export_test.go, pkg/storage/export/virt-exportserver/exportserver.go, pkg/virtctl/memorydump/memorydump.go, pkg/virtctl/vmexport/vmexport.go, pkg/virtctl/vmexport/vmexport_test.go
An issue with the hotplug pod termination/export pod creation caused the memory dump to lack sufficient permissions to be manipulated by the server. This uncommon bug is usually solved automatically when restarting the exporter pod. 
This Pull Request introduces the two following changes:
- Improves handling of error cases in export server so we return appropriate status codes when the server lacks permission to read the files. The server will also shut down if it lacks open file permissions during initialization. The pod will be recreated automatically by the export controller.
- Adds a new flag in the vmexport client so we can specify the number of download retries if the server returns a bad status, helping to mitigate the previously described bug.
Fixes # …
=> Implement retries in vmexport download when server returns unexpected status

pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go, pkg/virt-launcher/virtwrap/access-credentials/BUILD.bazel, pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go, pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go, tests/compute/credentials.go
This is a manual backport of: https://github.com/kubevirt/kubevirt/pull/11652 .
There were no changes, only the bot could not cherry-pick it automatically.
This PR fixes a bug where virt-handler was checking availability of incorrect guest agent commands.
Fixes: https://issues.redhat.com/browse/CNV-38523
```release-note
None
```
=> [release-1.2] virt-launcher: Fix SSH propagation command check for AgentVersionNotSupported condition

WORKSPACE
chore: bump virtio-win image version to 0.1.248
The old version 0.1.217-1 is not working on newest win11 - it fails to install pvpanic package.
```release-note
chore: bump virtio-win image version to 0.1.248
```
=> chore: bump virtio-win image version to 0.1.248

docs/coding-conventions.md
Update the coding conventions with the right way of using context with ginkgo.
See also #12140
```release-note
None
```
=> Use ginkgo's contexts - update the coding-conventions

staging/src/kubevirt.io/api/core/v1/defaults.go, staging/src/kubevirt.io/client-go/api/defaults_test.go, tests/network/vmi_lifecycle.go
PR https://github.com/kubevirt/kubevirt/pull/2405 removed this function from the default VMI configuration and moved its usage to another place.
It had only two usages left in the network e2e tests.
After this PR:
- The last two usages of the function are removed from network e2e tests.
- The function and its unit tests are removed.
Fixes #
```release-note
NONE
```
=> api, defaults: Remove SetDefaults_NetworkInterface

api/openapi-spec/swagger.json, pkg/instancetype/instancetype.go, pkg/instancetype/instancetype_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/instancetype/v1beta1/types.go, staging/src/kubevirt.io/api/instancetype/v1beta1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go
/cc @alromeros
/cc @alicefr
54ae532f7241edf393ed79882010fe7f73af7bdf (#11219) recently started to reject requests containing all non-virtio disks with dedicatedIoThreads enabled. This expanded on the previous check on SATA disks.
This change brings the PreferredDiskDedicatedIoThread preference in line with this and ensures that we only apply the preference to virtio disks.
Fixes #
```release-note
`PreferredDiskDedicatedIoThread` is now only applied to `virtio` disk devices
```
=> preference: Only apply PreferredDiskDedicatedIoThread to virtio disks

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
As set out in https://github.com/kubevirt/kubevirt/issues/12158 CurrentCPUTopology was previously being defined
before instance types were applied to the VMI. As a result the default
values for sockets, cores and threads of 1 would be used and could end
up with the HotVCPUChange condition later being applied if LiveUpdates
are enabled.
This change resolves this issue by breaking out the setup of
CurrentCPUTopology into a standalone function that is called once
instance types have been applied to the VMI.
Fixes #12158
This fix is based on https://github.com/kubevirt/kubevirt/pull/12152 …
=> [release-1.2] controller: Setup CurrentCPUTopology after applying instance types

automation/test.sh, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/migration_test.go, tests/decorators/decorators.go, tests/hotplug/memory.go
This fixes a bug where you cannot hotplug successfully when using hugepages due to virt-launcher being tricked into thinking that the target pod does not have enough memory to accomodate the new VMI with additional hotplugged memory.
Doing memory hotplug with hugepages gets the hotplug migration stuck indefinitely. 
After this PR:
Doing memory hotplug with hugepages works as expected.
Fixes #
```release-note
NONE
```
=> mem-hotplug: fix target pod requests calculation with hugepages

pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/converter_test.go
The IO policy was always wrongly set to threads when the iothread option was enabled for scsi disks.
This was part of https://github.com/kubevirt/kubevirt/pull/6425. I also tried to reproduce the original bug of the PR and I could successfully hotplug a volume.
The io policy was always set to `threads` when iothread where enable
```yaml
domain:
ioThreadsPolicy: auto
devices:
disks:
- disk:
bus: scsi 
name: containerdisk
io: native
```
and verify the yaml:
```xml
<disk type='file' device='disk'>
<driver name='qemu' type='qcow2' cache='none' error_policy='stop' io='threads' discard='unmap'/>
<source file='/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2' index='2'/>
<backingStore type='file' index='3'>
<format type='qcow2'/>
<source …
```
=> converter: fix IO policy overwrite

automation/test.sh, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/migration_test.go, tests/decorators/decorators.go, tests/hotplug/memory.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/12168.
This fixes a bug where you cannot hotplug successfully when using hugepages due to virt-launcher being tricked into thinking that the target pod does not have enough memory to accomodate the new VMI with additional hotplugged memory.
Doing memory hotplug with hugepages gets the hotplug migration stuck indefinitely. 
After this PR:
Doing memory hotplug with hugepages works as expected.
Fixes #
```release-note
NONE
```
=> [release-1.2] mem-hotplug: fix target pod requests calculation with hugepages

tests/operator/BUILD.bazel, tests/operator/operator.go
Change several lambdas in tests/operator/operator.go, to be regular functions. Also, change all patch implementation to use the patch package.
```release-note
None
```
=> tests/operator: Use patch package in operator

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
This is a manual backport of https://github.com/kubevirt/kubevirt/pull/12180 to `release-1.2`.
This change adds the restart required condition to VMs when NetworkInterfaceMultiqueue is enabled to prevent failures when trying to change existing tap devices.
Conflicts:
pkg/virt-controller/watch/vm.go
Note:
The conflict is due to an instancetypes related change that is not
present in release-1.2.
Fixes #
```release-note
VMs with a single socket and NetworkInterfaceMultiqueue enabled require a restart to hotplug additional CPU …
```
=> [release-1.2] fix: Add restart condition when network interface multiqueue is enabled

cmd/virt-exportserver/BUILD.bazel, pkg/storage/export/export/BUILD.bazel, pkg/storage/export/export/export.go, pkg/storage/export/export/export_test.go, pkg/storage/export/virt-exportserver/BUILD.bazel, pkg/storage/export/virt-exportserver/exportserver.go
This is a manual backport of https://github.com/kubevirt/kubevirt/pull/11911.
The vmexport integration has been removed from this backport since it's just an additional flag that helps mitigate transient server errors. This backport only covers the readiness probe and retry mechanism in export server.
Fixes # https://issues.redhat.com/browse/CNV-43125
```release-note
Bugfix: Implement retry mechanism in export server
```
=> [release-1.0] Manual backport of implement retries in export server

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, tests/hotplug/memory.go
This test proved to be a bit flaky
https://search.ci.kubevirt.io/?search=Memory+Hotplug+A+VM+with+memory+liveUpdate+enabled+should+successfully+hotplug+memory+twice&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job.
This makes sure we wait for the migration to have succeeded before inspecting the domain XML, otherwise the domain might not be running yet.
After this PR:
Fixes #
```release-note
NONE
```
=> mem-hotplug: fix flaky test and small issues

pkg/storage/export/export/BUILD.bazel, pkg/storage/export/export/export.go, pkg/storage/export/export/export_test.go, pkg/storage/export/virt-exportserver/BUILD.bazel, pkg/storage/export/virt-exportserver/exportserver.go
This is a manual backport of https://github.com/kubevirt/kubevirt/pull/11911.
The vmexport integration has been removed from this backport since it's just an additional flag that helps mitigate transient server errors. This backport only covers the readiness probe and retry mechanism in export server.
Fixes # https://issues.redhat.com/browse/CNV-43124
```release-note
Bugfix: Implement retry mechanism in export server
```
=> [release-1.1] Manual backport of implement retries in export server

pkg/storage/export/export/BUILD.bazel, pkg/storage/export/export/export.go, pkg/storage/export/export/export_test.go, pkg/storage/export/virt-exportserver/BUILD.bazel, pkg/storage/export/virt-exportserver/exportserver.go, pkg/virtctl/memorydump/memorydump.go, pkg/virtctl/vmexport/vmexport.go, pkg/virtctl/vmexport/vmexport_test.go
This is a manual backport of https://github.com/kubevirt/kubevirt/pull/11911.
Couldn't create an automatic cherry-pick since I had to address some conflicts with older vmexport flags.
Fixes # https://issues.redhat.com/browse/CNV-43123
```release-note
Bugfix: Implement retry mechanism in export server and vmexport
```
=> [release-1.2] Manual backport of implement retries in export server

pkg/virt-handler/vm.go, tests/migration/migration.go
Simplify IsoGuestVolumePath:
**1. Remove vmi as parameter**
2. Use const for constant variable
3. Use switch for if-else construct
4. Inline return
5. 
Fixes #
```release-note
NONE
```
=> Simplify IsoGuestVolumePath

cmd/virt-exportproxy/virt-exportproxy.go, pkg/storage/backend-storage/backend-storage_test.go, pkg/testutils/mock_config.go, pkg/util/tls/tls.go, pkg/util/tls/tls_test.go, pkg/virt-api/rest/profiler_test.go, pkg/virt-api/rest/subresource_test.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmexport-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter_test.go, pkg/virt-config/configuration_test.go, pkg/virt-controller/services/template_test.go, pkg/virt-controller/services/virtiofs_test.go, pkg/virt-controller/watch/vm_test.go, pkg/virt-controller/watch/vmi_test.go, pkg/virt-handler/device-manager/mediated_device_test.go, pkg/virt-handler/device-manager/mediated_devices_types_test.go, pkg/virt-handler/device-manager/pci_device_test.go
virt-exportproxy does not need the informers, but the stores are enough.
Simplifies the interface used to the bare minimum.
Fixes #
This PR also addresses https://github.com/kubevirt/kubevirt/pull/12047#pullrequestreview-2110264819 
```release-note
NONE
```
/cc @xpivarc @alicefr
=> virt-exportproxy: use stores instead of informers

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
When a VM with RerunOnFailure as RunStrategy is created with a DataVolume the VM would get stuck in Provisioning and never start even after the DV succeeded, this patch fixes this bug.
When a VM with RerunOnFailure as RunStrategy is created with a DataVolume the VM would get stuck in Provisioning and never start even after the DV succeeded.
After this PR:
The VM correctly starts after provisioning.
Fixes #
```release-note
fix RerunOnFailure stuck in Provisioning
```
=> vm: fix RerunOnFailure stuck in Provisioning

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
Manual cherrypick of https://github.com/kubevirt/kubevirt/pull/12193.
When a VM with RerunOnFailure as RunStrategy is created with a DataVolume the VM would get stuck in Provisioning and never start even after the DV succeeded, this patch fixes this bug.
When a VM with RerunOnFailure as RunStrategy is created with a DataVolume the VM would get stuck in Provisioning and never start even after the DV succeeded.
After this PR:
The VM correctly starts after provisioning.
Fixes #
```release-note
fix …
```
=>  [release-1.2] vm: fix RerunOnFailure stuck in Provisioning

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-launcher/virtwrap/device/hostdevice/BUILD.bazel, pkg/virt-launcher/virtwrap/device/hostdevice/hostdev.go, pkg/virt-launcher/virtwrap/device/hostdevice/hostdev_test.go
VMs would fail to start VM when multiple vGPUs are configured with ramfb.
After this PR:
Only a single vgpu display option with ramfb will be configured per VMI.
Fixes # CNV-42218
```release-note
Only a single vgpu display option with ramfb will be configured per VMI.
```
=> [BugFix] Configure a single vGPU display with ramfb

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/11341
```release-note
NONE
```
=> [release-1.1] Remove redundant DeepCopy calls

tests/operator/operator.go
tests/operator/operator.go defines many lambda function. This can be confusing, hard to read and hard to debug.
After this PR:
Several lambdas removed and replaced with inline code, and several others moved to be regular functions.
```release-note
None
```
=> Remove several lambda functions from tests/operator

tests/vmi_configuration_test.go
This test no longer appears to be flaky[1] and is passing in the periodic lanes. It can be removed from quarantine.
[1] https://search.ci.kubevirt.io/?search=test_id%3A1672&maxAge=336h&context=1&type=all&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
```release-note
NONE
```
=> e2e,compute: Remove hugepages-2mi test from quarantine

WORKSPACE, pkg/liveupdate/memory/memory.go, pkg/liveupdate/memory/memory_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-controller/watch/vm_test.go, tests/hotplug/memory.go, tests/vmi_configuration_test.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/12212.
The 1GiB mark is chosen as a tradeoff, it is enough memory for the guest kernel to allocate its internal data structures and to allocate the SWIOTLB.
It also means we can memory map all PCI devices
as they're memory mapped in the first 1Gi (PCI hole).
If there are 32bit devices that need to do DMA,
the kernel will allocate memory for the SWIOTLB, which is a bounce buffer to address memory after the 4Gi Mark, the SWIOTLB in Linux at the moment of this commit is 64MB and this causes an issue for the kernel with VMs with very small amounts of memory, if not enough memory is available this can lead to the guest kernel panicking while trying to allocate memory.
This SWIOTLB issue is present when setting `maxMemory` (which is …
=> [release-1.2] mem-hotplug: enable only for VMs with memory >= 1Gi

tools/perfscale-audit/api/api.go, tools/perfscale-audit/metric-client/metric-client.go
Before this PR: There are no benchmarks for cpu/memory utilization
After this PR: Added cpu/memory utilisation of virt api and virt controller benchamarks
Fixes #
```release-note
Add CPU/Memory utilization of components metrics to kubevirt benchmarks
```
=> Add memory/cpu utilization of components to kubevirt benchmarks

cmd/virt-handler/virt-handler.go, pkg/virt-handler/rest/common.go, pkg/virt-handler/rest/console.go, pkg/virt-handler/rest/lifecycle.go, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go
Remove the usage of the informers in the virt-handler controllers.
There is no need to hold informers, narrowing down
the interface can decrease the probability of making
a mistake.
Fixes #
```release-note
NONE
```
/cc @xpivarc
=> Remove informer usages from virt-handler

pkg/libvmi/network.go, pkg/network/vmispec/BUILD.bazel, pkg/network/vmispec/defaults.go, pkg/network/vmispec/defaults_test.go, pkg/virt-api/webhooks/BUILD.bazel, pkg/virt-api/webhooks/defaults.go, pkg/virt-config/virt-config.go, pkg/virt-controller/watch/vm.go, tests/network/vmi_networking.go
Currently, the logic that decides whether to automatically attach the pod network to a VMI - is a method of `virtconfig.ClusterConfig`.
After this PR:
This logic was moved under sig-network's ownership.
Unit tests were added.
Fixes #
```release-note
NONE
```
=> virt-config: Extract pod network attachment logic

api/openapi-spec/swagger.json, pkg/instancetype/BUILD.bazel, pkg/instancetype/instancetype.go, pkg/instancetype/instancetype_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/instancetype/v1beta1/types.go, staging/src/kubevirt.io/api/instancetype/v1beta1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go
/cc @alicefr 
/cc @0xFelix 
54ae532f7241edf393ed79882010fe7f73af7bdf recently started to reject requests containing all non-virtio disks with dedicatedIoThreads enabled. This expanded on the previous check on SATA disks.
This change brings the PreferredDiskDedicatedIoThread preference in line with this and ensures that we only apply the preference to virtio disks.
https://issues.redhat.com/browse/CNV-42700
```release-note
`PreferredDiskDedicatedIoThread` is now only applied to `virtio` disk devices
```
=> [release-1.2] preference: Only apply PreferredDiskDedicatedIoThread to virtio disks

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-launcher/virtwrap/device/hostdevice/BUILD.bazel, pkg/virt-launcher/virtwrap/device/hostdevice/hostdev.go, pkg/virt-launcher/virtwrap/device/hostdevice/hostdev_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/12053
```release-note
Only a single vgpu display option with ramfb will be configured per VMI.
```
=> [release-1.3] Configure a single vGPU display with ramfb

cmd/virt-handler/BUILD.bazel, cmd/virt-handler/virt-handler.go, pkg/monitoring/metrics/common/client/client_test.go, pkg/monitoring/metrics/common/client/metrics.go, pkg/virt-api/BUILD.bazel, pkg/virt-api/api.go, pkg/virt-controller/watch/BUILD.bazel, pkg/virt-controller/watch/application.go, pkg/virt-operator/BUILD.bazel, pkg/virt-operator/application.go, tests/monitoring/metrics.go
`kubevirt_rest_client_requests_total` was missing datapoints for some resources such as VMIs
After this PR:
`kubevirt_rest_client_requests_total` has data for all tracked resources
Fixes #
```release-note
Fix missing performance metrics for VMI resources
```
=> Fix missing performance metrics for VMI resources

tests/libstorage/BUILD.bazel, tests/libstorage/datavolume.go, tests/libstorage/vmi.go, tests/storage/hotplug.go, tests/storage/snapshot.go, tests/storage/storage.go
We have usage of this scattered around, let's unify and use it more instead of guessing the device name.
Fixes #
```release-note
NONE
```
=> tests: add helper for finding target volume path inside guest

tests/BUILD.bazel, tests/infrastructure/certificates.go, tests/libinfra/BUILD.bazel, tests/libinfra/certificates.go, tests/operator/BUILD.bazel, tests/operator/operator.go, tests/utils.go
cert related functions are in test.utils.
After this PR:
cert realted function moved to libinfra, following the example of https://github.com/kubevirt/kubevirt/commit/3edd103d4adeb1d8fb01b3d4c600d9076bc5a1f6
Fixes #
```release-note
NONE
```
=> tests: Move cert functions

pkg/libvmi/cloudinit/cloudinit.go, tests/BUILD.bazel, tests/migration/migration.go, tests/network/sriov.go, tests/storage/hotplug.go, tests/utils.go
Having cloud-init functions in tests/utils
After this PR:
Moved and adjusted the functions used to libvmi, adjusted code accordingly.
Functions:
AddCloudInitConfigDriveData -> WithCloudInitConfigDriveData, WithCloudInitConfigEncodedDriveData
AddUserData -> deleted (replaced with already existing one)
addCloudInitDiskAndVolume -> deleted
Fixes #
```release-note
NONE
```
=> tests, libvmi: move adjust and delete cloudinit function from tests/utils to libvmi

pkg/virt-controller/services/renderresources_test.go
PR #11915 removed the test body of:
"when the vmi requests interfaces with Passt binding" which used to test logic related to the discontinued passt binding.
Remove it, as it is now a leftover.
After this PR:
Fixes #
```release-note
None
```
=> virt-controller: Remove empty passt test

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-launcher/virtwrap/device/hostdevice/BUILD.bazel, pkg/virt-launcher/virtwrap/device/hostdevice/hostdev.go, pkg/virt-launcher/virtwrap/device/hostdevice/hostdev_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/12053
```release-note
Only a single vgpu display option with ramfb will be configured per VMI.
```
=> [release-1.2] Configure a single vGPU display with ramfb

tests/libsecret/secret.go, tests/testsuite/BUILD.bazel, tests/testsuite/namespace.go, tests/util/labels.go
The label "kubevirt.io/secret" used in e2e tests to mark secret that should be deleted before each test by the global test suite cleanup.
After this PR:
Remove the label definition from utilis/lables.go and export the one at libsecret package.
Fixes #
```release-note
NONE
```
=> utils, labels: Move tests secret label to libsecret

pkg/libvmi/cloudinit.go, tests/libvmifact/factory.go, tests/utils.go, tests/vmi_cloudinit_test.go
The NewRandomVMIWithEphemeralDiskAndConfigDriveUserdata is deprecated
After this PR:
NewRandomVMIWithEphemeralDiskAndConfigDriveUserdata was removed, and replaced by calls to the libvmi functions.
```release-note
None
```
=> Remove the deprecated function NewRandomVMIWithEphemeralDiskAndConfigDriveUserdata

manifests/generated/operator-csv.yaml.in, manifests/generated/rbac-operator.authorization.k8s.yaml.in, pkg/virt-operator/resource/generate/rbac/cluster.go, tests/access_test.go
The fact that this is missing makes it unusuable for a developer persona with admin rights in their own namespace.
So, as is, only cluster-admin could passthrough a client USB.
Fixes #
https://issues.redhat.com/browse/CNV-43200
```release-note
BugFix: Grant namespace admin RBAC to passthrough a client USB to a VMI
```
=> Grant namespace admin RBAC to passthrough a client USB to a VMI

pkg/emptydisk/BUILD.bazel, pkg/emptydisk/emptydisk_test.go
=> Refactor unit tests to use libvmi for resource creation in emptydisk

pkg/virt-controller/services/rendervolumes.go
Currently, the backend storage state pod volume
name is generated from the vmi name.
Pod Volume names must respect [RFC 1123 Label Names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names).
Using the vmi name is not correct since the latter must respect [DNS Subdomain Names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names),
which is more relaxed compared with the first one.
This can cause an unschedulable pod in the following cases:
- the vmi name contains dots(".")
- the resulting volume name has a length > 63
Besides that, there is no reason to reference the vmi name inside the pod volume name,
since they must be unique just inside the container pod.
Let's just use a fixed name `vm-state`, as we already …
=> backendstorage: use fixed volume name

pkg/storage/snapshot/restore.go
When old pvc had pv selector, new pvc should not include it.
=> LabelSelector should not be added while restoring pvc

hack/build-go.sh, pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
unit tests on s390x where not working, as with `make go-test` it runs the fuzz test. Additionally memory-hotplug tests where failling
After this PR:
unit-tests are passing for s390x
Fixes #
fuzz testing was disabled for s390x.
Finding an alternative way to allow fuzz tests to run only when specifically triggered. However i did not find any method that works on both golang and bazel testing.
Additionally, simply enabling memory-hotplug on s390x would have fixed the failling tests, however the feature itself is not working on s390x, likely because it uses live-migration. …
=> s390x: Fix unit tests on s390x for memory-hotplug and disable fuzz testing

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, tests/vm_test.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/12064
Fixes #
```release-note
BugFix: Graceful deletion skipped for any delete call to the VM (not VMI) resource
```
=> [release-1.1] Fix non-graceful termination of domain when deleting VM object

hack/prom-rule-ci/prom-rules-tests.yaml, pkg/monitoring/rules/alerts/vms.go
There is an edge case, usually during an upgrade, in which two or more different virt-controllers are reporting the `kubevirt_vmi_migration_succeeded` metric for the same migration (VMIM) on the same VMI. In that case, we need to count that migration only once regardless of it being reported multiple times for the purpose of firing the alert about excessive amount of migrations in the last 24 hours. The new PromQL isolates the entries with different VMIMs, then sets the value of '1' to all of them, and then we're summing by the pair of vmi and its namespace.
Jira-ticket: https://issues.redhat.com/browse/CNV-40981 …
=> monitoring: Fix wrong calculation for `KubeVirtVMIExcessiveMigrations` in an edge case

tests/network/bindingplugin_macvtap.go
No need to place a variable in a big scope when it is needed only in a smaller one. In the wider scope it may be mistakenly overwritten by a future test.
```release-note
NONE
```
=> test/network: avoid a var with a large context

tests/storage/storage.go, tests/vmi_configuration_test.go
Job and Pod are two distinct Kubernetes resources. When a Pod is returned, let us not call it a "job".
```release-note
NONE
```
=> tests: avoid a misleading variable name

api/openapi-spec/swagger.json, manifests/generated/kv-resource.yaml, pkg/network/netbinding/BUILD.bazel, pkg/network/netbinding/memory.go, pkg/network/netbinding/memory_test.go, pkg/virt-controller/services/BUILD.bazel, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-handler/BUILD.bazel, pkg/virt-handler/vm.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.KubeVirt.json, staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.KubeVirt.yaml, staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/network/bindingplugin_passt.go
This PR fixes a bug related to VM scheduling due to wrong resource specification.
Some network binding plugins require compute resource overhead to be added to the virt-launcher's pod `compute` container.
For example, the passt network binding plugin requires additional memory overhead requests to be added for the compute container in order to work correctly.
This is currently not possible, since there isn't an API that allows cluster-admins to specify their desire to have compute resource overhead when registering network binding plugins.
After this PR:
A field is added to the network binding plugin's definition in the KubeVirt CR.
The field is of type `k8scorev1.ResourceRequirements` that could hold any resource (not just CPU and memory) in order to allow future …
=> Network binding plugins: Add memory overhead for compute container

api/openapi-spec/swagger.json, manifests/generated/kv-resource.yaml, pkg/network/netbinding/BUILD.bazel, pkg/network/netbinding/memory.go, pkg/network/netbinding/memory_test.go, pkg/virt-controller/services/BUILD.bazel, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-handler/BUILD.bazel, pkg/virt-handler/vm.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/network/bindingplugin_passt.go
After this PR:
Manual cherrypick of #12235.
The PR is backported in order to fix a bug that impacts users of the [passt network binding plugin](https://kubevirt.io/user-guide/network/net_binding_plugins/passt/).
Fixes #
```release-note
Network binding plugins: Enable the ability to specify compute memory overhead
```
=> [release-1.3] Network binding plugins: Add memory overhead for compute container

pkg/libvmi/vm.go, tests/migration/postcopy.go
Add WithRunStrategy func to libvmi
WithRunStrategy is the correct way to choose
How vmi should behave and libvmi should include
option for RunStrategy setting.
postcopy.go: Remove use of RunVMAndExpectLaunchWithRunStrategy func
RunVMAndExpectLaunchWithRunStrategy should be deprecated as it is part
of tests_utils.go and use expensive get and update API calls
Instead of Updating VM runStrategy in postcopy.go create vm with
with the desired runStrategy.
```release-note
NONE
```
=> [Tests]postcopy.go: Remove use of RunVMAndExpectLaunchWithRunStrategy func

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, tests/framework/checks/checks.go, tests/framework/checks/skips.go
The memory hot plug feature is not available for s390x. This is causing unit tests to fail when running them on s390x.  The vm's architecutre is getting set using the runtime.GOARCH here: https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go#L2044 So it is getting set as s390x when we are running unit tests on s390x. Since the feature is not supported on s390x. It is throwing the error expected as `Memory hotplug is only available for x86_64 and arm64 VMs`  instead of failing with the below mentioned error. Failure logs here: 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-unit-test-s390x/1808521224393854976
```
[FAILED] Expected
<[]v1.StatusCause | len:1, cap:1>: [
{
Type: …
```
=> skip memory hot plug tests for s390x.

tests/utils.go
The deprecated `NewRandomVMIWithEphemeralDisk` function is used only once. Let us inline it, so no one is tempted to use it.
```release-note
NONE
```
=> tests/utils: inline NewRandomVMIWithEphemeralDisk into its only user

tests/hotplug/BUILD.bazel, tests/hotplug/memory.go
Flake:
```
{ Failure tests/hotplug/memory.go:322
<*errors.errorString | 0xc0014dbb90>: 
could not dump libvirt domxml (remotely on pod virt-launcher-testvmi-wrnv8-6pnmg): command terminated with exit code 1: 
, error: failed to get domain 'kubevirt-test-default1_testvmi-wrnv8'
{
s: "could not dump libvirt domxml (remotely on pod virt-launcher-testvmi-wrnv8-6pnmg): command terminated with exit code 1: \n, error: failed to get domain 'kubevirt-test-default1_testvmi-wrnv8'\n",
}
occurred
tests/hotplug/memory.go:352}
```
Use gomega in Eventually in order to prevent
transient errors
Fixes #
```release-note
NONE
```
=> Fix flaky mem hotplug test

tests/hotplug/BUILD.bazel, tests/hotplug/cpu.go
Flake
```
<*errors.errorString | 0xc00602dad0>: 
could not dump libvirt domxml (remotely on pod virt-launcher-testvmi-pffvl-8j4kh): command terminated with exit code 1: 
, error: failed to get domain 'kubevirt-test-default1_testvmi-pffvl'
{
s: "could not dump libvirt domxml (remotely on pod virt-launcher-testvmi-pffvl-8j4kh): command terminated with exit code 1: \n, error: failed to get domain 'kubevirt-test-default1_testvmi-pffvl'\n",
}
occurred
```
Move GetRunningVMIDomainSpec out of
the countDomCPUs as that is the only
thing that can have transient errors.
Fixes #
```release-note
NONE
```
=> Fix flaky cpu hotplug test

docs/network/network-binding-plugin.md
After this PR:
Following PR kubevirt/kubevirt#12235, it is now possible to specify memory overhead for the virt-launcher's compute container.
Add an explanation about the compute resource overhead in general, with a note that only memory overhead request is currently supported.
Fixes #
```release-note
None
```
=> Network binding plugin, docs: Add compute resource overhead

hack/prom-rule-ci/prom-rules-tests.yaml, pkg/monitoring/rules/recordingrules/virt.go
The underlying recording rule for `LowReadyVirtOperatorsCount` alert - `kubevirt_virt_operator_ready` which reports the number of ready virt-operator pods, is based on `kubevirt_virt_operator_ready_status` metric, which should report 0/1 per virt-operator pod. The latter metric is not 100% accurate. It isn't decreased when the virt-operator pod becomes unready. This caused the alert to never be triggered.
After this PR:
`kubevirt_virt_operator_ready` recording rule is now based on both `kubevirt_virt_operator_ready_status` and `kube_pod_status_ready` metrics (which get decreased properly when a pod becomes unready), and this gives us a more accurate way of monitoring virt-operator readiness. 
Fixes: https://issues.redhat.com/browse/CNV-39739 …
=> Fix LowReadyVirtOperatorsCount alert

tests/network/vmi_networking.go
The test is removed because:
- Assuming external connectivity in the test env is not assured.
- Connectivity tests for bridge and masquerade binding already exist.
- The default implicit configuration is already tested [1]
[1] https://github.com/kubevirt/kubevirt/blob/a363e7501fe62558936db4704b03d42c675595f5/tests/network/primary_pod_network.go#L66
Fixes #
```release-note
NONE
```
=> tests, net: Remove default settings with external connectivity test

pkg/virtctl/softreboot/BUILD.bazel, pkg/virtctl/softreboot/softreboot_test.go
=> Refactor unit tests to use libvmi for resource creation in softreboot

tests/validatingadmissionpolicy/noderestrictions.go
Currently, the VAP tests use the virt-handler token to ensure that only legit patch operations are allowed. They get all the nodes and pick a random one.
In those cases where the first node is a control-plane only node, the test fail since the virt-handler is not running there.
The virt-handler daemonset schedules virt-handler pods only in schedulable nodes.
Instead of pick a random node from the entire node list, pick a random node from the schedulable node list.
```release-note
NONE
```
=> fix(vap test): use schedulable nodes only

pkg/virtctl/vm/restart.go, pkg/virtctl/vm/restart_test.go, pkg/virtctl/vm/stop.go, pkg/virtctl/vm/stop_test.go, staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_virtualmachine_expansion.go, staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachine_expansion.go, staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go, tests/vm_test.go
`ForceRestart` and `ForceStop` methods are respectively duplicate of `Restart` and `Stop`.
The differences are expressed in options that the caller set.
We can drop the two methods if favor of the classic `Restart` and `Stop`
Fixes #
```release-note
Drop `ForceRestart` and `ForceStop` methods from client-go
```
/cc @xpivarc
=> client-go: remove `ForceRestart` and `ForceStop` duplicate methods

tests/compute/vmidefaults.go
When a VM with running is created, it creates a VMI. This can require a delta time to be created.
Put the VMI retrieving under an Eventually block,
preventing flakyness.
Fixes #
```release-note
NONE
```
/kind flake
=> fix(e2e test): add toleration waiting vmi to appear

.golangci.yml, pkg/libvmi/vm.go, tests/clone_test.go, tests/storage/datavolume.go, tests/storage/export.go, tests/storage/hotplug.go, tests/storage/memorydump.go, tests/storage/restore.go, tests/storage/snapshot.go, tests/vm_test.go
As we have a proposal to deprecate the running field (https://github.com/kubevirt/kubevirt/issues/11993)
Let's have some tests use run strategies instead of the running field via libvmi,
similarly to how we would also steer users towards the same direction.
Note we cannot simply abandon running (semver) and thus we will keep it in many test suites.
Storage tests were picked for some coverage of WithRunStrategy 
since they're more of a "casual" user of the running/runstrategy API
(indifferent to the specifics of running vs runstrategy)
For more info about the reasoning for runstrategies:
https://kubevirt.io/user-guide/compute/run_strategies/
Fixes #
This …
=> libvmi: introduce WithRunStrategy and prefer it over WithRunning in many tests

tests/instancetype/upgrade.go, tests/libinstancetype/builder/builder.go, tests/libinstancetype/builder/v1alpha1/builder.go, tests/libinstancetype/builder/v1alpha2/builder.go, tests/performance/BUILD.bazel, tests/performance/density.go, tests/subresource_api_test.go
/cc @fossedihelm
As discussed in https://github.com/kubevirt/kubevirt/pull/12248 this is the simple follow up you requested.
Two simple cleanups of libinstancetype. 
* `WithMemory` is aligned with libvmi's `WithResourceMemory` and now takes a simple string
* Calls of `WithCPUs` casting arguments to `uint32` are now replaced with simple `int`s.
Fixes #
```release-note
NONE
```
=> libinstancetype clean ups

pkg/virt-operator/resource/apply/BUILD.bazel, pkg/virt-operator/resource/apply/delete.go, pkg/virt-operator/resource/apply/delete_test.go
Removed the labels which is added to each node by virthandler
virt-handler does not clean up labels added by node-labeller
After this PR:
Introduced the logic to cleanup labels
Fixes #11571
```release-note
None
```
=> Introduced the function which clean up labels added by node-labeller

pkg/monitoring/metrics/virt-controller/BUILD.bazel, pkg/monitoring/metrics/virt-controller/leader_metrics.go, pkg/monitoring/metrics/virt-controller/metrics.go, pkg/monitoring/metrics/virt-operator/BUILD.bazel, pkg/monitoring/metrics/virt-operator/leader_metrics.go, pkg/monitoring/metrics/virt-operator/metrics.go, pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/workload-updater/workload-updater_test.go, pkg/virt-operator/application.go, tests/monitoring/metrics.go, tools/doc-generator/doc-generator.go
Global metrics were reported more than once, per virt-controller/virt-operator pod.
After this PR:
Global metrics are reported only by the virt-controller/virt-operator leader pods.
Affected metrics:
- kubevirt_vmi_number_of_outdated
- kubevirt_configuration_emulation_enabled
Fixes https://issues.redhat.com/browse/CNV-42007
```release-note
None
```
=> Report global metrics only by leader pods

tests/libvmifact/factory.go, tests/migration/migration.go, tests/storage/datavolume.go, tests/storage/export.go, tests/storage/hotplug.go, tests/storage/migration.go, tests/storage/restore.go, tests/storage/storage.go, tests/vm_test.go
The "#!/bin/bash\necho 'hello'\n" string would be used on several places through the repository
After this PR:
Instead of using the string and writing it over the code several times we use a factory function with the string being written only once
Fixes #
#11449 
Moving the string to constant was considered, but using a factory function might be a better solution for those cases - #12257 
There is still one use of the string left under  `NewRandomVMIWithEphemeralDiskAndUserdata`, the function should be deprecated and instead use libvmi. 
```release-note
NONE
```
=> Use factory function instead of echo hello string in libvmi uses

pkg/instancetype/instancetype.go, pkg/instancetype/instancetype_test.go
This change brings `FindPreferenceSpec` in-line with `FindInstancetypeSpec` where by default we attempt to lookup the cluster resource when kind is missing.
Fixes #12375
```release-note
NONE
```
=> instancetype: Attempt to find ClusterPreferences when kind missing

tests/utils.go, tests/vm_test.go
Removes RetryWithMetadataIfModified function from utils.
```release-note
None
```
=> tests: remove RetryWithMetadataIfModified function

tests/instancetype/instancetype.go
RunVMAndExpectLaunchWithRunStrategy should be deprecated as it is part of tests/utils.go and use expensive get and update API calls
Instead of Updating VM runStrategy in instancetype.go create vm with with the desired runStrategy.
After this PR:
Fixes #
```release-note
NONE
```
=> [Tests]instancetype.go: Remove use of RunVMAndExpectLaunchWithRunStrategy func

tests/guestlog/guestlog.go
This reverts commit 0c2c76a390e83b96f6187535bf801c3ff6bdd7ad.
As discussed on the [kubevirt-dev ML](https://groups.google.com/g/kubevirt-dev/c/c-zMktLPMlo) the flake appears to be resolved now so we can unquarantine the test. This will also need to be backported to `release-1.3` assuming it is also fixed there.
Fixes #12074
```release-note
NONE
```
=> Revert "guestlog, quarantine: Quarantine flakey QOSGuaranteed test"

cmd/sidecars/network-passt-binding/domain/BUILD.bazel, cmd/sidecars/network-passt-binding/domain/configurator.go, cmd/sidecars/network-passt-binding/domain/configurator_test.go, cmd/sidecars/network-passt-binding/server/server.go
Passt uses the source device "eth0" for domain xml
After this PR:
At some enviroments that should be "ovn-udn1" this PR try this first, if it do not exist do a fallback to eth0.
ovn-kubernetes place where the interface is not eth0:
- https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/cni/udn/primary_network.go#L30
Using harcoded value is not flexible, but we plan to make it configurable in the future.
Try to find the interface that has the default gw, problem is that at multus you can configure de default network at other interfaces. …
=> passt, sidecar: Look for optional link

tests/network/vmi_networking.go
This scenario is covered by the network admitter's unit tests [1].
[1] https://github.com/kubevirt/kubevirt/blob/d0befc774a69d3a43c06e2d9474eb8a326ce63d6/pkg/network/admitter/netiface_test.go#L159
After this PR:
Fixes #
```release-note
None
```
=> network, e2e: Remove invalid MAC address on pod network

cmd/virt-handler/BUILD.bazel, cmd/virt-handler/virt-handler.go, pkg/network/netbinding/memory.go, pkg/network/netbinding/memory_test.go, pkg/virt-controller/services/BUILD.bazel, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-controller/watch/application.go, pkg/virt-handler/BUILD.bazel, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go
Following PR #12235, it is possible to specify memory overhead for the compute container when registering a network binding plugin.
Decouple the memory overhead calculation when:
1. Calculating the compute container's memory overhead.
2. Calculating if there is enough memory in a memory hotplug scenario.
Introduce the `netBindingPluginMemoryCalculator` interface to:
1. templateService
2. VirtualMachineController
Expect the network binding plugin memory overhead calculation to be called in unit tests.
There is a check in `template.go` to see if the newly introduced interface is not `nil` in order to not break existing unit tests that use the real `templateService` struct:
- VMI controller
- Migration controller
Fixes #
The following alternatives were …
=> Network Binding Plugin: Decouple memory overhead calculation

pkg/virt-handler/device-manager/device_controller_test.go
During unit-tests, the device controller instances are never stopped, resulting in multiple controllers running at the same time.
After this PR:
The device controller is properly stopped after each test.
Fixes #
```release-note
None
```
=> virt-handler: Fix leaking goroutine during device_controller tests

pkg/util/util.go
This Pull Request aims to increase the log verbosity of a log in `AlignImageSizeTo1MiB` to avoid flooding.
This log is unskippable when using a non-aligned volume size, and appears quite frequently in `virt-launcher` and `virt-handler`. We currently log it as a warning, which is overkill for this specific case. We should increase the verbosity level and let it only appear when explicitly debugging.
Some cases where the log is triggered:
- In virt-handler, every time PVC/DV volumes are converted to hostDisk in `ReplacePVCByHostDisk`.
- In virt-launcher, when we use disks that allow expansion.
Fixes # https://issues.redhat.com/browse/CNV-43005
```release-note
NONE
```
=> Increase verbosity level of 1MiB-alignment log

tests/monitoring/monitoring.go
Fix runbook_url test to not expect the alert name as the URL suffix, as in some installations the alert name is not the URL suffix.
e.g. in openshift the runbooks are in https://github.com/openshift/runbooks/tree/master/alerts/openshift-virtualization-operator, and the suffix is `<alert-name>.md`.
```release-note
None
```
=> Fix runbook_url test

images/BUILD.bazel, images/vm-killer/BUILD.bazel
The vm-killer image is used in some of the e2e tests. Currently the vm-killer image is not supported for s390x as a result the s390x e2e tests which are using the vm-killer image are failing with the reason the image is not supported for s390x.
After this PR:
This pr adds the vm-killer image support for s390x. With this change the s390x e2e tests which are using vm-killer image are passing.
Fixes #
```release-note
None
```
=> add s390x support for vm-killer image.

cmd/virt-handler/BUILD.bazel, cmd/virt-handler/virt-handler.go, pkg/virt-handler/BUILD.bazel, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go
Currently, `NewController()` instantiates the concrete implementations of `netConf` and `netStat`.
Take `netConf` and `netStat` as parameters to `NewController()` in order to make the VMController independent of
`kubevirt.io/kubevirt/pkg/network/setup`.
Fixes #
https://github.com/kubevirt/kubevirt/pull/12326#discussion_r1677118016
```release-note
None
```
=> virt-handler: Remove dep on pkg/network/setup

tests/network/vmi_networking.go
This scenario is covered by the network admitter's unit tests [1].
[1] https://github.com/kubevirt/kubevirt/blob/d0befc774a69d3a43c06e2d9474eb8a326ce63d6/pkg/network/admitter/netiface_test.go#L135
Fixes #
```release-note
None
```
=> network, e2e: Rm VMI with unsupported iface model

pkg/virt-handler/device-manager/device_controller_test.go
The current unit test is only passing because timing wise it checks for the
devices to be stopped before they are even started. The actual devices are
never stopped.
This changes the behavior to ensure permanent devices are never removed while
others are removed when no longer permitted.
s390x unit-test job sometimes fails
After this PR:
s390x unit-test job is stable
Fixes #
```release-note
NONE
```
=> virt-handler: Fix broken device controller unit-test

pkg/virt-controller/watch/vm.go
fix some comments
Fixes #
```release-note
fix some comments
```
=> chore: fix some comments

tools/junit-merger/junit-merger.go
After this PR:
Fixes #
```release-note
```
=> fix: close files

hack/cluster-deploy.sh
Since the kernel issue is now fixed, we can go back to testing CDI with default memory limits:
https://gitlab.com/redhat/centos-stream/src/kernel/centos-stream-9/-/merge_requests/4523
Fixes #10822 
```release-note
NONE
```
=> Stop testing CDI with high memory limits

tests/scale/BUILD.bazel, tests/scale/virt-api.go
This PR enhances the efficiency and reliability of the `tests/scale/virt-api.go` by replacing the `Update` operation with the `Patch` operation.
This PR also removed redundant func `restorescc` and refactors  the `getApiReplicas` func
**Efficiency** - The `Patch` operation is more efficient for specific changes compared to the `Update` operation.
**Reliability** - Using `Patch` reduces the likelihood of conflicts and failures, especially when multiple changes are being made to the resource concurrently.
```release-note
NONE
```
=> tests/scale/virt-api.go: replace update api call with patch

tests/vmi_configuration_test.go
Setting a single label does not require updating the entire namespace object.
Furthermore, the Update operation has greater chances of failing in case the namespace object was changed by some other actor.
Fixes #
```release-note
None
```
=> VMI Config e2e, autocpulimit: Replace Update with Patch

pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
**Before this PR:** 
The pod-eviction-admitter tests used a scoped function `newVMI` as well as accompanying scoped types and builder functions of similar nature to [libvmi](https://github.com/kubevirt/kubevirt/tree/main/pkg/libvmi) in order to construct VMIs for the tests.
**After this PR:** 
Delegates any VMI construction logic to [libvmi](https://github.com/kubevirt/kubevirt/tree/main/pkg/libvmi) and removes redundant logic from the tests:
* Removes redundant types and VMI creation functions.
* Removes redundant option specification and sets default VMI options that are used for all tests (via `defaultVMIOptions`)
* Adds a new `withNodeName` function to compensate for the lack of VMI status update logic during construction (in accordance with the libvmi guidelines).
Partially addresses …
=> Move pod-eviction-admitter_test.go to use libvmi for VMI construction

pkg/virt-operator/application.go
Currently, when registering the virt-operator's validating webhooks, the handler functions are converted to type `http.HandlerFunc`. Since they already match this type - the conversion is redundant.
Fixes #
```release-note
None
```
=> virt-operator: Remove redundant type conversion

pkg/virtctl/expose/BUILD.bazel, pkg/virtctl/expose/expose_test.go
=> Refactor unit tests to use libvmi for resource creation in expose

pkg/libvmi/cloudinit/cloudinit.go, pkg/libvmi/storage.go, tests/BUILD.bazel, tests/container_disk_test.go, tests/dryrun_test.go, tests/utils.go, tests/vmi_cloudinit_test.go, tests/vmi_configuration_test.go
NewRandomVMIWithEphemeralDiskAndUserdata functions is deprecated
Replaced the deprecated functions with calls to libvmi
```release-note
None
```
=> Remove the  deprecated function NewRandomVMIWithEphemeralDiskAndUserdata from tests/utils.go

tests/network/BUILD.bazel, tests/network/vmi_networking.go
The test creates a VMI with implicit usage of bridge binding to the pod network.
This scenario is covered by unit tests [1].
[1] https://github.com/kubevirt/kubevirt/blob/9eee6fb8c1b9fc117f431d4a22978c18da4b7e26/pkg/network/vmispec/defaults_test.go#L79
Fixes #
```release-note
None
```
=> net, e2e: Rm rejection of VMI with pod net and bridge binding

tests/storage/datavolume.go
Before this PR: DV is updated
After this PR: DV is patched
jira-ticket: https://issues.redhat.com/browse/CNV-44579
Use Patch instead of Update whenever possible for shortening the tests and reducing potential conflicts.
```release-note
NONE
```
=> datavolume tests: use Patch instead of Update

tests/libstorage/BUILD.bazel, tests/libstorage/datavolume.go
Before this PR: CDI is updated
After this PR: CDI is patched
jira-ticket: https://issues.redhat.com/browse/CNV-44575
Use Patch instead of Update whenever possible for shortening the tests and reducing potential conflicts.
```release-note
NONE
```
=> tests, libstorage: Patch CDI instead of Update

tests/infrastructure/BUILD.bazel, tests/infrastructure/certificates.go
It is common practice on our e2e tests to use Update k8s API in order to run the test. In order to ensure the change was executed, these also are wrapped with RetryOnConflict. 
The issue is that most often tests do not really need to use Update (for an atomic change) and Patch would be quicker and more precises.
This PR replaces RetryOnConflict update w/ patch on tests/infrastructure/certificates
Fixes #
```release-note
NONE
```
=> tests/infra/certificates: Replace RetryOnConflict update with patch

tests/dryrun_test.go
Patch allows more precise usage, lighter and reduces the collision domain.
Fixes #
```release-note
None
```
=> tests, dry run: Use patch instead update

pkg/virt-controller/watch/workload-updater/BUILD.bazel, pkg/virt-controller/watch/workload-updater/workload-updater.go, pkg/virt-controller/watch/workload-updater/workload-updater_test.go
This series of commits gradually remove complexity of workload updater tests to the point where we reduce the runtime from ~100 seconds down to ~200ms.
Fixes #
I recommend to review commit by commit.
```release-note
NONE
```
=> Workload updater decrease test time and complexity

pkg/libvmi/storage.go, tests/migration/migration.go, tests/utils.go, tests/vmi_iothreads_test.go, tests/vmi_lifecycle_test.go
The deprecated function `AddEphemeralDisk` is in use in e2e tests.
After this PR:
Tests are using libvmi options instead of the deprecated function `AddEphemeralDisk`. The function is removed.
```release-note
None
```
=> Remove the deprecated function AddEphemeralDisk from tests/utils

pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
Currently, completed virt-launcher pods can trigger a live migration if an eviction request arrives.
This is wrong since completed pods should be simply evicted.
Fixes #
```release-note
Fix: eviction requests to completed virt-launcher pods cannot trigger a live migration
```
=> Admit eviction on completed virt-launcher pods

tests/storage/storage.go, tests/vmi_configuration_test.go
`createBlockDataVolume` was written twice over 2 different files making it more confusing and harder to change in the future.
After this PR:
`createBlockDataVolume` is removed and libdv is used directly instead.
```release-note
NONE
```
=> Remove createBlockDataVolume

tests/libstorage/datavolume.go, tests/storage/datavolume.go, tests/storage/restore.go, tests/vm_state_test.go
1Gi is a LOT, especially since most of the calls are for a tiny cirros/alpine VMs, with a few exceptions.
This triggers CI stress:
```
0/2 nodes are available: 1 Insufficient memory
```
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12023/pull-kubevirt-check-tests-for-flakes/1812438984626802688/artifacts/k8s-reporter-parallel/2/1_vmis.log
Fixes #
```release-note
NONE
```
=> tests: change default memory request for VM/DV factory

pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go
This series of commits gradually remove complexity of VMI tests to the point where we reduce the runtime from ~20 seconds down to ~200ms. On top of this we remove some unnecessary code and fix few issues.
Fixes #
```release-note
NONE
```
=> VMI decrease test time and complexity

tests/migration/migration.go
In case a cluster is configured to add hotpluggable cores then the `virsh vcpupin` outputs also these
cpus. Here full range is showed (as they are yet to be pinned).
Fixes #
```release-note
NONE
```
=> Migration test: Skip range cpu pin

pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/12451
```release-note
Fix: eviction requests to completed virt-launcher pods cannot trigger a live migration
```
=> [release-1.3] Admit eviction on completed virt-launcher pods

pkg/virt-api/rest/authorizer.go, pkg/virt-api/rest/authorizer_test.go
virt-api is broken on GKE because not decoding "extra" authorization header named X-Remote-Extra-Iam.gke.io%2fuser-Assertion:
After this PR:
Correctly decode header
Fixes #12459
```release-note
virt-api: unencode authorization extra headers
```
=> virt-api: unencode authorization extra headers

pkg/storage/snapshot/snapshot.go
When a volume associated with a VM is using a `StorageClass` which does not have a `VolumeSnapshotClass` associated with it, a log message is emitted at the warning level. In our environment using a CSI driver which does not support snapshots (AWS EFS), this generates excessive logs in the order of ~500k messages per day.
The log message will be emitted at verbosity level 3. This level was chosen as it is above the [default level of 2](https://github.com/kubevirt/kubevirt/blob/fb7c34663c81fc5c0c49ea984b1f970b62ea042b/staging/src/kubevirt.io/client-go/log/log.go?plain=1#L101) and would therefore be avoided by default.
Although the message will not be shown in logs, it will still be shown in the `status.volumeSnapshotStatuses` field of the VM resource.
This could potentially done by more …
=> Reduce severity when VolumeSnapshotClass is absent

pkg/apimachinery/patch/patch.go, pkg/virt-controller/watch/clone/BUILD.bazel, pkg/virt-controller/watch/clone/clone.go, pkg/virt-controller/watch/clone/clone_base.go, pkg/virt-controller/watch/clone/clone_test.go, pkg/virt-controller/watch/clone/vm-target.go
vmclone controller pkg cleanup:
1. Use the patch package to replace the hardcoded patch operations. This improves the readability and make the code more cohesive.
2. Remove the usage of the informers in the vmclone controller.
There is no need to hold informers, narrowing down
the interface can decrease the probability of making
a mistake.
Partially address: https://github.com/kubevirt/kubevirt/issues/11654
```release-note
NONE
```
=> vmclone: use patchset and remove informers from struct

pkg/util/webhooks/validating-webhooks/validating-webhook.go, pkg/virt-api/webhooks/validating-webhook/admitters/instancetype-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/preference-admitter.go
Currently, the `Admitter` interface is exported and the following structs (validating webhooks [1]) are "explicitly declaring" that they implement the `Admitter` interface:
- InstancetypeAdmitter
- ClusterInstancetypeAdmitter
- PreferenceAdmitter
- ClusterPreferenceAdmitter
This explicit declaration makes them dependent on the following package: "kubevirt.io/kubevirt/pkg/util/webhooks/validating-webhooks"
Unexport the `Admitter` interface in order to decouple usage from implementation.
In case one of the admitters will accidentally stop implementing the `admitter` interface, the `Serve` [2] function will not accept it as an admitter and the compilation will break.
This change is also aligned with the `mutator` [3] interface which represents mutating webhooks [4].
[1] …
=> validating webhooks: Unexport the Admitter interface

api/openapi-spec/swagger.json, pkg/network/admitter/netiface.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/schema.go, staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go
This adds the `igb` interface model as an option. 
Currently based on #11753 for the QEMU 8.2 as this is how I tested it to verify `igb` is actually working.
Tested with the following VM:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
name: ubuntu
spec:
running: false
template:
metadata:
labels:
kubevirt.io/size: medium
kubevirt.io/domain: ubuntu
spec:
domain:
cpu:
cores: 2
devices:
disks:
- name: containervolume
disk:
bus: virtio
- name: cloudinitvolume
disk:
bus: virtio
interfaces:
- name: default
model: igb
bridge: {}
resources:
requests:
memory: 1024M
networks:
- name: default
pod: {}
volumes:
- name: containervolume
containerDisk:
image: tedezed/ubuntu-container-disk:22.0
- name: cloudinitvolume
cloudInitNoCloud:
userData: |-
#cloud-config
bootcmd:
- echo …
```
=> Add `igb` interface model

pkg/virt-controller/watch/workload-updater/BUILD.bazel, pkg/virt-controller/watch/workload-updater/workload-updater.go, pkg/virt-controller/watch/workload-updater/workload-updater_test.go
Make sure that the migration has completed by checking if the target domain is ready. In certain cases, the migration can be  still in running phase but the migration process has already completed and the object hasn't been updated yet. In order to prevent the race condition of deleting the migration object, we check if the target is ready.
Fixes #12297
```release-note
NONE
```
=> workload-updater: avoid cancelling the migration when the migration has finished

OWNERS, cluster-up/OWNERS, cmd/OWNERS, hack/OWNERS, staging/src/kubevirt.io/api/OWNERS
The documentation states:
"WARNING: The approve plugin does not currently respect filters. Until that is fixed, filters should only be used for the labels key (as shown in the above example)"
From now on we can only use OWNERS files per directory.
Fixes #
```release-note
NONE
```
=> Remove usage of "filters" in OWNERS

pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go, pkg/virt-controller/watch/drain/evacuation/BUILD.bazel, pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
Switch using fakeClient since the latter better simulate real
behavior, lowering the bar for unit tests, eliminating false positives.
Also, the fake is standard for testing.
Fixes #
```release-note
NONE
```
=> Drain controllers: use fakeclient

pkg/virt-controller/watch/pool_test.go
Switch using fakeClient since the latter better simulate real
behavior, lowering the bar for unit tests, eliminating false positives.
Also, the fake is standard for testing.
```release-note
NONE
```
=> pool controller: Use fakeclient

pkg/virt-api/rest/streamer_test.go
Removes unnecessary `time.Sleep`. This reduce the runtime from ~40 seconds down to ~2 seconds
Fixes #
```release-note
NONE
```
=> Rest package: reduce test runtime

pkg/virt-controller/watch/clone/BUILD.bazel, pkg/virt-controller/watch/clone/clone_test.go
This series of commits gradually remove complexity of vmclone tests to the point where we reduce the runtime from ~3 seconds down to ~250ms. On top of this we remove some unnecessary code and fix few issues.
These changes follow the logic introduced here https://github.com/kubevirt/kubevirt/pull/12468
```release-note
NONE
```
=> vmclone: improve test time

pkg/virt-controller/watch/workload-updater/BUILD.bazel, pkg/virt-controller/watch/workload-updater/workload-updater.go, pkg/virt-controller/watch/workload-updater/workload-updater_test.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/12324
```release-note
NONE
```
=> [cherry-pick-1.3]  workload-updater: avoid cancelling the migration when the migration has finished

pkg/network/setup/netconf.go, pkg/network/setup/netpod/netpod.go
The netpod nmstate dumps about the pod network namespace current and desired states are useful in troubleshooting the network setup of virt-launcher pods if needed. It is also suppose to be a one-time execution, making the logging at "info" level reasonable.
This change fixes a missing reference to a VMI identifier.
A custom logger with the VMI object is now used.
Fixes #
```release-note
NONE
```
=> net, netpod: Include the VMI identifiers in the nmstate dump logs

pkg/virt-controller/watch/migration_test.go
This series of commits gradually remove complexity of pool tests to the point where we reduce the runtime from ~12 seconds down to ~150ms. On top of this we remove some unnecessary code and fix few issues.
These changes follow the logic introduced here https://github.com/kubevirt/kubevirt/pull/12468
```release-note
NONE
```
=> migration test: improve test time

pkg/virt-api/webhooks/validating-webhook/admitters/preference-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/preference-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
It is valid to use spread or preferSpread with PreferredCPUTopology, so
ensure that both are validated in the same way.
This bug was introduced in https://github.com/kubevirt/kubevirt/pull/11927 while transitioning from the prefixed to the non-prefixed constants for CPU topology.
CPU topology `preferSpread` was not validated in certain cases.
After this PR:
CPU topology `preferSpread` is validated the same as topology `spread`.
Fixes #
```release-note
None
```
=> fix(preferences): Fix validation of preferSpread cpu topology

pkg/virt-handler/vm.go
Migration related message consts in `virt-handler/vm.go` were only used in matching unit tests and actual events used string literals.
Replaced string literals with existing consts. 
```release-note
NONE
```
=> [virt-handler/vm.go] Use existing constants instead of string literals for VMI migration events

tests/BUILD.bazel, tests/storage/restore.go, tests/utils.go
Before this PR: VM is updated
After this PR: VM is started/stopped and patched
jira-ticket: https://issues.redhat.com/browse/CNV-44587
Use VM Start/Stop and Patch instead of Update whenever possible for shortening the tests and reducing potential conflicts.
```release-note
NONE
```
=> tests, utils: use VM Start/Stop and Patch instead of Update

pkg/virt-controller/watch/pool_test.go
This series of commits gradually remove complexity of pool tests to the point where we reduce the runtime from ~19 seconds down to ~250ms. On top of this we remove some unnecessary code and fix few issues.
These changes follow the logic introduced here https://github.com/kubevirt/kubevirt/pull/12468
```release-note
NONE
```
=> vmpool: improve test time

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter_test.go
we have no validatewebhook for newMacAddresses and we can set invalid mac address
```yaml
kind: VirtualMachineClone
apiVersion: "clone.kubevirt.io/v1alpha1"
metadata:
name: testclone
spec:
newMacAddresses:
interfaceName: "00-11-22"
```
After this PR:
only the valid mac address to be deployed.
```yaml
kind: VirtualMachineClone
apiVersion: "clone.kubevirt.io/v1alpha1"
metadata:
name: testclone
spec:
newMacAddresses:
interfaceName: "00:11:22:33:44:55"
```
Fixes #
```release-note
Adding newMacAddresses …
```
=> Adding newMacAddresses validatewebhook for  VMCloneAPI

pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/migration_test.go, pkg/virt-controller/watch/vmi.go, tests/storage/BUILD.bazel, tests/storage/migration.go
When the migration fails, the workload update continues to create new VMI migration object. Now, virt-controller implement the migration backoff mechanism also for workload update migrations
Add a functional test which replicates a migration failure when the destination image is smaller then source one.
```release-note
NONE
```
=> workload-update: implement bakoff mechanism

pkg/virtctl/imageupload/imageupload.go, tests/storage/imageupload.go
We've been using an older progress bar library for ages now that defaulted to stdout:
https://github.com/kubevirt/kubevirt/pull/12184
Let's keep it that way
Fixes #
```release-note
NONE
```
=> virtctl/imageupload progress bar: write to stdout

pkg/storage/types/dv.go, pkg/storage/types/pvc.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, staging/src/kubevirt.io/api/core/v1/types.go
Currently, virt-controller will create DataVolumeTemplates once the VM is created.  Even if the VM is stopped.  It also continually ensures that DataVolumeTemplates exist whenever a VM is reconciled.  Even if the VM is stopped.  This has a couple drawbacks:
1.  If the VM is never started, the underlying PVC (if on immediate bind StorageClass) was allocated unnecessarily
2. It is hard for the user or third party backup software to replace a DataVolume's underlying PVC.  See #11637 
After this PR:
User may add `kubevirt.io/immediate-data-volume-creation: "false"` annotation to the VM and it will only reconcile DataVolumeTemplates when the VM is running
Fixes #11637
https://issues.redhat.com/browse/CNV-42076
The following alternatives were …
=> More control over when DataVolumeTemplates are created

tests/monitoring/monitoring.go
The test _"KubeVirtVMIExcessiveMigrations should be triggered when a VMI has been migrated more than 12 times during the last 24 hours"_ is causing a lot of flakiness because it executes a VMI migration 13 times, and usually at least one of them fails.
After this PR:
The test is marked as pending to unblock other tasks until a permanent solution can be found.
Fixes #
```release-note
none
```
=> Mark KubeVirtVMIExcessiveMigrations alert test as pending

pkg/virtctl/vmexport/vmexport.go, pkg/virtctl/vmexport/vmexport_test.go, tests/storage/export.go
This Pull Request improves the garbage collection of `virtualmachineexport` resources in virtctl so, by default, we only delete resources created during the command's lifecycle.
Previously, the decision to delete a `virtualmachineexport` was based on the provided flags without adequately accounting for pre-existing resources. This could lead to inconsistencies between the flags and the actual state of resources.
Fixes #
```release-note
NONE
```
=> virtctl vmexport: Improve garbage collection of vmexport resources

pkg/network/istio/annotations.go, pkg/network/istio/proxy.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, tests/network/vmi_istio.go
[Istio](https://istio.io/)'s annotations were written in snake case and had a redundant prefix.
After this PR:
The annotations are aligned with Go's coding conventions [1] and are better documented. 
Fixes #
https://github.com/kubevirt/kubevirt/pull/12480#discussion_r1703831515
According to istio's documentation, the usage of the `sidecar.istio.io/inject` annotation is deprecated [2].
A follow-up PR will adjust the relevant logic.
[1] https://go.dev/doc/effective_go#mixed-caps
[2] https://istio.io/latest/docs/reference/config/annotations/#SidecarInject
This checklist is not enforcing, but it's a reminder of items that could be relevant to every …
=> Rename and document Istio's annotations

pkg/network/admitter/netiface_test.go, pkg/network/link/address_test.go, tests/network/vmi_networking.go
Remove "VirtualMachineInstance with custom MAC address in non-conventional format".
Enhance unit tests to make sure this scenario is covered.
Fixes #
```release-note
None
```
=> net, e2e: Remove VMI with custom MAC address in non-conventional format

automation/test.sh
`make cluster-sync` causes a large amount of IO operations as it is
building the required images and pushing them to the local registry.
This pushing of the images is reading and writing these images to the
same underlying disk.
This high level of IO can impact other CI jobs that are running on the
same worker node which can lead to some issues such as etcd timeouts that are
seen intermittently
Setting an ionice idle level for cluster-sync should reduce this impact
and give priority to the processes running the tests.
High levels of IO at the start of  presubmit prowjobs while cluster-sync is running
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12095/pull-kubevirt-e2e-k8s-1.30-sig-storage/1820723312959950848
After this PR:
Much lower …
=> ci: add ionice idle level to cluster-sync

tests/subresource_api_test.go
StartVirtualMachine should be deprecated as it is part of tests/utils.go and use expensive get and update API calls
Instead of Updating VM runStrategy in subresource_api_test.go create vm with with the desired runStrategy.
After this PR:
Fixes #
```release-note
NONE
```
=> [Tests]subresource_api_test.go:Remove use of StartVirtualMachine func

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
- "Running and RunStrategy are mutually exclusive"
- "One of Running or RunStrategy must be specified"
are updated to recommend users to use RunStrategy, as Running is deprecated.
After this PR:
Fixes #
```release-note
Advise users to use RunStrategy in virt-api messages
```
=> Advise users to use RunStrategy in virt-api messages

tests/network/bindingplugin_macvtap.go, tests/network/vmi_istio.go, tests/utils.go, tests/vmi_cloudinit_hook_sidecar_test.go, tests/vmi_hook_sidecar_test.go
Some tests use `GetVMPodName` to get the corresponding virt-launcher pod name.
After this PR:
GetVMPodName is removed and libpod.GetPodByVirtualMachineInstance is used instead.
Fixes #
```release-note
NONE
```
=> tests, utils: Remove GetPodName

tests/storage/migration.go
runc (at least) expects this to be an absolute path
```
runc create failed: Cwd must be an absolute path
```
Fixes #
```release-note
NONE
```
=> volume migration tests: adjust workdir path to absolute

pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/migration_test.go, pkg/virt-controller/watch/vmi.go, tests/storage/BUILD.bazel, tests/storage/migration.go
Manual backport of #12336
Fixes #
```release-note
NONE
```
=> [cherry-pick 1.3] workload-update: implement bakoff mechanism

pkg/storage/velero/BUILD.bazel, pkg/storage/velero/annotations.go, pkg/virt-controller/services/BUILD.bazel, pkg/virt-controller/services/template.go, tests/storage/BUILD.bazel, tests/storage/snapshot.go
Move Velero [1] annotations constants to a dedicated package under `pkg/storage`.
This is done in order for them to be under sig-storage's ownership.
Rename the annotations constants to use camel case in order to align them with Go's coding conventions [2].
Drop the `VELERO` prefix, as it repeats the package name.
Use the annotations constants from the `velero` package in the snapshot e2e test in order to re-use code.
[1] https://velero.io/
[2] https://go.dev/wiki/CodeReviewComments#mixed-caps
Fixes #
```release-note
None …
```
=> virt-controller, template: Move Velero annotations to a dedicated package

pkg/libvmi/cloudinit.go, tests/storage/snapshot.go, tests/vmi_configuration_test.go
If there is another volume using the name `disk1`, then it will conflict with the cloudinit constant name. Therefore, this change adds the random generation of the cloudinit name of the volume for libvmi.
Constant name `disk1` for the cloudinit volume for libvmi
After this PR:
Random suffix for the cloudinit volume
Fixes #12535
```release-note
NONE
```
=> libvmi: random name for cloudinit volume

pkg/storage/export/export/export.go, pkg/storage/export/export/export_test.go
We were emitting a secret created event even if the secret was not created. This was causing several events to be shown in the event log even though only one secret was created.
After this PR:
Only when actually creating the secret will we emit the event that it was created.
Fixes #
```release-note
Fixed issue emitting created secret events when not actually creating secrets during VMExport setup
```
=> Don't emit a secret created event if the secret was not created

tests/instancetype/upgrade.go
It is common practice on our e2e tests to use Update k8s API in order to run the test. In order to ensure the change was executed, these also are wrapped with Eventually/RetryOnConflict.
The issue is that most often tests do not really need to use Update (for an atomic change) and Patch would be quicker and more precises.
Replacing Update in the following functions:
- updateInstancetypeMatcher
- updatePreferenceMatcher
Fixes # https://issues.redhat.com/browse/CNV-44574
```release-note
NONE
```
=> tests/instancetype/upgrade: Replace Update w Patch

tests/storage/export.go
- use patch to start/stop VM
there's no reason to loop over an update with eventually
when there's an API that uses patch
- use patch for kv cert config changes
Although unlikely, the kubevirt install may change and thus cause the update calls to fail.
We can instead specifically issue a patch against the fields we care
about.
Fixes #
```release-note
NONE
```
=> export tests: patch instead of updates where it makes sense

pkg/virt-operator/resource/apply/admissionregistration.go, pkg/virt-operator/resource/apply/apiservices.go, pkg/virt-operator/resource/apply/apps.go, pkg/virt-operator/resource/apply/core.go, pkg/virt-operator/resource/apply/core_test.go, pkg/virt-operator/resource/apply/crds.go, pkg/virt-operator/resource/apply/prometheus.go, pkg/virt-operator/resource/apply/reconcile.go, pkg/virt-operator/resource/apply/routes.go
Hardcoded operation in virt-operator/apply
After this PR:
Replaced all the patch operation with the patch packge
Fixes #
Partially fix: https://github.com/kubevirt/kubevirt/issues/11654
```release-note
NONE
```
=> virt-operator: replace hardcoded patch operations 

tests/monitoring/BUILD.bazel, tests/monitoring/vm_monitoring.go
Use the KubeVirt client instead of using virtctl through a NewRepeatableVirtctlCommand in tests/monitoring/vm_monitoring.go.
After this PR:
Fixes #
```release-note
None
```
=> cleanup(vm_monitoring.go): Use client instead of virtctl

tests/operator/BUILD.bazel, tests/operator/operator.go
It is common practice on our e2e tests to use Update k8s API in order to
run the test. In order to ensure the change was executed, these also are
wrapped with RetryOnConflict.
In this PR, The RetryOnConflict used on all cases is miss-used so that conflicts
will not be retried (the Get should be inside the RetryOnConflict).
Refactoring test to use Patch, as this would be more precise.
Fixes #
```release-note
NONE
```
=> tests/operator: Refactor "reconcile components" test to use Patch

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/volume-migration/volume-migration.go, pkg/virt-controller/watch/volume-migration/volume-migration_test.go, pkg/virt-controller/watch/workload-updater/workload-updater.go, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go, staging/src/kubevirt.io/api/core/v1/types.go, tests/storage/migration.go
No conditions was set if the volume migration wasn't possible because the VM isn't migratable
After this PR:
Create new condition `VMIStorageLiveMigratable` which reports if the storage of the VM can be live migrate, and if not the causes in the error message.
```release-note
Add new condition for VMIStorageLiveMigratable
```
=> volume migration: improve conditions when the volume migration isn't possible

cmd/virt-chroot/BUILD.bazel, cmd/virt-chroot/cgroup.go, pkg/virt-handler/cgroup/BUILD.bazel, pkg/virt-handler/cgroup/cgroup.go, pkg/virt-handler/cgroup/cgroup_v1_manager.go, pkg/virt-handler/cgroup/constants/BUILD.bazel, pkg/virt-handler/cgroup/constants/constants.go, pkg/virt-handler/cgroup/util.go
After some investigations, it seems like bringing in the handler cgroup pkg causes some
"cannot allocate memory" errors when invoking virt-chroot.
The investigation is still ongoing (one of it's deps messing with rlimits?)
but there really is no need to bloat this binary with the entire package just for a few strings.
The error can be replicated locally (huge thx @xpivarc) prior to this commit with
```bash
cd cmd/virt-chroot
go build
for i in {1..100}; do  sudo ./virt-chroot --user qemu --memory 1000000000 --cpu 10 --mount /proc/1/ns/mnt exec -- /usr/bin/echo "hi"; done
```
And the diff between the builds is quite significant
```bash
$ go version -m virt-chroot | grep dep | wc -l
83
$ go version -m virt-chroot | grep dep | wc -l
18
```
Fixes #
https://issues.redhat.com/browse/CNV-46286 …
=> Remove handler cgroup pkg dep in virt-chroot

pkg/storage/snapshot/BUILD.bazel, pkg/storage/snapshot/restore_test.go, pkg/storage/snapshot/snapshot_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter_test.go, pkg/virt-controller/watch/clone/clone_test.go
We want to deprecate the use of spec.Running and use spec.RunStrategy instead.
Before this PR: using spec.Running in storage UT
After this PR: using spec.RunStrategy in storage UT
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-45439
relates to issue: #11993 
```release-note
NONE
```
=> sig-storage: update unit tests to use runStrategy instead of spec.Running

pkg/virt-api/api.go, pkg/virt-api/webhooks/utils.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
PR #12009 introduced a check to see whether the VMI update had originated from the virt-handler.
Remove the file-system read made by `webhooks.GetNamespace()`.
Additionally, remove a call to `IsKubeVirtServiceAccount` that internally performs a file-system read.
Base the logic on the KubeVirtServiceAccount set introduced by PR #11931.
Deprecate `IsKubeVirtServiceAccount`.
Partially addresses #11177.
After this PR, a single call to `IsKubeVirtServiceAccount` is still left.
Removing it requires additional refactoring. …
=> virt-api, VMI update admitter: Remove file-system reads

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, tests/io_utils.go, tests/storage/storage.go
This is a cherry-pick of https://github.com/kubevirt/kubevirt/pull/9872.
This is a manual backport so it also includes a fix that was introduced later to address a test flake https://github.com/kubevirt/kubevirt/pull/10451.
```release-note
Bugfix: Allow lun disks to be mapped to DataVolume sources
```
=> [release-1.0] Allow lun disks to be mapped to DataVolume sources

WORKSPACE
This PR aims to address an issue with gazelle where the [default grpc dependency](https://github.com/bazelbuild/bazel-gazelle/blob/v0.33.0/deps.bzl#L258-L264) was overriding the `WORKSPACE/go.mod` one, resulting in the grpc-go version being used during builds to be v1.50.0 instead of the go.mod's v1.58.3.
The `org_golang_google_grpc` `go_repository` is now declared prior to the `gazelle_dependencies()` call so as to override the default. 
Fixes issue addressed in #10673.
This is an unprecedented change in terms of the `WORKSPACE` configuration, there are several ways to go about dependency handling using bazel/gazelle, the recommended of which is to use the newly introduced [bazelmod](https://docs.bazel.build/versions/5.1.0/bzlmod.html) but I believe …
=> grpc-go: Fix gazelle discrepancy to use correct version during build

tests/libmigration/BUILD.bazel, tests/libmigration/migration.go, tests/migration/BUILD.bazel, tests/migration/migration.go
Inline several helpers since they are used only in a single place.
Additionally remove the virtctl case from the tests that used
these helpers because it does not provide any additional value.
Use the KubeVirt client instead of using virtctl through a
NewRepeatableVirtctlCommand where applicable in
tests/migration/migration.go.
Internally virtctl uses the same client call, so using virtctl does not
provide any additional value.
After this PR:
Fixes #
The following …
=> cleanup(tests,migration): Inline helpers and use client instead of virtctl 

tests/network/vmi_lifecycle.go
BinBash constants adds no abstraction over the /bin/bash string. Using it, however, forces vmi_lifecycle to depend on the catch-all package "tests".
```release-note
NONE
```
=> tests, network: use /bin/bash directly

pkg/virtctl/pause/pause.go
Remove globals usage.
Ran unit tests locally (which do cover dryRun).
Fixes #
```release-note
None
```
=> virtctl, pause: Remove globals

tests/storage/datavolume.go
This came up with 1.31 lanes more often but is normally an issue
all across the board, since we never ensure the PVC is gone before testing that scenario.
Fixes #
```release-note
NONE
```
=> sig-storage: fix a flake where we never ensure PVC is gone

tests/storage/migration.go
This fixes `Permission Denied` error with some storage providers.
The command `qemu-img create ...` fails with `EACCESS` when using Longhorn CSI. 
After this PR:
The command succeeds, and the test is green.
Fixes #
```release-note
NONE
```
=> tests: Set FSGroup to ensure proper permissions

docs/metrics.md, pkg/monitoring/metrics/virt-controller/vmstats_collector.go, pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go
No metric with VM resource requests data
After this PR:
`kubevirt_vm_resource_requests` hold memory resource requests for VMs
jira-ticket: https://issues.redhat.com/browse/CNV-44275
Fixes #
```release-note
Add kubevirt_vm_resource_requests metric for memory resource
```
=> Add kubevirt_vm_resource_requests metric for memory resource

pkg/virt-api/api.go, pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
Remove unused params of the functions serving the following admitters:
- InstancetypeAdmitter
- ClusterInstancetypeAdmitter
- PreferenceAdmitter
- ClusterPreferenceAdmitter
- MigrationPolicyAdmitter
Fixes #
```release-note
None
```
=> virt-api, admitters: Remove unused params

pkg/storage/types/dv.go, pkg/storage/types/pvc.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, staging/src/kubevirt.io/api/core/v1/types.go
After this PR:
Manual cherry-pick of #12194
Fixes #11637
```release-note
VM supports kubevirt.io/immediate-data-volume-creation: "false" which delays creating DataVolumeTemplates until VM is started
```
=> [release-1.2] More control over when DataVolumeTemplates are created

tests/libnet/BUILD.bazel, tests/libnet/mac.go, tests/network/sriov.go, tests/network/vmi_multus.go, tests/network/vmi_networking.go
Cleaning up the vmi_networking tests
Fixes #
```release-note
NONE
```
=> tests, net: Cleaning up the vmi_networking tests

hack/cluster-sync.sh
When a make target calls make and timestamping is enabled, the output gets double-timestamped.
Since the make rules for cluster-build and manifests just call the corresponding scripts, calling the scripts directly should fix double-timestamping without any side-effect.
The build section of the logs for every lane is double-timestamped (like `14:55:09: 14:55:09: selecting podman as container runtime`)
After this PR:
Single timestamps
Fixes #
Set $TIMESTAMP to 0 when calling sub-targets
```release-note
NONE …
```
=> cluster-sync: call scripts directly instead of make targets

pkg/virt-controller/watch/vm.go
Do not clear out `Memory` in `setGuestMemory` but rather overwrite the `Guest` field, otherwise if hugepages are configured for the VM the setting would get lost.
Creating a VM configured with hugepages does not actually use hugepages if memory is set through `memory.requests`
After this PR:
Creating a VM configured with hugepages does use hugepages if memory is set through `memory.requests`
Fixes #
```release-note
NONE
```
=> [release-1.2] fix: do not clear out spec.Domain.Memory

automation/test.sh, tests/decorators/decorators.go, tests/guestlog/guestlog.go
Introduce a decorator to label tests for being
executed only on periodic lanes.
Tests labelled as `PERIODIC` will only be executed
on test lanes containing periodic in their name so that
they are going to be skipped on pre-submit lanes.
This is especially useful for long running an not critical tests
and it will help containing CI execution time on open PRs.
We lack a mechanism to label long running non critical tests for being executed only on periodic lanes but not on pre-submit ones.
After this PR:
We lack a mechanism to label long running non critical tests for being executed only on periodic lanes but not on pre-submit ones.
Fixes https://issues.redhat.com/browse/CNV-46060
- Periodic test lanes are identified according to their name …
=> [tests] introduce a decorator for Periodic tests

tests/storage/BUILD.bazel, tests/storage/hotplug.go, tests/storage/memorydump.go
Drop the virtctl related tests in tests/storage/hotplug.go. As long as
virtctl calls the correct API endpoints these tests don't add any value. (see https://github.com/kubevirt/kubevirt/pull/12634)
Verify that the DryRun option in AddVolume requests works as intended.
These cases were covered only indirectly by tests using virtctl previously.
The goal of this and further PRs is to reduce the amount of unnecessary uses of virtctl in the e2e tests to stabilize tests, to reduce the number of flakes and to remove redudant tests.
Fixes # …
=> Drop virtctl related tests and add DryRun tests in hotplug.go 

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
This is a follow-up to PR #12568.
Un-export the fields of VMIUpdateAdmitter for better encapsulation.
Fixes #
```release-note
None
```
=> virt-api, vmi update admitter: Add a constructor

tests/network/expose.go
Use the KubeVirt client instead of using virtctl through a NewRepeatableVirtctlCommand where applicable in tests/network/expose.go.
The goal of this and further PRs is to reduce the amount of unnecessary uses of virtctl in the e2e tests to stabilize tests, to reduce the number of flakes and to remove redudant tests.
After this PR:
Fixes #
```release-note
None
```
=> cleanup(expose.go): Use client instead of virtctl

pkg/storage/types/dv.go
CDI v1.60.1 introduces a new reason `ImagePullFailed` for the DataVolume `Running` condition. Take it into account to properly update the printable status of a VM and to report the error.
The test `"[test_id:7679]should report an error status when data volume error occurs"` fails with the latest CDI v1.60.1
https://github.com/kubevirt/kubevirt/blob/a3a9e83da6fff2de37b7fd87efb43466cd6e07d4/tests/vm_test.go#L736
After this PR:
The test passes.
Fixes #
```release-note
NONE
```
=> Consider the new DV reason ImagePullFailed

tests/pausing_test.go
Use the KubeVirt client instead of using virtctl through a NewRepeatableVirtctlCommand where applicable in
tests/migration/migration.go.
Internally virtctl uses the same client call, so using virtctl does not provide any additional value.
This also drops duplicate tests combinations which can only occur when
using virtctl (e.g. pausing VM twice and pausing VMI twice, the client can
only pause VMIs and internally virtctl only gets a VM before pausing
the corresponding VMI) and reduces the amount of tests by combining the
test for VMI Ready and Paused condition and by dropping the test pausing
and unpausing a VMI multiple times, becomes this is already covered by the
check-tests-for-flakes lane.
The correctness of API calls made by `virtctl pause` and `virtctl unpause` is already covered in …
=> cleanup(tests,pausing): Use client instead of virtctl

Makefile, automation/test.sh, hack/build-go.sh, hack/check-unassigned-tests.sh
When building KubeVirt, lane logs have a lot of:
```
18:45:31: 18:45:31: [0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt
1774
18:45:33: 18:45:33: [14 / 21] ImageLayer cmd/pr-helper/version-container-layer.tar; 1s remote-cache, linux-sandbox
1775
18:45:35: 18:45:35: [14 / 21] ImageLayer cmd/pr-helper/version-container-layer.tar; 3s remote-cache, linux-sandbox
1776
18:45:36: 18:45:36: [16 / 21] GZIP cmd/pr-helper/version-container-layer.tar.gz; 0s remote-cache, linux-sandbox ... (3 actions, 2 running)
1777
18:45:38: 18:45:38: [18 / 21] GZIP cmd/pr-helper/version-container-layer.tar.gz; 2s remote-cache, linux-sandbox
1778
18:45:42: 18:45:42: [18 / 21] GZIP cmd/pr-helper/version-container-layer.tar.gz; 6s remote-cache, linux-sandbox
```
After this PR:
Progress …
=> bazel: disable progress output when running e2e test lanes

automation/github-source-tarball-signature.sh, automation/release.sh
Release source tarballs are unsigned - they don't have an external signature added as stated here: https://github.com/ossf/scorecard/blob/2ef20f17fb2e64147c83440cd2c769653454015a/docs/checks.md#signed-releases
After this PR:
Adds a step to the release creation that downloads the source tarball from the target release, generates a detached signature file, and uploads the signature file to the target release.
Requires `gh` cli tool.
The user-id to sign with is set via env GPG_USER_ID.
For successful verification on a target system the public key for the user-id used to create the signature has to be imported first. Release source tarball can be then verified using the command
```
gpg --verify ${release-tarball-file}.asc ${release-tarball-file}
```
Fixes #
The following …
=> release, verification: add source tarball signature upload

pkg/network/setup/netpod/discoverbridge.go, pkg/network/setup/netpod/netpod_test.go
PR #10396 had changed the logic deciding which routes will be passed into the VM via the DHCP server:
All non-default routes whose destination subnet contains the pod NIC's address are filtered out.
If a [CNI](https://www.cni.dev/) has defined a static route to a subnet wider than the local network of the pod's NIC - it will be filtered out.
For example, assuming the pod NIC IP address is 192.168.1.3/24, and there is the following static route:
`192.168.0.0/16 dev eth0`
it would be filtered-out.
Filter only non-default routes whose destination exactly matches the local subnet of the pod's NIC.
Fixes #12413
This checklist is not enforcing, but it's a reminder of …
=> bridge, discover: Don't filter static routes in wider subnets

tests/BUILD.bazel, tests/libssh/BUILD.bazel, tests/libssh/ssh.go, tests/vmi_vsock_test.go
Replace virtctl with netcat in tests where the example-guest-agent
needs to be copied into the VMI used to test the VSOCK functionality.
While functionally equivalent, this allows to decouple the VSOCK tests from virtctl.
NewRepeatableVirtctlCommand is used.
After this PR:
netcat is used instead.
After this PR:
Fixes # …
=> cleanup(tests,vmi_vsock): Replace virtctl with netcat

tests/operator/operator.go
Use the KubeVirt client instead of using virtctl through a 
NewRepeatableVirtctlCommand where applicable in tests/operator/operator.go.
The tests state that virtctl is used so that the subresources
for starting/stopping a VM are used. The KubeVirt client uses these
subresources too and if you look at the code of virtctl you see that it
does nothing different than calling the client like the tests do now.
After this PR:
Fixes # …
=> cleanup(operator.go): Use client instead of virtctl

pkg/virt-api/api.go, pkg/virt-api/webhooks/utils.go, pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, tests/storage/datavolume.go
Would always do clone authorization check, even if the DataVolume exists.  This can be problematic with clones because the original clone source namespace may have been deleted.  Or in the case of restoring to a different cluster, never exist
After this PR:
Only do clone auth check when DataVolume does not exist.
Fixes #12204
Eventually we will probably entirely remove the auth check from virt-api. virt-controller checks auth as well
```release-note
virt-api: skip clone auth check when DataVolume already …
```
=> virt-api: skip clone auth check when DataVolume already exists

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
In the pod eviction admitter some dry run requests were not caught due to KubeVirt only checking the dry-run field in the admission review but not in the object contained in the admission review.
This was causing dry run requests made through kubectl drain using the '--dry-run=server' flag to be processed as non dry-run requests.
It's possible that this is Kubernetes bug but it should be anyway fixed fixed in the meantime.
dry run requests made through kubectl drain using the '--dry-run=server' flag are processed as non dry-run requests
After this PR:
dry run requests made through kubectl drain using the '--dry-run=server' flag are processed correctly
Fixes #
Links to places where the discussion …
=> fix: correctly check dry-run requests

tests/launchsecurity/sev.go, tests/realtime/realtime.go, tests/storage/storage.go, tests/utils.go, tests/virtiofs/datavolume.go, tests/vmi_configuration_test.go
Follow up for https://github.com/kubevirt/kubevirt/pull/12612.
This Pull Request eliminates the `BinBash` const from test/utils so tests from other packages don't depend on it.
```release-note
NONE
```
=> Tests cleanup: Use /bin/bash directly

tests/console/console.go
The LinuxExpecter function watches the console for the beginning of the Linux boot (in order to ensure that keystrokes will not be sent to the firmware.  This is inherently racy because it's easy to miss the initial "Linux version" string if the expecter is not connected to the console quickly enough.  We can make it less racy by allowing other strings to match.  Switch to ExpectSwitchCase and add a regex for systemd messages which occur more frequently and throughout the boot process.
This does not completely eliminate the race but should help immensely.
Before this PR: [sig-storage]VM state tests are flaky
After this PR: [sig-storage]VM state tests are less flaky …
=> tests: Allow more matches when watching Linux console

automation/test.sh
PR https://github.com/kubevirt/kubevirt/pull/12594 was aiming to limit tests labelled as PERIODIC
to periodic lanes identifying them according to
the name of the test lane.
But it was incorrectly using the TARGET variable
leading to mismatches. Correctly use
JOB_NAME variable instead.
Fixes #
```release-note
NONE
```
=> [test] correctly identify periodic test lanes by JOB_NAME

tests/vmi_lifecycle_test.go
Use the KubeVirt client instead of using virtctl through a
NewRepeatableVirtctlCommand where applicable in tests/vmi_lifecycle_test.go.
Internally virtctl uses the same client call, so using virtctl does not provide
any additional value.
This also handles a previously unhandled error and drops the unused
nowAsJSONWithOffset helper.
The correctness of API calls made by virtctl unpause is already covered in unit
tests specified in pkg/virtctl/pause/pause_test.go.
After this PR:
The KubeVirt client is used instead.
Fixes #
The following …
=> cleanup(tests,vmi_lifecycle): Use client instead of virtctl and minor cleanups

docs/container-register-disks.md, docs/discard-passthrough.md, docs/quarantine.md, docs/release.md
- a few small spelling issues within docs
After this PR:
- less spelling issues within docs
Fixes #
- N/A
- N/A
- leaving the spelling issues as is
Links to places where the discussion took place: N/A
- Hi there, this project is incredible :smile: !  I was just looking through the docs and caught a few spelling issues that I wanted to fix.  I'm super willing to iterate and do anything necessary to help get this PR merged in :smile:. 
```release-note
NONE
```
=> docs: Small Spelling Fixes

pkg/virt-controller/watch/vm_test.go, tests/vm_test.go
Currently, our tests create a VM and then use
"tests.RetryWithMetadataIfModified()" to update
the VM with annotations.
This process involves creating the VM object in
a non-running state, patching it with annotations,
and then starting it.
Instead, setting annotations during VM creation
simplifies the process and improves efficiency.
Additionally, remove irrelevant functional test
that was testing carrying annotations from VM
to VMI and ignoring "kubevirt.io" and
"kubernetes.io" labels. This filtering and
functionality was removed in PR kubevirt#3110.
Instead, add a new unit test that tests the
scenario where VM's annotations can not be
carried to VMI annotations.
```release-note
None
```
=> tests: remove and set annotations on VM creation

pkg/network/dns/BUILD.bazel, pkg/network/dns/resolveconf.go, pkg/network/driver/BUILD.bazel, pkg/network/driver/common.go, pkg/virt-launcher/virtwrap/converter/BUILD.bazel, pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/network.go
The GetResolvConfDetailsFromPod function reads and parses `/etc/resolv.conf` - the DNS resolver's configuration file.
Move it from `pkg/virt-launcher/virtwrap/converter` to the `pkg/network/dns` package - under SIG network's ownership.
Fixes #
```release-note
None
```
=> net: Decouple DHCP server from converter pkg

pkg/virtctl/imageupload/BUILD.bazel, pkg/virtctl/imageupload/imageupload.go, pkg/virtctl/imageupload/imageupload_test.go
The golden image workflow in the UI needs a DataSource with a default-preference label, so extend the image-upload virtctl command to optionally create this DataSource and label it after image was uploaded.
```release-note
Optionally create data source using virtctl image upload.
```
=> feat: create datasource after image uploaded

pkg/virt-operator/BUILD.bazel, pkg/virt-operator/kubevirt_test.go
This series of commits gradually remove complexity of pool tests to the point where we reduce the runtime from ~22 seconds down to ~200ms. On top of this we remove some unnecessary code and fix few issues.
These changes follow the logic introduced here https://github.com/kubevirt/kubevirt/pull/12468
```release-note
NONE
```
=> Virt operator: improve test time

tests/console/console.go, tests/vm_state_test.go
This is not really needed as we could just ensure we're past boot via the guest agent condition.
This expecter has proven to be racy as well.
Fixes #
```release-note
NONE
```
=> vm state tests: get rid of custom console expecter

manifests/generated/operator-csv.yaml.in, manifests/generated/rbac-operator.authorization.k8s.yaml.in, pkg/storage/export/export/BUILD.bazel, pkg/storage/export/export/export.go, pkg/util/status/BUILD.bazel, pkg/util/status/status.go, pkg/virt-operator/resource/generate/components/crds.go, pkg/virt-operator/resource/generate/rbac/controller.go
After this PR:
status subresource enabled and consumed by virt-controller
Fixes #
```release-note
vmexport: enable status subresource for VirtualMachineExport
```
=> vmexport: enable status subresource for VirtualMachineExport

docs/metrics.md, pkg/monitoring/metrics/virt-controller/vmstats_collector.go, pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go
No metric with VM CPU resource requests data
After this PR:
kubevirt_vm_resource_requests hold CPU resource requests for VMs
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-46076
```release-note
Add kubevirt_vm_resource_requests for CPU resource
```
=> Add kubevirt_vm_resource_requests for CPU resource

pkg/storage/snapshot/snapshot.go, pkg/storage/snapshot/snapshot_test.go, pkg/storage/snapshot/source.go, tests/storage/snapshot.go
Just look for a VMI
Would check the VM run strategy when determining when a VM is running. Current code has faulty assumption that `Always` or `RerunOnFailure` means that VM cannot be stopped
After this PR:
Don't check .
Fixes #12515
```release-note
vmsnapshot: when checking if a VM is running, ignore runStrategy
```
=> vmsnapshot: when checking if a VM is running, ignore runStrategy

pkg/virt-api/webhooks/fuzz/fuzz_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-config/deprecation/feature-gates.go, pkg/virt-config/feature-gates.go, tests/migration/migration.go, tests/numa/BUILD.bazel, tests/numa/numa.go, tests/performance/BUILD.bazel, tests/performance/realtime.go, tests/realtime/realtime.go, tests/testsuite/kubevirtresource.go
First introduced by #5846 way back in v0.43.0 the NUMA feature gate is now deprecated with the feature state graduated to GA and as such always enabled.
Fixes #
```release-note
The `NUMA` feature gate is now deprecated with the feature state graduated to `GA` and thus enabled by default
```
=> config: Graduate NUMA featuregate to GA

examples/vm-alpine-datavolume.yaml, examples/vm-alpine-multipvc.yaml, examples/vm-cirros-clarge-virtio.yaml, examples/vm-cirros-clarge-windows.yaml, examples/vm-cirros-clarge.yaml, examples/vm-cirros-cluster-csmall.yaml, examples/vm-cirros-csmall.yaml, examples/vm-cirros-sata.yaml, examples/vm-cirros-with-sidecar-hook-configmap.yaml, examples/vm-cirros.yaml, examples/vm-priorityclass.yaml, examples/vm-windows-clarge-windows.yaml, tools/vms-generator/utils/utils.go
example vms are being generated with running field
After this PR:
examples vms will be generated with runStrategy instead of running
relates to issue: #11993
Partially addresses issue #12285 by replacing `spec.running` with `spec.runStrategy`
Links to places where the discussion took place:
```release-note
NONE
```
=> tools/vms-generator: use runStrategy for example VMs instead of running

pkg/virt-launcher/monitor_test.go
Reduce runtime of these test from ~38s down to ~6s. Major setbacks where locks that were held by goroutines and were only released when fake process times out.
Fixes #
```release-note
NONE
```
=> Monitor tests reduce runtime

tests/storage/export.go
This test is failing due to a bug - https://issues.redhat.com/browse/CNV-47542
and only succeeds as a fluke when the VM is stopped before the expansion could happen.
Quarantine while the issue is being worked on.
After this PR:
Fixes #
```release-note
NONE
```
=> Quarantine high impact failure in sig storage

pkg/instancetype/BUILD.bazel, pkg/instancetype/compatibility_test.go, pkg/instancetype/instancetype.go, pkg/instancetype/instancetype_test.go, tests/instancetype/instancetype.go
/cc @0xFelix 
$subject, this removes the final use of this package and replaces it `kubevirt.io/kubevirt/pkg/pointer`.
After this PR:
Fixes #
```release-note
NONE
```
=> instancetype: Remove use of `k8s.io/utils/ptr`

tests/sysprep_test.go, tests/utils.go
There is no need to make the entire tests package be aware of the location of an image used by a single test lane.
```release-note
NONE
```
=> tests: move DiskWindowsSysprep next to its only user

pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go
- Move the unit tests to the `admitters_test` package in order to explicitly test public API.
- Use fresh admitter instance per test.
- Extract the instantiation of the AdmissionRequest to a single function.
- Expect the full admission response.
Also, simplify the allowed response in the production code.
Fixes #
```release-note
None
```
=> Migration update admitter: Refactor tests

pkg/monitoring/metrics/virt-controller/vmistats_collector.go, pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
kubevirt_vmi_info is collected by telemetry systems but does not contain information on whether the VMI is evictable or not. And we don't want to collect additional metrics such as kubevirt_vmi_non_evictable
After this PR:
kubevirt_vmi_info contains "evictable" label stating if the VMI is or not evictable
jira-ticket: https://issues.redhat.com/browse/CNV-46653
Fixes #
```release-note
Add evictable label to kubevirt_vmi_info
```
=> Add evictable label to kubevirt_vmi_info

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/12353 and https://github.com/kubevirt/kubevirt/pull/12696.
Fixes #
```release-note
NONE
```
=> [release-1.3] fix: correctly check dry-run requests

pkg/virt-api/api.go, pkg/virt-api/webhooks/utils.go, pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, tests/storage/datavolume.go
After this PR:
manual cherry-pick of #12547
Fixes #
```release-note
virt-api: skip clone auth check when DataVolume already exists
```
=> [release-1.1] virt-api: skip clone auth check when DataVolume already exists

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
Manual backport https://github.com/kubevirt/kubevirt/pull/12696.
```release-note
NONE
```
=> [release-1.2] fix: correctly check dry-run requests

tests/instancetype/upgrade.go
When replacing the original CR the test asserts that it is removed from the cluster. This can take the controller some time to complete in a busy env so move this check into an Eventually call.
Reported downstream within RH under https://issues.redhat.com/browse/CNV-48098 with the following trace:
```
tests/instancetype/upgrade.go:340
Expected an error to have occurred.  Got:
<nil>: nil
tests/instancetype/upgrade.go:178
```
AFAICT this hasn't failed recently upstream searching on [`search.ci.kubevirt.io`](https://search.ci.kubevirt.io/?search=%22ControllerRevision+Upgrades+should+upgrade%22&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)
Fixes #
Links …
=> instancetype: Harden CR upgrade func test

pkg/virt-api/api.go, pkg/virt-api/webhooks/utils.go, pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, tests/storage/datavolume.go
After this PR:
manual cherry-pick of #12547
Fixes #
```release-note
virt-api: skip clone auth check when DataVolume already exists
```
=> [release-1.3] virt-api: skip clone auth check when DataVolume already exists

tests/BUILD.bazel, tests/softreboot_test.go
Use the KubeVirt client instead of using virtctl through a
NewRepeatableVirtctlCommand where applicable in tests/softreboot_test.go.
Internally virtctl uses the same client call, so using virtctl does not provide
any additional value.
This also removes unnecessary nesting of tests (When/It) to make the test
definitions easier to read.
The correctness of API calls made by virtctl softreboot is already covered in
unit tests specified in pkg/virtctl/softreboot/softreboot_test.go.
After this PR:
Fixes # …
=> cleanup(tests,softreboot): Use client instead of virtctl

pkg/virt-api/api.go, pkg/virt-api/webhooks/utils.go, pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, tests/storage/datavolume.go
After this PR:
manual cherry-pick of #12547
Fixes #
```release-note
virt-api: skip clone auth check when DataVolume already exists
```
=> [release-1.2] virt-api: skip clone auth check when DataVolume already exists

pkg/network/multus/BUILD.bazel, pkg/network/multus/annotation_test.go, pkg/network/multus/multus_suite_test.go
Following PR #12480, the code responsible for Multus' low-level annotation generation was moved under `pkg/network/multus`.
Add the missing suite file that causes the tests to run.
Fix the broken annotation pool test.
Fixes #
```release-note
NONE
```
=> net, multus annotations, test: Add missing suite file

tests/storage/hotplug.go, tests/storage/storage.go, tests/utils.go
Only storage tests need these paths, so they should not be exposed elsewhere.
```release-note
NONE
```
=> tests: move {Disk,}CustomHostPath into storage package

tests/realtime/realtime.go, tests/security_features_test.go, tests/utils.go, tests/vm_test.go, tests/vmi_configuration_test.go
The GetRunningVMIEmulator() function is short, trivial and does not simplify the code in any way, but rather makes it more complex by creating another layer of indirection.
As a bonus, we get to shorten tests/utils.go by getting rid of it.
```release-note
NONE
```
=> Inline GetRunningVMIEmulator() and remove it from tests/utils.go

tests/storage/migration.go
E2e storage migration helpers `UpdateVMWithPVC` and `UpdateVMWithDV` use client Update operation   to mutate the test VM object.
After this PR:
E2e storage migration helpers `UpdateVMWithPVC` and `UpdateVMWithDV` use client Patch to mutate the test VM object.
Fixes #
The code that finds the index of the subject volume name is simplified by using builtin `slices`.
```release-note
NONE
```
=> e2e, storage-migration: Replace client Update operations with patch

pkg/virt-api/rest/authorizer.go, pkg/virt-api/rest/authorizer_test.go
After this PR:
manual backport of #12460
Fixes #
```release-note
virt-api: unencode authorization extra headers
```
=> [release-1.1] virt-api: unencode authorization extra headers

pkg/virt-controller/watch/vm.go, tests/storage/migration.go
Hotplug is broken when the Volume migration feature gate is enabled. The volume update due to the imperative hotplug are interpreted as a replacement of the volumes.
After this PR:
Hotplug properly works with the volume migration feature gate enabled
Fixes #12670
```release-note
NONE
```
=> volume migration: fix hotplug volumes when the volume migration fg is enabled

tests/clone_test.go, tests/instancetype/instancetype.go, tests/operator/operator.go, tests/pool_test.go, tests/storage/restore.go, tests/storage/snapshot.go, tests/subresource_api_test.go, tests/virtctl/create_vm.go, tests/vm_test.go, tests/vmi_cloudinit_test.go
Deprecate the use of spec.Running and use spec.RunStrategy instead.
Before this PR: using spec.Running in e2e tests
After this PR: using spec.RunStrategy in e2e tests
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-45444
relates to issue: #11993
```release-note
NONE
```
=> tests: remove use of spec.Running from e2e tests

automation/test.sh, pkg/util/util.go, tests/access_test.go, tests/container_disk_test.go, tests/decorators/decorators.go, tests/storage/storage.go, tests/testsuite/kubevirtresource.go, tests/vmi_configuration_test.go, tests/vmi_lifecycle_test.go
There are no e2e tests enabled for s390x.
After this PR:
A subset of the existing e2e tests is enabled for s390x and tested against external CI cluster. All these tests which are tagged with [s390x] are tested against s390x cluster are passing.
Fixes #
```release-note
enable initial e2e tests for s390x.
```
=> enable initial e2e tests for s390x.

hack/functests.sh, tests/tests_suite_test.go
Ginkgo V2 has the decorator [Serial](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#serial-decorator) that is designed for running tests in serial. Also the [docs for parallel test support](https://onsi.github.io/ginkgo/#spec-parallelization) say that the test results will be captured in one output stream in Ginkgo 2.
In https://github.com/kubevirt/kubevirt/pull/8770 we have added the Serial decorator and modified the checks for tests running serial.
We are now removing the unnecessary shell code and the output file handling here, since the merge is no longer necessary. Thus also the fuss around output file names was removed from `tests_suite_test.go`.
Also we are adding `KUBEVIRT_FUNC_TEST_GINKGO_TIMEOUT` as variable to the script in order to be …
=> [rebased] Update tests wrt ginkgo 2: remove scripting running parallel vs. serial tests

pkg/libvmi/vm.go, pkg/storage/backend-storage/backend-storage.go, pkg/storage/backend-storage/backend-storage_test.go, pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_base.go, pkg/storage/snapshot/restore_test.go, pkg/virt-api/rest/subresource_test.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go, pkg/virtctl/memorydump/memorydump_test.go, tests/storage/restore.go, tests/virtctl/create_vm.go
In VM restore we updated/created the vm before the creation of the restored datavolumes
After this PR:
Instead of creating/updating the vm before the creation of the dv we create the dvs (as we do for the pvcs) before the
creation/update of the restored VM.
This is needed in order to prevent a race between the creation of the dvs by the restore controller and the vm contoller.
Also this makes the update of the VM spec to be after making sure all the new volumes of the restored vm exist without any errors so it prevents a case of having the vm spec updated with volumes that doesnt exist and cannot exist due to some error.
Add the prePouplated annotation to the DataVolumes to show CDI that no action is required on the dv other then owning and adopting the PVC. (For example …
=> VMRestore: create DVs before creation/update of restored VM

tests/subresource_api_test.go, tests/vm_test.go
Move the VM subresource tests without run strategy from tests/vm_test.go
into tests/subresource_api_test.go, clean them up a little and use the
KubeVirt client instead of virtctl through a NewRepeatableVirtctlCommand
where applicable.
Drop "[test_id:6310]should start a VirtualMachineInstance in paused
state" which is already covered by "[test_id:4597]should signal paused
state with condition" in tests/pausing_test.go.
After this PR:
The KubeVirt client is used instead.
Fixes #
The following alternatives …
=> cleanup(tests): Move VM subresource tests without run strategy and drop redundant tests

pkg/virt-handler/BUILD.bazel, pkg/virt-handler/options.go, pkg/virt-handler/options_test.go
VMI options parsing wasn't covered in terms of unit testing.
VMI options parsing is now covered in terms of unit testing.
Partially addresses https://github.com/kubevirt/kubevirt/pull/12652 which introduces additional logic to `options.go` and requires that certain changes be made to it. 
Struct initialization values reference [capabilities.xml](https://github.com/kubevirt/kubevirt/blob/3766e045c0157db9bc23cbd2698fd8e2809dea4f/pkg/virt-handler/node-labeller/testdata/capabilities.xml) and [capabilities_with_numa.xml](https://github.com/kubevirt/kubevirt/blob/3766e045c0157db9bc23cbd2698fd8e2809dea4f/pkg/virt-handler/node-labeller/testdata/capabilities_with_numa.xml) respectively.
This checklist is not enforcing, but it's a reminder of items that could …
=> [virt-handler]: Add options_test.go to test host capabilities parsing

.github/ISSUE_TEMPLATE/flaky_test_report.md
Flaky tests had to be reported with the standard issue templates.
After this PR:
Adds a template with which flaky tests can be reported.
Fixes #
/cc @brianmcarey @xpivarc 
```release-note
NONE
```
=> kubevirt, ci: add GitHub issue template for flaky tests

hack/bootstrap-ginkgo.sh, staging/src/kubevirt.io/api/apitesting/BUILD.bazel, staging/src/kubevirt.io/api/apitesting/apitesting_suite_test.go, staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/BUILD.bazel, staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/v1_suite_test.go
Some logical errors were present in this script:
- Does not check all folders
- Path to ginkgo binary wrong
Fixes #12774 
```release-note
NONE
```
=> Fix ginkgo bootstrapping script

manifests/generated/operator-csv.yaml.in, manifests/generated/rbac-operator.authorization.k8s.yaml.in, pkg/virt-operator/resource/generate/rbac/BUILD.bazel, pkg/virt-operator/resource/generate/rbac/controller.go, pkg/virt-operator/resource/generate/rbac/controller_test.go
Basically, OpenShift deploys enforcement that says we
`cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on` https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
We recently removed this rbac unintentionally in https://github.com/kubevirt/kubevirt/pull/12605/commits/dc6b76f494ffdb95305fed5ce038963539d469a1.
Fixes #
```release-note
BugFix: can't create export pod on OpenShift
```
=> Re-add finalizer update RBAC for VM export

tests/storage/restore.go
this flake is biting us quite frequently:
https://search.ci.kubevirt.io/?search=%5E+*%3C%5C*string+%5C%7C+0x0%3E%3A+nil%24&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
since we know this is just about the dataVolumeName field sometimes missing, we can quarantine until this is fixed.
Fixes #
```release-note
NONE
```
=> tests: quarantine flaky restore tests

tests/storage/export.go
The updated version of CDI in the Bump kubevirtci PR[1] has exposed an issue[2] with these two tests[3]
Quarantine these tests until the issue is resolved
[1] https://github.com/kubevirt/kubevirt/pull/12677
[2] https://github.com/kubevirt/kubevirt/issues/12792
[3] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12677/pull-kubevirt-e2e-k8s-1.31-sig-storage/1833875700851937280
Fixes #
/cc @akalenyu @awels @dhiller 
```release-note
NONE
```
=> e2e,storage: Quarantine two failing export tests due to bug

automation/repeated_test.sh
As noted here [1] `repeated_tests.sh` can only run either native or non native ssh tests, since what works depends on how the virtctl binary is built.
After this PR:
Since test.sh always excludes the native ssh tests [2] we add the filter to do the same for `repeated_test.sh`
[1]: https://github.com/kubevirt/kubevirt/pull/12804#issuecomment-2346046040
[2]: https://github.com/kubevirt/kubevirt/blob/6fb17773c7dddb9c9a526959605eb5acf07619cc/automation/test.sh#L479
Fixes #12814
#12804
/cc @0xFelix 
```release-note
NONE
```
=> check-tests-for-flakes: don't run native ssh tests

pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/12451
```release-note
Fix: eviction requests to completed virt-launcher pods cannot trigger a live migration
```
=> [release-1.1] Admit eviction on completed virt-launcher pods

pkg/ephemeral-disk/BUILD.bazel, pkg/ephemeral-disk/ephemeral-disk_test.go
=>  Refactor unit tests to use libvmi for resource creation in ephemeral-disk

pkg/virtctl/vm/BUILD.bazel, pkg/virtctl/vm/expand_test.go, tests/vm_test.go
These tests do not require a working cluster and do not provide
additional value to unit tests. Therefore these tests are dropped in
favor of the unit tests in pkg/virtctl/vm/expand_test.go.
The virtctl expand tests are refactored and add test cases for tests removed
in the previous commit are added.
The same virtctl expand tests are run in unit and functests.
After this PR:
virtctl expand tests run only in unit tests.
Fixes #
Merge after …
=> Drop virtctl expand functests and refactor unit tests 

tests/usbredir_test.go
As we spawn all clients in parallel we can't be
sure what goroutine will run sooner than others.
It well could be that last goroutine is running before the first.
Note: There still seem to be issue with the test as the code suggest that return value should be http status code 503 and not 500.
Fixes #
```release-note
NONE
```
=> usbredit: Don't assume order for client

pkg/virt-api/webhooks/mutating-webhook/mutators/clone-create-mutator_test.go, pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator.go, pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator_test.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go, pkg/virt-controller/watch/node.go, tests/hotplug/memory.go, tests/libkubevirt/config/kvconfig.go, tests/libkubevirt/config/netbinding.go, tests/libnet/hotplug.go, tests/libnode/node.go, tests/monitoring/component_monitoring.go, tests/pool_test.go
Directly using the [PatchOperation struct](https://github.com/kubevirt/kubevirt/blob/main/pkg/apimachinery/patch/patch.go#L28)
After this PR:
We are trying to simplify the patch operations and use everywhere in the code the [PatchSet](https://github.com/kubevirt/kubevirt/blob/main/pkg/apimachinery/patch/patch.go#L68). Eventually, we could set the PatchOperation struct as private.
```release-note
None
```
=> Replace the PatchOperation with the PatchSet

automation/test.sh
We are running e2e tests on changes that have no effect on the codebase, i.e. changes or additions to GitHub templates.
After this PR:
We already exclude doc only changes. This change also adds the `.github` folder to the folders which we don't run e2e tests on.
Fixes #
https://github.com/kubevirt/kubevirt/pull/12448#issuecomment-2346446049
```release-note
NONE
```
=> CI, GitHub: do not run e2e tests on gh only changes

tests/migration/migration.go
Migration bandwidth tests **are serial** and rely on changing **Kubevirt CR's cluster-wide configurations** to reduce migration bandwidth.
After this PR:
Migration bandwidth tests are **not serial** and rely on **migration policies** reduce migration bandwidth only for the specific VMI that's being tested.
```release-note
NONE
```
=> Parallelize migration bandwidth tests by relying on migration policies instead of KubevirtCR

tests/storage/storage.go, tests/utils.go, tests/vmi_configuration_test.go
This constant is used in the storage tests and the vmi configuration tests.
It is only used once in the VMI configuration tests and it can be set to any path.
Move the constant from utils to where is it used multiple times in the storage tests
Fixes #
```release-note
NONE
```
=> e2e,utils: Remove const that is only really used by the storage tests

tests/usbredir_test.go
ClientConnect is running in goroutine as well.
Therefore we need another defer here.
Fixes #
```release-note
NONE
```
=> usbdir test: Add missing defer GinkgoRecover

pkg/storage/snapshot/BUILD.bazel, pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_base.go, pkg/storage/snapshot/restore_test.go, pkg/virt-api/rest/subresource_test.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go, pkg/virtctl/memorydump/memorydump_test.go, tests/framework/matcher/getter.go, tests/framework/matcher/phase_test.go, tests/libdv/dv.go, tests/libstorage/datavolume.go, tests/libvmi/vm.go, tests/storage/restore.go, tests/virtctl/create_vm.go
This is a manual backport of PR https://github.com/kubevirt/kubevirt/pull/12764
NOTE On top of the backport Im adding another commit that was not introduced in the original PR since after the original PR merged a flake started to happen more frequently. I cherry-picked a commit that puts those tests in Quarantine as explained in PR: https://github.com/kubevirt/kubevirt/pull/12824
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-47105
Fixes #
```release-note
bugfix: vmrestore create DVs before creation/update of …
```
=> [release 1.2] VMRestore: create DVs before creation/update of restored VM

pkg/virt-handler/vm.go, pkg/virt-launcher/virtwrap/live-migration-source.go, pkg/virt-launcher/virtwrap/live-migration-target.go, staging/src/kubevirt.io/api/core/v1/types.go, tests/storage/migration.go
The libvirt option MIGRATE_NON_SHARED_INC wasn't set for volume migration
After this PR:
Consider block migration when there is a volume update change with shareable storage.
Fixes #12811
```release-note
NONE
```
=> volume-migration: fix migration from source RWX volumes

tests/virtctl/scp.go, tests/virtctl/ssh.go
This partially reverts the cleanups of
be4d5584723cf9205976d37b6c9753285c02ee5c, because the now reverted
changes invalidate the results of the changed tests.
For the tests to have a meaningful result, the actual virtctl binary
needs to run (CreateCommandWithNS) instead of running the virtctl
command as part of the test binary (NewRepeatableVirtctlCommand).
Tests do not have a meaningful result
After this PR:
Tests have a meaningful result
Fixes #
```release-note
None
```
=> fix(tests,virtctl): Partially revert cleanups

cmd/dump/dump.go, tests/reporter/BUILD.bazel, tests/reporter/kubernetes.go
Migration policies are not dumped as part of the `AfterSuite` after tests finish.
After this PR:
Migration policies are dumped as part of the `AfterSuite` after tests finish.
Tested locally:
```shell
> cat _out/artifacts/k8s-reporter/1_migrationpolicies.log 
{
"metadata": {
"resourceVersion": "247717"
},
"items": [
{
"kind": "MigrationPolicy",
"apiVersion": "migrations.kubevirt.io/v1alpha1",
"metadata": {
"name": "testpolicy-vnmz7",
"uid": "fd372a97-7974-46a5-b58f-db7039329f26",
"resourceVersion": "247708",
"generation": 1,
"creationTimestamp": "2024-09-16T07:58:39Z",
"labels": {
"test.kubevirt.io/kubevirt-test-default1": ""
}
},
"spec": {
"selectors": {
"virtualMachineInstanceSelector": {
"testpolicy-vnmz7-key-0": "testpolicy-vnmz7-value-0"
}
}
},
"status": {}
}
]
}
``` …
=> Report migration policies as part of the k8s reporter when tests finish

pkg/libvmi/status/BUILD.bazel, pkg/libvmi/status/status.go, pkg/libvmi/vmi.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/volume-migration/BUILD.bazel, pkg/virt-controller/watch/volume-migration/volume-migration.go, pkg/virt-controller/watch/volume-migration/volume-migration_test.go, pkg/virt-controller/watch/workload-updater/workload-updater.go, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go, staging/src/kubevirt.io/api/core/v1/types.go, tests/storage/migration.go
Manual backport of #12395 
The API change consists in a new condition which helps to better understand why the volume migration isn't possible.
This backport also includes the  commit from #12241 to facilitate the backport of the unit tests.
```release-note
Add new condition for VMIStorageLiveMigratable
```
=> [release.1.3] Manual backport of 12395

docs/quarantine.md
This document update covers what actions should be taken when test lanes are flaking with multiple test failures where quaranting the individual tests might not make sense.
Fixes #
/cc @dhiller @EdDev 
```release-note
NONE
```
=> doc: Extend quarantine doc to cover flaky required lanes

tests/storage/backendstorage.go
The tests under backendstorage.go would skip if no RWX file system storage was found
After this PR:
The tests under backendstorage.go will run on clusters with RWX file system storage, and remove the TODO task
```release-note
NONE
```
=> Add RequiresRWXFilesystemStorage to backendstorage.go

tests/instancetype/instancetype.go, tests/libdv/BUILD.bazel, tests/libdv/dv.go
This PR introduces `WithDefault{Instancetype,Preference` and `WithDataVolumeSourceRef` to `libdv` to address some basic `TODOs` within the instancetype functional tests.
Fixes #
```release-note
NONE
```
=> instancetypes: Address functional test TODOs and extend libdv

tests/BUILD.bazel, tests/subresource_api_test.go, tests/vm_test.go
Use the KubeVirt client instead of using virtctl through a
NewRepeatableVirtlCommand where applicable in tests/vm_test.go.
This restructures the RunStrategy related VM tests to work without
virtctl and also consolidates the tests where possible to avoid
duplication of test code.
The newVirtualMachineWithRunStrategy helper is dropped and instead the
tests create VMs with the help of libvmi now. This change allows to use
a guestless VM in most of the tests.
Drop duplicate tests in tests/subresource_api_test.go that are already
covered by tests in tests/vm_test.go and consolidate tests that assert
the behavior when trying to restart a stopped VM.
"[test_id:1304] should restart a VM" is already covered by
"[test_id:3164]with RunStrategyAlways".
"[test_id:3175]Should restart when VM is …
=> Use client instead of virtctl in RunStrategy related VM tests and cleanup subresource_api_test.go further

Makefile, pkg/network/pod/annotations/generator_test.go, pkg/storage/pod/annotations/generator.go, pkg/storage/pod/annotations/generator_test.go
PRs #12558 and #12710 introduced the following packages without linter covarage:
- pkg/network/pod/annotations
- pkg/storage/pod/annotations
Add linter coverage for both packages.
Fixes #
```release-note
None
```
=> Annotations generators: Add linter coverage

pkg/libvmi/status/status.go, pkg/network/vmispec/BUILD.bazel, pkg/network/vmispec/hotplug_test.go
Signed-off-by: ronger4 <rgershbu@redhat.com>
Unit tests directly created and modified VM and VMI resources by manipulating their fields.
After this PR:
Unit tests have been refactored to use the libvmi package for creating and modifying VM and VMI resources, promoting readability and standardization.
Unused funcs and vars are removed.
Using the libvmi package simplifies the unit tests and makes them more readable.
This approach ensures a standard way of creating VM and VMI resources across tests.
In addition, I removed unused vars and funcs.
- Direct manipulation of resources was replaced with utility functions, which may introduce minor overhead but enhances readability …
=> net, vmispec, hotplug, tests: Use libvmi for resource creation

pkg/virt-controller/watch/vmi/vmi.go
Creation should be observed when there is any creation error to avoid [skipping reconciliation loop forever](https://github.com/kubevirt/kubevirt/blob/e5400c3ac27800989b6e11fcd403433bab6cea9d/pkg/virt-controller/watch/vmi/vmi.go#L287) for some vmis.
After this PR:
Fixes #
```release-note
NONE
```
=> [BugFix]VMIController: creation should be observed

pkg/libvmi/replicaset/BUILD.bazel, pkg/libvmi/replicaset/replicaset.go, tests/BUILD.bazel, tests/infrastructure/BUILD.bazel, tests/infrastructure/k8s-client-changes.go, tests/network/BUILD.bazel, tests/network/expose.go, tests/replicaset_test.go, tests/utils.go
Move tests.NewRandomReplicaSetFromVMI from test/utils to a properly-named new package & file under libvmi.
Fixes #
This PR supersedes #12405 , rebasing and relocating the suggested builder under a libvmi sub-package.
```release-note
NONE
```
=> libvmi: Introduce replicaset subpackage builder

pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go, pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go, tests/BUILD.bazel, tests/pdb_test.go
When a Virtual Machine Instance (VMI) reaches its Final state (whether Succeeded or Failed, such as after a guest OS shutdown), the associated Pod Disruption Budget (PDB) is not deleted. This can lead to unnecessary PDB alerts being triggered.
The Pod Disruption Budget (PDB) associated with the VMI will be automatically removed once the VMI reaches its Final state. This prevents unnecessary PDB alerts from being triggered.
Without this fix, when a VMI is shut down from within the guest OS (or in similar cases), a PDB alert is triggered unnecessarily, potentially misleading users about the actual state of their VMs. This fix ensures that PDBs are properly cleaned up.
**Approach:**
The chosen solution deletes the PDB when the VMI reaches either the …
=> bug-fix: Ensure PDB Deletion when VMI Reaches Final State

hack/cluster-clean.sh, pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_base.go, pkg/storage/snapshot/restore_test.go, tests/storage/restore.go
Before this PR: VMRestore gets deleted without any cleanup of validation it can be deleted.
After this PR:     When calling delete on the restore we must make sure we are not leaving on the vm the restoreInProgress annotation. For that added a finalizer on the vmrestore object making sure it is not deleted until we remove the annotation from the vm. Queued the vmrestore object in case of deletion, then if the vm exists we remove the restore in progress annotation if it is for the same restore, only then remove restore finalizer allowing it to be deleted.
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-47106 …
=> bugfix: In case of err in vmrestore, leave VM without RestoreInProgress annotation allowing it to be started

pkg/virtctl/vm/add_volume.go, pkg/virtctl/vm/add_volume_test.go, pkg/virtctl/vm/remove_volume.go, pkg/virtctl/vm/remove_volume_test.go
When adding many volumes concurrently using virtctl one can get failures due to concurrent modifications of the VM resource.
After this PR:
When adding many volumes concurrently using virtctl, all the volumes are added successfully.
Fixes https://issues.redhat.com/browse/CNV-31844
```release-note
Concurrent addvolume/removevolume using virtctl no longer fail if concurrent modifications happen
```
=> Retry up to 15 times when hotpluggin a volume with virtctl

.golangci.yml, pkg/instancetype/instancetype.go, tests/instancetype/instancetype.go
there was a need to exclude some instancetype source files for the 'mnd' linter.
After this PR:
Remove the instancetype source files from the 'mnd' ignored files by solving the errors they produce.
Fixes #12662 
```release-note
None
```
=> Coverage for instance type resource using linter mnd

pkg/virtctl/vmexport/BUILD.bazel, pkg/virtctl/vmexport/vmexport.go, pkg/virtctl/vmexport/vmexport_test.go
OpenShift enables this admission controller - https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
So the user running virtctl needs to have permission to vmexport/finalizers 'update'
which I don't think we're too inclined to give out.
We can just not block owner deletion over the secret disappearing.
Fixes #
```release-note
BugFix: Fail to create VMExport via virtctl vmexport create
```
=> Stop setting blockOwnerDeletion on vmexport secret owner ref

api/openapi-spec/swagger.json, manifests/generated/kv-resource.yaml, pkg/virt-api/webhooks/defaults.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/hotplug/cpu.go
See issue for background. Now `MaxCpuSockets` will no be used if a VM defines more sockets but rather the #of sockets will be used for `MaxSockets`.
Fixes #12394
```release-note
MaxCpuSockets won't block creation of VMs with more Sockets than MaxCpuSockets declare
```
=> Fix behaivor of MaxCpuSockets

tests/kubectl_test.go
Instead of Updating VM runStrategy in kubectl_test.go create vm with with the desired runStrategy.
After this PR:
Fixes #
```release-note
NONE
```
=> [Tests]kubectl_test.go:Reduces API calls during the test

pkg/virt-controller/services/template_test.go
https://github.com/kubevirt/kubevirt/pull/10852 Added the appropriate logic to propagate virt-launcher Pod tolerations to the hotplug Pod but didn't add a matching unit test.
Adds a test to check whether VMI/virt-launcher tolerations are correctly propagated to the rendered hotplug Pod.
```release-note
NONE
```
=> [virt-controller/services] Add test for computing hotplug tolerations

tests/network/sriov.go
Neither tests.GetRunningVMIDomainSpec nor
tests.GetRunningVirtualMachineInstanceDomainXML should be used in end-to-end test. But for this specific test, GetRunningVMIDomainSpec is slightly better, as it makes the test code slightly shorter.
```release-note
NONE
```
=> tests/network/sriov: do not reimplement tests.GetRunningVMIDomainSpec

go.mod, tests/operator/BUILD.bazel, tests/operator/operator.go
This PR removes the CDI recovery code in the AfterEach block in tests/operator since there are no tests that changes the cdi resource
```release-note
None
```
=> tests/operator/operator.go: Remove CDI resource recovery in AfterEach

pkg/network/admitter/BUILD.bazel, pkg/network/admitter/slirp_test.go
Signed-off-by: ronger4 <rgershbu@redhat.com>
Unit tests directly created and modified VM and VMI resources by manipulating their fields.
After this PR:
Unit tests have been refactored to use the libvmi package for creating and modifying VM and VMI resources, promoting readability and standardization.
Using the libvmi package simplifies the unit tests and makes them more readable.
This approach ensures a standard way of creating VM and VMI resources across tests.
None
This …
=> Refactor net/admitter/slirp/tests to use libvmi package

docs/metrics.md, pkg/monitoring/metrics/virt-controller/BUILD.bazel, pkg/monitoring/metrics/virt-controller/vmistats_collector.go, pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go, pkg/monitoring/metrics/virt-controller/vmstats_collector.go, pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go
The only info available was about VMIs. Since Virtual Machines may not have been started yet, we would have no metrics about them. Users may be interested in this information to predict cluster state and capacities.
After this PR:
kubevirt_vm_info adds information about VMs not started yet
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-46768
```release-note
Add kubevirt_vm_info metric
```
=> Add kubevirt_vm_info metric

tests/migration/migration.go
I'm not sure why we need to test domxml here, but we certainly do not need to reimplement GetRunningVMIDomainSpec. This PR makes the test code a bit shorter.
```release-note
NONE
```
=> tests/migration: no need to reimplement tests.GetRunningVMIDomainSpec

pkg/instancetype/instancetype.go, pkg/storage/snapshot/BUILD.bazel, pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_base.go, pkg/storage/snapshot/restore_test.go, pkg/virt-api/rest/subresource_test.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go, pkg/virtctl/memorydump/memorydump_test.go, pkg/virtctl/vm/add_volume_test.go, tests/framework/matcher/getter.go, tests/framework/matcher/phase_test.go, tests/libdv/dv.go, tests/libstorage/datavolume.go, tests/storage/restore.go, tests/virtctl/create_vm.go
This is a manual backport of PR https://github.com/kubevirt/kubevirt/pull/12764
NOTE On top of the backport Im adding another commit that was not introduced in the original PR since after the original PR merged a flake started to happen more frequently. I cherry-picked a commit that puts those tests in Quarantine as explained in PR: https://github.com/kubevirt/kubevirt/pull/12824
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-47105
```release-note
bugfix: vmrestore create DVs before creation/update of restored …
```
=> [release 1.1] VMRestore: create DVs before creation/update of restored VM

hack/cluster-clean.sh, pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_base.go, pkg/storage/snapshot/restore_test.go, tests/storage/restore.go
This is a manual backport of PR https://github.com/kubevirt/kubevirt/pull/12835
(removed the last commit which is only relevant to main since in this release we still use statusUpdater)
Fixes # Jira-ticker: https://issues.redhat.com/browse/CNV-48787
```release-note
bugfix: In case of err in vmrestore, leave VM without RestoreInProgress annotation allowing it to be started
```
=> [release 1.3] bugfix: In case of err in vmrestore, leave VM without RestoreInProgress annotation allowing it to be started

hack/cluster-clean.sh, pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_base.go, pkg/storage/snapshot/restore_test.go, tests/storage/restore.go
This is a manual backport of PR https://github.com/kubevirt/kubevirt/pull/12835
(removed the last commit which is only relevant to main since in this release we still use statusUpdater)
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-47106
```release-note
bugfix: In case of err in vmrestore, leave VM without RestoreInProgress annotation allowing it to be started
```
=> [release 1.2] bugfix: In case of err in vmrestore, leave VM without RestoreInProgress annotation allowing it to be started

pkg/virt-controller/watch/vm/vm.go, pkg/virt-controller/watch/vm/vm_test.go
- VMIs with the same name but different namespaces previously generated the same firmware UUID.
After this PR:
- Updated UUID generation to use VMI name + namespace.
Fixes #
```release-note
None
```
=> vm-controller: fix duplicate firmware UUIDs for VMIs across namespaces

pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
MigrationCreateAdmitter:
1. Had exported fields and could be instantiated incorrectly.
2. Used the old `kubecli.KubevirtClient` clientset.
3. Used gomock for unit tests.
4. Used `v1 api` to create base VMIs for tests.
MigrationCreateAdmitter:
1. Has a constructor function and only unexported fields.
2. Uses KubeVirt's generated clientset.
3. Uses `libvmi` to create base VMIs for tests.
Fixes #
This is a follow up to https://github.com/kubevirt/kubevirt/pull/11897.
```release-note
NONE …
```
=> [virt-api, migration-create-admitter]: Use KubeVirt generated clientset

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/12696.
Fixes #
```release-note
NONE
```
=> [release-1.1] fix: correctly check dry-run requests

pkg/virt-launcher/virtwrap/api/defaults.go
Following PR #3568, this method does not contain any logic.
Fixes #
```release-note
NONE
```
=> virt-launcher, api: Rm Defaulter.SetDefaults_Devices

tests/virtctl/create_vm.go
Add the missing SigCompute decorator to the virtctl create vm functests.
After this PR:
Fixes #
```release-note
None
```
=> fix(virtctl,tests): Add missing SigCompute decorator

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
In the pod eviction admitter some dry run requests were not caught due to KubeVirt only checking the dry-run field in the admission review but not in the object contained in the admission review.
This was causing dry run requests made through kubectl drain using the '--dry-run=server' flag to be processed as non dry-run requests.
It's possible that this is Kubernetes bug but it should be anyway fixed fixed in the meantime.
(cherry picked from commit 6bdf1363534681d0d9dfaf44eb8607bbaf612869)
After this PR:
Fixes # …
=> [release-1.0] fix: correctly check dry-run requests

hack/cluster-clean.sh, pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_base.go, pkg/storage/snapshot/restore_test.go, tests/storage/restore.go
This is a manual backport of PR https://github.com/kubevirt/kubevirt/pull/12835
(removed the last commit which is only relevant to main since in this release we still use statusUpdater)
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-48788
```release-note
bugfix: In case of err in vmrestore, leave VM without RestoreInProgress annotation allowing it to be started
```
=> [release 1.1] bugfix: In case of err in vmrestore, leave VM without RestoreInProgress annotation allowing it to be started

OWNERS_ALIASES
Alona is no longer actively reviewing PRs in the project. Therefore, help Prow bot to avoid automatically assigning PRs for review on her name.
Fixes #
This change is made with consent from @AlonaKaplan .
```release-note
NONE
```
=> OWNERS_ALIAS: Remove Alona Kaplan from the reviewer list

pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_test.go
This miss of update was spotted in recent tests flakes, where we saw this variable missing in the test, while everything else works fine.
Looking into how this can happen I noticed the update of this variable in problematic places that with possible failure of the vmrestore status then we might not ever get to update it later.
Moving the update to before we generate the restored vm, making sure we have a dedicated function that makes sure this update is not missed. Added UT to make sure this is happening and we have the flaky tests for verification of this fix.
Those tests were quarantined in this PR: [https://github.com/kubevirt/kubevirt/pull/12824](https://github.com/kubevirt/kubevirt/pull/12824)
This changes should fix the flakes. Will remove the quarantine decorator after we will see …
=> VMRestore: fix possible miss update of dvname on vmrestore restores - fixes quarantine tests

tests/monitoring/vm_monitoring.go
This test is too flaky, it fail https://github.com/kubevirt/kubevirt/pull/12645 
KubevirtVmHighMemoryUsage alert is flaky 
After this PR:
KubevirtVmHighMemoryUsage alert is quarantine 
Fixes #https://github.com/kubevirt/kubevirt/issues/12918
```release-note
none
```
=> tests: quarantine flaky KubevirtVmHighMemoryUsage alert

pkg/network/pod/annotations/generator_test.go
The network info interfaces order is not always the same,
because it has map usage in the middle of the flow where it is created, 
hence use `ConsistOf` instead `Equal`.
Fixes #
```release-note
None
```
=> network,ut: Fix flaky test

tests/hotplug/BUILD.bazel, tests/hotplug/instancetype.go
This PR addresses a simple TODO and starts using the WithInstancetype libvmi option within the instance type hot plug tests. The deprecated WithRunning is also replaced by WithRunStrategy.
Fixes #
```release-note
NONE
```
=> instancetype: Resolve TODO within hotplug func test

pkg/virt-api/rest/expand.go, pkg/virt-api/rest/expand_test.go, pkg/virt-api/webhooks/BUILD.bazel, pkg/virt-api/webhooks/defaults.go, pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, tests/subresource_api_test.go
This PR separates the VM defaulting and mutations into a public function so external components can use it.
It also removed the `SetDefaultVirtualMachine` function that was not used anywhere in the VM creation flow.
This function didn't reflect reality in terms of changes that are applied to the VM object.
```release-note
None
```
=> virt-api: make VM defaulting and mutations public

pkg/storage/snapshot/snapshot_base.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-handler/cmd-client/client.go, tests/vmi_configuration_test.go
This PR removes old left-over TODOs that are redandunt.
See the per-commit description for more info.
```release-note
NONE
```
=> Code cleanup: Remove old and left-over TODOs

tests/network/expose.go
There are some flakiness that fail at test accessing services, but we cannot see exactly what's the error.
This change wrap that error so we can figure out the issue.
```release-note
NONE
```
=> e2e, net: Add missing error wrapping

Makefile, hack/bazel-server.sh, hack/builder/Dockerfile, hack/builder/build.sh, hack/builder/common.sh, hack/dockerized
This pr adds the s390x support to kubevirt builder image.
The kubevirt builder image for s390x does not contain Bazel. We are not including the Bazel because at the moment there is no upstream official support of Bazel for s390x. We are working with Bazel community to get the support. But it will take lot of time to get the support as the Bazel community has other priorities and they are not willing to add the support now. We also thought to publish the natively compiled Bazel Binary for s390x, We were not able to do it because of legal issues. We will include the Bazel in the  kubevirt builder once we get the Bazel support on s390x.
**How we are proceeding for unit and E2E Tests**.
Unit Test:
We will run the unit-tests using Golang . We will …
=> add s390x support for kubevirt builder.

pkg/virtctl/root.go, pkg/virtctl/version/version.go, pkg/virtctl/version/version_test.go
Embed the globals as part of the version struct,
in order to get rid from globals, which is a better practice.
Fixes #
```release-note
None
```
=> virtctl,version: Remove globals

tests/hyperv_test.go, tests/vmi_controller_test.go, tests/vmi_iothreads_test.go, tests/vmi_multiqueue_test.go, tests/vmi_sound_test.go, tests/vmi_vsock_test.go
Replace the use of GetRunningVirtualMachineInstanceDomainXML with the shorter and simpler to use GetRunningVMIDomainSpec wherever replacement is trivial. Some other tests perform a string analysis on the raw XML, those are not handled within the scope of this commit.
Test code was needlessly longer and more cumbersome that it could have been 
After this PR:
Some test code is a bit more concise, and in some cases imports fewer packages
Fixes #
More instances can be removed with not too much of an effort
- [] …
=> Code Quality: test utils cleanup

pkg/virt-controller/watch/vm.go, tests/storage/migration.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/12686
```release-note
NONE
```
=> [release 1.3] volume migration: fix hotplug volumes when the volume migration fg is enabled

hack/builder/build.sh
The kubevirt builder publish is failing with this error.
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-kubevirt-builder/1839337337553686528
```
podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
Error: short-name resolution enforced but cannot prompt without a TTY
```
The problem here is podman is not able to identify which registry to pull i.e docker.io 
Due to this the prow job which is running kubevirt builder-publish is failing and we do not have an updated builder image in the quay.io
After this PR:
The above issue will be resolved.
Fixes # …
=> fix the podman run command in build.sh.

pkg/storage/export/export/BUILD.bazel, pkg/storage/export/export/export.go, pkg/storage/export/export/vm-source.go, pkg/storage/export/export/vmsnapshot-source.go, pkg/storage/export/export/vmsnapshot-source_test.go
Replaced the deprecated package `k8s.io/utils/pointer` with kubevirt package `kubevirt.io/kubevirt/pkg/pointer` in the `/pkg/storage` directory.
- In the `/pkg/virt-api` we used `k8s.io/utils/pointer` package which is deprecated. 
After this PR:
Ref #12949
```release-note
None
```
=> Replaced the deprecated package `k8s.io/utils/pointer` with kubevirt package `kubevirt.io/kubevirt/pkg/pointer` in the `/pkg/storage` directory.

pkg/virt-api/rest/BUILD.bazel, pkg/virt-api/rest/subresource.go, pkg/virt-api/rest/subresource_test.go, pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel, pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/migrationpolicy-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
Replaced the deprecated package `k8s.io/utils/pointer` with kubevirt package `kubevirt.io/kubevirt/pkg/pointer` in the `/pkg/virt-api` directory.
- In the `/pkg/virt-api` we used `k8s.io/utils/pointer` package which is deprecated. 
After this PR:
Ref #12949
```release-note
None
```
=> Replaced the deprecated package `k8s.io/utils/pointer` with kubevirt package in `/pkg/virt-api` directory

tests/pausing_test.go
Instead of Updating VM runStrategy in pausing_test.go create vm with with the desired runStrategy.
After this PR:
Fixes #
```release-note
NONE
```
=> [Tests]pausing_test.go:Reduces API calls during the test

pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_test.go
manual cherry pick of: https://github.com/kubevirt/kubevirt/pull/12861
```release-note
bugfix: fix possible miss update of datavolumename on vmrestore restores
```
=> [release 1.3] VMRestore: fix possible miss update of dvname on vmrestore restores - fixes quarantine tests

pkg/virtctl/imageupload/BUILD.bazel, pkg/virtctl/imageupload/imageupload.go
Remove global variables that shared across
multiple functions in this command.
```release-note
None
```
=> refactor(virtctl/imageupload): remove global variables usages

pkg/virt-operator/BUILD.bazel, pkg/virt-operator/kubevirt_test.go, pkg/virt-operator/resource/apply/BUILD.bazel, pkg/virt-operator/resource/apply/apps.go, pkg/virt-operator/resource/generate/components/BUILD.bazel, pkg/virt-operator/resource/generate/components/crds.go, pkg/virt-operator/resource/generate/components/daemonsets.go, pkg/virt-operator/resource/generate/components/deployments.go, pkg/virt-operator/resource/generate/components/webhooks.go, pkg/virt-operator/resource/generate/csv/BUILD.bazel, pkg/virt-operator/resource/generate/csv/csv.go, pkg/virt-operator/webhooks/BUILD.bazel, pkg/virt-operator/webhooks/kubevirt-update-admitter.go, pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go
Replaced the deprecated package `k8s.io/utils/pointer` with kubevirt package `kubevirt.io/kubevirt/pkg/pointer` in the `/pkg/virt-operator` directory.
- In the `/pkg/virt-operator` we used `k8s.io/utils/pointer` package which is deprecated. 
After this PR:
Ref #12949
```release-note
None
```
=> Replaced the deprecated package `k8s.io/utils/pointer` with kubevirt package in `/pkg/virt-operator`

tests/network/hotplug_bridge.go, tests/network/hotplug_sriov.go
The VM Running API is deprecated.
User RunStrategy API in network tests.
Network e2e tests used the Running API to start VMs
After this PR:
Network e2e tests use RunStrategy APU to start VMs
Fixes #
```release-note
NONE
```
=> e2e, network: Remove VM Running API usage

pkg/virt-handler/node-labeller/node_labeller.go, pkg/virt-handler/node-labeller/node_labeller_test.go
#12652 introduced an issue where calling the `hasTSCCounter` method of node-labeller with a nil cpu counter would result in a nil pointer dereference.
This is a common occurence in some architectures such as s390x.
After this PR:
This PR relies on Go's short-circuit behavior to assert whether `cpuCounter` is nil as the first condition.
It also introduces a test to `node_labeller_test.go` that tests execution behavior when `cpuCounter` is nil.
Fixes bug introduced in #12652 
```release-note
NONE
```
=> [node-labeller] fix hasTSCCounter nil pointer dereference 

go.mod, go.sum, pkg/monitoring/metrics/virt-controller/vmstats_collector.go, pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/BUILD.bazel, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector_result.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/counter.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/counter_vec.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/gauge.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/gauge_vec.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram_vec.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/metric.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary_vec.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/wrapper_registry.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/BUILD.bazel, vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/compatibility.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/prometheusrules.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/registry.go, vendor/modules.txt
kubevirt_vm_info add VM name and namespace order switched
After this PR:
order is corrected and unit tests are added to more accurately validate
labels values against keys and not use relative position
Fixes #
```release-note
none
```
=> Fix wrong label order in kubevirt_vm_info

tests/BUILD.bazel, tests/framework/storage/BUILD.bazel, tests/framework/storage/nfs.go, tests/hyperv_test.go, tests/io_utils.go, tests/libstorage/BUILD.bazel, tests/libstorage/pvc.go, tests/operator/BUILD.bazel, tests/operator/operator.go, tests/storage/BUILD.bazel, tests/storage/export.go, tests/storage/hotplug.go, tests/storage/snapshot.go, tests/sysprep_test.go, tests/testsuite/BUILD.bazel, tests/testsuite/kubevirtresource.go, tests/vm_state_test.go, tests/vmi_multiqueue_test.go, tests/vmi_vsock_test.go, tools/vms-generator/utils/BUILD.bazel, tools/vms-generator/utils/utils.go
Replaced the deprecated package `k8s.io/utils/pointer` with kubevirt package `kubevirt.io/kubevirt/pkg/pointer` in the  `test` and `tools` directory.
- In the  `test` and `tools` directory, we used `k8s.io/utils/pointer` package which is deprecated. 
After this PR:
Ref #12949
```release-note
None
```
=> Replaced the deprecated package `k8s.io/utils/pointer` with kubevirt package in `test` and `tools` directory.

.golangci.yml, pkg/libvmi/vm.go, tests/compute/vmidefaults.go, tests/hotplug/affinity.go, tests/hotplug/cpu.go, tests/hotplug/memory.go, tests/hotplug/rolloutstrategy.go, tests/instancetype/instancetype.go, tests/monitoring/metrics.go, tests/network/hotplug_bridge.go, tests/network/hotplug_sriov.go, tests/performance/density.go, tests/storage/migration.go, tests/subresource_api_test.go, tests/vm_test.go
Use WithRunStrategy instead to create a running VM in the recommended way.
After this PR:
Fixes #
```release-note
NONE
```
=> [Tests]Remove usage of WithRunning as it is deprecated

tests/usbredir_test.go
This test is causing a lot of impact and leading to PRs getting stuck in the merge queue. It more than qualifies for quarantining[1]
[1] https://search.ci.kubevirt.io/?search=with+usbredir+support+Should+work+several+times&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
/cc @dhiller @xpivarc @victortoso 
This is blocking up the merge queue a bit so it would be good to get this in as soon as possible. 
```release-note
NONE
```
=> e2e,compute: Quarantine very flaky usb redir test

pkg/instancetype/instancetype.go, pkg/instancetype/instancetype_test.go
3a31137abe464d1560e9b693e91d311273ec69cd did not duplicate the original logic of PreferredUseEfi to ensure that we only apply PreferredEfi when a user has not provided their own EFI configuration *and* BIOS is additionally not enabled.
Fixes #12985 
```release-note
The `PreferredEfi` preference is now only applied when a user has not already enabled either `EFI` or `BIOS` within the underlying `VirtualMachine`.
```
=> instancetype: Do not overwrite EFI or BIOS with PreferredEfi

docs/network/network-binding-plugin.md
fix the sample configuration manifest to adhere to schema
The example manifest had a typo and was misaligned with schema, as a result the manifest did not pass validation 
After this PR:
The manifest validation passes successfully 
Fixes #
```release-note
NONE
```
=> typo fix in network binding plugin docs

Makefile, hack/lint-paths.txt, tests/libssh/ssh.go, tests/libwait/wait.go, tests/scale/virt-api.go
Increase linter coverage of tests packages 
Adds the following to linter:
- tests/libssh
- tests/libwait
- tests/libregistry
- tests/scale
Also decrease the number of lines allowed in test utils to reflect what is currently there. 
Fixes #
```release-note
NONE
```
=> lint: Increase linter coverage of tests packages 

pkg/network/multus/BUILD.bazel, pkg/network/multus/status.go, pkg/network/multus/status_test.go, pkg/network/pod/annotations/BUILD.bazel, pkg/network/pod/annotations/generator.go, pkg/network/vmicontroller/BUILD.bazel, pkg/network/vmicontroller/status.go, pkg/virt-controller/network/BUILD.bazel, pkg/virt-controller/network/vmcontroller.go, pkg/virt-controller/watch/vmi/vmi.go
PRs https://github.com/kubevirt/kubevirt/pull/12558 and https://github.com/kubevirt/kubevirt/pull/12833 have made the `pkg/network` package dependent on `pkg/virt-controller/network`.
Following this move, the cyclic dependency is broken.
Add unit tests to the moved function.
Fixes #
https://github.com/kubevirt/kubevirt/pull/12833#discussion_r1760051643
https://github.com/kubevirt/kubevirt/pull/12833#discussion_r1762945994
```release-note
None
```
=> pkg/network: Break cyclic dependency

pkg/virt-launcher/virtwrap/live-migration-source.go, pkg/virt-launcher/virtwrap/manager_test.go, tests/storage/migration.go
During volume migration, when the volumes are migrated from a block PVC to a filesystem one, the replacement needs to take into account that for filesystem PVC, the path of the PVC is the directory plus the image name.
During the replacement of block by filesystem, the path for the raw image was truncated
After this PR:
Fixes the image path by adding the `disk.img`
Fixes #https://github.com/kubevirt/kubevirt/issues/12823
```release-note
NONE
```
=> volume-migration: append disk image for block replacement

tests/BUILD.bazel, tests/network/vmi_networking.go, tests/replicaset_test.go, tests/utils.go, tests/vm_test.go, tests/vmi_configuration_test.go, tests/vmi_hook_sidecar_test.go, tests/vmi_lifecycle_test.go
Replace all uses of UnfinishedVMIPodSelector in tests/utils.go with libpod to improve consistency in the code.
```release-note
NONE
```
=> [Tests]Remove UnfinishedVMIPodSelector from tests/utils.go 

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
User could have created/updated a vm datavolumetemplate to be invalid which was not enforced in any validation ending with a vm with invalid spec. Using this vm can cause unexpected issues such as: https://issues.redhat.com/browse/CNV-48245
After this PR:
Add validation in the VM admit webhook that the datavolumetemplate has exactly one PVC/Storage definition, exactly one source/sourceref/datasource/datasourceref and if have source exactly 1 specific source.
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-48245 …
=> VM admitter: improve validation of datavolumetemplate

tests/infrastructure/prometheus.go
Failures in unmarshal might give meaningless
messages without full context.
Example
```
<*json.SyntaxError | 0xc007ee5920>: 
invalid character 'F' looking for beginning of value
{
msg: "invalid character 'F' looking for beginning of value",
Offset: 1,
}
occurred
```
Fixes #
```release-note
NONE
```
=> Add additional info to asser for test 4135

tests/network/sriov.go, tests/utils.go, tests/vmi_cloudinit_test.go
This PR moves MountCloudInitFunc function that is located on tests/utils to the files that use it, to be consumes locally.
Fixes #
```release-note
NONE
```
=> tests/utils: Move MountCloudInitFunc to local files

pkg/libvmi/status/status.go, pkg/virt-api/rest/BUILD.bazel, pkg/virt-api/rest/subresource.go, pkg/virt-api/rest/subresource_test.go, pkg/virt-controller/watch/vm/BUILD.bazel, pkg/virt-controller/watch/vm/vm.go, pkg/virt-controller/watch/vm/vm_test.go, tests/storage/migration.go
Possible to start a VM after a failed volume migration with an inconsistent volume set. In this case, the VM could be started from an unbootable disk
After this PR:
Avoid to start a VM if the ManualRecoveryRequiered is set.
```release-note
NONE
```
=> volume-migration: avoid to start a vm on failed migration

pkg/monitoring/metrics/virt-controller/vmistats_collector.go, pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
No metrics were mentioning which VMIs are outdated
After this PR:
`kubevirt_vmi_info` metric has a new 'outdated' label set to true if the VMI has an outdated launcher image
Fixes #
```release-note
Add a 'outdated' label to kubevirt_vmi_info metric
```
=> Add a 'outdated' label to kubevirt_vmi_info metric

pkg/virt-api/webhooks/fuzz/fuzz_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-config/deprecation/feature-gates.go, pkg/virt-config/feature-gates.go, tests/mdev_configuration_allocation_test.go
First introduced by #2597 way back in 2019 the GPU feature gate is now deprecated with the feature state graduated to GA and as such always enabled.
After this PR:
Fixes #
```release-note
The `GPU` feature gate is now deprecated with the feature state graduated to `GA` and thus enabled by default
```
=> config: Graduate GPU featuregate to GA

pkg/virt-api/webhooks/fuzz/fuzz_test.go, pkg/virt-config/deprecation/feature-gates.go, pkg/virt-config/feature-gates.go, pkg/virt-controller/services/BUILD.bazel, pkg/virt-controller/services/template_test.go
Deprecate the DockerSELinuxMCS FeatureGate
This feature gate was added in 2020 to address the DockerSELinuxMCS bug: https://github.com/moby/moby/issues/41370.
Since the bug has not been fixed until now, it's time to remove the feature gate as part of the effort to clean up old feature gates and follow the new process for introducing them.
Workaround to the bug could be done through DockerSELinuxMCS Feature Gate
After this PR:
DockerSELinuxMCS Feature Gate is deprecated
Fixes #
This checklist is not enforcing, but it's a remA doc PR for User Guide will be created soon.
inder of items that could be relevant to every PR. …
=> Deprecate DockerSELinuxMCS feature gate

pkg/virtctl/memorydump/memorydump_test.go, pkg/virtctl/utils/BUILD.bazel, pkg/virtctl/utils/test_utils.go, pkg/virtctl/vmexport/BUILD.bazel, pkg/virtctl/vmexport/vmexport.go, pkg/virtctl/vmexport/vmexport_test.go
This PR cleans up and enhances the vmexport unit tests by consolidating `AfterEach`/`BeforeEach` calls, simplifying test setup, reorganizing imports, and removing unnecessary cleanups. Helpers were added to reduce repeated command arguments, and global variable setters in virtctl's vmexport command were removed. The tests now properly use the fake client and a fake HTTP server where possible, with redundant dependencies eliminated. Additional assertions were added, along with missing test cases for creating and downloading VirtualMachineExport from {Snapshot, VM} sources. These changes improve test readability and maintainability.
virtctl in the e2e tests to stabilize tests, to reduce the number of flakes and …
=> cleanup(virtctl,vmexport): Refactor and cleanup unit tests

docs/getting-started.md
The Getting Started Guide for developers explains that in order to run e2e tests while focusing on only a single test file, the user can set the FUNC_TEST_ARGS variable and indicate a test file to focus on. The file that it references does not exist, but the execution does not indicate that and basically performs a no-op.
Fix the file reference to a file with a similar name that does exist
There was an error in the documentation referencing a file that did not exist, thus confusing the user.
If the user would run run the e2e tests as indicated ` FUNC_TEST_ARGS='-focus-file=vmi_networking_test' make functest` the process would execute and actually succeed, but when looking at the stats, one can notice that no tests were executed 
After this PR:
If the user executes the …
=> documentation error: reference to a file that does not exist

pkg/virtctl/create/vm/BUILD.bazel, pkg/virtctl/create/vm/vm.go, pkg/virtctl/create/vm/vm_test.go, pkg/virtctl/create/vm/volume.go, tests/virtctl/create_vm.go
This PR applies several cleanups to virtctl create and its unit and func tests in preparation for adding new features to the command. (see https://github.com/kubevirt/kubevirt/pull/13008)
Applied cleanups:
- Inline types used only once
- Move volume type definitions into separate file
- Reorganize imports
- Use kubevirt.io/kubevirt/pkg/pointer
- Drop no longer needed comment
- Remove wrapper around run method, pass it directly to RunE
- Simplify passing flags by using variadic args
- Reorder tests to resemble order of flags in code
- Name tests consistently
- Reusing existing consts
- Reorder tests and remove unnecessary nesting
After this PR:
Fixes #
Links to places where the discussion took …
=> Cleanups to virtctl create vm and its unit and func tests

BUILD.bazel, cmd/sidecars/BUILD.bazel, containerimages/container-disk-images.md, hack/bazel-build-images.sh, hack/bazel-push-images.sh, hack/push-container-manifest.sh
Images not implemented by an architecture would result in broken "amd64" images, where the binary is the target arch, but the base image is amd64, even though the image should not have been built for the target-arch in the first place.
After this PR:
We only build image for an architecture if it is enabled.
Fixes #12843
Testing the PR requires to delete the kubevirt volume containing the bazel cache, as otherwise old images might be pulled into the manifest instead. Please run:
```
podman volume rm kubevirt
```
before testing.
Approvers are expected …
=> bazel-images: Split image targets per architecture

pkg/monitoring/metrics/virt-controller/vmistats_collector.go, pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go, pkg/monitoring/rules/recordingrules/vmi.go, tests/monitoring/vm_monitoring.go
the value from `GuestOSInfo.Machine` being evaluated by the guest-agent is actually the system-arch (e.g x86_64) and not the actual machine-type-name from the domain-xml
After this PR:
The system arch which was the value of `vmi.status.guestOSInfo.machine` is being labeled as guest_os_arch and the machine type value is taken from the `vmi.status.machine.type`
example for metric output when deploying examples/vmi-fedora.yaml:
```
kubevirt_vmi_info{container="virt-controller", endpoint="metrics", 
evictable="true", flavor="<none>", guest_os_arch="x86_64",
guest_os_kernel_release="5.14.10-300.fc35.x86_64",
guest_os_machine="pc-q35-rhel9.4.0", guest_os_name="Fedora Linux",
guest_os_version_id="35", instance="10.244.196.178:8443", 
instance_type="<none>", …
```
=> monitoring/vmistats_collector: update guest_os_machine label in vmi_info

hack/lint-paths.txt, pkg/network/multus/BUILD.bazel, pkg/network/multus/annotation.go, pkg/network/multus/annotation_test.go, pkg/network/multus/nad.go, pkg/network/multus/nad_test.go, pkg/virt-controller/network/render.go
After this PR:
Fixes #
```release-note
None
```
=> Add linter coverage to pkg/network/multus

tests/storage/datavolume.go, tests/utils.go, tests/vm_test.go
Remove GenerateVMJson e2e util function, inline its code where used.
After this PR:
Fixes #
```release-note
NONE
```
=> tests,utils: Remove GenerateVMJson helper

pkg/storage/export/export/export.go
Trying to export a VM that has volumes (PVCs/DVs) with a dot in their name would fail.
Volume names are allowed to contain dots, however the VMExport was using the volume name as part of naming convention in the pod spec. The name in the pod spec does not allow dots.
After this PR:
One can successfully export a VM that has volumes with a dot in their name.
This patch replaces all dots with dashes in the volume name so the pod can be created successfully.
Fixes #
```release-note
BugFix: Allow VMExport to …
```
=> Allow dots in VM volume names

pkg/virt-config/deprecation/feature-gates.go
the message state that DockerSELinuxMCSWorkaround
will be discontinued But it is wrong it will deprecated.
After this PR:
Fixes #
```release-note
NONE
```
=> Fix warning message fix DockerSELinuxMCSWorkaround FG

pkg/virt-launcher/virtwrap/manager.go, tests/storage/datavolume.go
This Pull Request aims to fix disk expansion logic in Kubevirt so, instead of taking into account the requested disk capacity, we calculate the usable size instead.
The usable size provided by the storage provider can differ from the one requested in the PVC capacity. This can lead to unwanted behavior when expanding the disk to the requested size, as seen in [these](https://search.ci.kubevirt.io/?search=http+endpoint+when+exporting+snapshot&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job) test flakes.
Fixes # https://issues.redhat.com/browse/CNV-47542
Work in progress.
```release-note
Bugfix: Fix disk expansion logic by checking usable size instead of requested capacity
```
=> Use usable size instead of requested capacity in disk expansion logic

staging/src/kubevirt.io/client-go/kubevirt/typed/core/v1/async.go
Use the proxy found in kubeconfig if present and fallback to http.ProxyFromEnvironment, as the comment for Config.Proxy suggests.
> Proxy is the proxy func to be used for all requests made by this
> transport. If Proxy is nil, http.ProxyFromEnvironment is used. If Proxy
> returns a nil *URL, no proxy is used.
Previously a proxy configured in kubeconfig was ignored and only http.ProxyFromEnvironment was used.
Proxies configured in kubeconfig are ignored in client-go for asynchronous subresources like VNC or Console.
After this PR:
Proxies configured in kubeconfig are used in client-go for asynchronous subresources like VNC or Console.
Fixes #12808
Links to places where the discussion took place: …
=> fix(client-go): Use proxy from config if present

tests/storage/datavolume.go
This Pull Request removes an functional test that verifies volumes with preallocation do not have `discard='unmap'`.
The behavior is already fully covered by unit tests: https://github.com/kubevirt/kubevirt/blob/b6c95626967dcf0b18c93cfc1d2937e1fa336e79/pkg/virt-launcher/virtwrap/manager_test.go#L763
Since the functional test requires expensive API calls without improving test coverage its deletion should be justified.
```release-note
NONE
```
=> Test cleanup: Remove redundant volume discard test

pkg/virtctl/create/vm/BUILD.bazel, pkg/virtctl/create/vm/vm.go, pkg/virtctl/create/vm/vm_test.go, tests/libssh/BUILD.bazel, tests/libssh/ssh.go, tests/virtctl/create_vm.go, tests/virtctl/ssh.go
This adds flags to virtctl create vm which allow creating a basic
cloud-init config so the created VMs become more useful.
The added flags allow to:
- Set the username
- Read the password for the user from a file
- Add one or more SSH authorized keys for the user
- Enable qemu-guest-agent to write to the authorized_keys file of the
user (SELinux bool)
Furthermore, this addresses a TODO by extending the support cloud-init
data source types, so both noCloud and configDrive types are supported
now.
cloud-init config cannot be generated with virtctl create vm
After this PR:
Basic cloud-init config can be generated with virtctl create vm
Fixes #
This …
=> feat(virtctl,create): Add flags to generate cloud-init config 

cmd/virt-tail/BUILD.bazel, cmd/virt-tail/main.go
When virt-tail was first introduced, the logic for polling the directory's existence during watchFS() setup was using a for loop with sleep.
It was suggested then to use apimachinery's `PollUntilContextTimeout` instead to simplify the logic[1] but the implementation was postponed as the apimachinery version of KubeVirt at the time didn't have PollUntilContextTimeout.
[1] https://github.com/kubevirt/kubevirt/pull/10110/files#r1341050446
```release-note
NONE
```
=> [virt-tail] Replace watchFS polling with PollUntilContextTimeout

tests/clone_test.go, tests/instancetype/instancetype.go, tests/libdv/dv.go, tests/migration/migration.go, tests/migration/postcopy.go, tests/pool_test.go, tests/storage/datavolume.go, tests/storage/export.go, tests/storage/hotplug.go, tests/storage/migration.go, tests/storage/restore.go, tests/storage/snapshot.go, tests/storage/storage.go, tests/virtiofs/datavolume.go, tests/vm_test.go, tests/vmi_configuration_test.go
Many storage functional tests use the WithPVC function to modify options of a DataVolume that
should be created. The problem with this is that the PVC stanza defaults to filesystem volume
mode and ReadWriteOnce access mode. This is not always a valid combination for all storage
providers.
After this PR:
Use the WithStorage function to modify options of the DataVolume that should be created. The storage stanza allows the optimal volume mode and access mode to be derived from the storage profile associated with the storage class. This allows the tests to run and pass on more providers that would not pass before.
Fixes # …
=> Change storage tests from withPVC to withStorage

api/openapi-spec/swagger.json, pkg/virt-api/rest/subresource.go, pkg/virt-api/rest/subresource_test.go, pkg/virt-controller/watch/vm/BUILD.bazel, pkg/virt-controller/watch/vm/vm.go, pkg/virt-controller/watch/vm/vm_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.VirtualMachine.json, staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.VirtualMachine.yaml, staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/storage/migration.go
The ManualRecoveryRequiered was a filed in the VolumeMigrationState.
After this PR:
Now the manual recovery required information has been converted to a condition.
Fixes #
[Discussion on the mailing list](https://groups.google.com/g/kubevirt-dev/c/emTYi5OuC_4)
```release-note
Removed the ManualRecoveryRequired field from the VolumeMigrationState and convert it to the VM condition ManualRecoveryRequired
```
=> Use ManualRecoveryRequired as a Condition

pkg/monitoring/metrics/virt-controller/vmstats_collector.go, pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go
Adding the label `machine_type` to the `kubevirt_vm_info` metric would help detect if stopped VMS which don't have active VMI resource are using an outdated machine type.
This ensures the detection logic doesn't solely depend on the kubevirt_vmi_info metrics stored in the Prometheus database
example for the metric output with example/vm-cirros.yaml deployed:
```
kubevirt_vm_info{container="virt-controller", endpoint="metrics", flavor="<none>",
instance="10.244.196.134:8443", instance_type="<none>", job="kubevirt-prometheus-metrics",
machine_type="q35", name="vm-cirros", namespace="default", os="<none>",
pod="virt-controller-5cd9584758-9rvdk", preference="<none>", service="kubevirt-prometheus-metrics", 
status="Stopped", status_group="non_running", workload="<none>"}
```
Fixes # …
=> monitoring/vmstats_collector: add machine_type label for vm_info

docs/network/network-binding-plugin.md, pkg/virt-config/feature-gates.go
The network binding plugins feature has been introduce back in v1.1.0, over a year ago.
Since, it has seen wide adoption in the community with multiple plugin vendors that introduced various network bindings through it.
It seems that the feature has reached a level of maturity, allowing it to graduate to Beta and be targeted for GA in the next release.
The network binding plugins feature has a Feature Gate which is now marked as Beta in the next Kubevirt release (v1.4).
User guide has been updated here: https://github.com/kubevirt/user-guide/pull/842
The following limited support notice has been added to the documentation:
> Kubevirt provides regular support for the network binding plugin infrastructure for plugin authors. However, individual network plugin bindings are subject to …
=> virt-config, feature-gates: Graduate the network-binding-plugins to Beta

tests/BUILD.bazel, tests/io_utils.go, tests/storage/events.go
Similarly to tests/utils, tests/io_utils is a problematic file as it lumps together unrelated functions and dumps them in a catch-all package "tests". This PR moves two of these functions to the only test files that uses them.
```release-note
NONE
```
/kind cleanup
/cc @alromeros
=> tests/io_utils: move *FaultyDisk functions to their only user

api/openapi-spec/swagger.json, cmd/virt-handler/virt-handler.go, manifests/generated/kv-resource.yaml, pkg/network/domainspec/interface.go, pkg/network/domainspec/interface_test.go, pkg/network/setup/netconf.go, pkg/network/setup/netconf_test.go, pkg/network/setup/netpod/netpod.go, pkg/network/setup/netpod/netpod_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/network/bindingplugin.go
`managedTap` is added as a core domain attachment type to ease the
creation of simple network bindings.
As its name hints, it also creates the `tap` device (if missing) with a
Linux bridge that connects it to the pod interface.
This solution implements the `tap` + `bridge` alternative of the [Primary Network Binding for seamless migration](https://github.com/kubevirt/community/pull/325) design proposal.
A binding plugin that implements a bridge binding without IPAM:
```mermaid
graph LR;
subgraph virt-launcher
VM <--> tap0
tap0 <--> bridge0
bridge0 <--> eth0
end
subgraph Node
eth0 <--> veth123
end
```
Fixes #
This checklist is not enforcing, but it's a reminder …
=> net binding plugin: Introduce a new `managedTap` `domainAttachmentType`

pkg/virt-config/deprecation/feature-gates.go, pkg/virt-config/feature-gates.go, pkg/virt-controller/network/vmcontroller.go, pkg/virt-controller/network/vmcontroller_test.go, pkg/virt-controller/watch/application.go, pkg/virt-handler/vm.go, pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go, tests/network/hotplug_bridge.go, tests/network/hotplug_sriov.go, tests/testsuite/kubevirtresource.go
The network hotplug feature, limited to bridge and SR-IOV bindings interfaces has not changed since v1.1. There has been no rejections from the community so far and no special additions are foreseen at the moment
The network hotplug feature had a Feature Gate which is dropped by marking it as GA in the next Kubevirt release (v1.4).
User guide has been updated here: https://github.com/kubevirt/user-guide/pull/841
Fixes #
```release-note
Network hotplug feature is declared as GA.
```
=> net, hotplug: Graduate network hotplug feature to GA

api/openapi-spec/swagger.json, pkg/network/link/discovery.go, pkg/network/link/discovery_test.go, pkg/network/multus/status.go, pkg/network/multus/status_test.go, pkg/network/namescheme/networknamescheme.go, pkg/network/namescheme/networknamescheme_test.go, pkg/network/pod/annotations/generator.go, pkg/network/setup/netconf.go, pkg/network/setup/netpod/discover.go, pkg/network/setup/netpod/netpod.go, pkg/network/setup/netpod/netpod_test.go, pkg/network/setup/netstat.go, pkg/network/setup/netstat_test.go, pkg/network/setup/podnic.go, pkg/network/vmicontroller/BUILD.bazel, pkg/network/vmicontroller/status.go, pkg/network/vmicontroller/status_test.go, pkg/virt-controller/network/vmcontroller.go, pkg/virt-controller/watch/vmi/vmi.go, pkg/virt-handler/non-root.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.VirtualMachineInstance.json, staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.VirtualMachineInstance.yaml, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/network/BUILD.bazel, tests/network/vmi_infosource.go
Add a mechanism to dynamically determine the primary pod interface for KuveVirt virtual machines.
The goal is to move away from the hard coded eth0 interface and allow flexible, environment-driven interface
selection.
A new field is added to `v1.VirtualMachineInstanceNetworkInterface` in order to report the matching pod interface name.
VMI controller's network `UpdateStatus` logic is adjusted to report the primary pod interface name inferred from the pod's `k8s.v1.cni.cncf.io/network-status` annotation, with a fallback to the default `eth0`.
virt-handler's network status reporting logic is adjusted to preserve the primary pod interface name.
virt-handler and virt-launcher network setup logic is adjusted to consume a custom primary pod interface name.
Additionally, a small change is made …
=> Support Dynamic Primary Pod NIC Name

tests/storage/export.go
Flaky storage test: A verification pod is created to calculate the md5sum of the export disk. This pod uses fsGroup to give the correct user access to the disk.img. Sometimes the md5sum is executed before the chmod has had a chance to complete. 
After this PR:
This change adds a retry so that the md5sum can hopefully be calculated after the chmod completes.
Fixes #
```release-note
NONE
```
=> Retry calculating the md5sum of the export disk

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
Any modification attempt to the VM spec is rejected while a VM snapshot status is set. This can cause the finalizer to not be allowed to be set after the status is updated. For instance with an older VM spec that doesn't contain the architecture field. There is a mutating webhook that automatically adds the architecture field to the spec. However the status indicates that a snapshot is in progress and it will reject changes to the VM spec.
Now the snapshot can never complete because it can't get a 'lock' on the VM (which requires the finalizer).
After this PR:
Relaxed the requirement that any changes to the VM spec are rejected. Only changes to the disks/volumes are rejected. This prevents the above scenario from happening. 
Fixes https://issues.redhat.com/browse/CNV-48769 …
=> Allow modifications to VM spec during VM snapshot, except disks/volumes

docs/observability/metrics.md, pkg/monitoring/metrics/virt-controller/vmistats_collector.go, pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
No metric for dashboard information about VMIs IP addresses
After this PR:
New kubevirt_vmi_status_addresses per VMI network interface
`
kubevirt_vmi_status_addresses{address="10.244.140.76", container="virt-controller", endpoint="metrics", instance="10.244.196.142:8443", job="kubevirt-prometheus-metrics", name="vmi-migratable", namespace="default", node="node02", pod="virt-controller-68fd5b8596-x5bdq", service="kubevirt-prometheus-metrics", type="InternalIP"}
1`
jira-ticket: https://issues.redhat.com/browse/CNV-46592
Fixes #
Approvers are expected …
=> Add kubevirt_vmi_status_addresses metric

pkg/virt-controller/watch/vmi/vmi.go
Attachment pods are automatically deleted when the launcher pod is removed, as it is their only Owner.
Since the launcher pod is already deleted earlier in the same function, manual deletion of attachment pods is unnecessary.
See details in the Kubernetes API reference:
https://github.com/kubernetes/apimachinery/blob/a8f449e276fe566efddb149992049c78f0088492/pkg/apis/meta/v1/types.go#L232
After this PR:
Fixes #
```release-note
NONE
```
=> [VMIController]: Remove redundant deletion code

pkg/virt-launcher/virtwrap/manager.go, tests/storage/datavolume.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/12733.
```release-note
Bugfix: Fix disk expansion logic by checking usable size instead of requested capacity
```
=> [release-1.3]  Use usable size instead of requested capacity in disk expansion logic

cmd/virt-handler/virt-handler.go, pkg/network/setup/netconf.go, pkg/network/setup/netconf_test.go, pkg/network/setup/netpod/netpod.go, pkg/network/setup/netstat.go, pkg/network/setup/netstat_test.go, pkg/network/vmicontroller/status.go, pkg/network/vmicontroller/status_test.go, pkg/virt-config/feature-gates.go, pkg/virt-controller/watch/BUILD.bazel, pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/application_test.go, pkg/virt-controller/watch/vmi/vmi.go, pkg/virt-controller/watch/vmi/vmi_test.go, pkg/virt-handler/non-root.go, tests/network/vmi_infosource.go
The dynamic pod interface name discovery mechanism implemented at [1] was running unconditionally.
After this PR:
To enable the pod interface name discovery the feature gate related to it has to be enabled.
The dynamic pod interface naming need to be well tested, with the feature gate is disabled by default and only activated at testing scenarios.
```release-note
Add dynamic pod interface name feature gate
```
=> Add dynamic pod iface naming feature gate

pkg/virt-config/deprecation/feature-gates.go, pkg/virt-config/feature-gates.go, pkg/virt-config/virt-config.go, pkg/virt-handler/options.go, staging/src/kubevirt.io/api/core/v1/types.go
Promote Boshs display as default for EFI x86 guests.
For retaining the compatibility (in case some guest
need direct access) we provide kubevirt.io/vga-display-efi-x86
annotation on the Kubevirt CR that needs to be set
before cluster upgrade.
Fixes #
```release-note
BochsDisplayForEFIGuests is GAed, use  "kubevirt.io/vga-display-efi-x86" annotation on Kubevirt CR before upgrading in case you need retain compatibility.
```
=> GA BochsDisplayForEFIGuests

api/openapi-spec/swagger.json, automation/repeated_test.sh, pkg/storage/backend-storage/BUILD.bazel, pkg/storage/backend-storage/backend-storage.go, pkg/storage/backend-storage/backend-storage_test.go, pkg/virt-controller/services/rendervolumes.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/application_test.go, pkg/virt-controller/watch/migration/BUILD.bazel, pkg/virt-controller/watch/migration/migration.go, pkg/virt-controller/watch/migration/migration_test.go, pkg/virt-controller/watch/vmi/BUILD.bazel, pkg/virt-controller/watch/vmi/vmi.go, pkg/virt-controller/watch/vmi/vmi_test.go, pkg/virt-handler/BUILD.bazel, pkg/virt-handler/vm.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.VirtualMachineInstance.json, staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.VirtualMachineInstance.yaml, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/BUILD.bazel, tests/decorators/decorators.go, tests/storage/BUILD.bazel, tests/storage/backendstorage.go, tests/vm_state_test.go, tests/vmi_tpm_test.go
See https://github.com/kubevirt/community/pull/314
After this PR:
Fixes #
```release-note
backend-storage now supports RWO FS
```
=> backend-storage: add RWO FS support

pkg/virt-launcher/virtwrap/converter/BUILD.bazel, pkg/virt-launcher/virtwrap/converter/converter_test.go, tests/storage/BUILD.bazel, tests/storage/storage.go
This functional test only checks for converter behavior, which could easily be covered with unit tests.
This PR aims to move the test from functional to unit tests, in the same fashion as in the test here: https://github.com/kubevirt/kubevirt/pull/13051:
```release-note
NONE
```
=> Test cleanup: Move ephemeral volume test to unit tests

docs/observability/metrics.md, pkg/monitoring/metrics/virt-controller/vmstats_collector.go, pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go, tests/monitoring/metrics.go
No metric for VM resource limits
After this PR:
kubevirt_vm_resource_limits with CPU and memory resource limits
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-48192
```release-note
Add kubevirt_vm_resource_limits metric
```
=> Add kubevirt_vm_resource_limits metric

pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-config/configuration_test.go, pkg/virt-config/deprecation/feature-gates.go, pkg/virt-config/feature-gates.go, pkg/virt-config/virt-config.go, pkg/virt-controller/watch/vm/vm_test.go, tests/decorators/decorators.go, tests/hotplug/affinity.go, tests/hotplug/cpu.go, tests/hotplug/instancetype.go, tests/hotplug/memory.go, tests/hotplug/tolerations.go, tests/storage/migration.go, tests/testsuite/kubevirtresource.go
The `VMLiveUpdateFeatures` feature-gate has been introduced in KubeVirt v1.0.0 after being here for multiple releases and having undergone major cleanups and bug fixing I think is now ready to be GAed.
Note that this PR just GAs the feature-gate and doesn't change the default `vmRolloutStrategy` which remains `Stage`. 
Fixes #
```release-note
GA the `VMLiveUpdateFeatures` feature-gate.
```
=> GA VMLiveUpdateFeatures feature-gate

tests/migration/BUILD.bazel, tests/migration/eviction_strategy.go, tests/migration/migration.go
This PR was split into 2 parts after the review round. (Pt.2: https://github.com/kubevirt/kubevirt/pull/13066)
This PR aims to identify and label the tests in the migration pkg.
Also, a cleanup and refactoring of the tests is performed:
- convert e2e test into a unit test if possible;
- remove tests that do not add anything to an already present unit test;
- use patchset;
- remove duplicates;
- merge similar tests.
```release-note
NONE
```
=> Conformance tests for migration-Pt.1

pkg/storage/export/export/BUILD.bazel, pkg/storage/export/export/export.go, pkg/storage/export/export/export_test.go, pkg/virtctl/memorydump/memorydump.go, pkg/virtctl/vmexport/vmexport.go, pkg/virtctl/vmexport/vmexport_test.go
- A VM export CR and pod are created in the same namespace as the VM, not necessarily on the same network, or reachable by the kubelet doing the readiness probe.
- A VM export server deployed using `virtctl` has a hardcoded 2-minutes readiness timeout, not taking into account a new node may have to be scheduled for this pod
- End user can label or annotate the VM export object or ask for it through `virtctl vmexport` arguments, the generated export server will inherit from VM export labels and annotations
- End user can define the VM Export readiness timeout
- Expected VM export labels and annotations are now unit tested
- **Scenario 1:** End user can schedule the VM export object on a specific node through labels
- **Scenario 2:** End user can set a …
=> feat: propagate VMExport labels and annotations to associated pod

pkg/virt-operator/resource/generate/components/crds.go
This field is deprecated and already defaults to false. A duplicate public variable is also removed again after accidentally being reintroduced by 68fc524b68eb348c0a08942e510bc736 .
Fixes #
```release-note
NONE
```
=> virt-operator: Remove use of `crd.Spec.PreserveUnknownFields`

BUILD.bazel, WORKSPACE, hack/bazel-generate.sh, hack/bump-distroless.sh
The buildtools repo, while already using prebuilt binaries and only depending on rules_go without any specific go dependencies, still has two caveats:
* it requires still rules_go which can make updating more challenging
* it downloads all binaries for all buildtools supported architectures
After this PR:
Use buildifier and buildozer as toolchain, to only use download and use the binaries from the host platform (instead of downloading all) and only make it independent of rules_go for simplifying dependency management.
buildifier-prebuilt is pretty broadly in use and I also checked that the binaries and digests in use (buildtools 6.4.0) are really coming from where it is claiming that they are coming. 
```release-note
NONE
```
=> Introduce buildifier-prebuilt to reduce rules_go dependency complexity

pkg/virtctl/guestfs/BUILD.bazel, pkg/virtctl/guestfs/guestfs.go, pkg/virtctl/vm/BUILD.bazel, pkg/virtctl/vm/start_test.go, pkg/virtctl/vm/stop_test.go, staging/src/kubevirt.io/client-go/api/defaults_test.go
Replaced the deprecated package `k8s.io/utils/pointer` with kubevirt package `kubevirt.io/kubevirt/pkg/pointer` in the rest of the file.
- In some remaining file  we used `k8s.io/utils/pointer` package which is deprecated. 
After this PR:
fixes #12949
```release-note
None
```
=> Replace deprecated package with kubevirt package in rest of the file

tests/mdev_configuration_allocation_test.go
```
Timed out after 120.013s.
The function passed to Eventually returned the following error:
<wait.errInterrupted>: 
timed out waiting for the condition
{
cause: <*errors.errorString | 0xc000292b70>{
s: "timed out waiting for the condition",
},
}
tests/mdev_configuration_allocation_test.go:251}
```
This PRs decrease the waiting time for the Pod in order for the `Eventually` loop to attempt next try.
Fixes #
```release-note
NONE
```
=> Vgpu flake

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
Manual backport of pull request #13001
```release-note
Relaxed check on modify VM spec during VM snapshot to only check disks/volumes
```
=> [release-1.2] Allow modifications to VM spec during VM snapshot, except disks/volumes
