kubevirt/kubevirt

tests/monitoring/BUILD.bazel
tests/monitoring/component_monitoring.go

Flaky VirtHandlerRESTErrorsBurst and VirtHandlerRESTErrorsHigh were disabled
After this PR:
VirtHandlerRESTErrorsBurst and VirtHandlerRESTErrorsHigh added to the testing pipeline again
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-40856
```release-note
none
```

Re-enable VirtHandlerRESTErrorsBurst and VirtHandlerRESTErrorsHigh tests

---

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go

Manual backport of pull request #13001
```release-note
Relaxed check on modify VM spec during VM snapshot to only check disks/volumes
```

[release-1.1] Allow modifications to VM spec during VM snapshot, except disks/volumes

---

pkg/virt-launcher/virtwrap/converter/converter.go

Isolate the code for converting and assinging iothreads.
The code for converting the iothreads is messy and spread around the main conversion function
After this PR:
Group and simplified the logic into a single function.
```release-note
NONE
```

converter: refactor iothreads conversion

---

tests/vmi_cloudinit_test.go

1. Simplifies `tests/vmi_cloudinit_test.go`
2. CloudInit is standard way to configure VMs on launch
and therefore we should include this in our Conformance
suite.
3. Removes some duplicated e2e tests
Fixes #
```release-note
NONE
```

Conformance cloudinit

---

tests/storage/restore.go

These restore tests are passing consistently against the periodic e2e storage lanes so these can be reintroduced to the presubmit test lanes.
https://testgrid.kubernetes.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.31-sig-storage
Fixes #
It may also be worthwhile to backport this to recent branched v1.4 if we want these tests to run there. 
```release-note
NONE
```

e2e,storage: Dequarantine restore tests

---

cmd/virt-exportproxy/BUILD.bazel
cmd/virt-exportserver/BUILD.bazel
hack/bazel-build-images.sh
hack/bazel-push-images.sh

Both x86_64 image versions during the 1.4.0-alpha release contained s390x binaries. Enable to build actual images for the architecture to ensure this does not happen again.
After this PR:
Fixes #
```release-note
Enable virt-exportproxy and virt-exportserver image for s390x
```

s390x: Enable exportproxy and exportserver image

---

pkg/virt-launcher/virtwrap/converter/BUILD.bazel
pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/converter_test.go

User reported
```
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to start VirtualMachineInstance with flags 0.","name":"ygal","namespace":"default","pos":"manager.go:1246","reason":"virError(Code=67, Domain=31, Message='unsupported configuration: unknown CPU feature: mpx')","timestamp":"2024-10-25T14:17:53.539424Z","uid":"c16487ce-a18e-42b2-8713-e004691fd139"}
```
from ARM env that is running emulation.
This PR is fixing the issue.
Fixes #
```release-note
NONE
```

Disable mpx only on x86

---

pkg/network/setup/netpod/netpod.go

no change in functionality. purely for readability
improve readability of function without modifying functionality 
After this PR:
Fixes #
```release-note
NONE
```

net, netpod: refactor networkQueues

---

tests/decorators/decorators.go
tests/libstorage/pvc.go
tests/storage/migration.go

This helps filter out the tests on environments that cannot satisfy the test requirements.
Fixes #
```release-note
NONE
```

volume migration tests: add decorators for tests that have block requirements

---

tests/launchsecurity/sev.go
tests/libnode/node.go
tests/storage/events.go
tests/storage/hotplug.go
tests/storage/storage.go
tests/usb/usb.go

Per @0xFelix's request, make the function fit better into its new location in libnode.
```release-note
NONE
```

tests/libnode/node: rename NodeNameWithHandler

---

tests/libdv/dv.go
tests/storage/migration.go

In the wild, provisioners outright lie about the usable capacity for
filesystem volumes. So a 1Gi PVC has less than that usable.
Using the storage API inflates the sizes and thus should accommodate this
scenario.
Fixes #
```release-note
NONE
```

[release-1.3] migration block->fs test: use storage API to accommodate user scenario

---

automation/test.sh

We always want only "sig-compute" and "conformance" label to be focused.
Related to https://github.com/kubevirt/project-infra/pull/3715
Fixes #
```release-note
NONE
```

Automation for sig-compute-conformance lane

---

docs/observability/metrics.md
pkg/monitoring/metrics/virt-controller/metrics.go
pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go
pkg/virt-controller/watch/application.go
tests/monitoring/metrics.go
tools/doc-generator/doc-generator.go

add allocated disk size metric in order to monitor vms sizes.
kubevirt_vm_disk_allocated_size_bytes does not exists
After this PR:
kubevirt_vm_disk_allocated_size_bytes exists
Fixes # 
jira-ticket: https://issues.redhat.com/browse/CNV-49002
Metric output:
```release-note
kubevirt_vm_disk_allocated_size_bytes metric added in order to monitor vm sizes
```

add allocated disk size metric

---

hack/lint-paths.txt
pkg/network/netbinding/memory.go
pkg/network/netbinding/memory_test.go
pkg/network/netbinding/netbinding_test.go

- Break long lines
- Apply gofumpt
Fixes #
```release-note
None
```

pkg/network/netbinding: Add linter coverage

---

pkg/virt-controller/watch/vmi.go

manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/12850
Fixes #
```release-note
NONE
```

[release-1.3][BugFix]VMIController: creation should be observed 

---

tests/migration/migration.go

This flaky test has caused over 10% impact to the compute-migrations lane over the past 14 days and qualifies for quarantining[1]
Quarantine to give time for investigation.
https://github.com/kubevirt/kubevirt/issues/13143
[1] https://search.ci.kubevirt.io/?search=test_id%3A6980&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
/cc @dhiller @fossedihelm @xpivarc 
```release-note
NONE
```

e2e,migration: Quarantine flaky compute-migration test

---

tests/guestlog/guestlog.go

These tests seem to be sporadically failing due to a suspected libvirt bug:
- `Guest console log container fetch logs it should not skip any log line even trying to flood the serial console for QOSGuaranteed VMs` - failed 16 times over 619 executions: 2.58% failing rate
- `Guest console log container fetch logs it should fetch logs for a running VM with logs API` - failed 11 times over 631 executions: 1.74% failing rate
Per discussion with @tiraboschi and @kmajcher-rh, we decided to quarantine until the issue is resolved.
```release-note
NONE
```

tests: quarantine guest console log tests

---

manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-operator/resource/generate/rbac/controller.go
pkg/virt-operator/resource/generate/rbac/controller_test.go

Basically, OpenShift deploys enforcement that says we
```cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on```
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
We recently removed this unintentionally in https://github.com/kubevirt/kubevirt/commit/8d58ba50801dd4e3fed649bc8346e013ad7f2578.
Fixes #
```release-note
BugFix: VMSnapshots broken on OpenShift
```

Re-add finalizer update RBAC that was accidentally dropped

---

WORKSPACE

Since updating rules_go, this dependency is no longer required.
Fixes #
```release-note
NONE
```

build: Cleanup explicit bazel-skylib dependency as no longer needed

---

pkg/virtctl/guestfs/guestfs.go
pkg/virtctl/guestfs/guestfs_test.go

Remove globals, and some unused variables.
Fixes #
```release-note
None
```

virtctl, guestfs: Get rid of globals

---

pkg/virt-handler/vm.go
pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go
tests/vmi_lifecycle_test.go

Fix: graceful shutdown on non-ACPI architectures by using default signal
Graceful shutdown was failing on IBM Z (s390x) due to lack of ACPI support.
This fix changes virt-handler to send DOMAIN_SHUTDOWN_DEFAULT when a
graceful shutdown is requested.
This allows libvirt/QEMU to select the appropriate shutdown method:
- If the QEMU guest agent is present, it is used to initiate shutdown.
- If not, on x86, ACPI is used to signal shutdown.
- On non-ACPI architectures, an architecture-specific method is used.
This ensures proper shutdown handling across all architectures.
More info: https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainShutdownFlagValues
https://pve.proxmox.com/wiki/Qemu-guest-agent#Linux
Signed-off-by: Anand Nekkunti

Fix graceful shutdown on IBM Z (s390x)

---

pkg/virtctl/imageupload/BUILD.bazel
pkg/virtctl/imageupload/imageupload.go
pkg/virtctl/imageupload/imageupload_test.go

Use Printf the default from cobra library
to print user-facing logs.
Requested by @0xFelix to cleanup imageupload
command.
```release-note
None
```

refactor(virtctl/imageupload): use Printf from cobra library

---

pkg/virt-handler/isolation/detector.go
pkg/virt-handler/vm.go

The `FindProcess` function from the [`go-ps` package](github.com/mitchellh/go-ps) returns nil without error if a process isn't found, but our code incorrectly assumes an error. This commit adds a check to ensure the process is not nil before invoking its methods, preventing the panic.
Ideally, we should avoid using the [`go-ps` package](github.com/mitchellh/go-ps), as it is outdated and we don't want to keep it as a dependency.
Panics: https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.30-sig-compute/1768655952652800000 https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.30-sig-compute/1818665585588834304
Please review virt-handler logs for details on the panics.
After this PR:
Fixes #
The following tradeoffs …

[bugFix]: Fix panic in virt-handler when process is not found during CPU housekeeping

---

pkg/storage/backend-storage/backend-storage.go

The annotation name used to find the default virt storage class was taken from a design proposal draft, and was changed in the final version.
After this PR:
The correct annotation is used.
Fixes #
```release-note
backend-storage will now correctly use the default virtualization storage class
```

backend-storage: fix broken annotation name

---

pkg/network/setup/netpod/netpod.go

Most of the time users don't set the interface's `Model` field. Switch the comparisons order so fewer comparisons will be performed.
Fixes #
Addresses a [nit](https://github.com/kubevirt/kubevirt/pull/13160#discussion_r1826947665) from https://github.com/kubevirt/kubevirt/pull/13160.
```release-note
NONE
```

netpod, networkQueues: Switch the comparison order

---

pkg/virt-launcher/virtwrap/converter/amd64.go
pkg/virt-launcher/virtwrap/converter/archconverter.go
pkg/virt-launcher/virtwrap/converter/arm64.go
pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/converter/ppc64le.go
pkg/virt-launcher/virtwrap/converter/s390x.go

According to the official KubeVirt documentation [1], vCPU hotplug is currently unsupported on the ARM64 architecture. However, this limitation is not enforced in the code. A VM configured with more than one socket will still have `n` CPUs set as both `enabled` and `hotpluggable`, as shown in the following code: https://github.com/kubevirt/kubevirt/blob/bb8e5ad91b890adfa5e930a2fd0519216632ce8f/pkg/virt-launcher/virtwrap/converter/converter.go#L2061-L2090. 
This setup results in a libvirt error [2] on the `aarch64` architecture.
[1] https://kubevirt.io/user-guide/compute/cpu_hotplug/#limitations  
[2] https://gitlab.com/libvirt/libvirt/-/blob/763381df53d5a67804f828cb8db661f694d35296/src/qemu/qemu_process.c#L6073-6082
This PR introduces a check to …

virtwrap, converter: Skip CPU Hotplug Setup for ARM64

---

tests/framework/checks/checks.go

Following PR #8047 this function is unused.
Fixes #
```release-note
None
```

tests, framework: Remove HasLiveMigration

---

pkg/storage/backend-storage/BUILD.bazel
pkg/storage/backend-storage/backend-storage.go
pkg/virt-controller/watch/drain/evacuation/evacuation.go
pkg/virt-controller/watch/migration/migration.go
pkg/virt-controller/watch/pool/pool.go
pkg/virt-controller/watch/replicaset/replicaset.go
pkg/virt-controller/watch/vm/vm.go
pkg/virt-controller/watch/vmi/vmi.go

Many calls to `GetByKey()` use manually built strings with `namespace + "/" + name`
After this PR:
Those calls now use `controller.NamespacedKey()` instead
Fixes #
```release-note
NONE
```

virt-controller: use controller.NamespacedKey() instead of manual strings

---

pkg/storage/export/export/vm-source.go
pkg/storage/export/export/vm-source_test.go

It is possible that a VMI has completed or failed and one wants to export the VM disk. Right now the VMExport will remain pending because it finds the VMI and refuses to start.
After this PR:
This change allows the VMExport to become ready if a VMI exists that is either failed or succeeded.
Fixes https://issues.redhat.com/browse/CNV-49376
The default behavior if a VM is stopped normally is to delete the VMI, but in case this doesn't
happen, the VMExport should still be allowed to start.
```release-note
Fix …
```

Allow VMExport to start if completed VMI exists

---

pkg/network/deviceinfo/BUILD.bazel
pkg/network/deviceinfo/deviceinfo.go
pkg/network/deviceinfo/deviceinfo_test.go
pkg/network/multus/status.go
pkg/network/multus/status_test.go
pkg/network/namescheme/networknamescheme.go
pkg/network/namescheme/networknamescheme_test.go
pkg/network/pod/annotations/BUILD.bazel
pkg/network/pod/annotations/generator.go
pkg/network/vmicontroller/status.go
pkg/virt-controller/network/vmcontroller.go
pkg/virt-controller/watch/vmi/vmi.go

The value of the pod's `k8s.v1.cni.cncf.io/network-status` annotation is used for:
1. Updating the VMI's interfaces status.
2. Calculating the value of the `kubevirt.io/network-info` annotation.
3. Creating an ordinal naming scheme for a migration target pod in case the source pod uses it.
4. Discovering whether the VMI uses an ordinal naming scheme in VM Controller.
This PR:
1. Centralizes the logic responsible for parsing the value of the `k8s.v1.cni.cncf.io/network-status` annotation under `pkg/network/multus`.
2. Uses processed Go structs where applicable instead of raw strings.
3. Removes unnecessary mapping of NetworkStatus by pod interface name.
4. Cleans up after #13018.
Fixes #
Links to places where …

Improve network-status processing

---

hack/check-unassigned-tests.sh
tests/decorators/decorators.go
tests/performance/framework.go

`check-unassigned-tests` checks that there are no tests that are
not assigned to any sig.
To do that it ensures that every tests has `[sig-<sig_name>]` pattern
in the test descriptor.
This is not enough, since our `automation/test.sh` script is not
using file name based filtering anymore, but label filtering.
This means that, in case a test has the `[sig-<sig_name>]` string in
its name, but not the label, the check-unassigned-tests.sh passes but the
test is actually not executed.
Let's introduce the double check: the legacy file name based check and the
new label check.
Also, the `sig-compute-migrations` was not covered by this check, so introduced
it too.
This new check discovered that sig-performace tests were not properly labeled.
```release-note
NONE
```

Fix check unassigned test

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
pkg/virt-controller/watch/volume-migration/volume-migration.go
pkg/virt-controller/watch/volume-migration/volume-migration_test.go
tests/storage/migration.go

Volume migration wasn't allowed for hotplugged volumes
After this PR:
Enable volume migration for volume hotplug
Fixes #
```release-note
Enable volume migration for hotplugged volumes
```

volume-migration: remove restriction for the hotplug volumes

---

tests/network/primary_pod_network.go
tests/network/vmi_networking.go

Currently there are two tests that verifies VMI with bridge binding report the pod IP in status at test/network/primary_pod_network.go.
Both tests use Alpine VM which doesnt have QEMU guest-agent installed.
After this PR:
The are unified into the "multiple VM with bridge binding" test at tests/network/vmi_networking.go.
This test use Cirros VM which doesnt have QEMU guest-agent installed as well.
This PR change tests that perform connectivity check cross nodes to not skip silently but fail loudly, with a informative message.
Fixes #
Approvers are …

e2e, network: Unify IP report in status tests

---

tests/virtctl/imageupload.go

We've [recently](https://github.com/kubevirt/kubevirt/pull/12925#issuecomment-2481198061) switched the imageupload suite to run in parallel, which has introduced flakiness:  
https://search.ci.kubevirt.io/?search=unexpected+return+value+502&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
this was also seen in a previous attempt to make them parallel:
https://github.com/kubevirt/kubevirt/pull/11716#issuecomment-2373256509
let's put them back to running serial for now as the gain in runtime is not drastic.
After this PR:
Fixes # …

imageupload tests: run serially

---

OWNERS_ALIASES

Based on the project governance [1], maintainers that are idle for 6 months or more are to be moved to the emeritus list.
Unfortunately, it seems Alona has changed focus and is no longer active [2] in the project.
Therefore, Alona is moved to the emeritus approvers list.
[1] https://github.com/kubevirt/community/blob/main/GOVERNANCE.md#removing-maintainers
[2] https://github.com/AlonaKaplan?tab=overview&from=2024-05-10&org=kubevirt
Fixes #
This is a sad PR :/
```release-note
NONE
```

OWNERS: Move AlonaKaplan to the emeritus approvers

---

tests/network/vmi_networking.go

There are two tests that tests VMI with masquerade binning and custom CIDR [1]:
1. Regular CIDR (line 663).
2. CIDR who has octants with leading zeros (line 664).
[1] https://github.com/kubevirt/kubevirt/blob/1e946038f7f8ceef68209df8e5ffaddd7ab97645/tests/network/vmi_networking.go#L663-L664
After this PR:
Remove (2), because (1) covers custom CIDR usage in general and when using CIDR with leading zeros.
Fixes #
```release-note
NONE
```

e2e,network: Unify masquerade binding with custom CIDR tests

---

pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/source.go
staging/src/kubevirt.io/client-go/kubecli/handler.go
tests/storage/snapshot.go

vmsnapshot: update error on content and snapshot if freeze fails
Up until now if the freeze failed in the online
snapshot it was not reflected on the snapshot object
and eventually the deadline would exceed and the user
would not understand what happened.
Now in case freeze fails it will be marked as an error
on the vmsnapshotcontent which is reflected also on the vmsnapshot.
Remove logic of skiping volumesnapshots in case of error since
error should be able to change and then continue with the snapshot
with previous code if an error occured you will keep skipping
and putting an error on the content without exiting the error state.
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-48733
Links to places …

VMSnapshot: propagate freeze error failure

---

pkg/storage/types/BUILD.bazel
pkg/storage/types/cdi.go
pkg/storage/types/cdi_test.go
pkg/virt-controller/watch/vmi/vmi.go

Before this PR: 
NPE
After this PR:
Error
Fixes #
```release-note
Avoid NPE when getting filesystem overhead
```

Avoid NPE when getting filesystem overhead

---

pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
pkg/virt-launcher/virtwrap/converter/amd64.go
pkg/virt-launcher/virtwrap/converter/archconverter.go
pkg/virt-launcher/virtwrap/converter/archconverter_test.go
pkg/virt-launcher/virtwrap/converter/arm64.go
pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/converter/network.go
pkg/virt-launcher/virtwrap/converter/ppc64le.go
pkg/virt-launcher/virtwrap/converter/s390x.go
pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go
pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go

Currently, the arch converter is used
to differentiate the behavior between
the arch.
To do so, it should be initialized every time
you want to use it (`newArchConverter(arch)`).
The converterContext has the architecture string
as field.
We can expand the latter to the archConverter, so
that we can use it directly.
Ideally, the archConverter should be the centralized 
place where all the different strategies are contained,
without the need to specify `isARM` or `isAMD` spread
in the codebase.
I'd expect to see something like `is<feature>Enabled()`
where the different archconverter handles it.
Following this, new methods are added to the archConverter interface:
- isSMBiosNeeded() bool
- transitionalModelType(useVirtioTransitional *bool) string
- isROMTuningSupported() bool
- …

Expand archconverter usages

---

tests/decorators/decorators.go

Following PR #11915 the `PasstGate` decorator is no longer used.
Fixes #
```release-note
NONE
```

tests, decorators: Remove PasstGate

---

pkg/config/config-map_test.go
pkg/config/downwardapi_test.go
pkg/config/secret_test.go
pkg/config/service-account_test.go
pkg/config/sysprep_test.go
pkg/libvmi/config.go

Refactor unit tests to use libvmi for resource creation in config file

---

api/openapi-spec/swagger.json
manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/storage/snapshot/restore.go
pkg/storage/snapshot/restore_test.go
pkg/storage/snapshot/util.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
pkg/virt-operator/resource/generate/components/validations_generated.go
pkg/virt-operator/resource/generate/rbac/controller.go
staging/src/kubevirt.io/api/snapshot/v1beta1/deepcopy_generated.go
staging/src/kubevirt.io/api/snapshot/v1beta1/types.go
staging/src/kubevirt.io/api/snapshot/v1beta1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/storage/restore.go

If VMRestore was initiated when VM is still running the VMRestore webhook would have failed the creation of the object.
If somehow there was a race and the VM became running just after the webhook let the request pass then the reconcile loop will mark the restore in progress and then add a condition that the target of the restore is not ready.
After this PR:
The check of the VM state was removed from the webhook since this is a racefull check and not eventual consistent.
Moved the check of the VM state in the reconcile loop to be before marking the restore in progess.
Added to the restore TargetNotReadyPolicy that will define how to act if restore was initiated when the target is not ready yet.
The default option is wait a default grace period of 5min and if in that time …

Vmrestore - add options to handle cases when target is not ready

---

hack/kwok-perftests.sh

The path to kubectl.sh changed as part of https://github.com/kubevirt/kubevirt/pull/12872
The kwok-performance periodic lane is failing due to not being able to find kubectl.sh [1]
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.29-sig-performance-kwok/1858694400775819264
Fixes #
/cc @dhiller @xpivarc @alaypatel07 
```release-note
NONE
```

perf,kwok: fix path to kubectl.sh in kwok-perftests.sh

---

tests/storage/datavolume.go
tests/virtiofs/datavolume.go

A while ago https://github.com/kubevirt/kubevirt/pull/12072 merged and we started seeing kubevirt runs
with it against various test suite configs. This PR follows up with the lessons learned from those runs.
Fixes #
```release-note
NONE
```

storage tests: follow up cleanup of pvc->storage API

---

pkg/storage/types/pvc.go
pkg/virt-launcher/virtwrap/converter/BUILD.bazel
pkg/virt-launcher/virtwrap/converter/converter_test.go

We can use the built-in `min` function since Go 1.21.
Reference: https://go.dev/ref/spec#Min_and_max
```release-note
NONE
```

storagetypes: use built-in `min` function

---

pkg/virtctl/create/params/BUILD.bazel
pkg/virtctl/create/params/params.go
pkg/virtctl/create/params/params_suite_test.go
pkg/virtctl/create/params/params_test.go
pkg/virtctl/create/vm/vm_test.go

Add unit tests for pkg/virtctl/create/params that capture the current
behavior of the module.
Then apply cleanups to the module:
- Do not panic in Map, since it is able to return an error. Supported now always panics with a wrapped error.
- Return the correct count of slashes in errors returned by params.SplitPrefixedName. It was off by one previously.
- Remove named return in params.SplitPrefixedName.
- Add the missing support for string slices in params.Map.
Also apply these minor cleanups to the module:
- Rename variables to make the code easier to read
- Name variables consistently
- Inline assignments if possible
- Use pointer.P
- Extend comment of params.Map to clarify its behavior
pkg/virtctl/create/params has no unit tests and needs cleanups
After this PR: …

cleanup(virtctl,params): Add unit tests and apply cleanups

---

pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go

Guest and Hugepages memory requests were not included in the kubevirt_vm_resource_requests metric
After this PR:
The metric also exposes these values
jira-ticket: `https://issues.redhat.com/browse/CNV-51408`
Fixes #
```release-note
Add Guest and Hugepages memory to kubevirt_vm_resource_requests
```

Add Guest and Hugepages memory to kubevirt_vm_resource_requests

---

tests/libmigration/migration.go

Previously, `RunMigrationAndExpectFailure` used an `Eventually` block
to retry migration creation on transient failures. If `Create` failed
initially, the `migration` object was overwritten with an invalid result,
causing retries to use an empty migration.
After this PR:
This PR removes the `Eventually` block and now returns an error immediately on failure.
```release-note
None
```

tests/libmigration/migration: bug-fix migration create during retry

---

tests/libdv/dv.go
tests/storage/migration.go

Fix some volume migration tests if run in an environment that has ceph-rbd volumes properly configured.
Fixes https://issues.redhat.com/browse/CNV-51448
```release-note
NONE
```

Fix volume migration tests against ceph rbd

---

pkg/monitoring/metrics/virt-handler/migrationdomainstats/migrationstats_collector.go
pkg/monitoring/metrics/virt-handler/migrationdomainstats/queue.go

Infra tests were failing because vmi migration metrics did not include node label
After this PR:
Fixes #
```release-note
Add node label to migration metrics
```

Add node label to migration metrics

---

tests/migration/migration.go

During cleanup in #12838, in the test [test_id:6980] it was used the wrong annotation resulting in unstable behavior.
It was used `FuncTestForceLauncherMigrationFailureAnnotation` instead of `FuncTestBlockLauncherPrepareMigrationTargetAnnotation`.
Fixes https://github.com/kubevirt/kubevirt/issues/13143
Quarantine PR: https://github.com/kubevirt/kubevirt/pull/13192
```release-note
NONE
```
/kind-flake
/cc @xpivarc @dhiller @brianmcarey

fix quarantined [test_id:6980] test

---

tests/network/bindingplugin_passt.go

`startPasstVMI` takes two unused params - remove them.
Fixes #
```release-note
NONE
```

passt binding plugin, e2e: Remove unused params

---

tests/vmi_vsock_test.go

lsof does not exist in the fedora image:
```
[root@testvmi-txhzt fedora]# lsof
bash: lsof: command not found
```
which I believe breaks the check for netcat's exit. This causes a flake:
```
/usr/bin/example-guest-agent: Text file busy
```
Since the executable could be getting modified.
Fixes #12930 
May or may not help with this [flake](https://search.ci.kubevirt.io/?search=VSOCK+communicating+with+VMI+via+VSOCK+should+succeed&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job) …

vsock tests: use pgrep instead of non existing lsof

---

tests/migration/migration.go
tests/migration/postcopy.go

This is the second part of the original bigger one: https://github.com/kubevirt/kubevirt/pull/12838
This PR aims to identify and label the tests in the migration pkg.
Also, a cleanup and refactoring of the tests is performed:
- convert e2e test into a unit test if possible;
- remove tests that do not add anything to an already present unit test;
- use patchset;
- remove duplicates;
- merge similar tests.
```release-note
NONE
```
/cc @xpivarc

Conformance tests for migration-Pt.2

---

pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

Currently, when a migration fails we signal the target pod to cleanup, and then we rely on a domain change event from the informer to unmount all the volumes (containerdisks, etc...).
If the domain was never created (just for example: using `FuncTestForceLauncherMigrationFailureAnnotation`), the virt-handler is informed of the stale client connection only once the watchdog timeout expires (30 seconds).
This delay can cause some tests to fail, for example "old finalized migrations should get garbage collected".
This can be avoided by re-enqueueing the vmi object when the handler is acknowledged
that the migration has failed.
Fixes #
```release-note
NONE
```

fix: Proactively trigger handler final cleanup when a migration fails

---

pkg/network/admitter/admit_suite_test.go
pkg/network/admitter/binding.go
pkg/network/admitter/binding_test.go
pkg/network/admitter/validator.go
pkg/network/multus/annotation.go
pkg/virt-config/deprecation/feature-gates.go
pkg/virt-config/feature-gates.go
tests/network/bindingplugin.go
tests/network/bindingplugin_macvtap.go
tests/network/bindingplugin_passt.go
tests/network/bindingplugin_slirp.go
tests/network/vmi_istio.go

The network binding plugins feature has been introduce back in v1.1.0, over a year ago.
Since, it has seen wide adoption in the community with multiple plugin vendors that introduced various network bindings through it.
The feature has reached a level of maturity, allowing it to be declared GA for the coming release.
The network binding plugins feature has a Feature Gate which is now marked as GA in the next Kubevirt release (v1.5).
Production and e2e testing code no longer depend on it.
Fixes #
```release-note
Network …
```

virt-config, fg: Graduate the Network Binding Plugin feature to GA

---

tests/migration/migration.go

This PR adds a description to the eventually block failure at [test_id:2303]
without description it's hard to understand the cause of failure
Example:
```tests/migration/migration.go:1517
Timed out after 60.000s.
Expected
<bool>: false
to be true
tests/migration/migration.go:1552
```
```release-note
None
```

Add description to migration failures [test_id:2303]

---

WORKSPACE

The mirror uploader requires the sha256 to be included for each http_file in the WORKSPACE or the uploader will fail to mirror the file[1]
Add a sha256 for the newly added virtio-win ISO
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-mirror-uploader/1861703214181650432#1:build-log.txt%3A86
Fixes #
```release-note
NONE
```

build: Add sha256 for virtio-win ISO to fix kubevirt mirror uploader

---

pkg/controller/testing/BUILD.bazel
pkg/controller/testing/testing.go
pkg/virt-controller/watch/clone/BUILD.bazel
pkg/virt-controller/watch/clone/clone_test.go
pkg/virt-controller/watch/drain/disruptionbudget/BUILD.bazel
pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
pkg/virt-controller/watch/drain/evacuation/BUILD.bazel
pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
pkg/virt-controller/watch/migration/BUILD.bazel
pkg/virt-controller/watch/migration/migration_test.go
pkg/virt-controller/watch/node/BUILD.bazel
pkg/virt-controller/watch/node/node_test.go
pkg/virt-controller/watch/pool/BUILD.bazel
pkg/virt-controller/watch/pool/pool_test.go
pkg/virt-controller/watch/vm/BUILD.bazel
pkg/virt-controller/watch/vm/vm_test.go
pkg/virt-controller/watch/vmi/BUILD.bazel
pkg/virt-controller/watch/vmi/vmi_test.go
pkg/virt-controller/watch/workload-updater/BUILD.bazel
pkg/virt-controller/watch/workload-updater/workload-updater_test.go

The new `SanityExecute` makes sure that all objects in the cache are not modified.
Fixes #
```release-note
NONE
```

Controllers: Improve unit test to catch corruption

---

pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/13257
This commit diverges from the original one only in using:
`d.Queue.AddAfter` instead of `d.queue.AddAfter`
```release-note
NONE
```

[release-1.3] fix: Proactively trigger handler final cleanup when a migration fails

---

pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/13257
This commit diverges from the original one only in using:
`d.Queue.AddAfter` instead of `d.queue.AddAfter`
```release-note
NONE
```

[release-1.2] fix: Proactively trigger handler final cleanup when a migration fails

---

pkg/virt-handler/BUILD.bazel
pkg/virt-handler/vm_test.go

With https://github.com/kubevirt/kubevirt/pull/13068 we can prevent the cache corruption in virt-handler.
Also, improved event expectations using `Receive()` gomega matcher
```release-note
NONE
```

virt-handler: Improve unit test to catch corruption

---

pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/13257
This commit diverges from the original one only in using:
`d.Queue.AddAfter` instead of `d.queue.AddAfter`
```release-note
NONE
```

[release-1.1] fix: Proactively trigger handler final cleanup when a migration fails

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

The vmi-create-admitter tests are currently somewhat inconsistent, with many tests focusing on implementation details rather than actual behavior. Additionally, different approaches are used for object instantiation, such as `newBaseVmi` (which relies on `libvmi`) and `api.NewMinimalVMI` (which does not).
This PR lays the groundwork for refactoring the vmi-create-admitter tests based on the following criteria:
* Refocus all test cases on behavior rather than implementation details.
* Remove code redundancy (e.g., duplicate AdmissionReview instantiations).
* Standardize VMI instantiation using `libvmi`, establishing it as the primary method for VMI construction.
This PR specifically addresses tests outside of any Context, applying all the outlined …

vmi-create-admitter refactor: change tests to test behavior instead of implementation details

---

tests/numa/numa.go

adds stdout to the description failure on numa test when commands fails
example :
```
Expected success, but got an error:
<exec.CodeExitError>: 
command terminated with exit code 2
{
Err: <*errors.errorString | 0xc005fddab0>{
s: "command terminated with exit code 2",
},
Code: 2,
} 
```
```release-note
None
```

tests/numa: add stdout to error description on failure

---

pkg/network/domainspec/generators.go
pkg/network/domainspec/generators_test.go
pkg/network/link/BUILD.bazel
pkg/network/link/names.go
pkg/network/link/names_test.go
pkg/network/setup/netpod/netpod.go
pkg/network/setup/netpod/netpod_test.go
pkg/network/setup/podnic.go
pkg/virt-launcher/virtwrap/nichotplug.go
pkg/virt-launcher/virtwrap/nichotplug_test.go

Currently, tap devices generated by KubeVirt have a dynamic name that is derived from their associated pod interface name.
Following PR #13018, it is possible to have a dynamic name for the pod's primary interface (other than `eth0`).
At the moment, it is not possible to migrate to a target pod that has a primary interface name different from the source, as the tap name is set in the domain XML.
In order to provide an option for a futuristic ability to accommodate for this kind of migration - set the tap name associated with the VM's primary interface to `tap0`.
Doing so will allow migrating the domain XML without modifying it either at the source or at the target.
An additional API change would be required in order to support such a migration, but it could be differed to when the need …

net, setup: Set const name for tap associated with VM's primary iface

---

pkg/virtctl/create/instancetype/instancetype.go
pkg/virtctl/create/instancetype/instancetype_test.go
pkg/virtctl/create/preference/preference.go
pkg/virtctl/create/preference/preference_test.go

This applies the following cleanups to the virtctl create preference
subcommand:
- Reorder imports
- Eliminate unnecessary consts
- Unexport struct fields not required to be exported
- Eliminate the optionFn custom type
- Avoid wrapper function by changing signature of run method
- Update examples to not use deprecated consts for cpu topology
- Check all returned errors
- Inline err checks
- Simplify unit tests a little and bring them closer to test structure
of create vm
- Add test case for namespaced flag
and the following cleanups to the virtctl create instancetype
subcommand:
- Reorder imports
- Eliminate unnecessary consts
- Unexport structs not required to be exported
- Eliminate the optionFn custom type
- Avoid wrapper function by changing signature of run method
- Avoid …

cleanup(virtctl,create): Apply cleanups to create instancetype and create preference

---

tests/infrastructure/prometheus.go

using the service account token of virt-operator isn't enough to access prometheusrules/api subresource, so it should be the executor token that should be used
After this PR:
switch to using kubevirt.Client().Config().BearerToken
```release-note
None
```

tests/infra/prometheus: use executor token for commands instead of virt-operator SA token

---

hack/lint-paths.txt
tests/infrastructure/certificates.go
tests/infrastructure/cluster-profiler.go
tests/infrastructure/crds.go
tests/infrastructure/downward-metrics.go
tests/infrastructure/k8s-client-changes.go
tests/infrastructure/node-labeller.go
tests/infrastructure/prometheus.go
tests/infrastructure/security.go
tests/infrastructure/taints-and-tolerations.go
tests/infrastructure/tls-configuration.go
tests/infrastructure/virt-controller-leader-election.go
tests/infrastructure/virt-handler.go

Add tests/infrastructure to linter and fix resulting lint issues. 
Fixes #
```release-note
NONE
```

lint: Add tests/infrastructure to linter

---

pkg/virtctl/create/preference/preference.go

This is a manual cherry-pick of the fixes for virtctl create preference found in #13369 
After this PR:
Fixes #
```release-note
None
```

[release-1.4] Apply fixes to virtctl create preference

---

tests/vm_test.go

Use Eventually in test to allow time for reconciliation loop to update VM after VMI removal.
fix flake:
https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.30-sig-compute/1837630591583916032
After this PR:
Fixes #
```release-note
NONE
```

[Tests]Use Eventually in test to allow time for reconciliation loop

---

tests/monitoring/BUILD.bazel
tests/monitoring/component_monitoring.go

Replace the use of virtctl in a component_monitoring test with the golang client. virtctl is not required here.
virtctl is used unnecessarily in a component_monitoring functest
After this PR:
virtctl is not used in component_monitoring functests anymore
Fixes #
```release-note
None
```

cleanup(tests,component_monitoring): Replace virtctl with client

---

pkg/network/domainspec/generators.go
pkg/network/domainspec/generators_test.go
pkg/network/link/BUILD.bazel
pkg/network/link/names.go
pkg/network/link/names_test.go
pkg/network/setup/netpod/netpod.go
pkg/network/setup/netpod/netpod_test.go
pkg/network/setup/podnic.go
pkg/virt-launcher/virtwrap/nichotplug.go
pkg/virt-launcher/virtwrap/nichotplug_test.go

Automatic cherry-pick of #13374.
After this PR:
Fixes #
```release-note
NONE
```

[release-1.4] net, setup: Set const name for tap associated with VM's primary iface

---

cmd/virt-handler/virt-handler.go
pkg/network/setup/netconf.go
pkg/network/setup/netconf_test.go
pkg/network/setup/netpod/netpod.go
pkg/network/setup/netstat.go
pkg/network/setup/netstat_test.go
pkg/network/vmicontroller/status.go
pkg/network/vmicontroller/status_test.go
pkg/virt-config/deprecation/feature-gates.go
pkg/virt-config/feature-gates.go
pkg/virt-controller/watch/BUILD.bazel
pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/application_test.go
pkg/virt-controller/watch/vmi/vmi.go
pkg/virt-controller/watch/vmi/vmi_test.go
pkg/virt-handler/non-root.go
tests/network/BUILD.bazel
tests/network/vmi_infosource.go

The DynamicPodInterfaceNaming feature-gate was introduced in v1.4 by PR  https://github.com/kubevirt/kubevirt/pull/13078.
The feature works well for at least two projects.
No negative feedbacks were received from the community on the implementation other than the fact that is does
not support migration between two different primary interface names (in this case the migration will fail).
This scenario is not supposed to be supported for the foreseeable future.
Fixes #
```release-note
NONE
```

Graduate the DynamicPodInterfaceNaming FG

---

pkg/storage/snapshot/restore.go
pkg/storage/snapshot/restore_test.go
pkg/storage/snapshot/snapshot.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
tests/storage/restore.go

Having in webhooks checks of other objects is raceful and not eventual consistent.
This PR makes sure all the relevant logic and check of a valid vmsnapshot exists in the restore controller and deletes it logic from the webhook.
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-41559
```release-note
VMRestore: remove VMSnapshot logic from vmrestore webhook
```

VMRestore: remove VMSnapshot logic from vmrestore webhook

---

tests/network/bindingplugin.go
tests/network/bindingplugin_macvtap.go
tests/network/bindingplugin_passt.go
tests/network/bindingplugin_slirp.go
tests/network/hotplug_bridge.go
tests/network/hotplug_sriov.go
tests/network/networkpolicy.go
tests/network/port_forward.go
tests/network/primary_pod_network.go
tests/network/probes.go
tests/network/sriov.go
tests/network/vmi_istio.go
tests/network/vmi_multus.go
tests/network/vmi_networking.go
tests/network/vmi_subdomain.go

Cover the tests/network folder with the gofumpt formatter.
Fixes #
```release-note
NONE
```

tests, network: Format codebase using `gofumpt`

---

pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
pkg/virt-launcher/virtwrap/api/defaults.go
pkg/virt-launcher/virtwrap/api/defaults_test.go
pkg/virt-launcher/virtwrap/api/schema.go
pkg/virt-launcher/virtwrap/api/schema_test.go
pkg/virt-launcher/virtwrap/api/testdata/domain_arm64.xml.tmpl
pkg/virt-launcher/virtwrap/api/testdata/domain_ppc64le.xml.tmpl
pkg/virt-launcher/virtwrap/api/testdata/domain_x86_64.xml.tmpl
pkg/virt-launcher/virtwrap/converter/testdata/domain_arm64.xml.tmpl
pkg/virt-launcher/virtwrap/converter/testdata/domain_ppc64le.xml.tmpl
pkg/virt-launcher/virtwrap/converter/testdata/domain_s390x.xml.tmpl
pkg/virt-launcher/virtwrap/converter/testdata/domain_x86_64.xml.tmpl
pkg/virt-launcher/virtwrap/converter/testdata/domain_x86_64_root.xml.tmpl
pkg/virt-launcher/virtwrap/libvirtxml/convert.go

According to https://libvirt.org/formatdomain.html, the `VMPort` feature exists to enable emulation of the VMWare IO port, for vmmouse and so forth. Libvirt defaults it to on, but containers generally don't make use of the port, so it is better to explicitly disable this feature without even bothering to export it to users.
This is a continuation of https://github.com/kubevirt/kubevirt/pull/11197.
The virt-launcher API builds libvirt XML without the feature (`<vmport state=.../>`). In this case, libvirt defaults to `state="on"`, but that spends resources on exposing features that will never be used in the scope of Kubevirt.
After this PR:
libvirt XML is generated with explicit `<vmport state="off">`.
This checklist is not enforcing, but it's a reminder of items that could …

Unconditionally disable libvirt's VMPort feature which is relevant for VMWare only

---

pkg/virtctl/unpause/BUILD.bazel
pkg/virtctl/unpause/unpause_test.go

unit tests in unpause_test.go uses traditional methods for creating and modifying VM and VMI resources,
After this PR:
Unit tests have been refactored to use the libvmi package for creating and modifying VM and VMI resources,
Partially address: #12059 
* Using the libvmi package simplifies the unit tests and makes them more readable.
* This approach ensures a standard way of creating VM and VMI resources across tests.
* Direct manipulation of resources was replaced with libvmi functions, which enhances readability and maintainability.
The discussion took place in issue #12059 
Before refactoring the code, I encountered an error stating:
"Error …

Refactor unit tests to use libvmi for resource creation in unpause_test.go

---

tests/vmi_vsock_test.go

Attach /dev/null to netcat's stdin so it exits immediately instead of waiting to be brought back into the foreground if it should await any input.
See flakes like this one:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13378/pull-kubevirt-e2e-k8s-1.31-sig-compute-serial/1862145066760409088
VSOCK tests might flake because netcat does not exit.
After this PR:
VSOCK tests should not flake or at least fail with a more detailed reason because netcat exits.
Fixes # …

fix(tests,vsock): Attach /dev/null to netcat's stdin

---

pkg/virt-controller/watch/migration/migration.go
pkg/virt-controller/watch/migration/migration_test.go

The migration controller previously updated the status of migrations in a final state (`Final()`) by copying the `MigrationState` from the VMI, regardless of whether it matched the migration being processed. This caused finalized migrations to be incorrectly updated when the VMI's `MigrationState` was changed by a new migration.
This PR ensures that only the active migration receives status updates. It skips updates for migrations where the `MigrationUID` does not match the VMI's `MigrationState`, preserving the state of completed migrations and preventing unnecessary updates. 
```release-note
bug-fix: prevent status update for old migrations
```

watch/migration: bug-fix prevent status updates for finalized migrations

---

tests/migration/migration.go

If the vmi status update is not fast enough after the migration completion the Eventually block will always compare the old vmi IP with the newer one.
We have to retrieve also the vmi in the Eventually block.
```release-note
NONE
```

e2e migration: fix ip check between vmi and pod

---

pkg/virt-launcher/virtwrap/BUILD.bazel

Some unit test suites take longer times to run than others when not cached, to name a few:
`virt-launcher/virtwrap` - 44.8s 
`virt-operator/resource/generate/install` - 18.2s
`virtctl/pause` - 18.1s
`instancetype` - 17.7s
`virt-handler/cache` - 15.5s
`storage/snapshot` - 15.5s
`notify-client` - 11.6s
`util/openapi` - 11.5s
Make use of the `ginkgo_test` target[1] to run tests in parallel for `virt-launcher/virtwrap`. From multiple experiments it cut down the time to around ~8s instead of ~44s.
Other packages remain to be tested, I specifically chose virtwrap as it serves as a prominent component within KubeVirt with a relatively large test suite.
[1] https://github.com/kubevirt/kubevirt/pull/5749
This checklist is not enforcing, but it's a reminder of …

virt-launcher/virtwrap - run unit tests in parallel

---

pkg/virt-controller/watch/migration/migration.go
pkg/virt-controller/watch/migration/migration_test.go

Manual backport of #13426 
in migration_test: sanityExecute() wasn't introduced yet, so controller.Execute() is being used instead.
```release-note
bug-fix: prevent status updates for finalized migrations
```

[release-1.4] watch/migration: bug-fix prevent status updates for finalized migrations

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

The tests in the "with VirtualMachineInstance metadata" context instantiated VMIs using functions that didn't leverage `libvmi` as well as didn't make use of the `newAdmissionReviewForVMICreation` function to create admission reviews.
The tests in the "with VirtualMachineInstance metadata" context now instantiate VMIs using libvmi and use the `newAdmissionReviewForVMICreation` function to create admission reviews.
Partially addresses: https://github.com/kubevirt/kubevirt/issues/13407
```release-note
NONE
```

vmi-create-admitter_test refactor: refactor vmi metadata context tests

---

cmd/virt-handler/virt-handler.go
pkg/util/util.go
pkg/virt-operator/resource/generate/components/daemonsets.go

Only `/var/lib/kubelet/pods` is mounted in virt-handler, the rest of /var/lib/kubelet is accessed through `/proc/1/root`
After this PR:
`/var/lib/kubelet` is mounted in virt-handler, which lifts the need for /proc/1/root and should correctly follow an eventual symlink, see issue.
Fixes #12520 
```release-note
/var/lib/kubelet on the nodes can now be a symlink
```

virt-handler: mount all of /var/lib/kubelet

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

The tests in the "with probes given" context used instantiated VMIs using functions that didn't leverage `libvmi` as well as didn't make use of the `newAdmissionReviewForVMICreation` function to create admission reviews.
The tests in the "with probes given" context now instantiate VMIs using libvmi and use the `newAdmissionReviewForVMICreation` function to create admission reviews.
Partially addresses: https://github.com/kubevirt/kubevirt/issues/13407
```release-note
NONE
```

vmi-create-admitter_test refactor: refactor probe context tests

---

pkg/storage/types/BUILD.bazel
pkg/storage/types/cdi.go
pkg/storage/types/cdi_test.go
pkg/virt-controller/watch/vmi.go

After this PR:
manual backport of #13138
Fixes #
```release-note
Avoid NPE when getting filesystem overhead
```

[release-1.3] Avoid NPE when getting filesystem overhead

---

hack/kwok-perftests.sh
tools/perfscale-audit/api/api.go
tools/perfscale-audit/metric-client/metric-client.go

There are no metrics exported for virt-handler memory utilization
After this PR:
metrics for  the number of vmi scheduled per node 
metrics for the avg, min, max CPU and memory utilization of virt-handler pods
Removed double quotes in the shellscript because
use of quotes around ${extra_args} making it treat as a single variable, if it is empty or has space it is showing unexpected behaviour. As the args passed contain the space at the begining and "&&" it is showing unexpected behaviour https://github.com/kubevirt/kubevirt/blob/65e1db9516b52ecc4c7879ec72fcf2b0b3d39e6e/hack/kwok-perftests.sh#L78 .
Removed the quotes around when dealing with multi-word or special character arguments.
Fixes #13196 …

Add virt-handler cpu and memory usage metrics

---

pkg/network/setup/netpod/netpod.go
pkg/network/setup/netpod/netpod_test.go

Fedora 40 has Address Conflict Detection (ACD) for IPv4 enabled by default [1].
After receiving an IPv4 address from a DHCP server, it sends an ARP probe to make sure other devices don't use its allocated address.
When spinning up a Fedora 40 VM, connected to a pod network with managedTap binding, the ACD fails due to the network stack answering the ARP probe, thus failing the ACD - and preventing setting the IPv4 address on that interface.
Set the network stack to ignore ARP, similarly to bridge binding.
[1] https://fedoraproject.org/wiki/Changes/Enable_IPv4_Address_Conflict_Detection
Fixes #
This checklist is not enforcing, but it's a reminder of items that …

netpod, managedTap: Add ArpIgnore

---

tests/migration/paused.go

This tests has been flaky over the past two days- causing over 30% impact to the compute-migrations presubmit lane[1]
[1] https://search.ci.kubevirt.io/?search=paused+vmi+during+migration+should+migrate+paused+when+acceptable+time+exceeded+and+post-copy+is+forbidden+should+pause+the+VMI+and++fail+migration&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
/cc @dhiller @xpivarc @fossedihelm 
We have to get this one quarantined as quickly as we can. It is flaking a lot - https://testgrid.kubernetes.io/kubevirt-presubmits#pull-kubevirt-e2e-k8s-1.31-sig-compute-migrations&width=20 …

e2e,migration: Quarantine very flaky migration test with paused VMI

---

pkg/network/setup/netpod/netpod.go
pkg/network/setup/netpod/netpod_test.go

Automatic cherry-pick of #13458.
Fixes #
```release-note
Adjust managedTap binding to work with VMs with Address Conflict Detection enabled
```

[release-1.4] netpod, managedTap: Add ArpIgnore

---

pkg/virt-handler/BUILD.bazel
pkg/virt-handler/guestagent.go
pkg/virt-handler/heartbeat/BUILD.bazel
pkg/virt-handler/heartbeat/heartbeat.go
pkg/virt-handler/non-root.go
pkg/virt-handler/realtime.go
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

The virt-handler suffers of multiple possible race conditions during shutdown:
1. There isn't a correct sync between the controller and the heartbeat shutdown
2. There isn't proper error handling of the final node labelling process.
The intent of the `heartBeatDone` channel was
to ensure the heartbeat is finished
before stopping the handler vm controller.
In particular, its intention was to prevent
a shutdown race:
- heartbeat tries to stop and do a last http request
- controller shuts down
If the controller shuts down first, then the main function
just exists, killing all remaining go routines right away.
Actually it is not doing its job since
`c.heartBeat.Run(c.heartBeatInterval, stopCh)` is
not a blocking function (it spawns a goroutine and
immediately returns the channel).
As result, …

Virt handler fixes and cleanup

---

pkg/virt-launcher/virtwrap/converter/converter.go

The IoctlGetInt Got broken on Big Endian Architectures. So, it is giving the incorrect values for logicalSize and BlockSize.
and the BlockSize Feature is not working on s390x. Refer this issue : https://github.com/golang/go/issues/60429
After this PR:
I have replaced the IoctlGetInt with IoctlGetUint32 which will work on every architecture. 
Fixes #
```release-note
None.
```

fix: Use IoctlGetUInt32 instead of IoctlGetInt for fetching the logicalSize and physicalSize.

---

tests/storage/export.go

When importing a fully expanded image into a PVC that matches its size, the process can fail due to insufficient usable space in the scratch PVC caused by the presence of the lost+found directory.
We should probably address this behavior in CDI by increasing the default fs overhead. Until we decide what to do, this Pull Request temporarily addresses this issue in a quarantined test by doubling the size request, which results in increased overhead space now able to contain lost+found.
More info: https://issues.redhat.com/browse/CNV-51575.
Partially fixes https://github.com/kubevirt/kubevirt/issues/13316
```release-note
NONE
```

Tests: Address bug in quarantined export tests

---

tests/compute/console.go

Mark conformance tests following https://github.com/kubevirt/kubevirt/blob/main/docs/conformance.md for console tests.
The two marked tests cover all the cases:
- the first one is the positive case with no concurrent serial console open, and possibility to connect more times.
- the second one is the negative case
```release-note
NONE
```

e2e console: Mark conformance tests

---

pkg/virtctl/expose/OWNERS
pkg/virtctl/guestfs/OWNERS
pkg/virtctl/imageupload/OWNERS
pkg/virtctl/memorydump/OWNERS
pkg/virtctl/scp/OWNERS
pkg/virtctl/ssh/OWNERS
pkg/virtctl/vmexport/OWNERS
pkg/virtctl/vnc/OWNERS

Codify the ownership of some virtctl packages by adding OWNERS files. The ownership is mostly derived from labels found on virtctl's functional tests with the exception of virtctl expose.
virtctl sub packages do not have individual OWNERS.
After this PR:
virtctl sub packages have individual OWNERS.
Fixes #
```release-note
None
```

chore(virtctl): Codify ownership of virtctl packages

---

tests/storage/storage.go
tests/virtctl/guestfs.go

Missed these in https://github.com/kubevirt/kubevirt/pull/13137
Fixes #
```release-note
NONE
```

Add block label to some more tests

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

This PR reduces duplications in the unit tests at `vmi-create-admitter_test.go` by using the helper `newAdmissionReviewForVMICreation(vmi) ` for the  construction of admission-review objects
/kind cleanup
Relates-To: #13407
```release-note
None
```

vmi-create-admitter_test.go: reduce duplication in unit tests

---

api/openapi-spec/swagger.json
manifests/generated/kv-resource.yaml
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

After this PR:
Fixes #
```release-note
NONE
```

[Docs] Update VMRolloutStrategy documentation to include the VM liveUpdateable fields

---

pkg/virt-launcher/virtwrap/api/defaults.go
pkg/virt-launcher/virtwrap/api/schema_test.go
pkg/virt-launcher/virtwrap/api/testdata/domain_arm64.xml.tmpl
pkg/virt-launcher/virtwrap/api/testdata/domain_ppc64le.xml.tmpl
pkg/virt-launcher/virtwrap/api/testdata/domain_x86_64.xml.tmpl
pkg/virt-launcher/virtwrap/converter/amd64.go
pkg/virt-launcher/virtwrap/converter/archconverter.go
pkg/virt-launcher/virtwrap/converter/arm64.go
pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/converter/ppc64le.go
pkg/virt-launcher/virtwrap/converter/s390x.go
pkg/virt-launcher/virtwrap/converter/testdata/domain_arm64.xml.tmpl
pkg/virt-launcher/virtwrap/converter/testdata/domain_ppc64le.xml.tmpl
pkg/virt-launcher/virtwrap/converter/testdata/domain_s390x.xml.tmpl

VMPort is not support by the qemu on Arm64, so skip setting it via libvirt.
```
vmport is not available with this QEMU binary
```
Fixes #13436 
```release-note
NONE
```

virtwrap, arm64: not add VMPort on Arm64 platform

---

tests/storage/guestfs.go
tests/storage/storage.go

Missed these in https://github.com/kubevirt/kubevirt/pull/13137
Fixes #
```release-note
NONE
```

[release-1.4] Add block label to some more tests

---

tests/network/BUILD.bazel
tests/network/vmi_networking.go

There were 2 tests that created an Alpine VMI without networking and `AutoattachPodInterface=false`. One of which counted the number of interfaces in the guest and the other one just waited for the VMI to launch
After this PR:
Improve the more detailed test and delete the redundant one 
Fixes #
```release-note
NONE
```

tests, network, vmi_networking: Combine redundant tests of VMIs without network

---

pkg/virt-launcher/virtwrap/converter/converter_test.go

Arm64 does not support CPU hotplug now, we can skip the test
Fixes #13451
```release-note
NONE
```

unit, arm64: skip cpu hotplug unit test on Arm64

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go

manual backport of #13426
reason for backport is due to missing helper functions like `addPod(pod)`, `addNodeNameToVMI(vmi, "node02")`, and also the fake virtClientset  that  wasn't introduced yet for this release.
```jira-ticket
https://issues.redhat.com/browse/CNV-52436
```
```release-note
bug-fix: prevent status updates for finalized migrations
```

[release-1.1] watch/migration: bug-fix prevent status updates for finalized migrations

---

docs/debugging.md

Describe how to use a `delve` debugger with kubevirt go processes
Commits are incremented in steps of "depth", reviewers may choose to include only the first one or two commits 
replaces https://github.com/kubevirt/kubevirt/pull/13099
After this PR:
Fixes #
```release-note
NONE
```

docs, debug: explain how to use dlv debugger 

---

tests/virtctl/create_vm.go
tests/virtctl/guestfs.go
tests/virtctl/imageupload.go
tests/virtctl/memorydump.go
tests/virtctl/scp.go
tests/virtctl/ssh.go
tests/virtctl/vnc.go

The tests/virtctl folder was missing some of the test_id
After this PR:
All virtctl test should have a test_id
This will help map out the tests if a failure arises
https://issues.redhat.com/browse/CNV-45386
```release-note
NONE
```

add test_id to virtctl tests

---

tests/migration/paused.go

The failure rate of the compute migrations presubmit lane is higher than 50% mainly due to these tests[1]
Quarantine to give time to get a fix in place
[1] https://testgrid.kubernetes.io/kubevirt-presubmits#pull-kubevirt-e2e-k8s-1.31-sig-compute-migrations&width=20
Fixes #
```release-note
NONE
```

e2e,migrations: Quarantine very flaky paused VMI migration tests

---

api/openapi-spec/swagger.json
hack/cluster-deploy.sh
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/schema.go
staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/libstorage/BUILD.bazel
tests/libstorage/datavolume.go
tests/migration/migration.go
tests/migration/postcopy.go
tests/pool_test.go
tests/storage/datavolume.go
tests/storage/hotplug.go
tests/storage/restore.go
tests/storage/snapshot.go
tests/storage/storage.go
tests/virtctl/imageupload.go
tests/virtiofs/datavolume.go
tests/vm_test.go
tests/vmi_configuration_test.go

After several releases with CDI `DataVolume` garbage collection disabled by default, we decided to [deprecate](https://github.com/kubevirt/containerized-data-importer/pull/3552) it, as unfortunately it violates fundamental principle of Kubernetes. CR should not be auto-deleted when it completes its role (`Job` with `TTLSecondsAfterFinished` is an exception), and once CR was created we can assume it is there until explicitly deleted. In addition, CR should keep idempotency, so the same CR manifest can be applied multiple times, as long as it is a valid update (e.g. `DataVolume` validation webhook does not allow updating the spec).
```release-note
Remove deprecated DataVolume garbage collection tests
```

Remove deprecated DataVolume garbage collection tests

---

pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go

The Status label values were added with a Capital letter. It needs to be in all in lower case letters like all other label values.
status label in kubevirt_vm_info was in capital letters e.g. Stopped
After this PR:
status label in kubevirt_vm_info is in small letters e.g. stopped
Fixes # jira-ticket: https://issues.redhat.com/browse/CNV-51223
```release-note
none
```

Status label value in kubevirt_vm_info metric should be in lower case

---

pkg/virt-launcher/virtwrap/manager.go
tests/storage/datavolume.go

This PR aims to fix the usable disk size calculation during expansion.
We initially assumed `stat.Size` represented the actual disk usage, but after dealing with sparse disks it's been shown it matches the virtual size instead, leading to wrong calculations during expansion.  This PR fixes this behavior by getting the actual size with qemu-img.
```release-note
NONE
```

Fix usable disk size calculation during expansion

---

pkg/virt-launcher/virtwrap/manager.go
tests/storage/datavolume.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/13237. Needed to address a conflict in the test, no other major changes.
Follow-up for https://issues.redhat.com/browse/CNV-47542 (failed verification).
Fixes # https://issues.redhat.com/browse/CNV-47542
```release-note
NONE
```

[release-1.3] Fix usable disk size calculation during expansion

---

pkg/virt-launcher/virtwrap/manager.go
tests/storage/datavolume.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/13237. Needed to address a conflict in the test, no other major changes.
Follow-up for https://issues.redhat.com/browse/CNV-47542 (bug failed verification).
Fixes # https://issues.redhat.com/browse/CNV-47542
```release-note
NONE
```

[release-1.4] Fix usable disk size calculation during expansion

---

pkg/storage/export/export/BUILD.bazel
pkg/storage/export/export/export.go
pkg/storage/export/export/export_test.go
pkg/storage/export/export/vm-source.go
pkg/storage/export/export/vm-source_test.go
pkg/storage/export/export/vmsnapshot-source.go
pkg/storage/export/virt-exportserver/exportserver.go
pkg/storage/snapshot/restore.go
pkg/storage/snapshot/snapshot.go
pkg/storage/utils/BUILD.bazel
pkg/storage/utils/volumes.go
pkg/storage/utils/volumes_test.go
tests/storage/export.go

This PR introduces support for exporting backend storage PVCs using the export API.
Fixes # https://issues.redhat.com/browse/CNV-50230
Not including the backend volume in the export VM manifest as it doesn't make sense to use the original VM's TPM when recreating a different VM.
```release-note
Bugfix: Support exporting backend PVC
```

Export: Support exporting backend storage PVC 

---

pkg/storage/types/BUILD.bazel
pkg/storage/types/cdi.go
pkg/storage/types/cdi_test.go
pkg/virt-controller/watch/vmi.go

After this PR:
manual backport of https://github.com/kubevirt/kubevirt/pull/13138
Fixes #
```release-note
Avoid NPE when getting filesystem overhead
```

[release-1.2] Avoid NPE when getting filesystem overhead

---

docs/devel/virtual-machine.md
docs/probes.md
examples/vm-pool-cirros.yaml
pkg/virt-controller/watch/testing/testing.go
pkg/virt-controller/watch/vm/vm_test.go
tools/vms-generator/utils/utils.go

Removed instances of the deprecated `.spec.running` field in both examples and documentation.
Related to https://github.com/kubevirt/kubevirt/issues/11993.
```release-note
NONE
```

Remove usage of deprecated .spec.running field

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go

Manual backport of #13426
reason for backport is for some reason cherry-pick automation failed from #13448
```
https://issues.redhat.com/browse/CNV-52437
```
```release-note
bug-fix: prevent status updates for finalized migrations
```

[release-1.0] watch/migration: bug-fix prevent status updates for finalized migrations

---

tests/decorators/decorators.go
tests/virtctl/BUILD.bazel
tests/virtctl/create_vm.go
tests/virtctl/framework.go
tests/virtctl/guestfs.go
tests/virtctl/imageupload.go
tests/virtctl/memorydump.go
tests/virtctl/scp.go
tests/virtctl/ssh.go
tests/virtctl/vnc.go

Add a label to allow filtering for virtctl tests and add Describes that
allow to use this label easily. Then make use of the new VirtctlDescribe.
virtctl functests cannot be filtered with a label.
After this PR:
There is a label that allows to filter functests so only virtctl tests run.
Fixes #
Merge after #13415 
```release-note
None
```

chore(tests,virtctl): Add virtctl label and VirtctlDescribe

---

tests/migration/migration.go

Test "should reject a migration of a vmi with a non-shared data volume" requries a RWO Datavolume in order to actually test non-shared volume.
Fixes #
```release-note
NONE
```

Explicitly request RWO storage for tests

---

tests/storage/export.go

This may or may not help with flakes. "ready" is a bit of a stronger indication than "running".
```
error dialing backend: write tcp: use of closed network connection
```
Fixes #
```release-note
NONE
```

export tests: ensure pod readiness before command exec

---

tests/storage/export.go

This is not needed following https://github.com/kubevirt/kubevirt/pull/13321
Fixes #
```release-note
NONE
```

Drop [serial] text from test

---

docs/observability/metrics.md
pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go

We would like for the Admin to be able to filter the Virtual machines based on the date and time the VM was created. The metric value is reported as timestamp_seconds in epoch time.
(note that the name updated to `kubevirt_vm_create_date_timestamp_seconds`):
Fixes # jira-ticket: https://issues.redhat.com/browse/CNV-48216
```release-note
Add kubevirt_vm_create_date_timestamp_seconds metric
```

Add a metric that reports the VM create date

---

pkg/virt-controller/services/template.go

Fix bug by checking if PVC is nil instead of checking for an empty name
The real risk is the PVC being nil, which can lead to a panic in virt-controller.
After this PR:
Fixes #
```release-note
NONE
```

[virt-controller]Fix bug by checking if PVC is nil

---

tests/tests_suite_test.go

Rename "test suite" to "KubeVirt Test Suite" to
better distinguish suite when multiple suites
are run (conformance as example)
`Tests Suite: [sig-network] [rfe_id:694][...`
After this PR:
`KubeVirt Tests Suite: [sig-network] [rfe_id:694][`
Fixes #
```release-note
NONE
```

Provide better identification of our test suite

---

pkg/storage/backend-storage/backend-storage.go

VMs requesting persistent EFI may get non-persistent EFI instead
After this PR:
Persistent EFI is fixed
Fixes #
```release-note
Fixed bug where VMs may not get the persistent EFI they requested
```

backend-storage: add missing check for persistent EFI

---

tests/conformance/conformance.go

Now when we are moving to using labels instead
of text filtering we need to tweak our conformance binary to support this.
For now we make the focus and label filter mutual exclusive as the network conformance tests are not labeled yet.
Fixes #
Please try to run this
```release-note
NONE
```

Conformance: Integrate with label filter

---

pkg/virt-launcher/virtwrap/device/hostdevice/sriov/OWNERS

Mark the `pkg/virt-launcher/virtwrap/device/hostdevice/sriov` package as owned by SIG-network, as the SIG owns the SR-IOV NICs logic.
Fixes #
```release-note
NONE
```

virt-launcher, sriov: Add OWNERS file

---

cmd/fake-qemu-process/OWNERS
cmd/virt-chroot/OWNERS
cmd/virt-handler/OWNERS
cmd/virt-launcher-monitor/OWNERS
cmd/virt-launcher/OWNERS
pkg/hooks/OWNERS
pkg/virt-handler/virt-chroot/OWNERS
pkg/virt-launcher/OWNERS

Adds sig-compute OWNERS to relevant sub-directories.
```release-note
NONE
```

Add sig-compute OWNERS to sub-directories

---

pkg/virtctl/create/vm/BUILD.bazel
pkg/virtctl/create/vm/vm.go
pkg/virtctl/create/vm/vm_test.go

Validate the names of disks that are derived from the VM's name or specified by the user against RFC 1123 DNS label rules to avoid generating VMs with disk names that will lead to the VM being rejected upon creation.
virtctl create vm allows to generate VMs with disk names that will lead to rejection of the VM upon creation.
After this PR:
virtctl create vm validates disk names and prevents disk names that will lead to rejection of a VM upon creation.
Fixes #13340
```release-note
virtctl create vm validates …
```

fix(virtctl,create): Validate names of disks

---

tests/infrastructure/virt-controller-leader-election.go

This PR makes test_id:4642 slightly simpler and ever-so-slightly faster
/kind cleanup
```release-note
NONE
```

tests/infrastructure: Simplify virt controller recovery test

---

pkg/virtctl/expose/expose.go
pkg/virtctl/expose/expose_test.go

Use vm.kubevirt.io/name as label selector when exposing VMs and VMIs, since every virt-launcher Pod will have this label with the value set to the name of its VM/VMI. This makes virtctl expose more robust in situations where there are no or no unique labels defined on a VM/VMI.
virtctl expose uses any label found on a VM/VMI as a service selector. In case of non-unique label values this can lead to exposure of the wrong VM/VMI.
After this PR:
virtctl expose uses the unique `vm.kubevirt.io/name` label found on every virt-launcher Pod as a service selector.
Fixes #
This checklist is not enforcing, but it's a reminder of items that could be relevant …

fix(virtctl,expose): Use vm.kubevirt.io/name as label selector

---

pkg/storage/snapshot/restore.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
tests/storage/restore.go

Code had a faulty assumption that Always or RerunOnFailure means that VM cannot be stopped.
Instead we dont check the RunStrategy or Running field and we look on the VMI if it exists or not.
(This fix is not ideal since we prefere not to check other objects in the webhook since it's racy but, this is the minimal API change possible for a bug fix)
This issue was already handled in for vmsnapshot process but also applies here: #12515
This fixes:
Jira-ticket: https://issues.redhat.com/browse/CNV-51071
In main we had a PR that completely removed the webhook validation and this was handled in the controller alone, due to bigger API changes that were required we created this PR to fix the bug with minimal API changes. https://github.com/kubevirt/kubevirt/pull/13195
After this …

[release 1.4] VMRestore: allow creating vmrestore even if runstrategy is not Halted

---

pkg/virtctl/BUILD.bazel
pkg/virtctl/root.go
pkg/virtctl/root_test.go

The log verbosity flag is added initially to the default flag set by init() of glog. With this change the flag is re-added to virtctl's root command flag set, so it can be used within virtctl.
virtctl does not support the `-v` / `--v` log verbosity flag.
After this PR:
virtctl supports setting the log verbosity with the `-v` / `--v` flag.
Fixes #12779 
```release-note
None
```

fix(virtctl): Ensure the log verbosity flag is supported

---

pkg/virtctl/BUILD.bazel
pkg/virtctl/root.go
pkg/virtctl/root_test.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/13555
virtctl does not support the -v / --v log verbosity flag.
After this PR:
virtctl supports setting the log verbosity with the -v / --v flag.
Fixes https://github.com/kubevirt/kubevirt/issues/12779
Fixes #
```release-note
None
```

[release-1.4] fix(virtctl): Ensure the log verbosity flag is supported

---

pkg/instancetype/BUILD.bazel
pkg/instancetype/upgrade/BUILD.bazel
pkg/instancetype/upgrade/upgrade_suite_test.go
pkg/instancetype/upgrade/upgrade_test.go

/kind cleanup
This PR starts to move the existing unit tests into sub packages alongside their now extracted implementations, in this case starting with the ControllerRevision upgrade unit tests.
This work is part of instancetype.kubevirt.io - Refactor unit tests and consolidate consumers on newly extracted implementations https://github.com/kubevirt/kubevirt/issues/13507
Fixes #
```release-note
NONE
```

instancetype: Move upgrade tests into subpackage

---

tests/network/bindingplugin_passt.go

Currently, the passt binding plugin e2e tests register the plugin with the LinkRefresh migration method and expect the guest's IP address to change following a migration.
The LinkRefresh method works by switching the interface off for 100ms and turning it back on.
On newer Fedora versions (for example F39), NetworkManager does not take action, unless the link is down for at least six seconds [1] - thus the LinkRefresh method does not work with it and the test breaks since the guest IP does not change following the migration.
Passt has the ability to perform automatic NAT, meaning we can retain the previous IP address and the VM will still be able to communicate over the pod network following the migration.
[1] https://networkmanager.pages.freedesktop.org/NetworkManager/NetworkManager/Netwo …

passt binding plugin, e2e: Drop expectation for IP refresh

---

pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/converter/s390x.go
pkg/virt-launcher/virtwrap/converter/testdata/domain_s390x.xml.tmpl

Testers reported that keyboard input was not recognized when attempting to access the VM via VNC. This issue arose because no virtual keyboard was configured for the s390x architecture. This explains why console and SSH access functioned without any problems.
Before this PR: critical bug when connecting via VNC to s390x guests
After this PR: 
Fixes #
```release-note
NONE
```

fix: resolve critical issue with keyboard input for s390x

---

tests/framework/matcher/phase.go
tests/libmigration/migration.go
tests/libpod/render.go
tests/migration/eviction_strategy.go
tests/migration/migration.go
tests/migration/paused.go
tests/migration/postcopy.go

Post-copy tests are flaky
After this PR:
Code is cleaner and post-copy tests are less flaky
Fixes #13435
Please review commit by commit!
```release-note
NONE
```

Cleanup and reduce flakiness of some post-copy migration functests

---

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

The VMI creation admitter denies VMI creation in case there are readiness and/or liveness probes when there is no pod network defined.
Replace the call to the custom `getNumberOfPodInterfaces` with the standard `vmispec.LookupPodNetwork`.
Doing so, enable us to remove the unit tests of `getNumberOfPodInterfaces` which test an implementation detail instead
of the admitter's exported API.
The `Describe` container containing the unit tests for `getNumberOfPodInterfaces` unfortunately also contains additional tests, so its subject was changed.
This scenario described above is covered by the probes tests in the admitter's unit tests file.
Fixes # …

VMI create admitter: Remove getNumberOfPodInterfaces

---

tests/libnode/node.go
tests/mdev_configuration_allocation_test.go
tests/swap_test.go
tests/virt-handler_test.go

Continuing #13104 
The functions `ExecuteCommandInVirtHandlerPod` and `ExecuteCommandOnNodeThroughVirtHandler` are pretty much the same.
The only difference is `ExecuteCommandOnNodeThroughVirtHandler` returning the command stderr as is.
While `ExecuteCommandInVirtHandlerPod` combine the stderr as part of the returned error.
Since in all `ExecuteCommandOnNodeThroughVirtHandler` usages, the returned stderr is printed in one way or another (e.g.:  reported  it though ginkgoExpect message).
There is no value in returning it over having stderr part of the returned error message.
Hence, merge `ExecuteCommandOnNodeThroughVirtHandler` into `ExecuteCommandInVirtHandlerPod`.
Some tests use `ExecuteCommandOnNodeThroughVirtHandler` and others `ExecuteCommandInVirtHandlerPod`.
After …

 tests/libnode: Unify exec command on node functions

---

docs/metrics.md
pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go
tests/monitoring/metrics.go

This is a manual cherry-pick of
https://github.com/kubevirt/kubevirt/pull/12593, https://github.com/kubevirt/kubevirt/pull/12625 and https://github.com/kubevirt/kubevirt/pull/12910
jira-ticket: https://issues.redhat.com/browse/CNV-49890
Fixes #
```release-note
Add kubevirt_vm_resource_requests metric
```
/cc @sradco @avlitman

[release-1.3] Add kubevirt_vm_resource_requests metric

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go

IsKubeVirtServiceAccount is deprecated [1], adjust the code to use `admitter.kubeVirtServiceAccounts` instead.
[1] https://github.com/kubevirt/kubevirt/pull/12568
Partially addresses https://github.com/kubevirt/kubevirt/issues/11177.
```release-note
None
```

VMI update admitter: Rm call to deprecated IsKubeVirtServiceAccount

---

tests/vnc_test.go

After this PR:
Fixes #
```release-note
NONE
```

Fix: corrected the typo in "Timeout" in the vnc_test

---

tests/network/vmi_networking.go

Having tests that conditionally skip tests on run time is bad practice that should be avoided.
Having programmatic skips could lead to false positive results due to some env issues.
Tests should not be aware of the env, this is a responsibility of the entity that run the tests (e.g.: CI).
The mentioned test is not Conformance test and expected to be executed multi node cluster env.
On CI sig-network tests runs on multi nodes cluster env.
Programmatic skip is removed from VM with bridge binding tests.
The TCP network connectivity across nodes tests will always run.
Its safe to remove the skip because on CI these tests are executed on multi node cluster env.
**Notes:**
- In case D/S project like to skip TCP connectivity tests in case there are no two …

e2e,network: Remove skip in bridge binding TCP conn. tests

---

cmd/virt-tail/main.go
pkg/virt-controller/services/serialconsolelog.go
pkg/virt-controller/services/template.go

When the `virt-tail` times out, the `virt-monitor` still works well.
After this PR:
The `virt-tail` and `virt-monitor` share same timeout. If one of them works, they both should work.
Fixes #13466
In original design, the `virt-tail` only accepts 20 seconds timeout. However, the `virt-monitor` might take more than 20 seconds to start. At that moment, the `virt-tail` couldn't tail the `compute` container, even the compute container works well.
Although we can retry when the `virt-tail` fails, I think using retry or modifying timeout to 30 second or more is not a effective way to fix this issue.
Links to places where the discussion took place: Please check comments in …

feat: pass timeout from virt-monitor to virt-tail

---

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go

Unable to create VM with external dv population due to validating webhook.
```apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
labels:
kubevirt.io/vm: test
name: test
spec:
dataVolumeTemplates:
- metadata:
creationTimestamp: null
labels:
app.kubernetes.io/managed-by: kube-nfv
name: cirros-0-6-3-x86-64-disk-dv
spec:
pvc:
accessModes:
- ReadWriteOnce
dataSourceRef:
apiGroup: cdi.kubevirt.io
kind: VolumeImportSource
name: cirros-0-6-3-x86-64-disk
resources:
requests:
storage: 1Gi
instancetype:
kind: VirtualMachineInstanceType
name: flavour-bb9b22f8-4844-4dfa-8030-e5b4bd094236
revisionName: test-flavour-bb9b22f8-4844-4dfa-8030-e5b4bd094236-v1beta1-5476fdbc-7280-4eb9-9f7a-67e105a2fff8-1
preference:
kind: VirtualMachinePreference
name: …
```

Fix validateDataVolume function to allow externally populated Data Volume

---

tests/README.md
tests/framework/checks/skips.go
tests/kubectl_test.go
tests/migration/eviction_strategy.go
tests/migration/migration.go
tests/migration/paused.go
tests/migration/postcopy.go
tests/monitoring/vm_monitoring.go
tests/network/bindingplugin_macvtap.go
tests/network/vmi_istio.go
tests/network/vmi_networking.go
tests/storage/migration.go
tests/swap_test.go
tests/vmi_hook_sidecar_test.go
tests/vmi_tpm_test.go
tests/vmi_vsock_test.go

Removed explicit skipping from test code. Added documentation for skipping tests based on cluster requirements using the `KUBEVIRT_E2E_SKIP` variable. Also added a decorator for skipping tests requiring two schedulable nodes, which is useful for single-node clusters.
After this PR:
Fixes #
```release-note
NONE
```

[Tests]Remove migration test skips

---

pkg/network/pod/annotations/BUILD.bazel
pkg/network/pod/annotations/generator.go
pkg/network/pod/annotations/generator_test.go
pkg/network/vmispec/BUILD.bazel
pkg/network/vmispec/hotplug.go
pkg/network/vmispec/hotplug_test.go

PR #13235 had moved the NIC hotplug / unplug logic under the network annotations generator.
- Move `CalculateInterfacesAndNetworksForMultusAnnotationUpdate` from `pkg/network/vmispec` closer to its only caller.
- Drop `CalculateInterfacesAndNetworksForMultusAnnotationUpdate`'s unit tests in favor of testing it in the context of its caller.
- Rename `CalculateInterfacesAndNetworksForMultusAnnotationUpdate`.
Fixes #
```release-note
NONE
```

net annotations-gen: Cleanup NIC hotplug / unplug logic

---

tests/monitoring/vm_monitoring.go

Instead of Updating VM runStrategy in vm_monitoring.go create vm with with the desired runStrategy.
After this PR:
Fixes #
```release-note
NONE
```

[Tests]monitoring/vm_monitoring.go:Reduces API calls during the test

---

cmd/virt-chroot/cgroup.go
pkg/virt-handler/cgroup/cgroup_test.go
pkg/virt-handler/cgroup/cgroup_v2_manager.go

crun is test driving some [changes](https://github.com/containers/crun/commit/01fa4993d6e7a7025a7326179988a2f5e72549db) it integrated recently;
it's configuring two cgroups, `*.scope` and sub cgroup called `container`
while before, the parent existed as sort of a no op
(wasn't configured, so, all devices were allowed, for example)
This results in us having to adapt, by applying the filter to the second cgroup in such cases.
crun will eventually drop the `container` sub cgroup, once it's confident of some systemd dbus API integration point.
Fixes #
Will remove this following when crun stops creating an extra cgroup …

Adapt to crun transition period where it configures 2 cgroups

---

pkg/virtctl/create/vm/BUILD.bazel
pkg/virtctl/create/vm/vm.go
pkg/virtctl/create/vm/vm_test.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/13547
virtctl create vm allows to generate VMs with disk names that will lead to rejection of the VM upon creation.
After this PR:
virtctl create vm validates disk names and prevents disk names that will lead to rejection of a VM upon creation.
Fixes https://github.com/kubevirt/kubevirt/issues/13340
```release-note
virtctl create vm validates disk names and prevents disk names that will lead to rejection of a VM upon creation.
```

[release-1.2] fix(virtctl,create): Validate names of disks

---

tests/storage/datavolume.go
tests/storage/export.go
tests/storage/hotplug.go
tests/storage/memorydump.go
tests/storage/restore.go
tests/storage/snapshot.go
tests/storage/storage.go
tests/virtiofs/datavolume.go

Runtime skips are bad. The test suite should receive instructions upfront about cluster/storage capabilities
and pick up the test set according to that. This makes it harder to hit a false negative where the test run does not identify issues but many tests were in fact skipped at runtime.
Fixes #
This still leaves 
```bash
$ (cd tests/storage; git grep "Skip(" | wc -l)
9
```
Skips in sig-storage of very specific nature, these tests would require separate PRs to tackle
```release-note
Storage tests: eliminate runtime skips …
```

storage tests: get rid of most runtime skips

---

pkg/storage/backend-storage/BUILD.bazel
pkg/storage/backend-storage/backend-storage_test.go

Less unit tests
After this PR:
Moar unit tests
Fixes #
```release-note
NONE
```

backend-storage: add a few unit tests

---

WORKSPACE
hack/bootstrap.sh
hack/rpm-deps.sh
rpm/BUILD.bazel

virtio video type was enabled only for arch64
After this PR:
virtio video type is enabled for amd64 as well
```release-note
add support for virtio video device for amd64
```

enable virtio video type for amd64

---

pkg/virtctl/create/vm/BUILD.bazel
pkg/virtctl/create/vm/vm.go
pkg/virtctl/create/vm/vm_test.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/13547
virtctl create vm allows to generate VMs with disk names that will lead to rejection of the VM upon creation.
After this PR:
virtctl create vm validates disk names and prevents disk names that will lead to rejection of a VM upon creation.
Fixes https://github.com/kubevirt/kubevirt/issues/13340
```release-note
virtctl create vm validates disk names and prevents disk names that will lead to rejection of a VM upon creation.
```

[release-1.4] fix(virtctl,create): Validate names of disks

---

pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/converter/s390x.go

Testers reported that keyboard input was not recognized when attempting to access the VM via VNC. This issue arose because no virtual keyboard was configured for the s390x architecture. This explains why console and SSH access functioned without any problems.
Signed-off-by: Nestor Acuna Blanco <nestor.acuna@ibm.com>
(cherry picked from commit a12a14cf6620f7e2d02251751de733074f389208)
Manual backport of [PR #13581](https://github.com/kubevirt/kubevirt/pull/13581)
After this PR:
Fixes #
```release-note
None …
```

[release-1.4] fix: resolve critical issue with keyboard input for s390x

---

pkg/storage/export/export/export.go
pkg/util/util.go
pkg/virt-handler/heartbeat/heartbeat.go
pkg/virt-launcher/virtwrap/converter/vcpu/BUILD.bazel
pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go
pkg/virtctl/vmexport/vmexport.go

pkg/util/util.go includes several unrelated functions and constants. This PR drops a few of them and move a few others to more appropriate location.
/kind cleanup
```release-note
NONE
```

minor reduction of the footprint of pkg/util

---

tests/vmi_configuration_test.go
tests/vmi_lifecycle_test.go

The Issue happened after this PR which removes certain skips got merged.
https://github.com/kubevirt/kubevirt/pull/13144/files#diff-1d39a0c6d5edf649055941bb990db854c3807243c8577e2250b5c093c66b3964
Before the above pr got merged. The tests will check the CPU manager support on the worker nodes and if it did not find it will skip the tests. But all these skips are now removed and replaced with labels. These tests are running and failing because the CPU Manager is not supported on s390x. So, I have removed the wgS390x label from these tests. Since it is not supported, we should not be running these tests. It's a mistake from my side for enabling them initially.  The other failures were related to software emulation tests. Previously the tests will check whether the software emulation is …

fix the e2e test failures for s390x.

---

tests/BUILD.bazel
tests/network/sriov.go
tests/utils.go
tests/vmi_cloudinit_test.go

An extremely similar function already exists in vmi_cloudinit_test, so it is used instead of CheckCloudInitMetaData there.
The two other users are in network/sriov so this function is moved into there.
After this PR:
Fixes #
```release-note
NONE
```

tests/utils: drop CheckCloudInitMetaData, 13379 clone

---

hack/lint-paths.txt
tests/numa/numa.go

Add tests/numa to paths covered by linter and fix resulting linter errors
Fixes #
```release-note
NONE
```

lint: Add tests/numa to paths covered by linter 

---

pkg/instancetype/apply/vm.go
pkg/instancetype/expand/expand.go
pkg/instancetype/instancetype.go
pkg/instancetype/preference/find/cluster_preference.go
pkg/instancetype/preference/find/preference.go
pkg/instancetype/preference/find/revision.go
pkg/instancetype/preference/find/spec.go
pkg/instancetype/revision/store.go

/cc @0xFelix 
/kind cleanup
At present we only typically require one instance type and one preference find implementation. However as both sets provide a single Find function we need to wrap these within a struct when pulling them into a larger object.
This commit avoids this by simply renaming the find preference implementation function to FindPreference allowing us to in-line interfaces directly.
This commit also in-lines interfaces requesting ApplyToVMI as this also shouldn't be wrapped with a standalone struct.
Fixes # …

instancetype: Rename find preference implementation functions

---

tests/network/probes.go

There is no reason to use a privileged pod with HostPid , root user and a fully permissive security context, in order to serve as a probe for a VM. Use  unprivileged regular pod instead.
NONE
After this PR:
Fixes #
```release-note
NONE
```

tests, network, probes: Use unprivileged pod

---

hack/lint-paths.txt
pkg/network/setup/netstat.go
pkg/network/vmispec/defaults.go
pkg/network/vmispec/hotplug_test.go
pkg/network/vmispec/infosource.go
pkg/network/vmispec/interface.go
pkg/network/vmispec/interface_test.go
staging/src/kubevirt.io/api/core/v1/types.go

- Break long lines
- Apply gofumpt
- Remove redundant newlines
- Fix typos
- Convert snake_case to camelCase
Added a case to `SetDefaultNetworkInterface` in order to also consider `v1.DeprecatedPasstInterface`.
Propose an alternative implementation for `PopInterfaceByNetwork`.
Fixes #
```release-note
None
```

pkg/network/vmispec: Add linter coverage

---

hack/lint-paths.txt

Add linter coverage for the following packages:
- pkg/network/downwardapi
- pkg/network/errors
- pkg/network/netmachinery
- pkg/network/netns
Fixes #
```release-note
NONE
```

pkg/network: Add linter coverage

---

tests/storage/export.go
tests/storage/restore.go

Manual backports of https://github.com/kubevirt/kubevirt/pull/13326 and last 2 commits from https://github.com/kubevirt/kubevirt/pull/13152 to avoid not running these in this branch.
Fixes #
```release-note
NONE
```

[release-1.4] Dequarantine storage export tests

---

pkg/storage/snapshot/restore.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
tests/storage/restore.go

This is a manual backport of https://github.com/kubevirt/kubevirt/pull/13420
Jira-ticket: https://issues.redhat.com/browse/CNV-53953
```release-note
VMRestore: allow creating vmrestore even if runstrategy is not Halted
```

[release 1.3] VMRestore: allow creating vmrestore even if runstrategy is not Halted

---

pkg/virtctl/create/vm/vm.go

Change the virtctl create vm examples to use the correct flag for adding a sysprep volume to a created VM.
virtctl create vm examples list a wrong flag for adding a sysprep volume.
After this PR:
virtctl create vm examples list the right flag for adding a sysprep volume.
Fixes #
```release-note
None
```

fix(virtctl): Use correct flag for sysprep volume in example

---

pkg/storage/snapshot/restore.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
tests/storage/restore.go

This is a manual backport of https://github.com/kubevirt/kubevirt/pull/13420
Jira-ticket: https://issues.redhat.com/browse/CNV-53954
```release-note
VMRestore: allow creating vmrestore even if runstrategy is not Halted
```

[release 1.2] VMRestore: allow creating vmrestore even if runstrategy is not Halted

---

tests/network/sriov.go

Fixes #13648  
The test `SRIOV VMI connected to single SRIOV network migration should be successful with a running VMI on the target`  flakes recently on CI.
The test fail in two different places: after migration is finished it :
1. Asserts the SR-IOV interface present in the VMI status [[1]](https://github.com/kubevirt/kubevirt/blob/302800929bd42e586c58a2e5f49f6cdc37ffb359/tests/network/sriov.go#L299-L300).
2. Asserts the SR-IOV interface present inside the guest [[2]](https://github.com/kubevirt/kubevirt/blob/302800929bd42e586c58a2e5f49f6cdc37ffb359/tests/network/sriov.go#L299-L300).
When the test fail due to (1):
The migration target virt-launcher pod fails to attach the SR-IOV device because the network-info annotation mount, using downward API, is not populated at …

tests, sriov: Stablize "SRIOV VMI connected to single SRIOV network migration should be successful with a running VMI on the target"

---

tests/storage/BUILD.bazel
tests/storage/restore.go

these tests don't really require two distinct storage providers in the environment,
it suffices to force a host assisted clone in any way.
Fixes #
```release-note
NONE
```

storage tests: avoid cross storage class runtime skip

---

hack/lint-paths.txt
tests/libkubevirt/config/featuregate.go
tests/libkubevirt/config/kvconfig.go
tests/libkubevirt/config/netbinding.go
tests/libkubevirt/kubevirt.go

After this PR:
Fixes #
```release-note
NONE
```

lint: Add tests/libkubevirt to the paths covered by the linter

---

hack/lint-paths.txt
tests/virtctl/create_vm.go
tests/virtctl/guestfs.go
tests/virtctl/imageupload.go
tests/virtctl/memorydump.go
tests/virtctl/scp.go
tests/virtctl/vnc.go

Enable the linter for cmd/virtctl and tests/virtctl and fix all found issues to make it pass.
The linter does not run on cmd/virtctl and tests/virtctl.
After this PR:
The linter runs on cmd/virtctl and tests/virtctl, all found issues are resolved.
Fixes #
```release-note
None
```

chore(lint,virtctl): Enable linter for cmd/virtctl and tests/virtctl

---

pkg/virtctl/scp/native.go
pkg/virtctl/scp/native_unsupported.go
pkg/virtctl/scp/scp.go
pkg/virtctl/scp/wrapped.go
pkg/virtctl/scp/wrapped_test.go

Update native_unsupported.go to use the new LocalArgument and RemoteArgument structs. Update places where the structs passed to pass by reference to avoid unnecessary copies.
`excludenative` builds fail because the old structs are no longer present.
After this PR:
`excludenative` builds succeed and unnecessary copies of values are avoided.
Fixes #
```release-note
None
```

fix(virtctl,scp): Update native_unsupported.go to use new structs

---

tests/network/probes.go

This test is flaky becuase tcpProbe and httpProbe are (semi) global pointers which are written
to in ipv6 tests cases by pointIpv6ProbeToSupportPod(), which adds an ipv6 Host value to the probe.
Later in ipv4 tests cases the same pointer to tcpProbe and httpProbe are passed again. The Host is
already there and it is a wrong host (whould be empty for ipv4).
The fix is to remove the global pointers and call the probe factories directly from the table entries.
In addition, in ipv4, test server is added to the VM too soon, wait till the Guest Agent is ready
then we know that the network is already setup.
Last note: this commit is minimal. This test should be refactored and written more coherently.
After this PR:
Fixes #
The following …

 tests, network, probes: Bug fix: unintentional use of global pointer

---

pkg/libvmi/vmi.go
pkg/virt-controller/watch/volume-migration/BUILD.bazel
pkg/virt-controller/watch/volume-migration/volume-migration.go
pkg/virt-controller/watch/volume-migration/volume-migration_test.go

The volume migration was rejected because the backend PVC wasn't take into account into the volumes validation
After this PR:
We can perform the volume migration on a VM using TPM
Fixes #13582
```release-note
NONE
```

volume-migration: take into account the backend PVC

---

tests/framework/matcher/existence.go
tests/framework/matcher/existence_test.go
tests/framework/matcher/helper/reflect.go

Before:
```
expected object to be gone, but it still exists: &Pod{ObjectMeta:{virt-launcher-testvmi-n28r4-hmc9s virt-launcher-testvmi-n28r4- kubevirt-test-default3  ca309a13-5d0b-44d5-83cb-74322d66588d 12215 0 2024-10-21 12:09:14 +0000 UTC 2024-10-21 12:09:52 +0000 UTC 0xc0011e0e60 map[kubevirt.io:virt-launcher kubevirt.io/created-by:7f38c5ef-4f60-479e-a814-4bed0dbc1492 kubevirt.io/nodeName:node01 vm.kubevirt.io/name:testvmi-n28r4] map[cni.projectcalico.org/podIP:10.244.196.170/32 cni.projectcalico.org/podIPs:10.244.196.170/32,fd10:244::c4a9/128 descheduler.alpha.kubernetes.io/request-evict-only: k8s.v1.cni.cncf.io/network-status:[{
"name": "k8s-pod-network",
"ips": [
"10.244.196.170",
"fd10:244::c4a9"
],
"default": true,
"dns": {}
}] kubectl.kubernetes.io/default-container:compute …
```

Improve information displayed for existance matchers

---

pkg/virtctl/console/console.go

Improve the message shown when `virtctl` gets disconnected from the VM's serial console.
```release-note
NONE
```

virtctl: Improve console disconnect message

---

automation/test.sh

The mentioned issue [1] has been resolved long time ago, and it not longer needed for automation/test.sh to distinct "no-istio" job names since k8s-1.27 lanes.
Remove "no-istio" job name check.
[1] https://github.com/kubevirt/kubevirt/issues/9158
After this PR:
Fixes #
- This change affects presubmits sig-network jobs only.
- 
```release-note
NONE
```

automation,test.sh: Remove no-istio patch

---

pkg/instancetype/instancetype.go
pkg/instancetype/preference/requirements/BUILD.bazel
pkg/instancetype/preference/requirements/checker.go
pkg/instancetype/preference/requirements/cpu.go
pkg/instancetype/preference/requirements/memory.go

/cc @0xFelix 
While usable with the current instancetypeMethods approach we need to make the core implementation stateless before switching consumers over to it in the near future.
This will allow us to mock out the implementation within unit tests as is currently heavily done by the VMAdmitter tests for example.
Fixes #
```release-note
NONE
```

instancetype: Rework requirements checker implementation

---

automation/repeated_test.sh
automation/test.sh
hack/config-default.sh
hack/functests.sh
tests/decorators/decorators.go
tests/storage/datavolume.go

introduce a label that allows opting out of volume expansion tests for storage that doesn't support PVC resize
(pretty rare at this point among CSI drivers)
Fixes #
```release-note
NONE
```

storage tests: avoid volume expansion runtime skips

---

tests/network/vmi_lifecycle.go
tests/vmi_lifecycle_test.go

We used renderPkillAllPod function to kill process in the VMI
After this PR:
We use libpod.RenderPrivilegedPod directly without the need of a wrapper function. 
- renderPkillAllPod is declared precisely the same across 2 different files, this removes the repeated code.
- reduce the amount of code across the files
- simplify the test by not using complicated functions
```release-note
NONE
```

remove renderPkillAllPod function

---

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
pkg/virt-config/deprecation/feature-gates.go
pkg/virt-config/feature-gates.go
pkg/virt-controller/watch/vm/vm.go
pkg/virt-controller/watch/vm/vm_test.go
tests/libkubevirt/config/BUILD.bazel
tests/libkubevirt/config/kvconfig.go
tests/storage/migration.go

Volume Migration was behind a feature gate
After this PR:
The VolumeUpdateStrategy and VolumeMigration features are consider stable and general available.
The `VolumeUpdateStrategy` and `VolumeMigration` feature gates were introduced in v1.3.0 by #11533.
Both feature gates have been present for 2 releases and since then, multiple issues have been reported and fixed.
With the graduation of the two feature gates, we want to indicate to KubeVirt users that the feature will remain and that the API may be considered stable for use.
```release-note
Graduation of VolumeUpdateStrategy and VolumeMigration feature gates
```

Graduation of VolumeUpdateStrategy and VolumeMigration

---

automation/test.sh

Sometimes cluster-down fails on CI, because podman failed to clean-up the cluster.
Even if the tests passed, it will fail the whole lane, causing noise.
Ignore the cluster-down retcode, because the job runs in a container that will be cleaned anyhow.
Example
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13655/pull-kubevirt-e2e-k8s-1.30-sig-network/1877309480471891968
Fixes #
```release-note
None
```

automation: Ignore cluster-down ret code

---

tests/vmi_configuration_test.go

This test has been very flaky across all of the compute lanes over the past couple of days[1] and should be quarantined
[1] https://search.ci.kubevirt.io/?search=tests%2Fvmi_configuration_test.go%3A1630&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
/cc @dhiller @xpivarc @acardace 
```release-note
NONE
```

e2e,compute: Quarantine flaky defined CPU model test

---

pkg/storage/types/dv.go
pkg/storage/types/pvc.go
pkg/virt-controller/watch/vm/vm.go
pkg/virt-controller/watch/vm/vm_test.go

When a VM requests storage beyond the limits defined by a` ResourceQuota`, it gets stuck in the `Provisioning` status with only a `VMINotExists` reason. This leaves the user unaware of how to resolve the issue:
```
status:
conditions:
- message: VMI does not exist
reason: VMINotExists
status: "False"
type: Ready
```
The fix adds an informative `FailedCreate` condition:
```
status:
conditions:
- message: VMI does not exist
reason: VMINotExists
status: "False"
type: Ready
- message: 'Error encountered while creating DataVolumes: DataVolume my-vol importer is not running due to an error: persistentvolumeclaims "my-vol" is forbidden: exceeded quota: storage, requested: requests.storage=10737418240, used: requests.storage=0, limited: requests.storage=2Gi'
reason: FailedCreate
status: "True" …
```

Set VM status indication if storage exceeds quota

---

pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/snapshot_base.go
pkg/storage/snapshot/snapshot_test.go
pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/application_test.go

When choosing the volumesnapshotclass for a volumesnapshot
so far we would have listed the volumesnapshotclasses of the
storageclass of the volume and in case there is more then 1
we would have chosen the one with the default class annotation
(if exists). In CDI we have StorageProfile object which determines
storageclass best practices and preferences. Now in case StorageProfile
exists for the SC and it has the SnapshotClass option we will choose that
volumesnapshotclass for the volume.
Added UT checks that we take storageProfile class over the default
annotation one.
Fixes: Jira-ticket: https://issues.redhat.com/browse/CNV-54866
```release-note
VMSnapshot: honor StorageProfile snapshotClass when choosing volumesnapshotclass
```

VMSnapshot: honor StorageProfile snapshotClass when choosing volumesnapshotclass

---

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go

/cc @EdDev 
Since 7620cdaa644 any causes raised by a call to ValidateFeatureGates were appended into a slice that was always overwritten before being used. As a result any VirtualMachine request using a discontinued feature was allowed to proceed through the admission webhook.
While this behaviour might be something we want to change in the future for now this change corrects this by rejecting the request using the collected causes.
Fixes #
Noticed while working on https://github.com/kubevirt/kubevirt/pull/13700 …

fix(vms-admitter): Reject requests using discontinued features

---

pkg/network/setup/netstat_test.go

Currently, `newVMIStatusIface` receives seven parameters in order to instantiate `v1.VirtualMachineInstanceNetworkInterface`.
It does not scale well when a new field is added to the struct above.
Replace all calls to `newVMIStatusIface` with structs literals and remove the function.
Fixes #
```release-note
NONE
```

virt-handler, netstat, test: inline newVMIStatusIface

---

cmd/virt-handler/virt-handler.go
pkg/util/util.go
pkg/virt-handler/device-manager/socket_device.go
pkg/virt-handler/selinux/labels.go

selinux.RelabelFiles() always relabels files with a constant UnprivilegedContainerSELinuxLabel label. It is also the single user of this constant. Let us simplify the signature of the function by defining the constant internally.
/kind cleanup
```release-note
NONE
```

virt-handler: simplify selinux.RelabelFiles

---

pkg/virt-controller/services/renderresources_test.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/vmi_configuration_test.go

We allocate 20Mi of overhead memory for virtlogd. However, virtlogd was seen using 20968Ki, which is more.
After this PR:
We allocate 25Mi of overhead memory for virtlogd.
Fixes https://issues.redhat.com/browse/CNV-54566
```release-note
NONE
```

virtlogd: bump memory overhead

---

pkg/virt-launcher/virtwrap/live-migration-source.go

It might take up to 400 milliseconds for virt-launcher to see that a migration finished.
After this PR:
The end of a migration will immediately trigger a libvirt check.
This PR mitigates (but doesn't completely fix) #13112
A unit test could be written by making `monitorSleepPeriodMS` into a global var that could be set to a really high value.
```release-note
NONE
```

migration monitor: use channel to bypass timeout on migration end

---

pkg/network/admitter/netsource_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

Currently, the unit tests of the VMI creation admitter still contain a small number of network related unit tests.
These tests test an implementation detail (the `ValidateVirtualMachineInstanceSpec` function), rather than the admitter itself.
Remove duplicate tests, or move them closer to their production code in the network validator.
Fixes #
```release-note
NONE
```

VMI create admitter: Cleanup network tests

---

tests/operator/BUILD.bazel
tests/operator/operator.go
tests/operator/resourcefiles/BUILD.bazel
tests/operator/resourcefiles/resourcefiles.go
tests/operator/resourcefiles/templates/restore-template.yaml
tests/operator/resourcefiles/templates/snapshot-template.yaml
tests/operator/resourcefiles/templates/vm-template.yaml

That way the templates are kept in a dedicated files, to ease their
maintainence, allow IDE features by file type and so on.
The operator test writes several yaml files as part of the test. The implementation was to use a very long yaml string with fmt.Sprintf, to generate the file bytes, then write them to a file. 
This scenario is exactly why we have templates in golang. We don't need to have long, multi-lines strings inside the test logic. This is hard to read and maintain. That why we should prefer golang templates over fmt.Springf of long, structured strings.
After this PR:
Now the test uses templates of the required files. That way the templates are kept in a dedicated files, to ease their
maintenance, allow IDE features by file type and so on. …

e2e: In operator.go, use go templates to generate files

---

api/api-rule-violations-known.list
api/api-rule-violations.list
go.mod
go.sum
pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/snapshot_base.go
pkg/storage/snapshot/snapshot_test.go
pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/application_test.go
staging/src/kubevirt.io/api/go.mod
staging/src/kubevirt.io/api/go.sum
staging/src/kubevirt.io/client-go/api/openapi_generated.go
staging/src/kubevirt.io/client-go/go.mod
staging/src/kubevirt.io/client-go/go.sum
vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
vendor/modules.txt

This is a  manual backport of https://github.com/kubevirt/kubevirt/pull/13711
This includes also the most minimal bump to allow the backport to this release branch.
Fixes #
Jira-ticket: https://issues.redhat.com/browse/CNV-55043
```release-note
VMSnapshot: honor StorageProfile snapshotClass when choosing volumesnapshotclass
```

[release-1.3] VMSnapshot: honor StorageProfile snapshotClass when choosing volumesnapshotclass

---

tests/compute/vm_lifecycle.go
tests/vm_state_test.go
tests/vm_test.go

Instead of Updating VM runStrategy create vm with with the desired runStrategy.
After this PR:
Fixes #
```release-note
none
```

[Tests]Reduces API calls 

---

OWNERS_ALIASES

We use Prow to auto-assign folks for a PR review. These assigned reviewers are expected to act within a reasonable time, hence be pretty active community members.
This PR removes @stu-gott and @kbidarkar from being reviewers, since they've expressed their lack of time to constantly review PRs. They are still approvers (@stu-gott is a root approver and @kbidarkar is a test approver), but won't be assigned to code-reviews anymore.
I've pinged them both offline to make sure this is OK with them, but please raise your concerns / objections if you have any.
```release-note
NONE
```

[OWNERS] Remove stu-gott and kbidarkar from being reviewers

---

docs/observability/metrics.md
pkg/monitoring/metrics/virt-handler/migrationdomainstats/migrationstats_collector.go
pkg/monitoring/metrics/virt-handler/migrationdomainstats/migrationstats_collector_test.go
pkg/virt-launcher/virtwrap/stats/types.go
pkg/virt-launcher/virtwrap/statsconv/converter.go
pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
tests/libmigration/migration.go
tests/monitoring/metrics.go

No total constant amount for the total amount of data migrate
After this PR:
kubevirt_vmi_migration_data_total_bytes - The total Guest OS data to be migrated to the new VM.
Fixes jira-ticket: https://issues.redhat.com/browse/CNV-39060
```release-note
Add kubevirt_vmi_migration_data_total_bytes metric
```

Add kubevirt_vmi_migration_data_total_bytes metric

---

pkg/libvmi/vm.go
tests/clone_test.go

This PR refactors a function createVM on tests/clone_test.go.
Reducing function complexity by:
- removing function shadowing
- refactoring to use as regular function.
Fixes #
```release-note
NONE
```

tests/clone_test: Refactor createVM function

---

pkg/storage/backend-storage/backend-storage.go
pkg/virt-controller/watch/vmi.go

This is a manual backport of [`f97415f` (#12629)](https://github.com/kubevirt/kubevirt/pull/12629/commits/f97415f55a212f955dac7fbcc6d92a9c91ac323e)
```release-note
NONE
```

[release-1.3] backend-storage: address VMI cache corruption

---

pkg/storage/export/export/BUILD.bazel
pkg/storage/export/export/export.go
pkg/storage/export/export/export_test.go
pkg/storage/export/export/pvc-source_test.go
pkg/storage/export/export/vm-source_test.go
pkg/storage/export/export/vmsnapshot-source_test.go
pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/application_test.go

Currently, `VMExportController` holds the TemplateService field of type services.TemplateService, but only uses one method out of many.
Introduce an interface to decouple the controller from the template service.
The unit tests could be refactored to use a stub in a follow-up.
Fixes #
```release-note
NONE
```

storage: Decouple export ctrl from template service

---

tests/decorators/decorators.go
tests/vmi_configuration_test.go

This test makes an assumption about tmpfs not allowing O_DIRECT,
which is not the case with newer kernels:
https://github.com/torvalds/linux/commit/e88e0d366f9cfbb810b0c8509dc5d130d5a53e02
This change indeed made it recently to centos9 stream:
https://gitlab.com/redhat/centos-stream/src/kernel/centos-stream-9/-/commit/db6591e712447ed86569aaa9c758ebdb922f5d7e
And thus blocks https://github.com/kubevirt/kubevirt/pull/13733.
Dropping the check from the functest is okay since this functionality is unit tested:
https://github.com/kubevirt/kubevirt/blob/3ec3d2423ec290bd5889a71a8c33df598644c5e7/pkg/virt-launcher/virtwrap/converter/converter_test.go#L3399
Fixes #
This …

cache mode tests: drop assertion assuming tmpfs implies no direct io

---

docs/observability/metrics.md
pkg/monitoring/metrics/virt-controller/BUILD.bazel
pkg/monitoring/metrics/virt-controller/vmistats_collector.go
pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
tests/monitoring/metrics.go

No metric with start and end timestamps
After this PR:
kubevirt_vmi_migration_start_time_seconds and kubevirt_vmi_migration_end_time_seconds metrics
Fixes #
```release-note
Add kubevirt_vmi_migration_(start|end)_time_seconds metrics
```

Add kubevirt_vmi_migration_(start|end)_time_seconds metrics

---

api/openapi-spec/swagger.json
pkg/network/setup/netstat.go
pkg/network/setup/netstat_test.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.VirtualMachineInstance.json
staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.VirtualMachineInstance.yaml
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/libnet/hotplug.go
tests/network/vmi_infosource.go

Add the `LinkState` field to `VirtualMachineInstanceNetworkInterface` to
enable reporting the interfaces' operational [1] link state.
This field could have the following values:
- empty string - link state unknown
- `up`
- `down`
Report the link state for each interface in the VMI spec. 
Since currently virt-launcher does not set the link state field - the link state report will always be `up`.
When a network binding plugin with the `link refresh` migration method is used, the link state is explicitly set.
For SR-IOV NICs - don't report the link state, since KubeVirt is not aware to all changes made to them.
Interfaces which are only defined inside the guest will not have their link state reported - as qemu guest agent does not report this information ATM [2].
[1] …

virt-handler, netstat: Report interfaces' link state

---

pkg/monitoring/metrics/virt-controller/BUILD.bazel
pkg/monitoring/metrics/virt-controller/metrics.go
pkg/monitoring/metrics/virt-controller/vmistats_collector.go
pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go
pkg/virt-controller/watch/BUILD.bazel
pkg/virt-controller/watch/application.go
tests/monitoring/metrics.go
tools/doc-generator/doc-generator.go

Sometimes the VMs do not have any explicit resource requests/limits, but those are usually defined by Instance Types/Preferences. In this situation, the resource metrics were not collecting the data. 
After this PR:
kubevirt_vm_resource_requests and kubevirt_vm_resource_limits also collect data from the instance types and preferences.
Fixes #
jira-ticket: `https://issues.redhat.com/browse/CNV-53260`
```release-note
Collect resource requests and limits from VM instance type/preference
```
/cc @sradco …

Collect resource requests and limits from VM instance type/preference

---

pkg/virt-controller/services/rendercontainer.go
pkg/virt-controller/services/rendervolumes.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-launcher/virtwrap/util/libvirt_helper.go
pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go

With some storage providers (specifically, those that use NFS to achieve shared volumes),
it's possible for migrations to fail over libvirt's shared storage checks.
Since mounting an NFS share on the same host that is exporting it is known to cause issues and is therefore
not recommended, the mount on those providers appears as ext4.
Libvirt now provides a way to allow migration in such a configuration by
providing known shared paths upfront.
Fixes #
https://issues.redhat.com/browse/CNV-41442
```release-note
Enhancement: …
```

Pass shared filesystem paths to libvirt to avoid failing migration

---

tests/vm_test.go

Re-starting VM on failure causes the VMI to be gone.
Fixes #
```release-note
NONE
```

Fix test "the VMs running in that node should be respawned"

---

pkg/instancetype/controller/vm/controller.go
pkg/instancetype/controller/vm/mock.go
pkg/virt-controller/watch/vm/BUILD.bazel
pkg/virt-controller/watch/vm/vm.go

Some simple cleanups after https://github.com/kubevirt/kubevirt/pull/13037 landed.
* Incorrect package name used by VM controller implementation
* Unused functions listed by the consuming `instancetypeHandler` interface
Fixes #
```release-note
NONE
```

instancetype: VM controller implementation cleanups

---

pkg/virt-operator/kubevirt_test.go
pkg/virt-operator/resource/apply/apps_test.go
pkg/virt-operator/resource/apply/pdb_test.go
pkg/virt-operator/resource/generate/components/daemonsets.go
pkg/virt-operator/resource/generate/components/deployments.go
pkg/virt-operator/resource/generate/csv/csv.go
pkg/virt-operator/resource/generate/install/strategy.go
tools/csv-generator/csv-generator.go
tools/manifest-templator/manifest-templator.go

function signature was misleading, the returned error wasn't actually used inside the function.
It created boilerplate when reading the code, and redundant assertions in unit tests.
After this PR:
The error was removed from the functions and its wrappers, unit tests adjusted.
```release-note
NONE
```

[virt-operator]: clean up unused returned values 

---

pkg/network/multus/annotation.go
pkg/network/multus/annotation_test.go

`NetworkAnnotationPool` and `NewAnnotationData` are implementation details - no need to export them.
Fixes #
```release-note
None
```

net, Multus: Unexport implementation details

---

tests/vmi_lifecycle_test.go

In this comment https://github.com/kubevirt/kubevirt/pull/13740#issuecomment-2600850793, I've advised to remove the global VM variable from `vmi_lifecycle_test.go`. Since my advice was not addressed, I've decided to implement it myself with this tiny PR.
With ginkgo, global variables are usually used in order to be initialized with a `BeforeEach`, but in this case the variable is not initialized and is shadowed in many cases. This PR removed the global variable.
```release-note
NONE
```

[Cleanup] Eliminate global vm variable from vmi_lifecycle_test.go

---

tests/clone_test.go
tests/framework/matcher/BUILD.bazel
tests/framework/matcher/instancetype.go
tests/instancetype/BUILD.bazel
tests/instancetype/instancetype.go
tests/instancetype/upgrade.go
tests/libinstancetype/instancetype.go
tests/storage/restore.go

/kind cleanup
This change introduces a simple composite matcher to assert that
instance type and preference revisionNames are populated. This replaces
the cumbersome libinstancetype WaitForVMInstanceTypeRevisionNames helper
that is now removed.
Fixes #
```release-note
NONE
```

matcher: Introduce and use HaveRevisionNames

---

pkg/virt-controller/watch/vm/vm.go

/cc @0xFelix 
/cc @fossedihelm
Missed during #13037 and #13771, this func is now unused and can be removed.
Using a standalone PR for this to allow #13771 to merge in the meantime as it's already approved.
Fixes #
```release-note
NONE
```

controller: Remove unused shouldExpandInstancetypeAndPreference

---

tests/vmi_lifecycle_test.go

In this comment https://github.com/kubevirt/kubevirt/pull/13746#pullrequestreview-2562417508, I've advised to remove the global err variable. Since my advice was not addressed, I've decided to implement it myself.
```release-note
NONE
```

e2e: Drop global err variable

---

pkg/storage/types/dv.go
pkg/virt-controller/watch/vm/vm.go
pkg/virt-controller/watch/vm/vm_test.go

Manual backport of #13667
When a VM requests storage beyond the limits defined by a` ResourceQuota`, it gets stuck in the `Provisioning` status with only a `VMINotExists` reason. This leaves the user unaware of how to resolve the issue:
```
status:
conditions:
- message: VMI does not exist
reason: VMINotExists
status: "False"
type: Ready
```
The fix adds an informative `FailedCreate` condition:
```
status:
conditions:
- message: VMI does not exist
reason: VMINotExists
status: "False"
type: Ready
- message: 'Error encountered while creating DataVolumes: DataVolume my-vol importer is not running due to an error: persistentvolumeclaims "my-vol" is forbidden: exceeded quota: storage, requested: requests.storage=10737418240, used: requests.storage=0, limited: requests.storage=2Gi'
reason: …
```

[release-1.4] Set VM status indication if storage exceeds quota

---

pkg/virtctl/portforward/portforward.go
pkg/virtctl/portforward/portforward_test.go
pkg/virtctl/scp/scp_test.go
pkg/virtctl/ssh/ssh_test.go

With this change VMs/VMIs with dots in their name are supported if they are used as a target in virtctl portforward, ssh or scp. These are only supported if the namespace is explicitly specified, otherwise a distinction between name and namespace is not possible.
VMs/VMIs with dots in their name are not supported in virtctl portforward, ssh and scp.
After this PR:
VMs/VMIs with dots in their name are supported in virtctl portforward, ssh and scp.
Fixes https://github.com/kubevirt/kubevirt/issues/13679
There will be a follow-up to overhaul this feature and to deprecate dots as a way to separate namespace and name. For 1.4 this should be backported …

fix(virtctl): Support VMs/VMIs with dots in their name

---

pkg/monitoring/metrics/virt-controller/BUILD.bazel
pkg/monitoring/metrics/virt-controller/metrics.go
pkg/monitoring/metrics/virt-controller/vmistats_collector.go
pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go
pkg/virt-controller/watch/application.go
tests/monitoring/metrics.go
tools/doc-generator/doc-generator.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/13535
Sometimes the VMs do not have any explicit resource requests/limits, but those are usually defined by Instance Types/Preferences. In this situation, the resource metrics were not collecting the data.
After this PR:
kubevirt_vm_resource_requests and kubevirt_vm_resource_limits also collect data from the instance types and preferences.
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-53260
Fixes #
```release-note
Collect …
```

[release-1.4] Collect resource requests and limits from VM instance type/preference

---

pkg/virtctl/ssh/native_unsupported.go

this was probably meant to be included in https://github.com/kubevirt/kubevirt/commit/c28350d323da53fc3b95913a9cd2bdf343095d53
and results in virtctl ssh not building on unsupported platforms
Fixes #
```release-note
NONE
```

virtctl ssh: nativeSSH signature change for unsupported platforms

---

tests/infrastructure/prometheus.go

This commit refactors the VMI initialization logic in the `prepareVMIForTests` function. Instead of duplicating the initialization code for different cases, an option slice is used to collect functional options.
All VMIs now start with the `WithEmptyDisk` option by default. If the `preferredNodeName` argument is provided, the `WithNodeSelectorFor` option is appended to the slice. This results in a cleaner and more maintainable initialization process.
/kind cleanup
```release-note
None
```

tests/infra/prometheus: use option slice for cleaner VMI initialization

---

pkg/virt-controller/watch/clone/clone_test.go

generateNameWithRandomSuffix dosen't cover in UT
After this PR:
generateNameWithRandomSuffix covered in UT,UT coverage improve.
Fixes #
```release-note
NONE
```

[UT]cover generateNameWithRandomSuffix in virt-controller clone/util.go 

---

cmd/virt-launcher-monitor/virt-launcher-monitor.go

- Changed signaling of virt-launcher to always log (instead of only at high verbosity) because it doesn't happen often and won’t spam the logs.
- Added a log when the virt-launcher monitor process (main compute container) exits to show when the compute container should no longer be ready.
- Added a log when the main compute process terminates so the launcher monitor knows it should stop too.
- Added a log when delaying the shutdown of the launcher monitor to give qemu time to shut down properly.
Related Flake: These logs may help in solving the following flake: [Flake Details](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13278/pull-kubevirt-e2e-k8s-1.31-sig-network/1859202840329719808).
After this PR:
Fixes #
The following tradeoffs were …

Improve virt-launcher logging

---

automation/test.sh

The periodic is broken for a while since https://github.com/kubevirt/kubevirt/pull/13109 merged;
I think we're happy if these only run in the sig-storage lane.
This looks like it was anyway the intention in one of the commits: https://github.com/kubevirt/kubevirt/pull/13109/commits/26889969d0eb688fdb96a5dde83b3cfc24c1e330
Another option is introducing logic to filter based on the existence of block storage which I think we can avoid for now.
Fixes #
```release-note
NONE
```

Fix compute periodic by excluding some sig-storage tests

---

pkg/storage/memorydump/BUILD.bazel
pkg/storage/memorydump/memorydump.go
pkg/storage/memorydump/memorydump_suite_test.go
pkg/storage/memorydump/memorydump_test.go
pkg/virt-controller/watch/vm/BUILD.bazel
pkg/virt-controller/watch/vm/vm.go
pkg/virt-controller/watch/vm/vm_test.go

We want to remove storage logic from other places as much as possible to not overload general vm code and to be able to own storage code better.
Also moved and improved memory dump UT.
And change Update to Patch, since we can so why not.
Before this PR: memory dump code in watch/vm
After this PR: memory dump code in pkg/storage/memorydump
Fixes #
/kind cleanup
```release-note
NONE
```

Memory Dump: move memory dump code to pkg/storage

---

pkg/virt-controller/services/virtiofs.go
pkg/virt-handler/BUILD.bazel
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go
tests/libstorage/pvc.go
tests/migration/BUILD.bazel
tests/migration/migration.go

Recently, the infrastructure container were updated to Centos 9.6. That version includes virtiofsd 1.13.0, which support live migration (also the required qemu and libvirt versions).
This PR enables the live migration of a VMI using a volume shared using virtiofs, for instance:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
...
spec:
domain:
devices:
filesystems:
- name: foo
virtiofs: {}
volumes:
...
- name: foo
serviceAccount:
serviceAccountName: default
```
```release-note
Live migration support for VMIs with (virtiofs) filesystem devices
```

Enable VMI live migration using virtiofs volumes

---

pkg/virt-config/feature-gates.go
pkg/virt-config/featuregate/active.go
pkg/virt-config/featuregate/inactive.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/decorators/decorators.go
tests/testsuite/kubevirtresource.go
tests/vmi_configuration_test.go

First introduced by #10447 way back in 2023 the AutoResourceLimits feature gate is now deprecated with the feature state graduated to GA and as such always enabled.
After this PR:
Fixes #
```release-note
The `AutoResourceLimits` feature gate is now deprecated with the feature state graduated to `GA` and thus enabled by default
```

config: Graduate AutoResourceLimits featuregate to GA

---

pkg/virt-controller/services/renderresources_test.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/vmi_configuration_test.go

This is a cherry-pick of 10b0d9b1812c559f1da96fa33dbeec8890771fcb
There have been a number of test failures in the v1.4 compute lanes due to virtqemud using more RAM than expected[1][2]
This has already been increased to 40Mi on the main branch[3] - increase it to 40Mi for release-1.4
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13804/pull-kubevirt-e2e-k8s-1.29-sig-compute-1.4/1884286608010645504
[2] https://search.ci.kubevirt.io/?search=the+virtqemud+process+is+taking+too+much+RAM&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=1.4&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
[3] https://github.com/kubevirt/kubevirt/blob/668570a602d8bed9fbdb2e58bfca9a502fd028f6/pkg/virt-controller/services/template.go#L117
Fixes #
The following …

[release-1.4]virt-controller: Increase virtqemud memory overhead to 40Mi

---

pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go

One unintuitive but intentional behavior in Ginkgo is that all `DeferCleanup()` blocks are executed after all `AfterEach()` blocks. This causes a race in this test case, because `AfterEach()` removes a file that is being watched by a goroutine inside `HandleQemuAgentAccessCredentials()`. If the goroutine is faster, it will call `LookupDomainByName()` second time and panic.
Using `defer` instead of `DeferCleanup()` should fix the race.
For context, that this is intentional behavior in ginkgo: https://github.com/onsi/ginkgo/issues/1360#issuecomment-1949181004
```release-note
None
```

access-credentials: test: Fix race in unit test

---

pkg/network/setup/BUILD.bazel
pkg/network/setup/filters.go
pkg/network/setup/filters_test.go
pkg/virt-handler/BUILD.bazel
pkg/virt-handler/vm.go

Currently, the virt-handler's VM controller performs network setup based on some filtering logic:
1. On VM's initial setup.
2. When the VM is running - in order to perform NIC hotplug/unplug.
3. When a migration target pod is set up.
Extracting the logic above has several advantages:
1. The VM controller's code is shorter and more readable.
2. There is less SIG-specific code in a core component. 
3. This logic is specific to SIG-network and should be owned by it.
Fixes #
```release-note
NONE
```

virt-handler, vm ctrl: Extract networks filtering logic

---

pkg/virt-launcher/virtwrap/manager_test.go
tests/migration/paused.go

This PR is a follow up to a recently discovered quarantined migration test flake, described in https://github.com/kubevirt/kubevirt/pull/13462
It replaced the flaky e2e test with a unit test as the functional test depends on the size of the workloads and various node related factors. 
Factors that were not evident during the submission of the original test.
Fixes #
```release-note
NONE
```

Replace flaky e2e migration cancelation test with a paused workload with a unit test

---

pkg/util/util.go
pkg/virt-controller/services/renderresources.go
pkg/virt-controller/services/template.go
pkg/virt-controller/watch/topology/BUILD.bazel
pkg/virt-controller/watch/topology/tsc.go
pkg/virt-launcher/virtwrap/converter/converter.go

Move a few functions out of pkg/util in order to reduce coupling between unrelated parts of the code.
/kind cleanup
```release-note
NONE
```

pkg/util: move a few functions next to their users

---

pkg/virt-handler/cache/cache_test.go
pkg/virt-handler/cmd-client/client.go
pkg/virt-handler/cmd-client/client_test.go
pkg/virt-handler/device-manager/usb_device_test.go
pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/converter_test.go

remove redundant types in composite literals, redundant type conversions
/kind cleanup
```release-note
NONE
```

code clean: remove redundant types in composite literals, redundant type conversions

---

pkg/libdv/dv.go
pkg/virt-controller/watch/vm/vm.go
pkg/virt-controller/watch/vm/vm_test.go
pkg/virt-controller/watch/volume-migration/BUILD.bazel
pkg/virt-controller/watch/volume-migration/volume-migration.go
pkg/virt-controller/watch/volume-migration/volume-migration_test.go
tests/storage/migration.go

Volume migration with destination datavolumes which their storage class isn't a CSI could bring to races and fail. Storageclasses not supporting CSI don't use populators. For this reason, CDI uses a legacy import by running the importer as an additional pod.
However, this doesn't properly coordinate with the target virt-launcher pod created during the migration. In this case, the cdi importer pod fails because the PVC results already in use, and the DV never goes in succeeded state.
We decided to avoid this situation by refusing to migrate when the destination DV is using a no-csi class. CSI and volume populators are the modern way to handle storage in Kubernetes, therefore if users want still to use legacy storage classes, they need to use PVCs and cannot use datavolumes.
A storageclass …

vol-mig: invalidate destination DVs with no csi storageclass

---

cmd/virt-handler/virt-handler.go

Following PR #13626, this function is no longer used.
Fixes #
```release-note
NONE
```

virt-handler: Remove unused copy function

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-launcher/virtwrap/converter/BUILD.bazel
pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/converter_test.go

At the moment, for ACPI Slic table, we have defined that only Secrets should be used. Add a check to validate it.
We would not properly error if User tried a unsupported Volume type with SLIC table API
After this PR:
We only allow Secrets to be used. Checks added on webhooks and converter.
Related to: [CNV-44417](https://issues.redhat.com/browse/CNV-44417)
```release-note
Better handle unsupported volume type with Slic table
```

Check that only Secret is supported for SLIC table

---

tests/instancetype/instancetype.go
tests/migration/migration.go
tests/operator/operator.go

Changes runtime skips to failures when CDI is missing. Skips can hide errors, so using failures ensures better visibility. 
Fixes #
```release-note
NONE
```

Replace skips with failures for missing CDI

---

tests/vmi_lifecycle_test.go

Following PR #13670, this function is no longer used.
Fixes #
```release-note
NONE
```

e2e, vmi_lifecycle: Remove unused addBootOrderToDisk function

---

tests/usbredir_test.go

This reverts commit 7a28a3390dec09b15815be22be395161ea728dc9.
Flaky tests should all have been addressed by
https://github.com/kubevirt/kubevirt/pull/12977
```release-note
NONE
```

revert: Quarantine of e2e usbredir tests

---

hack/lint-paths.txt
pkg/network/istio/ports.go
pkg/network/istio/proxy.go

Cover the `pkg/network/istio` package by the linter.
[1] https://pkg.go.dev/strings#EqualFold
Fixes #
```release-note
NONE
```

net, istio: Add linter coverage

---

tests/libstorage/OWNERS

After this PR:
Fixes #
```release-note
NONE
```

 tests/libstorage: Add owners file

---

docs/observability/metrics.md
pkg/monitoring/metrics/virt-controller/vmistats_collector.go
pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go
tests/monitoring/metrics.go

Add 2 metrics that reports the vNIC information for vm's and vmi's. 
the metrics labels includes: 
**- name:** the vm/i name
**- namespace:** the vm/i namespace 
**- vnic_name:** the interface name 
**- binding_type:** can be core/plugin
**- network:** if using Pod it will be "pod networking", if using Multus it will be the Multus.NetworkName.  
**- binding_name:** can be masquerade/bridge/sriov/Binding.Name
see metrics:
notes: 
- The vmi metric will show values for running/pending/starting vmi's but not for stopped vmi's.
- The vm metric will show values for both running/starting/stopped vms, but only for vms that the network and interface defined on their spec.
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-51529 …

Add kubevirt_vm/i_vnic_info metrics

---

pkg/network/controllers/hotplug_test.go
pkg/network/controllers/vm_test.go

Currently, there are two unit test files testing the NIC hotplug / hotunplug logic:
- pkg/network/controllers/vm_test.go
- pkg/network/controllers/hotplug_test.go
Move tests testing lower level logic from `hotplug_test.go` to the higher level `vm_test.go` file that tests the network VM controller as a whole.
The end goal is have all logic tested via the network VM controller.
In order to limit this PR's scope, not all tests were moved and a follow-up will be required to complete the work.
Fixes #
```release-note
NONE
```

net, controllers, VM: Refactor NIC hotplug / hotunplug tests

---

tests/storage/snapshot.go

Some of the alleged non-guest-agent tests do in fact run with guest-agent-enabled
images for a while now, at least since:
https://github.com/kubevirt/kubevirt/pull/6108/commits/36aba3ec0d7feecc379bd157ca3e424c14bf2e48#diff-6744b3e54011de85527b1a5b5deb98fbc05a60aa7576c644315d5dc25ebcb74b
This results in flakes and extensive resource usage where alpine does just fine.
Fixes #
Ultimately we should refactor these to issue guest agent commands through `virsh`
and ensure the `{"execute":"guest-fsfreeze-status"}` returns `frozen`.
Anything beyond that is arguably out of kubevirt scope (so existence of an actual fsfreeze hook, for example). …

snapshot tests: use alpine instead of fedora for non-guest-agent tests

---

tests/infrastructure/cluster-profiler.go

This flaky test is causing significant impact to the sig-compute-serial lane[1] which is one of the more expensive and long running lanes.
Quarantine the test to allow time for investigation.
[1] https://search.ci.kubevirt.io/?search=tests%2Finfrastructure%2Fcluster-profiler.go%3A61&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
[2] https://github.com/kubevirt/kubevirt/issues/13865
Fixes #
/cc @fossedihelm @xpivarc 
```release-note
NONE
```

e2e,compute: Quarantine flaky subresource access test

---

pkg/virt-operator/resource/generate/components/daemonsets.go

The pr-helper couldn't see newly added devices and it was required to restart the entire virt-handler pod
After this PR:
Mount the `/dev` directory in the pr-helper container 
Fixes https://issues.redhat.com/browse/CNV-55705
Newly created devices under /dev must be monitored and accessible by the qemu-pr-helper. The /dev directory is created on devtmpfs by default for containers, and it does not receive additional devices.
Mount it in the pr-helper container after adding the host's /dev path. Please be aware that the qemu-pr-helper daemon is looking for the device under '/dev', but the pr-helper is a privileged container and may already have access to the devices through /proc/1/root/dev.
```release-note
NONE
```

Make dev directory dynamic for the pr-helper container

---

pkg/virt-launcher/virtwrap/live-migration-source.go

In the case, the destination image is smaller then the source volume, then the volume migration cannot be performed. In this case, the live migration fails with this obscure error message:
```
Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=1, Domain=10, message='internal error: process exited while connecting to monitor: 2024-11-20T09:00:01.341094Z qemu-system-x86_64: -blockdev {\"driver\":\"raw\",\"file\":\"libvirt-2-storage\",\"offset\":0,\"size\" :1073741824,\"node-name\":\"libvirt-2-slice-sto\",\"read-only\":false,\"discard\" :\"unmap\",\"cache\":{\"direct\":true,\"no-flush\":false}}: The sum of offset (0) and size (0) has to be smaller or equal to the  actual size of the containing file  (1006632960)')
```
This change makes the error …

vol-mig: improve error report when the destination is too small

---

tests/storage/snapshot.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/13874
Fixes #
```release-note
NONE
```

[release-1.4] snapshot tests: use alpine instead of fedora for non-guest-agent tests

---

pkg/storage/snapshot/restore.go
pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/snapshot_test.go
pkg/storage/snapshot/source.go
pkg/storage/snapshot/util.go
tests/libstorage/virtualmachinesnapshot.go
tests/storage/snapshot.go

Before this PR: When doing a vmsnapshot with unbound volumes the volumes will just be skipped, and so possibly getting a vmsnapshot without any storage.
After this PR: When doing a snapshot the snapshot will not start until all the volumes exist and are bound. In case of WFFC the user will be required to start the VM.
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-55923
```release-note
BugFix: VMSnapshot: wait for volumes to be bound instead of skip
```

VMSnapshot: wait for volumes to be bound instead of skip

---

api/openapi-spec/swagger.json
pkg/network/admitter/BUILD.bazel
pkg/network/admitter/admit.go
pkg/network/admitter/admit_test.go
pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/converter/network.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/schema.go
staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/network/BUILD.bazel
tests/network/link_state.go

Iniital part of  of [Enhancement: Adding Link State Management for vNICs](https://github.com/kubevirt/enhancements/pull/2) Implementation, to support setting an interface link state to `up` or `down`, in addition to the existing `absent` value.
Link management in runtime and associated interface hot-plug functionality follows in https://github.com/kubevirt/kubevirt/pull/13744
The reporting part of this enhancement is implemented in https://github.com/kubevirt/kubevirt/pull/13708.
VM network interface link state could not be changed via kubevirt API.
After this PR:
Link state can be changed through API with immediate effect.
Fixes #
[Enhancement: …

api, net: Manage Link State for vNICs

---

tests/framework/checks/skips.go

Following [1], this function is unused.
[1] https://github.com/kubevirt/kubevirt/pull/12540
Fixes #
```release-note
NONE
```

e2e, skips: Remove unused SkipIfNoRhelImage

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter_test.go

The VMClone admitter webhook was supposed to reject VMClone creation if the source used backend PVC (https://github.com/kubevirt/kubevirt/pull/13207)
Currently, the webhook only rejects this operation when the source of the clone is a VM. This Pull Request updates the webhook to reject it in all cases.
Fixes # https://issues.redhat.com/browse/CNV-55940
```release-note
Reject VM clone when source uses backend storage PVC
```

Reject VMClone creation when source uses backend storage PVC

---

pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go

Document descheduler integration in order to express that we don't use random string and this is assumption.
While we have unit test this should be more straightforward for readers 
Fixes #
```release-note
NONE
```

Document descheduler integration

---

pkg/util/cluster/BUILD.bazel
pkg/util/cluster/cluster.go
tests/framework/checks/skips.go
tests/network/vmi_multus.go
tests/network/vmi_networking.go

Users who execute these tests on OpenShift could skip them by name.
Fixes #
```release-note
NONE
```

net, e2e: Remove deprecated SkipIfOpenShift functions

---

pkg/storage/admitters/vmsnapshot.go
pkg/storage/admitters/vmsnapshot_test.go
tests/storage/snapshot.go

Before this PR: Webhook rejects creation of vmsnapshot if source doesnt exist yet.
After this PR: Snapshot is allowed to be created and the controller updates the snapshot conditions that the source doesnt exist.
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-41560
```release-note
VMSnapshot: allow creating snapshot when source doesnt exist yet
```

VMSnapshot: allow creating snapshot when source doesnt exist yet

---

cmd/virt-launcher/virt-launcher.go
pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go
tools/cache/BUILD.bazel
tools/cache/time-defined-cache.go
tools/cache/time-defined-cache_test.go

Adds the `KeepValueUpdated()` method to time-defined cache.
`KeepValueUpdated()` will keep the value updated in the cache by calling the re-calculation function every `minRefreshDuration` until the stopChannel is closed. This helps to ensure the cache is constantly updated, even if `Get()` calls aren't executed.
This change allows decoupling when the cache gets updated from when Get() calls are being executed. One of the reasons it's important is that this allows making relatively complex calculations as part of `GetDomainStats()` without blocking the caller. The cache would take care of updating the values on its own pace while the Get() calls will immediately return a value with no additional overhead. As an example, this is important for dirty-rate calculation which takes about 1 …

Add the KeepValueUpdated() method to time-defined cache

---

tests/BUILD.bazel
tests/security_features_test.go

Following [1], this function is no longer used.
[1] https://github.com/kubevirt/kubevirt/pull/11266
Fixes #
```release-note
NONE
```

e2e, security features: Remove runOnAllSchedulableNodes

---

docs/backup-restore-integration.md

Kubevirt's Velero plugin now includes the backend storage PVC in its VM object graph, so it makes sense to include documentation about this PVC and how to identify it in the backup and restore docs.
```release-note
NONE
```

Update backup and restore docs with info about backend PVC

---

tests/decorators/decorators.go

Several linter warning wrt godoc errors were showing up.
After this PR:
Linter warnings fixed
/kind cleanup
/wg code-quality
Fixes #
```release-note
NONE
```

godoc: fixes for decorators.go

---

pkg/virtctl/portforward/portforward.go
pkg/virtctl/scp/scp.go
pkg/virtctl/ssh/native.go
pkg/virtctl/ssh/ssh.go
tests/virtctl/scp.go
tests/virtctl/ssh.go

Deprecate type being optional in the syntax of virtctl port-forward/ssh/scp in preparation of making it mandatory in the future.
`type` in in the syntax of virtctl port-forward/ssh/scp is optional.
After this PR:
`type` in in the syntax of virtctl port-forward/ssh/scp is STILL optional but a deprecation warning is emitted.
Fixes #
```release-note
`type` being optional in the syntax of virtctl port-forward/ssh/scp is now deprecated.
```

feat(virtctl): Deprecate optional type in port-forward/ssh/scp

---

pkg/controller/virtinformers.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter_test.go
pkg/virt-controller/watch/clone/BUILD.bazel
pkg/virt-controller/watch/clone/clone.go
pkg/virt-controller/watch/clone/clone_base.go
pkg/virt-controller/watch/clone/clone_test.go
pkg/virt-controller/watch/clone/util.go
tests/BUILD.bazel
tests/clone_test.go

VMClone request is rejected in case VM source doesnt exist.
VMClone request is rejected in case a VM has a volume that its volumesnapshotstatus is `disabled`
After this PR:
In case of VM source doesnt exists VMClone will be created. We will get an event and the VMClone conditions will be updated accordingly, once VM is created the VMClone continues.
In case of a volume that its volumesnapshotstatus is `disabled` we will get an event and the VMClone conditions will be updated accordingly, once the status will change to `enabled` the clone will continue.
Fixes # jira-ticket: https://issues.redhat.com/browse/CNV-41557
This change is in order to make our product more aligned with k8s “eventual consistency” model.
We shouldn't reject requests when the rejection reason is able …

VMClone: Remove webhook that checks VM Source

---

pkg/virtctl/ssh/native.go
pkg/virtctl/ssh/native_unsupported.go
pkg/virtctl/ssh/ssh.go
tests/virtctl/create_vm.go
tests/virtctl/scp.go
tests/virtctl/ssh.go

This deprecates the --local-ssh flag, which previously defaulted to
false, meaning that the native SSH client built into virtctl was used by
default in virtctl ssh. The flag now defaults to true.
The reason for the deprecation of the flag is that the native SSH client
in virtctl has some short comings and long standing issues compared to a
real OpenSSH client, which are not trivial to address.
Instead of trying to fix all of these issues, it was decided to
deprecate the native client in order to discourage the use of it.
The `--local-ssh` flag in `virtctl ssh` defaults to `false`. By default the builtin SSH client in `virtctl ssh` is used.
After this PR:
The `--local-ssh` flag in `virtctl ssh` defaults to `true`. By default the local SSH client on the machine running …

feat(virtctl): Deprecate --local-ssh flag and use local ssh by default

---

pkg/monitoring/metrics/virt-controller/vmistats_collector.go
pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go

Non-cluster instance types and preferences were not being created in the `kubevirt_vm_info` and `kubevirt_vmi_info` because they required a namespaced key to be used when doing a lookup in the store.
After this PR:
Lookup is being made with a namespaced key and metrics labels are being now correctly set
/cc @lyarwood 
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-54195
```release-note
Fetch non-cluster instance type and preferences with namespace key
```

Fetch non-cluster instance type and preferences with namespace key

---

api/openapi-spec/swagger.json
pkg/util/openapi/openapi.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go

If you would try to apply vm-cirros with memory.guest using pure integer, you would get rejected by the vm-mutator with this error msg:
`spec.template.spec.domain.memory.guest in body must be of type string: "number"`
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
name: vm-cirros
spec:
template:
spec:
domain:
memory:
guest: 1234567
```
After this PR:
* Updated the `resource.Quanitiy` type in the openapi schema to support both strings and integer types.
* The memory.guest field can be populated with integers just fine.
```
https://issues.redhat.com/browse/CNV-36293
```
```release-note
None
```

open-api: update resource.Quantity type to support both string and integer

---

api/openapi-spec/swagger.json
manifests/generated/kv-resource.yaml
pkg/monitoring/profiler/profile-manager_test.go
pkg/virt-api/rest/profiler_test.go
pkg/virt-api/webhooks/fuzz/fuzz_test.go
pkg/virt-config/configuration_test.go
pkg/virt-config/feature-gates.go
pkg/virt-config/featuregate/active.go
pkg/virt-config/featuregate/inactive.go
pkg/virt-config/virt-config.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.KubeVirt.json
staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.KubeVirt.yaml
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/infrastructure/cluster-profiler.go

The ClusterProfiler feature had to be enabled using a feature gate
After this PR:
The ClusterProfiler feature gate is GA and to enable the functionality there is now a new configuration field
in the KubeVirt CR in the DeveloperConfiguration section.
Fixes #
```release-note
GA ClusterProfiler FG and add a config to enable it
```

GA ClusterProfiler FG and add a config to enable it

---

pkg/ignition/BUILD.bazel
pkg/ignition/ignition_test.go

Currently, we are creating and editing resources in unit tests changing directly the vm and vmi resources.
After this PR:
promoted the libvmi package under /pkg, we can use the utility functions to create resources. This increases readability and promotes a standard way to create vm and vmi. Thus updated the `pkg/ignition/ignition_test.go` accordingly
Partially address #12059
Links to places where the discussion took place: #12059
```release-note
NONE
```

Address issue: #12059 update ignition_test.go libvm

---

pkg/virt-operator/resource/generate/components/validatingadmissionpolicy.go
tests/validatingadmissionpolicy/BUILD.bazel
tests/validatingadmissionpolicy/noderestrictions.go

`kubevirt-node-restriction-policy` Validating Admission Policy was always returning the default failure reason (`Invalid`) when the virt-handler SA was used to try to amend some aspect of node object that it should not be able to edit.
The received object are likely valid so `Invalid` could be misleading.
After this PR:
Since we are for sure failing due to a lack of permissions, `Forbidden` reasons (`the server can be reached and understood the request, but refuses to take any further action. It is the result of the server being configured to deny access for some reason to the requested resource by the client`) are more appropriate.
None
None
It's only for the sake of consistency, I don't expect …

VAP: return a consistent reason for failures

---

pkg/virtctl/portforward/portforward.go
pkg/virtctl/scp/scp_test.go
tests/virtctl/create_vm.go

These are cleanups discovered after https://github.com/kubevirt/kubevirt/pull/13918 was already merged.
Discourage the use of virtctl with tthe SSH/SCP ProxyCommand to avoid
situations where syntaxes might break for users. The preferred way is to
let virtctl generate the ProxyCommand and to wrap SSH/SCP clients.
Also, clean up tests of virtctl by adding the type in calls to
ParseTarget and to virtctl itself where it is missing.
Fixes #
```release-note
None
```

cleanup(virtctl): Follow ups to deprecation of optional type in virtctl port-forward

---

automation/test.sh

The `cnao` lanes were dropped in [1].
[1] https://github.com/kubevirt/project-infra/pull/1081
Fixes #
```release-note
NONE
```

test.sh: Remove leftover reference to cnao lanes

---

tests/network/vmi_multus.go

- Refactor ptp ping test to better use libvmi.
- Remove a negative admission test which is covered by a unit test.
Fixes #
```release-note
NONE
```

net, e2e, vmi_multus: Minor cleanup

---

pkg/virt-operator/webhooks/BUILD.bazel
pkg/virt-operator/webhooks/webhook_test.go

virt-operator webhook test file is using the
mockinterfaces for kv, vmi, vm, rs resources and 
a lot of global variables that can be more scoped.
Switch using fakeclient for all the resources and 
renamed and sort imports following conventions.
Fixes #
```release-note
NONE
```

virt-operator webhook test: Use fakeclient and cleanups

---

tests/clone_test.go

This PR moves Move startClone,StopClone closure functions inline, using the vm API Start(),Stop()
Fixes #
```release-note
NONE
```

e2e/clone_test: Move start/StopClone inline

---

tests/decorators/decorators.go
tests/storage/restore.go

We have tests that assume provisioner-specific behavior such as pvc size round-up, which causes failures in clusters using valid storage classes with other provisioners. This PR adds a  `RequiresSizeRoundUp` decorator to allow skipping tests that require this behavior.
Fixes #
```release-note
NONE
```

Add RequiresSizeRoundUp decorator

---

tests/storage/export.go

these get passed to sprintf so syntax was off, making it harder to debug failures
Fixes #
```release-note
NONE
```

export tests: correct stdout/err printing syntax

---

docs/metrics.md
pkg/monitoring/metrics/virt-controller/BUILD.bazel
pkg/monitoring/metrics/virt-controller/vmistats_collector.go
pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
tests/monitoring/metrics.go

Manual cherry pick of https://github.com/kubevirt/kubevirt/pull/13428
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-56403
jira-ticket: https://issues.redhat.com/browse/CNV-56007
```release-note
Add kubevirt_vmi_migration_(start|end)_time_seconds metrics
```

[release-1.3] Add kubevirt_vmi_migration_(start|end)_time_seconds metrics

---

tests/clone_test.go
tests/decorators/decorators.go
tests/storage/hotplug.go
tests/virtctl/imageupload.go

Added and used this decorator in tests that require WFFC. Replaced Skip with Fail.
Lanes without WFFC SC can use it to filter the tests.
```release-note
NONE
```

Storage: add requiresWFFCStorageClass decorator and change skips to fail

---

tests/clone_test.go

This PR moves createSnapshot to be inline.
Fixes #
```release-note
```

tests/clone_tests: Move createSnapshot to be inline

---

tests/decorators/decorators.go
tests/storage/restore.go

Manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/13990.
```release-note
NONE
```

[release-1.4] Add RequiresSizeRoundUp decorator

---

tests/clone_test.go

This PR moves simple closure function to funcs.
Fixes #
```release-note
```

tests/clone_tests: Move simple closures to funcs

---

pkg/virt-controller/services/rendercontainer.go
pkg/virt-controller/services/rendercontainer_test.go

* There's an unidentified "double reconcile" and/or kind of race condition that is wrapping the exec conmmand twice when processing a VMI.
* Wrapping a `virt-probe` inside another `virt-probe` command definitely breaks the VMI and then requires a manual operation to fix it.
After this PR:
* wrapping function now verfiies that VMI probe exec command is not already wrapped before wrapping it.
**Fixes #11755**
* _none_
```release-note
NONE
```

fix(virt-controller): prevent exec probes to be wrapped twice

---

tests/network/vmi_istio.go

CI runs very old version of Istio that does not support new k8s features and block development that utilize such features (e.g.: restart policy for init containers).
There is an effort to upgrade Istio version CI use, but it fails due to because some Istio+passt tests failing [[1]](https://github.com/kubevirt/kubevirtci/pull/1331#issuecomment-2636048471)
Please see [[2]](https://github.com/kubevirt/kubevirt/issues/13927) for more details about the root cause.
Quarantine istio+passt failing tests to unblock istio upgrade and development.
Tracking issue for istio upgrade [[3]](https://github.com/kubevirt/kubevirt/issues/13832)
[1] https://github.com/kubevirt/kubevirtci/pull/1331#issuecomment-2636048471
[2] https://github.com/kubevirt/kubevirt/issues/13927 …

tests,network: quarantine istio+passt tests

---

pkg/virt-handler/virt-chroot/virt-chroot.go
tests/reporter/kubernetes.go

What this PR does / why we need it:
We have EVE open-source project, https://github.com/lf-edge/eve, needs
to run kubernetes(k3s for example) inside a container. Kubevirt is part
of that setup. Although this patch should be needed for running k8s/kubevirt
inside a container in general.
This patch addresses this issue:
-- launch a VM in kubevirt, can not mount the disk
mount target invalid: failed opening kubelet for path root: /, relative: /var/lib/kubelet/pods/91a750fc-c0e5-4ea4-923a-7e86e831f599/volumes/kubernetes.io~empty-dir/container-disks/disk_0.img: no such file or directory
( another issue  'error: failed to get emulator capabilities, and
error: internal error: Failed to start QEMU binary /usr/libexec/qemu-kvm for probing:'
was resolved by the system to add read/write capabilities …

allow kubevirt VM work under container

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-preset-admitter_test.go

Before this PR: Unit tests in `pkg/virt-api/webhooks/validating-webhook/admitters/vmi-preset-admitter_test.go` use the `NewMinimalVMI` function to create a VMI object, and then modify the data members of the VMI object to customize it.
After this PR: We will use the `libvmi.New` function to create a VMI object, and while doing so use its Builder design pattern to customize the VMI object.
Partially address: #12059 
- The following tradeoffs were made:
- Direct manipulation of resources was replaced with libvmi functions, which enhances readability and maintainability.
Links to places where the discussion took place: Issue …

Refactor unit tests to use libvmi for resource creation in vmi-preset-admitter_test.go

---

tests/flags/flags.go
tests/libmigration/migration.go
tests/migration/migration.go

This PR is a Manual backport of #13841
Since there was a conflict in tests/flags.go:103, the automatic cherry-pick failed.
/assign
/hold first #14034
/cherry-pick release-1.3
/cherry-pick release-1.2
```release-note
None
```

[release-1.4] tests/migration: manual backport of #13841

---

pkg/virtctl/console/console.go

This improves the help message for exiting the console by providing key combinations that should work on all common keyboard layouts. E.g. on nordic keyboard layouts it is not possible to use Ctrl + ], while Ctrl + 5 does work.
Help message only mentions `^]` / `Ctrl+]`
After this PR:
Help message mentions `^]` / `Ctrl+]` and `Ctrl+5`
Fixes #
```release-note
None
```

fix(virtctl,console): Improve exit console help message

---

pkg/virt-launcher/virtwrap/api/schema.go

device.
To support hot-unplugging of interfaces on s390x architecture, added CSSID, SSID, and DevNo fields to the Address struct. These fields are necessary for proper interface management on s390x systems for ccw device type.
These fields are implicitly used when the domain is read from libvirt and unmarshaled, Also these fields' values are only used for the NIC hotunplug flow in s390x.
This PR addresses the following issue/error:
After attempting to hot-unplug a secondary network interface (dyniface1) from a VirtualMachineInstance (VMI) the VMI enters a state where it fails to sync, showing the error:
`LibvirtError(Code=99, Domain=20, Message='device not found: no device found at address '0.0.0000' matching MAC address '02:6c:5b:00:00:06' and alias 'ua-dyniface1')`
Libvirt couldn't …

Add cssid, ssid and devno fields to Address struct for s390-ccw-virtio

---

pkg/virt-controller/watch/vm/BUILD.bazel
pkg/virt-controller/watch/vm/vm_test.go
pkg/virt-operator/resource/apply/apps_test.go
pkg/virt-operator/resource/apply/scc_test.go
pkg/virt-operator/resource/apply/ssc.go

used hardcoded patch operations
After this PR:
removed the unconvectional method of using patch and replaced it with the patchset
Relates to issue https://github.com/kubevirt/kubevirt/issues/13947
A couple of leftover in the code which required refactoring to use patchset
```release-note
NONE
```

fix: replace to patchset

---

tests/operator/BUILD.bazel
tests/operator/operator.go

Operator tests panic if an error occurs
After this PR:
Operator tests expect errors not to occur
Fixes #
```release-note
None
```

cleanup(tests,operator): Keep calm and don't panic

---

pkg/virt-config/featuregate/active.go

/cc @0xFelix 
/cherry-pick release-1.5
This graduation from Alpha to Beta was missed by the initial v1.5.0 release but should happen and be backported to allow GA and removal of the FG with v1.6.0.
Fixes #
```release-note
NONE
```

featuregates: Graduate InstancetypeReferencePolicy to Beta

---

cmd/virt-handler/virt-handler.go
pkg/virt-handler/node-labeller/BUILD.bazel
pkg/virt-handler/node-labeller/amd64.go
pkg/virt-handler/node-labeller/arch_labeller.go
pkg/virt-handler/node-labeller/arch_labeller_test.go
pkg/virt-handler/node-labeller/arm64.go
pkg/virt-handler/node-labeller/cpu_plugin.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/node-labeller/node_labeller.go
pkg/virt-handler/node-labeller/node_labeller_test.go
pkg/virt-handler/node-labeller/s390x.go
pkg/virt-launcher/virtwrap/converter/arch/converter_test.go

Use arch specific files for arch specific configuration.
arch specific code is mixed together with common code in node-labeller.
After this PR:
arch specific code can be called over a generic interface.
Fixes #
Split of from https://github.com/kubevirt/kubevirt/pull/13852
```release-note
NONE
```

virt-handler/node-labeller: Move arch specific content into separate files

---

pkg/virtctl/configuration/configuration.go

Before this PR:  
- The `pkg/virtctl/configuration` package had inconsistencies, including:  
- Unnecessary string concatenation in `usage()`  
- Use of `fmt.Printf` instead of `cmd.Printf` for logging  
- Minor formatting and readability issues  
After this PR:  
- **Refactored `usage()`** to be more concise  
- **Replaced `fmt.Printf` with `cmd.Printf`** for better CLI output handling  
- **Improved error message consistency**  
Fixes #13095
These changes improve code readability, maintainability, and ensure consistency in how CLI output is handled within the `virtctl` package. Using `cmd.Printf` aligns with Cobra's best practices for CLI tools. 
Kindly review this PR and let me know if there are any concerns or areas that need …

Refactored virtctl configuration and improved formatting

---

tests/operator/operator.go
tests/testsuite/fixture.go

In tests/operator/operator.go, drop waitForKvWithTimeout and replace it with `testsuite.EnsureKubevirtReadyWithTimeout`. Modify `testsuite.EnsureKubevirtReadyWithTimeout` to also check KubeVirt's `Created` condition.
```release-note
None
```
/kind cleanup

tests/operator.go: Drop waitForKvWithTimeout

---

pkg/virt-handler/BUILD.bazel
pkg/virt-handler/vm_test.go

Follow up from https://github.com/kubevirt/kubevirt/pull/13756. It moves unit test added checking live migration sharing volumes with virtiofs to use libvmi functions.
Virtiofs migration unit tests **do not use** libvmi Options to create the required VMI definitions.
After this PR:
Virtiofs migration unit tests **do use** libvmi Options to create the required VMI definitions.
Fixes # https://github.com/kubevirt/kubevirt/pull/13756#discussion_r1935251070
```release-note
None
```

cleanup(test,virtiofs): Use libvmi functions in migrations tests

---

automation/test.sh
tests/decorators/decorators.go
tests/infrastructure/security.go
tests/validatingadmissionpolicy/noderestrictions.go

Kubernetes versions lower than v1.30 are no longer supported or tested in the main branch so this filter is no longer needed.
Fixes #
```release-note
NONE
```

automation: Remove the filter for kubernetes version lower than v1.30

---

pkg/network/setup/filters.go
pkg/network/setup/filters_test.go

Currently, when performing a NIC hotunplug operation, virt-handler removes the network plumbing prior to virt-launcher detaching the interface from the domain.
Adjust the virt-handler's filtering logic to only unplug networks whose interfaces were already detached from the domain.
Partially addresses #13721
https://github.com/kubevirt/kubevirt/issues/13721
```release-note
NONE
```

NIC hotunplug: Rm plumbing after detachment from domain

---

tests/BUILD.bazel
tests/events/BUILD.bazel
tests/events/events.go
tests/framework/checks/BUILD.bazel
tests/framework/checks/skips.go
tests/libinfra/BUILD.bazel
tests/libinfra/leader.go
tests/libstorage/datavolume.go
tests/libstorage/pvc.go
tests/libstorage/storageclass.go
tests/monitoring/BUILD.bazel
tests/monitoring/component_monitoring.go
tests/storage/BUILD.bazel
tests/storage/storage.go
tests/testsuite/fixture.go
tests/testsuite/kubevirtresource.go
tests/testsuite/manifest.go
tests/testsuite/namespace.go
tests/testsuite/serviceaccount.go
tests/util/BUILD.bazel
tests/util/util.go
tests/vmi_configuration_test.go

Do as the title says.
Test code panics if it sees errors.
After this PR:
Test code expects errors not to occur.
Fixes #
```release-note
None
```

cleanup(tests): Keep calm, don't panic and expect errors not to occur

---

cmd/pr-helper/BUILD.bazel
cmd/pr-helper/entrypoint.sh
cmd/pr-helper/multipath.conf
pkg/virt-operator/resource/generate/components/daemonsets.go

The qemu-pr-helper forwards the persistent reservation request to the [multipath daemon](https://linux.die.net/man/8/multipathd). In order to perform the request the pr-helper and the multipathd needs to talk via a unix socket.
This change allows to configure the persistent reservation with multipath by creating a symlink to the  unix socket which will be made available inside the pr-helper container.
Alternative PR to https://github.com/kubevirt/kubevirt/pull/14060 .
In parallel to this PR there is an ongoing effort to support different network namespace and regular sockets in multipath, see https://github.com/opensvc/multipath-tools/issues/111.
What this PR does
Persistent reservation didn't work with multipath scsi device
After this PR:
Persistent reservation work with …

pr-helper: create entrypoint to generate symlink to multipath socket

---

tests/infrastructure/cluster-profiler.go

From checking the results in testgrid, this test has not failed once in the last two weeks of periodics so it should no longer be quarantined.
Fixes #13865
/cc @dhiller @fossedihelm 
```release-note
NONE
```

e2e,compute: Unquarantine subresource access test

---

tests/operator/operator.go

In upgrade tests, we install the previous kv version and then update to the current one.
We rely on github API to do this, fetching the latest upstream release tag.
These third-party requests are encapsulated in an Eventually loop with 10 sec timeout, but since there is no client timeout set, it could happen that we simply try one request (which lasts more than 10 secs).
Let's explicitly set a timeout in the http client, so that we try at least two times.
Fixes https://github.com/kubevirt/kubevirt/issues/13867 …

e2e: set a http client timeout for github requests

---

pkg/virtctl/guestfs/BUILD.bazel
pkg/virtctl/guestfs/guestfs.go
pkg/virtctl/guestfs/guestfs_test.go

libguestfs-tool pods don't receive tolerations, so they won't be scheduled if all available nodes are tainted. This patch lets the user specfiy their VM so the VMs tolerations can be applied to the libguestfs-tool pod.
If all available nodes were tainted, then the pod created by `virtctl guestfs` would not be scheduled due to missing tolerations.
After this PR:
User can now specify the VM (the one they want to inspect with `virtctl guestfs`) as a cmd line arg. The libguestfs-tool pod will receive that VMs tolerations and get scheduled.
The following tradeoffs were made: The user has to specify a VM but since `virtctl guestfs` is primarily to inspect VMs, this is reasonable.
The following alternatives were considered: 
- allowing the user to specify the tolerations instead …

virtctl, guestfs: Add --vm cmd line arg to guestfs

---

pkg/virt-controller/watch/vmi/BUILD.bazel
pkg/virt-controller/watch/vmi/datavolumes.go
pkg/virt-controller/watch/vmi/vmi.go
pkg/virt-controller/watch/vmi/vmi_test.go
pkg/virt-controller/watch/vmi/volume-hotplug.go

Refactors the storage related logic out of vmi.go.
Fixes #
```release-note
NONE
```

Make VMI controller lighter by moving storage logic into own files.

---

tests/network/vmi_infosource.go

The `kubevirt.io/api/core/v1` package was imported twice under different aliases.
Remove the redundant import statement.
Fixes #
```release-note
NONE
```

net, e2e, vmi_infosource: Apply linter

---

tests/libnode/node.go

Add 486-v1-x86_64-cpu to cpuDenyList to remove failures
See https://search.ci.kubevirt.io/?search=CPU+model+486-v1-x86_64-cpu&maxAge=48h&context=5&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
```release-note
NONE
```

tests: Add 486-v1-x86_64-cpu to cpuDenyList

---

pkg/virt-controller/watch/migration/migration.go
pkg/virt-controller/watch/migration/migration_test.go

Unhappy IDE
After this PR:
Happy IDE
Fixes #
```release-note
NONE
```

migration controller: code cleanup

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go

With the "root" feature gate enabled a PVC will be mounted with root permissions, making virtiofsd to fail when writing to a PVC, since the virtiofs container runs unprivileged even if the pod runs as root.
virtiofsd fails to write to a PVC with the root feature gate enabled
After this PR:
Fixes #13141
```release-note
NONE
```

template: set fsGroup unconditionally

---

tests/network/link_state.go

An assertion for successful VM creation was missing.
Fixes #
Taken from:
- https://github.com/kubevirt/kubevirt/pull/14081
```release-note
NONE
```

[release-1.5] net, e2e, link state: Add missing assertion

---

pkg/virt-operator/BUILD.bazel
pkg/virt-operator/kubevirt_test.go
tests/operator/operator.go

There's no extra value in e2e testing that the labels are passed,
a unit test should provide the same guarantee.
Fixes #13902 
```release-note
NONE
```

operator label propagation: convert to unit test

---

automation/test.sh
tests/network/hotplug_sriov.go
tests/network/sriov.go

This PR remove programmatic skips in SR-IOV test suite, including hotplug and migration tests.
The programmatic skip is replaces with error enable tests to fail faster in case env doest support the tests:
All tests, nodes doesnt expose the expected SR-IOV resource pool.
In migration and hotplug tests, cluster has less then two nodes
After this PR:
Fixes #
```release-note
NONE
```

tests, network, sriov: Rm programmatic skip

---

pkg/virtctl/version/version.go

Before this PR:  
- `virtctl version` command contained unnecessary complexity.  
- Used `fmt.Sprintf("%#v", value)` redundantly.  
- Error handling could be improved for better debugging.  
- Used `cobra.ExactArgs(0)` instead of `cobra.NoArgs`.  
After this PR:  
- **Refactored `usage()`** to use a multiline string for better readability.  
- **Improved error handling** using `fmt.Errorf("%w", err)` for better error wrapping.  
- **Used `cobra.NoArgs`** for idiomatic Go practices.  
- **Removed unnecessary `fmt.Sprintf("%#v", value)` calls** in `printf`.  
- **Applied early return pattern** to simplify the `Run()` function.  
Fixes #14085 
The following tradeoffs were made:  
- Improved code maintainability and readability without changing functionality.  
- Focused on Go best practices …

pkg/virtctl/version: code cleanups and refactoring (#14085)

---

pkg/virt-controller/watch/vmi/vmi.go
pkg/virt-controller/watch/vmi/vmi_test.go
tests/compute/vm_lifecycle.go

This PR fixes a bug in virt-controller where finalized launcher pods (Succeeded/Failed) could remain stuck in the cluster.
Previously, the controller only checked for pod deletion but did not handle cases where terminated pods were lingering due to slow garbage collection, collection thresholds, or other factors.
Now, the controller explicitly deletes finalized pods if they are detected as stuck, ensuring they do not block further operations.
Fixes #12931
```release-note
Ensure launcher pods are finalized and deleted before removing the VMI finalizer when the VMI is marked for deletion.  
```

virt-controller/watch/vmi: Bug Fix: Ensure Stuck Finalized Launcher Pods Are Deleted in virt-controller

---

pkg/virt-api/rest/lifecycle.go
pkg/virt-api/rest/memorydump.go
pkg/virt-api/rest/sev.go
pkg/virt-api/rest/subresource.go
pkg/virt-api/rest/subresource_test.go
pkg/virt-api/rest/volumes.go

Minor cleanup in virt-api:
- use patchset instead of jsonstring
- move const near their usage file
- extracted body decoding logic
- early exit where body is required
Fixes #
```release-note
NONE
```
/cc @0xFelix 

virt-api: use patchset instead of json string

---

automation/repeated_test.sh
tests/network/vmi_istio.go

Istio tests are decorated with Ginkgo label Istio, enabling filtering out Istio tests in case the env doesn't support it.
In Kubevirt CI, the automation creates a cluster with Istio installed and tests are running by default.
Hence, remove programmatic skip in istio tests.
After this PR:
Fixes #
As of today check-tests-for-flakes lane does not account for Istio tests, this PR retain this behavior.
A follow-up PR should add support for check-tests-for-flakes to cover Istio tests as well.
Given CI runs on Istio version that is not supported, IMO check-tests-for-flakes should should cover Istio tests once CI runs supported version of Istio.
This …

tests, network, istio: Remove programmatic skip

---

hack/linter/lint-paths.txt
pkg/virtctl/clientconfig/clientconfig.go

Before this PR: Running the linter against pkg/virtctl/clientconfig fails. 
After this PR: Running the linter against pkg/virtctl/clientconfig should succeeds without errors or warnings.
Fixes #14186 
The return variables were named in function signature.
```release-note
None
```

Fix linting issues in pkg/virtctl/clientconfig by naming return values

---

pkg/virt-handler/vm.go

Added prefix to the message of evens `AccessCredentialsSyncSuccess` and `AccessCredentialsSyncFailed`. This will make it clear that the events relate to access credentials sync.
Fixes: https://issues.redhat.com/browse/CNV-41083
```release-note
None
```

virt-handler: Improve event messages for SSH key sync

---

pkg/os/disk/disk.go
pkg/virt-handler/cgroup/BUILD.bazel
pkg/virt-handler/cgroup/cgroup.go
pkg/virt-handler/cgroup/util.go
pkg/virt-handler/hotplug-disk/mount.go
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go
pkg/virt-launcher/virtwrap/BUILD.bazel
pkg/virt-launcher/virtwrap/live-migration-source.go
pkg/virt-launcher/virtwrap/live-migration-source_test.go
tests/storage/migration.go

The functional test reproduce the issue described in https://issues.redhat.com/browse/CNV-55615
Volume migration was failing for filesystem to block migration, and also from block to filesystem. Additionally, the hotplug tests with volume migration were limited.
After this PR:
Fixed various bugs concerning the volume migration with hotplugged disks:
- Fixed the volume mode for migrated volume
- Fixed the paths for hotplugged volumes which are different from the regular disks
- Considering now migrated volume during the allow list generation for the launcher cgroup  
Added a test which verifies volume migration with a regular and an hotplug disk with all the volume mode combinations.
Fixes: https://issues.redhat.com/browse/CNV-55615
```release-note
NONE
```

volume-migration: fix several bugs: volume mode evaluation, hotplug paths and cgroup allow list generation

---

tests/network/sriov.go

The SR-IOV test suite doesn't have the sig-network decorator making it
harder to filter on running the tests.
Add sig-network decorator to SR-IOV test suite.
Similar to the rest of tests suite under test/network.
After this PR:
Fixes #
Following recent changes around decorator in e2e tests done by https://github.com/kubevirt/kubevirt/pull/14062
it seems SR-IOV test suite was left out.
```release-note
NONE
```

tests,sriov: Add missing sig-network decorator

---

pkg/libvmi/devices.go
tests/compute/subresources/expandspec.go
tests/mdev_configuration_allocation_test.go
tests/testsuite/fixture.go
tests/virt-handler_test.go
tests/virtctl/vnc.go
tests/vmi_configuration_test.go
tests/vmi_headless_test.go
tests/vmi_lifecycle_test.go
tests/vnc_test.go

Every VM started by e2e tests has a graphics card, which costs a lot to emulate and drive, when the vast majority of tests don't need graphics.
After this PR:
No graphics by default.
Fixes #
```release-note
NONE
```

testsuite: disable guest graphics by default

---

pkg/virt-config/configuration_test.go
pkg/virt-handler/node-labeller/node_labeller_test.go

Use Expect instead of Consistently
There is no reason for the results of the calls to change,
as there are no other goroutines running in these unit tests.
Removing Consistently would reduce testing time and simplify the tests.
After this PR:
Fixes #
```release-note
NONE
```

Use Expect instead of Consistently

---

pkg/virt-controller/watch/migration/migration.go

These were removed by mistake by the priority queue PR.
No rate-limit/delay on queue adds since https://github.com/kubevirt/kubevirt/pull/14141
After this PR:
Previous behavior restored
Fixes #
```release-note
NONE
```

migration controller: re-add rate limit and delay to queue adds

---

pkg/storage/snapshot/snapshot.go

When running getVolumeSnapshotStatus, it checks if volume is nil. However if it is - it directly uses it, and that will cause a [segmentation violation](https://go.dev/play/p/Sp3Cva3eNK6).
As this condition should never happen (the volume parameter is derived from a range command so no volume could be nil) - removing the condition entirely.
Fixes #
```release-note
NONE
```

pkg/storage/snapshot: Remove illogical condition

---

pkg/virt-config/featuregate/active.go

VMPersistentState is Alpha
After this PR:
VMPersistentState is Beta
Fixes #
```release-note
NONE
```

feature gates: graduate VMPersistentState to Beta

---

tests/compute/subresources/reset.go

Currently, the non persistent file is written in
the regular fs.
Actually it should be done in tmpfs, since it
is actually volatile.
Since reset does not involve pod recreation, it
could be possible that, depending on how k8s
manage the storage, that the file is still there
after the reset.
Fixes #
This flakiness was observed recently: https://search.ci.kubevirt.io/?search=Reset+subresource&maxAge=168h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
```release-note
NONE
```

e2e: write file in tmpfs for reset test

---

hack/linter/lint-paths.txt
pkg/virtctl/create/params/params.go
pkg/virtctl/create/params/params_test.go

- Added named return values to SplitPrefixedName function
- Replaced magic numbers with constants
- Fixed formatting and line length issues in tests
Fixes #14196
* package `pkg/virtctl/create/params` was not formatted as per listing rules
After this PR:
* package `pkg/virtctl/create/params` is now formatted as per listing rules, `make lint` passes
Fixes #
```release-note
None
```

virtctl: Fix linting issues in pkg/virtctl/create/params

---

hack/linter/lint-paths.txt
tests/conformance/conformance.go

After this PR:
Fixes #
```release-note
NONE
```

linter: Add tests/conformance to lint paths 

---

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-config/configuration_test.go
pkg/virt-config/virt-config.go
pkg/virt-controller/watch/vm/vm_test.go
tests/hotplug/affinity.go
tests/hotplug/tolerations.go

The default rollout strategy is `Stage` and must be changed to `LiveUpdate` to enable live propagation and therefore CPU/memory hotplug.
After this PR:
The rollout strategy is now `LiveUpdate` by default and must be set to `Stage` to opt-out of hotplug.
Fixes #
```release-note
Default VM Rollout Strategy is now LiveUpdate. Important: to preserve previous behavior, rolloutStrategy needs to be set to "Stage" in the KubeVirt CR.
```

VM Rollout Strategy: default to LiveUpdate

---

pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/snapshot_test.go
pkg/storage/snapshot/source.go
staging/src/kubevirt.io/api/snapshot/v1beta1/types.go
tests/storage/snapshot.go

We want to have a better indication that quiescing the guest failed, it should be marked clearly in the snapshot indications on top to the error.
Furthermore it is possible that the freeze will fail but will retry and succeed and the snapshot will be completed and marked as ready it while there is a small risk that the snapshot will be inconsistent. We should mark that there was a failure when freezing so the user will be aware of that risk, and might consider retrying. Added a UTs to cover this scenario. Functional test seems redundant.
Fixes #
Jira-ticket: https://issues.redhat.com/browse/CNV-56774
```release-note
VMSnapshot: add QuiesceFailed indication to snapshot if freeze failed
```

VMSnapshot: add QuiesceFailed indication to snapshot if freeze failed

---

OWNERS_ALIASES

@vladikr @enp0s3 and @xpivarc are already root approvers of the project. One of their main focus is sig-compute, an area they're expert and active in.
This PR reflects the long-standing reality in which these contributors approve a large portion of the sig-compute area. It will let users and developers know that these personas are experts in the sig-node field and can assist with approval reviews.
```release-note
NONE
```

Assign vladikr, enp0s3 and xpivarc as sig-compute approvers

---

tests/vmi_configuration_test.go

Test
`[sig-compute]Configurations...with CPU spec [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]when CPU model defined [test_id:1678]should report defined CPU model`
has been stabilized with PR
https://github.com/kubevirt/kubevirt/pull/13996
After this PR:
Test is taken out of quarantine.
Fixes #13868
/cc @fossedihelm @Barakmor1 
```release-note
```

fix: dequarantine [test_id:1678]

---

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-config/feature-gates.go
pkg/virt-config/featuregate/active.go
pkg/virt-config/featuregate/inactive.go
tests/testsuite/kubevirtresource.go

Using VM persistent features like TPM or EFI requires a feature gate.
After this PR:
Persistent TPM/EFI is still disabled by default, but the feature gate is gone.
Fixes #
```release-note
VM Persistent State GA
```

feature-gates: GA VMPersistentState

---

tests/compute/subresources/BUILD.bazel
tests/compute/subresources/reset.go

Currently, to check that the reset was performed,
we write a file in the `/tmp` folder and expect
that it is not there anymore after the reset.
Actually, the `/tmp` folder is not part of the
tmpfs, and hence some flakiness was observed.
The test can be improved by checking the boot time pre and post reset, and asserting that the two
are different.
Fixes #
- mount `/tmp` in as `/tmpfs`
- write a file into `/dev` (it is part of the tmpfs)
Thanks to @jean-edouard and @iholder101 for the alternatives.
```release-note
NONE
```

fix(reset): check boot time instead file

---

hack/ci/entrypoint.sh
hack/functests.sh
hack/kwok-perftests.sh
hack/perftests.sh
hack/realtime-perftests.sh
tests/access_test.go
tests/clientcmd/command.go
tests/flags/flags.go
tests/kubectl_test.go
tests/replicaset_test.go
tests/vm_test.go
tests/vmi_hook_sidecar_test.go

Tests now fail instead of silently skipping tests when a command is not found. It is achieved by converting clientcmd.SkipIfNoCmd to clientcmd.FailIfNoCmd. This also removes clientcmd.SkipIfNoCmd from places where it had no effect anyway.
Additionally, traces of the no longer used gocli command are removed and some smaller cleanups are applied.
Tests now fail instead of silently skipping tests when a command is not
found. It is achieved by converting clientcmd.SkipIfNoCmd to
clientcmd.FailIfNoCmd. This also removes clientcmd.SkipIfNoCmd from places
where it had no effect anyway.
Additionally, traces of the no longer used gocli command are removed and
some smaller cleanups are applied.
Tests are silently skipped if a command is not found.
After this PR:
Tests fail if a …

tests: Fail if command is not found

---

tests/compute/subresources/reset.go

A super duper tiny follow-up to https://github.com/kubevirt/kubevirt/pull/14313.
Checks that the boot time string is not empty, so the test won't pass as a false positive. see https://github.com/kubevirt/kubevirt/pull/14313#discussion_r2009129561.
```release-note
NONE
```

Reset subresource test: check that boot time string is not empty

---

pkg/monitoring/metrics/common/client/metrics.go

Metrics were registered with k8s client-go on metric setup call
After this PR:
Metrics are registered on init
Fixes https://github.com/kubevirt/kubevirt/issues/14282
```release-note
Register k8s client-go latency metrics on init
```

Register k8s client-go latency metrics on init

---

pkg/instancetype/controller/vm/BUILD.bazel
pkg/instancetype/controller/vm/controller_test.go
pkg/virt-config/BUILD.bazel
pkg/virt-config/configuration_test.go
pkg/virt-config/featuregate/active.go
pkg/virt-config/featuregate/inactive.go
pkg/virt-config/virt-config.go
tests/instancetype/BUILD.bazel
tests/instancetype/reference_policy.go

This change graduates the instance type reference policy feature to GA
removing the need for the associated feature gate to be enabled before
it is configurable by a cluster admin.
Fixes #
```release-note
The `InstancetypeReferencePolicy` feature has graduated to GA and no longer requires the associated feature gate to be enabled.
```

featuregates: Graduate InstancetypeReferencePolicy to GA

---

pkg/monitoring/metrics/virt-controller/vmistats_collector.go
pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go

Some metrics might have both the IP and the name missing and only the interface name. After https://github.com/kubevirt/kubevirt/pull/13386, this will no longer cause errors, but a metric for them will not be created.
After this PR:
A metric for these interfaces is also created.
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-57036
jira-ticket: https://issues.redhat.com/browse/CNV-57377
```release-note
Add interface name label to kubevirt_vmi_status_addresses
```

Add interface name label to kubevirt_vmi_status_addresses

---

cmd/virt-launcher/virt-launcher.go
pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go

Today, unit tests make an actual attempt to read the cpuset
from the filesystem that runs the unit tests.
This is wrong, since there are many assumptions baked into
the cpuset existing. One of them the cpuset controller is enabled for
non-root users, which is not always the case:
https://rootlesscontaine.rs/getting-started/common/cgroup2/#enabling-cpu-cpuset-and-io-delegation
This makes the unit tests fail with setups that don't
unit test with the host's cgroup
(arguably most common among kubevirt developers, podman default)
Fixes # …

Stop reading cpuset in unit tests

---

images/disks-images-provider/BUILD.bazel

The disks-images-provider is pointing to wrong alpine.iso(x86). Because of this one of the virtctl image upload test(test_id:4621) is failing.
After this PR:
The disk-images-provider is now pointed to s390x alpine.iso. 
Fixes #
```release-note
fix: disks-images-provider is pointing to wrong alpine image for s390x.
```

fix the disk-images provider for s390x.

---

pkg/instancetype/webhooks/vm/BUILD.bazel
pkg/instancetype/webhooks/vm/admitter_test.go
pkg/instancetype/webhooks/vm/vm_suite_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go

This change extracts the bulk of the instance type related
VirtualMachine admission tests alongside the recently extracted
implementation.
A single test asserting that the original VirtualMachine object is not
mutated during submission is retained.
Fixes #
```release-note
NONE
```

instancetype, webhooks: Extract admission tests

---

pkg/virt-config/featuregate/inactive.go

The `VMLiveUpdateFeaturesGate` FG was GAed on v1.5[1].
[1] https://github.com/kubevirt/kubevirt/pull/13091
Fixes #
```release-note
NONE
```

VMLiveUpdateFeaturesGate: Correct GA version

---

pkg/network/admitter/admit_suite_test.go
pkg/network/admitter/slirp.go
pkg/network/admitter/slirp_test.go
pkg/network/admitter/validator.go
pkg/virt-config/configuration_test.go
pkg/virt-config/virt-config.go

SLIRP was discontinued in v1.3 [1].
The net validator blocks creating VMs with SLIRP binding [2].
There is no need to keep the old validation logic that runs every time a VMI is created and/or updated.
[1] https://github.com/kubevirt/kubevirt/pull/11701
[2] https://github.com/kubevirt/kubevirt/blob/09fbbcf888b1fee3c509e6b6e87144c83e44d8c8/pkg/network/admitter/validator.go#L67
Fixes #
```release-note
NONE
```

net, admitter: Remove SLIRP validation

---

pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

At the end of live migration usually qemu do a super short domain pause to ensure that final bytes are copied, this is part of normal live migration flow and should not be exposed or affect statuses around but after merging [AllowWorkloadDisruption PR](https://github.com/kubevirt/kubevirt/pull/11833) that is exposes as a VMI statatus making VMI not ready for long time during live migration and breaking ingress tcp connections.
After this PR:
This change make sure that the status is modified only if the allow disruption at workload during live migration mechanism kicks in.
Fixed https://issues.redhat.com/browse/CNV-58354
Kubevirt live migration should work the same on normal workflow
N/A
This …

Don't expose as VMI status the implicit qemu domain pause at the end of live migration

---

hack/linter/.golangci.yml

/cc @orelmisan 
- Replace the deprecated exportloopref with copyloopvar
```
$ golangci-lint run
[..]
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
[..]
```
https://github.com/kyoh86/exportloopref
https://golangci-lint.run/usage/linters/#exportloopref 
https://golangci-lint.run/usage/linters/#copyloopvar
- mnd.checks is an array
https://golangci-lint.run/usage/linters/#mnd
- maligned is deprecated and no longer used
https://golangci-lint.run/usage/configuration/#config-file
- nolintlint.allow-leading-space was dropped some time ago
https://github.com/golangci/golangci-lint/issues/3063
Fixes #
Links to …

chore(linter): Fix linting errors and warnings within the config

---

automation/test.sh

The sig-compute-migrations has been experiencing clustered failures of tests intermittently[1]. These failures look to be due to nfs server timeouts.
Reducing the number of parallel tests running at once seems to avoid these nfs server timeouts. Tested through a number of rehearsal runs in project-infra[2]
This PR also moves the KUBEVIRT_NUM_NODES from the prow job config in project-infra to automation/test.sh - Keeping the lane configuration in one place makes it easier for people to understand what
each test lane is running and how it is configured.
[1] https://github.com/kubevirt/kubevirt/issues/12932
[2] https://github.com/kubevirt/project-infra/pull/4048
Fixes #
Links to places where the discussion took …

e2e,compute-migration: Reduce the number of parallel tests run in compute-migrations test lane

---

hack/cluster-deploy.sh

This reverts the workaround added by https://github.com/kubevirt/kubevirt/pull/13443, as I believe it is now hurting us more than helping.
Fixes #
```release-note
NONE
```

Revert "W/A NFS server becoming unreachable mid run"

---

automation/repeated_test.sh

Calling functest with `-focus=` containing whitespace doesn't work.
After this PR:
Added a step where we replace the whitespace in the escaping.
Fixes #
/cc @brianmcarey @akalenyu
```release-note
NONE
```

fix(check flakes): improve regex escaping

---

tests/migration/migration.go
tests/migration/postcopy.go
tests/vm_state_test.go

The compute-migrations e2e lane has been failing over 20% for over the last four months[1][2].
Normally this would qualify for quarantining the whole test lane but as migrations are important to test we are just quarantining the responsible tests.
These tests will still run as part of the periodics but they are failing far too often to be included in the presubmit lanes
[1]https://testgrid.kubernetes.io/kubevirt-presubmits#pull-kubevirt-e2e-k8s-1.32-sig-compute-migrations&width=20 [2] https://github.com/kubevirt/kubevirt/issues/12932
Fixes #
/cc @dhiller @akalenyu @xpivarc @fossedihelm  …

migrations,e2e: Quarantine flaky compute-migrations tests

---

hack/linter/lint-paths.txt
pkg/virtctl/create/vm/params.go
pkg/virtctl/create/vm/vm.go
pkg/virtctl/create/vm/vm_test.go

- Fixed stylecheck, govet, shadow, misspell, and magic number issues  
- Added `//nolint` comments where necessary for readability and logic  
- Excluded verbose test file (`vm_test.go`) from `dupl`, `gocritic`, and `lll` linters  
- Ensured `make lint` passes cleanly with no warnings  
This PR improves code quality by resolving a variety of lint issues across the `create-vm` logic in virtctl. It ensures compliance with the linter configuration used in the project while balancing readability and maintainability.
- Numerous linter issues were reported, including shadowed variables, naming inconsistencies, overly long lines, and more.
- Tests had excessive duplication and length issues, particularly in `vm_test.go`.
After this PR:
- Core logic in `vm.go` and `params.go` …

Chore/14198/resolve lint warnings in create-vm logic

---

pkg/storage/snapshot/BUILD.bazel
pkg/storage/snapshot/restore.go
pkg/storage/snapshot/restore_test.go
tests/storage/restore.go

When restoring a VM to its previous state, the runstrategy should remain unchanged and not automatically update to "Halted." Since the target VM being restored is the same as the original, it means that the user has already stopped the VM before initiating the restore. As a result, not altering the runstrategy ensures that the VM doesn't start during the restore.
This change also addresses a potential bug where, when a snapshot was taken, the VM could have either the Running field or the Runstrategy field. Without this update, this discrepancy could lead to errors when updating the VM, as both Running and Runstrategy might be applied simultaneously.
For new VMs, the runstrategy should be explicitly set to "Halted" to prevent the VM from starting automatically during the restore process. …

VMRestore: Keep VM RunStrategy as before the restore

---

pkg/network/admitter/BUILD.bazel
pkg/network/admitter/admit_test.go
pkg/network/admitter/binding_test.go
pkg/network/domainspec/BUILD.bazel
pkg/network/domainspec/domainspec_suite_test.go
pkg/network/setup/BUILD.bazel
pkg/network/setup/network_suite_test.go
pkg/network/setup/network_test.go

**Before this PR:**  
Network package tests used `api.NewMinimalVMI`/`api.NewMinimalVMIWithNS` for VMI creation.  
**After this PR:**  
Tests use `libvmi.New()` builder pattern for explicit and consistent VMI configuration.
- Promotes standardized test setup using `libvmi` builder pattern  
- Improves readability by explicitly defining networks/interfaces  
**Parent issue:** #12059  
Fixes #14152
Kindly review this PR and let me know if there are any concerns or areas that need improvement.
```release-note
None
```

Refactor: Use libvmi.New in tests

---

pkg/libvmi/BUILD.bazel
pkg/libvmi/vmi.go
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

Several function in the virt-handler/vm.go are untested
After this PR:
Added unit tests for some handler functions and fixed some minor bugs
Recently we have reviewed the virt-handler code for migration, and we discovered a lot of small bugs  (e.g https://github.com/kubevirt/kubevirt/pull/13729). This PR starts adding some unit tests for each functions. We have unit tests but they cover the general flow when the vm controller runs, but we don't test all the possible code paths. Hence, this PR start to introduce some more granular unit tests and a couple of small fixes
```release-note
NONE
```

vm: add unit test for virt-handler/vm functions and fix some small bugs - part 1

---

automation/test.sh

Remove the fixed seed to return the randomization.
Fixes #
```release-note
NONE
```

automation, tests: Enable e2e test randomization

---

tests/decorators/decorators.go
tests/storage/datavolume.go
tests/storage/hotplug.go
tests/storage/storage.go

Volume Hotplug tests are failing in clusters with node affinity constraints due to forced PVC binding, rendering the hotplug pod unschedulable.
This Pull Request aims to remove force-binding for volume hotplug tests, allowing the scheduler to do its job.
It also increases some timeouts and changes DV phase expectations in a couple of tests so they can pass with WFFC.
Fixes #
```release-note
NONE
```

Tests: General improvements to make tests work with WFFC

---

automation/test.sh

It makes more sense to keep as much of the test lane configuration in the one place rather than spread over different files in different repos.
Moving environement variables used for configuration from the prow job configurations in project-infra to automation/test.sh
Fixes #
/cc @dhiller 
```release-note
NONE
```

e2e, automation: consolidate e2e environment configuration in automation/test.sh

---

pkg/virt-handler/options.go
pkg/virt-handler/options_test.go

virt-handler became CrashLoopBackOff due to invalid memory address or nil pointer dereference
After this PR:
handled the nil pointer dereference
Fixes #https://github.com/kubevirt/kubevirt/issues/14064
```release-note
handle nil pointer dereference in cellToCell
```

handle nil pointer dereference and added a test

---

pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/snapshot_test.go
pkg/storage/snapshot/source.go
tests/storage/snapshot.go

This is a manual backport of PR https://github.com/kubevirt/kubevirt/pull/12582
/cc @mhenriks 
Fixes #
Fixes: https://github.com/kubevirt/kubevirt/issues/12515
Jira-ticket: https://issues.redhat.com/browse/CNV-54915
```release-note
vmsnapshot: when checking if a VM is running, ignore runStrategy
```

[release-1.3] vmsnapshot: when checking if a VM is running, ignore runStrategy

---

pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/snapshot_test.go
pkg/storage/snapshot/source.go
tests/storage/snapshot.go

This is a manual backport of PR https://github.com/kubevirt/kubevirt/pull/12582
/cc @mhenriks 
Fixes #
Fixes: https://github.com/kubevirt/kubevirt/issues/12515
Jira-ticket: https://issues.redhat.com/browse/CNV-54971
```release-note
vmsnapshot: when checking if a VM is running, ignore runStrategy
```

[release-1.2] vmsnapshot: when checking if a VM is running, ignore runStrategy

---

api/openapi-spec/swagger.json
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/schema.go
staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

Follow up for the PR that introduces the actual functionality: https://github.com/kubevirt/kubevirt/pull/13110
```
$ oc explain vm.spec.template.spec.domain.ioThreadsPolicy
...
DESCRIPTION:
...
One of: shared, auto
```
After this PR:
```
$ oc explain vm.spec.template.spec.domain.ioThreadsPolicy
...
DESCRIPTION:
...
One of: shared, auto, supplementalPool
```
Fixes #
```release-note
supplementalPool added to the description of the ioThreadsPolicy possible values
```

Add supplementalPool to the description of the ioThreadsPolicy possible values

---

hack/linter/lint-paths.txt
pkg/virt-launcher/virtwrap/agent-poller/BUILD.bazel
pkg/virt-launcher/virtwrap/agent-poller/agent_parser.go
pkg/virt-launcher/virtwrap/agent-poller/agent_parser_test.go
pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
pkg/virt-launcher/virtwrap/agent-poller/agent_poller_test.go
pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
pkg/virt-launcher/virtwrap/cli/libvirt.go
pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go

Replace guest agent commands with libvirt
API requests using Domain.GetGuestInfo,
to get and set Network Interfaces, Operating
System Info, Hostname, TimeZone, and
Users.
```release-note
None
```

refactor: replace guest agent commands

---

pkg/virt-config/featuregate/active.go

/cc @ShellyKa13 
/cc @mhenriks 
Both the `snapshot.kubevirt.io` and `export.kubevirt.io` APIGroups already serve `v1beta1` versions so bump the associated FGs to Beta.
Fixes #
Happy to create some tracking issues in the new enhancements repo to track both of these FGs to GA.
```release-note
NONE
```

storage: Move `Snapshot` and `VMExport` FGs to Beta in line with their associated APIGroups

---

pkg/virt-handler/BUILD.bazel
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

Cherry-pick from:
- https://github.com/kubevirt/kubevirt/pull/14288
At the end of live migration usually qemu do a super short domain pause to ensure that final bytes are copied, this is part of normal live migration flow and should not be exposed or affect statuses around but after merging [AllowWorkloadDisruption PR](https://github.com/kubevirt/kubevirt/pull/11833) that is exposes as a VMI statatus making VMI not ready for long time during live migration and breaking ingress tcp connections.
After this PR:
This change make sure that the status is modified only if the allow disruption at workload during live migration mechanism kicks in.
Fixed https://issues.redhat.com/browse/CNV-58354
Kubevirt live migration should work the same on …

[release-1.5] virt handler dont expose lm internal qemu pause

---

tests/storage/datavolume.go

When cloning DVs using volume snapshots as source, we use an abritrary size in the target DV and assume it'll be roughly equal to the source PVC size.
This behavior fails when running tests with a provisioner that sets restore size to a higher value so, in order to increase test consistency, this commit sets the target size to the volume snapshot restore size.
```release-note
NONE
```

Tests: Set DV size to volume snapshot restore size

---

pkg/libvmi/storage.go
pkg/virt-launcher/virtwrap/live-migration-source.go
pkg/virt-launcher/virtwrap/live-migration-source_test.go

RWX filesystem volumes were incorrectly evaluated during volume migration causing the error: 
```
{"component":"virt-launcher","level":"error","msg":"invalid argument: NBD URI must be supplied when migration URI uses UNIX transport method", "pos":"qemuDomainMigratePerform3Params:11252","subcomponent":"libvirt","thread":"26","timestamp":"2024-12-13T20:36:31.764000Z"}
````
After this PR:
Fixed shared hostdisk evaluation when generating migration parameters.
Fixes https://issues.redhat.com/browse/CNV-53156
```release-note
NONE
```

volume-migration: fix evaluation of RWX filesystem PVCs during the generation of the  parameters for the migration

---

pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go

Before this PR: `/pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go` used NewMinimalVMI() to create vmis
After this PR: Replaced all instances of `NewMinimalVMI()` with `libvmi.New(...)`
Relevant issue: https://github.com/kubevirt/kubevirt/issues/14147
```release-note
NONE
```

Replace NewMinimalVMI with libvmi in migration-update-admitter_test.go

---

pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
pkg/virt-api/webhooks/utils.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-config/virt-config.go
pkg/virt-controller/services/template.go

Architecture specific unit-test results are hidden in the testcode
After this PR:
Architecture specific unit-test results are separate testcases using Tables.
Fixes #
This improves the readability of testcases and moves into making the unit-tests more indepented of the architecture of the host it is being run on.
- 1 instance each of arm64 and ppc64le code has been left as is, since it is only a special case for them and i'm no expert on these 2 architectures, so i left it as is.
- `pkg/defaults` has been left unchanged, since the code is already in architecture specific files and it would be more complicated to use the interfaces approach here.
Links to places where the discussion took place: …

Simplify and improve multiarch unit-tests

---

pkg/liveupdate/memory/memory_test.go
pkg/monitoring/metrics/testing/metric_matcher.go
tests/monitoring/metrics.go

It's a nit, to make it harder for people to introduce wrong capitalization by copying these three exceptional files.
/kind cleanup
```release-note
NONE
```

nit: consistent `KubeVirt Authors` capitalization

---

pkg/virtctl/vnc/vnc.go

- `virtctl vnc` does not use a context, potentially leaking goroutines.
After this PR:
- `virtctl vnc` now uses a context, ensuring it can be shut down in a controlled manner without leaking goroutines.
Fixes #13414 
Using a context ensures that virtctl vnc can be canceled gracefully, avoiding goroutine leaks. This approach follows idiomatic Go practices for managing the lifecycle of operations.
Links to places where the discussion took place: https://github.com/kubevirt/kubevirt/pull/13378#discussion_r1863782022
```release-note
NONE
```

make use of context for vnc

---

pkg/controller/BUILD.bazel
pkg/controller/conditions_test.go

This PR updates the creation of the "test" VirtualMachineInstance in the test code from api.NewMinimalVMI to libvmi.New. This change is part of the effort to standardize VMI creation using the libvmi package for better consistency and maintainability.
```release-note
none
```

refactor: Convert test VMI Creation to Use libvmi.New

---

pkg/storage/export/export/export.go
pkg/storage/export/export/export_test.go
pkg/storage/utils/BUILD.bazel
pkg/storage/utils/volumes.go
pkg/storage/utils/volumes_test.go

We've been using unsanitized volume names in the exporter pod which could exceed 63 characters, causing pod validation failures.
This PR adds sanitization to trim volume names when necessary. It also trims the backend storage PVC volume name in the volume-enumeration helpers as a precaution.
Fixes # https://issues.redhat.com/browse/CNV-56635
```release-note
Bugfix: Truncate volume names in export pod
```

Truncate large volume names in export pod 

---

tests/operator/operator.go

The sig-operator tests are not enabled for s390x.
After this PR:
The sig-operator tests are enabled for s390x.
Fixes #
```release-note
None.
```

Update vmi image to use Alpine instead of cirros to enable sig-operator tests on s390x.

---

tests/migration/migration.go

This test has been passing in the periodic compute-migrations for over the last two weeks so it qualifies to be removed from quarantine https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.32-sig-compute-migrations&width=20&include-filter-by-regex=QUARANTINE
Fixes #
/cc @fossedihelm @dhiller 
```release-note
NONE
```

e2e,migration: Remove quarantine from migration test checking for target pod failure

---

tests/decorators/decorators.go
tests/tests_suite_test.go

Currently most test resources are cleaned up (vm/vmis, nodes, config)
following each spec, since `AfterEach() ` is global and uncustomizable.
This does not enable running multiple test cases on a single set of
VMs without complete cleanup and restart in between.
Some tests may benefit from delayed cleanup triggers, thus reduce test duration.
This change introduces a new decorator label 'skipGlobalCleanup',
Test that are labeled 'skipGlobalCleanup' and also `Ordered` are cleaned 
up only once per ordered container.
See [OncePerOrdered documentation](https://onsi.github.io/ginkgo/#setup-around-ordered-containers-the-onceperordered-decorator) for details.
After this PR:
Fixes #
Links to places …

e2e, tests-suite: Controlled cleanup for Ordered tests

---

tests/storage/export.go

Seems like this sometimes fails with no stderr/stdout, which likely means the command never ran on the pod.
https://search.ci.kubevirt.io/?search=Export+should+make+a+PVC+export+available+with+archive+content+type&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
```release-note
NONE
```

Export tests: wait for test pod readiness before issuing commands

---

docs/observability/metrics.md
pkg/monitoring/metrics/virt-controller/migrationstats_collector.go
pkg/monitoring/metrics/virt-controller/migrationstats_collector_test.go
tests/monitoring/metrics.go
tests/monitoring/vm_monitoring.go

VMIM's in unset simply means the virt-controller has not interacted with the VMIM object yet, but is expected to as it works through the incoming queue. This pr adds a separated metric for unset state instead of including it in kubevirt_vmi_migration_failed.
kubevirt_vmi_migration_failed included migrations in unset state.
After this PR:
migrations in unset state are reported in new metric named kubevirt_vmi_migrations_in_unset_phase instead of including it in kubevirt_vmi_migration_failed.
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-56912
```release-note
Added kubevirt_vmi_migrations_in_unset_phase, instead of including it in kubevirt_vmi_migration_failed.
```

Fix kubevirt_vmi_migration_failed to not include VMIMs in 'unset'

---

tests/decorators/decorators.go
tests/network/vmi_lifecycle.go

The test in question restarts the kubelet on the node the VMI is running on. It may cause disruptions to other workloads running on the node.
The label / decorator was added so the test could be easily skipped.
Fixes #
https://github.com/kubevirt/kubevirt/issues/14358
```release-note
NONE
```

net, e2e: Mark kubelet restart test as Disruptive

---

pkg/virt-launcher/virtwrap/nichotplug.go
pkg/virt-launcher/virtwrap/nichotplug_test.go

Currently, `withNetworkIfacesResources` is executing the passed `f` function twice sometimes.
The func passed is `SetDomainSpecStrWithHooks`, which executes `DomainDefineXML`. The latter requires a dom.Free() to be executed, freeing resources.
The Free is performed down on the stack in the `SyncVMI` func, but since it is fired twice, only the last one domain is freed.
Let's call `dom.Free()` in those cases where a second DomainDefineXML is required.
We don't release the domain in some cases.
After this PR:
We release the domain in every cases.
Fixes #
This checklist is not enforcing, but it's a reminder of items that could be relevant to every …

fix: Release domain when define is executed

---

pkg/virt-controller/watch/vmi/datavolumes.go
pkg/virt-controller/watch/vmi/vmi_test.go
staging/src/kubevirt.io/api/core/v1/types.go

The current part of the message "DVs are bound and not running" is somewhat confusing.
Message was changed to "DVs are bound and ready" instead.
```release-note
none
```

virt-controller, vmi: clarify VM dvReadyCondition message

---

tests/reporter/kubernetes.go

- Local e2e runs are full of `skipping vmi [...]` messages that sometimes include entire VMI specs.
- Whenever a VMI is not fedora/alpine/cirros, it gets marshalled to json 2 to 3 times at the end of each test.
After this PR:
Silence
Fixes #
This is mostly cosmetic, the time saved is negligible.
```release-note
NONE
```

e2e reporter: stop complaining about and marshalling diskless VMs

---

go.mod
tests/testsuite/BUILD.bazel
tests/testsuite/namespace.go

Following recent clean up around logger dependencies https://github.com/kubevirt/kubevirt/pull/14409
This PR drops usage of `k8s.io/klog` in favor of the project standard logger `kubevirt.io/client-go/log`.
Use `k8.io/klog` to log warning in tests.
After this PR:
Use the project standard logger instead.
Fixes #
```release-note
NONE
```

cleanup: Drop k8s.io/klog dependency

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

Improve machine type validation by ensuring the pattern is more strictly matched.
Expand unit-tests to cover more possible machine types for testing.
API allows machine types like q35-usagduzagd
After this PR:
It is more strict with verifying the glob pattern.
Fixes #14205
```release-note
Ensure stricter check for valid machine type when validating VMI
```

virt-api: Improve machine type validation

---

staging/src/kubevirt.io/api/core/v1/schema.go
staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go

Fix a typo in the API schema.
```release-note
NONE
```

schema: Fix typo

---

pkg/virt-handler/cmd-client/client.go
tests/hotplug/cpu.go

Right after a CPU hotplug, we check the domain XML and on rare occasions it appears to still contain the pre-hotplug values, causing flakiness.
Since the hotplug appears to be successful in failed tests, I assume libvirt just needs a couple seconds to reflect the change in the domain XML.
After this PR:
Move the expectation into a 20-second Eventually loop to give it time to update.
Fixes #
```release-note
NONE
```

tests: CPU hotplug: give time for domxml to update

---

tests/network/bindingplugin_passt.go

Reuse the VMs when executing both IP families
Utilize the `BeforeAll` fixture in ordered contexts and mark common
fixtures (plugin registration and NAD creation) with `OncePerOrdered` so
these will run only once for the ordered tests.
Fixes #
This change demonstrates the resource reuse between tests.
It depends on two PRs: The [passt e2e tests refactoring](https://github.com/kubevirt/kubevirt/pull/14390) and  the [controlled cleanup](https://github.com/kubevirt/kubevirt/pull/13786).
The relevant commits for review in this context are the last two.
```release-note
NONE
```

tests, network: Reuse of VMs between the passt e2e tests

---

tests/compute/vm_lifecycle.go

This test has passed consistently over the last week across the three compute periodic lanes so it qualifies to be removed from quarantine 
https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.32-sig-compute&include-filter-by-regex=QUARANTINE&width=20
Fixes #
/cc @dhiller @fossedihelm 
```release-note
NONE
```

e2e,compute: Remove from quarantine the test for force restart with termination grace period

---

tests/network/bindingplugin_passt.go
tests/network/hotplug_bridge.go
tests/network/vmi_multus.go

Currently, the network e2e tests are using Fedora 35 which had reached EOL a long time ago.
Prepare the network e2e tests for the upgrade to Fedora 39.
Fixes #
- https://github.com/kubevirt/kubevirt/pull/13322
- https://github.com/kubevirt/kubevirt/pull/13863
```release-note
NONE
```

net, e2e: Prepare for Fedora version upgrade

---

pkg/virt-handler/cgroup/BUILD.bazel
pkg/virt-handler/cgroup/cgroup.go
pkg/virt-handler/cgroup/util.go
pkg/virt-handler/hotplug-disk/mount.go
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go
pkg/virt-launcher/virtwrap/BUILD.bazel
pkg/virt-launcher/virtwrap/live-migration-source.go
pkg/virt-launcher/virtwrap/live-migration-source_test.go
tests/storage/migration.go

Manual backport: https://github.com/kubevirt/kubevirt/pull/13931
```release-note
NONE
```

[release-1.5] volume-migration: fix several bugs: volume mode evaluation, hotplug paths and cgroup allow list generation

---

pkg/monitoring/metrics/virt-controller/BUILD.bazel
pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go

instancetypes/preference kind keys in VM definitions can appear as lowercase only, being ignored in the VM monitoring processs.
After this PR:
instancetypes/preference kind keys are handled correctly in any casing style
Fixes #
jira-ticket: `https://issues.redhat.com/browse/CNV-54195`
```release-note
Handle lowercase instancetypes/preference keys in VM monitoring
```

Handle lowercase instancetypes/preference keys in VM monitoring

---

pkg/defaults/defaults.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go

Each machine type allows different number of vcpus, therefore let's have upper bound that is reasonable.
It's a follow-up to #14105 
Fixes #
```release-note
Bug fix: MaxSockets is limited so maximum of vcpus doesn't go over 512.
```

defaults: Limit MaxSockets based on maximum of vcpus

---

Makefile
hack/lint-test-cleanup-label.sh

The `OncePerOrderedCleanup` label was introduced in
https://github.com/kubevirt/kubevirt/pull/13786 as a pilot for SIG-Network and `virtctl`.
Its purpose is to enable sharing of VMs between multiple tests thus reducing test duration and resource usage. Since the feature is temporarily only allowed in the above areas, this commit adds a linter that will fail the lint process, should a file located elsewhere uses the label.
If additional files/areas would like to participate in the pilot, please add required file or directory to the `EXCLUDE_PATTERN` variable.
This entire commit is expected to be reverted once the whole project is on board.
After this PR:
Fixes #
Links to places where the …

make, lint: Limit use of OncePerOrderedCleanup

---

docs/conformance.md
tests/README.md
tests/conformance/conformance.go
tests/container_disk_test.go
tests/network/networkpolicy.go
tests/network/primary_pod_network.go
tests/network/services.go
tests/network/vmi_networking.go

Some tests used the Conformance decorator while others used the [Conformance] tag. The `conformance.go` test suite used in our Sonobuoy image was only matching by the tag, while other users of the test suite only matched by the decorator.
After this PR:
The tag is finally removed and the conformance.go suite defaults to use it.
Fixes #
The is a risk that some unknown users of [Conformance] still exist. This PR tries to adjust all the known callers.
With this change, the Sonobuoy test suite finally runs all the conformance tests. This brings the number of tests from 18 to 100. If anybody would like to keep testing only network conformance tests …

Replace use of [Conformance] with the Conformance decorator

---

tests/infrastructure/prometheus.go

These promethues endpoint tests are flaking badly lately - they are top of the flake stats report[1]
There is a 11% impact to the sig-compute serial lane over the last 7 days which qualifies these tests for quarantine
https://search.ci.kubevirt.io/?search=test_id%3A6241&maxAge=168h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
[1] https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2025-04-16.html#%5bsig-compute%5d%20Infrastructure%20%5brfe_id%3a3187%5d%5bcrit%3amedium%5d%5bvendor%3acnv-qe%40redhat.com%5d%5blevel%3acomponent%5dPrometheus%20Endpoints%20should%20include%20VMI%20infos%20for%20a%20running%20VM%20%5btest_id%3a6241%5d%20by%20IPv6
Fixes #
The …

e2e,prometheus: Quarantine flaky prometheus endpoint tests

---

WORKSPACE

`golang.org/x/sys` dependency is broken
Fixes #
```release-note
NONE
```

[release-0.58] Fix build functests dependency

---

pkg/monitoring/metrics/virt-controller/vmstats_collector.go

There are 2 ways to define datavolume size in the vm yaml, from Spec.PVC.Resources.Requests.Storage()  and Spec.Storage.Resources.Requests.Storage(). this pr makes sure we check both.
data volume size taken only from vm.Spec.DataVolumeTemplates.Spec.PVC.Resources.Requests.Storage()
After this PR:
data volume size taken from vm.Spec.DataVolumeTemplates.Spec.PVC.Resources.Requests.Storage() or vm.Spec.DataVolumeTemplates.Spec.Storage.Resources.Requests.Storage()
Fixes #
```release-note
none
```

Fix getSizeFromDataVolumeTemplates

---

pkg/virt-handler/device-manager/common.go
pkg/virt-handler/device-manager/device_controller.go
pkg/virt-handler/device-manager/device_controller_test.go
pkg/virt-handler/device-manager/mediated_device.go
pkg/virt-handler/device-manager/mediated_device_test.go
pkg/virt-handler/device-manager/mediated_devices_types.go
pkg/virt-handler/device-manager/mediated_devices_types_test.go
pkg/virt-handler/device-manager/pci_device.go
pkg/virt-handler/device-manager/pci_device_test.go

The Handler variable is only used internally and should not be exposed outside the package.
Additionally, it only needs to be initialized once, so the initHandler function is not needed.
device-manager unit-test would flake when run with race detection on (most pronounced on s390x)
After this PR:
device-manager unit-test no longer has a race condition
Fixes #14508
This PR does not solve the actual parallel execution of `BeforeEach` and `DeviceController.updatePermittedHostDevicePlugins`, which should not happen.
I first tried to make the stop channel blocking, however this did not solve the issue. …

virt-handler/device-manager: Do not expose global handler variable

---

pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go
pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
pkg/virt-launcher/virtwrap/cli/libvirt.go

Use libvirt API to set user password
instead of using QEMU agent command
directly.
This improves abstraction and aligns with
recommended usage patterns in libvirt-based
workflows.
Libvirt still uses the same guest agent command
internally. Password encoding is no longer
necessary, simplifying the implementation.
```release-note
None
```

refactor: use libvirt api to set user password

---

pkg/container-disk/container-disk.go
pkg/container-disk/container-disk_test.go

This function duplicates GetDiskTargetFromLauncherView but unnecessarily wraps non-existence as an error. It is only used once, so there's no justification for keeping it.
Instead, directly checking for file existence makes the code clearer
After this PR:
Fixes #
```release-note
NONE
```

container-disk.go:Remove redundant GetDiskTargetPartFromLauncherView function

---

pkg/monitoring/metrics/virt-controller/BUILD.bazel
pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/14327
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-54195
```release-note
Handle lowercase instancetypes/preference keys in VM monitoring
```

[release-1.5] Handle lowercase instancetypes/preference keys in VM monitoring

---

pkg/network/downwardapi/networkinfo.go
pkg/network/downwardapi/networkinfo_test.go

using a map caused interfaces slice to not have ordered data
After this PR:
slices retain the order & the interface struct is maintained for uniformity
Partially address #14442
```release-note
NONE
```

fix: network: sort the map keys to make Interfaces deterministic

---

tests/hotplug/cpu.go

This flake: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/14267/pull-kubevirt-e2e-k8s-1.32-sig-compute-migrations/1913880632807657472
After this PR:
Hopefully no more flake
Fixes #
```release-note
NONE
```

tests: CPU hotplug: flake: let GetRunningVMIDomainSpec retry on error

---

pkg/monitoring/metrics/virt-controller/BUILD.bazel
pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go

Manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/14327
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-54195
```release-note
Handle lowercase instancetypes/preference keys in VM monitoring
```

[release-1.4] Handle lowercase instancetypes/preference keys in VM monitoring

---

tests/migration/migration.go

Original expected message example:
0/2 nodes are available: 2 node(s) didn't match Pod's node affinity/selector`.` preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.
On OCP clusters we get:
0/X nodes are available: Y node(s) didn't match Pod's node affinity/selector`,` Y node(s) had untolerated taint {node-role.kubernetes.io/master: }. preemption: 0/X nodes are available: X Preemption is not helpful for scheduling.
The trailing period in the expected substring causes the test to fail. Remove it to make the check pass on both environments.
Fixes #
```release-note
none
```

tests/migration: fix unschedulable migration check flake

---

tests/reporter/kubernetes.go
tests/virtctl/imageupload.go

Use clientcmd.GetK8sCmdClient where appropriate
Some places use "kubectl" string literals to construct calls to cmds.
After this PR:
All places use clientcmd.GetK8sCmdClient to construct calls to cmds.
Fixes #
```release-note
None
```

cleanup(tests): Use clientcmd.GetK8sCmdClient where appropriate

---

tests/network/sriov.go

This flaky test is has caused 12% impact to the SRIOV e2e lane over the last 7 days and more than qualifies for quarantining. 
https://search.ci.kubevirt.io/?search=single+SRIOV+network+migration&maxAge=168h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
/cc @orelmisan @EdDev 
```release-note
NONE
```

e2e,network: Quarantine flaky single SRIOV network migration test

---

pkg/virt-controller/watch/vm/vm.go

/cc @0xFelix 
/cc @ShellyKa13 
lastSeenVMSpec was wrapped by a full lastSeenVM VirtualMachine object with 43540a4 but some uses of lastSeenVMSpec mistakenly remained.
This change removes these remaining uses of lastSeenVMSpec to ensure that we are always using lastSeenVM when determining if the RestartRequired condition should be added to the VM.
Fixes #
```release-note
NONE
```

virt-controller: Use lastSeenVM consistently within addRestartRequiredIfNeeded

---

hack/builder/common.sh

Currently, you cannot control via env variables for which architecture you want to build the builder.
They are always "amd64 arm64 s390x".
Sometime, for test purposes you want to save time and build only for a specific arch.
Fixes #
```release-note
NONE
```
/cc @brianmcarey @xpivarc

Set ARCHITECTURES externally

---

pkg/virt-api/webhooks/arm64.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

Previously, the validation rejected host-model but did not reject named models. [According to the user guide](https://kubevirt.io/user-guide/cluster_admin/virtual_machines_on_Arm64/#model), only host-passthrough is supported on Arm64.
Without this rejection, the pod associated with the VM can get stuck in scheduling state, because the node labeler is disabled on Arm clusters and the required label will never be added to the nodes.
/cc @dasionov 
After this PR:
Fixes #
```release-note
NONE
```

bugFix: Reject named CPU models on Arm64

---

pkg/storage/snapshot/restore.go
pkg/storage/snapshot/restore_test.go
tests/storage/restore.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/14281
```release-note
VMRestore: Keep VM RunStrategy as before the restore
```

[release-1.4] VMRestore: Keep VM RunStrategy as before the restore

---

hack/prom-rule-ci/prom-rules-tests.yaml
pkg/monitoring/rules/alerts/vms.go
tests/monitoring/vm_monitoring.go

VMCannotBeEvicted is being fired for scheduling VMIs
After this PR:
Trigger VMCannotBeEvicted only for running VMIs
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-56570
```release-note
Trigger VMCannotBeEvicted only for running VMIs
```

Trigger VMCannotBeEvicted only for running VMIs

---

api/openapi-spec/swagger.json
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

Update the documentation to better
reflect the purpose and limitations of
fsFreezeStatus.
Clarifies that it reflects the command
state reported by the guest agent, not
the actual filesystem status. Behavior
may differ on Windows guests due to
automatic thawing.
```release-note
None
```

docs: adjust description of the fsFreezeStatus

---

pkg/instancetype/preference/requirements/BUILD.bazel
pkg/instancetype/preference/requirements/memory.go
pkg/instancetype/preference/requirements/memory_test.go
tests/instancetype/instancetype.go

/cc @0xFelix 
/cc @geetikakay 
As set out in bug #14551 the VM admission webhook could previously crash with a nil-pointer error while asserting that the VM meets the memory requirements of a referenced preference.
This change corrects this by rewriting the checkMemory function to always default to a `0Mi` resource quantity while also fully asserting that values from the VMI spec (spec.template.spec.domain.memory.guest) are non-nil before use.
Support for validating preference requirements against memory provided within the VM by resource requests and various other clean ups are left for a follow up changes to allow this fix to be backported.
Fixes #14551
Links to places where the discussion …

fix(preference): Ensure memory requirements are respected when no memory is specified

---

tests/vm_test.go

This flaky test has caused more than 11% of sig-compute failures in the last 7 days which more than qualifies for quarantining.
https://search.ci.kubevirt.io/?search=test_id%3A6869&maxAge=168h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
/cc @fossedihelm @xpivarc 
```release-note
NONE
```

e2e,compute: Quarantine very flaky image pull error test

---

pkg/network/downwardapi/networkinfo.go
pkg/network/downwardapi/networkinfo_test.go

This PR is an automatic cherry-pick of https://github.com/kubevirt/kubevirt/pull/14477 and https://github.com/kubevirt/kubevirt/pull/14553.
Currently, when a VM has an SR-IOV NIC, the VMI controller adds the `kubevirt.io/network-info` annotation to the virt-launcher pod.
This annotation's value is a JSON array derived from the Multus network status annotation (`k8s.v1.cni.cncf.io/network-status`).
When there are multiple SR-IOV NICs, the order of the JSON array keeps changing - thus the VMI controller repeatedly patches the pod.
Create a JSON array ordered by lexicographical order so the VMI controller will not repeatedly patch the pod.
Fixes # …

[release-1.5] Fix repeated pod patching when VM has multiple SR-IOV NICs

---

pkg/network/setup/BUILD.bazel
pkg/network/setup/netstat.go
pkg/network/setup/netstat_test.go

The IP addresses reporting depends on the IP addresses observed from the pod (netns) and from the guest-agent if available. The existing logic depended only on the IPv4 data and assumed the same applied to IPv6 without verifying it. This behavior caused IPv6 addresses to be reflected incorrectly.
E.g. IPv4 detected on the pod, IPv6 existing only in the guest, results in the IPv6 not being reported.
This change introduces IP family independent checks, allowing each family to take a different decision and therefore resolve the scenarios in which the problem appeared.
Fixes # …

net, netstat: Process IPv4 & IPv6 addresses independently

---

api/openapi-spec/swagger.json
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/schema.go
staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

$subject, fixes a simple typo of explictly and corrects it to explicitly in the description of the vTPM Enabled attribute. Identified by [sourcery-ai](https://github.com/apps/sourcery-ai) in the following backport PR:
https://github.com/kubevirt/kubevirt/pull/14581#discussion_r2057900068
Fixes #
```release-note
NONE
```

chore(api): Fix typo within tpm.Enabled description

---

pkg/libvmi/cpu.go
pkg/libvmi/storage.go
pkg/virt-controller/services/renderresources.go
pkg/virt-controller/services/renderresources_test.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go

The number of calculated cpus was wrong using the supplementalPoolThreadCount failing with:
```
Pod "virt-launcher-rhel9-tomato-canidae-79-ztl4l" is invalid: spec.containers[0].resources.requests: Invalid value: "8": must be less than or equal to cpu limit of 4
```
After this PR:
Number of CPUs is now correctly allocated
Fixes https://issues.redhat.com/browse/CNV-59494
The `WithoutDedicatedCPU` and `WithCPUPinning` need to be fixed. There was mixture between calculated and vm limits/resources.
We still probably need to fix the memory resource/limits as well. This will be done in a separate pr.
```release-note
NONE
```

Fix cpu counting for io threads count

---

tests/storage/BUILD.bazel
tests/storage/datavolume.go

Use the go client in datavolume tests where possible and drop redundant test cases.
--cascade=true equals propagation policy background (the default) --cascade=false equals propagation policy orphan
DataVolume tests use kubectl.
After this PR:
DataVolume tests use golang client, redudant tests are removed.
Fixes #
```release-note
None
```

cleanup(tests,storage): Use go client and drop redundant tests

---

cmd/virt-handler/virt-handler.go
pkg/virt-handler/node-labeller/amd64.go
pkg/virt-handler/node-labeller/arch_labeller.go
pkg/virt-handler/node-labeller/node_labeller.go
pkg/virt-handler/node-labeller/node_labeller_test.go
pkg/virt-handler/node-labeller/s390x.go

This change enables the `node-labeller` routine for ARM64-based clusters in KubeVirt by updating the `archLabellerARM64` structure to drop `shouldLabelNodes()` since it returns true for all arches.
Previously, the `node-labeller` was disabled for ARM64 clusters due to incomplete support for labels like CPU features and models, which are supported on other architectures such as `amd64` and `s390x` - ref https://issues.redhat.com/browse/RHEL-88219.
For this PR, we’ve chosen to enable only machine-type labels for ARM64, as these are critical for virtual machine (VM) scheduling and represent the minimum functionality required from the `node-labeller`.
Note that machine-type labels were not required on arm64 clusters previously because VM scheduling on ARM64 did not depend on them. This …

node-labeller: enable node-labeller for ARM64 clusters

---

pkg/storage/snapshot/restore_test.go
staging/src/kubevirt.io/api/snapshot/v1alpha1/types.go
staging/src/kubevirt.io/api/snapshot/v1alpha1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

The `VMRestoreAdmitter` validates patches in `VirtualMachineRestore` and rejects those targeting fields outside of `/spec/`, `/metadata/labels/`, or `/metadata/annotations/`.
However, a [unit test](https://github.com/kubevirt/kubevirt/blob/a56c9c2b7d2e9fe4d1bfdb6d3b95ac516947267c/pkg/storage/snapshot/restore_test.go#L1413) in `restore_test.go` attempts to patch `/metadata/name`, which contradicts the validation logic and is invalid.
This PR removes the conflicting unit test to ensure tests align with the system's behavior.
Fixes #
```release-note
none
```

restore_test.go: Remove Invalid Unit Test for VM Name Patch

---

api/openapi-spec/swagger.json
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/schema.go
staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

The values in the disk cache mode description are internal enums, they cannot be used in the VM spec and fail validation.
This fix changes them to the allowed values the user can actually set in the spec.
kubectl explain and OpenShift Console show unusable values for Disk cache modes. Those are internal enums and not usable.
```
oc explain vm.spec.template.spec.domain.devices.disks.cache
GROUP:      kubevirt.io
KIND:       VirtualMachine
VERSION:    v1
FIELD: cache <string>
DESCRIPTION:
Cache specifies which kvm disk cache mode should be used.
Supported values are: CacheNone, CacheWriteThrough.     <-------
```
After this PR:
kubectl explain and OpenShift Console show usable values for Disk cache modes.
Fixes # https://issues.redhat.com/browse/CNV-50877
```
```

Fix v1.Disk cache mode values in the description.

---

pkg/virt-handler/heartbeat/heartbeat.go
pkg/virt-handler/vm.go

A small cleanup PR to handle some unhandled errors in virt-handler.
/kind cleanup
```release-note
NONE
```

cleanup: virt-handler to handle unhandled errors

---

cmd/virt-handler/virt-handler.go
pkg/virt-handler/node-labeller/BUILD.bazel
pkg/virt-handler/node-labeller/amd64.go
pkg/virt-handler/node-labeller/arch_labeller.go
pkg/virt-handler/node-labeller/arch_labeller_test.go
pkg/virt-handler/node-labeller/arm64.go
pkg/virt-handler/node-labeller/cpu_plugin.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/node-labeller/node_labeller.go
pkg/virt-handler/node-labeller/node_labeller_test.go
pkg/virt-handler/node-labeller/s390x.go

Manual backport of #14520
automatic cherry-pick failed because arch-labeller wasn't introduced yet for release-1.5
to overcome the conflicts i had to cherry pick [this](https://github.com/kubevirt/kubevirt/pull/13973/commits/2acda9cf945189f3afdf91c547b2b82a0efb2e37) commit as well
```release-note
Enable node-labeller for ARM64 clusters, supporting machine-type labels.
```

[release-1.5] node-labeller: enable node-labeller for ARM64 clusters

---

go.mod
go.sum
pkg/testutils/BUILD.bazel
pkg/testutils/mock_priorityqueue.go
pkg/virt-controller/watch/migration/BUILD.bazel
pkg/virt-controller/watch/migration/migration.go
pkg/virt-controller/watch/migration/migration_test.go
pkg/virt-controller/watch/migration/priorityqueue/BUILD.bazel
pkg/virt-controller/watch/migration/priorityqueue/metrics.go
pkg/virt-controller/watch/migration/priorityqueue/priorityqueue.go
pkg/virt-controller/watch/migration/priorityqueue/workqueue.go
vendor/github.com/google/btree/BUILD.bazel
vendor/github.com/google/btree/LICENSE
vendor/github.com/google/btree/README.md
vendor/github.com/google/btree/btree.go
vendor/github.com/google/btree/btree_generic.go
vendor/modules.txt

Manual backport of https://github.com/kubevirt/kubevirt/pull/14141 and https://github.com/kubevirt/kubevirt/pull/14251 and https://github.com/kubevirt/kubevirt/commit/8d2b7ce6dd4566305529457e3912d88a3ba2a235
> [!NOTE]  
> The first container-runtime version to include priorityqueue is v0.20.0, which also bumps go to 1.23. To avoid bumping the release-1.4 go version (1.22), the code was copy pasted into our tree.
```release-note
Large number of migrations should no longer lead to active migrations timing out
```

[release-1.4] migration controller: use a priority queue to unstarve active migrations

---

tests/storage/migration.go

Extend the volume migration tests, to verify if it possible to extend the destination volumes.
No test which verifies volume migration and disk expansion
After this PR:
Now also the case is verified
Fixes #
```release-note
NONE
```

test: verify volume expansion after a volume migration

---

hack/bazel-test.sh
tools/util/marshaller_test.go

- The `marshaller_test.go` test file failed to compile due to missing parameters in the `NewHandlerDaemonSet` function call.
- Tests under the `tools` directory were not included in the Bazel test runs.
After this PR:
- Fixed the compilation error in `marshaller_test.go` by providing all required arguments to `NewHandlerDaemonSet`.
- Updated the Bazel test script to include the `tools` directory, ensuring coverage of all testable components.
Fixes #12790
```release-note
None

Tools: fix unit-test and ensure execution

---

pkg/virt-handler/hotplug-disk/mount.go
pkg/virt-handler/vm.go

In certain scenarios, volume hotplugging can fail due to a non-fatal error. For example, in filesystem PVCs, the PVC may be unpopulated resulting in an os.ErrNotExist when attempting to mount it.
Previously, such errors didn't get logged, resulting in a deadlock for the AttachedToNode interim state despite having no message to indicate it. 
The aforementioned errors now get emitted as an `HotplugFailed` event on the VMI instead.
Fixes:
- https://issues.redhat.com/browse/CNV-56714
**The following alternatives were considered:**
Several alternatives have been considered:
- It's possible to error out on `ErrNotExist` but that would result in a `SyncError` which indicates a fatal error not being the case in this scenario.
- It's possible to log the …

virt-handler: emit VMI event on non-fatal hotplug failure 

---

tests/virtctl/vnc.go

There is no need to waste RAM, CPU and runtime to run three VMs just in order to test connection to them.
/kind cleanup
```release-note
NONE
```

tests/virtctl: use a single VM for three tests

---

hack/ci/entrypoint.sh
hack/functests.sh
hack/kwok-perftests.sh
hack/perftests.sh
hack/realtime-perftests.sh
tests/clientcmd/command.go
tests/flags/flags.go
tests/kubectl_test.go
tests/libmonitoring/prometheus.go
tests/libnode/node.go
tests/network/port_forward.go
tests/operator/operator.go
tests/replicaset_test.go
tests/reporter/kubernetes.go
tests/virtctl/imageupload.go

As much as we love OpenShift, we don't need to test (or even use) its command line tool `oc` in KubeVirt.
Let us simplify our command line dealings by dropping it.
```release-note
NONE
```

tests: drop flags.KubeVirtOcPath

---

pkg/virt-controller/watch/vmi/OWNERS

The VMI controller logic present inside datavolumes.go and storage.go should be owned by storage sig.
Fixes #
```release-note
NONE
```

Allow sig storage to approve storage related code

---

cmd/sidecars/network-passt-binding/domain/configurator.go
cmd/sidecars/network-passt-binding/domain/configurator_test.go
tests/network/vmi_istio.go

As of `passt` release [2025_02_17.a1e48a0](https://passt.top/passt/tag/?h=2025_02_17.a1e48a0) vhost-user protocol has been implemented. It offers improved network throughput and is also a prerequisite for advanced passt functionality to be implemented in the future. Namely, seamless TCP live migration.
Libvirt added support in version 10.10.0-7.
This commit modifies the DomainXML interface format to start `passt` in vhostuser mode.
In addition, as vhost-user data plane operates in shared memory, `MemoryBacking` of mode `shared` is added.
Unless pre-configured otherwise `<source type='memfd'>` is configured for shared memory. If a different source type is already defined, keep using it. 
Note that this version of net binding plugin cannot be used with older versions of `passt`, since those …

cmd, sidecars, passt: Enable vhost-user

---

hack/linter/lint-paths.txt
pkg/network/vmliveupdate/BUILD.bazel
pkg/network/vmliveupdate/restart.go
pkg/network/vmliveupdate/restart_test.go
pkg/network/vmliveupdate/vmliveupdate_suite_test.go
pkg/virt-controller/watch/vm/BUILD.bazel
pkg/virt-controller/watch/vm/vm.go
tests/network/link_state.go

Currently, the "RestartRequired" condition is added to the VirtualMachine object for every change made to network-related fields.
This is true for both `LiveUpdate` and `Staging` rollout strategies.
Users of the NIC hotplug / hotunplug and link state management features are required to restart their VMs in order for the "RestartRequired" condition to be removed.
Allow the following changes to network-related fields:
- Addition of interfaces and networks (hotplug).
- Changing the interface's state (hotunplug and link state management).
All other changes that are not explicitly mentioned - require restarting the VM in order for them to be applied.
The newly added logic does not depend on the rollout strategy, due to the following reasons:
- NIC hotplug and hotunplug can be performed …

vm ctrl: Allow live changes to network fields

---

pkg/storage/backend-storage/backend-storage.go
pkg/storage/backend-storage/backend-storage_test.go

This PR adds the `cdi.kubevirt.io/applyStorageProfile: "true"` label to PVCs created by the backend storage logic. This allows the PVCs to be mutated by CDI's `WebhookPvcRendering` feature if enabled via feature gate.
This is mainly to support applying a minimum supported PVC size via the storage profile annotation `cdi.kubevirt.io/minimumSupportedPvcSize`, which helps with provisioners that don't support small sizes like the default 10Mi used in KubeVirt.
Fixes # https://github.com/kubevirt/kubevirt/issues/13351
We decided to go with the mutating webhook approach after a long conversation in https://github.com/kubevirt/kubevirt/pull/13800.
```release-note
Label backend PVC to support CDI WebhookPvcRendering
```

Backend storage: Label backend PVC to support CDI WebhookPvcRendering

---

tests/vmi_configuration_test.go

Without double quotes around `dmidecode` output, bash throws: `"bash: [: too many arguments"` when values contain spaces. 
Quoting ensures proper string comparison in expect checks.
Fixes #
```release-note
none
```

tests/vmi_configurations: fix SMBIOS check quoting in test_id:2751

---

automation/test.sh

Like in rehearsal plugin, test-subset doesn't need, 
nor have `PULL_BASE_SHA`, `PULL_PULL_SHA` hence we need to 
ignore it on markdown changed check.
Example 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/14567/test-subset-pull-kubevirt-e2e-k8s-1.31-sig-compute/1920078922117025792
Fixes #
```release-note
None
```

automation: Allow test-subset to run

---

tests/vmi_lifecycle_test.go

**Before this PR**:
While [trying to adopt KubeVirt v1.6.0-alpha.0](https://github.com/kubevirt/hyperconverged-cluster-operator/pull/3502), HCO's smoke test [is failing](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/3502/pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure/1919707675671662592) on the `should prevent scheduling of a pod for a VMI with an unsupported machine type` test.
The test expects scheduling condition message to have this sub string: `"node(s) didn't match Pod's node affinity/selector."`, while the message in HCO test environment is:
`"0/6 nodes are available: 3 node(s) didn't match Pod's node affinity/selector, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: …

[v1.6.0-alpha.0]: Fix test expected error in HCO smoke test

---

tests/README.md
tests/clone_test.go
tests/config_test.go
tests/libmigration/migration.go
tests/libnet/cloudinit/cloudinit.go
tests/libnet/ping.go
tests/libnode/node.go
tests/mdev_configuration_allocation_test.go
tests/replicaset_test.go
tests/sysprep_test.go
tests/tests_suite_test.go
tests/vm_state_test.go
tests/vm_test.go
tests/vmi_configuration_test.go
tests/vmi_lifecycle_test.go
tests/vmi_vsock_test.go

files directly under tests and and nested *lib folders had some misspelling words in them
After this PR:
The words are written correctly in the related files
Will open another PR to address the other files, this way it will be easier to review and monitor those changes.
```release-note
NONE
```

Fix misspellings in tests and nested lib* folders under tests

---

api/openapi-spec/swagger.json
pkg/apimachinery/patch/patch.go
pkg/apimachinery/patch/patch_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter_test.go
pkg/virt-controller/watch/clone/clone_test.go
pkg/virt-controller/watch/clone/vm-target.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/clone/v1beta1/deepcopy_generated.go
staging/src/kubevirt.io/api/clone/v1beta1/types.go
staging/src/kubevirt.io/api/clone/v1beta1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

VMs that have been cloned using VirtualMachineClones couldn't be modified beyond removing/adding labels/annotations. 
After this PR:
It is possible to clone VMs with arbitrary modifications (adding labels/annotations, modifying/adding/deleting values in the specs).
Fixes #14588
```release-note
Added support for custom JSON patches in VirtualMachineClones.
A new property `patches` was added to the VirtualMachineClones CRD.
```

feat(clones): support arbitrary patches on vmclones

---

tests/storage/BUILD.bazel
tests/storage/reservation.go

The checking for the files inside the pr directory is wrong since the pr-helper.socket isn't cleaned-up when the pr-helper container is stopped, e.g if virt-handler pod is stopped or restarted.
Currently, the tests aren't failing because the multipathd.socket exists and makes the check true. However, in cases where the multipathd.socket doesn't exist the pr-helper.socket can still be there since the socket isn't clean-up.
For this reason, we simplify the this tests by checking that virt-handler pods are ready with a single container in it.
The test is buggy and fails when the multipathd.socket doesn't exist on the host
After this PR:
Remove the buggy checks
```release-note
NONE
```

tests: fix test for toggling PR feature gate

---

pkg/virt-api/webhooks/BUILD.bazel
pkg/virt-api/webhooks/amd64.go
pkg/virt-api/webhooks/s390x.go
pkg/virt-api/webhooks/utils.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

Validation of Watchdog based on supported watchdog device model for different architectures I.e it should reject Diag288 watchdog which is not supported on x86 and allow I6300ESB. For s390x it should reject I6300ESB watchdog device which and allow Diag288 device.  
After this PR:
It will reject invalid configuration/devices on the API. So if a user on x86 ask for the s390 specific watchdog device i.e Diag288 it will get rejected and in the same way on s390x it should reject I6300ESB watch device …

Watchdog validation based on watchdog device model for x86 and s390x architectures

---

pkg/virt-handler/vm.go
pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go

Provides graceful deletion for no ACPI guests.
Fixes #
```release-note
No ACPI guests can now receive termination signal through guest agent.
```

[release-1.4] Provide graceful deletion for no ACPI guests

---

pkg/defaults/defaults.go

ARM is yet to test and enable hotplug on launcher side.
Fixes #
The cause of this issue is hotplug code that will be fixed as follow up.
```release-note
ARM: CPU pinning don't panic now
```

Bug fix: Don't default hotplug on ARM

---

manifests/generated/operator-csv.yaml.in
pkg/virt-controller/services/rendercontainer.go
pkg/virt-controller/services/rendercontainer_test.go
pkg/virt-operator/resource/generate/components/daemonsets.go
pkg/virt-operator/resource/generate/components/deployments.go

We use FallbackToLogsOnError in order to enhance
the status of the Pod. This can be helpful in case the node cannot be queried for logs anymore.
Fixes #
```release-note
NONE
```

Add TerminationMessagePolicy to all containers

---

pkg/virt-controller/watch/vmi/vmi.go
pkg/virt-controller/watch/vmi/vmi_test.go

Manual cherry-pick of PR #14613.
The change was adjusted to match the file structure of release-1.5.
Fixes #
```release-note
NONE
```

[release-1.5] VMI: Sort network interfaces to avoid patch flood

---

tests/hotplug/memory.go

Remove domain XML validation from memory hotplug functests.
These are already covered by unit tests [here](https://github.com/kubevirt/kubevirt/blob/82d16c0d3a9774c988278b2a747fc63bd57a4df5/pkg/virt-launcher/virtwrap/converter/converter_test.go#L3095), so we can avoid wasting resources on functionally testing it.
Partially addresses https://github.com/kubevirt/kubevirt/pull/12831
```release-note
NONE
```

Remove domain XML validation from memory hotplug functests

---

pkg/instancetype/find/revision.go
pkg/instancetype/find/spec_test.go
pkg/instancetype/preference/find/BUILD.bazel
pkg/instancetype/preference/find/revision.go
pkg/instancetype/preference/find/spec_test.go
tests/hotplug/BUILD.bazel
tests/hotplug/instancetype.go

We currently check that a given VirtualMachine meets any referenced
preference requirements within the admission webhook.
With the recent move of references to captured ControllerRevisions of
instance types and preferences into the status of the VirtualMachine we
no longer populate `spec.{instancetype,preference}.revisionName`. This
data is now held under
`status.{instancetypeRef,preferenceRef}.controllerRevisionRef` and is
maintained by the core VirtualMachine sync loop.
This causes an issue when checking any referenced preference
requirements within the admission webhook as these references will still
point to ControllerRevisions of different objects when switching between
instance types or preferences during a live update etc.
This change fixes this by ensuring the ControllerRevisions …

instancetype: Only return revision of currently referenced object

---

pkg/virt-api/webhooks/BUILD.bazel
pkg/virt-api/webhooks/amd64.go
pkg/virt-api/webhooks/s390x.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

This PR is manual cherry pick of https://github.com/kubevirt/kubevirt/pull/14599. 
Validation of Watchdog based on supported watchdog device model for different architectures I.e it should reject Diag288 watchdog which is not supported on x86 and allow I6300ESB. For s390x it should reject I6300ESB watchdog device which and allow Diag288 device.
After this PR:
It will reject invalid configuration/devices on the API. So if a user on x86 ask for the s390 specific watchdog device i.e Diag288 it will get rejected and in the same way on s390x it should reject I6300ESB watch device
This checklist is not enforcing, but it's a reminder of items that could …

[release-1.5]Watchdog validation based on watchdog device model for x86 and s390x architectures.

---

Makefile
pkg/network/vmliveupdate/BUILD.bazel
pkg/network/vmliveupdate/restart.go
pkg/network/vmliveupdate/restart_test.go
pkg/network/vmliveupdate/vmliveupdate_suite_test.go
pkg/virt-controller/watch/BUILD.bazel
pkg/virt-controller/watch/vm.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/14602.
The link state management references were removed from the commit message and from `pkg/network/vmliveupdate/restart_test.go`. This is because link state management was introduced in KubeVirt v1.5. 
The PR fixes a bug of requiring the user to restart a VM following any change to network-related fields, including allowed changes such as NIC hotplug and hotunplug.
Fixes #
```release-note
The "RestartRequired" condition is not set on VM objects …
```

[release-1.3] vm ctrl: Allow live changes to network fields

---

hack/lint-paths.txt
pkg/network/vmliveupdate/BUILD.bazel
pkg/network/vmliveupdate/restart.go
pkg/network/vmliveupdate/restart_test.go
pkg/network/vmliveupdate/vmliveupdate_suite_test.go
pkg/virt-controller/watch/vm/BUILD.bazel
pkg/virt-controller/watch/vm/vm.go
tests/network/link_state.go

This is an automatic cherry-pick of https://github.com/kubevirt/kubevirt/pull/14602.
The PR fixes a bug of requiring the user to restart a VM following **any** change to network-related fields, including allowed changes such as NIC hotplug / hotunplug and link state management.
Fixes #
```release-note
The "RestartRequired" condition is not set on VM objects for live-updatable network fields
```

[release-1.5] vm ctrl: Allow live changes to network fields

---

tests/hotplug/memory.go

Enhancing the memory hotplug test to test the actual guest memory amount, not just the pod's resources and conditions.
For more info, see:
* https://github.com/kubevirt/kubevirt/issues/14622
* https://github.com/kubevirt/kubevirt/pull/14625#issuecomment-2853367595
/cc @enp0s3 @orelmisan 
```release-note
NONE
```

Memory hotplug: test actual guest memory

---

tests/vm_test.go

Before this PR: The test used the `Eventually` construct of Ginkgo to poll the VM status until it was in the desired state. However, the polling period of 1 second was missing the intermediate status of `ErrImagePull` (between two occurrences of the `ImagePullBackOff` status) in the second retry of image pull. This resulted in the `Eventually` assertion failure.
After this PR: The test relies on a Watch on the VM resource, so that no status updates are missed.
Fixes #14566
The following tradeoffs were made: At the
The following alternatives were considered: One alternative that was considered involved reducing the polling interval to detect VM status changes more quickly. However, this approach does not resolve the underlying race condition and would result in increased resource usage due …

Watch VM resource for status change instead of polling in tests/vm_test.go

---

pkg/instancetype/find/revision.go
pkg/instancetype/find/spec_test.go
pkg/instancetype/preference/find/BUILD.bazel
pkg/instancetype/preference/find/revision.go
pkg/instancetype/preference/find/spec_test.go
tests/hotplug/BUILD.bazel
tests/hotplug/instancetype.go

This is a manual backport of #14682 thanks to a conflict caused by
https://github.com/kubevirt/kubevirt/commit/9436b9a38f65631a43a0baa8ed4614ff9a48e1cf not being present on release-1.5
We currently check that a given VirtualMachine meets any referenced
preference requirements within the admission webhook.
With the recent move of references to captured ControllerRevisions of
instance types and preferences into the status of the VirtualMachine we
no longer populate `spec.{instancetype,preference}.revisionName`. This
data is now held under
`status.{instancetypeRef,preferenceRef}.controllerRevisionRef` and is
maintained by the core VirtualMachine sync loop.
This causes an issue when checking any referenced preference
requirements within the admission webhook as these references will still …

[release-1.5] instancetype: Only return revision of currently referenced object

---

hack/lint-paths.txt
pkg/network/vmliveupdate/BUILD.bazel
pkg/network/vmliveupdate/restart.go
pkg/network/vmliveupdate/restart_test.go
pkg/network/vmliveupdate/vmliveupdate_suite_test.go
pkg/virt-controller/watch/vm/BUILD.bazel
pkg/virt-controller/watch/vm/vm.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/14602.
The link state management references were removed from the second commit message and from `pkg/network/vmliveupdate/restart_test.go`. This is because link state management was introduced in KubeVirt v1.5. 
The PR fixes a bug of requiring the user to restart a VM following any change to network-related fields, including allowed changes such as NIC hotplug and hotunplug.
Fixes #
```release-note
The "RestartRequired" condition is not set on VM …
```

[release-1.4] vm ctrl: Allow live changes to network fields

---

pkg/virt-controller/watch/vmi/vmi.go
pkg/virt-controller/watch/vmi/vmi_test.go

Manual cherry-pick of PR https://github.com/kubevirt/kubevirt/pull/14613.
The change was adjusted to match the file structure of release-1.4.
Fixes #
```release-note
NONE
```

[release-1.4] VMI: Sort network interfaces to avoid patch flood

---

docs/conformance.md
tests/README.md
tests/conformance/conformance.go
tests/container_disk_test.go
tests/network/networkpolicy.go
tests/network/primary_pod_network.go
tests/network/services.go
tests/network/vmi_networking.go

Cherry-pick of https://github.com/kubevirt/kubevirt/pull/14509
The preferred way of labeling conformance tests is now using the
decorator. 
Reflect that in the conformance test suite, e2e tests and the documentation.
Fixes #
```release-note
Network conformance tests are now marked using the `Conformance` decorator. Use `--ginkgo.label-filter '(sig-network && conformance)` to select them.
```

[release-1.4] Replace use of [Conformance] with the Conformance decorator

---

tests/virt_control_plane_test.go

This PR just fixes a typo in the name of a test entree that tries to evict of single replica virt-api component
Fixes #
```release-note
none
```

virt_control_plane_test.go: fix typo in the test name

---

tests/monitoring/vm_monitoring.go

VM alerts tests fail with VMs stuck in scheduling
After this PR:
Tests work correctly
Fixes #
```release-note
none
```

Wait for alerts to stop firing after restore scales in e2e tests

---

docs/conformance.md
tests/README.md
tests/conformance/conformance.go
tests/container_disk_test.go
tests/decorators/decorators.go
tests/network/networkpolicy.go
tests/network/primary_pod_network.go
tests/network/services.go
tests/network/vmi_networking.go

The preferred way of labeling conformance tests is now using the
decorator.
Reflect that in the conformance test suite, e2e tests and the documentation.
See https://github.com/kubevirt/kubevirt/pull/14509 for more details.
Note that release-1.3 doesn't have lots of conformance tests as 1.4+.
Fixes #
```release-note
Network conformance tests are now marked using the `Conformance` decorator. Use `--ginkgo.label-filter '(sig-network && conformance)` to select them.
```

[release-1.3] Replace use of [Conformance] with the Conformance decorator

---

tests/storage/datavolume.go
tests/storage/export.go
tests/storage/hotplug.go
tests/storage/migration.go
tests/storage/reservation.go
tests/storage/restore.go
tests/storage/snapshot.go

files under tests storage had some misspelling words in them
After this PR:
The words are written correctly in the related files
Related PR:
Related PR:
- https://github.com/kubevirt/kubevirt/pull/14662
- https://github.com/kubevirt/kubevirt/pull/14688
- https://github.com/kubevirt/kubevirt/pull/14750
- https://github.com/kubevirt/kubevirt/pull/14751
```release-note
NONE
```

Fix misspellings in tests/storage

---

pkg/libvmi/network.go
pkg/network/setup/netpod/BUILD.bazel
pkg/network/setup/netpod/netpod.go
pkg/network/setup/netpod/netpod_test.go
pkg/virt-controller/watch/vm/vm.go
pkg/virt-controller/watch/vm/vm_test.go
tests/hotplug/cpu.go

Currently, KubeVirt requires a restart of the VM in case CPU hotplug is requested with when NetworkInterfaceMultiQueue knob enabled.
Some background:
A tap device can be created with or without multi-queue support.
virt-handler creates tap devices with multi-queue support if the requested queue count is greater than one.
When the `NetworkInterfaceMultiQueue` knob is enabled, for interfaces using the `virtio` model, virt-handler can create the tap device with multi-queue support.
The number of queues is dependent on the vCPU topology:
sockets * cores * threads.
Note: This is not applicable for SR-IOV devices.
When creating a VM with one socket, one core and one thread and
the NetworkInterfaceMultiQueue knob is enabled, the tap devices are
not configured for multi-queue.
When a CPU hotplug …

Allow CPU hotplug with net multi-queue

---

tests/migration/host_model.go
tests/migration/migration.go
tests/operator/operator.go

files under tests [migration, operator] had some misspelling words in them
After this PR:
The words are written correctly in the related files
Related PR:
- https://github.com/kubevirt/kubevirt/pull/14662
- https://github.com/kubevirt/kubevirt/pull/14688
- https://github.com/kubevirt/kubevirt/pull/14731
- https://github.com/kubevirt/kubevirt/pull/14750
```release-note
NONE
```

Fix misspellings in tests folders migration, operator

---

tests/network/sriov.go

Following PR https://github.com/kubevirt/kubevirt/pull/8226, virt-launcher uses a mechanism based on downward API in order to infer the PCI addresses of SR-IOV devices.
There is currently a fallback on an older mechanism that uses environment variables from:
- VMI controller [1]
- SR-IOV device plugin
in order to infer the PCI addresses of SR-IOV devices.
In preparation for removing the older mechanism, remove the assertions asserting the existence of the environment variables inside virt-launcher's `compute` container, as they observe an implementation detail.
[1] https://github.com/kubevirt/kubevirt/blob/b020b9e114150b73d5ac716cfb70c9e7abbdfc7c/pkg/virt-controller/services/template.go#L454-L457
Fixes #
Links …

e2e, SR-IOV: Rm env var assertions on virt-launcher

---

.github/workflows/label_approved_veps.yaml
automation/label-approved-veps.py

This PR adds a new GitHub action workflow to label PRs that are tied to an approved VEP
These PRs are the project's priority for the upcoming release and should get a large portion of the community review bandwidth
Labeling these PRs should allow the reviewers to find them easily. 
This PR depends on https://github.com/kubevirt/project-infra/pull/4163
```release-note
Node
```

Add VEP approval label GitHub action workflow

---

pkg/storage/admitters/vm-storage-status.go
tests/storage/restore.go

A recent fix enabled restoring VMs with a RunStrategy other than Halted.
However, when the VM has associated volumes being restored, the VM spec is
updated as part of the process. This causes a failure in the vm restore
because when updating the vm in the restore process the webhook detects
a spec change and previously only allowed it if the RunStrategy remained Halted.
Now that all RunStrategy values (except Always) are permitted, the restore
process should only ensure that the RunStrategy itself hasn't been modified
during the restore, rather than enforcing a specific value.
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-59294 …

VMRestore+VM admission webhook: fix check of update VM during restore

---

.github/workflows/label_approved_veps.yaml

This will allow the label_approved_veps GitHub Action to use a dedicated token
```release-note
NONE
```

Let the label_approved_veps github action to use a PAT

---

cmd/virt-freezer/BUILD.bazel
cmd/virt-freezer/main.go
cmd/virt-freezer/virt-freezer.go
cmd/virt-freezer/virt-freezer_suite_test.go
cmd/virt-freezer/virt-freezer_test.go
tests/storage/BUILD.bazel
tests/storage/snapshot.go

When running the virt-freeze hook in velero backups if the vm is paused at the time of the backup, the hook returns an error, the backup partially fails and the vm is not in the backup.
Testing of the hook is done with e2e test.
After this PR:
When running the virt-freeze hook in velero backups if the vm is paused at the time of the backup, the hook prints that the vm domain is not running and skips the freeze, the backup continues with backing the vm.
E2E tests of the hook is removed, the hook is tested with UTs.
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-61566
```release-note
virt-Freeze: skip freeze if domain is not in running state
```

virt-Freeze: skip freeze if domain is not in running state

---

pkg/monitoring/metrics/virt-controller/vmistats_collector.go
pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go

Add to the kubevirt_vm/i_vnic_info metrics,  the interface "model" (If exists) and which model it asks for. One of: e1000, e1000e, igb, ne2k_pci, pcnet, rtl8139, virtio.
kubevirt_vm/i_vnic_info metrics did not include "model" label
After this PR:
kubevirt_vm/i_vnic_info metrics includes "model" label
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-57901
example output for the metrics:
```release-note
none
```

Add "model" label to kubevirt_vm/i_vnic_info metrics

---

pkg/virt-controller/watch/vmi/BUILD.bazel
pkg/virt-controller/watch/vmi/storage.go
pkg/virt-controller/watch/vmi/vmi_test.go

Online volume expansion can fail when the provisioner allocates a fixed large capacity (e.g. 50Gi), causing small increases in requested size to be ignored by our controller requeuing logic, which only accounts for `Capacity` increases.
This PR fixes the issue by requeuing the affected VMIs when their PVC's requested size changes, ensuring the expansion is applied.
Fixes # https://issues.redhat.com/browse/CNV-58023
```release-note
Bugfix: Fix online expansion by requeuing VMIs on PVC size change
```

Volume Expansion: Fix online expansion by requeuing VMIs on PVC size change

---

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
tests/storage/restore.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/14733
```release-note
NONE
```

[release-1.4] VMRestore+VM admission webhook: fix check of update VM during restore

---

tests/monitoring/vm_monitoring.go

Flaky monitoring test [1] satisfies the quarantine criteria.
[1]: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2025-05-26.html#%5bsig-monitoring%5dVM%20Monitoring%20VM%20metrics%20that%20are%20based%20on%20the%20guest%20agent%20%5btest_id%3a11267%5dshould%20have%20kubevirt_vmi_info%20correctly%20configured%20with%20guest%20OS%20labels
After this PR:
Flaky test with test_id:11267 is quarantined.
Fixes #
/cc @machadovilaca @sradco 
```release-note
```

fix(quarantine,monitoring): kubevirt_vmi_info test

---

pkg/virt-controller/watch/vmi/BUILD.bazel
pkg/virt-controller/watch/vmi/vmi.go
pkg/virt-controller/watch/vmi/vmi_test.go

This is a manual backport of https://github.com/kubevirt/kubevirt/pull/14695. 
```release-note
Bugfix: Fix online expansion by requeuing VMIs on PVC size change
```

[release-1.5] Volume Expansion: Fix online expansion by requeuing VMIs on PVC size change

---

tests/storage/migration.go

Login into the VM after volume migration ensure that the bootable disk hasn't been corrupted during the migration.
```release-note
NONE
```

tests: add login into the VM after volume migration and some fixes/refactoring

---

go.mod
go.sum
go.work.sum
pkg/monitoring/metrics/virt-controller/vmistats_collector.go
pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/registry.go
vendor/github.com/machadovilaca/operator-observability/pkg/testutil/BUILD.bazel
vendor/github.com/machadovilaca/operator-observability/pkg/testutil/fetch_metrics.go
vendor/modules.txt

kubevirt_vmi_info and kubevirt_vm_info should not report <none> for missing labels. Like workload, flavor, instance_type, and preference.
This complicates the dashboards, since we don't want to show `<none>` value for labels that don't exist.
After this PR:
We only report labels if we have data for them
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-61830
```release-note
Replace metric labels' none values with empty values
```

Replace metric labels' none values with empty values

---

pkg/util/util.go
pkg/virt-controller/services/renderresources.go
pkg/virt-handler/non-root.go

Currently, when the cluster is configured with the `useEmulation` knob enabled, a VM using a virtio NIC fails to start due to the virt-handler attempting to claim ownership on the `/dev/vhost-net` device that doesn't exist. 
```release-note
Fix network setup when emulation is enabled
```

virt-handler, net setup: Account for emulation

---

pkg/controller/expectations.go
pkg/virt-controller/watch/vmi/lifecycle.go
pkg/virt-controller/watch/vmi/vmi.go
pkg/virt-handler/vm.go

Controllers set an expectation to 1 when updating an object and lower by 1 in the update callback of the informer for that object.
It means that external updates of the object will lower expectations below 0.
That is fine because negative expectations are still considered satisfied, and the next `set` will reset to 1 (if `raise` was used instead of `set` we'd have a problem).
Still, it makes more sense to clean this up and potentially avoid integer overflow in extreme cases.
After this PR:
Expectations won't go below 0.
Fixes #
Approvers are expected …

expectations: set to 0 instead of lowering by 1 in "binary" use-cases

---

pkg/virtctl/ssh/native.go
pkg/virtctl/ssh/ssh.go

When using the ssh command in tests before, it did not properly pick up the stream redirections from cobra.Command.
Instead of directly using os.* streams, ask the ginkgo command for the configured stream.
This is more correct and helpful in e2e testing when using cobra.Commands.
```release-note
None
```

[virtctl] Properly pick up cobra onfigured streams in ssh command

---

pkg/storage/backend-storage/backend-storage.go
pkg/storage/utils/volumes_test.go
pkg/virt-controller/watch/migration/migration.go

This PR updates the `CurrentPVCName` function in the backend storage logic to improve the handling of PVCs with different naming conventions.
Instead of requiring the PVC name to start with a specific prefix, the function now checks for the expected substring anywhere in the name. This fixes issues with restored PVCs that used a different prefix in their name.
Fixes # https://issues.redhat.com/browse/CNV-60685
Alternative solution to https://github.com/kubevirt/kubevirt/pull/14641. That solution sets a more generic and cleaner volume name, which I prefer, but carries a risk of introducing bugs after upgrade. This PR is simpler and safer, especially for VMs relying on the older behavior.
```release-note
Bugfix: Update backend-storage logic so it works with PVCs with non-standard naming …
```

Backend storage: Update backend logic so it works with restored PVCs

---

pkg/monitoring/metrics/virt-handler/collector/collector.go
pkg/virt-handler/cmd-client/client.go
pkg/virt-handler/cmd-client/client_test.go
pkg/virt-handler/dmetrics-manager/dmetrics-manager.go
pkg/virt-handler/isolation/detector.go
pkg/virt-handler/rest/lifecycle.go
pkg/virt-handler/vm.go

Current FindSocketOnHost is actually ignoring a host all together and would try to find any Pod. FindSocketWithHost now takes host as argument "host" and filters base on it. A FindSocket now automatically provides the host based on "NODE_NAME" env variable.
Fixes #
```release-note
NONE
```

Introduce FindSocket

---

WORKSPACE
hack/bootstrap.sh
hack/rpm-deps.sh
rpm/BUILD.bazel

This PR enables support for the `virtio-vga` video device model in `QEMU` for `amd64` architectures. When the `virtio` video model is specified in the VM Domain via libvirt, the backend probes QEMU capabilities to determine which `virtio` video device is supported. If `virtio-vga` is available, it is now selected as the preferred device. Otherwise, we fall back to `virtio-gpu` or `virtio-gpu-pci` if `virtio-vga` is not supported.
This PR ensures that the required `QEMU` capabilities for `virtio-vga` are available and recognized on `amd64` systems, allowing the device to be used reliably when requested.
- Even when specifying `virtio` as the video model, QEMU will fall back to `virtio-gpu` due to missing capability detection or support.
After this PR:
- `virtio` is now the …

Add virtio-vga video driver to launcher_base_amd64 image

---

pkg/virt-operator/resource/generate/components/crds.go

Fixes category for clusterscoped migrationpolicy crd
The all category should typically be set only on namespaced resources, otherwise a kubectl get all will fail to list all resources in a given namespace if a user has only permissions to that single namespace.
Migration policies are cluster scoped, while all other resources with the all category are only namespaced
Before this PR, migrationpolicy have category all which is not relevant for scope: cluster
oc get crd -o json | jq -rM '.items[] | [.metadata.name, .spec.names?.categories[]?] | @tsv' | grep -w all
dataimportcrons.cdi.kubevirt.io Namespaced      all
.....
migrationpolicies.migrations.kubevirt.io        Cluster all 
After this fix, we should not see migration policy when use 
oc get crd -o json | jq -rM '.items[] | …

Fix the category for cluster scoped migrationpolicy crd

---

automation/test.sh

The SEV test lanes are in the process of being reintroduced - add a filter for the SEV to automation/test.sh so that SEV prow jobs can make use of this script.
```release-note
NONE
```

automation: Add filter for SEV test lanes

---

OWNERS_ALIASES

Following https://github.com/kubevirt/community/pull/406, this PR moves @alicefr to become an emeritus approver.
This is mainly needed for the bot to avoid assigning her to new PRs.
@alicefr let me take this opportunity to thank you for all of your contributions!
Hope to still see your username pops up here every once in a while :)
```release-note
NONE
```

Move alicefr to become an emeritus approver

---

hack/build-go.sh

Starting from https://github.com/kubevirt/kubevirt/pull/14485 the generated_mock stuffs in the staging folder are not generated anymore, due to an error like:
`go: ignoring package kubevirt.io/client-go/log which exists in the vendor directory but is missing from vendor/modules.txt. To sync the vendor directory run go work vendor.`
Passing the client-go and api subpackages solves the issue, also avoiding creating temporary links.
```release-note
NONE
```

Fix mock generation in staging folder

---

tests/storage/migration.go

Picking up @alicefr effort in https://github.com/kubevirt/kubevirt/pull/13725
This is crucial since the total runtime of the storage lane is close to 3h.
Fixes #
```release-note
NONE
```

tests: run volume migration tests in parallel

---

pkg/virtctl/ssh/native_unsupported.go

This fixes builds with the excludenative tag, it should have been included in 3365c3e655bfebb91da76e8fdb421d9207cd250e.
```release-note
None
```

fix(virtctl): Update nativeSSH signature for unsupported platform

---

automation/test.sh
tests/testsuite/kubevirtresource.go

Introduce `KUBEVIRT_VERBOSITY` env var, which allows setting pods verbosity in e2e tests.
Example:
`export KUBEVIRT_VERBOSITY="virtLauncher:3,virtHandler:3"`
Current implementation doesn't merge the config, but overrides it.
It is fine because the default verbosity is empty.
This will allow users / plugins to set the desired verbosity.
Beside that:
Increase sriov-kind virt-handler and virt-launcher logs verbosity, 
in order to understand better about what happens with reattach event, before we refactor it.
For more info see:
https://github.com/kubevirt/kubevirt/pull/14757
Note that in any case, this is good to have in general, and doesn't affect production code, only CI.
Fixes #
Links to places where the …

e2e: Introduce KUBEVIRT_VERBOSITY and increase logs verbosity for kind-sriov

---

pkg/virtctl/vmexport/BUILD.bazel
pkg/virtctl/vmexport/vmexport.go
pkg/virtctl/vmexport/vmexport_test.go

Manual cherry pick of https://github.com/kubevirt/kubevirt/pull/12857
```release-note
BugFix: Fail to create VMExport via virtctl vmexport create
```

[release-1.2] Stop setting blockOwnerDeletion on vmexport secret owner ref

---

pkg/virt-controller/watch/vm/BUILD.bazel
pkg/virt-controller/watch/vm/vm.go
pkg/virt-controller/watch/vm/vm_test.go

Manual backport of  https://github.com/kubevirt/kubevirt/pull/14842
Conflict on import. It was needed to  add
```
testutils.UpdateFakeKubeVirtClusterConfig(kvStore, &v1.KubeVirt{
Spec: v1.KubeVirtSpec{
Configuration: v1.KubeVirtConfiguration{
VMRolloutStrategy: &liveUpdate,
},
},
})
````
```release-note
NONE
```

[release-1.5] Disable CPU hotplug on ARM

---

staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
staging/src/kubevirt.io/client-go/kubevirt/typed/core/v1/fake/fake_virtualmachineinstance.go
staging/src/kubevirt.io/client-go/kubevirt/typed/core/v1/virtualmachineinstance.go

VMI doesn't have status subresource enabled.
The `UpdateStatus` method is generated by the client-gen if the API has the `.Status` field.[1]
This can be avoided by using `+genclient:noStatus` tag.
[1] https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/generating-clientset.md
```release-note
NONE
```

Avoid vmi.`UpdateStatus` method generation

---

pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

VMIs that failed a post-copy migration may end up considered as having successfully completed (i.e. clean shutdown).
This is especially problematic for RestartOnFailure VMs, which may not restart after a failed post-copy migration.
After this PR:
VMIs that failed a post-copy migration are marked as failed.
Fixes #
```release-note
Failed post-copy migrations now always end in VMI failure
```

virt-handler: fail VMIs that failed a post-copy migration

---

tests/compute/vm_lifecycle.go

This test looks to have been removed from quarantine too soon[1] - the test continues to flake in the presubmits and qualifies for quarantining with over 5% impact in the last 14 days[2][3].
Return this test to quarantine.
[1] https://github.com/kubevirt/kubevirt/pull/14463
[2] https://search.ci.kubevirt.io/?search=test_id%3A3007&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
[3] https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2025-06-11.html#%5bsig-compute%5d%20%5brfe_id%3a1177%5d%5bcrit%3amedium%5d%20VirtualMachine%20%5btest_id%3a3007%5d%20Should%20force%20restart%20a%20VM%20with%20terminationGracePeriodSeconds%3e0
The following …

e2e,compute: Quarantine flaky terminationGracePeriod test

---

tests/operator/operator.go

Test
`[Serial][sig-operator]Operator [Serial] Seccomp configuration VirtualMachineInstance Profile with VirtualMachineInstance Profile set to custom should use localhost` shows a high flakiness rate [1] .
Example: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/14848/pull-kubevirt-e2e-k8s-1.27-sig-operator-1.2/1931614230277001216
[1]: https://search.ci.kubevirt.io/?search=%5C%5BSerial%5D%5C%5Bsig-operator%5DOperator+%5C%5BSerial%5D+Seccomp+configuration+VirtualMachineInstance+Profile+with+VirtualMachineInstance+Profile+set+to+custom+should+use+localhost&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Test
`[Serial][sig-operator]Operator [Serial] Seccomp configuration VirtualMachineInstance …

fix(quarantine): operator custom should use localhost

---

pkg/virt-controller/services/renderresources.go

This change fixes an issue introduced in [#10566](https://github.com/kubevirt/kubevirt/pull/10566).
for VMIs with dedicated CPU or QoS Guaranteed
VMIs with dedicated CPU or QoS Guaranteed get an extra 100Mi memory overhead. This overhead was added after applying the additionalOverheadRatio, so it was not included in the ratio calculation.
Now the extra 100Mi is added before applying the ratio, so the total overhead is calculated correctly.
```release-note
NONE
```

bugFix: Fix overhead calculation

---

pkg/virt-handler/node-labeller/node_labeller.go

This is a quick fix to restore the SEV and realtime functionality. 
Kubevirt expects these labels to have a value to schedule these VMs properly.
```release-note
None
```

node-labeller: SEV and realtime labels should have a value

---

pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/14793
```release-note
Failed post-copy migrations now always end in VMI failure
```

[release-1.5] virt-handler: fail VMIs that failed a post-copy migration

---

.github/workflows/label_approved_veps.yaml
automation/label-approved-veps.py

This PR reworks the Github action that is responsible for labeling VEP approved PRs
The goal is to more accurately determine if a VEP is prioritized for the current release cycle.
Previously, the script identified a PR as VEP approved if its description referenced a VEP issue in the kubevirt/enhancements repo.
It then checked if there was any merged PR in kubevirt/enhancements that mentioned this VEP issue.
With this logic we couldn't determine if the VEP was approved for the current release cycle.
After this PR:
In this PR, we are going to rely on a VEP issue status in the per-release VEP [tracker](https://github.com/orgs/kubevirt/projects/15)  using the GraphQL API.
It checks if any of the referenced VEP issues are present and have a `Tracked` status.
```release-note …
```

Label VEP tied PRs based on the KubeVirt project status

---

automation/test.sh

The setting of the provider was missed in https://github.com/kubevirt/kubevirt/pull/14861
This causes the lane to fail as the expected provider does not exist[1]
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/4128/rehearsal-pull-kubevirt-e2e-kind-1.31-sev/1935275606530854912#1:build-log.txt%3A119
```release-note
NONE
```

automation,sev: fix setting KUBEVIRT_PROVIDER for sev e2e lanes

---

tests/vm_test.go

Reverts https://github.com/kubevirt/kubevirt/pull/14851
We found that this was creating an increase in the flakiness: https://search.ci.kubevirt.io/?search=event+type+Warning%2C+reason+%3D+Stopped&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
```release-note
none
```
/priority critical-urgent
/kind flake

Revert "Remove GetRunningVMIDomainSpec from vm_test.go tests" 

---

pkg/virt-controller/watch/vm/vm.go

/cc @mhenriks
/kind cleanup
Noticed this in a local kubevirtci cluster, nothing important.
```
$ virtctl create vm --volume-import type:registry,url:docker://quay.io/containerdisks/fedora:latest,name:fedora,size:10Gi --preference fedora --instancetype u1.medium --name example | kubectl apply -f -
[..]
$ kubectl logs -l kubevirt.io=virt-controller -n kubevirt | grep "Declarative hotplug"
selecting podman as container runtime
{"component":"virt-controller","kind":"","level":"info","msg":"Declarative hotplug volumes are not enabled, skipping","name":"example","namespace":"default","pos":"vm.go:3337","timestamp":"2025-06-20T11:58:37.986052Z","uid":"e2ba7f28-84cf-4bdb-9019-4113422141a0"}
{"component":"virt-controller","kind":"","level":"info","msg":"Declarative hotplug volumes are not enabled, …
```

controller: Remove excessive info logging regarding volume hotplug

---

tests/migration/eviction_strategy.go

Test `[rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system][sig-compute] Live Migration with a live-migrate eviction strategy set with multiple VMIs with eviction policies set [release-blocker][test_id:3245]should not migrate more than two VMIs at the same time from a node` [1] has an impact of more than 33% [2].
[1]: https://github.com/kubevirt/kubevirt/blob/08da367a38d82a2201e59d327e83ee3d8f78dc40/tests/migration/eviction_strategy.go#L424
[2]: https://search.ci.kubevirt.io/?search=%5C%5Brelease-blocker%5D%5C%5Btest_id%3A3245%5Dshould+not+migrate+more+than+two+VMIs+at+the+same+time+from+a+node&maxAge=72h&context=1&type=bug%2Bissue%2Bjunit&name=pull.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
[3]: https://github.com/kubevirt/kubevirt/blob/main/docs/quarantine.md …

quarantine(migration): test_id:3245

---

tests/storage/declarative-hotplug.go
tests/storage/hotplug.go
tests/storage/restore.go

following some (great) dev cycles, we're encountering several flakes
that get in the way of PRs merging.
let's put those in quarantine for now track via issues.
[stop start hotplug](https://search.ci.kubevirt.io/?search=but+still+unpluggable+after+restart&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)
[eject](https://search.ci.kubevirt.io/?search=Declarative+Hotplug+Inject%2FEject+CD-ROM+Should+inject%2C+swap%2C+and+eject+a+CD-ROM&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)
[with volume restore policy InPlace and DV (not template)](https://search.ci.kubevirt.io/?search=with+volume+restore+policy+InPlace+and+DV&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&e …

tests: quarantine flaky sig-storage tests

---

pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/14961
```release-note
BugFix: Can't LiveMigrate Windows VM after Storage Migration from HPP to OCS
```

[release-1.5] Update migrationmethod on VMI regardless of condition existence

---

pkg/virt-api/rest/objectgraph.go
pkg/virtctl/BUILD.bazel
pkg/virtctl/objectgraph/BUILD.bazel
pkg/virtctl/objectgraph/OWNERS
pkg/virtctl/objectgraph/objectgraph.go
pkg/virtctl/objectgraph/objectgraph_suite_test.go
pkg/virtctl/objectgraph/objectgraph_test.go
pkg/virtctl/root.go
staging/src/kubevirt.io/client-go/kubevirt/typed/core/v1/fake/fake_virtualmachine_expansion.go
staging/src/kubevirt.io/client-go/kubevirt/typed/core/v1/fake/fake_virtualmachineinstance_expansion.go
staging/src/kubevirt.io/client-go/testing/actions.go

Follow-up for https://github.com/kubevirt/kubevirt/pull/14807.
This PR adds a simple virtctl command that prints the Object Graph of a VM or VMI.
```sh
virtctl objectgraph my-vm
virtctl objectgraph my-vmi --vmi
virtctl objectgraph my-vm --include-optional
virtctl objectgraph my-vm --selector="kubevirt.io/dependency-type=storage,kubevirt.io/dependency-type=compute"
``` 
**VEP 41:** https://github.com/kubevirt/enhancements/issues/41
```release-note
Add virtctl objectgraph command
```

VEP 41: Add virtctl objectgraph command

---

hack/build-go.sh

Since the transition to go workspace mode in KubeVirt[1] make clean has been broken due to an incompatibility between go clean with `-mod=vendor` and go.work.
This PR unsets `-mod=vendor` if the target is set to clean.
[1] https://github.com/kubevirt/kubevirt/pull/14485
```release-note
NONE
```

hack/build-go: fix make clean

---

pkg/instancetype/apply/memory_test.go
tests/instancetype/instancetype.go

This PR adds a functional tests to verify that a VirtualMachineInstance (VMI) correctly applies an instancetype with Memory.OvercommitPercent set to 80%, without using a preference and with a preference with .spec.requirements.
```release-note
None
```

Add test for applying 80% memory overcommit from instancetype to VMI

---

pkg/network/controllers/vm.go
pkg/network/controllers/vm_test.go

Currently, VM's absent interfaces which are not present in the VMI.Status.Interfaces slice, are removed.
This is problematic in the following scenario:
1. The dynamic-networks-controller is not deployed.
2. A VM is running with an interface connected to pod network.
3. A secondary interface is hotplugged and the VM is not migrated.
4. The interface above is marked for hot-unplug by setting its state field to `absent`.
In this case, the interface and its matching network are removed from the VM spec, but are kept in the VMI spec.
This is because, the controller does not set the VMI's interface state as absent, as in this scenario the naming scheme is unknown and assumed to be ordinal, thus preventing hot-unplug.
Adjust the logic for clearing VM interfaces and their matching networks to …

net, vm ctrl: Adjust VM's detached iface clearing logic

---

pkg/monitoring/metrics/virt-handler/domainstats/unit_converter.go
pkg/monitoring/metrics/virt-handler/domainstats/vcpu_metrics.go
pkg/monitoring/metrics/virt-handler/domainstats/vcpu_metrics_test.go

Before this PR: invoke `microsecondsToSeconds` in `kubevirt_vmi_vcpu_seconds_total`
After this PR: invoke `nanosecondsToSeconds` in `kubevirt_vmi_vcpu_seconds_total`
Fixes https://github.com/kubevirt/kubevirt/issues/13731
```release-note
Changed the time unit conversion in the kubevirt_vmi_vcpu_seconds_total metric from microseconds to nanoseconds.
```

kubevirt_vmi_vcpu_seconds_total should use nanosecondsToSeconds

---

cmd/virt-handler/virt-handler.go
docs/observability/metrics.md
pkg/monitoring/metrics/virt-handler/BUILD.bazel
pkg/monitoring/metrics/virt-handler/machine_type.go
pkg/monitoring/metrics/virt-handler/machine_type_test.go
pkg/monitoring/metrics/virt-handler/metrics.go
pkg/virt-handler/node-labeller/node_labeller.go
pkg/virt-handler/node-labeller/node_labeller_test.go
tests/infrastructure/prometheus.go
tests/monitoring/metrics.go
tools/doc-generator/doc-generator.go

This PR introduces two changes:
- Refactors the node-labeller controller to accept `[]libvirtxml.CapGuestMachine` as an argument instead of `[]libvirtxml.CapGuest`.
- Adds a new dedicated metric to expose the list of deprecated machine types per each node in the KubeVirt cluster.
KubeVirt did not have a dedicated metric to expose information about the deprecated machine types per each node in the cluster.
After this PR:
A dedicated metric is now available, listing all deprecated machine types per node that can be used for alerting purposes.
Fixes #
This lays the groundwork for future alerting features. It will help detect when virtual machines are provisioned using outdated or deprecated machine types that require upgrades.
```release-note
None
```

Add kubevirt_node_deprecated_machine_types metric

---

pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/14961
```release-note
BugFix: Can't LiveMigrate Windows VM after Storage Migration from HPP to OCS
```

[release-1.4] Update migrationmethod on VMI regardless of condition existence

---

tests/container_disk_test.go

since the feature is not expected to be enabled by default before 1.34.
Also add a login check after VM migration to ensure the VMI remains functional with ImageVolume.
```release-note
NONE
```

Skip the ImageVolume e2e test if K8s < 1.35

---

api/openapi-spec/swagger.json
manifests/generated/kv-resource.yaml
pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
pkg/virt-config/configuration.go
pkg/virt-config/configuration_test.go
pkg/virt-config/virt-config.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.KubeVirt.json
staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.KubeVirt.yaml
staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/vmi_configuration_test.go

github  Issue : https://github.com/kubevirt/kubevirt/issues/14953
**What this PR does**
KubeVirt configuration lacked support for the s390x architecture in the ArchitectureConfiguration struct. As a result, values     like MachineType, OVMFPath, and EmulatedMachines could not be set for s390x, and logic defaulted to hardcoded fallbacks.
Added s390x support in ArchConfiguration and ArchSpecificConfiguration
Integrated s390x with GetMachineType, GetEmulatedMachines, and GetOVMFPath
Updated tests to cover s390x scenarios for machine type, emulated machines, and CPU model behavior
Ensured consistency with existing amd64, arm64, and ppc64le configuration patterns
```release-note
Added support for architecture-specific configuration of `s390x` (IBM Z) in …
```

IBM  s390x architecture configuration

---

pkg/ephemeral-disk-utils/utils.go
pkg/host-disk/host-disk.go
pkg/host-disk/host-disk_test.go
tests/storage/storage.go

In DiskOrCreate mode, when the file exists, host-disk changes its owner.
host-disk only changes the owner of the files it creates.
```release-note
HostDisk: KubeVirt no longer performs chown/chmod to compensate for storage that doesn't support fsGroup
```

host-disk: only chown files we created

---

pkg/storage/snapshot/restore.go
pkg/storage/snapshot/restore_test.go
tests/storage/restore.go

This PR fixes flaky tests at https://github.com/kubevirt/kubevirt/issues/14982
Flaky tests on VM restores with VolumeRestorePolicy InPlace
Hopefully no flaky test
My analysis of the flaky test is a possible condition where the PVC deletion may error out, preventing the status of the VMRestore to be updated with the datavolume. But on the next resync cycle, the PVC got deleted because it was held by a finalizer (VM still up, Pod still up, anything that may slow down PVC deletion). We enter the bit of code where DataVolume is expected eventhough it was never set.
To fix this, we exit the reconciliation when setting the property, and we re-enter the reconciliation …

fix(vmrestore): volumerestorepolicy inplace flaky tests

---

automation/test.sh

Currently, NIC hotplug / unplug can be performed via migration or in-place.
Note: SR-IOV hotplug is always migration-based.
In-place hotplug requires Multus v4 (in the thick plugin configuration) and the dynamic-networks-controller.
Most SIG-network CI lanes, however, use Multus v3 without the dynamic-networks-controller.
To prepare for aligning all SIG-network lanes with Multus v4, `KUBEVIRT_WITH_DYN_NET_CTRL` will:
- Signal kubevirtci to deploy the dynamic-networks-controller [1].
- Enable selection of appropriate NIC hotplug tests based on the deployment method.
[1] https://github.com/kubevirt/kubevirtci/pull/1408
Complimentary project-infra PR:
- …

automation, test: Introduce KUBEVIRT_WITH_DYN_NET_CTRL

---

tests/vmi_configuration_test.go

The functionality tested by test_id:1684 is fully covered by unit tests in pkg/virt-handler/heartbeat/heartbeat_test.go.
This test checks that the node label `cpumanager` is set to "false" when the CPU Manager is not running. The same logic is verified thoroughly in the unit tests, making this E2E test redundant.
```release-note
none
```

tests: remove test_id:1684 as it's already covered by unit tests

---

pkg/virt-handler/cache/cache_test.go

The test waits 5 seconds for something that happens after 5 seconds, leading to potential flakes:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/15058/pull-kubevirt-unit-test/1940380205600215040
The test waits 10 seconds + misc cleanup
```release-note
NONE
```

tests: virt-handler cache: increase too short timeout

---

pkg/virtctl/imageupload/imageupload.go
pkg/virtctl/imageupload/imageupload_test.go

This PR adds the `cdi.kubevirt.io/applyStorageProfile: "true"` label to PVCs created by the image-upload command. This allows the PVCs to be mutated by CDI's WebhookPvcRendering feature if enabled via feature gate.
This is mainly to support applying a minimum supported PVC size via the storage profile annotation cdi.kubevirt.io/minimumSupportedPvcSize, which helps with provisioners that don't support small sizes.
- Fixes # https://issues.redhat.com/browse/CNV-64464
```release-note
Bugfix: Label upload PVCs to support CDI WebhookPvcRendering 
```

Image upload: Label PVCs to add support for rendering webhook 

---

pkg/network/vmispec/BUILD.bazel
pkg/network/vmispec/devices.go
pkg/network/vmispec/interface.go
pkg/util/BUILD.bazel
pkg/util/util.go
pkg/virt-controller/services/renderresources.go
pkg/virt-handler/non-root.go

Currently, `NeedVirtioNetDevice` and `NeedTunDevice` are located under a general purpose `pkg/util`.
Move the above functions and their dependencies under SIG-network's ownership.
```release-note
NONE
```

pkg/util: Mv net devices requirement logic under SIG network

---

tests/vm_test.go

58de529b3ede38604b06fc34c9f06a9ef69d5ff8 moved the reference to a ControllerRevision from the core spec of the VM to status. In doing so we introduced a few optional attributes to status, namely InstancetypeRef and ControllerRevisionRef below it. Both are pointers and both need to be asserted to not be nil before we attempt to read RevisionName as there's always a chance we could race the core VirtualMachine sync loop on slower test envs.
- Fixes #15148
```release-note
NONE
```

tests: Always check InstancetypeRef and ControllerRevisionRef are not nil

---

pkg/virt-controller/watch/application.go

https://github.com/kubevirt/kubevirt/pull/13535 introduced this bug in the 1.5 timeframe.
Later, in the 1.6 timeframe, https://github.com/kubevirt/kubevirt/pull/13839 was implicitly fixing the bug. The PR includes a lot of other logic that was not backported.
So we need to fix this manually in the release-1.5 and previous branches.
correct cluster preference informer for metrics
jira-ticket: https://issues.redhat.com/browse/CNV-54195
```release-note
Fix wrong cluster preference informer for metrics
```

[release-1.5] Fix wrong cluster preference informer for metrics

---

pkg/storage/export/export/export.go
pkg/storage/export/export/export_test.go

For some cases, we could not craft a proper service name and thus export failed indefinitely.
```release-note
BugFix: export fails when VMExport has dots in name
```

export: ensure service name is dns1035 label

---

automation/repeated_test.sh

The cluster used in flake check lanes doesn't support 1Gi hugepages or USB tests, which causes consistent failures unrelated to test stability:
https://github.com/kubevirt/kubevirt/pull/15086
https://github.com/kubevirt/kubevirt/pull/15126
```release-note
NONE
```

Skip 1Gi hugepages and USB tests in flake check lanes

---

hack/linter/lint-paths.txt
pkg/virtctl/console/console.go

Running the linter against `pkg/virtctl/console` gives errors.
Now it succeeds without errors or warnings
- Fixes  #14193
```release-note
NONE
```

fix: pkg/virtctl/console lint errors

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

When migrating a VM from another hypervisor, it is important to keep its
serial number, which may include spaces. libvirt (at least
libvirt-11.0.0 which I just tested) allows spaces, dollars and
other special characters in its system serial entry, as well as accepts
a string longer than 256.
```release-note
Drop an arbitrary limitation on VM's domain.firmaware.serial. Any string is passed verbatim to smbios. Illegal may be tweaked or ignored based on qemu/smbios version.
```

vmi-create-admitter: drop firmware.serial validation

---

pkg/storage/export/export/export.go
pkg/storage/export/export/export_test.go
pkg/virt-controller/services/template.go

following up on #15099, apparently there's
a few more places where we violate naming conventions:
- secret volume name
- export container name in pod
there is no reason for those to not be static anyway
```release-note
BugFix: export fails when VMExport has dots in secret
```

export: address additional naming convention issues

---

tests/migration/eviction_strategy.go

```release-note
Known issue: ParallelOutboundMigrationsPerNode might be ignored because of race condition 
```

[release-1.6] Un-quarantine should not migrate more than two VMIs at the same time from a node

---

cmd/virt-handler/virt-handler.go
pkg/virt-handler/migration-source.go
pkg/virt-handler/migration-source_test.go
tests/network/sriov.go

During virt-handler controller split [1], an update of network
interfaces status was lost from migration source flow:
vm.go[2] now returns early under isMigrationInProgress(), and skips
the call to netConf.UpdateStatus() down the sync() stack.
On the other hand this call had not been added to migration source
controller. As a consequence, the target does not see up-to-date VMI
interface status, specifically, it is not aware of interfaces that are
explicitly unplugged for migration, in order to be replugged at the
target.
Add netStat to migration-source controller and call UpdateStatus().
[1] https://github.com/kubevirt/kubevirt/pull/14705
[2] [`https://github.com/kubevirt/kubevirt/blob/0b1bf72712f9f51b36cecd42b272d7f24c51c440/pkg/virt-handler/vm.go#L395`](https://github.com/kubevirt/kubevi …

virt-handler, migration-src: Add netStat, call UpdateStatus

---

staging/src/kubevirt.io/api/core/v1/types.go

The IsRunning did not take decentralized migrations into account. This could cause a race condition if you create a VM and start it, and the immediately create a VMIM. The VM would be in 'starting' phase and a VMI would exist, but it would get stuck at starting because it thinks a migration was in progress. But because it was a decentralized migration which was in synchronizing phase which is the phase before starting a migration it would never start.
- VEP tracking issue: https://github.com/kubevirt/enhancements/issues/24 …

Fix IsRunning function on migration type

---

hack/cluster-sync.sh

As set out in bug #15218 1a311c24b759a9c4f627dcf7587a5bae0c3064e1 accidentally broke the `cluster-sync` flow when KubeVirt is already deployed.
This change forces all components to use the Always imagePullPolicy in these environments to force kubelet to query the registry even when the tag hasn't changed to ensure the digest is up to date. As is the case in our kubevirtci envs where we use a single `devel` tag for all builds.
- Fixes #15218
```release-note
NONE
```

hack: Force IMAGE_PULL_POLICY to Always when using cluster-sync

---

pkg/controller/controller.go

Removes code, leftover from https://github.com/kubevirt/kubevirt/pull/14311
```release-note
NONE
```

Remove PodCacheStore, not used

---

hack/license-header-check.sh
pkg/emptydisk/emptydisk.go
pkg/emptydisk/emptydisk_suite_test.go
pkg/emptydisk/emptydisk_test.go
pkg/host-disk/host_disk_suite_test.go
pkg/storage/admitters/vm-storage-admitter_test.go
pkg/storage/backend-storage/backend-storage_suite_test.go
pkg/storage/backend-storage/backend-storage_test.go
pkg/storage/export/export/paths.go
pkg/storage/hotplug/hotplug_suite_test.go
pkg/storage/hotplug/hotplug_test.go
pkg/storage/memorydump/memorydump_suite_test.go
pkg/storage/memorydump/memorydump_test.go
pkg/storage/pod/annotations/annotations_suite_test.go
pkg/storage/pod/annotations/generator.go
pkg/storage/pod/annotations/generator_test.go
pkg/storage/reservation/pr.go
pkg/storage/snapshot/restore_test.go
pkg/storage/snapshot/snapshot_test.go
pkg/storage/status/status.go
pkg/virtctl/guestfs/guestfs.go
pkg/virtctl/guestfs/guestfs_suite_test.go
pkg/virtctl/guestfs/guestfs_test.go
pkg/virtctl/imageupload/imageupload_suite_test.go
pkg/virtctl/imageupload/imageupload_test.go
pkg/virtctl/memorydump/memorydump_suite_test.go
pkg/virtctl/memorydump/memorydump_test.go
pkg/virtctl/vmexport/vmexport_suite_test.go
pkg/virtctl/vmexport/vmexport_test.go
pkg/virtiofs/virtiofs.go

- Standardizes license headers across all files 
- Adds missing license headers where needed
- Add sig-storage folders to license header linter
output when linter is failing:
This pr is a follow up for- https://github.com/kubevirt/kubevirt/pull/14597, https://github.com/kubevirt/kubevirt/pull/14748
```release-note
none
```

Add license header linter for sig-storage under pkg

---

pkg/storage/export/export/export.go
pkg/storage/export/export/export_test.go

Manual cherry pick https://github.com/kubevirt/kubevirt/pull/15099
```release-note
BugFix: export fails when VMExport has dots in name
```

[release-1.4] export: ensure service name is dns1035 label

---

pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
tests/storage/datavolume.go

There was a e2e test for `PreferredStorageClassName` which is already covered by a unit test in [vm-mutator_test.go](https://github.com/kubevirt/kubevirt/blob/96471d5212257b42a885326c10f07f0c5d87412b/pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go#L419-L429)
- `should use PreferredStorageClassName when storage class not provided by VM` test is removed
- test_id added to unit tests under vm-mutator_test.go
- refactor the test to reduce the complexity of the test - we only need a single test scope since the test only verify a single option
Links to places where the discussion took place: #14991 
```release-note
NONE
```

Remove e2e PreferredStorageClassName test and add test_id to unit covering it

---

tests/vm_state_test.go

Test `[sig-compute]VM state with persistent TPM VM option enabled should persist VM state of EFI across migration and restart` is flaky [1] [2] [3] .
Test is quarantined according to the [rules] .
[1]: https://search.ci.kubevirt.io/?search=%5C%5Bsig-compute%5DVM+state+with+persistent+TPM+VM+option+enabled+should+persist+VM+state+of+EFI+across+migration+and+restart&maxAge=336h&context=1&type=junit&name=&excludeName=periodic-.*&maxMatches=1&maxBytes=20971520&groupBy=job
[2]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/15171/pull-kubevirt-e2e-k8s-1.33-sig-compute-1.6/1944300551390892032
[3]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/15171/pull-kubevirt-e2e-k8s-1.33-sig-compute-1.6/1944300551390892032
[rules]: …

q(1.6,sig-compute): quarantine flaky persistent TPM

---

api/openapi-spec/swagger.json
pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

Libvirt API returns milliseconds of the
loginTime, and previously KubeVirt
API was using QEMU directly that
represents seconds only.
This conversion from milliseconds to
seconds is essential to keep consistency
of what is expected from the KubeVirt
API in the response of loginTime.
Also update the description of the
loginTime in the KubeVirt API
to ensure that user understands
the returned value of it.
Jira-Url: https://issues.redhat.com/browse/CNV-64776
```release-note
None
```

fix: convert login time to seconds

---

cmd/virt-handler/virt-handler.go
pkg/virt-handler/controller.go
pkg/virt-handler/device-manager/device_controller.go
pkg/virt-handler/device-manager/device_controller_test.go
pkg/virt-handler/migration-source.go
pkg/virt-handler/migration-source_test.go
pkg/virt-handler/migration-target.go
pkg/virt-handler/migration-target_test.go
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

Some code duplication between vm.go, migration-source.go and migration-target.go
Various eyesores
Less code duplication
Less eyesores
Logs include controller name
Addresses https://github.com/kubevirt/kubevirt/pull/14705#issuecomment-2941247789
Addresses https://github.com/kubevirt/kubevirt/pull/14705#issuecomment-2970688518
Best reviewed commit by commit
```release-note
NONE
```

virt-handler: refactor variables and code into base controller

---

tests/network/vmi_networking.go
tests/vmi_multiqueue_test.go

1. Currently, the Multi Queue Single CPU test relies on libdomain to check that an interface had been created, but it doesn't even validate that, because if libvirt doesn't create an interface, an empty loop would not run any assertions anyway.
Regardless, e2e tests should strive to avoid using libdomain, instead, run a real connectivity test to guarantee that the network interface is indeed functioning.
2. Since this is a network test, migrate it to SIG-Network area.
```release-note
NONE
```

e2e, net: Mv multi-Q single CPU to SIG Net

---

pkg/network/dhcp/serverv6/serverv6.go
pkg/network/dhcp/serverv6/serverv6_test.go
pkg/network/dns/resolveconf.go
pkg/network/dns/resolveconf_test.go
pkg/network/driver/common.go

Currently, parsing the Pod's nameservers is limited to IPv4 nameservers.
Fix it to support also IPv6 ones.
In order to populate the IPv6 ones to the VM, add IPv6 DHCP modifier, option 23,
which is used to advertise the IPV6 nameservers.
Note: Since Kubevirt doesn't support RA, SLAAC won't work out of the box,
and the VM won't get global IPv6, nor nameservers.
Hence `dhcp` method should be used (see examples in the PR comments).
Fixes #15011
Didn't add e2e, because we might not need e2e for it, and if we do
we can add it on the same test that  https://github.com/kubevirt/kubevirt/pull/14189 fixes,
once it is merged.
Because this mentioned PR purpose is also to …

network, dns: Support adding IPv6 Nameservers

---

manifests/generated/kubevirt-cr.yaml.in
tools/resource-generator/resource-generator.go

By setting `spec.configuration.imagePullPolicy` in manifest-templator, the `compute` container in `virt-launcher` will also respect it.
The `compute` container in `virt-launcher` will use the default `IfNotPresent` pull policy in dev environments.
The `compute` container in `virt-launcher` will use the `Always` pull policy in dev environments.
- Fixes #15218
```release-note
None
```

fix(manifests): Set pull policy for virt-launcher

---

pkg/synchronization-controller/synchronization-controller.go

It was copying the start timestamp instead of the end timestamp to the endtimestamp.
The start timestamp was copied into the end timestamp
The end timestamp is copied into the end timestamp.
```release-note
NONE
```

Fix wrong timestamp being copied

---

pkg/util/tls/ca-manager.go
pkg/util/tls/ca-manager_test.go
pkg/util/tls/tls.go
pkg/util/tls/tls_test.go
pkg/virt-api/api.go

Follows https://kubernetes.io/docs/tasks/extend-kubernetes/setup-extension-api-server/
1.  Introduce KubernetesCAManager interface
This interface extends ClientCAManager interface
with GetCNs function in order to determine what
CNs should be trusted for Aggregated API.
2. SetupTLSWithCertManager now enforces CN 
The CNs will be provided by Kubernetes.
If empty, any client certificate validated
by the authority is allowed.
```release-note
Common Names are now enforce for aggregated API
```

Enforce CNs for aggregated API

---

hack/linter/lint-paths.txt
pkg/virtctl/create/clone/clone.go
pkg/virtctl/create/clone/clone_test.go

Running the linter against pkg/virtctl/create/clone gives errors.
Added  pkg/virtctl/create/clone to hack/linter/lint-paths.txt and ran make lint. Fixed the lint issue in this package
- Fixes #14194
```release-note
NONE
```

fix: lint: pkg/virtctl/create/clone errors

---

hack/perfscale-tests.sh
hack/perftests.sh

Move the performance job tests up a directory level so results can be discovered by prow.
Prow was not able to see the published juitfile
Prow will now discover the file - https://github.com/kubevirt/project-infra/blob/7be6a09db6484ff087f36c5a99e7697a30be4d51/github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml#L52
- Fixes #15296 
```release-note
NONE
```

Move performance job artifacts to the base artifacts directory

---

pkg/storage/admitters/vmrestore.go
pkg/storage/admitters/vmrestore_test.go

The previous error message only mentioned "backend storage," which may be unclear to users. This PR improves the wording to explicitly mention persistent TPM or EFI as examples
- Fixes # https://issues.redhat.com/browse/CNV-62854
```release-note
NONE
```

Improve error message when restoring VMs with backend storage

---

pkg/instancetype/controller/vm/controller.go
pkg/instancetype/controller/vm/controller_test.go
pkg/instancetype/controller/vm/mock.go
pkg/instancetype/preference/apply/BUILD.bazel
pkg/instancetype/preference/apply/device.go
pkg/instancetype/preference/apply/device_test.go
pkg/virt-controller/watch/vm/vm.go

Previously the VM controller would always apply all device preferences ahead of default network and input devices being added to a VMI. As discussed in #15259 [1] this should be more targeted to the auto attach related preferences.
This change does this by extracting and refactoring the auto attach preference logic and tests, hopefully also making the intent more obvious to any readers.
[1] https://github.com/kubevirt/kubevirt/pull/15259#discussion_r2230495157
```release-note
NONE
```

preference: Refactor application of AutoAttach preferences

---

pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/snapshot_test.go
pkg/storage/snapshot/source.go
pkg/virt-api/rest/lifecycle.go
pkg/virt-api/rest/subresource.go
pkg/virt-api/rest/subresource_test.go
staging/src/kubevirt.io/api/snapshot/v1beta1/types.go
tests/storage/snapshot.go

VM snapshot with qemu-guest-agent fails when the domain is paused, because virt-controller sends a freeze/unfreeze request during snapshotting. This freeze/unfreeze is handled by virt-launcher, but it currently fails on paused VMs. Since paused VMs have a consistent filesystem state (similar to frozen), this change makes virt-launcher treat freeze as successful when the domain is paused. This allows snapshotting to continue safely.
- VM snapshot with qemu-guest-agent fails when the domain is paused. This happens since the snapshot flow trigger a freeze but since the VM is paused, freeze fails causing snapshot flow to also fail. since a Paused VM is considered a safe state to perform a snapshot, we expect it to pass when the VM is paused, but it doesnt.
- it is possible to unpause a VM …

Handle freeze on paused VMs during snapshot

---

manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-operator/resource/generate/rbac/operator.go

There was a duplicate of verbs in operator ClusterRole ( pkg/virt-operator/resource/generate/rbac/operator.go )
```go
func NewOperatorClusterRole() *rbacv1.ClusterRole {
// These are permissions needed by the operator itself.
// For successfully deploying KubeVirt with the operator, you need to add everything
// that the KubeVirt components' rules use, see below
// (you can't create rules with permissions you don't have yourself)
operatorRole := &rbacv1.ClusterRole{
TypeMeta: metav1.TypeMeta{
APIVersion: VersionNamev1,
Kind:       "ClusterRole",
},
ObjectMeta: metav1.ObjectMeta{
Name: components.OperatorServiceAccountName,
Labels: map[string]string{
virtv1.AppLabel: "",
},
},
Rules: []rbacv1.PolicyRule{
{
APIGroups: []string{
"kubevirt.io",
},
Resources: []string{
"kubevirts",
},
Verbs: …
```

Remove verb duplicates in operator clusterrole

---

pkg/virt-controller/watch/vmi/lifecycle.go
pkg/virt-controller/watch/vmi/vmi_test.go
staging/src/kubevirt.io/api/core/v1/types.go
tests/testsuite/namespace.go

This resolves the following warning often spammed in our e2e test logs:
```
W0707 13:05:14.007287  342008 warnings.go:70] metadata.finalizers: "foregroundDeleteVirtualMachine": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers
```
The original non-FQDN version of this finalizer has been deprecated for removal in a future release.
- Fixes #15095
```release-note
The `foregroundDeleteVirtualMachine` has been deprecated and replaced with the domain-qualified …
```

api: Introduce and use domain-qualified version of the foregroundDeleteVirtualMachine finalizer

---

pkg/virt-handler/cache/BUILD.bazel
pkg/virt-handler/cache/cache.go
pkg/virt-handler/cache/cache_test.go
pkg/virt-handler/cache/domain-watcher.go
pkg/virt-handler/cache/domain-watcher_test.go
pkg/virt-handler/cmd-client/client.go
pkg/virt-handler/cmd-client/client_test.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/15323/
```release-note
NONE
```

[release-1.4] virt-handler: validate sockets listed by the domain informer cache with ghost record cache

---

pkg/virt-controller/watch/descheduler/descheduler.go
pkg/virt-controller/watch/vm/vm.go
pkg/virt-controller/watch/vm/vm_test.go
pkg/virt-controller/watch/vmi/lifecycle.go
pkg/virt-controller/watch/vmi/vmi_test.go

The proposal of introducing `descheduler.beta.kubernetes.io/evict` annotation with Boolean logic to dynamically opt-in/opt-out selected pods as eviction candidates got refused.
We got instead an additional alpha annotation named `descheduler.alpha.kubernetes.io/prefer-no-eviction` that can be used to opt-out selected pods.
See: https://github.com/kubernetes-sigs/descheduler/pull/1723
Let's align the code to handle `descheduler.alpha.kubernetes.io/prefer-no-eviction` instead of `descheduler.beta.kubernetes.io/evict`.
This is just a change in the name of the handled annotation, no actual logic changes.
The code was syncing `descheduler.alpha.kubernetes.io/evict` and  `descheduler.beta.kubernetes.io/evict` (that is ignored by the Descheduler) from VM template -> VMI -> virt-launcher pod
The …

[descheduler] align opt-out annotation name

---

tests/libnet/hotplug.go
tests/libnet/interface.go
tests/network/hotplug_bridge.go
tests/network/link_state.go

- This PR adds coverage for hotplugging interface in down state.
- We are removing the InterfaceName key in the dict array of interface
status that is returned (to compare against) and cleaning off the
InterfaceName of the interface specs that is being compared.
Thus we make sure the correct interface has the correct state
(and other specs) irrespective of the guest interface it connects to.
- To test hotplugging interface in down state we need to compare the state in interface status with the state in interface specs. In the specs, if the state is unspecified, it is considered as up. This needs to be reflected in the interfaceStatusFromInterfaces function where we fetch the info from the specs to compare with the info from status. 
So we are adding a new normalizeState function that …

e2e, net, hotplug: Update hotplug tests to cover ifaces states up/down

---

manifests/generated/operator-csv.yaml.in
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-operator/resource/placement/placement.go
pkg/virt-operator/resource/placement/placement_test.go

node-role.kubernetes.io/master was deprecated back in k8s v1.20 [1] and has been removed from nodes on upgrade since k8s v1.25 [2]. As we currently only support >= v1.30.0 it should be safe to remove the use of this taint now and rely on the existing use of the node-role.kubernetes.io/control-plane that replaces it.
[1] https://github.com/kubernetes/kubernetes/blob/49945dbfab342a6d7dee7e83778bb1cc3886bdbe/CHANGELOG/CHANGELOG-1.20.md?plain=1#L1923
[2] https://github.com/kubernetes/kubernetes/blob/49945dbfab342a6d7dee7e83778bb1cc3886bdbe/CHANGELOG/CHANGELOG-1.25.md?plain=1#L2335
A followup `kubevirtci` change will remove the remaining uses of this taint in the …

virt-operator: Stop using deprecated node-role.kubernetes.io/master taint

---

tests/vmi_multiqueue_test.go

Remove test `[test_id:959][rfe_id:2065] 'Should honor multiQueue requests'` from vmi_multiqueue_test.go as it duplicates functionality already covered by converter unit tests.
The test was validating VMI spec to libvirt domain conversion for block multiqueue settings, which is tested in
https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-launcher/virtwrap/converter/converter_test.go#L2403
where the same functionality is already covered including: Queue assignment when BlockMultiQueue=true, Queue count matching CPU count, Multiple disk scenarios and CPU topology considerations.
convert BlockMultiQueue test to a unit test: https://issues.redhat.com/browse/CNV-64739
```release-note
NONE
```

tests: remove redundant block multiqueue integration test

---

tests/infrastructure/BUILD.bazel
tests/infrastructure/prometheus.go
tests/libinfra/metrics.go

Thanks to https://github.com/machadovilaca/operator-observability/pull/21 it's now possible for kubevirt to use a proper struct to fetch metrics into.
This PR removes the `collectMetrics` lambda and leverages the MetricsFetcher interface.
With this refactoring, metrics are now collected in a more structured way, using a map from metric name to a slice of MetricResult structs, which improves clarity and consistency in our tests.
```release-note
None
```

tests/infra/prometheus: refactor metrics tests to use MetricsFetcher

---

automation/repeated_test.sh
automation/test.sh
hack/conformance.sh
pkg/liveupdate/memory/memory.go
pkg/liveupdate/memory/memory_test.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
pkg/virt-api/webhooks/utils.go
pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
tests/decorators/decorators.go
tests/framework/checks/skips.go
tests/vmi_lifecycle_test.go

This PR cleans up a few recently added tests (both unit and e2e) that now fail on our arm64 lanes after we had a period of no arm64 coverage. A future PR will look into improving the arm64 e2e coverage by moving from the current allow list approach to an explicit deny list.
The bulk of unit test changes are focused on the VM and VMI admission webhooks where we were incorrectly using the test runner arch to assert various VM/VMI arch flows. Where required and possible this is now replaced with true VM/VMI arch test assertions for amd64, arm64 and s390x.
Approvers are …

arm64: Fix lanes

---

pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go
pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go
tests/compute/vm_lifecycle.go

Ensures that the cached grace period metadata inside virt-handler is synchronized with the `spec.TerminationGracePeriodSeconds` field from the VMI.
Special thanks to @Acedus and @akalenyu for their help in debugging and patching this issue.
Force stop commands like:
```bash
virtctl stop vm --force --grace-period=0
```
may not take effect on unresponsive VMs. 
The cached grace period in virt-handler could remain stale, ignoring updated values from the VMI spec. This leads to situations where shutdown appears to hang, especially on VMs that don't respond to ACPI signals (e.g., empty or diskless/ alpine VMs).
The metadata cache inside virt-launcher is now explicitly updated during each sync loop, ensuring that any changes to `spec.TerminationGracePeriodSeconds` are honored while prioritizing …

virt-handler: ensure grace period metadata sync before shutdown

---

manifests/generated/operator-csv.yaml.in
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-operator/resource/placement/placement.go
pkg/virt-operator/resource/placement/placement_test.go

/cc @xpivarc 
/cc @iholder101 
This reverts commit 0b0100200055035f7eb72321bb50505d749c40de.
While node labels are present some downstream environments only apply the original `node-role.kubernetes.io/master` taint so we can't remove this just yet. For now the original change is reverted and I will continue to monitor if we can switch over.
```shell
$ oc get nodes -o json | jq '.items.[] | select(.metadata.labels[] | contains("master")) | .spec.taints'
```
```json
[
{
"effect": "NoSchedule",
"key": "node-role.kubernetes.io/master"
}
]
[
{
"effect": "NoSchedule",
"key": "node-role.kubernetes.io/master"
}
]
[
{
"effect": "NoSchedule",
"key": "node-role.kubernetes.io/master"
}
]
```
Links to places where the …

Revert "virt-operator: Stop using deprecated node-role.kubernetes.io/master taint"

---

pkg/virt-operator/resource/generate/components/webhooks.go

We have not had to support v1beta1 since k8s v1.17 [1] so drop the
version from AdmissionReviewVersions.
[1] https://github.com/kubernetes/kubernetes/blob/49945dbfab342a6d7dee7e83778bb1cc3886bdbe/CHANGELOG/CHANGELOG-1.17.md?plain=1#L1965
```release-note
NONE
```

webhooks: Drop v1beta1 AdmissionReview version support

---

pkg/virt-controller/services/template.go
pkg/virt-controller/watch/migration/migration.go
pkg/virt-launcher/virtwrap/live-migration-target.go
tests/libmigration/BUILD.bazel
tests/libmigration/migration.go
tests/migration/namespace.go

Fixes a bug in decentralized live migration, where migrating a VM with a hotplugged volume would fail.
Unable to migrate a VM with a persistent hotplugged volume.
Successfully migrate a VM with a persistent hotplugged volume.
- Fixes https://issues.redhat.com/browse/CNV-64972
```release-note
NONE
```

Fix hotplug decentralized live migration

---

pkg/instancetype/apply/cpu.go

When applying an instancetype to a vmispec.domain.cpu, the validateCPU() function checks for conflicts in the instancetypespec.cpu and vmispec.domain.cpu. The nil checks in the applyCPU() function can be simplified to enhance clarity.
Partially addresses #13044 point n.1.
Overriding cpu.model is not possible. Specifying the spec.template.spec.domain.cpu.model in a vm and also referencing an instancetype with a set cpu model results in a conflict.
```release-note
NONE
```

cleanup: instancetype applyCPU

---

pkg/virtctl/portforward/portforward.go
pkg/virtctl/portforward/portforward_test.go
pkg/virtctl/ssh/ssh_test.go

Drop support for the legacy syntax that allowed to delimit the name and namespace of a target with a dot. This brings virtctl portforward closer to the syntax of kubectl port-foward.
Before:
'vmi/testvmi.with.dots' is parsed as name 'testvmi.with' and namespace 'dots.
After:
'vmi/testvmi.with.dots' parse as name 'testvmi.with.dots' and empty namespace.
This change affects the portforward, ssh and scp commands of virtctl.
The syntax was deprecated starting with the 1.6 release of KubeVirt, see #13939. 
```release-note …
```

cleanup(virtctl,portfoward): Drop support for legacy syntax

---

automation/repeated_test.sh
automation/test.sh
hack/conformance.sh
pkg/liveupdate/memory/memory.go
pkg/liveupdate/memory/memory_test.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
pkg/virt-api/webhooks/utils.go
pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
tests/decorators/decorators.go
tests/framework/checks/skips.go
tests/vmi_lifecycle_test.go

This is a manual backport of #14967, conflicts called out in the individual commits.
This PR cleans up a few recently added tests (both unit and e2e) that now fail on our arm64 lanes after we had a period of no arm64 coverage. A future PR will look into improving the arm64 e2e coverage by moving from the current allow list approach to an explicit deny list.
The bulk of unit test changes are focused on the VM and VMI admission webhooks where we were incorrectly using the test runner arch to assert various VM/VMI arch flows. Where required and possible this is now replaced with true VM/VMI arch test assertions for amd64, arm64 and s390x.
74deae19f6cde31ae307a9170d3f552dd3e93c78 is the only <=release-1.6 specific given the removal of arch specific coverage on main.
The following tradeoffs …

[release-1.6] arm64: Fix lanes

---

WORKSPACE
automation/test.sh
hack/functests.sh
tests/decorators/decorators.go
tests/flags/flags.go
tests/operator/operator.go
tests/testsuite/kubevirtresource.go

Fix build functests dependency
google.golang.org/grpc v1.30 defined in WORKSPACE
has golang.org/x/sys:v0.0.0-20190215142949-d0b11bdaac8a as dependency, as
defined in https://deps.dev/go/google.golang.org%2Fgrpc/v1.30.0/dependencies.
https://pkg.go.dev/golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a this version disappeared.
```release-note
NONE
```

[release-1.1] Fix project build related to functests dependency

---

pkg/virt-controller/watch/vmi/lifecycle.go

Added some code to prevent finalizer from being removed when decentralized migration fails, but it was not needed and caused issues when the migration failed. It prevent the user from removing the VM and VMIs.
If a decentralized migration failed, it would not be possible to remove the source VM/VMI
If a decentralized migration fails, it is possible to remove the source VM/VMI
- Fixes https://issues.redhat.com/browse/CNV-65156
- VEP tracking issue: https://github.com/kubevirt/enhancements/issues/24
```release-note
BugFix: …
```

Remove finalizer from source VMIs when decentralized migration fails

---

pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
tests/clone_test.go

This PR extends the firmware defaulting logic to ensure that a unique `Firmware.Serial` value is assigned to newly created VMs when one is not explicitly provided.
The main use-case is for cluster administrators who want every newly created VM in the cluster to have a unique and consistent `firmware.serial` value. This allows them to track and identify VMs reliably from within the guest OS by reading the DMI-exposed field at `/sys/devices/virtual/dmi/id/subsystem/id/product_serial`.
- `Firmware.Serial` was not defaulted.
- If `Firmware.Serial` is unset, it is defaulted with a new UUID. …

vm-mutator: assign default firmware.Serial for new VMs

---

cmd/sidecars/network-passt-binding/callback/callback.go
cmd/sidecars/network-passt-binding/domain/BUILD.bazel
cmd/sidecars/network-passt-binding/domain/configurator.go
cmd/sidecars/network-passt-binding/domain/configurator_test.go
cmd/sidecars/network-passt-binding/server/server.go

Currently, the passt binding plugin's sidecar tries to check whether some custom interface name exists inside the pod - and uses it in case it exists instead of using the traditional "eth0".
Replace this logic by inferring the pod interface's name from the VMI interface statuses.
This is done in order to:
- Be in sync with the dynamic primary NIC name feature [1][2]
- Simplify the code and tests
- Reduce external dependencies
Note: The PodInterfaceName field is expected to contain a valid value by the time it reaches this stage, so there is no need for a fallback.
[1] https://github.com/kubevirt/community/pull/324
[2] https://github.com/kubevirt/community/pull/357
Links to places where the discussion took …

passt BP, sidecar: Infer pod iface name from VMI

---

docs/observability/metrics.md
hack/prom-rule-ci/prom-rules-tests.yaml
pkg/monitoring/rules/recordingrules/operator.go

This pr adds virt-launcher to kubevirt_memory_delta_from_requested_bytes which will also means it will be added to [cnv_abnormal](https://github.com/kubevirt/hyperconverged-cluster-operator/blob/d9b7e6e9d8edd94b530c074ea366b641f11f8edc/pkg/monitoring/hyperconverged/rules/recordingrules/operator.go#L42) and [telemeter.](https://github.com/openshift/cluster-monitoring-operator/pull/2291/files)
We removed the KubevirtVmHighMemoryUsage alert, but users still need clear visibility when virt-launcher memory usage significantly exceeds its request. 
The records did not include virt-launcher memory delta
The records include virt-launcher memory delta
jira-ticket: https://issues.redhat.com/browse/CNV-49531
```release-note
Added virt-launcher to kubevirt_memory_delta_from_requested_bytes metric and …
```

Add virt-launcher to kubevirt_memory_delta_from_requested_bytes

---

tests/compute/guest_agent.go
tests/decorators/decorators.go

Add guest-agent-probes label to allow easier filtering for guest agent based liveness and readiness probe related functional tests.
Guest agent based liveness and readiness probe related functional tests cannot be targeted specifically.
Guest agent based liveness and readiness probe related functional tests can be targeted specifically.
```release-note
None
```

chore: Add guest-agent-probes label

---

pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go

- Ensures every virt-controller metrics test in pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go validates behavior with two VMs, not just one.
- Adds concise helpers to reduce duplication while keeping each test’s original semantics intact.
A recent backport bug slipped through because some tests only exercised a single VM. Doubling coverage per test catches issues that can appear with multiple vms.
Few tests include 2 vms in virt-controller metrics unit tests.
All tests include 2 vms in virt-controller metrics unit testes.
jira-ticket:https://issues.redhat.com/browse/CNV-59027
```release-note
none
```

Fix monitoring virt-controller unit to test 2 vms

---

WORKSPACE
automation/test.sh
hack/functests.sh
tests/decorators/decorators.go
tests/flags/flags.go
tests/operator/operator.go
tests/testsuite/kubevirtresource.go

google.golang.org/grpc v1.30 defined in WORKSPACE
has golang.org/x/sys:v0.0.0-20190215142949-d0b11bdaac8a as dependency, as defined in https://deps.dev/go/google.golang.org%2Fgrpc/v1.30.0/dependencies.
https://pkg.go.dev/golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a this version disappeared.
Fixes #
```release-note
None
```

[release-1.0] Fix build functests dependency

---

pkg/monitoring/metrics/common/workqueue/metrics.go
pkg/virt-controller/watch/migration/BUILD.bazel
pkg/virt-controller/watch/migration/migration.go
tests/monitoring/metrics.go

Missing workqueue metrics for a few controllers due to single registering the metrics with the name as a const label
Use vector metrics and use 'name' as a variable label, so each controller has its own instance of the metric with its own name
```release-note
none
```

Fix missing workqueue metrics

---

tests/default-ceph-config.json
tests/libstorage/config.go
tests/libstorage/storageclass.go
tests/storage/migration.go

Adding new StorageClassCSI config to KubeVirtTestsConfiguration that will define a CSI enabled storage class
Migration tests would fail on HPP lanes because they relied on the StorageSnapshot value which is not set in the `default-config.json`
Migration tests now pass after leveraging new config field
```release-note
NONE
```

Fix Volume Migration Tests

---

pkg/virt-launcher/virtwrap/converter/converter_test.go
tests/vmi_configuration_test.go

In the process of reducing the usage of domain XML for tests to e2e, few changes were made to memory configuration tests, block/net queues and removing unneeded domain XML, relying on what is actually being passed into the guest instead.
the changes includes:
1. Move memory configuration tests from `tests/vmi_configuration_test.go` to unit tests under `pkg/virt-launcher/virtwrap/converter/converter_test.go` while keeping the same test coverage.
2. Multiqueue functionality testing has been converted from XML domain inspection to actual guest verification by checking block device queues via `/sys/block/vda/mq` and network interface queues via `/sys/class/net/eth0/queues`. 
3. Remove redundant Chassis value XML check since this functionality is already covered by end-to-end testing that …

tests: Convert VMI configuration tests from integration to end-to-end

---

cmd/virt-handler/virt-handler.go
pkg/virt-handler/cgroup/cgroup.go
pkg/virt-handler/cmd-client/BUILD.bazel
pkg/virt-handler/cmd-client/client.go
pkg/virt-handler/cmd-client/errors.go
pkg/virt-handler/cmd-client/guest.go
pkg/virt-handler/container-disk/mount.go
pkg/virt-handler/container-disk/mount_test.go
pkg/virt-handler/hotplug-disk/mount.go
pkg/virt-handler/hotplug-disk/mount_test.go
pkg/virt-handler/isolation/detector.go
pkg/virt-handler/isolation/detector_test.go
pkg/virt-handler/isolation/generated_mock_detector.go
pkg/virt-handler/selinux/BUILD.bazel
pkg/virt-handler/selinux/labels.go

1. Removes some clutter in pkg/virt-handler/cmd-client/client.go by refactoring out error logic and guest logic into own files. 
2. Drop a vmi argument for "DetectForSocket". The argument
is only needed for "contextual" logging. The error itself
will be logged appropriately.
3. Isolation detector: Remove unused field 
4. VM Controller: Remove virtPrivateDir , unused 
Fixes #
```release-note
NONE
```

virt-handler: various cleanup

---

pkg/virt-handler/rest/lifecycle.go

All handlers in pkg/virt-handler/rest/lifecycle.go create cmdclient.LauncherClient, but none close the client, causing a leak.
All client are properly closed
- Fixes https://github.com/kubevirt/kubevirt/issues/15556
```release-note
Fix: grpc client in handler rest requests are properly closed
```

Fix rest handler leak

---

hack/functests.sh

In case there was whitespace in the focus / skip vars, it was corrupting the command.
Using bash array is safer when it involves appending variables, especially when they might have spaces.
Usage example:
`export KUBEVIRT_E2E_FOCUS="should be able to reach the outside world"`
Note that some characters need to be escaped still: 
`export KUBEVIRT_E2E_FOCUS="should be able to reach the outside world \[IPv4\]"`
```release-note
None
```

tests: Fix focus and skip support

---

pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/snapshot_test.go
pkg/storage/snapshot/source.go
pkg/virt-api/rest/subresource.go
pkg/virt-api/rest/subresource_test.go
staging/src/kubevirt.io/api/snapshot/v1beta1/types.go
tests/storage/snapshot.go

Manual backport of #15001
Automated backport failed due to missing `pkg/virt-api/rest/lifecycle.go` file as some of changed functions were still under `pkg/virt-api/rest/subresource.go`.
VM snapshot with qemu-guest-agent fails when the domain is paused, because virt-controller sends a freeze/unfreeze request during snapshotting. This freeze/unfreeze is handled by virt-launcher, but it currently fails on paused VMs. Since paused VMs have a consistent filesystem state (similar to frozen), this change makes virt-launcher treat freeze as successful when the domain is paused. This allows snapshotting to continue safely.
- VM snapshot with qemu-guest-agent fails when the domain is paused. This happens since the snapshot flow trigger a freeze but since the VM is paused, freeze fails causing …

[Release-1.5] Handle freeze on paused VMs during snapshot

---

tests/hotplug/BUILD.bazel
tests/hotplug/cpu.go
tests/hotplug/instancetype.go
tests/hotplug/memory.go
tests/hotplug/rolloutstrategy.go
tests/libkubevirt/config/kvconfig.go
tests/libkubevirt/config/netbinding.go
tests/network/bindingplugin.go
tests/network/bindingplugin_macvtap.go
tests/network/bindingplugin_passt.go
tests/network/bindingplugin_slirp.go
tests/network/hotplug_bridge.go
tests/network/hotplug_sriov.go
tests/network/vmi_istio.go
tests/storage/migration.go

`patchWorkloadUpdateMethodAndRolloutStrategy` were a set of unexported helper functions with the same name and functionality that existed throughout several test categories. 
This PR refactors `RegisterKubevirtConfigChange` to use the builder pattern and replaces `patchWorkloadUpdateMethodAndRolloutStrategy` with corresponding builder options.
```release-note
NONE
```

tests: Refactor RegisterKubevirtConfigChange and remove patchWorkloadUpdateMethodAndRolloutRunStrategy

---

pkg/network/dhcp/bridge.go
pkg/network/dhcp/bridge_test.go
pkg/network/dhcp/configurator.go
pkg/network/dhcp/configurator_test.go
pkg/network/setup/network_test.go
pkg/network/setup/podnic.go
pkg/network/setup/podnic_test.go

Currently, the `podNIC.launcherPID` field is always set to nil, thus it always configures the `BridgeConfigGenerator.launcherPID` field to "self".
- Remove these redundant fields
- Remove the `getPIDString` function
- Remove the unused `podNIC.cachedDomainInterface` method
- Change the signature of `newPodNIC` so it will not return an error
```release-note
NONE
```

virt-launcher, network setup: Minor cleanup

---

tests/network/sriov.go

Wait for infoSource to have domain, multus and guest agent.
This way it should proceed only after the hot plug has been done.
PR also uses logical name instead MAC to find the interface.
SR-IOV migration test was de quarantined.
```release-note
None
```

e2e, sriov: Wait for infoSources

---

pkg/virt-controller/watch/migration/migration.go

we're using the **vmim** key when
declaring PVC was observed && checking if the expectation was satisfied
but we send out the expectation towards the **vmi** key,
which is logically wrong.
```release-note
BugFix: Windows VM with vTPM that was previously Storage Migrated cannot live migrate
```

backend state migration: use same key in expect/observe

---

cmd/virt-handler/virt-handler.go
pkg/monitoring/metrics/virt-handler/domainstats/collector.go
pkg/monitoring/metrics/virt-handler/metrics.go
tests/libmonitoring/metrics.go

Remove `virtShareDir` and `nodeName` params from collector struct since
they are unused
```release-note
none
```
/hold
Based on https://github.com/kubevirt/kubevirt/pull/14790

monitoring: Remove unused params from collector

---

pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
tests/clone_test.go

Manual backport of #15357
The automated backport failed because the changes from #14130 (which introduced `firmware.uuid` for newly created VMs) were not present in release `v1.5`.
This PR manually introduces the `firmware.Serial` defaulting logic.
fixes: #15667
```release-note
ensure default Firmware.Serial value on newly created vms
```

[release-1.5] vm-mutator: ensure default Firmware.Serial value on newly created vms

---

docs/observability/metrics.md
hack/prom-rule-ci/prom-rules-tests.yaml
pkg/monitoring/rules/alerts/virt-controller.go
pkg/monitoring/rules/recordingrules/virt.go
tests/monitoring/BUILD.bazel
tests/monitoring/component_monitoring.go

No LowReadyVirtControllersCount e2e test
Added LowReadyVirtControllersCount e2e test
jira-ticket: https://issues.redhat.com/browse/CNV-56648
```release-note
none
```

Add LowReadyVirtControllersCount e2e test

---

pkg/network/istio/decorators.go
pkg/network/pod/annotations/generator.go
pkg/network/pod/annotations/generator_test.go

In Istio v1.25 a new annotation (`istio.io/reroute-virtual-interfaces`) was introduced as a replacement for  `traffic.sidecar.istio.io/kubevirtInterfaces` which was deprecated.
The old annotation was actually broken since Istio v1.25 due to [1].
In order to maintain BWC, and to continue supporting v1.24.4 alongside more recent versions, KubeVirt annotates pods with both old and new annotations, until it is decided to cease support for Istio versions < 1.25.
[1]  https://github.com/istio/istio/issues/57662#issuecomment-3301658947.
https://github.com/istio/istio/issues/57662 …

net, istio: Support Istio v1.25 and above 

---

pkg/network/setup/BUILD.bazel
pkg/network/setup/configstatecache.go
pkg/network/setup/netconf.go

Remove the one-time upgrade mechanism for the `configStateCache`. This logic was introduced in [1] to convert cache keys from the deprecated ordinal naming scheme to logical network names.
Given that more than two years and seven minor releases have passed (1.0-1.6), this compatibility mechanism can now be safely removed to reduce maintenance overhead.
The `ConfigStateCache.Exists` method is also removed as it became unused after this change.
[1] https://github.com/kubevirt/kubevirt/pull/9763
```release-note
NONE
```

netconf: Remove configStateCache upgrade

---

pkg/virt-handler/rest/lifecycle.go

This is a manual cherry-pick of [#15594](https://github.com/kubevirt/kubevirt/pull/15597)
```release-note
Fix: grpc client in handler rest requests are properly closed
```

[release-1.0] Fix rest handler leak

---

pkg/virt-controller/watch/pool/BUILD.bazel
pkg/virt-controller/watch/pool/pool.go
pkg/virt-controller/watch/pool/pool_test.go
staging/src/kubevirt.io/api/pool/v1alpha1/types.go

- VEP tracking issue: https://github.com/kubevirt/enhancements/issues/69
Example usecase - When a pod is deleted manually or vmpool replica count is scaled down, and the vmpool is configured to preserve the state of the VM and PVC, it might be possible that the vm might have deleted by the time vmpool reconcile is triggered. Adding a finalizer will help in preserving the pvc before deleting the VM.
```release-note
Add VMpool finalizer to ensure proper cleanup
```

Add VMpool finalizer to ensure proper cleanup

---

pkg/virt-handler/migration-source.go
pkg/virt-handler/migration-target.go
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

And add missing volume unmount in that scenario to avoid stuck pods on deletion
Stopping a VM that has a migration ongoing keeps the VMI in the running state.
This is because the VM controller in virt-handler ignores VMs that are migrating.
The VM controller will **not** ignore migrating VMIs if they are getting deleted.
The added unmounting of volumes in that scenario will also ensure target pods get properly deleted.
```release-note
NONE
```

virt-handler: ensure the VM controller sees VMI deletions during migrations

---

automation/repeated_test.sh

We were suspecting that running a binary repeatedly causes noticeable
overhead on running a (sub)set of tests in a repeated manner to detect
flakiness in test cases.
Side note:
Some docs were missing proper formatting.
This change adds a flag that runs the test binary only once,
instead leveraging the `--repeat` flag provided by ginkgo v2 that will
cause the selected subset of tests to be run a number of times.
Measurements have given evidence that the average overhead of running
the test binary repeatedly is around 20% overall. The overhead seems to
increase when the number of tests is increased, although the increase
doesn't seem to be linear.
| run\_functest\_once | num\_tests | runtime | reduct. | red. % | command …

chore: introduce INVOKE_FUNCTEST_ONCE

---

pkg/virt-operator/resource/apply/patches.go
pkg/virt-operator/resource/apply/patches_test.go

Converting from map to array in `flagsToArray` may change flags order. This leads to unnecessary restarts of virt-handler, virt-controller, and virt-api.
Add a few flags for components:
```
kind: KubeVirt
...
spec:
customizeComponents:
flags:
api:
metrics-listen: 127.0.0.1
metrics-port: "8080"
controller:
metrics-listen: 127.0.0.1
metrics-port: "8080"
handler:
metrics-listen: 127.0.0.1
metrics-port: "8080"
...
```
I see unnecessary changes in flags order and components restarts:
```
--- /dev/fd/63	2025-09-10 16:48:30.749728663 +0300
+++ /dev/fd/62	2025-09-10 16:48:30.749728663 +0300
....
@@ -201,10 +201,10 @@
- "2"
command:
- virt-handler
-        - --metrics-listen
-        - 127.0.0.1
- --metrics-port
- "8080"
+        - --metrics-listen
+        - 127.0.0.1
...
--- /dev/fd/63 …
```

config: sort customizeComponents.flags in command

---

tests/vmi_lifecycle_test.go

/kind flake
/wg arch-arm
/cc @brianmcarey
/cc @0xFelix 
As documented in https://github.com/kubevirt/kubevirt/issues/15733 the arm64 lanes on main currently have a ~17% impact rate due to VMI lifecycle test VMIs failing to reach a running state within the current 45 second timeout.
This change increases this timeout as we don't appear blocked or failing and instead appear to be suffering due to lower test environment performance compared to our amd64 environments.
- Fixes #15733
We might want to invest some time into configurable timeouts across architectures but for now a simple bump should stabilise the arm64 lanes enough to allow them to start gating.
This …

tests: Increase VMI lifecycle startup timeout to help arm64 lanes

---

docs/debugging.md

Typos in the debugging.md file
Fixed Typos in the debugging.md file
- Fixes #15738 
```release-note
```

fixed typos in Debugging docs

---

pkg/controller/virtinformers.go
pkg/synchronization-controller/synchronization-controller.go
pkg/synchronization-controller/synchronization-controller_test.go
pkg/util/migrations/BUILD.bazel
pkg/util/migrations/migrations.go
pkg/virt-controller/watch/drain/evacuation/BUILD.bazel
pkg/virt-controller/watch/drain/evacuation/evacuation.go
pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
pkg/virt-controller/watch/migration/BUILD.bazel
pkg/virt-controller/watch/migration/migration.go
pkg/virt-controller/watch/migration/migration_test.go
pkg/virt-controller/watch/vmi/vmi_test.go
pkg/virt-controller/watch/workload-updater/workload-updater.go
pkg/virt-controller/watch/workload-updater/workload-updater_test.go

Optimizes the migration controller by adding custom indexers to migration informers, reducing full-list scans (O(n)) to indexed lookups (O(1)) for better performance at scale 
Functions like `listMigrationsMatchingVMI`, `filterMigrations`, `findRunningMigrations`, and `ListUnfinishedMigrations` iterateed over all migrations in a namespace using c.migrationIndexer.ByIndex(cache.NamespaceIndex, namespace) followed by in-memory filtering - this led to high CPU/memory usage and delays in large clusters
- add indexers to improve complexity and lookup time
- Next: move GC into a separate goroutine (in a separate PR)
- 
```release-note
NONE
```

Improve migration controller sync time

---

BUILD.bazel
cmd/pr-helper/BUILD.bazel
hack/bazel-build-images.sh
hack/bazel-push-images.sh
hack/push-container-manifest.sh

When building the images using rules_oci, the resulting digest file is created like this for virt-launcher
```
bazel-bin/cmd/virt-launcher/virt-launcher-image.json.sha256
```
Update the bazel-build-images.sh & push-container-manifest.sh to handle this change
```release-note
NONE
```

build: update container manifest push to handle new digest file

---

staging/src/kubevirt.io/api/go.mod
staging/src/kubevirt.io/client-go/go.mod
vendor/modules.txt

The golang version in
staging/src/kubevirt.io/api
and
staging/src/kubevirt.io/client-go
is adjusted to the golang version of the root directory. This enables bumping the golang library dependencies in these two directories in kubevirt 1.5 to newer versions depending on a newer golang version.
staging/src/kubevirt.io/api
and
staging/src/kubevirt.io/client-go
using go 1.22.0
staging/src/kubevirt.io/api
and
staging/src/kubevirt.io/client-go
using go 1.23.0
like the root of the project
https://groups.google.com/g/kubevirt-dev/c/yYRcbI_3ViE
- This change might break backward compatibility.
Not bumping the golang version would block PRs like https://github.com/kubevirt/kubevirt/pull/15572 and …

[release-1.5] Adjust go version staging

---

pkg/storage/snapshot/restore.go
pkg/storage/snapshot/restore_test.go
tests/libstorage/datavolume.go
tests/storage/restore.go

When restoring a VM from a VMSnapshot, and if the VM has a regular PVC owned by the VM, the restore would not properly set the owner reference for the restored PVC. This would cause the restored PVC to remain orphaned. Once the user deletes the VM, the restored PVC would not be deleted.
When restoring a VMSnapshot with a regular PVC not owned by a DataVolume, the restored PVC would not be owned by the VM (regardless of the restore policy). The PVC would remain orphaned.
If the restore policy is set to VM, then any restored PVCs associated with the VMSnapshot will be owned by the VM. These PVCs will no longer be orphaned when the VM is deleted.
- Fixes https://issues.redhat.com/browse/CNV-67307
Links to places …

Properly set owner references for restored PVCs

---

pkg/testutils/mock_priorityqueue.go

In unit tests, `ExpectAdds` will not see `AddWithOpts` calls on a mocked priority queue, because the function is not mocked.
`AddWithOpts` will now decrement the `WaitGroup` counter, just like other `Add` functions.
```release-note
NONE
```

priority queue: add missing mocked AddWithOpts

---

hack/bazel-push-images.sh
hack/push-container-manifest.sh

Rather than dynamically finding the images names in hack/bazel-push-images.sh - use the list of PUSH_TARGETS that is already present. This can prevent issues with the find missing images such as with the virtio-container-disk image that is causing the HCO nightly builds to fail
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-hco-push-nightly-build-main/1973237033346273280
Also add a check to see if the remote image exists before adding it to the multiarch manifest. 
```release-note …
```

build: update to use PUSH_TARGETS to generate list of images for hack/push-container-manifest.sh

---

pkg/virt-operator/kubevirt_test.go
pkg/virt-operator/resource/apply/apps.go
pkg/virt-operator/resource/apply/apps_test.go

Take the number of nodes KubeVirt is able to schedule to into account
when calculating the number of virt-api replicas. This should avoid
spawning too many in larger environments when KubeVirt is not
universally deployed.
- Fixes # https://issues.redhat.com/browse/CNV-68814
```release-note
Replicas of `virt-api` are now scaled depending on the number of nodes within the environment with the `kubevirt.io/schedulable=true` label.
```

virt-operator: Scale virt-api using NodeSchedulable count

---

tests/libmonitoring/prometheus.go
tests/monitoring/metrics.go

Reorganize monitoring metrics e2e tests
Hard to know which metric failed
Mixed setup with validations
Added a log to understand failures better
Separate setup checks from validation checks
```release-note
none
```

Reorganize monitoring metrics e2e tests

---

pkg/virt-controller/watch/migration/migration_test.go

As set out in #15795 the returned order of migrations with the same priority isn't guaranteed leading to the previous serial assertion flaking. This change hardens this assertion by moving it outside of the loop and asserting that the expected set of running migrations is returned by the first 5 calls to GetWithPriority.
- Fixes #15795
```release-note
NONE
```

virt-controller: Harden returned running migration from queue assertion

---

pkg/storage/snapshot/restore.go
tests/storage/restore.go

Manual backport of #15692
Biggest difference is there is no `VolumeOwnershipPolicy` logic that was introduced recently.
```release-note
BugFix: Restoring naked PVCs from a VMSnapshot are now properly owned by the VM if the restore policy is set to VM
```

[release-1.4] Properly set owner references for restored PVCs

---

pkg/virt-api/rest/objectgraph.go
pkg/virt-api/rest/objectgraph_test.go

This PR updates the Object Graph to include the following resources:
- NetworkAttachmentDefinitions, as agreed in prior discussions. 
- ServiceAccounts, which were previously unintentionally omitted.
A follow-up POC PR will be later implemented to include a generic resource inclusion mechanism for external dependencies such as IPAMClaims.
- Fixes: https://issues.redhat.com/browse/CNV-64186
```release-note
Object Graph: Include NADs and ServiceAccounts
```

Object Graph: Include NADs and ServiceAccounts

---

automation/test.sh
tests/reporter/kubernetes.go

This PR optionally collects `containerd` or `crio` debug information on functional test failure when a new `KUBEVIRT_COLLECT_CONTAINER_RUNTIME_DEBUG` env var is enabled.
```
$ env | grep KUBEVIRT
KUBEVIRT_PROVIDER=k8s-1.34
KUBEVIRT_COLLECT_CONTAINER_RUNTIME_DEBUG=true
$ ll _out/artifacts/k8s-reporter/nodes/1_*
-rw-r--r-- 1 lyarwood lyarwood 77855 Oct  1 14:07 _out/artifacts/k8s-reporter/nodes/1_crio-journal_node01.log
-rw-r--r-- 1 lyarwood lyarwood  8759 Oct  1 14:07 _out/artifacts/k8s-reporter/nodes/1_node01_crictl-images.log
-rw-r--r-- 1 lyarwood lyarwood  6934 Oct  1 14:07 _out/artifacts/k8s-reporter/nodes/1_node01_crictl-info.log
-rw-r--r-- 1 lyarwood lyarwood  4184 Oct  1 14:07 _out/artifacts/k8s-reporter/nodes/1_node01_crictl-pods.log
-rw-r--r-- 1 lyarwood lyarwood  9466 Oct  1 …
```

reporter: Add `containerd` and `crio` debug on functional test failure

---

pkg/virt-handler/BUILD.bazel
pkg/virt-operator/BUILD.bazel

Since https://github.com/kubevirt/kubevirt/pull/15561 we start observing several failures on the
unit test jobs due to virt-operator timeout: 
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-unit-test
The timeout arg was set on the go_test but not on the ginkgo_test. Even if the ginkgo_test is a wrapper of go_test, it simply executes the binary, and the `timeout` is not something configurable at build time.
This leads to a timeout executing the virt-operator parallel tests.
Setting the timeout on the ginkgo_test rule, too, will solve the issue. …

test: set timeout to ginkgo_tests

---

pkg/virt-operator/resource/generate/components/secrets.go
pkg/virt-operator/resource/generate/components/secrets_test.go

Previously, MergeCABundle would truncate to 50 certificates before removing expired ones, causing valid new certificates to be dropped while expired certificates were retained. Now expired certificates are filtered out first, then the 50-certificate limit is applied to valid certificates only.
Fixes failing test: external CA - should properly manage adding entries to the configmap
Code was assisted by Cursor AI
```release-note
fix: prioritize expired cert removal over 50-cert limit in MergeCABundle
```

fix: prioritize expired cert removal over 50-cert limit in MergeCABundle
