- tests/vmi_multus_test.go
The multus tests check that no VMI exists in the cluster before starting the tests.
In the case where a replica set is left when starting the test, the corresponding VMIs will be deleted, which causes the replica
set to re-instantiate them.
The very same `BeforeEach` block checks for all the VMIs to be gone for 6 minutes, which would fail.
By executing the `BeforeAll` block before the `BeforeEach`, we delete the entire namespace - replica sets included. As a direct
result of this, when we attempt to delete the VMIs from the namespace, we will find none, which enables the test setup to
succeed.
This issue is not seen on upstream KubeVirt since the multus tests are only executed on the CNAO lane, where the replica …
> Multus func tests remove leftovers

- tests/subresource_api_test.go
We have a lot of tests running in parallel doing various things now. This can increase the variability when it comes to how long pods take to schedule and execute. 
In this functional test, a pod is scheduled to execute a command using a k8s client with a specific service account. Sometimes that pod takes longer than 30 seconds to be scheduled and created which causes this test to fail (as seen below in a sample prow output) Increasing the time maybe help.
```
1/730 Tests Failed. | expand_less
-- | --
Subresource Api [rfe_id:1195][crit:medium][vendor:cnv-qe@redhat.com][level:component] Rbac Authorization For Version Command with authenticated user [test_id:3172]should be allowed to access subresource version endpoint expand_less34stests/subresource_api_test.go:79 Timed out after 30.000s. …
```
> Mitigates a flaky test timing issue

- WORKSPACE
Fixes a bug which was sometimes reading symlink names only partially
from a reader. Unblocks #4882.
Without this update sometimes headers are read only partially, leading to results like this:
```
Error: failed to write header ./usr/lib/.build-id/67/2958a88dfe80c7c25608df9a39899332792a5f: archive/tar: cannot encode header: invalid PAX record: "linkpath = o./../../../usr/lib64/gconv/RK1048.s\x00"
```
The last character, an `o` was not read in this case. 
Fixes #
```release-note
NONE
```
> Bump bazeldnf to v0.0.15

- tests/vmi_multus_test.go
Two problems were found in this test:
- the error was not being checked
- the commands were not being sent to the VM ('\n' was missing)
Fixes #
#4905 should be rebased on top of this
```release-note
NONE
```
> multus, tests: assert error does not happen

- pkg/host-disk/host-disk.go
- pkg/virt-controller/services/template.go
- tests/storage_test.go
- tests/vmi_lifecycle_test.go
Currently, Virtio-FS is horribly broken when trying to do file operations as a non root user inside a guest.
Trying to write to a file leads to a very strange behavior:
```
open("test5", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
write(3, "data\n", 5)                   = -1 EPERM
```
The file descriptor opens, but the actual write fails with a permission error. Not very POSIX compliant. The source of this is the `fsGroup` that gets set in the security context of the virt-launcher Pod. As the `runAsUser` is root, I do not see the point of setting `fsGroup` and have simply removed it. Another option would be to just disable it when there are `Filesystems` attached, but introducing such subtle behavior changes can lead to more headaches down the line.
Is there a good reason to keep `fsGroup`? …
> Remove FSGroup from Pod spec to allow non-root guest usage of Virtio-FS

- pkg/cloud-init/cloud-init.go
This change fixes two `cloudinit.GenerateLocalData` issues raised by @ezrasilvera. It drops a needless `files` variable, and it defers removal of files right after they are created.
```release-note
NONE
```
> cloudinit.GenerateLocalData: minor refactoring

- pkg/virt-handler/device-manager/common.go
- pkg/virt-handler/device-manager/device_controller.go
- pkg/virt-handler/device-manager/pci_device_test.go
permittedHostDevices should support both upper and lowercase letters in the device ID
Fixes # #4925 
```release-note
permittedHostDevices will support both upper and lowercase letters in the device ID
```
> [fix] allow permittedHostDevices to support both upper and lowercase letters in the device ID

- tests/vmi_configuration_test.go
If the test runs at the top of the minute and the time on the node is slightly behind,
hwclock shows the previous minute and the test fails.
Changing from allowing just 1 minute in the future to 20 second both ways.
Also added verbosity to more easily debug this in the future if needed.
Fixes #
```release-note
NONE
```
> tests: fix flakyness on timezone test

- tests/storage_test.go
A couple of storage tests under test_id 3106 are almost always failing.
This is currently under investigation, but disabling them in the meantime will unblock the merging of PRs.
Fixes #
```release-note
NONE
```
> tests: temporarily disabling couple of extremely flaky test

- tests/reporter/kubernetes.go
This PR attempts to fix 2 different issues in the K8s test reporter:
- some parameters on the dmsg / audit logs print to stdout had whitespaces in between, causing an invalid command to be displayed
- the command to print the audit log features the audit log path twice
Other than this, I set the command in a variable, so we do not repeat ourselves.
Fixes #
```release-note
NONE
```
> Fix k8s reporter audit / dmsg log collection

- tests/framework/storage/nfs.go
Change the image pull policy for the NFS test pod to IfNotPresent
To mitigate #4962 
Related to #4960 
```release-note
NONE
```
> change the image pull policy for the NFS test pod to IfNotPresent

- pkg/virt-controller/services/template.go
- pkg/virt-controller/services/template_test.go
- pkg/virt-launcher/virtwrap/util/libvirt_helper.go
Signed-off-by: iholder <iholder@redhat.com>
Libvirt debug logs are being enabled if a label with "debugLogs"
key exists, without any dependency on the label's value.
For example, label definition "debugLogs: false" will
enable debug logs since "debugLogs" key exists.
After fix debug logs are to be enabled only if the label's
value is "true" (case in-sensitive).
Also, a unit-test was added to verify that the bug was fixed.
```release-note
Bug fixed: Enabling libvirt debug logs only if debugLogs label value is "true", disabling otherwise.
```
> Fix bug enabling libvirt debug logs if debugLogs label key exists

- pkg/cloud-init/cloud-init.go
- pkg/ephemeral-disk-utils/BUILD.bazel
- pkg/ephemeral-disk-utils/utils.go
- pkg/ephemeral-disk-utils/utils_suite_test.go
- pkg/ephemeral-disk-utils/utils_test.go
- pkg/virt-handler/vm.go
- pkg/watchdog/watchdog.go
Introduce a few tests to document RemoveFile and FileExists; simplify RemoveFile and rename it.
```release-note
NONE
```
> ephemeral-disk-utils: add few harmless tests and rename RemoveFile

- pkg/util/sysctl/sysctl.go
- pkg/virt-launcher/virtwrap/network/common.go
- pkg/virt-launcher/virtwrap/network/generated_mock_common.go
- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
- tests/utils.go
- tests/vmi_cloudinit_test.go
- tests/vmi_lifecycle_test.go
- tests/vmi_multus_test.go
- tests/vmi_networking_test.go
When kubelet is restarted, it goes over all pods, peeks in their
respective network namespaces and tries to detect their IP in order
to update their Pod objects.
However, with the bridge binding mode, we move this IP address to VM
and the pod interface is left IP-less. That causes kubelet's IP check
to fail and results in pod removal.
With this patch, we use a dummy interface named after the pod interface
to keep the pod IP address. When kubelet performs the check, it sees
interface with expected name (eth0) and reports its IP address on
Pod object.
Fixes: #2076
Authored-by: Petr Horacek <phoracek@redhat.com>
Authored-by: Ryan Hallisey <rhallisey@nvidia.com>
```release-note
VMs using bridged networking will survive a kubelet restart by having kubevirt create a dummy …
```
> keep original pod ip on a dummy interface

- repo.yaml
Fedora renamed branches to get rid of `master`. This broke some download
paths for us for gpg keys.
Here the announcement: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/IIGSUCATNFURZXKFHOQMLPN4PHQHEUAZ/
```release-note
NONE
```
> Fix gpg download url for fedora keys

- pkg/controller/expectations.go
The string "KeyFunc was changed, %v"
was duplicated 3 times in expectations.go, now a constant is defined to
avoid duplication.
Discovered by SonarCloud:
tinyurl.com/4sgtd4br
```release-note
NONE
```
> [SonarCloud]: Create constant to avoid string duplication

- WORKSPACE
We noticed that there are some images required by the build still hosted on Docker Hub after a recent outage of this service, it caused failures like https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4927/pull-kubevirt-e2e-k8s-1.20/1357016928580800512
I've moved these images to quay under the kubevirtci organization, this PR updates the references to use the quay images instead of the docker hub ones. 
Fixes #
```release-note
NONE
```
> WORKSPACE: update image references to use quay instead of docker hub

- cmd/example-hook-sidecar/smbios.go
The string "Hook's OnDefineDomain callback method has been called"
was duplicated 3 times in smbios.go, now a constant is defined to
avoid duplication.
Discovered by SonarCloud:
tinyurl.com/vhttfg0f
```release-note
NONE
```
> [SonarCloud] Create constant to avoid string duplication

- api/openapi-spec/swagger.json
- manifests/generated/kv-resource.yaml
- pkg/virt-operator/resource/apply/patches.go
- pkg/virt-operator/resource/apply/patches_test.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
We should allow users to use a wildcard selector for applying patches on resourceName and resourceType. This is a continuation of an older PR https://github.com/kubevirt/kubevirt/pull/4575
It also changes all fields of a Patch object to be required if a patch is specified. 
A follow up PR to add a validationwebhook for create and update of the KubeVirt CR that does not allow for empty strings is needed. 
Fixes #
```release-note
Change customizeComponents.patches such that '*' resourceName or resourceType matches all, all fields of a patch …
```
> Patches generic match

- pkg/virt-launcher/notify-client/notify_test.go
- pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
- pkg/virt-launcher/virtwrap/cli/libvirt.go
- pkg/virt-launcher/virtwrap/manager_test.go
- pkg/virt-launcher/virtwrap/util/BUILD.bazel
- pkg/virt-launcher/virtwrap/util/libvirt_helper.go
- pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go
- tests/migration_test.go
Virt-launcher will fail to send a correct domain when the domain is transient. This will corrupt the cache of `virt-handler` and cause bad decisions in the sync loop. This PR ensures we retrieve the correct domain even in a transient state.
Fixes #
BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1883875
https://bugzilla.redhat.com/show_bug.cgi?id=1886453
The root cause for seeing this is the fact that the domain stays transient after migration. Investigating...
```release-note
Fixing handling of transient domain
```
/cc @vladikr
> Support extracting metadata for transients domains

- pkg/util/sysctl/sysctl.go
- pkg/virt-launcher/virtwrap/network/common.go
- pkg/virt-launcher/virtwrap/network/generated_mock_common.go
- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
Set up necessary `net.ipv4.ip_forward=1` to use masq in kubevirt pod
drop depends on upstream CNI.
Fixes #2942 
```release-note
```
> Fix vmi created with pod masq on calico cannot be accessed

- pkg/host-disk/host-disk.go
- pkg/host-disk/host-disk_test.go
- pkg/virt-launcher/virtwrap/manager.go
- tests/storage_test.go
`host-disk.go` assumes that all PVCs mounted into the Pod will be used to mount a Block Volume to the VM. Therefor it converts the PVCs to a `HostDisk` and later on creates a `disk.img` in there. This fix checks to see if the PVC is used in a `Filesystem`. If it is, it does not convert the PVC to a `HostDisk` and no disk image is created.
Fixes #4440
```release-note
Fix a bug where a disk.img file was created on filesystems mounted via Virtio-FS
```
> Do not create Host Disks for Virtio-FS PVCs

- pkg/virtctl/imageupload/imageupload.go
On successful upload, file is closed by http transferWriter via BodyCloser, so we prevent double-close.
Solve virtctl "Error when closing file ... file already closed" that shows after successful image upload
```release-note
Solve virtctl "Error when closing file ... file already closed" that shows after successful image upload
```
> Prevent virtctl file double-close on successful upload

- pkg/virt-controller/services/template.go
Sometimes the attachmentPod would fail to start due to OOM. Increase
the limit to something higher to prevent the OOM during startup.
Prevent OOM on attachmentpod startup.
Fixes #
```release-note
NONE
```
> Increase mem limit on attachmentPod to prevent OOM

- automation/test.sh
Use make cluster-sync as this is the official target.
Remove the until, in case the cluster-sync is failed,
we shouldn't mask it with an infinite retry,
nor try forever in case there is a non transient failure,
consuming the resources of the CI.
The reasons it was used are outdated, as we don't have
a OKD provider anymore under kubevirtci.    
```release-note
None
```
> automation, Use cluster-sync instead its partial targets

- pkg/virt-handler/container-disk/mount.go
Sometimes the container disk is for whatever reason not ready. Unfortunately, we don't log that reason, which keeps us in the dark when such things occur.
Fixes #
```release-note
NONE
```
> container disk: log error reason when the disk is not ready

- cmd/virt-launcher/virt-launcher.go
- pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
- pkg/virt-launcher/virtwrap/converter/BUILD.bazel
- pkg/virt-launcher/virtwrap/converter/converter.go
- pkg/virt-launcher/virtwrap/converter/converter_test.go
- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
- tests/vmi_lifecycle_test.go
Add capability to enable QEMU SeaBios debug logs. This can be done through setting virt-launcher log verbosity to be greater than 5.
```release-note
Now it is possible to enable QEMU SeaBios debug logs setting virt-launcher log verbosity to be greater than 5.
```
> Support enabling QEMU SeaBios debug logs virt-launcher log verbosity

- pkg/virt-config/config_test.go
- pkg/virt-config/feature-gates.go
- pkg/virt-controller/services/BUILD.bazel
- pkg/virt-controller/services/template.go
- pkg/virt-controller/services/template_test.go
- pkg/virt-handler/vm.go
- pkg/virt-handler/vm_test.go
- pkg/virt-operator/resource/generate/components/scc.go
- tests/vmi_multus_test.go
At the current state, if you try to migrate SRIOV VM it will fail constantly with no error from virt-api (admission or validation webhooks).
Also libvirt doesn't support migration for domain that has SRIOV host-devices attached.
We would get the following error on VMI description if we try:
```
VirtualMachineInstance migration uid bc2b1c0d-b858-44ee-b043-382caad887c8 failed. reason:Live migration failed virError(Code=84, Domain=10, Message='Operation not supported: cannot migrate a domain with <hostdev mode='subsystem' type='pci'>')
```
Even though live migration for SRIOV VMs will always fail it is not blocked on kubevirt which may cause confusion.
Thus it should be blocked and return informative error until it will be supported. …
> Add feature-gate for SRIOV Live Migration feature

- pkg/virt-launcher/virtwrap/network/BUILD.bazel
- pkg/virt-launcher/virtwrap/network/common.go
- pkg/virt-launcher/virtwrap/network/common_test.go
- pkg/virt-launcher/virtwrap/network/generated_mock_common.go
- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
Currently the default is iptables, and only if iptables are not working we
try to use nft.
Since iptables is deprecated in fedora 32 we need to change the default to
be nft.
Fixes #
```release-note
virt-launcher, masquerade binding - prefer nft over iptables.
```
> virt-launcher: make nftables as the default

- pkg/virt-controller/services/template.go
- pkg/virt-controller/watch/vmi.go
- pkg/virt-controller/watch/vmi_test.go
- tests/datavolume_test.go
- tests/storage/hotplug.go
- tests/utils.go
Hotplug is now supported on WFFC datavolumes. This means the following happens when you hotplug a WFFC datavolume:
1. virt-controller detects the datavolume being hotplugged is WFFC, and not ready.
2. virt-controller creates a 'trigger' pod with the same affinity of a regular attachment pod.
3. This triggers the WFFC DV to become bound on the node the VM is running on.
4. This triggers CDI to populate the datavolume
5. Once CDI is done populating the datavolume, virt-controller now attaches the volume to the VM in same manner as before.
Fixes # …
> WFFC support for hotplugging volumes

- manifests/generated/operator-csv.yaml.in
- manifests/generated/rbac-operator.authorization.k8s.yaml.in
- pkg/util/lookup/BUILD.bazel
- pkg/util/lookup/lookup.go
- pkg/util/lookup/lookup_suite_test.go
- pkg/util/lookup/lookup_test.go
- pkg/virt-controller/watch/BUILD.bazel
- pkg/virt-controller/watch/node.go
- pkg/virt-controller/watch/node_test.go
- pkg/virt-operator/resource/generate/rbac/controller.go
This will give insight into the state of the cluster and let the operator know that some of their VMIs are in an orphaned state. They can then choose to shut down the VMIs or rerun the `virt-handler` on the node to migrate the VMIs off the node before re-removing the `virt-handler`. If the user in facts does not want the node running the `virt-handler`. 
This only creates an `event` if a node is running a VMI, the `virt-handler` is missing, and the virt-handler `daemonset` is running as expected and not in a transient state. 
Fixes #
**Special …
> add event for virt-handler missing

- Makefile
- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
- tests/migration_test.go
- tests/utils.go
This PR makes the libvirt migration target domains persistent, as opposed to transient.
Fixes #
```release-note
Migrated VMs stay persistent and can therefore survive S3, among other things.
```
> Migrate to persistent target domains instead of transient ones

- manifests/generated/operator-csv.yaml.in
- manifests/generated/rbac-operator.authorization.k8s.yaml.in
- pkg/virt-operator/resource/generate/rbac/cluster.go
Kubevirt resource is in category all.
`kubectl get all` fails if the user don't have the permissions to list Kubevirt resource.
Fixes #4888
```release-note
NONE
```
> Allow kubevirt:edit role to get,list kubevirts

- cmd/virt-handler/BUILD.bazel
- cmd/virt-handler/virt-handler.go
- pkg/controller/virtinformers.go
- pkg/virt-handler/vm.go
While looking through virt-handler logic, i realized we were creating multiple VMI informers. One of them is actually watching all VMIs in the entire cluster, which doesn't scale well for us in large cluster scenarios.
This PR consolidates our VMI informers used by virt-handler, and ensures we only use ones that target VMIs that are scheduled on the node in question, or are being migrated to the node in question. The VNC/Console handlers only need to be aware of the VMIs currently scheduled to the node, which is why that specific change has been made. 
```release-note
NONE
```
> Virt-handler should only be informed of VMIs scheduled on virt-handler nodes

- tests/job.go
- tests/migration_test.go
- tests/pod_servers.go
- tests/utils.go
- tests/vmi_lifecycle_test.go
The `Job`s being used to encapsulate HTTP / TCP / UDP clients that validate the functionality of Kubevirt's exposed `Service`s
should not be run as privileged pods, or share the host's PID namespace - both of these security options require a particular SCC on Openshift, something which is not being provisioned.
The simplest way out is to provide an option to have both privileged / unprivileged pods and let the developers choose which to use according to their requirements. 
In this case, the `Job`s do not require to be run as privileged, hence, we can just the `RenderPod` function, which creates wraps the `Job` in an unprivileged pod.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will …
> Run service clients as non privileged pods

- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
- tests/migration_test.go
- tests/utils.go
This is a manual cherry-pick of #5010
```release-note
Migrated VMs stay persistent and can therefore survive S3, among other things.
```
> [release-0.34] Migrate to persistent target domains instead of transient ones

- tests/vmi_configuration_test.go
None of events, virt-laucher logs or kubelet log suggest any issue other than that
the termination of the virt-launcher pod sometimes takes over 60 seconds,
which is the current timeout. 
After running the test in a loop, I got the following times of the virt-launcher deletion:
1) 29.204046882s
2) 22.108061286s
3) 44.314289431s
4) 1m4.375520696s
5) 1m5.409205096s
6) 1m3.500083379s
...
After increasing the timeout to 120s, the test has passed more than 20 times without failure. 
Fixes #5008
Fixes #5005
Fixes #4998 …
> Increase wait timeout for VMI deletion in tests/vmi_configuration_test.go

- docs/updating-dependencies.md
All the doc links need to point up a directory, to work in the
github web UI
```release-note
NONE
```
> docs: Fix links in update-dependencies.md

- tests/vmi_multus_test.go
The subnet of the ptp network, used in the multus tests,
is hard-coded, and the ptp gateway as well,
and they are being used through out the tests many times.
For that in this commit the subnet is extracted to a const, and the ptp-getaway
is calculated using the ip package of ptp cni-pluginy:
https://github.com/containernetworking/plugins/blob/master/pkg/ip/cidr.go.
In that way, the ptp subnet and gateway address can be changed in one place, if needed.
Signed-off-by: alonSadan <asadan@redhat.com>
Fixes #
```release-note
NONE
```
> multus-tests, ptp: extract ptp subnet to a const

- tests/utils.go
E2e tests use waitForVMI in order to check the vmi is starting.
`waitForVMIPhase` waits that `vmi.Status.Phase` will reach one of the desired phases, according its called arguments.
For example it can be one of the list `v1.Scheduling, v1.Scheduled, v1.Running` in one of its calls.
In case `waitForFail` is false, or if `v1.Failed` is included in the phases list it will assert / return upon `Fail` as well.
While waiting for the phase, it can create a watcher which will listen to VMI events and has two variants:
1. Log VMI warnings events, assert on VMI error events.
2. Assert both on VMI warning events and error events.
In case `ignoreWarnings` is true, it didn't create a watcher at all,
so VMI error events as well were not asserted / logged by the test's watcher.
The VMI might reach any …
> tests, Enable watching for vmi errors in case ignoreWarnings is true

- docs/devel/host-devices-and-device-plugins.md
As in https://github.com/kubevirt/user-guide/pull/396, device plugin
resourceName should match the case of deviceName requested by VMs.
```release-note
NONE
```
/cc @vladikr
> docs: host devices: resourceName case consistency

- tests/storage_test.go
- tests/utils.go
- tests/vmi_configuration_test.go
- tests/vmi_multus_test.go
In case running multi sriov jobs on CI,
transient warnings such as the following, occur [1]
`unknown error encountered sending command SyncVMI:
rpc error: code = DeadlineExceeded desc = context deadline exceeded`
It happens only when there are 2+ jobs at the same time, and if each of the job runs
2 VMs at the same time.
In this case it happens to around 30% of the jobs.
Kubevirt itself has a re-enqueuing mechanism for this kind of warnings,
so their effect is transient, and the test would pass once continued.
Add a mechanism to allow switching selected warnings
to be non fatal.
Use this mechanism in order to update this warning severity
to log only instead of failing the test.
There are some open issues that point
its related to resource extensive usage [2] (tried the suggested method): …
> sriov, Let SyncVMI DeadlineExceeded warning be non fatal in tests

- hack/builder/Dockerfile
- hack/builder/build.sh
- hack/builder/publish.sh
- hack/builder/version.sh
- hack/dockerized
Migrates the kubevirt/builder image from Docker Hub to quay.io
This PR also updates the image with `operator-courier 2.1.11` which is needed for some follow up work (WIP) done in https://github.com/kubevirt/kubevirt/pull/5017
Fixes #
```release-note
NONE
```
> Move kubevirt/builder image to quay.io

- pkg/virt-launcher/virtwrap/cli/libvirt.go
- pkg/virt-launcher/virtwrap/manager.go
Fix possible memory leak of `libvirt.Domains`. In these cases, the domains were not freed using `defer`.
```release-note
None
```
> Fix possible memory leak of libvirt.Domains

- examples/vm-alpine-datavolume.yaml
- examples/vm-alpine-multipvc.yaml
- examples/vm-cirros.yaml
- examples/vm-priorityclass.yaml
- examples/vmi-block-pvc.yaml
- examples/vmi-ephemeral.yaml
- examples/vmi-flavor-small.yaml
- examples/vmi-host-disk.yaml
- examples/vmi-migratable.yaml
- examples/vmi-nocloud.yaml
- examples/vmi-preset-small.yaml
- examples/vmi-pvc.yaml
- examples/vmi-replicaset-cirros.yaml
- examples/vmi-sata.yaml
- tests/libvmi/factory.go
- tests/restore_test.go
- tests/storage_test.go
- tests/utils.go
- tests/vm_test.go
- tests/vmi_configuration_test.go
- tests/vmi_iothreads_test.go
- tests/vmi_networking_test.go
- tests/vmi_slirp_interface_test.go
- tools/vms-generator/utils/utils.go
A OOM on Cirros ext4 file system was observed on Issue https://github.com/kubevirt/kubevirt/issues/4902
test_id:3134 which cause test to flake (more details at issue).
Changes of this PR:
* As suggested by Cirros community [1],
increase default VMI memory to be 128Mi
instead of 8Mi or 64Mi in the specific
functions that create VMI template and update
the memory request to 64M.
(affect other VMIs types as well, but only increase memory).
* Use the right notation of Mi instead of M.
* Remove duplicate memory settings in order
to make code lighter.
* The flake of test_id:3134 was detected when there was 64MB memory.
increase it to 512Mi, as it's guaranteed safe
according to the Cirros community.
128Mi might be enough, but Cirros boot tests
use 512Mi, so better be on the safe side.
The job …
> tests, Increase default memory of VMIs to 128Mi

- pkg/virt-operator/resource/generate/components/deployments.go
Reduces our liveness and readiness probe intervals. By default the probe is called every 10 seconds. With this change we only call liveness every 45 seconds and readiness every 20. Since the probes result in virt-handler verifying connectivity to the api server, we should reduce the probe interval. 
related to #5058 
```release-note
NONE
```
> Lower virt-handler probe intervals to prevent api server calls

- tests/vmi_multus_test.go
Sriov tests doesn't need to configure ipv6 for pod network,
as they don't check deafault pod network.
Moreoever in case we do need to config it, the right way
will be to use NetworkData, as it would also solve
potential misconfiguration that using hardocoded eth0
might lead to.
```release-note
None
```
> tests, sriov: Do not configure pod network IPv6 on fedora-login

- api/openapi-spec/swagger.json
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
We have no description for kubevirt VMIPreset right now. This PR adds a brief description that will also show in documentation.
Feel free to suggest a better description.
```release-note
None
```
> Add description to VirtualMachinePreset

- automation/run-quarantined-tests.sh
- automation/test.sh
- tests/imageupload_test.go
- tests/operator_test.go
- tests/storage_test.go
- tests/vmi_networking_test.go
**What this PR does / why we need it**: apply the `[QUARANTINE]` label to the flakiest tests at the moment, these tests won't be executed on the required lanes and will be run on separated non-required lanes added in this PR https://github.com/kubevirt/project-infra/pull/1003 
The quarantined tests have been selecting taking into account the most flaky tests as reported by testgrid here:
https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-e2e-k8s-1.17&width=20&show-stale-tests=
https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-e2e-k8s-1.17-rook-ceph&width=20&show-stale-tests=
https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-e2e-k8s-1.18&width=20&show-stale-tests= …
> Quarantine flakiest tests

- pkg/virt-launcher/virtwrap/network/network.go
- pkg/virt-launcher/virtwrap/network/network_test.go
The network package has a `podNICFactory = newpodNIC` that it mocked by the tests. I wish we could avoid these cumbersome mocking and have cleaner simpler tests. This PR is small step towards that, as it makes the factory function simpler and more focused to doing the one thing it should (creating a new `podNIC` object).
There should be no functional change in this PR.
```release-note
NONE
```
> network: simpler factory

- tests/vmi_headless_test.go
Let the failure text state the numbers which failed comparison.
```release-note
NONE
```
> test_id:713: make failure slightly more legible

- pkg/container-disk/container-disk.go
- pkg/container-disk/container-disk_test.go
- pkg/virt-controller/services/template.go
- pkg/virt-controller/services/template_test.go
This PR fixes the following bug: https://bugzilla.redhat.com/show_bug.cgi?id=1731819
Migration pods became evicted since no they used ephemeral-storage that they didn't request. Therefore this PR adds an ephemeral-storage of small amount (1MB) to both compute and volume-disk containers.
Unfortunately I couldn't reproduce the error. I've consulted @vladikr which said it might be very difficult to reproduce the bug locally.
```release-note
NONE
```
> [Bug-fix]: Migration pod becomes "Evicted" since no ephemeral-storage is requested

- pkg/virtctl/imageupload/imageupload.go
- pkg/virtctl/imageupload/imageupload_test.go
In case we tried to upload image to dv with a given
name of an existing pvc we would reach command timeout
since we try to get the dv with that name and it doesnt exist.
In case of upload to DV we need to also check if a DV with that name
exist.
Fixed the relevant test scenario to check for the new error.
Also added extra prints to other flows.
Fixes # BZ 1927473
```release-note
NONE
```
> handle image upload to data volume with existing pvc name

- automation/repeated_test.sh
Due to an error in the new_tests grep expression the names of the
changed tests were wrong in case of test file movement. We now
exactly grep the new file names and skip the sed later on.
Example run: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5170/pull-kubevirt-check-tests-for-flakes/1368948867701149698
Fixes #
@EdDev FYI , either cherry-pick the change or rebase your PR on this one
```release-note
NONE
```
> Fix repeated_test.sh on file rename

- pkg/virt-launcher/virtwrap/converter/converter.go
- pkg/virt-launcher/virtwrap/converter/converter_test.go
fix case when user set hyperv features and they omit the stimer feature
```
NONE
```
> fix stimer hyperv feature

- tests/imageupload_test.go
Test 4621 fails waiting for upload pod to be ready. Sometimes the upload pod has a slow start (probably image pulling). Updating timeout should help.
Updates timeout.
Fixes #
https://github.com/kubevirt/kubevirt/issues/4527
https://github.com/kubevirt/kubevirt/issues/4868
```release-note
NONE
```
> Extend timeout for a flaky imageupload test

- docs/metrics.md
- pkg/monitoring/vms/prometheus/fakeCollector.go
- pkg/monitoring/vms/prometheus/prometheus.go
- pkg/monitoring/vms/prometheus/prometheus_test.go
- pkg/virt-launcher/virtwrap/cli/BUILD.bazel
- pkg/virt-launcher/virtwrap/cli/libvirt.go
- pkg/virt-launcher/virtwrap/stats/types.go
- pkg/virt-launcher/virtwrap/statsconv/converter.go
- pkg/virt-launcher/virtwrap/statsconv/converter_test.go
- pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
- add dropped packets count
- split total errors metric to transmit and receive
- split total packets count metric to transmit and receive
- add metric for transmit and receive bytes while keeping the previous
metric in order to not break the UI
- modified networking metrics to display the interface alias label
instead of the guest target device
Fixes #
These metrics can be collected by executing `curl -sk http://localhost:8443/metrics` on the virt-handler pod
```release-note
Modified …
```
> Add networking metrics

- tests/utils.go
Initialize the KubeVirtDefaultConfig to original KV cluster configuration. 
The issue was that `KubeVirtDefaultConfig` wasn't
initialized in case the tests were run w/o the `--apply-default-configuration`
flag, but on the other hand this variable is being unconditionally used in the 
`BeforeTestCleanup()` function.
```release-note
NONE
```
> [tests] Fix kubevirt default configuration initialization

- pkg/virt-launcher/virtwrap/network/common.go
- pkg/virt-launcher/virtwrap/network/generated_mock_common.go
- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
Currently, we only have an option to create a tap device for root (there is a hardcoded default user&group owner). This PR just allow to pass user from place where we have VMI object.
This PR will easy following work for non-root launcher.
Fixes #
```release-note
None
```
> Allow to create tap device for any user

- docs/release-branch-backporting.md
- docs/release.md
This PR adds a document outlining our policy and expectations when it comes to backporting bug fixes to stable release branches. It's important that we as maintainers of the project uphold the policy outlined here so we clearly communicate what fixes are going into our release branches.
```release-note
Added our policy around release branch backporting in docs/release-branch-backporting.md
```
> Policy and criteria for backporting to stable release branches

- tests/vmi_networking_test.go
IPv6 connectivity check to the statically set address fails on CI.
The same tests pass locally.
Marking the assertion with xfail in order to allow investigation.
Ref: https://github.com/kubevirt/kubevirt/issues/5113
Fixes #
Seen on https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-e2e-k8s-cnao-1.19
Originally raised by @enp0s3 on slack.
```release-note
NONE
```
> tests, network: XFail IPv6 connectivity check to an external address

- tests/migration_test.go
- tests/operator_test.go
- tests/vm_test.go
This PR marks tests as ```[release-blocker]``` that are required to be enabled and passing before a new release can be cut. 
A [release-blocker] test is defined as a test that validates functionality involved with ensuring a release can handle seamless non-disruptive Kubernetes and KubeVirt updates. This includes validating basic updates from previous kubevirt releases as well as other update related functionality like migrations, pod eviction handling, and kubevirt API versioning support.
The idea here is that we'll never cut a release without all the  ```[release-blocker]``` passing, which will at a very minimum ensure that we have a path for delivering non-disruptive fixes.
As we move forward with addressing flaky tests, when a ```[release-blocker]``` test becomes flaky we need to …
> Add [release-blocker] test marker for critical tests involved with update path. 

- pkg/virt-launcher/virtwrap/device/sriov/hostdev_test.go
Currently some unit-tests fail randomly. The PR addresses the problem. It fixes timeout values in sriov package. The details are provided bellow.
The timeout of 1ns used in sriov unit tests is too strict for the
bellow case:
for {
select {
case ...:
...
case <-time.After(timeout):
...
}
}
Here the compiler will place the 'time.After(...)' call prior to the
'select' block (that can be observed in objdump). The call is equivalent
to 'NewTimer(...).C' and it will start the timer. Then each 'case'
statement will be probed for readiness (in the "source order") and the
timeout of 1ns has a good chance to expire. If several 'cases' are ready
to proceed, a single one is "chosen via a uniform pseudo-random select"
(according to the golang spec). That causes …
> Increase timeouts in sriov unit tests

- manifests/generated/kv-resource.yaml
- pkg/util/webhooks/validating-webhooks/BUILD.bazel
- pkg/util/webhooks/validating-webhooks/validating-webhook.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- pkg/virt-operator/webhooks/BUILD.bazel
- pkg/virt-operator/webhooks/kubevirt-update-admitter.go
- pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
This adds validation to KV resources CustomizeComponents object. It lets the user know before applying that empty strings for the `ResourceName` and `ResourceType` are not valid. It will also alert the user if the `patch` that they have provided is not valid json. 
This is a follow up to PR #4984 
Fixes #
```release-note
Add validation to CustomizeComponents object on the KubeVirt resource 
```
> add validationwebhook for KubeVirt.Spec.CustomizeComponents

- pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
- pkg/virt-launcher/virtwrap/cli/libvirt.go
- pkg/virt-launcher/virtwrap/device/sriov/BUILD.bazel
- pkg/virt-launcher/virtwrap/device/sriov/hostdev.go
- pkg/virt-launcher/virtwrap/device/sriov/hostdev_test.go
When detaching a SR-IOV host-device, the existing `DetachDevice`
function only updates the domain live state.
In order to update the domain config, the `DetachDeviceFlags` needs to
be used and instructed to update both domain states.
Fixes #
This should be a per-requirement for #5037 .
The issue has pop up after #5010 got in, fixing the domain mode on the target (from transient to persisted).
```release-note
NONE
```
> virt-launcher, sriov: Update the domain config state on detach

- automation/repeated_test.sh
Instead of several greps which will be error prone when renamed files
are in the changeset we just use the --diff-filter and awk print the
last column which always results in the new file name.
Also as test files do not necessarily have to have the _test suffix we
just grep for .go (while still excluding suite files).
Fixes #
```release-note
NONE
```
> Simplify greps in determination of new tests

- docs/metrics.md
- pkg/monitoring/vms/prometheus/fakeCollector.go
- pkg/monitoring/vms/prometheus/prometheus.go
- pkg/monitoring/vms/prometheus/prometheus_test.go
- pkg/virt-launcher/virtwrap/cli/libvirt.go
- pkg/virt-launcher/virtwrap/stats/types.go
- pkg/virt-launcher/virtwrap/statsconv/converter.go
- pkg/virt-launcher/virtwrap/statsconv/converter_test.go
- pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
- tests/infra_test.go
- Split swap traffic bytes metric to swap in and swap out
- Expose counter metrics for minor and major page faults
- Expose gauge metric for actual balloon bytes
- Expose gauge metric for usable memory bytes
- Expose gauge metric for total used memory
Fixes #
```release-note
Modified memory related metrics by adding several new metrics and splitting the swap traffic bytes metric
```
> Modify memory metrics

- automation/test.sh
- tests/network/expose.go
- tests/network/networkpolicy.go
- tests/network/vmi_multus.go
- tests/network/vmi_networking.go
- tests/network/vmi_slirp_interface.go
In order to have a method to run sig-network tests in an isolated environment,
mark the relevant tests with `sig-network`.
The dedicated job that has `sig-network` on its TARGET,
would run only the tests that are marked with `[sig-network]`.
CNAO is deployed on `sig-network` jobs.
See https://github.com/kubevirt/project-infra/pull/1007
```release-note
None
```
> sig-network, Add networking tests to the sig network family

- pkg/virt-operator/webhooks/BUILD.bazel
- pkg/virt-operator/webhooks/kubevirt-update-admitter.go
- pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go
- tests/operator_test.go
- tests/vmi_lifecycle_test.go
Allow modifying the node layout with kubevirt installed via taints and
labels without having to shut down all VMIs.
Previously, changing node layout was possible, but it was not possible
to adjust the KubeVirt installation without shutting down all VMIs
first.
The admin-supporting aspect of this feature, to detect if VMIs are left
unmonitored on some nodes where virt-handler is not running, is now
covered via proper alerting.
Further it fixes flakyness in the following test, if CI nodes were under pressure:
```
[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Creating a VirtualMachineInstance [Serial]when virt-handler is not responsive [test_id:1634]the …
```
> [virt-operator] Remove a webhook check which checks workload placement

- go.mod
- pkg/virt-handler/vm.go
- pkg/virt-handler/vm_test.go
Migrations are complicated to start with and our code paths in virt-handler compound that complexity by intertwining source and target code paths. 
This PR is an effort to begin detangling the source and target migration code paths by refactoring these logical chunks into standalone functions. It should be easier to follow what logic is invoked in certain scenarios now which will help us during debugging and future development. 
No functional impact is expected to occur as a result of these patches. I have some logical changes/fixes coming in future PRs, however I wanted to keep this PR as straightforward as possible by not including any of those changes. 
```release-note
NONE
```
> Virt Handler Migration logic refactor

- hack/dockerized
Ensure that file ulimits are high enough for bazel inside the
containerized build environment, independent on what the host default
for containers are.
The symptom is bazel failing with a stack trace containing this:
```
Caused by: io.netty.channel.ChannelException: Failed to open a socket.
```
Fixes #
```release-note
NONE
```
> Bazel can open quite some files, increase ulimits for files inside the build container

- tests/utils.go
HostDisk tests rely on random host-disk directories. The seed was not
finegrained enough to be different on every worker on parallel tests.
This led to a situation where tests were deleting host directories of
other host disk tests, executed in parallel.
When looking at failures like https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5182/pull-kubevirt-e2e-k8s-1.19/1370916956328169472 one can notice that in two different namespaces "random" VMIs with the same name were created. This was a hint that the seed was the same, which led to also creating identical "random" hostDisk dirs.
Fixes issues like
```
Unexpected Warning event received: testvmi-kxn4w,e37e69fc-d4bc-428a-b70a-b7df342dbf53: server error. command SyncVMI …
```
> Improve random seed initialization on the test suite

- tests/BUILD.bazel
- tests/operator_test.go
Our update functional test that validates updating from the previous release to the latest code is currently flaky due to vmi's failing during migrations
The issue is being tracked here. #5228 
Since it's very risky to disable the entire update test, I've targeted just the portion that is failing. Issue #5228 is being marked as a release blocker in order to guarantee we can't cut a new release until we get a root cause for whatever is going on here. 
Fixes #
```release-note
NONE
```
>  QUARANTINE the vmi workload update verification logic

- pkg/virt-launcher/virtwrap/converter/BUILD.bazel
- pkg/virt-launcher/virtwrap/converter/converter.go
- pkg/virt-launcher/virtwrap/util/BUILD.bazel
- pkg/virt-launcher/virtwrap/util/libvirt_helper.go
As @vladikr suggested in a [previous PR](https://github.com/kubevirt/kubevirt/pull/4917#discussion_r576464454), SeaBios debug logs should be part of virt-launcher log.
Also, as [explained here](https://www.seabios.org/Debugging#Timing_debug_messages) use a pipe instead of a file for logging to prevent the creation of a log file that keeps getting larger.
For some reason "syscall.Mkfifo" doesn't make a pipe with the permissions passed as a parameter. I've found a [solution here](https://wenzr.wordpress.com/2018/03/27/go-file-permissions-on-unix/) which is basically to make another call to "syscall.Chmod" to fix pipe's permissions.
Am I missing something here? Anyways I would be happy to hear about a more elegant …
> Move SeaBios debug log to be seen as part of the virt-launcher log

- tests/utils.go
Add ocs rbd storageClass for downstream testing, currently the tests only could be running on "rook-ceph.rbd.csi.ceph.com", "csi-rbdplugin" storage class for upstream
Fixes #
```release-note
None
```
> Add ocs rbd storageClass for downstream testing

- cmd/virt-handler/BUILD.bazel
- cmd/virt-launcher/BUILD.bazel
- images/BUILD.bazel
The definitions of group entries for gid=0 used the same
names as previously defined groups, which gives misleading
`ls -l` output in the container
```console
$ stat /usr/bin/alias | grep Gid
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    qemu)
$ ls -l /usr/bin/alias
-rwxr-xr-x. 1 root qemu 33 Jan  1  1970 /usr/bin/alias
$ id
uid=107(qemu) gid=107(qemu) groups=107(qemu)
```
This seems like a copy+paste accident.
Rename the groups to 'root'
```release-note
NONE
```
> containers: Fix duplicate group name for gid=0

- pkg/virt-launcher/notify-client/client.go
- pkg/virt-launcher/notify-client/notify_test.go
- pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
- pkg/virt-launcher/virtwrap/cli/libvirt.go
- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
- pkg/virt-launcher/virtwrap/util/BUILD.bazel
- pkg/virt-launcher/virtwrap/util/libvirt_helper.go
- pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go
- tests/migration_test.go
What this PR does / why we need it:
Virt-launcher will fail to send a correct domain when the domain is transient. This will corrupt the cache of virt-handler and cause bad decisions in the sync loop. This PR ensures we retrieve the correct domain even in a transient state.
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #
BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1883875
https://bugzilla.redhat.com/show_bug.cgi?id=1886453
```release-note
Fixing handling of transient domain
```
> [release-0.36] support extracting metadata for transients domains

- docs/metrics.md
- pkg/monitoring/vms/prometheus/fakeCollector.go
- pkg/monitoring/vms/prometheus/prometheus.go
- pkg/monitoring/vms/prometheus/prometheus_test.go
- pkg/virt-launcher/virtwrap/cli/libvirt.go
- pkg/virt-launcher/virtwrap/stats/types.go
- pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
This patch introduces the kubevirt_vmi_cpu_affinity metric which
displays the cpu pinning map via boolean labels in the form of
vcpu_X_cpu_Y.
Fixes #
```release-note
Added a metric for monitoring CPU affinity
```
> Expose CPU affinity metric

- pkg/virt-controller/watch/snapshot/snapshot.go
- pkg/virt-controller/watch/snapshot/snapshot_test.go
Simply rephrase the reason to:
`No VolumeSnapshotClass: Volume snapshots are not configured for this Storage Class [storage_class_name] [volume_name]`
Fixes #
```release-note
NONE
```
> rephrase "No VolumeSnapshotClass" reason

- hack/dockerized
Copy junit generated by gosec if junit file exists and we are on prow
Previous solution failed because we added GOSEC variable for running subset of tests
```release-note
None
```
/cc @dhiller
> Fix gosec target on prow

- automation/test.sh
In order to ease lane filtering, the `automation/test.sh` scrip will not compute the `KUBEVIRT_E2E_FOCUS` and the `KUBEVIRT_E2E_SKIP` environment variables according to the TARGET variable, one or them (or both) is already set.
That allows setting this variable from the test configuration.
```release-note
NONE
```
> Allow pre-setting the KUBEVIRT_E2E_FOCUS env var in tests

- staging/src/kubevirt.io/client-go/api/v1/register.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
The PR extends client-go by defining `SchemeGroupVersion` variable and by adding `genclient` to VM types. The purpose is to support external adopters that use code-generators. 
Harvester project uses code generator to produce the wrappers and an internal framework. The generator relies on certain common types, vars and directives to be present in the client. It would benefit from these additional changes.
```release-note
NONE
```
> Extend client-go

- automation/test.sh
In order to fail fast, in case the job doesnt set
TARGET due to an error, and to not hide
delicate errors that might occour, since otherwise
the default configuration would be selected,
Validate that TARGET is set.
Example 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1042/rehearsal-pull-kubevirt-e2e-kind-1.17-sriov/1372521867209871360
The job is using a new bootstrap image, which doesn't have apt, so the whole command of the job that exports env vars is not triggered.
The job still runs and uses the default provider, and might even pass after running all tests on a provider it didn't mean to, and tests it didn't mean.
Giving false positive and hiding problems.
```release-note
None
```
> automation, Validate that TARGET is non empty

- cmd/virt-handler/virt-handler.go
- pkg/monitoring/vms/prometheus/BUILD.bazel
- pkg/monitoring/vms/prometheus/prometheus.go
Signed-off-by: Marcus Sorensen <mls@apple.com>
Whenever prometheus metrics are scraped from virt-handler, the virt-handler calls the Kubernetes API to find the VMIs assigned to the node. This can cause considerable API load for large clusters. Instead, we can serve this information from the VMI informer cache.
Fixes #5193 
It looks like the existing infra_test suite covers validating that active VMI information properly presents in the /metrics scraping. It should sufficiently test this change, therefore no additional tests were added.
```release-note
Prometheus metrics scraped from virt-handler are now served from the VMI informer cache, rather than calling …
```
> Serve promethus VMI info from informer cache

- hack/builder/version.sh
- hack/dockerized
It is easy to override tags with the current builder bump flow. Since
quay.io does not keep images based on digest, if they have no tag,
applying a simple workaround to avoid that people accidentaly override
each others builder images.
It actually just happened right now. I restored the builder image from my local machine, but we need to prevent that.
This is really just a very simple workaround. On the long run I expect the builder image to be replaced with the kubevirtci/bootstrap image with bazel being installed as the only requirement.
The downside of risking to get different images from the same tag is tried to be minimized by creating the tags in a pretty unique way.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, …
> A very simple fix to avoid builder push collisions

- tests/vmi_configuration_test.go
The Chassis test gives an Expect only one second to succeed. This is not
always enough. Give it a reasonable value of 10 seconds.
Fixes issues like
```
tests/vmi_configuration_test.go:2352
Expected success, but got an error:
<expect.TimeoutError>: 1000000000
expect: timer expired after 1 seconds
tests/vmi_configuration_test.go:2376
```
Fixes #
Here an example job: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5082/pull-kubevirt-e2e-k8s-1.19/1372426865519628289
```release-note
NONE
```
> Give the expecter more time on a e2e test to retrieve info

- automation/release.sh
Can't work currently as the `env vars` from the job configuration are pointing to files that need to get passed in. Sp this PR removes the login to quay.io in the release script. Another PR in project-infra adds it to the job configuration. 
Fixes #
```release-note
NONE
```
> Remove quay login from release shell script

- automation/repeated_test.sh
Due to grep returning non zero exit code in case of no match we rewrite
the grepping logic to ignore these errors. This also makes it a bit
better to read as the awk sum is replaced by proper arithmetic
expressions.
Fixes #
@oshoval at some time in the past there was a convention of using `_test.go` for test files. As this is no more valid I need to adjust the logic to reflect that.
```release-note
NONE
```
> Fix estimation of number of tests per repeated test run

- WORKSPACE
- tests/libvmi/factory.go
- tests/utils.go
There is a potential race between e2e tests `LoginToFedora`,
and Cloud-init which reconfigure the password.
The flow is as follows:
1. e2e spins VM and wait for it to be 'Running'
2. e2e tries to Login to the VM via the console.
3. e2e waits for Agent connected event.
As part of the VM spinning this flow occurs:
A. The VM has Cloud-init UserData, which cause the Cloud-init to reconfig the VM
according the default distro configuration which reset the fedora user to not have a password.
And then runs the UserData commands which adds a password.
In case A started but didn't finish before 2 (login attempt), there will be a race that will cause the login
to fail.
This race can cause the login to eventually fail, in case the retires are exhausted, or in case the console
expecter is going out of …
> sriov, Fix race condition between LoginToFedora and cloud init

- tests/reporter/BUILD.bazel
- tests/reporter/outputenricher.go
- tests/tests_suite_test.go
Make warnings better searchable, by enriching  the junit report with
warning events if a test fails. This helps making Warning events
searchable in search.ci.kubevirt.io.
Fixes #
```release-note
NONE
```
> Log warnings to the junit report for failing tests

- tests/migration_test.go
Kubelet has problems deleting the launcher Pod in a situation where Pod is in initialization(init containers specifically) and we mark it for deletion.
`Feb 08 06:15:24 node01 kubelet[3378]: E0208 06:15:24.222370 3378 pod_workers.go:191] Error syncing pod 207ffddd-b100-4160-9e2f-2b3fd5597ed6 ("virt-launcher-testvmi-q8wqk-q4pr5_kubevirt-test-default1(207ffddd-b100-4160-9e2f-2b3fd5597ed6)"), skipping: failed to "StartContainer" for "container-disk-binary" with CreateContainerConfigError: "cannot find volume \"virt-bin-share-dir\" to mount into container \"container-disk-binary\""`
Waiting for VMI ensures that the launcher Pod will be initialized before we delete VM.  …
> Fix flaky test: Waiting for vmi

- tests/migration_test.go
- tests/network/vmi_multus.go
- tests/network/vmi_networking.go
- tests/utils.go
Ensure that some tests in vmi_networking.go clean up the VMIs they
create. The tests affected by this were partly assuming a complete
cleanup and partly assuming that they share common VMIs.
As a result they were anyway already creating their own VMIs, but were
not cleaning up VMIs from the previous test runs.
An example is this run: https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5248/pull-kubevirt-e2e-k8s-1.19/1372226042629984256.
The [overview.log](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5248/pull-kubevirt-e2e-k8s-1.19/1372226042629984256/artifacts/k8s-reporter/1_overview.log) shows the accumulated VMIs clearly:
```
kubevirt-test-default1   pod/virt-launcher-testvmi-5hrxg-wr4cz …
```
> Fix some vmi cleanup issues in vm_networking.go

- BUILD.bazel
- WORKSPACE
- docs/update-go-version.md
- hack/builder/Dockerfile
- hack/dockerized
- pkg/certificates/BUILD.bazel
- pkg/hooks/BUILD.bazel
- pkg/util/openapi/BUILD.bazel
- pkg/virt-api/webhooks/BUILD.bazel
- pkg/virt-controller/watch/drain/disruptionbudget/BUILD.bazel
- pkg/virt-launcher/virtwrap/device/BUILD.bazel
- pkg/virt-launcher/virtwrap/device/sriov/BUILD.bazel
- pkg/virtctl/BUILD.bazel
- pkg/virtctl/expose/BUILD.bazel
- pkg/virtctl/imageupload/BUILD.bazel
- pkg/virtctl/pause/BUILD.bazel
- pkg/virtctl/vm/BUILD.bazel
- tests/BUILD.bazel
- vendor/github.com/opencontainers/runc/libcontainer/configs/BUILD.bazel
- vendor/github.com/prometheus/client_golang/prometheus/BUILD.bazel
- vendor/github.com/u-root/u-root/pkg/rand/BUILD.bazel
- vendor/github.com/vishvananda/netlink/BUILD.bazel
Update Go version to 1.14.14.
This addresses the following Bugzilla bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1929069
As written in bug description, this bug is fixed in Go upstream:
https://github.com/golang/go/commit/d95ca9138026cbe40e0857d76a81a16d03230871
In addition, add a small tutorial that will document the procedure needed to update Go version.
```release-note
Go version updated to 1.14.14
```
> [Bugfix]: Fix crypto P-224 curve bug by updating Go version to 1.14.14

- pkg/virt-handler/vm.go
- pkg/virt-handler/vm_test.go
- pkg/virt-launcher/notify-client/client.go
- tests/BUILD.bazel
- tests/operator_test.go
This PR is to address the VMI failures during migration as identified by #5228 
There were 2 primary issues occurring here.
1. the VMI cache on virt-handler was being corrupted. This is due to a recent change with the ordering of how our informers start. Previously we'd start the domain infomer, inject some values into the vmi informer cache, then start the vmi informer. Now we start both informers in parallel, which meant when we injected values into the cache, we were working wiht a live informer rather than a pre-initialized cache.
ultimately, this caused some odd behavior. One of the odd behaviors is that the domain notify socket wouldn't get created for an active VMI until very late, around the time a migration starts, which didn't give the launcher enough time to reconnect to report …
> Fix issues impacting KubeVirt update test

- BUILD.bazel
- WORKSPACE
- hack/builder/Dockerfile
- hack/dockerized
- pkg/certificates/BUILD.bazel
- pkg/hooks/BUILD.bazel
- pkg/util/openapi/BUILD.bazel
- pkg/virt-api/webhooks/BUILD.bazel
- pkg/virt-controller/watch/drain/disruptionbudget/BUILD.bazel
- pkg/virt-launcher/virtwrap/device/BUILD.bazel
- pkg/virt-launcher/virtwrap/device/sriov/BUILD.bazel
- pkg/virtctl/BUILD.bazel
- pkg/virtctl/expose/BUILD.bazel
- pkg/virtctl/imageupload/BUILD.bazel
- pkg/virtctl/pause/BUILD.bazel
- pkg/virtctl/vm/BUILD.bazel
- tests/BUILD.bazel
- vendor/github.com/opencontainers/runc/libcontainer/configs/BUILD.bazel
- vendor/github.com/prometheus/client_golang/prometheus/BUILD.bazel
- vendor/github.com/u-root/u-root/pkg/rand/BUILD.bazel
- vendor/github.com/vishvananda/netlink/BUILD.bazel
Revert PR https://github.com/kubevirt/kubevirt/pull/5102 which bumps Go version to 1.14.14.
The reason for that are failures describe here: https://github.com/kubevirt/kubevirt/issues/5285.
After reverting, the problem needs to be debugged and the Go version should be bumped in a new PR. 
```release-note
NONE
```
> Revert update Go version to v1.14.14

- pkg/virt-launcher/virtwrap/cli/libvirt.go
- pkg/virt-launcher/virtwrap/manager.go
Check error before logging. My previous PR #5158 was merged before I noticed that it writes to log even if there is no error.
```release-note
None
```
> Check error before logging

- api/openapi-spec/swagger.json
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/schema.go
- staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
In KubeVirt API document at https://kubevirt.io/api-reference/master/definitions.html#_v1_disk , the default values for the disk cache mode should be specified for good user experience. 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1896795
```release-note
NONE
```
> Added supported values for v1.Disk cache mode in API document

- pkg/virt-operator/resource/apply/core.go
- pkg/virt-operator/resource/apply/reconcile.go
First CA bundles need to be published before new certificates by the new CA are published.
By first updating CA bundles, clients have a higher chance to know about
a certificate signed by the new CA when they first hit a certificate
signed by it.
Since file-based secrets are updated periodically and not immediately,
chances of running into a situation of a still unknown CA are low, but
it happens from time to time.
The rollout order is now like this:
1) create a fresh CA
2) publish the updated CA bundle on the kubevirt configmap
3) publish the updated CA bundle on webhooks and apiservices
4) rollout new certificate secrets for all components
Before this change, webhooks and apiservers were updated with the new CA bundle after new certificates were …
> Publish the CA bundle everywhere before rolling out new certificates from a new CA

- Makefile
- hack/bazel-test.sh
- pkg/hooks/manager.go
- pkg/hooks/manager_test.go
- pkg/virt-handler/hotplug-disk/mount_test.go
- pkg/virt-launcher/BUILD.bazel
- pkg/virt-launcher/monitor_test.go
- pkg/virt-launcher/virtwrap/cli/libvirt.go
- pkg/virt-launcher/virtwrap/cli/libvirt_test.go
- pkg/watchdog/watchdog.go
- pkg/watchdog/watchdog_test.go
The PR adjusts bazel options for unit-testing in CI
```bash
"--cache_test_results=no --runs_per_test=4"
``` 
Additionally it introduces small refactorings to enable parallel tests execution with `--runs_per_test=n` and reduce the overall tests execution time.
Fixes #5217, #5279
This is needed for https://github.com/kubevirt/kubevirt/issues/5217. The commits are atomic and can be reviewed one by one.
```release-note
NONE
```
> Bazel test args

- hack/prom-rule-ci/prom-rules-tests.yaml
- pkg/virt-operator/resource/generate/components/crds.go
Signed-off-by: Andrey Odarenko <andreyo@il.ibm.com>
This PR introduces new Prometheus alert that will fire when container that runs a VM is close to it's memory limit and close to a risky state of getting killed by runtime. Alert is firing when memory utilization is 20MB close to the memory limit.
```release-note
NONE
```
> Add alert for high memory utilization

- tests/network/vmi_networking.go
This PR move  test_id:1539 out of quarantine lane as it seems to be stable.
Between 21/2/2021 - 10/3/2021 it failed twice:
1. https://prow.k8s.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-cnao-1.19/1367009962546434048
failed due to a timeout along with other 53 tests due to timeouts as well.
2. https://prow.k8s.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-cnao-1.19/1367715990439202817
Reason: test_id:1539 failed due to virt-handler failed to send syncVMI command to virt-laucher pod
it failed because the VM failed to create as we can see in this [log](https://00f74ba44b66baab4437d56df86298651fac8d5214-apidata.googleusercontent.com/download/storage/v1/b/kubevirt-prow/o …
> Move test_id:1539 out of quarantine

- go.mod
- pkg/virt-controller/services/template.go
CRIs have different sets of default capabilities.
There is also always an option that CRI is configured
by administrator or operator deployed Kubernetes.
This PR ensures virtiofs will work on all configurations.
```release-note
None
```
> Require all capabilities for virtioFS

- tests/console_test.go
- tests/infra_test.go
- tests/migration_test.go
**What this PR does / why we need it**: Adds these flaky tests to quarantine:
test_id:1589, owner sig-compute
test_id:4100, owner sig-compute
test_id:3241, owner sig-compute
test_id:3243, owner sig-compute
test_id:2226, owner sig-storage
Fixes #
```release-note
NONE
```
> Quarantine flaky tests

- pkg/virt-handler/selinux/executor.go
Some commands return just the resutl code on the error that makes
difficult to debug problem, this change also add the command, stdout and
stderr to the error.
Fixes #
Some examples:
Here it just return `The failure to create the tap device only returned `exit status 1` with no additional info.
Journal logs: [https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev-prev/1374300084186910721/artifacts/k8s-reporter/3/nodes/1_journal_node02.log
]- Pod log: https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev-prev …
> Increase verbosity at selinux context run

- tests/migration_test.go
- tests/vmi_lifecycle_test.go
Test 3201 and 3241 fail too often.
See https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-03-17-168h.html#row38 and https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-03-17-168h.html#row34.
Fixes #
```release-note
NONE
```
> Move tests 3201 and 3241 into quarantine

- pkg/virt-operator/resource/apply/crds.go
- pkg/virt-operator/resource/apply/crds_test.go
This PR adds reconciliation of the CRD resources. If the spec or metadata of the cached CRD is different from the desired CRD we create a patch and update it. 
Fixes #
```release-note
Reconcile CRD resources
```
> reconcile crd to desired state

- pkg/util/webhooks/validating-webhooks/validating-webhook.go
- pkg/virt-api/webhooks/mutating-webhook/BUILD.bazel
- pkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go
`AdmissionReview` responses from Validating/Mutating webhooks are not well-formed as they do not include `apiVersion` and `Kind`, this commit fixes it.
For reference:
- https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#response
- https://github.com/kubernetes/kubernetes/issues/85681
Fixes #
```release-note
NONE
```
> webhooks: fix AdmissionReview responses

- api/openapi-spec/swagger.json
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/schema.go
- staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
In KubeVirt API document at https://kubevirt.io/api-reference/master/definitions.html#_v1_devices, the default value for the device blockMultiQueue setting should be mentioned for good user experience.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1896797
```release-note
NONE
```
> Add default value for the BlockMultiQueue parameter for API docu

- pkg/virt-operator/resource/apply/reconcile.go
When the operator registers a webhook, that needs to happen after the service referenced within the webhook is posted to the cluster.
So On installation
- services then webhooks
and on deletion
- webhooks then services. 
```release-note
Fixes race condition between operator adding service and webhooks that can result in installs/uninstalls failing
```
> Operator needs to create services before webhooks

- hack/cluster-build.sh
- hack/cluster-deploy.sh
- hack/prefetch-images.sh
In general everything except CDI is right now either already baked into kubevirtci or pre-fetched. With this PR CDI images are pre-fetched to all kubevirtci nodes during make cluster-sync to avoid weird unpredictable timeouts due to varying pull speeds.
Fixes #
Might fix flakiness in tests using CDI upload/import/clone.
```release-note
NONE
```
> Prefetch cdi images for tests

- tests/storage/datavolume.go
- tests/storage_test.go
- tests/utils.go
Update virtiofs test to wait for the first consumer with DataVolume.
Fixes: #4835 
```release-note
NONE
```
> Fix flaky virtiofs test to WFFC with data volume

- pkg/virt-handler/cmd-client/client.go
- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
This commit fixes 2 unit tests:
1. When running multiple parallel istances of the unit test
all of them would try to bind the same unix sockets and tcp
socket resulting in the test to panic.
2. In the 'should unpause a VirtualMachineInstance' test the second
call to VirDomain.Free() happens inside a goroutine launched by
UnpauseVMI() and was not waited upon causing the test to flag a
missing Free() in case the goroutine was not scheduled before ending
the test.
Co-authored-by: Daniel Hiller <daniel.hiller.1972@googlemail.com>
Fixes #
**Special …
> virtwrap: fix unit test flakyness

- tests/console_test.go
**What this PR does / why we need it**: All the recent failures of test_id:1589 are related to errors in PRs code or failed memory allocations because of golang bump (already fixed), so let's get it out of quarantine.
Fixes #
```release-note
NONE
```
> Get test_id:1589 out of quarantine

- tests/infra_test.go
Prevent conflicts when updating the existing secret as part of destroying the existing certificate.
Fixes # https://github.com/kubevirt/kubevirt/issues/4198
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5332/pull-kubevirt-e2e-k8s-1.18/1376449874530144256
```release-note
NONE
```
> Fix flaky secret update on "[test_id:4099] should be rotated when a new CA is created"

- pkg/virt-launcher/virtwrap/manager.go
Operations on the domain which involve its state change are protected
from concurrent access using a domain-modify-lock (mutex).
In the migration setup stage, currently two operations are affecting the
domain state:
- Detaching of SR-IOV devices.
- Preparing migration parameters (which includes the domxml)
These operation need to be protected from change of the domain and
therefore the domain-modify-lock is added.
As part of this journey, a refactoring was needed to avoid double-locking.
In addition, some small fixes have been added:
- Report migration status on all failures.
- Abort the detach operation in case of failure. …
> virt-launcher, migration: Protect the setup using a lock, fix some missing operations and refactor the code

- pkg/virt-api/api.go
- pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator.go
- pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator_test.go
- pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
- pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go
- pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
- pkg/virt-controller/watch/migration.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- tests/migration.go
- tests/migration_test.go
by adding a special migration label to be used as a label selector
This PR ensure no 2 migrations will ever run simultaneously for a given VMI
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1937920
```release-note
Creating more than 1 migration at the same time for a given VMI will now fail
```
> migration admitter: prevent creation of duplicate migrations

- pkg/virt-config/config-map.go
- pkg/virt-handler/device-manager/device_controller.go
- pkg/virt-handler/device-manager/device_controller_test.go
This PR addresses an edge-case where `permittedHostDevices` is added to the configMap/CR with PCI/Mdev entries, and then removed entirely.
In that case, we wouldn't typically do anything, and the device plugins would keep running.
This PR ensures they're all removed in that scenario.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1944379
Misc fixes:
- Ensure `config.PermittedHostDevices` always `nil` when empty
- In tests, ensure the configmap data is valid
- In tests, ensure no stop channel conflict
- In tests, avoid panic by mocking GetDevicePCIID() …
> device controller: remove all device plugins when permittedHostDevices is deleted

- pkg/virt-launcher/virtwrap/network/common.go
The tapOwner* constants have been left behind with #5145 .
Fixes #
```release-note
NONE
```
> virt-launcher, network: Remove unused tapOwner* constants

- pkg/virt-operator/resource/apply/crds.go
This message gets logged way too many times and it pollutes the logs with no useful info.
Fixes #
```release-note
NONE
```
> crds: do not log if crds are up-to-date

- pkg/controller/BUILD.bazel
- pkg/controller/virtinformers.go
- pkg/virt-operator/BUILD.bazel
- pkg/virt-operator/application.go
- pkg/virt-operator/kubevirt_test.go
- pkg/virt-operator/resource/apply/BUILD.bazel
- pkg/virt-operator/resource/apply/apiservices.go
- pkg/virt-operator/resource/apply/delete.go
- pkg/virt-operator/resource/apply/reconcile.go
- pkg/virt-operator/resource/generate/components/BUILD.bazel
- pkg/virt-operator/resource/generate/components/apiservices.go
- pkg/virt-operator/resource/generate/install/BUILD.bazel
- pkg/virt-operator/resource/generate/install/generated_mock_strategy.go
- pkg/virt-operator/resource/generate/install/strategy.go
- tests/infra_test.go
- tests/operator_test.go
- tests/reporter/BUILD.bazel
- tests/reporter/kubernetes.go
Change apiregistration.k8s.io/v1beta1 to apiregistration.k8s.io/v1
as the former is deprecated and will be removed from Kubernetes 1.22.
Replaces all occurrences of apiregistration.k8s.io/v1beta1 with apiregistration.k8s.io/v1
as the former is deprecated and will be removed from Kubernetes 1.22.
Fixes #
```release-note
NONE
```
> Update KubeVirt to use apiregistration.k8s.io/v1

- pkg/cloud-init/BUILD.bazel
- pkg/cloud-init/cloud-init.go
- pkg/cloud-init/cloud-init_test.go
- pkg/ephemeral-disk-utils/BUILD.bazel
- pkg/ephemeral-disk-utils/utils.go
listVmWithLocalData iterates over objects created in cloudinit package. Since 2018's https://github.com/kubevirt/kubevirt/commit/58b636ad28ed2d63db92f2ecc0f16541e41c29eb#diff-dd99dd4530ed2b9071463f32731f2134d96d0f429ef21bf59b9a4f469e3a15e4L82 , nothing is using it except its own test code.
This PR drops it.
```release-note
NONE
```
> move listVmWithLocalData out of diskutils

- tests/network/probes.go
Currently the network readiness probes tests flow:
- Creating a VM with TCP/Network readiness probe.
- Wait for the VM to start.
- Start TCP/HTTP probe server inside VM.
- Assert on virt-launcher pod and VM not ready state; both virt-launcher pod have Condition PodReady==False
or Condition Ready absence.
- Assert on virt-launcher pod and VM ready state; both virt-launcher pod and VM has Condition Ready==True.
Asserting pod and VM not-ready state after invoking probe server is start command might introduce flakes to those tests.
There might be a race between the time the probe server inside the VM is ready and the assertion on the pod/VM
Condition Ready sampling.
Currently both readiness and liveness tests the permutations of TCP/HTTP probe with …
> Fix flaky "[ref_id:1182]Probes for readiness should succeed [test_id:1202]with working HTTP probe and http server, no ip family is specified"

- api/openapi-spec/swagger.json
- pkg/virt-api/api.go
The generated API docs didn't specify the body needed for addvolume and removevolume. This PR specifies the types needed.
Fixes #4725
```release-note
NONE
```
> Specify consumes and body for add/removevolume in api docs

- pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
- pkg/virt-launcher/virtwrap/agent-poller/agent_poller_test.go
Guest agent poller timer has exponential backoff logic.
Since interval is already a time.Duration, it means it is already multiplied
by time.Second (see `pollInitialInterval` declaration).
Multiplying it again, will result in multiplying it by
1,000,000,000, and the pollers whose ticker is updated
won't be run for a long time, since the new
interval is not the expected one, but much bigger.
Fix it by removing the extra unneeded multiply.
Fix unit tests to validate the exponential backoff logic.
```release-note
None
```
> virt-launcher, agent-poller, Fix replaceTicker logic

- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
This commit fixes 2 unit tests:
1. When running multiple parallel istances of the unit test
all of them would try to bind the same unix sockets and tcp
socket resulting in the test to panic.
2. In the 'should unpause a VirtualMachineInstance' test the second
call to VirDomain.Free() happens inside a goroutine launched by
UnpauseVMI() and was not waited upon causing the test to flag a
missing Free() in case the goroutine was not scheduled before ending
the test.
Co-authored-by: Daniel Hiller <daniel.hiller.1972@googlemail.com>
Fixes #
**Special …
> virtwrap: fix unit test flakyness (take 2)

- pkg/virt-api/rest/subresource.go
- pkg/virt-api/rest/subresource_test.go
Fixes #5360
```release-note
None
```
> Return error if VMI is in Failed state when console access

- pkg/virt-api/api.go
- pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator.go
- pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator_test.go
- pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
- pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go
- pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
- pkg/virt-controller/watch/migration.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- tests/migration_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/5242
```release-note
Creating more than 1 migration at the same time for a given VMI will now fail
```
> [release-0.34] migration admitter: prevent creation of duplicate migrations by adding a special migration label to be used as a label selector

- hack/prom-rule-ci/prom-rules-tests.yaml
- pkg/virt-operator/resource/generate/components/crds.go
This is an addition alert for human operators to know if they have orphaned `vmis`. This prom query check to see if there are `vmis` running on a node that there is also a `virt-handler` running on that node, if there is not a `virt-handler` running on the node for more than an hour we alert. This allows for me discoverability into a cluster and is in addition to create an kubernetes event in this same case (https://github.com/kubevirt/kubevirt/pull/4952)
Fixes #https://bugzilla.redhat.com/show_bug.cgi?id=1868099 …
> alert users if they have an orphaned vmi for more than an hour

- pkg/virt-operator/resource/apply/BUILD.bazel
- pkg/virt-operator/resource/apply/core.go
- pkg/virt-operator/resource/apply/rbac.go
- pkg/virt-operator/resource/apply/rbacbackup.go
- pkg/virt-operator/resource/apply/reconcile.go
Reconcile Role and ClusterRole resources:
* Add a semantic deep equal on role and clusterrole `rules` object.
* Validate the metadata of the objects is equal with resourcemerge.EnsureObjectMeta() function.
Also refactor duplicate code in rbac.go and rbacbackup.go.
```release-note
NONE
```
> Reconcile Role and ClusterRole resources

- pkg/virt-launcher/notify-client/client.go
- pkg/virt-launcher/notify-client/notify_test.go
- pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
- pkg/virt-launcher/virtwrap/cli/libvirt.go
- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
- pkg/virt-launcher/virtwrap/util/BUILD.bazel
- pkg/virt-launcher/virtwrap/util/libvirt_helper.go
- pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go
- tests/migration_test.go
Backport of https://github.com/kubevirt/kubevirt/pull/4982
Fixes #
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1946082
```release-note
Fixing handling of transient domain
```
> [release-0.34]support extracting metadata for transients domains

- docs/discard-passthrough.md
Document the discard passthrough option introduced by the PR #5006.
Fixes #
```release-note
None
```
> docs: add documentation for discard passthrough

- tests/network/vmi_multus.go
On SRIOV IPv6 ping tests we spin up two VMI's where each have SRIOV interface
configured with IPv6.
Then we test IPv6 ping connectivity from each VM to the other.
Currently each VM ping itself instead of each other,
I guess it happen due to the last change to the test, with the current IP address variables naming its easy to confuse and ping the wrong address.
This PR suggest new naming for the IP addresses variables and fix the test logic.
Fixes #
```release-note
NONE
```
> Fix SRIOV IPv6 pings tests, ping destinations

- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
Domain spec is presistent between SyncVMI calls, therefore there is no
need to update it.
The existing update does not include network specific parameters which are
required for a proper domain spec (e.g. the tap device). Therefore, this flow
has not worked for some time now and is currently broken.
This change removes the domain spec update on secondary tries.
Fixes #
Related to https://github.com/kubevirt/kubevirt/pull/5021#discussion_r580353845
```release-note
NONE
```
> virt-launcher: Don't update domain on SyncVMI retries

- tests/storage/hotplug.go
- tests/vmi_configuration_test.go
**What this PR does / why we need it**: Puts in quarantine these tests:
* test_id:1678, owner: sig-compute
Failed 6 times in periodics in the last week https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-prev&width=20 and https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-latest&width=20 Also reported by flakefinder
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-04-06-024h.html, 
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-04-05-024h.html
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-04-06-168h.html#row14
* Hotplug Offline VM Should add …
> Add tests to quarantine

- pkg/virt-launcher/virtwrap/manager.go
- tests/migration_test.go
We should explicitly skip cdrom drives during migration. Adding a functional tests as well to cover this scenario.
Should address: https://bugzilla.redhat.com/show_bug.cgi?id=1927378
```release-note
NONE
```
> explicitly skip cd-rom drives during migration

- cmd/virt-handler/BUILD.bazel
- cmd/virt-handler/virt-handler.go
- pkg/virt-handler/node-labeller/BUILD.bazel
- pkg/virt-handler/node-labeller/cpu_plugin.go
- pkg/virt-handler/node-labeller/kvm-caps-info-plugin.go
- pkg/virt-handler/node-labeller/node_labeller.go
- pkg/virt-handler/node-labeller/node_labeller_test.go
- pkg/virt-handler/node-labeller/util/util.go
fix when case when node-labeller doesn't have access to kvm device
Fixes https://github.com/kubevirt/kubevirt/issues/5364
```
NONE
```
> Fix when case when node-labeller doesn't have access to kvm

- tests/utils.go
On ExecuteCommandOnPod failure print both err and stderr is exist.
Sometimes stderr contains more information than the err.
For example, I encountered the following -
"**err**: command terminated with exit code 1, **stderr**: cat: /sys/class/net/net12/mtu: No such file or directory"
Fixes #
```release-note
NONE
```
> tests: On ExecuteCommandOnPod failure print both err and stderr is exist

- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
This allows us to stop using `virtIface` on the pod networking
setup occurring in virt-handler on follow up PRs.
Fixes #
```release-note
NONE
```
> network, macvtap bind mech: add a MAC parameter to the bind mech

- tests/utils.go
Our test suite runs tests in parallel by default. We have a set of functions that provide a block device PVC with a cirros image to some tests, but there's a naming collision that results in multiple test workers all colliding on creating/deleting pvcs with the same name.
The result is if two tests running in parallel attempt to use a dynamically created block PVC using these standard util functions, they'll stomp on each other.
To fix this, since cirros is already a read only image, i just made each parallel test work use a unique name for the corresponding PVC/PV. 
```release-note
NONE
```
> Fix flaky block storage device tests

- tests/migration_test.go
This test showed up as having many failures due to unrelated issues
and being slightly flaky on a release branch. The master branch
already [had a fix](https://github.com/kubevirt/kubevirt/commit/daca413fe95f52741b7d16771a2c7f57c3fa181c), and after observing it for a while, we are sure
that it isn't flaky.
```release-note
NONE
```
> Remove test_id:3243 from quarantine.

- api/openapi-spec/swagger.json
- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/schema.go
- staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
- tests/network/vmi_networking.go
When using the masquerade binding method, an internal IPv6 network is used
for the pod-vm communication.
This change introduces the ability to customize this network address in
scenarios where the default one cannot be used.
~~Tests are missing for both CIDR 4 and 6.~~
```release-note
Add `vmIPv6NetworkCIDR` under `NetworkSource.pod` to support custom IPv6 CIDR for the vm network when using masquerade binding.
```
> schema: Introduce an IPv6 CIDR for the vm network

- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
- tests/migration_test.go
- tests/utils.go
Currently, VMIs in a paused state are being unpaused after migration.
This PR simply adds a flag to indicate that these VMIs shouldn't be unpaused on destination.
Fixes # [RHBZ#1939987]( https://bugzilla.redhat.com/show_bug.cgi?id=1939987)
```release-note
NONE
```
> Paused VMIs should remain paused after migration

- tests/storage/datavolume.go
remove test_id:3194 and test_id:3193 from quarantine
https://search.ci.kubevirt.io/?search=test_id%3A3194&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
https://search.ci.kubevirt.io/?search=test_id%3A3193&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes https://github.com/kubevirt/kubevirt/issues/4525
```
NONE
```
> remove test_id:3194 and test_id:3193 from quarantine

- hack/dockerized
- hack/prom-rule-ci/verify-rules.sh
- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
Domain spec is presistent between SyncVMI calls, therefore there is no
need to update it.
The existing update does not include network specific parameters which are
required for a proper domain spec (e.g. the tap device). Therefore, this flow
has not worked for some time now and is currently broken.
This change removes the domain spec update on secondary tries.
Fixes #
Cherry-pick from https://github.com/kubevirt/kubevirt/pull/5400
Depends on https://github.com/kubevirt/kubevirt/pull/5432
```release-note
NONE
```
> [release-0.26] virt-launcher: Don't update domain on sync retries

- pkg/virt-operator/kubevirt_test.go
- pkg/virt-operator/resource/generate/install/BUILD.bazel
- pkg/virt-operator/resource/generate/install/strategy.go
- pkg/virt-operator/resource/generate/rbac/BUILD.bazel
- pkg/virt-operator/resource/generate/rbac/apiserver.go
- pkg/virt-operator/resource/generate/rbac/cluster.go
- pkg/virt-operator/resource/generate/rbac/controller.go
- pkg/virt-operator/resource/generate/rbac/handler.go
- pkg/virt-operator/resource/generate/rbac/servicemonitor.go
This changes some instances of interface{} to instead use runtime.Object to avoid type casting. 
Fixes #
```release-note
None
```
> remove need for type casting by using runtime.Object

- docs/kubernetes-compatibility.md
This doc outlines the KubeVirt policy for Kubernetes compatibility. 
```release-note
Doc outlines our Kubernetes version compatibility commitment
```
> kubernetes version compatibility commitment doc

- tests/libnet/ping.go
- tests/network/vmi_networking.go
Test 1780, which pings 8.8.8.8 is flaky.
It does manage to ping 8.8.8.8 but it takes time,
since it tries to ping more than one packet,
and the first successful ping started already
too late.
Extend the timeout given for ping,
in order to solve this flakiness.
This PR will at least improve monitoring, since the ping will now won't
be abruptly interrupt by the RunCommand,
as the ping timeout updated to be smaller than RunCommand timeout.
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5427/pull-kubevirt-e2e-k8s-1.19-sig-network/1381524922219630592
See it managed to ping one packet at least, but then abruptly stopped by the RunCommand timeout.
```
{"component":"tests","kind":"VirtualMachineInstance","level":"info","msg":"[{1 \r\n$  [$  $ ]} {3 ping 8.8.8.8 …
```
> sig-network, Fix flaky test which pings 8.8.8.8

- pkg/virt-launcher/virtwrap/network/generated_mock_podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
The attribute on the bind mechanism interface is not used on any of the implementations.
As such, let's clean the interface up by removing it.
```release-note
NONE
```
> network: remove the unused attr from the startDHCP bind mech method

- pkg/virt-launcher/virtwrap/network/podinterface.go
PR [0] renamed all the bind mechanisms implementation receivers to
have the same name; however, for whatever reason, slirp was left
out.
This commit follows up on that, and also renames slirp receivers
accordingly.
[0] - https://github.com/kubevirt/kubevirt/pull/4856
Fixes #
```release-note
NONE
```
> Bind mech receiver name consistency

- pkg/virt-operator/resource/apply/crds.go
When passing `ops` as `nil` to `patchCRD()` the function
was creating a malformed patch due to initializing `ops` as a 1
element slice causing the next append to make it a 2 elements
slice and ending up in the patch being produced as:
`[, { "op": "replace", "path": "/spec", "value": "something" }]`
This is a simple reproducer of the bug:
```
package main
import "fmt"
const replaceSpecPatchTemplate = `{ "op": "replace", "path": "/spec", "value": %s }`
func main() {
var ops []string
if ops == nil {
ops = make([]string, 1)
}
ops = append(ops, fmt.Sprintf(replaceSpecPatchTemplate, "ciao"))
val := generatePatchBytes(ops)
fmt.Println(string(val))
}
func generatePatchBytes(ops []string) []byte {
opsStr := "["
for idx, entry := range ops {
sep := ", "
if len(ops)-1 == idx {
sep = "]"
}
opsStr = …
```
> crds: fix patch formatting

- pkg/virt-operator/resource/apply/crds.go
Manual cherrypick of #5463.
Fixes patching of CRDs when rolling out non-compatible CRD changes, this happens when upgrading from v0.36 to v0.40.
Fixes #
```release-note
Fixes upgrades from KubeVirt v0.36
```
> [release-0.40] crds: fix patch formatting

- docs/metrics.md
- hack/prom-rule-ci/prom-rules-tests.yaml
- pkg/virt-controller/watch/application.go
- pkg/virt-operator/application.go
- pkg/virt-operator/resource/generate/components/crds.go
- tests/infra_test.go
Some metrics and recording rules are difficult to find, this patch will
add a kubevirt_ prefix to those, making them more visible.
Generally, every component that ships metrics/alerts, names them with a common prefix, this helps the user search for those in the monitoring UI.
This PR renames and adds the kubevirt_ prefix to the following recording rules and metrics:
num_of_running_virt_api_servers -> kubevirt_virt_api_up_total
num_of_running_virt_operators -> kubevirt_virt_operator_up_total
num_of_running_virt_handlers -> kubevirt_virt_handler_up_total
num_of_running_virt_controllers -> kubevirt_virt_controller_up_total
num_of_ready_virt_controllers -> kubevirt_virt_controller_ready_total …
> Prepend kubevirt_ to recording rules and metrics

- rpm/BUILD.bazel
If nftables is not yet enabled, we fall back to iptables. For this the
iptables binary must be accessible for virt-handler.
Our rpm installation process does intentionally not execute post-install steps (since they require "privileges"). The post-install step would have created this link.
Fixes #
This issue exists for quite some time. This hints that we are not testing iptables, only `nftables`, and also that most people seem to use `nftables`.
```release-note
Fix fallback to iptables if nftables is not used on the host
```
> Add missing iptables link in virt-handler

- pkg/virt-api/webhooks/BUILD.bazel
- pkg/virt-api/webhooks/hyperv.go
- pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
- pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
- pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
- pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
- pkg/virt-controller/services/template.go
- pkg/virt-controller/services/template_test.go
- pkg/virt-handler/node-labeller/cpu_plugin.go
- pkg/virt-handler/node-labeller/model.go
- pkg/virt-handler/node-labeller/node_labeller.go
- pkg/virt-handler/node-labeller/util/util.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- tests/infra_test.go
- tests/vmi_lifecycle_test.go
HyperV EVMCS requires hyperv Vapic and vmx cpu feature to properly work.
This PR adds new checks for hyperv evmcs. When user sets evmcs, kubevirt now checks if vapic is enabled, if not, it enables it. Then it adds vmx cpu feature and node selector so the vm with evmcs will be scheduled only on intel nodes which supports vmx.
Previously when user set evmcs, kubevirt didn't add vapic and vmx features.
```
Add checks for hyperv evmcs feature
```
> add new checks for hyperv evmcs

- pkg/virt-api/rest/subresource.go
- pkg/virt-api/rest/subresource_test.go
- pkg/virtctl/console/console.go
- pkg/virtctl/templates/BUILD.bazel
- pkg/virtctl/templates/templates.go
- pkg/virtctl/vnc/vnc.go
- tests/pausing_test.go
Until now console connection to paused VM was not permitted. This PR will allow serial and VNC console into paused VM. Console will be active after VM is unpaused. 
This can be useful for debugging. In the future we can start VM with it's guest paused and debug guest OS boot issues.
```release-note
NONE
```
> Allow console connection to paused VM

- rpm/BUILD.bazel
Follow up of #5426 which does the same for arm64 containers like we do for amd64 containers.
Fixes #
```release-note
Fix fallback to iptables if nftables is not used on the host on arm64
```
> Add iptables symlink for arm64 base container

- docs/metrics.md
- pkg/monitoring/vms/prometheus/prometheus.go
- pkg/monitoring/vms/prometheus/prometheus_test.go
- pkg/virt-launcher/virtwrap/cli/libvirt.go
- pkg/virt-launcher/virtwrap/stats/types.go
- pkg/virt-launcher/virtwrap/statsconv/converter.go
- pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
- tests/infra_test.go
**What does this PR?**
This PR replaces
- `kubevirt_vmi_storage_iops_total` with  `kubevirt_vmi_storage_iops_read_total` and `kubevirt_vmi_storage_iops_write_total`
- `kubevirt_vmi_storage_traffic_bytes_total`  with `kubevirt_vmi_storage_read_traffic_bytes_total` and `kubevirt_vmi_storage_write_traffic_bytes_total`
- `kubevirt_vmi_storage_times_ms_total`  with `kubevirt_vmi_storage_read_times_ms_total` and `kubevirt_vmi_storage_write_times_ms_total`
This PR adds detailed functional tests which check the labels of metrics and verifies that volume names of VMIs exist there.
This PR contains the work in #5204 and it resolves review issues on that PR.  
`AliasSet` is removed in this PR after this comment: …
> Split storage metrics as read and write

- pkg/virt-api/api.go
> Fix verbosity for virt-api

- api/openapi-spec/swagger.json
- pkg/virt-controller/watch/snapshot/snapshot.go
- pkg/virt-controller/watch/snapshot/snapshot_test.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/deepcopy_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types_swagger_generated.go
- tests/storage/snapshot.go
Currently online vm snapshot is not supported, hence indications
should not be updated. When online vm snapshot will be supported
indications will be updated with a msg that the vm was running when
takeing the vm snapshot, futhermore in the future it will be
possible to decide if the vm snapshot should be taken using guest
agent coordination, if not then a msg that the guest agent was not
participating will be added to the indications.
Fixes #
```release-note
NONE
```
> Add vm snapshot indications

- pkg/virt-api/rest/subresource.go
- tests/storage/hotplug.go
There is a race condition when removing multiple volumes at once.
It is possible the first volume gets removed by the virt-controller
while we are calculating the patch for the second volume and now
the patch will fail. This retries by reloading the VM and recalculating
the patch.
Fixes #4974 
```release-note
NONE
```
> Fix offline hotplug test failing

- README.md
The kubevirt-dev slack channel is more targeted for kubevirt related topics that #virtualization. It's also the channel that many of us more closely watch now. Maybe we should consider updating our readme to reflect this. 
```release-note
NONE
```
> Update our README.md to point to kubevirt-dev slack

- pkg/virt-launcher/virtwrap/network/generated_mock_podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
This PR consolidates the API of the `BindMechanism` interface, by using attributes defined within the struct other than
passing them by parameter in each of the functions.
It is a first step in effectively splitting the `BindMechanism` portion executed in the `virt-handler` pod, which will be addressed
in a follow up PR.
Fixes #
Depends-on: #5057
```release-note
NONE
```
> Consolidate bind mechanism api

- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
Instead of re-reading the pod interface and extract its mac address, we return the mac address attribute of the structure read via netlink.
```release-note
NONE
```
> network, bridge binding: read the pod interface just once

- pkg/virt-handler/container-disk/BUILD.bazel
- pkg/virt-handler/container-disk/mount.go
- pkg/virt-handler/hotplug-disk/BUILD.bazel
- pkg/virt-handler/hotplug-disk/mount.go
- pkg/virt-handler/isolation/BUILD.bazel
- pkg/virt-handler/isolation/validation.go
- pkg/virt-handler/selinux/BUILD.bazel
- pkg/virt-handler/selinux/labels.go
- pkg/virt-handler/virt-chroot/BUILD.bazel
- pkg/virt-handler/virt-chroot/virt-chroot.go
- tests/reporter/BUILD.bazel
- tests/reporter/kubernetes.go
Important values like chroot binary path, default mount namespace
and mount execution options are not defined in a single place.
Therefore, the execution of virt-chroot, especially mounting/unmounting,
is duplicated and spread arround the code.
Now dedicated methods - MountChRoot(), UnmountChRoot() and ExecChroot() -
are added to virt-chroot.go file under util package. In addition,
GetChrootBinaryPath() and GetChrootMountNamespace() are added,
returning the data which is saved in a single place inside that file.
```release-note
None
```
> Add dedicated functions for virt-chroot execution

- pkg/virtctl/expose/expose.go
- pkg/virtctl/expose/expose_test.go
- tests/assert/xfail.go
- tests/network/expose.go
k8s 1.20 and beyond added support for dual stack services [1].
This PR allows passing dual stack `ipFamilies` ("ipv4,ipv6" and "ipv6,ipv4") to `virtctl expose` `ip-family` flag.
It also allows specifying `ipFamilyPolicy` ("SingleStack", "PreferDualStack", "RequireDualStack"). (TBD)
[1] https://kubernetes.io/docs/concepts/services-networking/dual-stack/
Note: Secondary IP on dual stack service is not working (at least not on k8s 1.20), therefore, XFail was added when testing it.
Tracking issue: https://github.com/kubevirt/kubevirt/issues/5477
Fixes #
**Release …
> Support dual stack service on "virtctl expose"

- pkg/virt-launcher/virtwrap/network/common.go
Fixes #
The NetworkUtilsHandler functions where using the global bar Handler
instead of the receiver, they should use the receivers instance.
```release-note
NONE
```
> network, handler: Use receiver at handler funcs

- pkg/virt-operator/kubevirt_test.go
- pkg/virt-operator/resource/apply/crds.go
- pkg/virt-operator/resource/apply/generations.go
- tests/operator_test.go
This PR reconciles CRD resources on change if their annotations or labels do not match the desired, as well as if they are updated and there generation is incremented outside of our reconciliation loop. 
Fixes #
```release-note
Reconcile CustomResourceDefinition resources 
```
> Reconcile crd

- pkg/virt-launcher/virtwrap/network/common.go
- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
Currently we are wrongfully assuming that the tap creation user GID and UID are the same. This might not be the case.
This PR addresses this, and relies and known constants to define them, instead of magic strings.
```release-note
NONE
```
> Use tap constants

- pkg/virt-launcher/virtwrap/network/podinterface.go
The `ensureDHCP` function no longer needs to use the `vmi` attribute, since the bind mechanism methods `startDHCP` stopped using the vmi attribute.
This PR is a left-over from #5452 . 
```release-note
NONE
```
> network, bind mech: remove vmi attr from ensureDHCP

- pkg/virt-handler/migration-proxy/migration-proxy.go
- pkg/virt-handler/migration-proxy/migration-proxy_test.go
- pkg/virt-handler/vm.go
- pkg/virt-launcher/virtwrap/live-migration-source.go
- pkg/virt-launcher/virtwrap/live-migration-target.go
- staging/src/kubevirt.io/client-go/log/log.go
The logging in our migration proxy code has gaps that leave us without valuable information pertaining to when proxies are start, stop, and fail. As a result, it can be difficult to debug what occurs when a migration fails due to connectivity issues. Without more fidelity in our logs, it's difficult to rule out an issue within our components vs an issue occurring within the cluster network. 
With these changes, we can clearly see when proxies are created, where they are going, when they close, and why they close. 
Below is an example of the new output on the target node.. We have structured fields for the socket the proxy listens to, and the outbound connection.
```
{"component":"virt-handler","level":"info","listening":":::32813","msg":"proxy started …
```
> Improve migration proxy logging

- pkg/virt-launcher/virtwrap/network/podinterface.go
The `vmi` and `virtIface` attributes on the `Slirp` bind mechanism implementation are not being used. 
This PR removes them from the code base.
```release-note
NONE
```
> network, slirp: remove unused attributes from bind mech

- WORKSPACE
Updating it to 0.1.4.1 to fix build issues like
```
ERROR: /home/rmohr/.cache/bazel/_bazel_rmohr/d8c39dc5bdaf4508a5ddf82e95ab388c/external/io_bazel_rules_docker/container/go/pkg/oci/BUILD:18:11: @io_bazel_rules_docker//container/go/pkg/oci:go_default_library depends on @com_github_google_go_containerregistry//pkg/v1/layout:go_default_library in repository @com_github_google_go_containerregistry which failed to fetch. no such package '@com_github_google_go_containerregistry//pkg/v1/layout': java.io.IOException: Error downloading [https://api.github.com/repos/google/go-containerregistry/tarball/8a2841911ffee4f6892ca0083e89752fb46c48dd] to /home/rmohr/.cache/bazel/_bazel_rmohr/d8c39dc5bdaf4508a5ddf82e95ab388c/external/com_github_google_go_containerregistry/temp3242427000601878860/8a2841911ffe …
```
> Fix disappearence of go_containerregistry 0.1.4

- pkg/virt-launcher/virtwrap/network/common.go
- pkg/virt-launcher/virtwrap/network/common_test.go
- pkg/virt-launcher/virtwrap/network/generated_mock_common.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
This PR cleans up the driver interface by removing an unused method from it.
`GenerateRandomMac` was dropped in https://github.com/kubevirt/kubevirt/pull/4804/ .
```release-note
NONE
```
> network, driver: remove unused method GenerateRandomMac

- tests/vmi_lifecycle_test.go
take test_id:3201 out of quarantine
```
NONE
```
> take test_id:3201 out of quarantine

- pkg/virt-launcher/virtwrap/network/common.go
- pkg/virt-launcher/virtwrap/network/network.go
- pkg/virt-launcher/virtwrap/network/network_test.go
- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
The virt-launcher network code contains a pair of global elements to
open the door for mocking, a `Handler` variable and a `podNICFactory`,
using global variables is in general bad practice. This change replace
those with structs constructed at the caller making code easier to
follow and to test.
Fixes #
This is part of the CleanCode initiative.
Depends on https://github.com/kubevirt/kubevirt/pull/5512
```release-note
NONE
```
> Remove global var Handler from virt-launcher/virtwrap/network

- pkg/virt-handler/cache/cache_test.go
- pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
- pkg/virt-launcher/virtwrap/cmd-server/server.go
- pkg/virt-launcher/virtwrap/cmd-server/server_test.go
- pkg/virt-launcher/virtwrap/generated_mock_manager.go
- pkg/virt-launcher/virtwrap/manager.go
`virt-handler` refreshes the VMI domain information,
each 300 seconds by `handleResync` function.
The information it got doesn't include
Guest Agent information such as Guest OS Info,
and interfaces status.
This will cause flakiness in the VMI status,
each time that the report is fetched,
until the next update of Guest Agent will be sent
by the `virt-launcher` to the `virt-handler`,
as this report does include the Guest Agent data.
This PR fix it by decorating the resync
domain info, with the Guest Agent information,
as the `virt-launcher` itself does before sending
the domain info to the `virt-handler`.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1907707
```release-note
None
```
> virt-launcher, Fix flaky VMI report (random missing Guest Agent data)

- hack/prefetch-images.sh
When docker pull on a node fails for any reason prefetching images, it's stuck forever
in a loop, because the max_retry variable is missing $ sign.
Fixes #
```release-note
NONE
```
> Add missing dollar signs to max_retry variable

- pkg/virt-launcher/virtwrap/live-migration-source.go
- pkg/virt-launcher/virtwrap/manager_test.go
- vendor/libvirt.org/libvirt-go/domain.go
Libvirt often returns only the last error for a given call, and occasionally it's a consequential error.
With live migration cancellation, we post this consequential error instead of the actual migration status.
This PR will:
- allow the monitor to check the migration status and act on it prior to posting the error.
- extracts the status of a completed migration job if we missed updating the status before the job was completed. 
This should address the flakiness of the migration cancelation tests.
```release-note
NONE
```
> Let live migration monitor verify the actual status of migration before posting an error from libvirt

- pkg/virt-launcher/virtwrap/network/podinterface.go
This PR switches the order of the caching operations (first cache VIF, only then the iface) since the criteria for knowing if the infrastructure is to be created is based on the cached iface existing.
```release-note
NONE
```
> cache `virtIface` as `setupPodNetworking` last operation

- tests/BUILD.bazel
- tests/events_test.go
Test the generation of K8s IO events introduced by #4840.
The test creates a faulty disk with dmsetup. A VMI is created with the
faulty disk, and this triggers the IO event generation. The dmsetup
command requires the privileged falg. For this reason, the dmsetup
command is executed inside the virt-handler.
Test the generation of K8s events on IO errors
```release-note
None
```
> tests: add test for io events

- WORKSPACE
Bump bazeldnf to fix `docker save` issues for containers created with
bazeldnf.
Fixes issues like
```
]# docker save  quay.io/kubevirt/virt-handler:v0.40.0  >image.tar
Error response from daemon: read /var/lib/docker/overlay2/7dcbf28f1c151e11c9d71d49f39ab76f0606f7efcb3fb8a909d0883ff4fbdf32/diff/lib64: is a directory
```
The background is that the RPM to Tar conversion left for symlinks the body size to the original non-zero value, since RPMs store the target link in the body, while on Tar headers there is an extra symlink header field, and the body size should be set to `0`: https://github.com/rmohr/bazeldnf/releases/tag/v0.1.0.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close …
> Bump bazeldnf version to v0.1.0

- tests/container_disk_test.go
- tests/template_test.go
Assigned to test files to `sig-compute`:
- tests/template_test.go
- tests/container_disk_test.go
```release-note
None
```
> Assign template and container disk tests to sig-compute

- pkg/virt-handler/cache/cache_test.go
- pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
- pkg/virt-launcher/virtwrap/cmd-server/server.go
- pkg/virt-launcher/virtwrap/cmd-server/server_test.go
- pkg/virt-launcher/virtwrap/generated_mock_manager.go
- pkg/virt-launcher/virtwrap/manager.go
This reverts commit 3e9ba98a98acc41134788bb1e85bfca9eeeea9e0.
Reverts https://github.com/kubevirt/kubevirt/pull/5428
Need to research this flake first
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5551/pull-kubevirt-e2e-k8s-1.20-sig-network/1387317121746210816
```release-note
None
```
> Revert "virt-launcher, Fix flaky VMI report"

- pkg/virt-handler/migration-proxy/migration-proxy.go
- pkg/virt-handler/migration-proxy/migration-proxy_test.go
- pkg/virt-handler/vm.go
- pkg/virt-launcher/virtwrap/manager.go
- staging/src/kubevirt.io/client-go/log/log.go
This is a manual backport of #5496 to release-0.34. We're justifying this backport as a defect to our logging fidelity. We've encountered migration failures that are impractical to debug due to lack of information in our logs. For example, we can tell that a migration fails due to connectivity issues, but because our migration proxy code lacks detailed enough logging, we can't tell if one of the CNV components caused the connectivity issue or if the issue is external to our components.
This logging is required to support this branch. 
----
The logging in our migration proxy code has gaps that leave us without valuable information pertaining to when proxies are start, stop, and fail. As a result, it can be difficult to debug what occurs when a migration fails due to connectivity issues. …
> [release-0.34] Improve migration debug logging 

- pkg/virt-handler/migration-proxy/migration-proxy.go
- staging/src/kubevirt.io/client-go/log/log.go
- staging/src/kubevirt.io/client-go/log/log_test.go
The `With()` function was being globally cached on the default logger rather than returning a new copy of the logger. This was a subtle change with the pointer arithmetic. The result is whenever the With() function was used, that value would get printed for every log line afterwards.
Now when the With function is used, it only pertains to the logger copy.  
```release-note
NONE
```
> fix log pkg With() function for custom arguments

- tests/operator_test.go
**What this PR does / why we need it**: `Tests Suite: [Serial]Operator should reconcile components checking updating resource is reverted to original state for deployments` is very flaky:
* https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-04-26-168h.html#row26
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.19-operator/1386937329628745728
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.19-operator/1386848322324533248
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-operator/1386948310983512064
* https://prow.apps.ovirt.org/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-operator/1385740315264028672 …
> Quarantine operator test

- pkg/virt-operator/resource/apply/core.go
Session affinity is a required defaulted field, since we do not set it in our required manifest the deep equal thinks the two resources are different and continuously patches. 
Fixes #
```release-note
NONE
```
> add cached session affinity before comparing service resource

- tests/operator_test.go
More accurate filtering based on a SIG label which is unique. will be used in the CI lanes jobs.
Usage of the operator SIG label on project-infra can be observed in this [PR](https://github.com/kubevirt/project-infra/pull/1162)
```release-note
NONE
```
> [tests] Adding SIG label for the operator e2e tests

- pkg/virt-launcher/virtwrap/live-migration-source.go
- pkg/virt-launcher/virtwrap/manager_test.go
Some functional and unit tests may become flaky as the live migration monitor kept time in Seconds. 
On some rare occasions, the `lastProgressUpdate` timestamp would be equal to the start timestamp.
Switching to Nanoseconds fixes the issue. 
```release-note
NONE
```
> live migration monitor: account time in NanoSeconds

- tests/vm_test.go
This PR is skipping a rename VM test (test_id:4659), since rename VM feature is broken when kubemacpool is deployed.
The issue is documented on BZ:[1954014](https://bugzilla.redhat.com/show_bug.cgi?id=1954014)
This Affects HCO smoke tests, since there kubemacpool is deployed there.
```release-note
NONE
```
> ci, Skip rename test test_id:4659

- pkg/virt-handler/migration-proxy/migration-proxy.go
- pkg/virt-handler/migration-proxy/migration-proxy_test.go
- pkg/virt-handler/vm.go
- pkg/virt-launcher/virtwrap/manager.go
- staging/src/kubevirt.io/client-go/log/log.go
This is a manual backport of #5496 to release-0.36. We're justifying this backport as a defect to our logging fidelity. We've encountered migration failures that are impractical to debug due to lack of information in our logs. For example, we can tell that a migration fails due to connectivity issues, but because our migration proxy code lacks detailed enough logging, we can't tell if one of the CNV components caused the connectivity issue or if the issue is external to our components.
This logging is required to support this branch. 
----
The logging in our migration proxy code has gaps that leave us without valuable information pertaining to when proxies are start, stop, and fail. As a result, it can be difficult to debug what occurs when a migration fails due to connectivity issues. …
> [release-0.36] Improve live migration proxy logging

- automation/repeated_test.sh
It will be more easy to correlate a test failure to the k8s-reporter logs.
For example, the `pull-kubevirt-check-for-flakes` CI job which uses `autmation/repeated_tests.sh` doesn't produce 
the timestamps.
```release-note
NONE
```
> [automation] adding timestamps for the repeated tests stdout

- cmd/virt-handler/virt-handler.go
- pkg/healthz/BUILD.bazel
- pkg/healthz/healthz.go
- pkg/healthz/healthz_suite_test.go
- pkg/healthz/healthz_test.go
- pkg/virt-api/api.go
- pkg/virt-controller/watch/application.go
- tests/utils.go
- tests/virt_control_plane_test.go
Add functional test for healthz endpoint on virt-handler
Signed-off-by: Marcus Sorensen <mls@apple.com>
The change moves the Kubernetes API version check that is performed by the controller /healthz endpoints to a struct that acts as a cache. So long as the controller watches don't encounter errors, the result of /healthz is served from this cache.  If the controller watch fails, the watch error handler function is called, which clears the cache. This is reflected as unhealthy in the /healthz response, and the /healthz cache then checks connectivity to the Kubernetes API until it is re-established.
Fixes #5058 
I wasn't sure how to come up with a proper test_id for the functional …
> Cache healthz version response and clear when informers error

- tests/storage/datavolume.go
Test is very flaky.
Quarantine it according guideline.
test_id:5252:
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-05-01-168h.html#row32
row 32
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5250/pull-kubevirt-e2e-k8s-1.20-sig-storage/1388786794761293824
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5578/pull-kubevirt-e2e-k8s-1.20-sig-storage/1388759047565479936
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5062/pull-kubevirt-e2e-k8s-1.20-sig-storage/1388746326212087808
```release-note
None
```
> Quarantine flaky test 5252

- tests/config_test.go
- tests/migration_test.go
- tests/security_features_test.go
- tests/storage/storage.go
- tests/utils.go
- tests/vmi_configuration_test.go
We previously had a lot of trouble with a lane running on "kubernetes in docker" (kind).
The only remaining use for it is the SR-IOV lane, that only runs a subset of tests.
Remove no longer relevant skips - the issues referenced by the skip are already closed.
```release-note
NONE
```
> Remove skips not used by any lane 

- docs/release.md
This changes our release policy to release on the first business day of the month rather than the first day of the month. This helps the team resolve issues. 
```release-note
Release branches are now cut on the first _business day_ of the month rather than the first day.
```
> update release policy to cut release branches the first business day of the month

- pkg/controller/controller_ref_manager.go
- pkg/virt-controller/watch/vm_test.go
Fixes a bug in the DataVolumes adoption logic, which tries to patch a VMI (add an ownerReference) instead of patching the DV.
The observed behavior is that the DV is left unclaimed, which manifests itself in several ways:
- If the VMI is stopped, then it can't be started
- If the VMI is running, then it can't be stopped
- If the VM is deleted, then the deletion doesn't cascade to the DV.
Steps to reproduce (using [this](https://gist.github.com/zcahana/010d0ffc1c54c29e6d993c72476d7297) example VM):
```sh
kubectl apply -f alpine.yaml
kubectl delete vm alpine --cascade=orphan
kubectl apply -f alpine.yaml
virtctl start alpine
```
Also added a unit test to cover this behavior.
```release-note
Fixes …
```
> Fix adoption of orphan DataVolumes

- pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
- tests/storage/datavolume.go
- tests/vmi_configuration_test.go
Reject VM defined with volume with no matching disk.
Bugzilla bug: https://bugzilla.redhat.com/show_bug.cgi?id=1954667
Github issue: https://github.com/kubevirt/kubevirt/issues/5556
```release-note
[bugfix] - reject VM defined with volume with no matching disk
```
> [Bug fix] Reject VM defined with volume with no matching disk

- pkg/virt-controller/watch/replicaset.go
- pkg/virt-controller/watch/replicaset_test.go
- pkg/virt-controller/watch/vm.go
- pkg/virt-controller/watch/vm_test.go
This PR removes obsolete code that manually deletes VMI/DV ownerReferences when the owner VM/VMRS has been deleted with the `--cascade=orphan` option.
This code was introduced as workaround for kubernetes/kubernetes#56348, which has been resolved long ago, hence the workaround is not needed anymore.
**Special notes for your reviewer:**
There's an [existing E2E test](https://github.com/kubevirt/kubevirt/blob/0ed56e62f4bac0aebc8564c99eba36eec5d342aa/tests/vm_test.go#L559) that verifies the behavior when VMs are deleted with `--cascade=orphan`.
```release-note
NONE
```
> Remove code to delete ownerReferences for orphan VMIs/DVs

- tests/storage/hotplug.go
This one has not failed in 13 days after #5445 was merged.
the PV test seems stable too, but I would like to wait longer to
be sure.
```release-note
NONE
```
> Remove now-stable test from quarantine

- go.mod
- pkg/virt-controller/watch/vm.go
- pkg/virt-controller/watch/vmi.go
Our KubeVirt control plane logs don't give us enough insight into why a VM/VMI is terminating and restarting. These log messages help.
```release-note
Improved logging around VM/VMI shutdown and restart
```
> Improve logging around VM/VMI shutdown/restart

- pkg/testutils/mock_queue.go
- pkg/virt-operator/kubevirt.go
- tests/BUILD.bazel
- tests/operator_test.go
Using queue.Add() adds the item immediately to be synced and does not take the rate queue limit into account. If added with `.AddRateLimitedItem()` the rate limiter will start to increase its rate limit. By using `AddAfter` we get the desired effect that the item is queued with a 5 second delay to allow the cache store to be populated and up to date. 
Fixes #
```release-note
NONE
```
> allow the cache store to sync during reconciliation

- tests/vm_test.go
The timeout for the `Eventually` block was wrongfully passed to the
`Should` assertion, which causes a panic when the test fails and hides
the actual assertion error, this commit fixes this issue, and changes the assertion to show the actual error when it occures
```release-note
None
```
> Fix test-id 4644

- pkg/testutils/mock_queue.go
- pkg/virt-config/config_test.go
- pkg/virt-handler/BUILD.bazel
- pkg/virt-handler/device-manager/device_controller.go
- pkg/virt-handler/device-manager/device_controller_test.go
- pkg/virt-operator/BUILD.bazel
- pkg/virt-operator/kubevirt_test.go
- pkg/virtctl/imageupload/imageupload_test.go
This PR fixes flaky unit tests by eliminating data races that occur during using go `-race` flag. Based on initial changes from rmohrs PR they isolate test data and synchronize go routines to avoid concurrency issues. 
Fixes #5313
This is a spinoff from https://github.com/kubevirt/kubevirt/pull/5262 in order to get the test changes in and help fixing test flake issues.
```release-note
Fix flaky unit tests
```
> Fix flaky unit tests

- pkg/virt-controller/watch/vmi.go
- pkg/virt-controller/watch/vmi_test.go
An issue was found where VMI is marked as Failed, while in fact it is still starting/being provisioned.
When temporaryPod successfully finishes but DataVolume is not yet updated from phase=WaitForFirstConsumer to any other phase the VMI should stay in Unprocessed phase. Only failed execution or premature termination of tempPod should change VMI state to Failed.
If temporaryPod started (and finished in the case of this isse), that means it had its PVC available in a bound state, and  DataVolume should no longer be in WaitForFirstConsumer phase. If DV still has WaitForFirstConsumer phase, that only means the virt-controller sarted reconciling the VMI and DV before the cdi controller managed to reconcile the DV.   …
> Fix the case when good VMI was marked as failed

- hack/ci/entrypoint.sh
After the prow migration the gcsweb base url has changed, this needs to get fixed in the script that downloads the manifests and the test binary from there. Otherwise the tests fail like this: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-4.8-e2e/1391589525796425728#1:build-log.txt%3A31
Fixes #
```release-note
NONE
```
> Fix gcsweb base url for kubevirt master nightly

- pkg/virt-api/api.go
Previously, during virt-api termination the process would immediately exit. This means that any in-flight requests get terminated and it's possible that new requests may briefly get routed to the terminated virt-api. We also had an issue where virt-api would always panic on exit, which means every shutdown resulted in a non-zero exit code.
In this PR, we now capture SIG_TERM and initiate a graceful shutdown by performing the following steps.
1. capture SIG_TERM and briefly wait 5 seconds in order to allow the load balancer to remove the pod from rotation
2. Initiate shutdown of the tls server, which ensures new requests are rejected and existing requests are allowed to complete.
3. Issue a force close() if existing idle connections do not terminate after a short period of time.
4. ensure …
> Gracefully shutdown virt-api

- BUILD.bazel
- WORKSPACE
- hack/bazel-test.sh
- nogo_config.json
- pkg/certificates/BUILD.bazel
- pkg/hooks/BUILD.bazel
- pkg/util/openapi/BUILD.bazel
- pkg/virt-api/webhooks/BUILD.bazel
- pkg/virt-controller/watch/drain/disruptionbudget/BUILD.bazel
- pkg/virt-launcher/virtwrap/device/BUILD.bazel
- pkg/virt-launcher/virtwrap/device/sriov/BUILD.bazel
- pkg/virtctl/BUILD.bazel
- pkg/virtctl/expose/BUILD.bazel
- pkg/virtctl/imageupload/BUILD.bazel
- pkg/virtctl/pause/BUILD.bazel
- pkg/virtctl/vm/BUILD.bazel
- tests/BUILD.bazel
- vendor/github.com/opencontainers/runc/libcontainer/configs/BUILD.bazel
- vendor/github.com/prometheus/client_golang/prometheus/BUILD.bazel
- vendor/github.com/u-root/u-root/pkg/rand/BUILD.bazel
- vendor/github.com/vishvananda/netlink/BUILD.bazel
Based on #5262, this PR restores the ability to run goveralls again. This contains the changes to reenable bazel coverage and also enable the go -race flag in order to catch flakyness and data races.
Fixes #
```release-note
Reenable coverage
```
> Enable coverage for goveralls

- tests/storage/hotplug.go
Waited a bit longer to see that this variant is also stable.
No failures in the past 14 days.
```release-note
NONE
```
> Remove now-stable hotplug test from quarantine.

- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
- tests/network/vmi_networking.go
VirtualMachine with the following spec fails to live migrate:
```
spec:
domain:
devices:
interfaces:
- name: default
masquerade: {}
ports:
- port: 22222 | 49152 | 49153
```
because ports 22222, 49152, 49153 are used for live migration. 
This PR excludes these three ports from being forwarded IF sent from virt-launcher localhost.
User is still able to reach services running inside the VM on any port, including the three mentioned above.
The consequence is that `kubectl port-forward` does not work for the three excluded ports.
Fixes #
BZ: …
> Avoid forwarding local traffic to ports used by live migration

- tests/vmi_configuration_test.go
**What this PR does / why we need it**: Quarantine ` [sig-compute]Configurations VirtualMachineInstance definition [Serial][rfe_id:2065][crit:medium][vendor:cnv-qe@redhat.com][level:component]with 3 CPU cores [test_id:1663]should report 4 vCPUs under guest OS`:
* Flakefinder report: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-05-09-168h.html#row3
* Recent failures:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-cgroupsv2/1391679499279536128
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sig-compute/1391478154152906752
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1 …
> Quarantine flaky sig-compute test

- pkg/network/cache/fake/infocache.go
- pkg/network/cache/infocache.go
- pkg/network/cache/infocache_test.go
- pkg/network/cache/types.go
- pkg/network/driver/common.go
- pkg/network/driver/common_test.go
- pkg/network/driver/generated_mock_common.go
- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
Extends the existing cache mechanism to also cache the network VIFs, which will be used to pass the original pod networking information to the DHCP server running in virt-launcher.
A follow-up PR will allow the get / set cached VIF functions to be moved away from `BindMechanism` interfaces, into the podNIC structs, thus further cleaning up the interface.
Depends-on: #5044 
```release-note
NONE
```
> Add vif cache

- tests/storage/restore.go
I can't point to a single commit, but it shares the bulk of its
logic with recently de-flaked tests, and it's reasonable to
suspect it is fixed.
```release-note
NONE
```
> Remove restore test from quarantine - hasn't failed in 14 days

- pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
- tests/vm_watch_test.go
When starting a lot of VMIs at once on a given cluster, it can take some time for VMI statuses to go from blank to pending.
That can be confusing to the user, and starting VMIs directly in the pending status should solve that.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1903667
```release-note
NONE
```
> Set VMI status to pending on creation

- api/openapi-spec/swagger.json
- pkg/virt-controller/watch/vm.go
- pkg/virt-controller/watch/vm_test.go
- pkg/virt-operator/resource/generate/components/crds.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
- tests/kubectl_test.go
- tests/vm_watch_test.go
This PR adds a new `status.printableStatus` field to the VirtualMachine CRD, as well as a new `STATUS` column to the output of `kubectl get vm`.
The purpose of this field is to provide a high-level representation of the status of the virtual machine. It's designated to be consumed by human users, and not automated processes (i.e., no state machine semantics, values may be added or dropped in the future, ...).
Here's an example output:
```bash
$ kubectl get vms
NAME     AGE   STATUS    VOLUME
testvm   4s    Stopped
```
**Release note:**
```release-note
Introduced a "status.printableStatus" field in the VirtualMachine CRD. This field is now displayed in the tabular output of "kubectl get vm".
```
> Introduce VirtualMachine status field and CLI column

- docs/release-branch-backporting.md
When supporting stable release branches, we often need to introduce changes that improve logging and debuggability. This updates our policy to officially allow for those changes so it's no longer a grey area.
```release-note
Expand backport policy to include logging and debug fixes
```
> Expand our backport policy to include logging and debug fixes

- pkg/controller/controller.go
- pkg/virt-controller/watch/migration.go
- pkg/virt-controller/watch/migration_test.go
- pkg/virt-operator/resource/apply/reconcile.go
This patch series involves three changes.
1. Refactoring the migration controllers sync() function into smaller functions
2. Transition to using PATCH rather than UPDATE when modifying VMIs from the migration controller
3. Only hand off the target pod to virt-handler once the target pod is considered ready (previously the pod was handed off immediately after being created). This is the same check performed by the vmi controller when handing off pods to virt-handler.
I also improved some logging throughout the controller.
```release-note
NONE
```
> Migration controller enhancements

- pkg/virt-operator/resource/generate/components/webhooks.go
related to: https://bugzilla.redhat.com/show_bug.cgi?id=1957477 
Previously, no default timeout was set on our validation webhook. The default timeout is usually 10 seconds on newer versions of k8s, but it has been seen to be as high as 30 seconds on older versions of k8s. So the default changed.
This has led to some unexpected results, where a Validation Webhook with a `failurePolicy: Ignore` actually blocks all modifications of resources due to the default 30 second webhook timeout bumping up into the api servers total request timeout period. 
Since the default timeout period can be inconsistent, we should instead explicitly set our timeout value and not depend on defaulting. This gives us stronger guarantees around what timeout the api server will observe. A 10 second timeout should be …
> Add default webhook timeouts

- pkg/virt-operator/creation/components/webhooks.go
backport of: #5661 
related to: https://bugzilla.redhat.com/show_bug.cgi?id=1957477 
Previously, no default timeout was set on our validation webhook. The default timeout is usually 10 seconds on newer versions of k8s, but it has been seen to be as high as 30 seconds on older versions of k8s. So the default changed.
This has led to some unexpected results, where a Validation Webhook with a `failurePolicy: Ignore` actually blocks all modifications of resources due to the default 30 second webhook timeout bumping up into the api servers total request timeout period. 
Since the default timeout period can be inconsistent, we should instead explicitly set our timeout value and not depend on defaulting. This gives us stronger guarantees around what timeout the api server will observe. A 10 …
> [release-0.34]  Add default webhook timeouts

- pkg/virt-operator/resource/generate/components/webhooks.go
Manual cherry pick of https://github.com/kubevirt/kubevirt/pull/5661 due to merge conflict. Original PR description follows:
-----------
related to: https://bugzilla.redhat.com/show_bug.cgi?id=1957477
Previously, no default timeout was set on our validation webhook. The default timeout is usually 10 seconds on newer versions of k8s, but it has been seen to be as high as 30 seconds on older versions of k8s. So the default changed.
This has led to some unexpected results, where a Validation Webhook with a failurePolicy: Ignore actually blocks all modifications of resources due to the default 30 second webhook timeout bumping up into the api servers total request timeout period.
Since the default timeout period can be inconsistent, we should instead explicitly set our timeout value and not …
> [release-0.41] Add default webhook timeouts

- cmd/virt-launcher/virt-launcher.go
- pkg/container-disk/container-disk.go
- pkg/emptydisk/emptydisk.go
- pkg/emptydisk/emptydisk_test.go
- pkg/ephemeral-disk/ephemeral-disk.go
- pkg/ephemeral-disk/ephemeral-disk_test.go
- pkg/ephemeral-disk/fake/BUILD.bazel
- pkg/ephemeral-disk/fake/ephemeral-disk.go
- pkg/hooks/BUILD.bazel
- pkg/hooks/manager.go
- pkg/hooks/manager_test.go
- pkg/hotplug-disk/hotplug-disk.go
- pkg/hotplug-disk/hotplug-disk_test.go
- pkg/network/driver/common_test.go
- pkg/virt-handler/hotplug-disk/mount.go
- pkg/virt-handler/hotplug-disk/mount_test.go
- pkg/virt-launcher/virtwrap/BUILD.bazel
- pkg/virt-launcher/virtwrap/converter/BUILD.bazel
- pkg/virt-launcher/virtwrap/converter/converter.go
- pkg/virt-launcher/virtwrap/converter/converter_test.go
- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
This is the first PR of a series which fixes a lot of unit tests which are not properly written. They had:
* shared contexts with global variables and functions which leads to:
* unwanted side effects if unit tests are run in parallel
*  complicated BeforeEach and AfterEach logic
* absolute paths hardcoded which  made it impossible to run them as non-root
* tests for a lot of golbal functions without context which
* made it very hard to mock them out
* required deep preparations when testing higher-level modules
Now they do the following:
* Introduce structs and  interfaces which
* have their own state, where for instance absolute paths can be cleanly replaced with temporary directories
* can easily be mocked out in higher level tests due to the …
> Properly deal with absolute paths in unit tests, part 1

- tests/storage/restore.go
Wait for resize successfully when using block mode
When creating a vm with block mode there is a resize of
the block device, it seems that in the CI the message of the success of
the resize might take some time to be printed and it fails the
test which expects at the time of the late print for
an empty prompt.
Instead we should check that the resize completed successfully before
continuing to the rest of the test.
Fixes #
```release-note
NONE
```
> Fix test from quarantine - Wait for resize successfully when using block mode

- tests/migration_test.go
- tests/vmi_hook_sidecar_test.go
**What this PR does / why we need it**: quarantine flaky tests to improve suite stability.
* `[Serial][rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system][sig-compute] VM Live Migration Starting a VirtualMachineInstance  with a Fedora shared NFS PVC (using nfs ipv4 address), cloud init and service account should be migrated successfully, using guest agent on VM [test_id:5004] with postcopy`
* Reported by flakefinder https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-05-16-168h.html#row0
* Recent failures:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sig-compute/1394135611610238976
* …
> Quarantine 2 sig-compute flaky tests

- Makefile
- hack/goveralls.sh
Use `PULL_BASE_REF` for referencing the base branch for coverage. Use `PULL_PULL_SHA` to override the git sha, as the one fetched from the presubmit is different due to branch rebasing. Use `PROW_JOB_ID` to reference the prow job this build result originates from. 
See [prow env var docs](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#job-environment-variables)) 
Fixes #
```release-note
NONE
```
> Fix base branch reference for coveralls

- .bazelrc
- pkg/virt-operator/BUILD.bazel
- pkg/virt-operator/kubevirt.go
- pkg/virt-operator/kubevirt_test.go
Improves the general execution speed of virt-operator from 167 seconds down to 26 seconds.
In addition the parallel ginkgo test execution is enabled which reduces the execution time to 10 seconds for the operator, and the virt-handler tests now need 50 seconds compared to more than 200 seconds.
For code coverage, parallel test execution of ginkgo is disabled to not confuse the coverage generator with the fork model which ginkgo uses for parallel runs.
Fixes #
```release-note
NONE
```
> Speed up unit tests

- pkg/network/BUILD.bazel
- pkg/network/reserved_macs.go
- pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
- pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
- pkg/virt-launcher/virtwrap/network/BUILD.bazel
- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
- tests/network/vmi_networking.go
Since the bridge MAC address no longer changes, the ARP tables do
not need to stabilize, which preserves connectivity from the
outside world to the guest.
This is tested in this commit since the `Eventually` block in the
vmi_networking_test for masquerade binding migration can be safely
removed.
Reserve the hardcoded mac address when masquerade binding is used; as such, throw an error whenever a user attempts to
specify that MAC on a masquerade interface.
Fixes #4999
```release-note
NONE
```
> masquerade, migration: hardcode the bridge MAC addr

- pkg/virt-operator/kubevirt_test.go
In #5684 I removed some `time.Sleep` which revealed a sync race in operator tests.
The races can be fixed by expecting the corresponding enqueues into the workqueue.
Fixes #
```release-note
NONE
```
> Fix a race in the operator unittests

- tests/migration_test.go
Fixed by vladikr in kubevirt#5323.
```release-note
NONE
```
> Take now-stable migration tests out of quarantine.

- pkg/virt-operator/creation/components/webhooks.go
backport of: #5661 
related to: https://bugzilla.redhat.com/show_bug.cgi?id=1957477 
Previously, no default timeout was set on our validation webhook. The default timeout is usually 10 seconds on newer versions of k8s, but it has been seen to be as high as 30 seconds on older versions of k8s. So the default changed.
This has led to some unexpected results, where a Validation Webhook with a `failurePolicy: Ignore` actually blocks all modifications of resources due to the default 30 second webhook timeout bumping up into the api servers total request timeout period. 
Since the default timeout period can be inconsistent, we should instead explicitly set our timeout value and not depend on defaulting. This gives us stronger guarantees around what timeout the api server will observe. A 10 …
> [release-0.36] Add default webhook timeouts

- pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
- tests/storage/datavolume.go
- tests/vmi_configuration_test.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/5585
------------
Reject VM defined with volume with no matching disk.
Bugzilla bug: https://bugzilla.redhat.com/show_bug.cgi?id=1954667
Github issue: https://github.com/kubevirt/kubevirt/issues/5556
original pr: https://github.com/kubevirt/kubevirt/pull/5585
```release-note
[bugfix] - reject VM defined with volume with no matching disk
```
> [release-0.41] Reject VM defined with volume with no matching disk

- pkg/virt-controller/watch/migration.go
- pkg/virt-controller/watch/migration_test.go
If a migration object transistions to "Failed" before being handed off to virt-controller, it's possible that we'll attempt to access the vmi.Status.MigrationState when it's an uninitialized null pointer.  This can happen for example if the target pod fails during execution before the handoff, or if the target pod is somehow deleted before the handoff.
The result is that virt-controller can get into a situation where it crash loops until the effected migration object is removed from the cluster.
```release-note
Fixes null pointer dereference in migration controller
```
> Fixes migration controller null pointer dereference

- .bazelrc
- pkg/util/types/BUILD.bazel
- pkg/util/types/patch.go
- pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
- pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator.go
- pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator_test.go
- pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
- pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
- pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
- pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
- pkg/virt-controller/watch/BUILD.bazel
- pkg/virt-controller/watch/migration_test.go
- pkg/virt-handler/node-labeller/BUILD.bazel
- pkg/virt-handler/node-labeller/node_labeller.go
This reverts commit 4d2680a385368330ed59e0d17f4107a2e349e526.
By adding `ginkgo.parallel.total=5` the unit tests seem to only run the first `Context` block under each unit tests describe.
Fixes #
```release-note
None
```
> Revert "Enable ginkgos parallel test runner for unit tests"

- pkg/virt-controller/watch/migration.go
- pkg/virt-controller/watch/migration_test.go
related to: https://bugzilla.redhat.com/show_bug.cgi?id=1945532
Pulls targeted fix from enhancement PR: #5593
Pulls unit test from PR: #5703
When virt-controller hands off a target pod to virt-handler, that hand off occurs by initializing the vmi.Status.MigrationState object. During this initialization, any previous completed migration is overwritten with the new migration data.
There's a bug in this logic...
Under a rare sequence of events, it's possible to re-initialize this vmi.Status.MigrationState object for an active migration that has already been handed off. This is caused by a race condition between the virt-controller's migration controller reconcile loop, and how quickly the informer cache is updated. As a result this is most likely to occur when the system is under load which …
> [release-0.34] Fix virt-controller clobbering in progress vmi migration state

- pkg/virt-handler/node-labeller/node_labeller.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- tests/infra_test.go
add special node-labeller annotations
this annotations causes that node-labeller will skip reconciling the
node which has this annotation
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1956792
```
add node-labeller.kubevirt.io/skip-node annotation 
```
> add special node-labeller annotations

- tests/flags/flags.go
When KubeVirt's e2e test are executed in a standalone mode (against an
arbitrary non-kubevirtci cluster), they fetch all the VM and utility
images from Docker Hub. That causes issues due to rate limiting.
With this change, the default registry is Quay.io, which is aligned with
the rest of the artifacts released under KubeVirt.
This issue is especially problematic in conformance testing, where there
is no option to overwrite the default --container-prefix through
Sonobuoy.
```release-note
NONE
```
> Point tests to quay images by default

- tests/kubevirt_configmap_test.go
**What this PR does / why we need it**: Quarantine flaky sig-compute tests:
* `[Serial][sig-compute]KubeVirtConfigmapConfiguration [test_id:4670]check health check returns configmap resource version`
* flakefinder report: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-05-26-168h.html#row36
* Recent failures: 
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1397674086238261248
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-sig-compute/1397560826742706176
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5558/pull-kubevirt-e2e-k8s-1.20-sig-compute/1397594545360736256
* …
> Quarantine 2 flaky sig-compute tests

- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
Right now if graceful shut down is called before acpi is able to receive events it will never reach acpi. According to https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-handler/vm.go#L1992 this should not be the case, but we should instead keep trying to send this event. 
This was verified by @xpivarc 
Bug https://bugzilla.redhat.com/show_bug.cgi?id=1933043 
```release-note
Allow multiple shutdown events to ensure the event is received by ACPI
```
> allow multiple calls to graceful shutdown in case acpi did not recieve call

- hack/build-manifests.sh
- hack/builder/Dockerfile
Drop j2 templates from the release manifests. Kustomize can be used for customiations. The templates were added a long time ago to support kubevirt-ansible roles which are no longer in use.
Fixes #
```release-note
Stop releasing jinja2 templates of our operator. Kustomize is the preferred way for customizations.
```
> Drop j2 templates

- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
- tests/network/BUILD.bazel
- tests/network/port_forward.go
- Until now, it has been possible to perform `port-forward` to
the VMI's pod, only when the target port was explicitly specified
in the VMI spec (With masquerade binding).
This commit adds nft and iptables rules to support `port-forward` also
when the port is not specified in the VMI spec,
and it will work for any port that the vmi listens to.
When the port is specified, the old behavior will be kept,
and port-forward will work only for the pre-defined port,
Making it possible for the user to limit the number of ports
that are allowed for port-forwarding.
-    Adds tests for `kubectl port-forward` to
the VMI's pod. It includes:
-  test `kubectl port-forward` to a port that is declared
in the VMI spec.
- test `kubectl port-forward` to a port that is …
> Fix port forward no explicit ports

- hack/check-unassigned-tests.sh
**What this PR does / why we need it**: While working on #5741 we noticed that new tests have been recently added without assigning them to any SIG. This PR adds a simple script to run `make functest` in dry mode with a skip to filter out all the SIG, SRIOV and GPU tests, if any test is left the execution fails. This script will be used on a presubmit lane that will warn us if a new test is added without assignment.
Fixes #
```release-note
NONE
```
> Add script to check for unassigned tests

- pkg/virt-launcher/virtwrap/network/podinterface.go
- tests/network/vmi_networking.go
A linux bridge MAC is set to the lowest mac address of any of the ports on it; the dummy is in place to
help keep the mac address of the bridge stable. 
Since we have started to use the same MAC address on all bridges masquerade binding bridges, plus
there's a single VM connected (hence a single tap) to the bridge, the dummy is redundant (the pod lives
as long as the VM).
Fixes #
```release-note
NONE
```
> network, masquerade: remove dummy

- pkg/virt-handler/vm.go
- tests/BUILD.bazel
- tests/events_test.go
- tests/io_utils.go
- tests/storage/storage.go
This PR reflects pausing of domain on IO error to VMI. 
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1901335
`SyncVMI` will try to unpause the domain.
```release-note
None
```
> Pause on IO error

- pkg/virt-handler/vm.go
- tests/BUILD.bazel
- tests/events_test.go
- tests/io_utils.go
- tests/storage/storage.go
This PR reflects pausing of domain on IO error to VMI. 
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1901335
`SyncVMI` will try to unpause the domain.
Backport of https://github.com/kubevirt/kubevirt/pull/5401
```release-note
None
```
> [release-0.41] paused on io error

- go.mod
- go.sum
- manifests/testing/cdi-v1.34.0.yaml.in
- staging/src/kubevirt.io/client-go/go.mod
- staging/src/kubevirt.io/client-go/go.sum
- vendor/modules.txt
1.34.0 was buggy
Fixes #
```release-note
Update CDI to 1.34.1
```
> update cdi to 1.34.1

- .bazelrc
- WORKSPACE
- hack/coverage.sh
- pkg/util/webhooks/BUILD.bazel
- pkg/virt-controller/watch/BUILD.bazel
- pkg/virt-controller/watch/node_test.go
- pkg/virt-controller/watch/vmi_test.go
- pkg/virt-handler/BUILD.bazel
- pkg/virt-handler/vm_test.go
- pkg/virt-operator/BUILD.bazel
- staging/src/kubevirt.io/client-go/testutils/BUILD.bazel
- staging/src/kubevirt.io/client-go/testutils/setup.go
- tools/ginkgo/ginkgo.bzl
This is the second attempt after #5712 to run unit tests in parallel through ginkgo. In the first attempt in #5684 I made a mistake which led to tests being skipped. This time it should be done properly.
A new `ginkgo_test` target is introduced. In order to make use of it, do the following:
First import `ginkgo_test` to a BUID file with the `go_test` target you want to speed up: 
```python
load("@kubevirt//tools/ginkgo:ginkgo.bzl", "ginkgo_test")`
```
Mark the original `go_test` target with the `cov` tag to avoid double exeuction if you do something like `bazel test //pkg/...`:
```python
go_test(
name = "go_default_test",
[...]
tags = ["cov"],
[...]
)
```
Introduce the new `ginkgo_test` target, point it to the `go_test` target and tell it to run in …
> Run a first set of unit tests in parallel through ginkgo

- hack/prom-rule-ci/prom-rules-tests.yaml
- pkg/virt-operator/resource/generate/components/crds.go
Add alerts for with CPU or memory exceed the requested resources for virt-controller, virt-api, virt-operator and virt-handler.
Fixes #
```release-note
Alert with resource usage exceeds resource requests
```
> add alerts for exceeding resouce requests

- tests/events_test.go
- tests/vmi_iothreads_test.go
- tests/vmi_kernel_boot_test.go
For a proper distribution of tests among the CI lanes
```release-note
NONE
```
> [tests] assign sig labels to the unlabelled tests

- .gitignore
- automation/test.sh
Generate rest coverage report after functional tests, this gives some insights about used endpoints and fields during tests execution.
Fixes #4768 
Currently the coverage tool ignores version of KubeVirt resources. For KubeVirt the openapi spec is generated for `v1` but all are sent to `v1alpha3` endpoint, because of that, I am not able to match audit log with openapi spec thus I ignore version.
I think in that case it's fine since the API structures are the same for v1alpha3 and v1.
There is a test prow job present that runs the coverage report tool. This …
> Generate REST coverage report after execution of functional tests

- tests/operator_test.go
**What this PR does / why we need it**: `Add test_id to daemonset and service reconcile tests`
Fixes #
```
NONE
```
> Add test_id to daemonset and service reconcile tests

- pkg/cloud-init/cloud-init.go
- pkg/config/config.go
- pkg/config/sysprep.go
- pkg/container-disk/container-disk.go
- pkg/hooks/manager.go
- pkg/inotify-informer/inotify.go
- pkg/virt-handler/cache/cache.go
- pkg/virt-handler/cmd-client/client.go
- pkg/virt-handler/container-disk/mount.go
- pkg/virt-handler/device-manager/common.go
- pkg/virt-handler/device-manager/mediated_device.go
- pkg/virt-handler/node-labeller/cpu_plugin.go
- pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go
- pkg/watchdog/watchdog.go
- tools/crd-validation-generator/validation-generator.go
- tools/manifest-templator/manifest-templator.go
Replace occurrences of the old and deprecated ioutil.ReadDir
with the new and more efficient os.ReadDir.
I also replaced some usages of the ioutil package along the way
as the whole module is deprecated as of Go 1.16.
Fixes #
```release-note
NONE
```
> use new os.ReadDir instead of the deprecated ioutil.ReadDir

- pkg/virt-handler/vm.go
- pkg/virt-launcher/virtwrap/converter/converter.go
- pkg/virt-launcher/virtwrap/converter/converter_test.go
- tests/vmi_configuration_test.go
This commit fixes UEFI mode with secureboot disabled
for base images (for virt-launcher) where only `OVMF_CODE.secboot.fd`
is shipped, letting the combination `OVMF_CODE.secboot.fd` +
`OVMF_VARS.fd` to be used to correctly boot in EFI mode with
no secureboot.
Previously when disabling secureboot virt-launcher would only try
to use `OVMF_CODE.fd` + `OVMF_VARS.fd` resulting in a VMI failure
when the former firmware file was not shipped.
Unfortunately a couple unit test had to be removed as the generated
VMI XML domain is now dependent on which files are present in the
filesystem and the FS cannot be mocked. …
> virt-launcher: fix UEFI-mode without secureboot

- pkg/network/cache/BUILD.bazel
- pkg/network/cache/types.go
- pkg/network/cache/types_test.go
- pkg/network/driver/BUILD.bazel
- pkg/network/driver/common_test.go
Currently, the `DhcpConfig.String()` method (which is not being used in the code) panics when the IP parameter is not set. Furthermore, its output for IPv4 and IPv6 addresses differed, by considering the IPv4 mask an entity in itself.
This PR addresses that, by aligning the ipv4 implementation w/ the ipv6 one - which handles nil.
I threw in renaming some vestigial `vif` references I've seen in the code to the new type, `DhcpConfig` . I'm aware this should have been done in a different PR, but, I felt silly pushing just that.
Fixes #
Depends-on: #5711 …
> Fix dhcp config string

- pkg/virt-handler/hotplug-disk/mount.go
- pkg/virt-handler/hotplug-disk/mount_test.go
Several `virt-launcher` pods may still be running for a single VMI after migration and that will prevent from mounting hotplug disks. Find the proper pod by checking if the expected hotplug directory exists.
After successfull migration the source launcher pod is not deleted:
```
virt-launcher-testvm-gs7n4       0/2     Completed   0          47m
```
and it stays in the list of VMI `Active Pods`:
```
Status:
Active Pods:
148a69ba-95ae-43dd-b12f-f0eab833a83b:  node02
c0a7a88a-4dac-44f9-bd5c-e966db1464d7:  node01
```
The fix is based on the approach implemented for `ContainerDisks`:
https://github.com/kubevirt/kubevirt/blob/d2eb0cf7ddc93eb88e0f590b1790558e44c6586b/pkg/container-disk/container-disk.go#L61-L79 …
> Handle several active VMI pods during disk hotplug

- WORKSPACE
Update kernel boot container to tag 07_05_2021__1.
The new container's binaries (kernel & initrd) are owned by QEMU (UID 107).
Container image on quay:
https://quay.io/repository/kubevirt/alpine-ext-kernel-boot-demo
PR to update Dockerfile:
https://github.com/kubevirt/kubevirtci/pull/613
```release-note
None
```
> Update kernel boot container files to be owned by QEMU

- tests/storage/datavolume.go
- tests/vm_test.go
**What this PR does / why we need it**: Quarantine flaky tests:
* `[rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-compute]VirtualMachine [Serial]A mutated VirtualMachine given [test_id:3312]should set the default MachineType when created without explicit value`
* flakefinder report https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-06-07-168h.html#row6
* Recent failures:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5402/pull-kubevirt-e2e-k8s-1.20-sig-compute/1402232004669345792
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5752/pull-kubevirt-e2e-k8s-1.20-sig-compute/1402221595346341888
* …
> Quarantine sig-compute and sig-storage flaky tests

- tests/utils.go
Small fix stop accumulating useless info in error message
```release-note
NONE
```
> Fix accumulating useless info in error message

- automation/release.sh
Since #5738  we don't generate templates anymore. Some leftovers make the release script fail.
Fixes #
```release-note
NONE
```
> Remove jinja2 leftovers in the release script

- pkg/virt-controller/watch/migration.go
- pkg/virt-controller/watch/migration_test.go
related to: https://bugzilla.redhat.com/show_bug.cgi?id=1945532
Pulls targeted fix from enhancement PR: #5593
Pulls unit test from PR: #5703
When virt-controller hands off a target pod to virt-handler, that hand off occurs by initializing the vmi.Status.MigrationState object. During this initialization, any previous completed migration is overwritten with the new migration data.
There's a bug in this logic...
Under a rare sequence of events, it's possible to re-initialize this vmi.Status.MigrationState object for an active migration that has already been handed off. This is caused by a race condition between the virt-controller's migration controller reconcile loop, and how quickly the informer cache is updated. As a result this is most likely to occur when the system is under load which …
> [release-0.41] Fix virt-controller clobbering in progress vmi migration state

- hack/patch.sh
Currenctly iterating on kubevirt take a lot of time on redploying the
changes. This change creates a hacky script that will patch
controller/handler/launcher to speed things up.
Fixes #
```release-note
NONE
```
> Add ./hack/patch.sh to patch kubevirt

- Makefile
- docs/conformance.md
- hack/config-default.sh
- hack/conformance.sh
- hack/functests.sh
- tests/README.md
- tests/flags/flags.go
- tests/network/vmi_networking.go
- tests/network/vmi_slirp_interface.go
Signed-off-by: alonsadan <asadan@redhat.com>
Internal  and external connectivity tests are two separate networking
capabilities, that should be tested seperatly. This PR extracts the external
conn' tests to a separate ginkgo case. 
In addition, to allow running the network tests also in an environment
with no internet connection, This PR adds the ability to skip, or set 
different addresses  for the outside conn' tests.
This allowes also to remove the XFAIL from the ipv6 outside conn' test.
Fixes #5113 
```release-note
NONE
```
> tests, outside-connectivity: change hard-coded addresses to cmd flags

- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
- tests/network/BUILD.bazel
- tests/network/vmi_istio.go
This pull request adds nft rules that correctly route
traffic proxied by Istio envoy if VMI has
Istio sidecar injection enabled with an annotation.
Not updating IPtables because this is a new feature.
This PR deals with VMI with masquerade binding
with interface, that doesn't explicitly specify any ports.
There are two issues addressed:
1) With Istio proxy, we can't dnat traffic at KUBEVIRT_PREINBOUND
2) Istio uses the following ports for its functionality:
"15000", "15001", "15006", "15008", "15020", "15021", "15090"
These ports need to be excluded from forwarding to the VM.
E2E tests are extended to also include VMI without explicitly specified
ports for each scenario.
Additionally, a test testing that port restricted for istio is not reachable in …
> Istio, Update nft rules for VMI with masquarade interface with no explicit ports

- pkg/virt-api/rest/BUILD.bazel
- pkg/virt-api/rest/authorizer.go
- pkg/virt-api/rest/authorizer_test.go
Replaced occurrences and ran 'make && make generate'
authorization/v1beta1 is deprecated as of k8s 1.22, this PR migrates the occurrences we have in KubeVirt to authorization/v1.
Fixes #
```release-note
migrated references of authorization/v1beta1 to authorization/v1
```
> migrate references of authorization/v1beta1 to authorization/v1

- Makefile
- hack/dep-update.sh
When people do go.mod updates we have a blind spot in CI, regarding to how well this was done. This PR adds a `deps-sync` target which can be used in CI to check if they are in sync.
In order to avoid any go dependency fetch issues, and still fully profit from the vendor folder, we can run the CI job only when `/vendor` content or a `go.mod` file is changed on the PR.
Fixes #
```release-note
NONE
```
> Add a target to check if our go.mod files and our vendor folder are all in sync

- go.mod
- go.sum
- vendor/modules.txt
The upgrade of golang from 1.13 to 1.16 missed the update to the go.mod file.
This caused some issues with tools that depend on it (e.g. IDE).
Fixes #
```release-note
NONE
```
> go.mod: Update the go version to 1.16

- pkg/virt-operator/resource/apply/BUILD.bazel
- pkg/virt-operator/resource/apply/core.go
- pkg/virt-operator/resource/apply/core_test.go
Right now if the ca-bundle is updated to something that is not parseable it will never be updated. This change updates the ca-bundle value if we can not parse it. 
Fixes #
```release-note
Update ca-bundle if it is unable to be parsed
```
> update configmap cabundle if it is not parseable

- cmd/virt-launcher/BUILD.bazel
- cmd/virt-launcher/virt-launcher.go
- tests/network/vmi_istio.go
- tests/utils.go
When VMI has Istio Proxy sidecar, then after migration the proxy keeps running in the original virt-launcher pod indefinitely.
This PR terminates the proxy, so that the original virt-launcher pod can get to `completed` state.
Fixes #5657
The solution introduced in this PR is best-effort, if for some reason the curl request fails, then the proxy is not terminated.
I tried to look into how virt-handler could deal with the `istio-agent` process in a "no questions asked" manner, but I couldn't figure out how to …
> Terminate Istio Proxy at VM Cleanup

- tests/BUILD.bazel
- tests/vm_watch_test.go
This PR complements #5528 by adding a functional test to verify the correct display of VM status via the CLI, across different VM lifecycle stages.
```release-note
NONE
```
> Extend VM watch functest to verify printableStatus transitions

- Makefile
- hack/gen-proto.sh
- hack/generate.sh
Calling "make generate" everytime there is a change at a .proto file
takes a lot of time, this change move the protoc generation to
hack/gen-proto.sh and it's called from hack/generate.sh and from a
target at Makefile so it can be called if needed.
Fixes #
```release-note
NONE
```
> Add make target to protoc generation

- pkg/virt-launcher/virtwrap/network/network.go
- pkg/virt-launcher/virtwrap/network/network_test.go
Currectly the errors from getNICs and getNICsWithLauncherPID are not
being propagated at Phase1 and Phase2. This change propagate them in
case they are not nil.
Fixes #
```release-note
NONE
```
> network, phases: Return error from getnic

- tests/vmi_lifecycle_test.go
The test has no failures on the periodics, so Removing quarantine label
```release-note
NONE
```
> Remove quarantine label

- tests/network/vmi_multus.go
Move test `should keep connectivity after a migration` to quarantine because of high flakiness.
Fixes #
```release-note
NONE
```
> tests, network: quarantine macvtap VMI migration test

- pkg/network/consts/BUILD.bazel
- pkg/network/consts/annotations.go
- pkg/virt-controller/services/BUILD.bazel
- pkg/virt-controller/services/template.go
- pkg/virt-controller/services/template_test.go
- pkg/virt-launcher/virtwrap/network/BUILD.bazel
- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
- tests/network/BUILD.bazel
- tests/network/vmi_istio.go
This PR adds default serviceAccountToken automatically when
sidecar.istio.io/inject annotation is added in the VMI.
This improves user experience, bacause users don't need to add a serviceAccountDisk manually.
Adding the annotation becomes the only requirement for Istio service mesh to work properly.
Fixes #
```release-note
Add serviceAccountDisk automatically when Istio is enabled in VMI annotations
```
> Istio, automount serviceAccountToken when Istio enabled in VMI annotations

- pkg/virt-controller/watch/application_test.go
- pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
- pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
- pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
- pkg/virt-controller/watch/migration_test.go
- pkg/virt-controller/watch/node_test.go
- pkg/virt-controller/watch/replicaset_test.go
- pkg/virt-controller/watch/snapshot/restore_test.go
- pkg/virt-controller/watch/snapshot/snapshot_test.go
- pkg/virt-controller/watch/vm_test.go
- pkg/virt-controller/watch/vmi_test.go
- pkg/virt-controller/watch/workload-updater/workload-updater_test.go
- pkg/virt-handler/vm_test.go
- pkg/virt-launcher/notify-client/notify_test.go
- pkg/virt-operator/kubevirt_test.go
We discovered a segfault that can occur as a result of reporting an event when a VMI pod's pdb is deleted and the VMI no longer exists.
This went unnoticed in our unit tests because our mock event recorder was ignoring objects that were passed into it. By making the mock recorder take into account objects, we catch segfaults like this because the mock recorder will crash when trying to dereference a null object pointer. 
This change to the mock recorder reproduced the bug in question and the bug has now been addressed. To  prevent similar issues from occurring in the future, i've enabled all mock recorders in our unit tests to parse the involved objects. 
```release-note
```
> Fixes Event recording segfault

- pkg/virt-handler/cache/cache_test.go
- pkg/virt-launcher/virtwrap/BUILD.bazel
- pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
- pkg/virt-launcher/virtwrap/agent-poller/agent_poller_test.go
- pkg/virt-launcher/virtwrap/cmd-server/server.go
- pkg/virt-launcher/virtwrap/cmd-server/server_test.go
- pkg/virt-launcher/virtwrap/generated_mock_manager.go
- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
Virt-handler refresh the VMI domain information,
each 300 seconds by handleResync function.
The information it fetched doesn't include
Guest Agent information such as Guest OS Info,
and interface status.
This will cause flakiness in the VMI status,
each time that the report is fetched,
until the next update of Guest Agent will be sent
by the virt-launcher to the virt-handler.
This commit fix it by decorating the resync
domain info, with the Guest Agent information,
as the virt-launcher itself does before sending
the domain info to the virt-handler.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1907707
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …
> [release-0.36] virt-launcher, Fix flaky VMI report

- tests/storage/restore.go
The test keeps failing due to different problems
with a print "resized successfully" being printed
unexpectedly (which is due the fact that the test is with block mode).
The origin fix was trying to expect for that print -
make sure the action occurred and only then continue
to the actual test, this doesn't seem to work by weird
logging behavior in the CI only.
The block mode was added because previously the default PVC fs was xfs,
Now the default fs is ext4 so no need for the block mode
which causes the problematic print.
Fixes #
**Special notes …
> fix quarantine test by changing it to run without block mode

- pkg/virt-handler/vm.go
> Fix typo in function name

- api/openapi-spec/swagger.json
- cmd/virt-launcher/virt-launcher.go
- manifests/generated/kv-resource.yaml
- pkg/host-disk/host-disk.go
- pkg/host-disk/host-disk_test.go
- pkg/virt-config/config-map.go
- pkg/virt-config/config_test.go
- pkg/virt-config/virt-config.go
- pkg/virt-controller/services/template.go
- pkg/virt-controller/services/template_test.go
- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Signed-off-by: Marcus Sorensen <marcus_sorensen@apple.com>
This allows the administrator of kubevirt to specify a minimum amount of 'reserve' space when KubeVirt automatically creates a 'disk.img' file on an empty PVC. The existing process for shrinking the size of disk.img and allowing for a tolerance of requested vs actual size remains intact, and if there is more than enough space for the requested volume then it is fulfilled exactly as requested.
It was found that some PVCs (namely those formatted XFS, but perhaps others), require a minimal amount of user 'available' space in order to do things like selinux relabeling, and the disk.img as sized to 'available' per `stat` can never actually grow to the full available space. The result is the VM …
> Allow for configurable minimum PVC reserve bytes, default to 128k

- pkg/virt-handler/vm.go
- pkg/virt-handler/vm_test.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- tests/migration_test.go
Fix [Bug 1945589](https://bugzilla.redhat.com/show_bug.cgi?id=1945589).
This PR add a new check to the computing of the LiveMigratable condition in the VMI status, and change the status to False if the VMI uses the virtiofs.
VMIs using virtiofs can't be live migrated, but trying migrating them returns no error. This PR prevents the migration of these VMIs.
Fixes Bugzilla bug 1945589: https://bugzilla.redhat.com/show_bug.cgi?id=1945589
```release-note
Fix bug 1945589: Prevent migration of VMIs that uses virtiofs
```
> Prevent migration of VMIs that uses virtiofs

- cmd/virt-handler/virt-handler.go
- pkg/monitoring/vms/prometheus/BUILD.bazel
- pkg/monitoring/vms/prometheus/prometheus.go
> Cherry pick 5269 to release 0.35

- pkg/virtctl/imageupload/BUILD.bazel
Run the imageupload unittests in 4 seconds instead of 30 seconds.
Fixes #
```release-note
NONE
```
> Run imageupload unit-tests in parallel

- BUILD.bazel
- Makefile
- hack/bazel-build-image-bundle.sh
Adds a bazel target `bazel build //:virt-components-bundle.tar` that results in a tar archive of the core virt-* images. I've found having a portable bundle for the release handy for my own external CI/CD processing use case.  The Makefile target isn't strictly necessary for me, but it was added in case others find it useful.
```release-note
New build target added to export virt-* images as a tar archive.
```
> Bazel target to build image bundle for external processing

- Makefile
- hack/build-go.sh
- hack/build-manifests.sh
- hack/config-default.sh
- pkg/virt-operator/resource/generate/components/daemonsets.go
The PR includes several fixes for native Go build (without Bazel):
- drop deprecated `-i` go build flag (to suppress warning)
- fix inconsistent path for node-labeler.sh (issue https://github.com/kubevirt/kubevirt/issues/5602)
- allow linux-only builds of virtctl (without windows and darwin)
- allow using go build for the templator when generating the manifests
Fixes #5602
```release-note
NONE
```
> Fix native go build

- pkg/virt-launcher/virtwrap/network/podinterface.go
Also rename SlirpSpecGenerator to SlirpLibvirtSpecGenerator
BindMechanism concept has being splitted, this change rename the part libvirt at virt-launcher as LibvirtSpecGenerator.
Fixes #
```release-note
NONE
```
> Rename BindMechanism to LibvirtSpecGenerator

- pkg/virt-launcher/notify-client/client.go
Fixes #5859
We might to this also with libvirt re-connections.
```release-note
Fix: ioerrors don't cause crash-looping of notify server
```
> Don't send watch error when ioerror occurs

- README.md
Moves the build badge from using Travis CI (which is no more in use for builds against the default branch) to use a prow badge based on `push-kubevirt-main` from https://prow.ci.kubevirt.io.
Fixes #5821
```release-note
NONE
```
> Set build badge to use kubevirt prow ci

- tests/migration_test.go
This PR is a continuation of the last PR (https://github.com/kubevirt/kubevirt/pull/5714) to take test 5004 out of quarantine.
Seems that the `stress` command fails on OOM. This is probably due to the fact the fedora images are always increase in size while our memory request (which is currently `1Gi`) stays as is.
There is no reason to use this much memory. 400 Mbs should be enough in order for post-copy to appear, especially when we set our seconds per Gigabyte to `1` in the tests (which means that the total time this migration needs to hang is maximum 1-2 seconds).
```release-note
NONE
```
> [migration_test]: decrease stressLargeVMSize to 400M

- tests/migration_test.go
This PR (https://github.com/kubevirt/kubevirt/pull/5895) got merged before I got the chance to remove quarantine. Let's get the quarantine back and wait for 14 days to see that test doesn't fail in periodics.
```release-note
NONE
```
> Quarantine test 5004. Remove if not failing periodics for 14 days

- pkg/virt-handler/isolation/validation.go
This fix is for newer versions of golang(1.14+) which seems to allocate more memory for exec.
Fixes #
```release-note
Fix: Kubevirt build with golang 1.14+ will not fail on validation of container disk with memory allocation error
```
> [release-0.41]Increase memory for validation of container disk

- automation/test.sh
- tests/BUILD.bazel
- tests/migration_test.go
- tests/storage/BUILD.bazel
- tests/storage/datavolume.go
- tests/storage/events.go
- tests/storage/hotplug.go
- tests/storage/imageupload.go
- tests/storage/restore.go
- tests/storage/snapshot.go
This PR enables `rook-ceph-default` coming with kubevirtci and focusses all sig-storage **and** rook-ceph tests for the sig-storage lanes (i.e. `TARGET=k8s-1.19-sig-storage`).
It also moves a test into `tests/storage` folder and removes a duplicate sig label.
Fixes #
```release-note
NONE
```
> Run rook ceph together with sig storage

- cmd/virt-handler/virt-handler.go
- pkg/monitoring/vms/prometheus/BUILD.bazel
- pkg/monitoring/vms/prometheus/prometheus.go
> Cherry pick 5269 to release 0.36

- hack/prom-rule-ci/prom-rules-tests.yaml
- pkg/virt-operator/resource/generate/components/crds.go
Adding severity label to each KubeVirt alert rule.
Fixes #
```release-note
NONE
```
> Add severity to KubeVirt alerts

- pkg/network/infraconfigurators/bridge.go
- pkg/network/infraconfigurators/common.go
- pkg/network/infraconfigurators/macvtap.go
- pkg/network/infraconfigurators/masquerade.go
- pkg/virt-launcher/virtwrap/network/network_test.go
- pkg/virt-launcher/virtwrap/network/podinterface.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
This PR renames some of the different `PodNetworkInfraConfigurator` implementing structs parameters to less generic names.
For example - `iface` -> `vmiSpecIface`.
It also removes from the struct parameters that are never used or can be calculated next to their usage.
Fixes #
Rebased on top of https://github.com/kubevirt/kubevirt/pull/5630
```release-note
NONE
```
> PodNetworkInfraConfigurator params renaming and redundantcy removal

- api/openapi-spec/swagger.json
- manifests/generated/kv-resource.yaml
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Make https://kubevirt.io/api-reference/master/definitions.html#_v1_pcihostdevice easier to understand.
@vladikr is this the place to add this content?
```release-note
NONE
```
> openapi: add description for PciHostDevice properties

- go.mod
- pkg/virt-controller/services/template.go
- pkg/virt-controller/watch/vmi.go
- pkg/virt-controller/watch/vmi_test.go
- pkg/virt-handler/hotplug-disk/BUILD.bazel
- pkg/virt-handler/hotplug-disk/findmnt.go
- pkg/virt-handler/hotplug-disk/findmnt_test.go
- pkg/virt-handler/hotplug-disk/mount.go
- pkg/virt-handler/hotplug-disk/mount_test.go
- tests/storage/hotplug.go
- vendor/modules.txt
The PR modifies the hotplug code to recreate the attachment pod with the current number of hotplug volumes in it. Instead of one pod per volume. This reduces the number of extra pods used by the hotplug system to 1 instead of N.
Fixes #
```release-note
Enhancement: remove one attachment pod per disk limit
```
> Flip flop attachment pod

- tests/operator_test.go
https://search.ci.kubevirt.io/?search=test_id%3A3145&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
The update test is timing out occasionally in the AFterEach function when restoring the orignal KV object. Lets see if increasing the timeout helps. 
```release-note
NONE
```
> Increase timeout when restoring the kubevirt object during func tests

- pkg/virt-handler/heartbeat/heartbeat_test.go
When the system is under load the initially chosen timeout of 1s may not be enough to hit 100 probes (having 1 probe per each 10ms).
The PR should fix the flaky heartbeat unit-test `Heartbeat without deviceplugin and becoming ready after a few probes, node should be set to unschedulable immediately and switch earlier than one minute`
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5914/pull-kubevirt-unit-test/1407998911380983808
Fixes #5753, fixes #5930
```release-note
NONE
```
> Fix flaky heartbeat test: increase device plugin wait timeout

- automation/test.sh
dockerized bazel shutdown was failing on several builds:
https://search.ci.kubevirt.io/?search=Usage%3A+bazel+%3Ccommand%3E+%3Coptions%3E&maxAge=336h&context=3&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
```release-note
NONE
```
> Remove bazel shutdown on automation/test.sh

- pkg/virt-controller/watch/workload-updater/BUILD.bazel
- pkg/virt-controller/watch/workload-updater/workload-updater.go
- pkg/virt-controller/watch/workload-updater/workload-updater_test.go
This removes a bunch of complicate logic for rate limiting a work queue. The logic is replaced by the standard queue rate limiting logic. 
```release-note
NONE
```
> Replace custom reconcile throttler with standard rate limit logic

- api/openapi-spec/swagger.json
- cmd/virt-handler/virt-handler.go
- manifests/generated/kv-resource.yaml
- pkg/virt-config/config-map.go
- pkg/virt-handler/migration-proxy/BUILD.bazel
- pkg/virt-handler/migration-proxy/migration-proxy.go
- pkg/virt-handler/migration-proxy/migration-proxy_test.go
- pkg/virt-handler/vm_test.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
- tests/migration_test.go
Sometimes getting the best performance is more important than encrypted migrations. For these rare cases, allow disabling migrations by setting `spec.migrations.disableTLS` to `true` to do migrations without TLS encryption.
Fixes #
```release-note
Add `spec.migrations.disableTLS` to the KubeVirt CR to allow disabling encrypted migrations. They stay secure by default.
```
> Allow disable tls for migrations in case getting the last bits of performance matters

- tests/storage/storage.go
It seems like those tests were flaky because they can't run in parallel.
Re-enabling them but in serial this time.
Fixes #
```release-note
NONE
```
> Re-enable a couple of storage tests

- pkg/controller/controller.go
- pkg/virt-controller/watch/replicaset.go
- pkg/virt-controller/watch/vm.go
- pkg/virt-controller/watch/vmi.go
- pkg/virt-handler/vm.go
A long time ago VMIs were called VMs, and the concept of a persistent and ephemeral virtual machine didn't exist. When we introduced the VMI object, a lot of code had to be split to account for what was essentially the rename of the existing VM object to a VMI. Some references never got updated, which I've found confusing.
This addresses those instances where we are not clearly separating a VM and VMI through our naming conventions. 
```release-note
NONE
```
> Minor code cleanups left over from transition to VMI and VM

- hack/parse-shasums.sh
**What this PR does / why we need it**: Now `hack/build-manifests.sh` is generating manifests without docker prefix in the deployment spec image property. These changes fix it by preventing the `manifest_docker_prefix` environment variable to be overridden by a sourcing `hack/config.sh` twice during the script execution.
Fixes #5950
```release-note
NONE
```
/cc @rmohr @ormergi @oshoval
> Prevent unset of manifest_docker_prefix

- hack/functests.sh
Currently the e2e tests run in two phases:
1. [the parallel tests run](https://github.com/kubevirt/kubevirt/blob/main/hack/functests.sh#L71)
2. [the serial tests run](https://github.com/kubevirt/kubevirt/blob/main/hack/functests.sh#L73)
Now, whenever the parallel tests have failures, the serial tests are not executed. This is especially more likely when run with QUARANTINE flag set, as those tests are more likely to fail (otherwise they wouldn't be in quarantine).
As an example please compare these two runs of the same job:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-sig-storage/1409743611955777536 (103 tests executed in total)
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k …
> Introduce KUBEVIRT_E2E_RUN_ALL_SUITES to continue serial tests

- pkg/virt-controller/services/template.go
Instead of using label selectors to make sure the attachment pod is on the same node as the virt-launcher, use a node selector instead, we know which node the virt-launcher is on before starting the attachment pod.
Fixes #
```release-note
NONE
```
> Use node affinity instead of label affinity for attachmentpod

- cmd/virt-handler/virt-handler.go
- pkg/monitoring/vms/prometheus/BUILD.bazel
- pkg/monitoring/vms/prometheus/prometheus.go
> Cherry pick 5269 to release 0.39

- cmd/virt-handler/virt-handler.go
- pkg/monitoring/vms/prometheus/BUILD.bazel
- pkg/monitoring/vms/prometheus/prometheus.go
> Cherry pick 5269 to release 0.38

- pkg/virt-handler/isolation/validation.go
This fix is for newer versions of golang(1.14+) which seems to allocate more memory for exec.
Fixes #
```release-note
Fix: Kubevirt build with golang 1.14+ will not fail on validation of container disk with memory allocation error
```
> [release-0.36]Increase memory for validation of container disk

- cmd/virt-handler/virt-handler.go
- pkg/monitoring/vms/prometheus/BUILD.bazel
- pkg/monitoring/vms/prometheus/prometheus.go
> Cherry pick 5269 to release 0.37

- WORKSPACE
Pull in protoc the right way, so that we can use a released binary
instead of compiling protoc ourselves on every branch switch.
This saves quite some compile time during local development.
Fixes #
For more context see https://github.com/bazelbuild/rules_scala/pull/1142 and https://github.com/bazelbuild/rules_proto/pull/36
```release-note
NONE
```
> Use precompiled protoc

- hack/build-func-tests.sh
**What this PR does / why we need it**: Currently the build targets in https://github.com/kubevirt/kubevirt/blob/main/hack/build-func-tests.sh create binaries for `$ARCHITECTURE`, this doesn't work when cross-compiling, we need to use instead `$HOST_ARCHITECTURE`.
Fixes #
```release-note
NONE
```
> Fix test binary build targets for cross-compiling

- docs/hotplug.md
There is a note in the documentation indicating one pod per hotplugged disk. Now that #5649 is merged, this is no longer true, its a single pod for all disks now. This PR removes the note in the documentation.
Fixes #
```release-note
NONE
```
> Remove note about one pod per disk hotplug

- pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
- pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
manual backport of the primary fix and unit test for #5849
This backport focuses only on the segfault and targeted unit test and does not include the other unit test enhancements #5849 introduced.
```release-note
```
> [release-0.34] fix pdb controller segfault 

- CONTRIBUTING.md
Currently, membership guidelines pointing to the outdated readme. We need to update it.
Fixes #
```release-note
```
> Fix membership guidelines link

- api/openapi-spec/swagger.json
- manifests/generated/kv-resource.yaml
- pkg/virt-config/virt-config.go
- pkg/virt-controller/services/template.go
- pkg/virt-controller/services/template_test.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
- tests/BUILD.bazel
- tests/utils.go
- tests/vmi_configuration_test.go
Allows administrator to specify a runtimeClassName for virt-launcher pods.
Fixes #5754 
```release-note
KubeVirt CR supports specifying a runtime class for virt-launcher pods via 'launcherRuntimeClass'.
```
> Configurable runtimeClassName for virt-launcher

- manifests/testing/rbac-for-testing.yaml.in
rbac.authorization.k8s.io/v1beta1 has been deprecated
Fixes #
```release-note
NONE
```
> manifests: use rbac.authorization.k8s.io/v1 instead of v1beta1

- pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
- pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
manual backport of the primary fix and unit test for #5849
This backport focuses only on the segfault and targeted unit test and does not include the other unit test enhancements #5849 introduced.
```release-note
```
> [release-0.36] fix pdb controller segfault 

- docs/getting-started.md
Just a small update for the `getting-started` guide. After doing `make && make push` I was still having old images deployed in my test cluster. I think it worth to mention in the docs that the manifests should be rebuilt.
Bazel push images creates digest files in
bazel-bin/push-<image-name>.digest
The SHA sums are taken from those files and if the manifests are not regenerated after pushing they will contain the old sums.
```release-note
NONE
```
> docs: Generate manifests after push images

- tests/console_test.go
- tests/migration_test.go
- tests/vm_test.go
As we have put together `rook-ceph` and `sig-storage` we need to add labels to existing tests that require rook-ceph to avoid skipping them.
Fixes #
/cc @maya-r @awels @rmohr 
```release-note
NONE
```
> Label remaining tests as rook-ceph to include them in sig-storage

- tests/vmi_configuration_test.go
Fixes flaky test where the test probably fails due to memory full
One of the logs for debug: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sig-compute/1409960067964342272
```release-note
NONE
```
> Fix flaky cpu test

- tests/operator_test.go
Signed-off-by: Simone Tiraboschi stirabos@redhat.com
On operator tests executed on periodics lanes
we sporadically still see some flakiness while
patching deployments or other objects.
We are not able to identify a reasonable
cause and we think it's just a matter of
short timings.
Fixes: test 3150 was still in quarantine
NONE
```release-note
NONE
```
> Increase timeouts for operator tests

- pkg/virt-api/rest/subresource.go
- pkg/virt-api/rest/subresource_test.go
- tests/vm_test.go
Allow Failed VM's to be stopped if `--force --gracePeriod 0` was used to stop it. Also update error messages to be more clear on errors in the case of the VM being unable to be stoped. 
I also added some tests around the new work flow and updated the "Halted" VM unit test since it was testing the wrong thing. 
Fixes #
```release-note
Allow Failed VMs to be stopped when using `--force --gracePeriod 0` 
```
> Update stop vm responses

- tests/template_test.go
BeforeEach got the containerdisk as parameter before commandline
arguments were parsed. Therefore the tag of the containerdisk was empty
in the template task.
Fixes #
Fixes issues like this in some test environments:
```
Failed to apply default image tag \"/fedora-cloud-container-disk-demo:\": couldn't parse image reference \"/fedora-cloud-container-disk-demo:\": invalid reference format"
```
```release-note
NONE
```
> Resolve containerdisk after initialization in template tests

- pkg/cloud-init/cloud-init.go
- tests/vmi_cloudinit_test.go
For e2e tests we generate the path where we can find the cloud-init iso.
Only set the expected path on the cloud-init package without trying to
create the path structure.
We don't see this in our CI tests because in the CI cluster, the test binary has the right to execute the path in question.
On other CI systems where the permission is not given, we just got an error which we ignored which lead to wrongly constructed paths.
This is a test-only issue.
Fixes #5973 
```release-note
NONE
```
> Generate cloud-init paths without creating directories

- tests/vmi_configuration_test.go
Instead of enabling the hostdisk featurgate in some tests, we should
skip them if the surrounding environment decided to disable it. Our
default test-setup enables it already, if desired.
Fixes issues in some test environments which don't want to run hostDisk based tests.
Fixes #
```release-note
NONE
```
> If the hostDisk feature gate is not enabled, skip tests

- hack/dockerized
There is an issue with _out directory being root-owned
when building the Kubevirt project for the first time on
a clean environment.
The root cause is that we don't explicitly create the
_out directory, leaving it to be done by rsync during the
sync out procedure. Therefore rsync creates the _out directory
with incorrect ownership, thus _out become root-owned.
Proposed solution is just to explicitly create the OUT_DIR
in case SYNC_OUT is turned on.
```release-note
NONE
```
> [automation] fix root owned _out directory issue

- hack/check-unassigned-tests.sh
add [sig-performance] label as possible assigned test
Fixes #5835
```release-note
NONE
```
> hack: add [sig-performance] label as possible asigned test

- pkg/virt-controller/services/template.go
- pkg/virt-controller/services/template_test.go
- tests/security_features_test.go
- tests/utils.go
CRIs have different sets of default capabilities.
There is also always an option that CRI can be configured by an administrator
of Kubernetes cluster or operator deployed in cluster.
Therefore let's explicitly request net_bind_service where it is required.
```release-note
None
```
> Require net_bind_service capability

- pkg/monitoring/workqueue/prometheus/prometheus.go
- pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
- pkg/virt-controller/watch/drain/evacuation/evacuation.go
- pkg/virt-controller/watch/migration.go
- pkg/virt-controller/watch/node.go
- pkg/virt-controller/watch/replicaset.go
- pkg/virt-controller/watch/snapshot/restore_base.go
- pkg/virt-controller/watch/snapshot/snapshot_base.go
- pkg/virt-controller/watch/vm.go
- pkg/virt-controller/watch/vmi.go
- pkg/virt-controller/watch/workload-updater/workload-updater.go
- pkg/virt-handler/node-labeller/node_labeller.go
- pkg/virt-handler/vm.go
- pkg/virt-operator/kubevirt.go
Today, KubeVirt has already some logic to expose the workqueue metrics to Prometheus
However, those metrics are not been exposed. It is missing some additional configurations to properly work.
- we must set the kubevirt namespace
- the name parameter of the functions that enable the metric should be used as the metric labels
- the metrics queue_duration_seconds and work_duration_seconds should be histograms
- workqueues cannot have empty names, otherwise the metrics are not exposed, see [here](https://github.com/kubernetes/client-go/blob/master/util/workqueue/metrics.go#L231).
Fixes #6012 …
> [Sig-scale] Expose workqueue metrics to Prometheus

- pkg/virt-launcher/virtwrap/live-migration-source.go
- pkg/virt-launcher/virtwrap/manager_test.go
Removing the whole kubevirt metadata bloc on migration can cause issues with existing code.
This PR limits the removal to only the migration section.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1966903
```release-note
NONE
```
> migration: only remove migration-specific metadata from libvirt XML

- pkg/virt-launcher/virtwrap/converter/numa_placement.go
- pkg/virt-launcher/virtwrap/converter/numa_placement_test.go
The NUMA mapping code did some miscalculations when it came to mapping memory to hugepages per node. Instead of just doing all calculations with bytes, the memory was converted to MiB. The conversion function had rounding issues which led to undividable MiB numbers.
For instance setting a memory of `2780Gi` led to this calculation:
```
requested memory can't be divided through the numa page size: 2846719 mod 1024 != 0
```
The issue is that `2780Gi` should be `2846710` and not `2846719`. Doing everything with bytes removes these round errors.
Fixes #
**Release …
> Fix rounding errors for NUMA memory allocation

- pkg/virt-config/config_test.go
- pkg/virt-config/virt-config.go
- pkg/virt-handler/vm_test.go
- pkg/virt-launcher/virtwrap/converter/converter.go
- pkg/virt-launcher/virtwrap/converter/converter_test.go
- pkg/virt-launcher/virtwrap/live-migration-source.go
- tests/migration_test.go
Set the boolean which makes the bandwidth limitation for migrations effective. In order to not break assumptions on existing installations the current default limit of 64Mi is removed and replaced with "unlimited" bandwidth.
The bandwidth limitation option for migrations was completely ignored before.
Further better define the function boundaries. The old implementation was quite
fuzzy in a few aspects:
* 0.9999 Mi was rounded to 0, while 1Mi is obviously the desired value.
* 0.1111 Mi was rounded to 0, while 0Mi would either mean no progress
or unlimited (was undefined).
* 5.9999 Mi was rounde to 5 while 6Mi is much more likely the intent.
Now the behaviour for the bandwidth calculation will be like this:
* A `0` quantity (`0` or `0Mi`, ...) means …
> Fix the bandwidth limitation option for migrations

- pkg/virt-operator/resource/generate/components/secrets_test.go
According to
https://search.ci.kubevirt.io/?search=should+set+the+notAfter+on+the+certificate+according+to+the+supplied+duration&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
there were a couple of failures where the specified interval on the
check was not sufficient. To give it more room we extend it to be ten
seconds now.
Failures:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5902/pull-kubevirt-unit-test/1413409469940895744
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5979/pull-kubevirt-unit-test/1413400102554308608
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5943/pull-kubevirt-uni …
> Fix flaky secrets certificate test

- pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
- pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
Manual backport for #5849  Backport the segfault fix and unit test and does not include the other unit test enhancements #5849.
```release-note
```
> [release-0.35] fix pdb controller segfault 

- pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
- pkg/virt-launcher/virtwrap/network/dhcp/dhcp_test.go
Router Option must be at least 4 octect long [0]
Classless Route Option has minimum length 5 bytes [1]
Setting these options with empty zero length values leads to sending
currupted DHCP Offer, which is rejected by Windows DHCP clients.
This commit adds checks for non-zere length of these option values so
that DHCP server doesn't produce invalid data.
[0] https://datatracker.ietf.org/doc/html/rfc2132#section-3.5
[1] https://datatracker.ietf.org/doc/html/rfc3442
Fixes #
```release-note
Fix …
```
> network, dhcp: Check for empty DHCP Routers and static routes options

- pkg/virt-controller/watch/vmi.go
- pkg/virt-controller/watch/vmi_test.go
- pkg/virt-handler/vm.go
During VMI startup, our control plane causes around 2-4 http 409 errors per a VMI while attempting to perform an "Update" on a VMI object that is not up to date. 
For example, here's a grafana graph capturing these errors during the startup of 15 VMIs in my dev environment
The issue appears to be caused by our controllers not waiting to observe a VMI update has occurred before attempting to issue a new Update. This occurs due to other informers (like the pod and domain informers) queuing the VMI on our controllers before the VMI's informer has completely caught up.
It seems like this collision would be a rare occurrence, but the way the timing works out these collisions actually occur nearly every time a VMI is posted.
This PR addresses this …
> Reduce VMI Update Collisions

- tests/storage/events.go
- tests/storage/imageupload.go
- tests/storage/restore.go
- tests/vm_watch_test.go
**What this PR does / why we need it**: 
Puts flaky tests in quarantine:
* `[sig-storage] [Serial]ImageUpload [rook-ceph] Upload an image and start a VMI with PVC [test_id:4621] Should succeed DataVolume/PVC`, 
* flakefinder report: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-07-07-168h.html#row17 and https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-07-07-168h.html#row18
* recent failures:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-sig-storage/1412884189392408576
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-sig-storage/1412642545032237056
* …
> Quarantine sig-storage and sig-compute tests

- tests/storage/hotplug.go
Most failures are because of:
```
"message": "Error: container create failed: time=\"2021-07-03T13:40:59Z\" level=warning msg=\"exit status 1\"\ntime=\"2021-07-03T13:40:59Z\" level=error msg=\"container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting \\\"/var/lib/kubelet/pods/8aab0b65-20f4-4159-b498-8218ca1133e1/volumes/kubernetes.io~empty-dir/hotplug-disks\\\" to rootfs at \\\"/path\\\" caused: stat /var/lib/kubelet/pods/8aab0b65-20f4-4159-b498-8218ca1133e1/volumes/kubernetes.io~empty-dir/hotplug-disks: no such file or directory\"\n"
```
Which suggests we are running out of tempDir space. I am unable to reproduce locally which
is running serial. So seeing of making the test run serially will make a difference. …
> Take "Should be able to add and remove and re-add multiple volumes out of quarantine"

- tests/vm_watch_test.go
This PR attempts to fix the [flaky](https://search.ci.kubevirt.io/?search=VmWatch) [VmWatch test](https://github.com/zcahana/kubevirt/blob/ecaaf34277a5a4361426125ba5f371b6678ac52f/tests/vm_watch_test.go#L144) which has been intermittently failing since #5675.
The current failure message don't provide much info as to why a timeout has reached, but the flakiness of this suggests that this is a timing issue (e.g., slow machines on test cluster).
Hence, this PR will:
- Increase the timeout waiting for VM/VMI status change from 5min to 10min.
- Augments the "timeout reached" error message with some additional info for better debuggability.
```release-note
NONE
```
> Attempt to fix flaky VmWatch test

- tests/BUILD.bazel
- tests/utils.go
It turns out that `DoScaleDeployment` and `DoScaleVirthandler` functions aren't consumed anymore, thus
cleaning them up from `tests/utils.go`
```release-note
NONE
```
> [tests] remove unused functions from utils.go

- Makefile
This command does not work as there is not, and never has been a `./hack/verify-deps.sh` script. The PR that added this command did not include the script file https://github.com/kubevirt/kubevirt/pull/4703/files. 
Fixes #
```release-note
NONE
```
> remove bad make verify-deps command

- pkg/virt-handler/cache/BUILD.bazel
- pkg/virt-handler/cache/maps.go
- pkg/virt-handler/vm.go
- pkg/virt-handler/vm_test.go
Currenctly all the VMIs are serialized at a mutex once per vmi+interface
at virt-handler, this change uses a sync.Map that will not serialize on
disjoint keys.
Fixes #
```release-note
NONE
```
> Use sync.Map for podCacheInterface

- pkg/virt-controller/watch/vm.go
- pkg/virt-controller/watch/vm_test.go
Have DataVolumes follow the priority class of the VM they
are associated with. We still allow different priority class
to be defined in the datavolume templates.
DataVolumes now pass PriorityClass to the transfer pods, but we want them to have the same priority class as the VMs. This PR will copy of the PriorityClassName from the VM to the created DVs if the DataVolumeTemplate does not define it, and the VM priority class is set.
Fixes #
```release-note
DataVolumes created by …
```
> Set DV priority class if VM priority class is set.

- pkg/controller/conditions.go
- pkg/controller/conditions_test.go
- pkg/virt-controller/watch/BUILD.bazel
- pkg/virt-controller/watch/vm.go
- pkg/virt-controller/watch/vm_test.go
- pkg/virt-controller/watch/vmi.go
- pkg/virt-controller/watch/vmi_test.go
- pkg/virt-operator/resource/generate/components/crds.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- tests/kubectl_test.go
- tests/vm_test.go
- tests/vm_watch_test.go
- tests/vmi_configuration_test.go
- tests/vmi_lifecycle_test.go
Add a `READY` column to the tabular output of `kubectl get vm` and `kubectl get vmi`, indicating the readiness condition of the VMI.
Here's how the output looks now:
```sh
zvic@ZVICAHANA-D2LK:~$ kubectl get vm
NAME     AGE   STATUS    READY
cirros   30s   Running   True
zvic@ZVICAHANA-D2LK:~$ kubectl get vmi
NAME     AGE   PHASE     IP            NODENAME   READY
cirros   37s   Running   10.244.0.74   minikube   True
zvic@ZVICAHANA-D2LK:~$ kubectl get vmi -o wide
NAME     AGE   PHASE     IP            NODENAME   READY   LIVE-MIGRATABLE   PAUSED
cirros   39s   Running   10.244.0.74   minikube   True    True
```
1. ~Note the slight casing difference between the VM and VMI outputs. The VM column feeds from the …
> Expose VM/VMI readiness via a dedicated CLI column

- Makefile
- hack/perftests.sh
- tests/BUILD.bazel
- tests/performance/BUILD.bazel
- tests/performance/density.go
- tests/performance/framework.go
- tests/tests_suite_test.go
This PR adds support for performance tests to be the basis of both performance and scalability tests. 
More specifically, It enables the creation of density tests to run (e.g., scheduling in parallel 100, 200 ... 600 VMs), measuring the VM's creation time (from submission to Running Phase) and failing when the time is higher than a given threshold. 
For further analysis, the VMI's phase transition latency, the VMI resource usage, and the Kubevirt control plane resource usage are also collected and logged into a file. Note that, resource usage is only collected when Prometheus is available.
The test configuration is defined in a YAML file so that it can be easily adapted to different environments. For rate control during the creation process, it is …
> [SIG-scale] Add density performance tests to evaluate the Kubevirt control plane

- pkg/network/dhcp/configurator.go
- pkg/network/dhcp/configurator_test.go
- pkg/network/dhcp/masquerade.go
- pkg/network/dhcp/masquerade_test.go
- pkg/network/driver/common.go
- pkg/network/driver/generated_mock_common.go
- pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
We shouldn't not pass MAC address to the masquerade DHCP server, it is redundant since the masquerade DHCP server is not filtering by MAC and the MAC value is not used by anything else.
Also -
The DHCP server has two fields -
```
clientMAC net.HardwareAddr,
filterByMAC bool,
```
There is no need to have both of them. Empty `clientMAC` is enough to indicate if there is no need filter by the MAC.
Fixes #
Rebased on top of https://github.com/kubevirt/kubevirt/pull/5902
```release-note
NONE
```
> virt-launcher,DHCP: Not passing MAC address to the masquerade DHCP server

- pkg/network/infraconfigurators/masquerade.go
This code removes an unused function from the masquerade infrastructure configurator; the same functionality is provided by 
https://github.com/kubevirt/kubevirt/blob/5083ee7b91bd25ce9186f0dc2d68322ee810d7c6/pkg/network/infraconfigurators/masquerade.go#L476
```release-note
NONE
```
> network, masquerade: remove dead code

- WORKSPACE
- tests/migration_test.go
The PR addresses [this issue](https://github.com/kubevirt/kubevirt/issues/6061).
```release-note
replace dead "stress" binary with new, maintained, "stress-ng" binary
```
> Replace dead "stress" binary with new, maintained, "stress-ng" binary

- hack/functests.sh
currently we can manage Ginkgo flags using the FUNC_TEST_ARGS
environment variable, but we couldn't manage the flags of our
own test suite defined in tests/flags.go now it can be possible
to manage them using the EXTRA_ARGS environment variable.
Controling EXTRA_ARGS will allow the user to manage the default
kubevirt e2e configuration.There are cases where Kubevirt deployment
is automated and managed by other operators, such as HCO.
In that case Kubevirt CR will be strictly reconciled to the one
defined in the HCO configuration. Therefore it doesn't make sense
to work with the e2e default configuration since it will be
immediately reconciled.
```release-note
NONE
```
> [tests] allow configuration of e2e tests extra args

- tests/reporter/kubernetes.go
Since parallel test execution is done in different processes,
we don't need to mutex anymore, its a leftover.
```release-note
None
```
> k8s reporter, Remove leftover mutex

- hack/ci/entrypoint.sh
Fixes the script that executes the tests on openshift-ci with KubeVirt versions. Seen here: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-4.8-e2e/1366222299895697408#1:build-log.txt%3A203
The binary pathes for the oc and kubectl binaries were wrong, possibly
due to overseen changes regarding downloading vs. injection. Fixed path
calculation.
Fixes #
/cc @maya-r thanks for the heads up :) 
/cc @rmohr as this script belongs to openshift ci I just created a draft, trying not to cause ci load. …
> Fix pathes for oc and kubectl binaries on openshift ci

- pkg/network/cache/types.go
- pkg/network/infraconfigurators/bridge.go
- pkg/network/infraconfigurators/common.go
- pkg/network/infraconfigurators/generated_mock_common.go
- pkg/network/infraconfigurators/masquerade.go
- pkg/virt-launcher/virtwrap/network/BUILD.bazel
- pkg/virt-launcher/virtwrap/network/podnic.go
- pkg/virt-launcher/virtwrap/network/podnic_test.go
Currently there are scenarios where the virt-launcher pod networking setup step can be executed multiple times, this is prevented by checking if the libvirt domain interface cache file is already stored since this happends after the networking setup step, this create a dependency between checking if the networking setup step has being executed and if the libvirt domain interfaces has being generated. To break this dependency the fact that the networking setup step has being done is reprenseted as a "state" field at pod interface yaml with the following values:
- **PodIfaceNetworkPreparationPending**: the virt-launcher networking setup has not being executed yet
- **PodIfaceNetworkPreparationFinished**: the virt-launcher networking setup has being …
> Prevent phase1 networking setup to run twice without using libvirt domain interface cache file

- tests/storage/datavolume.go
- tests/storage/restore.go
- tests/storage/storage.go
Quarantine flaky sig-storage tests:
* Full `[sig-storage] [Serial]DataVolume Integration Fedora VMI tests [rfe_id:5070][crit:medium][vendor:cnv-qe@redhat.com][level:component]fstrim from the VM influences disk.img` table, we already had 'test_id:5894` quarantined but the rest of entries are also failing a lot.
* flakefinder reports:
* https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-07-21-024h.html#row2 
* https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-07-21-024h.html#row6
* https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-07-21-024h.html#row7 …
> Quarantine sig-storage tests

- tests/reporter/kubernetes.go
Changes that were done:
1. Create needed folders (pods/nodes) only one time at the beginning.
2. Collect target list one time and reuse it in the info collectors.
3. Rearrange info collectors at Dump function by topic.
4. Update var name of `logVMs` from vmi to vm.
5. Add missing new lines in prints
This will ease extending the reporter.
No logical changes were done.
```release-note
None
```
> k8s reporter, Refactor info collectors

- pkg/virt-operator/resource/generate/components/scc.go
NET_BIND_SERVICE is right now explicitly requested to make the
requirement explicit. It needs to be added to the SCC too.
Fixes #
```release-note
Fix virt-controller SCC: Reflect the need for NET_BIND_SERVICE in the virt-controller SCC.
```
> Allow NET_BIND_SERVICE in the virt-controller SCC

- api/openapi-spec/swagger.json
- docs/hotplug.md
- pkg/controller/controller.go
- pkg/host-disk/host-disk.go
- pkg/util/types/pvc.go
- pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
- pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
- pkg/virt-controller/services/template.go
- pkg/virt-controller/watch/BUILD.bazel
- pkg/virt-controller/watch/application.go
- pkg/virt-controller/watch/application_test.go
- pkg/virt-controller/watch/migration.go
- pkg/virt-controller/watch/migration_test.go
- pkg/virt-controller/watch/vmi.go
- pkg/virt-controller/watch/vmi_test.go
- pkg/virt-handler/hotplug-disk/generated_mock_mount.go
- pkg/virt-handler/hotplug-disk/mount.go
- pkg/virt-handler/vm.go
- pkg/virt-handler/vm_test.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
- tests/storage/hotplug.go
Currently live migation of VMs with attached hotplug volumes is not implemented and it gets rejected by validation hook. This PR adds the missing pieces to enable it.
The PR is based on https://github.com/kubevirt/kubevirt/pull/5649 (which refactors hotplug disks implementation to use a single attachment pod for all volumes). Also it relies on the fix https://github.com/kubevirt/kubevirt/pull/5436. The logic is implemented as follows:
- For the migration with the status `MigrationPending` after creating the `virt-launcher` target pod, `virt-controller` checks if the VMI has hotplug volumes attached. In case if it does a new target attachment pod is created (with the target `virt-launcher` pod set as owner).
- …
> Enable live migration of VMs with hotplug volumes

- pkg/network/infraconfigurators/masquerade.go
Deletes duplicated function that sneaked in probably during rebase
Fixes #
```release-note
NONE
```
> network: delete duplicated function getEnvoyLoopbackAddress

- cmd/virt-launcher/BUILD.bazel
- cmd/virt-launcher/virt-launcher.go
Specify a 10 second timeout when requesting istio proxy
to terminate to avoid possibility of virt-launcher hanging when the
15021 port is open but doesn't respond.
Fixes #
```release-note
NONE
```
> network: Add timeout to istio-proxy termination request

- pkg/network/infraconfigurators/bridge.go
- pkg/network/infraconfigurators/common.go
- pkg/network/infraconfigurators/masquerade.go
- pkg/virt-launcher/virtwrap/network/podinterface_test.go
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
This PR removes MTU link validation from the pod links.
It is redundant to check that the links read from the kernel have valid MTUs since you cannot create a link with an invalid MTU.
As such, I'm removing both the MTU and the test that assures it.
```release-note
NONE
```
> network: remove MTU link validation from the pod links

- pkg/network/infraconfigurators/masquerade.go
- pkg/virt-launcher/virtwrap/live-migration-source.go
- pkg/virt-launcher/virtwrap/manager.go
- tests/network/vmi_networking.go
Initiate live migration directly using the unix socket proxy
exposed by the 'source' virt-handler, there's no need to have an
additional tcp proxy that tunnels the data to the local virt-handler.
It simplifies live migration by removing an 'excess' tcp proxy started on the source virt-launcher and transferring data directly to the unix socket migration proxy on the source virt-handler.  
Fixes #
```release-note
Initiate Live-Migration using a unix socket (exposed by virt-handler) instead …
```
> live-migration: initiate migration using a unix socket

- pkg/virt-controller/watch/vmi.go
- pkg/virt-controller/watch/vmi_test.go
- tests/storage/datavolume.go
Don't delete temp pods that aren't associated with VMI;
We do not want to delete temporary pods that are not owned by the VMI.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1974289
```release-note
BugFix: Pending VMIs when creating concurrent bulk of VMs backed by WFFC DVs
```
> [release-0.41] Manual cherry pick of #5891

- OWNERS_ALIASES
Add @zcahana as a reviewer.
I've been working with the KubeVirt project for several months now, contributing mostly to the kubevirt and hyperconverged-cluster-operator sub-projects. I'd be happy to continue contributing as a reviewer in the project.
```release-note
NONE
```
> Add Zvi Cahana to reviewers

- cmd/virt-handler/virt-handler.go
In the recent [SIG-scale meeting](https://docs.google.com/document/d/1d_b2o05FfBG37VwlC2Z1ZArnT9-_AEJoQTe7iKaQZ6I/edit#heading=h.50eclt5fctl9), we are discussing to run a scale test with more than 110 VMIs per node. It is trivial to increase the max number of pods per node, but the max number of VMIs is not straightforward. 
Currently, `virt-handler` already have `max-devices` flag to increase the number of VMs per node
https://github.com/kubevirt/kubevirt/blob/0514a664151863d901d90694feb08c86df0076bb/cmd/virt-handler/virt-handler.go#L527 However, the `virt-handler` configuration is determined by the `virt-operator` that reverts all changes in the `virt-handler` Daemonset during the  strict-reconciliation.
This PR change `virt-handler` to detect the …
> configure virt-handler max-device with kubelet maxPods

- tests/infra_test.go
Test proved it's stability during the last 14 days. Therefore removing it from quarantine
```release-note
NONE
```
> Take test_id:4100 out of quarantine

- pkg/virt-controller/watch/vm.go
- pkg/virt-controller/watch/vm_test.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- tests/vm_test.go
This PR extends the VM status field (`.status.printableStatus`) with a new `FailedUnschedulable` status, reported when an error occurs while scheduling the virt-launcher pod for the VM.
This will typically indicate that the VM was configured with unsatisfiable resource requests (e.g., too much memory requested), or unsatisfiable scheduling constraints (e.g., invalid node selector, missing tolerations, ...).
Related PR inflight: #6078
```release-note
Report FailedUnschedulable VM status when scheduling errors occur
```
> Detect and report a FailedUnschedulable VM status

- tests/storage/restore.go
This PR fixes a race that can cause test 5257 to fail like in run: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6133/pull-kubevirt-e2e-k8s-1.21-sig-storage/1420271384948379648
The test might fail to update the vm spec because vm spec
cant be updated during vmsnapshot. The BeforeTest creates the snapshot and waits
for it to be ready and then updates the vm spec to running, but the create snapshot
function doesnt wait for the SnapshotInProgress in the vm status to be
changed back to nil and so the vm update fails.
Fixes # …
> fix racy check in test 5257

- hack/perftests.sh
The previous PR #6076 was missing the file to build and run the test.
Fixes #
```release-note
NONE
```
> [Sig-scale] add scripts to build and run performance density tests

- tests/reporter/kubernetes.go
Use virt-chroot mounting the node's mnt namespace,
this way `logDMESG` will work also on kind based providers,
while still not having a dependency on dmesg in the container.
```release-note
None
```
> k8s reporter, Use virt-chroot in logDMESG

- tests/vm_watch_test.go
Follow up PR to #6030 with another attempt to stabilize the [flaky](https://search.ci.kubevirt.io/?search=VmWatch) [VmWatch test](https://github.com/zcahana/kubevirt/blob/ecaaf34277a5a4361426125ba5f371b6678ac52f/tests/vm_watch_test.go#L144).
Based on [this failure](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-cgroupsv2/1416805188089417728#1:build-log.txt%3A5563), it appears that there isn't sufficient time for the VMI to get recreated - the allotted time (previously 1m, now 5m) should allow both for the deletion of the old VMI (which sometimes takes a while, or even completely hang as in #6037), and the creation of another one.
```release-note
NONE
```
> Increase VM creation timeout in VmWatch test

- pkg/cloud-init/cloud-init.go
- tests/vmi_cloudinit_test.go
Manual cherry-pick of #5990 
```release-note
NONE
```
> [release-0.41] Generate cloud-init paths without creating directories

- api/openapi-spec/swagger.json
- manifests/generated/kv-resource.yaml
- pkg/virt-operator/resource/apply/BUILD.bazel
- pkg/virt-operator/resource/apply/apps.go
- pkg/virt-operator/resource/apply/apps_test.go
- pkg/virt-operator/resource/apply/reconcile.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Allows the user to easily modify the number of VMIs they would like to run per node
Fixes #6082
```release-note
Add VirtualMachineInstancesPerNode to KubeVirt CR under Spec.Configuration
```
> allow users to set MaxDevices on KubeVirt CR

- cmd/virt-launcher/virt-launcher.go
- pkg/virt-launcher/monitor.go
- pkg/virt-launcher/monitor_test.go
Under high load, we've observed that libvirt does not always successfully reap the qemu processes, which leaves them around in a defunc (zombie) state, never cleaning them up. Arguably this is a bug in libvirt, but we can handle it a bit more gracefully on our end as well.
The result is, when this occurs the virt-launcher pod never shuts down because the qemu pid virt-launcher is monitoring never disappears.
Previously, our pid monitoring only checked for the presence of the qemu pid. Now we detect the pid's presence and whether or not the pid is a zombie. When a zombie pid is detected, we exit the monitor loop and raise SIGCHLD to pid 1 (virt-launcher). Virt-launcher already watches for SIGCHLD and will call wait() to reap the process.
related to: …
> Handle Zombie QEMU Processes

- cmd/virt-launcher/libvirtd.conf
- pkg/virt-launcher/virtwrap/util/libvirt_helper.go
Remove duplicated settings we forcibly write in libvirtd.conf and qemu.conf since they're already present in the shipped config files.
Disable libvirt unencrypted TCP socket since we only use the unix socket to communicate with the daemon.
Fixes #
```release-note
virt-launcher: disable unencrypted TCP socket for libvirtd.
virt-launcher: 'cgroup_controllers = [ ]' is not injected anymore at runtime and thus is a required setting in the image /etct/libvirt/qemu.conf file.
```
> virt-launcher: libvirt and qemu conf cleanup

- BUILD.bazel
- go.mod
- hack/bazel-build.sh
- tools/perfscale-audit/BUILD.bazel
- tools/perfscale-audit/api/BUILD.bazel
- tools/perfscale-audit/api/api.go
- tools/perfscale-audit/metric-client/BUILD.bazel
- tools/perfscale-audit/metric-client/metric-client.go
- tools/perfscale-audit/perfscale-audit.go
- vendor/github.com/prometheus/client_golang/api/BUILD.bazel
- vendor/github.com/prometheus/client_golang/api/client.go
- vendor/github.com/prometheus/client_golang/api/prometheus/v1/BUILD.bazel
- vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
- vendor/modules.txt
This PR introduces a new tool called `perfscale-audit` which can be used to generate a performance report over a specific time period. The tool aggregates information from prometheus over a specified time range and generates a JSON structured report. This can be used in combination with stress tests to establish baseline performance expectations and test if those performance expectations are met.
`perfscale-audit` takes in an input config, which represents how to connect to prometheus and a time range to gather results. Then the tool outputs a results file formatted in JSON.
Example: Run a stress test and capture the start and end times.
```
$ export start=$(date -u +%Y-%m-%dT%TZ)
$ ./my-stress-test.sh
$ echo "sleeping in order to let metrics scraping catch up
$ sleep 30
$ export …
```
> [Sig Scale] PerfScale Audit Tool

- cmd/virt-launcher/virt-launcher.go
This commit fixes a race condition that would cause a VMI compute
pod to exit and end up in an erroneous 'Failed' state even if actually
the pod terminated gracefully.
The race condition is caused by having 2 goroutines doing a wait() on
the same PID, while a fix existed already it was not covering the whole
critical section causing to the race to persist (just with a lower
failure rate).
One example of the race is the following:
The goroutine executing on the SIGCHLD signal handler completes the
Wait4() and is about to write the exit status on the channel
goroutine 1
```
case syscall.SIGCHLD:
var wstatus syscall.WaitStatus
wpid, err := syscall.Wait4(-1, &wstatus, syscall.WNOHANG, nil)
if err != nil {
log.Log.Reason(err).Errorf("Failed to reap process %d", wpid)
}
**EXECUTION HERE**
if …
```
> virt-launcher: fix exit pod race condition

- hack/release.sh
The release-tool was still being pulled from docker hub. new release tool builds are now in quay. 
```release-note
NONE
```
> use latest release-tool image from quay.io

- pkg/virt-handler/migration-proxy/migration-proxy.go
- pkg/virt-handler/rest/console.go
Due to a channel not being buffered, and not having a guaranteed read occur, it's likely that one of the proxy copy goroutines blocks indefinitely writing to a non buffered channel. This is fixed by making the channel buffered. We see something similar in the console code as well. 
Here's an example showing what i'm referring to. With the code below, we'll never see the `sent error` print statement
```
package main
import (
"fmt"
"time"
)
func main() {
errChan := make(chan error)
go func() {
fmt.Println("sending error")
errChan <- fmt.Errorf("err")
fmt.Println("sent error")
}()
fmt.Println("sleeping")
time.Sleep(100 * time.Second)
}
```
But with this code we will see the print statement.
```
package main
import (
"fmt"
"time"
)
func main() {
errChan := make(chan error, 1)
go func() { …
```
> Fix goroutine leaks due to use of non-buffered channels

- pkg/virt-launcher/virtwrap/util/libvirt_helper.go
Root is using /etc/libvirt/qemu.conf
$XDG_CONFIG_HOME/libvirt/qemu.conf is used only in non-root
Fixes #
```release-note
NONE
```
> Don't copy qemu.conf when running as root

- api/openapi-spec/swagger.json
- pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
- pkg/virt-controller/watch/snapshot/snapshot.go
- pkg/virt-controller/watch/snapshot/snapshot_test.go
- pkg/virt-controller/watch/snapshot/util.go
- pkg/virt-operator/resource/generate/components/crds.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/deepcopy_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types_swagger_generated.go
- tests/storage/snapshot.go
It adds a failure phase to the vm snapshot in case it takes more the defined deadline time
In such case we mark the vm snapshot as failed and clean as needed. This phase is irreversible. 
```release-note
Add phases to the vm snapshot api, specifically a failure phase
```
> Add VMSnapshot failure phase and deadline

- tests/network/vmi_istio.go
- tests/utils.go
The negative test checking that Envoy refuses to
connect to external service was missing .Should(Succeed())
so when we changed from using "kubevirt.io" as an external
service to another cluster vmi, the test was broken without
us knowing about it.
This commit properly registers the server vmi (there are two VMIs, server VMI without proxy 
sidecar and the tested client VMI which does have the proxy sidecar) as a service by defining
VirtualService, destinationRule and Gateway.
The vmi HTTP server is now accessed via Istio ingressgateway, and when 
Sidecar disallowing all external services is created, the Envoy proxy properly
refuses to forward the request.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …
> network, Istio: Fix outbound test

- pkg/virt-controller/services/template.go
- pkg/virt-controller/services/template_test.go
- pkg/virt-controller/watch/application.go
- pkg/virt-controller/watch/application_test.go
- pkg/virt-controller/watch/migration_test.go
- pkg/virt-controller/watch/vmi_test.go
In the recent SIG-scale meeting, we are discussing to run a scale test with more than 110 VMIs per node. 
It is trivial to increase the max number of pods per node, and PR#6098 increased the `virt-handler` max-device to 1000.
However, it is still not possible to create more than 200 VMIs in my environment, because of creating such amount of VMIs the creation process is slow and the `virt-launcher` `qemu` response timeout.
Currently, `virt-launcher` already have `qemu-timeout` flag:
https://github.com/kubevirt/kubevirt/blob/962aabb5f4816066c99b18993513abdca96fcf49/cmd/virt-launcher/virt-launcher.go#L341
However, `virt-launcher` is created and configured by `virt-controller` which does have a flag to configure the `qemu-timeout`.
This PR introduces …
> [SIG-scale] Add the possibility to configure virt-launcher qemu-timeout via virt-controller

- tests/migration_test.go
Once again trying to see if we can get test_id:5004 out of quarantine after these two PRs have been merged:
- https://github.com/kubevirt/kubevirt/pull/6007 which fixes bandwidth restrictions that is now used in the test
- https://github.com/kubevirt/kubevirt/pull/6062 which replaces `stress` with `stress-ng` that is now used in all functional migration tests.
```release-note
NONE
```
> Test test_id:5004 stability

- pkg/controller/conditions.go
- pkg/virt-controller/watch/vm.go
- pkg/virt-controller/watch/vm_test.go
- pkg/virt-controller/watch/vmi.go
- pkg/virt-controller/watch/vmi_test.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- tests/vm_test.go
This PR extends the VM status field (`.status.printableStatus`) with new `ErrImagePull`/`ImagePullBackOff` statuses, reported when an error occurs when pulling a container image for the VM.
This will typically indicate that one of the container disks of the VM has failed to be pulled, but may also indicate that there was an error pulling the virt-launcher image or one of its init container images.
This was implemented by first propagating the `ErrImagePull`/`ImagePullBackOff` container status from the virt-launcher pod, to the VMI conditions (Synchronized=False, Reason: `ErrImagePull`/`ImagePullBackOff`), and then from the VMI to the VM's status.
This approach involves additional updates to the VMI object. …
> Detect and report an ErrImagePull/ImagePullBackOff VM status

- tests/migration_test.go
**What this PR does / why we need it**: The test `VM Live Migration Starting a VirtualMachineInstance with bandwidth limitations should apply them and result in different migration durations ` is failing in some cases with this error:
```
tests/migration_test.go:426
Expected
<float64>: 30
to be <
<float64>: 30
tests/migration_test.go:434
```
Examples: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6145/pull-kubevirt-e2e-k8s-1.20-sig-compute-nonroot/1420355203323924480 and https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6150/pull-kubevirt-e2e-k8s-1.20-sig-compute/1422195208744865792
This PR changes the numerical comparator so that low bandwidth migrations with 30s …
> Decrease factor for high bandwidth duration in bandwith limited migration test

- cmd/virt-freezer/BUILD.bazel
- cmd/virt-freezer/main.go
- cmd/virt-launcher/BUILD.bazel
- pkg/virt-controller/services/template.go
- pkg/virt-controller/services/template_test.go
- tests/storage/snapshot.go
Signed-off-by: Tomasz Baranski <tbaransk@redhat.com>
Added virt-freezer binary to the launcher pod. Its job is to
freeze/unfreeze the VM from within the launcher pod (without going
through the KubeVirt API) for the sake of Velero backup hooks.
Appropriate annotations for Velero are also added to the launcher pod.
```release-note
NONE
```
> Added virt-freezer

- cmd/dump/dump.go
- tests/reporter/kubernetes.go
This PR replaces a function with a boolean argument with two properly-named functions.
Function calls with a boolean argument, such as `Dump(duration, true)` are hard to read and understand. I believe that `DumpAllNamespaces(duration)` is clearer
```release-note
NONE
```
> janitorial: avoid one boolean argument

- tests/console/login.go
LoginToFedora had a bug that in case of re-login,
where the previous command failed, but its return code
was not consumed yet, it will fail the loggedin check
and execute almost all the login flow again,
(for example reconfigure the console).
Scenario for example:
1. Login to the VM.
2. Run a command that returns error (don't use check its return code).
3. Try to relogin to the VM.
Since the relogin tried to check that `echo $?` returns 0,
it would fail in the above case, since that last command returned non zero value.
The send of `\n` just before it, doesn't consume the non zero return code.
```
~ $ false
~ $ 
~ $ echo $?
1
~ $ 
```
The result will be that the either the relogin will perform unneeded steps,
or even fail if the user was already logged in as sudo, since sudo has a …
> tests, Fix Relogin of fedora

- pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
- pkg/virt-controller/services/template.go
- pkg/virtctl/BUILD.bazel
- pkg/virtctl/configuration/BUILD.bazel
- pkg/virtctl/configuration/configuration.go
- pkg/virtctl/root.go
Since permitted host devices can be updated and changed we should not reject the creation of a VMI if its host device is not currently permitted. 
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=1983079
```release-note
Remove HostDevice validation on VMI creation
```
> move host device validation to happen on pod creation

- pkg/virt-operator/webhooks/BUILD.bazel
- pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go
Going over the unit tests I've noticed the following redundancy:
1. Due to [PR#5221](https://github.com/kubevirt/kubevirt/pull/5221) we don't restrict the modification
of Kubevirt CR pod placement configuration while VMs are running, therefore these scenarios:
- `should accept workload update when no VMIS are running`
- `should accept KV update with VMIS running if workloads object is not changed`
seems not relevant anymore.
2. We test twice the same scenario of rejecting invalid JSON patching format, [here](https://github.com/kubevirt/kubevirt/blob/1375bcdacde6781d3fb40f3e2ce111677421164d/pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go#L133) and …
> [virt-operator] remove duplicated and redundant unit tests from webhook test suite

- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
Needed to do a manual cherry-pick due to unit test failing https://github.com/kubevirt/kubevirt/pull/6193/files. 
The params for the function `NewLibvirtDomainManager` changed so I needed to remove the `ephemeralDiskCreatorMock` param from the func test call to that function. 
Fixes #
```release-note
Allow multiple shutdown events to ensure the event is received by ACPI
```
> [release-0.41] allow multiple calls to graceful shutdown in case acpi did not recieve call

- hack/cluster-clean.sh
The script iterates on all the vm resource types,
and removes the finalizers from them.
But it also override the global namespace variable
where it shouldn't because this variable is reused
by managed_namespaces in order to delete all managed namespaces.
Fix it by using another variable.
```release-note
None
```
> cluster-clean, Fix overriding namespace variable

- pkg/virt-operator/resource/generate/components/secrets.go
- pkg/virt-operator/util/config.go
The purpose of this PR is to eliminate the false positive complaints about "hardcoded credentials" from "make gosec". The said complaints contain the initialization of string variables whose variable-names contain key-words "Secret" and "Pass". The current over-conservatively defined rule 101 for "potential hardcoded credentials" is defined at https://securego.io/docs/rules/g101.html. 
Overall, there are 2 complaints with regard to the rule G101. The proposed solution is to add 2 comment lines with "#nosec G101" at 
- https://github.com/kubevirt/kubevirt/blob/2250bcba717fd52611724abb1815dd4abf214d25/pkg/virt-operator/resource/generate/components/secrets.go#L23
- …
> Fix false positive gosec complaints on hardedcoded credentials

- pkg/util/util.go
- pkg/virt-handler/vm.go
- pkg/virt-launcher/virtwrap/converter/converter.go
This PR fixes a bug in virt-handler that attempts to set the file ownership of `/dev/kvm` also when running in emulation mode with no KVM device. This results with a VMI stuck in `Scheduled` phase, and the following errors in virt-handler's logs:
```
{"component":"virt-handler","level":"info","msg":"Processing event default/cirros","pos":"vm.go:1549","timestamp":"2021-08-05T08:39:25.238640Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled\n","name":"cirros","namespace":"default","pos":"vm.go:1551","timestamp":"2021-08-05T08:39:25.238747Z","uid":"433d2b7c-02bf-4219-acb4-0ba63219f207"}
{"component":"virt-handler","level":"info","msg":"Domain does not …
```
> Avoid setting ownership for /dev/kvm in emulation mode

- pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
Previously, the phase transition timestamp slice never got an entry due to the Pending phase being set during the VMI creation webhook. To account for this, we need to initialize the pending transition timestamp in the mutation webhook along side setting the phase to pending.
Without this fix, our Prometheus metrics related to calculating transition timestamps can't capture the time spent between pending and scheduling. 
```release-note
NONE
```
> Fix setting vmi Pending phase transition timestamp

- tests/console/login.go
There is no need to let Cirros relogin logic wait 10
seconds for the prompt.
Most of the tests do not relogin, so its a waste of time.
Even in cases where there is need for relogin, 10 seconds is too much.
Reduce it to 5 seconds.
```release-note
None
```
> login, Decrease Cirros relogin timeout to 5 seconds

- pkg/host-disk/host-disk_test.go
Test  `Should refuse to create disk image if reserve causes image to exceed lessPVCSpaceToleration` should never expect an event to be sent. This PR fixes the tests to first fail the test and then fixes it.
Fixes #
```release-note
NONE
```
> Fix host disk unit test

- hack/prom-rule-ci/prom-rules-tests.yaml
- pkg/virt-operator/resource/generate/components/crds.go
Add runbook_url to alerts.
Fixes #
```release-note
This PR adds to each alert the runbook url that points to a runbook that provides additional details on each alert and how to mitigate it.
```
> Add runbook_url to alerts

- CODE_OF_CONDUCT.md
- SECURITY.md
to match supplied CNCF addresses.
Signed-off-by: Josh Berkus <josh@agliodbs.com>
Email addresses for project contacts have changed.
> Update the emails for security and conduct violations

- hack/dockerized
It seems like podman expects all volume source directories to exist, while docker maybe creates them?
Anyway, when using podman as a container runtime, I often run into the artifacts-is-missing error.
This PR fixes it.
Fixes #6259 
Use podman
```release-note
NONE
```
> dockerized: ensure artifacts directory exists before using it as a volume

- WORKSPACE
- pkg/cloud-init/cloud-init.go
- pkg/config/config.go
- tests/config_test.go
- tests/vmi_cloudinit_test.go
This is a backport of #5806 with some minor tweaks to make it work in the release v0.36 branch.
Fixes #
Take a look at the SetLocalDirectoryNoCreate function. I had to add this because calling SetLocalDirectory tries to create the passed in directory, and when running locally, the user had no permissions to actually create the directory. However the call to SetLocalDirectory was there just so we could build the path of where the cloudInit/noCloud images are stored in the virt-launcher container. Because of the failure to create the directory, the value was …
> [release-0.36] Backport #5806

- hack/cluster-clean.sh
The logic was not correct, it waited for the wrong variable.
Adjust parameters and fix logic.
```release-note
None
```
> cluster-clean, Fix wait for namespace to disappear logic

- tests/network/vmi_multus.go
Matching the interface based on the mac address and retrieving the IP
value blindly is not safe. Although the interface may be in place, the
IP address may appear a bit later.
Fix by continuing querying the VMI state for the IP until it appears.
Fixes #
```release-note
NONE
```
> tests, net, macvtap: Wait for a non-empty IP value

- pkg/network/domainspec/BUILD.bazel
- pkg/network/domainspec/domainspec_suite_test.go
- pkg/network/domainspec/generators.go
- pkg/network/domainspec/generators_test.go
- pkg/network/driver/common.go
- pkg/network/infraconfigurators/bridge.go
- pkg/network/link/BUILD.bazel
- pkg/network/link/address.go
- pkg/network/link/address_test.go
- pkg/network/setup/network_suite_test.go
- pkg/network/setup/podinterface_test.go
- pkg/network/setup/podnic.go
- pkg/network/setup/podnic_test.go
This PR splits the invocation of the network setup operations (infrastructure configuration / libvirt spec generation)
which are located within the `setup` package from the actual domain spec generation.
The actual domain spec generation was moved to a new package under the network folder, having the following structure:
- pkg
- network
- **domainspec**
- **generators.go**
- infraconfigurators
- ...
- setup
- ...
```release-note
NONE
```
> Add spec generator pkg

- cmd/virt-launcher/virt-launcher.go
- pkg/host-disk/BUILD.bazel
- pkg/host-disk/host-disk.go
- pkg/host-disk/host-disk_test.go
- pkg/virt-controller/services/template.go
- pkg/virt-controller/services/template_test.go
- pkg/virt-handler/vm.go
- pkg/virt-launcher/virtwrap/BUILD.bazel
- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
- tests/storage/storage.go
Fixes #
```release-note
NONE
```
> Move host-disk to handler

- tests/network/vmi_multus.go
Addresses sonarcloud issues in vmi_multus tests
Commit 1:
- [linux-bridge duplication](https://sonarcloud.io/project/issues?fileUuids=AXg5J8E-ey6zG9Z1Sjkn&id=kubevirt_kubevirt&open=AXg5J8ZUey6zG9Z1SjlP&resolved=false&types=CODE_SMELL)
- [ptp-conf-1 duplication](https://sonarcloud.io/project/issues?fileUuids=AXg5J8E-ey6zG9Z1Sjkn&id=kubevirt_kubevirt&open=AXpaVJkQ6dE-hQjgpuho&resolved=false&types=CODE_SMELL)
- [ptp-conf-2 dup](https://sonarcloud.io/project/issues?fileUuids=AXg5J8E-ey6zG9Z1Sjkn&id=kubevirt_kubevirt&open=AXg5J8ZUey6zG9Z1SjlJ&resolved=false&types=CODE_SMELL)
- [cloud init data duplication](https://sonarcloud.io/project/issues?fileUuids=AXg5J8E-ey6zG9Z1Sjkn&id=kubevirt_kubevirt&open=AXg5J8 …
> network, tests: address vmi_multus sonarcloud

- api/openapi-spec/swagger.json
- cmd/virt-launcher/virt-launcher.go
- docs/software-emulation.md
- manifests/generated/kv-resource.yaml
- pkg/util/util.go
- pkg/virt-config/config-map.go
- pkg/virt-config/config_test.go
- pkg/virt-config/virt-config.go
- pkg/virt-controller/services/template.go
- pkg/virt-handler/vm.go
- pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
- pkg/virt-launcher/virtwrap/cmd-server/server.go
- pkg/virt-launcher/virtwrap/cmd-server/server_test.go
- pkg/virt-launcher/virtwrap/converter/converter.go
- pkg/virt-launcher/virtwrap/converter/converter_test.go
- pkg/virt-launcher/virtwrap/converter/network.go
- pkg/virt-launcher/virtwrap/live-migration-target.go
- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
- tests/utils.go
- tests/vmi_configuration_test.go
- tests/vmi_lifecycle_test.go
This PR renames all(*) code uses of "UseEmulation" config to "AllowEmulation", to better reflect the semantics of this field (i.e., allow to use software emulation as fallback in case hardware emulation is not available). The previous terminology was inaccurate since hardware virtualization was still attempted first, even when UseEmulation was explicitly set.
* (*) One notable exception is the `KubeVirt.spec.configuration.developerConfiguration.useEmulation` field that wasn't changed to retain backward compatibility. Corollary: should we deprecate that field and introduce a `.allowEmulation` heir?
* This PR also updates the [Software Emulation](./docs/software-emulation.md) doc to clarify the semantics of `.useEmulation`, as well as adds a doc …
> Rename "UseEmulation" --> "AllowEmulation"

- pkg/virt-handler/vm.go
This is an modified version of #6176 for compatibility with Go 1.13.
/assign @kwiesmueller
```release-note
Fix goroutine leak in virt-handler, potentially causing issues with a high turnover of VMIs.
```
> [release-0.41] fix goroutine leak in virt-handler

- hack/dockerized
This should allow running `make push` when using podman as a CRI
Fixes #6260
```release-note
NONE
```
> dockerized: handle podman auth files

- api/openapi-spec/swagger.json
- pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
- pkg/virt-controller/watch/snapshot/restore.go
- pkg/virt-controller/watch/snapshot/restore_base.go
- pkg/virt-controller/watch/snapshot/restore_test.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
- tests/storage/restore.go
When vm restore in progress prevent from starting the vm until the restore is done
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=1957852
```release-note
NONE
```
> Fix bug 1957852 - prevent vm to start when restore is in progress

- pkg/virt-controller/watch/snapshot/snapshot.go
- pkg/virt-controller/watch/snapshot/snapshot_test.go
the volume snapshot status for volumes types which doesnt support
snapshot was wrong, its not because they are lacking storage class
as was the previous error they dont need it at all they simply dont
support snapshot.
fix bug 1982143
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=1982143
Fixed BZ#1982143
```release-note
NONE
```
> fix bug 1982143 - Change volume not supporting snapshot status error

- hack/whatchanged.sh
Run `./hack/whatchanged.sh` after bumping (before committing),
in order to create a summary of what changed by
the kubevirtci bump.
Example of output:
```
2c2862b cnao, Bump CNAO to 0.58.0 on all providers (https://github.com/kubevirt/kubevirtci/pull/664)
ba05421 cluster-provision, Prefetch cdi images (https://github.com/kubevirt/kubevirtci/pull/660)
71d8ce5 Bump k8s providers (https://github.com/kubevirt/kubevirtci/pull/661)
0007793 cdi, Bump cdi to 1.36.0 on k8s-1.21 (https://github.com/kubevirt/kubevirtci/pull/659)
9c1261b Kind infra providers: Deploy default CNI (https://github.com/kubevirt/kubevirtci/pull/644)
```
Signed-off-by: Or Shoval oshoval@redhat.com
```release-note
None
```
> kubevirtci, Add whatchanged script

- hack/cluster-deploy.sh
- manifests/testing/uploadproxy-nodeport.yaml.in
- tests/storage/imageupload.go
Our functional tests are using `kubectl port-forward` to upload the images, which is not very reliable.
Since https://github.com/kubevirt/kubevirtci/pull/653, we have a port that is exposed from host -> VM;
We can look it up and set up a NodePort against it instead.
Fixes #
```release-note
NONE
```
> Switch kubectl port-forward -> NodePort as an attempt to stabilize 4621 from quarantine

- tests/network/BUILD.bazel
- tests/network/vmi_multus.go
As for today on Multus tests suite [[1]](https://github.com/kubevirt/kubevirt/blob/259de8032ac84f8c8a3e6f37cbb94f598f936c3d/tests/network/vmi_multus.go#L101) we create a linux-bridge on each cluster node [[2]](https://github.com/kubevirt/kubevirt/blob/259de8032ac84f8c8a3e6f37cbb94f598f936c3d/tests/network/vmi_multus.go#L173)    [[3]](https://github.com/kubevirt/kubevirt/blob/259de8032ac84f8c8a3e6f37cbb94f598f936c3d/tests/network/vmi_multus.go#L1409)
before all tests starts in order for the tests that uses bridge CNI plugin to work.
The bridge CNI plugin is capable of creating a linux-bridge on the cluster nodes 
according to the NAD definition as being done on the tests.
Thus there is no need to create …
> Remove linux-bridge creation before Multus tests suite starts

- hack/whatchanged.sh
Update markdown style of what changed script to
show links.
Fix also the potential case where there is a pound char,
in the kubevirtci PRs title, that will be updated to
a link where it shouldn't.
Example of output:
[576bc8c kind/podpreset.sh: fix error redirection to stderr](https://github.com/kubevirt/kubevirtci/pull/612)
[e86941a kind infra, podpreset: Increase PodPreset enabled validation timeout](https://github.com/kubevirt/kubevirtci/pull/669)
See previous style here 
https://github.com/kubevirt/kubevirt/pull/6316
```release-note
None
```
> whatchanged, Update markdown style of whatchanged script

- pkg/monitoring/client/prometheus/BUILD.bazel
- pkg/monitoring/client/prometheus/prometheus.go
- pkg/monitoring/client/prometheus/prometheus_suite_test.go
- pkg/monitoring/client/prometheus/prometheus_test.go
- staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
- staging/src/kubevirt.io/client-go/kubecli/kubecli.go
- tools/perfscale-audit/api/api.go
- tools/perfscale-audit/metric-client/metric-client.go
This PR introduces expands the rest_client_requests_total counter metric to provide labels for the resource and k8s verb associated with the request. This means we have a metric that can tell us how many times we call an operation (like "UPDATE" ) on a specific resource (like "VirtualMachineInstances")
I've also integrated this metric into our perf-audit tool which allows us to audit if specific operation/resource counts hit above an expected threshold over a set period of time.
For example, If i'm running a repeatable and predictable density test that starts 100 VMIs, then I'd expect a fairly consistent number of client API calls across our control plane involved with updating those VMI objects. We can run the density test, give the perf-audit tool a threshold for the number of VMI …
> [Sig-scale] Metric for monitoring Request Counts by Resource and Operation

- images/disks-images-provider/entrypoint.sh
- manifests/testing/disks-images-provider.yaml.in
- pkg/virt-handler/hotplug-disk/findmnt.go
- pkg/virt-handler/hotplug-disk/findmnt_test.go
- pkg/virt-handler/hotplug-disk/mount.go
- tests/config.go
- tests/default-config.json
- tests/storage/hotplug.go
- tests/utils.go
findmnt returns device[path relative in device] when looking up the
source of a mount by container pid. So on separate device that often
returned /<path> which is not where it is mounted in the boot device.
This PR modifies the check to look up the device, and then the path
where the device is mounted, and combines the two paths to get the
path relative to the boot device so we can properly bind mount the
hostpath volume into another container.
Fixes #6303 
I have made some modifications to …
> Fix hostpath hotplug not working when volume on separate device

- tests/storage/storage.go
Some tests related to the HostDisk feature gate are failing when it is not enabled instead of being skipped.
This PR extends the scope of the check for the HostDisk feature gate to more tests.
```release-note
NONE
```
> tests: fix skipping of HostDisk tests

- tests/container_disk_test.go
One of the tests was setting the memory limit for image verification to
a low value without restoring it afterwards. Therefore all the tests
executed later on were failing because of insufficient memory for
qemu-img.
There was a call to restore the test environemnt in the BeforeEach()
section. Though it needs to be called *after* the test.
Fixes #
The offending test is `disk verification should fail when the memory limit is too low`:
https://github.com/kubevirt/kubevirt/blob/c9e87c4cb6292af33ccad8faa5fb9bf269c0fbf4/tests/container_disk_test.go#L150-L151 …
> Fix qemu-img segmentation fault error in tests

- tests/reporter/kubernetes.go
- tests/reporter/outputenricher.go
- tests/tests_suite_test.go
- tests/utils.go
In order to make it finally possible to clean up environments as
expected in a `AfterEach` the reporters are now collecting the
environment info in a `JustAfterEach`. This means that it does no
longer matter if `BeforeTestCleanup` is called in a `BeforeEach` or
`AfterEach`.
Fixes #
```release-note
NONE
```
> Collect reporter artifacts in a JustAfterEach

- tests/storage/storage.go
Fetch the latest state of the hostpath job pod before it is returned to the caller: previously it was returned right after the creation and thus the `pod.Spec.NodeName` was empty (since it was not yet scheduled). The NodeName is needed to schedule NFS or VMI pods on the same node later on.
The PR fixes flaky storage NFS tests: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-cgroupsv2/1433336606130966528
UPD: also fixes https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6346/pull-kubevirt-check-tests-for-flakes/1433731379153080320
Follow-up of the: https://github.com/kubevirt/kubevirt/pull/6335 …
> Fix flaky hostpath storage tests

- tests/migration_test.go
This PR disables a release-0.41 test that basically never passes on the 1.18 test lane for unknown reasons.
This is hopefully pretty low risk, since the test is still active in master, testing PRs before they get backported here.
Fixes #
```release-note
NONE
```
> release-0.41: disable extremely flaky test

- WORKSPACE
- tests/migration_test.go
Manual cherrypick of #6062 
This patch should addresss the flakiness issue with `test_id:5004`.
```release-note
NONE
```
> [release-0.41] Replace dead "stress" binary with new, maintained, "stress-ng" binary

- pkg/virt-controller/watch/snapshot/snapshot.go
- pkg/virt-controller/watch/snapshot/snapshot_test.go
This is a cherry-pick of #6282 
```release-note
NONE
```
> [release-0.41] bug 1982143 -Change volume not supporting snapshot status error

- tests/framework/matcher/BUILD.bazel
- tests/framework/matcher/getter.go
- tests/framework/matcher/owner.go
- tests/framework/matcher/owner_test.go
- tests/framework/matcher/phase.go
- tests/storage/datavolume.go
Follow up of #4616. Making datavolume test work in parallel and refactor them with more custom ginkgo matchers to make them more maintainable.
***New Matchers***
Add some convenience functions for Running and Succeeded phase which is pretty common to match against:
```go
Expect(ThisDV(dv)).To(HaveSucceeded())
Expect(ThisVMI(vmi)).To(BeRunning())
```
Add matchers which can check for owner refereces in a convenient way:
```go
Expect(ThisVMI(vmi)).To(BeOwned())
Expect(ThisDV(dv)).ToNot(HaveOwners())
```
Checking for object states when just having the `name` and `namespace` at hand is pretty common. To avoid extre pre-pulls to pass in an object to the matchers, add a new set of getters which take `namespace` and `name` directly. They all have a `With` …
> Parallel datavolume tests

- hack/verify-generate.sh
In case generate diff exists, show both the files
and the actual diff, it makes it easier and faster
to fix in case its a small change.
```release-note
None
```
> generate, Show git diff in case generate diff exists

- docs/guestfs.md
Document the use of the virtctl guestfs command added by the PR
https://github.com/kubevirt/kubevirt/pull/5402
Fixes #
```release-note
NONE
```
> docs: Add docs for virtctl guestfs command

- automation/test.sh
Align sig-operator as the other sigs in
automation/test.sh script.
This way it can set TARGET as
k8s-1.x-sig-operator.
```release-note
None
```
> automation, Align sig-operator in automation scripts

- tests/BUILD.bazel
- tests/io_utils.go
Virt-handler no longer installs device-mapper, so tests using
these functions always fail. This was missed as they are flaky
and quarantined.
```release-note
NONE
```
> Test fix: Use a pod with virt-launcher image to run dmsetup commands.

- cmd/virt-handler/virt-handler.go
- pkg/virt-handler/non-root.go
- pkg/virt-handler/selinux/labels.go
We continue kubevirt if we can't install our policies when selinux is
permissive. As a consequence we also have to treat relabel attempts
gracefully when selinux is  permissive.
Fixes #5736
```release-note
Don't fail on failed selinux relabel attempts if selinux is permissive
```
> Don't fail  on relabeling if selinux is permissive

- tests/framework/matcher/getter.go
- tests/operator_test.go
In order to catch issues which would only be visible after a second
migration after a kubevirt update, migrate one VMI which got created
before the update a second time after the upgrade.
Related to #6340, where migrations the first time significantly differ after an upgrade.
Fixes #
```release-note
NONE
```
> Ensure that we can migrate a VM multiple times after update

- pkg/virt-handler/vm.go
- pkg/virt-launcher/virtwrap/converter/converter.go
- pkg/virt-launcher/virtwrap/converter/converter_test.go
- tests/vmi_configuration_test.go
This commit fixes UEFI mode with secureboot disabled
for base images (for virt-launcher) where only `OVMF_CODE.secboot.fd`
is shipped, letting the combination `OVMF_CODE.secboot.fd` +
`OVMF_VARS.fd` to be used to correctly boot in EFI mode with
no secureboot.
Previously when disabling secureboot virt-launcher would only try
to use `OVMF_CODE.fd` + `OVMF_VARS.fd` resulting in a VMI failure
when the former firmware file was not shipped.
Fixes #
```release-note
NONE
```
> [release-0.41] virt-launcher: fix UEFI-mode without secureboot

- tests/operator_test.go
This test failed 3 times in the last 2 month because of some
infra+TLS issues. The flakiness is so low and we decided to
remove it from QUARANTINE.
It also removes  the `[sig-compute]` label from the description
of the test given that we have now proper sig-operator lanes.
Fixes #
```release-note
NONE
```
> Remove test 3150 from QUARANTINE

- pkg/monitoring/perfscale/perfscale_test.go
- pkg/monitoring/perfscale/register.go
- pkg/monitoring/perfscale/vmi-phase-transitions.go
Time from deletion is the amount of time between the DeletionTimestamp and when kubevirt notices the VMI's Finalizer has been removed.
```release-note
Record the time it takes to delete a VMI and expose it as a metric
```
Closes: https://github.com/kubevirt/kubevirt/issues/6235
> [SIG-scale] Record the VMI deletion time

- hack/bazel-build.sh
bazel `run` targets require at this stage explicit `build` steps for a
dependency to be available locally if the remote fetch strategy does not
fetch all artifacts by default.
Fixes issues like
```
18:24:55: cp: cannot stat 'bazel-out/k8-fastbuild/bin/tools/perfscale-audit/perfscale-audit_/perfscale-audit': No such file or directory
```
Fixes #
```release-note
NONE
```
> Ensure that the perf tool binaries are always present

- tests/BUILD.bazel
- tests/migration_test.go
- tests/storage/datavolume.go
- tests/storage/hotplug.go
- tests/storage/snapshot.go
- tests/storage/storage.go
- tests/utils.go
> Use matcher rather than custom functions for waiting for DV phases

- automation/test.sh
- hack/cluster-deploy.sh
In order to make the kubevirt deploy lighter,
and install only whats needed, add a flag that
will determine if to install CDI.
This in turn will make less dependencies,
and faster cluster-sync.
`export KUBEVIRT_DEPLOY_CDI=false` in order to skip
CDI installation (default is to install it).
For kind providers,  `KUBEVIRT_DEPLOY_CDI` will be set to false automatically,
since we are not using CDI there, and because the loopback devices does conflict with DinD.
```release-note
None
```
> CDI, Introduce KUBEVIRT_DEPLOY_CDI flag

- pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
- pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
- pkg/virt-controller/services/template.go
- pkg/virt-controller/services/template_test.go
- tests/vmi_configuration_test.go
This PR fixes the default setting of CPU requests on the virt-launcher compute container.
The default vmipods CPU request is being calculated during the pod creation and scales with the number of vCPUS according to the `cpu_allocation_ratio` (which defaults to 10) setting 
This way, the default CPU request of a vmipod , created for a VMI with 1 vCPU, will be 100m.
This PR adds unit and functional tests to verify the correct behavior.
Fixes # rhbz#2002313 
```release-note
Fix the default setting of CPU requests on vmipods
```
> Fix the default setting of CPU requests on vmipods

- api/openapi-spec/swagger.json
- pkg/network/infraconfigurators/masquerade.go
- pkg/network/infraconfigurators/masquerade_test.go
- pkg/virt-controller/services/template.go
- pkg/virt-controller/services/template_test.go
- pkg/virt-controller/watch/vmi.go
- pkg/virt-controller/watch/vmi_test.go
- pkg/virt-handler/vm.go
- pkg/virt-handler/vm_test.go
- pkg/virt-launcher/virtwrap/BUILD.bazel
- pkg/virt-launcher/virtwrap/live-migration-source.go
- pkg/virt-launcher/virtwrap/live-migration-target.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/api/v1/types.go
- staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
This PR switches live migration to directly use Unix sockets between the virt-launchers and virt-handlers
This removes the need of proxying the connections between the components. 
```release-note
switch live migration to use unix sockets
```
> Switch live migration to use unix sockets between instead of TCP

- Makefile
- hack/prom-rule-ci/prom-rules-tests.yaml
- pkg/virt-operator/resource/generate/components/prometheus.go
This PR adds Prometheus records to track total amount of REST calls in last hour & 5 minutes, and bad REST calls over the same time-frame:
- `vec_by_virt_apis_all_client_rest_requests_in_last_5m`
- `vec_by_virt_apis_all_client_rest_requests_in_last_hour`
- `vec_by_virt_apis_failed_client_rest_requests_in_last_5m`
- `vec_by_virt_apis_failed_client_rest_requests_in_last_hour`
These records then set these alert rules:
- `VirtApiRESTErrorsHigh`: `More than 5% of the rest calls failed in virt-api for the last hour`
- `VirtApiRESTErrorsBurst`: `More than 80% of the rest calls failed in virt-api for the last 5 minutes`
I'm not entirely sure where `prom-rules-tests.yaml` is used besides testing. Does it have any …
> [virt-api]: Add Prometheus records & alerts for bad REST calls

- manifests/generated/operator-csv.yaml.in
- manifests/generated/rbac-operator.authorization.k8s.yaml.in
- pkg/virt-operator/resource/generate/rbac/cluster.go
- pkg/virt-operator/resource/generate/rbac/controller.go
- pkg/virt-operator/resource/generate/rbac/operator.go
- tests/BUILD.bazel
- tests/access_test.go
This is a manual backport of #6147.
```release-note
Fix rbac permissions for freeze/unfreeze, addvolume/removevolume, guestosinfo, filesystemlist and userlist
```
> [release-0.41] Fix RBAC subresource permissions for admin/edit/view roles

- tests/vmi_lifecycle_test.go
Increase the timeout for node to become scheduleable 
The current failures only seems to be related to timeouts 
Fixes quarantine test added in #6215 
```release-note
NONE
```
> [test] Increase the timeout for node to become scheduleable

- pkg/virtctl/imageupload/imageupload.go
- pkg/virtctl/imageupload/imageupload_test.go
A user can create volume for upload without specifying the accessMode
and volumeMode. The DataVolume is created using new spec.storage
field. If StorageProfile for StorageClass is available CDI will provide
recommended params.
Fixes #
This is an alternative to #6192
```release-note
virtctl imageupload now uses DataVolume.spec.storage
```
> Create volume using defaults provided by CDI

- go.mod
- go.sum
- pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go
- staging/src/kubevirt.io/client-go/go.mod
- staging/src/kubevirt.io/client-go/go.sum
- staging/src/kubevirt.io/client-go/log/log.go
- vendor/github.com/go-kit/kit/endpoint/BUILD.bazel
- vendor/github.com/go-kit/kit/endpoint/endpoint.go
- vendor/github.com/go-kit/kit/log/BUILD.bazel
- vendor/github.com/go-kit/kit/log/README.md
- vendor/github.com/go-kit/kit/log/doc.go
- vendor/github.com/go-kit/kit/log/json_logger.go
- vendor/github.com/go-kit/kit/log/log.go
- vendor/github.com/go-kit/kit/log/stdlib.go
- vendor/github.com/go-kit/kit/log/sync.go
- vendor/github.com/go-kit/kit/log/value.go
- vendor/modules.txt
This PR removes the `replace` directive that replaces go-kit `v0.9.0` with `v0.3.0` and updates the use of the `github.com/go-kit/kit/log` package to be compatible with the APIs supported by `v0.4.0` and beyond.
The `v0.3.0` APIs in `github.com/go-kit/kit/log` are incompatible with those in `v0.4.0` and beyond. This makes it impossible to import packages like `kubevirt.io/client-go/kubecli` into other projects where other dependencies rely on newer versions of go-kit (`go mod` will pick the higher version and this results in compilation errors in `kubevirt.io/client-go/log` due to conflicting APIs).
NONE
NONE
```release-note
Removed go module pinning to an old …
```
> Upgrade go-kit to v0.9.0

- manifests/generated/operator-csv.yaml.in
- manifests/generated/rbac-operator.authorization.k8s.yaml.in
- pkg/virt-operator/creation/rbac/cluster.go
- pkg/virt-operator/creation/rbac/controller.go
- pkg/virt-operator/creation/rbac/operator.go
- tests/access_test.go
This is a manual backport of #6147.
```release-note
Fix rbac permissions for freeze/unfreeze, addvolume/removevolume, guestosinfo, filesystemlist and userlist
```
> [release-0.36] Fix RBAC subresource permissions for admin/edit/view roles

- tests/storage/datavolume.go
- tests/storage/storage.go
Running tests in parallel seems to increase the load.
It's not clear whether the timeouts will help, but it's hard to ignore that they are low, and knowing the tests are also flaky with high timeouts will help us focus on actual failures.
```release-note
NONE
```
> Double timeouts of storage tests that flake when parallel

- hack/build-go.sh
Without this fix, `make go-test` fails with:
```
package kubevirt.io/kubevirt/cmd/container-disk-v2alpha: C source files not allowed when not using cgo or SWIG: main.c
make: *** [Makefile:72: go-test] Error 1
```
```release-note
NONE
```
> go-test: ignore cmd/container-disk-v2alpha which is not go

- pkg/virt-operator/webhooks/BUILD.bazel
- pkg/virt-operator/webhooks/kubevirt-update-admitter.go
- tests/operator_test.go
Added validation for the `Spec.infra` and `Spec.workloads` sections in Kubevirt CR. 
Validation code placed in the virt-operator webhook code, and it will happen upon CR update.
Added functional test coverage as well.
Since we weren't fail fast on incorrect configuration, the apply of this configuration on the control place deployments/DS 
would fail and we will have inconsistent state of the control plane deployment. 
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1938262
More refactoring in the virt-operator functest area will come in following PRs..
```release-note
NONE
```
> [virt-operator] add validation for the infra and workloads placement config in Kubevirt CR

- automation/test.sh
Since the introduction of whereabouts, completed ip-reconcilers can appear in the default namespace.
Without this fix, the script times out waiting for those to become "Running".
```release-note
NONE
```
> automation: avoid waiting forever that Completed pods become Running

- automation/test.sh
The latest kubevirtci bump introduced whereabouts on network lanes, which itself creates ip-reconciler pods that quickly complete.
https://github.com/kubevirt/kubevirt/pull/6431 was created to ignore those completed pods in the automation script.
However, that last PR is incomplete, and the script can still fail on the readiness check.
This PR addresses that.
```release-note
NONE
```
> automation: ignore completed pods when checking for readiness

- pkg/virt-controller/watch/vmi.go
Handle `cache.DeletedFinalStateUnknown` keys in the virt-controller for VMIs.  
fixes: https://github.com/kubevirt/kubevirt/issues/6418
```release-note
Fix virt-controller panic caused by lots of deleted VMI events
```
> Catch the deletion key before type assertion causes a panic

- pkg/virt-launcher/virtwrap/live-migration-source.go
- tests/migration.go
- tests/migration_test.go
The `PersistXML` migration parameter was overlooked when switching from transient to persistent target domains.
Without `PersistXML`, the target XML will actually be a copy of the source, ignoring our changes, as described in:
https://libvirt.org/html/libvirt-libvirt-domain.html#VIR_MIGRATE_PARAM_PERSIST_XML
```release-note
NONE
```
> migration: persist XML changes to the target

- manifests/generated/operator-csv.yaml.in
- manifests/generated/rbac-operator.authorization.k8s.yaml.in
- pkg/virt-operator/resource/generate/rbac/operator.go
This PR removes some obsolete permissions from virt-operator's ClusterRole.
These permissions were left in order to support upgrades from old versions (<=0.28, ~1.5yr ago), so can be safely removed at this point.
```release-note
Cleanup obsolete permissions from virt-operator's ClusterRole
```
> Cleanup obsolete permissions from virt-operator's ClusterRole

- tests/storage/restore.go
Before we realized our sig-storage k8s-1.19 and k8s-1.20 lanes
have a systematic issue, we tried to quarantine individual tests.
These were some of the affected, but they do not seem to fail in
the k8s-1.21 lane, which is far more stable.
```release-note
NONE
```
> Unquarantine storage tests mistakingly quarantined.

- hack/cluster-clean.sh
`hack/cluster-clean.sh` seems to have peculiar complexities which I'd like to understand and simplify
I have tested this with
```
make cluster-up
make cluster-sync
make functtest; ^C
make cluster-sync  # this first calls cluster-clean target
```
and it seemed to clean the cluster all right.
```release-note
NONE
```
> janitorial: clean cluster-clean.sh

- cmd/virt-launcher/virt-launcher.go
This commit fixes a race condition that would cause a VMI compute
pod to exit and end up in an erroneous 'Failed' state even if actually
the pod terminated gracefully.
The race condition is caused by having 2 goroutines doing a wait() on
the same PID, while a fix existed already it was not covering the whole
critical section causing to the race to persist (just with a lower
failure rate).
One example of the race is the following:
The goroutine executing on the SIGCHLD signal handler completes the
Wait4() and is about to write the exit status on the channel
goroutine 1
```
case syscall.SIGCHLD:
var wstatus syscall.WaitStatus
wpid, err := syscall.Wait4(-1, &wstatus, syscall.WNOHANG, nil)
if err != nil {
log.Log.Reason(err).Errorf("Failed to reap process %d", wpid)
}
**EXECUTION HERE**
if …
```
> [release-0.41] virt-launcher: fix exit pod race condition

- pkg/virt-launcher/virtwrap/manager.go
- tests/network/BUILD.bazel
- tests/network/vmi_multus.go
- tests/utils.go
- tests/vmi_cloudinit_test.go
SR-IOV interfaces are being added to the guest as `hostdev`s instead of `interface`s 
`hostdev`s were not previously considered when devices metadata was generated.
This PR should expose the tagged SRIOV interfaces in the config drive metadata.
Fixes #6413
```release-note
Tagged SR-IOV interfaces will now appear in the config drive metadata 
```
> Fix sriov tagging

- pkg/network/dhcp/server/server.go
- pkg/network/dhcp/server/server_test.go
PR requested by @maiqueb 
This PR fixes https://github.com/kubevirt/kubevirt/issues/6462, the behavior and need for the PR is extensively detailed there. The `.IPv4()` on the gateway IP can safely be done in `server.go` as it is the last place it is touched before handed over to the DHCP library.
Fixes https://github.com/kubevirt/kubevirt/issues/6462
```release-note
Fix corrupted DHCP Gateway Option from local DHCP server, leading to rejected IP configuration on Windows VMs.
```
> Properly process Gateway DHCP Option as IPv4 in DHCP Server

- automation/test.sh
**What this PR does / why we need it**: test_id:3145 is a release blocker test but it is very flaky in nonroot lanes. This PR skips it only for those lanes.
Fixes #
```release-note
NONE
```
> Skip test_id:3145 for nonroot lanes

- pkg/hotplug-disk/hotplug-disk.go
- pkg/hotplug-disk/hotplug-disk_test.go
- pkg/virt-handler/hotplug-disk/mount.go
- pkg/virt-handler/hotplug-disk/mount_test.go
- pkg/virt-launcher/virtwrap/converter/converter.go
- pkg/virt-launcher/virtwrap/converter/converter_test.go
- pkg/virt-launcher/virtwrap/manager_test.go
Before we mounted the directory containing the disk.img file into the
virt-launcher pod. If the virt-launcher pod was killed unexpectedly it
would generate a race between kubelet and virt-handler. If kubelet ran
first it, it would empty the contents of the emptyDir we had mounted
the volume directory in. It would also empty the contents of that directory.
It would be unable to remove the directory because it was bind mounted but
the contents were lost.
This commit changes the way we hotplug images, by bind mounting the image
directly, and thus preventing the race from becoming an issue. If kubelet
runs first, it won't be able to remove the disk image because the resource
will be busy. This gives …
> Resolve hotplug race between kubelet and virt-handler

- pkg/monitoring/perfscale/vmi-phase-transitions.go
In SIG-scale's testing, we saw VMI creation time running up against the highest transition bucket (10 minutes).  Add a few more buckets that we hopefully never have to use.
```release-note
NONE
```
> Add more phase transition buckets

- tests/template_test.go
Disclaimer: The template tests should be remove for a few reasons:
* they do not test any kubevirt functionality, just if `oc template` works for CRDs, which is not something which we have to do.
* they are never run in our CI lifecycle because we have no openshift
* We do not provide any official templates out of our test templates, so they have also no value there
* The tests are written overcomplicated and would require a complete rewrite
However here a fix which ensures that  the fedora template is actually written before `oc` tries to use the template.
Fixes # …
> Ensure that the BeforeTest function is actually called

- tests/storage/datavolume.go
Should speed things up, and reduce the chance we'll hit timeouts.
```release-note
NONE
```
> Use smaller writes for fstrim test, improve messaging on failure

- tests/infra_test.go
- tests/migration_test.go
**What this PR does / why we need it**: quarantine flaky sig-compute tests:
* [Serial][sig-compute]Infrastructure changes to the kubernetes client on the virt handler rate limiter should lead to delayed VMI running states
* flakefinder report: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-09-29-168h.html#row0
* recent failures:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6234/pull-kubevirt-e2e-k8s-1.21-sig-compute/1443173339290931200
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6467/pull-kubevirt-e2e-k8s-1.20-sig-compute/1443328854604124160
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kub …
> Quarantine flaky sig-compute tests

- pkg/network/dhcp/server/BUILD.bazel
- pkg/network/dhcp/server/server_test.go
This PR helps clarify what our DNS name requirements are, by enforcing those via a unit test.
Furthermore, it refactors the DNS related tests into a table, and exposes a bug on our search domain validation regex.
We already have a test that does the opposite - prevent domain names **starting** with `-` . 
This new test makes it more explicit that ending the domain name with `-` is **also** not legit.
From the [DNS RFC, section 2.3.1](https://datatracker.ietf.org/doc/html/rfc1035#section-2.3.1) I see that (quoting below):
```
The labels must follow the rules for ARPANET host names.  They must
start with a letter, end with a letter or digit, and have as interior
characters only letters, digits, and hyphen.  There …
```
> dns, tests: only accept preferred names syntax

- tests/storage/storage.go
The test "[rfe_id:3106][crit:medium][vendor:cnv-qe@redhat.com][level:component]With ephemeral alpine PVC should be successfully started with Ephemeral PVC from NFS using ipv6 address of the NFS pod" does not fail since a long time. 
The original problem with mounting/unmounting volumes was probably solved by kubevirtci/kuberneted update. 
Fixes #
The NFS server and the way the storage tests are run will be addressed in a task to unify the way storage tests are written between cdi and kubevirt projects. So this PR does not try to improve/change the NFS server …
> Remove test NFS test from quarantine

- pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
- pkg/virt-launcher/virtwrap/api/schema.go
- pkg/virt-launcher/virtwrap/converter/converter.go
- pkg/virt-launcher/virtwrap/converter/converter_test.go
- tests/storage/hotplug.go
- tests/vmi_configuration_test.go
Instead of trying to set the iothreads on the disk, set the
proper iothreads on the scsi controller and set the io to
'threads' on hotplugged disks.
Added unit and functional tests to ensure this works properly
Fixes #
```release-note
Hotplug disks are possible when iothreads are enabled.
```
> Handle iothreads for hotplugged disks.

- tests/utils.go
which can happen before DV success and is normal.
[Example failure](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.21-sig-storage/1437654969137238016)
```release-note
NONE
```
> Ignore "didn't find PVC associated with DataVolume" spurious warning

- tests/reporter/BUILD.bazel
- tests/reporter/kubernetes.go
Collect and dump DataVolume info on test failure. DataVolume information might be useful when investigating test failures. 
Fixes #
```release-note
NONE
```
> Collect DataVolumes info on test failure

- tests/network/vmi_multus.go
- tests/utils.go
Lately SR-IOV lane became flaky due to the warning:
    
`unknown error encountered sending command SyncVMI:
rpc error: code = DeadlineExceeded desc = context deadline exceeded` [1]
This is a warning level event, which has a built-in
retry mechanism in kubevirt.
    
SR-IOV tests are used to ignore this warning,
but a new function, `StartVmOnNode`, didn't.
Therefore remove waiting for the VMI start from `StartVmOnNode` function.
Notable points:
* It didn't ignore this specific warning mentioned above, which in turn
caused this warning to fail the tests.
* Each caller of `StartVmOnNode` already waiting for start anyhow,
with the correct ignore warnings settings upon need,
it was redundant and not correct, so it is safe to remove it.
* It also caused the VMI starting to be serial, instead …
> sriov, Fix flaky context deadline exceeded tests

- tests/storage/imageupload.go
This test hasn't failed in the k8s-1.21-sig-storage periodics
and therefore we think it is no longer flaky.
(The other sig-storage lanes are known as flaky and not taken
into account)
```release-note
NONE
```
> Remove test_id:4621 from quarantine (fixed in #6312)

- pkg/controller/controller.go
**What this PR does / why we need it**: This MR fixes a problem that leads to reporting incorrect metrics in Kubernetes. The problem is that `watchFunc` uses deprecated (since K8s v1.12) API call which seems to be incorrectly interpreted by `apiserver`. My fix is simply replacing old, deprecated method of indicating WATCH operation by a new one. After the fix the `apiserver_request_duration_seconds` metrics for LIST operation drop to normal levels:
Fixes #6436 
```release-note
Fix deprecated use of watch API to prevent reporting incorrect metrics.
```
> Fix deprecated use of watch API

- cmd/virt-launcher/virt-launcher.go
virt-launcher will actively check for newly created domains during the start
So far waitForDomainUUID reacted to libvirt events. In some cases, an empty
domain object could be received which would prevent the virt-launcher from
terminating when not running domains has been detected. This patch will not
consider domain objects without UUID. It will also actively query for new
domains.
This prevents cases where migration will not be processed if previous migration failed.
Fixes #
This is a cherrypick from https://github.com/kubevirt/kubevirt/pull/5328
**Release …
> [release-0.36] Fix domain lookup to ensure target pod of migration is cleanup

- tests/BUILD.bazel
- tests/dryrun_test.go
- tests/utils.go
Add functional tests to validate that dry-run requests for objects CRUD operations are honored.
This PR includes functional tests for VMI, VM, VMIMl, VMIRS, Presets, Snapshot, and KubeVirt CR.
Fixes #
```release-note
NONE
```
> Add DryRun functional tests for KubeVirt resources

- staging/src/kubevirt.io/client-go/log/log.go
It's a temporary solution until we will implement a proper behavior
of the virt-launcher in cases of unsupported GA commands.
The urgency for lowering this message came from a large scale
environment where this message appears to abuse the monitoring
system of the cluster.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2008522
```release-note
NONE
```
> [virt-launcher]: lower the log severity of GA unsupported commands

- pkg/virt-controller/watch/snapshot/snapshot.go
- tests/storage/snapshot.go
Signed-off-by: mhenriks@redhat.com <Michael Henriksen>
`status.Phase` was recently added to VirtualMachineSnapshot resource.
Unfortunately, we were not correctly handling the case when phase is unset on upgrade.  Were transitioning the snapshot to Failed state when should have transitioned to Succeeded.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2018521
```release-note
Fix BZ 2018521 - On upgrade VirtualMachineSnapshots going to Failed
```
> Fix vmsnapshot upgrade bug

- tests/migration.go
- tests/migration_test.go
This PR is trying to stabilize `[test_id:6978] Should detect a failed migration` test
1. use correct namespace to actually remove the killer pod
2. keep the killer pod around even after killing the handler (In case we detect wrong domain)
Relates to https://github.com/kubevirt/kubevirt/issues/6622
Fixes #
```release-note
None
```
> Fix [test_id:6978] Should detect a failed migration

- api/openapi-spec/swagger.json
- manifests/generated/kv-resource.yaml
- pkg/virt-operator/kubevirt_test.go
- pkg/virt-operator/resource/apply/apps.go
- pkg/virt-operator/resource/apply/reconcile.go
- pkg/virt-operator/resource/apply/update.go
- pkg/virt-operator/resource/generate/components/deployments.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- pkg/virt-operator/webhooks/kubevirt-update-admitter.go
- staging/src/kubevirt.io/client-go/apis/core/v1/componentconfig.go
- staging/src/kubevirt.io/client-go/apis/core/v1/deepcopy_generated.go
- staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
- tests/operator_test.go
and adjust PDBs accordingly
This PR allows for configuring the number of replicas to be created for virt-api and virt-controller.
It also adjusts the PDBs accordingly, or just skips creating them if only 1 replica is requested.
```release-note
The number of virt-api and virt-controller replicas is now configurable in the CSV
```
> Make the number of replicas for virt- pods configurable

- tests/network/vmi_multus.go
Following https://github.com/kubevirt/kubevirt/pull/6331 and https://github.com/kubevirt/kubevirt/pull/6293
This PR remove the usage of `BeforeAll` in Multus tests suite.
Fixes #6123
```release-note
None
```
> Remove BeforeAll from Multus tests

- pkg/container-disk/container-disk.go
- pkg/container-disk/container-disk_test.go
- pkg/testutils/matchers.go
- pkg/virt-controller/services/template.go
- pkg/virt-controller/watch/migration.go
- pkg/virt-controller/watch/migration_test.go
- tests/migration_test.go
Manual cherrypick of https://github.com/kubevirt/kubevirt/pull/6535
```release-note
Migrations use digests to reference containerDisks and kernel boot images to ensure disk consistency
```
> [release-0.44] Reference containerDisks and kernel boot images in reproducible format during migrations

- api/openapi-spec/swagger.json
- pkg/util/status/BUILD.bazel
- pkg/util/status/status.go
- pkg/util/status/status_test.go
- pkg/virt-api/api.go
- pkg/virt-api/rest/subresource.go
- pkg/virt-api/rest/subresource_test.go
- pkg/virt-controller/watch/workload-updater/workload-updater_test.go
- pkg/virtctl/vm/vm.go
- pkg/virtctl/vm/vm_test.go
- staging/src/kubevirt.io/client-go/apis/core/v1/deepcopy_generated.go
- staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go
- staging/src/kubevirt.io/client-go/apis/core/v1/types.go
- staging/src/kubevirt.io/client-go/apis/core/v1/types_swagger_generated.go
- staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
- staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
- staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
- staging/src/kubevirt.io/client-go/kubecli/kv.go
- staging/src/kubevirt.io/client-go/kubecli/kv_test.go
- staging/src/kubevirt.io/client-go/kubecli/vm.go
- staging/src/kubevirt.io/client-go/kubecli/vm_test.go
- tests/operator_test.go
- tests/storage/restore.go
- tests/storage/snapshot.go
- tests/subresource_api_test.go
- tests/utils.go
- tests/vm_test.go
- tests/vm_watch_test.go
Allows user to use `--dry-run` flag for start, stop and restart virtctl command.
Passing this flag to one of these command will do all checks showing possible failures, but changes will not be effective.
Fixes #
```release-note
Users can use --dry-run flag
```
> Add dry run functionality for stop start restart commands

- pkg/virt-controller/watch/application.go
The leader election process in virt-controller was affected by the rate limiter e2e tests. Therefore we've
decided to create a separate REST client for the leader election. That client won't be affected by external
rate limiter configuration from Kubevirt CR. 
**Which issue(s) this PR fixes** 
https://github.com/kubevirt/kubevirt/pull/6364
```release-note
NONE
```
> [virt-controller]: Use separate REST client with fixed rate limiter for the leader elector

- pkg/virt-controller/watch/vm.go
- pkg/virt-controller/watch/vm_test.go
- staging/src/kubevirt.io/client-go/apis/core/v1/types.go
This PR extends the VM status field (`.status.printableStatus`) with a new `WaitingForVolumeBinding` status, reported when a VM with a PVC/DV type of volume is started, and the backing PVC is not bound. 
This PR replaces #6454 and #6605. In contrast to #6454, it avoids presenting the status as an error, as well as heuristics to detect when binding failures occur - and simply make it visible when the VM cannot start due to unbound volumes (be it a short intermediary state, or a long lasting state that requires intervention). Also, in line with the discussion in #6605, it ensures that stopped VMs don't report `WaitingForVolumeBinding` nor `Provisioning`.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …
> Add a WaitingForVolumeBinding printable status 

- pkg/virt-api/webhooks/arm64.go
- pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
- pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
- staging/src/kubevirt.io/client-go/apis/core/v1/schema.go
- tests/flavor_test.go
- tests/vmi_lifecycle_test.go
Today if a CPU model is defined by KubevirtCR it is the default CPU mode for every VMI. If it no model is defined in KubevirtCR we keep CPU model empty.
While we do set the underlying domain to host-model as a default if no model is defined in KubevirtCR (as documented in our [user-guide](https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#enabling-default-cluster-cpu-model)) it is not reflected in the VMI manifest, making it harder for other components to identify VMI's actual CPU model.
Without this change components across our code-base would have to implicitly assume that `vmi.Domain.CPU == nil` means model is host-model which is error-prone and less maintainable.
P.S. This fixes a bug that already exists in [migration.go's …
> Set default CPU model in VMI spec, even if not defined in KubevirtCR

- pkg/util/pdbs/pdbs.go
- tests/migration_test.go
This change removes stale PDBs created by virt-controller < 0.41.1 which
had minAvailable permanently set to 2.
Func test also added.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2019453
Fixes #
```release-note
remove stale pdbs created by < 0.41.1 virt-controller
```
> pdb: reconcile all old pdbs

- manifests/generated/operator-csv.yaml.in
- pkg/virt-operator/resource/generate/components/deployments.go
Remove the obsolete `scheduler.alpha.kubernetes.io/critical-pod` annotation from virt-{operator,controller,api,handler} pods. 
This annotation has been [obsoleted in 1.16](https://github.com/kubernetes/kubernetes/blob/e9ce31bcb3feb411c4de4902651e43dbb78ed151/CHANGELOG-1.16.md#deprecations-and-removals) (i.e., it doesn't have any effect, except for generating warnings when updating/patching the virt-xyz deployments), in favor of the `priorityClassName` in the PodSpec (which we already make use of, as of #3236).
Note that this has already been attempted in #5901, which didn't make it through after all.
The current PR has a much narrower scope, and is only concerned with removing the obsolete annotation.
**Release …
> Remove obsolete scheduler.alpha.kubernetes.io/critical-pod annotation

- tests/storage/storage.go
We don't wait until virt-handler sees the effects of the feature gate
change, so we often run the test with the feature gate -- adjust
the output, it also means we can run this test in parallel again so
it's a win in many regards.
[Example failure](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6745/pull-kubevirt-e2e-k8s-1.21-sig-storage/1457380399587004416). The output for blockdev fits the scenario of it being expanded to the largest possible size.
```release-note
NONE
```
> Fix sig-storage lane flakiness: Adjust output instead of disabling featuregate

- hack/whatchanged.sh
Adds a NONE release-note block to the changelog generation, thus removing the need for adding a tedious NONE release note every time kubevirtci gets bumped.
Fixes #
```release-note
```
> Add release-note NONE to the changelog generation

- pkg/virt-operator/resource/apply/apps_test.go
- pkg/virt-operator/resource/apply/reconcile_test.go
- staging/src/kubevirt.io/client-go/apis/core/v1/types.go
A recent PR (#6565) has changed the `app.kubernetes.io/managed-by` label value from `kubevirt-operator` to `virt-opertor`. This label is used as a label selector for most of the informers used by virt-operator, e.g. [here](https://github.com/kubevirt/kubevirt/blob/a7cddcc4fb5b332429978204984b1aab8ffbb720/pkg/controller/virtinformers.go#L690).
When performing an upgrade (as opposed to a clean install) to KubeVirt v0.47.0, this causes the OperatorCRD informer to drop all existing CRDs (still labeled with `kubevirt-informer`) and hence to fail to observe that they already exist --> conflict.
Fixes …
> Revert #6565: kubevirt's components managed-by label's value changed to virt-operator

- tests/storage/storage.go
Tests enable all feature gates, so these tests enable the new
online resize. The disks get expanded to the largest size, causing
disk pressure that leaks into the next running test.
[Example of failure due to disk pressure](https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.22-sig-storage/1457226507951804416/artifacts/k8s-reporter/1_pods.log).
The previous running test was "[Serial]with NFS Disk PVC using ipv4 address of the NFS pod not owned by qemu".
```release-note
NONE
```
> Fix sig-storage flakiness: Use a smaller image for test

- pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
- pkg/virt-launcher/virtwrap/api/schema.go
- pkg/virt-launcher/virtwrap/api/schema_test.go
- pkg/virt-launcher/virtwrap/converter/converter.go
- tests/vmi_configuration_test.go
This PR will always add <hints-dedicated state='on'/> which set the KVM_HINTS_REALTIME 
According to QEMU documentation guest checks this feature bit to determine that vCPUs are never
preempted for an unlimited time, allowing optimizations.
```release-note
KVM_HINTS_REALTIME will always be set when dedicatedCpusPlacement is requested
```
> Always add hint-dedicated kvm feature with dedicated cpus to allow guest optimizations 

- pkg/network/errors/errors.go
- pkg/virt-handler/vm.go
Use error type instead of a boolean to detect critical errors in the
network setup flow.
Fixes #
```release-note
NONE
```
> virt-handler, net: Simplify critical-error handling

- tools/perfscale-audit/api/api.go
- tools/perfscale-audit/metric-client/metric-client.go
Record VMI phase counts in the audit tool's report so that we have more visibility into how the test went.
Convert `resourceRequestCountsByOperation` to a range vector by using `sum`.   `sum` with `offset` will get the counter's value during last `offset` of time.
Results from creating 21 VMIs:
```bash
{
"Values": {
"CREATE-events-count": {
"value": 167
},
"DELETE-pods-count": {
"value": 21
},
"GET-configmaps-count": {
"value": 2
},
"GET-endpoints-count": {
"value": 2038
},
"GET-nodes-count": {
"value": 46
},
"LIST-cdiconfigs-count": {
"value": 4
},
"LIST-cdis-count": {
"value": 4
},
"LIST-clusterrolebindings-count": {
"value": 9
},
"LIST-clusterroles-count": {
"value": 9
},
"LIST-configmaps-count": {
"value": 251
}, …
```
> Record VMI phase counts

- cmd/virt-launcher/virt-launcher.go
Small fix: today we log "Successfully signaled graceful shutdown" even if graceful shutdown is not successful.
```release-note
virt-launcher fix - stop logging successful shutdown when it isn't true
```
> [virt-launcher]: Stop logging successful shutdown when it isn't true

- cmd/libguestfs/entrypoint.sh
- tests/storage/guestfs.go
- tests/utils.go
Solve flakiness for the libguestfs tests.
1) Use a dedicated block PVC for the test instead of the local block device. In the previous version, the test was using the [CreateBlockVolumePvAndPvc](https://github.com/kubevirt/kubevirt/blob/48c74adf169a6aac04b1c8900a4beb2e28207bd6/tests/utils.go#L2555) to create the block PVC and it was backed by [/mnt/local-storage/cirros-block-device](https://github.com/kubevirt/kubevirt/blob/48c74adf169a6aac04b1c8900a4beb2e28207bd6/tests/utils.go#L2598) this might create some conflicts as it can be scheduled only on node `node01`. Using ceph PVC can allow using a dedicated PVC for the test. 
2) Check container state if it is running instead of PodStatus == Running
3) Avoid ps to detect if the libguestfs appliance has been extracted (see Roman's …
> Solve flakiness for libguestfs tests

- tests/network/vmi_multus.go
Following https://github.com/kubevirt/kubevirt/pull/6331
This PR remove the usage of `BeforeAll` in SRIOV tests suite.
Fixes #6123
```release-note
None
```
> Remove BeforeAll from SRIOV tests

- examples/vmi-macvtap.yaml
- examples/vmi-masquerade.yaml
- examples/vmi-multus-multiple-net.yaml
- examples/vmi-multus-ptp.yaml
- examples/vmi-slirp.yaml
- examples/vmi-sriov.yaml
- tools/vms-generator/utils/utils.go
This PR replaces bash scripts with cloud-config on cloud-init user data for the kubevirt examples.
This makes the examples more portable across different VM instances.
```release-note
NONE
```
> examples, cloud-init: use cloud-config instead of bash

- tests/storage/datavolume.go
Tests enable all feature gates, so these tests enable the new
online resize. The disks get expanded to the largest size, which
is a bit slow with our NFS server and causes timeouts which show
as flakiness.
Essentially the same as #6745, but in one more case.
I missed that this is another 5Gi NFS image and assumed the previous test is causing the flakiness.
```release-note
NONE
```
> Reduce sig-storage flakiness: Use a smaller image for NFS test

- pkg/network/cache/types.go
- pkg/network/dhcp/bridge.go
- pkg/network/dhcp/configurator.go
- pkg/network/dhcp/configurator_test.go
- pkg/network/dhcp/masquerade.go
- pkg/network/dhcp/server/BUILD.bazel
- pkg/network/dhcp/server/server.go
- pkg/network/dhcp/server/server_test.go
- pkg/network/dns/resolveconf.go
- pkg/network/dns/resolveconf_test.go
- pkg/network/driver/BUILD.bazel
- pkg/network/driver/common.go
- pkg/network/setup/podnic.go
- tests/network/BUILD.bazel
- tests/network/vmi_subdomain.go
- tests/windows_test.go
**What this PR does / why we need it:**
Kubevirt supports k8s subdomain feature (https://github.com/kubevirt/kubevirt/pull/784).
Since k8s doesn't update `/etc/resolv.conf` with the subdomain [1],
a VM can't resolves its own DNS / FQDN because the subdomain is missing as part of the FQDN.
This PR adds the missing subdomain to the search list (via DHCP option 119),
This way the FQDN can be resolved to
`vm_name.subdomain.namespace.svc.cluster_domain` as given by k8s.
Option 15 is affected as well, because option 15 takes the longest of `searchDomains`
which is now the one with subdomain.
In order to have the DNS entry added by k8s,
a headless service in the same namespace of the VMIs should exists.
It should be named as the subdomain.
The service should have a selector matching the VMIs in …
> virt-launcher, Add subdomain name to search list

- pkg/virt-handler/vm.go
- pkg/virt-handler/vm_test.go
In order to avoid network setup on phase 1 to be executed more than
once, a cache check exists. This "cache" uses the VMI UID as the key and
the virt-launcher PID as the value.
There is no apparent reason to include the PID and validate it did not
changed over time. If the virt-launcher terminates, a full teardown is
expected to occur, including this cache cleanup for the specific VMI.
Therefore, this change removes the PID usage in the cache.
Fixes #
This is a preliminary change to allow further refactoring to the network code base.
It is introduced in a …
> virt-handler, net: Drop virt-launcher pid usage in cache

- pkg/virt-launcher/virtwrap/live-migration-source.go
- tests/migration_test.go
It is suspected that migration bandwidth limitation was not applied since was overriden by test entry that overrides MigrationConfigurations.
> Fix migration limitation for test_id 5004

- tests/libvmi/network.go
- tests/network/primary_pod_network.go
- tests/network/services.go
- tests/network/vmi_subdomain.go
This PR extends the function that creates network interfaces with bridge binding to receive a "name" parameter.
This PR will improve code readability of PR #6766
Fixes #
```release-note
NONE
```
> tests, network: Add param to libvmi.InterfaceDeviceWithBridgeBinding

- pkg/virt-controller/watch/migration.go
- pkg/virt-controller/watch/migration_test.go
- staging/src/kubevirt.io/api/core/v1/types.go
- tests/migration_test.go
This solves the issue where migrations can get stuck indefinitely when a migration target pod is unschedulable.
In the future, we may want to expand this logic to include any other situations we encounter where a migration can get stuck indefinitely as well.
```release-note
Pending migration target pods timeout after 5 minutes when unschedulable
```
> Timeout Unschedulable Migration Target Pods

- staging/src/kubevirt.io/api/README.md
Add a README which will be synchronized to `kubevirt.io/api` whenever we call `hack/publish-staging.sh`.
Fixes #
```release-note
NONE
```
> Document client-gen usage for thirt party integration

- tests/network/vmi_multus.go
Following #6318 
We see macvtap test failures due to timeout of reporting the macvtap interface IP address
for a while now [1] [2] [3].
This PR increase the time we wait for it to be reported.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6267/pull-kubevirt-e2e-k8s-1.21-sig-network/1432264444922040320
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6312/pull-kubevirt-e2e-k8s-1.21-sig-network/1432303029054345216
[3] https://search.ci.kubevirt.io/?search=should+have+managed+to+figure+out+the+IP+of+the+server+VMI&maxAge=336h&context=1&type=all&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
**Which issue(s) this PR …
> Fix flaky Macvtap test: Increase macvtap interface IP report timeout

- tests/network/vmi_multus.go
Bridge CNI now supports MAC spoof check feature, which permits outbound
communication only to MAC addresses it knows.
In our context, with this feature enabled - a VM connected to a bridge CNI
can only send data through it - if its MAC address hasn't changed from
its initialization (supplied by the user or by the system).
This PR requires PR kubevirt/kubevirt#6774
Fixes #
The NetworkAttachmentDefinition used in the test uses 'cnv-bridge'
(deployed by CNAO), since containernetworking plugins haven't yet released …
> tests, multus: Add integration test for bridge CNI MAC spoof check

- cmd/virt-launcher/virt-launcher.go
The 10 second timeout is too long and may cause the launcher to
not terminate for longer than necessary.
Shortening the timeout to 2 seconds for http get requests, which
should be more than enough.
With this change, in the worst case scenario, the detection would
take at most 8 seconds (4*2) plus a few ms for jitter.
- https://bugzilla.redhat.com/show_bug.cgi?id=2017255
-->
```release-note
Shorten timeout for Istio proxy detection
```
> virt-launcher: decrease timeout for http get when detecting Istio

- tests/migration_test.go
DV is not referring to outer scope variable in BeforeEach(), instead it creates a new DV bounded to BeforeEach() sope.
This is wrong since in the AfterEach() block the DV is checked to be nil, if it is nil it's being deleted. Since we don't ever
re-assign the dv variable it is never freed (since it's always nil).
```release-note
NONE
```
> Fix DV not being deleted in AfterEach()

- pkg/virt-controller/watch/migration.go
- pkg/virt-controller/watch/vmi.go
If nodes on a cluster are updated, it is possible that features will be removed (e.g. TSX flag removed for Intel CPUs). It could be that a currently running VMI might have nowhere that it could be migrated. In this unfortunate case, it could actually be possible to block an update from proceeding (without rebooting all running VMs, possibly more than once).
This situation should result in an alert.
This alert is being fired at migration time if Migration is pending, VMI uses host-model and no other node is suitable to perform the migration.
```release-note
alert if migration for VMI with host-model CPU is stuck since no node is suitable
```
> alert if migration for VMI with host-model CPU is stuck since no node is suitable

- tests/infra_test.go
Test with id 4099 and 4100 are not waiting for VMI to come up. 
Therefore console connection is attempted sooner than it could succeed.
Fixes #
Connection timeout seems to be high(180sec) but I can see the connection to virt-handler is established just before the timeout and therefore failing the test. 
```release-note
None
```
> Fix certificate rotation tests

- tests/template_test.go
Manual cherry-pick of #6471 
```release-note
NONE
```
> [release-0.41] Ensure that the BeforeTest function is actually called

- pkg/controller/controller_ref_manager.go
- pkg/virt-api/rest/subresource.go
- pkg/virt-controller/watch/migration.go
- pkg/virt-controller/watch/migration_test.go
- pkg/virt-controller/watch/node.go
- pkg/virt-controller/watch/node_test.go
- pkg/virt-controller/watch/replicaset_test.go
- pkg/virt-controller/watch/vm.go
- pkg/virt-controller/watch/vm_test.go
- pkg/virt-controller/watch/vmi.go
- pkg/virt-controller/watch/vmi_test.go
- staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
- staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
- staging/src/kubevirt.io/client-go/kubecli/vmi.go
- tests/utils.go
- tests/vm_test.go
Fix a bug that occurs when a user uses both `--dry-run` and `--grace-period=<value>` in `stop` virctl command. It causes the patch of the vmi with the given grace-period which should not happen according to the dry-run specification. This happens due to a missed propagation of the DryRun value in the patch of the VMI, which occurs only when also grace-period is given
Fixes #
```release-note
Add PatchOptions to the Patch request of the VirtualMachineInstanceInterface
```
> Fix dry run using stop virctl command with grace-period

- tests/vm_test.go
**What this PR does / why we need it**: `Add test_id for Error status when missing PVC or DV`
Fixes #
```
NONE
```
> Add test_id for Error status when missing PVC or DV

- tests/migration_test.go
Remove MigrationsConfiguration argument from test table. Instead only pass mode and update current config accordingly.
```release-note
NONE
```
> [test_id:5004]: Update migration configurations correctly

- api/openapi-spec/swagger.json
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/api/core/v1/schema.go
- staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
- staging/src/kubevirt.io/client-go/api/openapi_generated.go
Fix small typo in kernel boot description.
This PR https://github.com/kubevirt/kubevirt/pull/6823 already did so but the creator decided to close it.
```release-note
NONE
```
> Fix kernel boot description typo

- staging/src/kubevirt.io/client-go/kubecli/vmi.go
Some auth plugins seem to trip over a hil header field.
Fixes #6607
```release-note
Fix a nil pointer in virtctl in combination with some external auth plugins
```
> [virtctl] Initialize the Headers field for some auth plugins

- tests/migration_test.go
Signed-off-by: Denys Shchedrivyi dshchedr@redhat.com
Since the default CPU mode for VMs is "host-model" (recently merged #6721), let's update migration test accordingly: remove the explicit "host-model" setting and check migration with default cpu mode. It may help to catch the issue if someone changes the default CPU value.
Fixes #
```release-note
NONE
```
> Update test (test_id:6981) - Check migration of VM with the default CPU instead of explicitly set 'host-model'

- pkg/util/pdbs/pdbs.go
- tests/migration_test.go
This is a manual cherry-pick of #6723
Fixes #
```release-note
remove stale pdbs created by < 0.41.1 virt-controller
```
> [release-0.41] pdb: reconcile all old pdbs

- hack/sync-kubevirtci.sh
When fetching kubevirtci over the old url we get a 404, so we change the
url to the one we get from the tags page. Also we add fail flag.
Fixes #
See https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-bump-kubevirt/1464247383884828672
```release-note
NONE
```
> Fix kubevirtci download url

- pkg/virt-handler/rest/lifecycle.go
These functions in virt-handler don't return when errors are encountered, which leads to the potential of using null pointer objects.
For example
```
client, err := cmdclient.NewClient(sockFile)
if err != nil {
log.Log.Object(vmi).Reason(err).Error("Failed to connect cmd client")
response.WriteError(http.StatusInternalServerError, err)
}
err = client.PauseVirtualMachine(vmi)
```
the `client` here is nil, but since we don't return in the `if err != nil` if block, we attempt to dereference the nil pointer. 
```release-note
NONE
```
> Fix null pointer dereference in virt-handler

- tests/infra_test.go
- tests/storage/guestfs.go
Guestfs test by https://github.com/kubevirt/kubevirt/pull/6739
Controller rate limiter test fixed by https://github.com/kubevirt/kubevirt/pull/6726
```release-note
NONE
```
> Remove now stable tests from quarantine

- manifests/generated/operator-csv.yaml.in
- manifests/generated/rbac-operator.authorization.k8s.yaml.in
- pkg/controller/conditions.go
- pkg/virt-api/rest/subresource.go
- pkg/virt-api/rest/subresource_test.go
- pkg/virt-controller/services/template.go
- pkg/virt-controller/watch/vmi.go
- pkg/virt-controller/watch/vmi_test.go
- pkg/virt-operator/resource/generate/rbac/controller.go
- staging/src/kubevirt.io/api/core/v1/types.go
- tests/pausing_test.go
- tests/vm_test.go
- tests/vm_watch_test.go
This PR marks VMIs as unready when they are paused.
This is done by adding a custom pod condition to the virt-launcher pod, which serves as a [readiness gate](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-readiness-gate).
The condition's value is toggled according to whether the VMI is paused or not, which sets the virt-launcher as unready when the condition value is false. The pod readiness condition is then synced back to the VMI and the VM for proper reporting.
This also ensures that service-fronted VMs aren't targeted with service traffic when they are paused.
Fixes …
> Mark paused VMs as unready

- automation/git-askpass.sh
- automation/release.sh
- hack/gen-swagger-doc/deploy.sh
- hack/publish-staging.sh
We had to switch off Travis CI a while back due to leaked credentials, and then we never bothered to update the release automation. This PR backports the release job automation scripts from main to 0.36 branch, so we can do releases without Travis using the postsubmit job working on release tags.
Requires mentioned postsubmit to get adjusted to work for 0.36: https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml#L42
Fixes #
/cc @rmohr 
```release-note
Backport prow …
```
> [release-0.36] Backport prow release automation changes from 0.40

- pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
- pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
- pkg/virt-controller/watch/snapshot/restore.go
- tests/operator_test.go
- tests/storage/restore.go
This point of this PR was to add vmsnapshots and restore to upgrade test to try and catch upgrade failures with snapshots.
During the work on the test found a bug in the restore process which fails if the vm had RunStrategy and not Running field (they are mutually exclusive) and some other small fixes.
Fixes #
```release-note
fix restore of VM with RunStrategy
```
> vm restore fixes + add snapshots and restore to kubevirt upgrade test

- pkg/virt-operator/resource/generate/components/crds.go
- tests/kubectl_test.go
In a large scale environment one may find a lots of VMIM resources. When it comes to CLI it is a tedious
task to manually determine the phase of each such resource and the VMI related to it.
Therefore we expose the VMI and PHASE columns
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2017802
```release-note
Added PHASE and VMI columns for the 'kubectl get vmim' CLI output
```
> [migrations]: add phase and VMI name to the VMIM CLI output

- pkg/virtctl/root.go
- pkg/virtctl/templates/templates.go
virtctl was writing errors to stdout so errors couldn't be differentiated from regular output
Fixes #
```release-note
virtctl errors are written to stderr instead of stdout
```
> Write virtctl errors to stderr

- pkg/virt-operator/resource/generate/components/prometheus.go
Adds a severity (warning) to the alert that fires after workloads  are not updated over 24 hours. 
```release-note
NONE
```
> Add severity for outdated workload alert

- hack/common.sh
- hack/functests.sh
- tests/flags/flags.go
- tests/operator_test.go
- tests/utils.go
This PR adds an important test case that simulates a KubeVirt upgrade scenario performed by upgrading the virt-operator itself.
This, in addition to the existing test that performed the upgrade by patching the KubeVirt CR with the desired release (while maintaining the virt-operator at its current version), covers the [two upgrade scenarios documented in the user guide](https://kubevirt.io/user-guide/operations/updating_and_deletion/#updating-kubevirt-control-plane).
The goal is to be able to catch virt-operator bugs the surface only when the operator itself is upgraded, e.g. #6763.
Fixes #6785 …
> Add test to verify virt-operator release upgrade

- pkg/virtctl/imageupload/imageupload.go
- tests/storage/imageupload.go
This PR adapts the tests to run in environments without ceph. It fixes CI failures in cgroup v2 periodic job: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-cgroupsv2/1464383532250959872
Additionally the PR fixes `virtctl image-upload` command with `--force-bind` flag: previously the flag wan't checked for DataVolumes causing an error if the phase was `WaitForFirstConsumer` (while the flag description states that WaitForFirstConsumer logic is supposed to be ignored) .
Fixes #
```release-note
NONE
```
> Fix image upload with force-bind flag

- tests/network/vmi_multus.go
We see errors on CI due to cloud-init fails to configure the SR-IOV network interface name on connectivity tests because its not valid [SearchCI](https://search.ci.kubevirt.io/?search=sriov-link-enabled%3A+Unexpected+error+while+running+command.&maxAge=336h&context=2&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job).
This PR rename the SR-IOV test network interfaces to valid one.
Fixes #
Network interface name length can be up to 15 characters.
```release-note
NONE
```
> tests, SR-IOV: Shorten tests SR-IOV NIC name

- pkg/virtctl/ssh/native.go
- pkg/virtctl/ssh/ssh.go
- pkg/virtctl/ssh/wrapped.go
If there is no RSA key present at the default location and the
authentication with RSA was not explicitly requested, just skip it and
directly go to password authentication.
In contrast to that when a path for the RSA key was provided, fail loud
if the remote side allows RSA authentication.
Fixes #
```release-note
Skip SSH RSA auth if no RSA key was explicitly provided and not key exists at the default location
```
> [virtctl] Make virtctl ssh work if no id_rsa file is present

- Makefile
- hack/build-manifests.sh
GO_BUILD env var becomes redundant and it can be dropped.
**What this PR does / why we need it**: Just a small cleanup in the build scripts.
Fixes #
**Special notes for your reviewer**: N/A
```release-note
NONE
```
> Use KUBEVIRT_NO_BAZEL env var instead of GO_BUILD

- tests/network/vmi_networking.go
We have not added a skip to this test. Due to that, it fails conformance
test runs on clusters that are not enabled with dual-stack.
Fixes #
```release-note
NONE
```
> Skip IPv6 outside connectivity test on non-IPv6

- tests/reporter/kubernetes.go
With this PR test suite reporter will dump cluster nodes and virt-launcher pods `/dev/vfio/` content status from failing tests
and save them at `artifacts/network/nodes` and `artifacts/network/pods` respectively.
Having those logs will help debugging failing tests due to VM's that fail to start because missing permissions to `/dev/vfio/vfio`.
Fixes #
This PR changes will help with working on #6771
```release-note
NONE
```
> tests suite reporter: Dump vfio devices mode

- hack/publish-staging.sh
Generate the pseudo version for kubevirt.io/api which is used in kubevirt.io/client-go the correct way to avoid `go mod` errors due to a wrong timestamp in the pseudo version.
Fixes #
```release-note
NONE
```
> Fix pseudo version generation for kubevirt.io/api

- tests/migration_test.go
**What this PR does / why we need it**: `Add test_ids for reconcile all old PDBs test`
Fixes #
```
NONE
```
> Add test_ids for reconcile all old PDBs test

- pkg/container-disk/container-disk.go
- pkg/virt-controller/services/template.go
- pkg/virt-controller/services/template_test.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/6589
Fixes #
```release-note
NONE
```
> [release-0.44] Pre-pull custom kernel / initrd as an init container

- pkg/virt-config/BUILD.bazel
- pkg/virt-config/configuration.go
- pkg/virt-config/configuration_test.go
As part of #6784 , many configuration unit tests were lost. This PR restored these tests, removes the non-relevant tests and mostly, transforms the configMap related tests to KubeVirt Config tests.
Some test case are not relevant because there is no need to translate strings to configuration values, as was done with the configMap.
On the other hand, some test cases are commented out with TODO, because they checks an invalid values that seem to not been forced now.
Fixes # …
> Restor the missing unit tests for configurations after dropping the configMap

- hack/builder/build.sh
- hack/builder/publish.sh
- hack/common.sh
- hack/dockerized
- hack/func-tests-image.sh
- hack/prom-rule-ci/verify-rules.sh
- hack/release.sh
This PR uses `determine_cri_bin()` function, which is now defined in `hack/common.sh` to dynamically discover right CRI to use if `KUBEVIRT_CRI` environment variable is not defined. Also, all hard-coded `docker` calls under `hack/` directory are now replaced with `${KUBEVIRT_CRI}`.
This allows Kubevirt developers to be able to develop either in Podman or in Docker to their choosing.
PR is tested to being able to perform `make` and `make test` in an environment without docker installed and without defining `KUBEVIRT_CRI` explicitly.
Note: `make cluster-up` and `make cluster-sync` are still not supported. In order to support Podman there as well further changes in CI are required (for example, …
> Add full Podman support for `make` and `make test` instead of hard-coded docker

- tests/migration_test.go
Sometimes node has qemu process which is defunct.
(probably from previous test)
Therefore we filter out these processes to only match
the incoming domain from migration.
Fixes #
```release-note
NONE
```
> Fix test: Kill virt-handler only if the VM exist

- pkg/virt-launcher/virtwrap/BUILD.bazel
- pkg/virt-launcher/virtwrap/device/hostdevice/BUILD.bazel
- pkg/virt-launcher/virtwrap/device/hostdevice/hotplug.go
- pkg/virt-launcher/virtwrap/device/hostdevice/hotplug_test.go
- pkg/virt-launcher/virtwrap/device/hostdevice/sriov/BUILD.bazel
- pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
- pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev_test.go
- pkg/virt-launcher/virtwrap/live-migration-source.go
- pkg/virt-launcher/virtwrap/manager.go
Extract the hot(un)plug code from the SR-IOV package to allow its usage
by the other hostdevice types.
Fixes #
```release-note
NONE
```
> virt-launcher, hostdev: Extract hot(un)plug from SR-IOV

- pkg/network/vmispec/BUILD.bazel
- pkg/network/vmispec/interface.go
- pkg/network/vmispec/interface_test.go
- pkg/network/vmispec/network.go
- pkg/network/vmispec/vmispec_suite_test.go
- pkg/virt-handler/BUILD.bazel
- pkg/virt-handler/vm.go
Extract most of the network validation logic that is done on migration to
check if it is allowed to perform the operation.
The code is moved under the network package.
Fixes #
```release-note
NONE
```
> virt-handler, net: Extract migration validation logic

- api/openapi-spec/swagger.json
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/api/core/v1/schema.go
- staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
- staging/src/kubevirt.io/client-go/api/openapi_generated.go
Signed-off-by: Helene Durand <helene@kubermatic.com>
This PR fixes 2 small typos in the API comments. Why is it needed? If you use this APIs to generate some swagger, and swagger clients and use some codespell to check the spelling, there are 2 spelling errors in the generated client code files.
Fixes #
```release-note
NONE
```
> Fix some typos in API comments

- hack/ci/Dockerfile.ci
mirror.openshift.com is retired, let's avoid referencing it.
```release-note
NONE
```
> Update openshift mirror URL to working one

- hack/perftests.sh
Increase the period of time the audit tool will measure.
```release-note
NONE
```
> Increase perf test buffer

- pkg/virtctl/expose/BUILD.bazel
- pkg/virtctl/expose/expose.go
- pkg/virtctl/expose/expose_test.go
The default `IPFamilyPolicyType` value for a service is `SingleStack`.
When multiple `IPFamily`s are provided, on k8s-1.23, this value is not
valid. As such, an appropriate backwards-compatible value is provided
on those scenarios.
Fixes #
```release-note
Update the `virtctl` exposed services `IPFamilyPolicyType` default to `IPFamilyPolicyPreferDualStack`
when multiple `IPFamily` are requested.
```
> services, ip-family-policy: valid default for multiple IP families

- pkg/virt-controller/watch/migration.go
Right now it looks like a migration is silently being ignored when global migration limits are hit. This makes it difficult to debug issues that occur in production when these limits are hit.
This PR simply adds visibility so we at least get log messages indicating when a migration limit is encountered by the migration controller. 
```release-note
NONE
```
> Add logs indicating when global migration limits are hit

- tests/pool_test.go
Quarantines flaky test `[sig-compute]VirtualMachinePool [Serial]pool should scale to five, to six and then to zero replicas`
Recent failures:
* https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6872/pull-kubevirt-e2e-k8s-1.20-sig-compute/1470946633758806016
* https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6938/pull-kubevirt-e2e-k8s-1.20-sig-compute/1470405597735161856
* https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6884/pull-kubevirt-e2e-k8s-1.21-sig-compute/1470331708149600256
* https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6399/pull-kubevirt-e2e-k8s-1.21-sig-compute/1469626039406694400
Quarantines flaky test …
> Quarantine flaky sig-compute tests for VMPool

- api/openapi-spec/swagger.json
- manifests/generated/operator-csv.yaml.in
- manifests/generated/rbac-operator.authorization.k8s.yaml.in
- pkg/virt-api/rest/BUILD.bazel
- pkg/virt-api/rest/definitions.go
- pkg/virt-controller/watch/application.go
- pkg/virt-operator/resource/generate/rbac/controller.go
This fixes the following issues with VMPools.
- fixes vmpool controller event error caused by not registering vmpool with controller's schema
- fixes OpenShift error ```cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on``` caused by virt-controller not have rbac for vmpool finalizers
- Adds vmpool to discovery definitions
```release-note
NONE
```
> VMPool bug fixes

- tests/operator_test.go
Test has had more than 20% failures in the last two days.
Source: https://search.ci.kubevirt.io/?search=test_id%3A4744&maxAge=48h&context=1&type=junit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Recent failures:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6933/pull-kubevirt-e2e-k8s-1.20-operator/1471742758426251264
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6933/pull-kubevirt-e2e-k8s-1.21-operator/1471742758359142400
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6933/pull-kubevirt-e2e-k8s-1.20-operator-nonroot/1471742758514331648
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6933/pu …
> Quarantine test_id:4744 due to flakiness

- automation/test.sh
- hack/check-unassigned-tests.sh
- hack/cluster-deploy.sh
- tests/BUILD.bazel
- tests/monitoring/BUILD.bazel
- tests/monitoring/monitoring.go
- tests/monitoring/prometheus_utils.go
- tests/tests_suite_test.go
- tests/utils.go
We have many metrics&alerts but we don't have tests which run with real Prometheus. This PR adds a new lane and a test case as an example. We will add more tests for alerts in time. 
Corresponding change in project-infra: https://github.com/kubevirt/project-infra/pull/1790
```release-note
Add a new lane for monitoring tests
```
> Add sig-monitoring lane

- pkg/controller/virtinformers.go
- pkg/virt-operator/resource/apply/apps_test.go
- pkg/virt-operator/resource/apply/reconcile.go
- pkg/virt-operator/resource/apply/reconcile_test.go
- pkg/virt-operator/util/types.go
- staging/src/kubevirt.io/api/core/v1/types.go
- tests/operator_test.go
Changed 'managed-by' label's value of kubevirt components to be 'virt-operator'
instead of 'kubevirt-operator', since the operator name is virt-operator.
we need it because the value 'kubevirt-operator' could be misleading.
A similar PR has been approved (#6565 ) and it caused failure on update( #6763 ),
This PR consider the update.
Fixes #
To test if this PR handle update i simulated an updated from 0.46.1 to this branch and verified with `kubevirt logs <operator's name> -n kubevirt`
```release-note
'kubevirt-operator' changed to …
```
> kubevirt's components managed-by label's value changed to virt-operator 

- tests/reporter/kubernetes.go
With this PR test suite reporter will collect cloud-init logs from guest VM's from failing tests
and save them at `artifacts/cloud-init/vmis`.
Having those logs will help debugging failing tests due to cloud-init configuration failures.
Fixes #
This PR changes will help with working on https://github.com/kubevirt/kubevirt/issues/6776
```release-note
NONE
```
> tests suite reporter: Collect guest VM cloud-init logs

- pkg/virt-controller/watch/migration.go
- pkg/virt-controller/watch/migration_test.go
- tests/migration.go
- tests/migration_test.go
This is PR to fix a bug this PR: https://github.com/kubevirt/kubevirt/pull/6773. 
This PR fixes a bug that caused alert for unschedulable host-model VMIs to trigger.
Two bugs are now fixed:
- In `alertIfHostModelIsUnschedulable()` function, which scans all nodes to check whether one or more nodes support the VMI host model and cpu required features, the source node is now skipped. If the source node is not skipped, it is always found to be suitable, obviously.
- In `isNodeSuitableForHostModelMigration()` function, iterate on Pod's `NodeSelector`, not `Labels`.
In addition, the PR includes several improvements:
- Introduces unit and functional test
- Moves logic to `handlePendingPodTimeout()` which already deals with unschedulable migration target …
> [Bug fix]: Unscheduable host-model VMI alert is not triggered 

- pkg/virtctl/imageupload/imageupload.go
- pkg/virtctl/imageupload/imageupload_test.go
- tests/storage/imageupload.go
- tests/utils.go
Fixes #
this should be merged after PR: https://github.com/kubevirt/containerized-data-importer/pull/1969 is merged,
released and CDI version is bumped in kubevirt
```release-note
Use virtctl image-upload to upload archive content
```
> Add archive upload option to image upload command

- OWNERS_ALIASES
Zvi has been committing quality code and code reviews for quite some time now across the kubevirt/kubevirt repo. I'd like to sponsor him as an approver.
Per out guidelines [here](https://github.com/kubevirt/community/blob/main/membership_policy.md#approver) We need one more approver to sponsor Zvi in addition to myself.
```release-note
NONE
```
> Add Zvi maintainer

- api/openapi-spec/swagger.json
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/api/migrations/v1alpha1/deepcopy_generated.go
- staging/src/kubevirt.io/api/migrations/v1alpha1/types.go
- staging/src/kubevirt.io/api/migrations/v1alpha1/types_swagger_generated.go
- staging/src/kubevirt.io/client-go/api/openapi_generated.go
The option to disable TLS in Migration Policies (https://github.com/kubevirt/kubevirt/pull/6399) is part of Migration Policies since it's also part of MigrationConfigurations in KubevirtCR.
This option was added to KubevirtCR since disabling TLS was supposed to provide a performance boost. After testing, it seems that disabling TLS does not provide any such boost, therefore disabling has no benefit and makes cluster less secure.
For these reasons it needs to be removed from MigrationPolicy CRD.
```release-note
Remove disabling TLS configuration from Live Migration Policies
```
> Remove disabling TLS option from Migration Policies

- manifests/testing/disks-images-provider.yaml.in
Server needs to run as root to be able to access
configuration.
Some platforms defaults container uid if its not set.
Fixes #
```release-note
NONE
```
> [release-0.41] Ensure cdi-http-import-server is running as root

- manifests/testing/disks-images-provider.yaml.in
Server needs to run as root to be able to access
configuration.
Some platforms defaults container uid if its not set.
Fixes #
```release-note
NONE
```
> [release-0.44] Ensure cdi-http-import-server is running as root

- hack/prom-rule-ci/prom-rules-tests.yaml
- pkg/virt-operator/resource/generate/components/prometheus.go
We want to be able to list all kubevirt alerts so we added labels to
differentiate them.
Signed-off-by: assafad <aadmi@redhat.com>
```release-note
Added common labels into alert definitions
```
> Add common labels into alert definitions

- pkg/virt-controller/watch/vm.go
This PR refactors VM controller by extracting some logic from main functions (like `updateStatus()`) to helper functions where it makes sense. This should cause the code to be easier to read and understand.
No behavior is changed - code is only moved around to helper functions.
```release-note
NONE
```
> Refactor VM-controller: extract logic to functions

- pkg/virtctl/ssh/BUILD.bazel
- pkg/virtctl/ssh/ssh_suite_test.go
- pkg/virtctl/ssh/ssh_test_suite.go
- pkg/virtctl/ssh/wrapped.go
- pkg/virtctl/ssh/wrapped_test.go
This PR will increase our test value and test coverage and reach our goal of 73% coverage.
```release-note
NONE
```
> Add unit tests for wrapped.go

- pkg/virt-controller/watch/snapshot/restore.go
New annotation added to PVCs in 1.23.  Has to be removed when creating restore PVC def.
See failure run here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6947/pull-kubevirt-e2e-k8s-1.23-sig-storage/1470770667963027456
Fixes #
```release-note
NONE
```
> k8s 1.23 storage lane fix

- Makefile
`prom-rule-dumper` binary is being built and run when performing `make prom-rules-verify` to verify (or "unit test") Prometheus rules. This is also being run by `pull-kubevirt-prom-rules-verify` lane.
Currently when performing a verification the executable is not being deleted. This is unintended as it can be added to one of the commits by mistake (as happened [here](https://github.com/kubevirt/kubevirt/pull/6956#issuecomment-999048809)). Now this binary is being automatically removed after verification.
The other alternative to deal with this is to add it to `.gitignore`. While possible I don't think it's a better approach since Prometheus rule verification is being done fairly rarely so the binary will be unneeded for most of the times. Also, …
> Auto delete prom-spec-dumper after verification

- tests/operator_test.go
Adds func test for configuring `VirtualMachingInstancesPerNode` (added in #6105).
This PR picks up the pending work from #6170 by @ashleyschuett (which is no longer involved in the project), and adds a tiny fix that addresses the last remaining [review comment](https://github.com/kubevirt/kubevirt/pull/6170#discussion_r681200235) (+rebase).
```release-note
NONE
```
> Add a test for configuring maxDevices on virt-handler

- pkg/virt-controller/watch/migration.go
- pkg/virt-controller/watch/migration_test.go
- pkg/virt-controller/watch/vmi.go
- tests/migration_test.go
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2017802
```release-note
generate event when target pod enters unschedulable phase
```
> [migrations]: generate event when target pod enters unschedulable phase

- pkg/network/dhcp/bridge_test.go
- pkg/network/dhcp/masquerade.go
- pkg/network/dhcp/masquerade_test.go
The subdomain was set in the DHCP config under the condition IPv6 enabled.
It is wrong, because the subdomain is not related to IPv6, and need to be
populated even if IPv6 is disabled, so in case it is specified,
the missing search domain will be added as part of IPv4 DHCP server
(which currently used by default, and always exists for masquerade interfaces).
Additional change:
Add missing subdomain unit test.
In case IPAM is enabled on bridge interface,
the subdomain should be propagated by
the bridge generator.
Fixes #
Fixes a problem of …
> network, fqdn: Fix subdomain flow

- pkg/network/netns/BUILD.bazel
- pkg/network/netns/netns.go
- pkg/network/setup/BUILD.bazel
- pkg/network/setup/netconf.go
- pkg/network/setup/netconf_test.go
- pkg/virt-handler/isolation/BUILD.bazel
- pkg/virt-handler/isolation/detector_test.go
- pkg/virt-handler/isolation/generated_mock_isolation.go
- pkg/virt-handler/isolation/isolation.go
- pkg/virt-handler/vm.go
- pkg/virt-handler/vm_test.go
The network namespace processing is extracted from the isolation
structure to its own package.
In order to support tests, the `NetConf` object can be created using
a custom `netns` factory. This is transparent to the production calls,
by providing a default factory.
No unit tests are written for the wrapping `netns` package as no logic
is exercised. It just forwards calls to the underlying `ns` external package.
Fixes #
~~Depends on #6781 , please review here only the last commit in the chain.~~
```release-note
NONE
```
> network: Extract netns execution and use it in the setup

- tests/windows_test.go
**What this PR does / why we need it**: 
tests, windows: Add bridge binding test to validate IP address
In case of bridge binding on Windows VM, DHCP server must provide
IPv4 address in proper v4 format, otherwise it will be parsed
incorrectly by the VM and as a result Windows VM will become
invisible on cluster network
This problem was fixed by issue#6448
Current test verifies that Windows VMI can be recognized by other components
in cluster
Fixes #
https://issues.redhat.com/browse/CNV-14301
See also: #6462, #6448
```release-note
NONE
```
> Windows VMI - adding bridge binding test to validate ip address

- pkg/network/setup/netstat.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/api/core/v1/types.go
Back in https://github.com/kubevirt/kubevirt/pull/1595 (from 2018), a
normalization has been added to populate the pod network iface name in
case it was missing, for compatibility reasons.
Since, another restriction was added: Only when the domain is not
reporting this iface as part of it.
As the normalization is performed now for more than 3 years and such old
virt-launchers are not expected to be supported by current
virt-handlers, this should be safer to remove.
The comment on the API, about making the iface name mandatory is also
removed, as this is known to be a valid option. Ifaces detected in the
guest by the guest-agent, with no ability to link them to an existing
network in the VMI spec will miss the name. …
> net, netstat: Remove pod network iface name normalization

- pkg/network/setup/netstat.go
Simplify the existing code that implements the cache behind the pod interface, by removing several wrappers and optimizing some parts of the logic.
Fixes #
~~Depends on #6781~~
~~Only the last 3 commits are relevant to review in this context.~~
```release-note
NONE
```
> netstat: Simplify pod interface volatile cache

- tests/reporter/kubernetes.go
there are cases when the /dev/vfio doesn't exist on
virt-launcher pod fs, which causes some noisy logs in the junit report
therefore we check if the directory exists. In case it won't there won't
be vfio-devices file in the k8s-reporter artifacts.
**Which issue(s) this PR fixes** 
https://search.ci.kubevirt.io/?search=cannot+access+%27%2Fdev%2Fvfio%27%3A+No+such+file+or+directory&maxAge=336h&context=1&type=all&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
```release-note
NONE
```
> [reporter]: do not list /dev/vfio if it doesn't exist

- pkg/util/util.go
- pkg/virt-handler/BUILD.bazel
- pkg/virt-handler/vm.go
- pkg/virt-handler/vm_test.go
- tests/migration_test.go
There is no need to migrate read-only disks. Therefore, setting the migration as Block Migration should be avoided for volumes that are used by read-only disks.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2035677
```release-note
Bugfix: Avoid setting block migration for volumes used by read-only disks
```
> [Bugfix]: Avoid setting block migration for volumes used by read-only disks

- pkg/virtctl/expose/expose.go
One cannot expose a VM that has no label. I had to read the code to
understand that that was my problem having read "missing label
information for vm: foo". I hope that the suggested text is more legible
and more in line with other error texts in this module.
```release-note
NONE
```
> virtctl expose: more legible error message

- docs/update-go-version.md
According to [this comment](https://github.com/kubevirt/kubevirt/pull/6974#discussion_r776757967) the dependency mirroring is done by our bot after the PR gets merged. Therefore it needs to be removed from the go update guide that says it's needed to be updated manually.
```release-note
NONE
```
> [Go version update guide]: Remove bullet on project-infra's mirror uploader tool

- pkg/network/setup/netstat.go
- pkg/network/setup/netstat_test.go
The VMI interfaces status has been "leaking" between update iterations, dragging along data which has the potential to be outdated.
Therefore, the interfaces status is now overridden on each update with last known data from the pod. Further processing will override some of the properties with data from the domain and guest-agent (if available).
This change also includes some small simplifications of the code, regarding the expected data arriving from the pod interface cache.
Fixes #
~~Depends on #6781 , only the last 3 commits are relevant to this PR.~~ …
> netstat: Drop dependencies between status report iterations and simplify the data collection from the pod

- pkg/virt-handler/options.go
Fix small typo: topologyToTopology() to capabilitiesToTopology()
```release-note
NONE
```
> Fix small typo: topologyToTopology() to capabilitiesToTopology()

- pkg/virt-handler/isolation/validation.go
- pkg/virt-handler/vm.go
and fix mis-uses of path instead of filepath
This is a manual cherry-pick of #6696 
```release-note
NONE
```
> [release-0.41] virt-handler: use /proc instead of virt-chroot to stat virt-launcher files

- docs/metrics.md
- hack/prom-rule-ci/prom-rules-tests.yaml
- pkg/monitoring/domainstats/prometheus/prometheus.go
- pkg/monitoring/domainstats/prometheus/prometheus_test.go
- pkg/virt-operator/resource/generate/components/prometheus.go
- tools/doc-generator/doc-generator.go
kubevirt_vmi_memory_used_total_bytes refers the amount of
memory declared in libvirt domain xml file. It is misleading.
We decided to rename it as "kubevirt_vmi_memory_domain_total_bytes".
We also think it is valuable to have a metric which gives
the amount of memory used in the VM. We define a new metric
"kubevirt_vmi_memory_used_bytes" for this purpose. It is computed as
"kubevirt_vmi_memory_available_bytes-kubevirt_vmi_memory_usable_bytes"
For all details, See  https://bugzilla.redhat.com/show_bug.cgi?id=2018925
```release-note
NONE
```
> Fix misleading domain memory metrics

- pkg/network/dns/resolveconf.go
- pkg/network/dns/resolveconf_test.go
- tests/network/vmi_subdomain.go
The default virt-launcher `dnsPolicy` is `ClusterFirst`
(unless changed via the VMI spec).
It means that k8s default search domains will be added as the first ones,
and in case the nodes have more entries, they will be appended
to the pod's search list. [1]
The current logic of adding the missing subdomain entry,
is to find the longest entry, and to add the subdomain to this entry.
In case the longest entry will be a node entry instead of the
entries that k8s added itself, the logic would fail to find
and add the subdomain to the right service domain entry.
The fix is to find the longest svc entry instead of the absolute longest entry,
which indicates it is a k8s added service entry, and to prepend this entry
with the subdomain if needed.
We search …
> network, fqdn: Fix adding subdomain search entry flow

- pkg/virt-handler/isolation/validation.go
- pkg/virt-handler/vm.go
and fix mis-uses of path instead of filepath
This is a manual cherry-pick of #6696 
```release-note
NONE
```
> [release-0.44] virt-handler: use /proc instead of virt-chroot to stat virt-launcher files

- pkg/network/infraconfigurators/masquerade.go
- pkg/network/infraconfigurators/masquerade_test.go
- pkg/network/istio/ports.go
- tests/network/vmi_istio.go
Istio by default excludes port 22 from proxying. The reason for this
exclusion is for use cases where istio proxies run on VMs, to prevent
loosing connectivity to nodes in case of misconfiguration of the proxies.
In our use case however, we're forwarding to the VM network namespace
only traffic that was proxied. Therefore, port 22 is missed as it's not
proxied.
Current implementation of this port 22 exclusion in Istio u/s doesn't
give us other option than add an exception for this port to make sure that
traffic to port 22 is forwarded to the VM.
Note: This means that traffic to 22 is not being proxied, but the same behaviour
would be with regular pods.
This is the line of code in Istio u/s that adds the port 22 exclusion: …
> Istio: Fix ssh traffic forwarding to VMIs with Istio proxy

- hack/prom-rule-ci/prom-rules-tests.yaml
- pkg/virt-operator/resource/generate/components/prometheus.go
Updated OrphanedVirtualMachineImages alert name to OrphanedVirtualMachineInstances.
The alert name is incorrect.
Fixes #
```release-note
Alert OrphanedVirtualMachineImages name was changed to OrphanedVirtualMachineInstances.
```
> Update OrphanedVirtualMachineImages alert name

- pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
- staging/src/kubevirt.io/api/core/v1/types.go
- tests/migration_test.go
- tests/vmi_configuration_test.go
This is a follow-up PR to https://github.com/kubevirt/kubevirt/pull/3144 
It will allow users to set disk cache mode to writeback
```release-note
Added Writeback disk cache support
```
> Add support for disk cache writeback

- pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
- pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
recently the e2e test id 3242 related to pod eviction become
flaky. The reason was a failure in updating the VMI object because
it was too old.
Therefore we use the patch method instead, since we want to do
only a partial update and not override the whole resource.
**Which issue(s) this PR fixes** 
[[test_id:3242] flakiness](https://search.ci.kubevirt.io/?search=test_id%3A3242&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)
As mentioned [here](https://github.com/kubevirt/kubevirt/pull/4012#discussion_r498246689), another improvement is required in the pod eviction admitter area, related to usage of client side …
> [virt-api]: replace UPDATE client method with PATCH in pod eviction admitter

- pkg/network/setup/netstat_test.go
The existing unit tests which cover the VMI interface status report is missing some realistic overall scenarios about the existing data available.
This change unifies and tries to place some rules on what is the expected data provided to the report processing.
The current netstat unit tests have been updated to reflect the
following expected behavior:
- When regular interfaces are added, this is the expected state/input:
- VMI spec interfaces and networks should be in sync with 1:1 relation.
- Domain spec is expect to reflect the VMI spec, i.e. having the same
interfaces.
- The filesystem cache should reflect the same interfaces as the VMI
spec.
- The volatile cache is optional, reflecting the same interface.
- The Guest Agent data is optional.
- …
> netstat: Update VMI interface status report unit tests

- tests/console/console.go
I hope that I understood the docstrings correctly and simplified their English.
```release-note
NONE
```
> tests, console: fix docstring

- api/openapi-spec/swagger.json
- pkg/cloud-init/cloud-init.go
- pkg/cloud-init/cloud-init_test.go
- pkg/util/hardware/BUILD.bazel
- pkg/util/hardware/hw_utils.go
- pkg/virt-launcher/virtwrap/BUILD.bazel
- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/api/core/v1/schema.go
- staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
- staging/src/kubevirt.io/client-go/api/openapi_generated.go
- tests/network/BUILD.bazel
- tests/network/vmi_multus.go
- tests/utils.go
- tests/vmi_cloudinit_test.go
- tests/vmi_configuration_test.go
So far KubeVirt didn't assign any NUMA node reference of the assigned PCI devices. This made it very hard for the guest OS users to find out the affinity of the device. I.E which vCPUs are mapped to pCPU that are aligned to the Numa node the device is in.
This is especially needed in case the vCPUs are mapped to pCPUs from various numa nodes. 
This PR will attempt to provide a list of the aligned vCPU (in case the VMI has requested dedicatedCPUPlacement) or the NUMA node number (in case the VMI has requested NUMA mapping)
Fixes #6667
```release-note
Numa information of an …
```
> Add NUMA information to config driver devices metadata

- api/openapi-spec/swagger.json
- pkg/virt-controller/watch/vmi.go
- pkg/virt-launcher/virtwrap/api/BUILD.bazel
- pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
- pkg/virt-launcher/virtwrap/api/schema.go
- pkg/virt-launcher/virtwrap/converter/converter.go
- pkg/virt-launcher/virtwrap/converter/converter_test.go
- pkg/virt-launcher/virtwrap/manager.go
- pkg/virt-launcher/virtwrap/manager_test.go
- pkg/virt-operator/resource/generate/components/validations_generated.go
- staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
- staging/src/kubevirt.io/api/core/v1/types.go
- staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
- staging/src/kubevirt.io/client-go/api/openapi_generated.go
With storage classes like NFS, HPP and local storage, the listed
status.capacity is the full underlying file system.
Using all of it for a single PVC is unexpected.
Don't expand beyond what we requested for the PVC in this scenario.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2034544
I had previously encouraged the UI to look at the VMI.Status.PersistentVolumeClaimInfo.Capacity, and because of this I think it might be wise to include the min(status.capacity, spec.requests) there instead of the current capacity, but I am unsure - it might be confusing due to the name of the fields.
```release-note
When expanding disk images, take the minimum between the request and the capacity - avoid using the …
```
> Limit ourselves to expanding to min(spec.request, status.capacity)

- tests/tests_suite_test.go
This PR addresses problems when running kubevirt e2e tests while using `KUBEVIRT_PROVIDER=external`. In that case a registry:5000 is normally not available, so the vm-generator needs to get passed the source registry from which to pull the utility images that we use for the tests. 
In oder to work for other image registries pointed at by
`--utility-container-prefix` and `--container-tag` when testing
we need to pass through that test flag to the vms-generator
which is used in the tests.
Fixes #
/cc @akalenyu @iholder-redhat 
```release-note …
```
> Pass through docker prefix and tag for vms-generator

- tests/network/vmi_infosource.go
The test that updates mac, was missing an assertion
that the IP should not be reported for the interface
that is derived from the domain spec.
Add also an assert that the interface with the new mac do have ip.
Fixes #
```release-note
None
```
> network, mac update test: Add assertion of the expected status

- hack/perftests.sh
- tests/performance/BUILD.bazel
- tests/performance/density.go
I noticed after the func test runs, the namespace used by the density test gets cleaned up.  That could be why we're seeing inconsistent results for the density test.  So instead of calling the audit tool after the func test runs, call it from inside the func test.   Calling from inside the func tests makes sense for future tests too since we'll want to call perf audit `afterEach` test.
```
------------------------------
• [SLOW TEST:89.300 seconds]
[sig-performance][Serial] Control Plane Performance Density Testing
tests/performance/framework.go:57
Density test
tests/performance/density.go:68
[small] create a batch of 20 VMIs
tests/performance/density.go:72
should sucessfully create all VMIS
tests/performance/density.go:73
------------------------------ …
```
> Trigger audit from inside the performance test

- tests/realtime/realtime.go
- tests/storage/storage.go
- tests/utils.go
On any reasonable system, /usr/bin/bash and /bin/bash are one and the same. Using both confuses the user to think that the differentiation matters.
```release-note
NONE
```
> tests: drop redudant UsrBinBash constant

- tests/tests_suite_test.go
The filenames need to be separate for the test processes that are
started so they don't overwrite each other. This needs to be done for
both the junit result files and the polarion result files.
Fixes #
```release-note
NONE
```
> Adjust file names to use parallelnode

- tests/storage/datavolume.go
- tests/storage/imageupload.go
- tests/storage/restore.go
- `should correctly handle eventually consistent DataVolumes`
Unless we specify a local registry (: separator), docker urls will continue to be parsed
as docker.io/${REPO}. This makes this test flow fail on an environment where we supply an external registry,
such as quay.io/kubevirt.
- `virtctl image-upload archive tests`
As these are not storage class specific, we need to force bind on env's
where the storage is WaitForFirstConsumer.
- Graceful termination in restore tests
We are stopping the VM right after calling sync() syscall, which does not guarantee finish upon return:
`The writing, although scheduled, is not necessarily complete upon return from sync().`
Need to be a little more cautious here because otherwise we end up with messed fs:
```bash
$ df -h
Filesystem …
```
> Adjust some storage tests to respect different environment

- pkg/virtctl/root.go
- pkg/virtctl/vm/vm.go
- pkg/virtctl/vm/vm_test.go
- tests/migration_test.go
Fixes #
```release-note
The command `migrate_cancel` was added to virtctl. It cancels an active VM migration.
Usage: `virtctl migrate_cancel vmname`
```
> Virtctl: cancel migrate

- tests/flags/flags.go
- tests/operator_test.go
Improve current test code for kubevirt release update test:
- allow to specify previous utility container registry and tag: it is possible that the utility containers for previous test release are in different repo from flags.PreviousReleaseRegistry, and have different tagging rules
- fix minor test issues about shasum when kubevirt infrastructure pod uses tags only (KUBEVIRT_ONLY_USE_TAGS enabled and -skip-shasums-check used in test flags)
Fixes #
```release-note
NONE
```
> Improve kubevirt update test

- tests/utils.go
Move DataVolume creation into a single auxiliary function. This makes it clearer to the reader to tell the difference between `NewRandomDataVolumeWithRegistryImportInStorageClass` and `NewRandomBlankDataVolume` (the difference is only the dv source).
This PR drops a needlessly-public constant `TestDataVolumeName` as it becomes an internal implementation detail of a single helper function.
```release-note
NONE
```
> tests, utils: coalesce datavolume creation functions

- tests/storage/storage.go
Extend the scope of the check for the HostDisk feature gate to more
tests.
Signed-off-by: Denis Ollier <dollierp@redhat.com>
Fixes #
```release-note
NONE
```
> [release-0.41] Manual backport of 'tests: fix skipping of HostDisk tests'

- tests/vmi_configuration_test.go
Most guest agent tests can run in parallel. Only a small set (which
keeps Serial) needs to change cluster settings. This runs 8 more tests in parallel.
Fixes #
```release-note
NONE
```
> Run guest agent e2e tests in parallel

- tests/config.go
- tests/conformance-config.json
- tests/default-ceph-config.json
- tests/default-config.json
- tests/migration_test.go
- tests/storage/datavolume.go
- tests/storage/hotplug.go
- tests/storage/imageupload.go
- tests/storage/storage.go
- tests/utils.go
This is a PR to continue the work in PR #6936 and PR #7010 the first commit is all the code in those PRs since it rely on those changes.
This PR removes the configuration of hostpath storage class since it is confusing and not needed specifically.
Fixes #
```release-note
NONE
```
> Improve functests usage of storage (part 3)

- pkg/virt-launcher/virtwrap/device/hostdevice/hotplug.go
- pkg/virt-launcher/virtwrap/device/hostdevice/hotplug_test.go
- pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
Limit the argument passed to the filter to the hostdevices list.
Fixes #
```release-note
None
```
> virt-launcher, hostdevice: Pass only hostdevices to the filter
