pkg/testutils/mock_config.go
pkg/virt-config/config-map.go
pkg/virt-config/virt-config.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/application_test.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-controller/watch/vmi_test.go

fix expected memory size fault for ARM64 
optimising arch detect logic 
**Release note:**
```release-note
NONE
```

bazel test failure fix for arm64 and code optimize

---

README.md

Currently, the section titles are big and using "#". The "#" It's only for the name of the project. See [1] how it looks in the forked repository.
This PR fixes it and improves the readability.
[1] https://github.com/benukhanov/kubevirt/tree/docs/improve-readme#kubevirt
Fixes #
```release-note
NONE
```

Improve section titles

---

README.md

The note is misleading since the project already has stable releases
```release-note
NONE
```

[docs] remove redundant note from README.md

---

tests/vmi_hook_sidecar_test.go

The test seems to be [stable](https://search.ci.kubevirt.io/?search=test_id%3A2666&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job).
Fixes #
```release-note
NONE
```

Take test with id 2666 out of QUARANTINE

---

pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go
tests/network/vmi_multus.go

It should be verified that CNI IPAM functions well on secondary networks with bridge binding.
This PR adds a case to the existing bridge binding test to verify that.
Fixes #
```release-note
NONE
```

Test ipam on secondary networks

---

tests/vmi_configuration_test.go

Remove quarantine label from the tests which are no longer flaky
Fixes #
```release-note
NONE
```

Remove quarantine label

---

tests/storage/restore.go
tests/storage/snapshot.go

Fixes #
```release-note
NONE
```

Add numbers to the new snapshot and restore tests

---

pkg/virt-launcher/virtwrap/util/libvirt_helper.go

Fixes #
```release-note
NONE
```

libvirt_helper: fix typo

---

pkg/virt-controller/watch/snapshot/BUILD.bazel
pkg/virt-controller/watch/snapshot/snapshot.go
pkg/virt-controller/watch/snapshot/snapshot_base.go
pkg/virt-controller/watch/snapshot/snapshot_test.go
pkg/virt-controller/watch/snapshot/source.go
pkg/virt-controller/watch/snapshot/util.go
staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types.go
tests/storage/restore.go
tests/storage/snapshot.go

Refactor to hopefully make code easier to follow by reducing paths/calls to Update.
Fixes #
```release-note
NONE
```

refactor snapshot controller

---

tests/storage/hotplug.go

Take functional test out of quarantine
Fixes #
```release-note
NONE
```

Take Should be able to add and remove and re-add multiple volumes with VMs and block out of quarantine

---

api/openapi-spec/swagger.json
manifests/generated/kv-resource.yaml
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
staging/src/kubevirt.io/client-go/api/v1/types.go
staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go

Fix spelling error	
tupple-->tuple
https://github.com/kubevirt/kubevirt/issues/6125
Signed-off-by: ansijain <ansi.jain@india.nec.com>
Fixes #
```release-note
NA
```

Fix spelling error

---

pkg/virt-handler/vm.go

As previously observed in https://github.com/kubevirt/kubevirt/issues/6056
and further confirmed in https://snapshot.raintank.io/dashboard/snapshot/M09k4WMjCr23lZDunw3tnbbE7JvyPvxD
`virt-handler` is leaking goroutines.
The main cause for this leak seems to be in the way we handle the domainNotifyPipe. In the current code we listen to a unix socket which is a blocking operation. This seems to prevent the code from ever reaching the cleanup part. As a solution we move the connection closing outside the loop into a seperate routine that will close the connection on a cleanup signal and cause the `Accept()` call to fail. Then we can check if it's a close error and return.
Another way to do this instead of the goroutine approach would be to set a …

fix goroutine leak in virt-handler

---

tests/kubevirt_configmap_test.go
tests/vm_test.go

taking out stable sig-compute tests out of quarantine
```release-note
NONE
```

[tests] take out stable sig-compute tests out of quarantine

---

tests/vm_test.go

Remove quarantine label from non-flaky test_id:3311
```release-note
NONE
```

Remove Quarantine label from test_id:3311

---

pkg/virt-controller/watch/vm_test.go

Fix a flaky VM CrashLoop unit test that has been intermittently failing (e.g., [here](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6190/pull-kubevirt-goveralls/1423671111240912896) and [here](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6171/pull-kubevirt-goveralls/1424653133119754240)) since merged with #5905.
See [this comment](https://github.com/kubevirt/kubevirt/pull/5905#discussion_r684765109) for explanation why this is failing.
The fix includes:
* Move the `retryAfter` timestamp evaluation into the test execution.
* Ensure assertions are made for every test case.
* Use a much smaller (2 seconds vs 30 seconds) tolerance when …

Fix flaky VM CrashLoop unit test

---

tests/migration_test.go
tests/vmi_configuration_test.go

Add test ids cnv-49

---

pkg/virt-controller/watch/migration_test.go

related to: https://bugzilla.redhat.com/show_bug.cgi?id=1945532
We already fixed a situation where double handoff to virt-handler can occur in PR #5593. This adds a missing unit test to validate that logic. 
```release-note
NONE
```

unit test to verify double migration hand off to handler does not occur

---

hack/cluster-clean.sh

Split cluster-clean script to functions.
```release-note
None
```

cluster-clean, Refactor script

---

tests/infra_test.go

Signed-off-by: Israel Pinto <ipinto@redhat.com>
```release-note
NONE
```

Add test ids 4.9 part 2

---

tests/libnet/BUILD.bazel
tests/libnet/expose_util.go
tests/network/BUILD.bazel
tests/network/expose.go

As a part of an effort to make network tests more clean and readable, 
this PR Addreses some sonarcloud "code-smells" and includes: 
a creating of a method to create `virtctl expose` command with little hard-coded code and
some helpers and consts to reduce  code repetition and the use of hard-coded strings.
Fixes #
```release-note
NONE
```

Refactor expose test

---

tests/vm_test.go

**What this PR does / why we need it**: `Add test-id's for VM Error States Test Cases`
Fixes #
**Special notes for your reviewer**: `Add test-id's for VM Error States Test Cases`
```
NONE
```

Add test-id's for VM Error States Test Cases

---

tests/vm_test.go

Signed-off-by: Israel Pinto <ipinto@redhat.com>
```release-note
NONE
```

test_id_debugability_of_vm

---

tests/nonroot_test.go

**What this PR does / why we need it**: `Add testid's for NonRoot virt-launcher Tests`
Fixes #
```
NONE
```

Add testid's for NonRoot virt-launcher Tests

---

tests/storage/storage.go

Attempt to make the test less flaky. I suspect we just need to wait longer on a highly loaded CI. When I get test artifacts, the VMI I see has the correct condition to pass the test. So just waiting a little longer might do it.
Fixes #
```release-note
NONE
```

Get start VMI should pause with IO error out of quarantine

---

tests/network/vmi_multus.go

The SRIOV test suite designed to avoid using the the general func for test teardown [1] before each test starts.
Instead [1] is called once before all tests starts, due to that VMI's clean up is done in-place before each test starts.
The VMI's clean up doesn't handle VMI's that take longer time to dispose or stuck in the Terminating phase.
Due to the fact that VMI's clean up occurs before tests starts, when it fails the test that about to start reported as it was failed instead of the one that just finished.
This PR Changes SRIOV test suite to use [1] before each test starts, it will clean up VMI's properly and prevent reporting wrong test failures.
**Which issue(s) this PR fixes** :
**Special notes for …

Fix flaky SRIOV tests suite: Perform teardown before each test start

---

tools/perfscale-load-generator/README.md

Fix Typo
Fixes #
```release-note
NONE
```

Fix Typo in PerfScale Load Generator Readme

---

tests/container_disk_test.go

**What this PR does / why we need it**: `Add test_id for vm obey disk verification limits`
Fixes #
```
NONE
```

Add test_id for vm obey disk verification limits

---

OWNERS_ALIASES

Ashley is no longer actively reviewing PRs.
```release-note
NONE
```

OWNERS_ALIASES: make Ashley an emeritus approver

---

docs/reviewer-guide.md

In an effort to improve review quality, I'm beginning to document some of the more common architectural conflicts that typically get commented about during PR reviews. 
If anyone else has any thoughts here about items to add, please let me know. 
```release-note
NONE
```

Docs: Reviewer guide to avoiding architecture flaws

---

docs/reviewer-guide.md

Add two additional best practices to the reviewer guide.
Fixes #
```release-note
NONE
```

Add more advises to the reviewer guide

---

tests/network/vmi_multus.go

On CI, we schedule SR-IOV lane jobs on nodes with SR-IOV hardware
with at least two PF's, each PF represents a physical port on the card.
We create containerized cluster with two worker nodes where each one
have single SR-IOV PF attached to their netns.
Tests that checks connectivity between VM’s may fail if the VM’s
are scheduled each on different node during the tests in case:
- SR-IOV PF's are not connected to each other or to the same network.
- SR-IOV card doesn't support or allow inter-connectivity between PF's.
By scheduling the VM's to the same node we prevent those tests
to fail, and remove this dependency on the environment.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …

Fix flaky SR-IOV tests: Schedule VM's on single node on connectivity tests

---

docs/snapshot-restore.md

Fixes #
```release-note
NONE
```

Add online vm snapshot and snapshot deadline documentation

---

hack/bazel-build.sh

**What this PR does / why we need it**: Similar to #6390, we need it to prevent errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6304/pull-kubevirt-e2e-k8s-1.19-operator/1438032939706224640#1:build-log.txt%3A888
/cc @rmohr 
Fixes #
```release-note
NONE
```

Add cluster-profiler to bazel build command 

---

third_party/toolchains/toolchains.bzl

A recent incident where the TLS certificate from developer.arm.com could
not be verified, revealed that we should mirror it too.
Fixes #
```release-note
NONE
```

Mirror the arm toolchain to our artifacts cache

---

pkg/virt-launcher/virtwrap/live-migration-source.go

This PR improves the function that alters the source libvirt XML to produce the target XML.
Using a slice to represent the current location in the XML allows for more readability and flexibility.
Fixes #
No functional change, unit/functional tests already exist.
```release-note
NONE
```

migrations: decomplexify XML parsing

---

hack/cluster-deploy.sh

Continue installing CDI like before #6339.
Fixes #
```release-note
NONE
```

Continue installing CDI by default

---

ADOPTERS.md

Signed-off-by: Chris Callegari <mazzystr@gmail.com>
kind/enhancement
Let's update out ADOPTERS format.  The website will devour this file then publish to the website.

Refactor ADOPTERS list

---

tests/migration_test.go

Fixes #
```release-note
NONE
```

Tests: Ensure all virt-handlers are ready before migration

---

automation/repeated_test.sh

Enables CNAO for repeated testing in order to avoid these problems: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6036/pull-kubevirt-check-tests-for-flakes/1439926458083446784#1:build-log.txt%3A1882
Fixes #
```release-note
NONE
```

Enable CNAO and CDI for check flakes by default

---

automation/test.sh
tests/migration.go
tests/nonroot_test.go
tests/storage/storage.go
tools/manifest-templator/manifest-templator.go

Non-root feature gate was renamed in [PR](https://github.com/kubevirt/kubevirt/pull/6041) during reviews. Therefore non-root lanes are now testing root implementation. This PR fix the feature gate and implementation as some of the tests are not passing.
Fixes #
```release-note
NONE
```

Fix non-root lanes

---

docs/getting-started.md

Document new ENV Variable introduced in PR #6339. 
Fixes #
```release-note
NONE
```

Document CDI deploy for cluster-sync

---

pkg/virtctl/imageupload/imageupload.go

The PR removes the logic to get storageclasses and storageprofile.
Previously When StorageClass is not provided then Virtctl requires the clients to have permissions to list storageclasses and get cdi storage profiles within the cluster, which limits who can upload images. This is only used to get error message faster, and to provide default value.
All of this is actually not needed, we don't need to figure out access modes and volume modes if not provided. We just fill in the parts of the DV storage section that we did get, and let the backend figure out the rest. This does mean we cannot give the nice error message about uploading to readonly volumes if the storage profile determines that is the access mode. But this should be a rare occurrence. …

Fix virtctl imageupload on default storageclass

---

pkg/virt-launcher/virtwrap/live-migration-source.go
tests/migration.go
tests/migration_test.go

This is a manual cherry-pick of #6424
```release-note
NONE
```

[release-0.41] migration: persist XML changes to the target

---

automation/test.sh

**What this PR does / why we need it**: Adds a function to determine which container runtime binary to use and replaces a hardcoded `docker` call to retrieve container logs with the result of calling it. Logic comes from https://github.com/kubevirt/kubevirtci/blob/main/cluster-up/cluster/ephemeral-provider-common.sh#L17-L36
Fixes #
```release-note
NONE
```

Determine CRI binary to collect debug logs

---

tests/storage/guestfs.go

The guestfs tests have been checking if the appliance is ready by
searching for one of the files that is unpacked at container startup.
This isn't robust enough since the tar process could still be unpacking
the archive.  To make this check more robust, check if all expected
files are present _and_ that tar is not still running in the container.
Signed-off-by: Adam Litke <alitke@redhat.com>
```release-note
NONE
```

tests: Make sure libguestfs appliance is fully unpacked

---

tests/storage/storage.go

Remove test VMI IO tests from Quarantine
Fixes #
```release-note
NONE
```

Remove test VMI IO tests from Quarantine

---

tests/access_test.go
tests/container_disk_test.go
tests/network/vmi_lifecycle.go
tests/storage/storage.go
tests/utils.go
tests/vm_watch_test.go
tests/vmi_lifecycle_test.go

Signed-off-by: Howard Zhang <howard.zhang@arm.com>
The test has been verified on the local arm64 server, all tests have passed.
```release-note
NONE
```

add initial tests cases for arm64

---

tests/storage/events.go

Remove test 6225 from Quarantine
Fixes #
```release-note
NONE
```

Remove test 6225 from Quarantine

---

pkg/host-disk/host-disk.go
tests/framework/storage/BUILD.bazel
tests/framework/storage/nfs.go
tests/storage/datavolume.go
tests/storage/storage.go
tests/utils.go

This fixes cases where VM is using DV and storage doesn't support fsgroup.
Fixes bz#2001987 
```release-note
NONE
```

[Non-root] Unify DV with PVC handling

---

examples/vmi-arm.yaml
tools/vms-generator/utils/utils.go
tools/vms-generator/vms-generator.go

Fix added vMI configuration to support ARM

---

hack/prom-rule-ci/prom-rules-tests.yaml
manifests/generated/operator-csv.yaml.in
pkg/virt-operator/resource/apply/core_test.go
pkg/virt-operator/resource/generate/components/crds.go
pkg/virt-operator/resource/generate/components/deployments.go
pkg/virt-operator/resource/generate/components/webhooks.go
tests/infra_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2008166
Manual cherry-picks
- #6570
- #6588
- #6652
```release-note
Fixes issues in up metrics and alerts based on namespace labels
```

[release-0.44] Fix issues in up metrics and alerts based on namespace labels

---

tests/storage/storage.go

- Manually backporting 6302 so we have some control over the PR (will close https://github.com/kubevirt/kubevirt/pull/6349)
Fixes #
```release-note
NONE
```

[release-0.44] tests: manual cherry pick of 6302

---

ADOPTERS.md

/kind enhancement
Adding ARM to ADOPTERS file
```release-note
NONE
```

Adding ARM to ADOPTERS file

---

docs/fossa.md

Adds a document that explains what FOSSA is all about, where the configuration is and how to run it locally.
Fixes #
/cc @oshoval 
```release-note
NONE
```

Add initial FOSSA documentation

---

pkg/virt-handler/node-labeller/node_labeller_test.go

Fixes the flakiness of the test `should run node-labeling`
The test calls `nlController.execute()` function which perform a `PATCH`, but the mock kubeClient hasn't the reactor to manage that api call. This causes a failure of the labeling process and a re-queuing of the node. The test should fail but, since the re-queue process is delayed, it passes most of the time. If the re-queue process succeed before test makes `Expect(nlController.queue.Len()).To(Equal(0), "labeller should process all nodes from queue")` the test fail, otherwise no.
Adding the patch reactor to the mock kubeClient makes the test pass.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR …

Fix node_labeller flaky test

---

pkg/virt-handler/vm.go

Pass to the method the isolation data it needs to avoid re-calculating
it multiple times in the setup flow.
Fixes #
```release-note
NONE
```

virt-handler: Refactor claimDeviceOwnership method

---

tests/network/vmi_multus.go

This allows creating a bridge Network Attachment Definition with
variable "type", "bridge" (name) and "macspoofchk" fields.
The change is required in order to test the MAC spoof check feature which is
currently available only with "cnv-bridge" (deployed by CNAO).
This PR is required for PR kubevirt/kubevirt#6766
Fixes #
```release-note
NONE
```

tests, multus: Add params to createBridgeNetworkAttachmentDefinition

---

tests/migration_test.go

The test run 'ps -x' through virt-luncher in order to extract libvirtd pid and for unclear reasons sometimes 'ps -x' generate the **expected output** with exit code 1. 
Instead of checking the exit code i modified the test to check if the pid extracted is in the right format and print all the information needed in case of an error.
Fixes #
```release-note
replacing the command that extract libvirtd's pid  to avoid this error:
`ps -x`      ->      `pidof <LIBVIRTD_PID>`
```

stabilize [test_id:4746] by extracting libvirt's pid in a different way

---

tests/operator_test.go

@dbasunag reported that this test case is not passing in OpenShift and I checked it. I found that prometheus-operator changed the key in prometheus-k8s secret and we need to update this part for new versions. To stay backward-compatible, I didn't break the existing mechanism. 
See https://github.com/prometheus-operator/prometheus-operator/commit/5643505cafd6e79137d7cffa558c7d895aa66995#diff-b3d3450b51af206bb0009c2b9c2f863c3d03a3575d64cbdb18510a2bc834144aR305 and https://github.com/prometheus-operator/prometheus-operator/commit/7bd3bd016d3fd576419b20786c0888ead940ab77
```release-note
NONE
```

Fix ServiceMonitor test for new versions of PrometheusOperator

---

tests/storage/storage.go

(cherry picked from commit 97eff8d7253f21ab0fff14611cb1d928929daf88,
adapted to release-0.41)
Like #6806 but adapted to release-0.41 (builds)
Closes #6806
```release-note
NONE
```

[release-0.41] Skip VirtIO-FS tests if the feature gate is disabled

---

tests/vm_test.go

Purpose:  to fix a flaky test [7164] that was introduced for a merged PR #6040.
Problem:  the test makes the assumption that if the VMI reaches a failed state that the pod will immediately also be in a failed state. Because there can be a lag between when the VMI and pod fail, the test has a race condition. 
Fixes: 
1. add an eventually block around the test when not to keep launcher alive case.
2. replace the testing of the eventual phase of the virt-launcher pod to testing the state of the container-status of the compute container to consistently be running. This adjustment better targets the test to PR #6040.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …

Fix flaky test [7164] for PR 6040: Leave virt-launcher container up for failed VMI

---

tests/migration.go
tests/migration_test.go

This is a manual cherry-pick of #6643
/assign enp0s3
```release-note
NONE
```

[release-0.41] Fix [test_id:6978] Should detect a failed migration

---

pkg/container-disk/BUILD.bazel
pkg/container-disk/validation_test.go

This file hasn't been tested - this PR will increase our test value and test coverage.
```release-note
NONE
```

Introduce unit test for validation.go

---

pkg/virtctl/imageupload/imageupload.go

Fixes #
```release-note
NONE
```

Fix typos in virtctl comments

---

pkg/virt-handler/vm.go

Refactor this function in pkg/virt-handler/vm.go,
so its cognitive complexity is reduced below 15
and corresponding sonarcloud issue is fixed.
Signed-off-by: Tomas Psota <tpsota@redhat.com>
Fixes #
```release-note
NONE
```

Refactor func processVmShutdown

---

tests/storage/restore.go
tests/storage/snapshot.go
tests/subresource_api_test.go

Signed-off-by: dalia-frank <dafrank@redhat.com>
Fixes #
```release-note
```

Add tests ID's

---

tests/dryrun_test.go

Signed-off-by: Zhe Peng <zpeng@redhat.com>
Fixes #
```release-note
NONE
```

Add functional tests ids for dry-run

---

pkg/virtctl/utils/utils.go

Don't try to put a filedescriptor which is not a terminal into raw mode when calling `virtctl console`.
Fixes #3876
```release-note
Fix "Make raw terminal failed: The handle is invalid?" issue with "virtctl console" when not executed in a pty
```

[virtctl] Don't change terminal settings if not run in a terminal

---

README.md

FOSSA shield points toward the wrong project, this fixes the image
generation and link in the README.
Fixes #
```release-note
NONE
```

Fix FOSSA shield in README.md

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
pkg/virt-controller/watch/snapshot/restore.go
tests/storage/restore.go

This is a cherry pick for PR #6839 
Fixes #
```release-note
NONE
```

[release-0.44] fix vm restore of vm with runstrategy

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
pkg/virt-controller/watch/snapshot/restore.go
tests/storage/restore.go

This is a cherry pick for PR #6839 
Fixes #
```release-note
NONE
```

[release-0.41] fix vm restore of vm with runstrategy

---

tests/pausing_test.go
tests/vm_test.go

Signed-off-by: Zhe Peng <zpeng@redhat.com>
Fixes #
```release-note
NONE
```

Add test_id for virtctl dry-run testing

---

tests/numa/numa.go
tests/virtoperatorbasic/virtoperator_basic.go

Fixes the serial test label for two tests so that the regular expression matches them. 
Fixes #
```release-note
NONE
```

Fix serial test labels to use uppercase for first letter

---

hack/prom-rule-ci/prom-rules-tests.yaml
pkg/virt-operator/resource/generate/components/prometheus.go

**What this PR does / why we need it**: In summary of LowKVMNodesCount, changed "life migration" to "live migration"
Fixes #
```release-note
NONE
```

fixing typo in the summary of LowKVMNodesCount

---

tests/vm_test.go

**What this PR does / why we need it**: `Add test_id for DV errors testcase`
Fixes #
```
NONE
```

Add test_id for DV errors testcase

---

tests/migration_test.go

Signed-off-by: Barak Mordehai <bmordeha@redhat.com>
remove the [QUARANTINE] tag from test_id:4746
due to the test stabilization.
https://github.com/kubevirt/kubevirt/pull/6734
Fixes #
```release-note
NONE
```

remove [QUARANTINE] tag from test_id:4746

---

tests/migration_test.go

As part of our [quarantine proceedure](https://github.com/kubevirt/kubevirt/blob/main/docs/quarantine.md), this PR gets test 5004 out of qarantine after it was fixed in this PR: https://github.com/kubevirt/kubevirt/pull/6804
```release-note
NONE
```

Remove quarantine from test 5004

---

pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go

Fixes #
```release-note
NONE
```

virt-api: Fix typo in a comment

---

pkg/virtctl/ssh/native.go
pkg/virtctl/ssh/ssh.go
pkg/virtctl/ssh/wrapped.go

Avoid passing arguments lots of times.
No functional change intended.
```release-note
NONE
```

Merge SSH, SSHOptions structs.

---

tests/migration_test.go

Fixes #
```release-note
NONE
```

[release-0.36]  Fix test that is overriding all devices instead of interfaces 

---

pkg/virt-launcher/virtwrap/BUILD.bazel
pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go

This PR will increase our test value and test coverage and reach our goal of 73% coverage.
```release-note
NONE
```

Add unit tests for helper functions in manager.go

---

tests/storage/datavolume.go

after kubevirt/containerized-data-importer#2001, CDI will always
preallocate such DVs, and so all the test cases for non-preallocated
fail all the time.
Remove also the preallocated test - it's a negative test, and now
we would never get the feature on Block DVs.
Another reason to do this is that these tests did a lot of unusual
things like using rook toolbox, and despite a lot of effort, they
were unstable and quarantined for a long time.
```release-note
NONE
```

Stop testing trim with Block DVs

---

tests/vmi_kernel_boot_test.go

Adding test_id for functional tests
```release-note
NONE
```

Add test_id for kernel boot tests

---

automation/test.sh
hack/functests.sh
tests/config.go
tests/conformance-config.json
tests/console_test.go
tests/default-ceph-config.json
tests/default-config.json
tests/migration_test.go
tests/storage/datavolume.go
tests/storage/guestfs.go
tests/storage/hotplug.go
tests/storage/imageupload.go
tests/storage/restore.go
tests/storage/snapshot.go
tests/storage/storage.go
tests/utils.go
tests/vm_test.go

Fixes #
```release-note
NONE
```

Improve functests usage of storage

---

README.md

IMHO, our example video image is too big and it takes too much space. Let's make it smaller -> [Click](https://github.com/benukhanov/kubevirt/tree/docs/asciinema#introduction) here to see how it looks in the forked repository.
Please let me know if we can remove `Click the image below to see an example video` instruction.
If this PR will be declined, then let's make this image as a gif.
```release-note
NONE
```

Change example video image

---

OWNERS_ALIASES

Add @marceloamaral as a reviewer.
I have been working with the KubeVirt project for several months now, mainly contributing to the kubevirt and project-infra subprojects. In addition,I have been also reviewing and approving PRs. I will be happy to continue contributing as a reviewer of the project.
Fixes #
/cc @zcahana @davidvossel @stu-gott 
```release-note
NONE
```

add Marcelo Amaral to reviewers

---

pkg/network/setup/netstat_test.go

Add unit tests that cover the following scenarios:
- Existing interfaces have their MAC changed.
- Existing interfaces are removed.
- Add a new interface.
Fixes #
```release-note
NONE
```

network, netstat: Add tests to cover changes in the guest

---

tests/vm_test.go

Signed-off-by: fossedihelm <fossedihelm@gmail.com>
Resolve the flakiness of the following tests: `[test_id:7529]`, `[test_id:7604]`
The flakiness is caused due to a `DeepEqual` between two retrieved VMIs (one before the `stop --dry-run` command and one after). This assertion is too strong because there are several fields that can change independently from the command causing, sometimes, test failure.
Since the `stop` command causes the deletion of the vmi, checking that the `DeletionTimestamp` remains `nil` for a reasonable time is enough to consider that the `dry-run` has worked.
Fixes # …

Fix flaky dry run functest

---

hack/cluster-clean.sh

Fixes #
```release-note
NONE
```

Fix typo in cluster-clean.sh: kubectl -> _kubectl

---

tests/storage/BUILD.bazel
tests/storage/hotplug.go

We fixed a bunch of tests on 0.44 and onwards but never backported those fixes to 0.41, specifically:
#5610, #5769, #5938, #5985
Fixes #
```release-note
NONE
```

[release-0.41] Manual bulk backport of hotplug test fixes

---

docs/freeze.md

Describe ways to freeze/thaw a VMI
Fixes #
```release-note
NONE
```

Describe ways to freeze/thaw a VMI

---

pkg/host-disk/host-disk.go
pkg/util/types/pvc.go

Fixes #
```release-note
NONE
```

Fix block detection in ReplacePVCByHostDisk

---

tests/utils.go

Remove unused functions from tests/utils.
Fixes #
```release-note
NONE
```

tests, utils: Remove unused functions

---

automation/test.sh

Fixed by https://github.com/kubevirt/kubevirt/pull/6445
Fixes #6473
```release-note
NONE
```

Take out of quarantine test_id:3145 for nonroot lanes

---

tests/access_test.go

Run 14 permission tests in parallel. Every test gets its own unique user.
Fixes #
```release-note
NONE
```

Run openshift permission tests in parallel

---

tests/performance/density.go
tools/perfscale-audit/metric-client/metric-client.go

We're using the Range Vector variable to focus when we gather metrics, however that's not what it's suppose to be used for.  Range Vector is described in this [blog ](https://www.section.io/blog/prometheus-querying/):
"
Your selection of range duration will determine how granular your chart is. A [1m] duration, for instance, will give a very spiky chart, making it difficult to visualize a trend, looking something like this:
For a one hour view, [5m] would show a decent view:
"
Since we're setting the Range Vector based on the amount of time it takes to run the test 1-2 minutes, the results can vary quite a bit.  A 20 VM test locally using `[1m]` showed 40 CREATE requests while changed the vector to `[5m]` on the same test showed 22. …

Hardcode range selector to 5m and add a Primer VMI before each test

---

pkg/virt-handler/node-labeller/BUILD.bazel
pkg/virt-handler/node-labeller/cpu_plugin_test.go
tests/credentials_test.go
tests/security_features_test.go
tests/storage/storage.go
tests/usbredir_test.go
tests/vmi_cloudinit_test.go
tests/vmi_configuration_test.go
tests/vmi_ignition_test.go
tests/vmi_iothreads_test.go
tests/vmi_multiqueue_test.go
tests/vnc_test.go

Remove some `BeforeAll` usages to make  progress towards removing it completely. 20 more tests are now executed in parallel.
Fixes #
```release-note
NONE
```

[tests] remove beforeall from a bunch of tests

---

pkg/network/setup/netstat_test.go

Fixes a typo in a test
Fixes #
```release-note
None
```

tests, network: Fix typo

---

api/openapi-spec/swagger.json
manifests/generated/kv-resource.yaml
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>
Fix a typo: inforamtion -> information
Fixes #
```release-note
NONE
```

Fix a typo: inforamtion -> information

---

docs/vm-presets.md

The docs are out of date, update the VirtualMachineInstance{Preset} versions to
v1
:)
Signed-off-by: jbpratt <jbpratt78@gmail.com>

docs: update versions to v1 in vm presets.md

---

automation/test.sh
tests/migration_test.go

Make 40+ migration tests run in parallel and move them to dedicated test lanes.
Fixes #
```release-note
NONE
```

Prepare migration tests to be executed in parallel

---

pkg/virt-api/rest/subresource.go
staging/src/kubevirt.io/client-go/kubecli/handler.go

The PR introduces common functions: `formatURI`, `httpGetRequestHandler` and applies them accross the code to reduce duplication. No functional changes.
Fixes #
```release-note
NONE
```

rest, endpoints: Reduce code duplication

---

pkg/virt-handler/device-manager/common.go
pkg/virt-handler/device-manager/device_controller.go
pkg/virt-handler/device-manager/device_controller_test.go
pkg/virt-handler/device-manager/generic_device.go
pkg/virt-handler/device-manager/generic_device_test.go
pkg/virt-handler/device-manager/mediated_device.go
pkg/virt-handler/device-manager/mediated_device_test.go
pkg/virt-handler/device-manager/mediated_devices_types_test.go
pkg/virt-handler/device-manager/pci_device.go
pkg/virt-handler/device-manager/pci_device_test.go
pkg/virt-handler/vm.go

This PR is a small refactoring of the device-manager package. I made it while looking for goroutine leaks.
```release-note
None
```

code change: Small improvements in virt-handler/device-manager

---

tests/utils.go

It is important for a test to be executed under a healthy Kubevirt deployment. Therefore we need
to ensure ahead of time that the control-plane components are ready.  
- We can improve test infra code by adding a matcher for Daemonset readiness 
I've added it in TODO since I don't want this PR to drift away from its main purpose
```release-note
NONE
```

[tests]: validate the readiness of kubevirt components before executing a test

---

pkg/virt-launcher/virtwrap/live-migration-source.go
pkg/virt-launcher/virtwrap/manager_test.go

This PR ensures we will re-try switching to post-copy in case it fails.
Fixes #
Investigation of why we see the error is ongoing.
```release-note
NONE
```

Fix handling of failed post-copy migration switch

---

tests/migration_test.go

take test id 4747 out of quarantine
https://search.ci.kubevirt.io/?search=test_id%3A4747&maxAge=336h&context=1&type=junit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
```
NONE
```

take test id 4747 out of quarantine

---

pkg/virt-operator/resource/apply/reconcile.go
tests/BUILD.bazel
tests/operator_test.go
tests/vmi_lifecycle_test.go

Add tests for kubernetes.io/os node label
```
NONE
```

Add tests for kubernetes.io/os node label

---

tests/reporter/kubernetes.go

In order to save time and storage,
collect node info only for nodes which
runs at least one virt-launcher.
Fixes #
```release-note
None
```

k8s reporter: Limit node info collection

---

OWNERS_ALIASES

Follow up to #7351, also remove me from the list of reviewers.
```release-note
NONE
```

Remove Zvi from the list of reviewers

---

api/openapi-spec/swagger.json
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/schema.go
staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

This PR provides interface binding types descriptions, which are currently missing from the [API generated docs](http://kubevirt.io/api-reference/master/definitions.html#_v1_interface).
Fixes #
```release-note
Provide interface binding types descriptions, which will be featured in the KubeVirt API.
```

api, network: provide interface binding types descriptions

---

tests/migration_test.go

Fixes migration on non-root test. Default network binding is the bridge(not migratable).
Fixes #
```release-note
NONE
```

Tests: Fix migration on non-root

---

tests/migration_test.go

Fixes #
```release-note
NONE
```
/cc @dhiller @enp0s3

Enable test 6978

---

hack/dockerized

Updates the builder image to latest version.
Fixes #
```release-note
NONE
```

Update builder image to latest version

---

docs/quarantine.md

This PR fixes a small typo in the quarantine.md doc.
Fixes #
```release-note
NONE
```

docs, Fix typo in quarantine.md

---

docs/monitoring-guidelines.md

Fix links in monitoring-guidelines
Fixes #
```release-note
NONE
```

Fix links in monitoring-guidelines

---

tests/canary_upgrade_test.go

On some clusters with >3 nodes 120 seconds seem to be not enough.
Fixes #
```release-note
NONE
```

tests: extend virt-handler canary upgrade test timeout

---

go.mod
go.sum
vendor/github.com/prometheus/client_golang/prometheus/promhttp/BUILD.bazel
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
vendor/modules.txt

Solve a CVE vulnerability that affects previous versions
Vulnerability: https://www.cve.org/CVERecord?id=CVE-2022-21698
Patch: [prometheus/client_golang/security/advisories/GHSA-cg3q-j54f-5p7p](https://github.com/prometheus/client_golang/security/advisories/GHSA-cg3q-j54f-5p7p)
Fixes #
```release-note
NONE
```

update prometheus/client-go to 1.11.1

---

OWNERS_ALIASES

Nominate vasiliy-ul as reviewer
Fixes #
Community Guidelines for eligibility:
https://github.com/kubevirt/community/blob/main/membership_policy.md#reviewer
```release-note
NONE
```

Nominate vasiliy-ul as reviewer

---

tests/vmi_lifecycle_test.go

Signed-off-by: Zhe Peng <zpeng@redhat.com>
Fixes #
```release-note
NONE
```

Add test_id for low level hypervisor logs testing

---

pkg/virt-operator/resource/generate/components/crds.go

This PR shortens the flavor and clusterflavor CRD shortnames so that they follow the existing examples VirtualMachine with vm and VirtualMachineInstance with vmi.
N/A
N/A
```release-note
NONE
```

flavors: Make ShortNames for flavors shorter

---

pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go

VM mutating webhook now fails on error.
```release-note
None
```

VM mutating webhook fails on error

---

WORKSPACE
hack/builder/Dockerfile
hack/dockerized

Update go to 1.17.8 to solve some CVE vulnerabilities that affects previous versions.
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-23772
Fixes #7306
```release-note
Upgraded go version to 1.17.8
```

Upgrade go to 1.17.8

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
tests/migration_test.go

Manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/7582
Fixes #
```release-note
Fix failed reported migrations when actually they were successful.
```

[release-0.49] virt-controller: fix false failed migrations

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
tests/migration_test.go

Manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/7582
Fixes #
```release-note
Fix failed reported migrations when actually they were successful.
```

[release-0.51] virt-controller: fix false failed migrations

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
tests/migration_test.go

Manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/7582
Fixes #
```release-note
Fix failed reported migrations when actually they were successful.
```

[release-0.50] virt-controller: fix false failed migrations

---

hack/dockerized

Noticed this when making https://github.com/kubevirt/kubevirt/pull/7563,
I was getting rid of the v1beta1 client but had to rm it manually since it stuck around after make generate.
Fixes #
```release-note
NONE
```

Fix 'make generate' to not keep unused client autogenerated files

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
pkg/virt-controller/services/template_test.go
tests/util/util.go
tests/virt_control_plane_test.go

Avoid `Expect(len(X)).To(Equal(n))` in favor out `HaveLen`
```release-note
NONE
```

tests: few more HaveLen

---

tests/infra_test.go

It was seen that under high utilization the un-mounting process
can be way slower that the test timeouts, thus object deletion timeout
can be reached and the test will fail.
Replace a bootable VM with a non bootable one. That should
spare the test from spending time on mounting and un-mounting
the container-disk volumes as part of the VM state transition.
Fixes #
https://search.ci.kubevirt.io/?search=virt+handler+rate+limiter&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
For non-bootable VMs, the traversal of the phases for the VMI and the VMI pod is the same as if a VM has a bootable OS. …

[e2e]: improve the virt-handler rate limiter test

---

OWNERS
OWNERS_ALIASES

**What this PR does / why we need it**: Removing inactive folks from OWNERS
Fixes #
```release-note
NONE
```

OWENERS: Removing a couple of folks who are not active anymore

---

tests/vmi_tpm_test.go

Signed-off-by: akriti gupta <akrgupta@redhat.com>
Add test_ids for vTPM Tests
Fixes #
**Does this PR introduce a user-facing change?**
```
NONE
```

Virt TMP testcase

---

tests/migration_test.go

Signed-off-by: akriti gupta <akrgupta@redhat.com>
Added test ids to migration to nonroot testcases
Fixes #
**Does this PR introduce a user-facing change?**
```release-note
None
```

added test_ids

---

pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
staging/src/kubevirt.io/api/core/v1/types.go

Manual cherry-pick of #7102
Fixes #
```release-note
Add Virtual Machine name label to virt-launcher pod
```

[release-0.50] Add Virtual Machine name label to virt-launcher pod

---

pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
staging/src/kubevirt.io/api/core/v1/types.go

Manual cherry-pick of #7102
Fixes #
```release-note
Add Virtual Machine name label to virt-launcher pod
```

[release-0.49] Add Virtual Machine name label to virt-launcher pod

---

tests/monitoring/monitoring.go

Fixes #
```release-note
NONE
```

Add test id for vm snapshot metrics functest

---

pkg/virt-handler/non-root.go

Previously there was assumption that all PVCs that
are passed to the function will be block volume mode
PVCs. This assumption is wrong.
Fixes #
```release-note
NONE
```

Remove assumption in changeOwnershipOfBlockDevices

---

pkg/hooks/manager.go

**What this PR does / why we need it**: This MR improves the errors in the `PreCloudInitIso` method. Now we include errors when we fail on `Marshal` function. Also changed `Infof` logs to `Error` when error occurs.
```release-note
NONE
```

Improve errors in `PreCloudInitIso` method

---

tests/infra_test.go
tests/utils.go

Let's make tests/utils a bit shorter.
```release-note
NONE
```

tests: move ContainsCrt into its only user

---

pkg/virt-launcher/virtwrap/live-migration-source.go

**What this PR does / why we need it**: This MR simplifies some expressions which are too verbose and sometimes even confusing with simpler ones for readability. Also removes unused parameters.
```release-note
NONE
```

Simplify methods and functions in `live-migration-source` file

---

docs/components.md

The section shares future plans on how advanced networking should be
done in KubeVirt. Since it was written, we have advanced in this area
and that should be reflected there.
This patch updates it to reflect the current architecture and focus.
Fixes #7066
It does not mention any specific plugins or extensions on purpose, so
the section does not become outdated with future integrations or bugs.
We should track details about APIs and extensions in the user-guide
instead and keep this document high-level.
```release-note
NONE
```

Update networking section of components overview

---

automation/test.sh
hack/common.sh
hack/functests.sh
manifests/generated/operator-csv.yaml.in
pkg/virt-operator/resource/generate/components/daemonsets.go
pkg/virt-operator/resource/generate/components/deployments.go
tests/canary_upgrade_test.go
tests/flags/flags.go
tests/framework/checks/checks.go
tests/framework/checks/skips.go
tests/infra_test.go
tests/kubectl_test.go
tests/operator_test.go
tests/swap_test.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/7345
```release-note
NONE
```

[release-0.53] Fix/Skip tests that are incompatible with single-replica environments

---

hack/dockerized

New lightweight builder image after https://github.com/kubevirt/kubevirt/pull/7733 cleanup
Fixes #
```release-note
NONE
```
/cc @jean-edouard @maya-r @andreabolognani

Update kubevirt builder image

---

tests/network/sriov.go

The code that filters the interface having a certain MAC address is
currently being duplicated 3 times. This commit exports that into a
function, that uses the `wait.Poll` k8s.io library function - thus
avoiding using `Eventually` within helper funcs.
Fixes #
```release-note
NONE
```

Find interface by mac sriov helper

---

README.md

Signed-off-by: Joël Séguillon <joel.seguillon@gmail.com>
Update old asciinema demo 
Fixes #7652
```release-note
NONE
```
/cc @xpivarc

update asciinema demo for README

---

pkg/virt-launcher/virtwrap/live-migration-source.go

This PR makes migrations more verbose by dumping the libvirt job info every 2+ seconds in the source virt-launcher logs.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2080155
```release-note
NONE
```

migration: log progress in source virt-launcher logs

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-handler/node-labeller/cpu_plugin.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/node-labeller/node_labeller.go
staging/src/kubevirt.io/api/core/v1/types.go
tests/infra_test.go
tests/migration_test.go
tests/utils.go

manual backporting https://github.com/kubevirt/kubevirt/pull/7672,https://github.com/kubevirt/kubevirt/pull/7770 from main
Fixes #
```release-note
NONE
```

Fixing host model support heterogeneus cluster  [release-0.53]

---

docs/metrics.md
pkg/monitoring/domainstats/prometheus/prometheus.go
pkg/monitoring/domainstats/prometheus/prometheus_test.go
pkg/virt-launcher/virtwrap/live-migration-source.go
pkg/virt-launcher/virtwrap/stats/types.go
pkg/virt-launcher/virtwrap/statsconv/converter.go
pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
tools/doc-generator/doc-generator.go

Add and fix metrics for live migration.
Fix MemoryDirtyRate
Add DiskBps
Add MemoryBps
```release-note
None
```

Improving live migration metrics

---

OWNERS_ALIASES

Nominate @alicefr as a reviewer.
```release-note
NONE
```

Nominate alicefr as a reviewer

---

docs/conformance.md
docs/container-empty-disks.md
docs/devel/guest-os-info.md
docs/devel/olm-integration.md
docs/devel/virtual-machine.md
docs/filesystem-pv-disks.md
docs/getting-started.md
docs/gosec.md
docs/guestfs.md
docs/libvirt-pod-networking.md
docs/localstorage-disks.md
docs/release.md
docs/reviewer-guide.md
docs/updates.md

try to fix some typo on doc
Signed-off-by: tgfree <tgfree7@gmail.com>
```release-note
NONE
```

fix some type on doc

---

OWNERS_ALIASES

Nominate @yuhaohaoyu for removal from the current reviewers list.
```release-note
NONE
```

Update to current reviewers list

---

.golangci.yml
Makefile
pkg/network/domainspec/generators.go
pkg/network/domainspec/generators_test.go

This PR adds `pkg/network/domainspec/` as a lint target, as removes the lint errors found in it.
Fixes #
```release-note
NONE
```

Lint network code domain spec generator

---

.golangci.yml
tests/console/login.go
tests/libnet/cluster/cluster.go
tests/libnet/dns.go
tests/libnet/expose_util.go
tests/libnet/namespace.go
tests/libnet/ping.go
tests/libvmi/status.go

goimports local-prefixes used a wrong value which has now been fixed.
The change also includes the required fixed in the covered code.
Fixes #
```release-note
NONE
```

gloangci-lint: Fix goimports local-prefixes

---

docs/deprecation.md

This PR introduces an initial deprecation policy documentation.
This document is expected to be updated when the discussion here https://github.com/kubevirt/kubevirt/issues/7745 advances. See the issue for more info.
See https://github.com/kubevirt/kubevirt/issues/7745 for more info
```release-note
Introduction of an initial deprecation policy
```

Introduce initial deprecation policy: Deprecating feature gates

---

hack/common.sh

Since https://github.com/kubevirt/kubevirtci/pull/824
a non root user can use rootful podman via a socket (as docker supports).
For that we need to support the default root socket path `/run/podman/podman.socket`
in case the default root socket path was used.
Fixes #
```release-note
None
```

podman: Support non root user via default root socket

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-handler/node-labeller/cpu_plugin.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/node-labeller/node_labeller.go
staging/src/kubevirt.io/client-go/api/v1/types.go
tests/infra_test.go
tests/migration_test.go
tests/utils.go

manual backporting https://github.com/kubevirt/kubevirt/pull/7672 ,https://github.com/kubevirt/kubevirt/pull/7770 from main
Fixes #
```release-note
NONE
```

[release-0.45] Fixing host model support heterogeneus cluster 

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-handler/node-labeller/cpu_plugin.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/node-labeller/node_labeller.go
staging/src/kubevirt.io/client-go/api/v1/types.go
tests/infra_test.go
tests/migration_test.go
tests/utils.go

manual backporting https://github.com/kubevirt/kubevirt/pull/7672 ,https://github.com/kubevirt/kubevirt/pull/7770 from main
Fixes #
```release-note
NONE
```

[release-0.46]Fixing host model support heterogeneus cluster 

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-handler/node-labeller/cpu_plugin.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/node-labeller/node_labeller.go
staging/src/kubevirt.io/client-go/api/v1/types.go
tests/infra_test.go
tests/migration_test.go
tests/utils.go

manual backporting https://github.com/kubevirt/kubevirt/pull/7672 ,https://github.com/kubevirt/kubevirt/pull/7770 from main
Fixes #
```release-note
NONE
```

[release-0.44]Fixing host model support heterogeneus cluster 

---

tests/vmi_multiqueue_test.go

It is nicer than defining a boolean
and referring it manually.
Fixes #
```release-note
None
```

tests, multi queue: Use pointer.Bool

---

tests/vmi_configuration_test.go

This PR substitutes tests.NewRandomVMIWithEphemeralDiskAndUserdata with
respective libvmi function to create Cirros, Alpine or Fedora
based VMI.
In some cases, the returned value wasn't always updated when creating a VM.
Changes in this PR ensure that on VMI create, the returned value is used to update the vmi
variable content (e.g. namespace, defaults).
It's also worth noting that tests.NewRandomVMIWithEphemeralDiskAndUserdata
adds a masquerade interface with pod network by default, even when some of the
tests don't need it.
This change doesn't add the masquerade interface, as it seems better to
not clutter the tests with code adding masquerade interface, when it's not required.
**Which issue(s) …

e2e, use libvmi factory functions for creating VMIs

---

pkg/virt-operator/resource/apply/apps.go
pkg/virt-operator/resource/apply/apps_test.go
tests/operator_test.go

Fix virt-operator to set kebab-case `--max-device` option
Fixes #7751
```release-note
NONE
```

Fix --max-devices option

---

pkg/util/status/status.go

**What this PR does / why we need it**:  The MR removes redundant calls to `errors.IsNotFound` (1 calls instead of 3) and simplifies the flow a bit.
```release-note
NONE
```

Remove redundant IsNotFound calls from `update-` and `patchWithSubresource` functions in utility file `status`

---

pkg/virt-controller/watch/snapshot/snapshot.go

When deleting the vm snapshot we first update the finalizer
on the content and then delete the content.
The update of the content can retrigger the update updateVMSnapshotContent
which in case the volumesnapshot wasnt created yet will freeze the vm
and if there is still an error with creating the volume snapshot it will
not unfreeze it, then the content will be deleted and the vm will remain
frozen after the snapshot and the content were already deleted.
Instead incase the vmsnapshot is already marked as deleted if the
content should also be deleted then just do nothing, if the content will
not be deleted then just refrain from creating the volume snapshot (and freezing the vm).
This should fix racy …

Fix race of deleting not ready vmsnapshot and freeze of vm

---

ADOPTERS.md

Make it a bit clearer how oVirt and okd integrate with KubeVirt
/cc @sandrobonazzola @aburdenthehand 
```release-note
NONE
```

ADOPTERS: elaborate on ovirt/okd integration

---

tests/operator_test.go

This is a manual cherry-pick of #8130
/assign @enp0s3 
```release-note
NONE
```

[release-0.53] [e2e tests]: improve operator test 4744 

---

pkg/virt-controller/watch/export/export.go

Error check added for `ExporterPodCreated` and `ServiceCreated` events, as the creation of the respective objects may fail.
Fixes #
```release-note
NONE
```

VMExport: Check the error before emitting events

---

tests/operator_test.go

Use more standard method of disabling/enabling feature gate,
which is more resilient to the kubevirt object being changed.
The test already assumed the feature gate is enabled with
Expect(exportEnabled).To(BeTrue())
[The test is flaky](https://search.ci.kubevirt.io/?search=should+delete+and+recreate+virt-exportproxy&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)
```release-note
NONE
```

Resolve flakiness in vmexport feature gate disabled test

---

tests/vmi_lifecycle_test.go

The feature that we require in the test might be the same feature we disable and that cause flackiness.
Fixes #
```release-note
NONE
```

Fixing flacky test_id:3202

---

tests/storage/restore.go

We add the permission in BeforeEach and immediately try to use
this permission which might be too quick.
This solution has been adopted in createVmSuccess in
tests/storage/datavolume.go, copy it.
Fixes flakes seen, for example [here](https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.24-sig-storage/1552448762796838912)
```release-note
NONE
```

Tolerate some errors in VM Create()

---

pkg/virt-controller/watch/snapshot/restore.go
tests/storage/BUILD.bazel
tests/storage/restore.go
tests/utils.go

This is manual cherry pick of https://github.com/kubevirt/kubevirt/pull/8078
Fixes #
```release-note
NONE
```

[release-v0.49] Must clear "cloneRequest" annotation on restore of PVC 

---

pkg/virt-controller/watch/snapshot/restore.go
tests/libstorage/BUILD.bazel
tests/libstorage/datavolume.go
tests/storage/BUILD.bazel
tests/storage/restore.go
tests/utils.go

This is manual cherry pick of #8078 
Fixes #
```release-note
NONE
```

[release-v0.53] Must clear "cloneRequest" annotation on restore of PVC

---

ADOPTERS.md

adds osbuild-operator to kubevirt adoptors list 
```release-note
NONE
```

Add OSBuild-Operator to the KubeVirt Adopters list

---

tests/migration_test.go

The test was using incorrect migration configuration
that caused it to be flaky. Because of the bad configuraiton
the failure was that migration is not completed on time (5 secs)
The resolution was to decouple the test from the migration monitor spec
Fixes #
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2022-08-01-168h.html#row0
```release-note
NONE
```

[e2e tests]: fix flaky test_id 8482 in migration suite

---

docs/reviewer-guide.md

When reviewing, writing or debugging controller code the implications of the usage of UPDATE/PATCH calls should be clear.
Fixes #
```release-note
NONE
```

Capture UPDATE/PATCH considerations when working with controllers

---

pkg/virt-api/rest/profiler.go

The outer goroutine is not needed, it would not improve performance.
```release-note
None
```

virt-api: Remove unnecessary goroutine

---

tests/network/sriov.go

Refactor and simplify the e2e SR-IOV tests.
Fixes #
```release-note
NONE
```

tests: Refactor SR-IOV tests

---

tests/libstorage/datavolume.go
tests/storage/datavolume.go
tests/storage/snapshot.go

Fixes #
```release-note
NONE
```

Add DV garbage collection tests

---

pkg/virt-handler/hotplug-disk/mount.go

Refactor some functions in `pkg/virt-handler/hotplug-disk/mount.go` and tries to simplify the flow avoiding repetitions
Fixes #
```release-note
NONE
```

code refactor: mount in virt-handler for hotplugged volumes

---

tests/reporter/kubernetes.go
tests/tests_suite_test.go
tests/utils.go

These issues are going to haunt us over here as well unless we backport the fixes.
Fixes #
```release-note
NONE
```

[release-0.49] Manual backport of 8222 - parallel testing complications

---

tests/reporter/kubernetes.go
tests/tests_suite_test.go
tests/testsuite/fixture.go
tests/testsuite/manifest.go
tests/utils.go

These issues are going to haunt us over here as well unless we backport the fixes.
Fixes #
```release-note
NONE
```

[release-0.53] Manual backport of 8222 - parallel testing complications

---

tests/libstorage/storageclass.go

In tests/libstorage/storageclass.go:
* Removed double imports.
* Reduce the complicity the CheckNoProvisionerStorageClassPVs function and make it more readable by
replacing a long condition within a loop, with a function call.
```release-note
None
```

[Clean Code] Tiny changes in storageclass.go

---

tests/storage/restore.go

This adds a functional test for verifying the fix for the following bug: 
https://bugzilla.redhat.com/show_bug.cgi?id=2104479 
Fixes #
```release-note
NONE
```

Restore test with deleting source pvc

---

pkg/container-disk/container-disk_test.go
pkg/virt-controller/watch/vm.go
tests/libvmi/vmi.go
tests/network/services.go
tests/vmi_configuration_test.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>
Fixes #
```release-note
NONE
```

chore: remove duplicate word in comments

---

Makefile
manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/network/sriov/BUILD.bazel
pkg/network/sriov/sriov.go
pkg/network/sriov/sriov_suite_test.go
pkg/network/sriov/sriov_test.go
pkg/network/vmispec/interface.go
pkg/network/vmispec/interface_test.go
pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/rendervolumes.go
pkg/virt-controller/services/template.go
pkg/virt-controller/watch/BUILD.bazel
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go
pkg/virt-launcher/virtwrap/device/hostdevice/sriov/BUILD.bazel
pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
pkg/virt-launcher/virtwrap/device/hostdevice/sriov/pcipool_netstatus.go
pkg/virt-launcher/virtwrap/device/hostdevice/sriov/pcipool_netstatus_test.go
pkg/virt-operator/resource/generate/rbac/controller.go
tests/network/sriov.go

This PR implements in steps the solution proposed on the SRIOV mapping [design](https://github.com/kubevirt/community/pull/185).
what is done so far (Commits):
- *sriov - Map sriov devices to pci addresses*
- *virt-controller, Patch network-pci map annotation*
- *virt-controller, Expose network-pci-map with DownwardAPI*
- *virt-launcher, sriov - Use new Network to PCI map with fallback*
Fixes https://github.com/kubevirt/kubevirt/issues/7444
```release-note
NONE
```

Remap SRIOV interfaces

---

tests/monitoring/monitoring.go

This PR adds new test cases for kubevirt alert definitions. We expect to see `summary`, `runbook_url`,`severity`, `kubernetes_operator_part_of` and `kubernetes_operator_component` for each alert. Those fields must not be empty and some must have specific values. 
Signed-off-by: assafad [aadmi@redhat.com](mailto:aadmi@redhat.com)
```release-note
None
```

Add sanity tests for alerts

---

tests/migration_test.go

The test framework performs teardown after each run test - part of
which, is to reset the taints and spec.Unschedulable attributes on the
nodes **if** they were previously tainted with the `NoExecute` taint.
Providing a function that when draining also applies the `NoExecute`
taint makes the developer life easier, since the test framework will
afterward reset the corresponding node.
Fixes #
```release-note
NONE
```

e2e tests, migration: provide node drain + taint in a single func

---

pkg/controller/conditions.go
pkg/storage/types/BUILD.bazel
pkg/storage/types/cdi.go
pkg/storage/types/dv.go
pkg/storage/types/dv_test.go
pkg/storage/types/pvc.go
pkg/virt-api/rest/BUILD.bazel
pkg/virt-api/rest/subresource.go
pkg/virt-api/rest/subresource_test.go
pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/rendervolumes.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-controller/watch/BUILD.bazel
pkg/virt-controller/watch/util/util.go
pkg/virt-controller/watch/vm.go
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go
pkg/virtctl/imageupload/BUILD.bazel
pkg/virtctl/imageupload/imageupload.go
pkg/virtctl/vm/BUILD.bazel
pkg/virtctl/vm/vm.go
pkg/virtctl/vm/vm_test.go

Continue with moving storage related code to storage pkg.
This PR focuses on dv  and pvc related code.
```release-note
NONE
```

Separate storage code to storage pkg - continue

---

docs/probes.md

Allow to perform the readiness probes. As it was, the SELinux system denied attempts to open the /tmp/healthy.txt file causing the probe to fail. The documentation is modified to explain why the context assignation is required. Finally, the disk image is updated to use a more modern one intended for end users.
Fixes #
```release-note
NONE
```

docs, probes: update the probe documentation

---

go.mod

Updated `go.mod` file by running `make deps-update`.
```release-note
None
```

modules: Run 'make deps-update'

---

tests/storage/storage.go

Use `Satisfy` matcher to simplify the code and improve the failure message.
Fixes #
```release-note
NONE
```

[Flaky test]: Improve matching test values and logging

---

pkg/virtctl/guestfs/guestfs.go
tests/storage/guestfs.go

In openshift we are moving to restricted SCC and running with uid != 0.
In the case, we run with SCC strategy RunAsAny for the FSGroup this field isn't automatically set. Without the specification of the fsgroup, Kubernetes doesn't change the ownership of the directory where the PVC is mounted. This causes an unusable PVC when we run with uid != 0 as we don't have the right to write in the directory.
This PR adds a new flag for setting the gid and fsgroup manually. The functional tests are always run with this flag to avoid permission issues with the PVC.
Fixes # …

guestfs: fix fsgroup for openshift

---

tests/vnc_test.go

It turns out that eventually the VNC screen ends up with a resolution of 720x400, but the initial seabios screen has a different resolution for a very short amount of time.
Cope with that by retrying until we see the expected resolution.
Example run: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-e2e-k8s-1.22-sig-compute/1574529294523174912
Fixes #
```release-note
NONE
```

Improve VNC screenshot test

---

api/openapi-spec/swagger.json
manifests/generated/kv-resource.yaml
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

This PR fills some of the missing API documentation for the KubeVirt CR.
It doesn't take care of everything, just developer and migration configuration.
The only manually modified file is types.go, the rest is generated code.
```release-note
NONE
```

Add CR API documentation for developer and migration configuration

---

docs/metrics.md
pkg/monitoring/domainstats/prometheus/prometheus.go
pkg/virt-controller/watch/workload-updater/workload-updater.go

Metrics documentation is not detailed enough.
Fixes #
Reference for some of the documentation :
https://libvirt.org/html/libvirt-libvirt-domain.html
```release-note
Improve metrics documentation
```

Improve metrics documentation to be detailed enough

---

docs/reviewer-guide.md

/cc @rmohr 
Based on the following ML thread:
https://groups.google.com/g/kubevirt-dev/c/q_hR1tFH4Rk
Fixes #
```release-note
NONE
```

reviewer-guide: Update notes on use of informers

---

tests/storage/datavolume.go

Not sure exactly what goes wrong here, at first, I thought it was a low timeout (nanoseconds) but apparently, gomega will convert integers to seconds.
Possibly the double return value paired with a single matcher? https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1695
Regardless, I think this reads a little better.
Fixes #
```release-note
NONE
```

[e2e tests]: Address flake in test_id:4643

---

tests/reporter/kubernetes.go
tests/storage/snapshot.go
tests/testsuite/namespace.go

Use Satisfy matcher to simplify the code and improve the failure message. Add correct offset to failure message.
Additionally improved the report and the namespace cleanup (might help with the Aftersuite failures)
Fixes #
```release-note
NONE
```

[flaky] Snapshot test case - improve test reports and cleanup

---

manifests/generated/operator-csv.yaml.in
pkg/virt-operator/resource/generate/components/deployments.go

Fixes #
```release-note
NONE
```

[release-0.49] Revert "Set SeccompProfile"

---

tests/network/probes.go

Signed-off-by: Geetika Kapoor <gkapoor@redhat.com>
Create test id for probes.go 
Fixes #
```release-note
None
```

Added test_id for probes.go

---

tests/infra_test.go

Signed-off-by: akriti gupta <akrgupta@redhat.com>
Add test_ids for infta tls configuration Tests
Fixes #
**Does this PR introduce a user-facing change?**
```
NONE
```

adding polarion test ids

---

OWNERS_ALIASES

Add 0xFelix (myself) to the list of reviewers.
/cc @rmohr
```release-note
None
```

Add 0xFelix as reviewer

---

OWNERS_ALIASES

Self nominating myself as a reviewer.
```release-note
NONE
```

Add lyarwood as reviewer

---

tests/BUILD.bazel
tests/hyperv_test.go
tests/windows_test.go

These test doesn't require Windows OS to be
tested. CI has only one copy of Windows license
and therefore limited bw on Windows lane.
Fixes #
```release-note
NONE
```

Move tests agnostic to Windows OS from Windows lane

---

tests/instancetype_test.go

Add testids to instancetype functional tests.
Fixes #
```release-note
NONE
```

instancetype: Add testids to functional tests

---

tests/storage/export.go

Basically following up loose ends from https://github.com/kubevirt/kubevirt/pull/8670
Fixes #
```release-note
NONE
```

[e2e tests]: Run export test pods as PSA-compliant as well

---

tests/network/vmi_networking.go

`runMigrationAndExpectCompletion` function is implemented both locally and on migration package.
In order to align with other migration tests, replacing function with equivalent on migration package.
Fixes #
```release-note
NONE
```

tests, network: Replace run migration function

---

tests/reporter/kubernetes.go

Some of our tests don't run VMs (e.g. guestfs tests) and we are missing valuable info by only recording information from nodes that run virt-launcher pods.
Basically, re-doing #6687 with the requested change by roman
```release-note
NONE
```

Log nodes running pods in test namespaces

---

WORKSPACE
tests/network/vmi_istio.go
tests/virtctl/scp.go
tests/virtctl/ssh.go

We switched out to fedora to unblock various CI's in https://github.com/kubevirt/kubevirt/pull/8410 but definitely should be able to do this with alpine
and save some resources.
Needs an alpine bump because we fixed cloud init with https://github.com/kubevirt/kubevirtci/pull/876.
Fixes #
```release-note
NONE
```

[scp/ssh tests]: switch fedora to alpine

---

pkg/virt-api/webhooks/hyperv.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
tests/BUILD.bazel
tests/hyperv_test.go
tests/vmi_lifecycle_test.go
tests/windows_test.go

This is a manual backport PRs of : 
https://github.com/kubevirt/kubevirt/pull/8556
which move tests agnostic to Windows OS from Windows lane
and 
https://github.com/kubevirt/kubevirt/pull/8773
that fix evmcs hyperv feature bug.
Fixes #
```release-note
NONE
```

[release-0.58]Fix evmcs hyperv bug

---

api/openapi-spec/swagger.json
manifests/generated/kv-resource.yaml
pkg/virt-config/configuration_test.go
pkg/virt-config/virt-config.go
pkg/virt-handler/device-manager/device_controller.go
pkg/virt-handler/device-manager/mediated_devices_types_test.go
pkg/virt-handler/heartbeat/heartbeat.go
pkg/virt-handler/heartbeat/heartbeat_test.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/mdev_configuration_allocation_test.go

Fixes RHBZ#2054863
```release-note
CR option mediatedDevicesTypes is deprecated in favor of mediatedDeviceTypes
```

Deprecate mediatedDevicesTypes in favor of mediatedDeviceTypes

---

api/openapi-spec/swagger.json
pkg/safepath/safepath.go
pkg/virt-controller/services/template.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go
pkg/virt-handler/BUILD.bazel
pkg/virt-handler/selinux/BUILD.bazel
pkg/virt-handler/selinux/labels.go
pkg/virt-handler/vm.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

This PR is an attempt at matching the SELinux level of virt-launcher in hotplug attachment pods, instead of using s0.
Fixes #
```release-note
NONE
```

hotplug-disk container: match SELinux level of virt-launcher 

---

pkg/virt-handler/device-manager/mediated_devices_types.go
pkg/virt-handler/device-manager/mediated_devices_types_test.go
tests/mdev_configuration_allocation_test.go

This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/8481
Fixes #
```release-note
NONE
```

[release-0.58] Always refresh the mediated devices

---

OWNERS_ALIASES

My username is changed from `iholder-redhat` to `iholder101`, updating owners file with the new username.
```release-note
NONE
```

Change iholder-redhat username to iholder101 in owners file

---

OWNERS_ALIASES

Nominate Antonio as a test approver.
Fixes #
```release-note
NONE
```

Nominate Antonio as an approver in the tests directory.

---

OWNERS_ALIASES

Proposing @acardace for kubevirt/kubevirt approver.
Antonio is on the project for [almost 2 years now](https://github.com/kubevirt/kubevirt/pull/5017)  and made numerous [contributions to the project](https://github.com/kubevirt/kubevirt/pulls?q=is%3Aclosed+is%3Apr+author%3Aacardace)  
and [reviews](https://github.com/kubevirt/kubevirt/pulls?page=1&q=is%3Apr+commenter%3Aacardace+is%3Aclosed+-author%3Aacardace).
Fixes #
/cc @mhenriks
/cc @dhiller
/cc @rthallisey
/cc @davidvossel
/cc @vladikr
/cc @stu-gott
/cc @fabiand
/cc @rmohr 
/cc @enp0s3 …

Make acardace approver for kubevirt/kubevirt

---

tests/vnc_test.go

According to video device type, set expected screenshot resolution, 720x400 for vga device, 1280x800 for
virtio-gpu device.
You can get more information from the following code.
https://github.com/qemu/qemu/blob/7c09a7f6ae1770d15535980d15dffdb23f4d9786/include/hw/virtio/virtio-gpu.h#L150-L151
```release-note
None
```

tests: Set expected screenshot resolution

---

pkg/virt-handler/device-manager/generic_device.go
pkg/virt-handler/device-manager/mediated_device.go
pkg/virt-handler/device-manager/pci_device.go

Drop some workarounds that should no longer be necessary.
```release-note
NONE
```

device-manager: Drop workarounds

---

docs/release.md

After a few iterations we settled on a schema that is centered around the Kubernetes release date. This update is trying to document the guiding principles and documents the release schema.
Updates to the KubeVirt release schema.
Fixes #
```release-note
NONE
```

release: Update release.md to reflect the schema that we settled on

---

tests/operator_test.go

Sometimes it takes a while until the pod is created in test_id:4927 when we update virt-components deployment and if the pod will be created after the call toallPodsAreReady in the AfterEach scope than we will run the next test with side effect of pending pods.
Fixes #
```release-note
NONE
```

Fixing race that cause flackiness in functional tests

---

manifests/generated/operator-csv.yaml.in
pkg/virt-operator/resource/generate/components/daemonsets.go
pkg/virt-operator/resource/generate/components/deployments.go

This is a manual cherry-pick of #8613
```release-note
NONE
```

[release-0.49] Bump memory requests according to value seen in testing

---

tests/storage/snapshot.go

Fixes #
```release-note
NONE
```

add test id

---

tests/storage/memorydump.go
tests/storage/restore.go
tests/storage/snapshot.go

Fixes #
Add missing test_ids
```release-note
None
```

Add missing test_ids

---

automation/test.sh
tests/decorators/decorators.go
tests/virtctl/scp.go
tests/virtctl/ssh.go

This updates the functional virtctl tests for the ssh and scp commands
to test local-ssh functionality depending on provided label-filters.
```release-note
None
```

virtctl: Update functional tests for excludenative build tag

---

tests/vm_test.go

See https://search.ci.kubevirt.io/?search=should+delete+old+vm+revision+and+create+new+one+when+restarting+vm&maxAge=48h&context=3&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
```release-note
NONE
```

Fix flaky revision test

---

tests/storage/restore.go

It appears we need the mac address patch here as well, otherwise, we're creating a new restored VM with same MAC as source. Kubemacpool environments caught this.
Fixes #
```release-note
NONE
```

[restore tests]: apply mac patch to controllerrevision test as well

---

tests/monitoring/prometheus_utils.go

Later versions of kubernetes do not automatically generate tokens for service accounts[1]. This leads to the monitoring tests timing out due to the authorization token not being in place [2].
This change creates a service account token which allows the tests to complete successfully on versions later than 1.23. Tested locally against the 1.26 kubevirtci provider.
[1] https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-an-api-token-for-a-serviceaccount 
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2553/rehearsal-pull-kubevirt-e2e-k8s-1.26-sig-monitoring/1615267361609224192
```release-note
NONE
```

[sig-monitoring] Create token for prometheus-k8s service account

---

tests/operator_test.go

Using `Update` method can hit collisions.
https://search.ci.kubevirt.io/?search=should+be+blocked+if+a+workload+exists&maxAge=48h&context=3&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes https://issues.redhat.com/browse/CNV-23369
```release-note
NONE
```
/cc @dhiller

e2e: fix block uninstall operator test

---

tests/security_features_test.go

The test was failing on non-schedulable control-plane nodes because of an oversight in the code.
Fixes #
```release-note
NONE
```

SELinux test bugfix: do not expect virt-handlers on non-schedulable nodes

---

pkg/virtctl/create/vm.go
pkg/virtctl/create/vm_test.go
tests/virtctl/create_vm.go

This adds the flags --infer-instancetype and --infer-preference.
When specified the instancetype and/or preference to be used are inferred
from the first volume of a created VM. The flags are mutually exclusive to
the --instancetype respectively --preference flag.
```release-note
virtctl: Add options to infer instancetype and preference when creating a VM
```

virtctl: Allow to infer [instancetype|preference] when creating a VM

---

tests/network/vmi_networking.go

This will enable us to make the network PSA lane gating. 
Fixes #
```release-note
NONE
```

Fix network test to make it 'restricted' PSA compliant

---

tests/storage/guestfs.go

Adjust functions to pass namespace, and use the privileged namespace for the test that runs guestfs as root.
```release-note
NONE
```

Fix guestfs test failure with PSA enabled

---

tests/storage/export.go

If macpool installed the exported VM definition contains the mac address of the source VM, this causes the test to fail when trying to replicate into the same cluster.
Clearing out the mac before attempting to create a new one fixes the problem
Fixes #
```release-note
NONE
```

Fix export datavolume tests duplicate mac

---

tests/operator/operator.go

Currently, imagePullSecrets tests checks that the virt-launcher pod has no imagePullSecrets. This is not always true, because if the ServiceAccount that runs the pod has an imagePullSecret, the pod will inherit it, causing a failure. This patch changes the check:
If the Kubevirt CR has no imagePullSecrets, then the virt-launcher pod should have the same imagePullSecrets of its ServiceAccount.
Fixes #
```release-note
NONE
```
/cc @enp0s3

e2e test: Fix imagePullSecrets check

---

pkg/virt-launcher/virtwrap/converter/converter.go

Signed-off-by: zhuanlan <zhuanlan_yewu@cmss.chinamoblie.com>
fix a typo, `needsSCSIControler` -> `needsSCSIController`
Fixes #
```release-note
NONE
```

fix a typo

---

manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-operator/resource/generate/rbac/cluster.go

Neither exports nor clones had proper RBAC configured This adds RBAC for both.
Fixes #
```release-note
Default RBAC for clone and export
```

RBAC for export and clone virtual machine

---

staging/src/kubevirt.io/api/core/v1/schema.go
staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go

Fixes #
```release-note
NONE
```

remove optional option from secret secretName

---

automation/test.sh
tests/decorators/decorators.go
tests/network/vmi_istio.go

This is a temporary measure allowing us to disable Istio tests on setups that don't support Istio yet - CentOS 9.
Fixes #
Should get in together with https://github.com/kubevirt/project-infra/pull/2592.
```release-note
NONE
```

Label Istio test and allow disabling them with TARGET envvar

---

tests/migration_test.go

This is a manual backport of https://github.com/kubevirt/kubevirt/pull/9195
Fixes #
```release-note
NONE
```
/cc @enp0s3

[release-0.58] [e2e] Fix flaky tls test

---

tests/operator/operator.go

This was missed.
Fixes #
```release-note
NONE
```

Test: Seccomp increase timeout

---

pkg/instancetype/instancetype.go
pkg/instancetype/instancetype_test.go
pkg/storage/export/export/export.go
pkg/virt-api/rest/subresource.go
pkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/vm_test.go

This PR addresses various clean ups and refactors identified in #8537.
Fixes #
```release-note
NONE
```

instancetype: Follow ups from #8537

---

tests/vmi_cloudinit_test.go

it may happen that the spec connects to the vm console too late thus missing the prompted string from the cloud-init executed script.
with this change, the script creates a file on the fs and the spec waits until login appears, then checking the file existence.
**Special notes for the reviewer:**
In some circumstances I didn't use `DescribeTable` because helper functions such as `cd.ContainerFor` can panic and therefore cannot by called from `Entry`
```release-note
NONE
```

[e2e]: improve cloud-init user-data specs

---

pkg/virtctl/create/BUILD.bazel
pkg/virtctl/create/create.go
pkg/virtctl/create/params/BUILD.bazel
pkg/virtctl/create/params/params.go
pkg/virtctl/create/vm/BUILD.bazel
pkg/virtctl/create/vm/vm.go
pkg/virtctl/create/vm/vm_suite_test.go
pkg/virtctl/create/vm/vm_test.go
tests/virtctl/BUILD.bazel
tests/virtctl/create_vm.go

This PR  moves already existing files from create folder into subfolders so that each command will be in its own package.
```None
```

Move existing files from create folder into subfolders

---

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
pkg/virt-controller/watch/vm.go
pkg/virt-controller/watch/vm_test.go
tests/storage/datavolume.go
tests/storage/snapshot.go
tests/vm_test.go

This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/8937 and https://github.com/kubevirt/kubevirt/pull/9259
Fixes #
```release-note
Added foreground finalizer to  virtual machine
```

[release-0.59] Add VirtualMachine foreground finalizer

---

tests/pausing_test.go

Add 4 seconds of toleration from the comparison between the guest and the host uptime difference before pause.
The uptime command returns the value in seconds.
If you capture the uptime when it is at the beginning of that second or at the end of that second, the value comes out the same even though in fact a whole second has almost passed. In extreme cases, as we take 4 readings (2 initially and 2 after the unpause), the deviation could be up to just under 4 seconds. This fact does not invalidate the purpose of the test, which is to prove that during the pause the vmi is actually paused.
Fixes # …

[e2e] Fine-tuning of the pausing test

---

pkg/virt-launcher/virtwrap/manager.go

Currently, it may happen that we invoke
the sync operation too soon. (Read the domain
is actually not running on the target.) In this
case but also in some cases of failure we flood
the logs with warnings.
This commits changes the verbosity of repeating
logs and make sure it is logged at the end.
Fixes #
BZ https://bugzilla.redhat.com/show_bug.cgi?id=2064160
```release-note
NONE
```

Dont flood logs on sync guest time

---

pkg/virt-handler/node-labeller/cpu_plugin.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/node-labeller/model.go
pkg/virt-handler/node-labeller/node_labeller.go
pkg/virt-handler/node-labeller/node_labeller_test.go
pkg/virt-handler/node-labeller/testdata/cpu_map/x86_Opteron_G2.xml
pkg/virt-handler/node-labeller/testdata/cpu_map/x86_Skylake-Client-IBRS.xml
pkg/virt-handler/node-labeller/testdata/virsh_domcapabilities.xml

manual back-port of:
https://github.com/kubevirt/kubevirt/pull/9325
Fixes #
```release-note
NONE
```

[release-0.58]node-labeller: Take CPU features into account when labeling nodes

---

docs/release.md

Adds more details on how a new CI provider is introduced.
Fixes #
/cc @rthallisey @fabiand 
```release-note
NONE
```

Add CI provider introduction details

---

api/openapi-spec/swagger.json
pkg/storage/export/export/vm-source.go
pkg/storage/export/export/vmsnapshot-source.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/export/v1alpha1/deepcopy_generated.go
staging/src/kubevirt.io/api/export/v1alpha1/types.go
staging/src/kubevirt.io/api/export/v1alpha1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/storage/export.go

Backport of #9145
Fixes # 
```release-note
NONE
```

[release-0.59] Show VM name in export status

---

pkg/storage/snapshot/restore.go
pkg/storage/snapshot/restore_test.go

In case we had datavolumetemplates and the storage class was WFFC we would wait for the DVs to become succeeded although with WFFC they will never be.
Instead in case of WFFC we will let the restore complete.
we currently dont have a lane with wffc snapshotable storage class defined in kubevirtCI we plan on adding periodic lane to test all our tests with wffc snapshotable storage class
Fixes # BZ https://bugzilla.redhat.com/show_bug.cgi?id=2172612
```release-note
Fix vmrestore with WFFC snapshotable storage class
```

Fix vmrestore with WFFC snapshotable storage class

---

tests/swap_test.go

This will make tests more readable and prevent
modifying nodes.
Fixes #
```release-note
NONE
```

[e2e-tests]Use nodeAffinity instead of labeling nodes

---

tests/vmi_headless_test.go

This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/9298
Fixes #
```release-note
NONE
```
/cc @xpivarc

[release-0.53] [e2e] Increase timeout for agentConnected condition

---

tests/vmi_headless_test.go

This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/9298
Fixes #
```release-note
NONE
```

[release-0.58] [e2e] Increase timeout for agentConnected condition

---

tests/vmi_headless_test.go

This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/9298
Fixes #
```release-note
NONE
```
/cc @xpivarc

[release-0.49] [e2e] Increase timeout for agentConnected condition

---

pkg/virtctl/imageupload/imageupload.go
pkg/virtctl/imageupload/imageupload_test.go

This Pull Request aims to improve the error handling in image-upload so, when uploading a DV with an already existing PVC (PVC with the same name already exists), we trigger a different error message depending on if the PVC is related or not to the DV.
1. If the PVC contains the `DeleteAfterCompletion` annotation, we assume it was created and populated by CDI and that its DV has been already garbage-collected. We now reflect that in the error message.
2. If the PVC doesn't contain that annotation, we assume it's independent of any DV. We trigger the already existing error message.
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2176422
I think we can't simply change the …

Improve error handling in image-upload when uploading a DV with already existing PVC

---

tests/storage/datavolume.go

~createdVirtualMachine is used in AfterEach() to cleanup the VM. If not properly initialized, the test may fail when deleting the object.~
Previously createdVirtualMachine was used in AfterEach() to cleanup the VM. However, the var was not properly initialized in one of the tests and that was causing failures when deleting the object. Such a cleanup is not needed in general, since VMs are deleted during global cleanup after each test.
Also ensure the other variables used for the cleanup are properly null'ed in AfterEach().
Fixes #
[This …

tests: Drop createdVirtualMachine variable

---

tests/storage/export.go

Since this test runs in parallel to the route one, 
on OKD testing, we might pick the ingress object in the route test (instead of the route), and thus fail.
Fixes #
```release-note
NONE
```

[Export tests]: Make export via ingress test serial

---

tests/operator/operator.go

The installation test of the custom seccomp profile acts like this:
1. delete previously profile in the virt-handler pod, if exists.
2. enable the feature gate in order to install the profile.
3. check if the profile exists in the virt-handler pod.
To enable the feature gate it is used the utility function `tests.EnableFeatureGate(virtconfig.KubevirtSeccompProfile)` The latter does not perform any update if the feature is already present. Since the feature is enabled by default, this results in a non action, and the profile deleted at point 1. will not be re-installed, causing the failure. To effectively check that, once you add the feature gate, the profile is installed, firstly delete the feature gate (if present), and then add it again.
**Which …

[e2e tests] Fix seccomp profile tests

---

pkg/certificates/triple/cert/cert.go
pkg/certificates/triple/cert/pem.go
pkg/certificates/triple/triple.go
pkg/storage/export/export/export.go
pkg/storage/export/export/export_test.go
pkg/virt-operator/resource/generate/components/secrets.go
pkg/virt-operator/resource/generate/components/secrets_test.go
tests/infra_test.go
tests/storage/export.go

This is a manual backport of https://github.com/kubevirt/kubevirt/pull/9127
Fixes #
```release-note
Use ECDSA instead of RSA for key generation
```

[release-0.58] Use ECDSA instead of RSA

---

tests/io_utils.go
tests/storage/storage.go

Fixes #
```release-note
NONE
```

[release-0.59] Manually backport error disk test fix

---

automation/test.sh
tests/decorators/decorators.go
tests/monitoring/monitoring.go

Add missing e2e tests for components low count  
Fixes #
```release-note
NONE
```

Add e2e tests for low count alerts

---

tests/storage/export.go

We see single node installs where this may take a little longer.
Fixes #
```release-note
NONE
```

[export tests]: Increase timeout for bound PVC

---

tests/monitoring/monitoring.go

Add e2e tests for REST errors high alerts:
- VirtApiRESTErrorsHigh
- VirtControllerRESTErrorsHigh
- VirtHandlerRESTErrorsHigh
- VirtOperatorRESTErrorsHigh
jira-ticket: CNV-22403
Fixes #
```release-note
NONE
```

Add e2e tests for REST errors high alerts

---

tests/virtctl/create_instancetype.go
tests/virtctl/create_preference.go
tests/virtctl/create_vm.go

This adds ids to create cmd related tests.
```release-note
None
```

test(virtctl): Add ids to create cmd related tests

---

ADOPTERS.md

As discussed during the project meeting on Tuesday, here is our entry to the adopters list.
```release-note
* Add Genesis Cloud to the adopters list
```

add genesiscloud to adopters

---

pkg/virtctl/create/vm/vm.go
pkg/virtctl/create/vm/vm_test.go
tests/virtctl/create_vm.go

This adds the --memory flag to virtctl create vm, which allows to specify the guest memory of a VM. If no instancetype was specified or is inferred the default value is set to 512Mi. This flag is mutually excluse with the --instancetype and --infer-instancetype flags.
Fixes #9635 
```release-note
virtctl: Allow to specify memory of created VMs. Default to 512Mi if no instancetype was specified or is inferred.
```

feat(virtctl): Add memory flag to create vm

---

OWNERS_ALIASES

#8858 proposed to introduce SMEs, SIGs, *and* reassign ownership - all at once.
This might be too much, thus this PR starts by sanitizing group names and adding the `sig-` prefix and adding empty SME groups.
In the next step members can be assigned and code can be moved to create tangible areas (SIGs for pkgs, SMEs for knowledge areas) of ownership.
Fixes #
```release-note
NONE
```

Extend SIGs

---

api/openapi-spec/swagger.json
pkg/safepath/safepath.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go
pkg/virt-handler/BUILD.bazel
pkg/virt-handler/selinux/BUILD.bazel
pkg/virt-handler/selinux/labels.go
pkg/virt-handler/vm.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

Manual cherry-pick of #8344 
```release-note
NONE
```

[release-0.58] hotplug-disk container: match SELinux level of virt-launcher

---

Makefile
pkg/instancetype/compatibility.go
pkg/instancetype/compatibility_test.go
pkg/instancetype/instancetype.go
pkg/instancetype/instancetype_test.go

This change adds the pkg/instancetype directory to the lint Makefile target and fixes some identified issues.
Fixes #
```release-note
NONE
```

instancetype: Add package to lint Makefile target and fix *some* issues

---

tests/vmi_configuration_test.go

This test sometimes timeout and therefore this
commit is trying to see if it is related to disk expansion.
Fixes #
```release-note
NONE
```

Run test Custom PCI Addresses configuration in serial & disable disk expansion

---

api/openapi-spec/swagger.json
manifests/generated/kv-resource.yaml
pkg/virt-config/configuration_test.go
pkg/virt-config/feature-gates.go
pkg/virt-config/virt-config.go
pkg/virt-handler/device-manager/device_controller.go
pkg/virt-handler/device-manager/mediated_devices_types.go
pkg/virt-handler/device-manager/mediated_devices_types_test.go
pkg/virt-handler/heartbeat/heartbeat.go
pkg/virt-handler/heartbeat/heartbeat_test.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/mdev_configuration_allocation_test.go

Fixes #
```release-note
NONE
```

[release-0.58] device manager: externally provided mediated devices should not be removed

---

pkg/testutils/mock_config.go
pkg/virt-config/configuration.go
pkg/virt-operator/BUILD.bazel
pkg/virt-operator/application.go
pkg/virt-operator/application_test.go

Reinitialize when detected to ServiceMonitor and PrometheusRule CRD has been introduced/removed.
Fixes #6551
```release-note
None
```

Detect to ServiceMonitor and PrometheusRule CRD

---

pkg/virt-handler/device-manager/BUILD.bazel
pkg/virt-handler/device-manager/socket_device.go
pkg/virt-handler/device-manager/socket_device_test.go
tests/storage/reservation.go

This PR address some left comments from #9177 and added unit test for the socket device plugin
Fixes #
```release-note
NONE
```

persistent reservation address left comments

---

pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go

Cleanup missed in https://github.com/kubevirt/kubevirt/commit/3f4e898ccbc62c2295a3571ba989101806f4e619#diff-cd1bc170fc251c2471efffe8c9a7152aed4775195fc25840d58d2ba94fee3561
Fixes #
```release-note
NONE
```

Chore: Remove unused functions in unit test

---

README.md

-  Shifted the Logo of Kubevirt at the top in the Readme file.
- And made the tag lines alignment in the centre.
Fixes #
`#Before`
`#After`
```release-note
none
```

Positional changes around the Kubevirt logo in the README.md file

---

hack/dockerized

PR#9789 fixes a build error related to git.
Use the builder image that includes that fix.
Fixes #
```release-note
NONE
```

dockerized: Update builder image

---

pkg/virt-api/webhooks/arm64.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

Fixes #8916
```release-note
NONE
```

Virt-api, Arm64: Add error message for watchdog and sound device on Arm64

---

automation/release.sh

Publish multiarch manifests with each release.
https://github.com/kubevirt/kubevirt/issues/9756
```release-note
Publish multiarch manifests with each release
```

Publish multiarch manifest with releases

---

cmd/virt-controller/kubernetes.repo

This file was created in late 2016, and it seems that there are no references to it.
Fixes #
```release-note
NONE
```

controller: Remove kubernetes.repo

---

api/openapi-spec/swagger.json
pkg/instancetype/instancetype.go
pkg/instancetype/instancetype_test.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/instancetype/v1alpha1/conversion_generated.go
staging/src/kubevirt.io/api/instancetype/v1alpha2/conversion_generated.go
staging/src/kubevirt.io/api/instancetype/v1beta1/deepcopy_generated.go
staging/src/kubevirt.io/api/instancetype/v1beta1/types.go
staging/src/kubevirt.io/api/instancetype/v1beta1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

/hold
Fixes #
```release-note
Allow to define the preferred subdomain in VirtualMachine{Preferences,ClusterPreferences}
```

instancetype: Introduce `PreferredSubdomain`

---

pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go

Signed-off-by: HF <crazytaxii666@gmail.com>
**What this PR does / why we need it**: Fixed code error. Invalid parsing result shouldn't be put into store.
Fixes #
```release-note
NONE
```

Invalid parsing result shouldn't be put into store

---

pkg/virt-handler/vm.go

**What this PR does / why we need it**: The updateVMIStatus has gotten quite long, so for maintainability and to reduce complexity, the function has been broken up. Since there were comments denoting the jobs of the various blocks of code, I moved these blocks into separate functions based on the way they were grouped up originally, as well as pulling out the code to handle sync errors and record an event when the VMI's phase changes into separate functions as well.
Fixes #
```release-note
NONE
```

code cleanup: break up virt-handler's updateVMIStatus function

---

OWNERS_ALIASES

I would like to propose a nomination of Itamar Holder AKA @iholder101 for core approver role.
Itamar is one of the [main contibutors](https://github.com/kubevirt/kubevirt/graphs/contributors) to Kubevirt. To me he is a great asset to the kubevirt core. He has:
* More than 100 [merged PRs](https://github.com/kubevirt/kubevirt/pulls?q=is%3Aclosed+is%3Apr+author%3Aiholder101+is%3Amerged+)
* More than 100 [reviews](https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+commenter%3Aiholder101+is%3Aclosed+-author%3Aiholder101+is%3Amerged)
I would like to note some of his most significant efforts:
- cgroup v2 support (https://github.com/kubevirt/kubevirt/pull/6042)
- Live-Migration Policies API …

nominate iholder101 as core approver

---

tests/storage/reservation.go

Fix error message print in the Expect
Fixes #
```release-note
NONE
```

tests: fix error print on Expect

---

tests/testsuite/namespace.go

This is a  manual cherrypick of https://github.com/kubevirt/kubevirt/pull/9786
Fixes #
```release-note
NONE
```

[release-0.58] e2e: Remove events in the namespace after each test

---

hack/prom-metric-linter/metric_name_linter.sh

Fix the lint-metrics test to fail only when needed.
Fixes #
```release-note
```

[BUG] Fix lint-metrics ci test

---

BUILD.bazel
hack/bazel-push-images.sh
hack/push-container-manifest.sh

https://github.com/kubevirt/kubevirt/pull/8989#issuecomment-1599126575
Fixes #9964
```release-note
NONE
```

push multiarch manifest for utility images

---

tests/migration_test.go

Adds tests IDs to cluster-wide eviction strategy tests
Fixes #
```release-note
None
```

Adding test id to cluster level eviction strategy tests

---

tests/framework/checks/skips.go
tests/migration_test.go
tests/network/expose.go
tests/operator/operator.go
tests/replicaset_test.go
tests/swap_test.go

Removes redundant skips against old, unsupported Kubernetes versions.
Fixes #
```release-note
NONE
```

Remove redundant skips

---

hack/prom-rule-ci/prom-rules-tests.yaml
pkg/virt-operator/resource/generate/components/prometheus.go

This is a manual cherry-pick of #9073
Fixes #
```release-note
Fix incorrect KubevirtVmHighMemoryUsage description
```

[release-0.58] Fix incorrect KubevirtVmHighMemoryUsage description

---

hack/prom-rule-ci/prom-rules-tests.yaml
pkg/virt-operator/resource/generate/components/prometheus.go

This is a manual cherry-pick of #9073
Fixes #
```release-note
Fix incorrect KubevirtVmHighMemoryUsage description
```

[release-1.0] Fix incorrect KubevirtVmHighMemoryUsage description

---

tests/hotplug/cpu.go

Cover cases where returned error is not checked
Fixes #
```release-note
NONE
```

[e2e-fix] Expect error have not occurred during vm creation

---

.github/PULL_REQUEST_TEMPLATE.md

In the last kubevirt CI group meeting it was discussed that a default to create draft PRs would be favorable. Unfortunately this is not possible: https://github.com/refined-github/refined-github/issues/2238
Thus we add a comment to the Pull Request template notifying the author to consider creating a draft PR, linking the CONTRIBUTING.md section of draft PRs.
Fixes #
```release-note
NONE
```

Add note to consider draft PR to pull request template

---

tests/mdev_configuration_allocation_test.go

Enable the test in order to collect feedback from CI
Fixes #
```release-note
NONE
```

Remove mediated devices from quarantine

---

pkg/virt-operator/resource/apply/apps.go
tests/scale/BUILD.bazel
tests/scale/virt-api.go

Fix virt-api replicas calculation conflict
replicas should be determined by patch if
set otherwise by current heuristics.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2175710
Fixes #
```release-note
NONE
```

Fix patch api conflict

---

tests/launchsecurity/sev.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/10026 to 1.0
Fixes #
/cc @vasiliy-ul @dhiller @xpivarc 
```release-note
NONE
```

[release-1.0] Fix flaky SEV test

---

pkg/virt-operator/resource/apply/apps.go
tests/scale/BUILD.bazel
tests/scale/virt-api.go

This is a backport PR of:
https://github.com/kubevirt/kubevirt/pull/10027
Fixes #
```release-note
NONE
```

[Release-0.58] Fix patch api conflict

---

pkg/cloud-init/cloud-init.go
pkg/cloud-init/cloud-init_test.go

Moves a function to a test file as it is not needed in production code.
Fixes #
```release-note
NONE
```

Cloud init: remove unused function

---

ADOPTERS.md

Signed-off-by: SIMON COTER <simon.coter@oracle.com>
Add Oracle to the ADOPTERS list for KubeVirt
```release-note
NONE
```

add Oracle to the Adopters list

---

pkg/virt-controller/services/template_test.go
pkg/virt-handler/container-disk/mount.go
tests/migration_test.go
tests/vm_test.go
tests/vmi_kernel_boot_test.go
tools/vms-generator/utils/BUILD.bazel
tools/vms-generator/utils/utils.go

A set of tiny fixes to kernel boot tests and code.
Please see commits for more info.
```release-note
NONE
```

[Kernel Boot]: Tiny fixes - typo fix, unique name for test VMIs

---

tests/network/vmi_lifecycle.go

This ensures we catch something like https://github.com/kubevirt/kubevirt/pull/9616#issuecomment-1566168918 in the sig-compute lane,
with a test that isn't likely to get skipped (i.e. unsupported bridge binding on some platforms)
Fixes #
```release-note
NONE
```

Duplicate kubelet restart test in sig-compute

---

automation/repeated_test.sh

If the file `tests/tests_suite_test.go` is included in the set of changed files, it will pull in all the other tests, which will void using `-focus-file` flag.
Example: PR https://github.com/kubevirt/kubevirt/pull/9902 , job run https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9902/pull-kubevirt-check-tests-for-flakes/1678382062605701120#1:build-log.txt%3A2275
Thus we extend the filtering grep to also exclude the suite file.
We also add `--dry-run` flag in order to see which tests will actually be run but neither executing them nor spinning up the cluster if the flag is set.
Finally we move the cluster-sync out of the inner loop, since we only need to do this once at the start of the test cycle, since if a test fails …

repeated_test: Remove tests_suite_test.go from focus-file set

---

api/openapi-spec/swagger.json
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/schema.go
staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

It's leaving a hint in the API docs about what type of console we are adding
Fixes #
```release-note
NONE
```

converter: Hint at the type of serial console

---

tests/network/hotplug.go

Test `[sig-network] nic-hotunplug a stopped VM cannot be subject to **hot** unplug, but will mutate the template.Spec on behalf of the user` may be flaky and sometimes have a panic.
The test is waiting for `Absent` interface to appear in the VMI spec after it was aded to the VM template spec. 
However, since the `Absent` interfaces are eventually removed from the spec, a condition waiting for the VMI interface to be Absent may be flaky.
Fixing the test to wait for the VMI interface to be Absent or to be removed from the spec.
Fixes # …

bridge hotunplug, e2e flake: test may miss the stage when VMI interface Absent

---

pkg/instancetype/instancetype.go
pkg/instancetype/instancetype_test.go

/cc @AlonaKaplan 
/cc @oshoval
/cherry-pick release-1.0
As set out in https://github.com/kubevirt/kubevirt/issues/10053 we shouldn't apply `PreferredInterfaceMasquerade`
when another binding is configured for an interface such as SRIOV etc.
We also shouldn't apply PreferredInterfaceMasquerade on non PodNetwork
interfaces. This change introduces basic checks for each of these and
adds simple unit test coverage.
Fixes #10053
```release-note
NONE
```

instancetype: Improve `PreferredInterfaceMasquerade` application 

---

tests/network/hotplug.go

Test [sig-network] nic-hotunplug a stopped VM cannot be subject to **hot** unplug, but will mutate the template.Spec on behalf of the user may be flaky and sometimes have a panic.
The test is waiting for Absent interface to appear in the VMI spec after it was aded to the VM template spec.
However, since the Absent interfaces are eventually removed from the spec, a condition waiting for the VMI interface to be Absent may be flaky.
Fixing the test to wait for the VMI interface to be Absent or to be removed from the spec.
Fixes #
Backport of …

[release-1.0] bridge hotunplug, e2e flake: test may miss the stage when VMI interface Absent

---

ADOPTERS.md

A small hint in the adopters filw of how to add yourself to the file
Fixes #
```release-note
NONE
```

adopters: Small hint of how to add yourself.

---

cmd/virt-launcher/virt-launcher.go

The ticker is not stopped, It will leak
Fixes #
```release-note
NONE
```

fix ticker leak

---

pkg/storage/snapshot/snapshot_base.go
tests/storage/snapshot.go

There should always be a VolumeSnapshotClass for "rook-ceph-block" StorageClass.  But the vmsnapshot controller may not have initialized it's VolumeSNapshotClass informer before processing VMSnapshot work items.  Especially in failover/restart situations 
Fixes #
```release-note
NONE
```

Address sig-storage flakes with in memory etcd

---

tests/network/hotplug.go

Interfaces set with state 'absent' of stopped VMs are expected to be removed from spec.
Fixes #
```release-note
NONE
```

[release-1.0] e2e, hotplug ifaces: Assert absent ifaces removed from spec of stopped VMs

---

tests/decorators/decorators.go
tests/hotplug/cpu.go

This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/10196
Fixes #
```release-note
NONE
```

[release-1.0][e2e] Decorate hotplug tests with VMLiveUpdateFeaturesGate decorator

---

pkg/hotplug-disk/hotplug-disk.go
pkg/hotplug-disk/hotplug-disk_test.go
pkg/virt-handler/hotplug-disk/mount.go
pkg/virt-handler/hotplug-disk/mount_test.go

Fixes #
Quick grep shows that `sourcePodBasePath` and `targetPodBasePath` are not actually used in the code.
```release-note
NONE
```

Cleanup unused code (hotplug disks)

---

cmd/virt-chroot/BUILD.bazel
cmd/virt-chroot/selinux.go
cmd/virt-handler/virt-handler.go
pkg/storage/reservation/pr.go
pkg/util/util.go
pkg/virt-handler/device-manager/socket_device.go
pkg/virt-operator/resource/generate/components/BUILD.bazel
pkg/virt-operator/resource/generate/components/daemonsets.go
tests/storage/BUILD.bazel
tests/storage/reservation.go

Manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/10186
Fixes #
```release-note
NONE
```

[release-1.0] Fix pr leftover mount

---

cmd/virt-handler/BUILD.bazel
cmd/virt-handler/virt-handler.go
pkg/virt-handler/device-manager/socket_device.go
pkg/virt-operator/resource/generate/components/daemonsets.go

Fix the user for the pr-helper container and fixes the directory permission on device creation.
This PR contains should be merged after #10186.
See [comment](https://github.com/kubevirt/kubevirt/pull/10186#issuecomment-1665222614) about the directory permission and [comment](https://github.com/kubevirt/kubevirt/pull/10186#issuecomment-1665289361) for the user.
Fixes #
```release-note
NONE
```

reservation: fix user 

---

cmd/example-hook-sidecar/README.md
docs/getting-started.md

This PR makes the following documentation changes:
1. Steps to enable feature gate(s) for dev cluster (I couldn't find this in existing docs)
2. Correct the path for trying sidecar hook in the examples.
Fixes - N/A
```release-note
NONE
```

Doc to enable feature gate in dev cluster and correct path

---

BUILD.bazel
cmd/example-hook-sidecar/BUILD.bazel
cmd/example-hook-sidecar/smbios.go
cmd/sidecars/BUILD.bazel
cmd/sidecars/README.md
cmd/sidecars/sidecar_shim.go
hack/bazel-push-images.sh
hack/config-default.sh
tests/vmi_hook_sidecar_test.go

This is a PoC of [Fabian's suggestions](https://github.com/kubevirt/kubevirt/pull/9166#issuecomment-1420439281) to have a base container that wraps the gRPC boilerplate and can be easily extended by those who want to write their own sidecars.
I'd also like to discuss if https://github.com/kubevirt/kubevirt/pull/6975 would not be a viable alternative as well.
Relates to (but not fixes) #8420 
This is a PoC. The base container is amd64 only at this moment. Not 100% sure the functional tests are working.
```release-note
Introduces sidecar-shim …
```

Meta sidecar

---

pkg/virt-launcher/virtwrap/live-migration-source.go

https://bugzilla.redhat.com/show_bug.cgi?id=2160622
Fixes #
```release-note
NONE
```

virt-launcher: log migration info in MB and Mbps

---

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go

**What this PR does / why we need it**: The ValidateVirtualMachineSpec and validateVolumeRequests functions in virt-api VMs admitter were both very long. This PR aims to make these functions simpler and less long by extracting parts of it into separate functions.
Fixes #
```release-note
NONE
```

(code cleanup) Simplify validate functions in virt-api VMs admitter

---

OWNERS_ALIASES

My work assignments don't allow me to do repeated carefule code-review. We have luckily now a solit set of reviewers which are aware of the main architecture of kubevirt and can perform review.
I still plan to spend time on the approver role, to be able to perform checks if the superficial palcements regarding architecture, API and so forth are on the right place.
Fixes #
```release-note
NONE
```

Removing myself as code reviewer

---

pkg/virtctl/imageupload/imageupload.go

Apparently with k8s 1.28 there may be some contention between kube-controller and provisioner
Fixes # 
https://issues.redhat.com/browse/CNV-32500
**Checklist**
```release-note
NONE
```

fix flaky archive upload test

---

docs/filesystem-pv-disks.md
docs/reviewer-guide.md
docs/vm-configuration.md

Correct some spelling errors in the document
Fixes #
fix typos.
**Checklist**
```release-note
```

fix typos.

---

.github/PULL_REQUEST_TEMPLATE.md

Updates the PR Template wording a little.
Fixes #
**Checklist**
```release-note
```

PR Template: Small rewording (no scope change)

---

ADOPTERS.md

update ADOPTERS.md to add KubeSphere as an adopter for KubeVirt 
Fixes #
```release-note
KubeSphere added to the adopter's file!
```

update ADOPTERS.md to add KubeSphere as an adopter for KubeVirt

---

tests/infrastructure/node-labeller.go

Make sure we do not override the default map
Fixes #
**Checklist**
```release-note
NONE
```

Fix flaky node labeller test

---

docs/README.md
docs/container-empty-disks.md

fix syntax errors in order to make coders read better
Fixes #
**Checklist**
```release-note
```

fix syntax errors

---

tests/utils.go
tests/vmi_configuration_test.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/10235
Fixes #
**Checklist**
```release-note
NONE
```

[release-1.0] Replace/sanitize `ps` calls in isolated emulator thread tests

---

pkg/virtctl/create/vm/vm.go
pkg/virtctl/create/vm/vm_test.go
tests/virtctl/create_vm.go

This enables the inference of instancetype and preferences in the virtctl create vm subcommand by default.
**Checklist**
```release-note
virtctl: Enable inference in create vm subcommand by default
virtctl: Add --infer-instancetype-from and --infer-preference-from switches to create vm subcommand
```

virtctl: Enable inference in create vm by default

---

tests/clone_test.go

We were hardcoding the ns to `kubevirt-test-default`, but for the sig-*-root lanes we want to dynamically decide that based on the root feature gate.
Fixes #
**Checklist**
```release-note
NONE
```

[e2e tests] Fix sig-storage-root periodic by not hardcoding default ns

---

go.mod
go.sum
vendor/github.com/opencontainers/runc/libcontainer/cgroups/ebpf/ebpf_linux.go
vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/fs.go
vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/memory.go
vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
vendor/github.com/opencontainers/runc/libcontainer/user/user.go
vendor/modules.txt

The current version - v1.1.4 - has a CVE - [0], and thus should be updated.
The original reported github security advisory is [1].
[0] - https://nvd.nist.gov/vuln/detail/CVE-2023-25809
[1] - https://github.com/opencontainers/runc/security/advisories/GHSA-m8cg-xc2p-r3fc
Fixes #
**Checklist**
```release-note
NONE
```

build: update github.com/opencontainers/runc version

---

pkg/virt-handler/heartbeat/BUILD.bazel
pkg/virt-handler/heartbeat/ksm_test.go

Fix tests introduced in https://github.com/kubevirt/kubevirt/pull/10477
Fixes #
**Checklist**
```release-note
NONE
```

Fix no-op unit tests

---

hack/bootstrap.sh
hack/rpm-deps.sh
rpm/BUILD.bazel

We do rpm generation with Bazel. This PR fixes it for sidecar-shim image.
Fixes #
Missed from https://github.com/kubevirt/kubevirt/pull/10479
**Checklist**
```release-note
NONE
```

Fix sidecar shim rpm generation

---

pkg/virt-handler/node-labeller/cpu_plugin_test.go

Remove usage BeforeSuite. Prevent tests from being dependent on their order.
Fixes #
**Checklist**
```release-note
NONE
```

Remove usage BeforeSuite

---

tests/network/vmi_passt.go

This PR extend passt e2e test to cover MAC and PCI addresses settings 
Fixes #
**Checklist**
```release-note
NONE
```

e2e, passt: Extend test to cover explicit MAC and PCI addresses setting

---

pkg/virtctl/create/vm/vm.go
pkg/virtctl/create/vm/vm_test.go
tests/virtctl/create_vm.go

Using the `--volume-import` flag with `PVC` and `Snapshot` types may result in VMs taking ownership of cloned DVs due to the incorrect use of the name parameter. To resolve this issue, we are introducing the src parameter for the `--volume-import` flag.
Fixes https://github.com/kubevirt/kubevirt/issues/10592
**Checklist**
```
None
```

fix virtctl create vm volume-import flag

---

Makefile
WORKSPACE
automation/conformance.sh
docs/conformance.md
hack/conformance.sh
tests/console/login.go
tests/framework/checks/checks.go
tests/framework/checks/skips.go
tests/network/networkpolicy.go
tests/network/services.go
tests/reporter/BUILD.bazel
tests/reporter/kubernetes.go
tests/storage/storage.go
tests/utils.go
tests/vmi_configuration_test.go

Make conformance tests run on Arm64 platform
```release-note
None
```

Arm64, conformance test: initial enablement for conformance tests on Arm64

---

OWNERS_ALIASES

Unfortunately, I’m no longer involved in the KubeVirt project.
Fixes #
This PR removes me form the list of code reviewers.
**Checklist**
```release-note
NONE
```

Remove me as a code reviewer

---

Makefile
hack/bootstrap-ginkgo.sh
hack/build-ginkgo.sh
pkg/virt-api/webhooks/fuzz/BUILD.bazel
pkg/virt-api/webhooks/fuzz/fuzz_suite_test.go
pkg/virtctl/credentials/add-key/BUILD.bazel
pkg/virtctl/credentials/add-key/add-key_test.go
pkg/virtctl/credentials/add-key/add_key_suite_test.go
pkg/virtctl/credentials/remove-key/BUILD.bazel
pkg/virtctl/credentials/remove-key/remove-key_test.go
pkg/virtctl/credentials/remove-key/remove_key_suite_test.go
pkg/virtctl/credentials/set-password/BUILD.bazel
pkg/virtctl/credentials/set-password/set-password_test.go
pkg/virtctl/credentials/set-password/set_password_suite_test.go

We no longer have the ginkgo cli since https://github.com/kubevirt/kubevirt/commit/9d9b35ec9909f126f6836bbf661ae4fc6831fbec so this script silently fails.
Fixes #
```release-note
NONE
```

Fix ginkgo bootstrap script

---

tests/infrastructure/tls-configuration.go
tests/operator/operator.go

From recent flakefinder we see these tests to fail. Lets improve the debug info to help us identify root cause.
Fixes #
**Checklist**
```release-note
NONE
```

Improve debug info of some tests

---

OWNERS_ALIASES

Nominate @fossedihelm officially as code reviever. Federico has a strong history of reviewing PRs, so this change makes the obvious official :)
PRs reviewed:
https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+is%3Amerged+reviewed-by%3Afossedihelm+
Fixes #
/cc @xpivarc @acardace 
**Checklist**
```release-note
NONE
```

Nominate fossedihelm as reviewer

---

tests/BUILD.bazel
tests/testdata/sidecar-hook-configmap.sh
tests/vmi_hook_sidecar_test.go

Fixes #
**Checklist**
```release-note
Functional tests for sidecar hook with ConfigMap
```

Functional tests for sidecar hook with ConfigMap

---

pkg/util/openapi/BUILD.bazel
pkg/util/openapi/openapi.go
pkg/virt-api/BUILD.bazel
pkg/virt-api/api.go

clean deprecated func
Fixes #
**Checklist**
```release-note
NONE
```

clean deprecated code

---

cmd/virt-launcher-monitor/virt-launcher-monitor.go

virt-launcher-monitor is (eventually) preparing
a file to signal the request for a quick
shutdown to virt-tail if all the others
IPC mechanisms are failing.
This file is in the private dir that is
asyncronously initialized virt-launcher
so some file creation attempts are expected
to fail on virt-launcher-monitor side.
Be less verbose on them to avoid polluting
logs with false error messages.
Fixes: None
log cleaning only
**Checklist** …

be less verbose during virt-launcher-monitor startup

---

.snyk

feat: add .snyk file
This file is used for excluding vendor folders from snyk code scans
```release-note
NONE
```

[release-1.0]feat: add .snyk file

---

.snyk

feat: add .snyk file
This file is used for excluding vendor folders from snyk code scans
```release-note
NONE
```

[release-1.1]feat: add .snyk file

---

.snyk

feat: add .snyk file
This file is used for excluding vendor folders from snyk code scans
```release-note
NONE
```

[release-0.58]feat: add .snyk file

---

.snyk

feat: add .snyk file
This file is used for excluding vendor folders from snyk code scans
```release-note
NONE
```

[release-0.59]feat: add .snyk file

---

tests/guestlog/guestlog.go

Functional test
"it should not skip any log line even trying to
flood the serial console for QOSGuaranteed VMs"
is generating many sequential log lines over the serial console fetching the output from k8s log api
and ensuring that all the expected logs lines are
there and in the correct order.
Looking at periodic jobs results the test
is sometimes (~10%) failing due to duplicated
chars in the logs, something like:
```
logline 0006195 0006195 0006195 0006195 0006195 0006195 0006195 0006195 0006195 0006195 0006195 0006195 0006195 0006195 0006195
loglline 0006196 0006196 0006196 0006196 0006196 0006196 0006196 0006196 0006196 0006196 0006196 0006196 0006196 0006196 0006196
logline 0006197 0006197 0006197 0006197 0006197 0006197 0006197 0006197 0006197 …
```

[test] dump serial console log for debug purposes

---

pkg/virt-controller/services/template.go

when we add tolerations to vm, the corresponding hotplug pod should also add tolerations automatically

hotplug pod can get tolerations from launcher pod

---

pkg/virt-launcher/virtwrap/api/schema.go

Generates valid libvirt xml
Fixes #
```release-note
NONE
```

Fix generated xml

---

tests/infrastructure/prometheus.go

There are two tests that check for leader pods of the virt-controller and virt-operator components - these steps for checking the leader pod can be moved to its own function. 
Fixes #
**Checklist**
- ~[ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required~
- ~[ ] Upgrade: Impact of this change on upgrade flows was considered …

[e2e] Move the check for leader pod to its own function

---

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go

This reverts commit fb9c692099011243e1bac6af643e29551980262b.
Reverting until issues pointed out by https://github.com/kubevirt/kubevirt/pull/10840#issuecomment-1850501004 get addressed.
Fixes #
**Checklist**
```release-note
NONE
```

Revert "virt-api: request/limits can now be used with CPU/Memory hotplug

---

tests/network/vmi_networking.go

The bridge and masquerade network bindings do not support dynamic IPv6 allocation, or more accurately, it supports only DHCPv6 without RA.
In practice, it requires users to define IPv6 routes manually. Tests have been using this method to configure IPv6:
```
dhclient -6 eth0
ip -6 route add <Network CIDR> dev eth0
ip -6 route add default via <gateway>
```
In addition, cloud-init network configuration have been setting DHCPv6 as enabled, causing the guest client (in the tests, it is NetworkManager) to expect IPv6 dynamic allocation. While older NM version did not block on not receiving an address, new ones do.
Therefore, this change replaces the cloud-init network DHCPv6 setting to a static IPv6 configuration and removes the manual configuration in …

tests, net: Replace semi-dynamic IPv6 configuration with a static one

---

tests/network/vmi_networking.go

Most of the masquerade tests configure IPv6 on the guest statically. To cover DHCP6, one test was changed to use DHCP6.
Fixes #
**Checklist**
```release-note
```

test DHCP6: change one test to use DHCP6

---

tests/storage/storage.go

No reason to import the same package twice, with two different names.
**Checklist**
```release-note
NONE
```

tests/storage: import kubevirt.io/api/core/v1 only once

---

OWNERS_ALIASES

Unfortunately, rhrazdil is no longer active in the project. Therefore, removing him from the reviewers list.
Fixes #
**Checklist**
```release-note
NONE
```

reviewers: Remove rhrazdil from the active reviewers list

---

pkg/network/driver/procsys/netip.go

Fixes #
fix: when disable ipv6  leads to err  (#10857)
**Checklist**
```release-note
```

fix: when disable ipv6  leads to err  (#10857)

---

tests/BUILD.bazel
tests/compute/BUILD.bazel
tests/compute/console_test.go
tests/console_test.go
tests/libvmi/vmi.go

Clean up tests that do the same thing.
Fixes #
**Checklist**
```release-note
NONE
```

Drop similiar console tests

---

tests/storage/imageupload.go

Follow-up for https://github.com/kubevirt/kubevirt/pull/10532. Following some offline conversations, we've decided that it's appropriate to add coverage for this flag in functional tests.
Fixes #
```release-note
NONE
```

Add test coverage for --volume-mode flag in image-upload

---

tests/storage/imageupload.go

Follow up for https://github.com/kubevirt/kubevirt/pull/10890#discussion_r1443035176.
This Pull Request cleans up some redundant deletes in the image-upload tests.
```release-note
NONE
```

tests: Clean-up redundant deletes in image-upload tests

---

tests/libvmi/OWNERS

Edy is the original author of this wonderful library. With this PR he will own it.
Grant @EdDev maintainer rights for libvmi.
Fixes #
**Checklist**
```release-note
NONE
```

libvmi: EdDev to be an approver

---

OWNERS_ALIASES

I started collaborating to KubeVirt back in 2020 but most of my contributions were from last year. My work in Red Hat's virtualization team is very connected with KubeVirt, so I expect to things keep progressing well in 2024.
Most of my reviews or help (e.g: slack) are around areas that I've worked already, like sidecars, device plugins and virtctl.
As required per [policy](https://github.com/kubevirt/community/blob/main/membership_policy.md) my approver sponsor is @alicefr (thanks!)
- 20 [PRs merged](https://github.com/kubevirt/kubevirt/pulls?q=author%3Avictortoso+is%3Apr+is%3Amerged)
- 06 [reviewed PRs](https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+is%3Amerged+reviewed-by%3Avictortoso+-author%3Avictortoso …

Nominate victortoso as reviewer

---

tests/operator/operator.go

Remove uneseccary lambda function that contains
hard-coded parameter.
```release-note
None
```

tests: remove sanityCheckDeploymentsExist() lambda

---

pkg/virtctl/create/vm/vm.go
pkg/virtctl/create/vm/vm_test.go
tests/virtctl/create_vm.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/10627 to adjust the release note.
Fixes #
**Checklist**
```release-note
Warning: This changes the way the CLI of virtctl works when using --volume-import.
The src parameter was added to --volume-import, which decouples the name parameter for the destination DV from the name of the source PVC.
```

[release-1.1] fix virtctl create vm volume-import flag

---

tests/access_test.go

The OpenShift specific access tests do not run in any e2e lane and are not required anymore, therefore drop them.
Fixes #10522
**Checklist**
```release-note
None
```

chore: Drop the OpenShift specific access tests

---

docs/network-binding-plugin.md

When there is a need to change the pod network namespace, CNI plugins can be used by a network binding.
The part CNI has in creating a network binding is described in a new section named "The Complete Plugin".
Fixes #
**Checklist**
```release-note
NONE
```

docs, network binding: The use of CNI plugins

---

cmd/virtctl/OWNERS
pkg/virtctl/OWNERS

Making 0xFelix and oshoval maintainer and mentee of virtctl.
They have been active in this area in the past.
Fixes #
This does give 0xFelix approval rights for virtctl related things.
**Checklist**
```release-note
NONE
```

virtctl: Add owners

---

.github/PULL_REQUEST_TEMPLATE.md

Fix a template markup issue
```release-note
NONE
```

PR template: Fix markup

---

OWNERS_ALIASES
pkg/handler-launcher-com/OWNERS
pkg/virt-handler/OWNERS

make sure that we have specialists
Fixes #
This is adding no new approver permissions, only defining ownership of some paths.
**Checklist**
```release-note
NONE
```

sig-node: Introduce some responsibilities

---

automation/test.sh

If there are only docs or ownership changes, then there were no code changes, thus why should we run functests in that case?
This is a pragmatic change in order to exit early in case of only known non-CI impacting changes.
Before this PR: functests were run on every change
After this PR: functests are exited early ("not run") in the case of changes limited to `docs/*` and `*/OWNERS`.
The following tradeoffs were made: Simple change in order to safe compute resources
The following alternatives were considered: Adding it to prow, but this seemed to be complex.
- None
None
```release-note
NONE
```

functest: If doc changes only, then skip functests

---

tests/hotplug/cpu.go
tests/hotplug/memory.go

Signed-off-by: 
Vasiliy Sibirsky [vsibirks@redhat.com](mailto:vsibirks@redhat.com)
What this PR does / why we need it: 
Add test IDs for CPU/Memory hotplug tests
Release note:
```release-note
NONE
```

Add test IDs for CPU/Memory hotplug tests

---

cmd/virt-freezer/main.go

This PR adds better logging to handle error we might get when backing up and freezing windows VM
Fixes #
-
```release-note
None
```

Handle virt-freezer failures focused on possible freeze windows vm issues

---

tests/storage/snapshot.go

Hey all,
There is a bug preventing snapshot-related finalizers from being removed after the resource is deleted. Following some offline discussions we've decided it's better to quarantine this test until the bug is addressed.
We should probably close https://github.com/kubevirt/kubevirt/pull/11236 after merging this.
**Release note:**
```release-note
NONE
```

[e2e] Quarantine flaky fsfreeze test

---

tests/BUILD.bazel
tests/infrastructure/BUILD.bazel
tests/infrastructure/certificates.go
tests/utils.go

Move GetCertFromSecret() out of utils
to the only place where it is used.
```release-note
None
```

tests: move GetCertFromSecret()

---

go.mod
go.sum
pkg/monitoring/metrics/virt-controller/BUILD.bazel
pkg/monitoring/metrics/virt-controller/migration_metrics.go
pkg/monitoring/metrics/virt-controller/perfscale_metrics.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram_vec.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/registry.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary_vec.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/wrapper_registry.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/prometheusrules.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/registry.go
vendor/modules.txt

There was an error setting up prometheus.Histogram buckets in operator-observability package
After this PR:
operator-observability version is updated to 0.0.14 which already has the bug fix
Fixes #
```release-note
Fix perfscale buckets error
```

Fix perfscale buckets error

---

docs/backup-restore-integration.md

Document VM instancetype and preference controller revisions in the VM backup dependency graph
```release-note
None
```

[Doc] Add VM instancetype and preference controller revisions to backup graph

---

tests/compute/credentials.go

Fixes a failing compute root lane. https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.29-sig-compute-root/1760142493132787712
Fixes #
```release-note
NONE
```

Fix credential tests: Create secrets in VMI's namespace

---

pkg/virt-handler/heartbeat/ksm.go

These vars are used only in calculateNewRunSleepAndPages They should be defined in this func as local vars
For better Encapsulation.
After this PR:
Fixes #
```release-note
NONE
```

ksm.go: move global vars to be local vars

---

OWNERS_ALIASES
cmd/libguestfs/OWNERS
cmd/pr-helper/OWNERS
cmd/virt-exportserver/OWNERS

Add sig-storage ownership to additional paths and add alicefr in the sig-storage approvers.
```release-note
NONE
```

Sig-storage ownership

---

docs/update-go-version.md

Change the GIMME_GO version in the [hack/builder/Dockerfile](https://github.com/kubevirt/kubevirt/blob/main/hack/builder/Dockerfile) to the desired Go version.
After this PR:
Change the GIMME_GO_VERSION in the [hack/builder/Dockerfile](https://github.com/kubevirt/kubevirt/blob/main/hack/builder/Dockerfile) to the desired Go version.
Fixes #
```release-note
NONE
```

Fix a typo in update-go-version doc

---

pkg/storage/snapshot/restore.go
pkg/storage/snapshot/restore_test.go
pkg/storage/types/pvc.go
pkg/virt-controller/watch/workload-updater/workload-updater_test.go
pkg/virt-operator/resource/generate/install/strategy.go
pkg/virtctl/expose/expose.go

The same package is imported repeatedly using different names.
After this PR:
Remove duplicate packages
Fixes #
```release-note
NONE
```

[refectory] remove duplicated package

---

tests/network/vmi_subdomain.go

Add test coverage for spec hostname.

Add coverage for spec hostname

---

pkg/virt-launcher/virtwrap/manager.go

SyncVMI had 175 lines and doing VirDomain creation, handling VirtDomainState related logic, handling disks and network attachments.
After this PR:
SyncVMI has 43 lines due to creation of 4 helper functions.
Fixes #
I'm actually working on improving https://github.com/kubevirt/kubevirt/pull/11324 to help avoid issues with hook sidecars... this changes are not required for that, but helped a bit separate which the code I need to change, etc.
```release-note
NONE
```

refactor: factor out some logic from virtwrap's SyncVMI

---

ADOPTERS.md

This PR adds Microsoft Corporation as an adopter of KubeVirt.

Add Microsoft as a KubeVirt adopter

---

tests/clone_test.go
tests/framework/matcher/phase.go
tests/migration/migration.go
tests/storage/datavolume.go
tests/storage/export.go
tests/storage/imageupload.go
tests/storage/restore.go
tests/storage/snapshot.go
tests/storage/storage.go
tests/utils.go
tests/virtiofs/BUILD.bazel
tests/virtiofs/datavolume.go
tests/vmi_configuration_test.go

This is a manual cherry-pick of #11478 
```release-note
NONE
```

[release-1.2] Fix tests to pass with snapshotable wffc storage

---

tests/storage/datavolume.go

- A test in datavolume.go would use the deprecated function NewRandomVirtualMachineInstanceWithDisk
After this PR:
- The test would use libvmi instead as notified in the deprecation warning
After this PR it would be easier to remove NewRandomVirtualMachineInstanceWithFileDisk and NewRandomVirtualMachineInstanceWithBlockDisk
```NONE
NONE
```

Remove NewRandomVirtualMachineInstanceWithDisk from datavolume test

---

tests/infrastructure/node-labeller.go
tests/libmigration/migration.go
tests/libnode/node.go
tests/migration/migration.go
tests/utils.go

Move function to its right context
```release-note
NONE
```

tests/utils: move GetNodeHostModel to libnode

---

tests/vmi_configuration_test.go

Test fails when root.
After this PR:
Test passes when root.
```release-note
NONE
```

tests: fix namespace bug with root

---

pkg/virt-launcher/virtwrap/converter/vcpu/vcpu_test.go

The rand.Seed() function has been deprecated, and the official document recommends the rand.New(rand.NewSource) function.
The math/rand package now automatically seeds the global random number generator (used by top-level functions like Float64 and Int) with a random value, and the top-level Seed function has been deprecated. Programs that need a reproducible sequence of random numbers should prefer to allocate their own random source, using rand.New(rand.NewSource(seed)). -  https://tip.golang.org/doc/go1.20 -
Fixes # …

refectory: replace Seed() function to New() and NewSource() function

---

tests/storage/hotplug.go

Try at least 3 times, this is done because `AddVolume` is inherently racy in the way it's implemented as when it patches the VM Status it expects the field `volumeRequests` to be there (by using a test json patch op), but at the same time virt-controller trims this field when all requests have been satified. To avoid hitting these we should explicitly try multiple times.
This is being changed after a few failures in the upstream CI where this race condition was seen
https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.30-sig-storage/1775991881285505024.
Why isn't the `Eventually` not enough? Because it tries for 3 seconds and does not guarantee that the op will be tried more than once.
Test [sig-storage] Hotplug [storage-req] Online VM should …

tests: always try adding a hotplug volume 3 times

---

OWNERS_ALIASES

`sig-buildsystem` did have only one approver.
After this PR:
`sig-buildsystem` has three approvers.
Fixes #
n/a
n/a
/cc @xpivarc @brianmcarey @fabiand @jean-edouard
- ~[ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required~
- ~[ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)~
- ~[ ] …

sig-buildsystem: nominate xpivarc and brianmcarey as approvers for sig-buildsystem

---

pkg/virt-controller/services/nodeselectorrenderer.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-controller/watch/topology/tsc.go
tests/hyperv_test.go
tests/libnode/node.go
tests/vmi_configuration_test.go
tests/vmi_lifecycle_test.go

Use well defined constants for labels.
Fixes #
```release-note
NONE
```

Consolidate node-labeller's labels usage

---

pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/snapshot_base.go
pkg/storage/snapshot/snapshot_test.go
tests/clone_test.go
tests/storage/snapshot.go
tests/testsuite/namespace.go

Remove a couple tests from quarantine.  The tests were not failing directly.  Rather they were not being fully cleaned up resulting in failures in `AfterSuite`.
After this PR:
Fixes #
https://issues.redhat.com/browse/CNV-33473
```release-note
NONE
```

Un-quarantine clone tests

---

tests/libwait/wait.go

The `watchVMIForPhase` function tries to fetch the vmi waiting for a specific phase.
During the `Eventually` the original vmi variable is continuously overwritten by the retrieved value one.
This could lead to a failure of the whole `Eventually` in case of one of the `Get` before reaching the desired phase fails. This is because the later attempts will not provide to the `Get` operation the correct vmi name, Actually the later attempts will provide an empty name.
In fact, a `Get` always returns a vmi (with empty fields in case of error).
Let's store the retrieved vmi in a separate variable.
Failure example: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11685/pull-kubevirt-e2e-k8s-1.28-sig-storage/1781258067900370945
Fixes #
The following tradeoffs were …

fix: do not override original vmi during eventually cycle

---

pkg/host-disk/host-disk_test.go
pkg/virt-handler/selinux/labels_test.go
pkg/virt-launcher/virtwrap/manager_test.go

Instead of creating and cleaning a temp directory ourselves, 
use built-in Ginkgo TemptDir which does that already.
Fixes #
```release-note
None
```

unit tests: Use TempDir

---

ADOPTERS.md

After this PR:
Fixes #
```release-note
NONE
```

Add ncr voyix adopters entry

---

cmd/virt-launcher/node-labeller/node-labeller.sh
pkg/virt-handler/node-labeller/cpu_plugin.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/node-labeller/model.go
pkg/virt-handler/node-labeller/node_labeller.go
pkg/virt-handler/node-labeller/node_labeller_test.go
pkg/virt-handler/node-labeller/util/util.go
pkg/virt-launcher/virtwrap/converter/converter.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/11671
Conflicts:
`node-labeller_tests.go` - The tests dropped in the first commit were refactored
`cpu_plugin_tests.go` - The tests dropped in the first commit were refactored
```release-note
NONE
```

[release-1.1] BugFix: Refined CPU Validation per Libvirt Guidelines

---

tests/network/bindingplugin_passt.go

There was no need to pass the expectation result (success or failure) to the helper function. Therefore the implementation was changed to use `RunCommand`.
The command details has been abstracted away through a regular function (instead of the lambda).
Fixes #
```release-note
NONE
```

tests, net: Simplify console command execution to check connection

---

pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go

Network interfaces unit test was using a single function that gets one of three possible inputs. Those inputs require different implementation in most of the function, so the function had many conditions, for every possible input. This is not readable and maintainable.
After this PR:
Instead, separate to 3 tests, and use `beforeEach()` for the common code.
/cc @EdDev
```release-note
None
```

Seprate network interfaces unit test

---

automation/test.sh

Currently rehearsals are failed because `PULL_BASE_SHA` and `PULL_PULL_SHA` 
aren't set correctly when rehearsing.
Simply skip the checking for rehearsal jobs will fix it, 
because it is basically not needed when rehearsing.
Example of failure
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3388/rehearsal-pull-kubevirt-e2e-k8s-1.30-ipv6-sig-network/1785687216379400192
Tested here
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3388/rehearsal-pull-kubevirt-e2e-k8s-1.30-ipv6-sig-network/1786029488383987712
Fixes # …

tests: Fix changes detection to support rehearsals

---

pkg/virt-controller/watch/vm.go

1. Remove not used functions
2. Unify v1 and metav1 imports
3. Remove redundant args
Fixes #
```release-note
NONE
```

Clean vm.go

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go

In vmi-create-admitter.go there are a lot places where we could return early and avoid unnecessary nesting.
After this PR:
Simplify the code nesting
```release-note
NONE
```

refactor: simplification and clean-up of vmi-create-admitter.go

---

pkg/virt-controller/watch/BUILD.bazel
pkg/virt-controller/watch/vm_test.go

Backport of https://github.com/kubevirt/kubevirt/pull/11783
Fixes #
```release-note
NONE
```
/hold 
Based on https://github.com/kubevirt/kubevirt/pull/11884

[release-1.2] VM controller - move unit tests to fake client (VirtualMachineInstanceInterface) 

---

cmd/sidecars/sidecar_shim.go

The hook executable is currently without a way to logging.  We wrap stderr into sidecar-shim logging component.
Example output of a python script logging $msg to stderr with this patch:
```json
{
"component":"shim-sidecar","hook":"onDefineDomain","level":"info",
"msg":"qemu-args: Found 1 env vars and 2 args in libvirt.vm.kubevirt.io/qemuArgs",
"pos":"sidecar_shim.go:236","timestamp":"2024-05-14T14:05:10.832686Z"
}
```
`sidecar-shim` could log but the hook it called could not.
After this PR:
the hook called by `sidecar-shim` can log and will do so using `sidecar-shim`'s component
Fixes #
Rework of https://github.com/kubevirt/kubevirt/pull/11818 …

sidecar-shim: include hook's stderr logs

---

OWNERS_ALIASES

After this PR:
Fixes #
```release-note
NONE
```

Add ShellyKa13 to sig-storage reviewers

---

pkg/virt-config/virt-config.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-controller/watch/pool.go
pkg/virt-controller/watch/topology/nodetopologyupdater_test.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/vm.go
pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/device/hostdevice/generic/addresspool.go
pkg/virt-launcher/virtwrap/device/hostdevice/gpu/addresspool.go
tests/framework/checks/checks.go
tests/hyperv_test.go
tests/libmigration/migration.go
tests/windows_test.go

Simplify range expression.
Remove useless codes.
```release-note
NONE
```

Simplify range expression

---

docs/backup-restore-integration.md

This doc describes how a backup partner can assess its compatibility with Kubevirt, either automatically or manually.
Fixes #
This doc refers to some stuff that is currently in a PR: https://github.com/kubevirt/kubevirt-velero-plugin/pull/247
hold until that gets merged.
**Checklist**
```release-note
None
```

Document backup partner maturity validation

---

pkg/virt-controller/watch/migration.go

VirtualMachineInstanceMigration events:
```
Events:
Type     Reason                           Age                  From                       Message
----     ------                           ----                 ----                       -------
Normal   SuccessfulCreate                 34m                  virtualmachine-controller  Created migration target pod virt-launcher-i-be12131d9a184d72830f-h6tpd
Normal   SuccessfulDelete                 29m                  virtualmachine-controller  unschedulable pod timeout period exceeded%!(EXTRA string=virt-launcher-i-be12131d9a184d72830f-h6tpd)
```
After this PR:
```
Events:
Type     Reason                           Age                  From                       Message
----     ------                           ---- …
```

controller: Fix event message recorded by migration

---

pkg/virt-controller/watch/migration.go

Hardcoded operation in migration.go
Replaced all the patch operations with the patch package
Fixes #
Partially fix: https://github.com/kubevirt/kubevirt/issues/11654
```release-note
NONE
```

migration controller: replace hardcoded patch operations

---

pkg/storage/export/export/vmsnapshot-source.go
pkg/storage/snapshot/restore.go
pkg/storage/snapshot/restore_test.go

This is a manual cherry-pick of PR: https://github.com/kubevirt/kubevirt/pull/11996
```release-note
BugFix: Fix restore panic in case of volumesnapshot missing
```

[release-1.2][BUGFIX] Fix restore panic in case of volumesnapshot missing

---

tests/network/hotplug_bridge.go

The hotplug of bridge binding network interface has been covering a
scenario in which after a successful hotplug, the VM is restarted and
the interfaces are re-examined for existence.
This change drops the 2 tests that cover the described scenario.
It is trivial that once the VM spec has been modified, restarting or
starting (post stopping) a VM is identical to the scenario that does not
involve hotplug at all. I.e. it does not matter why the VM spec changed,
the new created VMI spec is going to be based on the VM spec.
Fixes #
Depends on #12018 , please review only the last commit in this PR.
This checklist is not enforcing, but it's a reminder of items that …

tests, net, hotplug: Drop reset-after-hotplug test

---

OWNERS_ALIASES

Nominate João Vilaça (@machadovilaca) as sig/observability approver. 
Since joined the project, João has been a [key contributor](https://github.com/kubevirt/kubevirt/graphs/contributors?from=2021-12-28&to=2024-06-08&type=c) to Kubevirt, especially in the observability area. He has over 60 [merged PRs](https://github.com/kubevirt/kubevirt/pulls?q=is%3Aclosed+is%3Apr+author%3Amachadovilaca+is%3Amerged+) and more than 30 [reviews](https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+commenter%3Amachadovilaca+-author%3Amachadovilaca).
/cc @enp0s3 @sradco
```release-note
None
```

Nominate machadovilaca as sig/observability approver

---

tests/clone_test.go

clone_test.go: Remove use of RunVMAndExpectLaunchWithRunStrategy func
RunVMAndExpectLaunchWithRunStrategy should be deprecated as it is part
of tests_utils.go and use expensive get and update API calls
Instead of Updating VM runStrategy in clone_test.go create vm with
with the desired runStrategy.
After this PR:
Fixes #
```release-note
NONE
```

clone_test.go: Remove use of RunVMAndExpectLaunchWithRunStrategy func

---

pkg/storage/backend-storage/backend-storage_test.go
pkg/testutils/mock_config.go
pkg/util/tls/tls_test.go
pkg/virt-api/rest/profiler_test.go
pkg/virt-api/rest/subresource_test.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmexport-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter_test.go
pkg/virt-config/configuration.go
pkg/virt-config/configuration_test.go
pkg/virt-controller/services/template_test.go
pkg/virt-controller/services/virtiofs_test.go
pkg/virt-controller/watch/vm_test.go
pkg/virt-controller/watch/vmi_test.go
pkg/virt-handler/device-manager/mediated_device_test.go
pkg/virt-handler/device-manager/mediated_devices_types_test.go
pkg/virt-handler/device-manager/pci_device_test.go

Simplifies used interface to bare required minimum. 
Fixes #
```release-note
NONE
```

Virt-config simplify

---

pkg/virt-controller/watch/vm.go

Hardcoded operation in vm.go
After this PR:
Replaced all the patch operation with the patch packge
Fixes #
Partially fix: https://github.com/kubevirt/kubevirt/issues/11654
```release-note
NONE
```

vm: replace hardcoded patch operations

---

pkg/virt-handler/node-labeller/node_labeller.go

Hardcoded operation in virt-handler package.
Replaced all(only 1) the patch operations with the `patch.PatchSet` in the virt-handler package.
Fixes #
Partially address: https://github.com/kubevirt/kubevirt/issues/11654
```release-note
NONE
```
/cc @alicefr @0xFelix

virt-handler: Use patchset for patch operations

---

manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-operator/resource/generate/rbac/operator.go
pkg/virt-operator/resource/generate/rbac/operator_test.go

This is a manual cherry-pick of #12089 
```release-note
Less privileged virt-operator ClusterRole
```

[release-1.0] Collect component Role rules under operator Role instead of ClusterRole

---

pkg/virt-controller/watch/pool.go
pkg/virt-controller/watch/vmi.go

Hardcoded operation in vmi controller and pool controller.
Replaced all the patch operations with the `patch.PatchSet` in the vmi and pool controller
Fixes #
Partially address: https://github.com/kubevirt/kubevirt/issues/11654
```release-note
NONE
```

vmi and pool controller: Use patchset for patch operations

---

tests/vmi_configuration_test.go

These tests we're being skipped for a while since sig-compute doesn't
have block volume support.
Fixes #
```release-note
NONE
```

tests: unskip some storage-related tests by moving them to sig-storage

---

pkg/virt-handler/cache/cache_test.go

verifyObj needs to check cache in Eventually
in order to be usable after first sync.
The HasSynced does check only for the first
sync and later sync doesn't affect the return
value of HasSynced.
Fixes #
See https://search.ci.kubevirt.io/?search=should+watch+for+domain+events.&maxAge=336h&context=7&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
```release-note
NONE
```

Fix flaky cache unit test

---

tests/BUILD.bazel
tests/usbredir_test.go

USB is not supported on s390x.
Building s390x fails, as it wants to pull in code that is unsupported on s390x
After this PR:
Building s390x works
Fixes #
```release-note
NONE
```

tests/usbredir: Disable test for s390x

---

OWNERS

sig-buildsystem was added as reviewer and approver for changes to `BUILD.bazel` files.
After this PR:
sig-buildsystem is no longer added as reviewer and approver for changes to `BUILD.bazel` files.
Fixes #
Changes to BUILD.bazel files should be owned by approvers from the appropriate sig, since sig-buildsystem is not able to tell in all cases whether changes are applicable and valid.
/cc @brianmcarey @xpivarc 
```release-note
```

sig-buildsystem: remove ownership for BUILD.bazel changes

---

pkg/virt-controller/watch/vm.go
pkg/virt-controller/watch/vm_test.go
tests/hotplug/memory.go

This is a manual cherry-pick of #12153
/assign acardace
```release-note
NONE
```

[release-1.3] mem-hotplug: fix flaky test and small issues

---

tests/network/hotplug_bridge.go

The scenario of marking a network interface to be unplugged (set to
`absent` state) can be considered redundant because it is not a
hotunplug (the VM is not running, i.e. no VMI) scenario.
Dropping this test from the e2e tests and moving it to a unit test seems
more appropriate.
Fixes #
Depends on #12018 , please review only the last commit in this PR context.
```release-note
NONE
```

tests, net, hotplug: Drop stopped VM test

---

cmd/sidecars/README.md
examples/vm-cirros-with-sidecar-hook-configmap.yaml
examples/vmi-with-sidecar-hook-configmap.yaml
tools/vms-generator/utils/utils.go
tools/vms-generator/vms-generator.go

Over the time a few enhancements got implemented
for the sidecar-shim feature.
Amend its README.md for consistency.
Add a generated example of a VM
with hook sidecar ConfigMap.
PR #10637 and #11272 introduced a few changes that are still not fully reflected
in cmd/sidecars/README.md , updating it for consistency.
```release-note
NONE
```

Enhance sidecar-shim README

---

tests/network/expose.go

Have createAndWaitForJobToSucceed accept a plain Job instead a jobFactory. Passing function references adds cognitive load.
```release-note
NONE
```

tests/network/expose.go: simplify helper function

---

tests/storage/restore.go

RunVMAndExpectLaunchWithRunStrategy should be deprecated as it is part of tests/utils.go and use expensive get and update API calls
Instead of Updating VM runStrategy in restore.go create vm with with the desired runStrategy.
After this PR:
Fixes #
```release-note
NONE
```

restore.go: Remove use of RunVMAndExpectLaunchWithRunStrategy func

---

pkg/storage/export/virt-exportserver/exportserver.go
pkg/storage/export/virt-exportserver/exportserver_test.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/12283
This PR addresses a flake in the unit tests introduced in https://github.com/kubevirt/kubevirt/pull/11911.
```release-note
NONE
```

[release-1.2] Mock permission checking in export server to avoid issues during testing

---

WORKSPACE
containerimages/BUILD.bazel

There is no s390x support for fedora-test-tooling in kubevirt.
After this PR:
Thie pr adds the s390x support for fedora-test-tooling in kubevirt.
Fixes #
This pr https://github.com/kubevirt/kubevirtci/pull/1207 added the s390x support to fedora-test-tooling image in kubevirtci and the image got published to quay.io. In this Iam updating the image hash to latest which has the s390x support and also updated the BUILD.bazel with necessary changes to support s390x.
```release-note
None
```

add fedora-test-tooling image support for s390x.

---

pkg/storage/export/virt-exportserver/exportserver.go
pkg/storage/export/virt-exportserver/exportserver_test.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/12283
This PR addresses a flake in the unit tests introduced in https://github.com/kubevirt/kubevirt/pull/11911.
```release-note
NONE
```

[release-1.1] Mock permission checking in export server to avoid issues during testing

---

pkg/storage/export/virt-exportserver/exportserver.go
pkg/storage/export/virt-exportserver/exportserver_test.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/12283
This PR addresses a flake in the unit tests introduced in https://github.com/kubevirt/kubevirt/pull/11911.
```release-note
NONE
```

[release-1.0] Mock permission checking in export server to avoid issues during testing

---

tests/storage/hotplug.go

There is no need to call Update in these tests
to modify the CDI object, as this update modifies
a single field.
It's better to use Patch instead of Update
since it's more likely to succeed.
After this PR:
Fixes #
```release-note
NONE
```

tests/storage/hotplug.go :Replace the update API call with a patch

---

tests/monitoring/vm_monitoring.go

`kubevirt_vmi_last_api_connection_timestamp_seconds` e2e test seems to be flaky because the first connection to the VMI doesn't always disconnect completely before trying to connect again. 
After this PR:
As a workaround, to ensure two connections are being made, after the first connection we delete the VMI and then create the same VMI and connect again.
```release-note
None
```

Fix flaky connection metric test

---

tests/vm_test.go

Replace RetryWithMetadataIfModified() with Patch
to set VM run strategy instead of using Update.
```release-note
None
```

tests: replace retry with patch

---

tests/libreplicaset/BUILD.bazel
tests/libreplicaset/replicaset.go
tests/utils.go
tests/vm_test.go

Remove RetryIfModified from utils, to keep utils shorter and also remove the dependency of retryWithMetadataIfModified from this function.
```release-note
None
```

tests: remove RetryIfModified function

---

tests/reporter/kubernetes.go

- Remove duplicate VM snapshot function
- Skip all volume snapshot log collections when volume snapshots are not available
- Remove unused function parameters
- Add print functions to avoid duplication of writers and '\n's, and unhandled error warnings
- Improve some messages
Fixes #
```release-note
NONE
```

test reporter: code cleanup

---

WORKSPACE

There is some issue with the s390x alpine iso starting from the version v3.9.x. So as a result of this the end to end tests that create alpine virtual machines are crashing for s390x. We have raised the issue in the alpine community for a fix. https://gitlab.alpinelinux.org/alpine/aports/-/issues/16310 . 
After this PR:
I have downgraded the alpine version to v3.18 until we get the fix. Now the tests with the alpine container disks are working successfully.
Fixes #
```release-note
None
```

fix s390x alpine containerdisk.

---

pkg/virt-controller/watch/node_test.go

Switch using fakeClient since the latter better simulate real
behavior, lowering the bar for unit tests, eliminating false positives.
Also, the fake is standard for testing.
```release-note
NONE
```

node controller: Use fakeclient 

---

tests/monitoring/monitoring.go

Switched from Update to Patch to avoid overwriting resource fields
unintentionally. Patch allows precise updates to specific fields,
reducing the risk of accidental changes and improving test reliability.
The test using update
After this PR:
The test using patch
jira-ticket: https://issues.redhat.com/browse/CNV-44576
```release-note 
none
```

tests/monitoring/monitoring: Replace update with Patch

---

pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/converter_test.go

the issue was that the cpuCount variable was holding the total amount of CPUs instead of holding the amount of current active CPUs. Therefore the calculation of block queues could be incorrect in cases where CPU hotplug is configured.
Added unit test to cover the case when CPU hotplug is configured on the VMI, and the # of total CPU can be different than the # of active CPUs.
Wrong calculation of the number of VirtIO block queues with CPU hotplug topology
After this PR:
correct calculation of the number of VirtIO block queues with CPU hotplug topology
Fixes #
https://issues.redhat.com/browse/CNV-44102
https://issues.redhat.com/browse/CNV-44103
Any attempt to refactor a piece of code the converter ended up with big changes. So …

[bugfix] Fix VCPU count in virt-launcher converter

---

pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/12451
```release-note
Fix: eviction requests to completed virt-launcher pods cannot trigger a live migration
```

[release-1.2] Admit eviction on completed virt-launcher pods

---

pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
pkg/virt-controller/watch/drain/evacuation/evacuation.go

There is no need to hold informers, narrowing down
the interface can decrease the probability of making
a mistake. It also simplifies the controller and unit
tests.
```release-note
NONE
```

Drain controllers: narrow down interfaces

---

tests/storage/snapshot.go

RunVMAndExpectLaunchWithRunStrategy should be deprecated as it is part of tests_utils.go and use expensive get and update API calls
Instead of Updating VM runStrategy in snapshot.go create vm with with the desired runStrategy.
After this PR:
Fixes #
```release-note
NONE
```

[Tests]snapshot.go: Remove use of RunVMAndExpectLaunchWithRunStrategy func

---

pkg/virtctl/vm/expand.go
pkg/virtctl/vm/expand_test.go

- The virtctl expand command did not support reading from standard input (-).
- Running `./cluster-up/virtctl.sh expand --file -` would result in an error: error reading file open -: no such file or directory.
After this PR:
- The virtctl expand command supports reading from standard input.
- Users can now use the - option to specify standard input for the --file flag.
Fixes #12376
- Supporting standard input for --file flag aligns with common usage patterns in command-line tools, making the tool more flexible and user-friendly.
- Keeping the existing behavior without support for standard input. This was deemed less user-friendly and not aligned with common practices.
Links to places where the …

Enhance expand command to support reading from stdin and improve code quality

---

tests/vm_test.go

Replacing `Update()` directives in tests/vm_test.go with `Patch()` in order to avoid conflicts on objects and reduce flakiness.
`.Update()` is being used to update VM objects.
After this PR:
`.Patch()` is being used to update VM objects according to the test cases.
Fixes #
Jira-issue: https://issues.redhat.com/browse/CNV-44590
```release-note
tests/vm_tests.go: replace Update() with Patch()
```

[code-quality] tests/vm_test.go: Replace `Update()` with `Patch()`

---

pkg/virtctl/adm/logverbosity/logverbosity.go
pkg/virtctl/credentials/addkey/addkey.go
pkg/virtctl/credentials/common/BUILD.bazel
pkg/virtctl/credentials/common/common.go
pkg/virtctl/credentials/password/BUILD.bazel
pkg/virtctl/credentials/password/password.go

Use PatchOperation for creating the patch 
After this PR:
Refactor and use the patchset to uniform the patch operations in the code
```release-note
NONE
```

credentials: use patchset for the patch operations

---

docs/container-register-disks.md

the docs is inaccuracy when creating containerDisk, and the containerDisk is not working
After this PR:
the containerDisk is now working
Fixes #
```release-note
NONE
```

docs: create containerDisk should chown

---

pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
tests/network/sriov.go

Following #12691, this PR mitigates SR-IOV lane breakage by temporarily set e2e tests ignore the mentioned warning.
In follow up PR we will introduce sustainable solution to enable having good indication in case of a real problem.
When network-info mount is not ready on time, syncVMI rutine would raise the following error:
In a scenario virt-launcher pod network-info mount is not populated on time, syncVMI routine raises an error with no context making it impossible to trace when debugging:
```
{ Failure tests/network/sriov.go:257
Unexpected Warning event received: testvmi-p4f9s,e84120d3-398c-480f-a1bf-68a0abf6cb19: server error. command SyncVMI failed: "timed out waiting for the condition"
Expected
<string>: Warning
not to equal
<string>: Warning …
```

e2e, SR-IOV: Ignore warnings due downward API mount not ready on time

---

tests/operator/operator.go

This PR enhances the efficiency and reliability of the `tests/operator/operator.go` test_id 4744 by replacing the `Update` operation with the `Patch` operation.
```release-note
NONE
```

tests/operator/operator: Replace Update with Patch test_id 4744

---

tests/hotplug/cpu.go

This test exercise a path where a topology is not provided instead we use the requests. This covers a regression found in 1.2 release.
Fixes #
```release-note
NONE
```

Cpu hotplug: Introduce test for default topology

---

tests/hotplug/BUILD.bazel
tests/hotplug/cpu.go

Manual backport https://github.com/kubevirt/kubevirt/pull/12309/
Fixes #
```release-note
NONE
```

[release-1.2] Fix flaky cpu hotplug tests

---

cmd/virt-handler/virt-handler.go
pkg/virt-handler/cache/BUILD.bazel
pkg/virt-handler/cache/cache.go
pkg/virt-handler/cache/cache_test.go
pkg/virt-handler/cache/domain-watcher.go

Fixes #
```release-note
NONE
```

Refactor: Isolate domain watcher

---

tests/hotplug/BUILD.bazel
tests/hotplug/memory.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/12298#
Fixes #
```release-note
NONE
```

[release-1.2] Fix flaky mem hotplug

---

.golangci.yml
tests/framework/checks/skips.go

Deprecate Skips, it should be handled by labels. This helps us and users of our suite to fight shadow skips.
Fixes #
```release-note
NONE
```

Deprecate Skips, it should be handled by labels

---

pkg/virtctl/imageupload/imageupload.go

Set default labels directly to the object metadata instead of using labels.
```release-note
None
```

refactor(virtctl/imageupload): set labels using object metadata

---

tests/vm_test.go

Use the KubeVirt client instead of using virtctl through a NewRepeatableVirtctlCommand where applicable in tests/vm_test.go.
Internally virtctl uses the same client call, so using virtctl does not provide any additional value.
There are more test cases in this file using virtctl which are not changed in this commit because they need to be moved to subresource_api_test.go or should be dropped entirely.
The correctness of API calls made by virtctl start / stop/ restart is already covered in
unit tests specified in `pkg/virtctl/vm/{start,stop,restart}_test.go`.
NewRepeatableVirtctlCommand is …

cleanup(tests,vm_test): Use client instead of virtctl

---

OWNERS_ALIASES

Proposing Felix as an approver for kubevirt tests.
Felix has been a long time contributor to the KubeVirt project. He also has done multiple [reviews](https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+is%3Aclosed+commenter%3A0xFelix+test+label%3Aapproved+) and [contributions](https://github.com/kubevirt/kubevirt/pulls?page=4&q=is%3Apr+is%3Aclosed+author%3A0xFelix+test+label%3Aapproved) to tests.
Overall, Felix is interested in improving tests and is actively working on it.
```release-note
NONE
```

sig-tests: Add 0xFelix as approver

---

tests/usbredir_test.go

Fixes https://github.com/kubevirt/kubevirt/pull/12640#issuecomment-2343226644
Fixes #12787
```release-note
NONE
```

usbredir test: Add GinkgoRecover for goroutines

---

pkg/virtctl/BUILD.bazel
pkg/virtctl/root.go
pkg/virtctl/unpause/BUILD.bazel
pkg/virtctl/unpause/unpause.go
pkg/virtctl/unpause/unpause_suite_test.go
pkg/virtctl/unpause/unpause_test.go

Split commands to files.
Each file is responsible for one command only, ease readability and 
reduces collision domain.
Fixes #
```release-note
None
```

virtctl, pause: Refactor commands

---

pkg/virtctl/create/vm/vm.go
pkg/virtctl/create/vm/vm_test.go

This change enables the inference from registry or snapshot sources when creating a VM with virtctl create vm and the --volume-import flag.
Inference is possible only from PVC sources.
After this PR:
Inference is possible from PVC, Registry and Snapshot sources.
Fixes #12784 
```release-note
virtctl: Created VMs can infer an instancetype or preference from PVC, Registry and Snapshot sources now.
```

feat(virtctl): Allow inference from registry or snapshot volume imports

---

WORKSPACE

The old fedora-test-tooling image is having netcat command not found issue for s390x, this issue is fixed and rebuit the fedora-test-tooling image to reflect the changes. This is the pr that has updated the fedora-test-tooling image
https://github.com/kubevirt/kubevirtci/pull/1268
After this PR:
This pr updates the fedora-test-tooling image with latest hash.
Fixes #
``` 
NONE
```

Update fedora-with-test-tooling image to the latest.

---

tests/vm_test.go

Changes:
1. Kill virt-laucher process instead of creating VMI with a
mismatched disk
Currently these tests Create a Kernel Boot VMI with
a mismatched disk when doing so the controller keeps
trying to mount the bogus kernel location which making
these test flacky as the test expect the VMI to fail.
2. Create a running VM instead of using expensive
API calls through virtctl
3. Check existence of launcher pod directly once the VMI
Fail instead of adding unnecessary complex conditions.
Currently, the launcher verification uses Eventually and
Consistently scopes for objects that never change.
Fixes #
This checklist is not enforcing, but it's a reminder of items that …

[Tests]Stop the quarantine of [test_id:7164] and [test_id:6993]

---

tests/compute/credentials.go

credential test file has a lot of duplicated code. 
The tests can be merged together with describe table.
```release-note
NONE
```

credential test: Refactor

---

docs/conformance.md

In order to promote usage of Conformance tests but also the extension of it, we define some goals and requirements.
Fixes #
```release-note
NONE
```

Elaborate on definition for Conformance tests

---

tests/hotplug/cpu.go

Manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/12583
Fixes #
```release-note
NONE
```

[release-1.3] Cpu hotplug: Introduce test for default topology

---

tests/network/vmi_networking.go

A vmi with a custom MAC is created for the Multiple VM Connectivity test Therefore complete the custom MAC assertion within the scope of that test and remove the standalone Custom MAC test
A specific test would launch a redundant VM to assert that its MAC address was identical to a custom MAC address requested by the user. That would waste time and resources in e2e tests execusion 
After this PR:
Functionality is asserted within the scope of another test that launches a VM with a custom MAC address anyway
Fixes #
Note that the test that was removed used a `Masquerade` network while the replacement test uses `Bridge` network.
This should not make …

e2e tests cleanup: remove custom MAC test

---

OWNERS_ALIASES

Nominating @fossedihelm for SIG compute approver
Federico has been contributing to Kubevirt for 3 years, dating first contribution back to https://github.com/kubevirt/kubevirt/pull/6681 5.11.2021
He contributed  200+ PRs https://github.com/kubevirt/kubevirt/pulls?q=is%3Amerged+is%3Apr+author%3Afossedihelm+ raging from big features(KSM, free pages reporting, Improved IO errors handling, generated clients) to small iterative improvements of the code base, bug fixes (such as memory leaks in our c-bindings) or tests improvements(Fake client, speedups of unit tests, conformance tests).
He reviewed almost 600 PRs https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+commenter%3Afossedihelm+is%3Aclosed+-author%3Afossedihelm+ . Most notably PRs around hotplug, volume migration, rollout, console …

Nominate fossedihelm for sig-compute approver

---

pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/container_disk_test.go
tests/container_disk_test.go

Fixes #
**Checklist**
```release-note
NONE
```

Tests:  Remove redundant container disk tests

---

pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/rendercontainer.go
pkg/virt-controller/services/serialconsolelog.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-controller/services/virtiofs.go
pkg/virt-controller/watch/clone/BUILD.bazel
pkg/virt-controller/watch/clone/clone.go
pkg/virt-controller/watch/clone/util.go
pkg/virt-controller/watch/pool/BUILD.bazel
pkg/virt-controller/watch/pool/pool.go
pkg/virt-controller/watch/topology/BUILD.bazel
pkg/virt-controller/watch/topology/hinter.go
pkg/virt-controller/watch/topology/hinter_test.go
pkg/virt-controller/watch/topology/tsc_test.go

Replaced the deprecated package `k8s.io/utils/pointer` with kubevirt package `kubevirt.io/kubevirt/pkg/pointer` in the `/pkg/virt-controller` directory.
- In the `/pkg/virt-controller` we used `k8s.io/utils/pointer` package which is deprecated. 
After this PR:
Ref #12949
```release-note
None
```

Replaced the deprecated package `k8s.io/utils/pointer` with kubevirt package in  `/pkg/virt-controller` directory.

---

pkg/storage/backend-storage/backend-storage.go

backend-storage defaults to using the default storage class for the cluster
After this PR:
backend-storage defaults to using the default storage class for virtualization workloads, then falls back to the cluster default
Fixes #
```release-note
NONE
```

backend-storage: support (and prefer) the default storage class for virtualization

---

pkg/virt-handler/vm.go
pkg/virt-launcher/virtwrap/live-migration-source.go
pkg/virt-launcher/virtwrap/live-migration-target.go
staging/src/kubevirt.io/api/core/v1/types.go
tests/storage/migration.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/12818.
Fixes https://github.com/kubevirt/kubevirt/issues/12811
```release-note
NONE
```

[release-1.3] volume-migration: fix migration from source RWX volumes

---

OWNERS_ALIASES

/sig compute
While I'm already a root reviewer I'd like to help specifically with the sig-compute review backlog where possible.
Fixes #
```release-note
NONE
```

OWNERS: Add lyarwood as sig-compute-reviewer

---

OWNERS_ALIASES

Nominating @0xFelix for SIG compute approver
Felix has been contributing to Kubevirt for more than 2 years, he is a very active member of the community contributing both with code and reviews. 
He contributed  100+ PRs https://github.com/kubevirt/kubevirt/pulls?q=is%3Amerged+is%3Apr+author%3A0xFelix, his main contributions were in core KubeVirt, instance types and virtctl, he also helped the project making big strides in having more reliable and maintainable tests.
He reviewed ~ 350 PRs https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+commenter%3A0xFelix+is%3Aclosed+-author%3A0xFelix.
I think @0xFelix deserves to be a sig-compute approvers given the number and the importance of his contributions, also this will help the project grow as Felix does a great job in reviewing a lot of PRs …

Nominate 0xFelix for sig-compute approver

---

tests/operator/operator.go

It is common practice on our e2e tests to use Update k8s API in order to run the test. In order to ensure the change was executed, these also are wrapped with Eventually/RetryOnConflict.
The issue is that most often tests do not really need to use Update (for an atomic change) and Patch would be quicker and more precises.
This PR is replacing an unneeded use of update in favor of patch, in test_id:3145.
Fixes #
```release-note
NONE
```

tests/operator, test_id:3145: Replace Update with Patch

---

pkg/storage/snapshot/restore.go
pkg/storage/snapshot/restore_test.go

manual cherry pick of: https://github.com/kubevirt/kubevirt/pull/12861
```release-note
bugfix: fix possible miss update of datavolumename on vmrestore restores
```

[release 1.1] VMRestore: fix possible miss update of dvname on vmrestore restores - fixes quarantine tests

---

tests/container_disk_test.go
tests/pool_test.go

This PR aims to identify and label the tests in the pool_test and containerdisk files.
```release-note
NONE
```

Conformance tests for pool_test and containerdisk

---

pkg/storage/snapshot/restore.go
pkg/storage/snapshot/restore_test.go

manual cherry pick of: https://github.com/kubevirt/kubevirt/pull/12861
Fixes #
```release-note
bugfix: fix possible miss update of datavolumename on vmrestore restores
```

[release 1.2] VMRestore: fix possible miss update of dvname on vmrestore restores - fixes quarantine tests

---

tests/vm_test.go

Following discussion at https://github.com/kubevirt/kubevirt/pull/13015/files#r1789759957
Remove tests following tests because they verify basic k8s functionality, not related to Kubevirt:
- "[test_id:232]should create same manifest twice via command line" Any k8s type or CRD type instance can be created multiple times
- "[test_id:233][posneg:negative]should fail when deleting nonexistent VM" Any non existing type instance deletion should fail with not-exist error from k8s API server.
- "[test_id:243][posneg:negative]should create VM only once" Any type instance that create twice should fail with an 'already-exist' error by k8s API server.
- Tests under Context "as ordinary OCP user trough test service account" These tests verifies some 'oc' functionality, which is not an artifact by this …

tests, vm_test: Remove tests that verifies basic k8s functionality

---

pkg/virt-launcher/virtwrap/live-migration-source.go
pkg/virt-launcher/virtwrap/manager_test.go
tests/storage/migration.go

Manual backport of #12851
```release-note
NONE
```

[release-1.3] volume-migration: append disk image for block replacement

---

pkg/virt-api/rest/subresource_test.go
pkg/virt-launcher/virtwrap/converter/BUILD.bazel
pkg/virt-launcher/virtwrap/converter/converter_test.go
tests/BUILD.bazel
tests/virt-handler_test.go
tests/vmi_headless_test.go

1. Removes tests that don't bring value
2. Converts e2e tests to unit tests
3. Make sure that only relevant tests are in the vmi_headless_test.go
Fixes #
```release-note
NONE
```

Revisit headless tests

---

tests/vmi_cloudinit_test.go

instead of obtaining the MAC and PCI addresses, that were dynamically allocated by libvirt, from the domain XML, set everything explicitly. Then we know exacly what to expect to find inside the VM. The test still asserts what it's meant to assert: that the cloudinit metadata file in the VM includes the correct tag and interface details
GetRunningVirtualMachineInstanceDomainXML was used in the test only in order to find out which MAC and PCI addresses were dynamically assigned, in order to validate that the cloud-init metadata file in the VM was correct
After this PR:
There no need to check the Domain XML because addresses are explicitly set  
Fixes #
Links to places where the discussion took …

tests/utils cleanup: remove GetRunningVirtualMachineInstanceDomainXML from vmi_cloud_init_test

---

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go

This is a manual cherry-pick of : https://github.com/kubevirt/kubevirt/pull/12933
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-48245
```release-note
VM admitter: improve validation of vm spec datavolumetemplate
```

 [release-1.3] VM admitter: improve validation of datavolumetemplate 

---

pkg/virtctl/OWNERS

/cc @0xFelix 
/cc @oshoval 
$subject, also drop the `sig/cluster` label as this doesn't map to an actual SIG.
Fixes #
```release-note
NONE
```

virtctl, OWNERS: Add lyarwood as reviewer

---

tests/portforward_test.go

This PR aims to identify and label the tests in the portforward_test file.
```release-note
NONE
```

Conformance tests for portforward_test

---

tests/libinfra/BUILD.bazel
tests/libinfra/leader.go

The user of this function has been removed in
commit 130f806e4281e806086e0998821c44ef5396fb18
/kind cleanup
```release-note
NONE
```

tests/libinfra: drop unused function GetNewLeaderPod

---

pkg/storage/export/export/export.go
pkg/storage/export/export/export_test.go

If there are no volumes to export, and the tokenSecretRef was not set, the VMExport controller would try to create a secret endlessly. It would succeed the first time, and each subsequent time it would fail because the secret already exists.
This was causing noise in the API server about creating a secret that already exists. 
After this PR:
Before attempting to create the token secret, check if there are volumes to export, if not, there is no reason to create the secret. This stops the excess creation of secrets and subsequent spamming of the API server.
Fixes https://issues.redhat.com/browse/CNV-49427 …

Only create VMExport token secret if there are volumes to export

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
tests/vmi_sound_test.go

Revisit sound tests. Remove tests that don't bring value.
Fixes #
```release-note
NONE
```

Revisit sound test

---

pkg/network/vmispec/interface_test.go
pkg/virt-config/configuration.go
pkg/virt-controller/watch/clone/util.go
tests/monitoring/component_monitoring.go
tests/performance/realtime.go

5 functions have been found that nothing is calling them, so we can safely remove them from the code base.
/kind cleanup
After this PR:
Fixes #
```release-note
NONE
```

Code Cleanup: Remove unused functions

---

pkg/virt-controller/watch/vm/vm.go
pkg/virt-controller/watch/vm/vm_test.go
pkg/virt-controller/watch/vmi/vmi.go

Corruption is bad, cache being corrupted is also bad, This PR fixes it ;)
Fixes #
```release-note
NONE
```

Fix corruption 

---

tests/compute/credentials.go

Cover SSH pub key propagation through
multiple propagation methods and password
propagation via GA.
Also don't make assert in helper and rather
return the error to be asserted at caller.
Fixes #
```release-note
NONE
```

Conformance: Cover credentials tests

---

pkg/virt-controller/watch/clone/OWNERS
pkg/virt-controller/watch/descheduler/OWNERS
pkg/virt-controller/watch/drain/disruptionbudget/OWNERS
pkg/virt-controller/watch/drain/evacuation/OWNERS
pkg/virt-controller/watch/migration/OWNERS
pkg/virt-controller/watch/node/OWNERS
pkg/virt-controller/watch/pool/OWNERS
pkg/virt-controller/watch/replicaset/OWNERS
pkg/virt-controller/watch/testing/OWNERS
pkg/virt-controller/watch/topology/OWNERS
pkg/virt-controller/watch/vm/OWNERS
pkg/virt-controller/watch/vmi/OWNERS
pkg/virt-controller/watch/vsock/OWNERS
pkg/virt-controller/watch/workload-updater/OWNERS

Added OWNERS file for the controllers
```release-note
NONE
```
/cc @xpivarc @acardace @vladikr 
FYI @0xFelix

virt-controller: add OWNERS file

---

tests/security_features_test.go

This PR aims to identify and label the tests in the security_test file.
```release-note
NONE
```

Conformance tests for security_test

---

pkg/network/pod/annotations/generator.go

Return early in case the source pod does not have an ordinal naming scheme.
Fixes #
```release-note
None
```

net, annotations-gen: Refactor GenerateFromSource

---

pkg/network/vmicontroller/status.go
pkg/network/vmicontroller/status_test.go

virt-handler adds interface status entries for guest-internal interfaces, discovered by QEMU guest agent.
They have an empty name and their infoSource is `guest-agent`.
Prior to PR https://github.com/kubevirt/kubevirt/pull/13018, the UpdateStatus function (called by VMI controller) used to work directly on the `vmi.Status.Interfaces` slice.
Thus, it implicitly kept the guest-internal interface statuses.
PR https://github.com/kubevirt/kubevirt/pull/13018 changed the interface statuses calculation to be explicit, and unintentionally dropped the guest-internal interface statuses -
which caused the e2e tests to flake.
Currently, the logic adds / updates interface status entries for all interfaces existing in the VMI spec.
Explicitly preserve interface status entries that do not exist in the …

net, VMI UpdateStatus: Keep guest internal ifaceStatuses

---

tools/perfscale-audit/metric-client/metric-client.go

- VirtControllerCPUUsage collected the avg usage.
- minVirtAPIMemUsageInMB and maxVirtAPIMemUsageInMB these metrics resulted in the single lowest or highest observed memory usage for each container in the given time frame. Due to this the weekly average graph fluctuated significantly, appearing inconsistent and "noisy".
- minVirtControllerMemUsageInMB and maxVirtControllerMemUsageInMB calculate the minimum or maximum usage for each pod and then took the maximum value.
After this PR:
- VirtControllerCPUUsage metric will take into consideration of the leader pod.
- updated minVirtAPIMemUsageInMB and maxVirtAPIMemUsageInMB to return average memory usage for all the containers in the given time frame.By averaging the query smoothens the data.
- minVirtControllerMemUsageInMB …

Update promql query of cpu and memory metrics for sig-performance tests

---

pkg/virt-controller/watch/vm/vm.go
pkg/virt-controller/watch/vm/vm_test.go

Once we have successfully expanded and updated the VirtualMachine we should ensure any instance type or preference ControllerRevisions are removed from the cluster.
Fixes #13117
```release-note
NONE
```

instancetype, virt-controller: Clean up CRs after expand

---

ADOPTERS.md

Hi, we utilize KubeVirt for running and managing virtual machines in our product Alauda Container Platform(ACP). 
We are very happy to be a adopter of KubeVirt, and I'd like to share this information to you.
Thanks

Add Alauda as ADOPTERS

---

tests/operator/operator.go

Currently serial tests rely on the global cleanup. Actually the global cleanup just ensure the kv.spec.config is restored, not the entire spec.
Test id [test_id:3683] changes the uninstallStrategy to `BlockUninstallIfWorkloadsExist` but does not restore the previous setting.
This can lead to failure to the subsequent tests, for example `[test_id:3146]should be able to delete and re-create kubevirt install`, in which uninstall strategy is evaluated.
Failure example: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13139/pull-kubevirt-check-tests-for-flakes/1854890798374457344
/kind flake
Fixes #12730
```release-note
NONE
```

fix: Properly restore kv.spec.uninstallStrategy

---

manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-operator/resource/generate/rbac/controller.go
pkg/virt-operator/resource/generate/rbac/controller_test.go

Totally missed these two in https://github.com/kubevirt/kubevirt/pull/13197/commits/dbc3bf93b892a3e9df02172cdb6a9fe5365320d0 which are crucial in the vmsnap with instancetype/pref and backend state PVC flow.
Fixes #
https://issues.redhat.com/browse/CNV-51225
```release-note
BugFix: VMSnapshot 'InProgress' and Failing for a VM with InstanceType and Preference
```

Re-add finalizer update RBAC for vmsnapshots/vmis

---

pkg/libvmi/BUILD.bazel
pkg/libvmi/devices.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
tests/migration/migration.go
tests/vmi_configuration_test.go

Cover part of configuration tests in conformance testing. See https://github.com/kubevirt/kubevirt/blob/main/docs/conformance.md
Fixes #
```release-note
NONE
```

Conformance configuration tests, part 1

---

tests/network/vmi_networking.go

Currently there are 4 tests that verifies TCP connectivity in following ways:
1. pod to VM on the same node, over nodes network
2.  pod to VM on different node, over nodes network
3. pod to VM on same node (over pod network)
4. pod to VM on different node (over pod-network)
After this PR:
(1) & (2) are dropped, Kubevirt plumbs the network inside the pod, pod-to-network is basic functionality given buy the default cluster network CNI.
Unify (3) & (4) to single test, by running two pods, one on the same node as the VM and another on different node, and perform the connectivity check in the same test.
This PR change tests that perform connectivity check cross nodes to not skip silently but fail loudly, with a informative message.
Fixes #
The …

tests, network: Unify TCP connectivity tests

---

tests/vm_test.go

Remove unused variables.
Check unchecked errors.
Prevent from failing Eventually incase of possible temp issue with client availability.
-->
```release-note
NONE
```

tests/vm_test: code cleanup

---

tests/storage/datavolume.go

This PR aims to fix a nil pointer dereference in a volume expansion test.
```release-note
NONE
```

Tests: Fix nil pointer deref in expansion test

---

OWNERS_ALIASES

It is time that we all get together and acknowledge the fact that @akalenyu is the guy you call when something KubeVirt storage related is broken, and you have no idea why, but you know @akalenyu will figure it out. Usually, he's already on the case and has a handle on it. He is THAT GUY. So let's do the most logical thing ever and make him a sig-storage approver.
His [contributions](https://github.com/kubevirt/kubevirt/pulls?page=1&q=is%3Amerged+is%3Apr+author%3Aakalenyu) and [reviews](https://github.com/kubevirt/kubevirt/pulls?page=1&q=is%3Apr+commenter%3Aakalenyu+is%3Aclosed+-author%3Aakalenyu+sort%3Acreated-desc) are numerous and speak for themself. He really hates bugs and flaky tests with a passion. I don't think anyone has done more to keep the sig-storage lanes humming. Thank you …

Nominate akalenyu sig-storage approver

---

OWNERS_ALIASES

It is my honor to nominate @ShellyKa13 to be a sig-storage approver. She has been an active KubeVirt [contributor](https://github.com/kubevirt/kubevirt/pulls?q=is%3Amerged+is%3Apr+author%3AShellyKa13) for over three years and has authored some pretty major features in the storage arena, including:
- [Online VM Snapshots](https://github.com/kubevirt/kubevirt/pull/5382)
- [VM Snapshot Guest Agent Integration](https://github.com/kubevirt/kubevirt/pull/5942)
- [VM Memory Dump](https://github.com/kubevirt/kubevirt/pull/7517)
Not only has @ShellyKa13 displayed the ability to own a feature from idea to implementation, she has proven to be a thorough and thoughtful [reviewer](https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+commenter%3AShellyKa13+is%3Aclosed+-author%3AShellyKa13). Her …

Nominate ShellyKa13 sig-storage approver

---

pkg/virt-launcher/virtwrap/converter/BUILD.bazel
pkg/virt-launcher/virtwrap/converter/archconverter.go
pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/converter/testdata/domain_s390x.xml.tmpl

converter behavior is strictly related to the arch
and every functionality should be tested for each
architecture.
This PR closes the gap a little bit and performs
a little cleanup.
Related issue: https://github.com/kubevirt/kubevirt/issues/13258
```release-note
NONE
```
/kind cleanup

Improve converter test

---

OWNERS_ALIASES

Unfortunately, I will not be able to dedicate enough time to do regular code reviews in the nearest future due to a change of focus. Therefore, I remove myself from the list to avoid automatic review assignments.
Due to personal reasons, I will not be very active in the community during the following few months. Hence, it is better to avoid creating confusion for other contributors expecting review from me.
Still hope to get back in the future, but for now do not have exact timeline for that.
After this PR:
Fixes # …

OWNERS_ALIAS: Remove myself from code reviewers

---

tests/virtctl/create_vm.go
tests/virtctl/imageupload.go
tests/virtctl/memorydump.go
tests/virtctl/scp.go
tests/virtctl/ssh.go

Add the header to every file in tests/virtctl that is missing it.
After this PR:
Fixes #
```release-note
None
```

cleanup(tests,virtctl): Add missing headers

---

pkg/virt-api/webhooks/arm64.go
tests/network/vmi_networking.go
tests/storage/datavolume.go
tests/storage/export.go

Removes unused functions and variables.
/kind cleanup
```release-note
NONE
```

[cleanup]: remove unused functions and variables

---

pkg/virt-handler/container-disk/mount.go
pkg/virt-handler/container-disk/mount_test.go

The existing `ContainerDisksReady` is only checking if the socket exists. This might be in very rare case not enough. Such case is when the container disk container is created later and the handler performs the check right after the socket was created but before it is able to accept a connection.
Fixes #
The only downside I can think of is hiding some degradation or bug in lower part of the stack. Maybe we could expose a metric to track how long it takes for the container disks to be ready.
```release-note
Bug-fix: Reduced probability of false "failed to detect socket for containerDisk disk0: ... connection refused" warnings
```

Improve container ready check

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

The tests in the "tolerations with eviction policies given" context focused on implementation details rather than expected behavior. They also instantiated VMIs using functions that didn't leverage libvmi, and enabled the `LiveMigration` FG despite being a GA feature.
The tests in the "tolerations with eviction policies given" context have been refactored accordingly:
1. Removes enabling `LiveMigrationGate` as LiveMigration is GA.
2. Tests behavior instead of implementation details by calling `Admit`
instead of `ValidateVirtualMachineInstanceSpec`.
3. Standardizes VMI creation around `libmvi` instead of
`api.NewMinimalVMI`.
4. Updates terminologies (e.g., "migration policies" -> "eviction
strategies").
Partially addresses: …

vmi-create-admitter_test refactor: refactor eviction context tests

---

tests/monitoring/monitoring.go

reasons:
1. Clean Test Logic: The test focuses on what’s being tested, while helper functions handle the details, making it easier to read.
2. Better Error Handling: Functions return errors, keeping the test flexible and separating actions from checks.
Fixes #
```release-note
None
```

tests/monitoring: Remove lambda functions

---

pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/source.go
staging/src/kubevirt.io/client-go/kubecli/handler.go
tests/storage/snapshot.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/13270
```release-note
VMSnapshot: propagate freeze error failure
```

[release-1.4] VMSnapshot: propagate freeze error failure

---

tests/network/sriov.go

End to end tests are intended for high level functionality validation.
`GetRunningVMIDomainSpec` is a function that parses and checks the `DomainXML` details, which is an intermediate tech detail that could be tested in Unit Tests but does not belong in e2e tests.
In addition, GetRunningVMIDomainSpec is implemented in from test.utils, which is a central module external to network-sig.  We strive to decouple network logic and tests from other areas in the code and generally to eliminate test.utils alltogther.
Given the above, this PR removes one use of `GetRunningVMIDomainSpec`, additional removal PRs will follow.
After this PR:
Fixes #
This …

tests, net, sriov: remove use GetRunningVMIDomainSpec

---

tests/reporter/kubernetes.go

Adding logs for the processes running inside the compute container will help identify source pods 
with leftover compute resources and improve debugging of the virt-launcher monitor process.
After this PR:
Fixes #
```release-note
NONE
```

[Tests]Add process logs for test artifacts and virt-launcher debugging

---

tests/network/vmi_networking.go

Consolidate two tests that verify vNIC vendor in the guest into a single test with one VM that has 2 interfaces
2 different tests launched 2 different VMs, each one with a single interface of a different model
After this PR:
One test/VM was removed, and the 2 models and validations are consolidated into a single test/VM
Fixes #
```release-note
NONE
```

tests, net, vmi_networking: Unify vNIC vendor validation tests

---

pkg/monitoring/metrics/virt-controller/vmistats_collector.go
pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go

Duplicate metrics with the same label values were created due to missing IP address in multus networks status, causing the Prometheus server to error and not expose any metrics.
After this PR:
Metric has an additional network name to avoid duplicates. There is also a fallback to not creating the metric if the network name and the IP address are not defined.
Fixes #13346
```release-note
Ensure IP not empty in kubevirt_vmi_status_addresses metric
```

Ensure IP not empty in kubevirt_vmi_status_addresses metric

---

pkg/storage/snapshot/BUILD.bazel
pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/source.go
staging/src/kubevirt.io/client-go/kubecli/handler.go
tests/storage/snapshot.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/13270
Jira-ticket: https://issues.redhat.com/browse/CNV-52252
```release-note
VMSnapshot: propagate freeze error failure
```

[release-1.3] VMSnapshot: propagate freeze error failure

---

pkg/storage/snapshot/BUILD.bazel
pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/source.go
staging/src/kubevirt.io/client-go/kubecli/handler.go
tests/storage/snapshot.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/13270
Jira-ticket: https://issues.redhat.com/browse/CNV-52253
```release-note
VMSnapshot: propagate freeze error failure
```

[release-1.2] VMSnapshot: propagate freeze error failure

---

tests/guestlog/guestlog.go

Sort imports and drop DescribeTable already covered by
unit tests.
```release-note
NONE
```

e2e guestlog: Cleanup

---

pkg/cloud-init/cloud-init.go
pkg/network/setup/network_test.go
pkg/network/setup/podnic_test.go
pkg/network/vmispec/interface_test.go
pkg/virt-handler/container-disk/mount.go
pkg/virt-operator/resource/apply/admissionregistration_test.go
pkg/virt-operator/resource/apply/apiservices.go
pkg/virt-operator/resource/apply/core.go
pkg/virt-operator/resource/apply/delete.go
pkg/virt-operator/resource/generate/install/strategy.go
tests/network/probes.go
tests/storage/events.go
tests/storage/hotplug.go
tests/storage/migration.go

General cleanup: Remove unused constants & redundant condition checks
/kind cleanup
```release-note
NONE
```

General cleanup: Remove unused constants & redundant condition checks

---

pkg/virt-controller/watch/vm.go
pkg/virt-controller/watch/vm_test.go

Manual backport https://github.com/kubevirt/kubevirt/pull/13306
```release-note
NONE
```

[release 1.3] Fix Hotplug disk to VM adds RestartRequired condition

---

automation/test.sh
tests/canary_upgrade_test.go
tests/decorators/decorators.go
tests/framework/checks/skips.go
tests/hyperv_test.go
tests/instancetype/BUILD.bazel
tests/instancetype/instancetype.go
tests/launchsecurity/BUILD.bazel
tests/launchsecurity/sev.go
tests/migration/migration.go
tests/network/sriov.go
tests/numa/BUILD.bazel
tests/numa/numa.go
tests/operator/operator.go
tests/performance/BUILD.bazel
tests/performance/realtime.go
tests/realtime/BUILD.bazel
tests/realtime/realtime.go
tests/testsuite/fixture.go
tests/testsuite/kubevirtresource.go
tests/virt_control_plane_test.go
tests/virtiofs/BUILD.bazel
tests/virtiofs/config.go
tests/vmi_configuration_test.go
tests/vmi_iothreads_test.go
tests/vmi_lifecycle_test.go
tests/vmi_vsock_test.go

We now have less skips
Fixes #
```release-note
NONE
```

Remove some Skips

---

pkg/virt-launcher/monitor_test.go

and cleanup
Saw https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13536/pull-kubevirt-unit-test/1868734576357019648
After this PR:
Timeout is now 10 seconds instead of 1
Fixes #
```release-note
NONE
```

virt-launcher monitor unit tests: increase timeout to reduce flakiness

---

tests/compute/console.go

30 seconds is a stretch here in my opinion, since we have no guarantee things will converge this quickly on the CI env with parallel testing and resource constraints.
This is causing flakes:
https://search.ci.kubevirt.io/?search=%5C%5Btest_id%3A1588%5C%5Dshould+return+OS+login&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
```release-note
NONE
```

console tests: increase timeout

---

tests/network/sriov.go

In order to stop relying on DomainXML checks in e2e tests, replace root PCI bus checks
that were performed in the DomainXML intermediate product, with a check of
the actual PCI hierarchy in the guest
After this PR:
Fixes #
```release-note
NONE
```

tests, net, sriov:  check PCI hierarchy in guest instead of in DomainXML

---

automation/test.sh
tests/access_test.go
tests/container_disk_test.go
tests/decorators/decorators.go
tests/framework/checks/skips.go
tests/hyperv_test.go
tests/network/vmi_lifecycle.go
tests/storage/storage.go
tests/virtctl/vnc.go
tests/vmi_configuration_test.go
tests/vmi_lifecycle_test.go
tests/vnc_test.go

e2e, arm64: use decorator to label and filter arm64 e2e test
Fixes #13576
```release-note
NONE
```

e2e, arm64: use decorator to label and filter arm64 e2e test

---

pkg/virtctl/expose/expose.go
pkg/virtctl/expose/expose_test.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/13496
virtctl expose uses any label found on a VM/VMI as a service selector. In case of non-unique label values this can lead to exposure of the wrong VM/VMI.
After this PR:
virtctl expose uses the unique vm.kubevirt.io/name label found on every virt-launcher Pod as a service selector.
Fixes #
```release-note
virtctl expose now uses the unique `vm.kubevirt.io/name` label found on every virt-launcher Pod as a service selector.
```

[release-1.3] fix(virtctl,expose): Use vm.kubevirt.io/name as label selector

---

pkg/virt-handler/non-root.go
pkg/virt-handler/vm.go

Fixes #
```release-note
NONE
```

Remove redundant function input vars

---

tests/network/hotplug_bridge.go
tests/network/hotplug_sriov.go

Some network hotplug introduce flakes on CI, manifesting in some
assertions that depends on the guest-agent reported data fail due to
data is not reported on time by the GA.
At the current state the subject tests indicate a VM is ready by the
Ready phase and getting login prompt.
These indication sufficient to ensure the GA has started and the
expected data is reported in status.
This PR changes network hotplug tests VM readiness check to wait for the AgentConnected condition.
Network hotplug tests indicates VM is ready by the Ready phase and getting guest prompt.
This is not good enough indication as the GA may have not started yet.
Network hotplug tests indicate VM is ready depending on the AgentConnected condition, which indicates the GA has been …

tests,net,hotplug: Indicate VM ready by AgentConnected condition

---

OWNERS_ALIASES

Add nunnatsa and orenc1 to observability reviewers
Fixes #
```release-note
none
```

Add nunnatsa and orenc1 to observability reviewers

---

automation/test.sh
tests/BUILD.bazel
tests/decorators/decorators.go
tests/vmi_configuration_test.go

3 new labels are introduced:
1. HostDiskGate
2. requireHugepages1Gi
3. blockrwo
At the same time the Skips/Fails
are moved closer to the tests that needs them.
Fixes #
```release-note
Test suite: 3 new labels are available to filter tests: HostDiskGate, requireHugepages1Gi, blockrwo
```

Configuration test: Convert Skips to Fails

---

tests/decorators/decorators.go
tests/vm_state_test.go

This label should be used for tests that requires
RWO FS storage class.
In this commit, the efi and tpm tests are marked.
Fixes #
```release-note
NONE
```

Introduce RWO FS label

---

pkg/virt-launcher/notify-client/client.go
pkg/virt-launcher/notify-client/notify_test.go

The launcher was storing the previous status and reason values from the domain, and then fetching the new state.
However, the domain status was always empty in the eventCallback when it was called by the case 'eventChan' because the domain is constructed by the function [NewDomainFromName](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-launcher/virtwrap/util/libvirt_helper.go#L425), then [NewDomainReferenceFromName](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-launcher/virtwrap/api/schema.go#L1268) which doesn't populate the Status field (see [here](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-launcher/virtwrap/api/schema.go#L1275)).
This resulted in wrong prints. For example, we were always printing the domain status, even if it didn't …

launcher: fix prints for the domain events

---

OWNERS_ALIASES

Since this stable version is going to be maintained for a while, it would benefit us to have
more sig-storage approvers here as well as in main (https://github.com/kubevirt/kubevirt/pull/13313, https://github.com/kubevirt/kubevirt/pull/13312)
Fixes #
```release-note
NONE
```

[release-1.4] backport recent storage approver nominations

---

api/api-rule-violations-known.list
api/api-rule-violations.list
go.mod
go.sum
staging/src/kubevirt.io/api/go.mod
staging/src/kubevirt.io/api/go.sum
staging/src/kubevirt.io/client-go/api/openapi_generated.go
staging/src/kubevirt.io/client-go/go.mod
staging/src/kubevirt.io/client-go/go.sum
vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
vendor/modules.txt

This is the most minimal bump to allow backporting https://github.com/kubevirt/kubevirt/pull/13711
to this release branch.
Fixes #
```release-note
NONE
```

[release-1.4] Minimal bump to CDI API for StorageProfile.Status.SnapshotClass

---

pkg/virt-controller/watch/vm.go
pkg/virt-controller/watch/vm_test.go
pkg/virt-controller/watch/vmi.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/13064
Fixes #
```release-note
Fix cache corruption
```

[release-1.2] Fix corruption

---

pkg/virt-controller/services/template_test.go

Currently, the output of template service in regard to the cluster-wide useEmulation configuration option is tested in e2e tests [1][2][3], which is wasteful.
Add unit test coverage in order to prepare the ground for dropping the e2e tests.
[1] https://github.com/kubevirt/kubevirt/blob/742d7538553b028325313aa5efbca6b96814b869/tests/vmi_lifecycle_test.go#L1355
[2] https://github.com/kubevirt/kubevirt/blob/742d7538553b028325313aa5efbca6b96814b869/tests/vmi_lifecycle_test.go#L1383
[3] https://github.com/kubevirt/kubevirt/blob/742d7538553b028325313aa5efbca6b96814b869/tests/vmi_lifecycle_test.go#L1404
Fixes #
This checklist is not enforcing, but it's a reminder of …

virt-ctrl, template, tests: Add coverage for UseEmulation

---

manifests/generated/operator-csv.yaml.in
pkg/virt-operator/resource/generate/components/daemonsets.go
pkg/virt-operator/resource/generate/components/deployments.go

https://docs.openshift.com/container-platform/4.17/authentication/managing-security-context-constraints.html#security-context-constraints-requiring_configuring-internal-oauth
Fixes #
```release-note
NONE
```

Provide openshift.io/required-scc

---

tests/operator/operator.go

verifyVMIsEvicted never changes and is not a closure. There is no value in making it a lambda.
/kind cleanup
```release-note
NONE
```

tests/operator: verifyVMIsEvicted: convert to a static func

---

README.md

Update the link in the README.md to point to the up to date Ansible collection.
README.md points to old and archived Ansible collection.
After this PR:
README.md points to the current and up-to-date Ansible collection.
Fixes #
```release-note
None
```

docs(README.md): Update links to Ansible collection

---

tests/flags/flags.go
tests/infrastructure/prometheus.go

This PR introduce flag to set the promehtues-install-namesapce for  [test_id:4135]
```release-note
None
```

tests/infra/prometheus: adjust [test_id:4135] prometheus install namespace

---

tests/compute/subresources/reset.go

Currently, to allow the console to catch
the logs generated by a vmi reset, a goroutine
that waits for 5 sec before firing the reset is
spawned.
This is causing flakiness on the CI, because 
it could happen that the reset is fired before the 
watcher is waiting for the correct log.
Swapping between the reset and the console watcher 
should be more stable since we start watching before 
sending the reset request, so we cannot miss it.
Fixes #
search CI link: https://search.ci.kubevirt.io/?search=Reset+a+VirtualMachineInstance+should+succeed&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
This checklist …

e2e: fix flaky vmi reset test

---

WORKSPACE

It's going to be hard maintaining this release branch if we don't do this, some of the mirrors are already down
Fixes #
I dug this out of the history in https://github.com/kubevirt/kubevirt/pull/13540
```release-note
NONE
```

[release-1.4] backport some RPM mirroring

---

tests/instancetype/instancetype.go
tests/instancetype/reference_policy.go

Instead of creating a stopped VM and starting it, create a vm with with the desired runStrategy.
After this PR:
Fixes #
```release-note
NONE
```

[Tests]instance_type.go: Reduces API calls

---

pkg/virt-handler/vm.go

This is an attempt to rationalize the code of the vmUpdateHelperDefault in virt-handler.
I was losing track of what was happening in some of the functions in virt-handler and wanted to rework it.
```release-note
NONE
```

simplify vmUpdateHelperDefault

---

pkg/virt-operator/resource/generate/components/daemonsets.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/13866
```release-note
NONE
```

[release-1.3] Make dev directory dynamic for the pr-helper container

---

tests/clone_test.go

There is no reason for the function to be a closure. Also only passing needed params.
After this PR:
Fixes #
```release-note
NONE
```

tests/clone_tests: Refactor generateSnapshot to normal function

---

tests/instancetype/upgrade.go

Update is likely to fail. A simple patch should do the trick.
This should fix flake as https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13764/pull-kubevirt-e2e-k8s-1.32-sig-compute/1892540271221018624
Fixes #
```release-note
NONE
```

instance types, upgrade tests: Don't use update

---

tests/storage/snapshot.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/13874
Fixes #
```release-note
NONE
```

[release-1.3] snapshot tests: use alpine instead of fedora for non-guest-agent tests

---

cmd/virt-handler/virt-handler.go
pkg/virt-handler/cache/BUILD.bazel
pkg/virt-handler/cache/cache.go
pkg/virt-handler/cache/cache_test.go
pkg/virt-handler/cache/domain-watcher.go
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

Refactor ghost records from singleton(global package) to struct. This should help with separating some of the components.
Fixes #
```release-note
NONE
```

Refactor Ghost records 

---

pkg/virt-handler/vm_test.go

Removes usage of informers from handler unit tests in order to simplify them and allow them to be faster in future.
One test is now fixed. Small cleanup of global variables is included.
Fixes #
```release-note
NONE
```

Handler unit tests: Remove informer usage

---

pkg/monitoring/metrics/virt-controller/BUILD.bazel
pkg/monitoring/metrics/virt-controller/metrics.go
pkg/monitoring/metrics/virt-controller/vmistats_collector.go
pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go
pkg/virt-controller/watch/application.go
tests/monitoring/metrics.go
tools/doc-generator/doc-generator.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/13535 and https://github.com/kubevirt/kubevirt/pull/13805
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-56955
```release-note
Collect resource requests and limits from VM instance type/preference
```

[release-1.3] Collect resource requests and limits from VM instance type/preference

---

tests/network/link_state.go

- Apply gofumpt
- Add a missing error assertion
- Break long lines
- Replace magic numbers with consts
- Avoid variable shadowing
The `switch` statement in `assertLinkStateCmd` was replaced with an `if` statement in order to avoid the linter's error about the `switch` statement not being comprehensive due to it ignoring the `v1.InterfaceStateAbsent` state.
In case the `desiredLinkState` is neither `up` nor `down` - an illegal command will be generated and en error will occur.
Fixes #
```release-note
NONE
```

net, e2e, link_state: Apply linter

---

pkg/virt-handler/vm.go

Fixes small bug, see https://github.com/kubevirt/kubevirt/pull/13878#discussion_r1976503582
Fixes #
Not to fix the bug? 
Not to fix the bug? 
https://github.com/kubevirt/kubevirt/pull/13878#discussion_r1976503582
Did the previous section helped?
```release-note
NONE
```

Fix: Actually wait for session or key

---

OWNERS_ALIASES

I would like to suggest the nomination of @orelmisan as a SIG network approver.
Orel has been active in the core kubevirt repo from late 2021, contributing over
[150 PRs](https://github.com/kubevirt/kubevirt/pulls?page=1&q=is%3Amerged+is%3Apr+author%3Aorelmisan), including features, bug fixes, optimizations, code quality improvements and documentation.
Orel reviewed over [250
PRs](https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+commenter%3Aorelmisan+is%3Aclosed+-author%3Aorelmisan) and participated in reviews of multiple design proposals.
Noticeable features include:
- [Descheduler support](https://github.com/kubevirt/community/blob/main/design-proposals/descheduler-support.md)
- [Dynamic primary pod NIC name](https://github.com/kubevirt/community/blob/main/design-proposals/dynamic-pr …

Nominate orelmisan for sig-network approver

---

tests/clone_test.go

Volumes are not needed for the test, and also introduce an issue with unbound PVCs in stopped VM when WFFC storage is used.
```release-note
NONE
```

tests/clone_test: use guestless VM in ControllerRevisions test

---

tests/hyperv_test.go

with matcher.ThisVMI and matcher.HaveConditionFalseWithMessage to verify non-migratable VMs when TSC Frequency is not exposed on the cluster.
Also, remove unnecessary use of Consistently since the VMI condition is not expected to change after being added, making the expensive consistency check redundant.
Merge the test cases `should be able to start successfully` and
`should be marked as non-migratable` to a single test to save resources
/kind cleanup
After this PR:
Fixes #
```release-note
NONE
```

hyperv_test:Replace large condition fetch and verification lambda function and merge tests

---

pkg/virt-handler/cache/cache.go
pkg/virt-handler/cmd-client/client.go
pkg/virt-handler/device-manager/device_controller.go
pkg/virt-handler/device-manager/usb_device.go
pkg/virt-handler/device-manager/usb_device_test.go
pkg/virt-handler/hotplug-disk/mount.go
pkg/virt-handler/hotplug-disk/mount_test.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/node-labeller/node_labeller.go
pkg/virt-handler/vm.go

Cleanup: Remove redundant size capacity, handle potential nil pointer dereference, replace an empty slice with nil
```release-note
NONE
```

Cleanup: Remove redundant size capacity, handle potential nil pointer dereference, replace an empty slice with nil

---

automation/repeated_test.sh

We are currently using a shotgun approach to determine which tests have been changed - we are only looking at the test files that have been modified and re-running all of them.
After this PR:
Uses `cannier extract changed-tests` to fetch the test names of changed tests, then focuses only these.
Fixes #
```release-note
NONE
```

ci: narrow down re-run tests to changed tests only

---

OWNERS_ALIASES

@dasionov have introduced his [first PR](https://github.com/kubevirt/kubevirt/pull/12427) more than 6 months ago.
Since then, he reviewed [89 PRs](https://github.com/kubevirt/kubevirt/pulls?q=is%3Amerged+is%3Apr+commenter%3Adasionov+) and merged [36 PRs](https://github.com/kubevirt/kubevirt/pulls?q=is%3Amerged+is%3Apr+author%3Adasionov+).
By doing that, he fulfils the basic [requirements](https://github.com/kubevirt/community/blob/main/membership_policy.md#requirements-1) for becoming a reviewer.
Thank you @dasionov for your work. I'm certain that your help to sig-compute would be valuable and fruitful.
```release-note
NONE
```

Nominate dasionov as a sig-compute reviewer

---

automation/repeated_test.sh

Otherwise, we panic if there are curly brackets in test name during ginkgo set assembly
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13422/pull-kubevirt-check-tests-for-flakes/1904903510810431488/build-log.txt
Fixes #
```release-note
NONE
```

Escape arg passed to ginkgo --focus in flake lane

---

pkg/instancetype/controller/vm/controller.go
pkg/instancetype/controller/vm/controller_test.go
pkg/instancetype/webhooks/vm/admitter.go
pkg/instancetype/webhooks/vm/admitter_test.go
tests/framework/matcher/conditions.go
tests/framework/matcher/conditions_test.go
tests/instancetype/instancetype.go

The mutation and validation webhooks would both reject the creation of a VirtualMachine that referenced an instance type or preference that was not available within the cluster.
After this PR:
The webhooks no longer reject the creation request of a VirtualMachine referencing an instance type or preference that are unavailable within the cluster. Additionally the VirtualMachine controller will now correctly decorate the `Failure` condition with a `FailedFind{Instancetype,Reason}` to provide context to a user for why the `VirtualMachine` cannot start.
Fixes # …

instancetype: Stop rejecting vm if not found by webhooks

---

pkg/instancetype/instancetype.go
pkg/monitoring/metrics/virt-controller/BUILD.bazel
pkg/monitoring/metrics/virt-controller/metrics.go
pkg/monitoring/metrics/virt-controller/vmistats_collector.go
pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
pkg/monitoring/metrics/virt-controller/vmstats_collector.go
pkg/monitoring/metrics/virt-controller/vmstats_collector_test.go
pkg/testutils/mock_instancetype.go
pkg/virt-controller/watch/application.go
tools/doc-generator/doc-generator.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/13535 and https://github.com/kubevirt/kubevirt/pull/13805
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-56404
```release-note
Collect resource requests and limits from VM instance type/preference
```

[release-1.2] Collect resource requests and limits from VM instance type/preference

---

ADOPTERS.md

After this PR:
Adds Aussie Broadband as an end-user of the KubeVirt Project
Fixes #
-
```release-note
```

Add Aussie Broadband as an end-user of KubeVirt

---

pkg/virt-operator/kubevirt_test.go

[This](https://github.com/kubevirt/kubevirt/pull/13960) was only considering one of the deployments. Thanks @ShellyKa13
Fixes #
```release-note
NONE
```

Consider both deployments in product labels unit test

---

tests/network/bindingplugin_passt.go

Refactor the network passt tests and arrange them to separate between based on the required setup.
Focusing on VM creation and setup and executing tests per IP stack in the body.
This has a potential to re-use the VMs for the IP stack specific tests.
As a side-effect, tests names have changed a bit.
Fixes #
For the review, it is recommended to use the `Hide whitespace` option (due to the indentation changes).
```release-note
NONE
```

tests, net, passt: Refactor tests and separate VM setup and test body for IP dual stack sceanrios

---

ADOPTERS.md

After this PR: Swisscom is listed in the ADOPTERS.md file as vendor.
Fixes #
```release-note
```

add Swisscom as vendor to ADOPTERS.md

---

tests/virtctl/scp.go
tests/virtctl/ssh.go

Create a VMI before the virtctl ssh or scp tests just once and reuse it
for all test cases. This saves recreating a VMI for every test case, as
they can easily work with the same VMI.
This is based on https://github.com/kubevirt/kubevirt/pull/13786
virtctl ssh and scp tests create a new VMI before each test case.
After this PR:
virtctl ssh and scp tests create a new VMI just once and reuse it.
Fixes #
This PR is intended to demonstrate the time and resources saved by reusing VMIs.
```release-note
None
```

chore(tests,virtctl): Reuse VMI in ssh and scp tests 

---

tests/migration/migration.go

It can happen that the Kubernetes haven't setup
the quota yet. This commit will wait for status report
Fixes #
Flakes are not cool
```release-note
NONE
```

Migration quota test: Wait for quota

---

pkg/libvmi/storage.go
pkg/virt-controller/watch/vmi/datavolumes.go
pkg/virt-controller/watch/vmi/lifecycle.go
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go
tests/libstorage/datavolume.go
tests/storage/hotplug.go

Could not boot from a VM with only hotpluggable disks
After this PR:
Can boot from hotpluggable disk. This is mostly interesting when combined with future work for inject/eject cdrom or boot from usb drive
Fixes #
```release-note
hotplug volume: Boot from hotpluggable disk
```

hotplug volume: Boot from hotpluggable disk

---

tests/storage/export.go

"local" opts out of chown/chmod if multiple mount points exists
exist at a given time, so the pod will never be able to read
files.
Normally, this would've worked, but fsgroup tests run with group
2000 which is left on the local volumes.
this is a NASTY interdependency that is probably further uncovered
by truly randomizing the order (6be5f4acba)
example failure:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/14519/pull-kubevirt-e2e-k8s-1.32-sig-storage/1913922387133337600
Fixes # …

Fix permission flake in export tests

---

pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/snapshot_test.go
pkg/storage/snapshot/source.go
staging/src/kubevirt.io/api/snapshot/v1beta1/types.go
tests/storage/snapshot.go

This is a manual  cherry-pick of https://github.com/kubevirt/kubevirt/pull/14096
```release-note
VMSnapshot: add QuiesceFailed indication to snapshot if freeze failed
```

[release-1.4] VMSnapshot: add QuiesceFailed indication to snapshot if freeze failed

---

pkg/network/downwardapi/networkinfo_test.go

PR [1] has adjusted `CreateNetworkInfoAnnotationValue` to produce the JSON array string ordered by network name in lexicographical order.
- Add a third network to increase the chances the test will fail in case the ordering logic fails [2].
- Compare the actual network info struct to an expected struct in order to show all the info in case the assertion fails.
[1] https://github.com/kubevirt/kubevirt/pull/14477
[2] https://go.dev/ref/spec#For_range
Fixes #
https://github.com/kubevirt/kubevirt/pull/14477#discussion_r2051689868 …

net, downwardapi: Refactor net-info annotation tests

---

hack/linter/lint-paths.txt
pkg/virtctl/adm/adm.go
pkg/virtctl/adm/logverbosity/logverbosity.go
pkg/virtctl/adm/logverbosity/logverbosity_test.go

After this PR:
Fixes 
- https://github.com/kubevirt/kubevirt/issues/14185
```release-note
none
```

fixed lint issue in pkg/virtctl/adm

---

WORKSPACE

After this PR:
Fixes #
```release-note
NONE
```

[release-1.4] Manual run of uploader to add missing mirror URLs

---

pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go

Ensure that the unit-test for default machine type runs independent from the host architecture while covering all supported arches.
The unit test for default machine type is dependent on the host architecture
After this PR:
The unit test for default machine type is independent on the host architecture
Fixes #
https://github.com/kubevirt/kubevirt/pull/13852#discussion_r1993050336
```release-note
NONE
```

virt-api: Make machine type unit-test for unknown arch independent from host

---

pkg/virt-controller/watch/vmi/lifecycle.go
pkg/virt-controller/watch/vmi/vmi_test.go

`/status/interfaces` would be constantly patched due to the non-deterministic network interface slices causing DeepEqual to return false.
After this PR:
Patch flood is prevented.
Fixes #14442 
```release-note
NONE
```

VMI: Sort network interfaces to avoid patch flood

---

tests/storage/migration.go

assert that the volume is gone after unplugging instead of asserting it exists
(which probably only ever passed as a fluke)
Fixes #
```release-note
NONE
```

storage migration tests: fix inverse assertion

---

pkg/libvmi/cpu.go
pkg/libvmi/storage.go
pkg/virt-controller/services/renderresources.go
pkg/virt-controller/services/renderresources_test.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go

Manual backport #14569
```release-note
NONE
```

[release-1.5] Fix cpu counting for io threads count

---

tests/network/vmi_multus.go

Remove redundant test checking single secondary `multus` network.
Quite a few other tests already check such settings.
For example: [ should be able to ping between two vms [test_id:1577]with secondary network only](https://github.com/kubevirt/kubevirt/blob/release-1.5/tests/network/vmi_multus.go#L44).
Keep the test that uses an alternate namespace for the NAD, as it is unique.
Remove the test that verifies custom mac address, as the [VirtualMachineInstance with Linux bridge CNI plugin interface and custom MAC](https://github.com/kubevirt/kubevirt/blob/release-1.5/tests/network/vmi_multus.go#L447) test, already verifies that.
After this PR:
Fixes #
Consolidating tests under a single VM …

e2e, net, multus: Cleanup redundant tests

---

OWNERS_ALIASES

Since I am no longer involved with the project.
Thank you KubeVirt team and keep up the great work!
So long, and thanks for all the fish! :)
After this PR:
Fixes #
```release-note
NONE
```

OWNERS: Move acardace to the emeritus approvers

---

pkg/virtctl/vnc/vnc.go

VNC clients were hardcoded. This prevented client versions with unexpected paths (for example TigerVNC v1.15.0 which had lowercase "viewer" in the path, where capital was expected), to be used.
After this PR:
Users can now specify the `--vnc-type` and `--vnc-path` to specify their VNC client. If none are provided it falls back to the original logic to ensure backwards compatibility.
There are security concerns over passing these to the `CommandContext`. In the context of `virtctl vnc` I don't believe this could be of concern, but I can be overlooking some detail. Please let me know.
I first implemented checks for specific patterns on VNC client names but it didn't solve the underlying security …

feat(virtctl): add support for user provided vnc type and path of vnc client

---

tests/storage/reservation.go

Currently, we don't test multipath socket handling in functional tests, since multipath isn't installed in kubevirtci, and we don't have any CSI storage handling mpath volumes.
Multipath is, generally, installed and managed outside KubeVirt. However, kubevirt needs to guarantee that the multipathd.socket is reachable by the pr-helper daemon.
This functional tests makes sure that multipathd.socket is correctly mounted inside the handler pod.
We didn't test the mpath handling, only with unit tests
After this PR:
Add additional some coverage for the mpath socket handling. 
Fixes #
Generally, we are trying to move as much testing as possible to unit …

tests: verify handling of multipathd.socket

---

pkg/hooks/manager.go

In case there are expected sidecars but no sockets at all (for example due to bug on one of the sidecars),
hook manager Collect would not have chance to check the triggered timeout, hence won't respect the request timeout argument.
Since virt-launcher blocking wait for the collect, the virt-launcher will hang forever (or until higher level,
such as e2e test timeout will stop it).
Fix it by checking it in the right place, as it was checked in the wrong loop (the internal one which process sockets).
Fixes #
Recommended to review without whitespace
https://github.com/kubevirt/kubevirt/pull/14764/files?diff=split&w=1 …

virt-launcher,sidecars: Fix gRPC socket Collect corner case

---

pkg/network/controllers/vm.go
pkg/network/controllers/vm_test.go

In case a user marked an interface as absent, and immediately
stopped the VM, absent devices would linger until the VM
is restarted again.
Fix it by cleaning absent interfaces and their network also
if VM is stopped.
Fixes #
```release-note
Clean absent interfaces and their relative networks from stopped VMs.
```

virt-controller, network: Fix absent interfaces cleaning

---

tests/vm_test.go

When ran the test, and hit a failure in test_id:4119, the error message was:
```
[FAILED] Timed out after 240.001s.
Expected
<bool>: false
to be true
In [It] at: tests/vm_test.go:795 @ 05/21/25 11:54:41.358
```
This failure message can be improved to be more informative.
This commit changes the `Eventually` expression in test_id:4119, to print a relevant error mesage instead of the generic gomega.BeTrue() non-informative default error message.
```release-note
None
```

Improve the readability of test_id:4119 failures

---

cmd/virt-freezer/BUILD.bazel
cmd/virt-freezer/main.go
cmd/virt-freezer/virt-freezer.go
cmd/virt-freezer/virt-freezer_suite_test.go
cmd/virt-freezer/virt-freezer_test.go
tests/storage/BUILD.bazel
tests/storage/snapshot.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/14737
```release-note
NONE
```

[release-1.5] virt-Freeze: skip freeze if domain is not in running state

---

cmd/virt-freezer/BUILD.bazel
cmd/virt-freezer/main.go
cmd/virt-freezer/virt-freezer.go
cmd/virt-freezer/virt-freezer_suite_test.go
cmd/virt-freezer/virt-freezer_test.go
tests/storage/BUILD.bazel
tests/storage/snapshot.go

This is a manual cherry-pick of #14737
```release-note
NONE
```

[release-1.4] virt-Freeze: skip freeze if domain is not in running state

---

pkg/virt-controller/watch/vm/BUILD.bazel
pkg/virt-controller/watch/vm/vm.go
pkg/virt-controller/watch/vm/vm_test.go

Currently CPU hotplug is not supported on ARM.
```release-note
NONE
```

Disable CPU hotplug on ARM

---

pkg/virt-launcher/notify-client/notify_test.go

Cleanup of notify_test
Fixes #
```release-note
NONE
```

Notify test

---

cmd/virt-chroot/tap-device-maker.go

Currently, when creating a tap device, we specify the number of required queues to the netlink library.
It causes the library to create redundant file descriptors that are discarded when the virt-chroot binary exists.
The file descriptors that are used by qemu are actually created by libvirt [1].
Explicitly specify the required flags used for creating the tap device in the multi-queue case.
[1] https://github.com/libvirt/libvirt/blob/v10.0.0/src/util/virnetdevtap.c#L206-L236
Fixes #
```release-note
NONE
```

virt-chroot, create-tap: Don't create redundant fds

---

pkg/virt-controller/watch/vm/firmware.go
pkg/virt-controller/watch/vm/firmware_test.go

Both deepcopy and equal check can be expensive
to execute each sync. Therefore we refactor the
firmware controller to a state where these 2
actions are not needed.
At the same time this commit contains small
refactor of unit tests to make them little bit more clear.
```release-note
NONE
```

firmware: Remove deepcopy and equal check

---

tests/containerdisk/containerdisk.go
tests/migration/BUILD.bazel
tests/migration/migration.go

Test fix: Properly use kernel boot cd image

---

manifests/generated/operator-csv.yaml.in
pkg/virt-operator/resource/generate/components/deployments.go

It is a good practice to have a livenss probe
in order to get "auto-recovery".
Fixes #
```release-note
NONE
```

Operator: Add liveness probe

---

pkg/virt-controller/services/template.go

Added padding directly to gracePeriodSeconds
Remove redundant helper function
Make virtProbeOverhead a local variable
Make virtProbeTotalAdditionalOverhead a local variable
/cleanup
```release-note
NONE
```

virt-controller: cleanup

---

tests/storage/declarative-hotplug.go

Split up flaky batch and make parts idempotent
Increase timeouts
```release-note
NONE
```

flaky test: Fix Declarative Hotplug Flake

---

pkg/virt-controller/services/renderresources.go
pkg/virt-controller/services/renderresources_test.go
pkg/virt-controller/services/template.go

The `vmi` parameter of `hotplugContainerResourceRequirementsForVMI` is unused.
```release-note
NONE
```

vmi ctrl, template: Rm unused function parameter

---

pkg/synchronization-controller/synchronization-controller_test.go

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/14887/pull-kubevirt-unit-test-s390x/1937455876868673536 shows a data race.
The AfterEach which close connections, doesnt wait for the go routine to finish, hence it can still run when the next test initialize again the controller.
Sync between the AfterEach and go routine finalize.
```release-note
None
```

unit tests: Fix Data race

---

BUILD.bazel
WORKSPACE
automation/release.sh
cmd/cniplugins/passt-binding/cmd/BUILD.bazel
cmd/cniplugins/passt-binding/passt-binding-ds.yaml
hack/bazel-build-functests.sh
hack/bazel-build.sh
hack/bazel-push-images.sh
hack/cluster-sync.sh
hack/deploy-to-nodes.sh

Instead exporting the passt binary, wrap it with a container image.
Use a daemonSet to deploy it.
```release-note
Release passt CNI image, instead the CNI binary itself.
```

cniplugins: Advertise passt cni image

---

pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

In https://github.com/kubevirt/kubevirt/pull/11833 we added the AllowWorkloadDisruption field.
// UPGRADE PATH IS
1. daemonsets - ensures all compute nodes are updated to handle new features
2. wait for daemonsets to roll over
3. controllers - ensures control plane is ready for new features
4. wait for controllers to roll over
5. apiserver - toggles on new features.
If a migration is triggered from a node where the handler has been updated,
but the controller has not been updated yet, a nil pointer exception is raised.
This because the older migration controller set the vmi.Status.MigrationState.MigrationConfiguration without specifying the AllowWorkloadDisruption field.
At that point, the upgraded virt-handler tries to start the migration, but when
it tries to specify the migration …

[release-1.5] Fix possible nil pointer caused by migration during kv upgrade

---

pkg/virt-handler/migration-source_test.go
pkg/virt-handler/migration-target_test.go

As an immediate follow-up for https://github.com/kubevirt/kubevirt/pull/14875,
Addressing this important comment : https://github.com/kubevirt/kubevirt/pull/14875#discussion_r2166558449.
Currently, migration source and migration target unit test inject a `passt` handler stub to controllers but they do not verify that it is actually called.
Enhance existing test to verify that the handler is indeed called when it should be.
VEP tracking issue: https://github.com/kubevirt/enhancements/issues/21
https://github.com/kubevirt/kubevirt/pull/14875#discussion_r2166558449 …

virt-handler, migration tests: Expect passt handler call

---

api/openapi-spec/swagger.json
pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/application_test.go
pkg/virt-controller/watch/migration/migration.go
pkg/virt-controller/watch/migration/migration_test.go
pkg/virt-operator/resource/apply/core.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/libmigration/migration.go

Manual backport of #15021 
```release-note
NONE
```

[release-1.6] Add synchronizationAddress to migration resource status

---

.github/OWNERS

If there are issues in the github actions, sig-buildsystem may need to act quickly to resolve issues so they require ownership over this directory. 
```release-note
NONE
```

github, actions: Add sig-buildsystem as owners of the .github dir

---

hack/linter/lint-paths.txt

The directories in question could be covered by the linter without performing any code changes.
Additionally, make sure the `hack/linter/lint-paths.txt` file is sorted.
```release-note
NONE
```

Linter: Cover additional "clean" directories

---

pkg/controller/virtinformers.go
pkg/virt-controller/watch/application.go

Currently, k8s DRA FG is not enabled by default https://kubernetes.io/docs/concepts/scheduling-eviction/dynamic-resource-allocation/
KV side, there are 2 FGs related to DRA (GPUsWithDRAGate, HostDevicesWithDRAGate). When both are disabled, the DRA controller is not executed; however, the informer factory is started for both resourceClaim and resourceSlice.
This is causing some spam in virt-controller logs: `pkg/controller/virtinformers.go:373: failed to list *v1beta1.ResourceSlice: the server could not find the requested resource (get resourceslices.resource.k8s.io)` and
`pkg/controller/virtinformers.go:373: failed to list *v1beta1.ResourceClaim: the server could not find the requested resource (get resourceclaims.resource.k8s.io)`.
In order to avoid this, 2 dummy informers are …

Introduce dummy dra informers when FG disabled

---

pkg/network/controllers/vm.go

PR https://github.com/kubevirt/kubevirt/pull/14914 pushed the VMI patch operation down the call stack.
Move the VMI patch operation one level up the call stack in order to make it more visible.
https://github.com/kubevirt/kubevirt/pull/14914#discussion_r2164404211
```release-note
NONE
```

net, vm ctrl: Mv VMI patch up the stack

---

cmd/sidecars/network-passt-binding/server/server.go
hack/linter/lint-paths.txt

- Break long lines
- Use strings.EqualFold(val, "true") following the linter's recommendation.
```release-note
NONE
```

Linter: Cover passt BP sidecar's server package

---

hack/bazel-push-images.sh

/sig buildsystem
The switch statement wasn't obvious and was easy to misinterpret. As we only care about skipping images for s390x turn this into a simple conditional.
Created to avoid future embarrassment after https://github.com/kubevirt/kubevirt/issues/15189
```release-note
NONE
```

hack: Refine and document bazel-push-images logic

---

pkg/virt-launcher/virtwrap/device/hostdevice/dra/gpu_hostdev.go

virt-launcher: Reduce logging of "No DRA GPU devices found for vmi"

---

pkg/virt-controller/watch/drain/evacuation/BUILD.bazel
pkg/virt-controller/watch/drain/evacuation/evacuation_test.go

Refactors unit tests in order to remove complexity and reduce runtime ~3 seconds to ~0.1 seconds.
```release-note
NONE
```

Evacuation controller refactor

---

tests/migration/namespace.go

This failure is impacting the merging of other PRs.
https://search.ci.kubevirt.io/?search=%5C%5Brfe_id%3A393%5D%5C%5Bcrit%3Ahigh%5D%5C%5Bvendor%3Acnv-qe%40redhat.com%5D%5C%5Blevel%3Asystem%5D%5C%5Bsig-compute%5D+Live+Migration+across+namespaces+container+disk+should+live+migrate+a+container+disk+vm%2C+with+an+additional+PVC+mounted%2C+should+stay+mounted+after+migration&maxAge=336h&context=1&type=junit&name=pull-kubevirt-e2e-k8s-1.32-sig-compute-migrations-1.6&excludeName=periodic-.*&maxMatches=1&maxBytes=20971520&groupBy=job …

[release-1.6] Quarantine decentralized lm test

---

automation/test.sh

Multus v4 is the actively developed version, succeeding v3. Currently, Multus v3 is being used on most CI lanes owned by SIG network.
Deploy Multus v4 across all SIG network-owned lanes via CNAO.
Note: The SR-IOV lanes remain unaffected as they use a separate Multus deployment.
```release-note
NONE
```

test.sh, SIG network: Always deploy Multus v4

---

hack/linter/lint-paths.txt
pkg/network/driver/virtchroot/tap.go

Apply `make gofumpt`.
```release-note
NONE
```

net, driver, virtchroot: Add linter coverage

---

.github/workflows/label_approved_veps.yaml

Update the vep approved labeller using the 1.7 project
```release-note
none
```
/cc @vladikr

Update target project url for 1.7 vep

---

tests/network/vmi_networking.go

Currently the subject tests check connectivity against virt-handler pods, which is a system core component. 
It may or may not be accessible from any namespace, i.e.: when network-policy is in place restricting access to/from kubevirt namespace.
And in general applications running on a cluster should avoid interacting with system components directly, avoiding unexpected behavior and disruptions.
Perform connectivity check against pod in the same namespace as the tested vm, as in other e2e tests that check network connectivity.
The following tests check connectiviry against virt-handler pods
```
Networking VirtualMachineInstance with masquerade binding mechanism when performing migration preserves connectivity - IPv4 [It] with explicit ports used by live migration
Networking …
```

 tests,network: Perform conn. check against pod in tests namespace

---

pkg/virt-handler/cache/cache.go
pkg/virt-handler/cgroup/cgroup.go
pkg/virt-handler/cmd-client/client.go
pkg/virt-handler/hotplug-disk/mount.go
pkg/virt-handler/isolation/detector.go

The `detector` pkg is now using safepath
```release-note
NONE
```

Safepath: detector 

---

pkg/virt-operator/BUILD.bazel
pkg/virt-operator/strategy_job.go

$title
```release-note
NONE
```

Make strategy job comply Pod Security

---

pkg/host-disk/BUILD.bazel
pkg/host-disk/host-disk.go
pkg/host-disk/host-disk_test.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/15386
```release-note
NONE
```

[release-1.2] Host-disk & PVC: Contain disk inside volume

---

pkg/virt-handler/cache/cache.go
pkg/virt-handler/cgroup/cgroup.go
pkg/virt-handler/cmd-client/client.go
pkg/virt-handler/hotplug-disk/mount.go
pkg/virt-handler/isolation/detector.go

Manual backport [15393](https://github.com/kubevirt/kubevirt/pull/15393)
```release-note
NONE
```

[release-1.4] Safepath: detector

---

pkg/network/link/BUILD.bazel
pkg/network/link/address.go
pkg/network/link/address_test.go

FilterPodNetworkRoutes was removed already on
https://github.com/kubevirt/kubevirt/pull/10396/files#diff-ea9fe04fcc67ad85b7b58b117f1fc7a62882bed0d683661fe1d8e6d762b91eefL119
Just tests of it left.
```release-note
None
```

network: Removed unused function

---

pkg/virt-handler/cmd-client/BUILD.bazel
pkg/virt-handler/cmd-client/client.go
pkg/virt-handler/cmd-client/client_test.go

This is a manual cherry-pick of #15430
/assign xpivarc
```release-note
NONE
```
/cherrypick release-1.4 release-1.3 release-1.2 release-1.1 release-1.0

[release-1.5] Safepath, cmd-client: FindSocketOnHost

---

.github/PULL_REQUEST_TEMPLATE.md

$subject
```release-note
none
```

fix typo in pr template

---

pkg/virt-handler/cache/cache.go
pkg/virt-handler/cgroup/cgroup.go
pkg/virt-handler/cmd-client/BUILD.bazel
pkg/virt-handler/cmd-client/client.go
pkg/virt-handler/cmd-client/client_test.go
pkg/virt-handler/hotplug-disk/mount.go
pkg/virt-handler/isolation/detector.go

This is a manual cherry-pick of  #15418 and #15499
/assign xpivarc
```release-note
NONE
```
/cherrypick release-1.2 release-1.1 release-1.0

[release-1.3] Safepath, cmd-client|detector: FindSocketOnHost

---

pkg/virt-handler/rest/lifecycle.go

This is a manual cherry-pick of [#15582](https://github.com/kubevirt/kubevirt/pull/15585)
```release-note
Fix: grpc client in handler rest requests are properly closed
```
/cherrypick release-1.3 release-1.2 release-1.1 release-1.0

[release-1.4] Fix rest handler leak

---

pkg/network/multus/annotation.go

The `networkAnnotationPool` type is a thin wrapper for a `[]networkv1.NetworkSelectionElement` slice that adds no significant functionality.
To simplify the codebase and reduce indirection, this abstraction is removed in favor of using the underlying slice directly.
```release-note
NONE
```

net, multus: Remove networkAnnotationPool

---

pkg/network/netbinding/netbinding.go

network bindings: Fix typo

---

pkg/synchronization-controller/synchronization-controller.go

Remove code that looks up DNS record for the pod ip address. We are really only interested in the pod ip address.
We would try to look up a DNS record for the IP address and use that. This would cause issues
when we provide the FQDN to the other side since the DNS record doesn't exist there.
Pass the IP address as is instead of looking up the DNS record.
- VEP tracking issue: https://github.com/kubevirt/enhancements/issues/24
```release-note
Allow decentralized live migration on L3 networks
```

Allow L3 network for decentralized migrations

---

tests/vm_test.go

This reverts commit c3277ad3cd11f0f501135d34a70ea65e190462f8.
```release-note
NONE
```

Reapply "Remove GetRunningVMIDomainSpec from vm_test.go tests"

---

tests/default-ceph-config.json
tests/libstorage/config.go
tests/libstorage/storageclass.go
tests/storage/migration.go

Cherry pick of #15254
```release-note
NONE
```

[release-1.5] Fix Volume Migration Tests

---

BUILD.bazel
cmd/synchronization-controller/BUILD.bazel
hack/bazel-build-images.sh

We need it prefixed with "virt-" following https://github.com/kubevirt/kubevirt/pull/15741
but in any case that would've been the standard
(see other image target names)
Otherwise, this gets pushed to quay.io/kubevirt/synchronization-controller
which may be regarded as breaking an API
```release-note
NONE
```

Adapt synchronization-controller oci_image name

---

go.work.sum
pkg/virt-launcher/virtwrap/BUILD.bazel
pkg/virt-launcher/virtwrap/live-migration-target.go
pkg/virt-launcher/virtwrap/live-migration-target_test.go

This PR builds up on https://github.com/kubevirt/kubevirt/pull/15721, tweaking the logic and timeouts and adding tests and comments.
- Premature failure when job info not available
- Timeout too long
- Not enough tests
- Not enough comments
Fixed
```release-note
NONE
```

target migration monitor: improve logic, timeouts and tests

---

pkg/storage/snapshot/restore.go
tests/storage/restore.go

Manual backport of #15692
Biggest difference is there is no `VolumeOwnershipPolicy` logic that was introduced recently.
```release-note
BugFix: Restoring naked PVCs from a VMSnapshot are now properly owned by the VM if the restore policy is set to VM
```

[release-1.5] Properly set owner references for restored PVCs
