kubevirt/kubevirt

tests/storage/storage.go

These tests have both been [flaking for a while, including in periodic runs.](https://search.ci.kubevirt.io/?search=should+pause+VMI+on+IO+error&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)
Let's re-add them to quarantine so they don't waste the time of people who are wondering why their pull requests fail tests.
```release-note
NONE
```

Add "IO error" functional tests back to quarantine

---

tests/reporter/kubernetes.go

I noticed a very odd [error log](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7044/pull-kubevirt-e2e-k8s-1.20-sig-compute-nonroot/1479758653413134336#1:build-log.txt%3A2835) where a [Cirros VM](https://github.com/kubevirt/kubevirt/blob/1b5960a/tests/vmi_configuration_test.go#L1061) is [not recognized as such](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7044/pull-kubevirt-e2e-k8s-1.20-sig-compute-nonroot/1479758653413134336#1:build-log.txt%3A2863).
I have no idea what is the problem there, but this PR would like to reduce the distraction caused by unrelated glitches.
```release-note
NONE
```

tests.reporter.kubernetes minor cleanup

---

pkg/virt-handler/device-manager/device_controller.go
pkg/virt-handler/device-manager/pci_device.go
pkg/virt-handler/device-manager/pci_device_test.go
tests/vmi_hostdev_test.go

Fix the initialization of the PCI device list for the device plugin with the same resource name.
The current code has a bug that doesn't correct initialize the PCI devices with different vendor/product id before the device plugin is started ([here](https://github.com/kubevirt/kubevirt/blob/314b515473a3720dce35f5477c6dbfdc7d544e5c/pkg/virt-handler/device-manager/device_controller.go#L151-L160)). The variable `isRunning` is always false as we haven't started the device plugin yet and if we have multiple devices with the same resource name we are overwriting the previous value and pass a single device.  …

Fix initialization of the device plugin with different vendor/product id but same resource name

---

tests/tests_suite_test.go

This PR addresses problems when running kubevirt e2e tests while using KUBEVIRT_PROVIDER=external. In that case a registry:5000 is normally not available, so the vm-generator needs to get passed the source registry from which to pull the utility images that we use for the tests.
In oder to work for other image registries pointed at by
--utility-container-prefix and --container-tag when testing
we need to pass through that test flag to the vms-generator
which is used in the tests.
**Which issue(s) this PR fixes**(optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #
```release-note
NONE
```
/cc @dhiller

[release-0.44]Pass through docker prefix and tag for vms-generator

---

pkg/virt-controller/watch/snapshot/source.go
tests/storage/restore.go
tests/storage/snapshot.go

The hotplugs were included in the vmsnapshotcontent
but volumesnapshot wasnt created for them since the
volumes list was taken from the vm revision and
not from the current vm volumes.
Added the vmsnapshot hotplugs test of snapshot
and restore a check for the volumebackup and volumesnapshot
and number of restores.
Fixed: BZ#2042908
Fixes #
```release-note
NONE
```

Fix hotplugs volumesnapshot was not created in vmsnapshot

---

tests/replicaset_test.go

An individual test creates at max 6 cirros VMs with 128Mb each. This is
still less than a single fedora instance requests, and we allow running
fedora based tests in parallel already.
On my machine the 16 tests need roughly 100s compared to 250s+ before.
Fixes #
```release-note
NONE
```

Run replica set tests in parallel

---

pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go
tests/vmi_configuration_test.go

We are using informers for setting limits on VMI creation.
Informers can lag behind real state. Therefore we need to
check eventual consistency of applying limits from LimitRange.
Fixes #
I have included small refactoring. Personally, I don't find the inner function declaration readable.
```release-note
None
```

Fix test LimitRange

---

OWNERS_ALIASES
pkg/network/OWNERS
tests/network/OWNERS

Update existing OWNERS file for the sig/network and add one for the pkg/network folder.
They now allow auto-labeling with `sig/network` and explicitly specify the sig/network maintainer.
Fixes #
```release-note
NONE
```

sig/network OWNERS file

---

pkg/network/setup/netstat.go
pkg/network/setup/netstat_test.go
pkg/network/vmispec/interface.go

This change aims to simplify the status update logic for network
interface.
It follows the expected logic where:
- The interface status is populated with IP data from the configuration
cache (written to during the network setup).
- Afterwards, it gets updated by the data collected from the domain
configuration.
- Lastly, it gets updated by the (optional) guest-agent data.
With the new logic in place, the SR-IOV reporting is partially fixed to
not report interfaces when the guest-agent is missing.
A full fix should come in a following change that resolves
https://github.com/kubevirt/kubevirt/issues/7050 …

network, netstat: Simplify status update

---

pkg/network/setup/network.go
pkg/network/setup/network_suite_test.go
pkg/network/setup/network_test.go
pkg/network/setup/podnic.go
pkg/network/setup/podnic_test.go
pkg/network/vmispec/interface.go

Some tiny cleanup:
- Drop the redundant interface count check
- Use LookupInterfaceByNetwork at podnic
- Drop redundant variable
Fixes #
```release-note
NONE
```

network, setup: tiny cleanup

---

CONTRIBUTING.md

Signed-off-by: Mor Cohen <mocohen@redhat.com>
There is a broken link in `CONTRIBUTING.md` file under `Additional Topics` section:
[Introducing Operators: Putting Operational Knowledge into Software](https://coreos.com/blog/introducing-operators.html) which redirects to https://cloud.redhat.com/blog and not to the article.
I found a snapshot of the article on archive.org so I updated the link. 
```release-note
NONE
```

docs: Fix a broken link in CONTRIBUTING.md

---

pkg/virt-handler/container-disk/generated_mock_mount.go
pkg/virt-handler/container-disk/mount.go
pkg/virt-handler/vm.go
tests/vmi_kernel_boot_test.go
tools/vms-generator/utils/utils.go

Currently when trying to delete a VMI that is defined with disks + external kernel boot, the VM/VMI is deleted but the virt-launcher pod is stuck on "Terminating" status.
This bug is caused since `MountKernelArtifacts()` function uses `setMountTargetRecord()` which overrides the previous mount records. Therefore these mounts aren't being unmounted causing the Pod to stuck. This PR adds a `addMountTargetRecord()` function which appends records to the existing ones, which is used now when mounting kernel artifacts.
In addition, for better robustness, now the functions to mount/unmount kernel artifacts are unexported ("private") and are used only by the main mount/unmount functions.
A new functional test is introduced to make sure this bug does not …

[Bug fix] VMI with kernel boot stuck on "Terminating" status if more disks are defined

---

pkg/virt-handler/BUILD.bazel
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

`reflect.DeepEqual` cannot be used to reliably compare k8s objects since it may return unexpected results in certain scenarios. E.g. if one of the objects contains an uninitialized slice (`== nil`) while the other has it initialized but empty (`!= nil`), `reflect.DeepEqual` will return false. However semantically the objects will be equal.
This may result in unwanted side effects like unnecessary update calls which interfere with current expectations logic. To avoid such issues semantic comparison is now used.
This is the follow-up of the https://github.com/kubevirt/kubevirt/pull/6997. The PR fixes the bug described in https://github.com/kubevirt/kubevirt/pull/6997#issuecomment-1019546079
**Which issue(s) this PR fixes** *(optional, in `fixes …

Use semantic equality comparison in VMI controller

---

pkg/virt-api/rest/profiler.go

This is a fix for a [flaky](https://github.com/kubevirt/kubevirt/blob/ca59262fb8f4b301a4535f675294388717d5dbca/tests/infra_test.go#L1569) e2e test related to cluster profiler.
Fixes #
#6787 
```release-note
NONE
```

[cluster-profiler]: fix for flaky test - do not dump data from a pod that is under deletion

---

pkg/virt-controller/watch/snapshot/source.go
tests/storage/restore.go
tests/storage/snapshot.go

The hotplugs were included in the vmsnapshotcontent
but volumesnapshot wasnt created for them since the
volumes list was taken from the vm revision and
not from the current vm volumes.
Added the vmsnapshot hotplugs test of snapshot
and restore a check for the volumebackup and volumesnapshot
and number of restores.
Fixes: BZ#2042908
This is a cherry pick of PR #7117 
Fixes #
```release-note
NONE
```

[release-0.49]  Fix hotplugs volumesnapshot was not created in vmsnapshot

---

pkg/virt-operator/kubevirt_test.go
pkg/virt-operator/resource/apply/BUILD.bazel
pkg/virt-operator/resource/apply/delete.go
pkg/virt-operator/resource/apply/delete_test.go
staging/src/kubevirt.io/api/core/v1/types.go
tests/operator_test.go

related to: https://bugzilla.redhat.com/show_bug.cgi?id=2035324 
To understand what's occurring I need to point out a few things about how the system works.
1. We register mutation/validation webhooks our CRDs which are served by virt-api
2. Update/Patch to our KubeVirt APIs fail when virt-api is unavailable due to these webhook registrations
3. virt-api will fail to initialize if not all CRDs are registered due to not being able to sync informer cache.
What we have going on in this BZ is that during teardown, virt-api re-initialized (most likely due to CDI apis being removed), and was unable to come back online due to some of our CRDs no longer being registered. Since virt-api hosts the webhooks for all our CRDs, any remaining KubeVirt CRs in the cluster that require the removal of …

Fix CRD removal race condition

---

cmd/virt-launcher/virt-launcher.go
pkg/virt-controller/services/template.go
pkg/virt-launcher/virtwrap/util/BUILD.bazel
pkg/virt-launcher/virtwrap/util/libvirt_helper.go
pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go
staging/src/kubevirt.io/api/core/v1/types.go
tests/vmi_lifecycle_test.go

This PR serves two purposes:
1) Adds a possibility to override Kubevirt's default libvirt log filters though VMI annotations. This may be helpful for both debugging, developing and production. To override defaults filters one needs to add an annotation where the key is `kubevirt.io/libvirt-log-filters` and the value is a string representing libvirt filters.
Example:
```yaml
kind: VirtualMachineInstance
metadata:
name: my-vmi
annotations:
kubevirt.io/libvirt-log-filters: "3:remote 4:event 3:util.json 3:util.object 3:util.dbus 3:util.netlink 3:node_device 3:rpc 3:access 1:*"
```
2) <del>Massively reduces log length where libvirt debug logs are turned on (environment variable `LIBVIRT_DEBUG_LOGS` is defined and equals to 1) alongside virt-launcher log …

New annotation to customize libvirt log filters + gradually increase libvirt logs according to virt-launcher logVerbosity

---

hack/prom-rule-ci/prom-rules-tests.yaml
pkg/virt-operator/resource/generate/components/prometheus.go

Updated kubevirt_vm_container_free_memory_bytes recording,
since kube_pod_container_resource_limits_memory_bytes metric was deprecated
in favor of kube_pod_container_resource_limits.
Fixes #6486
If there is no memory limit set to the VM, the recording rule kubevirt_vm_container_free_memory_bytes, will not return any result for the VM.
```release-note
Updated recording rule "kubevirt_vm_container_free_memory_bytes" 
```

Fix kubevirt_vm_container_free_memory_bytes

---

tests/libvmi/factory.go
tests/libvmi/network.go
tests/network/vmi_networking.go
tests/utils.go

When creating Alpine/Cirros based VMI/s, use `libvmi` package.
Using `libvmi` provides transparency to what is created, avoiding needless helpers which hide unneeded details.
The lack of transparency when creating VMI/s causes callers to override values which such helpers add.
Fixes #
*Code Cleanup*
```release-note
NONE
```

tests, network: Create VMI/s using libvmi (in vmi_networking)

---

tests/migration_test.go

There can be qemu proccess that is defunct or
in D state (uninterruptible sleep).
We are not counting with the latter case in our detection.
Fixes #
```release-note
NONE
```

Tests: Fix detection of incoming domain

---

tests/config.go
tests/conformance-config.json
tests/default-ceph-config.json
tests/default-config.json
tests/migration_test.go
tests/storage/datavolume.go
tests/storage/hotplug.go
tests/storage/imageupload.go
tests/storage/storage.go
tests/utils.go

This is an manual cherry-pick of #7014 
```release-note
NONE
```

[release-0.49] Improve functests usage of storage (part 3)

---

automation/perfscale-test.sh
hack/cluster-deploy.sh
hack/perfscale-tests.sh
tools/perfscale-load-generator/README.md
tools/perfscale-load-generator/examples/workload/kubevirt-density/kubevirt-density-scale.yaml
tools/perfscale-load-generator/examples/workload/kubevirt-density/kubevirt-density-warmup.yaml
tools/perfscale-load-generator/examples/workload/kubevirt-density/kubevirt-density.yaml
tools/perfscale-load-generator/examples/workload/kubevirt-density/templates/vmi-ephemeral.yaml
tools/perfscale-load-generator/flags/flags.go

Add configuration to run density scaling performance testing by varying the number of VMIs creation from 400, 600, up tp 800.
This configuration will be used for the Medium-scale performance test that will run daily on the performance cluster on our CI/CD system. This test is part of the planned performance tests being introduced to monitor performance regressions.
This PR is related to #6309
/cc @fgimenez @rmohr @davidvossel @rthallisey 
Fixes #
```release-note
None
```

[sig-scale] add script and configuration files to automate the execution of performance test in our CI/CD system

---

pkg/util/util.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
pkg/virt-controller/services/template.go
pkg/virt-handler/non-root.go
pkg/virt-handler/vm.go
tests/network/vmi_multus.go
tests/nonroot_test.go

This will enable SRIOV VMs with non-root implementation.
`/dev/vfio/vfio` is changed to `0666`
`/dev/vfio/{group}` ownership is changed to `qemu`
Fixes #
```release-note
[Nonroot] SRIOV is now available.
```

Configure VFIO for non-root & tun device

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
tests/migration_test.go

related to https://bugzilla.redhat.com/show_bug.cgi?id=2021992
With the addition of the `workload updates` api, VMIs will automatically get migrated after a kubevirt update in order to run on the latest virt-launcher pod.
This automation is eventually consistent, and will continually attempt to migrate VMIs until all "migratable" VMIs are running on new virt-launcher pods. In the even that a VMI continually fails to live migrate, the number of Migration objects will grow indefinitely as the system continually tries to move the VMI. 
To avoid allowing the finalized migrations for a VMI grow indefinitely, this PR garbage collects all but the most recent 5 migration objects. This means we continue to have a buffer of migration objects which we can use to debug issues, while not having an …

Garbage collect finalized Migration objects

---

hack/builder/Dockerfile
hack/dockerized
hack/gen-swagger-doc/build.gradle
hack/gen-swagger-doc/gen-swagger-docs.sh

In the current situation the asciidcotor tool is being used from inside
gradle, as a plugin. The repo of the plugin will go down soon.
Therefore we do the transition to call this tool directly from the builder
container. This will also reduce the dependency in a third party repo.
- I will hold the PR since these changes require a new builder to be published.
- The other Gradle plugin can also be probably used locally from inside the container,
I've decided to defer the work to a follow up PR.
```release-note
NONE
```

[builder]: embed the asciidoctor utility into the builder container

---

pkg/controller/virtinformers.go
pkg/virt-controller/watch/snapshot/BUILD.bazel
pkg/virt-controller/watch/snapshot/restore_test.go
pkg/virt-controller/watch/snapshot/snapshot_base.go
pkg/virt-controller/watch/snapshot/snapshot_test.go
pkg/virt-controller/watch/vm.go
pkg/virt-controller/watch/vm_test.go
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go
tests/storage/datavolume.go
tests/storage/snapshot.go

VM controller should make sure to trigger reconcile for DataVolumes referenced (but not owned by the VM) so that printableStatus is set/unset when DataVolume provisioning is in progress.  See bz below
VM snapshot controller should behave similarly in order to update snapshot status values
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2010908
```release-note
NONE
```

make sure to watch/trigger reconcile for DataVolumes not owned by VM

---

pkg/controller/virtinformers.go
pkg/virt-controller/watch/snapshot/BUILD.bazel
pkg/virt-controller/watch/snapshot/restore_test.go
pkg/virt-controller/watch/snapshot/snapshot_base.go
pkg/virt-controller/watch/snapshot/snapshot_test.go
pkg/virt-controller/watch/vm.go
pkg/virt-controller/watch/vm_test.go
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go
tests/storage/datavolume.go
tests/storage/snapshot.go

Manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/7104
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2010908
```release-note
NONE
```

[release-0.49] make sure to watch/trigger reconcile for DataVolumes not owned by VM

---

tests/stability_test.go

Reusage of existing helper functions makes this file awfully shorter and
clearer.
```release-note
NONE
```

stability_test: simplify

---

cmd/virt-launcher/virt-launcher.go
pkg/virt-launcher/monitor.go
pkg/virt-launcher/monitor_test.go

The shutdown callback can get pid == 0 if the monitored process is zombie and the grace period has expired:
https://github.com/kubevirt/kubevirt/blob/c793106e6eefeee585fc8f22c89ee7bb78427e2b/pkg/virt-launcher/monitor.go#L154-L164
During test run, sending SIGTERM to PID 0 (i.e. to the current process group) will interrupt the execution with an error:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6958/pull-kubevirt-unit-test/1488030763378020352
This should fix the problem with monitor tests:
```
Received interrupt.  Emitting contents of GinkgoWriter...
230
---------------------------------------------------------
231
{"component":"","level":"info","msg":"Found PID for 7fcd88f2-37cc-4bc4-bc4f-71d044c8dc49: …
```

monitor: Don't send SIGTERM to the current process group

---

tests/performance/density.go
tools/perfscale-audit/api/api.go
tools/perfscale-audit/metric-client/metric-client.go
tools/perfscale-audit/perfscale-audit.go

Programmatically determine how and when a metric query is used based on test duration and Prometheus' scrape interval in order to get the most accurate results from interpolation.
Two things I want to solve in this patch:
1. Establishing a minimum 10x relationship between range vector and `PrometheusScrapeInterval` so interpolation metrics like `increase` and `rate` get accurate results.  This [comment](https://github.com/kubevirt/kubevirt/pull/7075#issuecomment-1020242919) explains why that's important.
2. Setting the range vector to be close in duration to the perf-scale test or we risk data leaking into future tests or inaccurate results
```release-note
NONE
```

Dynamically set the range vector in perf-scale tests

---

tests/console_test.go

This PR simplifies tests/console_test.go by reusing libvmi.New* functions and by dropping three redundant tests that are unrelated to console connectivity.
```release-note
NONE
```

console_test: minor code simplifications

---

automation/test.sh
tests/console_test.go

Some migration tests were still executed on the sig-storage lane. Since they were executed in parallel there were not enough resources available. Skipping them now.
DataVolumes can take a little bit until they are fully imported.
Increase the timeout, as well as removing the custom cleanup, to collect
in our test reporter the DataVolume, in case something is wrong with the
DataVolume and the test fails.
This helps debugging issues like the one.
Fixes #
```release-note
NONE
```

Skip migration tests on sig-storage and remove DataVolume custom cleanup

---

tests/vmi_configuration_test.go

To avoid getting errors from junit-merger we make the test name for 2Gi
with guest memory configuration unique.
Fixes #
/cc @rmohr 
```release-note
NONE
```

Fix test name duplicate for hugepages tests

---

images/disks-images-provider/entrypoint.sh
tests/storage/hotplug.go

On certain OSs /tmp is tmpfs, and when the hotplug code tries to resolve the actual path on the host, it uses findmnt to do so, and if the actual path is on tmpfs it is unable to locate the real path. Now using hostpath on tmpfs is not something someone will do anyway so this commit modifies the path used from potentially a tmpfs to a real path.
This is just a test fix for certain types of hosts.
Fixes #
Note kubevirtci /tmp is a real directory not tmpfs, we specifically spotted this on an RHCOS node.
**Release …

Use /mnt instead of /tmp for hostpath hotplug test

---

tests/vmi_controller_test.go

This makes the test slightly shorter and easier to read.
```release-note
NONE
```
/cc @brybacki

vmi_controller_test: reuse libvmi.NewCirros()

---

tests/migration_test.go

fix tests ID 4747
remove redundant configuration of kubevirt CR
update vm specification
Failure logs:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6425/pull-kubevirt-e2e-k8s-1.21-sig-compute/1443322259866390528
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6182/pull-kubevirt-e2e-k8s-1.19-sig-compute/1443032079519453184
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6329/pull-kubevirt-e2e-k8s-1.20-sig-compute/1442391933665153024
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.21-sig-compute/1441523049454112768
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sig-compute/1443299 …

fix flaky tests ID 4747

---

tests/migration_test.go

Ensure on the two remaining migration cancel tests that the bandwidth is limited to 1Mi, to avoid races. Follow up of #7192 which improved the situation, but where I missed two tests.
Fixes #
@xpivarc thanks for spotting.
```release-note
NONE
```

Adjust another set  of mgiration cancel tests to limit the bandwidth

---

staging/src/kubevirt.io/client-go/go.mod

`github.com/openshift/client-go  v0.0.0` is an unknown revision and makes it impossible to get `kubevirt/client-go` package, even if it is defined in the `replace` directive.
Fixes #7196 
```release-note
NONE
```

Fix openshift/client-go version

---

hack/prom-rule-ci/prom-rules-tests.yaml
pkg/virt-operator/resource/generate/components/prometheus.go

Updated the KubevirtVmHighMemoryUsage to be calculated based on the requested memory instead of the memory limit.
This alert will help us to identify if the current requested memory that we set by default for the virt-launcher pods is enough.
We initially based it on the memory limit, but since we don't set the VM memory limit by default, it will not help us much with what we want to check.
If we see this alert fires frequently we can decide to increase the requested memory.
Fixes #
Please test this alert based …

Updated the KubevirtVmHighMemoryUsage alert

---

tests/performance/density.go
tools/perfscale-audit/api/api.go
tools/perfscale-audit/metric-client/metric-client.go

Add `ratio` and `metric` to the `InputThresold` config.  This will make the audit tool check if the `metric` is within the expected `ratio` of another metric.  For example, we expect there to be less than 2x the number of `PATCH-virtualmachineinstances-count` than the number of `CREATE-pods-count`.
The 100 VMI density test is configured with the following thresholds:
```
{
"prometheusURL": "http://127.0.0.1:9090",
"startTime": "$start",
"endTime": "$end"
"thresholdExpectations": {
"PATCH-virtualmachineinstances-count": {
"ratio": 2,
"metric": "CREATE-pods-count"
},
"UPDATE-virtualmachineinstances-count": {
"ratio": 10,
"metric": "CREATE-pods-count"
},
"vmiCreationToRunningSecondsP95": {
"value": 60
},
"vmiCreationToRunningSecondsP50": { …
```

Add thresholds for some requests counts and phase transitions

---

tests/infra_test.go

The infra test related to pporf proved to be stable. Results [here](https://search.ci.kubevirt.io/?search=ClusterProfiler&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)
https://github.com/kubevirt/kubevirt/pull/6787
```release-note
NONE
```

[e2e]: taking out quarantined infra test since its stable now

---

pkg/virtctl/imageupload/imageupload_test.go
tests/storage/imageupload.go
tests/utils.go

The archive file was reused in many tests. Tests were 
failing when multiple tests created and deleted it at the 
same time (parallel tests). Fix is easy - create a 
temporary file with random name.
Fixes #
https://github.com/kubevirt/kubevirt/issues/7203
```release-note
NONE
```

Flaky test fix - make archive file random

---

tests/mdev_configuration_allocation_test.go
tests/migration_test.go
tests/utils.go

Rename the prefix label (`mdevTestLabel1`) applied to a node during test `MediatedDevices - with mediated devices configuration - Should override default mdev configuration on a specific node`.
Using the standard prefix `tests.kubevirt.io` makes the cleanup function remove it.
Fixes #
```release-note
NONE
```

Remove leftover label applied to a node

---

tests/job.go
tests/network/expose.go
tests/network/services.go
tests/network/vmi_networking.go
tests/utils.go

Reuse `tests.RunVMIAndExpectLaunch` and `libvmi.NewCirros`, and fix a function that did two things based on a boolean argument.
```release-note
NONE
```
/cc @maiqueb @EdDev

tests: minor network expose cleanup

---

tests/utils.go

Get rid of deprecation warnings when we clean up jobs.
Fixes #
```release-note
NONE
```

[tests] Remove Job Delete Deprecation warnings

---

pkg/virt-api/rest/subresource.go
pkg/virt-api/rest/subresource_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
pkg/virt-controller/watch/vm.go
pkg/virt-controller/watch/vm_test.go
staging/src/kubevirt.io/api/core/v1/types.go
tests/vm_test.go

This PR adds a new RunStrategy to the VM api called `Once`.
The `Once` RunStrategy allows someone to declare that their VM should run exactly once to completion (a finalized phase) and should remain stopped after completion. This is similar in concept to the `RunStrategy: RerunOnFailure`, with the key difference here being that `RunStrategy: Once` will remained stopped regardless if the vmi fails or succeeds. 
These are the subresource rules when RunStrategy: Once is set
* Start - fails because it doesn't make sense. vm will automatically start the first time similar to `Always`
* Restart - fails because it invalidates the guarantee that the VMI will only run `Once`
* Stop - succeeds if VM is currently running.
**Use Case**
There are scenarios in the …

RunStrategy: Once

---

manifests/generated/operator-csv.yaml.in
pkg/virt-operator/resource/generate/components/deployments.go
staging/src/kubevirt.io/api/core/v1/types.go

https://bugzilla.redhat.com/show_bug.cgi?id=2001385
virt-operator pods should have name label like other operator pods 
among the OLM deployments within the openshift-cnv namespace.
we need this for consistency among  the OLM deployments
within the openshift-cnv namespace and for easier testing.
How to verify that other operators pods have this label:
` oc get pod -l "app.kubernetes.io/managed-by=olm" -n openshift-cnv -ojson |jq '.items[].metadata.labels'`
Fixes #
```release-note
Add a name label to virt-operator pods 
```

Add a name label to virt-operator pods 

---

tests/softreboot_test.go

Improve code readability by decommissioning a local auxiliary function `runVMI` with two boolean args and using `libvmi` constructs.
While at it, eliminate possible nil deference by ensuring `err` is non-nil before using it.
```release-note
NONE
```

softreboot_test: minor cleanup

---

pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go

Fix improper formated events like this:
```
shrank PodDisruptionBudget%!(EXTRA string=kubevirt-disruption-budget-ae8fd)
```
Fixes #
```release-note
Properly format the PDB scale event during migrations
```

Properly format PDB scaling event which is triggered during migrations

---

automation/perfscale-test.sh

The [periodic-kubevirt-performance-cluster-100-density-test](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-performance-cluster-100-density-test/1489821217111150592) is failing because when it finishes it calls `make cluster-clean`. There is no message why it failed.
This PR moves the `make cluster-clean` from the trap command in the script to run right after the test finished.
Fixes #
The `make cluster-clean` should not fail. But If it still fails in the test, we will be able to see in the logs what is failing... …

Remove make clean from trap in automation script to do not hide failures

---

tests/console_test.go

Following PR #7114, here are few more simplifications of console_test.go, which make the code easier to read and quicker to run.
```release-note
NONE
```

console_test: more simplification

---

hack/cluster-clean.sh

The CRDs may have finalizers added by virt-operator (https://github.com/kubevirt/kubevirt/pull/7064). Those need to be removed in order not to block the cleanup.
Fixes #
```release-note
NONE
```

cluster-clean: Remove finalizers from CRDs

---

tests/vm_watch_test.go

Skips the migration part in test 6870 in case of migration not being possible.
Fixes #
```release-note
NONE
```

Skip migration in test 6870 if migration is not possible

---

pkg/emptydisk/BUILD.bazel
pkg/emptydisk/emptydisk.go
pkg/host-disk/host-disk.go
pkg/host-disk/host-disk_test.go
pkg/util/util.go
pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go
tests/storage/storage.go
tests/vmi_configuration_test.go

Recent libvirt/qemu now refuse to start if any disk is not 1MiB-aligned.
This PR ensures disk image creation/resize will always produce 1MiB-aligned images by rounding the size down to the nearest 1MiB boundary.
Fixes #6712
2G (2000000000) happens to be 1k-aligned (!), so I used 1G in the test to ensure mis-alignment. (1k used to be fine, and might still be in some cases)
```release-note
New and resized disks are now always 1MiB-aligned
```

Only create 1MiB-aligned disk images

---

tests/network/BUILD.bazel
tests/network/port_forward.go

`port-forward` tests run a forward to the same local port. In serial execution, no error occurs. Since we run these tests in parallel, the `port-forward` commands overlap each other making the test execution wrong.
Now each test forward in its local port.
Fixes #
Fixes the failing sig-network lanes of [https://github.com/kubevirt/kubevirt/pull/7198](https://github.com/kubevirt/kubevirt/pull/7198)
```release-note
NONE
```

test: fix port-forward tests

---

tests/libvmi/factory.go

Cirros needs non-empty userData in order to skip 230 seconds waiting for
network cloudinit data.
Alpine, however, works just fine without it.
```release-note
NONE
```

libvmi: document why Cirros requiers userData

---

pkg/virt-launcher/virtwrap/manager_test.go

This PR fixes test setup and enforce we call the `MIgrateStartPostCopy` once
Fixes #
```release-note
NONE
```

Test: Ensure we call MigrateStartPostCopy once

---

pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
staging/src/kubevirt.io/api/core/v1/types.go

Adding this label will allow monitoring systems to correlate the `virt-launcher` pods running the VMs and the VMs themselves.
We should guarantee that if the user is not using an internal template with predefined labels, we will still ensure we have this information
/cc @sradco 
Fixes #
```release-note
Add Virtual Machine name label to virt-launcher pod
```

Add Virtual Machine name label to virt-launcher pod

---

tests/infra_test.go
tests/network/vmi_lifecycle.go
tests/network/vmi_networking.go
tests/utils.go
tests/vmi_cloudinit_test.go
tests/vmi_configuration_test.go
tests/vmi_ignition_test.go
tests/vmi_lifecycle_test.go

After waiting for a VMI to launch or schedule, return the most recently-fetched version of the VMI. The returned value is going to  shorten several tests, one of them is included as an example in this PR.
```release-note
NONE
```

test/utils: return a fresher vmi from RunVMI* and WaitFor*

---

pkg/virt-controller/watch/snapshot/snapshot_test.go
pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go
tests/storage/snapshot.go

FS thaw is idempotent but it does run the thaw
hook even though the fs was already thawed.
To prevent that we can check the fs status and incase
it is thawed dont execute the fs thaw.
Fixes #
```release-note
NONE
```

Check FSStatus before executing fs thaw

---

hack/builder/Dockerfile
hack/dockerized

periodics are failing due to outdated pr-creator instance in the builder
image:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-mirror-uploader/1498554960588050432
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/bump-kubevirt-rpms-weekly/1498305451098378240
This PR updates the pr-creator version in the builder. Updated images
have already been pushed.
Fixes #
```release-note
NONE
```

Update pr-creator in builder image

---

tests/framework/matcher/BUILD.bazel
tests/framework/matcher/getter.go
tests/framework/matcher/helper/BUILD.bazel
tests/framework/matcher/helper/reflect.go
tests/framework/matcher/owner.go
tests/framework/matcher/phase.go
tests/framework/matcher/phase_test.go

Adds `kind` and the `name` of the object (if exist) when the phase matcher fails. 
Makes it easier to spot the failing object.
Fixes [https://github.com/kubevirt/kubevirt/issues/7216](https://github.com/kubevirt/kubevirt/issues/7216)
Moved the `toUnstructured(actual interface{})` function from `owner.go` to `helper.go`
```release-note
NONE
```

e2e: enrich phase matcher

---

tests/BUILD.bazel
tests/pool_test.go
tests/utils.go

The test code is slightly clearer due to this change, as arcane implementation details are encapsulated (Cirros's requirement of coud-init userData has nothing to do with VM pools) and the signature of newPoolFromVMI() is made simpler.
```release-note
NONE
```

pool_test: simplify by using libvmi.NewCirros and tidying newPoolFromVMI up

---

tests/operator_test.go

Test passed the period of stability check, as can be seen from the [searchCI](https://search.ci.kubevirt.io/?search=test_id%3A4744&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)
```release-note
NONE
```

[e2e]: taking test_id:4744 out of quarantine

---

pkg/config/BUILD.bazel
pkg/config/sysprep.go
pkg/config/sysprep_test.go

Previously validateAutounattendPresence would ensure autounattend.xml
had to be provided along with unattend.xml. Thus blocking the usecase
where a user might want to provide *only* unattend.xml to a previously
sealed Windows guest.
This change corrects this by allowing unattend.xml to be provided
without autounattend.xml.
Fixes #7240
```release-note
Fixed a bug that prevents only a unattend.xml configmap or secret being provided as contents for a sysprep disk. (#7240, @lyarwood)
```

sysprep: Allow only unattend.xml to be provided

---

tests/monitoring/monitoring.go

This PR adds new tests cases for alert definitions. We expect to see "runbook_url" annotations in alerts and those urls must be accessible.
Signed-off-by: assaf-admi <aadmi@redhat.com>
```release-note
None
```

Add test cases for runbook URLs

---

tests/network/probes.go

This PR aims to simplify `tests/network/probes.go` by using `libvmi` to define VMIs, dropping confusing helper functions, removing non-important-yet-confusing tests, and avoiding few opaque boolean arguments. There is more to be done there: two of the `table.DescribeTable` functions are left with a complex `if-else` that is yet to be cleaned.
```release-note
NONE
```

partial cleanup of network probes tests

---

tests/dryrun_test.go

Deleting Kubevirt object is usually only allowed when no VMI and other Kubevirt objects exist. Therefore this test needs to be serial.
Fixes #
```release-note
NONE
```

Make "delete a KubeVirt CR" test Serial

---

api/openapi-spec/swagger.json
pkg/util/util.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
pkg/virt-controller/services/template_test.go
pkg/virt-controller/watch/migration.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
staging/src/kubevirt.io/client-go/api/schema_test.go
tests/migration_test.go
tests/nonroot_test.go
tests/utils.go
tests/vmipreset_test.go

This PR enables to migrate VMIs that are using root implementation of launcher to nonroot.
Fixes #
I am not sure if we should remove the annotation in case of failed/aborted migration.
```release-note
Workloads will be migrated to nonroot implementation if NonRoot feature gate is set. (Except VirtioFS)
```
/cc @davidvossel @rmohr

Enable live migration from root to nonroot

---

go.mod
go.sum
pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/kubectl_test.go
vendor/k8s.io/kubectl/LICENSE
vendor/k8s.io/kubectl/pkg/cmd/util/podcmd/BUILD.bazel
vendor/k8s.io/kubectl/pkg/cmd/util/podcmd/podcmd.go
vendor/modules.txt

Add default container annotation to virt-launcher Pod for `kubectl logs <vmi-pod>` to display logs without specifying container.
```release-note
Users now don't need to specify container for `kubectl logs <vmi-pod>` and `kubectl exec <vmi-pod>`.
```

Add default container annotation to Pod

---

tests/kubectl_test.go
tests/migration_test.go
tests/network/vmi_multus.go
tests/network/vmi_networking.go
tests/pausing_test.go
tests/storage/storage.go
tests/utils.go

The reader of `tests.RunVMIAndExpectLaunchWithIgnoreWarningArg(vmi, timeout, false)` has a tough time guessing what "false" means. Using `tests.RunVMIAndExpectLaunch()` or `tests.RunVMIAndExpectLaunchIgnoreWarnings()` directly is clearer.
```release-note
NONE
```

tests: inline RunVMIAndExpectLaunchWithIgnoreWarningArg

---

tests/container_disk_test.go

Using libvmi.NewAlpine, libvmi.NewCirros and tests.RunVMIAndExpectScheduling
makes container disk tests slightly shorter and clearer.
Simple replacement did not work right away in some of the tests, e.g test_id:1463.
I don't understand those test and their
peculiar usage of objs on top of vmis so I leave their cleanup to a
future PR.
```release-note
NONE
```

clean container_disk_test a bit

---

docs/probes.md

The cloud init `user-config` configuration is modified to start the guest
agent and create the readiness file for the probe.
As a result, the instructions to manually perform this after the VM's
boot was removed.
Must still assure this works; will update the PR in the coming days.
```release-note
NONE
```

docs, probes: simplify doc

---

hack/prom-rule-ci/prom-rules-tests.yaml
pkg/virt-operator/resource/generate/components/prometheus.go

Added a condition to KubevirtVmHighMemoryUsage
alert, to check the free memory based on container_memory_rss,
in addition to the container_memory_working_set_bytes since
there are both are considered when the scheduler checks if the container should be evicted. 
Fixes #
```release-note
NONE
```

Update KubevirtVmHighMemoryUsage alert

---

pkg/util/cluster/cluster.go
pkg/virt-controller/watch/workload-updater/workload-updater.go
pkg/virt-operator/application.go
pkg/virt-operator/util/client.go
tests/infra_test.go
tests/migration_test.go
tests/operator_test.go
tests/reporter/kubernetes.go
tests/virt_control_plane_test.go

Update some deprecated function calls. In particular:
- `EvictV1beta1()` instead of `Evict()`
- `ServerGroupsAndResources()` instead of `ServerResources()`
- `GetKubevirtClientConfig()` instead of `GetConfig()`
Fixes #
```release-note
NONE
```

Update deprecated function calls

---

pkg/virt-api/api.go
pkg/virt-api/webhooks/utils.go
pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/validating-webhook.go

Remove the VMI informers from virt-api due to the following reasons:
1. In contrast to virt-controller, virt-api only ever cares about a small subset of states on the cluster. Like the create webhook in this case only needs to know about the current VMI when the migration object is created.
2. There is no leader-election on virt-api. If virt-api scales out, then all instances have an active watcher where the apiserver has to transfer state to.
3. The VM webhook already gets a fresh state from the apiserver of the VM in question, the VMI webhook for the VMI, and so forth, so in contrast to virt-controller, we already get the main object in question "unasked" as part of the admission review.
4. We mostly care about VMIs in webhooks in cases where we …

Remove the VMI informer from virt-api

---

tests/BUILD.bazel
tests/network/BUILD.bazel
tests/network/vmi_slirp_interface.go
tests/utils.go

**What this PR does / why we need it**: Decouple the test util code with openapi generated code to avoid the kube-openapi conflict by just using the test util code.
Fixes #7272
```release-note
NONE
```

Remove the kubevirt.io/client-go/api dependency from kubevirt.io/tests

---

hack/cluster-clean.sh

Currently, in the prow performance job, the `make cluster-clean` command is failing with a timeout when deleting the kubevirt object. However, this timeout is somehow expected as there is a logic to remove finalizers right after the timeout. In fact, although there is the error, kubevirt is successfully deleted from the cluster after removing the finalizers. However, the timeout error in the [logs](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-performance-cluster-100-density-test/1498880868951789568 ) is very annoying, showing the timeout as a failure.
So this PR increases the kv delete timeout and removes the timeout from being an error in the cluster cleanup script. …

remove the annoying timeout error from being an error during cluster cleanup

---

automation/test.sh
tests/migration_test.go
tests/network/vmi_networking.go

Move the migration network test from the network tests to the migration
tests.
The migration network option is maintained and focus on the compute area
and less in the network domain. In other words, it does not test network
components, but the migration ability to use a secondary network.
Fixes #
```release-note
NONE
```

tests: Relocate migration network test

---

pkg/virt-operator/resource/apply/reconcile.go
pkg/virt-operator/resource/apply/update.go

the deployment object is already deep-copied inside the syncDeployment
function, there's no need to do it twice.
Fixes #
```release-note
NONE
```

virt-operator: remove redundant object DeepCopy

---

tests/network/vmi_networking.go

There is no need to Get another vmi update, as tests.WaitUntilVMIReady
already returns a fresh one.
```release-note
NONE
```

tests/network/vmi_networking: use WaitUntilVMIReady return value

---

hack/config-default.sh
hack/functests.sh
tests/flags/flags.go
tests/migration.go

Dedicated migration network tests currently fail on clusters nodes that use another NIC than eth1, since the value is hardcoded.
This PR makes it configurable at runtime.
Fixes #
```release-note
NONE
```

tests: make secondary NIC configurable

---

tests/network/vmi_multus.go
tests/network/vmi_networking.go

tests.BashHelloScript is an internal implementation glitch, needed to
get Cirros VMs boot faster. It should not spread to any test.
```release-note
NONE
```

tests/network: drop references to tests.BashHelloScript

---

pkg/virt-controller/watch/vm.go

Avoid return `nil` failure message like following:
```
lastProbeTime: <nil>
lastTransitionTime: 2022-03-10T03:19:06Z
message: Failure attempting to delete VMI: <nil>
reason: FailedDelete
status: True
type: Failure
```
Logs in virt-controller:
```
{"component":"virt-controller","kind":"","level":"info","msg":"Stopping VM with VMI in phase Running due to runStrategy: Halted","name":"test-stop","namespace":"default","pos":"vm.go:725","timestamp":"2022-03-10T03:19:06.757895Z","uid":"598f466b-0932-4998-b316-e93710635251"}
{"component":"virt-controller","kind":"","level":"info","msg":"Dispatching delete event for vmi default/test-stop with phase Running","name":"test-stop","namespace":"default","pos":"vm.go:991","timestamp":"2022-03-10T03:19:06.773812Z","u …
```

Avoid to return nil failure message

---

tests/storage/datavolume.go

It's unclear what fixed this test. Time-wise, the flakes stopped when
kubevirt#6936 was merged, but it didn't touch this test.
Nevertheless, it hasn't failed in over a month, so let's remove it
from quarantine.
```release-note
NONE
```

Remove fstrim tests from quarantine.

---

pkg/virt-launcher/virtwrap/BUILD.bazel
pkg/virt-launcher/virtwrap/live-migration-source.go
pkg/virt-launcher/virtwrap/manager_test.go

[Job](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7218/pull-kubevirt-e2e-k8s-1.23-sig-compute-migrations/1492080339227512832) & [kubevirtci search](https://search.ci.kubevirt.io/?search=live+migration+cancelation&maxAge=48h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job) show we have problem in migrations. 
Findings from the analysis:
1. We have not accurate logging as in [this case](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-launcher/virtwrap/cmd-server/server.go#L135). The migration might not be reported because the abort is async.
2. We don't "abort fast". [Here](https://github.com/kubevirt/kubevirt/blob/467ea8b35cc97f40226f68c18ff322b45fe65b5a/pkg/virt-lau …

Fix migration abort

---

api/openapi-spec/swagger.json
manifests/generated/kv-resource.yaml
pkg/virt-operator/BUILD.bazel
pkg/virt-operator/kubevirt.go
pkg/virt-operator/kubevirt_test.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/operator_test.go

In a resource, when `objectMeta.generation` is being incremented it means the user desire has changed
and the controller execution loop starting the reconciliation work. When the controller finishes to process the desired
state, it puts the value of `objectMeta.generation` in `status.observedGeneration`. 
We would like to achieve the same in virt-operator. 
This pattern is already being used by various controllers in kube-controller.
Currently we don't have any indication about the progress of the virt-operator sync loop. There are cases
where the operator sync process can be asynchronous, for example if one of the control-plane components is not ready
the virt-operator will wait till it be ready …

[virt-operator] Add observedGeneration to Kubevirt CR status

---

pkg/virtctl/vnc/vnc.go

- Adds feature in issue #7254
Signed-off-by: tyleraharrison <tyleraharrison@gmail.com>
**What this PR does / why we need it**: Ability to specify in the command line flags which address to listen for connections to the VNC proxy started with `virtctl vnc`
Fixes #7254
**Special notes for your reviewer**: While this does pass all of the current tests, there still need to be tests written that incorporate `--address [ipAddress]`. I have never written them before so if someone else would like to write reliable tests rather than rely on my inexperience, feel free to.
```release-note
Users are now able to specify …
```

Added ability to specify VNC proxy listening address

---

Makefile

Often when I write code I don't want to waste time on formatting it in a nice human-readable way, therefore I'm writing it in a messy way and then execute `./hack/dockerized "hack/bazel-fmt.sh"`. This PR introduces a shortcut to do that via `make format`.
This is especially helpful for things like struct definitions:
```go
type SomeStruct struct {
x string
y int
z byte
}
```
When adding an element to the struct:
```go
type SomeStruct struct {
x string
y int
z byte
variableWithLongerName bool
}
```
After `make format`:
```go
type SomeStruct struct {
x                       string
y                       int
z                       byte
variableWithLongerName  bool
}
```
Obviously, the more variables in the struct the more valuable it is to use auto …

Add `make format` to Makefile

---

tests/network/expose.go
tests/network/vmi_multus.go

The gomega-idiomatic form
```
Expect(x).To(HaveLen(n))
```
is better than
```
Expect(len(x)).To(Equal(n))
```
because when the expectation fails, the tester sees the value of x, not just its length, and has more information to debug it. In my humble opinion, reviewers and maintainers should enforce this for the benefit of future testers.
```release-note
NONE
```

tests/network: avoid Expect(len())

---

tests/utils.go

This string is used only once, inside this package. There is no reason to clutter the api and expose it.
```release-note
NONE
```

tests/utils: do not expose ApiServerCloseConnectionError

---

tests/storage/hotplug.go
tests/storage/restore.go

The gomega-idiomatic form
```
Expect(x).To(HaveLen(n))
```
is better than
```
Expect(len(x)).To(Equal(n))
```
because when the expectation fails, the tester sees the value of x, not just its length, and has more information to debug it.
```release-note
NONE
```

tests/storage: avoid Expect(len())

---

OWNERS_ALIASES

Since I've left my job at IBM, I expect to have much less time to invest in the KubeVirt project.
Therefore I feel it's better to step down from my approver role.
I hope to remain involved to some extent, as much as time permits.
And either way I definitely stick around, so feel free to tag me here or on Slack if anything relevant comes up.
```release-note
NONE
```

Move Zvi to emeritus approvers

---

tests/libvmi/cloudinit.go
tests/network/vmi_lifecycle.go
tests/network/vmi_multus.go
tests/network/vmi_networking.go

`tests.NewRandomVMIWithEphemeralDiskAndUserdata` is long and rigid relative to the alternative provided by `libvmi.WithCloudInitNoCloudUserData`. Make the required changes to stop using it in tests/network (mostly reading the return
value of tests.Wait* commands to collect a vmi object with its namespace set)
```release-note
NONE
```

tests/network: drop remaining NewRandomVMIWithEphemeralDiskAndUserdata

---

tests/libvmi/network.go
tests/network/vmi_slirp_interface.go
tests/utils.go

This PR updates the e2e tests to use libvmi to create CirrOS VMs with slirp network.
The `InterfaceDeviceWithSlirpBinding` factory function had to be
updated, allowing the interface to feature a list of exposed ports, akin
to the masquerade interface type.
Fixes #
```release-note
NONE
```

network, e2e tests: use libvmi to create CirrOS VMs with slirp network

---

staging/src/kubevirt.io/client-go/kubecli/vmi.go

This PR fixes `virtctl` so that it can be used with clusters accessed via Rancher's authentication proxy.
Here is an example kubeconfig to illustrate the problem:
```yaml
apiVersion: v1
kind: Config
clusters:
- name: "rancher-managed-cluster"
cluster:
server: "https://rancher.example.com/k8s/clusters/c-137"  # this is a cluster managed by Rancher
- name: "rancher-server"
cluster:
server: "https://rancher.example.com"  # the cluster running Rancher Server, similar URL but no path
...
```
As you can see, the URL for the `rancher-managed-cluster` contains a path component, which is valid, but uncommon so one might assume that they are never present if they have not encountered it before.
I ran `virtctl console myvmi` with a debugger until I found where …

Preserve path for cluster server endpoints (fixes virtctl with Rancher)

---

pkg/virt-controller/watch/vmi_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vmi test

---

pkg/controller/conditions_test.go

Replace occurrences of `Expect(len($VAR)).To(Equal($X))` with
`Expect($VAR).To(HaveLen($X)` which is more gomega-idiomatic and gives
better error messages when the expectation fails.
Fixes #
```release-note
NONE
```

conditions, test: replace `Expect(len(..).To(Equal(..))` with `Expect(..).To(HaveLen(..))`

---

pkg/cloud-init/cloud-init_test.go

Replace occurrences of `Expect(len($VAR)).To(Equal($X))` with
`Expect($VAR).To(HaveLen($X)` which is more gomega-idiomatic and gives
better error messages when the expectation fails.
Use the `BeEmpty()` matcher where the expected len is 0.
Fixes #
```release-note
NONE
```

cloud-init, test: replace `Expect(len(..).To(Equal(..))` with `Expect(..).To(HaveLen(..))`

---

pkg/virt-handler/cache/cache_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in cache test

---

pkg/virt-controller/watch/pool_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in pool test

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-preset-admitter_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vmi preset admitter test

---

pkg/virt-handler/device-manager/mediated_devices_types_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in mediated device types test

---

pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vmi update admitter test

---

pkg/virt-controller/services/template_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in template test

---

pkg/virt-handler/cmd-client/client_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in client test 

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vmi create admitter test

---

pkg/virt-controller/watch/vm_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vm test

---

pkg/virt-handler/container-disk/mount_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in mount test

---

pkg/virt-handler/device-manager/mediated_device_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in mediated device test

---

pkg/virt-handler/device-manager/pci_device_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in pci device test

---

pkg/virt-launcher/virtwrap/cmd-server/server_test.go
pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/manager_test.go
tests/network/vmi_slirp_interface.go

replace the wrong `Equal(nil)` matchers, with the gomega dedicated `BeNil()`, to get better readability.
```release-note
None
```

replace gomega `Equal(nil)` matchers, with `BeNil()`

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vmrestore admitter test

---

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vms admitter test

---

pkg/virt-controller/watch/snapshot/snapshot_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in snapshot test

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter_test.go

[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vmsnapshot admitter test

---

pkg/virt-controller/watch/migration_test.go
staging/src/kubevirt.io/api/migrations/v1alpha1/types.go
staging/src/kubevirt.io/api/migrations/v1alpha1/types_swagger_generated.go

In Live Migration Policies' design proposal [it says](https://github.com/kubevirt/community/blob/main/design-proposals/migration-policies.md#policies-precedence) that `It is possible that a multiple policies apply to the same VMI. In such cases, the precedence is in the same order as the bullets above (VMI labels first, then namespace labels)`.
This PR gives precedence to VMI labels over namespace labels.
```release-note
[Migration Policies]: precedence to VMI labels over Namespace labels
```

[Migration Policies]: Precedence to VMI labels over Namespace labels

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-handler/vm.go
tests/migration_test.go

In this PR https://github.com/kubevirt/kubevirt/pull/6399 that introduced Migration Policies, new fields were introduced to `VirtualMachineInstanceMigrationState` struct which is a property of the VMI status. One of those fields is named `MigrationConfiguration` which lists the actual migration configurations that were applied.
Before this PR this information was part of a VMI status only if the migration was matched to a migration policy.
After this PR this information would be part of VMI status for every migration - not only migrations that were matched to a policy.
Usually, when a VMI migrates without matching to a policy (which means the configs are taken from Kubevirt CR) the applied configurations can be found in Kubevirt CR. This is not …

Always show applied migration configuration in VMI status

---

tests/utils.go
tests/virt_control_plane_test.go

Do not only ensure that the readiness check, which tries to reach the
apiserver succeeds, but also ensure that at least the config watchers
resume their work. Due to repreated failed connects, they can have
accumulated some back-off penalty, therefore give it a bigger grace
period to resume.
Doing this gives us two things:
1. We also test that the watchers indeed reconnect
2. We ensure in the follow-up test, that config changes are updated within a reasonable amount of time
Fixes #
Fixes one of our more flaky tests …

[tests] Ensure that virt-handler watcher can reach the apiserver after outage

---

tests/migration_test.go
tests/operator_test.go
tests/performance/realtime.go
tests/pool_test.go
tests/realtime/realtime.go
tests/replicaset_test.go
tests/security_features_test.go
tests/usbredir_test.go
tests/vm_test.go
tests/vmi_configuration_test.go
tests/vmi_gpu_test.go
tests/vmi_iothreads_test.go
tests/vmi_sound_test.go
tests/vmipreset_test.go

The gomega-idiomatic form `Expect(x).To(HaveLen(n))`
is better than `Expect(len(x)).To(Equal(n))`
because when the expectation fails, the tester sees the value of x,
not just its length, and has more information to debug it.
Fixes #
```release-note
NONE
```

tests: Avoid Expect(len())

---

pkg/flavor/flavor_test.go
pkg/virt-controller/watch/replicaset_test.go
pkg/virt-controller/watch/vmi_test.go
tests/migration_test.go
tests/network/vmi_multus.go
tests/operator_test.go
tests/storage/restore.go
tests/vmi_configuration_test.go
tests/vmi_lifecycle_test.go

This PR changes `HaveLen(0)` to `BeEmpty()` in our tests' expectation for better readability and more idiomatic style.
For example, instead of `Expect(SomeSlice).To(HaveLen(0))`, replace with `Expect(SomeSlice).To(BeEmpty())`
```release-note
NONE
```

[Code Cleaning]: Change HaveLen(0) to BeEmpty()

---

pkg/virtctl/ssh/BUILD.bazel
pkg/virtctl/ssh/knownhosts.go
pkg/virtctl/ssh/knownhosts_test.go
pkg/virtctl/ssh/ssh.go

* Ensure that newlines are appended to know hosts file entries. Otherwise some tools are just adding
keys to the previous key on the same line.
* Manage known hosts file entries in a separate `~/.ssh/kubevirt_known_hosts` file, similar to `gcould compute ssh`.
* Ensure that the known_hosts file gets created if not present.
Fixes #7357
```release-note
Fix knowhosts file corruption for virtctl ssh
```

Properly manage knownhosts files

---

pkg/virt-launcher/virtwrap/device/hostdevice/sriov/BUILD.bazel
pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev_test.go

This fixes the ability to set the following fields on a list of SR-IOV NICs:
- pciAddress (as seen by the Guest)
- bootOrder
This also adds tests to check SR-IOV NICs with custom guest PCI addresses and boot order in different configurations.
There was a closure created inside a loop, which captured the iteration variable.
This caused the guest PCI address and boot order settings of the last item in the list to be applied on all other list items.
For more information about capturing the iteration variable in a closure, please see:
https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables …

virt-launcher, hostdevice: Respect SR-IOV guest pciAddress and bootOrder

---

pkg/virt-handler/hotplug-disk/findmnt_test.go
pkg/virt-handler/hotplug-disk/mount_test.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/vm_test.go

Replace occurrences of 
```
Expect(len($VAR)).To(Equal($X))
``` 
with
```
Expect($VAR).To(HaveLen($X)
``` 
which is more gomega-idiomatic and gives better error messages when the expectation fails.
Use the `BeEmpty()` matcher where the expected len is 0.
Fixes #
```release-note
NONE
```

Use HaveLen gomega matcher

---

tests/operator_test.go
tests/storage/datavolume.go
tests/template_test.go
tests/utils.go
tests/vm_test.go
tests/windows_test.go

Thanks to our recent adoption of Ginkgo2, we can now use `GinkgoT().TempDir()` instead of defining our own temp dir creation and deletion code.
~~Several of our tests create a work dir on the machine executing the functional tests for their temporary files. The directory are named kubevirt-test-* so it is clear to the machine owner what has created them.~~
~~None of the tests care about the precise name of the directory, they just need to create it. Therefore, it is cleaner to expose a function that creates the directory and hide the constant name prefix.~~
```release-note
NONE
```

tests/utils: drop public constant TempDirPrefix

---

pkg/util/hardware/hw_utils_test.go
pkg/util/lookup/lookup_test.go

Replace `Expect(len(...)).To(Equal(...))` with `Expect(...).To(HaveLen(...))` to get a better info when it fails.
N/A
N/A
```release-note
NONE
```

tests: replace To(Equal(...)) to To(HaveLen(...))

---

tests/infra_test.go
tests/launchsecurity/sev.go
tests/libvmi/factory.go
tests/migration_test.go
tests/network/primary_pod_network.go
tests/network/vmi_multus.go
tests/network/vmi_networking.go
tests/softreboot_test.go
tests/utils.go
tests/vmi_configuration_test.go

Unify several NewFedora factories
Several Fedora based factories pointed to the same underline
image, containing no differences.
Therefore, these have been unified into a single factory.
---
Remove NewSEVFedora
NewSEVFedora is being used in only one place, therefore
it seems reasonable to use the options directly at the
caller.
Generally speaking, libvmi should contain only factories
that are frequently used by the tests.
Specific usages should use options to compose the
needed VMI spec, either directly or through local helpers.
Fixes # …

tests libvmi: factory cleanup

---

tests/vmi_lifecycle_test.go

recent commit 18e6fec08f added an import of `kubevirt.io/kubevirt/tests/util` even though another one already existed.
```release-note
NONE
```

vmi_lifecycle_test: import kubevirt.io/kubevirt/tests/util only once

---

pkg/monitoring/domainstats/collector_test.go
pkg/monitoring/domainstats/downwardmetrics/hostmetrics_test.go
pkg/monitoring/vmistats/collector_test.go

Replace `Expect(len(...)).To(Equal(...))`
with `Expect(...).To(HaveLen(...))` and `Expect(...).To(BeEmpty())` to get
a better info when it fails.
N/A
N/A
```release-note
NONE
```

tests: use HaveLen(...) and BeEmpty()

---

api/openapi-spec/swagger.json
manifests/generated/kv-resource.yaml
pkg/virt-operator/resource/apply/apps.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/componentconfig.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

[This PR](https://github.com/kubevirt/kubevirt/pull/6663) introduces an option in Kubevirt CR's spec to manually determine the number of replicas for Kubevirt's core components like `virt-api`, `virt-controller`, etc.
As laid out in [this discussion](https://github.com/kubevirt/kubevirt/pull/7397#discussion_r828858282), this is problematic as it prevents us from auto-scaling the component in a smart way. As we're heading for auto-piloting and auto-scaling our component (e.g. [this PR](https://github.com/kubevirt/kubevirt/pull/7401)), this field is not recommended for use, expect for maybe advanced users that know exactly what they're doing.
```release-note
Add warning for manually determining core-component replica count in …
```

Add warning for manually determining core kubevirt infra component replica count

---

tests/io_utils.go

Some runs like:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7404/pull-kubevirt-e2e-k8s-1.23-sig-storage/1504849982212018176
Show a flake where we pass `-` to the PV as the device path:
```bash
"capacity": {
"storage": "1Gi"
},
"local": {
"path": "-"
},
```
Let's try a few times so a path that is not yet populated (like `-`) does not end up on the PV,
or, if we don't converge to a legitimate path in time, we'll fail much earlier (prior to PV creation).
Fixes #
**Release …

Attempt to fix error disk flakes by looping over path

---

hack/prom-rule-ci/prom-rules-tests.yaml
pkg/virt-operator/resource/generate/components/prometheus.go

The alert rule complains in OpenShift 4.9/4.10 (OpenShift Virtualization 4.9.3) about:
```
ts=2022-03-16T10:31:02.800Z caller=manager.go:609 level=warn
component="rule manager" group=kubevirt.rules msg="Evaluating rule
failed" rule="alert: KubeVirtComponentExceedsRequestedMemory\nexpr:
((kube_pod_container_resource_requests{container=~\"virt-controller|virt-api|virt-handler|virt-operator\",namespace=\"openshift-cnv\",resource=\"memory\"})\n
- on(pod) group_left(node)
container_memory_usage_bytes{namespace=\"openshift-cnv\"})\n  < 0\nfor:
5m\nlabels:\n  severity: warning\nannotations:\n  description: Container
{{ $labels.container }} in pod {{ $labels.pod }} memory usage\n
exceeds the memory requested\n  summary: The container is using more
memory …
```

Fix `KubeVirtComponentExceedsRequestedMemory` alert on duplicate series

---

pkg/virt-launcher/virtwrap/manager.go

Giving two names to one package increases cognitive burden.
```release-note
NONE
```

virt-launcher: import kubevirt.io/kubevirt/pkg/util only once

---

pkg/virt-operator/kubevirt_test.go
pkg/virt-operator/resource/apply/apps_test.go
pkg/virt-operator/resource/apply/core_test.go
pkg/virt-operator/resource/apply/delete_test.go
pkg/virt-operator/resource/apply/patches_test.go
pkg/virt-operator/resource/apply/prometheus_test.go
pkg/virt-operator/resource/apply/reconcile_test.go
pkg/virt-operator/util/client_test.go
pkg/watchdog/watchdog_test.go
staging/src/kubevirt.io/client-go/api/defaults_test.go
staging/src/kubevirt.io/client-go/api/types_test.go

Change all `Expect(len(var)).To(Equal(some-length))` to `Expect(var).To(HaveLen(some-length))` in pkg/virt-operator, taging/src/kubevirt.io/client-go/api and pkg/watchdog. 
If the expected length is 0, the the new matcher is `BeEmpty()`
```release-note
None
```

Code Cleanup: Improve gomega matchers in several packages

---

pkg/virt-controller/watch/workload-updater/workload-updater_test.go

replace the sleep(1)s with a proper way to detect when the VMI
informer has caught up.
Fixes #
```release-note
NONE
```

workload-updater, test: remove `time.Sleep(1)`

---

automation/release.sh

Host our `stable.txt` file at `gs://kubevirt-prow/release/kubevirt/kubevirt/` instead of `gs://kubevirt-prow/devel/release/kubevirt/kubevirt/` since it is not realted to `devel` releases.
Keep the old location too to not break scripts.
Fixes #
```release-note
Move stable.txt location to a more appropriate path
```

Fix stable.txt location

---

cmd/virt-chroot/main.go
pkg/virtctl/BUILD.bazel
pkg/virtctl/root.go
pkg/virtctl/version/BUILD.bazel
pkg/virtctl/version/version.go
pkg/virtctl/version/version_suite_test.go
pkg/virtctl/version/version_test.go
staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
staging/src/kubevirt.io/client-go/kubecli/version.go
tests/utils.go

When a `virtctl` command returns an error we check if the server and client versions are aligned: if not, show a warning message suggesting, implicitly, that a possible cause could be this difference.
This message shows also the `ClientVerison` and `ServerVersion` to highlight the difference.
The check is based on the equality of the `Major` and `Minor` values, excluding the `Patch` one.
In this way, if client and server versions differ only from the `Patch` value they are considered as aligned.
The equality check it's based on 
Fixes # …

[virtctl] Warning message for client and server versions not aligned

---

BUILD.bazel
WORKSPACE
containerimages/BUILD.bazel
examples/vmi-secureboot.yaml
tests/console/login.go
tests/containerdisk/containerdisk.go
tests/migration_test.go
tests/storage/datavolume.go
tests/utils.go
tests/vmi_configuration_test.go
tools/vms-generator/utils/utils.go

The PR introduces fedora-with-test-tooling image based on Fedora 35 (https://github.com/kubevirt/kubevirtci/pull/713). The new version supports UEFI boot (required for https://github.com/kubevirt/kubevirt/pull/6166).
Also the new image replaces microlivecd in secure boot tests.
Fixes #
Major differences in Fedora 35:
- `bash` and `libreadline` in Fedora 35 come with `bracketed-paste` mode enabled by default. This results in extra escape sequences in the console output. The mode is now explicitly disabled in `/etc/profile.d/disable-bracketed-paste.sh` for all …

tests: Use fedora-with-test-tooling based on Fedora 35

---

pkg/virtctl/ssh/native.go

If a private key is parsed and the returned err is not nil and not
ssh.PassphraseMissingError, a nil Signer would have been returned
erroneously without this change.
```release-note
None
```

virtctl/ssh: Fix missing check when parsing a private key

---

OWNERS_ALIASES

My focus at the moment has shifted to cluster-api-provider-kubevirt and I'm not able to reliably keep up with the auto-assigned review requests in kubevirt/kubevirt right now.
If you need a review, ping me directly on kubernetes slack (username: vossel).
I'll request to add myself back if my focus becomes freed up again for kubevirt/kubevirt. 
```release-note
NONE
```

Removing myself from automated review assignment

---

pkg/virt-api/webhooks/mutating-webhook/mutators/preset_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go

Change all `Expect(len(var)).To(Equal(some-length))` to `Expect(var).To(HaveLen(some-length))`
in two files under pkg/virt-api/webhooks:
* pkg/virt-api/webhooks/mutating-webhook/mutators/preset_test.go
* pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
If the expected length is 0, the the new matcher is BeEmpty()
```release-note
None
```

Code Cleanup: Improve gomega matchers in pkg/virt-api/webhooks

---

pkg/virt-config/feature-gates.go

We are going to test NonRoot extensively from now on
and therefore there is no reason to call it
Experimental. Let's rename it.
Fixes #
```release-note
Users can now enable the NonRoot feature gate instead of NonRootExperimental
```

Add NonRoot feature gate

---

pkg/virtctl/ssh/wrapped.go

Appends the `-i <identity-file-path>` when custom identity-file is specified with `--local-ssh` option for `virtctl`.
Fixes #7071
- I am still familiarizing myself with the kubervirt's flow. Please let me know, in case this change leads to an unexpected behavior. :)
```release-note
Don't ignore --identity-file when setting --local-ssh=true on `virtctl ssh`
```

append identity file with local-ssh

---

manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-operator/resource/generate/rbac/cluster.go

The admin/edit user had vmi/addvolume and vmi/removevolume but for the 'persistent' version vm/addvolume and vm/removevolume the permissions were missing.
Fixes #
```release-note
BugFix: Fixed RBAC for admin/edit user to allow virtualmachine/addvolume and removevolume. This allows for persistent disks
```

Set RBAC for VM/addvolume and VM/removevolume

---

tests/BUILD.bazel
tests/serviceaccount.go
tests/utils.go

Continue cleaning up `utils` by extracting out code to dedicated file with common logic/responsibility.
It has not yet been placed under a dedicated package due to some dependencies to the original `utils` file.
This should be resolved as `utils` is cleaned up.
Fixes #
~~Depends on #7439~~
```release-note
NONE
```

tests: Move service-account helpers to a separate file

---

tests/BUILD.bazel
tests/operator_test.go
tests/swap_test.go
tests/utils.go

For now these tests won't run on any test lane as a presubmit.
We just need to begin gaining experience with swap and have a way to validate environments.
For additional information: 
https://github.com/kubevirt/kubevirtci/pull/723
This verifies we can migrate nodes using swap both away from over commited nodes and to over committed nodes.
Fixes #
```release-note
None
```

Addition of functional tests exercising migration of VM using swap memory

---

pkg/container-disk/container-disk_test.go

Replace occurrences of `Expect(len($VAR)).To(Equal($X))` with
`Expect($VAR).To(HaveLen($X)` which is more gomega-idiomatic and gives
better error messages when the expectation fails.
Fixes #
```release-note
NONE
```

container-disk, test: replace `Expect(len(..).To(Equal(..))` with `Expect(..).To(HaveLen(..))`

---

pkg/virt-controller/services/template.go

The cluster configuration parameter is not in use in the
`getRequiredCapabilities` function.
Furthermore, inline the usage of the aforementioned function - there is
no reason to use a variable.
Fixes #
```release-note
NONE
```

Remove redundant parameter from pod template capabilities

---

pkg/virt-operator/kubevirt_test.go
pkg/virt-operator/resource/apply/BUILD.bazel
pkg/virt-operator/resource/apply/apps.go
tests/BUILD.bazel
tests/scale/BUILD.bazel
tests/scale/virt-api.go
tests/tests_suite_test.go

Today Kubevirt has severe scalability issues that are caused by the bounded number of replicas for our component.
For example, an experiment was recently made where Kubevirt was deployed over a 100 nodes cluster with 500 VMs that were created at once. Kubevirt got stuck and the main bottle-neck seemed to be virt-api. With 10 replicas everything worked like a charm. This makes sense, as today the number of replicas is hardcoded to 2, but 2 replicas is not enough for a load caused by a huge cluster.
Several alternatives were discussed in [this issue](https://github.com/kubevirt/kubevirt/issues/7101), and the conclusions are:
- **In the short term** we should be scalable. This should be achieved immediately. To achieve this we can start with a very …

Scale virt-api deployment replicas according to number of nodes

---

api/openapi-spec/swagger.json
manifests/generated/kv-resource.yaml
pkg/virt-operator/kubevirt_test.go
pkg/virt-operator/resource/apply/reconcile.go
pkg/virt-operator/resource/generate/components/validations_generated.go
pkg/virt-operator/resource/generate/install/strategy.go
pkg/virt-operator/util/config.go
pkg/virt-operator/util/config_test.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

I added field to kubevirtCR to set Prometheus ServiceMonitor object's namespace.
I added logic to remove the old monitoring components, fixed some bugs regarding the removal of old components.
I added unit test to verify that old objects are being deleted .
And refactored related functions names and if statement for better clarity.
I will update the user guide to consider the new field if that PR will be merged .
Currently we always deploy our ServiceMonitor object in Prometheus installation namespace this is not necessary.
Some projects with KubeVirt might want to deploy it in different namespace.
For instance in OpenShift-CNV Prometheus ServiceMonitor objects should be deployed in `openshift-cnv` 
namespace (kubevirt installation namespace) , it …

Add field to kubevirtCR to set Prometheus ServiceMonitor object's namespace

---

pkg/ephemeral-disk/ephemeral-disk_test.go

Replacing explicit TempDir creation makes the test shorter, and also makes it harder to forget directory cleanup.
```release-note
NONE
```

ephemeral-disk_test: shorten with GinkgoT.TempDir()

---

tests/storage/datavolume.go

The test fails sometimes on this wait time
https://search.ci.kubevirt.io/?search=expected+phase+is+%27WaitForFirstConsumer%27+but+got+%27%27&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
```release-note
NONE
```

Test flakiness - longer time wait

---

pkg/virt-operator/webhooks/BUILD.bazel
pkg/virt-operator/webhooks/kubevirt-update-admitter.go
pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go

Let's make sure we reject `LiveMigrate` as a WorkloadUpdateMethod when the `LiveMigration` feature gate is not enabled.
Fixes #
```release-note
Reject `LiveMigrate` as a workload-update strategy if the `LiveMigration` feature gate is not enabled.
```

virt-operator, webhooks: add validation for WorkloadUpdateMethods

---

pkg/virt-launcher/virtwrap/device/hostdevice/sriov/BUILD.bazel
pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev_test.go
tests/network/vmi_multus.go

This is a manual cherry-pick of #7422 and #7501.
It fixes Bugzilla [2070050](https://bugzilla.redhat.com/show_bug.cgi?id=2070050).
```release-note
Fixed setting custom guest pciAddress and bootOrder parameter(s) to a list of SR-IOV NICs.
```

[release-0.50] virt-launcher, hostdevice: Respect SR-IOV guest pciAddress and bootOrder

---

pkg/virt-launcher/virtwrap/device/hostdevice/sriov/BUILD.bazel
pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev_test.go
tests/network/vmi_multus.go

This is a manual cherry-pick of #7422 and #7501.
It fixes Bugzilla [2070050](https://bugzilla.redhat.com/show_bug.cgi?id=2070050).
```release-note
Fixed setting custom guest pciAddress and bootOrder parameter(s) to a list of SR-IOV NICs.
```

[release-0.49] virt-launcher, hostdevice: Respect SR-IOV guest pciAddress and bootOrder

---

tests/network/vmi_multus.go

This PR improves the multus e2e test readability by:
- assert the list of VMs as empty rather than the sum of the lengths of both lists should be zero
- using the `HaveLen` matcher rather than checking if the length of an array is equal to the expected number
Fixes #
```release-note
NONE
```

Better matcher usage have len be empty

---

OWNERS_ALIASES

Nominating @xpivarc as an approver. 
Community guidelines on eligibility:
https://github.com/kubevirt/community/blob/main/membership_policy.md#approver
```release-note
NONE
```

Nominate xpivarc as an approver

---

tests/mdev_configuration_allocation_test.go

Some mdev-related tests are being flaky on the vGPU lanes.
Flakefinder reports
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2022-04-11-168h.html#row43
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2022-04-11-168h.html#row42
```release-note
NONE
```

[e2e]: quarantine a few flaky mdev tests

---

tests/storage/storage.go

Following the standard protocol of waiting 14 days,
these have been green since https://github.com/kubevirt/kubevirt/pull/7455.
Fixes #
https://search.ci.kubevirt.io/?search=should+pause+VMI+on+IO+error&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
```release-note
NONE
```

Remove IO error storage tests from quarantine

---

pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
staging/src/kubevirt.io/api/core/v1/types.go
tests/vmi_lifecycle_test.go

The cluster-api-provider-kubevirt (capk) project needs a way for VMI's to be blocked from eviction, yet signal capk that eviction has been called on the VMI so the capk controller can handle tearing the VMI down.
Here's why.
When a VMI is being evicted, we need a way to have that eviction blocked so the cluster api related controllers can properly drain the k8s node running within the VMI before the VMI is torn down. We already have all the mechanisms in place in the cluster-api controllers to coordinate this, we just need a way to detect the VMI needs to go down (without actually taking the VMI down)
With `EvictionStrategy: External`, kubevirt will create a PDB for the VMI which blocks eviction, and it will also set the `vmi.Status.EvacuationNodeName` on the vmi's status. When the capk …

EvictionStrategy: "External"

---

ADOPTERS.md

Signed-off-by: Andrew Burden <aburden@redhat.com>
Minor update to correct the OKD link in the ADOPTERS.md file. 
Wasn't sure whether to link directly to the OKD Virt guide. Decided this was more permanent option (docs link could change) and splash page adds additional context for user. 
```
NONE
```

Updating OKD link in adopters file, previously linked to minikube site

---

tests/vmi_configuration_test.go

The CPU pinning test seems to have a copy-paste error since
after creating the second VMI without CPI pinning, it awaits the
first VMI to run -- but that VMI is already running.
Fixes #
```release-note
NONE
```

e2e: fix CPU pinning test

---

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

Kernel args are not supported when a custom kernel image is not provided (a QEMU limitation [1]).
Therefore, allowing it is a bug. This PR fixes this by rejecting such VMI definition.
[1] - https://qemu-project.gitlab.io/qemu/system/linuxboot.html
Also made this PR for fixing the upstream documentation: https://github.com/kubevirt/user-guide/pull/529
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2070897
```release-note
[External Kernel Boot]: Disallow kernel args without providing custom kernel
```

[External Kernel Boot]: Disallow kernel args without providing custom kernel

---

OWNERS_ALIASES

Nominate iholder-redhat as a reviewer
Community Guidelines for eligibility:
https://github.com/kubevirt/community/blob/main/membership_policy.md#reviewer
```release-note
NONE
```

Nominate iholder-redhat as reviewer

---

tests/reporter/kubernetes.go

Daemonsets can be useful for debugging functional tests, and are crucially absent from the artifacts. Adding them.
Fixes #
```release-note
NONE
```

tests reporter: log KubeVirt daemonsets

---

WORKSPACE

This updates the virtio-win image in the virtio-container-disk to version 0.1.217-1.
The current version 0.1.171 misses the `.exe` and `.msi` installers.
How to update the `storage.googleapis.com` mirror?
```release-note
Update virtio-container-disk to virtio-win version 0.1.217-1
```

Update virtio-win image to 0.1.217-1

---

pkg/virt-launcher/virtwrap/api/schema.go

The AutoPort param on Graphics struct must be all lowercase letter for
libvirt's xml, see
https://libvirt.org/formatdomain.html#graphical-framebuffers.
If use AutoPort param, it will be a bug, so fix it now before use it.
Signed-off-by: shewensheng <shewensheng@chinatelecom.cn>
Fixes #
```release-note
```

AutoPort should be all lowercase for xml

---

manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-operator/resource/generate/rbac/cluster.go

The permissions were applied to the wrong resource name, it was missing an s.
Fixes #
```release-note
NONE
```

Fix typo in permissions, was missing (s) in virtualmachines

---

cmd/virt-launcher/BUILD.bazel

When run as non-root user swtpm_setup will try to write the state under
${XDG_CONFIG_HOME} which is currently set to /var/run. The default
permissions allow only the root user to write to that directory. Create
the required layout and setup access bits during the image build.
Note: creating the empty_dirs like bellow will set the mode and owner
also for each component in the path (i.e. for /var, /var/lib, /run,
etc.):
pkg_tar(
name = "swtpm-localca-tar",
empty_dirs = [
"var/lib/swtpm-localca",
"run/var/lib/swtpm-localca",
],
mode = "0750",
owner = "107.107",
)
Fixes # …

Pre-create directories for non-root TPM state

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
tests/migration_test.go

This patch checks that the vmi.Status.MigrationState.MigrationUID
matches the migration being processed before proceeding in moving
the state of the migration from `MigrationScheduled` to
`MigrationPreparingTarget`.
The fix is needed because the `vmi.Status.MigrationState.MigrationUID`
field is updated during the target handoff (which happens in the
`MigrationScheduled` phase) and it might happen that if the migration
is re-processed immediately (because its key has been re-added in the workqueue)
after updating its `Phase` and the cluster is under moderate load, the
vmi Informer might have not caught up resulting in virt-controller
marking the migration as `Failed` because of a take-over by another
migration object even if it actually was …

virt-controller: fix false failed migrations

---

tests/network/probes.go

This PR cleans up the e2e probes test by:
- removing boolean arguments from its table
- adding some when clauses that make the tests more readable - for instance, one of the booleans was used to run more code *after* the test was executed. This literally means the "old" test is the test setup of this new, unrelated test.
- add a couple of local (un-exported) `libvmi.Option` for setting probes
It furthermore fixes a bug on the guest agent probes, since the readiness of the VMI **depends** on the availability of the guest agent. It previously was making sure the VMI status is `Ready` after the guest agent is disabled.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …

Simplify e2e probes tests remove boolean input parameters

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/vmi_configuration_test.go

This PR effectively addresses a TODO in the memory overhead calculation for virt-launcher.
It replaces an arbitrary overhead value with the observed memory usage of each process running inside virt-launcher.
A test also ensures we catch any future growth.
Fixes #
```release-note
NONE
```

virt-launcher: adjust overhead calculation for processes

---

tests/framework/checks/BUILD.bazel
tests/framework/checks/skips.go
tests/infra_test.go
tests/libnode/node.go
tests/mdev_configuration_allocation_test.go
tests/migration_test.go
tests/network/BUILD.bazel
tests/network/macvtap.go
tests/network/sriov.go
tests/network/vmi_multus.go
tests/storage/hotplug.go
tests/swap_test.go
tests/util/BUILD.bazel
tests/util/util.go
tests/utils.go
tests/virt_control_plane_test.go
tests/vm_test.go
tests/vmi_configuration_test.go
tests/vmi_iothreads_test.go
tests/vmi_lifecycle_test.go
tests/vmi_multiqueue_test.go

As part of the effort to cleanup `tests/utils.go` and better structure the e2e tests, move more helpers to `libnode`.
The first commit also includes some import aliases fixes. 
Fixes #
```release-note
NONE
```

tests: Continue moving helpers that are node related to libnode.

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go

We need to always require capabilities we set on virt-launcher
binary otherwise we encounter failure. The reason is that
process(virt-launcher) is always trying to acquire these
capabilities to effective set once we set the capabilities on binary.
Fixes #
```release-note
NONE
```

Always require capabilites which we set on binary

---

pkg/virt-api/rest/BUILD.bazel
pkg/virt-api/rest/subresource_test.go
pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-operator/resource/generate/csv/BUILD.bazel
pkg/virt-operator/resource/generate/csv/csv.go
pkg/virtctl/vm/BUILD.bazel
pkg/virtctl/vm/vm_test.go

This PR replaces raw pointers with pointers that are created by using the [pointer](https://pkg.go.dev/k8s.io/utils/pointer) library which is part of the [k8s utils repo](https://github.com/kubernetes/utils).
In general, the changes look something like this:
```go
_true := true
s := SomeStruct{
SomeBoolPtrField: &_true
}
```
After this PR:
```go
s := SomeStruct{
SomeBoolPtrField: pointer.BoolPtr(true)
}
```
The changes bring two main advantages:
1. Nicer code. Using things like `_true := true` is ugly, unclear, and adds noise to the code.
2. With `pointer` library the values are cached, so only one pointer is made for `false` and one for `true`. This also applies to integers, strings, etc. Many values are re-used all the time (e.g. …

[Code cleaning]: Replace "raw" pointers by using "pointer" library

---

docs/devel/scheduling.md

This PR removes empty `scheduling.md` doc under `docs/devel/`, which only contains a `TODO` text.
The file was introduced in [this commit](https://github.com/kubevirt/kubevirt/commit/0c8f3639b1c2a8f3cc524171997c0d35cc4bb70a) about 5.5 years ago and it is unclear what was the original intent. Some other files (e.g. `storage.md`) were introduced in this commit that were also empty except for the `TODO` text, and they don't exist anymore.
I think that after 5.5 years it's time to remove this empty doc. If this doc is needed, it should be posted by a new PR, and better be added the the [user-guide](https://kubevirt.io/user-guide/) rather then to this repo.
```release-note
NONE
```

[Code cleaning]: Delete empty scheduling doc

---

docs/devel/networking.md

Unprivileged networking does not require `NET_ADMIN` since KubeVirt
0.41.0 - [0] - featured PR [1].
Currently, the only capability required is `CAP_NET_BIND_SERVICE`.
[0] - https://kubevirt.io/2021/changelog-v0.41.0.html
[1] - https://github.com/kubevirt/kubevirt/pull/5147
Fixes #
```release-note
NONE
```

docs, network: update the required capabilities for networking

---

api/openapi-spec/swagger.json
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
pkg/virt-controller/watch/snapshot/BUILD.bazel
pkg/virt-controller/watch/snapshot/restore.go
pkg/virt-controller/watch/snapshot/restore_test.go
pkg/virt-controller/watch/snapshot/snapshot_test.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/snapshot/v1alpha1/deepcopy_generated.go
staging/src/kubevirt.io/api/snapshot/v1alpha1/types.go
staging/src/kubevirt.io/api/snapshot/v1alpha1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/flavor_test.go
tests/storage/restore.go
tests/utils.go

This PR adds support to restore a snapshot to a target VM that is different from the source VM. For exmaple, `VM 1` could take a snapshot and restore it to `VM 2` could restore from that snapshot. Before this PR such action is considered as an error.
This change is a first step towards supporting VM cloning. To have a better context, I suggest taking a look on [the design proposal](https://github.com/kubevirt/community/pull/159), and especially [this comment](https://github.com/kubevirt/community/pull/159#pullrequestreview-880329021) that summarizes up the path forward.
-------
Summary of the changes that were made:
* Possibility to restore to a VM that is different than the source VM
* Such a restore is valid **only if the target VM does not …

[VM Restore]: Support restoring to a target VM different than the source

---

cmd/virt-launcher/virt-launcher.go
pkg/virt-launcher/virtwrap/live-migration-source.go
pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go

**What this PR does / why we need it**: Now `ephemeralDiskDir` is propagated from the flag instead of constant.
```release-note
NONE
```

Propagate 'ephemeralDiskDir' from flag

---

images/disks-images-provider/entrypoint.sh

Testing on environments that are not kubevirtci, we won't have https://github.com/kubevirt/kubevirtci/blob/main/cluster-provision/k8s/1.23/k8s_provision.sh#L172-L173
done for us. Let's make sure disks-images-provider does that.
Right now this doesn't happen which results in a broken hotplug test on OpenShift environment.
Fixes #
```release-note
NONE
```

Run chcon on local storage path in disks-images-provider

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go

These checks are not reachable anymore after https://github.com/kubevirt/kubevirt/pull/4935 duplicated them
higher up in ValidateVirtualMachineInstanceSpec [1].
This change removes the checks and associated tests, existing tests
introduced by https://github.com/kubevirt/kubevirt/pull/4935 should continue to provide coverage for the use case
when ValidateVirtualMachineInstanceSpec is called.
[1] https://github.com/kubevirt/kubevirt/blob/52e6e9bdd42c3cd727ba989c3dad0dd169f8259d/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go#L121-L129
Fixes # …

vmi-create-admitter: Remove duplicate disk and volume length checks 

---

pkg/virt-controller/watch/vmi_test.go

`Expect(x).To(HaveLen(n))` has clearer failure information than
`Expect(len(x)).To(Equal(n))`.
In a few cases, it could be even better to have something like `Expect(x).To(HaveSameLenAs(y))`, but this is left as a future exercise.
```release-note
NONE
```

virt-controller/watch/vmi_test: use HaveLen matcher

---

cmd/fake-qemu-process/fake-qemu.go
cmd/virt-launcher/virt-launcher.go
pkg/virt-launcher/monitor.go
pkg/virt-launcher/monitor_test.go

We used to grep `/proc/*/cmdline` for the domain UUID to find qemu, which created issues when adding TPM, since the swtpm process also include the domain UUID.
So we switched to grepping for "uuid=<uuid>", but that string is found in the smbios option, which is not present on ARM, so ARM testing is currently broken.
This PR tries to end this once and for all by reading the PID file created for qemu under `/run`.
Fixes #7067 
Fixes (hopefully) ARM test suite
```release-note
NONE
```

virt-launcher monitor: read the qemu pid file instead of grepping /proc

---

tests/kubectl_test.go

`Expect(result).ToNot(BeEmpty())` would fail more meaningfully
```release-note
NONE
```

kubectl_test: use more meaningful expecter

---

pkg/virt-handler/device-manager/mediated_device_test.go
pkg/virt-handler/device-manager/pci_device_test.go

HaveLen and BeEmpty expecters make failures more readable.
```release-note
NONE
```

virt-handler/device-manager tests: use HaveLen and BeEmpty

---

tests/utils.go

This is a re-open of https://github.com/kubevirt/kubevirt/pull/7222
The PR cleans up a bunch of things in tests/utils.go, like:
- Variables named after imports / builtins
- Unused parameters
- Redundant parentheses / casts
- Capitalized error strings and incomplete function comment
- Empty slice declarations using literals (`x := []Type{}`)
- Non-explicit function return ignoring
Fixes #
```release-note
NONE
```

test utils: address various code smells

---

pkg/virt-launcher/virtwrap/live-migration-source.go
pkg/virt-launcher/virtwrap/manager_test.go

This PR prints the migration progress timeout logs in actual seconds instead of nanoseconds.
It also swtiches to always updating m.progressWatermark, in case m.lastProgressUpdate goes up
Fixes #
```release-note
NONE
```

Show migration progress timeout in actual seconds

---

pkg/virt-operator/resource/apply/core_test.go

fix the 'should patch if ClusterIp == \"\" during update' unit test in
/pkg/virt-operator/resource/apply/core_test.go
The test compared a slice to an empty string (""), expecting them to be
not equal. This condition will always be true and so the test allways
passed, regardless the content of the slice.
This PR fixes the test by expecting the slice to be empty.
The PR also fixes the style of the test description and the also test
description of the following test, to remove the `\"\"`, replace them by
more readable version.
Fixes # …

Fix a wrong unit test

---

tests/libvmi/network.go

Use constant `DefaultInterfaceName` that is already defined, instead of "default" literal
for default masquerade interface factory.
Fixes #
```release-note
NONE
```

tests: Use DefaultInterfaceName const instead of "default" literal

---

pkg/virt-handler/rest/lifecycle.go

**What this PR does / why we need it**: Refactor the VMI lifecycle handler to remove repetitious code dealing with querying the VMI instance and VMI launcher client from the VMI cache
```release-note
NONE
```

Refactor VMI lifecycle handler

---

tests/network/vmi_networking.go

Conformance migration test with emulation fix
Due to https://github.com/kubevirt/kubevirt/issues/6885, network conformance tests fail on environments using emulation.
The failure is caused by VM reboot that is performed as part of migration test flow.
The role of VM reboot in migration test is to rerun DHCP client initialization process and to validate network connection after the migration is completed.
To resolve this issue, VM reboot has been replaced with DHCP client explicit restart which is sufficient to initiate DHCP request to reset VM's IP 
Signed-off-by: Diana Teplits <dteplits@redhat.com>
Fixes #
https://github.com/kubevirt/kubevirt/issues/7299
``` …
```

tests, network: Conformance migration test with emulation fix

---

pkg/virt-launcher/virtwrap/converter/converter.go

Device isa-debugcon does not support on Arm64,
and no good alternative device found, so just
disable it on Arm64.
Signed-off-by: Howard Zhang <howard.zhang@arm.com>
Fixes #7650
```release-note
NONE
```

virt-launcher: disable isa-debugcon on Arm64

---

tests/migration_test.go

Quarantining due to high flakiness, can be seen here:
https://search.ci.kubevirt.io/?search=tests%2Fmigration_test.go%3A2059&maxAge=336h&context=1&type=all&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2022-05-02-168h.html
Signed-off-by: borod108 <boris.od@gmail.com>

Quarantine test_id:8482 due to flakiness

---

manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-operator/resource/generate/rbac/cluster.go
pkg/virt-operator/resource/generate/rbac/operator.go
tests/access_test.go

Fix RBAC permission for the `virtualmachineinstances/portforward` subresource. 
With the current version I get the following permission error as regular user:
`
can't access VMI vm-test: [virtualmachineinstances.subresources.kubevirt.io](http://virtualmachineinstances.subresources.kubevirt.io/) "vm-test" is forbidden: User <my-user> cannot get resource "virtualmachineinstances/portforward" in API group "[subresources.kubevirt.io](http://subresources.kubevirt.io/)" in the namespace "test"
`
```release-note
NONE
```

fix rbac for virtualmachineinstances/portforward

---

tests/access_test.go

We need to have the test names unique, otherwise the junit-merger
complains when they are run in parallel (which is always done in CI).
Unfortunately the issue with the touched test names can only be reproduced
with an OKD/OpenShift cluster, as they are specific to these environments.
That is also the reason why these tests never
failed upstream, since they are not run on vanilla k8s.
Fixes #
```release-note
NONE
```

Make names of access tests around test_id:2921 unique

---

pkg/virt-launcher/virtwrap/live-migration-source.go
pkg/virt-launcher/virtwrap/manager_test.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/7654
```release-note
NONE
```

[release-0.41] Show migration progress timeout in actual seconds

---

pkg/virt-launcher/virtwrap/live-migration-source.go
pkg/virt-launcher/virtwrap/manager_test.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/7654
```release-note
NONE
```

[release-0.49] Show migration progress timeout in actual seconds

---

tests/operator_test.go

use ProductComponent instead of hardcoded kubevirt value in test_id:8235
Fixes [7663](https://github.com/kubevirt/kubevirt/issues/7663)
```
NONE
```

use ProductComponent instead of hardcoded kubevirt value in test_id:8235

---

cmd/virt-handler/virt-handler.go
pkg/virt-handler/BUILD.bazel
pkg/virt-handler/node-labeller/cpu_plugin.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/node-labeller/model.go
pkg/virt-handler/node-labeller/node_labeller.go
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

Signed-off-by: Andrey Odarenko <andreyo@il.ibm.com>
virt-handler VirtualMachineController performs GET Node API calls when trying to access its associated Node object labels to detect the host CPU model.
This PR will remove direct API calls by using NodeLabeller field which indicates that the host CPU model was successfully detected.
Reducing direct API calls should improve the system performance and scalability.
For reference: https://github.com/kubevirt/kubevirt/pull/7236
```release-note
NONE
```

Remove Get Nodes API calls

---

ADOPTERS.md

**What this PR does / why we need it**: We are [puzl.ee](https://puzl.ee), a cloud-native computing provider and a new adopter of Kubevirt, so we're extending the Kubevirt adopters list. On Puzl, people can run Kubevirt based cloud VMs using native k8s API or dashboard with per-second billing.
**Special notes for your reviewer**: Would be cool if you also add us to kubevirt.io website. Please find our logo here  https://static-cdn.puzl.ee/master/static/images/branding/logo__w-text__512.png
```release-note
NONE
```

Add puzl.ee to adopters

---

pkg/virt-controller/watch/migration.go
tests/migration_test.go

Launcher in versions v0.43-v0.51 recognizes VMI as nonroot
if kubevirt.io/nonroot annotation is present. Therefore
we need to mark the VMI with this annotation upon migration
to be able to seamlessly update from these versions.
Fixes #
Updates of the launcher with a version lower than v0.43 are not possible.
```release-note
NONE
```

Fix root to nonroot migration

---

pkg/virt-launcher/virtwrap/live-migration-source.go
pkg/virt-launcher/virtwrap/manager_test.go

'DataRemainingSet' should be set to 'true' when 'DataRemaining' field
contains some meaningful value. This is checked in the live migration
processing code. The behaviour needs to be replicated in tests as well.
Fixes #
The checking of `DataRemainingSet` was introduced in https://github.com/kubevirt/kubevirt/pull/7654:
https://github.com/kubevirt/kubevirt/blob/3703b66c94ebac5558a4d22e50c90a0520bdec26/pkg/virt-launcher/virtwrap/live-migration-source.go#L850-L852
Since then I noticed that the unit tests in `pkg/virt-launcher/virtwrap/manager_test.go` were …

Initialize properly libvirt.DomainJobInfo struct

---

cmd/subresource-access-test/subresource-access-test.go
manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-api/api.go
pkg/virt-operator/resource/generate/rbac/cluster.go
pkg/virtctl/guestfs/guestfs.go
pkg/virtctl/guestfs/guestfs_test.go
staging/src/kubevirt.io/client-go/kubecli/guestfs.go
tests/subresource_api_test.go

- Handle a case where we were discarding a possible image name prefix in virtctl guestfs
- Grant unprivileged user access to the /guestfs endpoint (otherwise virtctl can't infer image url)
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2068905
```release-note
BugFix: virtctl guestfs incorrectly assumes image name
```

Handle virtctl guestfs incorrectly assuming image name, grant access to /guestfs endpoint

---

tests/reporter/kubernetes.go

Maintenance of the k8s reporter:
1. Remove deprecated dumping of sriov operator that we don't use upstream anymore.
2. Remove virt-launcher lspci dumping because we don't have the binary anymore.
3. Update `ls /dev/vfio` commands to not fail due to splitting by spaces.
Fixes #
Fixes the errors written on https://github.com/kubevirt/kubevirt/issues/7170 description
```release-note
None
```

k8s reporter: Remove deprecated parts

---

tests/reporter/kubernetes.go

The console is not available when a VMI is in paused state and any attempt to connect blocks the exection for a ~2min timeout. Instead of waiting just skip paused VMIs when dumping the logs.
Fixes #
Not sure if it makes sense to unpause and then log it instead. Anyway currently no logs are dumped for a paused VMI so this PR does not change the behaviour.
```release-note
NONE
```

tests: Don't try to log a paused VMI

---

cmd/virt-launcher/BUILD.bazel
pkg/virt-controller/services/template.go
pkg/virt-launcher/virtwrap/util/libvirt_helper.go

Some processes require adding files to the root of XDG_CACHE_HOME/XDG_CONFIG_HOME.
We currently just use /var/run and assume the container user can write to it.
/var/run/kubevirt-private is a better place for that, since it is managed by k8s.
Fixes #
```release-note
NONE
```

non-root: use /var/run/kubevirt-private for cache and config files

---

tests/operator_test.go

Recently we upgraded cirros and alpine images to
new versions. These versions need more memory to
boot. Therefore we are doubling the memory from
64MiB to 128MiB.
Fixes #
```release-note
NONE
```

Increase memory in upgrade test

---

cmd/subresource-access-test/subresource-access-test.go
manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-api/api.go
pkg/virt-operator/resource/generate/rbac/cluster.go
pkg/virtctl/guestfs/guestfs.go
pkg/virtctl/guestfs/guestfs_test.go
staging/src/kubevirt.io/client-go/kubecli/guestfs.go
tests/subresource_api_test.go

- Handle a case where we were discarding a possible image name prefix in virtctl guestfs
- Grant unprivileged user access to the /guestfs endpoint (otherwise virtctl can't infer image url)
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2068905
```release-note
BugFix: virtctl guestfs incorrectly assumes image name
```

[release-0.44] Manual backport of 7592

---

cmd/subresource-access-test/subresource-access-test.go
manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-api/api.go
pkg/virt-operator/resource/generate/rbac/cluster.go
pkg/virtctl/guestfs/guestfs.go
pkg/virtctl/guestfs/guestfs_test.go
staging/src/kubevirt.io/client-go/kubecli/guestfs.go
tests/subresource_api_test.go

- Handle a case where we were discarding a possible image name prefix in virtctl guestfs
- Grant unprivileged user access to the /guestfs endpoint (otherwise virtctl can't infer image url)
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2083594
```release-note
BugFix: virtctl guestfs incorrectly assumes image name
```

[release-0.49] Manual backport of 7592

---

pkg/virt-launcher/virtwrap/live-migration-source.go
pkg/virt-launcher/virtwrap/manager_test.go

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/7654
```release-note
NONE
```

[release-0.44] Show migration progress timeout in actual seconds

---

pkg/util/nodes/BUILD.bazel
pkg/util/nodes/nodes.go
pkg/virt-controller/watch/topology/BUILD.bazel
pkg/virt-controller/watch/topology/nodetopologyupdater.go
tests/libnode/BUILD.bazel
tests/libnode/node.go
tests/migration_test.go

This PR aims to stabilize CI by making `disableNodeLabeller()` less flaky by using a patch instead of an update.
For more info, please have a look here: https://github.com/kubevirt/kubevirt/issues/7703.
```release-note
NONE
```

[CI Stabilization]: disableNodeLabeller() - use patch instead of update

---

automation/perfscale-test.sh
hack/perfscale-tests.sh

The [performance tests](https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-performance-cluster-scale-density-test&width=20) are failing after the introduction of the PR #7265.
The PR changed the`perfscale-load-generator` removing docker image parameters, but the `hack/perfscale-tests.sh` was not updated.
This PR is removing the deprecated parameter used in `hack/perfscale-tests.sh`
Fixes #
```release-note
NONE
```

fix perf test removing a deprecated parameter

---

hack/prom-rule-ci/prom-rules-tests.yaml
hack/prom-rule-ci/verify-rules.sh
pkg/virt-operator/resource/generate/components/prometheus.go

The admin can edit deployment and cause the virt-controller/operator to not be ready.
As a consequence, NoReady* alerts would not fire. This PR fixes this case.
Fixes #https://bugzilla.redhat.com/show_bug.cgi?id=2036676
I have packaged multiple fixes into this PR. I will try to ping relevant people for reviews.
```release-note
NoReadyVirtController and NoReadyVirtOperator should be properly fired.
```

NoReadyVirtController and NoReadyVirtOperator are never triggered 

---

hack/builder/Dockerfile
hack/builder/build.sh

This reduces the number of packages included in the builder image and cleans up a few additional bits. The size goes from 2.19GB to 1.96GB, which is a solid 10% reduction. Some tweaks and cleanups not related to image size are also included.
I have used the updated builder image to build KubeVirt locally without running into any issues, so I'm fairly confident the packages that are no longer being included in the image were not really needed. It'd be great to have that conclusion double checked though :)
```release-note
NONE
```

builder: Clean up and reduce in size

---

tests/kubectl_test.go

libvmi.NewCirros is preferable over the long tests.NewRandomVMIWithEphemeralDisk().
```release-note
NONE
```

kubectl_test: use the more succinct libvmi.NewCirros

---

tests/migration_test.go

**What this PR does / why we need it**: This MR changes usage of `reflect.DeepEqual` to standard `gomega.Equal` function to simplify the code.
```release-note
NONE
```

Use gomega.Equal instead of reflect.DeepEqual

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-handler/node-labeller/cpu_plugin.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
tests/migration_test.go
tests/utils.go

1) Vmi can't migrate back to older nodes (only to nodes with the same or more features than the current one) with host-model cpu
2) vmi with host-model can't migrate if the target node does't have the same host model even if the target node support the host-model of the source node and has all the required features.
For instance:
- if vmi start with hosmodel-cpu in node01 that doesn't have feature A and than migrate to node02 that has feature A we won't be able to migrate back to node01 because in the case virt-launcher will be schedule with nodeSelector for feature A even due it
can run on …

Adding and fixing support for host-model migration in heterogeneous cluster

---

tests/network/BUILD.bazel
tests/network/mac.go
tests/network/macvtap.go
tests/network/sriov.go
tests/network/vmi_multus.go
tests/utils.go

Let's make tests/utils.go shorter.
```release-note
NONE
```

tests: move GenerateRandomMac into the network package

---

pkg/virt-launcher/virtwrap/cli/libvirt.go

The PR fixes a double-free error.
Do not call Free() in the main function body. GetDomainStats already registers a defered routine to cleanup the domains.
Fixes #
I already have a PR addressing `Free()` calls in `virtwrap/manager` tests: https://github.com/kubevirt/kubevirt/pull/7700. This definitely needs to be covered by a unit-test so will try to add one there. Meanwhile submitting the fix.
```release-note
NONE
```

Fix double free of VirDomain object

---

automation/test.sh
hack/common.sh
hack/functests.sh
manifests/generated/operator-csv.yaml.in
pkg/virt-operator/resource/generate/components/daemonsets.go
pkg/virt-operator/resource/generate/components/deployments.go
tests/canary_upgrade_test.go
tests/flags/flags.go
tests/framework/checks/checks.go
tests/framework/checks/skips.go
tests/infra_test.go
tests/kubectl_test.go
tests/operator_test.go
tests/swap_test.go

- Test 4642 ensure another replica of virt-controller will take over if the leader dies. That obviously won't work in single-replica, added a skip.
- The kubectl test that runs a migration should be skipped when migrations are not possible
- Test 6256 uses the virt-controller PDB, which doesn't exist on single-replica deployments. Added a skip.
- Both swap tests do migrations, they should be skipped when migration is not possible
- The `Command` for virt-handler containers include args. Those should be moved to `Args`.
- Test 6308 can cause a crash loop since it removes all environment variables on virt-handler containers. It should append its env var instead.
- The operator update (KubeVirt upgrade) tests create VMs and expect them to migrate. Such …

Fix/Skip tests that are incompatible with single-replica environments

---

tests/testsuite/namespace.go

Currently if namespace creation returns AlreadyExist error then
test failure is skipped. Since this can cause scenarios where an
existing namespace has leftovers that can affect later tests,
Failing namespace creation on any non-nil error.
This issue was observed while examining [test-kubevirt-cnv-4.11-network-ocs](https://main-jenkins-csb-cnvqe.apps.ocp-c1.prod.psi.redhat.com/job/test-kubevirt-cnv-4.11-network-ocs/98/consoleFull) pipeline failing on namespaces still lingering from prior pipelines. As this PR won't solve the issue causing the namespace to delay deletion, we should fail the test in the first place it is observed, hence this PR
```release-note
NONE
```

test, Fail on namespace creation failure

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/vmi_configuration_test.go

On some environments, libvirtd was seen using more than 16Mi of memory, bumping by 1Mi.
Adding the memory usage of every process on functest failure will help updating these values in the future without having to run the test multiple times.
Fixes #
```release-note
NONE
```

virt-launcher overhead: bump virtlogd and add logs to functest

---

examples/vm-cirros-sata.yaml
examples/vm-template-windows2012r2.yaml
examples/vmi-sata.yaml
examples/vmi-windows.yaml
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
tests/vmi_configuration_test.go
tests/vmidefaults_test.go
tools/vms-generator/utils/utils.go
tools/vms-generator/vms-generator.go

At present users must always define and associate a disk or filesystem with a volume within the VirtualMachineInstanceSpec of a VirtualMachine.  This PR removes this requirement and introduces some basic logic to add a `Disk` for any `Volumes` not associated with a `Disk` or `Filesystem` when generating the `VirtualMachineInstance` at runtime.
Fixes #
```release-note
The requirement to define a `Disk` or `Filesystem` for each `Volume` associated with a `VirtualMachine` has been removed. Any `Volumes` without a `Disk` or `Filesystem` defined …
```

Remove VirtualMachineInstance volume disk or filesystem requirement

---

manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-operator/resource/generate/rbac/cluster.go

Add `virtualmachines/migrate` resource to edit and admin clusterrole.
Edit and admin users are able to create a virtualmachineinstacemigration
posting a CR, but was not authorized using `virtctl migrate <vm-name>``
returning the error:
```
User <name> cannot update resource "virtualmachines/migrate"
in API group "subresources.kubevirt.io" in the namespace <namespace>
```
This happens because edit and admin user was not granted to make requests
to the subresource "virtualmachines/migrate" of "subresources.kubevirt.io"
Fixes #
```release-note …
```

Allow edit/admin user to create migration via virtctl

---

automation/perfscale-test.sh

The Periodic density test expects the user to create the test namespace.
```
{"component":"","level":"info","msg":"Running Load Generator","pos":"load-generator.go:36","timestamp":"2022-05-17T16:19:06.872610Z"}
{"component":"","level":"info","msg":"Burst Load Generator CreateWorkload","pos":"burst.go:71","timestamp":"2022-05-17T16:19:06.880683Z"}
{"component":"","level":"info","msg":"Replica 1 of 400","pos":"burst.go:83","timestamp":"2022-05-17T16:19:06.880727Z"}
{"component":"","level":"error","msg":"error creating obj VirtualMachineInstance: namespaces \"kubevirt-density\" not found","pos":"utils.go:41","timestamp":"2022-05-17T16:19:07.035660Z"}
{"component":"","level":"info","msg":"Replica 2 of …
```

Create and delete the kubevirt-density namespace

---

tests/libnet/cloudinit.go

When using slices, there is no need to initialize it before performing an append operation.
Fixes #
```release-note
NONE
```

tests, libnet, cloudinit: Drop redundant slice init

---

pkg/virt-handler/BUILD.bazel
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

Includes the reason why a VM is not live migratable to event. User is now able to now able to see a particular problem (e.g. "EvictionStrategy is set but vmi is not migratable (cannot migrate VMI which does not use masquerade to connect to the pod network)")
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2052466
```release-note
Adds the reason of a live-migration failure to a recorded event in case EvictionStrategy is set but live-migration is blocked due to its limitations.
```

Add more descriptive message for failure during live-migration

---

tests/migration_test.go

Using stress to delay migration showed to be not reliable.
We have often seen that stress fails because it doesn't
have enough memory available. Limiting bandwidth seems to
work just fine.
This commit also reduces the memory consumption to 400(from 800)
which showed to be enough.
Fixes #
```release-note
NONE
```

[release-0.41]Post copy 4747 fix

---

pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/rendercontainer.go
pkg/virt-controller/services/rendercontainer_test.go
pkg/virt-controller/services/template.go

This PR refactors the virt-controller templating service. It is barely understandable. 
It focuses explicitly in generating the specification of containers. It replaces the ad-hoc generation of containers in the `virt-launcher` pod by using a builder pattern, allowing the customization of the spec via options. It is working for the following containers:
- compute
- sidecars
- init container
Follow up PRs will re-use this approach for the following resources:
- env vars
- volumes
- resources (this one will be tricky ... that code is all over the place)
- compute container command
- ...
Fixes # …

Refactor virt controller template machine container spec

---

pkg/virt-launcher/virtwrap/converter/converter.go

**What this PR does / why we need it**: `HostDeviceList` is unused anywhere and should be removed. This is something that I've noticed during refactor in https://github.com/kubevirt/kubevirt/pull/7786
```release-note
NONE
```

Remove unused `HostDeviceList` struct

---

tests/storage/storage.go

Quarantine two flaky tests:
* [\[sig-storage\] Storage Starting a VirtualMachineInstance with error disk should pause VMI on IO error](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2022-05-23-168h.html#row11) 
* [\[sig-storage\] Storage Starting a VirtualMachineInstance with faulty disk should pause VMI on IO error](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2022-05-23-168h.html#row12)
Fixes #
/cc @brybacki @xpivarc 
```release-note
NONE
```

Quarantine flaky VMI pause tests

---

pkg/virt-launcher/virtwrap/api/schema.go

**What this PR does / why we need it**: This MR fixes incorrect/nonexistent `emitempty` tag with `omitempty`. It looks like a simple typo.
```release-note
Empty (`nil` values) of `Address` and `Driver` fields in XML will be omitted.
```

Fix incorrect `emitempty` tag with `omitempty`

---

tests/infra_test.go

We need more information about remote command execution failures in infra tests
therefore we will print the stdout and stderr in case the assertion fails.
```release-note
NONE
```

[e2e]: provide more information upon failure in executing commands in pods

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-handler/node-labeller/cpu_plugin.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/node-labeller/node_labeller.go
staging/src/kubevirt.io/api/core/v1/types.go
tests/infra_test.go
tests/migration_test.go
tests/utils.go

Currently we threat host-model of a node as a supported cpuModel
because the node contains: `cpu-model.node.kubevirt.io/<host-model-name>: "true"` label
in order to run host-model libvirt has to disable some features that the node doesn't have
and if we define the cpuModels to be `<host-model-name>` of some node the vmi will fail.
In this case virt-launcher shouldn't had been scheduled at all because the node doesn't support all the 
<host-model-name> features.
In order to fix this we can define new set of labels (`migration-cpu-model.node.kubevirt.io/<model-name>`) just for migrations with   host-model because in migration we need selector that will allow us to migrate to one of the following:
- target node with the same host-model and all the …

The host-model cpuModel isn't usually fully supported in the nodes and we should take it into account

---

pkg/virt-launcher/virtwrap/manager.go

**What this PR does / why we need it**: We are using `.Reason(err)` which could not be set and even if it's set it's not relevant to this part of the code.
```release-note
NONE
```

Remove incorrect reason when logging

---

pkg/virt-launcher/virtwrap/device/hostdevice/generic/addresspool.go

**What this PR does / why we need it**: This MR fixes a typo `devises` -> `devices`.
```release-note
NONE
```

Rename `devises` to `devices`

---

tests/migration_test.go
tests/utils.go

Move LibvirtDomainIsPersistent from utils to
migration_test to make utils shorter.
Signed-off-by: Ben Oukhanov <boukhanov@redhat.com>
We had [here](https://github.com/kubevirt/kubevirt/pull/7810/files#diff-847cd06c1bf6ef597ea96894f8b32ecb4d074ad1bc785b39871e11fb6ab71b3dL2201):
```
vmiPod, err := getRunningPodByVirtualMachineInstance(vmi, util2.NamespaceTestDefault)
if err != nil {
return false, err
}
```
Now we're using `GetRunningPodByVirtualMachineInstance` and have `util2.PanicOnError(err)` [there](https://github.com/benukhanov/kubevirt/blob/19e78a2ec267db569acf8c1e662a52332df8d6a1/tests/utils.go#L845).
```release-note
NONE
```

test: move LibvirtDomainIsPersistent from utils

---

OWNERS_ALIASES

@alonSadan is not longer an active participant in the project for 1.5 years now.
Removing him from the network-reviewers list so he will no longer be
assigned as reviewer by the bot.
Fixes #
```release-note
NONE
```

OWNERS, network-reviewers: Remove inactive member

---

Makefile

It is very tempting to add code to tests/utils.go, even though it is
already too long to read. Let us try to avoid further growth of this
file by adding this lint target.
This simple/stupid validation is intended to start the discussion. It
should probably be replaced by a test of the specific diff from
origin/master. Or even better: be replaced by a proper go linter that
can guide us about the quality of the code we write.
This suggested target should be exercisable locally and via a job such as the one proposed by https://github.com/kubevirt/project-infra/pull/2124 
```release-note
NONE
```

Makefile: add a lint target

---

hack/prom-rule-ci/prom-rules-tests.yaml
pkg/monitoring/vmistats/collector.go
pkg/virt-handler/cmd-client/client.go
pkg/virt-handler/vm.go
pkg/virt-operator/resource/generate/components/prometheus.go

If a VMI has been successfully migrated more than 12 times over a period of 24 hours, which is considerably higher than normal operation including an upgrade, an alert with a severity of `warning` is being fired.
Also, fixing some typos.
Signed-off-by: orenc1 <ocohen@redhat.com>
Excessive number of migrations on a single VMI over a period of time can suggest issues related to cluster configuration or available resources. Firing an alert if excessive migrations have been found on a VMI.
Fixes #
```release-note
new alert for excessive number …
```

Add an alert for excessive migrations on a VMI

---

pkg/virt-controller/watch/snapshot/snapshot_test.go

There was an issue with the volume snapshot class sometimes taking time to be added.
Fixed by adding in the relevant tests a waiter to check the add had occured.
Ran all the snapshot UT for more then 200 times and no flakiness with this fix.
This solves at lease this 2 issues: 
https://github.com/kubevirt/kubevirt/issues/7776
https://github.com/kubevirt/kubevirt/issues/7647
```release-note
NONE
```

Fix vmsnapshot unittests flakiness

---

pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
pkg/virt-launcher/virtwrap/agent-poller/agent_parser_test.go
pkg/virt-launcher/virtwrap/api/schema_test.go
pkg/virt-launcher/virtwrap/cli/libvirt_test.go
pkg/virt-launcher/virtwrap/cmd-server/server_test.go
pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/converter/vcpu/numa_placement_test.go
pkg/virt-launcher/virtwrap/converter/vcpu/vcpu_test.go
pkg/virt-launcher/virtwrap/device/hostdevice/generic/hostdev_test.go
pkg/virt-launcher/virtwrap/device/hostdevice/gpu/hostdev_test.go
pkg/virt-launcher/virtwrap/device/hostdevice/hotplug_test.go
pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev_test.go
pkg/virt-launcher/virtwrap/efi/efi_test.go
pkg/virt-launcher/virtwrap/manager_test.go
pkg/virt-launcher/virtwrap/statsconv/converter_test.go
pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go

Improves matching for errors, length, and substrings.
```release-note
None
```

Code cleanup: Improve gomega matchers in `pkg/virt-launcher/virtwrap`

---

pkg/virt-handler/device-manager/BUILD.bazel
pkg/virt-handler/device-manager/mediated_device.go
pkg/virt-handler/device-manager/pci_device.go
pkg/virt-handler/vm_test.go
pkg/virt-launcher/virtwrap/device/hostdevice/generic/addresspool.go
pkg/virt-launcher/virtwrap/device/hostdevice/generic/addresspool_test.go
pkg/virt-launcher/virtwrap/device/hostdevice/gpu/addresspool.go
pkg/virt-launcher/virtwrap/device/hostdevice/gpu/addresspool_test.go
pkg/virt-launcher/virtwrap/manager.go
staging/src/kubevirt.io/api/core/v1/types.go

**What this PR does / why we need it**: We have been using `PCI_RESOURCE`  and `MDEV_PCI_RESOURCE` constant in different places. This MR unifies usage.
```release-note
NONE
```

Unify usage of PCI and MDev prefixes

---

hack/functests.sh
pkg/virtctl/ssh/native.go
pkg/virtctl/ssh/ssh.go
pkg/virtctl/ssh/wrapped.go
pkg/virtctl/ssh/wrapped_test.go
tests/virtctl/BUILD.bazel
tests/virtctl/key.go
tests/virtctl/ssh.go

Allow to execute arbitrary command on the remote server via SSH. It adds the option to pass additional flag to the local ssh.
Fixes #
https://github.com/kubevirt/kubevirt/issues/7680
This PR requires and include  the fix https://github.com/kubevirt/kubevirt/pull/7682 . Once merge it needs to be rebased.
```release-note
Add --command and --local-ssh-opts" options to virtctl ssh to execute remote command using local ssh method
```

Improvement of virtctl ssh command

---

hack/prom-rule-ci/prom-rules-tests.yaml
pkg/virt-operator/resource/generate/components/prometheus.go

Added namespace to the KubevirtVmHighMemoryUsage
alert so that the pod will be correctly identified.
Fixes #
```release-note
NONE
```

Fix KubevirtVmHighMemoryUsage alert

---

tests/operator_test.go

fix test id 8235
in release-v0.53 branch product component value was hardcoded to kubevirt in test id 8235. This caused test to fail, when product component was different. Now test uses value from kubevirt config and if empty, it will use kubevirt value.
```
NONE
```

[release-v0.53] fix test id 8235

---

tests/infra_test.go
tests/libvmi/factory.go
tests/libvmi/vmi.go
tests/network/vmi_slirp_interface.go
tests/utils.go

This PR purges two public constants from `tests.libvmi`, as they are not required and dropping them makes the code simpler. In particular, it makes it simpler to start a diskless VM via `libvmi` and simplifies the code introduced in PR #7649.
/cc @EdDev as this modifies `libvmi` APIs
/cc @enp0s3 as this modifies `infra_test`'s rate limiter test
```release-note
NONE
```

tests: simplify libvmi and use it to start diskless VM

---

pkg/hooks/manager.go

**What this PR does / why we need it**: Reduces complexity/nestiness of `OnDefineDomain` method by reverting if conditions. Also changing the version check so it's easier to catch cases when the hook version is not correctly defined (see https://github.com/kubevirt/kubevirt/pull/7642#discussion_r859648236).
```release-note
NONE
```

Reduce nestiness of `OnDefineDomain` method

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/vmi_lifecycle_test.go

If vmi starts with some cpuModel that isn't host-model/passthough a node selector must be added to virt-launcher otherwise
this could lead to failure when starting vmi on node that doesn't support the cpuModel in vmi.Spec.
Fixes #
If CPUNodeDiscovery featureGate is disabled ( which it is by default :\ ) than vmi with some cpuModel might be scheduled to node that doesn't support this cpuModel.
To understand this bug you can create a vmi with Haswell cpuModel in kubevirt-ci, Haswell isn't supported but 
virt-launcher is being scheduled anyway and this is a bug because virt-launcher pod should …

stop considering cpu node discovery feature gate

---

pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

Add reason to AgentVersionNotSupported condition.
Fixes #7433
```release-note
User now gets information about the type of commands which the guest agent does not support.
```

Add reason to AgentVersionNotSupported condition

---

tests/reporter/BUILD.bazel
tests/reporter/kubernetes.go

In order to keep to logs cleaner and more informative,
refrain from printing the same error again again,
and also save time if the container / pod aren't
reachable (instead of running more commands).
Additionally - Fix logic of checking if the virt-handler's compute container is healthy,
not just exist.
Fixes #7799 
```release-note
None
```

k8s-reporter: Stop dumping unreachable container's info

---

tests/libstorage/BUILD.bazel
tests/libstorage/pvc.go
tests/storage/memorydump.go
tests/utils.go

These were introduced in #7324 and would perfectly fit in libstorage.
Fixes #
Looking at pod funcs in the big utils.go, I think we have enough justification to create `libpod`.
WDYT?
```release-note
NONE
```

tests, libstorage: relocate some recently introduced PVC utils

---

tests/reporter/kubernetes.go

Since virt-launcher core code was changed (https://github.com/kubevirt/kubevirt/pull/7451),
and the processes are not suffixed with no-fork
anymore, fix the pgrep logic that find the pid
according the new naming (`virt-launcher-monitor` and `virt-launcher`)
Fixes #
```release-note
None
```

k8s reporter: Fix virt-launcher pid find logic

---

examples/vm-template-fedora.yaml
examples/vm-template-rhel7.yaml
examples/vm-template-windows2012r2.yaml
tools/vms-generator/utils/utils.go

Up to release 4.8 the `oc` command fixes `apiVersion` in YAML or JSON ocp resource files
from v1 to the correct value for the object.
From release 4.9 this is not true anymore, and we have to specify not only the version but also the apiGroup.
ref: https://docs.openshift.com/container-platform/4.9/release_notes/ocp-4-9-release-notes.html - Table 1. Deprecated and removed features tracker
Fixes #
```release-note
NONE
```
/cc @dhiller @Barakmor1

Add apiGroup to Template resource

---

tests/storage/imageupload.go
tests/utils.go

Make test/utils.go slightly shorter by moving `createArchive` into its only user.
```release-note
NONE
```

tests/utils: a very minor cleanup

---

pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go

We currently have no mechanism to protect us from executing
`MigrateVirtualMachine()` (which instructs virt-launcher to start
the migration) twice which has unfortunately happened on some
production clusters.
If this occurs virt-launcher detects the double-start and fails the
migration immediately after tearing down the migration proxies,
unfortunately in the logs this appears as a "network error"
(because the source virt-launcher cannot reach the target node
anymore) even if it's clearly not a network error but rather
a migration abort.
This patch prevents this and adds a unit test.
Snippet from source virt-launcher:
```
2022-04-26T20:49:10.291497895Z {"component":"virt-launcher","level":"error","msg":"error encountered copying data to outbound …
```

virt-handler: add protection against migration double-starts

---

pkg/virt-operator/resource/generate/components/secrets_test.go

Use `math/rand` instead of `crypto/rand` in tests to speed up execution 

---

tests/migration_test.go

This test is flaky because the target pod is potentially paused when reaching the exec code, failing the test.
Including the exec error in the Eventually loop instead of failing on it should address the issue.
Fixes #
```release-note
NONE
```

tests: empty iso: handle potentially paused target

---

pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/rendervolumes.go
pkg/virt-controller/services/rendervolumes_test.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go

This PR refactors the virt-controller templating service, introducing a builder pattern to generate volume specification.
The ad-hoc generation of volumes for the virt-launcher pod is replaced by a builder pattern, allowing the customization of the launcher spec via options. 
It provides a simpler, more explicit way to achieve the same thing - volume spec generation becomes easier to write, and a lot easier to read / reason about. Going forward, it even defines a solid ground to expand the functionality of volume spec generation, instead of forcing the developer to find the appropriate nested if else and put his adapter copied code there. 
Finally, the added unit tests are a chance to clearly document how to configure each of the relevant options. …

Refactor virt controller template machine volumes

---

tests/console/login.go

In case LoginToAlpine fails,
it printed Infof instead of Errorf.
Fixes #
```release-note
None
```

tests, login: Fix error printing

---

tests/network/primary_pod_network.go

The existing testing framework flow requires that the cleanup of the
test be executed at the beginning (setup) of the next test [1].
Therefore, remove all VMI cleanups from the teardown fixtures.
[1] Cleaning up at the teardown step will remove objects before they
are collected by the custom reporting (which helps debug).
This reporting is hooked into ginkgo where it is called only after a
test finishes (either with success or failure).
The cleanup is added at the beginning of the tests (setup).
Fixes #
```release-note
NONE
```

tests, network, primary-pod: Remove VMI deletion on teardown

---

hack/config-default.sh
manifests/generated/kubevirt-cr.yaml.in
pkg/virt-operator/resource/generate/components/crds.go
pkg/virt-operator/util/config.go
tools/manifest-templator/manifest-templator.go
tools/resource-generator/BUILD.bazel
tools/resource-generator/resource-generator.go

When KUBEVIRT_INFRA_REPLICAS is not set, we still add `replicas: 2` in the CR, since it was the default until recently, and made the code simpler.
However, replicas are now dynamic, and we don't want to force a specific value when none is set.
This PR adds an `if` block to the CR template to address that.
Fixes #
```release-note
NONE
```

Remove assumption that infra replicas default to 2

---

tests/vmi_lifecycle_test.go

Currently the supportedFeatures var is set to be all the Features that are supported
in at least one node in the cluster but in tests we assume that this set of features exist 
in all the nodes of the cluster.
This might cause flakiness if the cluster is heterogeneous and some of the features 
are not supported in all node as this test try to avoid scheduling vm to node with one of
those features and verify that the VMI is unschedulable but it can still schedule the vm to a node
that doesn't support this feature.
Fixes #
To fix this i modifed the the …

Fixing flacky test_id:3203

---

tests/console/console.go

The expecters working on BIOS/EFI logs are given a freshly created VMI, to maximize their chance of catching those early logs.
Therefore, they need an initial timeout long enough for the VMI to start, 10 seconds is just not enough.
Fixes #
```release-note
NONE
```

tests: console: bootloader expecters: give the VMI enough time to start

---

tests/migration_test.go
tests/vmi_ignition_test.go

Inline isUsingBuiltinNodeDrainKey and hasExperimentalIgnitionSupport
functions as requested by @xpivarc in #7848.
```release-note
NONE
```

test: inline unnecessary functions

---

tests/storage/datavolume.go

Test: `[sig-storage] DataVolume Integration [rfe_id:3188][crit:high][vendor:cnv-qe@redhat.com][level:system] Starting a VirtualMachineInstance with a DataVolume as a volume source Alpine import should accurately report DataVolume provisioning`
fails sometimes, need to investigate if the test is flaky or there is a real issue.
Fixes #
Improving test reporting - Investigating the issue, trying to run locally and in the CI env. The commit with real fix should follow.
```release-note
NONE
```

[Flaky] 3188 test - improve reporting to catch a problem

---

pkg/virt-api/rest/subresource.go

The current error message lacks context about what "Always" is.
```
$ virtctl start xyz
Error starting VirtualMachine Operation cannot be fulfilled on virtualmachine.kubevirt.io "xyz": Always does not support manual start requests
```
```release-note
NONE
```

virt-api: start subresource: clearer error message

---

tests/network/vmi_networking.go

test_ids: 1550,1551,1772 are experiencing flakiness issues [0,1,2] with Alpine login on
OCP clusters.
Moving to use Cirros image to check if the issues persist.
Also, in order to avoid a known issue in Cirros on ipv6-only clusters, skipping these tests in such case.
[0] https://issues.redhat.com/browse/CNV-18762
[1] https://issues.redhat.com/browse/CNV-18761
[2] https://issues.redhat.com/browse/CNV-18823
Note that this PR is not offering to fix the Alpine issue, but simply check that it is not needed
Fixes #
```release-note
NONE
```

vmi_networking, Move flaky tests to Cirros

---

tests/reporter/kubernetes.go

Currently when a test fails a dump is collected from the cluster for
later debugging. This dump includes various ssh expecter sessions to the vmi,
which are also printed to the screen. This makes it hard understanding when
the test ended and when the repoting started.
A simple solution is to add a step before the dump is collected.
Fixes #
```release-note
NONE
```

ci, reporter, Add step before reporter dump starts

---

Makefile

My former attempt at `make lint` used `git-diff` and as such can confuse
Tide. Far worse it simply did not work failing with
fatal: Not a valid object name origin/main
and should not have been merged.
Let us quickly revert to simple static approach, where someone (e.g. me)
is going to update the threathold once in a while, until tests/utils is
gone.
This version is tested to fail when the file grows above the threshold
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7852/pull-kubevirt-code-lint/1537101643487645696#1:build-log.txt%3A25
```release-note
NONE
```

test/utils: static file length limit

---

tests/infra_test.go
tests/libvmi/factory.go
tests/libvmi/vmi.go
tests/utils.go
tests/vmi_lifecycle_test.go

In continuation to PR #7850, this PR suggests to further simplify the API of `libvmi` by dropping the compulsory `name` argument, which is never used by us. This makes it simpler to reimplemnt `tests.NewRandomVMIWithNS` with `libvmi`. If we ever need to set the VMI name, we can add a WithName() builder option.
```release-note
NONE
```

tests: libvmi.New: no explicit name

---

pkg/util/util.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
pkg/virt-config/virt-config.go
pkg/virt-controller/watch/BUILD.bazel
pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/application_test.go
pkg/virt-controller/watch/vm.go
pkg/virt-controller/watch/vm_test.go
tests/flavor_test.go

With the introduction of flavors and preferences we now need to ensure some of the default logic fired by the `VirtualMachineInstance` mutation webhook is called *before* any flavor and/or preference application within the `VirtualMachine` controller. Doing so should ensure that any device preferences (such as preferred disk bus or interface model) are applied to any default network interfaces or missing volume disks that are added to the `VirtualMachineInstance` at runtime.
Fixes #
```release-note
Device preferences are now applied to any …
```

flavors: Apply preferences to any added default network interfaces or missing volume disks

---

pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/snapshot/restore.go
pkg/virt-controller/watch/snapshot/restore_base.go
pkg/virt-controller/watch/snapshot/restore_test.go
pkg/virt-controller/watch/snapshot/snapshot.go
pkg/virt-controller/watch/snapshot/snapshot_base.go
tests/storage/restore.go

Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2086825
Copy of https://github.com/kubevirt/kubevirt/pull/7920 which needs a rebase
```release-note
BugFix: Fix vm restore in case of restore size bigger then PVC requested size
```

Fix vm restore in case of restore size bigger then PVC requested size

---

hack/prom-rule-ci/prom-rules-tests.yaml
pkg/virt-operator/resource/generate/components/prometheus.go

Removed recording rule kubevirt_num_virt_handlers_by_node_running_virt_launcher and updated the alert to fire when there is a node that is running VMs but doesn't have a ready virt-handler pod.
Fixes #
```release-note
NONE
```

Drop recording rule for orphaned VMs alert and fix alert definition

---

pkg/virt-controller/watch/migration.go
tests/migration_test.go

The migration code allows VMIs to migrate from root to non-root, but not the other way around.
Sounds like an oversight to me, this PR addresses that.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2091911
Will write unit/functional test(s) if preliminary reviews are positive.
```release-note
Non-root VMs will now migrate to root VMs after a cluster disables non-root.
```

migration: enable migrating from non-root to root

---

tests/network/primary_pod_network.go

Use `libvmi` to create the VMI spec/s in the network, primary-pod e2e tests.
Prefer explicitly showing in the tests the building blocks of the VMI rather than hide it in helpers.
Fixes #
```release-note
NONE
```

tests, network, primary pod: use libvmi to create VMI specs

---

pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/node-labeller/node_labeller.go

On each and every node-labeller control loop, it removed its managed labels from the node and assigns them again.
But two labels are not being removed currently. These are:
```go
const HostModelCPULabel              = "host-model-cpu.node.kubevirt.io/"
const HostModelRequiredFeaturesLabel = "host-model-required-features.node.kubevirt.io/"
```
These are now being removed.
In addition, I've added a test and did some minor refactoring to node-labeller.
```release-note
bugfix: node-labeller now removes "host-model-cpu.node.kubevirt.io/" and "host-model-required-features.node.kubevirt.io/" prefixes
```

[Bugfix] [Node-Labeller]: Properly remove all node-labeller labels

---

tests/infra_test.go
tests/libnode/BUILD.bazel
tests/libnode/node.go
tests/migration_test.go

Currently, libnode marshalls the whole node just to add a label/annotation. Then, it patches the whole node.
This is clearly wasteful, and with such a basic operation that could slow up our whole testing suite.
This PR avoids marshalling and patches only the labels / annotations in an efficient way. In addition, it adds support for label/annotation removal.
```release-note
NONE
```

Optimize libnode's annotation/label modification functions + stabilize & fix migration functests

---

pkg/virt-handler/isolation/detector_test.go

Since https://github.com/kubevirt/kubevirt/pull/7451
virt-launcher processes names were changed.
Adapt the unit test accordingly, by being agnostic
to the binary names, as it doesn't affect the test
as long as the stubs don't have the expected qemu
names.
Fixes #7878 
```release-note
None
```

unit test, isolation: Make test agnostic to virt-launcher process name

---

pkg/cloud-init/BUILD.bazel
pkg/cloud-init/cloud-init.go
pkg/cloud-init/cloud-init_test.go
pkg/virt-controller/watch/snapshot/restore.go
pkg/virt-launcher/virtwrap/manager.go
tests/console/console.go
tests/libvmi/cloudinit.go
tests/network/sriov.go
tests/vmi_cloudinit_test.go

Before this patch the VMI uuid was used as the cloud-init `uuid`
(which is then used by cloud-init to build the `instance-id`),
this had the side-effect of letting the cloud-init `instance-id`
change on every VM reboot causing the 'on-first boot' cloud-init
configuration to be executed on every restart and not just once.
This for example would cause the VMI to regenerate SSH keys at
every restart which is not desirable (thus causing a ssh public key
mismatch when connnecting with a client).
This patch fixes this by using the VM UID as uuid which
makes the cloud-init 'instance-id' stable, in case the VMI is not
associated to a VM the VMI's UID will be used instead. …

cloud-init: make cloud-init 'instance-id' persistent

---

tests/vmi_lifecycle_test.go

The rfe_id:273 test starts a VM with no disk and no operating system.
However, it allocates 256Mi for the VM RAM. This memory size was chosen
as it is the minimal memory required for running a Fedora guest on the
ARM architecture. This motivation is irrelevant for this test and
needlessly causes us to waste 255Mi of runtime RAM.
Let us reduce the memory consumed by this test, in order to strain our CI platform a bit less.
This PR was split  from https://github.com/kubevirt/kubevirt/pull/7858 to allow clearer discussion.
```release-note
NONE
```

vmi_lifecycle_test: consume less memory

---

pkg/util/types/patch.go
pkg/virt-api/rest/BUILD.bazel
pkg/virt-api/rest/subresource.go
pkg/virt-api/rest/subresource_test.go
pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-controller/watch/node.go
pkg/virt-operator/resource/apply/apps_test.go

To avoid manually writing strings for patches, which is error prone, delicate and hard to debug, the `PatchOperation` struct was introduced. While being a very good idea that eases the process, it can still be improved. This PR aims to improve the patch generation process in terms of ease of use, readability and code safety.
This PR introduces:
* `GeneratePatchPayload(patches ...PatchOperation)` function. This eliminates the need to manually initialize an array of patch operations + marshalling it.
* `GenerateTestReplacePatch()` function. This aims to ease the process of making a test & replace patches.
* Constant patch operations (add, replace, etc) to reduce probability of errors in patch operations
I believe these changes contribute to the code …

[Code Quality]: Improve & ease patch generation

---

pkg/virt-handler/node-labeller/cpu_plugin.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
tests/infra_test.go

Currently if a source node has a Feature that is in MinCpuModel's features and a target node doesn't a migration to this node will fail and it will be very hard to understand why because the features in MinCpuModel don't appear in the node's labels.
There are two options to solve this:
1) stop considering MinCpuModel's field and maybe remove it completely
(might be a problem because of backward compatibility)
2) check if every node contain at least the MinCpuModel's features and mark it as unschedulable node if it doesn't.
In this PR i chose the first choice since the second choice will result unschedulable nodes.
Another problem with that field:
What if someone want to use node Affinity in the vmi for some feature that is one of the features of the …

fixing MinCPUModel's field logic

---

pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/snapshot/restore.go
pkg/virt-controller/watch/snapshot/restore_base.go
pkg/virt-controller/watch/snapshot/restore_test.go
pkg/virt-controller/watch/snapshot/snapshot.go
pkg/virt-controller/watch/snapshot/snapshot_base.go
tests/storage/restore.go

Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2086825
```release-note
BugFix: Fix vm restore in case of restore size bigger then PVC requested size
```

[release-0.53] Backport 'Fix vm restore in case of restore size bigger then PVC requested size'

---

tests/storage/restore.go
tests/utils.go

`echo hello` userdata is an implementation detail of Cirros VMs. It should not be mentioned in each test, and it does not deserve its own public constant. This PR makes the constant public and replaces one of its usages by a `libvmi.NewCirros` call.
/cc @brybacki as this is storage
```release-note
NONE
```

tests/storage/restore: less `echo hello`

---

tools/crd-validation-generator/validation-generator.go

This fixes the issue where generating the CRD validation code fails if code comments for API types contain backticks (`).
Any backticks in the schema description fields are now replaced with single quotes so that they don't break the code syntax when wrapped in string literals / raw strings.
See #7844
```release-note
Fixed a bug that caused `make generate` to fail when API code comments contain backticks. (#7844, @janeczku)
```

Fix CRD validation code generation

---

tests/libvmi/cloudinit.go
tests/libvmi/status.go
tests/libvmi/storage.go
tests/libvmi/vmi.go

The lint target [1] revealed several issues with the covered libvmi
codebase.
The various issues have been fixed by this change.
[1] https://github.com/kubevirt/kubevirt/pull/7908
The original linter report which this change fixed based is:
```
tests/libvmi/cloudinit.go:32:15: string `disk1` has 2 occurrences, make it a constant (goconst)
diskName := "disk1"
^
tests/libvmi/status.go:28:32: G601: Implicit memory aliasing in for loop. (gosec)
if controller.IsControlledBy(&pod, vmi) {
^
tests/libvmi/status.go:29:20: G601: Implicit memory aliasing in for loop. (gosec)
controlledPod = &pod
^
tests/libvmi/vmi.go:51:39: mnd: Magic number: 5, in <argument> detected (gomnd)
return "testvmi" + "-" + rand.String(5)
^
tests/libvmi/cloudinit.go:25:2: ST1019: …
```

tests, libvmi: Adjust code to pass linter

---

.golangci.yml
Makefile
hack/builder/Dockerfile
hack/dockerized

Introduce golangci-lint [1] into the builder image in order to start
using a linter to detect common mistakes and attempt to place some
order in the code.
Include golangci-lint in the makefile `lint` target and a basic
configuration file.
At this stage, it processes only `tests/libvmi` folder.
[1] https://github.com/golangci/golangci-lint
Fixes #
The linter is reporting a few errors which need treatment.
These will be handled in a separate PR.
```release-note
NONE
```

builder, makefile, lint: Introduce golangci-lint

---

pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/snapshot/restore.go
pkg/virt-controller/watch/snapshot/restore_base.go
pkg/virt-controller/watch/snapshot/restore_test.go
pkg/virt-controller/watch/snapshot/snapshot.go
pkg/virt-controller/watch/snapshot/snapshot_base.go
tests/storage/restore.go

This is a manual cherry pick of PR https://github.com/kubevirt/kubevirt/pull/7933
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2101168
```release-note
BugFix: Fix vm restore in case of restore size bigger then PVC requested size
```

[release-0.49] Backport 'Fix vm restore in case of restore size bigger then PVC requested size'

---

pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/snapshot/restore.go
pkg/virt-controller/watch/snapshot/restore_base.go
pkg/virt-controller/watch/snapshot/restore_test.go
pkg/virt-controller/watch/snapshot/snapshot.go
pkg/virt-controller/watch/snapshot/snapshot_base.go
tests/storage/restore.go

This is a manual cherry pick of PR https://github.com/kubevirt/kubevirt/pull/7933
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2101174
```release-note
BugFix: Fix vm restore in case of restore size bigger then PVC requested size
```

[release-0.44] Backport 'Fix vm restore in case of restore size bigger then PVC requested size'

---

.golangci.yml
Makefile
tests/infra_test.go
tests/libnet/cloudinit.go
tests/libnet/cluster/cluster.go
tests/libnet/dns.go
tests/libnet/ipaddress.go
tests/libnet/namespace.go
tests/libnet/ping.go
tests/libnet/service/service.go
tests/libnet/skips.go
tests/network/expose.go
tests/network/port_forward.go
tests/network/probes.go
tests/network/services.go
tests/network/vmi_istio.go
tests/network/vmi_lifecycle.go
tests/network/vmi_networking.go
tests/storage/storage.go
tests/windows_test.go

The `tests/libnet` package is added to the lint target and required fixed applied.
These are the treated errors:
```
tests/libnet/service/service.go:28:1: paramTypeCombine: func(serviceName string, exposedPort int, portToExpose int, selectorKey string, selectorValue string) *k8sv1.Service could be replaced with func(serviceName string, exposedPort, portToExpose int, selectorKey, selectorValue string) *k8sv1.Service (gocritic)
tests/libnet/service/service.go:34:1: paramTypeCombine: func(serviceName string, exposedPort int, portToExpose int, selectorKey string, selectorValue string) *k8sv1.Service could be replaced with func(serviceName string, exposedPort, portToExpose int, selectorKey, selectorValue string) *k8sv1.Service (gocritic) …
```

lint: Add `tests/libnet` to the linter coverage

---

tests/reporter/kubernetes.go

In case we don't use a kind sriov provider, /dev/vfio info doesn't
exists and not needed.
It adds noise to the logs.
Hence dump it only for kind sriov providers.
Fixes #
```release-note
None
```

k8s reporter, sriov: Dump /dev/vfio for kind providers only

---

tests/performance/density.go

The performance test running in the Prow workload cluster is failing:
[https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-e2e-k8s-1.21-sig-performance&width=20](https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-e2e-k8s-1.21-sig-performance&width=20)
```
Timed out after 300.003s.
Expected
<int>: 101
to equal
<int>: 100 
```
After an update in the test that creates one VMI to init the Prometheus database to correctly calculate the counters, the test will create 100 VMIs plus 1. Which is what is failing in the expected value.
This PR updates the expected value to 101.
Fixes # …

tests: performance: update the expected number of created vmis

---

Makefile
tests/console/console.go
tests/console/login.go

Add the `tests/console` folder to the linter coverage.
The following errors are treated:
```
tests/console/console.go:239:2: appendCombine: can combine chain of 3 appends into one (gocritic)
opts = append(opts, expect.SendTimeout(timeout))
^
tests/console/console.go:230:2: assignOp: replace `timeout = timeout - time.Now().Sub(startTime)` with `timeout -= time.Now().Sub(startTime)` (gocritic)
timeout = timeout - time.Now().Sub(startTime)
^
tests/console/console.go:177:7: badCall: no-op append call, probably missing arguments (gocritic)
b := append([]expect.Batcher{
^
tests/console/console.go:204:7: badCall: no-op append call, probably missing arguments (gocritic)
b := append([]expect.Batcher{
^
tests/console/console.go:149:11: preferFprint: …
```

lint: Add `tests/console` to the linter coverage

---

tests/utils.go

This PR exposes to logs the error when the `WaitForConfigToBePropagatedToComponent()` function fails.
Fixes #
```release-note
NONE
```

utils, Expose error when update config fails

---

WORKSPACE
tests/libnet/ping.go

The new alpine image has the following:
- Bump to alpine 3.16
- ssh access
- fix not space left issue
- replace busybox ping commands with iptools
- installed curl command
- activate sshd at startup
```release-note
Bump alpine_with_test_tooling
```

workspace: Bump alpine-with-tooling image

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/vmi_configuration_test.go

Recent tests show that 75Mb is not enough.
virt-launcher memory overhead may vary during execution
depending on many factors, such as when the garbage collector runs.
Increase the virt-launcher overhead to avoid OOM kill.
Here is a report of some collected data
Here is the document where we are collecting data from the current running test:
https://docs.google.com/spreadsheets/d/1Dd_bRffT6hr1fw_rlh7hqOFRFbVQWaCOyU7IZVwGDVo/edit?usp=sharing
Fixes #
```release-note
Increase virt-launcher memory overhead
```

Increase virt-launcher memory overhead

---

tests/storage/datavolume.go

Test is flaky. VM is created, then it should show Provisioning.
But sometimes when the virt-controller quits with error more than once
on "the object has been modified; please apply your changes...",
then we can miss the PrintableStatus == provisioning,
because the next time it reconciles, it will see DV Succeeded and will
show status Stopped
Sample failure:
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7634/pull-kubevirt-e2e-k8s-1.22-sig-storage/1534424372658311168/artifacts/k8s-reporter/3/pods/1_kubevirt_virt-controller-6c969c86d6-xmlt5-virt-controller.log).
Fixes …

Quarantine 3188 test

---

hack/dockerized

make would fail with below error message when build environment behind a firewall.
To make the build system work properly, the proxy configurations of the host should
be passed to the docker build environment:
$ export HTTP_PROXY="xxx.com:888"
$ export HTTPS_PROXY="xxx.com:888"
$ export NO_PROXY="127.0.01, .example.com"
$ make
```
Waiting for it to complete...
Another command (pid=16) is running. Waiting for it to complete on the server (server_pid=20)...
Loading: 0 packages loaded
Fetching com_github_bazelbuild_buildtools; fetching
make: *** [Makefile:187: format] Error 1
```
Signed-off-by: Haibo Xu <haibo1.xu@intel.com> …

Add proxy configuration to build system when host behind a firewall

---

.gitattributes

BUILD.bazel files in pkg/, staging/ and tests/ are 100% auto-generated
and pretty much 100% of the time not something which need a review.
These paths are also the places where most of the code changes happen.
Let's mark them as dependencies which should be collapsed by default on PR reviews.
In the only case where they are normally an issue and need to be fixed
is when unintended custom modifications were done. In this case CI will
uncover that.
Properties are detected correctly:
```bash
$ git check-attr --all pkg/container-disk/BUILD.bazel
pkg/container-disk/BUILD.bazel: linguist-vendored: set
$ git check-attr --all tests/conformance/
BUILD.bazel     conformance.go  def.bzl         
$ git check-attr --all tests/conformance/
BUILD.bazel …
```

Let github collapse BUILD.bazel files in certain locations

---

WORKSPACE

The cache link was bumped by accident in a PR without giving the CI bot
a chance to do that automatically. Removing the link so that the bot can
upload the image.
This should help with the virtio disk donwload slowness on initial `make
cluster-sync` calls.
Fixes #
```release-note
NONE
```

Remove dead virtio cache link

---

tests/network/sriov.go

When a test failed due to failure in finding SR-IOV interface by MAC, there is no description why it failed
that could help with realizing when and how many times such test failed (for example, by using SearchCI).
This PR add description to find VMI interface by MAC address assertions.  
Fixes #
```release-note
NONE
```

tests, sriov: Improve error of finding VMI iface by MAC assert

---

pkg/virt-controller/watch/snapshot/restore.go
tests/storage/restore.go

This is a follow-up PR to https://github.com/kubevirt/kubevirt/pull/7807.
As laid out in [this comment](https://github.com/kubevirt/kubevirt/pull/7807#discussion_r901681007), no identity stripping logic should reside within snapshot / restore controllers, but only at the [cloning controller](https://github.com/kubevirt/kubevirt/pull/7336).
This PR removed the identity stripping from snapshot package. Instead, the functional tests now use a custom patch to strip the firmware UUID.
Please read this comment for some more context: https://github.com/kubevirt/kubevirt/pull/7807#discussion_r901681007
```release-note
NONE
```

Remove identity stripping logic leftovers from restore controller

---

vendor/modules.txt

`pull-kubevirt-verify-go-mod` lane is failing. This PR is the result of running `make deps-sync` so that the lane would pass.
```release-note
NONE
```

Sync kubevirt dependencies

---

BUILD.bazel
hack/bazel-generate.sh
hack/bootstrap.sh
tools/analyzers/BUILD.bazel
vendor/github.com/gordonklaus/ineffassign/pkg/ineffassign/BUILD.bazel
vendor/modules.txt

Instruct gazelle with an explicit mapping directive to use the right
golang.org/x/tools dependency for the Analyzer interface which is also
used by nogo to load the custom analyzers.
Since gazelle now does the correct mapping, all special handling of
files with a `#gazelle: ignore` annotation is no longer necessary.
The BUILD.bazel files for analyzers are now generated like all the other
build files.
Fixes #
```release-note
NONE
```

Let nogo linters use the right golang.org/x/tools dependency

---

BUILD.bazel
go.mod
nogo_config.json
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-controller/watch/export/export_test.go
pkg/virt-controller/watch/snapshot/restore_test.go
pkg/virt-handler/device-manager/mediated_devices_types_test.go
pkg/virt-handler/isolation/isolation_test.go
staging/src/kubevirt.io/client-go/api/defaults_test.go
tests/infra_test.go
tools/analyzers/ginkgolinter/BUILD.bazel
tools/analyzers/ginkgolinter/README.md
tools/analyzers/ginkgolinter/ginkgo_linter.go

This PR adds a linter for ginkgo checks. For the first phase, the linter looks for wrong length checks (see below), and suggests alternatives.
This is a golang linter to check usage of the ginkgo and gomega packages.
ginkgo is a testing framework and gomega is its assertion package.
The linter finds usage of the golang built-in `len` function, and then all kind of matchers, while there are already gomega matchers for these usecases.
There are several wrong patterns:
```go
Expect(len(x)).To(Equal(0)) // should be Expect(x).To(BeEmpty())
Expect(len(x)).To(BeZero()) // should be Expect(x).To(BeEmpty())
Expect(len(x)).To(BeNumerically(">", 0)) // should be Expect(x).ToNot(BeEmpty())
Expect(len(x)).To(BeNumerically(">=", 1)) // should be Expect(x).ToNot(BeEmpty()) …
```

Add ginkgo linter

---

tests/libvmi/storage.go
tests/storage/storage.go

Use `libvmi` where possible in storage tests. Many tests already use this new lib, so using it here makes codebase more consistent (simpler to maintain). This is one of required steps to remove big universal utils.go.
With this PR a new factory functions were added to create a VM with provided DV or PVC. Also new function was used in a few places as an example. In a followup PR I'll try to replace all tests.RandomVM usages.
Fixes #
```release-note
NONE
```

Use libvmi consistently in storage tests

---

pkg/virtctl/scp/BUILD.bazel
pkg/virtctl/scp/native.go
pkg/virtctl/scp/scp.go
pkg/virtctl/scp/scp_suite_test.go
pkg/virtctl/scp/wrapped.go
pkg/virtctl/scp/wrapped_test.go
pkg/virtctl/ssh/knownhosts.go
pkg/virtctl/ssh/knownhosts_test.go
pkg/virtctl/ssh/native.go
pkg/virtctl/ssh/resize_unix.go
pkg/virtctl/ssh/ssh.go
pkg/virtctl/ssh/wrapped.go
pkg/virtctl/ssh/wrapped_test.go
tests/virtctl/scp.go
tests/virtctl/ssh.go

This adds the option to use the local scp client instead of the native go
ssh client for scp operations. Like for the local ssh client virtctl is
used as ProxyCommand for scp.
```release-note
Add option to wrap local scp client to scp command
```

virtctl: Add option to wrap local scp client to scp command

---

tests/access_test.go

This is a manual cherry-pick of #7673
/assign dhiller
```release-note
NONE
```

[release-0.49] Make names of access tests around test_id:2921 unique

---

tests/access_test.go

This is a manual cherry-pick of #7673
/assign dhiller
```release-note
NONE
```

[release-0.51] Make names of access tests around test_id:2921 unique

---

tests/access_test.go

This is a manual cherry-pick of #7673
/assign dhiller
```release-note
NONE
```

[release-0.50] Make names of access tests around test_id:2921 unique

---

tests/libvmi/vmi.go
tests/utils.go
tests/vmi_configuration_test.go

Replacing spec's objects might mislead and surprise the users.
We should change only the field that the function refer to instead.
Changing `WithUefi` function to  enable `SMM` when secureBoot is `true` as the  required settings
of secure boot include enabling `Uefi` and `SMM` feature as well  :
http://kubevirt.io/api-reference/master/definitions.html  ( v1.EFI )
Fixes #
```release-note
NONE
```

tests, libvmi: Do not override dependent spec sub trees

---

pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go

**What this PR does / why we need it**: 
The mechanism to obtain CDI's filesystem overhead in KubeVirt uses `cdi` as hardcoded key to check if the resource exists. This behavior conflicts when CDI has a custom name, such as `cdi-kubevirt-hyperconverged` in HCO.
This Pull Request aims to fix said mechanism, so the value is obtained independently of CDI's name.
**Which issue(s) this PR fixes:** 
https://bugzilla.redhat.com/show_bug.cgi?id=2097436
```release-note
[Bug-fix]: Fix mechanism to fetch fs overhead when CDI resource has a different name
```

Fix mechanism to fetch filesystem overhead when the CDI resource has a different name

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-handler/node-labeller/cpu_plugin.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-handler/node-labeller/node_labeller.go
staging/src/kubevirt.io/client-go/apis/core/v1/types.go
tests/infra_test.go
tests/migration_test.go
tests/utils.go

manual backporting https://github.com/kubevirt/kubevirt/pull/7672 ,https://github.com/kubevirt/kubevirt/pull/7770 from main
Fixes #
```release-note
NONE
```

[release-0.47] Fixing host model support heterogeneus cluster 

---

pkg/virt-handler/device-manager/device_controller_test.go

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8006/pull-kubevirt-unit-test/1542490796945575936
```
{ Failure pkg/virt-handler/device-manager/device_controller_test.go:182
Timed out after 1.001s.
Expected
<bool>: true
to be false
pkg/virt-handler/device-manager/device_controller_test.go:197}
```
For now this change increases the Eventually timeout used by various
tests to hopefully avoid this.
Fixes #
```release-note
NONE
```

trivial: Increase timeout of device controller tests

---

pkg/virt-controller/watch/clone/BUILD.bazel
pkg/virt-controller/watch/clone/clone.go
pkg/virt-controller/watch/snapshot/restore.go
pkg/virt-controller/watch/snapshot/snapshot.go
tests/storage/clone.go

The new cloning API [was merged](https://github.com/kubevirt/kubevirt/pull/7336) [1] recently. Since then, we're seeing some CI failures (e.g. [this one](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.23-sig-storage/1544549474116833280) [2]).
The failures are coming from validating webhooks [3]. These webhooks don't allow VMs to start if a restore is still in progress.
The cloning API is making sure the restore object states that it's ready [4], but it doesn't check the VM's status.
Essentially, this is the current flow:
- Restore is complete. Its status is changed to reflect it.
- Then, these two things happen in parallel:
- Cloning controller moves to "Succeeded" and considers the VM as ready
- The VM …

[Clone API]: Fix race between VM and restore readiness

---

tests/storage/clone.go

The simple clone test still looks to be flaky after the fix was merged (https://github.com/kubevirt/kubevirt/pull/8059)
[VirtualMachineClone Tests VM clone with more complicated VM with a simple clone](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8099/pull-kubevirt-e2e-k8s-1.23-sig-storage-nonroot/1547967495300714496)
CI Search link:
https://search.ci.kubevirt.io/?search=VirtualMachineClone&maxAge=6h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
/cc @dhiller 
**Release …

Quarantine flaky test for clone of more complicated VM

---

Makefile
tests/subresource_api_test.go
tests/sysprep_test.go
tests/template_test.go
tests/utils.go
tests/windows_test.go

tests/utils.go is still too long to read and understand. This PR moves some of its content to more relevant locations.
```release-note
NONE
```

tests: shorten tests/utils

---

Makefile

The time it takes for the linters to run seem to have a large
fluctuation range, between 4sec to over 10sec.
As there are no guarantees given for such jobs (e.g. CPU time), we are
left with increasing the timeout period.
This is mainly triggered by the instability (timeouts) on CI runs.
A possible alternative is to define resource requirements for jobs,
reducing the inconsistent run duration results.
Fixes #
```release-note
NONE
```

golangci-lint: Increase timeout

---

go.mod
go.sum
staging/src/kubevirt.io/client-go/go.mod
staging/src/kubevirt.io/client-go/go.sum
vendor/github.com/emicklei/go-restful/BUILD.bazel
vendor/github.com/emicklei/go-restful/CHANGES.md
vendor/github.com/emicklei/go-restful/cors_filter.go
vendor/github.com/emicklei/go-restful/parameter.go
vendor/github.com/emicklei/go-restful/request.go
vendor/github.com/emicklei/go-restful/response.go
vendor/github.com/emicklei/go-restful/route.go
vendor/github.com/emicklei/go-restful/route_reader.go
vendor/github.com/emicklei/go-restful/web_service.go
vendor/modules.txt

Bump the version of emicklei/go-restful from 2.15.0  to 2.16.0 to fix https://github.com/emicklei/go-restful/pull/493
See https://github.com/emicklei/go-restful/issues/489#issuecomment-1148861521.
(https://github.com/emicklei/go-restful/pull/503)
Fixes #
**Modified files ( not auto generated ) :**
go.mod
staging/src/kubevirt.io/client-go/go.mod
```release-note
Bump the version of emicklei/go-restful from 2.15.0 to 2.16.0
```

Bump the version of `go-restful` to 2.16.0

---

tests/storage/BUILD.bazel
tests/storage/snapshot.go

The test is flaky with the following error:
```
{ Failure tests/storage/snapshot.go:383
<*errors.StatusError | 0xc0057a4320>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "Operation cannot be fulfilled on
virtualmachines.kubevirt.io \"testvmi-kz6kb\": the object has been
modified; please apply your changes to the latest version and try again",
Reason: "Conflict",
Details: {
Name: "testvmi-kz6kb",
Group: "kubevirt.io",
Kind: "virtualmachines",
UID: "",
Causes: nil,
RetryAfterSeconds: 0,
},
Code: 409,
},
}
tests/storage/snapshot.go:446}
```
Update operations may fail in case the resource is updated on the API …

tests, storage, snapshot: Retry a flaky VMI Update

---

tests/config_test.go
tests/utils.go

Following are the improvements:
- Replace usage of host-path Alpine with a container-disk based VM disk, that should reduce the VM launch time.
- Adapt the suite to use `libvmi` thus reducing the content of `utils.go`
- Run the suite in parallel manner.
Perhaps more refactoring can be done i.e. merge the suite to the `vmi_configuration_test.go` suite
I wanted to reduce the complexity of the PR thus decided to start with these changes.
```release-note
NONE
```

[e2e tests]: improve the `config_test.go` suite

---

pkg/virt-controller/watch/snapshot/restore.go
tests/libstorage/BUILD.bazel
tests/libstorage/datavolume.go
tests/storage/BUILD.bazel
tests/storage/restore.go
tests/utils.go

BugId:  2070366
If a VM disk is originally created by network clone, then snapshotted, the "cloneRequest" annotation must be cleared from the new PVC.  Otherwise, CDI network cloning will be initiated.
Fixes #
BugId: https://bugzilla.redhat.com/show_bug.cgi?id=2070366
```release-note
NONE
```

Must clear "cloneRequest" annotation on restore of PVC

---

pkg/virt-handler/device-manager/device_controller.go
pkg/virt-handler/device-manager/device_controller_test.go
pkg/virt-handler/device-manager/mediated_device_test.go
pkg/virt-handler/device-manager/mediated_devices_types_test.go
pkg/virt-handler/device-manager/pci_device_test.go
pkg/virt-handler/vm.go
tests/launchsecurity/BUILD.bazel
tests/launchsecurity/sev.go

Having `/dev/sev` in the list of permanently available devices may impose
a security risk as it can be requested and accessed by an arbitrary pod.
Stop advertizing the device when the corresponding feature gate is
disabled.
Fixes #
```release-note
NONE
```

Respect the feature gate when exposing SEV device

---

tests/operator_test.go

The test aims to verify that virt-handler is being updated
with the configured maximum amount of devices. The test was
missing the validation of Kubevirt status, whether deployment of new
configuration has finished. It also missed checking that all the virt-handler
pods are ready after the rollout.
This caused flakes in the subsequent tests i.e. `test_id:4744` was failed on timeout waiting for the patch 
to be propogated.
```release-note
NONE
```

[e2e tests]: fix test 6987 in operator suite

---

tests/storage/storage.go

Not assigning vmi from Create call causes
that the vmi is missing namespace.
Namespace is required for helper in our test suite
causing 100% failure.
Fixes #
```release-note
NONE
```

Tests: Fix flaky io error

---

pkg/virt-controller/watch/snapshot/restore.go
pkg/virt-controller/watch/snapshot/restore_test.go
tests/storage/clone.go

Currently a VM clone test is in quarantine.  The issue is that the VirtualMachineRestore resource is deleted before the VM restore controller clears the VM `status.restoreInProgress`.  Fix is to clear restoreInProgrress before marking the restore complete.
Fixes #
```release-note
NONE
```

Get VM clone test out of quarantine

---

tests/operator_test.go

the test verifies successful component patching using the customize
components configuration from Kubevirt CR. A proper verification would be:
- To compare the generation numbers between the CR and the component under test
- Verify the changes on the component.
- In this test case verify successful roll-out of the component.
My assumption was that if we aim to check only if the patch was applied to the resource we could do so 
in unit tests, I think that in e2e we should check the health of the subject under test, such as a successful roll-out
in our case.
```release-note
NONE
```

[e2e tests]: improve operator test 4744

---

manifests/generated/operator-csv.yaml.in
pkg/virt-operator/resource/generate/components/deployments.go

this PR adds kubernetes.io/os: linux nodeSelector to virt-operator.
All other components already have this nodeSelector and virt-operator
was missing it
```
Add nodeSelector kubernetes.io/os: linux to virt-operator csv manifest
```

add nodeSelector kubernetes.io/os: linux to virt-operator csv

---

tests/windows_test.go

Cleans up windows test code:
- Removes tests checking `kubectl` - it is not windows specific
- Removes tests that check VM start and stop - also not windows specific
- Simplify test code
```release-note
None
```

tests: Windows tests small cleanup

---

tests/migration_test.go
tests/utils.go

The use of a public constant CouldNotFindComputeContainer exposes that
we had three reimplemenations of GetComputeContainerOfPod. Let us reuse
that function instead, to shorten our code and to make it more readable.
```release-note
NONE
```

tests: reuse GetComputeContainerOfPod

---

tests/network/vmi_istio.go
tests/network/vmi_passt.go

As part of the passt effort all the istio tests were moved to use Alpine.
The alpine VM was created without cloud-init network data which caused the VM startup to be very slow (it added ~2 hours per
network lane).
Adding network data to the alpine VMs to workaround the issue.
Fixes #
```release-note
NONE
```

slow tests: adding cloud init network data to alpine VM

---

tests/storage/storage.go

There are two very similarly named tests - one "with faulty disk"
which is currently failing and #8140 is aiming to fix it, another
["with error disk" that hasn't failed in 2 weeks except in release
lanes.](https://search.ci.kubevirt.io/?search=with+error+disk&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)
While here, give it a slightly different name so it isn't confused
as easily.
```release-note
NONE
```

Remove "should pause on IO error" test from quarantine

---

tests/mdev_configuration_allocation_test.go

Currently, VGPU test override existing FeatureGates entirely with `GPUGate`.
This causes problems with nonroot lanes, since it delete the `NonRoot` FG, resulting
the vmis running as root.
Instead of entirely replace the feature gates, append the desired one to the already
existing.
Fixes #
```release-note
NONE
```

e2e test: append `GPUGate` FG to existing ones instead of override them

---

tests/libvmi/factory.go
tests/network/vmi_istio.go
tests/network/vmi_passt.go

When AlpineWithTestTooling supplied with no user data, it takes the image more than 200s to allow login.
Adding default empty user data to speed up the startup.
Fixes #
```release-note
NONE
```

slow AlpineWithTestTooling startup

---

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter_test.go
tests/storage/clone.go
tests/storage/snapshot.go

VM clone webhook should make sure all PVCs support snapshots.  Otherwise the clone target will refer to the same PVC as the source.
Fixes #
```release-note
NONE
```

VM Clone validation - make sure all PVCs snapshot-able

---

docs/metrics.md
pkg/monitoring/domainstats/prometheus/prometheus.go
pkg/monitoring/domainstats/prometheus/prometheus_test.go
tools/doc-generator/fakeCollector.go

Currently, in the dashboard, under Virtualization -> Overview, the filesystem
report uses a metric about the pod filesystem usage. This PR adds new metrics
with values corresponding to VM filesystem usage so they can be used in the 
dashboard.
Fixes #
```release-note
Add VMI filesystem usage metrics
```

Add VMI filesystem usage metrics

---

pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/renderresources.go
pkg/virt-controller/services/renderresources_test.go
pkg/virt-controller/services/template.go

This PR refactors the virt-controller templating service, introducing a builder pattern to generate resource specification.
The ad-hoc generation of resources for the virt-launcher pod is replaced by a builder pattern, allowing the customization of the launcher spec via options.
It provides a simpler, more explicit way to achieve the same thing - resource spec generation becomes easier to write, and a lot easier to read / reason about. Going forward, it even defines a solid ground to expand the functionality of resource spec generation, instead of forcing the developer to find the appropriate nested if else and put his adapter copied code there.
Finally, the added unit tests are a chance to clearly document how to configure each of the relevant …

Refactor virt controller template resources

---

tests/io_utils.go
tests/storage/storage.go

The PR tries to find and fix the flakiness in one of the storage tests. 
- first commit - Make sure the actual vmi is used, and improve logging.
- second commit - fix the actual problem. 
The problem is that the test is using a virtual scsi device which randomly returns errors. The device sometimes fails during resize - before actually starting a VM. This is because kubevirt has `ExpandDisks` on, and the pvc has bigger size than the device. The fix creates the device and pvc with the same size so it does not need to be resized. 
```
{"component":"virt-launcher","level":"info","msg":"Domain name event: kubevirt-test-default3_testvmi-f9xqt","pos":"client.go:413","timestamp":"2022-05-19T10:13:31.756618Z"} …
```

Flaky test: pause on IO error

---

pkg/virt-api/webhooks/hyperv.go
pkg/virt-controller/watch/topology/BUILD.bazel
pkg/virt-controller/watch/topology/hinter.go
pkg/virt-controller/watch/topology/tsc.go
pkg/virt-controller/watch/topology/tsc_test.go
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go
pkg/virt-launcher/virtwrap/converter/converter.go
tests/BUILD.bazel
tests/libvmi/vmi.go
tests/migration_test.go
tests/windows_test.go

A windows VM using HyperV Reenlightenment cannot migrate successfully. An example for such VM:
```yaml
spec:
domain:
features:
hyperv:
reenlightenment:
enabled: true
```
(of course, the spec is trimmed down only to the relevant portion.
On [a commit to QEMU](https://gitlab.com/qemu-project/qemu/-/commit/561dbb41b1d752098249128d8462aaadc56fd15d), it says: `"Require 'tsc-frequency=' command line option to be specified for successful migration when re-enlightenment was enabled by the guest."`
IOW, the `tsc-frequency` parameter needs to pass to QEMU if HyperV Reenlightenment is enabled.
In converter.go [1], we're adding a tsc frequency parameter if `vmi.Status.TopologyHints != nil && vmi.Status.TopologyHints.TSCFrequency != nil`.
In virt-controller [2] …

[Bug-fix]: Windows VM HyperV Reenlightenment enabled fails to migrate

---

pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-config/configuration_test.go
pkg/virt-config/feature-gates.go
pkg/virt-operator/application.go
pkg/virt-operator/webhooks/BUILD.bazel
pkg/virt-operator/webhooks/kubevirt-update-admitter.go
pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go
tests/framework/checks/skips.go
tests/operator_test.go

Finally - the moment we've all been waiting for... :smiley: 
When live migration feature was first presented to Kubevirt, it was immature and unstable. Over time, the situation had drastically changed.
Currently, Live migration is a mature and stable feature. Therefore, it shouldn't be guarded by a feature gate anymore. Now, that we have a [deprecation policy for feature gates](https://github.com/kubevirt/kubevirt/pull/7791), it's time to deprecate this feature gate.
For more information, take a look at the new deprecation policy here: https://github.com/kubevirt/kubevirt/blob/main/docs/deprecation.md
```release-note
Deprecate live migration feature gate
```

Deprecate live migration feature gate

---

hack/common.sh

In order to make the code easier to maintain
and agnostic of custom socket path,
use `KUBEVIRTCI_PODMAN_SOCKET`.
See https://github.com/kubevirt/kubevirtci/pull/833
for more details.
Fixes #
```release-note
None
```

podman: Use kubevirtci's KUBEVIRTCI_PODMAN_SOCKET

---

pkg/virt-handler/cgroup/cgroup.go
pkg/virt-handler/cgroup/cgroup_test.go
pkg/virt-handler/cgroup/cgroup_v1_manager.go
pkg/virt-handler/cgroup/cgroup_v2_manager.go
pkg/virt-handler/cgroup/generated_mock_cgroup.go

This PR aims to adress this issue https://github.com/kubevirt/kubevirt/issues/8122 that was introduced after this PR https://github.com/kubevirt/kubevirt/pull/8073.
Essentially, our cgroup package wraps runc's cgroup `Manager` interface. This underlying manager was not mocked properly, therefore causing errors when a v2 environment was trying to run v1 tests locally.
Now the underlying interface is properly mocked.
Fixes #
https://github.com/kubevirt/kubevirt/issues/8122
```release-note
Fix cgroups unit tests: mock out underlying runc cgroup manager
```

Fix cgroups unit tests: mock out underlying runc cgroup manager

---

automation/release.sh

As part of the tests suites publish on the release the dump binary so
reporter can be used by other projects that consume kubevirt too.
```release-note
NONE
```

cmd, dump: Publish k8s reporter dump

---

OWNERS_ALIASES
hack/OWNERS
pkg/monitoring/perfscale/OWNERS
tests/performance/OWNERS
tools/OWNERS

SIG-scale maintains tooling in /hack /tools and /tests/performance and some code in /pkg/monitoring/perfscale.  Add approvers and reviewers for this code to the owners file.
```release-note
NONE
```

Add scale OWNERS

---

tools/perfscale-load-generator/watcher/watcher.go

This helps in asserting the Delete semantics of the api during
performance testing. It is required that when Delete request is processed
against kubevirt api objects (VMI, VM and VirtualMachineReplicaSet),
kubevirt system is able to observe the complete garbage collection
(from delete request all the way to finalizer being removed and object being
removed from the kube api)
In order to avoid stomping apiserver with get requests from the e2e test suite
a further optimization of introducing a cache is required
Fixes #8025 
```release-note
Wait …
```

Add isGarbageCollected to perfscale-load-generator ObjListWatcher

---

tests/storage/clone.go

This PR https://github.com/kubevirt/kubevirt/pull/8120 solved flakieness of "simple clone" functest.
Following [this process](https://github.com/kubevirt/kubevirt/blob/main/docs/quarantine.md), since 3 days passed without failures, we can remove the quarantine.
**Useful links:**
Test grid: https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.24-sig-storage&width=20&show-stale-tests=
CI search: https://search.ci.kubevirt.io/?search=.*with+a+simple+clone.*&maxAge=48h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
```release-note
NONE
```

De-quarantine simple clone functest

---

pkg/virt-api/webhooks/hyperv.go
pkg/virt-controller/watch/topology/BUILD.bazel
pkg/virt-controller/watch/topology/hinter.go
pkg/virt-controller/watch/topology/tsc.go
pkg/virt-controller/watch/topology/tsc_test.go
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go
pkg/virt-launcher/virtwrap/converter/converter.go
tests/BUILD.bazel
tests/migration_test.go

Manual backport of this PR: https://github.com/kubevirt/kubevirt/pull/7986.
```release-note
[Bug-fix]: Windows VM with WSL2 guest fails to migrate
```

[release-0.53] [Bug-fix]: Windows VM HyperV Reenlightenment enabled fails to migrate

---

pkg/virtctl/scp/BUILD.bazel
pkg/virtctl/scp/native.go
pkg/virtctl/scp/native_unsupported.go
pkg/virtctl/ssh/BUILD.bazel
pkg/virtctl/ssh/knownhosts.go
pkg/virtctl/ssh/knownhosts_test.go
pkg/virtctl/ssh/native.go
pkg/virtctl/ssh/native_unsupported.go
pkg/virtctl/ssh/resize_unix.go
pkg/virtctl/ssh/resize_windows.go
pkg/virtctl/ssh/ssh.go

By specifying the go build tag 'excludenative' the native ssh client in
virtctl is excluded from the build and the wrapped local ssh client is
always used instead.
https://github.com/kubevirt/kubevirt/pull/8192 is needed to be able to define the tag when building without bazel.
When building with bazel the build target in `.bazelrc` can be modified.
```release-note
None
```

virtctl: Add build tag to allow excluding native SSH

---

tests/migration_test.go

During the review of test failure, I noticed our famous false is not true and misleading line on where the assertion happened.
This PR is a clean-up PR. It is modifying the function `confirmVMIPostMigrationAborted` to use `*WithOffset`, removing a couple of redundant functions.
Fixes #
```release-note
NONE
```

Tests: Clean migration tests (part 1)

---

tests/libvmi/BUILD.bazel
tests/libvmi/cpu.go
tests/libvmi/memory.go

Split performance.go into cpu.go and memory.go to be more specific.
Follow up to #8161 
```release-note
None
```

libvmi: Split performance.go into cpu.go and memory.go

---

Makefile
hack/build-go.sh
hack/common.sh

This adds env variable KUBEVIRT_GO_BUILD_TAGS to hack/common.sh and
hack/build-go.sh, which allows to specify additonal go build tags when
not building with bazel. The tag 'selinux' is always present.
Example for adding additional tags to the default build:
export KUBEVIRT_GO_BUILD_TAGS=additionaltag1,additionaltag2
Resulting tags during build:
KUBEVIRT_GO_BUILD_TAGS=selinux,additionaltag1,additionaltag2
This is useful for e.g. https://github.com/kubevirt/kubevirt/pull/8193
```release-note
None
```

build-go.sh: Introduce KUBEVIRT_GO_BUILD_TAGS

---

go.mod

https://github.com/kubevirt/kubevirt/pull/8198 had previously introduced
a direct dependency [1] without rerunning deps-sync causing the
`pull-kubevirt-verify-go-mod` job to fail when ran [2].
[1] https://github.com/kubevirt/kubevirt/blob/03db26180e7afd2ff618e7aacbed71da0e903f2a/tools/analyzers/banncheck/banncheck.go#L8
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8172/pull-kubevirt-verify-go-mod/1552964985548705792
Fixes #
```release-note
NONE
```

Run make deps-sync to correct go.mod

---

pkg/virt-controller/services/template.go

This code simplifies the `templateService` `renderLaunchManifest` receiver function by doing two things:
- exports code into functions that will be called inline
- creates the `Pod.Spec` with as much info as possible, instead of initializing it with some, then update it with other
```release-note
NONE
```

Simplify template service

---

tests/pool_test.go

* Taking the VM pool scale tests out of quarantine - according to Testgrid these tests were passing the periodic lanes for a couple of weeks, hence taking them back as they proved to be stable.
* Improving the time it takes to run some of the VM pool tests -  the VM pool suite contains tests with running VMs. These tests only observe the statuses of the VMIs and the VM pool resources. They don't interact directly with the guest OS. Therefore we can use a diskless approach when a VM runs the "no bootable device" phase. It will save the time it takes to setup the container-disk.
**Special notes for the reviewer**:
* The minimum amount of RAM required to run SeaBIOS is 1M, I've decided to put 2Mi to be on …

[e2e tests] improvements in the VM pool suite

---

pkg/util/migrations/migrations.go
pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-handler/vm.go
pkg/virt-launcher/virtwrap/BUILD.bazel
pkg/virt-launcher/virtwrap/live-migration-source.go
tests/libnode/BUILD.bazel
tests/libnode/node.go
tests/migration_test.go
tests/utils.go
tests/virt_control_plane_test.go

This PR fixes a bug related to aborting live migrations:
When a migration starts and the target pod cannot be scheduled the migration is stuck. In this situation, if the migration is aborted (which is achieved via deleting the relevant VMIM object), the migration will hang forever and wouldn't be able to be deleted.
The core problem is that we do not have a mechanism to abort a migration before the target pod starts running. Therefore, the current situation is:
* A finalizer is attached to the VMIM, which prevents its deletion. The finalizer is removed only once the the migration is final, which means it's either failed or succeeded.
* virt-contoller's migration controller waits for the target pod to be running before handling abort logic
* …

[Live-Migrations / Bugfix]: Allow aborting non-running migrations

---

pkg/controller/controller.go
pkg/util/types/patch.go
pkg/virt-controller/watch/drain/disruptionbudget/BUILD.bazel
pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
pkg/virt-controller/watch/migration.go
tests/BUILD.bazel
tests/infra_test.go
tests/instancetype_test.go
tests/pool_test.go
tests/replicaset_test.go
tests/storage/BUILD.bazel
tests/storage/datavolume.go
tests/storage/export.go
tests/storage/restore.go
tests/storage/snapshot.go

The execution of the e2e tests are producing a large amount of conflict errors [1].
There are two methods for updating an object manifest on the API server:
- Update
- Patch
Update is used to change the whole object and can detect conflicts when using the `resourceVersion`.
Patch is used to change only a subset of the object and comes in several flavors.
This change suggests replacing all `Update` operations with `Patch` ones in the e2e tests.
It should reduce the conflict/collisions experienced as the tests will no longer race with various controllers that touch the objects being changed. When using `Update`, a conflict may manifest itself even when the test changes a spec value and a controller in parallel changes a status value.
Using `Patch` …

tests: Replace `Update` with `Patch`

---

tests/utils.go
tests/vmi_monitoring_test.go

The function is reimplemented using libvmi, making the code shorter and
more readable while making tests/utils.go shorter.
```release-note
NONE
```

tests: re-implement NewRandomVMIWithWatchdog

---

tests/mdev_configuration_allocation_test.go

Currently we are checking if devices are created once.
This patch extends this to perform this check multiple
times.
This should fix failures
```
Timed out after 180.001s.
Pod/test-all-mdev-createdvs54c expected phase is 'Succeeded' but got 'Failed'
```
Fixes #
```release-note
NONE
```

Tests mdev: Check periodically for created devices

---

hack/prom-rule-ci/prom-rules-tests.yaml
pkg/virt-operator/resource/generate/components/prometheus.go

The assumption that the `kube_pod_status_ready` metric with `condition="true"` doesn't return values when the pod is unready was wrong. The metric shows all pods, but pods that are ready has Value=1, non-ready pods - Value=0.
This PR updates the `OrphanedVirtualMachineInstances`  alert when virt-handler pod is unready.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2052556
The query verifies that the nodes have a virt-handler and that it is in ready state, only for nodes that have running VMs on them. …

Update orphaned vm alert

---

tests/io_utils.go

sysfs provides us the information as well, let's read that.
redhat has a slightly differently built virt-handler/nodes which end up with no lsscsi, causing this test to fail.
lsscsi isn't required for kubevirt functionality, and we can make it optional for the tests too.
```release-note
NONE
```

Alter scsi test code to work without the lsscsi binary

---

api/openapi-spec/swagger.json
pkg/network/setup/netstat.go
pkg/network/setup/netstat_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/network/BUILD.bazel
tests/network/vmi_infosource.go
tests/vmi_multiqueue_test.go

Multi queue will configure only virtio interfaces.
Kubevirt won't reject VMs without virtio interfaces when multi queue is configured.
It is now best effort, i.e enable multi queue when it makes sense instead
enable it at all costs.
In order to expose what is the actual configuration per interface,
add `queueCount` field to vmi.status.interfaces.
The field specifies how many queues are configured per interface
if it can be determined.
It can't determine it for interfaces that are reported by guest-agent only.
In this case it will be omitted.
Fixes https://github.com/kubevirt/kubevirt/issues/7671 …

virt-api: relax networkInterfaceMultiqueue semantics, introduce queueCount

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-handler/container-disk/mount.go
pkg/virt-handler/isolation/isolation.go
tests/vmi_kernel_boot_test.go

This PR aims to resolve an issue that was discovered involving booting from external source functionality. Currently, Kubevirt provides the ability for the user to specify options for booting directly from a kernel/initrd as part of the VM spec. An issue was identified in which scenarios where the user opts to boot from a kernel (`kernelPath` argument provided) but does not have a need to specify a path for initrd, the verification of kernel artifact mount success will fail. 
Fixes #
fixes #8191
```release-note
NONE
```

Corrected issue with external boot which only kernelPath is specified without initrd path

---

api/openapi-spec/swagger.json
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/vmi_configuration_test.go
tests/vmi_lifecycle_test.go

Signed-off-by: janeczku <jabruder@gmail.com>
Depends on: https://github.com/kubevirt/kubevirt/pull/7845
Use case:
To achieve high availability as well as efficient resource utilization a given set of VM instances should be distributed evenly across cluster failure domains.
Solution:
This PR adds support for configuring [Topology Spread Constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) for virtual machine and replica set resources, allowing a user to control how related VMIs are spread across failure-domains such as availability zones, nodes, and other user-defined topology domains.
Example usage:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstanceReplicaSet
metadata:
name: mssql2016
spec: …
```

Support topology spread constraints for virtual machine instances

---

tests/vmi_configuration_test.go
tests/vmi_lifecycle_test.go

Using libvmi instead of NewRandomVMI functions.
Add options to libvmi in order to use libvmi builder pattern in functional tests instead of NewRandomVMI functions.
Fixes #
```release-note
NONE
```

code cleanup: Use libvmi builder pattern instead of NewRandomVMI functions.

---

tests/instancetype_test.go

Use libvmi builder pattern in tests/instancetype_test.go.
Use less resources in the test to be more resources efficiency.
Fixes #
```release-note
NONE
```

Code clean: Use libvmi builder pattern in tests/instancetype_test.go

---

tests/storage/datavolume.go

Using libvmi instead of NewRandomVMI functions.
Fixes #
```release-note
NONE
```

code cleanup:Using libvmi instead of NewRandomVMI functions in test_id:4643,test_id:4644

---

automation/test.sh
tests/README.md
tests/vmi_lifecycle_test.go

Tests that require advanced/special storage capabilities are marked with `[storage-req]`;
Currently, [storage-req] tests from all SIGs are added to each lane that uses rook-ceph.
We might want to revisit that, as it does not make much sense for sig-migrations (for example)
to run sig-storage tests.
The sig-migrations tests which have [storage-req] will continue to run as these are a subset.
If and when we introduce other less "advanced" storage lanes
we could capitalize on [storage-req] to skip these.
Fixes # …

Stop including all [storage-req] tests in lanes

---

pkg/virtctl/guestfs/guestfs.go

Set the RunAsNonRoot to false by default
Fixes #
```release-note
Set RunAsNonRoot as default for the guestfs pod
```

guestfs: set the RunAsNonRoot

---

tests/libnode/node.go

This is blocking the conformance tests, which run in a sonobuoy pod,
which do not have the `kubectl` binary installed.
A follow-up PR will sort out this mess, and properly uncordon the node via
the API - leaving user-cordoned nodes out of the ordeal.
Fixes #
```release-note
NONE
```

libnode, e2e tests, teardown: ignore errors when uncordoning nodes

---

tests/libvmi/cloudinit.go
tests/libvmi/network.go
tests/network/primary_pod_network.go
tests/network/sriov.go
tests/network/vmi_istio.go
tests/network/vmi_multus.go
tests/network/vmi_networking.go
tests/utils.go

A casual reader finds it hard to understand what is "false" in
WithCloudInitNoCloudNetworkData(networkData, false)
This can be solved by introducing a named argument or even an
enumeration for encoding. However, none of our tests wants to set the
"true" value, so let us just drop the b64Encoding argument and make the
function and its users simpler.
```release-note
NONE
```

libnet: avoid WithCloudInitNoCloudNetworkData's boolean arg

---

pkg/virt-handler/container-disk/mount.go

When we are performing unmount we may already find a record that is not mounted. Skip this record instead of looping on it.
Fixes #
```release-note
NONE
```

Fix containerdisk unmount logic

---

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
pkg/virt-api/webhooks/validating-webhook/admitters/validate-k8s-utils.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

Signed-off-by: Alay Patel <alayp@nvidia.com>
This PR adds validation for spec.topologySpreadConstraints field which was introduced in #7846 
Fixes #8250 
```release-note
add server-side validations for spec.topologySpreadConstraints during object creation
```

add validations for spec.topologySpreadConstraints

---

pkg/network/setup/netstat.go
pkg/network/setup/netstat_test.go
pkg/network/vmispec/interface.go
pkg/network/vmispec/interface_test.go
pkg/network/vmispec/network.go
tests/network/BUILD.bazel
tests/network/kubectl.go

Signed-off-by: Diana Teplits <dteplits@redhat.com>
Currently "kubectl get vmis" API return details of the first interface in Status.Interfaces list.
In case primary interface exist but is not the first one in the list, the user will not receive it's details.
This PR adds a change that makes sure that once primary interface exist, it will always be returned as a result of "kubectl get vmis" API call.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2093996
```Having primary interface defined in vm spec, it will always appear first in …
```

network: Primary intefrace should be first in Status.Interfaces list

---

tests/storage/datavolume.go

Follow up for #4277 basically, we probably just forgot to remove this one;
We definitely allow and start the VM if someone chose to use a DV's underlying PVC.
This is "accidentally" passing because we use Eventually instead of Consistently.
Fixes #
```release-note
NONE
```

Delete test that checks underlying DV's PVC won't trigger VM start

---

tests/monitoring/BUILD.bazel
tests/monitoring/monitoring.go

Add e2e test for KubeVirtVMIExcessiveMigrations alert
```release-note
NONE
```

Add e2e test for KubeVirtVMIExcessiveMigrations alert

---

tests/vmi_configuration_test.go

Qemu binary may have different names depending on the base container
image used by virt-launcher. E.g. qemu-kvm or qemu-system-x86_64. Try
to handle that by considering also the qemu-system-* prefix when looking
through the list of running processes.
Fixes #
This test currently fails in our downstream CI because the qemu proccess has different name.
```release-note
NONE
```

Tests: Handle various names of the qemu binary

---

tests/testsuite/manifest.go

We had a situation in e2e where we hit the 'Test Panicked'
assertion but without a stack trace or an error message.
The reason was that panic(err) was called with err being nil.
This patch fixes the err assignment
**Fixes #**
Situations that lack stack trace i.e.:
```
tests/tests_suite_test.go:92
Test Panicked
tests/util/util.go:19
```
```release-note
NONE
```

[e2e]: Fix a panic call in BeforeSuite

---

tests/libnode/BUILD.bazel
tests/libnode/node.go
tests/migration_test.go

**What this PR does / why we need it**:   
`libnode` is relying on `kubectl uncordon` to make the node
schedulable again - this fails on the conformance lanes executed on the
kubevirtci project, since the sonobuoy container where the conformance
tests are executed do **not** have the kubectl binary.
Uncordoning a node is, quite literaly, making it schedulable - something
which is achieving by setting the `node.Spec.Unschedulable` flag to
false - which is already being done in the stategic-merge patch command
being sent to the API [some lines below](https://github.com/kubevirt/kubevirt/blob/cdbc0a94a93ec5a758cde487edc62499ae2ff84f/tests/libnode/node.go#L107).
Furthermore, one of the tests - `test_id:6982` - was missing tainting the node with
`NoSchedule` effect, which would cause the test …

e2e tests, libnode: only uncordon node once

---

pkg/virt-handler/device-manager/mediated_device.go

Recently we observed issues where we allocate devices but virt-launcher doesn't see them. We can see that devices disappear but we don't know why. Let's improve logging and the logic to hopefully gain more insights.
Fixes #
```release-note
NONE
```

Vgpu check mdev is present on allocation 

---

tests/libstorage/pvc.go
tests/reporter/kubernetes.go
tests/tests_suite_test.go
tests/testsuite/fixture.go
tests/testsuite/manifest.go

- Add storage class/csidriver logging
- Avoid deleting test manifests on all ginkgo nodes
`SynchronizedAfterSuite` takes two function arguments. The first func runs on all nodes; the second runs only on parallel node 1,
and only after all other nodes have finished and exited.
We only want to delete manifests such as `disks-images-provider` in the second function we pass.
- Random PV name to avoid AlreadyExist in recreation
`TestCleanup()` is cleaning up PVs. A potential issue is that when we recreate PVs, we'll back off if they AlreadyExist;
Consider the following:
1. DELETE is called on alpine-host-path-disk-for-tests-ns1.
2. PV sticks around for a few extra seconds (Terminating phase)
3. CREATE attempt of alpine-host-path-disk-for-tests-ns1 …

Address some parallel testing complications that cause flakes

---

hack/prom-rule-ci/prom-rules-tests.yaml
pkg/virt-operator/resource/generate/components/crds.go

This is a manual cherry-pick of #7372 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2118317
/assign @enp0s3 
```release-note
NONE
```

[release-0.44] Fix `KubeVirtComponentExceedsRequestedMemory` alert on duplicate series

---

tests/network/vmi_istio.go
tests/network/vmi_passt.go

This PR skips Paast e2e tests if the Passt featureGate is disabled.
This skip also affects tier1 tests running on d/s clusters.
Fixes #
```release-note
NONE
```

paast, e2e, Skip if featureGate is disabled

---

pkg/virt-api/webhooks/BUILD.bazel
pkg/virt-api/webhooks/amd64.go
pkg/virt-api/webhooks/arm64.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
pkg/virt-launcher/virtwrap/converter/BUILD.bazel
pkg/virt-launcher/virtwrap/converter/converter_test.go
staging/src/kubevirt.io/api/core/v1/defaults.go

As SATA is not supported by qemu-kvm in virt-launcher of Arm64, set scsi as default bus for disk.
Fix vmi-mutator_test errors
```release-note
none
```
@rmohr 
Currently, there are three place to do CPU arch specific modification, 
1. in the `virt-api webhooks`, set DefaultCPUModel, DefaultBootloader and DefaultDisksBus
2. in the `virt-config/configuration.go`, set DefaultOVMFPath, DefaultEmulatedMachines and DefaultMachineType
3. in the `virt-launcher/virtwrap/converter/converter.go`, set `AutoattachGraphicsDevice`, `OS.SMBios` and ` domain.Spec.Devices.Controllers`
Is it better to manage them in one place? What your opinion?

set scsi as default disk bus on Arm64

---

api/openapi-spec/swagger.json
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/schema.go
staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/libvmi/storage.go
tests/migration_test.go
tests/storage/storage.go

Fixes #
```release-note
Add support for USB disks
```

Add support for USB Disks

---

tests/network/vmi_istio.go

This commit uses tests.RunVMIAndExpectLaunch function to
create VMI and wait for it to be running, before calling console.LoginToAlpine, because attempting to log in the VMI
causes flakes when the VMI isn't running.
Fixes flake: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7007/pull-kubevirt-e2e-k8s-1.22-sig-network/1559831970916077568
```release-note
NONE
```

e2e, istio: Wait for VMI to launch before Logging in

---

docs/metrics.md
tools/doc-generator/doc-generator.go

Update kubevirt_vmi_memory_used_bytes recording rule type to gauge.
It was set to counter by mistake. The recording rule is calculated based on gauge metrics.
Fixes #
```release-note
NONE
```

Update kubevirt_vmi_memory_used_bytes type

---

tests/instancetype_test.go

Unfortunately these assertions and their use of the default MachineType
of `q35` hid bug #8338 upstream where a MachineType is always provided
by the VirtualMachine mutation webhook [1] thus causing
PreferredMachineType to never be applied later by the VirtualMachine
controller [2].
This change removes these assertions while we look into a complete
bugfix, likely requiring looking up preferences within the
VirtualMachine mutation webhook to ensure they supersede any
configuration defaults.
[1] https://github.com/kubevirt/kubevirt/blob/bcfbd78d803e9868e0665b51878a2a093e9b74c2/pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go#L98-L112
[2] https://github.com/kubevirt/kubevirt/blob/bcfbd78d803e9868e0665b51878a2a093e9b74c2/pkg/instancetype/ins …

instancetype: Drop PreferredMachineType test assertions

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
tests/container_disk_test.go

This test ensures we don't let users create VMIs with relative disk paths
Fixes #
```release-note
NONE
```

Add a functional test to ensure we catch bogus disk paths

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/vmi_configuration_test.go

In some deployment, virtlogd was seen using just a bit more than 17Mi (17468Ki).
Bumping its overhead to the next Mi should address that, with some room to grow.
Testing on this PR revealed that libvirtd can reach 35400Ki.
Added a commit to bump its overhead to 35Mi.
Fixes RHBZ#2111794
```release-note
NONE
```

Bump virtlogd memory requirement to 18Mi and libvirtd to 35Mi

---

pkg/virt-handler/vm.go

When using legacy matching for Guest Agent compatibility, if a matching version is not found, the status condition didn't specify a reason why it was applied.
```release-note
NONE
```

Legacy GAVersion matching did not report a reason for failure

---

manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-operator/resource/generate/rbac/controller.go

Was seen before with https://github.com/kubevirt/kubevirt/pull/6957/commits/6ac5d6223f70b9bc876f5d5caa2d062ab4bc92a3;
Basically, OpenShift deploys enforcement that says we `cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on`.
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
Fixes #
```release-note
NONE
```

Fix VMClone OpenShift owner reference requirement

---

pkg/network/driver/common.go
pkg/network/driver/generated_mock_common.go
pkg/network/infraconfigurators/masquerade.go
pkg/network/infraconfigurators/masquerade_test.go
pkg/util/sysctl/sysctl.go

This commit adds handler method for enabling route_localnet
sysctl option. This option enables/disables routing of
127.0.0.0/8 traffic.
This option is required in the following scenario for VMs with masquerade interface:
- kubectl port-forward
- Istio service mesh
Since we only need to enable this for the in-pod bridge, enabling
this option doesn't allow martian traffic to leave the virt-launcher
pod.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2081306
IPv6 doesn't have an alternative to route_localnet …

istio,handler: enable ipv4 route_localnet for k6t-eth0

---

pkg/virtctl/ssh/wrapped.go

This changes the verbosity of the wrapped ssh command to 3 so it is no
longer logged by default.
```release-note
virtctl: Do not log wrapped ssh command by default
```

virtctl: Do not log wrapped ssh command by default

---

tests/usbredir_test.go
tests/vmi_configuration_test.go

Add options to libvmi in order to use libvmi builder pattern in functional tests instead of NewRandomVMI functions.
Using libvmi instead of NewRandomVMI functions.
Fixes #
```release-note
NONE
```

code cleanup: Use libvmi builder pattern instead of NewRandomVMI function

---

pkg/virt-operator/resource/generate/components/prometheus.go

This PR updates recording rules names which don't meet the naming convention. Recording rules should follow the same naming conventions as metrics (i.e. have a `kubevirt_` prefix).
These are the suggested changes:
`num_of_allocatable_nodes` --> `kubevirt_allocatable_nodes_count`
`num_of_kvm_available_nodes` --> `kubevirt_kvm_available_nodes_count`
Signed-off-by: assafad <aadmi@redhat.com>
```release-note
None
```

Update recording rules names

---

api/openapi-spec/swagger.json
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
pkg/virt-operator/resource/generate/components/crds.go
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

VirtualMachineInstancePresets are based on the PodPresets k8s resource
and API that injected data into pods at creation time. However this API
never graduated from alpha and was removed in 1.20 [1]. While useful
there are some issues with the implementation that have resulted in
alternative approaches such as  VirtualMachineInstanceTypes and
VirtualMachinePreferences being made available within KubeVirt.
As per the CRD versioning docs this change updates the generated CRD
definition of VirtualMachineInstancePreset marking the currently
available versions of v1 and v1alpha3 as deprecated.
[1] https://github.com/kubernetes/kubernetes/pull/94090
[2] https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning …

Deprecate VirtualMachineInstancePresets

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/vmi_configuration_test.go

This is a manual backport of https://github.com/kubevirt/kubevirt/pull/7264
This commit effectively addresses a TODO in the memory overhead calculation for virt-launcher.
It replaces an arbitrary overhead value with the observed memory usage of each process running inside virt-launcher.
A test also ensures we catch any future growth.
```release-note
NONE
```

[release-0.49] virt-launcher: adjust overhead calculation for processes

---

cmd/virt-freezer/main.go
tests/storage/snapshot.go

Currently, velero will consider backups partially failed if a VM does not contain a guest agent.  Not very user friendly, especially when you consider that always add the hook annotations to virt-launcher pods.
Fixes #7750
```release-note
NONE
```

virt-freezer exit 0 if no guest agent

---

pkg/virt-config/configuration_test.go
pkg/virt-config/feature-gates.go
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go
tests/network/sriov.go

Following https://github.com/kubevirt/kubevirt/pull/5558, virt-launcher doesn't execute with the `SYS_RESOURCE` capability anymore, thus `SRIOVLiveMigration` feature-gate is redundant.
~~SR-IOV live migration will be controlled by `LiveMigration` feature-gate similar to non-SR-IOV VMs.~~
Fixes #
- SRIOVLiveMigration feature gate was introduced by #4874
- `virt-launcher` is no longer executed with `SYS_RESOURCE` capability by #5558
- Once virt-handler pods are upgraded, migrating old SR-IOV VMs will not be blocked …

Remove SRIOVLiveMigration feature-gate

---

pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go
tests/vmi_configuration_test.go

It appears that we are incorrectly setting the guest memory to equal `resources.limits.memory`.
VMI specs that don't explicitly provide a value for `domain.memory.guest`
and provide different values for resources requests and limits will be converted to a domain definition where guest memory equals `resources.limits.memory`.
From my recollection, we used to have a vmi mutator webhook that set the correct value, but I don't see it right now.
```release-note
fix the guest memory conversion by setting it to resources.requests.memory when guest memory is not explicitly provided 
```

fix guest memory setting

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/vmi_configuration_test.go

This is a manual backport of https://github.com/kubevirt/kubevirt/pull/7264
This commit effectively addresses a TODO in the memory overhead calculation for virt-launcher.
It replaces an arbitrary overhead value with the observed memory usage of each process running inside virt-launcher.
A test also ensures we catch any future growth.
```release-note
NONE
```

[release-0.44] virt-launcher: adjust overhead calculation for processes

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/vmi_configuration_test.go

Tests discover that 150Mi is not enough for the 2 virt-launcher processes.
Also, we need 17Mi for the virtlogd process.
This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/8011 and https://github.com/kubevirt/kubevirt/pull/7685
Fixes #
```release-note
NONE
```

[release-0.49] virt-launcher overhead: bump virtlauncher and virtlogd

---

pkg/controller/virtinformers.go
pkg/storage/export/export/BUILD.bazel
pkg/storage/export/export/export.go
pkg/storage/export/export/export_test.go
pkg/storage/export/export/links.go
pkg/storage/export/export/pvc-source.go
pkg/storage/export/export/pvc-source_test.go
pkg/storage/export/export/vm-source.go
pkg/storage/export/export/vm-source_test.go
pkg/storage/export/export/vmsnapshot-source.go
pkg/storage/export/export/vmsnapshot-source_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmexport-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmexport-admitter_test.go
pkg/virt-controller/watch/application.go
pkg/virt-controller/watch/application_test.go
tests/libstorage/datavolume.go
tests/storage/export.go
tests/storage/restore.go

Add VM source type to VMExport object CRD, including all needed code to support it in the controller and admission webhooks. The export will not start if a running VM is detected (VMI exists) and will be stopped if a VMI is detected associated with the VM after the export started.
Fixes #
Addressed the style comment noted in the VMSnapshot PR.
```release-note
VirtualMachineExport now supports VM export source type.
```

Add vm export vm

---

hack/builder/build.sh

On Fedora 36, setting up support for building multiarch containers in Docker using the multiarch/qemu-user-static container image doesn't work as intended. Specifically, running
```
$ docker run --platform=linux/aarch64 --rm alpine uname -m
```
doesn't produce any output and results in the SELinux error
```
avc: denied { read } for comm="uname" path="/usr/bin/qemu-aarch64-static"
```
Installing the qemu-user and qemu-user-binfmt packages results in being able to successfully run container images for foreign
architectures, but since we currently run the container-based qemu-user setup unconditionally, that will get blown away as soon as `make builder-build` is executed and the build will not be able to complete successfully.
Fix this by only running …

builder: Don't set up multiarch support multiple times

---

tests/network/sriov.go
tests/utils.go

SR-IOV tests execution on CI has shown flakes where the VF configuration
has been modified after assigning the device to the pod.
The primary suspect is a CNI DELETE instruction from a previous pod
which is somehow racing with the re-assignment of the device to the new
pod.
In order to mitigate this suspected issue (and as side effect, prove it)
this change assures the VMI/s used with SR-IOV are deleted and absent
before starting the next test.
Fixes #
~Depends on #8299 (only the last 2 commits are relevant)~
```release-note
NONE
```

tests, sriov: Wait for VMI removal at test teardown

---

tests/migration_test.go

`test_id:1862` tends to fail due to the following error during VM boot:
```
Cloud-init v. 22.2 running 'init' at Sun, 07 Aug 2022 15:03:53 +0000. Up 46.66 seconds.
ci-info: ++++++++++++++++++++++++Net device info++++++++++++++++++++++++
ci-info: +--------+-------+---------+------+-------+-------------------+
ci-info: | Device |   Up  | Address | Mask | Scope |     Hw-Address    |
ci-info: +--------+-------+---------+------+-------+-------------------+
ci-info: |  eth0  | False |    .    |  .   |   .   | 52:54:00:a8:54:b5 |
ci-info: |   lo   | False |    .    |  .   |   .   |         .         |
ci-info: +--------+-------+---------+------+-------+-------------------+
ci-info: 
2022-08-07 15:03:53,983 - …
```

[e2e tests]: fix flaky migration test 1862

---

pkg/storage/export/export/export.go
pkg/storage/export/export/vmsnapshot-source.go
pkg/storage/export/export/vmsnapshot-source_test.go

Currently this is
```yaml
ownerReferences:
- apiVersion: v1alpha1
```
But we want
```yaml
ownerReferences:
- apiVersion: export.kubevirt.io/v1alpha1
```
This gets validated with https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
which is enabled in OpenShift, but disabled in our kubevirtci clusters.
Fixes #
```release-note
NONE
```

Fix export restore PVC owner reference

---

tests/testsuite/kubevirtresource.go

Recently live migration feature gate [was deprecated](https://github.com/kubevirt/kubevirt/pull/8047) according to the new feature gate [deprecation policy](https://github.com/kubevirt/kubevirt/pull/7791).
This policy dictates that whenever a feature get is being deprecated, a warning should pop up when explicitly enabling the feature gate. In our functional test suite, we enable live migration feature gate, therefore whenever functests are being run the following warning pops up:
`W0830 09:39:42.797978  103627 warnings.go:70] feature gate LiveMigration is deprecated, therefore it can be safely removed and is redundant. For more info, please look at: https://github.com/kubevirt/kubevirt/blob/main/docs/deprecation.md`
After this PR functests won't …

Stop enabling deprecated live migration feature gate as part of functional tests initialization

---

staging/src/kubevirt.io/client-go/kubecli/guestfs.go
staging/src/kubevirt.io/client-go/kubecli/version.go
staging/src/kubevirt.io/client-go/kubecli/vm.go
staging/src/kubevirt.io/client-go/kubecli/vmi.go

This PR relates to `virtctl` and its unability to use kubeconfigs provided by RANCHER. The underlying reason is that a RANCHER cluster URL will typically have a path describing the proxied cluster in the querystring (e.g. : `https://rancher-url/k8s/clusters/c-m-someid`) whereas Kubernetes cluster URLs typically have no path (e.g. : `https://192.168.3.3:6443
`)
As a consequence, using `virtctl` on RANCHER proxied clusters typically wrongly defines the URIs to use to call Kubernetes APIs. For example, calling `virtctl start xxx` on a RANCHER cluster would hit `https://rancher-url/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachines/xxx/start` instead of `https://rancher-url//k8s/clusters/c-m-someid/apis/subresources.kubevirt.io/v1a …

Rancher proxy uris

---

tests/infra_test.go
tests/migration_test.go

As stated in k8s 1.24 [changelog](https://github.com/kubernetes/kubernetes/blob/58c10aa6eb5adfb1f3aa4d6cb898b8c347ba9e72/CHANGELOG/CHANGELOG-1.24.md), kueadm would be migrated away from using the word `master`.
`node-role.kubernetes.io/control-plane` would be used instead.
Therefore some places in the e2e code were updated. Also refactored var names
where master word was used.
Fixes #
https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.24-sig-compute/1554882304050991104
```release-note
NONE
```

[e2e tests]: adapt tests to the master node-role label deprecation

---

manifests/testing/disks-images-provider.yaml.in

In some cases like in `test_id:4134` the toleration is being tested against
the cluster, and since the disk-images-provider is not part of the control-plane
components, it would be evicted.
Therefore I've added the toleration to improve stability during test runs.
Fixes #
https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.23-sig-compute/1555106282447310848
```release-note
NONE
```

[e2e]: add toleration to the disk-images-provider manifest

---

tests/BUILD.bazel
tests/tests_suite_test.go

Include the auth provider client library in the test_suite so users can leverage external auth processes to access kubernetes clusters.
fixes: #8392 
```release-note
NONE
```

Add auth clients to test suite

---

hack/dockerized

Signed-off-by: Brian Carey <bcarey@redhat.com>
An intermittent issue appears when testing kind based e2e jobs with
podman in CI[1]. The rsync container hits an error as the rsync daemon
fails to attach to the specified port. Adding a restart policy to
restart unless the container is stopped allows the vgpu lanes to run
successfully using podman.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-kind-1.23-vgpu/1564606226711449600
```release-note
NONE
```

Add restart policy to rsync container used in cluster-sync

---

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
pkg/virt-controller/services/template_test.go
pkg/virt-handler/node-labeller/cpu_plugin_test.go
pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
tests/infra_test.go
tests/network/vmi_infosource.go
tests/operator_test.go
tests/storage/export.go
tests/subresource_api_test.go
tests/vmi_gpu_test.go

Fix all cases with gomaga's Equal assertion to a boolean values.
`Equal(true)` ahould be `BeTrue()`
`Equal(false)` ahould be `BeFalse()`
```release-note
None
```

[Clean code] Equal(true/false) => BeTrue/BeFalse

---

docs/metrics.md
pkg/monitoring/domainstats/prometheus/prometheus.go
pkg/monitoring/domainstats/prometheus/prometheus_test.go

`kubevirt_vmi_memory_domain_total_bytes` and `kubevirt_vmi_filesystem_total_bytes` were not following the metrics naming convention that we are following in the other metrics. This PR renames them.
`kubevirt_vmi_memory_domain_total_bytes` -> `kubevirt_vmi_filesystem_capacity_bytes_total` 
`kubevirt_vmi_filesystem_total_bytes` -> `kubevirt_vmi_memory_domain_bytes_total`
```release-note
Rename metrics to follow the naming convention
```

Rename metrics to follow the naming convention

---

pkg/hotplug-disk/hotplug-disk.go
pkg/safepath/safepath.go
pkg/virt-handler/hotplug-disk/mount.go

Giving more details which path caused the error can improve the
debugging of the root cause.
Fixes #
This could help in debugging safepath related issue like for example: https://github.com/kubevirt/kubevirt/issues/8387
```release-note
NONE
```

safepath: improving error messages

---

tests/libstorage/BUILD.bazel
tests/libstorage/datavolume.go
tests/migration_test.go
tests/storage/datavolume.go
tests/storage/export.go
tests/storage/restore.go
tests/utils.go

- The node pull method is basically taking advantage of pulling images
the same way k8s would if you specified them in a pod's `container.image`:
https://github.com/kubevirt/containerized-data-importer/blob/main/doc/image-from-registry.md#import-registry-image-into-a-data-volume-using-node-docker-cache
It does not require scratch space so we should not see situations in CI
where there are 6 PVCs of 6Gi size each:
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7549/pull-kubevirt-e2e-k8s-1.23-sig-storage/1554905217219170304/artifacts/k8s-reporter/2/1_pvcs.log
Potentially exhausting all ceph capacity.
- Attempt to not use huge DV sizes where they are not needed. for example …

[e2e tests]: Less large PVCs during parallel testing

---

tests/io_utils.go

cherry-pick of https://github.com/kubevirt/kubevirt/pull/8204
Fixes #
```release-note
NONE
```

[release-0.49] Alter scsi test code to work without the lsscsi binary

---

pkg/virt-config/feature-gates.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go

A bug in docker (https://github.com/moby/moby/issues/41370) forces
us to implement a workaround in the SELinux options of virt-launcher.
This workaround (disabling categories on non-compute containers)
weakens the security of the project for all when it is only needed
for a very specific use-case: deployments on clusters
that have docker nodes with SELinux enforced on the system and
enabled in the docker configuration (it is disabled by default).
That bug was filed more than 2 years ago, so it is time to disable
the workaround by default, with a feature gate for those who need it.
Fixes # …

virt-launcher: add opt-in feature gate for docker bug workaround

---

pkg/virt-controller/watch/vm.go
pkg/virt-controller/watch/vm_test.go
tests/instancetype_test.go

/cc @akrejcir 
/cc @rmohr 
Until now ControllerRevisions for instancetypes and preferences had only
been created by the VirtualMachine controller when starting the
VirtualMachine and initially creating the VirtualMachineInstance. This
delay allowed users to potentially update or delete any referenced
instancetype or preference before a copy was made in a
ControllerRevision.
This change moves the creation of the ControllerRevisions to earlier
within the reconcile loop, ensuring they are created as soon as the
VirtualMachine is seen by the controller. This should help avoid
races with user modifications or removals that could then cause
the VirtualMachine to fail to launch at a later time.
A single VirtualMachine …

instancetype: Create ControllerRevisions earlier within VM reconcile loop

---

tests/vmi_kernel_boot_test.go

This test is causing impact to the sig-compute CI lanes due to flaky failures[1].
[1] https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2022-09-07-024h.html
The intermittent failure has been raised in the following issue:
https://github.com/kubevirt/kubevirt/issues/8423
Signed-off-by: Brian Carey <bcarey@redhat.com>
/cc @enp0s3  @xpivarc 
```release-note
NONE
```

Quarantine flaky test with external alpine-based kernel boot

---

cmd/virt-launcher/BUILD.bazel

Workaround for https://github.com/moby/moby/issues/44106
Need to create the directory upfront, otherwise it gets assigned wrong permissions when unpacked.
Fixes #8195, fixes #8362
The same directory with qemu modules is present in the aarch64 image. Applied the workaround there as well.
```release-note
NONE
```

Create /usr/lib64/qemu-kvm with proper permissions

---

staging/src/kubevirt.io/client-go/testutils/BUILD.bazel
staging/src/kubevirt.io/client-go/testutils/setup.go

This PR intends to make unit test results more explicit, and avoid nonsense like:
```
Expected
<string>: "...r": 0,
..."
to equal               |
<string>: "...r": 0
}
}..."
```
(see https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8344/pull-kubevirt-unit-test/1567932631205548032)
Fixes #
I'm open to suggestions for the maximum string length. 8192 seems like a good compromise to me.
```release-note
NONE
```

unit tests: disable string truncation in failed test output

---

pkg/util/types/patch.go
pkg/util/util.go
pkg/virt-controller/watch/topology/BUILD.bazel
pkg/virt-controller/watch/topology/generated_mock_hinter.go
pkg/virt-controller/watch/topology/hinter.go
pkg/virt-controller/watch/topology/hinter_test.go
pkg/virt-controller/watch/topology/tsc.go
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go
pkg/virt-handler/BUILD.bazel
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go
pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/converter_test.go
staging/src/kubevirt.io/api/core/v1/types.go
tests/windows_test.go

This is a follow-up to this PR: https://github.com/kubevirt/kubevirt/pull/7986. In this PR, I've explicitly provided QEMU with the lowest TSC frequency on the cluster since that's the only way such VMIs can be migratable.
However, sometimes (e.g. on some virtual nodes) TSC frequency is not exposed. In such cases, VMIs with Reenlightenment shouldn't be migratable - but they should be able to run.
In the above PR, an error occurs when trying to create a Reenlightenment VMIs when TSC frequency is not exposed on the cluster nodes. In this PR it would be started successfully, but wouldn't be able to migrate. …

[Bugfix]: HyperV Reenlightenment VMIs should be able to start when TSC Frequency is not exposed

---

pkg/storage/snapshot/snapshot.go

Ensure that the snapshot controller only updates the VM status when something changed.
Without this comparision, the snapshot controller is performing a REST operation after every trigger. This leads to the following behaviour:
* Every VM modification leads to a rest call by the snapshot controller.
* On ther periodic 5-minute reconcile by this controller a REST call is performed too.
This can easily be observed by watching this metric:
```
rest_client_request_latency_seconds_count{url="https://10.96.0.1:443/apis/kubevirt.io/v1alpha3/namespaces/%7Bnamespace%7D/virtualmachines/%7Bname%7D/status",verb="PUT"} 26
```
Even if the cluster is idle, the number of REST calls goes up by the number of existing VMs every 5 minutes.
**Which issue(s) this PR …

Stop updating volume snapshot status on every reconcile

---

tests/reporter/BUILD.bazel
tests/reporter/kubernetes.go

We fetch quite some resources. Increase the rate limiter a little bit, to shorten report times, which can otherwise easily be minutes.
Fixes #
```release-note
NONE
```

Increase rate limits for k8s test reporter

---

nogo_config.json

pkg/instancetype currently builds successfully without any errcheck errors and so can be removed from exclude_files.
Fixes #
```release-note
None
```

errcheck, instancetype: Remove pkg/instancetype from exclude_files

---

tests/testsuite/BUILD.bazel
tests/testsuite/namespace.go

With the deprecation of VirtualMachineInstancePresets by 16ca54f
warnings were previously printed during functional test runs cluttering
the output:
```
FUNC_TEST_ARGS='-focus=Instancetype -regexScansFilePath' make functest
[..]
W0830 12:16:53.681522 2907587 warnings.go:70] kubevirt.io/v1alpha3 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
[..]
```
This change introduces a simple warning handler that ignores this
deprecation warning when cleaning up namespaces. Warnings will still be
printed for tests that interact directly with the deprecated CRD.
Fixes #8381 …

tests: Ignore deprecation warnings when cleaning up namespaces

---

pkg/virtctl/guestfs/guestfs.go

Drop all the capabilities, set allowPrivilegeEscalation to false and
seccompProfile type to RuntimeDefault.
Fixes #
```release-note
NONE
```

guestfs: restrict container security context

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go

Signed-off-by: Xiaodong Ye <yeahdongcn@gmail.com>
Add the missing `break` in `validateEmulatedMachine`.
Fixes #
1. Correct several typos
2. Remove unnecessary use of `fmt.Sprintf`
```release-note
NONE
```

Add break in validateEmulatedMachine

---

pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/nodeselectorrenderer.go
pkg/virt-controller/services/nodeselectorrenderer_test.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go

This PR refactors the virt-controller templating service, introducing a builder pattern to generate the node selector attributes for the pod.
The ad-hoc generation of node selectors for the virt-launcher pod is replaced by a builder pattern, allowing the customization of the launcher spec via options.
It provides a simpler, more explicit way to achieve the same thing - requesting particular requirements from nodes at launcher pod scheduling time becomes easier to write, and a lot easier to read / reason about. 
Finally, the added unit tests are a chance to clearly document how to configure each of the relevant options. …

Refactor node selector

---

pkg/util/types/patch.go
pkg/util/util.go
pkg/virt-controller/watch/topology/BUILD.bazel
pkg/virt-controller/watch/topology/generated_mock_hinter.go
pkg/virt-controller/watch/topology/hinter.go
pkg/virt-controller/watch/topology/hinter_test.go
pkg/virt-controller/watch/topology/tsc.go
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go
pkg/virt-handler/BUILD.bazel
pkg/virt-handler/vm.go
pkg/virt-handler/vm_test.go
pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/converter_test.go
staging/src/kubevirt.io/api/core/v1/types.go
tests/BUILD.bazel
tests/windows_test.go

This is an manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/8359
**Reason for manual cherry-pick**
The main conflict was with node labeller test helper functions that did not exist in this release. Therefore, in commit https://github.com/kubevirt/kubevirt/pull/8452/commits/76bb414f43a4f3f6d2de13fa73e1780a3b4f3884 I've added them into the test's local scope. Aside from that, nothing significant is changed.
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2125985
```release-note
[Bugfix]: HyperV Reenlightenment VMIs should be able to start when TSC Frequency is not exposed
```

[release-0.53] [Bugfix]: HyperV Reenlightenment VMIs should be able to start when TSC Frequency is not exposed

---

tests/vmi_kernel_boot_test.go

Signed-off-by: Brian Carey <bcarey@redhat.com>
A large number of failures[1] have been seen in the following test: 
```
[sig-compute]VMI with external kernel boot with external alpine-based kernel & initrd images [test_id:7748]ensure successful boot
```
These flaky failures are causing impact to CI and the number of retests that are required.
A similar test was quarantined in https://github.com/kubevirt/kubevirt/pull/8428
[1] https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2022-09-12-168h.html#row0
Fixes #
/cc …

Quarantine test 7748 due to large number of flaky failures

---

tests/virtctl/scp.go
tests/virtctl/ssh.go

Some testing environment may have an older SCP, and thus not have the -O option.
I don't think there is a particular reason to opt for the legacy method:
https://wiki.archlinux.org/title/SCP_and_SFTP
```
Note: Since OpenSSH 8.8 the scp utility uses the SFTP protocol by default. The -O option must be used to use the legacy SCP protocol.
```
```
Warning: The scp protocol is outdated, inflexible and not readily fixed. Its authors recommend the use of more modern protocols like sftp and rsync for file transfer instead:
https://lists.mindrot.org/pipermail/openssh-unix-dev/2019-March/037672.html
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …

[e2e tests]: Use default scp protocol instead of explicitly using legacy

---

pkg/virt-handler/hotplug-disk/mount.go
pkg/virt-handler/hotplug-disk/mount_test.go
pkg/virt-handler/isolation/isolation.go

On a host with btrfs the source of the hotplug PVC mount may reside on a subvolume. E.g. on '/@' like in the example below:
```
bash-4.4# findmnt -T /local-pvc -N 19272 -J
{
"filesystems": [
{
"target": "/local-pvc",
"source": "/dev/sda2[/@/opt/local-path-provisioner/pvc-e316b528-46fd-43e8-a64a-ab0e0a54fcca_default_local-pvc]",
"fstype": "btrfs",
"options": "rw,relatime,space_cache,subvolid=262,subvol=/@/opt/local-path-provisioner/pvc-e316b528-46fd-43e8-a64a-ab0e0a54fcca_default_local-pvc"
}
]
}
```
To bind mount such a source, the subvolume '/@' needs to be resolved in the node's context. This fix reuses the functionality from isolation package and adds handling of such cases (similar to how it is done with containerdisks).
**Which issue(s) this PR …

Fix hotplug of FileSystem PVCs backed by btrfs

---

pkg/storage/export/export/export.go

This fixes the following container runtime error:
>  failed to generate user string: user group "107" is specified without user
Fixes #
Faced this error on `rke2` cluster (uses `containerd`). Not sure why the error is not reproducible in the CI. Maybe a different container runtime?
UPD: `containerd` explicitly validates the user/group combination in: https://github.com/containerd/containerd/blob/db3ecb286bd5f082d13ae9d5646f189a7d284805/pkg/cri/server/container_create_linux.go#L592
UPD2: https://github.com/kubernetes/cri-api/blob/2b5244cefaeace624cb160d6b3d85dd …

Drop RunAsGroup from the exporter pod manifest

---

tests/libvmi/storage.go
tests/nonroot_test.go
tests/storage/hotplug.go
tests/storage/restore.go
tests/storage/storage.go
tests/utils.go

This PR introduces new functions to libvmi and
changes the tests in tests/storage to use libvmi.
```release-note
None
```

Use libvmi in tests/storage

---

pkg/virt-handler/device-manager/generic_device.go
pkg/virt-handler/device-manager/mediated_device.go
pkg/virt-handler/device-manager/pci_device.go

Signed-off-by: Christopher Desiniotis <cdesiniotis@nvidia.com>
This is the recommended order when starting a device plugin. Additionally, this addresses issues seen on K8s 1.25. Without this change, all device plugins fail to start on K8s 1.25 and we see the following kubelet logs:
```
"Got registration request from device plugin with resource" resourceName="***" 
"Unable to connect to device plugin client with socket path" err="failed to dial device plugin: context deadline exceeded" path="/var/lib/kubelet/device-plugins/***.sock"
```
For an explanation on what changed in 1.25 concerning the device-plugin registration process, see the following: https://github.com/kubernetes/kubernetes/issues/112395.
**Which issue(s) this PR fixes** *(optional, in …

Start serving the device plugin API prior to registering with kubelet

---

pkg/instancetype/instancetype.go
pkg/instancetype/instancetype_test.go
pkg/virt-controller/watch/vm_test.go

/cc @akrejcir
/cc @davidvossel
Even after moving the creation of the instancetype CRs earlier in the
reconcile loop of the virt-controller there remained a small window
where updates to an instancetype after the VM had been accepted by the
API could result in undetected conflicts with the VM later at runtime.
This change seeks to remove this window entirely by preforming one final
check for conflicts using the copy of the instancetype that will be
stored in the CR.
Fixes #
This is a follow up from …

instancetype: Add one final check for conflicts before creating CRs 

---

pkg/controller/virtinformers.go
pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/snapshot_base.go
pkg/storage/snapshot/snapshot_test.go
staging/src/kubevirt.io/api/snapshot/v1alpha1/types.go

This should fix flakiness in test: [test_id:6837]delete snapshot after freeze, expect vm unfreeze
The issue presented there was:
deleting vmsnapshot-> deleting vmsnapshot content while the update content reconcile loop was during a wait for a call to the freeze source api command. In the CI it seems that sometimes the call can take longer time(~1s) to return. Once return there is the attempt to create the volumesnapshot that test added a fake webhook to make that call fail, hence the call returns error the reconcile loop is exited and when needing to call it again the content is already deleted.
In order to fix this issue we moved the remove of the content finalizer from the vmsnapshot reconcile to the vmsnapshotcontent reconcile which happens only …

Fix possible race when deleting unready vmsnapshot and the vm remaining frozen

---

tests/network/sriov.go

SRIOVLiveMigration feature gate has been removed so the test is not needed anymore.
Fixes #
```release-note
NONE
```

Drop SRIOVLiveMigration feature gate test

---

pkg/container-disk/container-disk.go

It appears that `ContainerStatuses[].Image` from the Pod spec cannot be used to reliably identify the name of the containerdisk image. E.g. while testing the bellow containerdisk:
```
quay.io/kubevirt/fedora-with-test-tooling-container-disk:v0.57.0
```
it was observed with `containerd` that `ContainerStatuses[].Image` may contain either an internal image ID in the form of:
```
sha256:e3559e53b6b1df866598887793f94b9908d3a7e343f4a6394670d69fbe511cb2
```
or the image can be resolved to an alias:
```
192.168.122.1:5000/fedora-with-test-tooling-container-disk@sha256:30750fe1f8936e21890a4e45289ec3afdbcae3d9072ec7d7629ec20f4afbd00e
```
This eventually breaks live migration, as such references cannot be resolved on the target node.
To solve the issue, the …

Use the containerdisk image name from the VMI spec

---

hack/cluster-deploy.sh

Prevent DV-related CI failures in the next kubevirt-bot kubevirtci bump PR (with bump-cdi), due to:
https://github.com/kubevirt/containerized-data-importer/pull/2421
Fixes #
```release-note
Enable DataVolume GC by default in cluster-deploy
```

Enable DataVolume GC by default in cluster-deploy

---

docs/release.md

KubeVirt has been released monthly since its early days, but it might be time to settle into a slower release cycle.  The high velocity of KubeVirt made sense to keep a monthly release cadence since the project's beginning.  There were key features KubeVirt needed in order to be production ready those features needed to get into customer hands as soon as possible.  However, KubeVirt has now reached production readiness, which is backed-up by the [many companies that use it in production](https://github.com/kubevirt/kubevirt/blob/main/ADOPTERS.md), so it might be time for the community to pivot.
For vendors and end-users, a monthly release cadence puts pressure on teams to upgrade constantly.  There's sometimes a security update, often new features, or some bug fixes that need to be rolled …

Change KubeVirt to follow the Kubernetes release guidance

---

pkg/virt-config/virt-config.go
pkg/virt-operator/application.go

Until now it wasn't possible to set virt-operator's verbosity. In fact, for all other components it's possible to set verbosity level through [log verbosity](https://kubevirt.io/api-reference/master/definitions.html#_v1_logverbosity) configurations in Kubevirt CR, but for some reason virt-operator did not support this, although a `virtOperator` configuration spec field existed, but as a no-op.
I also made a small refactoring in virt-api so that the logic of getting a component's verbosity level isn't duplicated for each and every component.
Fixes: …

Allow setting virt-operator log verbosity through Kubevirt CR

---

tests/network/BUILD.bazel
tests/network/probes.go

The guest agent liveliness probe was not tested before.
```release-note
None
```

probe: Add test for guest agent ping liveliness probe

---

tests/storage/snapshot.go

On 1.24 and thus OpenShift 4.11 v1beta1 is not going to be served anymore (deprecated), which means we will skip these tests.
On newer branches we had this fixed by https://github.com/kubevirt/kubevirt/pull/8173 (Can't cherry pick because its part of a bigger commit)
Fixes #
```release-note
NONE
```

[release-0.53] Snapshot tests: Partial backport of snapshot tests skip condition change

---

BUILD.bazel
cmd/example-disk-mutation-hook-sidecar/BUILD.bazel
cmd/example-disk-mutation-hook-sidecar/README.md
cmd/example-disk-mutation-hook-sidecar/diskimage.go
cmd/virt-launcher/virt-launcher.go
pkg/virt-controller/services/template_test.go
pkg/virt-handler/vm_test.go
pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go
staging/src/kubevirt.io/api/core/v1/schema.go
tests/storage/hotplug.go
tests/storage/snapshot.go
tests/utils.go

Signed-off-by: Prashanth Dintyala <vdintyala@nvidia.com>
#8237 fixed the scenario where `SyncVMI` is being called for the first time and new domain was being created. However, when `SyncVMI` is called subsequently, the `vmi *v1.VirtualMachineInstance` passed as input doesn't contain the disk mutation made by the hook as `hookManager.OnDefineDomain` is only called only when  `LookupDomainByName` returns `NotFound` error. The `getAttachedDisk`/`getDetachedDisk` compare the disks obtained from `dom.GetXMLDesc(0)`, containing disk mutation changes and `domain.Spec.Devices.Disks`, obtained from `vmi` passed as parameter which doesn't contain mutations by hook. This will result in incorrect detach/attach operation  and the VMI will fail to boot.
This PR: …

Fix hotplug with disk mutating sidecar; add integration tests

---

pkg/virtctl/portforward/portforward.go

This changes the verbosity of the port-forwarding destination in stdio mode to 3 so it is no logged by default.
In combination with https://github.com/kubevirt/kubevirt/pull/8326 the log output of `virtctl ssh` is now the same for the native and the wrapped ssh client.
```release-note
virtctl: Be less verbose when using the local ssh client
```

virtctl: Be less verbose when forwarding in stdio mode

---

tests/migration_test.go

By reusing the identifier 'disk0' the empty disk with 'DiskBusUSB' was never attached to the VM because of libvmi silently doing nothing when trying to re-add an existing disk with another bus type.
See https://github.com/kubevirt/kubevirt/pull/8348 for more information.
```release-note
None
```

tests/migration_test.go: Fix migration test with usb disk

---

tests/infra_test.go

Testing on FIPS-compliant clusters might fail miserably because the cipher we pick for testing purposes is not FIPS-friendly.
https://wiki.openssl.org/index.php/FIPS_mode_and_TLS
Fixes #
It seems the failure would occur on the top level afterEach so can't even clean up the cipher field,
potentially messing up an entire test suite
```release-note
NONE
```

[e2e tests]: Use FIPS compliant cipher in crypto cfg tests

---

tests/network/expose.go
tests/storage/clone.go
tests/storage/snapshot.go

The following tests were identified as flaky from the most recent weekly flakefinder report[1].
These flaky failures are leading to a large number of retests being required in order to merge PRs (>5 retests to merge) - quarantining these tests until the flakes have been resolved.
```
[sig-network] [rfe_id:253][crit:medium][vendor:cnv-qe@redhat.com][level:component]Expose Expose a VM as a service. Expose a VM as a ClusterIP service. [label:masquerade_binding_connectivity]Should Verify an exposed service of a VM is not functional after VM deletion. over IPv6 IP family
```
```
[sig-network] [rfe_id:253][crit:medium][vendor:cnv-qe@redhat.com][level:component]Expose Expose a VM as a service. Expose a VM as a ClusterIP service. …
```

Quarantine flaky network and storage tests that are causing high retests to merge

---

api/openapi-spec/swagger.json
pkg/storage/export/export/BUILD.bazel
pkg/storage/export/export/export.go
pkg/storage/export/export/export_test.go
pkg/virt-operator/resource/generate/components/validations_generated.go
pkg/virtctl/vmexport/vmexport.go
pkg/virtctl/vmexport/vmexport_test.go
staging/src/kubevirt.io/api/export/v1alpha1/deepcopy_generated.go
staging/src/kubevirt.io/api/export/v1alpha1/types.go
staging/src/kubevirt.io/api/export/v1alpha1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/storage/export.go

This PR introduces a new mechanism in the export controller so that when a VMExport with no `tokenSecretRef` is created, a corresponding secret is made using a name specific to the current object.
**Which issue(s) this PR fixes**: https://issues.redhat.com/browse/CNV-20651
**Special notes for your reviewer**: Work in progress
```release-note
Enable automatic token generation for VirtualMachineExport objects
```

Enable automatic token generation for VirtualMachineExport objects

---

tests/testsuite/fixture.go

There might not be pods for the daemonset yet at the time we check.
Resolves a flake where disks-images-provider is not yet ready in time
for running the tests.
This failure doesn't show up in our regular CI as the daemonset is also
deployed by `make cluster-sync` and has plenty of time to come up, but
will show up if we attempt to run the testsuite on a cluster deployed in
other means.
```release-note
NONE
```

Wait for daemonsets to be ready before starting the testsuite

---

OWNERS_ALIASES

Proposing Vasily as an approver for kubevirt/kubevirt.
Since his first contribution in Dez. 2020 (https://github.com/kubevirt/kubevirt/pull/4671), Vasiliy has been a steady and reliable contributor to KubeVirt.
He has more than 50 PRs merged: https://github.com/kubevirt/kubevirt/pulls?q=is%3Aclosed+is%3Apr+author%3Avasiliy-ul+
He helped reviewing and bringing in more than 50 PRs : https://github.com/kubevirt/kubevirt/pulls?page=2&q=is%3Apr+commenter%3Avasiliy-ul+is%3Aclosed+-author%3Avasiliy-ul
When you go through his contributions, you will see that he has deep knowledge on almost all areas of KubeVirt. He helped on the lowest layers (with container disk mount points, cgropus v1/v2), on the user-facing layers (e.g. rancher proxy, SEV, affinity …

Make vasiliy-ul an approver for kubevirt/kubevirt

---

pkg/virt-config/virt-config.go

It was observed that recently memory limit applied to virt-chroot is too low. This is an attempt to fix
this issue. Further profiling and optimization are needed.
Fixes #
```release-note
NONE
```

Increase DefaultDiskVerificationMemoryLimitMBytes

---

SECURITY.md

Clarifying how KubeVirt is supported by vendor security teams, removes the requirement for PGP encrypted vulnerability reporting.
Fixes #
Removal of PGP encryption got discussed offlist.
While it is less confidential, it is removing friction on the reporter side, as well as on the maintainer side - this benefit is considered to be more beneficial (aka faster and lower burden for reporters) besides the increased security of an encrypted email.
```release-note
NONE
```

SECURITY: Vulnerability reporting and vendor update

---

tests/mdev_configuration_allocation_test.go

These mediated devices tests have passed successfully in the last 12 runs of the periodic vgpu test lane[1] so they should be removed from quarantine.
[1]https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-kind-1.23-vgpu
```release-note
NONE
```
Signed-off-by: Brian Carey <bcarey@redhat.com>

Remove mediated devices tests from quarantine

---

pkg/util/util.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/rendercontainer.go
pkg/virt-controller/services/rendercontainer_test.go
pkg/virt-controller/services/rendervolumes.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/virtiofs.go
pkg/virt-controller/watch/migration.go
pkg/virt-handler/BUILD.bazel
pkg/virt-handler/vm.go
pkg/virt-launcher/virtwrap/api/schema.go
pkg/virt-launcher/virtwrap/converter/BUILD.bazel
pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/virtiofs.go
pkg/virtiofs/BUILD.bazel
pkg/virtiofs/virtiofs.go
tests/nonroot_test.go
tests/storage/storage.go

This work is based on https://github.com/kubevirt/kubevirt/pull/7570. It allows us to use virtiofs with Nonroot feature gate.
Fixes #
```release-note
Virtiofs can be used with Nonroot feature gate
```

Virtiofs:  Container approach

---

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
pkg/virt-api/webhooks/validating-webhook/admitters/vmexport-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmexport-admitter_test.go

Right now the validator will accept VMExports with local object references that have missing or invalid APIGroups. The controller will reject then and nothing happens, but no error message is generated for human users.
Fixes #
```release-note
NONE
```

Update VM export validator to take APIGroup into account

---

pkg/storage/snapshot/source.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
tests/storage/BUILD.bazel
tests/storage/snapshot.go

/cc @akrejcir
Previously the VirtualMachine validation webhook would attempt to apply
any referenced instancetype and preferences to the provided
VirtualMachineInstanceSpec within the VirtualMachine before validating
the contents. Doing so however would cause calls to
validateSnapshotStatus to fail when a snapshot was in progress as the
now updated VirtualMachineInstanceSpec differed from the original. In
issue https://github.com/kubevirt/kubevirt/issues/8435 this left the Snapshot controller unable to update the
VirtualMachine with a required finalizer, blocking the progress of the
overall snapshot.
This PR corrects this by applying any referenced instancetype and
preferences to a copy of the VirtualMachine and using this updated …

instancetype: Apply instancetype to copy of VM during admission

---

pkg/controller/virtinformers.go
pkg/storage/snapshot/snapshot_base.go

Revert "Add vm snapshot obj to queue in case of content deletion" With the exception of callback to handleVMSnapshotContent in case of delete.
This change wasn't required and also introduced a flakiness due to race of updating the content and updating the vmsnapshot status with the content name, hence the indexer didnt work all the time as expected.
This reverts commit e7621e58921c8615dbd91747b0b55f63798c1672.
This should fix the flakiness in snapshot tests espacially in the last quarantined test: 
[test_id:6952][QUARANTINE]snapshot change phase to in progress and succeeded and then should not fail …

Fix flakiness in vmsnapshot tests due to racy indexer

---

pkg/cloud-init/cloud-init.go
pkg/cloud-init/cloud-init_test.go

When a ConfigDrive cloud-init is configured the networkData from the mounted secret has to be only checked if NetworkDataSecretRef is set.
```release-note
Don't show a failure if ConfigDrive cloud init has UserDataSecretRef and not NetworkDataSecretRef
```

cloud-init: Skip networkData lookup if not needed

---

manifests/generated/kubevirt-cr.yaml.in
tools/resource-generator/resource-generator.go

When `KUBEVIRT_INFRA_REPLICAS` is not set, we currently create an empty infra section in kubevirt-cr, which is incompatible with some versions of kubectl (see linked issue)
This PR fixes the issue by only creating an infra section when needed.
Fixes #8251 
```release-note
No more empty section in the kubevirt-cr manifest
```

manifests: avoid empty infra section in kubevirt-cr

---

WORKSPACE

We use bazeldnf, which uses sassoftware/go-rpmutils, which uses klauspost/compress, which just deprecated go 1.16.
This shouldn't have been a problem, because bazeldnf actually replaces sassoftware/go-rpmutils with a safe fork:
https://github.com/rmohr/bazeldnf/blob/eeba90f99f2088abf6ffdf0b9d0b57de62eece4b/deps.bzl#L501
However, that replace doesn't seem to work, probably because of this bug:
https://issuehint.com/issue/bazelbuild/bazel-gazelle/1045
Forcing klauspost/compress to a release prior to go 1.16 deprecation fixes the issue.
Fixes # …

[release-0.49] WORKSPACE: Freeze repository that deprecated go 1.16

---

tests/storage/datavolume.go

DV spec does not have namespace yet so it cannot be used. Need to use the same namespace
name as VM so it can be used by VM.
Fixes #
Test is still quarantined so the sample failure can be seen on periodic lane:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.23-sig-storage/1575744836093349888
```release-note
NONE
```

Test: Use correct namespace in 3188 test

---

pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go

/cc @akrejcir 
b91332fd2b1b8b2967b1cac92da0522908e95763 recently added a preference lookup within the mutation webhook but this was done before setDefaultPreferenceKind was able to run. As a result the call could fail if a user had not provided a kind within the preferenceMatcher.
This changes corrects this by moving the setDefaultMachineType to after setDefaultPreferenceKind ensuring a kind is always set by the mutation webhook before any lookups are attempted.
Fixes #
I've not written up a bug for this as …

virt-api: Set default machinetype after preference kind

---

tests/libnet/cloudinit.go
tests/libvmi/network.go
tests/network/primary_pod_network.go
tests/network/sriov.go
tests/network/vmi_istio.go
tests/network/vmi_networking.go
tests/utils.go

`CreateDefaultCloudInitNetworkData` returns an error that needs to be handled. There is mostly no better action than panic so let's just do it and reduce the awkward error handling. This will also differ from normal test failure.
Fixes #
```release-note
NONE
```

Test: Remove unnecessary error

---

pkg/virtctl/imageupload/BUILD.bazel
pkg/virtctl/imageupload/imageupload.go
pkg/virtctl/imageupload/imageupload_test.go
tests/storage/imageupload.go

When running the `virtctl image-upload` command, some storageclass-related errors leave the command waiting for pod creation without providing any relevant error message.
This pull request improves the error handling in those cases, so an appropriate message is returned instead.
**Which issue(s) this PR fixes:** 
https://bugzilla.redhat.com/show_bug.cgi?id=2126104
```release-note
[Bug-fix] Fix error handling in virtctl image-upload 
```

Improve error handling in virtctl image-upload

---

cmd/virt-handler/virt_launcher.cil
pkg/util/util.go
pkg/virt-config/virt-config.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/libvmi/vmi.go
tests/network/vmi_passt.go
tests/storage/storage.go
tests/vmi_configuration_test.go

The default SELinux type for containers, container_t, is good enough for most VMIs.
As of now, our custom SELinux policy is only needed for hugepages and virtiofs.
This PR enables the custom policy only for those cases.
Fixes #
```release-note
Most VMIs now run under the SELinux type container_t
```

virt-launcher: use our custom SELinux type only when necessary

---

cmd/virt-handler/virt_launcher.cil

The SELinux policy for virt-launcher extends`container_domain` from [container-selinux](https://github.com/containers/container-selinux).
Some of the custom rules we defined have been added upstream and don't need to be in the custom virt-launcher policy anymore.
This PR removes them.
Many of our custom rules are now also part of `container_t`, adding comments about those not blocking a potential switch.
Fixes #
These are the commands I use to check our rules against `container_domain`:
```
allow container_domain proc_type:file getattr;
allow container_domain …
```

virt-launcher: SELinux policy: cleanup the rules and add comments

---

docs/metrics.md
hack/prom-rule-ci/prom-rules-tests.yaml
pkg/monitoring/vmstats/BUILD.bazel
pkg/monitoring/vmstats/collector.go
pkg/monitoring/vmstats/collector_test.go
pkg/monitoring/vmstats/vmstats_suite_test.go
pkg/virt-controller/watch/BUILD.bazel
pkg/virt-controller/watch/application.go
pkg/virt-operator/resource/generate/components/prometheus.go
tests/monitoring/monitoring.go
tools/doc-generator/BUILD.bazel
tools/doc-generator/doc-generator.go
tools/doc-generator/fakeVMCollector.go

Sometimes VMs are stuck in unhealthy starting, migrating, or error status. This PR adds new metrics and alerts to provide more visibility over these situations.
For these metrics we considered some options:
1. We discarded using a binary value (0 or 1) to identify if a VM is or is not in a given status because we would lose a considerable amount of information such as for how long the VM has a given status, when did the transitions to those status happened, etc. Having the transition timestamps in the labels was not considered. Each different set of labels represents a new time series. If we had a new time series for each transition timestamp, that would dramatically increase the amount of data stored.
2.  We considered using the number of seconds a …

Add alerts for VMs unhealthy states

---

pkg/virt-launcher/virtwrap/manager_test.go

The spec passed to `migratableDomXML()` should be the current domain spec. If unmarshall the domXML to domain, the `domain.Spec` is actually empty and the 2 new assertions added in this commit will fail.
**What this PR does / why we need it**:  It fixes a unit test logic. Although the test passes originally but the logic is not correct.
Fixes #
I seems unmarshalling the domain xml to the `Domain` object is not correct. The domain xml can be only unmarshalled to the `DomainSpec` object. Is this by design or a bug?
```release-note
NONE …
```

Fix the CPU set migration test case.

---

pkg/storage/snapshot/restore.go
pkg/storage/snapshot/restore_test.go
tests/storage/restore.go

With the [dataSourceRef API inclusion](https://kubernetes.io/blog/2021/08/30/volume-populators-redesigned/) in k8s v1.22, a new validation mechanism was added for PVCs ensuring that, if present, both the dataSource and dataSourceRef fields must be equal.
This behavior conflicts with the restore-controller, which creates the restore PVC using the source spec as a reference, but overwriting the dataSource field. If the source PVC has a populated dataSourceRef field, just overwriting the dataSource triggers the validation error.
This Pull Request aims to modify this behavior, so both dataSource and dataSourceRef are overwritten.
https://bugzilla.redhat.com/show_bug.cgi?id=2128872
In …

Fix bug in restore-controller when creating a restore PVC with both dataSource and dataSourceRef

---

staging/src/kubevirt.io/client-go/kubecli/guestfs.go
staging/src/kubevirt.io/client-go/kubecli/instancetype.go
staging/src/kubevirt.io/client-go/kubecli/kv_test.go
staging/src/kubevirt.io/client-go/kubecli/migration_test.go
staging/src/kubevirt.io/client-go/kubecli/migrationpolicy_test.go
staging/src/kubevirt.io/client-go/kubecli/profiler.go
staging/src/kubevirt.io/client-go/kubecli/replicaset_test.go
staging/src/kubevirt.io/client-go/kubecli/version.go
staging/src/kubevirt.io/client-go/kubecli/version_test.go
staging/src/kubevirt.io/client-go/kubecli/vm.go
staging/src/kubevirt.io/client-go/kubecli/vm_test.go
staging/src/kubevirt.io/client-go/kubecli/vmi.go
staging/src/kubevirt.io/client-go/kubecli/vmi_test.go
staging/src/kubevirt.io/client-go/kubecli/vmipreset_test.go

Handling of cluster URIs with additional path elements added in the commit fba65ed2ce can be simplified with the use of `Request.AbsPath`
https://github.com/kubevirt/kubevirt/blob/0f2c6714ae95371f14b34361f747c2311df18a4d/vendor/k8s.io/client-go/rest/request.go#L305-L317
which literally does the same as the introduced `adaptUriForHostPath` function:
https://github.com/kubevirt/kubevirt/blob/0f2c6714ae95371f14b34361f747c2311df18a4d/staging/src/kubevirt.io/client-go/kubecli/vmi.go#L177-L183
Fixes #
This is a follow-up of the discussion …

Simplify handling of cluster URIs from kubeconfig

---

pkg/virt-handler/heartbeat/heartbeat.go
pkg/virt-handler/heartbeat/heartbeat_test.go
pkg/virt-handler/vm.go

Signed-off-by: prnaraya <prnaraya@redhat.com>
**What this PR does / why we need it**: This aims to address an issue in which making master nodes schedulable and then unschedulable results in a mismatch between the daemonset state and the pods state, with the master nodes still showing up as schedulable.
Fixes #
```release-note
NONE
```

Patching node set kubevirt.io/schedulable to false upon exiting heartbeat

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/vmi_configuration_test.go

This is a partial manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/8247
Fixes #
```release-note
NONE
```
/cc @acardace

[release-0.49] Bump virtlogd memory requirement to 18Mi

---

pkg/certificates/triple/cert/cert.go
pkg/storage/export/export/export_test.go
pkg/storage/export/export/links.go
tests/storage/export.go

Before we returned just the found certificate and not the entire chain. To properly verify the certificate you must have the entire chain. This commit looks up the chain until either we find the root CA or we can't find anything else in the config map.
Also checking the OnBefore and OnAfter times, to figure out which cert is most valid in case of a cert rotation and the bundle containing multiple valid certificates.
Fixes #
```release-note
NONE
```

Return certificate chain for export cert

---

api/openapi-spec/swagger.json
pkg/storage/export/export/export.go
pkg/storage/export/export/export_test.go
pkg/storage/export/export/pvc-source_test.go
pkg/storage/export/export/vm-source_test.go
pkg/storage/export/export/vmsnapshot-source_test.go
pkg/virt-operator/resource/generate/components/validations_generated.go
pkg/virtctl/vmexport/vmexport.go
pkg/virtctl/vmexport/vmexport_test.go
staging/src/kubevirt.io/api/export/v1alpha1/deepcopy_generated.go
staging/src/kubevirt.io/api/export/v1alpha1/types.go
staging/src/kubevirt.io/api/export/v1alpha1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/storage/export.go

Currently, there is no way to limit the lifetime of an export, which users might actually desire;
- No reason to keep serving after import on the other end took place
- Security concerns
This PR attempts to allow this option.
Fixes #
```release-note
Add an option to specify a TTL for VMExport objects
```

Add TTL field for VMExport objects

---

pkg/network/driver/common.go
pkg/network/driver/generated_mock_common.go
pkg/network/infraconfigurators/passt.go
pkg/util/sysctl/sysctl.go
tests/network/vmi_passt.go

Cherry-pick of https://github.com/kubevirt/kubevirt/pull/8516
When using Passt network binding mechanism, and not specifying any ports explicitly, traffic to the low ports (<1024) is not passed through to the VM.
This PR sets all virt-launcher ports to be unprivileged, so that all ports may be used by Passt.
This allows using for example SSH to access VM with Passt binding.
The capability for binding to lower ports is moved to a bazel file, instead of defining it in the handler
code, however, due to the following bugs:
https://bugs.passt.top/show_bug.cgi?id=15
https://bugs.passt.top/show_bug.cgi?id=18
Passt is still unable to bind to lower ports.
When the abovementioned bugs are resolved, we can remove the code introduced in the first commit of this …

Passt unprivilege low ports release 0.58

---

docs/getting-started.md

Document the fact that, for SELinux support, KubeVirt requires a recent-enough version of container-selinux to be installed on the nodes.
Fixes #
```release-note
NONE
```

docs: add minimum container-selinux version

---

cmd/virt-chroot/BUILD.bazel
cmd/virt-chroot/selinux.go

Instead of using lgetxattr on a fd path (/proc/self/fd/<num>), directly use `fgetxattr`.
It turns out that `lgetxattr` does not return a consistent result on all kernel version when used on a filedescriptor path.
This is often not an issue. It would just mean that virt-handler would label a few devices in its namespces on every start, even if it would not have to. But on some operating systems (e.g. Centos8, but not Centos8 stream) we then fail on the not needed relabeling attempt.
Before:
lgetxattr sometimes returns weird resources on a file descroptor path:
```
Error: error relabeling file /proc/self/fd/7 from label system_u:system_r:spc_t:s0 to label system_u:object_r:container_file_t:s0. Reason: operation not supported
[...]
error relabeling …
```

Use fgetxattr to get selinux labels

---

cmd/virt-handler/virt_launcher.cil
pkg/virt-controller/services/rendervolumes.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go

Fixes #
```release-note
VMs configured with hugepages can now run using the default container_t SELinux type
```

Switch VMs with hugepages to use the container_t SELinux type

---

tests/utils.go

Kubernetes internally uses a namespace informer
that might not be up to date after virt-controller relabeled the namespace to use a 'privileged' policy, let's ignore those events in tests as with enough time k8s will catch up and the pod will be created.
This patch has to be removed when KubeVirt will be able to run VMs using the 'restricted' PSA level.
Fixes #
```release-note
NONE
```

tests: ignore transient PSA warning events

---

tests/storage/snapshot.go

Test verifies that snapshot is failed, and expects VM to not have SnapshotInProgress. VM will be eventually updated. Test waits for VM to be updated.
Fixes #
```release-note
NONE
```

[flaky] test 6838 should wait for VM to be updated

---

tests/network/probes.go

Add liveness qemu-exec test probes IDs.
```release-note
NONE
```

probes: Add liveness qemu-exec test probes IDs.

---

manifests/testing/disks-images-provider.yaml.in

The manual creation of local block storage has been removed from images/disks-images-provider/entrypoint.sh along with the LOOP_DEVICE env var in 23fae807d7. So drop the leftover cleanup code of the loop device as it causes failures of the pre stop hook.
This fixes the error when trying to remove the daemonset `kubectl -n kubevirt delete daemonset disks-images-provider --cascade=foreground`:
```
Exec lifecycle hook ([/bin/sh -c source /etc/bashrc && chroot /host losetup -d ${LOOP_DEVICE} && chroot /host umount ${LOOP_DEVICE_HP} && chroot /host losetup -d ${LOOP_DEVICE_HP}]) for Container "target" in Pod "disks-images-provider-p2xtr_kubevirt(205e6ca9-0fa7-4bd5-8726-db5914e42ce5)" failed - error: command '/bin/sh -c source /etc/bashrc && chroot /host …
```

Fix the pre stop hook for disks-images-provider

---

CONTRIBUTING.md

Advertise the design proposal document in the contributors guide.
https://github.com/kubevirt/kubevirt/issues/8566
```release-note
NONE
```

Point to the design proposal document in the contrib guide

---

tests/vmi_ignition_test.go

Make vmi_ignition_test shorter and clearer by using `libvmi` to define a VM and by reusing `RunVMIAndExpectLaunch` instead of re-implementing it.
Furthermore, have the test verify that the requested ignition data exists in `/sys/firmware/qemu_fw_cfg/by_name/opt/com.coreos/config/raw`
```release-note
NONE
```

vmi_ignition_test: shorten and improve

---

tools/perfscale-audit/api/api.go
tools/perfscale-audit/metric-client/metric-client.go

Adds deletion time percentiles to the audit report
```
$ cat _out/artifacts/perfscale/perfscale-audit-results.json | grep -C 3 vmi.*To.*
"UPDATE-virtualmachineinstances-count": {
"value": 131.11111111111111
},
"vmiCreationToRunningSecondsP50": {
"value": 15
},
"vmiCreationToRunningSecondsP95": {
"value": 19.5
},
"vmiCreationToRunningSecondsP99": {
"value": 19.9
},
"vmiDeletionToFailedSecondsP50": {
"value": 0
},
"vmiDeletionToFailedSecondsP95": {
"value": 0
},
"vmiDeletionToFailedSecondsP99": {
"value": 0
},
"vmiDeletionToSucceededSecondsP50": {
"value": 0.625
},
"vmiDeletionToSucceededSecondsP95": {
"value": 0.9624999999999999
},
"vmiDeletionToSucceededSecondsP99": {
"value": 0.9925
}
}
```
**Which issue(s) this PR fixes** *(optional, in `fixes …

[sig-scale] add deletion percentiles to audit report after sig-scale tests

---

cmd/virt-freezer/BUILD.bazel
cmd/virt-freezer/main.go
tests/storage/snapshot.go

This Pull Request aims to modify `fsfreeze` behavior so, in case of using it with a paused VM, it exits triggering an appropriate error message.
```release-note
NONE
```

Improve error handling when using fsfreeze with paused VMs

---

staging/src/kubevirt.io/api/OWNERS

Fixes the labels for **kind/api-change**
Following the examples from upstream kubernetes documentation: https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#filters
```release-note
NONE
```
cc @rthallisey @rmohr

fix regex for kind/api-change labels

---

tests/libdv/BUILD.bazel
tests/libdv/dv.go
tests/migration_test.go
tests/storage/datavolume.go
tests/storage/export.go
tests/storage/hotplug.go
tests/storage/restore.go
tests/storage/snapshot.go
tests/storage/storage.go
tests/utils.go
tests/vmi_configuration_test.go

This commit modifies the `libdv.WithPVC` dvOption to be more readable, by removing all its mandatory parameters, and replace them with optional list of `pvcOption`s.
The default values of the `WithPVC` dvOption are:
* no storage class
* access mode of `ReadWriteOnce`
* volume size of `cd.CirrosVolumeSize`
* no volume mode. kubernetes default is `PersistentVolumeFilesystem`
The new pvcOptions are:
* `PVCWithStorageClass` adds the storage class name to the DV
* `PVCWithVolumeSize` overrides the default volume size (`cd.CirrosVolumeSize`), with the size parameter. The size parameter must be a parsable valid quantity string.
* `PVCWithVolumeMode` adds the volume mode to the DV
* `PVCWithBlockVolumeMode` adds the PersistentVolumeBlock volume mode to the DV
* `PVCWithAccessMode` overrides the …

Change the libdv.WithPVC to work with default values and options

---

pkg/instancetype/instancetype_test.go
pkg/network/domainspec/domainspec_suite_test.go
pkg/network/domainspec/generators_test.go
pkg/network/infraconfigurators/bridge.go
pkg/network/infraconfigurators/common.go
pkg/network/infraconfigurators/masquerade.go
pkg/network/setup/network_suite_test.go
pkg/testutils/domain.go
pkg/util/util.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-launcher/virtwrap/api/BUILD.bazel
pkg/virt-launcher/virtwrap/api/schema_test.go
pkg/virt-launcher/virtwrap/converter/converter.go
pkg/virt-launcher/virtwrap/converter/converter_test.go
pkg/virt-launcher/virtwrap/converter/network.go
pkg/virt-launcher/virtwrap/converter/pci-placement.go
staging/src/kubevirt.io/api/core/v1/schema.go
staging/src/kubevirt.io/api/core/v1/types.go
staging/src/kubevirt.io/client-go/api/schema_test.go
tests/infra_test.go
tests/instancetype_test.go
tests/migration_test.go
tests/vmi_configuration_test.go
tests/vmi_multiqueue_test.go
tools/vms-generator/utils/utils.go

In case the following happen together:
1. Multi queue is enabled
2. There is more than one vCPU
3. There is at least one non virtio interface,
the VMI would fail to be created with the following error:
`"LibvirtError(Code=38, Domain=0, Message='Unable to create tap device tap0: Invalid argument')"`
Multi queue is only implemented for virtio interfaces.
The tap device which is created, didn't take into account the
interface model when calculating the number of queues.
This caused the problem for non virtio interfaces.
Fix it by taking into account the interface model.
`vmi.Spec.Domain.Devices.Rng` is removed from the test because it
is already included in `libvmi.NewFedora` which is used.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …

multi queue: Fix VMI creation in case non virtio interface present and multi vCPU

---

bazel/toolchain/aarch64-none-linux-gnu/cc_toolchain_config.bzl

Fix build error
```
ERROR: /workspace/kubevirt/cmd/container-disk-v2alpha/BUILD.bazel:3:10: Compiling cmd/container-disk-v2alpha/main.c failed: undeclared inclusion(s) in rule '//cmd/container-disk-v2alpha:container-disk':
this rule is missing dependency declarations for the following files included by 'cmd/container-disk-v2alpha/main.c':
'/usr/lib/gcc/aarch64-redhat-linux/8/include/stdarg.h'
'/usr/lib/gcc/aarch64-redhat-linux/8/include/stddef.h'
'/usr/lib/gcc/aarch64-redhat-linux/8/include/stdbool.h'
INFO: Elapsed time: 60.067s, Critical Path: 2.08s
INFO: 476 processes: 134 internal, 342 linux-sandbox.
FAILED: Build did NOT complete successfully
```
```release-note
None
```

add gcc library for local build on Arm64

---

api/openapi-spec/swagger.json
pkg/storage/export/export/export.go
pkg/storage/export/export/export_test.go
pkg/storage/export/export/pvc-source_test.go
pkg/storage/export/export/vm-source_test.go
pkg/storage/export/export/vmsnapshot-source_test.go
pkg/virt-operator/resource/generate/components/validations_generated.go
pkg/virtctl/vmexport/vmexport.go
pkg/virtctl/vmexport/vmexport_test.go
staging/src/kubevirt.io/api/export/v1alpha1/deepcopy_generated.go
staging/src/kubevirt.io/api/export/v1alpha1/types.go
staging/src/kubevirt.io/api/export/v1alpha1/types_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go
tests/storage/export.go

The release was cut on Oct 3rd, but we would consider it an issue if a user wouldn't be able to limit the lifetime of an export:
- No reason to keep serving after import on the other end took place
- Security concerns
Backport #8521 
https://bugzilla.redhat.com/show_bug.cgi?id=2136534
```release-note
BugFix: Add an option to specify a TTL for VMExport objects
```

[release-0.58] Backport 8521 'TTL field for VMExport objects' 

---

go.mod

Missing dependency in go.mod for release-0.41 resulting in
error for midstream repo.
Signed-off-by: Homaja Marisetty <hmariset@redhat.com>
Since cachito is using go 1.18 it is not adding missing dependency in go.mod file therefore brew builds are failing for midstream repo. 
Fixes #
```NONE
```

Since cachito is running go 1.18 we needed to update

---

tests/network/BUILD.bazel
tests/network/expose.go

e2e,expose: Correct expectation for service endpoints
Endpoint only exposes IP addresses of one family. If dual-stack
cluster is used, then Endpoints expose addresses of whatever family is
the first in the list (for ipv4,ipv6 it's ipv4 and for ipv6,ipv4 it's ipv6).
Since Kubernetes 1.21, there is a new resource EndpointSlices.
The EndpointSlices controller creates a new EndpointSlice for each
address family for Pods selected by a service.
For example, having a Pod with IPv4 and IPv6 address, with a service
selecting it, the following EndpointSlices are created:
```
$ kubectl get EndpointSlices -n kubevirt-test-default1
NAME                               ADDRESSTYPE   PORTS   ENDPOINTS        AGE
cluster-ip-target-vmivnmz7-l892x   IPv6          80 …
```

e2e expose: Use EndpointSlices instead of Endpoints and remove XFail blocks

---

tests/BUILD.bazel
tests/utils.go
tests/vmi_configuration_test.go

This PR brings a few fixes and improvements to default runtime class configuration tests.
In short, the main changes are:
- Expect error from createRuntimeClass() to not have occurred
- Ignore warning about fake runtime class not being found
- Use NodeV1 client instead of NodeV1beta1 to eliminate deprecation warning
- Refactoring and a few small fixes
Please see commit description for more info
```release-note
NONE
```

[Functest] several fixes to default runtime class configuration tests

---

pkg/host-disk/host-disk.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
pkg/virt-config/feature-gates.go
pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
tests/migration_test.go
tests/realtime/realtime.go
tests/security_features_test.go
tests/utils.go

Fixes #
```release-note
Kubevirt now runs with nonroot user by default
```

Make nonroot default runtime

---

hack/dockerized

The dockerized script is run numerous times during the large e2e jobs. Each time the script is run a temporary rsync container is started. If one of these rsync containers is not cleaned up correctly it can lead to rsync daemon failures[1] when e2e jobs are run with podman.
`podman stop`[2] attempts to stop a container using `SIGTERM` if this fails within the default 10 seconds a `SIGKILL` is used to forceably stop the container. Previously the script was not waiting for the container to be successfully stopped.
Also updating the wait before the `SIGKILL` to 1 second.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-kubevirt-main/1582303864453861376#1:build-log.txt%3A1017 
[2] …

Wait for podman to stop rsync container successfully

---

tests/libnet/BUILD.bazel
tests/libnet/namespace.go
tests/testsuite/namespace.go

We noticed the label sync and PSA labels are missing in test runs;
This happens because today, we just reset the labels completely before each test.
Let's keep some labels at all times and only delete ephemeral ones that get in the way.
```bash
"metadata": {
"name": "kubevirt-test-privileged3",
"uid": "96dd63f7-5210-4d74-b484-7e80f0564c28",
"resourceVersion": "7736",
"creationTimestamp": "2022-10-25T10:47:45Z",
"labels": {
"kubernetes.io/metadata.name": "kubevirt-test-privileged3",
"test.kubevirt.io/kubevirt-test-privileged3": ""
},
```
Fixes # …

[e2e tests]: Avoid deleting default labels when cleaning up namespace

---

hack/bazel-test.sh

Fix following error when running ` make test`
```
INFO: Build options --action_env, --cache_test_results, --features, and 2 more have changed, discarding analysis cache.
Analyzing: target //tools/junit-merger:junit-merger (0 packages loaded, 0 targets configured)
Analyzing: target //tools/junit-merger:junit-merger (0 packages loaded, 0 targets configured)
ERROR: While resolving toolchains for target @io_bazel_rules_go//:cgo_context_data: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.
ERROR: Analysis of target …
```

fix junit-merger build error on Arm64

---

tests/virtctl/ssh.go

Improve error in "using the local ssh method" test
For easier debugging.
Fixes #
```release-note
NONE
```

Improve error in "using the local ssh method" test

---

pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/vmi_configuration_test.go

The 18Mi virtlogd limit still seems to be a little tight.
Increase it to 20Mi.
Fixes #
```release-note
NONE
```

Bump virtlogd memory requirement to 20Mi

---

manifests/generated/operator-csv.yaml.in
pkg/virt-operator/resource/generate/components/daemonsets.go
pkg/virt-operator/resource/generate/components/deployments.go

This PR bumps up the memory requests for various components (namely virt-operator, virt-api and virt-handler).
I took the highest values seen in recent testing and rounded them up. These are the values:
virt-operator: 380MB
virt-api: 300MB
virt-controller: 250MB
virt-handler: 270MB
Having values that are too low not only triggers many `KubeVirtComponentExceedsRequestedMemory` alerts, but also risks getting killed on busy nodes.
Fixes #
These values are high, but they just represent our current consumption.
As a separate effort, we need to investigate the high …

Bump memory requests according to values seen in testing

---

tests/container_disk_test.go

We override DeveloperConfiguration in test_id:7182
Instead we should just set DeveloperConfiguration.DiskVerification
This issue cause failure when PSA is enabled
in the cluster becuase we disable PSA featureGate
when overriding DeveloperConfiguration
Fixes #
```release-note
NONE
```

Fix test_id:7182

---

tests/migration_test.go

Some tests change the nodes spec and restore them during the test itself. This could cause that if the test fails before resetting the spec, all the subsequent tests will have a non-cleaned cluster, generating fails on cascade. Resetting the cluster conditions on `AfterEach` will improve test stability.
Fixes #
```release-note
NONE
```

e2e: restore cluster condition

---

pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go
pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits_test.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
tests/vmi_configuration_test.go

LimitRange integration had long standing bug
that caused every VMI to require namespace to
be set.
This also fixes situations where we don't apply
limits to VMI if the VMI is missing the label.
Fixes #7681
```release-note
Bug-fix: LimitRange integration now works when VMI is missing namespace
```

Fix LimitRange namespace bug

---

pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
pkg/virt-controller/watch/drain/evacuation/evacuation.go
pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/node.go
pkg/virt-controller/watch/pool.go
pkg/virt-controller/watch/replicaset.go
pkg/virt-controller/watch/vm.go
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/workload-updater/workload-updater.go
pkg/virt-operator/kubevirt.go

workqueue
Signed-off-by: HF <crazytaxii666@gmail.com>
Fixed code error.
Return directly when key function executes failed, the unexpected key should not be added into workqueue.
```release-note
NONE
```

Return directly when key function executes failed

---

pkg/virtctl/imageupload/imageupload_test.go

testInit is later than usage of kubeClient, this
would lead to nil pointer error when do go_parallel_test
Signed-off-by: Howard Zhang <howard.zhang@arm.com>
```release-note
None
```

tests: fix nil point error for kubeClient

---

tests/vmi_configuration_test.go

Ensure that vm configuration tests use random runtime classes, to avoid colliding with delayed deletions of the custom runtime class from previous tests.
The failing runtime test in https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2022-10-24-168h.html#row0 shows that the test does not have the runtime class present.
Digging into the artifacts logs shows that the runtime class is indeed not present. It turns out that when we crate the runtime class, we don't check for an error. This allows that we will still start the test if the runtime class exists, but is already makred for deletion.
Switch to random runtime classes, to give runtime classes all the time they need to be finally removed (when all pods …

[tests] Use random custom runtime classes to avoid cleanup collisions

---

pkg/virt-handler/rest/console.go

the default base image for virt-handler is centos, which workdir is /. but we use a custom debian:buster as the base image, which workdir is /root.
when we run `virtctl -n test vnc vm1`, it reports an error:  
Can't access VMI vm1: Internal error occurred: dialing virt-handler: websocket: bad handshake 
I digged into this problem, and found that the virt-vnc sock path in `getUnixSocketPath` is `proc/3484989/root/var/run/kubevirt-private/a44829ef-d44c-4a64-bf8a-2bcf274bad12/virt-vnc` without leading '/'.
when it runs `os.Stat` with this path, it will return an error "no such file or directory".
so, I think maybe we can add a leading '/' to make an absolute path, it will work no matter what the workdir of the virt-handler image is.
Signed-off-by: huyinhou <huyinhou@bytedance.com>
**What …

fix stat virt-vnc and virt-serial0 return error

---

examples/vm-cirros-cluster-csmall.yaml
tools/vms-generator/utils/utils.go

Change VirtualMachineClusterInstancetype name value from "csmall" to "cluster-csmall" for making it work with the ClusterInstanceType defined at cluster-csmall.yaml.
Fixes #
```release-note
NONE
```

Fix vm-cirros-cluster-csmall VirtualMachineClusterInstancetype name value.

---

cmd/libguestfs/BUILD.bazel
pkg/virtctl/guestfs/BUILD.bazel
pkg/virtctl/guestfs/guestfs.go
pkg/virtctl/guestfs/guestfs_test.go
tests/storage/guestfs.go

Add flag to specify uid for guestfs pod.
Fixes #
```release-note
Flag for setting the guestfs uid and gid
```

guestfs: flag to set uid and gid

---

tests/storage/hotplug.go
tests/storage/restore.go
tests/storage/storage.go

If the underlying volume has already been formatted to ext4, the tool will prompt for a user confirmation to proceed:
```
$ mkfs.ext4 img
mke2fs 1.46.5 (30-Dec-2021)
img contains a ext4 file system
created on Thu Oct 27 09:12:53 2022
Proceed anyway? (y,N)
```
This is probably not desirable during a test run.
Fixes #
I hit this issue while running the tests with Longhorn storage provisioner.
```release-note
NONE
```

tests: Run mkfs.ext4 with force flag -F

---

pkg/virt-controller/watch/vsock_test.go

**What this PR does / why we need it**: It fixes the flaky VSOCK unit test.
The [`randName()`](https://github.com/kubevirt/kubevirt/blob/main/tests/libvmi/vmi.go#L49) doesn't guarantee to generate unique name all the time.
Before the fix `ginkgo --repeat=100 --focus-file=vsock_test.go ./pkg/virt-controller/watch` fails every time I run.
After the fix `ginkgo --repeat=1000 --focus-file=vsock_test.go ./pkg/virt-controller/watch` passes 3 times in a rolls.
Fixes #
```release-note
NONE
```

Fix the flaky VSOCK unit test

---

tests/libstorage/BUILD.bazel
tests/libstorage/pvc.go
tests/storage/export.go
tests/utils.go

This fixes the test "should successfully update a VMI's CPU set on migration" when run in a cluster with PSA enabled.
Fixes #
```release-note
NONE
```

tests: create PSA compliant pod in `renderContainerSpec()`

---

tests/performance/BUILD.bazel
tests/performance/density.go

/cc @rthallisey 
Adds a basic set of VM and VM with instancetype density tests.
Fixes #
Draft as I can't run these locally at the moment, will run the performance tests and clean up before marking the PR as ready for review.
```release-note
NONE
```

tests, performance: Add VM and VM with instancetype density tests

---

tests/utils.go

Infrequently, when we try to execute stuff on this executor, it will error out saying it doesn't exist or it is paused.
A readiness probe gives it more time to start up.
Intended to fix flakes like these failures: [1](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8225/pull-kubevirt-e2e-k8s-1.24-sig-storage-dv-gc/1580753114925895680), [2](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8614/pull-kubevirt-e2e-k8s-1.24-sig-storage/1582014062466699264)
```release-note
NONE
```

Use a readiness probe for memory dump test executor

---

pkg/virt-operator/BUILD.bazel
pkg/virt-operator/application.go
pkg/virt-operator/kubevirt.go
pkg/virt-operator/kubevirt_test.go
pkg/virt-operator/resource/apply/BUILD.bazel
pkg/virt-operator/resource/apply/apps_test.go
pkg/virt-operator/resource/apply/pdb_test.go
pkg/virt-operator/resource/generate/components/daemonsets.go
pkg/virt-operator/resource/generate/components/deployments.go
pkg/virt-operator/resource/generate/csv/csv.go
pkg/virt-operator/resource/generate/install/strategy.go
pkg/virt-operator/util/BUILD.bazel
pkg/virt-operator/util/config.go
pkg/virt-operator/util/config_test.go
pkg/virt-operator/util/env_var_manager.go
tests/BUILD.bazel
tests/operator_test.go
tests/utils.go
tools/csv-generator/csv-generator.go
tools/manifest-templator/manifest-templator.go

This PR adds the ability to provide custom images for core components, e.g. `virt-handler`, `virt-launcher`, etc.
Custom images can be provided via environment variables:
```yaml
env:
- name: VIRT_OPERATOR_IMAGE
value: some.registry.com:tag1
- name: VIRT_API_IMAGE
value: some.registry.com:tag2
- name: VIRT_CONTROLLER_IMAGE
value: some.registry.com@sha256:abcdefghijklmnop
- name: VIRT_HANDLER_IMAGE
value: some.registry.com:tag4
- name: VIRT_LAUNCHER_IMAGE
value: some.registry.com:tag5
- name: VIRT_EXPORTPROXY_IMAGE
value: some.registry.com:tag6
- name: VIRT_EXPORTSERVER_IMAGE
value: some.registry.com:tag7
```
In addition, I've made some refactoring, mainly to use mocked environment variables to perform better isolation between unit tests.
This work …

Allow specifying custom images for core components

---

automation/test.sh

A possible solution to slighly de-synchronize mass-job-starts.
Fixes #
```release-note
NONE
```

Slighlty randomize CI startup to distribute disk usage a little bit

---

tests/testsuite/namespace.go

Dont panic on not found error when trying to delete services in cleanup
In the cleanup process we try to clean the namespace, if the service was deleted right after the list command we shouldn't panic on that.
examples for the failures:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8666/pull-kubevirt-e2e-k8s-1.24-sig-storage-dv-gc-0.58/1587903106249658368
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8650/pull-kubevirt-e2e-k8s-1.23-sig-storage/1586255028778176512
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8279/pull-kubevirt-e2e-k8s-1.24-sig-storage/1586014159605075968
Fix flakiness of virtctl export tests …

Fix flakiness of virtctl export tests

---

tests/network/vmi_slirp_interface.go

Retry curl command verifying Slirp connectivity: The orignal code using curl was problematic due to its lack of retry - temporary connection drop would fail the test. With this patch, the curl command is retried. 
This PR also removes unused HTTP server from a Slirp test.
This should resolve flakes like https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.22-sig-network/1587200279651028992#1:build-log.txt%3A3067.
Due to its lack of ICMP support, the test cannot employ the same ping technique as adopted by otherwise similar [vmi_networking.go](https://github.com/kubevirt/kubevirt/blob/main/tests/network/vmi_networking.go#L729).
```release-note
NONE
```

Stabilize slirp outside connectivity test

---

tests/network/vmi_networking.go

This PR fixes duplicate imports in vmi_netowrking.go tests
Fixes #
```release-note
NONE
```

tests, network: Remove duplicate imports

---

pkg/virt-controller/watch/snapshot/restore.go
pkg/virt-controller/watch/snapshot/restore_test.go
tests/storage/restore.go

Manual backport of https://github.com/kubevirt/kubevirt/pull/8568.
**Which issue(s) this PR fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2128872
```release-note
NONE
```

[release-0.53] Manual backport of fix bug in restore-controller when creating a restore PVC with both dataSource and dataSourceRef

---

tests/security_features_test.go
tests/storage/snapshot.go
tests/subresource_api_test.go
tests/vmi_cloudinit_hook_sidecar_test.go
tests/vmi_lifecycle_test.go

Use `libvmi` to simplify a few tests. This makes the tests slightly more readable, dropping `echo hello` boilerplate when defining Cirros VMs.
```release-note
NONE
```

tests: less echo hello

---

WORKSPACE
hack/bootstrap.sh
hack/rpm-deps.sh
rpm/BUILD.bazel

The ability to use virtio-gpu, which is the default video device for aarch64 VMs, was lost during the switch to CentOS Stream 9.
This PR restores it.
Fixes #8708
```release-note
NONE
```

Re-enable virtio-gpu for aarch64 VMs

---

pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go

When no SR-IOV interfaces are set on the vmi, there is no need to try and create a SRIOV pool. Return an empty HostDevice list.
Not doing so results with the `found no SR-IOV networks to PCI-Address mapping. fall back to resource address pool` warning to pop up even if there are no SRIOV interfaces on the vmi.
Fixes #
```release-note
NONE
```

hostdev: Avoid creating SR-IOV pool when not configured

---

pkg/monitoring/client/prometheus/prometheus.go

Current `rest_client_request_latency_seconds` histogram `Buckets` values are arbitrary, do not correspond to real-life requests latency distribution and are not giving the best observability possible. 
Assuming that in a production deployment, majority of requests has a latency from range `[150ms, 1s]`, current histogram definition will segregate the requests into only 3 buckets (`(0.128, 0.256], (0.256,0.512], (0.512, + Inf)`). This behavior causes KPIs like P95 or P99 to be less precise.
This PR follows the example of Kubernetes (https://github.com/kubernetes/kubernetes/pull/73638) and introduces custom buckets values for requests latency histogram. Especially, for mentioned before range of latencies `[150ms, 1s]`, it will segregate the requests …

Add more precise rest_client_request_latency_seconds histogram buckets

---

docs/components.md

An instance of a Custom Resource Definition is a Custom Resource. Talking about it indirectly is a bit more confusing and verbose, so simplify it to just talk about VMI CRs.
Simplify documenation
Fixes #
```release-note
NONE
```

Simplify terminology a bit

---

api/openapi-spec/swagger.json
pkg/virt-operator/resource/generate/components/validations_generated.go
staging/src/kubevirt.io/api/core/v1/schema.go
staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
staging/src/kubevirt.io/client-go/api/openapi_generated.go

Fixes #
```release-note
NONE
```

Add GC note to DataVolumeSource api doc

---

pkg/virt-controller/services/renderresources.go
tests/network/vmi_istio.go
tests/network/vmi_passt.go

When VMI uses Passt interface and doesn't specify ports, all the ports are forwarded by Passt process.
Opening all the sockets for forwarding causes kernel to consume considerable amount of memory.
At the moment, Passt binding can only be used on primary interface, but since we need to loop over the VMI interfaces anyway, there's no reason not to be generic and account for each Passt binding with no specified Ports.
Fixes #
```release-note
Add overhead of interface with Passt binding when no …
```

network,passt: consider overhead when binding all ports

---

pkg/virt-operator/resource/generate/components/scc.go

With PSA, one of the things we will try to comply with is the seccomp profile:
https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
Thus, we need our SCC to allow setting this.
Note this is also included in the restricted-v2 SCC:
```bash
$ oc get scc restricted-v2 -o json | jq .seccompProfiles
[
"runtime/default"
]
```
Fixes #
```release-note
NONE
```

Add restricted seccomp profile to controller SCC

---

docs/metrics.md
pkg/monitoring/domainstats/prometheus/prometheus.go
pkg/monitoring/domainstats/prometheus/prometheus_test.go

This is a manual cherry-pick of #8401 
```release-note
Rename metrics to follow naming convention
```

[release-0.53] Rename metrics to follow naming convention

---

tests/storage/guestfs.go

We have a flake where the pod is terminating -- this is likely due to the name conflict with another test. This name is more appropriate, too.
This test has [flakes](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8724/pull-kubevirt-e2e-k8s-1.23-sig-storage/1589919931783188480)
Not 100% sure this is the cause, as I don't see the previous test running just before it, but it's likely.
```release-note
NONE
```

Use a unique pvc/pod name for guestfs test

---

tests/network/primary_pod_network.go

When testing pod IPs reported by the guest-agent on the VMI
the tests wait for a default timeout to get the updated IPs.
Since the status update depends on guest agent polling and propagation
between virt-launcher and virt-handler which can take more time
the Expect timeout should allow more time in order to make sure 
that the IPs are picked up by the test.
Timeout is set to 2 minutes which is the guest agent steady state polling time
Fixes #
```release-note
NONE
```

guest-agent, tests: Increase timeout fetching pod IPs

---

tests/testsuite/namespace.go

This was done there because the virt-controller auto labelling
mechanism is overlapping and fighting with the
Openshift Pod Security Admission Autolabeling.
So we were setting that at test suite level
assuming that the Kubevirt PSA FG was always
on when deploying on Openshift.
Now we revisited that decision and so HCO
is not going to enable the PSA FG on Kubevirt, see:
https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2136
https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2135
https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2134
https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2133
but at this point, if PSA is enabled on the cluster,
on Openshift we should rely on its default
Pod …

tests: avoid opting out from OCP/OKD podSecurityLabelSync

---

tests/numa/numa.go

For some reason, running `ps ax` in virt-handler keeps failing, no matter how much effort we put into making it work...
This PR replaces the call with a grep in /proc, hopefully fixing the flakyness once and for all.
Fixes #
```release-note
NONE
```

tests: numa: yet another attempt at unflaking test_id:7299

---

cmd/virt-handler/virt_launcher.cil
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
tests/testsuite/kubevirtresource.go

With the Centos 9 update, we got a much more recent version of virtiofsd.
Let's see if the functional tests pass with the new version and without our custom SELinux rules.
Fixes #
```release-note
NONE
```

Remove the virtiofs SELinux rules from our custom policy

---

api/openapi-spec/swagger.json
cmd/subresource-access-test/BUILD.bazel
cmd/subresource-access-test/subresource-access-test.go
manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-api/api.go
pkg/virt-api/rest/authorizer.go
pkg/virt-api/rest/authorizer_test.go
pkg/virt-api/rest/expand.go
pkg/virt-api/rest/expand_test.go
pkg/virt-operator/resource/generate/rbac/cluster.go
staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
staging/src/kubevirt.io/client-go/kubecli/instancetype.go
staging/src/kubevirt.io/client-go/kubecli/instancetype_test.go
staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
tests/access_test.go
tests/subresource_api_test.go
tests/testsuite/serviceaccount.go

The expand-spec endpoint is renamed to expand-vm-spec and made
namespaced to allow proper authorization.
This PR adds code to the virt-api authorizer to check namespaced
base resource endpoints and unittests/functests to verify the authorization.
Based on https://github.com/kubevirt/kubevirt/pull/8399 and https://github.com/kubevirt/kubevirt/pull/8570
```release-note
The expand-spec subresource endpoint was renamed to expand-vm-spec and made namespaced
```

Rename and authorization for namespaced expand-spec endpoint

---

tests/storage/export.go

As non-root out of the box, most storage's won't give us a PVC that is world writeable. Noticed this on OpenShift testing lanes where cephcsi is used instead of the "local" SC that is used in kubevirtci.
Ceph stopping chmod 777 reference:
https://github.com/ceph/ceph-csi/pull/2697
Fixes #
```release-note
NONE
```

[export tests]: Specify fsGroup so we can write the exported PVC

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
pkg/virt-controller/watch/vmi.go
staging/src/kubevirt.io/api/core/v1/types.go
tests/migration_test.go

When migrating a VM fails an increasingly exponential backoff will be applied before retrying.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2124528
```release-note
Use exponential backoff for failing migrations
```

Use exponential backoff for failing migrations

---

pkg/virt-api/webhooks/hyperv.go
pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
tests/hyperv_test.go
tests/vmi_lifecycle_test.go

Fix Evmcs Hyperv bug.
Fixes #
Currently whenever EVMCS HyperV feature
Is not nil in the vm spec than all dependencies
features of EVMCS are enabled.
Even if we set vmi.Spec.Domain.Features.Hyperv.EVMCS.Enabled
to be false.
```release-note
NONE
```

Fix evmcs hyperv feature bug

---

pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-controller/watch/topology/generated_mock_hinter.go
pkg/virt-controller/watch/topology/hinter.go
pkg/virt-controller/watch/topology/hinter_test.go
pkg/virt-controller/watch/topology/tsc.go
pkg/virt-controller/watch/topology/tsc_test.go
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go
pkg/virt-launcher/virtwrap/converter/converter.go
tests/hyperv_test.go

This PR aims to fix an inconsistency regarding re-enlightenment VMs and TSC frequency.
While the converter.go's logic checked whether we have topology hints defined and that tsc frequency is [required](https://github.com/kubevirt/kubevirt/blob/v0.58.0/pkg/virt-controller/watch/topology/tsc.go#L19) (which is the right thing to do), template.go logic did not check the later. The both flows are now aligned, with `IsManualTSCFrequencyRequired()` being the sole source of truth.
```release-note
Fix: Align Reenlightenment flows between converter.go and template.go
```

Fix: Align Reenlightenment flows between converter.go and template.go

---

tests/storage/BUILD.bazel
tests/storage/guestfs.go

Sometimes, the libguestfs pod is deleted by the test clean-up but the function runGuestfsOnPVC hasn't gracefully terminated yet. The function runGuestfsOnPVC has a goroutine that returns when the channel of the fakeCreateAttacher is closed. Before this fix, there was a race between the `defer f.closeChannel()` and the test clean-up
Without the coordination, the [runGuestfsOnPVC](https://github.com/kubevirt/kubevirt/blob/main/tests/storage/guestfs.go#L85) function can return an error that the pod isn't existing anymore.  
Fixes # …

guestfs: solve flakiness for guestfs tests

---

cmd/virt-handler/virt-handler.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-handler/node-labeller/BUILD.bazel
pkg/virt-handler/node-labeller/node_labeller.go
pkg/virt-handler/node-labeller/node_labeller_test.go
staging/src/kubevirt.io/api/core/v1/types.go
tests/infra_test.go

Currently if a node has host-model cpu that is included in ObsoleteCPUModels
and we create vmi with host-model cpu it can still be scheduled to that node,
than the vmi will run with a obsoleteCpuModel and won't be able to migrate.
This PR fix this problem.
Fixes #
```release-note
NONE
```

Vmi shouldn't run with obsolete cpu model 

---

pkg/virt-controller/watch/drain/evacuation/evacuation.go
pkg/virt-controller/watch/drain/evacuation/evacuation_test.go

If not considering the maximum per-source-node active migrations we can have a scenario where we reach the maximum capacity of concurrent migrations in a cluster, where most of the migrations are pending because all the migrations are from the same source node.
This can be problematic in a case where multiple drains occur at the same time, therefore evictions from different source nodes can start simultaneously, but it won't happen because the migraiton queue was occupied with VMs from the same source node.
The solution is to observe migration queue with active migrations from same source node and limit the creation of new migrations up to the ParallelOutboundMigrationsPerNode.
**Which issue(s) this PR …

[virt-controller]: consider the ParallelOutboundMigrationsPerNode when evicting VMs

---

manifests/generated/operator-csv.yaml.in
pkg/virt-operator/resource/generate/components/deployments.go
pkg/virt-operator/resource/generate/csv/csv.go
pkg/virt-operator/util/config.go
pkg/virt-operator/util/config_test.go
tools/csv-generator/csv-generator.go
tools/manifest-templator/manifest-templator.go

This is a follow-up for https://github.com/kubevirt/kubevirt/pull/8673. This PR aims to expose the new env vars introduced in the previous PR to csv-generator and manifest-templator.
```release-note
Expose new custom components env vars to csv-generator and manifest-templator
```

Expose new custom components env vars to csv-generator and manifest-templator

---

tests/libnode/node.go

Currently `CleanNodes()` does not restore the nodes if a test only changes the `spec.unschedulable` field. This can happen for example in a migration test, which set all control-plane nodes unschedulable, in a cluster where all nodes are both control-plane and worker. This results in a test failure, and since the nodes are not properly restored, the subsequent tests fail on cascading.
Fixes #
```release-note
NONE
```

Improve CleanNodes() function

---

pkg/virt-handler/device-manager/mediated_devices_types.go
pkg/virt-handler/device-manager/mediated_devices_types_test.go
tests/mdev_configuration_allocation_test.go

This is an attempt at reacting to platform changes such as hardware hotplug and driver bind/unbind, independent of CR configuration changes.
For now, this PR just removes all checks and runs the whole code on each virt-handler heartbeat.
Probably not the best solution, hence the `draft` status. But I think this is a good starting point, and it works as expected when binding a device to a driver after CR edits.
Fixes #
Let's identify which sections of the code can safely be made conditional, without missing events.
```release-note
NONE
```

Always refresh the mediated devices

---

docs/local-custom-files.md

In certain situations, we want to build KubeVirt using local files. This howto tries to help users to easily replace and build KubeVirt with custom local files.
Fixes #
```release-note
NONE
```

docs: build kubevirt using local files

---

api/openapi-spec/swagger.json
cmd/subresource-access-test/BUILD.bazel
cmd/subresource-access-test/subresource-access-test.go
manifests/generated/operator-csv.yaml.in
manifests/generated/rbac-operator.authorization.k8s.yaml.in
pkg/virt-api/api.go
pkg/virt-api/rest/authorizer.go
pkg/virt-api/rest/authorizer_test.go
pkg/virt-api/rest/expand.go
pkg/virt-api/rest/expand_test.go
pkg/virt-operator/resource/generate/rbac/cluster.go
staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
staging/src/kubevirt.io/client-go/kubecli/instancetype.go
staging/src/kubevirt.io/client-go/kubecli/instancetype_test.go
staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
tests/access_test.go
tests/subresource_api_test.go
tests/testsuite/serviceaccount.go

This is a manual backport of #8720
/assign @davidvossel 
/assign @lyarwood 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2134825
```release-note
The expand-spec subresource endpoint was renamed to expand-vm-spec and made namespaced
```

[release-0.58] Rename and authorization for namespaced expand-spec endpoint

---

pkg/virt-controller/watch/migration.go
pkg/virt-controller/watch/migration_test.go
tests/migration_test.go

Fixes #
```release-note
Apply migration backoff only for evacuation migrations.
```

migration: apply backoff only for evacuation migrations

---

tests/storage/storage.go

Not sure if this test should have ever worked without an OS;
```yaml
volumes:
- name: disk0
persistentVolumeClaim:
claimName: ioerrorpvcg5gnq
```
(Just a VM with the error block device)
Seems that its also the reason we don't get manifests in the periodic, @maya-r spotted this.
Fixes #
```release-note
NONE
```

Run quarantined io error test with alpine

---

manifests/generated/operator-csv.yaml.in
pkg/virt-operator/resource/generate/components/deployments.go
pkg/virt-operator/resource/generate/csv/csv.go
pkg/virt-operator/util/config.go
pkg/virt-operator/util/config_test.go
tools/csv-generator/csv-generator.go
tools/manifest-templator/manifest-templator.go

Tiny follow up to https://github.com/kubevirt/kubevirt/pull/8673 and https://github.com/kubevirt/kubevirt/pull/8792: add support for the gs image.
```release-note
Custom components: support gs
```

Custom components: support gs

---

pkg/virt-controller/services/BUILD.bazel
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-controller/watch/topology/generated_mock_hinter.go
pkg/virt-controller/watch/topology/hinter.go
pkg/virt-controller/watch/topology/hinter_test.go
pkg/virt-controller/watch/topology/tsc.go
pkg/virt-controller/watch/topology/tsc_test.go
pkg/virt-controller/watch/vmi.go
pkg/virt-controller/watch/vmi_test.go
pkg/virt-launcher/virtwrap/converter/converter.go
tests/hyperv_test.go

Manual backport for https://github.com/kubevirt/kubevirt/pull/8740.
The reason a manual backport is required is because the functional tests are added to [hyperv_test.go](https://github.com/kubevirt/kubevirt/blob/main/tests/hyperv_test.go) which didn't exist in `release-58` branch because the [PR](https://github.com/kubevirt/kubevirt/pull/8556) that created this file wasn't backported.
```release-note
Fix: Align Reenlightenment flows between converter.go and template.go
```

[release-0.58]: Fix: Align Reenlightenment flows between converter.go and template.go

---

manifests/generated/operator-csv.yaml.in
pkg/virt-operator/resource/generate/components/deployments.go
pkg/virt-operator/resource/generate/csv/csv.go
pkg/virt-operator/util/config.go
pkg/virt-operator/util/config_test.go
tools/csv-generator/csv-generator.go
tools/manifest-templator/manifest-templator.go

This is a manual backport for both https://github.com/kubevirt/kubevirt/pull/8792 and https://github.com/kubevirt/kubevirt/pull/8811.
```release-note
Expose new custom components env vars to csv-generator, manifest-templator and gs
```

[release-0.58] Expose new custom components env vars to csv-generator, manifest-templator and gs

---

pkg/storage/snapshot/snapshot.go
pkg/storage/snapshot/snapshot_test.go

Turns out that it may take a long time for a VolumeSnapshot to be "ready to use."  For example with EBS backed PVCs that store snapshots in S3.  So instead of unfreezing a VM when all snapshots are ready, just unfreeze when `status.creationTime` is set.
Fixes #
```release-note
NONE
```

Unfreeze VM when all VolumeSnapshots "created" instead of "ready"

---

tests/hyperv_test.go

In HyperV tests in the `"TSC frequency is not exposed on the cluster"` case, at the BeforeEach(), we stop node labeller on a node if TSC is exposed to fake as if it's not exposed.
In the AfterEach(), we then expect node-labeller to be stopped, although it's not always the case (as said above, if TSC is not exposed in the first place, we don't stop node-labeller).
```release-note
NONE
```

HyperV functest fix: don't expect node-labeller to always be stopped

---

pkg/virt-launcher/virtwrap/cmd-server/server.go
pkg/virt-launcher/virtwrap/cmd-server/server_test.go
pkg/virt-launcher/virtwrap/generated_mock_manager.go
pkg/virt-launcher/virtwrap/manager.go
pkg/virt-launcher/virtwrap/manager_test.go

Some methods in `DomainManager` always return `nil` error. This PR removes the error return value for these methods.
```release-note
None
```

virt-launcher: Remove always nil return values from DomainManager

---

tests/canary_upgrade_test.go

Put test in quarantine due to high flakiness. According to [ci search](https://search.ci.kubevirt.io/?search=%5C%5BSerial%5D%5C%5Bsig-operator%5Dvirt-handler+canary+upgrade+should+successfully+upgrade+virt-handler&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job )
it has on average beyond 5% impact, max 15%.
See [KubeVirt Quarantine Docs](https://github.com/kubevirt/kubevirt/blob/main/docs/quarantine.md#putting-tests-in-quarantine)
Fixes #
```release-note
```

Quarantine canary upgrade test

---

WORKSPACE
cmd/libguestfs/BUILD.bazel
cmd/libguestfs/entrypoint.sh
hack/rpm-deps.sh
pkg/virtctl/guestfs/guestfs.go

Libguestfs package available in centos stream 9 supports using the root in qcow2 format. This allows to keep the libguestfs-tools image with a reasonable size (~550MB), and at the same time it avoids to extract the appliance at runtime.
Fixes #
```release-note
Change libguestfs-tools image using root appliance in qcow2 format
```

Use libguestfs appliance with qcow2 root

---

pkg/virtctl/imageupload/imageupload.go
pkg/virtctl/imageupload/imageupload_test.go

Express deprecation via `MarkDeprecated`, leading to the following warnings:
```
Flag --pvc-name has been deprecated, specify the name as the second argument instead.
Flag --pvc-size has been deprecated, use --size instead.
```
Further marking them as deprecated removes them from the `--help` page.
Fixes #
An alternative may be to just drop these flags now?
```release-note
NONE
```

[virtctl] Express image-upload options deprecation via pflag

---

hack/dockerized

**What this PR does / why we need it**: This MR drops ':z' bind option when using Podman and MacOS as it may not work correctly, see https://github.com/containers/podman/issues/13631. If the kubevirt repo is used to do for example `make test` without this MR it may fail with:
```
Error: lsetxattr /Users/januszm/.docker/secrets: operation not supported
```
**Special notes for your reviewer**: More about ':z' and ':Z' bind option, see: https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label
```release-note
NONE
```

Drop ':z' bind option when using Podman and MacOS

---

cmd/virt-launcher/BUILD.bazel
pkg/virt-controller/services/rendercontainer.go
pkg/virt-controller/services/rendercontainer_test.go
pkg/virt-controller/services/template.go
pkg/virt-controller/services/template_test.go
pkg/virt-launcher/virtwrap/util/libvirt_helper.go
pkg/virt-operator/resource/generate/components/scc.go
tests/security_features_test.go

Drops the `SYS_PTRACE` capability from the virt-launcher pod.
We're now using libvirt 8.7.0, and the additional capability was only needed for versions of libvirt older than 8.1.0.
I keep hitting
```
•! [PANICKED] [0.000 seconds]
Template
pkg/virt-controller/services/template_test.go:62
Rendering
pkg/virt-controller/services/template_test.go:163
[It] should require capabilites which we set on virt-launcher binary
pkg/virt-controller/services/template_test.go:3384
Test Panicked
In [It] at: GOROOT/src/runtime/panic.go:260
runtime error: invalid memory address or nil pointer dereference
Full Stack Trace
kubevirt.io/kubevirt/pkg/virt-controller/services.glob..func6.6.39() …
```

virt-launcher: Drop SYS_PTRACE capability

---

pkg/virt-controller/services/nodeselectorrenderer.go
pkg/virt-controller/services/template_test.go
tests/hyperv_test.go

Fix Evmcs Hyperv bug.
Fixes #
Currently whenever EVMCS HyperV feature
Is not nil in the vm spec than the vm require 
Intel vendor.
Even if we set vmi.Spec.Domain.Features.Hyperv.EVMCS.Enabled
to be false.
This is a follow up PR to:
https://github.com/kubevirt/kubevirt/pull/8773
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2140808 
```release-note
NONE
```

Fix evmcs hyperv bug

---

tests/credentials_test.go
tests/framework/matcher/BUILD.bazel
tests/framework/matcher/conditions.go
tests/framework/matcher/conditions_test.go
tests/infra_test.go
tests/migration.go
tests/migration_test.go
tests/network/primary_pod_network.go
tests/network/probes.go
tests/network/sriov.go
tests/network/vmi_infosource.go
tests/network/vmi_multus.go
tests/operator_test.go
tests/pausing_test.go
tests/pool_test.go
tests/replicaset_test.go
tests/softreboot_test.go
tests/storage/hotplug.go
tests/storage/restore.go
tests/storage/snapshot.go
tests/storage/storage.go
tests/subresource_api_test.go
tests/utils.go
tests/virt_control_plane_test.go
tests/vm_test.go
tests/vmi_configuration_test.go
tests/vmi_lifecycle_test.go

This PR does 2 following things:
1. Uses libvmi in pause tests and cleans the tests a little bit
2. Introduce VM/I condition matcher that is showing all conditions and what condition was expected. This is better than seeing false is not true or similar outputs.
Fixes #
I recommend reviewing commit by commit.
```release-note
NONE
```

Pause tests

---

pkg/virt-api/rest/expand_test.go

This adds a unit test which sets an empty namespace as path parameter for a call to the ExpandSpecRequestHandler. This is a theoretical situation which should not be technically possible at the moment.
Setting of the namespace path parameter in the following test was removed as it was redundant. callExpandSpecApi already does it.
This as a follow up to #8720 
```release-note
None
```

virt-api: Add test for empty namespace in expand_test.go

---

pkg/storage/export/virt-exportserver/exportserver.go

When I use export service, I forgot to enable the `device_ownership_from_security_context = true`. service is started, but when I download the `disk.img` file, the pod does not print any logs, just return 500.
The error is the same as  `https://github.com/kubevirt/kubevirt/issues/8618`.
By adding logs, you can quickly help uses and developers locate where the problem is. 
fixes #8618 
```release-note
NONE
```

[exportServer] Add download file logs when read file error

---

pkg/virt-controller/watch/migration_test.go
tests/BUILD.bazel
tests/migration_policy.go
tests/migration_test.go
tests/utils.go

This PR uses migration policies to limit bandwidth instead of using Kubevirt CR. This enhances tests isolation as they're not dependent on a global resource. In addition, it allows more tests to run in parallel.
One of the tests that now uses this method is test 8482 which is currently quarantined.
The logs (see example [1]) show that the migration already is finished when the test failed on not finding any Prometheus metrics. This sounds familiar - many tests used stress in the past to delay migration progress and prevent it from finishing immediately, and this issue was fixed for other tests by limiting migration bandwidth. The same approach is used here.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.24-sig- …

[Functest stabilization]: Properly limit bandwidth with migration policies

---

pkg/virt-controller/services/nodeselectorrenderer.go
pkg/virt-controller/services/template_test.go
tests/hyperv_test.go

This is a manual backport PR for https://github.com/kubevirt/kubevirt/pull/8840
the cherry-pick conflict was redundant import in hyperv_test.go
Fixes #
```release-note
NONE
```

[release-0.58]Fix evmcs hyperv vendor bug

---

tests/storage/restore.go

A redundant VM console prompt login has been removed. It caused some flakes in the tests, when the second login was attempted.
Although for the Fedora guest, detecting a login should have been supported, it seems that from time to time the detection is not working as expected. Reducing double logins may help reduce the flakes a bit.
Fixes #
```release-note
NONE
```

tests, storage/restore: Remove a redundant prompt login

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
staging/src/kubevirt.io/api/core/v1/schema.go

/area api-server
As set out in bug #8844 when `Timer` was previously empty it was not omitted from `Clock`  causing validation failures to be raised as an object was expected. This PR now ensures that `Timer` is omitted from `Clock` when empty, avoiding the validation failure.
Fixes #8844
```release-note
An empty `Timer` is now correctly omitted from `Clock` fixing bug #8844.
```

api: Ensure Timer is omitted when empty from Clock

---

tests/storage/guestfs.go

Run guestfs tests in parallel.
Fixes #
```release-note
None
```

Run guestfs tests in parallel

---

tests/storage/export.go

This PR fixes a minor error in the virtctl vmexport download snapshot test, so we use an appropriate volume name to download.
Fixes #
```release-note
NONE
```

Fix vmexport download snapshot test

---

tests/reporter/kubernetes.go

Make it easier to tell what's happening on a CI failure.
```release-note
NONE
```

Dump VM Exports on tests failure

---

tests/console/login.go

The expect "Caser" has only treated the `fedora` user when handling the detecting a logged in prompt.
Add also the `root` user.
Fixes #
```release-note
NONE
```

tests, console/login: Add fedora root prompt detection

---

manifests/generated/operator-csv.yaml.in
pkg/virt-operator/kubevirt.go
pkg/virt-operator/kubevirt_test.go
pkg/virt-operator/resource/generate/components/deployments.go
tests/operator_test.go

Small bug fix - use virt-operator custom image if provided.
This is another tiny follow-up to https://github.com/kubevirt/kubevirt/pull/8673, https://github.com/kubevirt/kubevirt/pull/8792 and https://github.com/kubevirt/kubevirt/pull/8811.
```release-note
Bugfix: use virt operator image if provided
```

Bugfix: use virt operator image if provided

---

pkg/virt-handler/BUILD.bazel
pkg/virt-handler/realtime.go
pkg/virt-handler/setsched.go

It is preferable to avoid CGO linking in virt-handler and limit it as much as possible to the virt-launcher (where it must link with the libvirt lib).
This is sometimes impossible, but in this case, the stable Linux API can be partially duplicated into the native Go code.
The CGO linkage had side effects on packages which imported the `virthandler` package, causing build issues.
(specifically, it collided with the e2e test binary)
Fixes #
While building the e2e tests, the following error is seen on some platforms:
```
/lib64/libc.so.6: version `GLIBC_2.32'
/lib64/libc.so.6: version `GLIBC_2.34' …
```

virt-handler: Replace CGO linking with a Go alternative

---

tests/storage/export.go

The VM start helper is using ginkgo `Eventually` to retry the spec update. In the retry flow, the vm variable is updated even when the update fails, which in practice initializes it.
Update the retry loop by storing the VM namespace and name upfront and using the stored names to fetch a fresh object content.
Fixes #
Test failure has been observed [here](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8903/pull-kubevirt-e2e-k8s-1.24-sig-storage-root/1599488862600564736).
This is the error:
```
20:42:54:   Unexpected error:
20:42:54:       <*errors.errorString | …
```

tests, storage, export: Fix VM start helper

---

pkg/storage/snapshot/restore.go
pkg/storage/snapshot/restore_test.go

https://github.com/kubevirt/kubevirt/commit/5cc62c0f8f1fc368ffc920ab29fda7b55272728f failed to accommodate repeat
attempts to reconcile a VirtualMachineRestore that in turn lead to
multiple calls to restoreInstancetypeControllerRevision being made for
the same ControllerRevision.
This change handles this case by ignoring any existing
ControllerRevisions found during the restore, assuming that the existing
ControllerRevision was created by a previous call to
restoreInstancetypeControllerRevision.
Future changes will check the contents of this ControllerRevision
against that of the VirtualMachineSnapshot to ensure they match.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …

instancetype: Ignore unexpected existing CRs during restore

---

hack/prom-rule-ci/prom-rules-tests.yaml
pkg/virt-operator/resource/generate/components/prometheus.go

Alerting on 20MB free space margin is too close, and late alert for the consumers. This PR increases the threshold to 50MB.
jira-ticket: CNV-21883
Fixes #
```release-note
Change KubevirtVmHighMemoryUsage threshold from 20MB to 50MB
```

Change KubevirtVmHighMemoryUsage threshold from 20MB to 50MB

---

images/vm-killer/BUILD.bazel
tests/utils.go

Currently, in order to run jobs with specific non-root users, the container spec is set with the userID.
Such a configuration is used on the vm-killer-image image. This however reqires higher SCC priviliges for the jobs running this image.
In order to avoid this, configuring the image to use a non root user on the container dockerfile image level.
Fixes #
```release-note
NONE
```

vm-killer-image, Add nonroot user to container image

---

pkg/hooks/manager.go

**What this PR does / why we need it**: This MR improves the errors in the `OnDefineDomain` method. Now we include errors when we fail on Marshal function. Also changed `Infof` logs to `Error` when error occurs.
```release-note
NONE
```

Improve errors in `OnDefineDomain` method

---

pkg/virt-operator/resource/generate/components/BUILD.bazel
pkg/virt-operator/resource/generate/components/deployments.go
pkg/virt-operator/resource/generate/components/deployments_test.go

**What this PR does / why we need it**: `kubevirt-prometheus-metrics` Service must be created with `ClusterIP` set to `None`. If not, we end up creating a LoadBalancer rule with endpoints equal to number of nodes in the cluster. If we have a 1000-node cluster, then we will have a LB rule with 1000 endpoints. For more info see: https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
```release-note
Service `kubevirt-prometheus-metrics` now sets `ClusterIP` to `None` to make it a headless service.
```

Set `clusterIP` field for kubevirt-prometheus-metrics service to `None`

---

WORKSPACE

Fix for https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8878/pull-kubevirt-build/1601145621404717056
```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
compilepkg: missing strict dependencies:
/tmp/cache/bazel/6f347497f91c9a385dcd9294645b76e0/sandbox/processwrapper-sandbox/289/execroot/kubevirt/external/com_github_sassoftware_go_rpmutils/uncompress.go: import of "github.com/xi2/xz"
No dependencies were provided. 
```
Fixes #
```release-note
NONE …
```

Fix dependency

---

tests/operator_test.go

Sometimes it takes a while until the pod is created in test_id:4927 when we update virt-components deployment and if the pod will be created after the call toallPodsAreReady in the AfterEach scope than we will run the next test with side effect of pending pods.
This is a manual back port PR of https://github.com/kubevirt/kubevirt/pull/8876/files
Fixes #
```release-note
NONE
```

[release-0.53]Fixing race that cause flackiness in functional tests

---

pkg/virt-operator/kubevirt_test.go

This PR fixes `pkg/virt-operator` test suite.
A [new test](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-operator/kubevirt_test.go#L2169) introduced unwanted side effect by setting environment variable in `mockEnvVarManager` which is a pointer to the struct shared by all tests.
Fixes #8927
```release-note
NONE
```

Fix gooveralls tests by unsetting VirtOperatorImageEnvName in AfterEach

---

cmd/virt-launcher/BUILD.bazel

We don't not need to set the selinux context for virt-launcher binary. Uploading the PR to test if it is actually required or not.
No matter what we set, we end up with the selinux labels for all files in the container:
```bash
$ kubectlexec -it virt-launcher-vmi-nocloud-t5pxv -- /bin/sh
sh-5.1$ ls -lhZ /usr/bin/virt-launcher
-r-xr-xr-x. 1 root root system_u:object_r:container_file_t:s0:c76,c631 56M Jan  1  1970 /usr/bin/virt-launcher
sh-5.1$ ls -lhZ /
total 4.0K
dr-xr-xr-x.   2 root root system_u:object_r:container_file_t:s0:c76,c631    6 Jan  1  1970 afs
lrwxrwxrwx.   1 root root system_u:object_r:container_file_t:s0:c76,c631    7 Jan  1  1970 bin -> usr/bin
dr-xr-xr-x.   2 root root system_u:object_r:container_file_t:s0:c76,c631    6 Jan  1  1970 …
```

Do not set selinux context for virt-launcher binary.

---

pkg/virt-handler/BUILD.bazel
pkg/virt-handler/retry_manager.go
pkg/virt-handler/retry_manager_test.go
pkg/virt-handler/vm.go

Currently, once a VM is Paused due to IO error, the VM status is flipping between Paused and Running multiple times per second. This because the virt-handler tries to restart the VM, and if the IOError is not resolved, the latter will be paused again.
In order to limit the impact to the apiserver, when a domain IOError occurs, an increasingly exponential backoff will be applied before retrying to start the VM again.
Co-authored-by: fossedihelm <ffossemo@redhat.com>
Co-authored-by: lzang <zangli@google.com>
Fixes [https://bugzilla.redhat.com/show_bug.cgi?id=2029391](https://bugzilla.redhat.com/sho …

vm-cycle: use exponential backoff when pause due to IO error

---

tests/migration_test.go

This PR https://github.com/kubevirt/kubevirt/pull/8586 fixed issues related to test_id 8482.
According to our [quarantine policy](https://github.com/kubevirt/kubevirt/blob/main/docs/quarantine.md), this test can now be taken out of quarantine.
Test grid: https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.24-sig-compute-migrations&width=5
```release-note
NONE
```

Dequarantine test_id 8482

---

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go

SATA hard-drives, in contranst to SATA cdroms, can't not have read only set because the SATA bus does not support it for disks.
This validation fix avoids running into libvirt sync errors like this:
```
command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: readonly sata disks are not supported')"
```
More information can be found in https://bugzilla.redhat.com/show_bug.cgi?id=915162.
```release-note
Fix read-only sata disk validation
```

Fix read-only validation for sata hard-drives

---

tests/infra_test.go
tests/libnet/cluster/cluster.go
tests/libnet/skips.go
tests/network/dual_stack_cluster.go
tests/network/expose.go
tests/network/macvtap.go
tests/network/port_forward.go
tests/network/primary_pod_network.go
tests/network/probes.go
tests/network/services.go
tests/network/vmi_istio.go
tests/network/vmi_lifecycle.go
tests/network/vmi_multus.go
tests/network/vmi_networking.go
tests/network/vmi_passt.go
tests/network/vmi_slirp_interface.go
tests/network/vmi_subdomain.go
tests/storage/storage.go

The virt-client is a singleton in the e2e test, therefore, it is preferable to just fetch it each time it is needed directly.
Passing it down the stack is redundant.
This in turn cleans a bit the tests, removing some boilerplate code.
Fixes #
```release-note
NONE
```

tests, libnet/cluster: Stop passing the virt-client

---

tests/operator_test.go

We saw that the pods were terminating and we could see an event of successful delete right after the timeout.
Test results flaky due to the short timeout.
```release-note
NONE
```
/cc @xpivarc

e2e test: Fix flaky test increasing timeout when changing replicas number

---

Makefile
WORKSPACE
hack/builder/Dockerfile
hack/bump-distroless.sh
hack/dockerized

This bumps automatically:
* distroless images
* the rpm based images with their dependencies
That should be all our production ready base-images.
Further the distroless bump was executed right away, so also updating the distroless images.
Fixes #8940
```release-note
Bump distroless base images
```

Add an entrypoint to bump all production relevent image dependencies

---

pkg/virt-operator/resource/generate/components/scc.go

Not all components are able to run with
runtime default seccomp profile. This will
allow to preserve current behavior -
run as unconfined.
Fixes #
```release-note
NONE
```

SCC: allow unconfined seccomp

---

pkg/rest/filter/filter.go

when deploy the kubevirt in an ipv6-only cluster, the remoteAddress field in virt-api rest log is truncated, which looks like `{"component":"virt-api","contentLength":2677,..."remoteAddress":"[fd00",` 
so we use the `net.SplitHostPort` to split the host and port, then log the real host in remoteAddress field.
Signed-off-by: huyinhou <huyinhou@bytedance.com>
Fixes #
```release-note
Fix remoteAddress field in virt-api log being truncated when it is an ipv6 address
```

Fix remoteAddress field being truncated when it is an ipv6 address

---

docs/metrics.md
tools/doc-generator/doc-generator.go

This PR adds kubevirt_vmsnapshot_disks_restored_from_source_total and kubevirt_vmsnapshot_disks_restored_from_source_bytes recording rules to the documentation in metrics.md.
Fixes #7720 
```release-note
NONE
```

Add VM snapshot recording rules to documentation
