kubevirt/kubevirt

WORKSPACE, hack/bump-distroless.sh
To make the script idempotent, we need to work around the fact that buildozer returns a non-zero exit code (3), if the commands succeeded, but the file was not changed. Now, first the digest is replaced with a timestamp, to force buildozer in having to change the file, even if the actual digest stayed the same since the last run.
Further, since that leads to more buildozer invocations, the commands are changed to take multiple instructions from stdin, to do batch modifications.
Fixes #8965 
```release-note
NONE
```
=> Improve the distroless bump script

hack/prom-rule-ci/prom-rules-tests.yaml, pkg/virt-operator/resource/generate/components/prometheus.go, tests/monitoring/monitoring.go
Signed-off-by: assafad <aadmi@redhat.com>
This PR adds to each of kubevirt alerts a label named `operator_health_impact`, which indicates how the alerts impact the operator health. This will enable us filtering alerts based on their impact on the operator health itself, rather than the workload, and to later have an operator health metric, which will tell the user what is the aggregated operator health.
This label gets one of the following values:
- `critical` indicates that the alert fires duo to an issue that impacts the operator health badly, and an action must be taken immediately in order to solve it (e.g. `VirtOperatorDown` alert).
-  `warning` indicates that the alert fires duo to an issue that soon might impact the operator health badly, and …
=> Add `operator_health_impact` label to each of kubevirt alerts

tests/container_disk_test.go, tests/hyperv_test.go, tests/libvmi/status.go, tests/network/expose.go, tests/security_features_test.go, tests/vm_test.go, tests/vmi_configuration_test.go, tests/vmi_gpu_test.go, tests/vmi_headless_test.go, tests/vmi_lifecycle_test.go
1. **Add error return value for `GetPodByVirtualMachineInstance` in libvmi**
Currently if a matching pod for vmi isn't exist yet by the time we call `GetPodByVirtualMachineInstance` than we will return nil
while the original the intent was to panic with: "no controlled pod was found for VMI" massage the panic is inside nested if statement that checks if an old unrelated err var is nil (probably a bug).
2. wait for the pod to be created when calling `GetPodByVirtualMachineInstance` in tests
where it's necessary .
3. Handle errs in other `GetPodByVirtualMachineInstance` calls where there is no need to wait for the pod
because we already waited for the vmi to be ready or schedule therefore the pod is created for sure.
4. Replace …
=> Fix and arrange `libvmi.GetPodByVirtualMachineInstance` function to avoid flakiness 

automation/test.sh
The ovirt templates server will be decommissioned soon. Update to download the VM images from a private gcs bucket where the images have been mirrored to.
Also remove unused rhel7 download.
Fixes #
This requires the following PR to be merged first:
https://github.com/kubevirt/project-infra/pull/2525
```release-note
NONE
```
=> Download Windows VM images from GCS bucket

hack/functests.sh
the e2e suite is called twice, for the parallel tests and again
for the serial tests. In case KUBEVIRT_E2E_RUN_ALL_SUITES is set,
even if the parallel suite had failures, the serial suite will run afterwards.
This situation may cause a loss in k8s-reporter dumps, since they will be deleted
by the cleanup procedure.
Thus move the k8s-reporter to k8s-reporter-parallel before
starting the serial suite.
validated using:
```
export KUBEVIRT_E2E_PARALLEL=true
export KUBEVIRT_E2E_RUN_ALL_SUITES=true
export KUBEVIRT_E2E_FOCUS="VMIlifecycle"
```
With assertions in both parallel and serial tests, I saw both 
```
_out/artifacts/k8s-reporter  
_out/artifacts/k8s-reporter-parallel …
```
=> [e2e tests]: k8s-reporter: protect artifacts from consequent run cleanup

pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go
defaultVMIResourceRequirements() is a function that is duplicated from Kubernetes' defaultContainerResourceRequirements() [1][2]. In Kubernetes' code, they are DeepCopying the value from the limit range that is applied to the VMI. This commit brings the same DeepCopy to our code. This is probably a bug fix that we aren't synced with.
p.s. since the original function is private we must duplicate it and cannot use it directly.
[1] https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go#L86
[2] https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/limitranger/admission.go#L214
```release-note
Align with k8s fix for default limit range requirements
```
=> Align with k8s fix for default limit range requirements

pkg/virt-operator/kubevirt.go, pkg/virt-operator/kubevirt_test.go, pkg/virt-operator/resource/apply/apps.go, pkg/virt-operator/resource/apply/apps_test.go, pkg/virt-operator/resource/apply/reconcile.go, pkg/virt-operator/resource/apply/reconcile_test.go
The install strategy job needs to make use of the infra placement hints
too, or sometimes people have the issue that the install strategy job
can't be placed on the right nodes (like not having appropriate taints)
and can never be scheduled.
Fixes #6813, fixes #6764
```release-note
The install strategy job will respect the infra node placement from now on
```
=> Set infra placement on the installstrategy job

pkg/virt-handler/node-labeller/node_labeller.go
This workaround is necessary because currently Opteron_G2 require svm by libvirt.
(see /usr/share/libvirt/cpu_map/x86_Opteron_G2.xml)
But libvirt still marks it as Usable:yes even without `svm` because it is usable by qemu.
(/var/lib/kubevirt-node-labeller/virsh_domcapabilities.xml)
For more info:
https://wiki.qemu.org/Features/CPUModels -
"Getting information about CPU models" section
https://bugzilla.redhat.com/show_bug.cgi?id=2122283
Fixes #
```release-note
NONE
```
=> Workaround to prevent libvirt error when using Opteron_G2 cpuModel without `svm` 

tests/monitoring/monitoring.go
This pull request removes the obligation to include a runbook URL annotation on all alerts. The enforcement of this requirement has been causing delays in the implementation of alerts, adding extra effort in monitoring contributors, and sometimes resulting in inaccurate runbooks. While runbooks are still supported and encouraged, they should be made optional to allow documentation contributors the time and freedom to create accurate and complete runbooks.
```release-note
NONE
```
=> Remove validation for runbook URL annotation on alerts

pkg/pointer/BUILD.bazel, pkg/pointer/pointer.go, tests/libvmi/BUILD.bazel, tests/libvmi/vmi.go
The pointer package has a single P function that returns the address of the given value.
It is aimed to replace `k8s.io/utils/pointer` with a generic version. Unlike the previous version, the generic one accepts any type.
To illustrate its usage, the initial usage is done in the e2e tests, at the libvmi package.
Fixes #
A more extensive work has been proposed on the original util implementation: https://github.com/kubernetes/utils/pull/269
However, that work is blocked until all its consumers will support generics.
```release-note
NONE
```
=> pointer: Introduce a generic pointer package

pkg/virt-handler/vm.go
The `handlePostMigrationProxyCleanup` function returns an error, but there's nothing in its implementation that might fail. Thus, it's perfectly fine to simplify its signature.
Fixes #
```release-note
NONE
```
=> virt-handler: simplify post migration proxy cleanup

pkg/virt-controller/services/renderresources.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go
Currently the resource requirements are absolutely hardcoded on hotplug pods, which makes it hard to play nicely with LimitRange's maxLimitRequestRatio: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#limitrangeitem-v1-core
Fixes #
- This just for making the situation better and not block usages where maxLimitRequestRatio is 1
(The one which makes the most sense?)
If someone goes maxLimitRequestRatio 2 they'd still fail with hotplug pods/containerdisk init containers etc
(Not sure how …
=> Take QoS into account in hotplug pod resource requirements

pkg/controller/controller_ref_manager.go, pkg/virt-api/rest/subresource.go, pkg/virt-api/rest/subresource_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/migration_test.go, pkg/virt-controller/watch/node.go, pkg/virt-controller/watch/node_test.go, pkg/virt-controller/watch/pool.go, pkg/virt-controller/watch/replicaset_test.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, pkg/virtctl/pause/pause.go, pkg/virtctl/pause/pause_test.go, pkg/virtctl/vnc/screenshot/screenshot.go, staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go, staging/src/kubevirt.io/client-go/kubecli/kubevirt.go, staging/src/kubevirt.io/client-go/kubecli/vmi.go, staging/src/kubevirt.io/client-go/kubecli/vmi_test.go, tests/migration_test.go, tests/pausing_test.go, tests/storage/snapshot.go, tests/testsuite/namespace.go, tests/vm_test.go
This is a follow-up to PR #8908.
Currently, the `VirtualMachineInstance` methods that are using an underlying REST client, are not receiving a context, thus are unstoppable from the outside.
Internally they use `context.Background()` when calling the underlying REST client.
Add the `context` parameter to the VMI's applicable methods:
- Patch
- Watch
- Screenshot
- Pause
- Unpause
Add the `context.Background()` to all calls to these methods.
Partially fixes issue #8885.
```release-note
client-go: Added context to additional …
```
=> client-go, VMI: Add context to applicable methods 2

pkg/storage/snapshot/snapshot_test.go, pkg/storage/snapshot/source.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, pkg/virtctl/softreboot/softreboot.go, pkg/virtctl/softreboot/softreboot_test.go, pkg/virtctl/vm/vm.go, pkg/virtctl/vm/vm_test.go, staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go, staging/src/kubevirt.io/client-go/kubecli/kubevirt.go, staging/src/kubevirt.io/client-go/kubecli/vmi.go, staging/src/kubevirt.io/client-go/kubecli/vmi_test.go, tests/softreboot_test.go, tests/storage/hotplug.go, tests/storage/snapshot.go, tests/subresource_api_test.go, tests/vmi_configuration_test.go, tests/vmi_headless_test.go
This is a follow-up to PRs #8908 and #9018.
Currently, the `VirtualMachineInstance` methods that are using an underlying REST client, are not receiving a context, thus are unstoppable from the outside.
Internally they use `context.Background()` when calling the underlying REST client.
Add the `context` parameter to the VMI's applicable methods:
- Freeze
- Unfreeze
- SoftReboot
- GuestOsInfo
- UserList
- FilesystemList
- AddVolume
- RemoveVolume
Add the `context.Background()` to all calls to these methods.
Partially fixes issue #8885. …
=> client-go, VMI: Add context to applicable methods 3

tests/container_disk_test.go, tests/hyperv_test.go, tests/libvmi/status.go, tests/network/expose.go, tests/security_features_test.go, tests/vm_test.go, tests/vmi_configuration_test.go, tests/vmi_gpu_test.go, tests/vmi_headless_test.go, tests/vmi_lifecycle_test.go
This PR is manual backport of  https://github.com/kubevirt/kubevirt/pull/8902/commits/7e53ea9cf346ef6f98217c1be206875a7d7924e8
Fixes #
```release-note
NONE
```
=> [release-0.58]Fix and arrange libvmi.GetPodByVirtualMachineInstance function to avoid flakiness

tests/hyperv_test.go
This is a tiny fix to one of our hyperv functional tests.
At the beginning of the test, a vmi is created and a `tests.RunVMIAndExpectScheduling(vmi, 60)` call is executed.
Afterwards, a `libvmi.GetPodByVirtualMachineInstance(vmi, vmi.Namespace)` is executed to get the vmi's running pod.
This exposes a race between the VMI being scheduled and the call to get its running pod.
Instead of `RunVMIAndExpectScheduling()`, now a `RunVMIAndExpectLaunch()` is called to ensure the pod already exists.
```release-note
NONE
```
=> Hyperv functest: wait until VM had started successfully

hack/cluster-deploy.sh
The bash regexp "os-*" somehow matches "k8s-1.26-centos9"
Fixes #
```release-note
NONE
```
=> cluster-sync: remove obsolete if statement that breaks centos9 providers

pkg/instancetype/instancetype.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go, staging/src/kubevirt.io/api/instancetype/register.go, tests/instancetype_test.go
/cc @0xFelix 
A requirement has arisen to expose the default instance type and preference metadata as labels to allow users (such as 
I) to make use of server side filtering. This change moves the recently landed but unreleased implementation for 
inferring instance type defaults from volumes over to using labels instead of annotations.
Fixes #
```release-note
`inferFromVolume` now uses labels instead of annotations to lookup default instance type and preference details from a referenced `Volume`. This …
```
=> instancetype: Switch default inference to labels

pkg/virt-config/virt-config.go
It was observed that recently memory limit applied to virt-chroot is too low in docker in docker
environemnt on Arm64 platform, which lead to e2e
test crash. Further profiling and optimization are needed.
Signed-off-by: howard zhang <howard.zhang@arm.com>
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-arm64/1611240965291380736
```release-note
NONE
```
=> virt-config: Increase DefaultDiskVerificationMemoryLimitMBytes

docs/metrics.md, hack/prom-rule-ci/prom-rules-tests.yaml, pkg/monitoring/migrationstats/collector.go, pkg/virt-operator/resource/generate/components/prometheus.go, tests/monitoring/monitoring.go
`kubevirt_migrate_vmi_succeeded_total` and `kubevirt_migrate_vmi_failed_total` contain the keyword `total`, which is incorrect because they hold the value per vmi, vmim and namespace
Fixes #
```release-note
Rename migration metrics removing 'total' keyword
```
=> Rename migration metrics removing 'total' keyword

tests/hyperv_test.go
The absence of stopped labeller is not a failure
Fixes #
```release-note
NONE
```
=> [release-0.53] Tests: Fix hyperv clean-up

pkg/instancetype/instancetype.go, pkg/storage/snapshot/BUILD.bazel, pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_test.go, pkg/storage/snapshot/snapshot_test.go
This is a follow up to #8466 that I've broken out of that PR given the need to refactor some existing code before using it during the restore of a `VirtualMachine`. This PR should ensure that the contents of any existing instance type or preference `ControllerRevisions` found during a restore to an existing `VirtualMachine` match those of the `VirtualMachineSnapshot`.
Fixes #
```release-note
NONE
```
=> Instancetype: Refactor ControllerRevision comparison code and use to check existing CR content during restore

pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go
Currently the resource requirements are absolutely hardcoded on hotplug pods, which makes it hard to play nicely with LimitRange's maxLimitRequestRatio: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#limitrangeitem-v1-core
Backport of https://github.com/kubevirt/kubevirt/pull/9025
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2159096
```release-note
BugFix: Hotplug pods have hardcoded resource req which don't comply with LimitRange maxLimitRequestRatio of 1
```
=> [release-0.53] Take QoS into account in hotplug pod resource requirements

tests/migration_test.go
The `By` sentence says that the config will be updated to allow autoconverge, but then the postcopy is activated.
Fixes #
```release-note
NONE
```
=> e2e tests: Fix mismatch between `By` sentence and code

tests/operator_test.go
Since Kubevirt now supports any custom image format (see https://github.com/kubevirt/kubevirt/pull/8673) the functional tests need to allow such formats.
In this commit, parseImage() function is changed to adjust to these new capabilities.
I've made the following examples to demonstrate how the new logic works:
see this example for `@sha256` version format: https://go.dev/play/p/oRmW0MqIfgp
see this example for `:my-tag` version format: https://go.dev/play/p/d_tjdC7-0KX
See https://github.com/kubevirt/kubevirt/pull/8673, https://github.com/kubevirt/kubevirt/pull/8792, https://github.com/kubevirt/kubevirt/pull/8811, https://github.com/kubevirt/kubevirt/pull/8887 for previous PRs in this area. …
=> Adjust operator functional tests to custom images specification

hack/common.sh
Currently, when Podman is available but not Docker, some `make` commands will fail by default (unless a podman.sock is exposed): `make fmt`, `make generate`, etc.
It is possible to create a Podman socket that understands Docker API (see https://stackoverflow.com/a/72693093). This is valuable, for example, when trying to use Podman inside Podman/Docker.
Currently, to detect if Podman exists, we check if the podman.sock exists. Since in most scenarios such a socket doesn't exist, this logic doesn't make sense.
Now, to detect if Podman is available, we execute "podman ps" and test its exit code - in the exact same way we detect Docker existance.
A similar logic exists in …
=> Fix podman CRI detection

cmd/virt-handler/virt-handler.go, docs/getting-started.md, pkg/virt-config/feature-gates.go, pkg/virt-controller/services/template.go, tests/security_features_test.go
By default, a custom SELinux policy gets installed by virt-handler on every node, and it gets used for VMIs that need it.
Currently, the only VMIs using it are the ones that enable passt-based networking.  
However, having KubeVirt install and use a custom SELinux policy is a security concern. It also increases virt-handler boot time 20/30 seconds.  
Therefore, a feature gate was introduced to disable the installation and usage of that custom SELinux policy: `DisableCustomSELinuxPolicy`.  
The side effect is that passt-enabled VMIs will fail to start, but only on nodes that use container-selinux version 2.192.0 or lower.  
container-selinux releases 2.193.0 and newer include the necessary permissions for passt-enabled VMIs to run successfully. …
=> Introduce a feature gate to disable the custom SELinux policy

automation/test.sh, tests/virtctl/scp.go, tests/virtctl/ssh.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/8955
This updates the functional virtctl tests for the ssh and scp commands to test local-ssh functionality depending on provided skip regexes.
Conflicts:
automation/test.sh
tests/decorators/decorators.go
tests/virtctl/scp.go
tests/virtctl/ssh.go
NOTE(0xFelix): The conflict is due to not having decorators and libssh refactorings in release-0.58. The tests are changed to fallback to KUBEVIRT_E2E_SKIP instead.
```release-note
None
```
=> [release-0.58] virtctl: Manual backport of update functional tests for excludenative build tag

tests/storage/export.go
Fixes the flaky test by being less strict about it requirements.
Fixes #
```release-note
NONE
```
=> Fix flaky test 'Export Route should populate external links and cert and contain route host`

hack/prom-rule-ci/prom-rules-tests.yaml, pkg/virt-operator/resource/generate/components/prometheus.go
This is a manual cherry-pick of both #8599 and #9073
Fixes #
```release-note
Change KubevirtVmHighMemoryUsage threshold from 20MB to 50MB
```
=> [release-0.53] Change KubevirtVmHighMemoryUsage threshold from 20MB to 50MB

api/openapi-spec/swagger.json, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/migration_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/migration.go, tests/migration_test.go, tests/monitoring/monitoring.go, tests/network/macvtap.go, tests/network/sriov.go, tests/storage/hotplug.go, tests/swap_test.go
The VMI status holds the MigrationState data that reflects the most updated status of an ongoing/completed migration.
However, the final state of a given migration does not propagate to the migration object.
The migration object only contains the final status (i.e failed/succeeded) without any additional information about the migration.
Keeping this additional could be very helpful when debugging migration related issues on a long running system. 
```release-note
Store the finalized VMI migration status in the migration objects.
```
=> Store the finalized VMI migration status in the migration object

tests/clone_test.go, tests/migration_test.go, tests/storage/datavolume.go
Remove a couple of tests from quarantine as they have been very stable in the periodic test lanes. 
- `[sig-storage] DataVolume Integration ... Starting a VirtualMachineInstance with a DataVolume as a volume source Alpine import [QUARANTINE] should accurately report DataVolume provisioning`
- `[rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system][sig-compute] VM Live Migration Starting a VirtualMachineInstance [Serial] migration monitor [test_id:6978][QUARANTINE] Should detect a failed migration`
- `VirtualMachineClone Tests VM clone simple VM and cloning operations regarding domain Firmware [QUARANTINE] should strip firmware UUID`
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …
=> Remove tests from quarantine

pkg/virt-controller/services/template.go
The value was being overridden by the container's SecurityContext.
Fixes #
```release-note
NONE
```
=> virt-controller: remove stale SecurityContext from hotplug pod

tests/decorators/decorators.go, tests/hyperv_test.go, tests/migration_test.go, tests/network/vmi_istio.go, tests/network/vmi_passt.go, tests/vmi_configuration_test.go
In some use-cases a user might want to test
KubeVirt within a cluster that is different
from kubevirt-ci therefore we should expose
the tests dependencies.
Please note that this PR goal isn't to replace all the
skips in func tests but to take small steps to this goal.
Fixes #
```release-note
NONE
```
=> [e2e tests]Add Labels to expose dependencies of tests

api/openapi-spec/swagger.json, manifests/generated/operator-csv.yaml.in, manifests/generated/rbac-operator.authorization.k8s.yaml.in, pkg/controller/conditions.go, pkg/util/status/BUILD.bazel, pkg/util/status/status.go, pkg/virt-controller/watch/pool.go, pkg/virt-controller/watch/pool_test.go, pkg/virt-controller/watch/vm_test.go, pkg/virt-operator/resource/generate/components/crds.go, pkg/virt-operator/resource/generate/components/validations_generated.go, pkg/virt-operator/resource/generate/rbac/controller.go, staging/src/kubevirt.io/api/pool/v1alpha1/types.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go
This is an attempt to add status/scale subresources to VM Pools. When I get the object, it still doesn't show up the subresources. Any guidance is much appreciated.
Signed-off-by: Marcelo Feitoza Parisi <marcelo@feitoza.com.br>
**What this PR does / why we need it**: This PR tries do add status and scale subresources to VM Pools in order to be able to support HPA.
**Which issue(s) this PR fixes**: *None*
**Special notes for your reviewer**: I would really appreciate any input so I can have this fixed and running accordingly.
```release-note
Adding support for status/scale subresources so that VirtualMachinePool now supports HorizontalPodAutoscaler
```
=> Add VMPool status/scale subresources for HPA Support

pkg/virt-handler/vsock/server.go
The VSOCK TLS improvement loads a different VSOCK module and causes the VSOCK feature broken
After merging PR #8889, VM creation with `autoattachVSOCK` failed. Libvirt complains about `failed to open vhost-vsock device`.
The host is GCE instance with Ubuntu 20.04 and the guest OS is also Ubuntu 20.04.
After debugging, it turns out that the [code](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-handler/vsock/server.go#L67) doesn't load the correct module in my setup.
```
lsmod | grep vsock
vmw_vsock_virtio_transport_common    32768  0
vmw_vsock_vmci_transport    32768  1
vsock                  36864  3 vmw_vsock_virtio_transport_common,vmw_vsock_vmci_transport
vmw_vmci               69632  1 …
```
=> Make sure the VSOCK system service loads the correct module

WORKSPACE
switch to git commit
Not exactly sure what's going on here but it appears that the contents of `https://api.github.com/repos/google/go-containerregistry/tarball/efb2d62d93a7705315b841d0544cb5b13565ff2a` changed.  Rather than using the new hash, maybe it's better to use git commit like other deps such as `org_golang_x_crypto` `com_github_masterzen_simplexml`, etc
Fixes #
```release-note
NONE
```
=> go_containerregistry download url hash changed

tests/network/vmi_networking.go
The test that examined if the PCI Address specification on input reached the guest has been passing even though no interface appeared (in the guest).
The test is fixed by using a proper PCI Address and simplifying the assertion.
Fixes #
```release-note
NONE
```
=> tests, network: Fix guest PCI address check

tests/migration_test.go
This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/9046
Fixes #
```release-note
NONE
```
=> [release-0.58] e2e tests: Fix mismatch between By sentence and code

pkg/storage/export/export/export_test.go, pkg/storage/export/export/links.go
If the export code cannot match on the route/Ingress host or domain with wild card, return the entire contents of the config map. Filter out expired or not yet valid certificates. This happens if the `kube-root-ca.crt` only contains the root CA for instance.
Fixes #
```release-note
NONE
```
=> Return entire CA PEM if unable to match host/domain for export

pkg/virtctl/root.go, pkg/virtctl/vm/BUILD.bazel, pkg/virtctl/vm/vm.go, pkg/virtctl/vm/vm_test.go, tests/vm_test.go
This adds 'expand' command to virtctl, whichs allows
to expand Virtual Machine spec by using CLI.
```
Add 'expand' command to virtctl
```
Signed-off-by: Ondrej Pokorny <opokorny@redhat.com>
=> Add virtctl expand command

pkg/virt-api/rest/subresource.go, pkg/virt-api/rest/subresource_test.go, tests/storage/hotplug.go
- Fix bug of allowing to add existing volume pvc/dv with another volume name: the code checked for volume.Name instead of checking the dv/pvc name.
- Fix bug of allowing to remove existing volume which wasnt hotplugged.
-  Add the check of add and remove volume to persistent add/remove volume code path - in case of add/remove to VM the checks should also happen.
Fixes # Jira: [CNV-23867](https://issues.redhat.com/browse/CNV-23867)
[CNV-24856](https://issues.redhat.com/browse/CNV-24856)
```release-note
Fix addvolume not rejecting adding …
```
=> Fix addvolume removevolume bugs

pkg/network/domainspec/generators_test.go, pkg/network/istio/ports.go
istio documentation specify the list of ports istio is using - https://istio.io/latest/docs/ops/deployment/requirements/#ports-used-by-istio
kubevirt is using this list to avoid forwarding traffic to the vm on those ports in case of masquerade binding. And to avoid opening socket on those ports in case of passt.
Some ports were missing in the list kubevirt is using, this PR adding the missing ports.
Fixes #
```release-note
NONE
```
=> Add missing ports to istio reseved ports list

tests/testsuite/BUILD.bazel, tests/testsuite/fixture.go, tests/utils.go
`ensureKubevirtInfra()` ensures that all kubevirt components are synced and ready for testing. Virt-operator does the same, and reports the status via the Kubevirt CR conditions. So it doesn't makes sense to compete virt-operator or to mimic its logic. Its enough to observe the Kubevirt CR conditions, and this change suggests exactly that.
```release-note
NONE
```
=> [e2e]: treat kubevirt CR conditions when preparing the environment

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, tests/storage/snapshot.go, tests/vm_test.go
Currently, when deleting a vm which has an associated vmi,
the vm object is immediately removed, while the vmi object wait
for the pod deletion first.
This can cause a misunderstanding in case the vmi is not deleted
due to some errors. For example, the subsequent creation of a vm
with the same name results in the adoption of the pending vmi.
Adding a finalizer on the vm object prevents new vm creation with
the same name to be avoided, since the original vm object remains
in a terminating state, until the vmi object is gone.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2132873
**Special …
=> Add VirtualMachine foreground finalizer

tests/infra_test.go
Tests that check for running in serial need to get adapted to use info from the current spec, since there's no more separate running, thus the `ParallelTotal` will stay the same, even if the test is run in Serial mode
Fixes #
```release-note
NONE
```
=> Fix check for Serial run

api/openapi-spec/swagger.json, pkg/storage/export/export/vm-source.go, pkg/storage/export/export/vmsnapshot-source.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/export/v1alpha1/deepcopy_generated.go, staging/src/kubevirt.io/api/export/v1alpha1/types.go, staging/src/kubevirt.io/api/export/v1alpha1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/storage/export.go
For display purposes it is handy to have the VM name of the VM/VMSnapshot available in the export status. Added a new field containing the name and populating it during the standard reconcile loop.
Fixes #
```release-note
Show VirtualMachine name in the VMExport status
```
=> Show VM name in export status

automation/perfscale-test.sh
The performance cluster had to be rebuilt due to issues running the workloads against the cluster.
This update points the port-forward to the new prometheus service in the rebuilt cluster.
Tested locally against the new performance cluster
Fixes #
/cc @dhiller @rthallisey 
```release-note
NONE
```
=> Update performance automation to point to new prometheus svc

pkg/storage/export/export/export.go, pkg/storage/export/export/links.go, pkg/storage/export/export/pvc-source.go, pkg/storage/export/export/vm-source.go, pkg/storage/export/export/vmsnapshot-source.go, pkg/storage/export/export/vmsnapshot-source_test.go, tests/storage/export.go
This PR fixes an inconsistency between the links displayed in the vmexport status and the actual path in the export-server when exporting snapshots.
While the links are still generated using the restore PVC name, the volume name displayed in the status matches the original volume as appears in the VM, so users can easily identify their download target.
```release-note
NONE
```
=> Fix inconsistency between export-server and vmexport status links

automation/test.sh, cmd/virt-handler/virt_launcher.cil, hack/functests.sh, tests/decorators/decorators.go, tests/flags/flags.go, tests/security_features_test.go, tests/testsuite/kubevirtresource.go
The custom SELinux policy is not required anymore when running recent OSes like Centos 9.
This PR also updates the custom policy with more passt permissions found while testing on Centos 9. Not sure if any of them is critical, but it's better to have them to ensure proper passt behavior when using the custom policy.
Fixes #
```release-note
NONE
```
=> Disable the use of the custom SELinux policy on Centos 9 providers

tests/operator/BUILD.bazel, tests/operator/operator.go
We can't perform a check if Pod was created without Seccomp
profile on clusters where PSA is enabled because the Pod
will be denied.
Therefore we need to verify we at least see PSA related error.
Fixes #
```release-note
NONE
```
=> Tests: Fix seccomp on psa enabled clusters

cmd/virt-handler/virt_launcher.cil, pkg/util/util.go, pkg/virt-config/virt-config.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, tests/network/vmi_passt.go, tests/storage/storage.go, tests/vmi_configuration_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/8402
Fixes #
It is a big oversight that this PR was not included in the original release.
This will break platform upgrades to recent OSes like Centos9. (and already breaks the upgrade test in release-0.59 on Centos 9 lanes)
```release-note
Most VMIs now run under the SELinux type container_t
```
=> [release-0.58] virt-launcher: use our custom SELinux type only when necessary

pkg/storage/types/dv.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, tests/storage/datavolume.go
For consistency with other k8s objects, we allow creating clone DataVolumes even when the source PVC doesn't exist. This means that a VirtualMachine can be successfully created with volumes that may remain unpopulated until the source PVC is created.
This PR improves the handling of this case, so we check if the source PVC exists and, if not, we trigger an event to let users know.
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2145223
```release-note
NONE
```
=> Improve handling of clone DataVolumes without source PVC

pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/converter_test.go, tests/vmi_vsock_test.go
Qemu removes the support for virtio transitional in https://gitlab.com/qemu-project/qemu/-/commit/6209070503989cf4f28549f228989419d4f0b236
**What this PR does / why we need it**: 
The VSOCK feature is broken when using virtio transitional.
QEMU gives the error `'vhost-vsock-pci-transitional' is not a valid device model name`.
After debugging, I found `vhost-vsock-pci-transitional` is removed from QEMU in https://gitlab.com/qemu-project/qemu/-/commit/6209070503989cf4f28549f228989419d4f0b236
Fixes #
```release-note
NONE
```
=> Force to use the virtio non-transitional for VSOCK device.

tests/operator/operator.go
The PSA violation is in the Message not in
the Reason
Fixes #
```release-note
NONE
```
=> Tests: Fix seccomp test typo

tests/hyperv_test.go
Currently in some tests we are waiting for
the node labeller to be resumed in any nodes
including unschedulable nodes and that will not work
because master shouldn't be labeled by node
labeller.
Fixes #
```release-note
NONE
```
=> [e2e-tests]Should remove and restore labeler only from workers

pkg/virt-controller/watch/BUILD.bazel, pkg/virt-controller/watch/vmi_test.go, tests/decorators/decorators.go, tests/hyperv_test.go, tests/migration_test.go, tests/vmi_configuration_test.go
when tests require Reenlightenment they should require to expose Freq as well.
Fixes #
```release-note
NONE
```
=> [e2e-tests]If Reenlightenment is enabled Freq must be exposed

tests/libvmi/factory.go, tests/libvmi/vmi.go
This is partial cherry-pick of [#7858](https://github.com/kubevirt/kubevirt/pull/7858)
Eliminate boilerplate of dealing with VMI names. They better to be random, in order to avoid side-effects.
**Fixes:**
#8423 
```release-note
NONE
```
=> [release-0.49] tests: libvmi.New: no explicit name

pkg/instancetype/instancetype_test.go, pkg/storage/export/virt-exportserver/exportserver_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, tests/vm_test.go
This PR is a preparation for the next version of the ginkgolinter, that will enforce this change.
```release-note
None
```
=> Replace `HaveLen(0)` with `BeEmpty()`

staging/src/kubevirt.io/api/instancetype/v1alpha1/types.go, staging/src/kubevirt.io/api/instancetype/v1alpha1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go
This was actually switched to PreferSockets sometime ago by
https://github.com/kubevirt/kubevirt/commit/9d49758fffe76e62c296fbe826619401e1534efc.
Fixes #
```release-note
NONE
```
=> api: Correct default `PreferredCPUTopology` referenced in docs

pkg/virt-api/webhooks/validating-webhook/admitters/instancetype-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/instancetype-admitter_test.go, tests/instancetype_test.go
/cc @opokornyy 
This reverts commit 48a2adea3eec3aa267fdaa7139c8e74ca06fb07a.
Thanks to e7898af39b54298043adef02ae578d825743120e [1][2] we now apply defaults to a copy of the VirtualMachineInstanceSpec before running the associated validations in the VirtualMachine validation webhook. This actually resolves the original issue with enabling dedicatedCPUPlacement from instance types [3] as it ensures any guest visible memory is expressed as resources requests before we attempt to validate.
As such we can drop the blocking validations from the instance type webhooks and allow `dedicatedCPUPlacement` to be set once again.
[1] https://github.com/kubevirt/kubevirt/pull/9103 
[2] …
=> Revert "Add checks of dedicatedCPUPlacement to validation webhook"

tests/pool_test.go, tests/reporter/kubernetes.go
* The `status.Replicas` field indicate the amount VMs created for the pool. The `status.ReadyReplicas` indicated the number of running VMs that are ready. Therefore for tests that require a VM to reach its ready state the eventual poll will use `status.ReadyReplicas` 
* In test cases where scale in happens, make sure that the VMs that are left are owned by the actual pool. This will help with analyzing some situations where there are VMs that are not related to the pool.
* Add the `VirtualMachinePool` objects to the reporter logs
Tests that involved persistent storage were failing on some environments when those were bit overloaded.
```release-note
NONE
```
=> [e2e]: improve vmpool tests 

pkg/virt-api/webhooks/hyperv.go, pkg/virt-controller/watch/topology/BUILD.bazel, pkg/virt-controller/watch/topology/hinter.go, pkg/virt-controller/watch/topology/tsc.go, pkg/virt-controller/watch/topology/tsc_test.go, pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, pkg/virt-launcher/virtwrap/converter/converter.go, tests/BUILD.bazel, tests/migration_test.go
Manual backport of this PR: https://github.com/kubevirt/kubevirt/pull/8201.
```release-note
[Bug-fix]: Windows VM with WSL2 guest fails to migrate
```
=> [release-0.49] [Bug-fix]: Windows VM HyperV Reenlightenment enabled fails to migrate

tests/libstorage/pvc.go, tests/storage/memorydump.go, tests/virtctl/create_vm.go
`CreateFSPVC` is a helper function that creates a PVC. If you want to add some labels to the PVC, you are forced to Update the PVC just after the creation. This can cause some collisions during update because the object has been modified. Adding the `labels` parameter allows us to save an `Update` operation and avoid such collisions described above.
Fixes #
```release-note
NONE
```
/cc @akalenyu @enp0s3
=> [e2e] Add "labels" parameter to CreateFSPVC helper function

pkg/storage/export/export/export.go, pkg/storage/export/export/links.go, pkg/storage/export/export/pvc-source.go, pkg/storage/export/export/vm-source.go, pkg/storage/export/export/vmsnapshot-source.go, pkg/storage/export/export/vmsnapshot-source_test.go, tests/storage/export.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/9123.
This PR fixes an inconsistency between the links displayed in the vmexport status and the actual path in the export-server when exporting snapshots.
While the links are still generated using the restore PVC name, the volume name displayed in the status matches the original volume as appears in the VM, so users can easily identify their download target.
```release-note
NONE
```
=> [release-0.59] Fix inconsistency between export-server and vmexport status links

pkg/virt-controller/services/virtiofs.go
Signed-off-by: Romà Llorens <roma.llorens@gmail.com>
We found that with intensive disk usage, virtiofs container OOMs at the current limit (40M)
Bumping this limit to 80M solved our issue (Max usage observed is 71M)
Fixes #
Issue discussed on Slack Channel with @xpivarc
```release-note
Bump virtiofs container limit
```
=> Fix OOM virtiofs container limit

tests/network/BUILD.bazel, tests/network/vmi_multus.go
The security test for mac-spoof-check is failing on CentOS Stream 9 due to a permission problem to access files under the `/tmp` folder.
Mark the test with xfail so it will always run and on the problematic distribution it will not fail the suite.
Ref: https://github.com/kubevirt/kubevirt/issues/9245
---
https://github.com/kubevirt/project-infra/pull/2592
```release-note
None
```
=> tests, network: xfail mac-spoof-check

pkg/virt-api/rest/subresource.go, pkg/virt-api/rest/subresource_test.go, tests/storage/hotplug.go
This is a manual backport of #9133 
```release-note
Fix addvolume not rejecting adding existing volume source, fix removevolume allowing to remove non hotpluggable volume
```
=> [release-0.58]  Fix addvolume removevolume bugs

pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go
All VMI labels are synced to the VMI pod at creation time [here](https://github.com/kubevirt/kubevirt/blob/67a421b2d42dd43b3c26527363286e408ede6691/pkg/virt-controller/services/template.go#L1351). These labels can fall out of sync after creation time.
I don't necessarily want to get into the business of continually reconciling all pod labels to ensure they match what's on the VMI. That get's complicated quickly because people might be adding labels to the pods after creation time which we'd potentially squash afterwards by changing this existing behavior.
I would like to ensure a few well known labels remained synced from the VMI to the active VMI pod after live migration though.
```release-note
NONE
```
=> Sync VMI dynamic labels to pod after live migration

manifests/generated/operator-csv.yaml.in, pkg/virt-operator/resource/generate/components/daemonsets.go, pkg/virt-operator/resource/generate/components/deployments.go
Testers saw these max usage values:
virt-api: 485Mi
virt-controller: 252Mi
virt-handler: 315Mi
virt-operator: 419Mi
This PR adjusts the memory requests accordingly.
Fixes #
```release-note
NONE
```
=> virt-*: bump memory requests above highest values seen in testing

pkg/virt-api/api.go, pkg/virtctl/guestfs/guestfs.go, pkg/virtctl/guestfs/guestfs_test.go, staging/src/kubevirt.io/client-go/kubecli/guestfs.go
If the custom override exists, there is really no reason to assemble the url ourselves.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2158515
```release-note
BugFix: Guestfs image url not constructed correctly
```
=> Respect GS_IMAGE in virtctl guestfs

tests/mdev_configuration_allocation_test.go
The test looks to be quite flaky as it fails 29% of the time in the periodic vgpu lane [1]
This test also causes the vgpu lane in the kubevirtci repo to fail nearly everytime. [2]
[1] https://search.ci.kubevirt.io/?search=Should+override+default+mdev+configuration+on+a+specific+node&maxAge=336h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
[2] https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/check-up-kind-1.23-vgpu
Fixes #
```release-note
NONE
```
=> Quarantine flaky vgpu test that overrides default mdev config

pkg/virt-controller/watch/vm.go, tests/storage/datavolume.go
With https://github.com/kubevirt/kubevirt/pull/8937 a foreground finalizer has been added to the vm.
If `--cascade=orphan` is passed to a vm delete command the controller should not delete the associated vmi.
Fixes https://github.com/kubevirt/kubevirt/issues/9223
```release-note
NONE
```
/cc @xpivarc @maya-r
=> Fix vm deletion with --cascade=orphan

pkg/virt-launcher/virtwrap/manager.go, pkg/virt-launcher/virtwrap/manager_test.go
Checking the memory dump file path and seeing it already updated indicates that the request dump already occured or in progress we dont want to simply return we want to skip this duplicate call.
This bug was introduced in this commit: https://github.com/kubevirt/kubevirt/pull/8820/commits/f7c1a4c7a2c2a75c184ed3e99f0863b577a4f0ac
of refactoring the virt-launcher to use metadata cache instead of libvirt metadata #8820 
In it when identifying that the metadata is already updated with the dump path instead of skipping the core dump command it just returned silently.
So in case of calling the virt-launcher memory dump before the status of the memory dump updated on the VM as succeeded caused the core dump command to be called again although dump marked …
=> Fix bug of possible re-trigger of memory dump

hack/dockerized
The latest version of podman (>v4.4.0) has dropped the CHROOT capability from the default configuration[1]. The rsync container used as part of cluster-sync requires chroot capabilities so this causes it to fail.[2]
The update allows it to run successfully with podman >v4.4.0.
Also tested the docker flow and this change has no impact on users running with docker.
[1] https://blog.podman.io/2022/12/dropping-capabilities-making-containers-more-secure/
[2] https://github.com/kubevirt/kubevirt/issues/9279
Fixes #9279 
```release-note
NONE
```
=> Add chroot capability to rsync container in hack/dockerized

pkg/network/vmispec/interface.go, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go, staging/src/kubevirt.io/api/core/v1/types.go
At some scenarios like hypershift kubevirt provider the CNI will support        
doing live-migration when the VM net interface is bridged to the pod            
network. This change add a annotation to allow live migration is                
configured so on those scenarios.        
```release-note
Add annotation for live migration and bridged pod interface
```
=> virt-handler: Add live-migration bridge pod net annotation

tests/testsuite/namespace.go
Privileged namespace is meant to be allowed to run
any privileged Pod required by our test suit.
Okd/Openshift does have a mechanism that overrides a defined level of enforcement.
Fixes #
```release-note
NONE
```
=> Test: Fix PSA issue on OKD

cmd/virt-handler/virt-handler.go, pkg/virt-handler/BUILD.bazel, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go
This is needed to avoid breaking the LiveMigration condition for existing VMIs when upgrading from 0.49 to 0.53+.
Without this patch the existing VMIs with reenlightenment enabled will become non-live-migratable as they're missing topologyHints.
Fixes #
```release-note
Fix Live Migration for reenlightenment VMIs
```
=> [release-0.49] Fix Live Migration for reenlightenment VMIs

tests/storage/datavolume.go
These are slightly flaky on the centos9 lane, and we know the feature works as they sometimes pass. Let's quarantine them so the lane can be made mandatory for the branch.
Note that the fstrim feature is minor, and we know it works, but the tests are quite demanding.
Let's quarantine them while we investigate the failure - so that the sig-storage centos9 lane can be enabled.
```release-note
NONE
```
=> Quarantine fstrim tests so sig-storage-centos9 can be enabled

pkg/virt-config/feature-gates.go, pkg/virt-handler/device-manager/device_controller.go, pkg/virt-handler/device-manager/mediated_devices_types.go, pkg/virt-handler/device-manager/mediated_devices_types_test.go, pkg/virt-handler/heartbeat/heartbeat.go, tests/mdev_configuration_allocation_test.go
virt-handler is deleting any mediated device that is created on the system even if it explicitly 
configured as an externally provided resource.
```
permittedHostDevices:
mediatedDevices:
- externalResourceProvider: true
mdevNameSelector: NVIDIA A10-24Q
resourceName: nvidia.com/NVIDIA_A10-24Q
```
This PR prevents the deletion of externally configured mediated devices.
Mediated devices handling can be disabled altogether by setting a `DisableMDEVConfiguration` feature gate.
In this case, no mediated devices will be created or removed.
```
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
name: kubevirt
namespace: kubevirt
spec:
configuration:
developerConfiguration: 
featureGates:
- DisableMDEVConfiguration
- .....
- .....
```
**Which issue(s) this …
=> device manager: externally provided mediated devices should not be removed

cmd/virt-freezer/main.go, tests/storage/snapshot.go
As discussed in https://issues.redhat.com/browse/CNV-21659, this Pull Request updates the error message when virt-freezer fails on paused VMs so it's more descriptive.
Fixes #
```release-note
NONE
```
=> Improve error message when virt-freezer fails on paused VM

pkg/virtctl/imageupload/imageupload.go, pkg/virtctl/imageupload/imageupload_test.go
Fix a typo in the error message that is emitted when `imagePath` and `archivePath` are both empty.
Fixes #
```release-note
None
```
=> virtctl, image-upload: Fix a typo in an error message

pkg/virt-controller/services/renderresources.go, pkg/virt-controller/services/renderresources_test.go, tests/vmi_configuration_test.go
Recent code cleanup made the isolatedEmulatorThread CPU calculation mishandle the user-defined CPU Limits setting.
User-defined `resources.limits.cpu` simply overwrites the calculated value a causes the vmi pod to be rejected.
This PR is a minor fix to improve the CPU limits handling and explicitly set the calculated value for CPU limits.
Fixes # [rhbz#2166512](https://bugzilla.redhat.com/show_bug.cgi?id=2166512)
```release-note
fixes the requests/limits CPU number mismatch for VMs with isolatedEmulatorThread
```
=> bug: fix the requests/limits CPU number mismatch for VMs with isolatedEmulatorThread

pkg/virt-launcher/virtwrap/manager.go, pkg/virt-launcher/virtwrap/manager_test.go
To prevent weird behavior we shouldn't allow fsfreeze during migration.
Fixes #
```release-note
NONE
```
=> Fail fsfreeze of VMI in case it is during migration

tests/vmi_headless_test.go
`AgentConnected` condition requires more time to be added to the vmi. 30 seconds is really too small an amount of time. Increase up to 240.
Note: In the codebase generally it is used 12 Minutes
Fixes #
Related to https://github.com/kubevirt/kubevirt/pull/9297
```release-note
NONE
```
/cc @brianmcarey @xpivarc @iholder101
=> [e2e] Increase timeout for agentConnected condition

pkg/instancetype/instancetype_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, staging/src/kubevirt.io/api/core/v1/types.go
Signed-off-by: prnaraya <prnaraya@redhat.com>
**What this PR does / why we need it**: "Default" is not a supported mode, removes it from list of supported modes in the error message and prevents VM from getting stuck trying to start with an invalid value for "io" in "driver". From libvirt's XML D
From libvirt's Domain XML format [page](https://libvirt.org/formatdomain.html):
>  The optional io attribute controls specific policies on I/O; qemu guests support "threads" and "native" Since 0.8.8 , io_uring Since 6.3.0 (QEMU 5.0) .
Fixes #
```release-note
NONE
```
=> Remove "default" from supported disk IO modes

pkg/virtctl/expose/expose.go
VMI live migration changes the label kubevirt.io/migrationTargetNodeName
and the selector the VMI's service will no longer match. This change
remove that label from the selector similar to "kubevirt.io/nodeName".
/kind bug
```release-note
Skip label kubevirt.io/migrationTargetNodeName from virtctl expose service selector
```
=> virtctl, expose: Ignore migration target

pkg/virt-controller/services/renderresources.go, tests/storage/hotplug.go
Setting the ratio for mem/cpu to 1 allows the pod to be created under any combination of mem/cpu request/limit ratio. Added functional test to demonstrate various ratios work without issue.
This is a quick fix for just hotplug attachment pod containers for issue #9302 We should investigate a better option that doesn't waste some resources for resource constrained environments.
Fixes #
```release-note
NONE
```
=> Set mem/cpu request and limits on hotplug attachment pod container to 1 to 1 ratio

cmd/example-guest-agent/BUILD.bazel, cmd/example-guest-agent/main.go, pkg/certificates/triple/cert/cert.go, pkg/certificates/triple/cert/pem.go, pkg/certificates/triple/triple.go, pkg/storage/export/export/export.go, pkg/storage/export/export/export_test.go, pkg/virt-operator/resource/generate/components/secrets.go, pkg/virt-operator/resource/generate/components/secrets_test.go, tests/infra_test.go, tests/storage/export.go
Currently, kubevirt generates certificates with RSA signature. ECDSA, in general, create signatures faster than RSA. Also, OLM already uses ECDSA<sup>[1]</sup>, and it would be right to conform. The elliptic curve used is the NIST P-256 (FIPS 186-3, section D.2.3), also known as secp256r1 or prime256v1: this is supported by TLS1.3<sup>[2]</sup>.
<sup>[1]</sup> https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/controller/certs/certs.go#L31:L34
<sup>[2]</sup> https://www.rfc-editor.org/rfc/rfc8446#section-4.2.7
Fixes #
**Release …
=> Use ECDSA instead of RSA

cmd/virt-launcher/node-labeller/node-labeller.sh, pkg/virt-operator/resource/generate/components/BUILD.bazel, pkg/virt-operator/resource/generate/components/daemonsets.go
In a cluster with mixed x86 and arm workloads, the operator job deployment can not generate the daemonset spec properly for both x86 and arm handler nodes, as it has only one `runtime.GOARCH`.
So it's better to create the init container for all handler pods and do the arch check in node-labeller.sh instead.
Fixes #
```release-note
node-labeller: Check arch on the handler side
```
=> node-labeller: Check arch on the handler side

tests/vmi_cloudinit_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/9242
`libwait` package was introduced later than realease-0.53, so here we still use the package `tests`
Fixes #
```release-note
NONE
```
/cc @enp0s3
=> [release-0.53][e2e]: improve cloud-init user-data specs

api/openapi-spec/swagger.json, manifests/generated/kv-resource.yaml, pkg/virt-controller/services/renderresources.go, pkg/virt-controller/services/renderresources_test.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-handler/hotplug-disk/mount_test.go, pkg/virt-handler/isolation/detector.go, pkg/virt-handler/isolation/generated_mock_detector.go, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, pkg/virt-operator/webhooks/kubevirt-update-admitter.go, pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go, staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/vmi_configuration_test.go
Kubevirt computes [[1](https://github.com/kubevirt/kubevirt/blob/v0.59.0-alpha.2/pkg/virt-controller/services/renderresources.go#L272)] the estimation of the total memory overhead needed for infra components inside virt-launcher which are responsible to run the guest (e.g. libvirtd, qemu, etc).
Not only that this overhead currently suffers from known issues and non-accurate calculation which needs to be fixed - this calculation is in essence an educated guess / estimation, and not an accurate calculation. The reason is that even if a careful profiling will take place (which is a very difficult task to do, since the environments on which we would profile makes the results biased), there are still many components we cannot control, e.g. kernel …
=> Add guest-to-request memory headroom ratio

pkg/virt-controller/watch/drain/evacuation/BUILD.bazel, pkg/virt-controller/watch/drain/evacuation/evacuation.go, pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
virt-controller panic can happen if we play with migration configuration in Kubevirt CR.  Steps for reproduction can be
found in the BZ link below. 
In case the user drained a node with evictable VMs, migrations have started according to the configured maximum concurrent migrations per node. While the migrations are active the user decides lower the configured maximum per node. In this case the virt-controller can panic, although there are no free spots, there are no migration candidates either (because all VMs have active migrations). The execution loop continues with negative index.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2171395
**Special notes for the reviewer**:
```
runtime error: slice bounds out of range [:-9]
Full Stack Trace …
```
=> [virt-controller] fix out-of-bound slice index in evacuation controller

pkg/virt-controller/services/renderresources.go, tests/storage/hotplug.go
Manual backport of #9312 needed to adjust the functional test to use older mechanisms.
Fixes #
```release-note
NONE
```
=> [release-0.58] Set mem/cpu request and limits on hotplug attachment pod container to 1 to 1 ratio

pkg/virt-controller/watch/migration.go, tests/BUILD.bazel, tests/migration_test.go
For a long time, Libvirt was using the hostname
to perform a check if it performs migration
from&to the same node. This check was dropped
or rather it is implemented in another way
since 6799b72d927015db4ce4cab879f072abc91a41ae 2020.
Therefore we can drop this limitation and actually address a long-standing bug with services.
Fixes #
```release-note
Bug fix: DNS integration continues to work after migration
```
=> Remove hostname limitation for migrations

pkg/virt-api/rest/subresource.go, tests/pausing_test.go
Allow paused VM to migrate. This is currently possible only through VMIM API.
Fixes #
```release-note
Bug fix: API and virtctl invoked migration is not rejected when the VM is paused
```
=> Bug fix: Allow paused VM to migrate

pkg/virt-controller/services/renderresources.go, tests/storage/hotplug.go
Manual backport of #9312
Fixes #
```release-note
NONE
```
=> [release-0.59] Set mem/cpu request and limits on hotplug attachment pod container to 1 to 1 ratio

pkg/virt-handler/node-labeller/cpu_plugin.go, pkg/virt-handler/node-labeller/cpu_plugin_test.go, pkg/virt-handler/node-labeller/model.go, pkg/virt-handler/node-labeller/node_labeller.go, pkg/virt-handler/node-labeller/node_labeller_test.go, pkg/virt-handler/node-labeller/testdata/cpu_map/x86_Opteron_G2.xml, pkg/virt-handler/node-labeller/testdata/cpu_map/x86_Skylake-Client-IBRS.xml, pkg/virt-handler/node-labeller/testdata/virsh_domcapabilities.xml
Don't add a label with CPU model if the host does not support the required features. Libvirt may still mark such models as 'usable' as they can be used by qemu, however an attempt to run a VM on such a node will fail since it will not pass validation (KubeVirt does not explicitly disable the checking of CPU features for usable models):
https://libvirt.org/formatdomaincaps.html#cpu-configuration
This handles scenarios when cpu_map expects features deprecated on modern CPUs to be present:
https://gitlab.com/libvirt/libvirt/-/issues/304
Fixes #
This is a …
=> node-labeller: Take CPU features into account when labeling nodes

api/openapi-spec/swagger.json, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/vm_test.go
Provides clarity regarding if the vmi is out of date of the vm. 
Add observed and desired generation into the vm status which will track the observed generation that the vmi is updated with, as well as the desired generation for the vmi to be updated to.
Add vm generation into metadata of vmi, and add logic to backfill this from a vm controller revision if needed.
Previously there was no clear definition regarding if a vmi is out of sync with the vm. The controller revision name could be used, but this was not well defined and would also not be bumped if the spec stays the same. 
**Special notes …
=> Add observed and desired generation to the vm status

api/openapi-spec/swagger.json, manifests/generated/kv-resource.yaml, pkg/virt-controller/services/BUILD.bazel, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-handler/hotplug-disk/mount_test.go, pkg/virt-handler/isolation/detector.go, pkg/virt-handler/isolation/generated_mock_detector.go, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, pkg/virt-operator/webhooks/kubevirt-update-admitter.go, pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go, staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/vmi_configuration_test.go
Manual backport of: https://github.com/kubevirt/kubevirt/pull/9364.
```release-note
Add guest-to-request memory headroom ratio.
This can be enabled by setting `kubevirt.spec.configuration.additinalGuestMemoryOverheadRatio = "1.234"`
```
=> [release-0.49] Add guest-to-request memory headroom ratio

api/openapi-spec/swagger.json, manifests/generated/kv-resource.yaml, pkg/virt-controller/services/renderresources.go, pkg/virt-controller/services/renderresources_test.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-handler/hotplug-disk/mount_test.go, pkg/virt-handler/isolation/detector.go, pkg/virt-handler/isolation/generated_mock_detector.go, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, pkg/virt-operator/webhooks/kubevirt-update-admitter.go, pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go, staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/vmi_configuration_test.go
Manual backport of: https://github.com/kubevirt/kubevirt/pull/9322.
No conflicts occurred (not sure why the bot failed with automatic backport).
```release-note
Add guest-to-request memory headroom ratio.
This can be enabled by setting `kubevirt.spec.configuration.additinalGuestMemoryOverheadRatio = "1.234"`
```
=> [release-0.59] Add guest-to-request memory headroom ratio

tests/hyperv_test.go
Currently in some tests we are waiting for
the node labeller to be resumed in any nodes
including unschedulable nodes and that will not work because master shouldn't be labeled by node
labeller.
manual back-port of:
https://github.com/kubevirt/kubevirt/pull/9215
Fixes #
```release-note
NONE
```
=> [release-0.58]Should remove and restore labeller only from workers

pkg/virt-controller/services/template.go, tests/libstorage/BUILD.bazel, tests/libstorage/datavolume.go, tests/storage/hotplug.go
Manual backport of #9312 with some additional changes to add functions needed for the functional tests.
Fixes #
```release-note
NONE
```
=> [release-0.53] Set mem/cpu request and limits on hotplug attachment pod container to 1 to 1 ratio

pkg/config/config-map.go, pkg/config/config-map_test.go, pkg/config/config.go, pkg/config/downwardapi.go, pkg/config/downwardapi_test.go, pkg/config/secret.go, pkg/config/secret_test.go, pkg/config/service-account.go, pkg/config/service-account_test.go, pkg/virt-controller/services/rendervolumes.go, pkg/virt-handler/vm.go
Currently, using a virtiofs filesystem you can share ConfigMaps, Secrets and DownwardAPI volumes with the VM.  And if we share those volumes using virtiofs all the iso files are created since some parts of the code assumes that those volumes always have a Disk associated.
This PR refactors the code, so the iso files are not created if it's not necessary. It also removes the duplication of source/iso disk path calculation.
Fixes #
This is PR was part of #9254, but as requested we only included the refactoring commits
-->
```release-note
NONE …
```
=> Create iso files only if Disk is present

docs/getting-started.md
Since Bazel does not support OSX keychain, the current documentation asks mac users to deactivate the `Securely store Docker logins in macOS keychain` option in Docker Desktop's preferences. This is misleading since the option is no longer present in the Docker Desktop's preferences.
There are some nuances with the way docker handles authentication and [credential helpers](https://github.com/docker/docker-credential-helpers). This PR captures my learnings and updates the docs to be in sync with the way the system behaves now. 
In order to make docker store the credentials in the config.json file (so that Bazel can make use of it), we have to disable all the credential helpers. There appears to be no way to generally disable the credential helpers …
=> [Docs] Update Docs for Docker Authentication in Mac

examples/vm-alpine-datavolume.yaml, tools/vms-generator/utils/utils.go
http with a registry source is not a valid datavolume.
```release-note
NONE
```
=> Fix example YAML

tests/clone_test.go
This tests needs snapshotable storage class which we have only in the sig-storage lane. so far this tests were always skipped.
Fixes #
```release-note
NONE
```
=> Run clone tests that require special storage in storage lane

tests/vmi_cloudinit_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/9242
`libwait` package was introduced later than realease-0.58, so here we still use the package `tests`
Fixes #
```release-note
NONE
```
/cc @enp0s3
=> [release-0.58][e2e]: improve cloud-init user-data specs

pkg/virt-controller/watch/BUILD.bazel, pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, tests/network/hotplug.go, tests/network/vmi_multus.go, tests/testsuite/kubevirtresource.go
The guest agent interfaces are only computed from the virt-handler,
thus, we need to carry them over from the current status. Otherwise, we
would get caught in a reconcile storm between these two components.
Fixes #9396 
```release-note
NONE
```
=> Hotplug controller read guest agent iface status

pkg/virt-api/rest/interfacehotplug.go
The `request.AddInterfaceOptions != nil` has been used in a defensive manner on functions which are dedicated to adding an vNIC. I.e. the code flow would have reached these functions only if the operation has been recognized as a hotplug, implying that the request has this data and there is no need to re-check it again in the stack.
Fixes #
```release-note
NONE
```
=> virt-api, iface-hotplug: Drop redundant conditions

pkg/virt-launcher/virtwrap/converter/converter_test.go, pkg/virt-launcher/virtwrap/converter/network.go
The networks are already validated in the admission webhook, specifically the type part [1] which this change focuses on.
Such configuration validations on the VMI spec should not be needed at this layer of processing. The validation should be left higher in the stack, close to the API as possible.
[1] https://github.com/kubevirt/kubevirt/blob/2f3661e7d4de89ef9c61ec2692ae9db36db36e40/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go#L940
Fixes #
```release-note
NONE
```
=> virt-launcher, converter: Drop network validation

pkg/network/setup/netconf.go, pkg/network/setup/netconf_test.go, pkg/network/setup/network.go, pkg/network/setup/network_test.go, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go, pkg/virt-launcher/virtwrap/manager.go, pkg/virt-launcher/virtwrap/nichotplug.go
Embed most of the hotplug logic into the existing network setup flow.
This includes the logic of identifying if hotplug should be done and on which networks. Functions signatures have been adjusted to fit both the regular and hotplug setups.
The change handles both phase 1 and phase 2.
Future changes should strive to unify the logic, such that even a regular network setup can reconcile by hot-plugging the missing networks.
Fixes #
```release-note
NONE
```
=> network: Refactor network handling to integrate hotplug

WORKSPACE
This new version of bazeldnf contains a fix for the issue that we had to work around in 8052a7f3e30b ("rpm: Manually fix URL for passt package").
```release-note
NONE
```
=> bazeldnf: Update to v0.5.5

pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/network.go, pkg/virt-launcher/virtwrap/nichotplug.go
This PR exports the `isVirtIOProhibited` into a function.
It also changes the code to invoke this from within the `CreateDomainInterfaces` function.
Fixes #
```release-note
NONE
```
=> launcher: fix virtIONet prohibited func

api/openapi-spec/swagger.json, pkg/network/setup/netstat.go, pkg/network/setup/netstat_test.go, pkg/network/vmispec/BUILD.bazel, pkg/network/vmispec/hotplug.go, pkg/network/vmispec/hotplug_test.go, pkg/network/vmispec/infosource.go, pkg/network/vmispec/infosource_test.go, pkg/network/vmispec/interface.go, pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/network/hotplug.go, tests/network/sriov.go, tests/network/vmi_infosource.go
Network detected on the multus networks status pod annotation has been marked on the VMI status interface using a dedicated flag (`podConfigDone`).
This change removed the flag in favor of a new source option in the `inforSource` field.
The virt-controller detects a multus network status on the VMI pod and adds the `multus-status` source to the `infoSource` field. The virt-handler, when calculating the VMI status interfaces, preserves this information.
Fixes #
The API change is limited to a field added to the VMI Status interface a few weeks back and was not …
=> network, api: Replace `podConfigDone` field with `infoSource`

tests/launchsecurity/sev.go
Some rare test failures were observed. Give it a bit more time to detect the changes. That should mitigate potential high load issues.
Fixes #
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2023-03-14-024h.html#row36
https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-e2e-k8s-1.26-sig-compute/1635528122403131392
```release-note
NONE
```
=> Increase timeout for SEV device management test

automation/test.sh, tests/decorators/decorators.go, tests/network/hotplug.go, tests/network/vmi_multus.go
Currently, the sig-network gating lanes run tests with Multus v4.0.0-alpha (thick plugin form) which is not GAed yet.
In order to improve the sig-network lanes' integrity, set the lanes to run Multus v3 which is a GA'ed version.
Since the hotplug NICs tests depend on Multus v4 (thick plugin form) this PR set the e2e tests suite to check the env var `KUBEVIRT_WITH_MULTUS_V3`, if 'true', set the test suite to **not** run the in-place hotplug NICs tests.
This PR changes the sig-network lanes to run with Multus v3 (from manifests) instead of Multus v4 (using CNAO).
The hotplug NICs tests will run on a different periodic lane that runs Multus v4 https://github.com/kubevirt/project-infra/pull/2641
It also enable running sig-network tests with Multus v4 on …
=> Set sig-network lane run tests with Multus v3

automation/test.sh
Adapt and optimize test.sh to support k3d provider.
* Support k3d on test.sh - 
Adapt script to not run SR-IOV in parallel both for kind and k3d providers.
Do not export number of nodes for k3d, as k3d is fixed 1 control-plane and 2 workers.
* Skip sleep for kind / k3d providers - the sleep was [introduced](https://github.com/kubevirt/kubevirt/pull/8663) in order to reduce stress on disk
in case a lot of jobs start on the same time.
Since there is only one SR-IOV at a time, it is safe to let it start without delay.
The rest of the non SR-IOV jobs will have this sleep.
It will save us time while running SR-IOV jobs, which have very limited resources.
Same for kind vGPU, since it runs only one at a time (has anti affinity). 
* Skip cluster-down on CI …
=> e2e tests: Support k3d SR-IOV lane

tests/storage/storage.go
The following test has been impacting the storage test lanes over the past two weeks:
`Storage Starting a VirtualMachineInstance with faulty disk [It] should pause VMI on IO error`
As the impact has been greater than 5% over the past 14 days[1], this test qualifies for quarantine.
This test may also be impacting another storage test[2] so quarantining will allow us to see if this helps to reduce the flakiness.
[1] https://search.ci.kubevirt.io/?search=Starting+a+VirtualMachineInstance+with+faulty+disk&maxAge=336h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
[2] https://github.com/kubevirt/kubevirt/blob/main/tests/storage/storage.go#L159
[3] https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kube …
=> Quarantine flaky storage test that starts VMI with faulty disk

tests/operator/operator.go
Remove the custom profile before enabling the
feature-gate otherwise we might remove a newly
installed profile.
Fixes #
```release-note
NONE
```
=> tests: fix racy seccomp test

tests/hyperv_test.go
This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/9215
Fixes #
```release-note
NONE
```
=> [release-0.53] [e2e-tests]Should remove and restore labeler only from workers

pkg/virtctl/create/BUILD.bazel, pkg/virtctl/create/create.go, pkg/virtctl/create/preference/BUILD.bazel, pkg/virtctl/create/preference/preference.go, pkg/virtctl/create/preference/preference_suite_test.go, pkg/virtctl/create/preference/preference_test.go, tests/virtctl/BUILD.bazel, tests/virtctl/create_preference.go
This PR adds virtctl create preference command. This implementation does not cover all parameters that can be defined in a VirtualMachinePreference. Instead, it can be used as a starting point for users to streamline the creation of their own VirtualMachinePreference specifications.
```
Add 'create preference' command to virtctl
```
=> Add virtctl create preference command

pkg/virtctl/memorydump/memorydump_test.go, pkg/virtctl/utils/BUILD.bazel, pkg/virtctl/utils/test_utils.go, pkg/virtctl/vmexport/vmexport.go, pkg/virtctl/vmexport/vmexport_test.go, tests/monitoring/prometheus_utils.go, tests/storage/BUILD.bazel, tests/storage/export.go
In order to make it easier to copy VM (+1 disks) from one cluster to another, virtctl supports a new manifest flag for the `download` argument that allows one to get a manifest that you can directly apply to the target cluster if the target cluster can connect to the source cluster. The URLs associated with the disks will contain the export URLs, and the appropriate certificate config map and header secret are available.
Examples:
```bash
virtctl vmexport download export --manifest
virtctl vmexport download export --manifest --vm=example
virtctl vmexport download export --manifest --snap=example
virtctl vmexport download export --manifest --include-secret
virtctl vmexport download export --manifest --manifest-output-format=json
virtctl vmexport …
```
=> Add virtctl vmexport manifest option

pkg/virt-handler/vm.go
The fact that the migration method is `BlockMigration` is being logged every time any change occurred in the VMI object (even when the migration method had not changed).
This PR makes it such that the log will be shown only when:
1. We check the volumes for the first time (`vmi.Status.MigrationMethod == ""`)
2. The migration method was `LiveMigration` but it is going to be changed to `BlockMigration` 
The updated logs screenshot above shows that the block migration log is shown only once. 
Fixes #7214 
```release-note
None
```
=> [Fix] Get rid of noisy logs in `checkVolumesForMigration`

pkg/monitoring/vmistats/BUILD.bazel, pkg/monitoring/vmistats/collector.go, pkg/monitoring/vmistats/collector_test.go, pkg/virt-controller/watch/application.go
Recently Instancetypes and Preferences were added to simplify and reuse VM configurations. In this PR we will collect the Instancetypes and Preferences used in the `vmi_phase_count`.
Fixes #
```release-note
Add VM instancetype and preference label to vmi_phase_count metric
```
jira-ticket: https://issues.redhat.com/browse/CNV-22079
=> Add VM instancetype and preference label to vmi_phase_count metric

examples/example-migration-policy.yaml, tools/vms-generator/BUILD.bazel, tools/vms-generator/utils/BUILD.bazel, tools/vms-generator/utils/utils.go, tools/vms-generator/vms-generator.go
This PR adds a migration policy manifest example to our `/examples` directory.
This will ease playing with policies for either testing or exploration.
```release-note
NONE
```
=> Add an example migration policy to `/examples` directory

pkg/virt-launcher/virtwrap/manager_test.go
The PR includes some refactoring and fixes for `virtwrap/manager` unit tests:
- avoid using `AnyTimes()` in expectation for `VirDomain.Free()` since that does not ensure that the call has been made
- ~migration abort internally spawns an async goroutine. Need to wait untill it finishes to avoid flaky behaviour in the tests (separate commit)~
- small refactor of `GetAllDomainStats` test (in a separate commit)
Fixes #
```release-note
None
```
=> tests: Set exact expectations on VirDomain.Free() call

pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/network.go, pkg/virt-launcher/virtwrap/nichotplug.go
This is a follow-up to PRs #6852 and #9406.
Currently, CreateDomainInterfaces() is called in two scenarios:
1. Regular VM setup.
2. NIC hot-plug.
The function currently receives a variadic parameter [1] that represents the VM's logical interfaces that should to be plugged.
The function also have an internal logic to determine whether it was called from a setup or hot-plug scenario.
Adjust the function signature to fit both scenarios. Remove the above internal logic, similarly to what was done in PR #9406.
[1] https://go.dev/ref/spec#Function_types
Fixes #
PR …
=> virt-launcher, converter: Refactor CreateDomainInterfaces()

tests/vm_test.go
The AfterEach function deletes the vm created in the It spec.
This is used from two tests; in one of them the deletion is already performed,
but the vm does not disappear since it has a custom finalizer.
In AfterEach, before the vm deletion, the custom finalizer is removed from the vm.
Since the deletion was already fired the subsequent deletion may fail due to:
`Message: "virtualmachines.kubevirt.io \"testvmi-hcx9l\" not found",`
This fix prevents this flakiness by ignoring the "Not found" error.
Fixes #
```release-note
NONE
```
=> e2e: fix flakiness of vm foreground finalizer test

pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go, staging/src/kubevirt.io/api/core/v1/types.go
/area instancetype 
As set out in issue #9132 requests to update the `Name` of an `{Instancetype,Preference}Matcher` were always accepted regardless of the `RevisionName` also being updated. This would result in an older and likely unwanted `ControllerRevision` being used containing an outdated or completely wrong `Instancetype` or `Preference`.
With this change the VM mutation webhook will now reject requests to update the target `Name` of a `{Instancetype,Preference}Matcher` without also updating the `RevisionName`.
Fixes #9132 …
=> instancetype: Reject Matcher updates without updating RevisionName

tests/storage/export.go
Sometimes, the kernel kills the initial process and its children (such as the kill process) before the kill process returns, and it exits with error code 137 (processed SIGKILL'd).
Don't fail the test over this.
Motivated by this test flaking, for example [here](https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9376/pull-kubevirt-e2e-k8s-1.26-sig-storage/1632764098540212224).
```release-note
NONE
```
=> VMExport test: don't expect `kill 1` to succeed without error

tests/migration_test.go
The following test has been very flaky over the past week as can been seen in the latest flakefinder report[1].
`[rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system][sig-compute] VM Live Migration [Serial]with a dedicated migration network Should migrate over that network`
It has had a 9% impact over the past two weeks[2] so it qualifies for quarantine.
[1] https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2023-03-21-168h.html#row25
[2] https://search.ci.kubevirt.io/?search=Should+migrate+over+that+network&maxAge=336h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job …
=> Quarantine flaky migration test over dedicated network

hack/dep-update.sh, staging/src/kubevirt.io/client-go/go.sum
dep-update.sh has the following comment:
```
remove compat=1.17 when we move to go 1.18
```
Since we're running go 1.19+, this argument can be removed.
```release-note
NONE
```
=> Remove --compat=1.17 from dep-update.sh

tests/network/hotplug.go
The test following test is currently flaking sometimes:
- `cannot be subject to **hot** plug, but will mutate the template.Spec on behalf of the user`
Since the VM template is mutated by the virt-controller we may need to wait a bit before the change is actually seen in the VM. Thus, I am replacing the occurances of `Expect` by `Eventually` in this test.
Fixes #9446 
```release-note
NONE
```
=> hotplug, e2e: address stopped VM nic hotplug flake

tests/testsuite/fixture.go
When updating the Kubevirt CR, It takes time for the virt-operator to process the new desired state and report the status. If the HC function called in that time-frame we may think Kubevirt is synced. Therefore I've added another check, that compares the generation numbers. Its equity is an evidence that the execution loop of virt-operator is finished.
Another improvement is to check whether virt-operator is alive. Since KV CR is owned by a user rather than by virt-operator, if operator was deleted somehow, the CR is left and not cleaned by GC, and the status information there is not relevant.
Also, health-check added to the initial before suite stage (SynchronizedBeforeTestSetup)
```release-note
NONE
```
=> [e2e]: improve the kubevirt health-check function

OWNERS_ALIASES
Proposing Alice as an approver for kubevirt/kubevirt.
Since her first contribution in Aug. 2020 (https://github.com/kubevirt/kubevirt/pull/4027), Alice has been a steady and reliable contributor to KubeVirt.
She has more than 30 PRs merged: https://github.com/kubevirt/kubevirt/pulls?q=is%3Aclosed+is%3Apr+author%3Aalicefr+
She helped reviewing on more than 100 PRs : https://github.com/kubevirt/kubevirt/pulls?page=4&q=is%3Apr+commenter%3Aalicefr+is%3Aclosed+-author%3Aalicefr
When you go through her contributions, you will see a broad set of contributions. From implementing and maintaining her biggest feature -- libguestfs (This break-glass support has been a life-saver in many customer debug sessions for me) -- over fixing flakes unrelated to her …
=> Add alicefr as core approver

automation/test.sh, tests/decorators/decorators.go, tests/network/hotplug.go, tests/network/vmi_multus.go
Those tests will run only on network lanes that have multus v3.
Since hotplug to a pod was introduced on multus v4, clusters with multus v3 cannot support VM in place hot plug.
When hotplugging an interface to a VM running on a cluster with multus v3, the new interface will be added to the VM/VMI immediately, but the virt-launcher pod will be updated only after a migration (when a new virt-launcher pod will be created).
Only then the hotplug will be completed and the interface will be hot-plugged to the guest.
Fixes #
```release-note
NONE …
```
=> Migration based hotplug e2e tests

tests/console/console.go
The [NewExpecter](https://github.com/kubevirt/kubevirt/blob/13779f333957ec1937973262c91a21c06b0d30a3/tests/console/console.go#L214) constructor function is creating a serialConsole object and then spawns a generic process - both of which are included for the NewExpecter timeout.
Sometimes the first action takes longer than the whole timeout, causing the spawned process to start with no chance to finish within the overall timeout duration.
In order to fix this, Adding a check to prevent the spawned process from starting if the timeout has already passed.
Fixes # …
=> tests, console: Prevent NewExpecter negative timeout scenario

api/openapi-spec/swagger.json, pkg/controller/controller.go, pkg/virt-api/rest/interfacehotplug.go, pkg/virt-api/rest/interfacehotplug_test.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vmi_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, pkg/virtctl/network/dynamicifaces.go, pkg/virtctl/network/dynamicifaces_test.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/network/hotplug.go
PR #6852 introduced the AddInterfaceOptions struct, which is used as part of a NIC hot-plug.
Currently, this struct contains a field named `NetworkName`. The field name is misleading, because it represents the name of a NetworkAttachmentDefinition[1] object, and not a Network[2] object.
Rename this field so its name will properly represent its value.
Rename the `InterfaceName` field to `Name`.
Also apply similar changes to `virtctl`.
[1] https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/how-to-use.md#create-network-attachment-definition
[2] http://kubevirt.io/api-reference/main/definitions.html#_v1_network …
=> api, AddInterfaceOptions: Rename fields

tests/console/console.go
Lane https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-code-lint is failing
since https://github.com/kubevirt/kubevirt/pull/9497 was merged.
Fixes #
```release-note
NONE
```
=> Fix `make lint` lane failure

manifests/generated/operator-csv.yaml.in, pkg/virt-operator/resource/generate/components/daemonsets.go, pkg/virt-operator/resource/generate/components/deployments.go
This is a manual cherry-pick of #9125
Note: the values were adjusted to match actual release-0.49 testing
Fixes [rhbz#2078545](https://bugzilla.redhat.com/show_bug.cgi?id=2078545)
```release-note
NONE
```
=> [release-0.53] virt-*: bump memory requests above highest values seen in testing

manifests/generated/operator-csv.yaml.in, pkg/virt-operator/resource/generate/components/daemonsets.go, pkg/virt-operator/resource/generate/components/deployments.go
This is a manual cherry-pick of #9125
Note: the values were adjusted to match actual release-0.49 testing
Fixes [rhbz#2151170](https://bugzilla.redhat.com/show_bug.cgi?id=2151170)
```release-note
NONE
```
=> [release-0.49] virt-*: bump memory requests above highest values seen in testing

pkg/virt-operator/BUILD.bazel, pkg/virt-operator/kubevirt.go, pkg/virt-operator/strategy.go, pkg/virt-operator/strategy_job.go
Keep the latest used install strategy.
The current cache behavior is to cache every
install strategy and only clear the cache when
Kubevirt is uninstalled.
This is increasing memory consumption with every change
to Kubevirt CR and ultimately lead to oom.
Fixes #
```release-note
NONE
```
=> Fix operator oom

manifests/generated/operator-csv.yaml.in, pkg/virt-operator/resource/generate/components/daemonsets.go, pkg/virt-operator/resource/generate/components/deployments.go
This is a manual cherry-pick of #9125
Fixes [rhbz#2152518](https://bugzilla.redhat.com/show_bug.cgi?id=2152518)
```release-note
NONE
```
=> [release-0.58] virt-*: bump memory requests above highest values seen in testing

tests/console/console.go
This is a manual cherry-pick of #9497 and the proposed change in #9515.
Fixes #
```release-note
None
```
=> [release-0.58] tests, console: Prevent NewExpecter negative timeout scenario

hack/prom-rule-ci/rule-spec-dumper.go, pkg/virtctl/vm/vm_test.go, staging/src/kubevirt.io/client-go/kubecli/vmi.go, staging/src/kubevirt.io/client-go/util/util.go, tests/conformance/conformance.go, tests/libstorage/config.go, tests/monitoring/prometheus_utils.go, tests/operator/operator.go, tests/sysprep_test.go, tests/template_test.go, tests/utils.go, tests/virtctl/scp.go, tests/vm_test.go
The response from `/healthz` request is not closed.
Also, switch using non deprecated function call. In the specific I replaced:
- `ioutil.ReadAll` with `io.ReadAll`
-  `ioutil.ReadFile` with `os.ReadFile`
- `ioutil.WriteFile` with `os.WriteFile`
- `ioutil.TempFile` with `os.CreateTemp`
Fixes #
```release-note
NONE
```
=> Close resp.Body from `/healthz` requests and fix deprecated ioutil call

tests/console/console.go
This is a manual cherry-pick of #9497 and the proposed change in #9515.
Fixes #
```release-note
None
```
=> [release-0.59] tests, console: Prevent NewExpecter negative timeout scenario

pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, tests/vm_test.go
/cc @fossedihelm
/cc @0xFelix
As set out in issue #9438 previously attempts to remove a namespace would be blocked if it contained VirtualMachines using VirtualMachineInstancetypes. This was due to the update call to remove the virtualMachineControllerFinalizer being rejected as the ControllerRevision associated with the VirtualMachineInstancetype had already been deleted, causing admission of the request to be rejected.
This change adds basic logic to both the mutation and admission webhooks that returns early *if* the VirtualMachine is being deleted. Ensuring the update to remove the virtualMachineControllerFinalizer is successful and allowing the overall namespace removal to also complete. …
=> webhooks: Return early when VirtualMachine is being deleted

tests/utils.go
This PR reverts https://github.com/kubevirt/kubevirt/pull/9476 and increases timeout of `WaitForConfigToBePropagatedToComponent` function
Fixes #
```release-note
NONE
```
/cc @xpivarc
=> Increase timeouts for WaitForConfigToBePropagatedToComponent

pkg/virt-launcher/virtwrap/BUILD.bazel, pkg/virt-launcher/virtwrap/manager.go, pkg/virt-launcher/virtwrap/nichotplug.go, pkg/virt-launcher/virtwrap/nichotplug_test.go
We were currently hotplugging interfaces based on the interfaces present
in the `VMI.Spec.Interfaces`, but not present in the
`VMI.Status.Interfaces`, having its `PodConfigDone` attribute enabled.
This commit changes this, by hotplugging based on interfaces present in
the `VMI.Spec.Interfaces`, but not presently available in the
**domain**, which is more accurate.
/sig network
```release-note
Compute the interfaces to be hotplugged based on the current domain info, rather than on the interface status.
```
=> Hotplug network ifaces based on the current domain info, rather than on the interface status

pkg/virt-operator/util/config.go, pkg/virt-operator/util/config_test.go
now that its possible to pass the name of a virt-component image to the operator manifest using the VIRT_*_NAME env, its also possible to place a tag or digest of the container as part of the name, for example:
```
acme-dot-com/kubevirt/my-virt-handler@sha256:afafaf
```
In case a digest is in use, we would like to keep the functionality as it was when the *_SHA_SUM vars were used per each virt-component (this method is deprecated), thus when asking for component version, the digest will be return, if used.
**Which issue(s) this PR fixes** 
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2180146
Regarding unit tests, since there is a lot of place for refactoring, I've …
=> [virt-operator]: fix issue with retrieval of virt-component version

pkg/virt-launcher/virtwrap/manager.go, pkg/virt-launcher/virtwrap/nichotplug.go, pkg/virt-launcher/virtwrap/nichotplug_test.go
launcher, nic hotplug: refactor allowing unit tests
This refactor allows us to unit test the virt-launcher part of the nic
hotplug  feature.
We introduce a simple mock of the `VMNetworkConfigurator` struct, via
which we can simulate failures; a mock of the libvirtClient is also
used, to control both success and failures of the `AttachDevice` function.
Fixes #
Inner refactor to increase unit test coverage.
/sig network
Depends-on: #9428 
```release-note
NONE
```
=> Launcher nic hotplug unit tests

tests/vm_test.go
This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/9366.
Conflicts:
The `.Get()` and `.Delete()` function does not use `Context`
Fixes #
```release-note
NONE
```
=> [release-0.59] e2e: fix flakiness vm foreground finalizer test

pkg/virt-launcher/virtwrap/nichotplug.go
This was a leftover from PR [0], and is not needed since the "updated" domain interfaces are calculated in [1]. Thus, the function `virtIOInterfaceManager.hotplugVirtioInterface` does not require the `converterContext` at all.
[0] - https://github.com/kubevirt/kubevirt/pull/9429
[1] - https://github.com/kubevirt/kubevirt/blob/615f9e5b6da1976854aa225e517fb41faa91cc53/pkg/virt-launcher/virtwrap/converter/converter.go#L1768
Fixes #
```release-note
NONE
```
=> launcher: remove `converterContext` from virtIOInterfaceManager

tests/utils.go
Currently, when we update the kubevirtCR (in serial tests or in AfterEach function), we ensure that the config is propagated checking the revision number of the components. To do this, we do a port forward to the pods. This port-forward has a timeout of 10 seconds, and it is inside an Eventually block with max duration of 10 seconds and 1 second of polling interval. Since the next polling in the Eventually block does not start until the first one is finished, we only try once to do the port-forward. Let's try at least 2 times, decreasing the port-forward timeout to 5 seconds.
This commit reverts https://github.com/kubevirt/kubevirt/pull/9514 and reintroduces https://github.com/kubevirt/kubevirt/pull/9476
**Which issue(s) this PR fixes** *(optional, …
=> Decrease portForward timeout when waiting config to be propagated

api/openapi-spec/swagger.json, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/migration_test.go, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go, pkg/virt-launcher/notify-client/client.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/migration.go
When a live migration is in progress, we need a reliable indication that can tell us when the target pod is hosting the active qemu instance. We will be using this indication in OVNKubernetes to determine when to update the pod IP routes. 
The result of this PR is that the target pod will receive an annotation indicating the timestamp of when virt-handler detects the domain is running on the target node.
```release-note
NONE
```
=> Indication of when target pod hosts active qemu instance during live migration

tests/console/console.go
This is a manual cherry-pick of #9497 and the proposed change in #9515.
Fixes #
```release-note
NONE
```
=> [release-0.57] tests, console: Prevent NewExpecter negative timeout scenario

pkg/instancetype/instancetype_test.go, pkg/storage/export/virt-exportserver/exportserver_test.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, tests/vm_test.go
/hold
/cc @fossedihelm
/cc @0xFelix
/cc @mhenriks
As set out in issue https://github.com/kubevirt/kubevirt/issues/9438 previously attempts to remove a namespace would be blocked if it contained VirtualMachines using VirtualMachineInstancetypes. This was due to the update call to remove the virtualMachineControllerFinalizer being rejected as the ControllerRevision associated with the VirtualMachineInstancetype had already been deleted, causing admission of the request to be rejected.
This change adds basic logic to both the mutation and admission webhooks that returns early if the VirtualMachine is being deleted. Ensuring the update to remove the virtualMachineControllerFinalizer is successful and allowing the overall namespace …
=> [release-0.59] webhooks: Return early when VirtualMachine is being deleted

tests/console/console.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/9497 and the proposed change in https://github.com/kubevirt/kubevirt/pull/9515.
Fixes #
```release-note
NONE
```
=> [release-0.53] tests, console: Prevent NewExpecter negative timeout scenario

pkg/virt-operator/resource/generate/components/crds.go
This results in `k get all -n <namespace>` returning those cluster-scoped resources.
```bash
$ oc get all -n openshift-config
Warning: kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
NAME                                                                                AGE
virtualmachineclusterinstancetype.instancetype.kubevirt.io/cx1.2xlarge              5d22h
virtualmachineclusterinstancetype.instancetype.kubevirt.io/cx1.4xlarge              5d22h
```
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2177763 …
=> Remove "all" category from virtualmachineclusterinstancetypes/preferences

pkg/virt-operator/util/config.go, pkg/virt-operator/util/config_test.go
When the virt-operator image has digest instead of a tag, parse kubevirt version from KUBEVIRT_VERSION environment variable.
there was an issue when virt-operator image had digest instead of a tag, the hardcoded "latest" tag was used and KUBEVIRT_VERSION was ignored.
This led to an issue with tracking the kubevirt upgrade process. Periodic comparison of the KUBEVIRT_VERSION with the `status.observedKubevirtVersion` failed because the latter field got the `latest` string, instead of having the version as defined in KUBEVIRT_VERSION. 
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2180146
```release-note
NONE
```
=> [virt-operator]: fix kubevirt version parsing

pkg/virt-operator/util/config.go, pkg/virt-operator/util/config_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/9564
Fixes [rhbz#2180146](https://bugzilla.redhat.com/show_bug.cgi?id=2180146)
```release-note
NONE
```
=> [release-0.59] virt-operator: fix kubevirt version parsing

pkg/virtctl/create/BUILD.bazel, pkg/virtctl/create/clone/BUILD.bazel, pkg/virtctl/create/clone/clone.go, pkg/virtctl/create/clone/clone_suite_test.go, pkg/virtctl/create/clone/clone_test.go, pkg/virtctl/create/create.go, pkg/virtctl/create/instancetype/instancetype.go, pkg/virtctl/create/params/params.go, pkg/virtctl/create/vm/vm.go
This PR adds a `virtctl create clone` command.
Here's the full usage details:
```bash
> ./cluster-up/virtctl.sh create clone --help
Create a clone object manifest
Usage:
virtctl create clone [flags]
Examples:
virtctl create clone --source-name sourceVM --target-name targetVM
virtctl create clone --name my-clone --source-name sourceVM --target-name targetVM
virtctl create --source-name sourceVM
virtctl create clone --source-name sourceVM --source-type vm --target-name targetVM --target-type vm
virtctl create clone --source-name mySnapshot --source-type snapshot --target-name targetVM
virtctl create clone --source-name sourceVM --label-filter "*" --label-filter "!some/key" 
virtctl create clone --source-name sourceVM --annotation-filter "*" …
```
=> Add "virtctl create clone" command

pkg/virt-controller/watch/migration.go, tests/BUILD.bazel, tests/migration_test.go
For a long time, Libvirt was using the hostname
to perform a check if it performs migration
from&to the same node. This check was dropped
or rather it is implemented in another way
since 6799b72d927015db4ce4cab879f072abc91a41ae 2020.
Therefore we can drop this limitation and actually address a long-standing bug with services.
Fixes #
This is manual backport of https://github.com/kubevirt/kubevirt/pull/9189
The conflict was in imports and the RunMigrationAndExpectCompletion has different signature
```release-note
Bug fix: DNS integration …
```
=> [release-0.53] Remove hostname limitation for migrations

pkg/virt-controller/watch/migration.go, tests/BUILD.bazel, tests/migration_test.go
For a long time, Libvirt was using the hostname
to perform a check if it performs migration
from&to the same node. This check was dropped
or rather it is implemented in another way
since 6799b72d927015db4ce4cab879f072abc91a41ae 2020.
Therefore we can drop this limitation and actually address a long-standing bug with services.
Fixes #
This is manual backport of https://github.com/kubevirt/kubevirt/pull/9189
The conflict was in imports and the RunMigrationAndExpectCompletion has different signature
```release-note
Bug fix: DNS integration …
```
=> [release-0.58] Remove hostname limitation for migrations

cmd/virt-launcher-monitor/BUILD.bazel, cmd/virt-launcher-monitor/virt-launcher-monitor.go, cmd/virt-launcher/BUILD.bazel
The `virt-launcher` binary needs the `cap_net_bind_service` capability to work. Currently, we are using [xattr](https://man7.org/linux/man-pages/man7/xattr.7.html) as a part of the bazel build toolchain to add this capability (https://github.com/rmohr/bazeldnf/blob/main/pkg/xattr/xattr.go) to the binary executable file as a file capability. Ambient capabilities are a better solution for this use case. #8967 suggests we use ambient capabilities rather than file capabilities (using xattr). [Here](https://github.com/kubevirt/kubevirt/blob/main/cmd/virt-launcher/BUILD.bazel#L72) we can see the `cap_net_bind_service` capability added to the virt-launcher binary using xattr. 
Ideal solution would be to ask Kubernetes to start `virt-launcher-monitor` with …
=> [Refactor] Use ambient capabilities for the virt-launcher binary

pkg/virt-handler/hotplug-disk/mount.go, pkg/virt-handler/isolation/isolation.go, pkg/virt-handler/isolation/isolation_test.go
When a VM was running multiple NFS disks (one boot disk) and one hotplugged disk. The mount filtering was returning multiple possible mounts on the host, and sorting on the length of the 'root' path of the mount. For NFS these are the same (/). This caused the wrong NFS mount to be picked when hotplugging and an attempt was made to hotplug the boot disk. This commit improves the situation by passing the 'source' field to the filter, and it filters out entries that don't have matching sources. This allows us to find the correct mount on the host.
Fixes # …
=> Improve mountinfo filtering for hotplugging NFS disks

cmd/virt-launcher/node-labeller/node-labeller.sh
At some scenarios like running kubevirt on github actions there are not nested virtualization so kvm is not present at nodes and emulation have to be used, the node-labeller.sh script was failing if there is no kvm at pipefail. This change remove pipefail and also add "-x" to show the script and debug it in case of failure.
This prevent running stuff like https://kubevirt.io/quickstart_kind with emulation.
This issue was introduced at:
- https://github.com/kubevirt/kubevirt/pull/9320
/kind bug
```release-note
Adapt node-labeller.sh script to work at non kvm envs with emulation.
```
=> node-labeller: Remove pipefail to fix non kvm envs

WORKSPACE, cmd/example-cloudinit-hook-sidecar/BUILD.bazel, cmd/example-disk-mutation-hook-sidecar/BUILD.bazel, cmd/example-hook-sidecar/BUILD.bazel, images/winrmcli/BUILD.bazel, tests/BUILD.bazel
While creating a binary in my local Fedora 37 and pushing it to Fedora31 container, it would not run due conflict with libc. Fedora 31 was EOL in 2020-11-24, so the base image is overdue to an upgrade.
Further discussion in slack,  it was suggested to use distroless/base image as that is something we update more often.
```release-note
NONE
```
=> Move away from fedora 31 and use distroless/base instead

pkg/instancetype/instancetype.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go, tests/instancetype_test.go
As set out in issue #9431 it is valid for a DataVolumeSourceRef to not provide a namespace, the assumption being that the resource it points to is in the same namespace as the VirtualMachine.
This change handles this by switching to the namespace of the VirtualMachine when no namespace is provided by the DataVolumeSourceRef, avoiding a previous panic.
NOTE(lyarwood): conflict caused by
c09acad4db9cddf75c5b059d62c1074c40bd85ab not being present the in release-0.59 branch.
Signed-off-by: Lee Yarwood <lyarwood@redhat.com>
(cherry picked from commit 50befd593b10b6a5c2a574f12ff9c6cbd6a9674d)
Fixes # …
=> [release-0.59] instancetype: Handle DataVolumeSourceRef without namespace when inferring defaults

tests/storage/hotplug.go, tests/storage/imageupload.go
`namespace` in this context is the `--namespace` string
I guess this is not a problem in main because the tests are parallel so each one gets it's own fresh ns,
but, for older lanes such as 0.53 where these tests are serial we get
```
"reason": "FailedCreate",
"message": "failed to create virtual machine pod: pods \"virt-launcher-testvmi-lvm87-sm5n8\" is forbidden: [cpu max limit to request ratio per Container is 5750m, but provided ratio is 10.000000, memory max limit to request ratio per Container is 2250m, but provided ratio is 2.780720]"
```
on a totally different test.
Also changed variable names to avoid this confusion later on.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will …
=> [LimitRange tests]: Fix cleanup of LimitRange

api/openapi-spec/swagger.json, pkg/virt-api/api.go, pkg/virt-api/api_test.go, pkg/virt-api/rest/authorizer.go, pkg/virt-api/rest/authorizer_test.go
This cleans up the API by:
- by removing the duplicated '/apis' entry in the list of root paths
- by removing the test endpoint below VMIs doing nothing
- by avoiding a useless loop when adding the endpoint for
'/apis/subresources.kubevirt.io'.
The check for endpoints requiring authentication is improved by
explicitly stating every endpoint that requires no authentication.
This avoids running through a loop every time the virt-api is hit.
This also allows for finer granularity when specifying endpoints
which require no authentication.
```release-note
None
```
=> virt-api: Cleanup API and improve authentication required checks

hack/builder/arch.sh, hack/builder/build.sh, hack/builder/publish.sh, hack/builder/version.sh
/cc @brianmcarey 
/cc @rmohr 
/cc @xpivarc 
The builder-publish makefile target will now build and publish the
builder image in a single step. The version of the initial image now
being shared from the underlying build.sh script to ensure the correct
image is published.
Fixes #
```release-note
NONE
```
=> builder: Build and publish image using shared version

tests/storage/hotplug.go
Manual backport of the first commit in https://github.com/kubevirt/kubevirt/pull/9619
Fixes #
```release-note
NONE
```
=> [release-0.53] Manual backport - Fix cleanup of LimitRange

tests/storage/hotplug.go
Manual backport of the first commit in https://github.com/kubevirt/kubevirt/pull/9619
Fixes #
```release-note
NONE
```
=> [release-0.58] Manual backport - Fix cleanup of LimitRange

tests/testsuite/manifest.go
Sometimes we pick up the wrong disks-images-provider pod due to the deletion happening asynchronously.
It may be nicer to just make sure the deletion of the pods is done here.
This appeared to be the motivation in https://github.com/kubevirt/kubevirt/pull/2182
(Not sure why background was chosen, as that is the default)
Fixes #
```release-note
NONE
```
=> [e2e tests]: foreground delete testing manifests

pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, tests/storage/storage.go
Only proceed to template rendering when all PVCs are present.  The template renderer also checks for PVC existence, but if the PVC appeared between the check and the template rendering, the limited render-check will miss subtleties like checking if the PVC belongs to a DV and an import needs to be finished before creating the launcher pod.
This fixes a race, where sometimes a launcher pod for a VMI could already be created while the DV was in the middle of creating the PVC and importing.
As a consequence the VMI controller thinks that the import is already done and will just proceed with the VM start, which leads to a broken import and a failing VMI start. …
=> Check for PVC and DataVolume existence in a central place

pkg/virt-launcher/virtwrap/api/schema.go, pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/converter_test.go, pkg/virt-launcher/virtwrap/manager.go, pkg/virt-launcher/virtwrap/manager_test.go, staging/src/kubevirt.io/api/core/v1/types.go, tests/vmidefaults_test.go
With [freePageReporting](https://docs.kernel.org/mm/free_page_reporting.html) the [guest OS informs the hypervisor](https://lwn.net/Articles/808807/) about pages which are not in use by the guest anymore. The hypervisor can use this information for freeing these pages.
`freePageReporting` is an attribute that can be defined at [Memory balloon device in libvirt](https://libvirt.org/formatdomain.html#memory-balloon-device).
Currently, freePageReporting for the memballoon device is disabled by default, since in libvirt you need to explicitly enable it.
With this PR, freePageReporting will be enabled by default for all the new vmis which does not have `autoattachMemballoon` equal to false, *AND* which are not requesting any high performance components. …
=> Enable freePageReporting at vmi level

pkg/virt-operator/util/config.go, pkg/virt-operator/util/config_test.go
**Background**
***Kubevirt upgrade process***
The upgrade process consists of the following steps:
* Patching of the virt-operator deployment and the core resources (RBAC, service-account, etc).
* (Optional) Re-create the Kubevirt CR.
* New virt-operator re-creates the install strategy.
* New virt-operator patches the control plane deployments (virt-api, virt-controller, virt-handler, etc.)
In order to trigger the upgrade you can choose one of these methods to patch your virt-operator deployment:
**1**. Operator image pull URL, KUBEVIRT_VERSION 
**2**. Operator image pull URL, SHASUM of each operand (this way is deprecated).
**3**. Operator image pull URL, VIRT_*_NAME of each operand.
**Note**: There is another semi-upgrade process where you can …
=> [virt-operator]: Fix kubevirt version parsing when custom operator image name provided 

tests/vm_test.go
Use libvmi in tests/vm_test.go and do the following refactorings:
- Inline newVirtualMachine and NewRandomVirtualMachineWithRunStrategy
- Rename import of virtctl to allow variables named 'vm'
- Remove duplication of createVirtualMachine()
- Deduplicate VM creation and JSON serialization
- Refactor startVM and stopVM
- Use Eventually where possible
- Use appropriate matchers in virtctl tests
- Consistently name variables across file
- Use const and type inferring where possible
- Fix typos and whitespace
- Replace deprecated call to ioutil.TempFile
```release-note
None
```
=> tests/vm_test.go: Use libvmi and refactor

pkg/virtctl/create/params/params.go, pkg/virtctl/create/vm/vm.go, pkg/virtctl/create/vm/vm_test.go, tests/virtctl/create_vm.go
This adds a new param `bootorder` to flags of `virtctl create vm`,
which allows to specify the boot order of added volumes.
Support for fields of type `*uint` is added to `params.go` for this. 
Also some refactorings are applied to `virtctl create vm`.
The param is added to the following flags:
- volume-containerdisk
- volume-datasource
- volume-clone-pvc
- volume-pvc
The method getInferFromVolume is added to vm.go to allow inferring
instancetypes or preferences from the disk with the lowest boot order or
if no boot order was specified the first volume.
```release-note
virtctl: Allow to specify the boot order of volumes when creating VMs
```
=> feat(virtctl): Add boot order support to create vm

tests/kubectl_test.go
Starting from version 1.27, `kubectl explain` returns
metadata	<ObjectMeta>
instead of
metadata	<Object>
Fixes #
```release-note
NONE
```
=> tests: Support the output from recent kubectl

pkg/virt-controller/watch/topology/filter.go, pkg/virt-controller/watch/topology/tsc.go, pkg/virt-controller/watch/topology/tsc_test.go
It is possible to migrate VMs to nodes that have a TSC frequency within 250PPM of theirs.
This adds support for it by tagging nodes with VMI frequencies within the tolerance range.
Fixes RHBZ#2184860
```release-note
TSC-enabled VMs can now migrate to a node with a non-identical (but close-enough) frequency
```
=> TSC frequencies: add 250PPM tolerance

pkg/virt-controller/services/virtiofs.go, tests/virtiofs/config.go
Currently, we can share configuration volumes, such as ConfigMaps, Secrets, DownwardAPI and ServiceAccount using virtiofs, but the virtiofs container requires to be run as root. 
Virtiofsd supports being run without privileges, so this PR to modify the container to run as the unprivileged user when sharing configuration volumes.
Reported-by: Javier Cano Cano <jcanocan@redhat.com>
Tested-by: Javier Cano Cano <jcanocan@redhat.com>
Related #7735
```release-note
Add support for running virtiofsd in an unprivileged container when sharing configuration volumes.
```
=> Run the virtiofsd container as non-root for config volumes

pkg/virt-controller/watch/vmi.go
Change warning event to informal event in case that a DataVolume did not yet create a PVC.
The associated warning appears now pretty often since we now also watch for PVC creations.
An example occurance:
```
Unexpected Warning event received: testvmi-ljj6b,ea924cc3-98fe-4cb7-a578-df78ec4f946f: PVC kubevirt-test-default3/test-datavolume-75kg65rhgcwr does not exist, waiting for it to appear
Expected
<string>: Warning
not to equal
<string>: Warning
```
This is now much more often seen since #9435
Fixes #
```release-note
NONE
```
=> When a DataVolume is created, it is not clear when a PVC will appear

pkg/virtctl/create/preference/preference.go, tests/instancetype_test.go, tests/testsuite/namespace.go, tests/virtctl/create_preference.go
This PR removes dryRun options and adds functionality to CleanNamespaces to remove VirtualMachinePreference and VirtualMachineClusterPreference instead. It also updates help message for this command.
```
None
```
=> cleanup(virtctl): Remove dryRun options

WORKSPACE
Bazeldnf 0.5.6 will make dependency management easier since it now pulls in prebult binaries and does no longer have to build the binary.
This should avoid two problems:
* Previously we had to integrate bazeldnf golang dependencies which was error prone
* Updating gazelle was blocked because external bazeldnf dependencies are no longer resolvable with latest gazelle versions. These versions have significant improvements but changed some default behaviour.
Fixes #
```release-note
NONE
```
=> Bump bazeldnf to 0.5.6

hack/builder/build.sh
In order to only echo the build VERSION, some commands need their output redirected to stderr.
Fixes a regression introduced in #9604
Fixes #
```release-note
NONE
```
=> Fix version detection for builder build script

cmd/virt-handler/virt-handler.go, tests/framework/checks/checks.go, tests/security_features_test.go
This is a manual backport of https://github.com/kubevirt/kubevirt/pull/9639
```release-note
NONE
```
=> [release-0.59] SELinux policy: ensure it never gets installed if the feature gate is set

OWNERS_ALIASES
Replaces using `{}` with `[]` in OWNERS_ALIASES, which seems to confuse prow components resulting in lgtm and approve not appearing and [makes autoowners fail](https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/logs/periodic-project-infra-autoowners)
Fixes #
/cc @xpivarc @fabiand 
```release-note
NONE
```
=> Fix OWNERS_ALIASES formatting

pkg/virt-operator/resource/generate/components/prometheus.go
When scraping multiple instances of kube-state-metrics, there will be several series with a different label for instance.
Using sum() adds together the results from these kube-state-metrics.
By using max() instead, the maximum value seen from any kube-state-metrics is used, which is equivalent to scraping a single kube-state-metrics with sum().
Users running multiple copies of kube-state-metrics will receive intermittent unexpected alerts for OrphanedVirtualMachineInstances. This PR solves the problem by aggregating the result of kube-state-metrics.
Fixes # …
=> Update OrphanedVirtualMachineInstances alert

pkg/network/setup/BUILD.bazel, pkg/network/setup/configstate.go, pkg/network/setup/configstate_test.go, pkg/network/setup/network.go, pkg/network/setup/network_test.go, pkg/network/setup/podnic.go, pkg/network/setup/podnic_test.go
The network setup has processed each network/interface one at a time,
passing through all setup steps (discovery, configuration, persisting to
the cache).
This change adjusts the flow so each setup step will process all
networks before proceeding to the next step.
Following this pattern, enables the replacement of entire steps (e.g. configuring the pod networks).
Fixes #
~~Depends on #9053 (please review only the last 2 commits)~~
```release-note
NONE
```
=> network, setup: Iterate over all networks per each step

pkg/instancetype/BUILD.bazel, pkg/instancetype/compatibility.go, pkg/instancetype/compatibility_test.go, pkg/instancetype/instancetype_test.go
As set out in issue #9261 there have been reports of older VirtualMachineInstancetypeSpecRevision objects being stored in ControllerRevisions without APIVersion set. This is likely due to a known client-go issue [1] stripping TypeMeta from returned objects.
Given the limited support for v1alpha1 and the fact that we moved away from VirtualMachineInstancetypeSpecRevision to complete objects being captured in ControllerRevisions by v1alpah2 this change simply works around this issue by ignoring the value of APIVersion. This should allow the conversion to complete correctly until we upgrade these ControllerRevisions in the future.
[1] https://github.com/kubernetes/client-go/issues/541
**Which issue(s) this PR fixes** *(optional, in …
=> instancetype: Handle VirtualMachineInstancetypeSpecRevision without APIVersion

hack/prom-rule-ci/prom-rules-tests.yaml, pkg/virt-operator/resource/generate/components/prometheus.go, tests/monitoring/BUILD.bazel, tests/monitoring/component_monitoring.go, tests/monitoring/monitoring.go, tests/monitoring/prometheus_utils.go, tests/monitoring/scaling_utils.go
Add e2e tests for KubeVirtComponentExceedsRequestedCPU and KubeVirtComponentExceedsRequestedMemory alerts
I found that the KubeVirtComponentExceedsRequestedCPU and KubeVirtComponentExceedsRequestedMemory alerts were not being triggered when I added tests. The expressions used in these alerts used mixins not available on all clusters. Whenever I ran the expressions in Prometheus, the result was always empty. As a result, I updated the expressions and also updated the unit tests to reflect the new labels that were required.
jira-ticket: CNV-22403
Fixes # …
=> Add e2e tests for KubeVirtComponentExceedsRequestedCPU and KubeVirtComponentExceedsRequestedMemory alerts

pkg/virtctl/create/vm/vm.go, pkg/virtctl/create/vm/vm_test.go, tests/virtctl/create_vm.go
This changes the --infer-instancetype and --infer-preference flags to
take optional strings which allow to specify the volume of the VM from
which the instancetype or preference should be inferred from. If no
string is passed the previous behaviour is kept (infer from first boot
disk or first volume).
This is based on #9629, merge after.
```release-note
virtctl: Allow to infer instancetype or preference from specified volume when creating VMs
```
=> feat(virtctl): Allow to infer from specified volume in create vm

Makefile, hack/bazel-test.sh
During unit test development, it is very helpful being able to only test
a single package. This can be achieved by setting the variable WHAT.
Example:
export WHAT="//pkg/virt-handler/..."
make test
This speed up the execution of unit tests focused on a single package and it can be very useful for developers during the unit test development.
Even if you set a focus on a single test, this is effective only under a single path
Fixes #
```release-note
NONE
```
=> use variable to select packages to test for unit tests

tests/vm_test.go
Some of the VirtualMachineControllerFinalizer test use Eventually with a polling function but are missing a matcher to verify the polling function actually succeeds. This adds matchers where they are missing.
```release-note
None
```
=> tests/vm_test.go: Add missing matcher to Eventually

tests/vm_test.go
By explicitly setting the namespace in the virtctl expand tests the returned error will always contain the expected namespace. This is an issue on downstream tests where the default namespace can differ.
```release-note
None
```
=> tests/vm_test.go: Set NS in virtctl expand tests

pkg/virt-handler/isolation/generated_mock_isolation.go, pkg/virt-handler/isolation/isolation.go, pkg/virt-handler/vm.go, tests/utils.go, tests/vmi_configuration_test.go
Certain use-cases rely on injection of PIT interrupts to the guest in a timely fashion. Today, the kvm-pit kernel thread which is responsible for emulating PIT interrupts runs on housekeeping cores, sharing time with other kubernetes threads (such as kubelet). This has been found to be a problem for a particular workload requiring timely PIT interrupts (see trace below). The fix is to affine kvm-pit kernel thread to the same cpu as vcpu-0, when dedicated cpu placement is enabled in the guest configuration.
<idle>-0     [000] d.h. 102470.847586: hrtimer_expire_entry: hrtimer=00000000e3dea339 function=pit_timer_fn [kvm] now=102463903132805
<idle>-0     [000] d.h. 102470.847587: sched_waking: comm=kvm-pit/67 pid=1212317 prio=120 target_cpu=001
<idle>-0 …
=> affine kvm-pit kernel thread to vcpu-0 cpumask

pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/application_test.go, pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go
Remove the following unused fields from struct `VMIController`:
- `onOpenshift`
- `namespaceStore`
Fixes #
```release-note
NONE
```
=> virt-controller, VMI: Remove unused fields

pkg/virt-handler/BUILD.bazel, pkg/virt-handler/non-root.go
Virt-handler needs to perform an extra step for non-root VMIs with
macvtap interfaces: it needs to set the owner of the device files as the
pod user. Thus, to identify the ifindex of a pod interface, it was
needed to update the algorithm to find the corresponding pod interface.
Before this patch we were attempting to change the ownership of the file
pointed to by the name of the multus network - i.e. the network
attachment definition name. This was wrong: we need to use the name of
the pod interface (macvlan side). This only worked in CI since the name
of the net-attach-def used is `net1` - which [matches the name of the pod
interface](https://github.com/kubevirt/kubevirt/blob/c2a498a00f4f9ecc974f547db7db24f5a5f728bd/tests/network/macvtap.go#L66), …
=> macvtap: fix ownership change of the tap interface

pkg/instancetype/BUILD.bazel, pkg/instancetype/compatibility.go, pkg/instancetype/compatibility_test.go, pkg/instancetype/instancetype_test.go
This is a manual backport of https://github.com/kubevirt/kubevirt/pull/9584
```release-note
None
```
=> [release-0.59] instancetype: Handle VirtualMachineInstancetypeSpecRevision without APIVersion

pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-controller/services/virtiofs.go, pkg/virtiofs/BUILD.bazel, pkg/virtiofs/virtiofs.go, tests/virtiofs/BUILD.bazel, tests/virtiofs/datavolume.go, tests/virtiofs/feature_gate.go
It's currently possible to share config volumes using an unprivileged virtiofs container. So, let's remove the requirement for a feature gate for this type of sharing.
Tested-by: Javier Cano Cano <jcanocan@redhat.com>
Fixes # https://github.com/kubevirt/kubevirt/issues/7735
```release-note
NONE
```
=> virtiofs: Remove feature gate for config volumes

hack/prom-rule-ci/verify-rules.sh
By relabeling bind mounted test files the Makefile target prom-rules-verify is able to be used with Podman.
Additionally all files are mounted read-only.
```release-note
None
```
=> prom-rule-ci: Relabel bind mounted test files

pkg/network/setup/BUILD.bazel, pkg/network/setup/configstate.go, pkg/network/setup/configstate_test.go, pkg/network/setup/configstatecache.go, pkg/network/setup/configstatecache_test.go, pkg/network/setup/netconf.go, pkg/network/setup/netconf_test.go, pkg/network/setup/network.go, pkg/network/setup/network_suite_test.go, pkg/network/setup/network_test.go, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go
This PR extends ConfigState to contain in-memory cache alongside with
a file cache.
This is needed to avoid reading from the file each time the cache is
accessed.
Previously this cache was used by SetupPodNetworkPhase1 in virt-launcher's
network namespace.
This PR is changing the code to use this cache to check whether virt-handler should
try to plug an interface or not before entring the virt-launcher's network namespace.
Only if there is actually an interface to plug, virt-launcher's network namespace is entered.
The PR also removes NetConf.WithCompletionCache since now ConfigState cache is cehcked before entring the virt-launcher's network namespace it is redundant. …
=> virt-handler, net: Use ConfigState before entring virt-launcher's network namespace

tests/canary_upgrade_test.go, tests/infra_test.go
Takes tests:
* [sig-compute: Infrastructure changes to the kubernetes client on the virt handler rate limiter should lead to delayed VMI running states](https://github.com/kubevirt/kubevirt/tree/e7016777cc6e8207d8dbc0cc9dcb47d83a79e83c/tests/infra_test.go#L166)
* [sig-operator: virt-handler canary upgrade should successfully upgrade virt-handler](https://github.com/kubevirt/kubevirt/tree/e7016777cc6e8207d8dbc0cc9dcb47d83a79e83c/tests/canary_upgrade_test.go#L177)
See https://storage.googleapis.com/kubevirt-prow/reports/quarantined-tests/kubevirt/kubevirt/index.html
Fixes #
**Special notes for …
=> Take tests out of quarantine

cmd/container-disk-v2alpha/README.md, docs/updates.md, manifests/generated/kv-resource.yaml, manifests/release/demo-content.yaml.in, staging/src/kubevirt.io/api/core/v1/BUILD.bazel, staging/src/kubevirt.io/api/core/v1/doc.go, staging/src/kubevirt.io/api/core/v1/register.go, staging/src/kubevirt.io/client-go/kubecli/kv_test.go, staging/src/kubevirt.io/client-go/kubecli/migration_test.go, staging/src/kubevirt.io/client-go/kubecli/replicaset_test.go, staging/src/kubevirt.io/client-go/kubecli/vm_test.go, staging/src/kubevirt.io/client-go/kubecli/vmi_test.go, staging/src/kubevirt.io/client-go/kubecli/vmipreset_test.go
This change moves the storage version for all core API CRDs to v1. This does not impact existing objects that will continue to be stored using their original v1alpha3 version while being served as v1alpha3 or v1, as was the case previously.
Work will be required in the future to ensure all stored v1alpha3 objects are read and updated to v1 but for the time being this isn't required as part of this PR.
For more context please review the following k8s documentation:
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning
Additionally the following KubeVirt dev ML thread covers this topic:
https://groups.google.com/g/kubevirt-dev/c/bSayedthHmY
**Which issue(s) this PR fixes** *(optional, in `fixes …
=> api: Move the core API storage version to `v1` and deprecate `v1alpha3`

tests/utils.go
Due to datavolume garbage collection, there's a small race where we may inspect a PVC which refers to a DV, but the DV is already gone, causing spurious and short-lived errors.
We've opted not to fix this race in this PR:
https://github.com/kubevirt/containerized-data-importer/pull/2487
Tolerate the warning showing up - this is a rare occurrence.
[Example failure here](https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8796/pull-kubevirt-e2e-k8s-1.24-sig-storage-root/1592810005592018944)
```release-note
NONE
```
=> tests: Tolerate DV being missing warning

pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go
This PR would render the VolumeDevices on the `hp-volume-` pod, no matter if it is ever generated.
Fixes #9263 
I already had some discussions with @awels on this [thread](https://kubernetes.slack.com/archives/C8ED7RKFE/p1675734184935669).
We could continue here and also make it a note.
Thanks for your review!
```
Render VolumeDevices to hp-volume- no matter if it is ever generated.
```
=> virt-controller: render hp-volume- pod should respect blockdevices

tests/performance/density.go
This PR exports the performance job metrics into an artifacts directory
Fixes #
This is related to on going sig-scale effort to crunch performance metrics for kubevirt stack. 
The collection of results need an identifier to differentiate the metrics for each test.  Since `AfterEach` needs to have this differentiation, instead of co-ordinating AfterEach blocks of each test via a global variable, this PR shifts the collection of metrics as part of the test to avoid races in collection.
```release-note
```
=> sig-scale: export the audit tool result to files in artifacts directory

pkg/virt-api/rest/authorizer.go, pkg/virt-api/rest/authorizer_test.go
Add /apis as unAuth enpoint
This path is being queried by Kubernetes
\>= 1.27 and therefore needs to be exposed.
Fixes #9725
```release-note
NONE
```
=> Add /apis as unAuth enpoint

pkg/virt-handler/node-labeller/BUILD.bazel, pkg/virt-handler/node-labeller/model.go, pkg/virt-handler/node-labeller/node_labeller.go, pkg/virt-handler/node-labeller/node_labeller_test.go, staging/src/kubevirt.io/api/core/v1/types.go
If KSM is enabled (not only available) on a node,
then handler will add `kubevirt.io/ksm-enabled` label to the node.
Fixes #
```release-note
ksm enabled nodes will have `kubevirt.io/ksm-enabled` label
```
=> [node-labeller] Labeling of nodes with ksm enabled

pkg/virtctl/create/clone/clone.go, pkg/virtctl/create/clone/clone_test.go, pkg/virtctl/create/instancetype/instancetype.go
virtctl create clone command was introduced not long ago in this PR: https://github.com/kubevirt/kubevirt/pull/9596.
After the PR had merged, I received some further feedback. This follow-up addresses this feedback.
```release-note
NONE
```
=> virtctl create clone: minor improvements

pkg/apimachinery/resource/BUILD.bazel, pkg/apimachinery/resource/extend.go, pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/network.go, pkg/virt-api/webhooks/validating-webhook/admitters/network_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-controller/services/BUILD.bazel, pkg/virt-controller/services/renderresources.go, pkg/virt-controller/services/renderresources_test.go, pkg/virt-controller/services/template.go, pkg/virt-launcher/virtwrap/BUILD.bazel, pkg/virt-launcher/virtwrap/manager.go, pkg/virt-launcher/virtwrap/nichotplug.go, pkg/virt-launcher/virtwrap/nichotplug_test.go, tests/libvmi/BUILD.bazel, tests/libvmi/network.go, tests/network/hotplug.go
Introduce the `kubevirt.io/interface` resource name to reserve domain resources for network interfaces
Users may express the requested number of network interfaces that
the domain should reserve for future additions (hotplug).
The value is expressed through the VMI spec, as a resource-name
(`kubevirt.io/interface`) in the `resources.requests` list.
The value may be any integer between 0 and 32 (including).
The domain configuration is now generated as follows:
- Add to the domain configuration input, interfaces as placeholders.
- Create a (libvirt) object which contains auto-generated domain
configuration values (beyond the user input one).
- Remove the placeholder interfaces from the (full) domain configuration
- Create a new (libvirt) object which …
=> api, virt-launcher: Reserve domain resources for network interfaces

pkg/storage/snapshot/snapshot_test.go
Example flake:  https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9268/pull-kubevirt-unit-test/1651563524318564352
Pleoblem is that the test infra was not waiting for informers to start
Fixes https://issues.redhat.com/browse/CNV-28423
```release-note
NONE
```
=> Fix flaky VM snapshot test

pkg/virt-launcher/virtwrap/device/hostdevice/hostdev.go
This PR reduces the number of log entries produced by virt-launchers in `createHostDevice` function, by compacting multiple log records into a single one. Logs cluttering is especially significant when multiple devices are created often. 
```release-note
NONE
```
=> Make createHostDevices logs more compact

pkg/network/cache/podinterface.go, pkg/network/setup/BUILD.bazel, pkg/network/setup/configstate.go, pkg/network/setup/configstate_test.go, pkg/network/setup/configstatecache.go, pkg/network/setup/netconf.go, pkg/network/setup/podnic.go
Stop using the pod interface name as the cache key and use the logical
network name instead.
This should allow the unification of the pod-state and pod-interface
persisted storage.
---
The change includes:
- Do not override the existing data in the pod interface cache.
- Upgrade existing entries which use the previous keys (pod interface name) to the new keys (logical network name).
Fixes #
```release-note
NONE
```
=> network/setup: Use the logical network name for configstate cache keys

pkg/virt-api/webhooks/validating-webhook/admitters/network.go, pkg/virt-api/webhooks/validating-webhook/admitters/network_test.go, pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/converter_test.go, pkg/virt-launcher/virtwrap/converter/network.go, pkg/virt-launcher/virtwrap/nichotplug.go, pkg/virt-launcher/virtwrap/nichotplug_test.go, tests/libvmi/network.go
Follow up on several comments in https://github.com/kubevirt/kubevirt/pull/9746 .
It includes the interpretation processing of the `UseVirtioTransitional` flag to better share its logic.
Fixes #
```release-note
NONE
```
=> Follow up on PR#9746 comments

pkg/network/infraconfigurators/bridge.go, pkg/network/infraconfigurators/bridge_test.go, pkg/network/infraconfigurators/masquerade.go, pkg/network/infraconfigurators/masquerade_test.go, pkg/network/link/BUILD.bazel, pkg/network/link/discovery.go, pkg/network/link/discovery_test.go, pkg/network/link/names.go, pkg/network/link/names_test.go, pkg/network/namescheme/BUILD.bazel, pkg/network/namescheme/networknamescheme.go, pkg/network/namescheme/networknamescheme_test.go, pkg/network/setup/BUILD.bazel, pkg/network/setup/netconf.go, pkg/network/setup/network.go, pkg/network/setup/network_test.go, pkg/network/setup/podnic.go, pkg/network/setup/podnic_test.go, pkg/network/sriov/sriov.go, pkg/network/sriov/sriov_test.go, pkg/virt-controller/services/multus_annotations.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, pkg/virt-handler/BUILD.bazel, pkg/virt-handler/non-root.go, pkg/virt-handler/non-root_test.go, tests/network/vmi_multus.go
**Summary:**
This PR implements the next phase of hotplug NICs feature, changing the VM pod network interfaces name scheme.
https://github.com/kubevirt/community/blob/main/design-proposals/nic-hotplug/nic-hotplug.md#virtctl-1
This PR changes are necessary to enable unplug interface functionality in KubeVirt.
**Why we need it:**
As of today, virt-launcher pod interface names have an ordinal factor (net1, net2, …, netX), which is derived from the interfaces ordering in the VMI spec.
Mapping between the VMI spec interfaces and virt-launcher pod interfaces  (in `pod k8s.v1.cni.cncf.io/networks` annotation) depends on the fact that pod interface names derive from the order of the VMI spec interfaces.
The fact that pod interface names have ordinal factor is not sustainable for introducing the …
=> Non-ordinal pod network interfaces name scheme

docs/updates.md
The following PR recently merged moving the storage version of all core objects to `v1`:
https://github.com/kubevirt/kubevirt/pull/9628
To accommodate the eventual removal of the original `v1alpha3` version this change adds a note to the updates document recommending the use of the kube-storage-version-migrator tool to automate the upgrade of all stored core objects to `v1` ahead of the removal of `v1alpha3`.
An older note suggesting new CRD versions are not allowed is also removed as this is no longer the case.
Fixes #
```release-note …
```
=> docs: Add upgrade note regarding v1 storage version migration

tests/storage/datavolume.go
The regular VMI launch code will grab the resourceVersion, wait for the DV, then try to watch if any events happened since we created the VMI.
The import of a fedora DV is sufficiently slow that we often see that [the resourceVersion of the original VMI is too old to run the Watch comment](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.26-sig-storage/1658663845566091264).
Avoid this problem entirely by waiting for the DV to succeed before trying to launch the VMI.
We could probably close #9175 which is another attempt at the same flaky test.
```release-note
NONE
```
=> Avoid "resourceVersion too old" warnings in fstrim tests

hack/builder/publish.sh
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-kubevirt-builder/1660974893405048832
```
723dd28d880e090e13b29aadf1792d4153dbad74a0a0dbd0b22979218e18137e
+ podman manifest push quay.io/kubevirt/builder:2305231145-64a7cd17b
Error: accepts 2 arg(s), received 1
```
publish-kubevirt-builder uses podman to build and publish the builder image. This change works around a known podman manifest push bug [1] by providing the destination until a now merged fix is released [2].
[1] https://github.com/containers/podman/issues/18360
[2] https://github.com/containers/podman/commit/bab4217cd16be609ac35ccf3061d1e34f787856f …
=> builder: Workaround podman bug during manifest push

pkg/virt-handler/isolation/generated_mock_isolation.go, pkg/virt-handler/isolation/isolation.go, pkg/virt-handler/vm.go, tests/utils.go, tests/vmi_configuration_test.go
This is a manual backport of https://github.com/kubevirt/kubevirt/pull/9613
"""
Certain use-cases rely on injection of PIT interrupts to the guest in a timely fashion. Today, the kvm-pit kernel thread which is responsible for emulating PIT interrupts runs on housekeeping cores, sharing time with other kubernetes threads (such as kubelet). This has been found to be a problem for a particular workload requiring timely PIT interrupts (see trace below). The fix is to affine kvm-pit kernel thread to the same cpu as vcpu-0, when dedicated cpu placement is enabled in the guest configuration.
<idle>-0     [000] d.h. 102470.847586: hrtimer_expire_entry: hrtimer=00000000e3dea339 function=pit_timer_fn [kvm] now=102463903132805
<idle>-0     [000] d.h. …
=> [release-0.58] affine kvm-pit kernel thread to vcpu-0 cpumask

tests/testsuite/namespace.go
Events are never deleted; they will be only at the end of the entire suite execution, during namespace deletion.
Events cardinality can be very high, delaying the namespace deletion. Since events scope ends at the end of each test we can remove them during namespace cleanup.
Fixes #
```release-note
NONE
```
=> e2e: Remove events in the namespace after each test

docs/metrics.md, hack/prom-rule-ci/prom-rules-tests.yaml, hack/prom-rule-ci/verify-rules.sh, pkg/virt-operator/resource/generate/components/prometheus.go, tests/monitoring/monitoring.go, tests/monitoring/prometheus_utils.go
This adds an alert which triggers when KubeVirt APIs marked as deprecated
are used. It makes use of the Kubernetes apiserver_requested_deprecated_apis
and apiserver_request_total metrics.
The PromQL query is based on the Kubernetes API deprecation docs [1].
[1] https://kubernetes.io/docs/reference/using-api/deprecation-policy/#rest-resources-aka-api-objects
```release-note
An alert which triggers when KubeVirt APIs marked as deprecated are used was added.
```
=> monitoring: Add KubeVirtDeprecatedAPIsRequested alert

pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/application_test.go, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/migration_test.go
Remove the following unused fields from struct `MigrationController`:
- `onOpenshift`
- `namespaceStore`
Fixes #
A similar change was made in PR #9679.
```release-note
NONE
```
=> virt-controller, migration: Remove unused fields

hack/builder/Dockerfile
Resolves the following error when using builder >= 2304121609-faf545b82 that now provides git-2.39.1-1.el9.x86_64 (previously git-2.31.1-2.el9.2.x86_64 with 2212180911-8818abcfa):
```
$ make generate
[..]
+ /root/go/src/kubevirt.io/kubevirt/hack/build-go.sh generate
fatal: detected dubious ownership in repository at '/root/go/src/kubevirt.io/kubevirt'
To add an exception for this directory, call:
git config --global --add safe.directory /root/go/src/kubevirt.io/kubevirt
[..]
+ go build
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
make: *** [Makefile:48: generate] Error 1
```
This could be handled in the individual build and generate scripts but would result in the same directory being appended to the …
=> builder: Create KubeVirt source directory and mark it as safe for git

docs/metrics.md, pkg/monitoring/domainstats/prometheus/prometheus.go, pkg/monitoring/domainstats/prometheus/prometheus_test.go, pkg/virt-launcher/virtwrap/stats/types.go, pkg/virt-launcher/virtwrap/statsconv/converter.go, pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go, tools/doc-generator/fakeDomainCollector.go
**What this PR does**: 
This PR adds a vmi metric -`kubevirt_vmi_memory_cached_bytes`, which relies on [VIR_DOMAIN_MEMORY_STAT_DISK_CACHES](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainMemoryStatTags) stat, by using https://github.com/libvirt/libvirt-go/blob/master/domain.go#L383.
**why we need it**:
Some applications use cached memory and never release it. Users need to take this memory into account when planning the memory requirements. 
[CNV-15415](https://issues.redhat.com/browse/CNV-15415) (same metric that was added in https://bugzilla.redhat.com/show_bug.cgi?id=1024010 is needed in KV).
```release-note
Add `kubevirt_vmi_memory_cached_bytes` metric
```
=> Add vmi cached memory  metric

manifests/generated/operator-csv.yaml.in, manifests/generated/rbac-operator.authorization.k8s.yaml.in, pkg/controller/virtinformers.go, pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/application_test.go, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/migration_test.go, pkg/virt-operator/resource/generate/rbac/controller.go, staging/src/kubevirt.io/api/core/v1/types.go, tests/migration_test.go, tests/testsuite/namespace.go
- Add condition that indicates that migration was rejected by ResourceQuota
- Add resourceQuota informer within the migration controller to get fast response 
whenever resourceQuota blocked the migration and than was deleted/modified
the migration controller should respond quickly.
In a multi-tenant environment, a cluster administrator creates a namespace for each tenant and controls the amount of resources that they can use by creating a ResourceQuota object within the namespace.
During the migration process, there is a hidden cost involved in creating a new virt-launcher pod before terminating the old one. This differs from how standard pods are moved and can result in unexpected resource utilization from the user's perspective. This poses a …
=> [Migration-Controller]Indicate resource quota rejection

pkg/virt-controller/watch/drain/evacuation/evacuation.go, pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/9338, since the automatic one failed: https://github.com/kubevirt/kubevirt/pull/9788.
A test has been refactored to avoid the dep of `kubevirt.io/kubevirt/pkg/pointer`.
Fixes #
```release-note
virt-controller: fix out-of-bound slice index bug in evacuation controller.
```
=> [release-0.58] [virt-controller] fix out-of-bound slice index in evacuation controller

pkg/virtctl/imageupload/BUILD.bazel, pkg/virtctl/imageupload/imageupload.go, pkg/virtctl/imageupload/imageupload_test.go
This change introduces support for labelling images being uploaded to newly created PVCs or DVs with a default instance type or preference.
Users can then use the existing inferFromVolume feature [1] to automatically select an instance type and/or preference when creating a VirtualMachine from the given image.
[1] https://kubevirt.io/user-guide/virtual_machines/instancetypes/#inferfromvolume
See below for an example of how this currently works:
```
$ env | grep KUBEVIRT
KUBEVIRT_PROVIDER=k8s-1.24
KUBEVIRT_MEMORY=32768
KUBEVIRT_DEPLOY_CDI_LATEST=true
KUBEVIRT_STORAGE=rook-ceph-default 
$ ./cluster-up/kubectl.sh kustomize https://github.com/kubevirt/common-instancetypes.git | ./cluster-up/kubectl.sh apply -f -
[..]
$ …
```
=> virtctl: Add default instance type support on image-upload

pkg/util/migrations/migrations.go, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go, pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go, staging/src/kubevirt.io/api/core/v1/types.go, tests/framework/matcher/BUILD.bazel, tests/framework/matcher/getter.go, tests/migration_test.go, tests/vmi_lifecycle_test.go
Add a `LiveMigrateIfPossible` eviction strategy to the KubeVirt CR and VMIs. This strategy makes it easier to express an admin intent on the KubeVirt CR, that in general live-migrations are preferred, but if users do not explicitly request on VMs that they require a live-migration, non-migratable VMs would still just be stopped during evictions.
This solves the issue, that right now we would create for non-migratable VMIs a PodDisruptionBudget if the cluster-wide  eviction strategy is `LiveMigrate`, leading to to the following two situations:
1. Evictions may be blocked by such VMs indefinitely, where the user did not itself explicitly request migrations.
1. We emit warning events, despite no explicit opt-in from the user that live migrations are a …
=> Add LiveMigrateIfPossible eviction strategy

pkg/virt-launcher/virtwrap/access-credentials/BUILD.bazel, pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go, pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go, pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go, pkg/virt-launcher/virtwrap/cli/libvirt.go
This PR simplifies how SSH keys are set in the guest. It uses functions provided by libvirt, instead of writing to the `authorized_keys` file directly.
```release-note
None
```
=> virt-launcher: Use libvirt function to set SSH keys in the guest

manifests/generated/operator-csv.yaml.in, manifests/generated/rbac-operator.authorization.k8s.yaml.in, pkg/controller/virtinformers.go, pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/application_test.go, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/migration_test.go, pkg/virt-operator/resource/generate/rbac/controller.go, staging/src/kubevirt.io/api/core/v1/types.go, tests/migration_test.go, tests/testsuite/namespace.go
Backport PR of: https://github.com/kubevirt/kubevirt/pull/9738
Fixes #
```release-note
Add condition to migrations that indicates that migration was rejected by ResourceQuot
```
=> [release-0.59]Indicate resource quota rejection

hack/multi-arch.sh
Make bazel build for correct Architecture, when there is only one parameter in BUILD_ARCH
As we set `BUILD_ARCH=crossbuild-aarch64` in the build process, and the parameter does not pass to `bazel build` which lead to cross build not works at the moment.
https://github.com/kubevirt/project-infra/blob/39e4c9854a682d00f762868f58ec0b9a4bf6e013/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml#L322-L323
This is a fix to https://github.com/kubevirt/kubevirt/issues/3558#issuecomment-1533261386
```release-note
NONE
```
=> multi-arch: set ARCHITECTURE equal to BUILD_ARCH

BUILD.bazel, cmd/virtctl/BUILD.bazel, hack/bazel-build.sh, hack/build-go.sh
When we build on linux on amd64 we are already
building virtctl also for darwin and windows
OSs but still only for amd64.
But client architecture could differ the cluster ones.
kubectl for instance is shipped for linux, darwin
and windows in both amd64 and arm64 architectures. Check as a reference:
- https://dl.k8s.io/release/v1.27.2/bin/linux/amd64/kubectl
- https://dl.k8s.io/release/v1.27.0/bin/linux/arm64/kubectl
- https://dl.k8s.io/release/v1.27.2/bin/darwin/amd64/kubectl
- https://dl.k8s.io/release/v1.27.2/bin/darwin/arm64/kubectl
- https://dl.k8s.io/release/v1.27.2/bin/windows/amd64/kubectl.exe
- https://dl.k8s.io/release/v1.27.2/bin/windows/arm64/kubectl.exe
Let's start taking the same approach for virtctl.
Address also the `bazel` based …
=> build virtctl also for arm64 for linux, darwin and windows

cmd/virt-handler/virt-handler.go, pkg/cloud-init/cloud-init.go, pkg/host-disk/host-disk.go, pkg/ignition/ignition.go, pkg/monitoring/domainstats/prometheus/prometheus.go, pkg/monitoring/migrationstats/collector.go, pkg/monitoring/vmstats/collector.go, pkg/network/dhcp/serverv6/serverv6.go, pkg/storage/export/export/export.go, pkg/virt-api/rest/interfacehotplug.go, pkg/virt-api/rest/subresource.go, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vmi.go, pkg/virt-handler/vm.go, pkg/virt-launcher/virtwrap/live-migration-source.go, pkg/virt-launcher/virtwrap/manager.go, staging/src/kubevirt.io/client-go/log/BUILD.bazel, staging/src/kubevirt.io/client-go/log/log.go, staging/src/kubevirt.io/client-go/log/log_test.go, tools/perfscale-load-generator/load-generator.go, tools/perfscale-load-generator/object/namespace.go, tools/perfscale-load-generator/object/unstructured.go, tools/perfscale-load-generator/watcher/watcher.go
These are redundant function calls that set the verbosity level of the log message that are warning or error. Verbosity level are only interesting for Info messages.
Related to #8164
None
```release-note
NONE
```
=> Remove verbose fn calls to Warn & Error

pkg/virt-launcher/virtwrap/converter/converter.go
`tpm-crb` is now the preferred vTPM model:
https://bugzilla.redhat.com/show_bug.cgi?id=1519013#c20
https://bugzilla.redhat.com/show_bug.cgi?id=1867917#c8
Fixes #
This change should not cause issues with existing VM(I)s, since KubeVirt has yet to release with persistent vTPM support.
```release-note
NONE
```
=> vTPM: switch model from tpm-tis to tpm-crb when persistence is enabled

hack/prom-rule-ci/prom-rules-tests.yaml, pkg/virt-operator/resource/generate/components/prometheus.go
This is a manual cherry-pick of [Remove mixin query not available on all clusters](https://github.com/kubevirt/kubevirt/pull/8944/commits/5eb7a1e5432bf4393d78f54bf244c39b8e04ce90) commit in #8944
```release-note
Remove mixin query not available on all clusters
```
=> [release-0.59] Remove mixin query not available on all clusters

api/openapi-spec/swagger.json, manifests/generated/kv-resource.yaml, pkg/virt-controller/watch/BUILD.bazel, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/migration_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/security_features_test.go
When VMIs use RWX disks based on some storage classes, like cephfs, both the source and target pods of a migration need to have access to the files.
There are 2 ways to achieve that:
- either remove the SELinux categories on the files for the duration of  the migration (see https://github.com/kubevirt/kubevirt/pull/9190)
- or match the source categories of the source pod on the target pod
Both solutions have negative security implications, but they're the only way to deal with shared resources.
I believe this is the best approach, as it doesn't mess with the disk and doesn't expose files to the entire node/cluster for the duration of the migration.
The only downside here is that the target node could (have) create(d) a pod with the same categories. …
=> migration: match SELinux level of source pod on target pod

tests/network/expose.go
Currently, the expose e2e test contains several anonymous functions that are not closures [1].
Convert them to regular functions in order to reduce noise from the test body.
[1] https://go.dev/tour/moretypes/25
Fixes #
```release-note
NONE
```
=> network, e2e: Convert anonymous functions to regular ones

pkg/network/dhcp/serverv6/serverv6.go, pkg/network/dhcp/serverv6/serverv6_test.go
Fixes #9843
```release-note
DHCPv6 server handle request without iana option
```
=> DHCPv6 server should handle request without iana option

pkg/virtctl/memorydump/memorydump.go
Changes to the VM export download code caused an npe in memory dump download because the writer was not assigned. This PR properly sets the output writer. However it does not allow the output to be written to stdout like VM export download.
Fixes #
I would have loved to create a functional test for this particular case, but memory-dump doesn't take a `--service-url` flag like `vmexport download` does, so I can't even manually port-forward to test.
```release-note
NONE
```
=> Assign writer to output file when downloading memory dump

pkg/virt-api/rest/BUILD.bazel, pkg/virt-api/rest/dialers.go, pkg/virt-api/rest/dialers_test.go
Fixes #9850 
```release-note
virt-api: portfowrad can handle IPv6 VM
```
=> virt-api: dialer should wrap ipv6 address with square brackets to portfoward ipv6 VM

tests/storage/restore.go, tests/storage/snapshot.go
180 seconds may be too short of a timeout for an external import to complete and a VM to start.
This presented itself in external testing where we don't use a local registry for the images.
Fixes #
```release-note
NONE
```
=> [snapshot-restore tests]: Bump VM start timeout

hack/OWNERS, pkg/monitoring/perfscale/OWNERS, pkg/network/OWNERS, tests/OWNERS, tests/network/OWNERS, tests/performance/OWNERS, tools/OWNERS
Approvers and Reviewers aliases were updated as part of https://github.com/kubevirt/kubevirt/pull/9453.  Update the affected OWNERS files.
```release-note
None
```
=> Update OWNERS to the new alias

Makefile, hack/build-go.sh
With https://github.com/kubevirt/kubevirt/pull/9832 we start shipping arm64 version of virtctl.
This happens only if the building machine is amd64. Let's start doing it in arm64 machine too.
In order to save time during normal development, to generate all versions of virtctl it is necessary to set an environment variable (`KUBEVIRT_RELEASE`).
In other words, when `KUBEVIRT_RELEASE` is true build-go.sh will generate virtclt binary for linux/darwin/windows and amd64/arm64; otherwise the only version(os/arch) of the local machine will be generated.
When KUBEVIRT_RELEASE is true, the outcome will be:
```
virtctl -> virtctl-0.59.1-linux-amd64
virtctl-0.59.1-darwin-amd64
virtctl-0.59.1-linux-amd64
virtctl-0.59.1-windows-amd64.exe …
```
=> [go-build] Build virtctl for all architectures

tests/storage/export.go
This is not from a linter. I saw it happen on a test run that create likely failed and the next use of dv produced bogus results.
```release-note
NONE
```
=> Add missing error check to test

hack/perfscale-tests.sh
This fixes the artifacts exported to s3 bucket. Currently the artifacts directory is missing the audit results
See this for reference: https://gcsweb.ci.kubevirt.io/gcs/kubevirt-prow/logs/periodic-kubevirt-performance-cluster-100-density-test/1638400214094057472/
Fixes #
This removes overriding the ARTIFACTS variable set by prow 
```release-note
None
```
=> sig-scale: use right directory for ARTIFACTS in density tests

pkg/virt-handler/isolation/generated_mock_isolation.go, pkg/virt-handler/isolation/isolation.go, pkg/virt-handler/vm.go, tests/utils.go, tests/vmi_configuration_test.go
This is a manual backport of https://github.com/kubevirt/kubevirt/pull/9613
"""
Certain use-cases rely on injection of PIT interrupts to the guest in a timely fashion. Today, the kvm-pit kernel thread which is responsible for emulating PIT interrupts runs on housekeeping cores, sharing time with other kubernetes threads (such as kubelet). This has been found to be a problem for a particular workload requiring timely PIT interrupts (see trace below). The fix is to affine kvm-pit kernel thread to the same cpu as vcpu-0, when dedicated cpu placement is enabled in the guest configuration.
<idle>-0     [000] d.h. 102470.847586: hrtimer_expire_entry: hrtimer=00000000e3dea339 function=pit_timer_fn [kvm] now=102463903132805
<idle>-0     [000] d.h. …
=> [release-0.59]  affine kvm-pit kernel thread to vcpu-0 cpumask

pkg/virt-api/webhooks/validating-webhook/admitters/instancetype-admitter.go
Int is being casted to string in a wrong way.
In some environments, it leads to a compilation error: `conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)`
```release-note
NONE
```
=> Fix bad cast of int to string

pkg/instancetype/compatibility_test.go, pkg/instancetype/instancetype.go, pkg/instancetype/instancetype_test.go
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-code-lint
Looks like a few things slipped through while I was out, fixing them up here.
* Duplicate spec creation code is removed from compatibility_test.go
* A naked return while valid is replaced with a named return
* A shadow declaration of a test variable is also removed
* A magic number is moved into a constant
Fixes #
```release-note
NONE
```
=> instancetype: Fix linting

tests/testsuite/manifest.go
In external testing, we see that `AlreadyExists` occurs from time to time
when a new test suite attempts to recreate the DaemonSet.
This happens because we now use foreground deletion which waits for the underlying pods to be gone (https://github.com/kubevirt/kubevirt/pull/9496),
which may take a while.
Fixes #
```release-note
NONE
```
=> [e2e tests]: Wait for testing manifests to be gone on suite cleanup

hack/prom-rule-ci/prom-rules-tests.yaml, pkg/virt-operator/resource/generate/components/prometheus.go, tests/monitoring/monitoring.go
Renaming KubeVirtDeprecatedAPIsRequested to
KubeVirtDeprecatedAPIRequested avoids confusion about use of singular or plural.
See https://github.com/kubevirt/monitoring/pull/172#discussion_r1219942486 and https://github.com/kubevirt/monitoring/pull/178.
```release-note
None
```
=> cleanup: Rename deprecated API alert to singular

hack/prom-rule-ci/prom-rules-tests.yaml, pkg/virt-operator/resource/generate/components/prometheus.go
Fixes #
```release-note
Fix incorrect KubevirtVmHighMemoryUsage description
```
=> Fix incorrect KubevirtVmHighMemoryUsage description

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, tests/io_utils.go, tests/storage/storage.go
This pull request modifies the vmi admission webhook to allow using DataVolume sources for Lun Disks, instead of allowing only PVCs.
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2190171
```release-note
Bugfix: Allow lun disks to be mapped to DataVolume sources
```
=> Allow lun disks to be mapped to DataVolume sources

pkg/virt-api/rest/BUILD.bazel, pkg/virt-api/rest/subresource.go
In order to allow a swift and safe restart, set the deletion grace period to 1 on the pod delete when a force restart is requested.
One is the shortest safe restart period where we don't risk a split-brain scenario for VMs, since Zero effectively deletes the pod right away.
This leads to the following outcome:
* If a guest OS is stuck, people get a swift restart.
* Users don't risk data corruption.
* Reserving a force pod delete for situations where the cluster is unhealthy.
Fixes #9830
```release-note
Fix the possibility of data corruption …
```
=> Set the deletion grace period to 1 on forced VM restarts

.bazelrc, Makefile, go.mod, go.sum, hack/fuzz.sh, pkg/util/webhooks/webhooks.go, pkg/virt-api/webhooks/fuzz/BUILD.bazel, pkg/virt-api/webhooks/fuzz/fuzz_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, vendor/github.com/google/gofuzz/.travis.yml, vendor/github.com/google/gofuzz/BUILD.bazel, vendor/github.com/google/gofuzz/CONTRIBUTING.md, vendor/github.com/google/gofuzz/README.md, vendor/github.com/google/gofuzz/bytesource/BUILD.bazel, vendor/github.com/google/gofuzz/bytesource/bytesource.go, vendor/github.com/google/gofuzz/fuzz.go, vendor/modules.txt
Fuzzing, done continuously, can reveal bugs in places where users are providing the input. The CNCF project [recommends](https://github.com/cncf/cncf-fuzzing) for CNCF project doing fuzzing and eventually integrating into [oss-fuzz](https://github.com/google/oss-fuzz).
This is a starting point, which makes use of the new built-in Fuzz support, starting with golang 1.18.
Right now this covers:
* Syntactic validation of VMI and VM create admitters
* 90% coverage on VMI semantic validation
* 25% coverage of VM semantic validation
At the moment, 500 iterations are executed on semantic and syntactic validation of VM and VMI (so 4 *500 overall).
An optional presubmit prowjob will be introduced in https://github.com/kubevirt/project-infra/pull/2814.
The …
=> Add basic fuzz testing and fix an initial set of issues discovered by fuzzing

pkg/network/setup/netconf_test.go, pkg/network/setup/network.go
Kubevirt expects SR-IOV interfaces to be set with userspace driver (vfio-pci) in order to attach them to VMs.
The interfaces are passthroughed to the VM using Libvirt API. 
Thus SR-IOV networks should not be part of the network setup.
Fixes #
This is a follow-up PR to resolve https://github.com/kubevirt/kubevirt/pull/9268#discussion_r1199753143
```release-note
NONE
```
=> virt-handler, network setup: Do not create podNIC for SR-IOV networks

pkg/virt-config/feature-gates.go
CPUNodeDiscoveryGate is not used, depercate the feature.
I am not sure if we should put it in `deprecatedFeatureGates` or just remove it.
-->
```release-note
NONE
```
=> virt-config: Deprecate CPUNodeDiscoveryGate

pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-launcher/virtwrap/live-migration-source.go, tests/hotplug/cpu.go
This PR is a follow-up to #9757; It addresses some immediate issues.
- It adds validation to prevent live updating of the VMI sockets during an inflight live migration.
Before this PR, it was theoretically possible to change the VMI sockets count before the migration hand-off; That way the target pod could be created with inadequate CPU resources.
- Fixes some validation webhook tests.
- Fixes migration of VMs with dedicated CPUs and defined MaxSockets
- The original PR has an issue that prevents VM with dedicated CPUs from migrating because MaxSockets was not taken into account when calculating target CPU topology.
A functional test has been adjusted to verify that it's not possible to migrate hot-pluggable VMs with dedicated CPUs and that it's not …
=> cpu hot plug: improve cpu hot plug validation and tests

tests/operator/operator.go
The following test appears to be very flaky and impacting across the 1.25 and 1.26 lanes[1][2]
`[Serial][sig-operator]Operator [rfe_id:2897][crit:medium][vendor:cnv-qe@redhat.com][level:component]Dynamic feature detection [test_id:3153]Ensure infra can handle dynamically detecting DataVolume Support`
[1] https://search.ci.kubevirt.io/?search=test_id%3A3153&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
[2] https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2023-06-13-024h.html#row0
Fixes # …
=> Quarantine flaky sig-operator test that dynamically detects DV support

pkg/instancetype/instancetype.go, pkg/instancetype/instancetype_test.go, tests/instancetype_test.go
As mentioned in #9912 the overcommit value is not calculated correctly.
This fix makes the value actually calculated.
Fixes #9912
```release-note
NONE
```
=> instancetype: Fix overcommit percent calculation

pkg/network/cache/dhcpconfig.go, pkg/network/cache/domaininterface.go, pkg/network/cache/domaininterface_test.go, pkg/network/driver/common.go, pkg/network/driver/generated_mock_common.go, pkg/network/link/discovery.go, pkg/network/setup/BUILD.bazel, pkg/network/setup/configstate.go, pkg/network/setup/configstate_test.go, pkg/network/setup/configstatecache.go, pkg/network/setup/configstatecache_test.go, pkg/network/setup/netconf.go, pkg/network/setup/netconf_test.go, pkg/network/setup/netstat.go, pkg/network/setup/network.go, pkg/network/setup/network_suite_test.go, pkg/network/setup/network_test.go, pkg/network/setup/podnic.go, pkg/network/setup/unpluggedpodnic.go, pkg/network/setup/unpluggedpodnic_test.go, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go, pkg/virt-launcher/virtwrap/manager.go
The purpose of the PR is on hotunplug - to remove the interfaces created by phase1 (bridge, tap, dummy nic) and the caches (file and volatile).
Hotunplug is detected when the spec interfaces/networks doesn't contain a network that is stored in the configState cache.
In such case unplug phase1 will try to clean the bridge, tap, dummy nic and the caches in case they exist.
The PR doesn't include -
In case a network has caches but the preparation for some reason didn't start, hotunplug won't remove the cached since the indicator to the cleanup is that the configState is `PodIfaceNetworkPreparationStarted` or `PodIfaceNetworkPreparationFinished`.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
=> hotunplug - reverse phase1

pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
/cc @opokornyy 
PersistentVolumeClaimSpec is an optional attribute of DataVolumeSpec but wasn't previously checked by setPreferenceStorageClassName. This change fixes this and reworks unit tests that were also not correctly asserting the behaviour of setPreferenceStorageClassName as the VirtualMachine provided contained no DataVolumeTemplates.
Fixes #9868
```release-note
NONE
```
=> webhooks: Fix setPreferenceStorageClassName during mutation

pkg/controller/virtinformers.go
/cc @vladikr 
/cc @0xFelix 
As shown in #9913 the `InstancetypeV1alpha2` clients were previously being used causing the following error to be logged by virt-controller:
```
E0614 15:16:18.269082       1 reflector.go:507]
pkg/controller/virtinformers.go:346: expected type
*v1beta1.VirtualMachineInstancetype, but watch event object had type
*v1alpha2.VirtualMachineInstancetype
```
Fixes #9913 
```release-note
NONE
```
=> virtinformers: Use InstancetypeV1beta1 client

hack/builder/publish.sh, hack/common.sh, hack/multi-arch.sh, hack/push-container-manifest.sh
`bazel-push-images.sh` puts the digests files in paths based on the formatted arch names.
The same does not happen in `push-container-manifest.sh` which tries to find digests file using the plain arch names.
This results in a failure if you are building `aarch64` and `x86_64` together, as it happens for example in `automation/release.sh` Move the `format_archname` function to common.sh file, so that it can be also used by `push-container-manifest.sh`
Fixes #https://github.com/kubevirt/kubevirt/issues/9908
```release-note
NONE
```
/cc @rmohr …
=> [multi-arch] Use formatted archname in push-container-manifest

pkg/virt-controller/watch/vmi.go, tests/storage/datavolume.go, tests/storage/storage.go, tests/utils.go, tests/virtiofs/datavolume.go
When Kubevirt will run with newer version of CDI with integration of data volumes and CDI populators DV with WFFC SCI storage class will have new phase pendingPopulation, when hotpluging a dv with this phase we can continue to create the attachment pod and it will trigger the population.
This PR fixes the check if a dv is ready to be attached.
Also adjusting some tests to take into account either WFFC phase or PendingPopulation phase. 
```release-note
Fix for hotplug with WFFC SCI storage class which uses CDI populators
```
=> Fix for hotplug with WFFC and CDI populators + test fixes

tests/container_disk_test.go, tests/infra_test.go, tests/libwait/BUILD.bazel, tests/libwait/wait.go, tests/utils.go, tests/vmi_cloudinit_test.go
With cluster level EvictionStrategy "LiveMigrate", during the start
of a non live migratable vmi, an event will be emitted.
Since most of the time we don't tolerate any warning during vmi startup,
this can cause a failure.
Let's ignore this warning when the cluster level eviction strategy is
`LiveMigrate`.
Also, a refactoring to `libwait` is proposed:
`libwait` contains many functions with duplicate code.
To reduce duplication and increase readability, the `Waiting` struct was introduced,
which allows to specify defaults and to easily override them.
In addition, a description of utility functions has been provided.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …
=> [e2e] Refactoring libwait & ignore EvictionStrategy warning

pkg/virt-handler/vm.go, staging/src/kubevirt.io/api/core/v1/types.go
Blocking live migration with isolated emulator thread was introduced due to a misunderstanding: there is nothing that prevents a VM, with isolated emulator thread, to be live migrated (since the VM configuration, including emulator thread isolation, happens at VM initialization time).
This was introduced in PR 
https://github.com/kubevirt/kubevirt/pull/8233
Users would like to migrate VMs with isolated emulator threads.
Fixes #
```release-note
NONE
```
=> enable live migration with dedicated cpus and isolated emulator thread

pkg/util/net/grpc/grpc.go
Some non grpc-go servers fail with "protocol error" when contacted by KubeVirt's gRPC client. The suspected cause is that grpc-go sends invalid Authority headers when using unix domain sockets.
This issue prevents implementation of hook sidecars in other languages, such as Rust with its Tonic library.
A similar issue was encountered in Kubernetes [1], where it was solved by explicitly setting the Authority header. This patch uses the same approach.
[1] https://github.com/kubernetes/kubernetes/pull/112597
Fixes #
The alternative approach, using `unix:` or …
=> grpc: Fix authority header sent to unix sockets

cmd/container-disk-v2alpha/main.c
Fix a bug where logging an error in the container disk will turn out in a corrupted mix of characters.
Fixes #
```release-note
Bug fix - correct logging in container disk
```
=> Use vfprintf instead of fprintf to correctly log

tests/network/kubectl.go, tests/network/vmi_networking.go
So the test can run on d/s.
The tests for on teir1 tests with - `EvictionStrategy is set but vmi is not migratable; cannot migrate VMI which does not use masquerade to connect to the pod network or bridge with kubevirt.io/allow-pod-bridge-network-live-migration VM annotation`.
To avboid this the primary interface of the tested VMs was changed to masquerade.
Fixes #
```release-note
NONE
```
=> e2e test: changing the default interface to masquesrade

pkg/virt-handler/vm.go, staging/src/kubevirt.io/api/core/v1/types.go
Blocking live migration with isolated emulator thread was introduced due to a misunderstanding: there is nothing that prevents a VM, with isolated emulator thread, to be live migrated (since the VM configuration, including emulator thread isolation, happens at VM initialization time).
Fixes #
```release-note
NONE
```
=> [release-0.58] enable live migration with dedicated cpus and isolated emulator thread

CONTRIBUTING.md
Add section about automated testing and draft pull requests to the CONTRIBUTING.md doc.
Fixes #
**This PR is ready for review, it's marked as draft, since the change is entirely markdown and CI signal is not needed.!**
/cc @fabiand @brianmcarey @xpivarc 
```release-note
Add some context for initial contributors about automated testing and draft pull requests.
```
=> CONTRIBUTING.md: Add section about automatic testing and draft PRs

tests/credentials_test.go, tests/hyperv_test.go, tests/libwait/wait.go, tests/migration_test.go, tests/network/probes.go, tests/network/sriov.go, tests/network/vmi_passt.go, tests/network/vmi_slirp_interface.go, tests/pausing_test.go, tests/portforward_test.go, tests/storage/datavolume.go, tests/storage/events.go, tests/storage/hotplug.go, tests/storage/imageupload.go, tests/storage/reservation.go, tests/storage/restore.go, tests/storage/snapshot.go, tests/storage/storage.go, tests/subresource_api_test.go, tests/sysprep_test.go, tests/utils.go, tests/vmi_configuration_test.go, tests/vmi_lifecycle_test.go, tests/vmi_multiqueue_test.go, tests/vmi_tpm_test.go, tests/windows_test.go
This is a followup PR of https://github.com/kubevirt/kubevirt/pull/9901
`libwait` package exposed several utility functions that can be generalized using variadic.
Fixes #
Addressing https://github.com/kubevirt/kubevirt/pull/9901#discussion_r1230732096
```release-note
NONE
```
/cc @dhiller @acardace @EdDev
=> [e2e] cleanup libwait utility functions

BUILD.bazel, hack/bazel-push-images.sh, hack/parse-shasums.sh
Avoid any confusion and mismatches and always use `libguestfs-tools` name.
Fixes #9908
```release-note
NONE
```
=> Add -tools suffix to libguestfs push rule

pkg/host-disk/host-disk.go, pkg/host-disk/host-disk_test.go
This change limits the Capacity of any host-disks created when using a
filesystem PVC. This ensures the overall Capacity of the underlying PV
is not used as this can cause issues with providers as set out in
bug https://github.com/kubevirt/kubevirt/issues/9809.
Fixes #9809
```release-note
NONE
```
=> host-disk: Limit disk size to that requested by PVC

pkg/network/setup/network.go, pkg/network/setup/podnic.go, pkg/network/setup/podnic_test.go
Following PRs https://github.com/kubevirt/kubevirt/pull/9268 and https://github.com/kubevirt/kubevirt/pull/9890, we now look up an interface by its network name
in `getPhase1NICs()` and in `getPhase2NICs()`.
The same lookup operation also occurs at `newPodNIC()` which is called from both
`getPhase1NICs()` and `getPhase2NICs()`.
Pass the interface found in `getPhase1NICs()` and `getPhase2NICs()`
down the stack to `newPodNIC()`, so it could be used instead of performing the
same operation again.
Fixes #
~~Depends on PR #9890, please review only the last …
=> Network, setup: Remove redundant lookup of interface by network

hack/cluster-deploy.sh
Prevent DV-related CI failures in the next kubevirt-bot kubevirtci bump PR (with bump-cdi), due to:
https://github.com/kubevirt/containerized-data-importer/pull/2754
Fixes #
```release-note
NONE
```
=> Disable DataVolume GC by default in cluster-deploy

tests/libwait/BUILD.bazel, tests/libwait/wait.go, tests/testsuite/BUILD.bazel, tests/testsuite/fixture.go, tests/testsuite/runconfiguration.go, tests/utils.go
EvictionStrategy can be set at cluster level.
When it is `LiveMigrate` and a vmi which is not live migratable is started, a warning event is emitted. This warning can cause the failure of the test because the utility function that wait for the vmi to start, generally, does not tolerate any warning.
Set the specific warning in the warning ignore list when we detect that the cluster level eviction strategy is `LiveMigrate`.
Fixes #
```release-note
NONE
```
/cc @xpivarc @acardace
=> [e2e] Ignore LiveMigrate warning

api/openapi-spec/swagger.json, manifests/generated/operator-csv.yaml.in, manifests/generated/rbac-operator.authorization.k8s.yaml.in, pkg/virt-api/api.go, pkg/virt-api/rest/BUILD.bazel, pkg/virt-api/rest/interfacehotplug.go, pkg/virt-api/rest/interfacehotplug_test.go, pkg/virt-controller/watch/vm.go, pkg/virt-operator/resource/generate/rbac/cluster.go, pkg/virt-operator/resource/generate/rbac/controller.go, pkg/virtctl/network/dynamicifaces.go, pkg/virtctl/network/dynamicifaces_test.go, staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go, staging/src/kubevirt.io/client-go/kubecli/kubevirt.go, staging/src/kubevirt.io/client-go/kubecli/vmi.go, tests/network/hotplug.go
This PR removes the rest-api and virctlcommands  for hotplugging/unplugging an interfaces to/from a VMI.
Interface hotplugging/unplugging will be supported via VMs only.
It was noticed that allowing users to access the VMI (through the virt-api) is introducing too many corner cases (for example interface hotplugged to a VMI didn't get MAC from kubemacpool) and complexity in the system. Users should have access only to their user facing API, which is the VM object. Allowing the system to apply the desired spec in the VM to the backend VMI.
Fixes #
**Release …
=> Remove hotplug VMI API

hack/gen-client-python/deploy.sh, hack/gen-swagger-doc/deploy.sh, hack/publish-staging.sh
Replace old bot user email with new `kubevirtbot@redhat.com`. Also swap git `user.name` and `user.email` configurations to use correct defaults.
The old email was removed from the kubevirt-bot GitHub account, thus the publish job for nightly build failed:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-main/1669510740576309248#1:build-log.txt%3A1510
Fixes #
/cc @xpivarc @brianmcarey 
```release-note
NONE
```
=> Remove invalid email reference

tests/testsuite/namespace.go
Currently, we are deleting every events in a namespace after each test. The way we are doing this increased the runtime of the e2e lanes by a considerable amount.
Let's use delete collection instead of retrieving the events and delete one by one.
Fixes #
Alternative for https://github.com/kubevirt/kubevirt/pull/9960
```release-note
NONE
```
=> [e2e] Improve events deletion in AfterEach

tests/reporter/kubernetes.go, tests/tests_suite_test.go
The message was in `JustBeforeEach` and if the test failed in one of its `BeforeEach`es it wasn't printed although the artifacts were collected. Moving the message to `JustAfterEach` makes sure that if the artifacts are collected the text is printed as well.
Fixes #
```release-note
NONE
```
=> reporter: move the message with the artifacts dir to `JustAfterEach`

pkg/virt-handler/vm.go
Important to note that the io error is the cause the cause for pausing, and that it comes from the low-levels.
Explain a condition better
Fixes #
```release-note
NONE
```
=> Improve the IOError condition description.

tests/network/hotplug.go
When testing multiple hotplug interfaces a redundant migration was executed after the second hotplug.
By executing the migration before the new interface propagated to the VMI, flakes are seen (pod interface missing on the target).
Therefore, drop one migration and depend on the one performed as part of the `verifyDynamicInterfaceChange` helper.
Fixes #
The problem is seen rarely.
Here is one occurrence of it:  https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9954/pull-kubevirt-e2e-k8s-1.26-sig-network/1672845055431282688
Note …
=> tests, hotplug: Remove redundant migration

pkg/virtctl/vm/BUILD.bazel, pkg/virtctl/vm/add_volume.go, pkg/virtctl/vm/common.go, pkg/virtctl/vm/expand.go, pkg/virtctl/vm/fs_list.go, pkg/virtctl/vm/guestosinfo.go, pkg/virtctl/vm/migrate.go, pkg/virtctl/vm/migrate_cancel.go, pkg/virtctl/vm/remove_volume.go, pkg/virtctl/vm/restart.go, pkg/virtctl/vm/start.go, pkg/virtctl/vm/stop.go, pkg/virtctl/vm/user_list.go, pkg/virtctl/vm/vm.go
This PR separates VirtualMachine related commands from one single file `vm.go` into it's own file. It should break the complexity of a original `vm.go` file.
```None
```
Signed-off-by: Ondrej Pokorny <opokorny@redhat.com>
=> Separate vm commands into single files

tests/storage/reservation.go
In certain case, the targetcli backstores/fileio create command fails with:
Could not expand file to 1073741824 bytes
We can try to avoid this issue by creating a smaller backend image. We simply hardcoded 800M instead of 1G as in these tests the size of the disk doesn't matter. This is used to test the SCSI persistent reservation ioctls.
Fixes #
```release-note
NONE
```
=> tests: leave some space for metadata on the backend PVC

tests/container_disk_test.go, tests/infra_test.go, tests/libwait/BUILD.bazel, tests/libwait/wait.go, tests/testsuite/BUILD.bazel, tests/testsuite/fixture.go, tests/testsuite/runconfiguration.go, tests/utils.go, tests/vmi_cloudinit_test.go
This is a manual backport of https://github.com/kubevirt/kubevirt/pull/9901 and https://github.com/kubevirt/kubevirt/pull/9948
Fixes #
```release-note
NONE
```
=> [release-1.0] [e2e] Refactoring libwait & ignore EvictionStrategy warning

tests/libwait/wait.go
Currently, if the cluster is using `LiveMigrate` as eviction strategy we are overriding any warning list provided by the tests with the global warning list to ignore. This happens because `libwait.WithWarningsIgnoreList` function does not append the new list to the already existing values.
For example, if we use: https://github.com/kubevirt/kubevirt/blob/d89207bd558440af2c273870540093951a82e97c/tests/utils.go#L287-L292
`WaitForVMIPhase` initially set the WarningsIgnoreList to `[]string{"didn't find PVC", "unable to find datavolume"}`, but then in https://github.com/kubevirt/kubevirt/blob/d89207bd558440af2c273870540093951a82e97c/tests/libwait/wait.go#L74
we will override the field with the only `testsuite.TestRunConfiguration.WarningToIgnoreList` …
=> [e2e-fix] Append global warning to ignore instead of override

tests/BUILD.bazel, tests/migration_test.go
VMI eviction strategy is inherited from the cluster value if it is not explicitly set in the vmi spec.
Since, cluster level eviction strategy can also be `LiveMigrate` in some other test configuration, let's ensure the eviction strategy is `None` in those tests where we want to test it.
Fixes #
```release-note
None
```
=> [e2e] Set vm eviction strategy explicitly

tests/BUILD.bazel, tests/events/BUILD.bazel, tests/events/events.go, tests/infra_test.go, tests/migration_test.go, tests/operator/BUILD.bazel, tests/operator/operator.go, tests/storage/BUILD.bazel, tests/storage/events.go, tests/vmipreset_test.go
Until now we have been using events as a global thing. Meaning if we had to check VMI1-caused event we were checking if any VMI caused the particular event. This is not the best solution as it is error-prone. Events from previous tests can cause a match. At the same time, Kubernetes events contain associations with a particular object.
This PR is making use of the above fact, making it easier to test events in the future. It also removes redundant code and makes 2 Serial tests run in parallel.
Fixes #
```release-note
NONE
```
=> Improve testing of events

tests/launchsecurity/sev.go
The following test is very flaky[1][2]:
`AMD Secure Encrypted Virtualization (SEV) device management should reset SEV capacity when the feature gate is disabled`
The timeout was previously increased[3] however that does not seem to have resolved the flakiness.
Quarantining the test as it is causing impact to the sig-compute lanes.
[1] https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2023-06-27-168h.html#row1
[2] https://search.ci.kubevirt.io/?search=SEV+capacity+when+the+feature+gate+is+disabled&maxAge=336h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
[3] https://github.com/kubevirt/kubevirt/pull/9907
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …
=> Quarantine flaky SEV test that tries to reset SEV capacity

hack/dockerized
If cred helpers are required, they will very likely not work from within the build container, since we don't install any cred helpers, and we don't know what information they need to work.
This should help developer flows when cred helpers are configured in docker. Otherwise `make cluster-sync` breaks due to missing cred helpers, even if the cred helper related repos are not even in use.
Fixes #
```release-note
NONE
```
=> Don't mount docker config if cred helpers are required

hack/prom-rule-ci/prom-rules-tests.yaml, pkg/virt-operator/resource/generate/components/prometheus.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/9073
Fixes #
```release-note
Fix incorrect KubevirtVmHighMemoryUsage description
```
=> [release-0.59] Fix incorrect KubevirtVmHighMemoryUsage description

pkg/virt-handler/node-labeller/cpu_plugin.go, pkg/virt-handler/node-labeller/cpu_plugin_test.go, pkg/virt-handler/node-labeller/model.go, pkg/virt-handler/node-labeller/node_labeller.go, pkg/virt-handler/node-labeller/node_labeller_test.go, pkg/virt-handler/node-labeller/testdata/cpu_map/x86_Opteron_G2.xml, pkg/virt-handler/node-labeller/testdata/cpu_map/x86_Skylake-Client-IBRS.xml, pkg/virt-handler/node-labeller/testdata/virsh_domcapabilities.xml, tests/infra_test.go
manual back-port of:
https://github.com/kubevirt/kubevirt/pull/9325
and of:
https://github.com/kubevirt/kubevirt/pull/7765
Fixes #
```release-note
NONE
```
=> [release-0.53]node-labeller: Take CPU features into account when labeling nodes && fixing MinCPUModel's field logic

tests/network/BUILD.bazel, tests/network/vmi_multus.go
The issue with accessing the /tmp folder seems to have been resolved.
This change is reverting commit 102f057c9
Fixes #
When reviewing, it is recommended to enable "Hide whitespace" in the diff file window.
```release-note
NONE
```
=> tests, network: Remove xfail from mac-spoof-check test

tests/security_features_test.go
It's possible that a test node still has our custom SELinux policy installed from a previous version of KubeVirt, but now uses a version that doesn't include it anymore.
In that specific scenario, the corresponding test will fail. This PR makes it succeed if the file is missing, since there's nothing more to do.
Fixes #
```release-note
NONE
```
=> tests: don't assume the custom SELinux policy file is present

pkg/virt-launcher/virtwrap/converter/converter.go
As of now, the expandDisksEnabled is enabled for all volumes including volumes like configMap, cloud-init and secret. Since these volumes don't have capacity, error message "No disk capacity" is logged repeatedly in the virt-launcher logs. Only enable expandDisksEnabled on PVC volumes since only those volumes can be expanded.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=2216093
Fixes #
```
Only enable expandDisksEnabled on PVC volumes
```
=> Only enable expandDisksEnabled on PVC volumes

tests/testsuite/fixture.go, tests/testsuite/runconfiguration.go
`InitRunConfiguration` is executed in `SynchronizedBeforeTestSetup` function, which is executed only in the process#1 (https://onsi.github.io/ginkgo/#parallel-suite-setup-and-cleanup-synchronizedbeforesuite-and-synchronizedaftersuite). This causes that the `TestRunConfiguration` is misconfigured in the other processes, that can result in failures in case of `LiveMigrate` cluster level eviction strategy. Move the `InitRunConfiguration` function in `BeforeTestSuiteSetup` function.
Fixes #
```release-note
NONE
```
/cc @xpivarc
=> [e2e] Share KubeVirtDefaultConfig between all ginkgo nodes

pkg/controller/controller.go, pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/application_test.go, pkg/virt-controller/watch/network.go, pkg/virt-controller/watch/network_test.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, pkg/virt-controller/watch/vmi.go
When marking a network interface for removal, the VM controller is
patching the VMI object to reflect the same on the running VM.
However, for older VMs where its pod interfaces use ordered naming, the
unplug operation is not supported.
Therefore, the VM controller now checks against the pod network
annotation about the naming of the pod interfaces and if detected as
ordered, it will not patch the VMI.
The change assures VMI objects which do not support interface hot-unplug
will not be marked as such in the first place.
Therefore, code which the VMI controller has to cancel the unplug
request and code in the virt-handler and virt-launcher, can be removed
as followup. …
=> virt-controller, vm: Avoid unplugging interfaces on older running VMs

hack/prom-rule-ci/rule-spec-dumper.go, pkg/virt-operator/kubevirt_test.go, pkg/virt-operator/resource/apply/prometheus_test.go, pkg/virt-operator/resource/generate/components/prometheus.go, pkg/virt-operator/resource/generate/components/prometheus_test.go, pkg/virt-operator/resource/generate/install/strategy.go, pkg/virt-operator/util/config.go, tests/operator/operator.go
I don't see any harm in permanent deployment of that alert. The evaluation of `kubevirt_vmi_outdated_count != 0`
will remain false even the metric is stale, so I don't see any risk of false positives here.
In the current situation if we configure a workload update method in the Kubevirt CR it will
cause re-deployment of all the virt-components. That is because adding a method will populate the `additionalProperties` map, which in turn cause changes in kubevirt deployment config digest.
We can change the logic and to inject the alert in the virt-operator sync loop in the reconciler, but 
I think it is a redundant considering the fact the deployment of this alert anyway won't cause any
harm. …
=> [virt-operator]: always deploy the outdated VMI workload alert

automation/repeated_test.sh, hack/functests.sh
According to [A Survey of Flaky Tests], Section [Detection]
* almost all flaky tests were independent of the execution
platform, so environmental issues should be considered with
higher priority
* devs may be unaware of many flakes due to order-dependent
tests
* simple techniques of reversing or shuffling the test order
may be more efficient and effective than more sophisticated
approaches
* “One study found that 88% of flaky tests were found to
consecutively fail up to a maximum of five times before
passing,
though another reported finding new flaky tests even after
10,000 test suite runs.”
Therefore we by default
* use only latest kubevirtci provider,
* run all changed tests five times and
* randomize the test order each time
We fix a couple of …
=> Increase probability of flake check to reveal flakes

pkg/virt-controller/watch/network.go, pkg/virt-controller/watch/network_test.go, pkg/virt-controller/watch/vm.go, tests/network/hotplug.go
When KubeMacPool exists and opt-in to manage VMs MAC addresses, it patch **VirtualMachine** objects and add MAC address to their interfaces in the template spec. 
On VM creation,  the VM is patched by KubeMacPool and the interfaces in the spec will be set with the allocated MAC addresses.
The corresponding **VMI** will be created with the same MAC addresses as in the VM template spec (given by the user/KubeMacPool).
But for interface hotplug this is not the case, the MAC address in the VM template spec won't replicate to the VMI spec, and the interface in the guest ends up with a random MAC address.
Hotplug on VM flow:
```
- virt-api handles VM interface-add request and add interface request to the VM status.
- virt-controller realizes there is a …
```
=> virt-controller, VMController: Patch VMI interfaces mac address

tests/launchsecurity/sev.go
This PR is supposed to fix the SEV test which was added to quarantine https://github.com/kubevirt/kubevirt/pull/9996
Considering that we want to ensure SEV devices are not advertised when the feature gate is disabled, probably it makes more sense to check the allocatable resources. Since the capacity just reflects the maximum number observed at some point in time.
Fixes #
```release-note
NONE
```
=> Fix flaky SEV test

pkg/monitoring/vmistats/collector.go, pkg/monitoring/vmistats/collector_test.go
kubevirt_vmi_phase_count was not being created because a label was missing
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2211512
```release-note
Fix kubevirt_vmi_phase_count not being created
```
=> Fix kubevirt_vmi_phase_count not being created

pkg/virt-handler/isolation/detector.go, pkg/virt-handler/isolation/detector_test.go, pkg/virt-handler/isolation/process.go, pkg/virt-handler/isolation/process_test.go, tests/realtime/BUILD.bazel, tests/realtime/realtime.go, tests/security_features_test.go, tests/utils.go, tests/vmi_configuration_test.go
- Lookup qemu process by executable prefix
Exact matching with `qemu-system` does not work since the executable name also includes a suffix with current architecture, e.g. qemu-system-x86_64. This leads to errors of type:
no QEMU process found under process 16427 child processes
- Detect the qemu emulator binary in runtime during e2e testing
Avoid hardcoding qemu-kvm since the underlying images may use e.g. qemu-system-*.
Fixes #
```release-note
NONE
```
=> Fix qemu-system-* process lookup

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, tests/instancetype_test.go
As set out in bug https://github.com/kubevirt/kubevirt/issues/10047 and demonstrated by the functional test in the
previous commit previously defaults were not applied before we would
check that preference requirements were met by a VirtualMachine.
This change extracts the preference check from applyInstancetypeToVm and
calls it directly after SetDefaultVirtualMachine has been called.
Ultimately this should allow preference requirements of a single vCPU to
to pass when no vCPUs have been provided by the original VirtualMachine.
Fixes #10047 …
=> instancetype: Apply defaults before checking preference requirements

pkg/virtctl/create/clone/BUILD.bazel, pkg/virtctl/create/clone/clone.go, pkg/virtctl/root.go
This PR fixes two bugs regarding `virtctl create` commands.
Firstly, it replaces `"gopkg.in/yaml.v2"` with `"sigs.k8s.io/yaml"` in `virtctl create clone` command.
Before this PR, this is the command's output:
```yaml
$ virtctl create clone --source-name test-vm
typemeta:
kind: VirtualMachineClone
apiversion: clone.kubevirt.io/v1alpha1
objectmeta:
name: clone-9txwp
generatename: ""
namespace: ""
selflink: ""
uid: ""
resourceversion: ""
generation: 0
creationtimestamp: "0001-01-01T00:00:00Z"
deletiontimestamp: null
deletiongraceperiodseconds: null
labels: {}
annotations: {}
ownerreferences: []
finalizers: []
managedfields: []
spec:
source:
apigroup: kubevirt.io
kind: VirtualMachine
name: test-vm
target:
apigroup: kubevirt.io
kind: VirtualMachine
name: …
```
=> Bug fix: `virtctl create clone` marshalling and replacement of `kubectl` with `kubectl virt`

pkg/storage/snapshot/snapshot.go, pkg/storage/snapshot/snapshot_test.go, tests/storage/snapshot.go
Runstrategy `Manual` + VM stopped would result in VMSnapshot hanging until VM started
Fixes #9944
```release-note
NONE
```
=> Fix VMSnapshot + Manual RunStrategy

api/openapi-spec/swagger.json, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-launcher/virtwrap/api/schema.go, pkg/virt-launcher/virtwrap/converter/BUILD.bazel, pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/converter_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go, staging/src/kubevirt.io/api/core/v1/schema.go, staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/storage/BUILD.bazel, tests/storage/storage.go, tests/utils.go
This PR enables users to change the behavior of the VM when it encounters an IO error. Currently, the default and only behavior is to pause the VM. 
Other possible options are `report`, `ignore`, `enospace` (see [libvirt documentation](https://libvirt.org/formatdomain.html)). 
Example:
```yaml
spec:
domain:
devices:
disks:
- disk:
bus: virtio
name: containerdisk
errorPolicy: "report"
- lun:
bus: scsi
name: scsi-disk
errorPolicy: "report"
```
Fixes #
```release-note
Add field errorPolicy for disks
```
=> Configure error policy for disks on IO errors

pkg/storage/export/export/export.go, pkg/storage/export/export/export_test.go
The generated DataVolumes were not compatible with populator populated sources. In particular the populators would have a datasource or datasourceRef set.
This PR clears the values so that the target CDI can properly generate PVCs from the Datavolume
Fixes #
```release-note
NONE
```
=> Export create populator compatible datavolumes from VM

hack/cluster-deploy.sh, tests/libstorage/datavolume.go
DV GC was disabled by default in CDI 1.57
Fixes #
```release-note
NONE
```
=> Adapt DV GC test to disabled by default

pkg/virt-launcher/virtwrap/api/schema.go, pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/converter_test.go
This will help access the BIOS/EFI menu when starting the VMI as paused otherwise there's not enough actual time to get into it. 
Fixes #
https://issues.redhat.com/browse/CNV-22801
```release-note
Add boot-menu wait time when starting the VM as paused.
```
=> Add BootMenu wait when starting a VM as paused

pkg/network/setup/netstat.go, pkg/network/setup/netstat_test.go, pkg/network/vmispec/interface.go, pkg/network/vmispec/interface_test.go, pkg/virt-handler/vm.go, pkg/virt-launcher/virtwrap/nichotplug.go, pkg/virt-launcher/virtwrap/nichotplug_test.go
Currently an unplugged iface reporting is flaky due to a race between virt-handler and virt-controller, where virt-handler set the VMI iface status according to the domain which dosent include detached interfaces.
On the other hande virt-controller see the subject external interface stil exist (according to the CNI annotation) and add it to the VMI status.
The end result is unpluged interfaces status is flaky, where it keeps get deleted and added.
To fix this, keep detached interfaces status whos  external iface exist in pod (have info-source mutlus-status) and also exist in the spec.
Fixes # …
=> virt-handler, VMI iface status: Fix detached interfaces status reporting

tests/hotplug/cpu.go
* The `countDomCPUs` helper function wasn't asserting with offset in some cases.
* In the dedicated CPU scenario there are two migrations that happen sequentially. The test was looking at the wrong migration object, since the object doesn't have any metadata about its originator, be it the hotplug mechanism or a manual trigger.
Fixes #
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2023-06-26-168h.html#row3
```release-note
NONE
```
=> [e2e]: CPU hotplug e2e fixes

cmd/virt-exportserver/BUILD.bazel
This is a quality of life change to help with https://bugzilla.redhat.com/show_bug.cgi?id=2156525.
Note that standalone non CDI PVCs will still not work unless a VM was utilizing them.
Due to non-root efforts, we must have fsGroup on our side to allow writing. Some provisioners like in-tree nfs just don't support fsGroup.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2156525
```release-note
Change exportserver default UID to succeed exporting CDI standalone PVCs (not attached to VM)
```
=> Change exportserver default UID to play nicer with CDI standalone PVCs

pkg/monitoring/domainstats/prometheus/prometheus.go
Fix not reporting vcpu wait metric when value is less than 1 second.
Currently we are converting `Wait` metric reported in microseconds into seconds, but we have a bug that if a metric is less than `1000000` it will always equal 0. This is happening due to us using `uint64` to calculate fraction of second instead of using `float64`.
Example:
```go
shouldNotBeZero := float64(80) / float64(100)
shouldNotBeZeroButWillBe := float64(80 / 100)
fmt.Println(shouldNotBeZero) // prints 0.8
fmt.Println(shouldNotBeZeroButWillBe) // prints 0
```
Fixes # …
=> Fix not reporting vcpu wait metric when value is less than 1 second

pkg/virt-controller/watch/vm.go
The VirtualMachine validation admission webhook should cover this case now as suggested by the also remove TODO comment:
https://github.com/kubevirt/kubevirt/blob/f737c5be56dc467f943bb5e3bd1e698ae94cfa05/pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go#L321-L327
Fixes #
```release-note
NONE
```
=> controller: Remove VirtualMachineInstanceTemplateSpec check

tests/instancetype_test.go
This PR adds functional tests for VirtualMachineClusterPreference fields PreferredTerminationGracePeriodSeconds and PreferredSubdomain
```
NONE
```
=> Tests instancetype: add subdomain and termination grace period

pkg/virt-controller/watch/network.go, pkg/virt-controller/watch/network_test.go, pkg/virt-controller/watch/vm.go, tests/libnet/interface.go, tests/network/hotplug.go
Currently, hot-unplugged interfaces are marked as absent and
remain in the VM & VMI spec even after the interface is no longer
exist in the guest or virt-launcher pod.
Remove detached interfaces with absent state from VM & VMI spec.
An interface is considered as detached if it exists in the VMI spec,
have 'absent' state, and are not being reported in the VMI status.
Fixes #
~~Depends on #10063 (first 3 commits)~~
In the scenario in-place hotplug is performed using Multus V4,
since there is no indication regarding the wiring and cache files Kubevirt
sets in …
=> Clear absent ifaces

tests/testsuite/namespace.go
Tests weren't cleaning up VMExports, and leaving them around in the test namespace. This PR adds the cleanup of these resources
Fixes #
```release-note
NONE
```
=> Cleanup VMExports after tests

pkg/virt-handler/node-labeller/node_labeller.go
In some environments, sysfs is mounted read-only even for privileged containers. Use the ksm path from the host filesystem.
Related issue: https://github.com/containerd/containerd/issues/8445
Fixes #
```release-note
NONE
```
=> ksm: Access sysfs from the host filesystem

pkg/virt-launcher/virtwrap/manager.go
Without this PR a  `warning` will override the log level.
Fixes #
```release-note
NONE
```
=> [release-0.59]logs: Do not set verbosity for higher log levels

pkg/virt-controller/watch/network.go, pkg/virt-controller/watch/network_test.go, pkg/virt-controller/watch/vm.go, tests/libnet/interface.go, tests/network/hotplug.go
Cherry-pick #10116 
Fixes #
It's necessary to do this manually due to conflicts
```release-note
Existing detached interfaces with 'absent' state will be cleared from VMI spec.
```
=> [release-1.0] Clear absent ifaces

pkg/virt-controller/services/template_test.go, pkg/virt-controller/services/virtiofs.go
**What this PR does / why we need it**: this PR is for the bug fix https://github.com/kubevirt/kubevirt/issues/10005, looks like there are some hardcode to prevent virt-launcher pod enter guaranteed qos group when use virtiofs, becasue virtiofs sidecar is not a guaranteed qos container
**Which issue(s) this PR fixes** :
Fixes # https://github.com/kubevirt/kubevirt/issues/10005
```release-note
fix guaranteed qos of virt-launcher pod broken when use virtiofs
```
=> fix guaranteed qos of virt-launcher pod broken when use virtiofs

tests/reporter/kubernetes.go, tests/storage/BUILD.bazel, tests/storage/export.go, tests/storage/snapshot.go
Increased some timeouts to allow longer times to finish tests. Cleaned up Ptr from deprecated functions to newer functions. Made condition checks order independent and return better state information if the test does fail.
Fixes #
```release-note
NONE
```
=> Clean up storage tests to reduce flakiness

pkg/monitoring/perfscale/vmi-phase-transitions.go
It adds a help text to the VMI phase transition time metrics.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2196257
The metrics are histograms.
```release-note
NONE
```
=> Add help text to the phase transition time metrics

pkg/instancetype/instancetype.go, pkg/instancetype/instancetype_test.go, pkg/storage/snapshot/restore.go, pkg/storage/snapshot/snapshot_test.go, pkg/storage/snapshot/source.go, staging/src/kubevirt.io/api/instancetype/register.go
ControllerRevisions are used to store point in time copies of instance
type and preference objects for each VirtualMachine making use of the
feature, see the following user-guide docs for more on this:
Instance types and preferences - Versioning
https://kubevirt.io/user-guide/virtual_machines/instancetypes/#versioning
This change adds labels to these ControllerRevision, exposing metadata
of the stored objects. With this in place it becomes easier to track the
objects stored within these ControllerRevisions and in the future
orchestrate the migration of these objects to newer versions of the API
and CRDs as these are introduced.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
=> instancetype: Label ControllerRevisions with stored object metadata

pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
DataVolumeSpec provides two mutually exclusive ways of defining attributes of the destination volume through either a PersistentVolumeClaimSpec [2] or StorageSpec [3].
Both provide ways of controlling the storageClass of the eventual PVC but as outlined in bug #10025 previously PreferredStorageClassName was only applied to the PersistentVolumeClaimSpec of a DataVolumeSpec.
This change corrects this ensuring PreferredStorageClassName is applied to the StorageSpec if provided within a DataVolumeSpec.
[1] http://kubevirt.io/api-reference/main/definitions.html#_v1beta1_datavolumespec
[2] http://kubevirt.io/api-reference/main/definitions.html#_k8s_io_api_core_v1_persistentvolumeclaimspec
[3] http://kubevirt.io/api-reference/main/definitions.html#_v1beta1_ …
=> instancetype: Apply PreferredStorageClassName to StorageSpec if provided

api/openapi-spec/swagger.json, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/instancetype/v1alpha2/types.go, staging/src/kubevirt.io/api/instancetype/v1alpha2/types_swagger_generated.go, staging/src/kubevirt.io/api/instancetype/v1beta1/types.go, staging/src/kubevirt.io/api/instancetype/v1beta1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go
/cc @0xFelix 
/cc @cwilkers 
This was missed in 3e2ffba1797fa84c5f2751ef5504d337c9f492d9 as `v1alpha2` had already been copied from `v1alpha1` with the mistake in place.
https://github.com/kubevirt/kubevirt/blob/ab6645487f1a09abe33d5b1cadec0fb7811a6eeb/pkg/instancetype/instancetype.go#L71-L78
Fixes #
```release-note
NONE
```
=> instancetype: Fix default PreferredCPUTopology value in API docs

tests/migration_test.go, tests/vmidefaults_test.go
Currently, some memballoon and FPR e2e tests rely on the fact that FPR is enabled; this because FPR is enabled by default. Some installation can have FPR explicitly disabled, resulting in failures.
For memballon tests: Start considering the expected output based on the cluster kv config.
For migration test: Enable FPR before starting the test.
Also: Dropped a `tests.UpdateKubeVirtConfigValueAndWait(kvConfiguration)` function call in the AfterEach section, since the kv config is restored by global cleanup.
Fixes #
```release-note
NONE
```
/cc …
=> [e2e] Fix FPR tests, supporting several cluster config

pkg/virt-handler/isolation/detector.go
The file is not closed，and the sock connection has not been truly closed, and it occupy connections for libvirtd
=> isolation:  close file when exits

pkg/virt-controller/watch/vmi.go, pkg/virt-launcher/virtwrap/converter/converter.go, tests/storage/hotplug.go
When the hotplug attachment pod is deleted, the VMI volumestatus goes back to bound, which triggers the manager to detach the volume from the running VM
interrupting any IO on that volume. The pod is then re-created and the volume gets re-attached and operation can continue, but if the volume is mounted, it needs to be re-mounted in the VM.
This commit modifies the logic so that if the volume is ready, it cannot go back to bound if the attachment pod disappears. This prevents the detachments and issues with IO on the running VM.
Fixes # …
=> Fix volume detach on hotplug attachment pod delete

pkg/virt-controller/watch/topology/filter.go, pkg/virt-controller/watch/topology/filter_test.go, pkg/virt-controller/watch/topology/hinter.go
Currently, when virt-handler tries to find the lowest TSC frequency on the cluster, all nodes are being considered even if they're unschedulable. This makes no sense, and we shouldn't consider those when finding the lowest TSC frequency, or else some VMs on some environments would be stuck at "scheduling" forever.
Fixes #
```release-note
NONE
```
=> Stop considering master nodes when finding lowest TSC frequency on the cluster

docs/metrics.md, pkg/monitoring/domainstats/prometheus/prometheus.go, pkg/monitoring/domainstats/prometheus/prometheus_test.go, tools/prom-metrics-collector/metrics_collector.go
Fixes: #9713
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-28961
```release-note
Remove affinities label from kubevirt_vmi_cpu_affinity and use sum as value
```
=> Remove affinities label from kubevirt_vmi_cpu_affinity and use sum as value

tests/instancetype_test.go
As discovered in #9805 these functional tests have actually not been
running for some time now. The ultimate goal of this refactor is to
allow these tests to run once again under the default `local`
storageclass provided by kubevirtci.
The following changes were made to the tests to accommodate this:
- Remove the use of Ordered
- Remove the dependency on a RWO block StorageClass
- Validate the VirtualMachine prior to any attempt to start
- Use a DataVolume to orchestrate the creation of the source PVC
- Use of the ForceBinding annotation to ensure the PVC is bound
- Use libdv to build DataVolume objects
- Add TODOs for possible libdv and other follow ups (posted as a draft https://github.com/kubevirt/kubevirt/pull/9885 to avoid blocking this PR)
- …
=> instancetype: Refactor and fix inferFromVolume functional tests

pkg/virt-launcher/BUILD.bazel, pkg/virt-launcher/monitor.go, tests/migration_test.go
When virt-launcher starts, it searches for `qemu-kvm` PID.
If a virtual machine migration is created and then cancelled, before the virt-launcher detects the qemu-kvm process pid, the target virt-launcher is not cleaned up immediately and waits for the qemu-timeout (which is 3 minutes by default).
It will wait in the refresh monitor here https://github.com/kubevirt/kubevirt/blob/f77d50591ddd0f74c0c876e38fdf14ca3fe54be8/pkg/virt-launcher/monitor.go#L126.
This PR fixes this bug by stopping to search for the PID if the migration is cancelled.
This PR also adjusts a functional test that I confirm that fails without these changes and passes after them.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2161184
**How to …
=> Bugfix: target virt-launcher pod hangs when migration is cancelled

docs/metrics.md, pkg/monitoring/domainstats/prometheus/prometheus.go, pkg/monitoring/domainstats/prometheus/prometheus_test.go, pkg/virt-launcher/virtwrap/stats/types.go, pkg/virt-launcher/virtwrap/statsconv/converter.go, pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
Add vcpu delay domain metrics, which reports amount of seconds VM spent in  waiting in the queue instead of running.
According to libvirt docs:
```
vcpu.<num>.delay - time the vCPU <num> thread was enqueued by the host scheduler, but was waiting in the queue instead of running. Exposed to the VM as a steal time.
```
Fixes #
```release-note
Expose kubevirt_vmi_vcpu_delay_seconds_total reporting amount of seconds VM spent in  waiting in the queue instead of running.
```
=> Expose kubevirt_vmi_vcpu_delay_seconds_total metric.

pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go, pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
The secret that contains SSH keys for a VM can potentially contain multiple keys separated by newline, or just a single key with a newline at the end. This PR removes the newlines and splits the keys into a slice.
First commit in this PR add a `Stop()` method to the `AccessCredentialManager`, which is used in the new unit test to stop `fsnotify` and not leak it.
```release-note
None
```
=> virt-launcher: access-credentials: Trim newlines from SSH keys in secret

api/openapi-spec/swagger.json, manifests/generated/kv-resource.yaml, pkg/virt-config/configuration.go, pkg/virt-config/configuration_test.go, pkg/virt-config/virt-config.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/vmi_configuration_test.go
`spec.config.machineType` got obsoleted by https://github.com/kubevirt/kubevirt/pull/8293 but it still exist and should therefore be honored if set to not break compatibility.
The field is now also marked as deprecated so that it can be removed in the future.
Fixes #
```release-note
Deprecate `spec.config.machineType` in KubeVirt CR.
```
=> Fix and deprecate `machineType` in KubeVirt CR Config

pkg/virt-launcher/BUILD.bazel, pkg/virt-launcher/monitor.go, tests/migration_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/10099.
The automated cherry-pick failed because of a function moved to `libwait` which didn't exist in this branch.
```release-note
Bugfix: target virt-launcher pod hangs when migration is cancelled.
```
=> [release-0.58] Bugfix: target virt-launcher pod hangs when migration is cancelled

manifests/generated/operator-csv.yaml.in, manifests/generated/rbac-operator.authorization.k8s.yaml.in, pkg/virt-operator/resource/generate/rbac/controller.go, pkg/virt-operator/resource/generate/rbac/operator.go
Instead of giving virt-operator and virt-controller cluster-wide lease access, restrict the permissions to the install namespace.
Fixes #
<!--  Write your release note:
```release-note
Restrict coordination/lease RBAC permissions to install namespace
```
=> Move coordination/lease RBAC permissions to Roles

pkg/virt-launcher/virtwrap/api/deepcopy_generated.go, pkg/virt-launcher/virtwrap/api/schema.go, pkg/virt-launcher/virtwrap/api/schema_test.go, pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/pci-placement.go, tests/libvmi/vmi.go, tests/operator/operator.go, tests/utils.go, tests/vmi_configuration_test.go, tests/vmi_monitoring_test.go
The issue has been found while testing a downstream build of KubeVirt v1.0.0 with libvirt **9.5.0**. Currently, it is not reproducible with the latest upstream images, since the libvirt version there is **9.0.0**. However, this issue is likely to emerge after an update of the virt stack.
The failing test with a watchdog device:
https://github.com/kubevirt/kubevirt/blob/d16161124f3008a0404de663f678f5a1b463ce5a/tests/vmi_configuration_test.go#L145-L155
Starting from version **9.1.0**, Libvirt adds an implicit watchdog device for q35 machine:
https://gitlab.com/libvirt/libvirt/-/commit/926594dcc82b40f483010cebe5addbf1d7f58b24
https://libvirt.org/formatdomain.html#watchdog-devices
> Having multiple watchdogs is usually not something very common, but be …
=> Fix for libvirt >= 9.1.0: Support multiple watchdogs in the domain schema

tests/decorators/decorators.go, tests/hotplug/cpu.go
CPUHotplug requires `VMLiveUpdateFeatures` fg.
Decorate the related tests with a proper decorator.
Fixes #
```release-note
NONE
```
=> [e2e] Decorate hotplug tests with VMLiveUpdateFeaturesGate decorator.

docs/metrics.md, pkg/monitoring/domainstats/prometheus/prometheus.go, pkg/monitoring/domainstats/prometheus/prometheus_test.go, tests/monitoring/prometheus_utils.go, tests/monitoring/vm_monitoring.go
kubevirt_vmi_cpu_system_usage_seconds
kubevirt_vmi_cpu_usage_seconds
kubevirt_vmi_cpu_user_usage_seconds
are cumulative values and cannot arbitrarily go up and down, therefore they should be Counters and not Gauges
Fixes #
```release-note
Change kubevirt_vmi_*_usage_seconds from Gauge to Counter
```
**JIRA ticket**:
```jira-ticket
https://issues.redhat.com/browse/CNV-31131
```
=> Change kubevirt_vmi_*_usage_seconds from Gauges to Counters

pkg/virt-controller/watch/topology/filter.go, pkg/virt-controller/watch/topology/filter_test.go, pkg/virt-controller/watch/topology/hinter.go
This is a follow-up to https://github.com/kubevirt/kubevirt/pull/10169.
It basically reverts the previous changes and instead filters nodes without `kubevirt.io/schedulable` label from the TSC discovery.
For more info:
- https://github.com/kubevirt/kubevirt/pull/10169#issuecomment-1651537898
- https://github.com/kubevirt/kubevirt/issues/10181
Fixes #10181
```release-note
Stop considering nodes without `kubevirt.io/schedulable` label when finding lowest TSC frequency on the cluster
```
=> Stop considering nodes without `kubevirt.io/schedulable` label when finding lowest TSC frequency on the cluster

pkg/virt-operator/resource/apply/reconcile.go
As set out in the following associated code comment(s) this logic was only used for backward compatibility with older versions of KubeVirt, specifically <= `v0.29.0`.
```
// This is for backward compatibility where virt-api managed the entity itself.
// If someone upgrades from such an old version and then has to roll back, we want avoid deleting a resource
// which was not explicitly created by an operator, but is still visible to it.
// TODO: Remove this once we don't support upgrading from such old kubevirt installations.
```
Fixes # …
=> virt-operator: Remove virt-api compat code when removing resources

BUILD.bazel, cmd/libguestfs/BUILD.bazel, cmd/pr-helper/BUILD.bazel, cmd/virt-exportserver/BUILD.bazel, cmd/virt-handler/BUILD.bazel, containerimages/BUILD.bazel, images/BUILD.bazel, images/disks-images-provider/BUILD.bazel
These rules have been extracted from the Bazel sources and are now available at bazelbuild/rules_pkg.
See the following issue for more details:
https://github.com/bazelbuild/bazel/issues/8857
Fixes #
```release-note
NONE
```
=> bazel: Move to rules_pkg extracted version of pkg_tar

pkg/controller/controller.go, pkg/virt-controller/watch/network.go, pkg/virt-controller/watch/network_test.go, pkg/virt-controller/watch/vm.go
This commit fixes the bug be explicitly adding the default interface to the VM on hotplug.
If a VM has no interfaces a default one may be automativally added to the VMI.
A VM with no interfaces (that has a default interface added to its VMI) ends up with only one interface after a hotplug although the VMI has two. Therefore, after the VM is restarted, the default interface disappear.
Fixes #
hotplug API was changed on the main branch. 
The user is directly updating the VM spec template to hotplug. So the bug that this PR is fixing is not relevant there. …
=> [release-1.0] hotplug interface: Fixing VM with default interface bug

cmd/virt-chroot/BUILD.bazel, cmd/virt-chroot/selinux.go, cmd/virt-handler/virt-handler.go, pkg/storage/reservation/pr.go, pkg/util/util.go, pkg/virt-handler/device-manager/socket_device.go, pkg/virt-operator/resource/generate/components/BUILD.bazel, pkg/virt-operator/resource/generate/components/daemonsets.go, tests/storage/BUILD.bazel, tests/storage/reservation.go
The PR fixes the issues outlined in https://github.com/kubevirt/kubevirt/issues/10172:
- The `pr-helper` container does not terminate properly and reports `Permission denied` error. This happens because the default user for the container is `1001` while the directory where it stores the socket is owned by `107:107 (qemu:qemu)`. Thus, the socket unlink fails.
- Leftover tmpfs mount point on the node. This is likely due to a redundant volume mount of the `pr-helper-socket-vol` in the `virt-handler` container.
Additionally, the PR extends the e2e testing by checking that the resources have been properly cleaned up and also ensures that KubeVirt CR is in ready state before running the actual tests (toggling `PersistentReservation` feature gates triggers …
=> Fix pr leftover mount

tests/utils.go, tests/vmi_configuration_test.go
The 2 tests under `test_id:4023` are flaky, one is even quarantined (quarantine removed to see if it still trips the flake finder).
They both make a bunch of calls to `ps`, which has proven unreliable in the past, although we never really pinpointed the exact issue.
This PR replaces most calls to `ps` with more reliable options, and puts the last one in an `Eventually()` loop just in case that helps...
Fixes #
```release-note
NONE
```
=> Replace/sanitize `ps` calls in isolated emulator thread tests

tests/libstorage/pvc.go
The helper pod needs permissions to access the PVC data. In most cases, it is owned by the qemu (107) user.
Fixes #
Found during **downstream** testing of v1.0.0. Currently, some of the storage hotplug tests fail:
https://github.com/kubevirt/kubevirt/blob/90e08909ac8b67dbb9902062abef21b26a667ec3/tests/storage/hotplug.go#L1099
The tests import a containerdisk with cirros image to a Filesystem PVC using a DataVolume. Then a helper pod is started to rename the image file from `disk.img` to smth different. The renaming fails with `Permission denied`:
```
mv: …
```
=> tests: Run helper pod as qemu (107) user

examples/vmi-fedora.yaml, tools/vms-generator/utils/utils.go
Often I find it valuable to use `vmi-fedora` as a migratable VM instead of `vmi-migratable` which is alpine-based. As an example, in the fedora image we have several tools available like `stress-ng`.
WIth this in place, the `migration-job.yaml` can be changed to refer to `vmi-fedora`, and the user could choose which migratable vmi to use.
```release-note
NONE
```
=> Make `examples/vmi-fedora.yaml` migratable

tests/decorators/decorators.go, tests/vm_state_test.go, tests/vmi_tpm_test.go
This way the kubevirt tests can not pick up these tests when
a cluster does not have an RWX FS storage solution.
Fixes #
```release-note
NONE
```
=> [e2e tests]: Decorate vTPM tests with RWX FS storage requirement

tests/operator/operator.go
Checking if the kubevirt PrometheusRule cr exists, a comparison between the posted Cr and a generated one is done. This comparison is too strict, since some vendors could use a different `RUNBOOK_URL`, causing a failure.
From an operator functionality perspective, it is enough to check that the CR exists and the group contains a set of rules.
Fixes #
```release-note
NONE
```
=> [e2e] Relax prometheus cr operator test

pkg/virt-operator/util/readycheck.go
Applying a custom `NoSchedule` taint to a nod will flip the `Available` condition of KubeVirt to `False`:
```
- lastProbeTime: "2023-08-07T14:15:43Z"
lastTransitionTime: "2023-08-07T14:15:43Z"
message: Deploying version devel with registry registry:5000/kubevirt
reason: DeploymentInProgress
status: "False"
type: Available
```
This will only resolve back to `True` if the pod gets manually evicted, or if the daemonset gets updated.
The background is, that we will see more up-to-date virt-handler pods in ready state than we actually want.
Relax the readiness check slightly by counting misscheduled but up-to-date and ready virt-handlers as something which does not trigger a `DeploymentInProgress` state.
**Which issue(s) this PR fixes** *(optional, in …
=> [virt-operator] cope with misscheduled virt-handler pods

staging/src/kubevirt.io/api/README.md
This pull request provides install instructions for how to install the Kubernetes client code generator as this might not be obvious to everyone.
=> Provide client-gen install instructions

pkg/virt-handler/device-manager/mediated_devices_types.go
When /sys/bus/mdev/devices directory exists, then no cleanup is necessary, and we don't have to log that the directory does not exist.
Fixes recurring messages like this:
```
2023-08-10T08:45:41.541322652Z {"component":"virt-handler","level":"error","msg":"failed to remove mdev types: failed to read the content of /sys/bus/mdev/devices directory","pos":"mediated_devices_types.go:263","reason":"open /sys/bus/mdev/devices: no such file or directory
```
Fixes #
```release-note
NONE
```
=> Fix recurring heartbeat error logs when no mdev devices are present

docs/metrics.md, pkg/monitoring/domainstats/prometheus/prometheus.go, pkg/monitoring/domainstats/prometheus/prometheus_test.go, tools/prom-metrics-collector/metrics_collector.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/10070
Fixes #
```release-note
Remove affinities label from kubevirt_vmi_cpu_affinity and use sum as value
```
=> [release-1.0] Remove affinities label from kubevirt_vmi_cpu_affinity and use sum as value

pkg/testutils/mock_config.go, pkg/virt-api/webhooks/defaults.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go, pkg/virt-config/configuration.go
Store the VM assigned eviction strategy into the VMISpec, this
comes in handy as it's not always clear which evictionStrategy is
assigned to a VM if the cluster-wide setting was different
when the VM was first started.
https://bugzilla.redhat.com/show_bug.cgi?id=2228036
Fixes #
```release-note
NONE
```
=> virt-controller: always store evictionStrategy in Spec

tests/vm_test.go
Otherwise this test will fail when MachineType is externally in the KubeVirt CR as it takes precedence over the architectureConfiguration.
Fixes #
```release-note
NONE
```
=> tests: unset MachineType

tests/monitoring/monitoring.go
This PR adds a check to the alerts rules test, which verifies that the alerts `runbook_url` annotations has the alerts names as a suffix.
**Which issue(s) this PR fixes**: https://issues.redhat.com/browse/CNV-30798
```release-note
None
```
=> Force runbooks names to equal alerts names

tests/decorators/decorators.go, tests/vmi_tpm_test.go
This way the kubevirt tests can not pick up these tests when a cluster does not have an RWX FS storage solution.
Fixes #
```release-note
NONE
```
=> [release-1.0] Backport 'Decorate vTPM tests with RWX FS storage requirement'

pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, pkg/virt-handler/hotplug-disk/mount.go, tests/storage/hotplug.go
Before deleting the old attachment pod, wait for the new attachment pod to be ready, so k8s will not detach the volume from the node since there will always be a pod using the volume from its perspective. This should prevent issues with certain CSI drivers that don't respect the device being in use before detaching it from the node. This will now break csi drivers that don't allow multiple pods on the same node to use the volume (this is a bug in that driver).
Fixed issue where when adding or removing a volume the existing volumes would still have the UID of the old attachment pod in the VMI status which caused errors to appear in the virt-handler logs about not being able to find the device or image. This can be observed with SyncFailed events on …
=> Wait for new hotplug attachment pod to be ready

automation/repeated_test.sh
This PR fixes three things:
We do not want to use the latest provider if it is not stable yet, since there might be regressions that are not yet fixed in an rc.
Thus we use the latest stable provider instead.
Some tests need two nodes with cpu manager installed, since the first node doesn't have it installed, they then fail.
Set nodes to 3 in that case.
The [default test script increases the node memory](https://github.com/kubevirt/kubevirt/blob/main/automation/test.sh#L109).
Since [a test was failing for this reason](https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-check-tests-for-flakes) (thanks @jean-edouard) we increase the node memory to the same amount. …
=> flake-check: use stable kubevirtci provider, set 3 nodes if required

tests/operator/operator.go
Manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/10238.
```release-note
None
```
=> [Release-1.0] Relax prometheus cr operator test

tests/migration_test.go
In order to slow a migration, we set the `BandwidthPerMigration` to a very low value.
Currently, since this value is a `Millibyte`, when converting it to byte, it results that the migration params will be `BandwidthSet:false Bandwidth:0`, which means that we are not slowing the migration. Let's use `NewQuantity` instead of `NewMilliQuantity`, so that the result will be `BandwidthSet:true Bandwidth:1`
Fixes #
```release-note
NONE
```
/cc @xpivarc
=> [e2e] Fix migration bandwidth

pkg/virt-api/rest/BUILD.bazel, pkg/virt-api/rest/profiler.go, pkg/virt-api/rest/profiler_test.go
`ClusterProfiler` FG enables to run the profiler inside the component pod (virt-api, virt-controller, virt-operator, virt-handler). Currently, to filter these pod, we retrieve the full list of the pods and then search if the name contains `virt-api`,`virt-operator`,`virt-handler`,`virt-controller`. This can result in failure if other external components match these name(e.g. kubevirt-apiproxy from HCO). In this patch there are two improvements:
- use label selector to filter pods that have kubevirt.io label.
- use a regex to filter the components.
Fixes # …
=> Fix filter component pod in profiler

docs/metrics.md, pkg/monitoring/domainstats/prometheus/prometheus.go, pkg/monitoring/domainstats/prometheus/prometheus_test.go, tests/monitoring/monitoring.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/10273
Fixes #
```release-note
Change kubevirt_vmi_*_usage_seconds from Gauges to Counters
```
=> [release-0.59] Change kubevirt_vmi_*_usage_seconds from Gauges to Counters

docs/metrics.md, pkg/monitoring/domainstats/prometheus/prometheus.go, pkg/monitoring/domainstats/prometheus/prometheus_test.go, tests/monitoring/prometheus_utils.go, tests/monitoring/vm_monitoring.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/10138
Fixes #
```release-note
Change kubevirt_vmi_*_usage_seconds from Gauges to Counters
```
=> [release-1.0] Change kubevirt_vmi_*_usage_seconds from Gauges to Counters

BUILD.bazel, cmd/network-slirp-binding/BUILD.bazel, cmd/network-slirp-binding/README.md, cmd/network-slirp-binding/callback/BUILD.bazel, cmd/network-slirp-binding/callback/callback.go, cmd/network-slirp-binding/callback/callback_suite_test.go, cmd/network-slirp-binding/callback/callback_test.go, cmd/network-slirp-binding/dns/BUILD.bazel, cmd/network-slirp-binding/dns/resolvconf.go, cmd/network-slirp-binding/domain/BUILD.bazel, cmd/network-slirp-binding/domain/domain.go, cmd/network-slirp-binding/domain/domain_suite_test.go, cmd/network-slirp-binding/domain/domain_test.go, cmd/network-slirp-binding/main.go, cmd/network-slirp-binding/server/BUILD.bazel, cmd/network-slirp-binding/server/server.go, hack/bazel-push-images.sh
This PR introduce Slirp hook sidecar, its a new hook sidecar for configuring Slirp network interfaces in Kubevirt.
Currently Slirp interfaces configure by Kubevirt, internally. 
With the new sidecar hook, its possible to delegate Slirp interfces configuration outside Kubevirt
and enable reducing code maintenance.
Unlike other hook sidecar examples, Slirp hook-sidcar is set automatically by Kubevirt for VMs who has Slirp interface.
No need to add Kubeviet hook-sidecar annotation or any other configuration.
Fixes #
Commits 4-7 are for testing slirp hook sidecar …
=> Slirp hook sidecar

pkg/virtctl/memorydump/memorydump.go, pkg/virtctl/memorydump/memorydump_test.go, pkg/virtctl/utils/test_utils.go, pkg/virtctl/vmexport/BUILD.bazel, pkg/virtctl/vmexport/vmexport.go, pkg/virtctl/vmexport/vmexport_test.go, tests/storage/BUILD.bazel, tests/storage/export.go, tests/storage/memorydump.go, vendor/k8s.io/kubectl/pkg/util/BUILD.bazel, vendor/k8s.io/kubectl/pkg/util/apply.go, vendor/k8s.io/kubectl/pkg/util/pod_port.go, vendor/k8s.io/kubectl/pkg/util/service_port.go, vendor/k8s.io/kubectl/pkg/util/umask.go, vendor/k8s.io/kubectl/pkg/util/umask_windows.go, vendor/k8s.io/kubectl/pkg/util/util.go, vendor/modules.txt
VirtualMachineExport volumes are only downloadable outside the cluster when proper ingress or routes are configured.
In some cases, it's helpful to force a way to download the volumes without this configuration, so this pull request introduces an option to set port-forwarding using the vmexport service so that we can get the vmexport contents outside the cluster without additional configuration.
Usage examples:
```sh
$ virtctl vmexport download vm1-export --pvc=pvc-test --output=disk.img.gz --port-forward
$ virtctl vmexport download vm1-export --pvc=pvc-test --output=disk.img.gz --port-forward --local-port=4342
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …
=> Add port-forward functionalities to virtctl vmexport

tests/network/hotplug_sriov.go
PR #10185 introduced the SR-IOV migration-based hotplug with an E2E test that fails [1] in case the `HotplugNICs` feature gate is disabled.
The CI system of kubevirt/kubevirtci, has an SR-IOV lane that deploys a cluster and runs the conformance test mechanism with a focus on SR-IOV tests[2] without enabling the `HotplugNICs` feature gate.
This causes the pre-submit jobs in kubevirt/kubevirtci to fail[3], and requires a maintainer override in order to merge PRs.
As an immediate fix, skip the SR-IOV migration based hotplug tests if the `HotplugNICs` feature gate is disabled.
The kubevirt/kubevirt tests will not be affected by this change. A more permanent fix will follow.
[1] https://github.com/kubevirt/kubevirt/blob/cb29e9f87d41deae0d9e1efa6b0cde53ecd8c28a/tests/network/hotplug_sriov.go#L52 …
=> net, e2e: Skip SR-IOV hotplug if FG is disabled

pkg/network/setup/netstat.go, pkg/network/vmispec/hotplug.go, pkg/network/vmispec/hotplug_test.go, pkg/network/vmispec/interface.go, pkg/virt-controller/watch/network.go, pkg/virt-controller/watch/network_test.go, pkg/virt-controller/watch/vm.go, pkg/virt-handler/vm.go, pkg/virt-launcher/virtwrap/nichotplug.go
Refactor the `vmispec` and virt-controller dynamic interfaces calculation.
Fixes #
```release-note
NONE
```
=> network: Cleaning up `vmispec`

tests/access_test.go
`testAction()` is called *many* times by the tests in that file. Every time with different parameters.
On failure, we need to know which one failed.
Fixes #
```release-note
NONE
```
=> tests: add meaningful logs to access failures

pkg/instancetype/instancetype.go, pkg/instancetype/instancetype_test.go
Previously when provided the values of these preferences always overwrote any corresponding user values provided in the `VirtualMachine`.
Fixes #10313
```release-note
NONE
```
=> instancetype: Fix `PreferredUse{BiosSerial,SecureBoot}`

pkg/virtctl/vm/add_volume.go, pkg/virtctl/vm/common.go, pkg/virtctl/vm/migrate.go, pkg/virtctl/vm/remove_volume.go, pkg/virtctl/vm/restart.go, pkg/virtctl/vm/start.go, pkg/virtctl/vm/stop.go, pkg/virtctl/vm/vm_test.go
As a follow up to #9183, simplified the nested if/else logic in the Stop and Restart command. Also moved the  code block for setting the dryRunOption to a common helper function and made dryRunOption a global variable as it used in multiple different commands.
Fixes #
```release-note
NONE
```
=> code cleanup: Simplify virtctl VM command files

docs/metrics.md, pkg/virt-controller/watch/application.go
a metric name changed only in the test files and not in the metric definition, see https://github.com/kubevirt/kubevirt/pull/9821 and see the bug here:https://github.com/kubevirt/kubevirt/pull/9821/files#diff-9ad6a6110d7d4105a50147793d748edfaa2237b821bd4e5a6f512b5cb3030ef7R352
Blocking https://github.com/kubevirt/kubevirt/pull/10323
```
Deprecation notice for the metric listed in the PR. Please update your systems to use the new metrics names:
kubevirt_virt_controller_leading | kubevirt_virt_controller_leading_status
```
=> [bug-fix] Reference changed without changing the definition

pkg/virt-controller/watch/migration_test.go, tests/BUILD.bazel, tests/migration_policy.go, tests/migration_test.go
This PR parallelizes post-copy related functional tests by using migration policies (which apply a specific scope) instead of Kubevirt CR for configuration (which is cluster-wide).
In addition, it introduces many stabilization and improvements, such as:
* Tune bandwidth limitation and stress size properly. See commit description for more info.
* Tune stress sleep time properly. Reduced from ~26 minutes, which is completely exaggerated, to 30 seconds.
* Add a `AlignPolicyAndVmi()` function to match existing policy and VMI.
* General refactoring.
```release-note
NONE
```
=> [functest 4747]: Stabilize and parallelize post-copy related functional tests

images/nfs-server/BUILD.bazel, images/nfs-server/entrypoint.sh, tests/storage/storage.go
Kubelet fails to umount the NFS volume and gets stuck when performing pod cleanup if the server has already gone. Ensure that the VMI is deleted first, and the corresponding volume is released (current global tests cleanup hook does not guarantee deletion order).
Fixes #
I observe the issue after running nightly tests. I see the nodes in `NotReady` state with stale NFS mount points:
```
10.42.1.220:/ on /var/lib/kubelet/pods/0747bcc2-9f8d-473d-acfc-21393679e9d0/volumes/kubernetes.io~nfs/test-nfsfb92r6g7cvw57rghvh25q7j99wj7vws9tbbqwhkp58v222mq type nfs4 …
```
=> tests: Delete VMI prior to NFS server pod

cmd/network-slirp-binding/domain/domain.go, cmd/network-slirp-binding/domain/domain_test.go
This PR make Slirp network binding plugin to not duplicate Slirp networking QEMU cmd args  in the domain spec.
In order words make the plugin idempotent.
Fixes #
```release-note
NONE
```
=> Slirp network binding plugin: Do not duplicate slirp iface QEMU cmd args

pkg/util/migrations/migrations.go, pkg/virt-controller/watch/drain/evacuation/evacuation.go, pkg/virt-controller/watch/drain/evacuation/evacuation_test.go, pkg/virt-controller/watch/workload-updater/workload-updater.go, pkg/virt-controller/watch/workload-updater/workload-updater_test.go, tests/BUILD.bazel, tests/migration_test.go
Kuebvirt has cluster-level threshold for concurrent active migrations, with per-source-node granularity.
When a controller checks whether it allowed to create more migrations, it should not count pending migrations
but only these migrations that are already scheduled and running. 
Controllers to fix: evacuation, workload-updater 
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2210070
```release-note
NONE
```
=> [virt-controller] don't count pending migrations when validating the allowed migrations limit

pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/migration.go, pkg/virt-controller/watch/workload-updater/workload-updater.go
While working on metrics, I found this double multiplication which transforms a 5 second value into a ~158 year one, which seems wrong.
This PR fixes that in its first commit, and provides some nit-picky code cleanup in its second commit.
Fixes #
The `defaultThrottleInterval` const is still used for 3 completely unrelated things, none of which seem to match its comment.
This code probably needs further cleanup.
**Checklist** …
=> virt-controller: fix double `time.Second` multiplication in rate limiter

pkg/instancetype/instancetype_test.go
Add a test to validate that when we start a VM with disk bus defined and a preference with disk bus, the preference is ignored.
```
NONE
```
=> tests: add ignore preference disk bus test

pkg/virt-operator/resource/generate/components/scc.go, pkg/virt-operator/resource/generate/components/scc_test.go
Fixes #
**Checklist**
```release-note
NONE
```
=> [release-1.0] SCC: Re-introduce CAP_SYS_PTRACE

pkg/virtctl/create/BUILD.bazel, pkg/virtctl/create/clone/BUILD.bazel, pkg/virtctl/create/clone/clone.go, pkg/virtctl/create/clone/clone_test.go, pkg/virtctl/create/create.go, pkg/virtctl/create/instancetype/BUILD.bazel, pkg/virtctl/create/instancetype/instancetype.go, pkg/virtctl/create/instancetype/instancetype_test.go, pkg/virtctl/create/preference/BUILD.bazel, pkg/virtctl/create/preference/preference.go, pkg/virtctl/create/preference/preference_test.go, pkg/virtctl/create/vm/BUILD.bazel, pkg/virtctl/create/vm/vm.go, pkg/virtctl/create/vm/vm_test.go, pkg/virtctl/root.go
With this PR virtctl applies the namespace passed with the
--namespace flag to the following created manifests:
- VirtualMachine
- VirtualMachinePreferences
- VirtualMachineInstancetype
- VirtualMachineClone
```release-note
virtctl: Apply namespace to created manifests
```
=> virtctl: Apply --namespace to created manifests

pkg/network/domainspec/domainspec_suite_test.go, pkg/network/domainspec/generators.go, pkg/network/domainspec/generators_test.go, pkg/network/setup/network.go, pkg/network/setup/podnic.go, pkg/virt-controller/services/net_binding.go, pkg/virt-controller/services/net_binding_test.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-launcher/virtwrap/converter/converter_test.go, pkg/virt-launcher/virtwrap/converter/network.go
This PR changes Kubevirt network setup logic to delegate Slirp networking configuration to sidecar 
using Slirp network binding plugin (introduced by #10272).
From the user perspective there is no change, configuring VM with Slirp remains.
Fixes #
In case no Slirp network binding plugin is registered (i.e.: spesified in Kubevirt config), the following default image will be used: 
`quay.io/kubevirt/network-slirp-binding:20230830_638c60fc8`
This is to reduce friction for users upgrading to the comming release (v1.1.0) in case no image is registered.
In the next …
=> Delegate Slirp network configuration to hook sidecar using Slirp network binding plugin

pkg/virtctl/imageupload/imageupload.go, pkg/virtctl/imageupload/imageupload_test.go, tests/storage/imageupload.go
This PR aims to fix virtctl image-upload so we allow DVs to recover from `PendingPopulation` phase, as we do with `WaitForFirstConsumer`.
This means that, if an image-upload command fails due to a DV being in `PendingPopulation` phase, we can call the command again after creating a consumer and the upload will continue as expected.
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2236060
We have two ways of fixing this, either in CDI by adding the missing annotations into the target PVC, or in virtctl by getting the PVC Prime and checking its annotations. We generally attempt to ignore populator logic outside CDI, but I think that adding the annotations into the target PVC is …
=> Allow image-upload to recover from PendingPopulation phase

docs/getting-started.md
The ginkgo flag -regexScansFilePath has been deprecated in favor of -focus-file[1]
[1] https://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed--regexscansfilepath
Fixes #
**Checklist**
```release-note
NONE
```
=> docs: Replace deprecated ginkgo regexScansFilePath flag with -focus-file

api/openapi-spec/swagger.json, manifests/generated/kv-resource.yaml, pkg/virt-launcher/virtwrap/api/BUILD.bazel, pkg/virt-launcher/virtwrap/api/schema_test.go, pkg/virt-launcher/virtwrap/api/testdata/cpu_pinning.xml, pkg/virt-launcher/virtwrap/api/testdata/domain_numa_topology.xml, pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go
This is minor/misc fixes.
To not create PR with single/trivial fixes, I put some of those in a side branch, to let it grow. 5 changes seems like okay to have a PR :)
* Yesterday found 2 more possible moves to go:embed under virtwrap/schema. Follow up of https://github.com/kubevirt/kubevirt/pull/10263
* The doc change is about removing duplication (probably a copy-paste error?)
* The converter refactor was related to some work I was doing with logs. I think it should be considered good practice to make code blocks that are architecture depended, just my opinion.
```release-note
NONE
```
=> misc fixes: go:embed (2), docs (1) and minor refactor

pkg/virt-operator/resource/generate/components/scc.go, pkg/virt-operator/resource/generate/components/scc_test.go
Fixes #
**Checklist**
```release-note
NONE
```
=> [release-0.59] SCC: Re-introduce CAP_SYS_PTRACE

tests/libnode/node.go, tests/libvmi/vmi.go, tests/migration/BUILD.bazel, tests/migration/eviction_strategy.go, tests/migration/migration.go
As a followup of https://github.com/kubevirt/kubevirt/pull/10362 we could start splitting the `tests/migration/migration.go` file into several smaller files.
Let's start with an easy one: **eviction strategy**.
Fixes #
**Checklist**
```release-note
NONE
```
/cc @dhiller @jean-edouard @xpivarc 
=> [e2e] Extract eviction strategy migration tests in their own file

pkg/storage/export/export/export_test.go, pkg/virt-controller/services/renderresources.go, pkg/virt-controller/services/template.go, staging/src/kubevirt.io/api/core/v1/types.go, tests/storage/export.go
Currently the VMExport pod won't start inside a namespace with a quota. It will also not work inside a namespace with a specific limit range ratio. This commit allows one to specify the requests and limits of the VMExport pod, and it adds some defaults so it will work inside a namespace with a quota.
Fixes # [RHBZ 2236422](https://bugzilla.redhat.com/show_bug.cgi?id=2236422) 
**Checklist** …
=> Allow setting of requests/limits on VMExport pod

tests/hotplug/cpu.go, tests/utils.go
We need to ensure we do not use the "source" node
to find the Pod which holds the domain.
Fixes #
**Checklist**
```release-note
NONE
```
=> Flaky test: Ensure VMI has updated migration status

tests/libnode/BUILD.bazel, tests/libnode/node.go
**What this PR does / why we need it**: This MR fixes semantic of `GetAllSchedulableNodes` by also filtering out the Nodes that are marked as unschedulable (`spec.unschedulable=true`).
Fixes #10413
**Checklist**
```release-note
NONE
```
=> Filter out Nodes which are marked as unschedulable in GetAllSchedulableNodes

pkg/virt-controller/watch/topology/filter.go, pkg/virt-controller/watch/topology/filter_test.go, pkg/virt-controller/watch/topology/hinter.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/10182 (which is a follow-up to https://github.com/kubevirt/kubevirt/pull/10169).
Fixes https://github.com/kubevirt/kubevirt/issues/10181
```release-note
Stop considering nodes without `kubevirt.io/schedulable` label when finding lowest TSC frequency on the cluster
```
=> [release-1.0] Stop considering nodes without `kubevirt.io/schedulable` label when finding lowest TSC frequency on the cluster

tests/storage/storage.go
This pull request aims to fix a test that's been consistently failing on k8s-1.26-sig-storage during these last days, as tested in https://github.com/kubevirt/kubevirt/pull/10449.
Introduces two fixes:
- Uses a fake storage class to force static provisioning. Using an existing SC was flaky behavior.
- Builds the name of the VM device with more precision, instead of relying on the disk name.
Fixes #
```release-note
NONE
```
=> Fix flaky test in k8s-1.26-sig-storage

pkg/virtctl/memorydump/memorydump.go, pkg/virtctl/memorydump/memorydump_test.go, pkg/virtctl/vmexport/vmexport.go, pkg/virtctl/vmexport/vmexport_test.go
This PR aims to add a new `--raw` flag in virtctl vmexport, so users can request downloading the raw image instead of the compressed one. It also adds a `--decompress` flag to download and decompress gzipped files.
**Usage example**:
```bash
{{ProgramName}} vmexport download vm1-export --volume=volume1 --output=disk.img --format=raw
```
Planning to add a flag to decompress the image if needed too.
```release-note
Add new vmexport flags to download raw images, either directly (--raw) or by decompressing (--decompress) them
```
=> Allow specifying download format in vmexport

tests/hotplug/cpu.go
The following test is causing 20% impact to the sig-compute-migrations e2e test lanes[1]:
`CPU Hotplug A VM with cpu.maxSockets set higher than cpu.sockets should successfully plug guaranteed vCPUs`
[1] https://search.ci.kubevirt.io/?search=CPU+Hotplug+A+VM+with+cpu.maxSockets+set+higher+than+cpu.sockets+should+successfully+plug+guaranteed+vCPUs&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
/cc @dhiller 
**Checklist**
This checklist is not enforcing, but it's a reminder of items that could …
=> Quarantine flaky cpu hotplug test in compute-migration lane

pkg/virtctl/create/vm/vm.go, tests/virtctl/create_vm.go
This PR contains small cleanups found during work on #10450 and #10463.
- Fix examples in create vm
- The values provided to the --volume-blank flag were saved into the wrong
slice.
- Make unmarshalVM in the functional tests more strict by asserting
APIVersion and Kind of the unmarshaled VM as it is done in the unit
tests of create vm already.
**Checklist**
```release-note
None
```
=> Small cleanups in virtctl

tests/libnode/BUILD.bazel, tests/libnode/node.go
There is logic in test suite relying on GetAllSchedulableNodes returning all "Kubevirt" schedulable nodes rather than Kubernetes and Kubevirt nodes. This logic needs to be checked before we can make this change.
Fixes #
**Checklist**
```release-note
NONE
```
=> Revert:  Filter out Nodes which are marked as unschedulable

pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/converter_test.go
When creating a VM with `liveFeatureUpdate: { cpu: {} }`, the enabled vCpu calculation is incorrect because the number of sockets, which can be more than 1 when creating a VM, is not taken into count.
**Which issue(s) this PR fixes**  #
Fixes #10462
**Checklist**
```release-note
```
=> virt-launcher: fix enabled cpu num

pkg/container-disk/container-disk.go, pkg/virt-controller/watch/application.go
The ephemeral directory for containerdisks needs to be known by virt-controller to create the right pod templates. By mistake the controller also tries to create the ephemeral directory.
By accident virt-controller also tries to create this directory in its own image without actually using it. If that fails (e.g. permission issues since untested and no functional difference) we get a warning which can lead to confusions.
Removing the code which tries for no reason to create the directory which look like this:
```
failed to create ephemeral disk dir: mkdir /var/run/kubevirt-ephemeral-disk
``` …
=> [virt-controller] Fix warning about ephemeral dir creation

tests/migration/migration.go
The test suite already takes care of that. Benefits:
- Cleaner tests
- Smaller migration.go
- Less code duplication
- Reduced flakiness
Fixes #
**Checklist**
```release-note
NONE
```
=> tests: migration: remove redundant VMI deletions

pkg/virt-launcher/virtwrap/manager.go
In order to calculate the proper key for host-devices, their fixed alias-prefix needs to be removed.
The removal was buggy in case the same alias-prefix was used in the original name of the device.
To resolve the issue, the alias-prefix of the relevant host-device is removed only from the name prefix (once).
fixes: https://github.com/kubevirt/kubevirt/issues/10401
Fixes #10401
This code is not covered by unit tests.
There is a need to refactor the code and cover it using unit tests (with a follow up PR).
**Checklist**
This checklist is not enforcing, but it's …
=> virt-launcher: Fix host-device metadata key calculation

tests/hotplug/cpu.go
Since https://github.com/kubevirt/kubevirt/pull/10476 is merged,
we can un-quarantine cpu hotplug test.
This reverts https://github.com/kubevirt/kubevirt/pull/10453
Fixes #
**Checklist**
```release-note
NONE
```
/cc @brianmcarey @xpivarc
=> Revert "Quarantine flaky cpu hotplug test in compute-migration lane"

pkg/storage/export/export/export_test.go, pkg/storage/export/export/pvc-source_test.go, pkg/storage/export/export/vm-source_test.go, pkg/storage/export/export/vmsnapshot-source_test.go, pkg/virt-config/feature-gates.go, pkg/virt-controller/services/renderresources.go, pkg/virt-controller/services/renderresources_test.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/application_test.go, pkg/virt-controller/watch/migration_test.go, pkg/virt-controller/watch/vmi_test.go, staging/src/kubevirt.io/api/core/v1/types.go, tests/testsuite/kubevirtresource.go, tests/vmi_configuration_test.go
When a ResourceQuota with memory limits set is associated to a namespace, if vm creators try to start a vm, the vmi remains is Pending state, due to missing memory limits.
In fact, a resource quota with memory limits requires every pod in that namespace to have memory limits set.
Currently, KubeVirt is not setting that limits for every vmi, but only for the vmi with dedicated CPU.
The virt-launcher overhead is hard to calculate, and it can vary depending on the vmi spec.
Several testing are ongoing to extract some values, but they require a lot of time.
This commit introduces an initial easy implementation to avoid the Pending state of the vmi.
This initial implementation consists in setting limits to the double of the memory requests.
This will …
=> Set memory limits if there is a resource quota with limits.

tests/hotplug/affinity.go
Hotplug affinity tests should be labelled by the proper label.
Fixes #
**Checklist**
```release-note
NONE
```
/cc @vladikr @xpivarc
=> e2e: Add VMLiveUpdateFeaturesGate label to hotplug affinity tests

api/openapi-spec/swagger.json, pkg/instancetype/instancetype.go, pkg/instancetype/instancetype_test.go, pkg/storage/export/export/export.go, pkg/testutils/mock_instancetype.go, pkg/virt-api/rest/expand.go, pkg/virt-api/rest/expand_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-controller/watch/vm.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/instancetype/v1alpha1/conversion_generated.go, staging/src/kubevirt.io/api/instancetype/v1alpha2/conversion_generated.go, staging/src/kubevirt.io/api/instancetype/v1beta1/deepcopy_generated.go, staging/src/kubevirt.io/api/instancetype/v1beta1/types.go, staging/src/kubevirt.io/api/instancetype/v1beta1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/instancetype_test.go
This PR adds preferred and required annotations to preferences and instance types. It also renames ApplyToVmi function to Apply.
```
None
```
=> Add required and preferred annotations

manifests/generated/operator-csv.yaml.in, manifests/generated/rbac-operator.authorization.k8s.yaml.in, pkg/virt-operator/resource/generate/rbac/controller.go
The virt-controller component only requires the `GET` RBAC permissions, thus, all others can be dropped.
Fixes #
**Checklist**
```release-note
Remove the network-attachment-definition `list` and `watch` verbs from virt-controller's RBAC
```
=> build, controller: remove list and watch verbs from RBAC

pkg/virt-controller/services/multus_annotations.go, pkg/virt-controller/services/multus_annotations_test.go, pkg/virt-controller/services/template_test.go, pkg/virt-controller/watch/vmi_test.go
When templating the launcher pod, use network selection elements struct (from the k8snetworkplumbingwg) instead of a locally defined struct.
Fixes #
**Checklist**
```release-note
NONE
```
=> pod template, network: use network-selection-elements structs

automation/repeated_test.sh, automation/test.sh, docs/quarantine.md, tests/decorators/decorators.go, tests/operator/operator.go
In https://github.com/kubevirt/kubevirt/pull/8881 we switch using label based filtering instead of
name based filtering.
We introduced several labels and adjusted the script to consume them.
The Quarantine process is still using name based filtering, and we want to align the two behaviors.
Fixes #
**Checklist**
```release-note
NONE
```
/cc @brianmcarey @dhiller
=> e2e: Introduce QUARANTINE label

pkg/virt-controller/services/BUILD.bazel, pkg/virt-controller/services/net_binding.go, pkg/virt-controller/services/net_binding_test.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-controller/watch/application.go, tests/network/BUILD.bazel, tests/network/vmi_networking.go
Raise verbosity of warning by rasing an event  in case no Slirp network binding plugin image is registered and Kubevirt use the default image.
Fixes #
It was necessary to pass the VMI event recorder to the template service.
Handling Slirp default image is moved from `ReadNetBindingPluginConfiguration` to the caller because an raising an event requires the VMI event recorder and the VMI objects.
**Checklist**
**Release …
=> Raise event in case using default Slirp binding plugin image 

tests/vmi_configuration_test.go
The `err` variable is not valued in the "they should be applied to the launcher pod"
test, but there is an expectation regarding it.
Since `err` is global var and never cleaned, this means that we are checking the err value of the previous test.
If the previous test is a negative test this can cause a failure, even if there is no failure.
i.e. if the previous test is "[test_id:3113]should failed to the VMI creation", which
expect that the creation of a vmi fail if there are no memory request, there will be a failure.
From https://onsi.github.io/ginkgo/#extracting-common-setup-beforeeach:
> Information is shared between closures via closure variables. It is idiomatic for these closure variables to be declared within the container node closure and …
=> e2e: Fix not cleaned global err variable causing flakyness

tests/decorators/decorators.go, tests/vmi_configuration_test.go
Label `AutoResourceLimits` tests
Fixes #
**Checklist**
```release-note
NONE
```
/cc @xpivarc
=> Add autoResourceLimit label decorator

pkg/storage/export/export/export_test.go, pkg/storage/export/export/pvc-source_test.go, pkg/storage/export/export/vm-source_test.go, pkg/storage/export/export/vmsnapshot-source_test.go, pkg/virt-config/feature-gates.go, pkg/virt-controller/services/renderresources.go, pkg/virt-controller/services/renderresources_test.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/application_test.go, pkg/virt-controller/watch/migration_test.go, pkg/virt-controller/watch/vmi_test.go, staging/src/kubevirt.io/api/core/v1/types.go, tests/decorators/decorators.go, tests/testsuite/kubevirtresource.go, tests/vmi_configuration_test.go
This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/10447 and https://github.com/kubevirt/kubevirt/pull/10497
Fixes #
**Checklist**
```release-note
Add a Feature Gate to KV CR to automatically set memory limits when a resource quota with memory limits is associated to the creation namespace
```
/cc @acardace @jean-edouard @vladikr @fabiand
=> [release-1.0] Set memory limits if there is a resource quota with limits

go.mod, go.sum, vendor/libvirt.org/go/libvirt/.gitlab-ci.yml, vendor/libvirt.org/go/libvirt/README.rst, vendor/libvirt.org/go/libvirt/domain.go, vendor/libvirt.org/go/libvirt/libvirt_generated_enums.h, vendor/libvirt.org/go/libvirt/libvirt_generated_macros.h, vendor/modules.txt
Update the libvirt Go bindings to match the C library, which was recently updated as part of https://github.com/kubevirt/kubevirt/pull/10050
```release-note
NONE
```
=> vendor: Update libvirt.org/go/libvirt

manifests/generated/operator-csv.yaml.in, manifests/generated/rbac-operator.authorization.k8s.yaml.in, pkg/virt-operator/kubevirt_test.go, pkg/virt-operator/resource/generate/rbac/cluster.go, tests/access_test.go, tests/testsuite/serviceaccount.go
This ClusterRole provides read only access to the cluster-scoped VirtualMachineCluster{Instancetype,Preference} resources within a cluster.
This is required as the existing aggregated kubevirt:view ClusterRole does not provide access to cluster-scoped resources when bound to a user using a RoleBinding.
As such we need a seperate ClusterRole to provide access to our cluster scoped resources that can be bound with a ClusterRoleBinding without providing access to all of the resources listed in the aggregated view ClusterRole.
Fixes #10437 …
=> rbac: Add instancetype.kubevirt.io:view ClusterRole

docs/metrics.md, hack/prom-rule-ci/prom-rules-tests.yaml, pkg/monitoring/domainstats/prometheus/prometheus.go, pkg/monitoring/migrationstats/collector.go, pkg/monitoring/migrationstats/collector_test.go, pkg/virt-operator/resource/generate/components/prometheus.go, tests/libmigration/migration.go, tests/monitoring/vm_monitoring.go
VMI Migration metrics names are inconsistent. Some of them have a `kubevirt_vmi_` prefix (as expected), and some `kubevirt_migrate` prefix. In addition, some of the migration metrics names don't represent properly what the metrics do. For example, `kubevirt_vmi_migrations_succeeded` metric is actually a boolean metric per VMI and migration, and thus this PR changes its name to `kubevirt_vmi_migration_succeeded` (same issue with `kubevirt_vmi_migrations_failed` metric). 
Fixes https://issues.redhat.com/browse/CNV-33042, https://bugzilla.redhat.com/show_bug.cgi?id=2239648
**Checklist** …
=> Rename VMI migration metrics

pkg/virt-operator/application.go, pkg/virt-operator/resource/generate/components/webhooks.go, pkg/virt-operator/webhooks/BUILD.bazel, pkg/virt-operator/webhooks/kubevirt-create-admitter.go, pkg/virt-operator/webhooks/kubevirt-create-admitter_test.go, tests/dryrun_test.go, tests/operator/operator.go
Fixes #
This is https://github.com/kubevirt/kubevirt/pull/10499 plus removing an e2e test that is now unnecessary.
**Checklist**
```release-note
NONE
```
=> Prevent creation of another Kubevirt

pkg/virt-operator/application.go, pkg/virt-operator/resource/generate/components/webhooks.go, pkg/virt-operator/webhooks/BUILD.bazel, pkg/virt-operator/webhooks/kubevirt-create-admitter.go, pkg/virt-operator/webhooks/kubevirt-create-admitter_test.go, tests/dryrun_test.go, tests/operator/operator.go
Signed-off-by: Luboslav Pivarc <lpivarc@redhat.com>
(cherry picked from commit 663fe0155ebc03655ed9f2253823fb698e8da16c)
Fixes #
**Checklist**
```release-note
NONE
```
=> [release-1.0] Prevent creation of another Kubevirt

pkg/container-disk/BUILD.bazel, pkg/container-disk/container-disk.go
Currently MTQ Operator is using GenerateContainers func to evaluate the target pod and figure out if it can release blocked migration, the current log result repeating logging which make it hard to debug.
Fixes #
**Checklist**
```release-note
NONE
```
=> Delete repeating log without value

pkg/instancetype/instancetype.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, tests/BUILD.bazel, tests/instancetype_test.go
This should really contain the field causing the conflict to avoid the reader having to look around further for this information.
Fixes #
**Checklist**
```release-note
NONE
```
=> instancetype: Improve admission conflict message

pkg/network/netbinding/BUILD.bazel, pkg/network/netbinding/netbinding.go, pkg/network/netbinding/netbinding_suite_test.go, pkg/network/netbinding/netbinding_test.go, pkg/virt-controller/services/BUILD.bazel, pkg/virt-controller/services/sidecar.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-controller/watch/BUILD.bazel, pkg/virt-controller/watch/application.go, tests/network/BUILD.bazel, tests/network/vmi_networking.go
Decouple the net binding sidecar spec definition logic from where it is called in the flow.
The separation assists with structuring the code, reducing complexity from the existing rendering function and simplifying dependencies.
The approach is aimed to assist in adding similar sidecar creators (not limited to network bindings).
Fixes #
**Checklist**
```release-note
NONE
```
=> virt-controller, net: Refactor netbinding sidecar compose

pkg/storage/snapshot/source.go, tests/BUILD.bazel, tests/clone_test.go, tests/storage/restore.go, tests/storage/snapshot.go, tests/utils.go
Recently a new logic was introduced to the snapshot controller which copies the VMI spec to the VM spec during snapshots. The logic was introduced [here](https://github.com/kubevirt/kubevirt/pull/6642/files#diff-7bc7197d1045e0af2ba9d29fdedb1195aadd5365362d00be0d709be10ee601f6R203-R212):
https://github.com/kubevirt/kubevirt/blob/866e725bb93a9cae87cc47c9496d8dfe6baafb8a/pkg/storage/snapshot/source.go#L271-L280
Copying the VMI spec to the VM spec is a bug. Kubevirt is designed around the principle in which the VM is a user-facing object, while the VMI is an internal object. For example, while the VM spec specifies the user's desired state, the VMI is being expanded with default values and is being patched and updated by Kubevirt's controllers.
For …
=> Stop copying VMI spec to VM during snapshots

tests/network/macvtap.go, tests/network/vmi_istio.go, tests/utils.go
tests/utils.go is way too long and too many things depend on it. Let's have one less.
```release-note
NONE
```
=> tests: avoid a global constant

pkg/virtctl/imageupload/imageupload.go, pkg/virtctl/imageupload/imageupload_test.go
We had to adjust some of the image-upload behavior with the addition of populators and the PVC Prime logic. This PR improves the handling of a specific error case to better report the status of the PVC.
When searching for the PVC Prime name annotation, if there's a pod succeeded annotation in the target PVC, we can safely assume it was successfully populated, so now we return a `PVC already successfully populated` message instead of the previous, more generic `Unable to get PVC Prime name`.
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2241658
**Release …
=> Improve error handling when attempting to upload an already succeeded DataVolume

tests/console/login.go
This PR workarounds
```
{ Failure tests/infrastructure/downward-metrics.go:49
Expected success, but got an error:
<*errors.errorString | 0xc004f1e2f0>: 
send to spawned process command reached the timeout 9.970984101s
{
s: "send to spawned process command reached the timeout 9.970984101s",
}
tests/infrastructure/downward-metrics.go:53}
```
Fixes #
**Checklist**
```release-note
NONE
```
=> CI: Workaround Fedora login issue

pkg/virtctl/imageupload/imageupload.go, pkg/virtctl/imageupload/imageupload_test.go
This Pull Request aims to introduce a `volume-mode` flag to allow specifying either filesystem or block volume modes in image-upload.
This behavior also marks the old `block-volume` flag as deprecated, which only allows specifying block mode.
Fixes #
Unsure about the consequences of marking `block-volume` as deprecated. The flag is still usable and feels redundant since the new one allows both volume modes, but feel free to argue otherwise.
```release-note
Add --volume-mode flag in image-upload
```
=> Add --volume-mode flag in image-upload to allow specifying volume mode

cmd/virt-launcher/virt-launcher.go, pkg/virt-launcher/monitor.go
libvirt initializes the log file for the
serial console device as owned by its user
and with 600 permissions.
So when executing in rootful mode (deprecated)
virt-tail, running rootless by design, is not
able to read it.
Fix pre-creating the log file with the
expected ownership when in rootful mode.
Fixes: https://issues.redhat.com/browse/CNV-33763
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2242849
It can be reproduced only in rootful mode, rootful CI lanes are not executed by default as part of pre-submit jobs
**Checklist** …
=> [guest-console-log] initialize log file if rootful

cmd/virt-operator/BUILD.bazel
virt-operator would write current version to `status.operatorVersion` of `KubeVirt` CR. but in current build rule, stamp is missing.
Fixes #
```release-note
fix embed version info of virt-operator
```
=> fix stamp for virt-operator

pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/network.go
In case a VM requires virtio network, when at least one interface model is set to virtio explicitly or empty (implicitly), virt-controller template code will add mount /dev/vhost-net to virt-launcher pod.
The virt-launcher converter code (VM spec to domain XML) checks if /dev/vhost-net exist, if not and Kubevirt is not set to allow software emulation, it will fail syncVMI routine and cause re-enqueues.
In Kubernetes, if a pod spec specifies a resource that doesn't exist the pod hang on scheduling phase and wont start.
In our case, when '/dev/vhost-net' is not present in any node virt-launcher pod wont start.
Failing in case a VM has virito interface(s) but '/dev/vhost-net' is not present is redundant, because when virt-launcher converter code runs …
=> virt-launcher, converter: Remove redundent check for '/dev/vhost-net' presense

api/openapi-spec/swagger.json, manifests/generated/kv-resource.yaml, pkg/virt-handler/device-manager/usb_device.go, pkg/virt-handler/device-manager/usb_device_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/usb/usb.go
This is a follow up from https://github.com/kubevirt/kubevirt/pull/10015
It does minor fixes suggested by @xpivarc and adds support to `external resource provider`, similar to PCI and Mediated devices.
**Checklist**
```release-note
NONE
```
=> Add external resource provider to USB Host Pass through device

pkg/network/setup/netpod/netpod.go
On bridge binding the pod interface name is renamed. The code allows to setup the same interface multiple times (for example we can try to hotplug an interface that is already hotplugged, but the VMI status is not updated yet).
In bridge binding setup we need to take care of the scenario the network is already configured on the pod and the pod interface name was already changed.
Fixes #
**Checklist** …
=> multiple bridge interfaces hotplug bug fix

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
Remove unused `nonroot` parameter from `validateRealtime()`.
Fixes #
**Checklist**
```release-note
NONE
```
=> VMI Create admitter: Remove unused `nonroot` param

hack/builder/arch.sh, hack/builder/build.sh, hack/builder/common.sh, hack/builder/publish.sh, hack/dockerized
**What this PR does / why we need it**: This MR allows to build custom builder image easily by configuring `DOCKER_PREFIX` and `DOCKER_IMAGE` (as well as `KUBEVIRT_BUILDER_IMAGE`) env variables instead of using hardcoded `quay.io/kubevirt/builder`. Also in the future it will be much easier to destination (either registry or image) whenever needed.
**Special notes for your reviewer**: Note that by default we will be still using `quay.io/kubevirt/builder` so nothing changes here.
**Checklist** …
=> Make builder image and registry name configurable

pkg/instancetype/instancetype.go, pkg/testutils/mock_instancetype.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go, tests/instancetype_test.go
With this change the guest memory of VMs is cleared when inference of an instancetype was successful and the IgnoreInferFromVolumeFailure policy was set in the instancetype matcher. This allows to enable inference of instancetypes in virtctl by default without breaking the previous behavior by allowing virtctl to provide a fallback amount of memory to be used when inference fails.
Fixes #
Required to keep previous behavior before #10450 and #10463 were introduced.
**Checklist** …
=> instancetypes: Clear VM guest memory when ignoring inference failures

api/openapi-spec/swagger.json, manifests/generated/kv-resource.yaml, pkg/network/netbinding/netbinding.go, pkg/virt-controller/services/BUILD.bazel, pkg/virt-controller/services/multus_annotations.go, pkg/virt-controller/services/multus_annotations_test.go, pkg/virt-controller/services/template.go, pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go
This PR implement the Network binding plugin API's Pod Creation & Definition integration point  [[1]](https://docs.google.com/document/d/13fLaqZuM8El_CT5XzxPv-1epKsB1-Spv_jtXveEkkdQ#heading=h.qcw5usdbc0nx), enable invoking CNIs  to configure virt-launcher pod network namespace.
How it works:
Similar to secondary networks, the binding plugin CNI is invoked by Multus, its necessary to define a `NetworkAttachmentDefiniton` for the bidning plugin.
Kubevirt will add the requested binding plugin `NetworkAttachmentDefiniton` to virt-launcher pod's Multus network selection annotation.
When the pod is created, its CNI chain will be invoked including the required binding plugin CNI.
How to use:
Given a network binding plugin 'dummy' that require invoking CNI. …
=> Network plugin binding API: Support CNI plugins

pkg/virtctl/create/vm/vm.go, pkg/virtctl/create/vm/vm_test.go, tests/virtctl/create_vm.go
To keep previous behavior before inference of instancetypes by default
was enabled the guest memory is not cleared when implicitly inferring
instancetypes.
Based on #10543, merge after
**Checklist**
```release-note
None
```
=> virtctl: Do not clear memory when implicitly inferring instancetype 

pkg/instancetype/instancetype.go, pkg/instancetype/instancetype_test.go, staging/src/kubevirt.io/api/instancetype/v1beta1/types.go, tests/instancetype_test.go
This commit adds PreferAny option to CPU preferences that should allow a user to accept any topology when there are required number of vCPUs provided.
**Checklist**
```
None
```
=> Add PreferAny option to CPU preferences

pkg/virt-controller/services/BUILD.bazel, pkg/virt-controller/services/renderresources.go, pkg/virt-controller/services/renderresources_test.go
Preliminary tests showed that the virt-overhead is underestimated by 100Mi. For guaranteed vmi this means that the limits we set are too stringent.
Also, add the full unit test coverage of the `getMemoryOverhead` function.
Fixes #
**Checklist**
```release-note
NONE
```
/cc @xpivarc
=> Add 100Mi of overhead for guaranteed vmis

pkg/virt-controller/services/BUILD.bazel, pkg/virt-controller/services/renderresources.go, pkg/virt-controller/services/renderresources_test.go
This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/10566
Fixes #
**Checklist**
```release-note
Add 100Mi of memory overhead for vmi with dedicatedCPU or that wants GuaranteedQos
```
=> [release-0.59] Add 100Mi of overhead for guaranteed vmis

cmd/virt-exportproxy/virt-exportproxy.go, cmd/virt-handler/virt-handler.go, pkg/storage/export/virt-exportserver/exportserver.go, pkg/virt-api/api.go, pkg/virt-controller/watch/application.go, pkg/virt-operator/application.go
Recommended remediation for CVE-2023-39325 CVE-2023-44487
Fixes #
**Checklist**
```release-note
Disable HTTP/2 to mitigate CVE-2023-44487
```
=> Disable HTTP/2

cmd/virt-launcher-monitor/virt-launcher-monitor.go
Fix virt-launcher monitor dump-log-file code to not log file not found errors.
Fixes #
**Checklist**
```release-note
NONE
```
=> virt-launcher monitor, dumpLogFile: Dont log file-not-found errors

pkg/virt-api/webhooks/fuzz/fuzz_test.go, pkg/virt-config/feature-gates.go
The NonRootExperimental feature gate was deprecated in PR #8563.
The presence or absence of this feature gate does not change KubeVirt's behavior.
Fixes #
**Checklist**
```release-note
Remove leftover NonRootExperimental feature gate
```
=> Remove leftover NonRootExperimental feature gate

pkg/virt-controller/services/multus_annotations.go, pkg/virt-controller/services/multus_annotations_test.go
This PR fixes the network binding plugin API's logic network name CNI arg.
CNI args should be in camel case form.
Fixes #
**Checklist**
```release-note
NONE
```
=> network binding plugin API: Fix logic network name CNI arg format

automation/test.sh
Basically following up on 2 commits:
https://github.com/kubevirt/kubevirt/pull/7194/commits/5a630968c4a6dcff841074d92688a2cff8015813 https://github.com/kubevirt/kubevirt/pull/8242/commits/fa52935ce06a4c1f8d9daa12e6f4c1f049c7a924
I believe we did not intend for sig-compute tests to be run on sig-storage and vice-versa (this direction was handled in 8242), so let's stop doing that. storage-req tests that are under other sigs will continue running.
Fixes #
```release-note
NONE
```
=> [e2e-tests]: Don't run all storage-req tests in sig-storage jobs

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/converter_test.go, pkg/virtctl/vm/add_volume.go, pkg/virtctl/vm/add_volume_test.go, tests/storage/hotplug.go
This PR aims to allow LUN disks to be hotplugged, instead of simply allowing regular Disk types.
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2211266
```release-note
Allow LUN disks to be hotplugged
```
=> Allow LUN disks to be hotplugged

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, tests/vm_test.go
This PR deals with issues faced when a user tries to force delete a running VM directly (in this case, if the VMI is stuck in `Terminating` and block the VMI and VM both from being deleted) using `kubectl delete vm [vmName] --force --grace-period=0`, the VM continues to be stuck and the VMI and VM don't get deleted until the VMI's `Spec.TerminationGracePeriodSeconds` expires. This becomes an issues for VMs that have high termination grace periods (for example, Windows VM templates in [kubevirt/common-templates](https://github.com/kubevirt/common-templates/blob/master/templates/windows11.tpl.yaml) by default have a termination grace period of 3600 seconds), when the user expects the VM to be deleted immediately when using a force deletion.
When force stopping a VM using `virtctl stop …
=> virt-controller set TerminationGracePeriod of VMI to DeletionGracePeriod of VM when deleting VM with kubectl

tests/hotplug/cpu.go, tests/utils.go
It should be more reliable to check domain xml once migration is done.
Currently, we see that the wrong Pod is picked for domain xml. There is more work to fix this behavior.
Fixes #
**Checklist**
```release-note
NONE
```
=> Improve cpu hotplug test

pkg/virt-handler/heartbeat/ksm.go, pkg/virt-handler/heartbeat/ksm_test.go, tests/infrastructure/virt-handler.go
$subject
Fixes #
**Checklist**
```release-note
NONE
```
=> ksm: fix bug on checking annotation value and move 2 functional tests to unit tests

tests/migration/eviction_strategy.go
The `setSchedulable` and `setUnschedulable` functions are called in the reverse way.
Fixes #
credits: @akalenyu 
Thanks for discovering this!
**Checklist**
```release-note
NONE
```
=> [e2e] Fix flipped set control plane node schedulability

pkg/virt-handler/migration.go
The network-status downward API file can take some time to get populated, and since virt-handler reads it just once on startup, the dedicated migration network can get ignored.
This is only a problem in k8s 1.27+.
This PR is a workaround, for 1.1 only (unless we decide to backport it). We are working on a proper fix in main, but it is taking longer than expected due to a potential bug in virt-operator.
Fixes the "falky" dedicated migration test (the code is flaky, not the test)
- The proper fix in main is https://github.com/kubevirt/kubevirt/pull/10600
- On …
=> [release-1.1] virt-handler: wait up to 2 seconds for the network-status downwardAPI to appear

pkg/virtctl/imageupload/imageupload.go, pkg/virtctl/imageupload/imageupload_test.go
This pull request aims to act as a minor correction/follow-up for this PR: https://github.com/kubevirt/kubevirt/pull/10534.
Instead of checking both the pod phase and the pvcPrime annotation, it's more straightforward to check the target PVC phase: When using populators, a bound target PVC will always mean that the population has succeeded. This will help us address some corner cases in https://bugzilla.redhat.com/show_bug.cgi?id=2241658.
Fixes # Partial fix of https://bugzilla.redhat.com/show_bug.cgi?id=2241658
```release-note
NONE
```
=> Improve image-upload condition to know if population succeeded

pkg/network/domainspec/domainspec_suite_test.go, pkg/network/domainspec/generators.go, pkg/network/domainspec/generators_test.go, pkg/network/setup/netpod/discover.go, pkg/network/setup/netpod/netpod.go, pkg/network/setup/netpod/netpod_test.go, pkg/network/setup/podnic.go, tests/network/vmi_multus.go
Masquerade, bridge and macvtap bindings are using a tap to connect to the guest.
The domain interface of all those bindings is very similar and therefore the domain interface generation was refactored to one general tap generator instead of three separate generators.
Besides the fact it made the code shorter and nicer, in a follow-up PR this tap generator will be used by the binding plugin for plugins that will use `tap` `domain-attachment`.
Changes that had to be done so it will be possible to use the general tap generator:
- bridge binding
-  store the original pod interface MAC on the dummy interface
- read the MAC and the MTU for the domain attachment from the dummy interface
- masquerade binding
-  in case there is no MAC address on the spec …
=> Tap generator

tests/reporter/kubernetes.go, tests/tests_suite_test.go
After all tests finished and all teardown fixtures executed, report
the state of the cluster.
This is useful for cases where all tests pass but the suite fails, due
to one of its teardown cleanups (e.g. waiting for all test namespaces to
be deleted).
Fixes #
**Checklist**
```release-note
NONE
```
=> tests, reporter: If the suite fails, execute the reporter

pkg/network/driver/common.go, pkg/network/driver/nmstate/spec.go
correct some log messages in  in pkg/network/driver/ 
Fixes #
**Checklist**
```release-note
```
=> correct log message in pkg/network/driver/

tests/infrastructure/tls-configuration.go
This test has caused ~20% impact to the sig-compute lanes over the past 2 days[1] and is top of the most recent flakefinder report[2] so it should be quarantined.
[1] https://search.ci.kubevirt.io/?search=test_id%3A9306&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
[2] https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2023-11-07-024h.html#row0
Fixes #
**Checklist**
This checklist is not enforcing, but it's a reminder of items that …
=> Quarantine flaky client side tls configuration test

docs/metrics.md, pkg/monitoring/domainstats/prometheus/prometheus.go, pkg/monitoring/domainstats/prometheus/prometheus_test.go, pkg/virt-launcher/virtwrap/stats/types.go, pkg/virt-launcher/virtwrap/statsconv/converter.go, pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go, tests/libmigration/migration.go, tools/doc-generator/doc-generator.go
As reported in https://bugzilla.redhat.com/show_bug.cgi?id=2117186
qemu blockjobs no longer report the actual bandwidth used.
This PR removes the related metric
Fixes #
**Checklist**
```release-note
Remove MigrateVmiDiskTransferRateMetric
```
/cc @enp0s3 @sradco
=> Remove MigrateVmiDiskTransferRateMetric

pkg/virt-handler/BUILD.bazel, pkg/virt-handler/cgroup/BUILD.bazel, pkg/virt-handler/cgroup/cgroup.go, pkg/virt-handler/cgroup/cgroup_test.go, pkg/virt-handler/cgroup/cgroup_v2_manager.go, pkg/virt-handler/cgroup/util.go, pkg/virt-handler/hotplug-disk/generated_mock_mount.go, pkg/virt-handler/hotplug-disk/mount.go, pkg/virt-handler/hotplug-disk/mount_test.go, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go, tests/storage/hotplug.go
This is just a resurrection of https://github.com/kubevirt/kubevirt/pull/8865 that unites the tests commits and adds some new ones.
Credit goes to @vasiliy-ul, @awels, @iholder101 
When a block volume is non-hotpluggable (i.e. it is specified explicitly in the VMI spec), the device cgroup permissions are managed purely by Kubernetes and CRI. For v2, a BPF program is assigned to the pod's cgroup.
However, today, when we attach hotplug volumes, we overwrite the BPF program to allow access to the new block device
since there is no way to append a single device to the allow list (https://github.com/opencontainers/runc/issues/3196).
With the current path, we also "forget" to populate the new allow list with the existing non hotpluggable disks.
This …
=> cgroupsv2: reconstruct device allowlist/drop internal device allow list state

pkg/virt-launcher/virtwrap/util/libvirt_helper.go
The qemu log path is now under /var/run/kubevirt-private/libvirt/qemu instead of /var/run/libvirt/qemu. This change adapt the virt-launcher code to that
Fixes #https://issues.redhat.com/browse/CNV-34884
**Checklist**
```release-note
virt-launcher: fix qemu non root log path
```
=> virt-launcher: fix qemu non root log path

pkg/virt-controller/watch/migration.go
**What this PR does / why we need it**: This PR cleans up two very long functions, `sync` and `updateStatus` in virt-controller `migration.go`, extracting code snippets in placing them into separate functions.
Fixes #
**Checklist**
```release-note
NONE
```
=> Clean up long functions in virt-controller migration.go

tests/reporter/kubernetes.go
The tests reporter raises errors regarding passt log recording failures:
```
19:49:03:   failed to execute command [[ -f /var/run/kubevirt/passt.log ] && cat /var/run/kubevirt/passt.log] on virt-launcher-testvmi-m2mf5-f5vz6, stdout: , stderr: [: missing ']'
19:49:03:   , error: command terminated with exit code 2
```
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/10432/pull-kubevirt-e2e-k8s-1.26-sig-compute/1715448253694087168#1:build-log.txt%3A3394
Since passt log recording command include the follwoing terms `[ .. ] && .. ) ` and
not running in a shell, the command is not interpreted correctly and fails.
Fix the the reporter passt logging by executing commands in pod using a shell.
To avoid creating empty log …
=> test reporter: Fix passt log recording

pkg/virt-controller/watch/migration_test.go, pkg/virt-handler/retry_manager_test.go
Some unit tests require some time alignment
to test the right behavior.
This could cause some failures if there isn't
a reasonable tolerance on the margin of error.
Let's reduce the flakiness, increasing the
tolerance.
Fixes https://github.com/kubevirt/kubevirt/issues/10670
- Retry manager flakyness:
https://search.ci.kubevirt.io/?search=Should+do+exponential+backoff+on+failure+retries&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=%5Epull-kubevirt-unit-test%24&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
- Migration test flakyness: …
=> test: tweak some time based test values

pkg/hooks/hooks.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go
Use a PVC for storing and sharing files between the compute and the sidecar containers.
This PR adds the possibility of using a PVC with the KubeVirt hook sidecar and the compute container. 
One usage of this enhancement is for debugging purposes and a full guide with a demo is available [here](https://github.com/alicefr/kubevirt-debug/tree/main/launch-qemu-strace). This option allows to supply of additional debug tools without the need to rebuild the virt-launcher image and explain how to launch QEMU with a debug tool like strace.
A concrete example of when this can be useful is when QEMU faces some permission issues, like in [this case](https://github.com/kubevirt/kubevirt/pull/9668#issuecomment-1630331947). For those types of failures, starting …
=> hook: add PVC option

pkg/hotplug-disk/hotplug-disk.go, pkg/hotplug-disk/hotplug-disk_test.go, pkg/virt-handler/BUILD.bazel, pkg/virt-handler/cgroup/BUILD.bazel, pkg/virt-handler/cgroup/cgroup.go, pkg/virt-handler/cgroup/cgroup_test.go, pkg/virt-handler/cgroup/cgroup_v2_manager.go, pkg/virt-handler/cgroup/util.go, pkg/virt-handler/hotplug-disk/generated_mock_mount.go, pkg/virt-handler/hotplug-disk/mount.go, pkg/virt-handler/hotplug-disk/mount_test.go, pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go, tests/storage/hotplug.go
Manual cherrypick of https://github.com/kubevirt/kubevirt/pull/10689.
Include cleanup from https://github.com/kubevirt/kubevirt/pull/10216 as well.
Fixes #
**Checklist**
```release-note
BugFix: cgroupsv2 device allowlist is bound to virt-handler internal state/block disk device overwritten on hotplug
```
=> [release-1.0] cgroupsv2: reconstruct device allowlist/drop internal device allow list state

tests/migration_test.go
Manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/10455
```release-note
NONE
```
=> [release-1.0] tests: migration: remove redundant VMI deletions

cmd/virt-handler/virt-handler.go, go.mod, pkg/virt-handler/BUILD.bazel, pkg/virt-handler/migration.go, pkg/virt-handler/migration_test.go, pkg/virt-handler/vm.go, pkg/virt-operator/resource/generate/components/daemonsets.go, staging/src/kubevirt.io/api/core/v1/types.go
Starting with k8s 1.27, the downwardAPI network status file can take a few seconds to get populated in the pod.
Before that, the file exists but it's empty.
Since virt-handler reads it on startup, it can sometimes be empty.
Fixes `Flaky "dedicated migration" test`
**Checklist**
```release-note
NONE
```
=> virt-handler: check for dedication migration interface instead of relying on an annotation

pkg/virt-controller/services/renderresources.go, pkg/virt-controller/services/renderresources_test.go, pkg/virt-controller/services/template_test.go
As a quick fix we modified the requests and limit ratio to be 1. However this is not ideal since it reserves a lot of cpu and memory for that container that doesn't really do anything at all. Its purpose is to attach a volume to the node.
We added the ability to set the requests and limits for all the supporting containers in (#9422). At this point anyone can set the ratio to what they want. So lets restore the defaults to the original values, so that people that don't care don't end up using a lot of memory for no reason.
Fixes #
**Checklist**
This checklist …
=> Restore default hotplug attachment pod request to original values

tests/clone_test.go
https://search.ci.kubevirt.io/?search=AfterSuite&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=pull-kubevirt.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
**Checklist**
```release-note
NONE
```
=> Quarantine test that triggers AfterSuite ns deletion failure

api/openapi-spec/swagger.json, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-launcher/virtwrap/api/schema.go, pkg/virt-launcher/virtwrap/converter/BUILD.bazel, pkg/virt-launcher/virtwrap/converter/converter.go, pkg/virt-launcher/virtwrap/converter/converter_test.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go, staging/src/kubevirt.io/api/core/v1/schema.go, staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/storage/BUILD.bazel, tests/storage/storage.go, tests/utils.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/10058
For correctly deploying Windows Shared Cluster Filesystem, we need to be able to configure the error policy to `report`.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2249846
```release-note
Add field errorPolicy for disks
```
=> [release-1.0] Manual cherry-pick of 10058

tests/guestlog/guestlog.go
In case the log contains `\r\n` sequence, replace it with just `\n` to allow matching against patterns with Linux-style newlines.
Fixes #
I checked the tests with `make cluster-up` and indeed, the resulting logs contain `\r\n`. However, on my Linux environment, some of the tests fail when matching against `\r\n` pattern due to `\n` newlines in the returned output. Apparently, the newlines somehow depend on the environment (though seeing `\r\n` on Linux seems weird). Anyway, the patch modifies the tests to support both variants.
**Checklist** …
=> [guest-console-log] tests: Normalize newlines in guest console log

pkg/virt-controller/watch/topology/nodetopologyupdater.go
Over time, virt-controller logs are getting filled with TSC update logs telling you everything went fine and nothing got updated.
This PR adds a condition to only print the line when something changed (or didn't go well).
Fixes #
**Checklist**
```release-note
NONE
```
=> virt-controller: tsc loop: log only when something happened

tests/infrastructure/prometheus.go
This test was marked as pending and flaky over three years ago[1] - from
a number of  local runs the test seems to be stable enough. Removing the
Pending flag from the test.
If it flakes again this should be removed as it was not missed for the
last number of years.
[1] https://github.com/kubevirt/kubevirt/commit/b01540f71f2c08857ad28c221603c076fa44000e
Fixes #
**Checklist**
- ~[ ] Design: A [design …
=> Remove Pending flag from test to find leading virt-controller

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-config/feature-gates.go, pkg/virt-controller/services/renderresources.go, pkg/virt-controller/services/renderresources_test.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, staging/src/kubevirt.io/api/core/v1/types.go
This PR add an annotation related to the `isolateEmulatorThread` feature, in order to avoid getting SMT alignment error by kubelet on the virt-launcher pod:
```
SMT Alignment Error: requested 9 cpus not multiple cpus per core = 2
```
The conditions needed in order to get this error:
- The node has hyperthreading (SMT) enabled.
- Kubelet’s CPUManager is set to static - full-pcpus-only.
- Kubevirt CR's defaultRuntimeClass is set to a high performance runtimeClass.
- VM is set with dedicatedCPUPlacement and IsolateEmulatorThread enabled.
- VM requests an even number of CPUs.
The meaning of this is that instead of IsolateEmulatorThread adding an extra CPU to the virt-launcher pod, it will add two CPUs when needed in order to get a total number of even …
=> isolateEmulatorThread: Add full-pcpu-only support

pkg/virtctl/BUILD.bazel, pkg/virtctl/adm/BUILD.bazel, pkg/virtctl/adm/adm.go, pkg/virtctl/adm/logverbosity/BUILD.bazel, pkg/virtctl/adm/logverbosity/logverbosity.go, pkg/virtctl/adm/logverbosity/logverbosity_suite_test.go, pkg/virtctl/adm/logverbosity/logverbosity_test.go, pkg/virtctl/root.go
Add `adm` subcommand under `virtctl`, and `log-verbosity` subcommand under `adm`.
`virtctl adm log-verbosity [flags]`
The `log-verbosity` command is:
- To show the log verbosity of one or more components (when the log verbosity is unattended in the KubeVirt CR, show the default verbosity)
- To set the log verbosity of one or more components
- To reset the log verbosity of all components (empty the log verbosity field, which means reset to the default verbosity)
Note:
- The components are `<virt-api | virt-controller | virt-handler | virt-launcher | virt-operator>`
- `Show` and `Set`/`Reset` cannot coexist
- The verbosity value must be `0-9`. The default cluster config is normally `2`.
- The verbosity value `10` is accepted but the operation is …
=> virtctl: adm and logverbosity command initial commit

pkg/host-disk/host-disk.go, pkg/host-disk/host-disk_test.go
/cc @xpivarc 
This is a follow up to #9810 where we started to limit the capacity of a HostDisk to the request storage resource size if smaller than the capacity storage resource size.
Both the requests and capacity are actually optional attributes of the PersistentVolumeClaimInfo[1] object used to pass them into this code. As such this change introduces some additional checks to ensure they are present before attempting to populate the capacity of the HostDisk.
[1] https://github.com/kubevirt/kubevirt/blob/0f4cbbf0cf273c7014a16d5e09fb3d3dee77444a/staging/src/kubevirt.io/api/core/v1/types.go#L298-L304 …
=> host-disk: Check existence of capacity and request storage resource

cmd/virt-launcher/virt-launcher.go
Currently, the `virtShareDir` parameter is unused, thus it could be removed.
Fixes #
**Checklist**
```release-note
None
```
=> launcher, startDomainEventMonitoring: rm param

api/openapi-spec/swagger.json, pkg/rest/mime.go, pkg/virt-api/BUILD.bazel, pkg/virt-api/api.go, pkg/virt-api/definitions/definitions.go, pkg/virt-api/rest/authorizer.go
Due to non conformant OpenAPI definition, [ZAP](https://www.zaproxy.org/) scanner aborts when trying to discover the KubeVirt subresources API.
This patch series fixes the issues reported by ZAP so that the security scan can proceed.
Fixes https://issues.redhat.com/browse/CNV-34685
**Checklist**
```release-note
NONE
```
=> Improve conformance of subresources.kubvirt.io openapi spec

tests/network/hotplug_bridge.go
Restarting the VM after the interfaces in the spec are gone is redundant. The VM will obviously be re-created based on the new spec.
Fixes #
**Checklist**
```release-note
NONE
```
=> tests, network, hot-unplug: Drop the VM restart step

pkg/network/setup/netstat.go, pkg/network/setup/netstat_test.go, tests/network/primary_pod_network.go, tests/network/vmi_infosource.go
Up until this change, for interfaces that used masquerade-like binding, the guest-agent data has not overridden the pod IPs. But it did override any pod information for other bindings (e.g. bridge).
In order to generalize the logic and avoid the dependency on specific bindings, the following logic is now used:
- VMI interface status will reflect the pod IPs unless GA data for the specific interface is showing no IP (i.e. the guest has no IP set).
- In case GA reports no IP, it will clear any IP from the interface status. The logic behind this is: If there is no IP in the guest, the VM is not reachable and therefore we can reflect that through the VMI interface status by not reporting the IP.
- In case there is no IP data from the pod, GA IP data …
=> net, netstat: Prioritize pod IP info over GA data

pkg/virt-handler/vm.go, pkg/virt-launcher/virtwrap/converter/BUILD.bazel, pkg/virt-launcher/virtwrap/converter/converter_test.go, pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go, pkg/virt-launcher/virtwrap/manager.go
This PR updates the Housekeeping cgroup to support multiple CPUs.
When setting the VM to full-pcpu-only, it is possible to get a full core - containing multiple CPUs - to the emulator thread [0].
This PR assigns these CPUs to the Housekeeping cgroup, so that they can be used on the emulatorThread processes. 
Note: this PR implements the second phase of the https://github.com/kubevirt/community/pull/247.
[0] https://github.com/kubevirt/kubevirt/pull/10593
**Checklist** …
=> Housekeeping cgroup: Add full-pcpu-only support

pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, tests/network/hotplug_bridge.go
If the calculated multus annotation is identical to the existing, there
is no need to execute a patch on the VMI object.
This change also resolves a bug that occurs when unplugging the last
secondary network.
Before this fix, when the last network got unplugged, no secondary
network got left, therefore there was no multus annotation generated.
And this led to not patching the VMI object, although it should have.
The relevant e2e test has been updated to cover the last unplug interface.
Fixes #
The problem has been detected with an initial fix on …
=> virt-controller, vmi: Update the multus annotation only if it changed and fix an unplug bug

tests/libvmi/README.md
In order to try and keep the libvmi package clean and simple, a detailed rule-set is defined.
Maintainers which approve changes to this package are requested to follow these rules and keep things organized, focused and clean.
Fixes #
Unfortunately, the existing state of libvmi is already out of sync with these rules.
An effort will be made to clean things up and fine-tune the rules if needed.
**Checklist**
**Release …
=> tests, libvmi: Add README with reasoning and rules

pkg/virt-handler/device-manager/usb_device.go, pkg/virt-launcher/virtwrap/api/schema.go, pkg/virt-launcher/virtwrap/device/hostdevice/hostdev.go, tests/usb/BUILD.bazel, tests/usb/usb.go
The device plugin for USB host pass though is not properly configuring device permissions prior to allocate the USB device to VMI. This PR fixes it.
Fixes #10727 
The fix is a one liner, by prefixing the path with `/proc/1/root`
I've added an extra check to the functional test to verify the emulated USB device has the right permission _after_ the VMI is created.
**Checklist**
```release-note
Fixes …
```
=> Fix host usb permissions

pkg/virt-controller/services/multus_annotations.go, pkg/virt-handler/non-root.go, pkg/virt-handler/vm.go, tests/network/bindingplugin.go
This PR allows using macvtap binding as a plugin.
Those are the extra steps that need to be done to run a VM with a macvtap plugin binding interface (the rest is similar to the old API usage).
**Enable network binding plugin feature-gate in the KV CR**
```
kubectl patch kubevirts -n kubevirt kubevirt --type=json -p='[{"op": "add", "path": "/spec/configuration/developerConfiguration/featureGates/-",   "value": "NetworkBindingPlugins"}]'
```
**Register the macvtap binding plugin in the KV CR**
note: use the name of the network-attachment-definition defined earlier.
```
kubectl patch kubevirts -n kubevirt kubevirt --type=json -p='[{"op": "add", "path": "/spec/configuration/network",   "value": {
"binding": {
"macvtap": {
domainAttachmentType: tap,
}
} …
```
=> Macvtap binding plugin

pkg/virt-operator/kubevirt_test.go, pkg/virt-operator/resource/apply/instancetype_test.go, pkg/virt-operator/resource/apply/instancetypes.go, pkg/virt-operator/resource/apply/reconcile.go, tests/operator/operator.go
Previously kv.Spec.ProductComponent was not honored in all places when handling resources from common-instancetypes (e.g. deleting them and in tests). This extracts the existing logic to get the correct AppComponent value into a helper function and calls it in every place where the value is needed.
Fixes #
**Checklist**
```release-note
None
```
=> virt-operator: Fix AppComponent value in common-instancetypes

docs/metrics.md, pkg/monitoring/virt-api/metrics/BUILD.bazel, pkg/monitoring/virt-api/metrics/metrics.go, pkg/monitoring/virt-api/metrics/vm_metrics.go, pkg/virt-api/BUILD.bazel, pkg/virt-api/api.go, pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, tools/doc-generator/doc-generator.go
Track the total number of VMs created by virt-controller
Fixes #
**Checklist**
```release-note
Add total VMs created metric
```
```jira-ticket
https://issues.redhat.com/browse/CNV-15536
```
/cc @sradco @enp0s3
=> Add total VMs created metric

automation/repeated_test.sh, tests/decorators/decorators.go, tests/framework/checks/BUILD.bazel, tests/framework/checks/expects.go, tests/hotplug/BUILD.bazel, tests/hotplug/cpu.go, tests/libnode/BUILD.bazel, tests/libnode/node.go, tests/migration/migration.go, tests/numa/numa.go, tests/performance/BUILD.bazel, tests/performance/realtime.go
Extracts `ExpectAtLeastTwoWorkerNodesWithCPUManager` as func and puts it into checks package. Replaces explicit node fetches with using the func where applicable.
Adds func name to grep call in `repeated_test.sh` to make sure kubevirtci instance has two cpumanager nodes if tests that require them are run.
Fixes #
/cc @xpivarc @jean-edouard 
**Checklist**
```release-note
NONE
```
=> create `ExpectAtLeastTwoWorkerNodesWithCPUManager` as check and deduce number of nodes from usage inside `repeated_test.sh`

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
The limitation in configuring requests/limits when using CPU/Memory hotplug has no real technical roadblock and as such can be removed to have more freedom when defining a VM.
Fixes #
**Checklist**
```release-note
Requests/Limits can now be configured when using CPU/Memory hotplug
```
=> virt-api: request/limits can now be used with CPU/Memory hotplug

hack/build-go.sh
Ensure that running tests indivdually is done in the same manner as when running all tests at once.
Currently running `make go-test` runs the tests with the `-race`. This is not the case when running tests individually with `make WHAT=pkg/some/package go-test`.
This PR adds the flag to test executed individually.
Fixes #
**Checklist**
```release-note
Not needed, as it affects only how tests are run. …
```
=> hack/build-go.sh: Use race flag when running go test for individual packages

pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, tests/containerdisk/containerdisk.go, tests/storage/hotplug.go
When hotplug a large number of volumes at once the number of created and deleted attachment pods is quite large and puts a strain on the api server. This commit puts a rate limit on how fast attachment pods can be created.
This is especially important for when kubevirt is used to host another kubernetes cluster, and that cluster deploys an application that creates a lot of volumes at once. This can potentially overwhelm the API server with attachment pods. This can manifest itself in one of two ways.
1. Too many attachment pods being created at once (and deleted). This mainly happens when there are not a lot of volumes attached to a VM.
2. When there are a lot of volumes attached to a VM (100+) creating a new attachment pod takes some time, …
=> Add rate limit for creating attachment pods

tests/reporter/kubernetes.go
Fixes #
**Checklist**
```release-note
NONE
```
=> [Test suite]: log snapshot resources from all namespaces

pkg/virt-controller/watch/clone/clone_test.go, pkg/virt-controller/watch/clone/vm-target.go
Manual backport of https://github.com/kubevirt/kubevirt/pull/10860
Fixes #
**Checklist**
```release-note
BugFix: Double cloning with filter fails
```
=> [release-1.1] Backport 'Drop certain keys from clone annotation filters'

pkg/virt-launcher/virtwrap/converter/converter_test.go, pkg/virt-launcher/virtwrap/converter/vcpu/BUILD.bazel, pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go
Currently, when CPUManagerPolicyBetaOption annotation is set to
full-pcpus-only on the VMI, the virt-launcher pod is assigned with extra
two CPU threads meant for emulator-threads [0] - but only if the amount
of CPUs originally requested was even.
This is not aligned with the EmulatorThreadPin assignment on
virt-launcher, where 2 threads are requested regardless of the amount of
vCPUs.
Fix the EmulatorThreadPin assignment to request the second emulator
thread only if the amount of vCPUs is even.
[0] https://github.com/kubevirt/kubevirt/pull/10593
Fixes # …
=> virt-launcher, vcpu: Fix EmulatorThreadPin assign strategy 

pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go, pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-config/feature-gates.go, pkg/virt-controller/services/renderresources.go, pkg/virt-controller/services/renderresources_test.go, pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go, pkg/virt-launcher/virtwrap/converter/converter_test.go, pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go, staging/src/kubevirt.io/api/core/v1/types.go
This PR aligns the current implementation with the proposal suggested in PR kubevirt/community#247.
This PR is a follow up PR to #10593, #10783 and #10839.
The `kubevirt.io/CPUManagerPolicyBetaOptions` annotation and feature-gate were introduced in PR #10593 in order to change the isolateEmulatorThread CPU assignment behavior, to support SMT enabled nodes when the CPU-Manager policy is `full-pcpu-only` [0]. 
This PR is:
- removing the logic introduced to the vmi-create validating webhook on #10593.
- changing the annotation name to `alpha.kubevirt.io/EmulatorThreadCompleteToEvenParity` and feature-gate name to `AlignCPUs`. The reason is that Kubevirt should not couple itself with a beta API if not necessary, because it could and could break if …
=> IsolateEmulatorThread: Add cluster-wide parity completion setting

pkg/virt-launcher/virtwrap/cli/libvirt.go
VMI with passt interface cause virt-launcher to crash when statistic are collected (prometheus).
The reason is that passt domain interface doesn't have a domain.target which is used as the key value of the domain statistics map.
Fixes #
**Checklist**
```release-note
None
```
=> Avoid crashing of virt-launcher when then domain interface has no target

pkg/virt-handler/container-disk/mount.go, pkg/virt-handler/container-disk/mount_test.go, tests/migration/migration.go
1. Fixes this flake https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/10884/pull-kubevirt-e2e-k8s-1.28-sig-compute/1737261845598703616 by making sure kernelboot containers are ready before trying to mount kernel artifacts into virt-launcher.
2. Removes a useless e2e test which will always fail when run with CRIO 1.28.
Fixes #
**Checklist**
```release-note
NONE
```
=> Fix e2e tests when using CRIO 1.28

tests/libvmi/vmi.go, tests/vmi_lifecycle_test.go
Update vmi lifecycle tests to use libvmi and simplify tests
Includes replacing repeated create and start of VMI with `RunVMIAndExpectLaunch` function.
Fixes #
**Checklist**
- ~[ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required~
- ~[ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if …
=> [e2e] Update vmi lifecycle tests to use libvmi and simplify tests

pkg/virt-handler/vm.go
when we execute `kubectl get vmi myvm -o yaml` and `virtctl guestosinfo myvm` we find that the vmi's status misses `Michine`
Fixes #10897
**Checklist**
```release-note
vmi status's guestOsInfo adds `Machine`
```
=> To solve vmi status-guestosinfo missing machine

pkg/virt-controller/watch/clone/clone.go
Create function returns an obj and an error.
In case of error the returned obj is the empty object of the expected type. For example, the Create function for the Restore resource, in case of error, will return the empty VirtualMachineRestore obj.
In the clone process, when creating the snapshot and the restore, in case of `already exists` error we set, respectively, the snapshot name and the restore name in the clone status.
Since we are overriding the same variable with the returned value, the snapshot name we are trying to save is an empty string.
This misbehavior can be fixed by defining a new variable for the returned obj. …
=> fix(vmclone): avoid override variables with returning obj

api/openapi-spec/swagger.json, pkg/virt-api/webhooks/fuzz/fuzz_test.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go, pkg/virt-config/deprecation/BUILD.bazel, pkg/virt-config/deprecation/feature-gates.go, pkg/virt-config/deprecation/macvtap.go, pkg/virt-config/feature-gates.go, pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/schema.go, staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go, staging/src/kubevirt.io/client-go/api/openapi_generated.go, tests/testsuite/kubevirtresource.go
Following the introduction of Kubevirt Network Binding Plugin API [1] and of Macvtap network binding plugin [2], it's now possible to remove Macvtap network binding implementation from Kubevirt core.
The transition will be conducted in two phases across the next two releases:
Phase 1 (v1.2) - Kubevirt will raise a warning when the Macvtap interface is being used - this PR.
Phase 2 (v1.3) - Macvtap interface API will stop being supported by kubevirt (using the API will lead to no-op).
[1] https://kubevirt.io/user-guide/virtual_machines/network_binding_plugins
[2] https://kubevirt.io/user-guide/virtual_machines/net_binding_plugins/macvtap
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will …
=> Macvtap deprecation

tests/storage/storage.go, tests/utils.go
This PR makes tests/utils.go slightly shorter and manageable.
**Checklist**
```release-note
NONE
```
=> tests/utils: move NewRandomVMIWithEphemeralPVC next to its users

pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go
The VMI status.GuestOSInfo struct is filled by the virt-handler, from values received in the Domain.
Currently, the `Version` field is pointing to the value of the `VersionID` field.
Point it to the correct value.
Add the missing GuestOSInfo fields to the unit test.
After this PR the following values are equal:
```bash
./cluster-up/kubectl.sh exec -t virt-launcher-vmi-fedora-b2gqj virsh guestinfo 1
...
os.id               : fedora
os.name             : Fedora Linux
os.pretty-name      : Fedora Linux 35 (Cloud Edition)
os.version          : 35 (Cloud Edition)
os.version-id       : 35
os.machine          : x86_64
os.variant          : Cloud Edition
os.variant-id       : cloud
os.kernel-release   : 5.14.10-300.fc35.x86_64
os.kernel-version   : #1 SMP …
```
=> VMI status, GuestOSInfo: Fix version field

.golangci.yml, tests/compute/credentials_test.go, tests/libvmi/cloudinit.go, tests/libvmi/factory.go, tests/migration/migration.go, tests/network/vmi_infosource.go, tests/network/vmi_istio.go, tests/network/vmi_multus.go, tests/network/vmi_networking.go, tests/performance/realtime.go, tests/realtime/realtime.go, tests/storage/storage.go, tests/utils.go, tests/virtctl/scp.go, tests/virtctl/ssh.go, tests/virtiofs/datavolume.go, tests/vmi_cloudinit_test.go, tests/vmi_vsock_test.go
A casual reader of
```
libvmi.NewFedora(libvmi.WithCloudInitNoCloudUserData(userdata, false))
```
would find it hard to understand what is "false" about this function call. Reading deeper would reveal that it means that the userdata argument is not going to be base64-encoded before being passed to kubevirt.
As is commonly the case with functions that have a boolean argument, libvmi.WithCloudInitNoCloudUserData has actually two functions. Let us define these two functions with readable names.
**Checklist**
```release-note
NONE
```
=> libvmi: avoid a boolean argument in WithCloudInitNoCloudUserData

pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go
Manual cherry-pick of PRs #10898 and #10916.
Fixes #
**Checklist**
```release-note
Fix VMI status.GuestOSInfo Machine and Version fields
```
=> [release-1.1] Fix VMI status.GuestOSInfo

pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go
Manual cherry-pick of PRs #10898 and #10916.
Fixes #
**Checklist**
```release-note
Fix VMI status.GuestOSInfo Machine and Version fields
```
=> [release-0.59] Fix VMI status.GuestOSInfo

pkg/virt-handler/vm.go, pkg/virt-handler/vm_test.go
Manual cherry-pick of PRs #10898 and #10916.
Fixes #
**Checklist**
```release-note
Fix VMI status.GuestOSInfo Machine and Version fields
```
=> [release-1.0] Fix VMI status.GuestOSInfo

pkg/virt-controller/watch/vmi.go, pkg/virt-launcher/virtwrap/device/hostdevice/sriov/BUILD.bazel, pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go, pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev_test.go, pkg/virt-launcher/virtwrap/manager_test.go
In case SRIOV interface/s exist, syncVMI tries to plug them to the VM.
If it fails, the whole syncVMI fails.
However, there are use cases we konw in advance it is fine to have a
SRIOV interface but not yet manage to plug it.
For example, when hotplugging a SRIOV interface. Until a migration is
done the interface/device is not plugged to the pod, therefore,
syncVM` will fail.
The PR allows ignoring SRIOV interface which are not yet plugged to
the pod and avoiding syncVMI failure.
Fixes #
**Checklist**
This checklist is not enforcing, but it's a reminder of …
=> SRIOV - syncVMI try to plug an SRIOV interface that is not in the pod

tests/infrastructure/k8s-client-changes.go
The following test appears to be very flaky over the past week[1]
`Infrastructure changes to the kubernetes client on the virt handler rate limiter should lead to delayed VMI running states`
It is causing over 24% impact to the sig-compute 1.28 presubmit lane in the last 2 days[2]
This test should be quarantined to reduce impact on merge queue PRs and allow time for investigation.
[1] https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2024-01-01-168h.html#row0
[2] https://search.ci.kubevirt.io/?search=Infrastructure+changes+to+the+kubernetes+client+on+the+virt+handler+rate+limiter+should+lead+to+delayed+VMI+running+state&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes= …
=> Quarantine flaky virt handler rate limiter test

tests/utils.go, tests/vmi_configuration_test.go
**Checklist**
```release-note
NONE
```
=> tests/utils: replace a long-named function with libvmi.NewFedora

pkg/virt-operator/resource/generate/components/daemonsets.go, pkg/virt-operator/resource/generate/components/deployments.go
We already use 3 libraries for the same thing, there is no need to keep a module-local version, too.
Fixes #
**Checklist**
```release-note
NONE
```
=> virt-op deployments: use k8s's pointer

tests/operator/operator.go
tests/operator/operator.go is very long and complex. This PR makes a very small simplification in it, hoping to show the way how it could become more readable.
usesSha() is a single static function. Defining it as a named lambda
needlessly adds mental burden, as the read need to keep in mind that it
may change in the future.
With this change, there is no need to declare usesSha in one place, and
define it elsewhere, and indentation level is reduced.
```release-note
NONE
```
=> tests/operator: define one less lambda

cmd/virt-tail/main.go
In the virt-log command, a context is created while its cancel function
is ignored.
This PR adds the missing call as a best practice.
**Checklist**
```release-note
None
```
=> Add a missing call to a context cancel function

pkg/virtctl/create/clone/clone.go, pkg/virtctl/create/clone/clone_test.go
virtctl support to add template label and annotation filters
Fixes #10374 
https://github.com/kubevirt/kubevirt/pull/10658
**Checklist**
```release-note
virtctl create clone --source-name sourceVM --template-label-filter '*' --template-label-filter '!some/key'
virtctl create clone --source-name sourceVM --template-annotation-filter '*' --template-annotation-filter '!some/key'
```
=> virtctl: cloneAPI add template filters

pkg/virt-operator/resource/generate/components/validations_generated.go, staging/src/kubevirt.io/api/core/v1/types.go, staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
This PR introduces a change made to the virtualMachine CRD, setting the default value to the status.printableStatus field to "Stopped".
[0]
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
Fixes BZ#1997705
**Checklist**
```release-note
Change vm.status.PrintableStatus default value to "Stopped"
```
=> staging/api: Add PrintableStatus default value

tests/BUILD.bazel
The conformance lanes are currently failing due to `go_default_test` being unable to find a required GLIBC version[1].
This is also preventing us from testing in the kubevirtci repo as we rely on the conformance tests there. 
The test_image[2] rpm bundle includes the required dependencies.
[1] https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-push-nightly-conformance/1742735308912332800/artifacts/podlogs/sonobuoy/sonobuoy-kubevirt-conformance-job-24808aede4884e3e/logs/plugin.txt
[2] https://github.com/kubevirt/kubevirt/blob/f9391ddcd4a8f6c72b80606e36cd0bcb555e1e7a/rpm/BUILD.bazel#L2003 …
=> Fix conformance make target

pkg/virt-api/rest/subresource.go, pkg/virt-api/rest/subresource_test.go, pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go, staging/src/kubevirt.io/api/core/v1/types.go, tests/vm_test.go
Shutting down a RerunOnFailure changes its runStrategy to Halted.
This PR is an attempt to preserve RerunOnFailure.
Fixes #
**Checklist**
```release-note
NONE
```
=> Keep RerunOnFailure VM runStrategy across stop/start

pkg/virt-controller/watch/application.go, staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go, staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
This PR sets a timeout on the REST client used by the migration controller.
That avoids a potential deadlock if an API call never receives a reply.
Fixes https://issues.redhat.com/browse/CNV-30386
**Checklist**
```release-note
NONE
```
=> Add rest timeout to migration controller

pkg/network/setup/netconf_test.go, pkg/network/setup/netpod/discover.go, pkg/network/setup/netpod/netpod.go
Otherwise, the status of the VMI will contain only the GA IPs.
This fix was done because of a bug discovered in passt binding plugin tests.
In passt the guest IP6 is not the same as the pod one (in case the guest has not DHCPv6 client).
The fact that the pod IPv6 wasn't cached, caused the internal GA IPv6 to be in the VMI status.
Fixes #
**Checklist**
```release-note
Report IP of interfaces using …
```
=> network: pod IPs should be stored in a cache file for binding plugin

tests/storage/datavolume.go
When CDI uses volume populators with malformed DataVolume, the VM ~eventually~ initially transitions to `Scheduling` phase.
Fixes #
This addresses the issue raised in CDI repo: https://github.com/kubevirt/containerized-data-importer/issues/3028
**Checklist**
```release-note
NONE
```
=> tests: Adapt VM phase expectation

automation/test.sh
Allow to use `KUBEVIRT_LABEL_FILTER` in order to focus certain labels.
usage: `export KUBEVIRT_LABEL_FILTER="(x)"`
Note: the global [labels](https://github.com/kubevirt/kubevirt/pull/10987/files#diff-ce25e369a9df9edc525425cc144fc8c40599fff3cc1e5058b64336d71af67162R437-R450) will be still added.
Fixes #
**Checklist**
```release-note
None
```
=> tests: Add label focus

pkg/virtctl/vmexport/vmexport.go, pkg/virtctl/vmexport/vmexport_test.go
=> vmexport: Reject volume exports when no output file is specified

automation/test.sh
We do not want to run tests which exclude native SSH functionality, so ensure that they are always skipped by the label filter.
Fixes #
See https://github.com/kubevirt/kubevirt/pull/10929#issuecomment-1869577344
**Checklist**
```release-note
None
```
=> fix: Never run tests which exclude native SSH

pkg/virt-controller/services/template.go, pkg/virt-handler/vm.go
Fix wrong overhead memory, when run in hybrid environments, such as x86 host together with arm host
Fixes #
virt-controller render launcher pod resource request, and call GetMemoryOverhead func to calc overhead memory for launcher pod,  this func use ClusterCPUArch for all vmis.  when run in hybrid environments, will get incorrect memory overhead value for those vmis whose architecture is different with virt-controller.
so change to replace ClusterCPUArch  with vmi.Spec.Architecture.
**Checklist** …
=> Fix wrong overhead memory when run in hybrid environments

tests/BUILD.bazel, tests/libnet/BUILD.bazel, tests/libnet/network_attachment_definition.go, tests/libvmi/network.go, tests/libvmi/vmi.go, tests/network/BUILD.bazel, tests/network/bindingplugin.go, tests/network/bindingplugin_passt.go, tests/network/hotplug_bridge.go, tests/network/hotplug_sriov.go, tests/network/kubectl.go, tests/network/macvtap.go, tests/network/sriov.go, tests/network/vmi_istio.go, tests/network/vmi_multus.go, tests/network/vmi_passt.go, tests/testsuite/kubevirtresource.go, tests/virtiofs/datavolume.go, tests/vmi_configuration_test.go
The PR changes the passt tests to use the passt plugin binding.
Only one test is left to cover the old passt binding API.
Fixes #
Depends on PR https://github.com/kubevirt/kubevirt/pull/10981
**Checklist**
```release-note
NONE
```
=> Change passt tests to use the passt plugin binding

cmd/virt-tail/main.go, tests/guestlog/BUILD.bazel, tests/guestlog/guestlog.go
When a shutdown of the guest OS got
triggered from the guest,
the socket file for the serial console
device could get removed even before virt-launcher-monitor detects that the VM is down and made virt-tail aware.
Due to that, virt-tail should not exit with an error when the socket file for the serial console gets removed.
Fixes [https://issues.redhat.com/browse/CNV-36451](https://issues.redhat.com/browse/CNV-36451)
None
**Checklist** …
=> [guest-log] Avoid reporting error if the socket file got closed

pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, staging/src/kubevirt.io/api/core/v1/types.go, tests/framework/matcher/BUILD.bazel, tests/framework/matcher/phase.go, tests/storage/datavolume.go, tests/vm_test.go
Today we have really detailed conditions
on DataVolumes but they are not directly reported on VMs and VMIs.
Conditions provide a standard mechanism for higher-level status reporting from a controller:
when a VM/VMI is not in the expect state the user is supposed to check its conditions to understand what's wrong. Let's aggregate DataVolumes conditions in a top level one ("DataVolumesReady") to simple expose to the user
an aggregated top-level condition on VM/VMI summarizing more detailed conditions from datavolumes.
This is simplified version consuming only
cdiv1.DataVolumeReady and ignoring DataVolumeRunning and DataVolumeBound.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close …
=> Aggregate DVs conditions on VMI (and so VM) (simplified)

docs/network-binding-plugin.md
Provide a developer guide on how to create a network binding plugin for Kubevirt.
This initial text describes a zero-code plugin and one that includes a sidecar.
Plugins with a custom CNI will be cover in a follow up.
Fixes #
**Checklist**
```release-note
NONE
```
=> docs, net: Network binding plugin developer-guide

tests/utils.go
These functions are deprecated by libvmi.
New tests should be using one of the convenient factory functions: `NewAlpine`,... or construct new 
with `New` function.
Fixes #
**Checklist**
```release-note
NONE
```
=> Deprecate functions in tests/utils.go

manifests/generated/operator-csv.yaml.in, manifests/generated/rbac-operator.authorization.k8s.yaml.in, pkg/virt-operator/resource/generate/rbac/cluster.go, pkg/virt-operator/resource/generate/rbac/cluster_test.go
Kubevirt resource is in category all.
`kubectl get all` or `virtctl permitted-devices` fails if
the user don't have the permissions to list Kubevirt resource.
Fixes #
**Checklist**
```release-note
Allow `kubevirt.io:default` clusterRole to get,list kubevirts
```
/cc @acardace
=> Allow `kubevirt:default` clusterRole to get,list kubevirts

tests/libvmi/network.go, tests/network/primary_pod_network.go, tests/network/services.go, tests/network/vmi_networking.go, tests/network/vmi_passt.go, tests/network/vmi_slirp_interface.go, tests/network/vmi_subdomain.go, tests/windows_test.go
libvmi/network exposes two public constants, `DefaultInterfaceName` and `PasstBindingName` that should be used elsewhere and are not used elsewhere, respectively. Removing them makes `libvmi` API cleaner and more precise.
**Checklist**
```release-note
NONE
```
=> libvmi: less public constants

pkg/virt-controller/watch/vm.go
The two structs contain pointers. Changing the values behind those pointers on the VMI would wrongly affect the VM.
Fixes #
**Checklist**
```release-note
NONE
```
=> VM controller: deepcopy VM Spec and ObjectMeta into new VMI

pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, staging/src/kubevirt.io/api/core/v1/types.go, tests/framework/matcher/BUILD.bazel, tests/framework/matcher/phase.go, tests/storage/datavolume.go, tests/vm_test.go
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/10905 due to the need of amending the functional test.
Fixes #11030 
A small change on the functional test  is needed due to the lack
of `NewVirtualMachine` helper function on older branches.
See #10947
/assign acardace
**Checklist**
```release-note
Aggregate DVs conditions on VMI (and so VM)
```
=> [release-1.1] Aggregate DVs conditions on VMI (and so VM) (simplified)

cmd/virt-tail/main.go, tests/guestlog/BUILD.bazel, tests/guestlog/guestlog.go
This is a manual cherry-pick of #10993 and #11034
/assign acardace
The additional commit from #11034 is simply addressing a ginkgolinter warning.
**Checklist**
```release-note
None
```
=> [release-1.1] [guest-log] Avoid reporting error if the socket file got closed

pkg/virt-handler/isolation/detector.go, pkg/virt-handler/isolation/detector_test.go, pkg/virt-handler/isolation/generated_mock_detector.go
Removes unused function of `PodIsolationDetector`.
Fixes #
**Checklist**
```release-note
NONE
```
=> Detector cleanup

Makefile, tests/BUILD.bazel, tests/libvmi/BUILD.bazel, tests/libvmi/factory.go, tests/libvmi/selector.go, tests/libvmi/storage.go, tests/libvmi/vmi.go, tests/migration/migration.go, tests/monitoring/vm_monitoring.go, tests/network/hotplug_bridge.go, tests/network/macvtap.go, tests/network/sriov.go, tests/network/vmi_multus.go, tests/performance/realtime.go, tests/pool_test.go, tests/realtime/realtime.go, tests/replicaset_test.go, tests/storage/reservation.go, tests/storage/restore.go, tests/storage/storage.go, tests/utils.go, tests/vm_test.go, tests/vmi_cloudinit_test.go, tests/vmi_configuration_test.go, tests/vmi_lifecycle_test.go
`tests/utils.go` file contains some utility functions that can be considered as duplicated.
In fact many things can be achieved with the already present `libvmi`/etc funcions.
Other times, it is possible to extract functions from `utils` to `libvmi`.
This PR aims to extract and refactor a small part of the tests/utils.go file.
In particular, in this PR we:
- extract `libvmi.WithHostDisk`.
- extend `utils.NewRandomVMI` function to accept libvmi options.
- remove `utils.NewRandomVMIWithPVCAndUserData`, `NewInt32`, `NewBool` and `CreateVmiOnNode` functions.
Fixes # …
=> refactor: tests/utils.go cleanup

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go, pkg/virt-controller/watch/vm_test.go, tests/operator/operator.go
We should prevent rejecting a VM from being created
if it can eventually be valid.
It is possible CDI is on the process of being installed
and DV resource will be avaliable soon, we should allow the
VM to be created in such case.
The VM will show in the status conditions that the dv resource
can't be found. Once CDI is installed the VM will eventually start.
Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-35866
**Checklist** …
=> Remove cdi check webhook to be aligned with k8s eventual consistency

tests/operator/operator.go, tests/utils.go
I don't understand why operator.go uses the forbidden function deprecatedBeforeAll. But at least make sure that this is the only user of this deprecated function.
```release-note
NONE
```
=> test/utils: hide deprecatedBeforeAll inside operator tests

Makefile, tests/container_disk_test.go, tests/launchsecurity/sev.go, tests/monitoring/vm_monitoring.go, tests/network/vmi_lifecycle.go, tests/network/vmi_networking.go, tests/operator/operator.go, tests/storage/datavolume.go, tests/storage/storage.go, tests/utils.go, tests/vmi_configuration_test.go
This function was giving the false impression of allowing the caller to
wait for the VMI to be running by allowing to supply a timeout.
In reality this function only created a VMI and was using a nonsensical
Eventually loop around the Create call.
Get rid of RunVMI by replacing all its usages with direct calls to the
kubevirt client.
Fixes #
**Checklist**
```release-note
None
```
=> tests/utils.go: Get rid of RunVMI

pkg/virt-operator/kubevirt_test.go, pkg/virt-operator/resource/generate/rbac/cluster.go, pkg/virt-operator/resource/generate/rbac/cluster_test.go, tests/access_test.go
This adds a ClusterRolebinding which grants every authorized user read
access to VirtualMachineCluster{Instancetype,Preference} CRs.
This allows unprivileged users to make use of
VirtualMachineCluster{Instancetypes,Preferences} by default.
Also previously the wrong constant for ClusterInstancetypes was used instead, so fix that.
Fixes https://issues.redhat.com/browse/CNV-36300
**Checklist** …
=> fix: Add ClusterRoleBinding for instancetype:view ClusterRole

pkg/virt-operator/resource/generate/rbac/cluster.go, pkg/virt-operator/resource/generate/rbac/cluster_test.go
Fixes #
Only authenticated users should be able to get KV CR
**Checklist**
```release-note
restrict default cluster role to authenticated only users
```
/cc @acardace @0xFelix 
@xpivarc FYI
=> fix: restrict default cluster role to authenticated only users

tests/operator/operator.go, tests/utils.go
PrometheusRuleEnabled and ServiceMonitorEnabled are only used in the operator tests - move these functions from utils to the operator suite.
Fixes #
**Checklist**
```release-note
None
```
=> [e2e] Move operator test functions from utils to operator suite

pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
This fixes the VMI admitter, so VMs with a preference specifying preferSpread as the CPU topology and without an instancetype can be created without the VMI admitter panicking.
Fixes #11057 
**Checklist**
```release-note
None
```
=> fix: Do not panic when specifying preferSpread without instancetype

manifests/generated/operator-csv.yaml.in, manifests/generated/rbac-operator.authorization.k8s.yaml.in, pkg/virt-operator/resource/generate/rbac/cluster.go, pkg/virt-operator/resource/generate/rbac/cluster_test.go
This is an manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/11001 and https://github.com/kubevirt/kubevirt/pull/11050
Fixes #
**Checklist**
```release-note
Allow `kubevirt.io:default` clusterRole to get,list kubevirts
```
=> [release-1.1] Allow kubevirt:default clusterRole to get,list kubevirts

pkg/virt-handler/device-manager/usb_device.go, pkg/virt-handler/device-manager/usb_device_test.go
Fix a panic when trying to list USB Devices on host without USB devices
None
**Checklist**
```release-note
Fix potential crash when trying to list USB devices on host without any
```
=> virt-handler: Fix panic when listing devices on host without USB devices

WORKSPACE, cmd/sidecars/network-passt-binding/BUILD.bazel, tests/BUILD.bazel
The builder image (centos stream 9) uses glibc verion 2.34 - the old stable go base image (debian 11) has
glibc verion 2.31.
This causes issues with running binaries that are built by the builder image
and run inside of containers based on the go base image.
```
/usr/bin/csv-generator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/csv-generator)
/usr/bin/csv-generator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/csv-generator)
```
Updating the base image to the current stable debian 12 resolves these
issues as the current stable has glibc version 2.36[1]
[1] https://tracker.debian.org/pkg/glibc
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, …
=> Update go base image to use current stable debian 12 base

pkg/controller/virtinformers.go, pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_base.go, pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/application_test.go, pkg/virt-controller/watch/clone/clone.go, pkg/virt-controller/watch/clone/clone_base.go, pkg/virt-controller/watch/clone/clone_test.go, tests/clone_test.go, tests/libstorage/storageclass.go
The clone process involves `vmsnapshot` and `vmrestore`.
Currently, these are both deleted as soon as the restore is finished. If the source vm has a pvc the `vmrestore` process creates another pvc, pointing to the volumesnapshot previously created by the `vmsnapshot`.
With `Immediate` binding mode the pvc(s) created are immediately bound.
When `WaitForFirstConsumer` binding mode is used the pvc will stay in "Pending" state until a pod is created(the virt-launcher pod).
In the latter case, when the cloned vm is started, it is stuck in "WaitingForVolumeBinding" becuse the related PVC binding is failing, due to the snapshot source has being deleted. In other words, we cannot delete the snapshot resources until all the pvc are Bound.
This patch aim to delay the snapshot and the restore …
=> fix(vmclone): delete snapshot and restore after pvc bound

tests/pool_test.go, tests/replicaset_test.go
There is an issue with slower VMI deletion[1] that is causing widespread test flakes which is severely impacting CI.
Quarantine the three tests that are flaking the most due to this issue.
Tests were identified from the latest flakefinder report
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2024-01-21-168h.html
[1] https://issues.redhat.com/browse/CNV-36682
Fixes #
**Checklist** …
=> [e2e] Quarantine tests effected by slower VMI deletion issue

pkg/controller/virtinformers.go, pkg/storage/snapshot/restore.go, pkg/storage/snapshot/restore_base.go, pkg/virt-controller/watch/application.go, pkg/virt-controller/watch/application_test.go, pkg/virt-controller/watch/clone/clone.go, pkg/virt-controller/watch/clone/clone_base.go, pkg/virt-controller/watch/clone/clone_test.go, tests/clone_test.go, tests/libstorage/storageclass.go
This is an manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/10888
Fixes #
**Checklist**
```release-note
[Bugfix] Clone VM with WaitForFirstConsumer binding mode PVC now works.
```
/cc @acardace
=> [release-1.1] fix(vmclone): delete snapshot and restore after pvc bound

pkg/virtctl/vm/BUILD.bazel, pkg/virtctl/vm/add_volume_test.go, tests/libdv/dv.go
Convert inline functions to static functions.
Defining it as a named lambda needlessly adds mental burden, as the read need to keep in mind that it
may change in the future.
Beside that:
Remove unrequired interface usage, by using the casted variable.
Use libdv, and add WithName decorator for libdv.
Fixes #
**Checklist**
```release-note
None
```
=> unit test: Convert unneeded lambda functions

tests/network/vmi_networking.go, tests/sysprep_test.go, tests/utils.go, tests/windows_test.go
tests/utils is too long.
```release-note
NONE
```
=> Use libvmi.WithMasqueradeNetworking instead of an ad hoc tests/utils function

pkg/virt-controller/watch/clone/clone.go, pkg/virt-controller/watch/clone/clone_test.go
vm clone can filter out labels and annotations with filtering. These filters result in a set of patches that will be applied to the target vm.
If the vm clone source is a vm, it could happen that between the snapshot creation and the subsequent restore, some new annotations or labels are added.
If the latter should be filtered out, the vmrestore patches will cover them as well.
But the restore process tries to apply the patches to the vmsnapshotcontent, not the current vm, resulting in a failure with `Unable to remove nonexistent key...`.
To avoid this situation, intead of the current vm, the vmrestore pathes should be always generated from the vmsnapshotcontent vm. …
=> fix(vmclone): generate vm patches from vmsnapshotcontent vm

pkg/virt-controller/watch/vmi.go, pkg/virt-controller/watch/vmi_test.go, tests/BUILD.bazel, tests/libpod/BUILD.bazel, tests/libpod/blackhole.go, tests/virt_control_plane_test.go, tests/vm_test.go
It aims to reduce the VM recovery time when an operator such as [NodeHealthCheck](https://github.com/medik8s/node-healthcheck-operator/) is used to remediate unhealthy nodes, i.e. nodes no longer responsive.
In such scenario, the launcher pod is deleted, and the VMi needs to be rescheduled if the spec `runStrategy` is configured as `Always` or `RerunOnFailure`. The VM's Phase is `Running` but VM has the following condition:
```
Status:
Conditions:
Last Probe Time:       2023-12-18T16:31:31Z
Last Transition Time:  2023-12-18T16:31:31Z
Message:               virt-launcher pod has not yet been scheduled
Reason:                PodNotExists
```
Eventually, the VMi is rescheduled and the virt-launcher pod recreated.  However, it takes over than 100 …
=> fix: Reduce VM recovery times

pkg/virt-operator/kubevirt_test.go, pkg/virt-operator/resource/generate/rbac/cluster.go, pkg/virt-operator/resource/generate/rbac/cluster_test.go, tests/access_test.go
This is a manual backport of #11025.
This adds a ClusterRolebinding which grants every authorized user read
access to VirtualMachineCluster{Instancetype,Preference} CRs.
This allows unprivileged users to make use of
VirtualMachineCluster{Instancetypes,Preferences} by default.
Conflicts:
pkg/virt-operator/resource/generate/rbac/cluster.go
Note:
The conflict is due to a code refactoring in cluster.go that was not
backported.
Fixes #
Merge after #11070 
**Checklist**
This checklist is not enforcing, but it's a reminder of items that could be relevant to every …
=> [release-1.0] fix: Add ClusterRoleBinding for instancetype:view ClusterRole

tests/libpod/BUILD.bazel, tests/libpod/query.go, tests/libpod/sort.go, tests/migration/migration.go, tests/utils.go, tests/vm_test.go
CPU hotplug involves live-migration and since `GetRunningPodByLabel` was used in the test, sometimes
it returned the wrong running pod, thus resulted in a flake. The PR aims to fix `GetRunningPodByLabel` and 
do some code cleanup on the way.
Fixes #
https://github.com/kubevirt/kubevirt/issues/10690
**Checklist**
```release-note
NONE
```
=> [e2e]: fix CPU hotplug flakes

tests/guestlog/guestlog.go
Address a ginkgolinter warning
introduced with https://github.com/kubevirt/kubevirt/pull/10993 since it's currently preventing a backport
of it to a stabilization branch
where ginkgolinter is enforcing.
Fixes https://github.com/kubevirt/kubevirt/pull/11026
No real code changes, it's simply addressing a ginkolinter warning. 
**Checklist**
```release-note
NONE
```
=> [chore] Address a ginkgolinter warning

tests/operator/operator.go
Use expect rather than panics for error handling in operator tests.
Follow up to a previous PR review comment[1]
[1] https://github.com/kubevirt/kubevirt/pull/11053#discussion_r1463266953
Fixes #
**Checklist**
```release-note
NONE
```
=> [e2e] Use expect rather than panics for error handling in operator tests

OWNERS_ALIASES, pkg/hotplug-disk/OWNERS, pkg/storage/OWNERS, tests/storage/OWNERS
This PR is clarifying the ownership of two pkgs.
Fixes #
A follow up question could be: Should disk hotplug belong into storage?
And: What about the other storage-y things like hostpath, containerdisk, etc
**Checklist**
```release-note
NONE
```
=> sig-storage: Set some ownership

OWNERS, OWNERS_ALIASES, bazel/OWNERS
Setting some ownership to make it clear who can help to merge stuff
Setting owners for build - mostly bazel - related things.
We want this in order to know who can help, and who should care.
The list is loosely based on the git history on some bazel files.
Fixes #
What other files/directories should be owned by sig-buildsystem
**Checklist**
```release-note
NONE
```
=> sig-buildsystem: Set some ownership

BUILD.bazel, WORKSPACE
Update bazeldnf to v0.5.9-rc2.
Needed for s390x support, see https://github.com/kubevirt/kubevirt/pull/10490.
Once it's been verified that the update doesn't break anything, I will make sure that the final v0.5.9 release is tagged and pick it up before removing the draft status from this PR.
```release-note
NONE
```
=> bazeldnf: Update to v0.5.9

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
Volumes can be used for both filesystem and disk devices. When validating the VMI's volume count, both need to be considered.
The miscount causes problems when when hotplugging disks to a virtual machine that also uses virtiofs.
Fixes #9653
Enabling the `ExperimentalVirtiofsSupport` feature gate during tests was necessary to crate VMIs with filesystems. I am unsure if that is the desired way to do this.
**Checklist** …
=> vmi update admission webhook: fix volume miscount when using filesystems

tests/hotplug/cpu.go, tests/testsuite/kubevirtresource.go
Saw flakes on the migration lane because only 1 node has cpumanager ready.
This PR should fix that.
Fixes #
**Checklist**
```release-note
NONE
```
=> e2e: wait for all workers to enable cpumanager before starting

pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter.go, pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter_test.go
Currently, there are multiple occurrences of the following string literals:
- "VirtualMachine"
- "VirtualMachineSnapshot"
Replace them with constants.
Fixes #
**Checklist**
```release-note
None
```
=> vmclone admitter: Replace string literals with consts

tests/vm_test.go
The linter enforces the usage of `Should()` statements when a `Eventually` check is used.
It adds the missing `Eventually()` statements `Should()` checks.
Also, `DeferCleanup` has been dropped in favor of `defer`. The [`resetToDefaultConfig()` ](https://github.com/kubevirt/kubevirt/blob/cb1b6e53540189d6664c4a8c126ab6e0a84ff8c4/tests/utils.go#L1842) is called before the test `DeferCleanup`, creating the following error:
```
[FAILED] in [AfterEach] - tests/utils.go:1601 @ 01/29/24 15:32:28.576
<< Timeline
[FAILED] Timed out after 10.001s.
<*errors.errorString | 0xc006203230>: 
resource & config versions (5548 and 4736 respectively) are not as expected. component: "virt-handler", pod: "virt-handler-zdv7f" 
{
s: "resource & config …
```
=> fix: `Eventually()` missing `Should()` statement and sync error

tests/compute/credentials_test.go, tests/libvmi/cloudinit.go, tests/utils.go, tests/vmi_cloudinit_test.go
Make tests/utils.go slightly shorter by moving two functions away from it.
**Checklist**
```release-note
NONE
```
=> test/utils: drop two public functions

pkg/virtctl/vm/add_volume_test.go
Discard function boolean arg by splitting to two functions.
Discard unrequired args which are the same all over the table entries.
Split DV and PVC to two DescribeTable blocks.
It ease maintenance, when each blocks is focused on one time,
and removes args and condition.
The common code that it saved is not big and added mental burden.
Inline single usage functions, and get rid of the offset.
Replaced strings with consts.
Fixes #
**Checklist**
Approvers are …
=> unit tests, volumes: Refactor in order to reduce unrequired parameters and ease readability

tests/network/bindingplugin_passt.go
code-lint fails
After this PR:
code-lint succeeds?
Fixes #
-
```release-note
NONE
```
=> tests: network: make linter happy

tests/exec/execute.go, tests/libnet/interface.go, tests/libnet/network_attachment_definition.go, tests/libvmi/network.go, tests/network/BUILD.bazel, tests/network/bindingplugin_macvtap.go, tests/network/hotplug_bridge.go, tests/network/macvtap.go, tests/network/vmi_multus.go, tests/testsuite/BUILD.bazel, tests/testsuite/kubevirtresource.go
This PR changes the macvtap tests to use the network binding plugin API.
Only one test is left to cover the old macvtap interface API.
Fixes #
**Checklist**
```release-note
NONE
```
=> Change macvtap tests to use the network plugin binding API 

pkg/virtctl/create/params/params.go, pkg/virtctl/create/vm/vm.go, pkg/virtctl/create/vm/vm_test.go
Allow to omit size when creating a VM and using --volume-import to clone a PVC or a VolumeSnapshot.
Specifying size when creating a VM and using --volume-import to clone a PVC or a VolumeSnapshot was always required.
After this PR:
Specifying size when creating a VM and using --volume-import to clone a PVC or a VolumeSnapshot is optional now.
Fixes #
-
```release-note
virtctl: Specifying size when creating a VM and using --volume-import to clone a PVC or a VolumeSnapshot is optional now
```
=> virtctl: Allow size to be optional when creating VMs

pkg/virt-controller/watch/application.go
Currently, the evacuation controller's recorder has the `disruptionbudget-controller` componentName.
This makes events emitted by evacuation controller, indistinguishable from events emitted by disruption budget controller.
After this PR:
Rename the recorder's componentName to `evacuation-controller`.
Fixes #
-
```release-note
NONE
```
=> Evacuation ctrl, recorder: Rename componentName

tests/vmi_configuration_test.go
Otherwise fields like the `Namespace` will be empty and could cause following `Get` calls to fail.
Example failure: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/10672/pull-kubevirt-check-tests-for-flakes/1754720757860012032
After this PR:
Fixes #
-
```release-note
NONE
```
=> tests: always retrieve vmi after creation

tests/libstorage/storageclass.go, tests/storage/datavolume.go
We have a mechanism to say which storage class we want to test snapshots with, let's use that, and completely skip those tests if nobody tells us that we can snapshot.
This is useful so we don't run snapshot tests on lanes that are dedicated to storage that doesn't support them.
Fixes #
```release-note
NONE
```
=> [restore tests]: Use supplied snapshot storage class, don't attempt discover

pkg/util/pdbs/pdbs.go, pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go, pkg/virt-controller/watch/migration.go
`pdb.Spec.MinAvailable` is of type *intstr.IntOrString. We check it as it cannot be nil.
After this PR:
Avoid possible nil pointer dereference error by checking it.
Fixes #
```release-note
NONE
```
=> fix(pdb): fix possible nil pointer dereference

pkg/virt-controller/watch/drain/evacuation/evacuation.go
Currently, the evacuation controller has four informers:
1. vmiInformer
2. vmiPodInformer
3. migrationInformer
4. nodeInformer
but it only waits for two of them.
After this PR:
Add a wait for all informers' cache to be synced.
Fixes #
-
```release-note
NONE
```
=> Evacuation ctrl: Wait for all informers' cache sync

tests/migration/eviction_strategy.go
Currently, migrations during node drain tests are not available in those
tests where all the nodes are both control-plane and worker; this is because
on the BeforeEach function, all the control-plane nodes are set as unschedulable,
and hence all the nodes are set as unschedulable, resulting in the impossibility
to start a vmi. This trick was done to prevent the vmi to be scheduled initially
on the control-plane node.
We want to avoid this situation in which the vmi will be scheduled on the control-plane
node in topology where there is only one control-plane, because the subsequent drain
will be disruptive.
To prevent the above situation, we will use the PreferredDuringSchedulingIgnoredDuringExecution
term to avoid the vmi to be scheduled in the only …
=> e2e: enable drain migration tests for several cluster topology

pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go, pkg/virt-controller/watch/clone/BUILD.bazel, pkg/virt-controller/watch/clone/clone_test.go
Using fake client has a benefit to actually
assert on what exactly we can find after a cycle.
In this way we can check whether a restore or a
snapshot are gone or not.
This PR contains a refactoring of the whole vmclone test file.
Fixes #
In order to increase readability I split this work in logical steps.
**Checklist**
```release-note
None
```
=> Use fakeclient instead of reactor in vmclone

tests/network/sriov.go
In a SR-IOV setup, the node and pod stack is not involved at all. Only the guest stack is IP stack aware and that is not something Kubevirt is interested to cover in the e2e tests.
An attempt to bump the guest OS has exposed this redundant dependency. The new guest OS (Fedora) had issues to handle the IPv6 cloudinit configuration when IPv4 was not set.
In order to continue checking the connectivity, IPv4 guest setups tests have been left.
Fixes #
-
```release-note
NONE
```
=> tests, sriov: Drop IPv6 connectivity test

tests/container_disk_test.go, tests/hotplug/BUILD.bazel, tests/hotplug/cpu.go, tests/hotplug/memory.go, tests/libpod/BUILD.bazel, tests/libpod/container.go, tests/migration/migration.go, tests/utils.go, tests/vmi_configuration_test.go, tests/vmi_headless_test.go
Extract the helpers out of utils and rename them to fit nicely in their new home package.
Fixes #
```release-note
NONE
```
=> tests, utils: Extract container lookup helpers to libpod

pkg/virt-handler/rest/lifecycle.go, tests/storage/snapshot.go
Fsfreeze can sometimes fail for causes unrelated to kubevirt, such as certain selinux policies or unsupported filesystems. This can lead to situations where snapshot fails without providing any pertinent information in any of the involved objects. This PR aims to add an event to avoid issues such as https://issues.redhat.com/browse/CNV-32664.
Fixes # https://issues.redhat.com/browse/CNV-32664
Still working on adding a test but I'm really struggling to replicate a fsfreeze behavior, specially the selinux one described in the jira. …
=> Improve error reporting when fsfreeze fails

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
The UUID generated needs to depend on the uniqueness of the VM name and its namespace (same name may appear in two different namespaces).
fix: https://github.com/kubevirt/kubevirt/issues/11166
Fixes #
```release-note
NONE
```
=> virt-controller, vm: Set domain firmware UUID based on namespace & name

tests/migration/migration.go, tests/storage/storage.go, tests/vm_state_test.go
Signed-off-by: Zhe Peng <zpeng@redhat.com>
After this PR:
Fixes #
-
```release-note
NONE
```
=> Add test id for USB and TPM/EFI persistent

Makefile, tests/libpod/blackhole.go, tests/libpod/query.go, tests/libpod/render.go, tests/virt_control_plane_test.go, tests/vm_test.go
Cover `tests/libpod` with the linter checks.
The following errors have been resolved to allow this:
```
tests/libpod/blackhole.go:37:2: rangeValCopy: each iteration copies 1048 bytes (consider pointers or indexing) (gocritic)
for _, pod := range pods.Items {
^
tests/libpod/blackhole.go:38:46: G601: Implicit memory aliasing in for loop. (gosec)
_, err = exec.ExecuteCommandOnPod(virtCli, &pod, containerName, []string{"ip", "route", addOrDel, "blackhole", serviceIp})
^
tests/libpod/blackhole.go:47: line is 153 characters (lll)
kubernetesService, err := virtClient.CoreV1().Services(kubernetesServiceNamespace).Get(context.Background(), kubernetesServiceName, metav1.GetOptions{})
tests/libpod/render.go:110: line is 161 characters (lll)
func RenderHostPathPod(podName string, dir string, …
```
=> lint: Cover tests/libpod using the linter

tests/hotplug/BUILD.bazel, tests/hotplug/rolloutstrategy.go, tests/storage/storage.go, tests/tests_suite_test.go, tests/utils.go
It does not make sense for SetupAlpineHostPath to be in the global testsuite cleanup, therefore remove it from there and inline it in the only other place where is is used.
Fixes #
**Checklist**
```release-note
None
```
=> chore: Inline SetupAlpineHostPath

pkg/virt-handler/cgroup/util.go, tests/storage/hotplug.go
To achieve hotplug functionality on cgroupsv2, we reconstruct the container device allowlist to add the new disk.
Today, we "forget" to re-add `/dev/urandom` to this list depending on whether it's needed (rng device in vmi).
After this PR:
We now correctly add `/dev/urandom` to the allow list when hotplugging a block volume
Fixes #
https://issues.redhat.com/browse/CNV-38193
```release-note
Fix migration breaking in case the VM has an rng device after hotplugging a block volume on cgroupsv2
```
=> Fix migration when VM has rng devices and hotplugged block volume

pkg/virt-handler/dmetrics-manager/dmetrics-manager.go
Actually check if the VMI still exists in the DownwardMetricsManager `stopServer` map before calling the related Context canceling function as `processVmCleanup()` could be called multiple times by virt-handler's reconciliation loop when cleaning up the VMI.
This prevents virt-handler from panicking because of a segfault.
```release-note
NONE
```
=> downwardmetrics: add safety checks in StopServer()

pkg/virt-handler/cgroup/util.go, tests/storage/hotplug.go
This is a backport of https://github.com/kubevirt/kubevirt/pull/11205
Fixes #
```release-note
Fix migration breaking in case the VM has an rng device after hotplugging a block volume on cgroupsv2
```
=> [release-1.0] Fix migration when VM has rng devices and hotplugged block volume

pkg/virt-handler/cgroup/util.go, tests/storage/hotplug.go
This is a backport of https://github.com/kubevirt/kubevirt/pull/11205
Fixes #
```release-note
Fix migration breaking in case the VM has an rng device after hotplugging a block volume on cgroupsv2
```
=> [release-1.1] Fix migration when VM has rng devices and hotplugged block volume

pkg/virt-controller/services/template.go, pkg/virt-controller/services/template_test.go
The network Passt binding does not require any special SELinux tweaks to operate now.
Fixes #
```release-note
NONE
```
=> virt-controller, template: Remove Passt binding SELinux adjustment

hack/prom-rule-ci/prom-rules-tests.yaml, pkg/monitoring/rules/alerts/vms.go
`KubeVirtVMIExcessiveMigrations` and `VMCannotBeEvicted` alerts descriptions don't include the VM's namespace.
After this PR:
All specific VMs alerts descriptions mention the VM's namespace.
Fixes: [CNV-35084](https://issues.redhat.com/browse/CNV-35084)
When a specific VM alert is firing, it is important to know the namespace the VM belongs to, for easier mitigation.  
```release-note
None
```
=> Add namespace to VM specific alerts descriptions

tests/network/bindingplugin.go
Waiting of a VMI object readiness before it actually exists causes
flakes.
There is no apparent reason to use a VM in this case.
Directly using a VMI simplifies the test and avoids the detected flake.
Fixes #
Detected on CI run: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11217/pull-kubevirt-e2e-k8s-1.29-ipv6-sig-network/1757332821854130176
```release-note
NONE
```
=> tests, network, bindingplugin: Create the VMI object directly

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
The original change may break users when starting an old VM. When starting with the new generated UUID, most likely the machine UUID will change which in turn may place the guest in an unexpected state.
There is a need to distinguish old and new VMs in order to provide a backward compatible fix.
Fixes #
A new fix should be posted that considers old stopped VMs.
For now, it would be safer to revert the fix changes and re-open the issue.
```release-note
NONE
```
=> revert: Set domain firmware UUID based on namespace & name

tests/storage/hotplug.go, tests/storage/memorydump.go, tests/storage/storage.go, tests/utils.go
Move storage helpers from utils to the storage tests using them.
Fixes #
```release-note
NONE
```
=> tests: Move storage helpers from utils

cmd/sidecars/README.md
More than once, users thought that /usr/bin/onDefineDomain could be a folder where they install their hook binary. Fix it.
Users considered that their hook binary could be installed in a folder named `/usr/bin/onDefineDomain`
After this PR:
It should be clear that the binary full path is `/usr/bin/onDefineDomain`
Fixes #
none
none
none
```release-note
NONE
```
=> sidecar-shim: README: fix misinterpretation

pkg/virt-controller/watch/vm.go, pkg/virt-controller/watch/vm_test.go
A cache is corrupted.
After this PR:
A cache is not corrupted ;)
Fixes #
This is a suboptimal patch to be able to backport this for the latest releases.
```release-note
Bug fix: VM controller doesn't corrupt its cache anymore
```
=> Vm controller copy fix

.golangci.yml, Makefile, tests/libnode/node.go
Cover tests/libnode with the linter checks.
The following errors have been resolved to allow this:
```
tests/libnode/node.go:144:11: string `/metadata/` has 2 occurrences, make it a constant (goconst)
Path:  "/metadata/" + string(mapType) + "s",
^
tests/libnode/node.go:68:3: builtinShadow: shadowing of predeclared identifier: new (gocritic)
new := node.DeepCopy()
^
tests/libnode/node.go:253:2: builtinShadow: shadowing of predeclared identifier: new (gocritic)
new := node.DeepCopy()
^
tests/libnode/node.go:275:2: importShadow: shadow of imported from 'kubevirt.io/kubevirt/pkg/util/nodes' package 'nodes' (gocritic)
nodes := make([]*k8sv1.Node, 0)
^
tests/libnode/node.go:291:2: importShadow: shadow of imported from 'kubevirt.io/kubevirt/pkg/util/nodes' package 'nodes' (gocritic)
nodes, err …
```
=> lint: Cover tests/libnode using the linter

tests/guestlog/guestlog.go
The majority of the tests use a cirros VMI - update the remaining to use cirros.
This allows us to stop defining an alpine VMI before each test which is not even used by most of these tests.
Fixes #
/cc @tiraboschi @dhiller @xpivarc 
```release-note
NONE
```
=> e2e,guestlog: update tests to just use the cirros VMI

tests/vm_test.go
2 failures are wrongly highlighted by prow in every successful sig-compute run. The matching string appears to be `Failure [`.
See https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11114/pull-kubevirt-e2e-k8s-1.29-sig-compute/1754487307475357696
or any sig-compute job really.
After this PR:
The words are moved around so `Failure [` doesn't appear anymore.
Fixes #
-
```release-note
NONE
```
=> tests: avoid triggering the failure parser
